### ISSUE TITLE
Header markdown highlighting doesn't stop if next line begins with MathJax

### ISSUE THREAD

**Issue by nicktimko** [jupyter/notebook#10]
Picture worth a thousand words:

![screen shot 2015-04-13 at 11 29 10 am](https://cloud.githubusercontent.com/assets/5297556/7120146/928e2e7c-e1d0-11e4-8cd9-7042773cd047.png)

But basically, a line that begins with MathJax causes the header highlighting to bleed.

Produced in OS X 10.10.1 Chrome 41.0.2272.118 and Safari 8.0.2 (10600.2.5)

**Comment by minrk** [comment]
While this is an issue in our ipythongfm codemirror mode, I suspect it's a bug in CodeMirror's implementation of multiplexing modes, where the multiplexing ends up stripping the previous mode's handling of newlines. Let's report it upstream.

**Comment by Carreau** [comment]
reported on codemirror/CodeMirror#3535 to get more info, bumping as 5.0.

**Comment by Carreau** [comment]
Fixed upstream. Thanks !

**Comment by minrk** [comment]
Let's leave this open and mark it closed when we ship a CodeMirror with the fix. Thanks for taking it upstream, @Carreau!
