### ISSUE TITLE
Should symlink option in nbextensions API fall back to copy?

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#100]
`install_nbextension()` takes a `symlink=` boolean parameter, which instructs it to symlink the extension rather than copying it. In most cases this will fail on Windows, and the docstring says as much.

If symlink fails, should it automatically fall back on copying (the default without `symlink=True`)?

In favour: this is what most extensions probably want, and if we don't have a fallback, they have to have that fallback themselves.

Against: some extensions may rely on it actually making a symlink (e.g. symlink a directory into nbextensions, then change the contents of that directory). Automatic fallbacks make it harder to know what's really happening.

From ipython/ipython#8440

**Comment by Carreau** [comment]
Can we have a third option like `ifNotWindows` (string of object) that would do the sasne things and let extensions override that if they really wish to ?

**Comment by takluyver** [comment]
We could. Though I think if we go that way, it should probably be `ifPossible` rather than `ifNotWindows` - in some cases it may be possible to make a symlink on Windows.

**Comment by damianavila** [comment]
>We could. Though I think if we go that way, it should probably be `ifPossible`

Yep... I think is a better name...

**Comment by minrk** [comment]
I'm not sure. I might be inclined to just force `symlink=False` on Windows (maybe warn). That seems relatively common practice for other projects. Windows may technically have symlinks now, but they don't seem reliably functional.

**Comment by takluyver** [comment]
I believe that if you succeed in making them they work, but making them in the first place requires a permission bit that non-admin users don't have by default. But it's probably rare enough that we could just assume there's no symlinking on Windows.

**Comment by minrk** [comment]
We now force symlink=False when os.symlink is undefined (Windows Python 2). This may be sufficient, though we should think about what we do in the symlinks-available-but-not-allowed case.

**Comment by damianavila** [comment]
>This may be sufficient, though we should think about what we do in the symlinks-available-but-not-allowed case.

I guess some kind of warn and force to False...

**Comment by minrk** [comment]
I'm not sure we can reliably detect the case until we get to the end and it fails, though.

**Comment by ellisonbg** [comment]
I know this one has been dormant for a while, but I don't think we should attempt to copy if a symlink fails and a user has requested `symlink=True`. Too much surprise.

**Comment by JamiesHQ** [comment]
Hi All: what is the next step on this issue? Should it be added to the backlog as a development item, be labeled as a reference, or closed? Thanks!

**Comment by ellisonbg** [comment]
Not sure, thoughts @minrk @takluyver ?

**Comment by takluyver** [comment]
Let's close it. It doesn't seem to have been a big issue in practice.
