### ISSUE TITLE
Long input lines of code overwrite the input cell bounds on Chrome

### ISSUE THREAD

**Issue by akhmerov** [jupyter/notebook#1003]
Notebook v4.1, no custom css.

Firefox 43 / Ubuntu (expected behavior):

![image](https://cloud.githubusercontent.com/assets/2069677/12598858/3843d930-c48d-11e5-8202-5d30cf62425c.png)

Chrome 48 / Ubuntu (cell too wide):

![image](https://cloud.githubusercontent.com/assets/2069677/12598913/8debe206-c48d-11e5-9dc0-f0f9aba617ea.png)

**Comment by minrk** [comment]
This is a bug in Chrome 48 (dev channel). I just tested in Chrome 47 (no bug), updated to 48 and saw it. Hopefully it will be fixed by the time it reaches stable.

**Comment by RafalSkolasinski** [comment]
I believe that Chrome 48 is already stable.

**Comment by minrk** [comment]
Ah, so it is. Well, crap. I'll see if I can make a reproducible test case and reopen the upstream Chrome bug.

**Comment by minrk** [comment]
[Reported upstream](https://code.google.com/p/chromium/issues/detail?id=582141). It seems we can workaround it if we ensure that `div.input_area` has a width specified explicitly, defeating the entire purpose of flexbox.

**Comment by mogthesprog** [comment]
Cheers for getting to this. Also seen it too. +1

**Comment by willingc** [comment]
Updated the title of the issue so it is easier to find via search parameters.

**Comment by zdeland1** [comment]
Yeah this is bugging the heck out of me too (Chrome 48, Windows 7).At least in my case, I'm able to switch the input type to Markdown (ctrl+M) (where it automatically text-wraps to multiple lines), do the editing I need, switch back to code (ctrl+Y), and execute.

**Comment by parente** [comment]
[Comment #4 upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=582141#c4)  says this is not a regression and won't be fixed.

> This is not a regression, the parent needs min-width: 0. We fixed our implementation to match the spec (we also match Firefox and Edge now). See https://drafts.csswg.org/css-flexbox/#min-size-auto

**Comment by parente** [comment]
Adding `min-width:0` to `.inner_cell` in the notebook appear to correct Chrome.

**Comment by parente** [comment]
And I'm a day late to the party: https://github.com/jupyter/notebook/commit/7934f299178c60e8450af2caff93f85f19987f25

Thanks @minrk!
