### ISSUE TITLE
ui_components.rst has broken links

### ISSUE THREAD

**Issue by IsakFalk** [jupyter/notebook#1004]
The file that describes the UI components in https://github.com/jupyter/notebook/blob/master/docs/source/ui_components.rst 
doesn't show the correct png files as the links is broken.

**Comment by willingc** [comment]
Hello @IsakFalk,

The rendered version of the file can be seen on ReadTheDocs here: http://jupyter-notebook.readthedocs.org/en/latest/ui_components.html

I will look into the links within GitHub. Thanks.

**Comment by eckerr** [comment]
this issue has been fixed and should be closed - I'm a Jupyter Day Chicago attendee

cc @captainsafia

**Comment by takluyver** [comment]
Thanks @eckerr

**Comment by willingc** [comment]
Thanks @eckrr :cake:
