### ISSUE TITLE
Add support for multiple cursor in the code editor

### ISSUE THREAD

**Issue by radaniba** [jupyter/notebook#1006]
Today I missed that feature, I usually use editors like SublimeText, Atom or PyCharm, they all have that keybinding to make a multiple cursor selection

It would be great to have this somehow implemented in the notebook

Any ideas ?

**Comment by takluyver** [comment]
Multiple cursors are possible - on my system I can Ctrl + click to create them. I forget if there's a keyboard shortcut, but somebody else should be able to tell you.

**Comment by willingc** [comment]
@radaniba This [mailing list thread](http://comments.gmane.org/gmane.comp.python.ipython.devel/14016) gives a bit of detail on the subject.

Here are some documents that you may find helpful on configuring the notebook frontend and keyboard shortcuts:
[Configuring the notebook frontend](http://jupyter-notebook.readthedocs.org/en/latest/frontend_config.html)

[Keyboard shortcut configuration](http://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Custom%20Keyboard%20Shortcuts.ipynb)

**Comment by slundberg** [comment]
Codemirror (used by Jupyter) already supports multiple cursors, but the key bindings used in Jupyter don't match the ones you would expect as a sublime or Atom user. To make cmd-D (or ctrl-D) work see: #278

**Comment by radaniba** [comment]
@takluyver @willingc @slundberg Thank you, yes indeed ! that worked for me as well. Thank you guys
