### ISSUE TITLE
Shortcut help for 'split cell' shortcut - display broken

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#1008]
![screenshot from 2016-01-27 11 05 50](https://cloud.githubusercontent.com/assets/327925/12611708/19856f96-c4e6-11e5-98f7-e0d800cf59a0.png)

I would never call that key 'subtract', either. I'd normally say 'dash', and I'd consider 'hyphen' or 'minus' valid alternatives ('minus' is the symbol, 'subtract' is the operation it indicates). The Unicode character it inserts is called HYPHEN-MINUS.

Also, I don't think the shortcut should be duplicated in help. We should pick one way to represent it.

**Comment by minrk** [comment]
dash would be technically incorrect (minus/hyphen: -, dashes: –, —). I'd be fine with `minus`. Subtract does seem weird. I think a lot of people don't know the word 'hyphen'.

**Comment by bjlange** [comment]
FYI, looking into this
