### ISSUE TITLE
add a execute button near "In [ ]" so it can be like the refresh button in dashboard page

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#1009]

**Comment by cailiang9** [comment]
it can be a simple and fast dashboard

**Comment by cailiang9** [comment]
The patch code is here:
`sed -i -e 's/In.*&nbsp.*/In<\/bdi>\&nbsp;['"'"' + ns + '"'"']:<br\/><a href="#" onclick="setTimeout(function(){ Jupyter.notebook.get_selected_cell().execute();},100); return false;">Run\&gt<\/a>'"'"';/' notebook/js/main.min.js`

And it looks like:
![image](https://cloud.githubusercontent.com/assets/3636844/26139322/5397dfbe-3b02-11e7-8ff3-c25cef19cf98.png)

**Comment by takluyver** [comment]
How does that look on a single line cell? I could imagine something like that being really useful for people accessing the notebook from phones or tablets.

**Comment by cailiang9** [comment]
It is not that bad. I think there are many ways to improve.
![image](https://cloud.githubusercontent.com/assets/3636844/26157795/b3d02e46-3b4c-11e7-8753-de93215f5090.png)

**Comment by jasongrout** [comment]
What about a single-line cell without a horizontal scroll bar? Just curious.

**Comment by cailiang9** [comment]
you can look at the bottom

**Comment by cailiang9** [comment]
We can also move Run to left of In [ ]

**Comment by takluyver** [comment]
It doesn't look so tidy on the single line cell without a scrollbar (which ought to be the normal case for single lines). I'm not particularly keen on putting it to the left either - we don't want to reserve another UI column on smaller screens.

**Comment by blink1073** [comment]
Another option is to make the prompt itself clickable with a hover indication and tooltip ("Run Cell").

**Comment by damianavila** [comment]
> Another option is to make the prompt itself clickable with a hover indication and tooltip ("Run Cell").

I would definitely prefer something like that...

**Comment by arovit** [comment]
Hey guys, do you need any help with this feature ? This feature looks simple and interesting, I would love to work on this.

**Comment by arovit** [comment]
![screen shot 2018-03-16 at 5 27 28 pm](https://user-images.githubusercontent.com/4410397/37549644-701bf0e0-293f-11e8-9c6f-f7c1d5ded31a.png)

How about like this ? It doesn't use any extra space and retains the look and feel of previous versions.

**Comment by takluyver** [comment]
Interesting idea! I have some concern that people might be used to clicking on the prompt to select a cell without going into edit mode, and if that suddenly executes the  cells, it could be an unpleasant surprise - especially for cells which take a long time to run.

I'll try to think about how we might test it out.

**Comment by cailiang9** [comment]
seems it is better to add a run icon on the left of In []:

**Comment by arovit** [comment]
@takluyver you are right, I thought about this scenario. That's why only the space between "[ ]" is made clickable instead of entire prompt e.g "ln [2]". Another thought: How about making it "double click" instead of single click to avoid accidental executions ?

**Comment by lucasoshiro** [comment]
@arovit I liked you idea, I think that it makes the cell cleaner than adding a button. However, when I was testing you code it was running the previous selected cell, instead of the cell whose prompt I had clicked (the cell was selected after the click event). In order to prevent it, I rewrote it based on the corresponding cell, instead of the selected cell. I will create a pull request with it.

**Comment by cailiang9** [comment]
Run button disappeared on release 5.7.0?

**Comment by jasongrout** [comment]
> Run button disappeared on release 5.7.0?

Right. See https://github.com/jupyter/notebook/issues/3772.
