### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ahwillia** [jupyter/notebook#101]
I'm using Ubuntu trusty. I executed all the commands and pip seemed to install everything in requirements.txt fine. However I get the following error when executing `jupyter notebook`

<pre>
  File "/home/alex/.virtualenvs/jupyter_notebook/bin/jupyter-notebook", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/alex/jupyter_notebook/scripts/jupyter-notebook", line 3, in <module>
    from jupyter_notebook.notebookapp import main
  File "/home/alex/jupyter_notebook/jupyter_notebook/notebookapp.py", line 49, in <module>
    from tornado import web
  File "/home/alex/.virtualenvs/jupyter_notebook/lib/python2.7/site-packages/tornado/web.py", line 63, in <module>
    import hmac
  File "/home/alex/anaconda/lib/python2.7/hmac.py", line 8, in <module>
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest
</pre>

**Comment by minrk** [comment]
I don't suppose you have an `operator.py` or `operator` directory in the CWD?

**Comment by ahwillia** [comment]
No? I tried launching directly in the `jupyter_notebook` directory at first. It doesn't launch in any directory.

**Comment by minrk** [comment]
What happens when you do this in a regular IPython session:

```python
import operator
print(operator.__file__)
import hmac
```

**Comment by ahwillia** [comment]
<pre>
In [1]: import operator

In [2]: print(operator.__file__)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9d31da67500b> in <module>()
----> 1 print(operator.__file__)

AttributeError: 'module' object has no attribute '__file__'

In [3]: import hmac
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-3e28f1954a71> in <module>()
----> 1 import hmac

/home/alex/anaconda/lib/python2.7/hmac.py in <module>()
      6 import warnings as _warnings
      7 
----> 8 from operator import _compare_digest as compare_digest
      9 
     10 

ImportError: cannot import name _compare_digest
</pre>

**Comment by minrk** [comment]
Then I think your virtualenv is the problem, because it's missing an important part of the standard library. Try creating a new env and see if you still have the issue.

**Comment by minrk** [comment]
What do you see from `print(operator)` in the broken env?

**Comment by ahwillia** [comment]
In [3]: print(operator)
    <module 'operator' (built-in)>

**Comment by ahwillia** [comment]
Thanks for walking me through this. Could the problem be related to the `pip install` bit? In order to get that to work I need to replace the command with:

    env CC=/usr/bin/gcc-4.8 pip install -r requirements.txt -e .

**Comment by minrk** [comment]
Since it's part of the stdlib, I don't think pip would be involved. The virtualenv is missing critical files somehow.

**Comment by ahwillia** [comment]
Is the virtualenv entirely necessary? Are there alternate installation instructions somewhere?

**Comment by takluyver** [comment]
The virtualenv isn't necessary, just suggested when you run unstable versions of software so that you can easily get back to your standard environment. If you're not worried about that, use pip with the `--user` option to install things under your home directory.
