### ISSUE TITLE
Update MathJax to 2.6, to fix rendering artifact

### ISSUE THREAD

**Issue by eronlloyd** [jupyter/notebook#1010]
I'm getting the following artifact of a right sided border on rendered MathJax objects (see image) from either manually created LaTeX code (as below) or Sympy expression renderings. The issue happens for both $ ... $ and $$ ... $$ items, where the MathJax object terminates; inline expressions will have them, too. This was working on the default install of a plain Python installation, using notebook 4.1, but under the most recent distribution of Anaconda, it's happening.

![image](https://cloud.githubusercontent.com/assets/197778/12616595/0625ccb8-c4da-11e5-9c58-3f1e90dabf36.png)

```
We know the following:
* Side AC = 500
* Side BC = 300
* Angle BAC = 36.87
* Angle ABC = 90

We need to solve for side AB. As described, angle BAC allows us to use its cosine ratio to derive AB, since it is adjacent and side AC is opposite angle ABC, and thus is the hypotenuse:

$\cos{36.87} = \frac{AB}{500}$  
$500 \cdot \cos{36.87} = AB$  
$400 = AB$

We can check this using the Pythagorean theorem, $a^2 + b^2 = c^2$:  
$300^2+b^2=500^2$  
$90000+b^2=250000$  
$b^2 = 160000$  
$b = \sqrt{160000} = 400$
```

I can do further testing, but wanted to at least bring this to your attention first to know if I'm missing something here. Thanks!

**Comment by akhmerov** [comment]
Do you observe this in chrome? If so, it's likely a known rounding bug in recent chrome: mathjax/MathJax#1300

**Comment by eronlloyd** [comment]
Yes, thanks for pointing that out. It's not a bug with notebook, then, so I'll close this out. I assume that we will get an update that includes MathJax 2.6 in the near future, which fixes this? Looks like it addresses a large number of rendering issues that could affect many users.

**Comment by eronlloyd** [comment]
Issue is with https://github.com/mathjax/MathJax/issues/1300, which should be fixed in version 2.6. For now, either apply a local patch or use a non-Chrome browser.

**Comment by kjyv** [comment]
I think this bug should not yet be closed as the required MathJax version in bower.json is still 2.5 which shows the described behavior. Therefore even though the bug is closed in MathJax, jupyter notebook still has a problem which needs to be fixed. It works fine with version 2.6 as far as I can tell.

**Comment by takluyver** [comment]
Reopening to remind us to upgrade MathJax

**Comment by eronlloyd** [comment]
Good call. Thanks for ensuring attention to this!

**Comment by DMRobertson** [comment]
Until MathJax gets upgraded by, notebook server hosts can add the line
`c.NotebookApp.mathjax_url = 'https://cdn.mathjax.org/mathjax/latest/MathJax.js'`
to their `jupyter_notebook_config.py` file to use the latest stable version from the MathJax CDN.

**Comment by igozali** [comment]
Is there any way to somehow embed or use that URL @DMRobertson referenced inside notebooks for distribution (instead of modifying the notebook server config)?

**Comment by willingc** [comment]
@minrk @takluyver Now that notebook 4.2 has been released, this should now work. Correct?

**Comment by akhmerov** [comment]
Just double-checked: it works with notebook v4.2 + chrome 50. Mathjax v2.6 is used.

**Comment by willingc** [comment]
Thanks @akhmerov for checking. 🌊
