### ISSUE TITLE
Update docs requirements.txt

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#1012]
Changing the build on jupyter_client recently seems to have caused the docs to fail to build. The version of setuptools is not being set correctly for RTD (18.2 RTD vs needed 18.5). docs/requirements.txt needs update. 

cc/@takluyver

**Comment by takluyver** [comment]
Actually, I think there's a better way. Let's use RTD's new conda support. I'll have a go at it.

**Comment by willingc** [comment]
@takluyver Sounds good to me.

**Comment by willingc** [comment]
@takluyver Ran into this issue with Sphinx, RTD conda support a few weeks ago when I was experimenting. FYI https://github.com/willingc/calpoly-cnw/blob/master/doc-workflow/experimental-conda-rtd.md
