### ISSUE TITLE
Multiply-wrapped elements over-indented

### ISSUE THREAD

**Issue by hsharrison** [jupyter/notebook#1016]
Currently, the notebook wraps double-wrapped elements as:

    a = np.array([
            1,
            2,
        ])

That is, it doubles up the indentation.

Compare this to the behavior of PyCharm:

    a = np.array([
        1,
        2,
    ])

Sublime Text takes a third approach:

    a = np.array([
                 1,
                 2,
                 ])

As far as I can tell, PEP8 doesn't have a recommendation here, so I recognize this is ambiguous. Nevertheless, I find the PyCharm behavior ideal. To me, Sublime's behavior is the worst of the three, *However*, once you fix the second line (with the `1` in my examples), further newlines will start  at the same indentation level. In the notebook, even after adjusting the `1` line, the `2` line starts one level deeper. The indentation has to be fixed on every line. Even if there's no consensus as to which default behavior is best, ideally the current indentation should be picked up on.

Thoughts?

**Comment by minrk** [comment]
Indentation of these things is governed by the CodeMirror mode, not anything in Jupyter, so this is probably a question better raised over there.

**Comment by hsharrison** [comment]
Ah okay, thanks.
