### ISSUE TITLE
Make ssl an optional import

### ISSUE THREAD

**Issue by jasongrout** [jupyter/notebook#1019]
Not everyone wants to (or can, for license reasons) use openssl.  It looks like we import ssl at https://github.com/jupyter/notebook/blob/a3e074c3a7e29eb3ec8b94627370698458f048ce/notebook/notebookapp.py#L22, but the *only* place the import is used is at https://github.com/jupyter/notebook/blob/a3e074c3a7e29eb3ec8b94627370698458f048ce/notebook/notebookapp.py#L873 and https://github.com/jupyter/notebook/blob/a3e074c3a7e29eb3ec8b94627370698458f048ce/notebook/notebookapp.py#L879, both just for the constants.

Thanks to @williamstein for making us aware of the issue.

**Comment by Carreau** [comment]
I'me fine with conditional import (as long as the behavior if not imported is sane, of course)

**Comment by Carreau** [comment]
Do you want that for a 4.2 ? or a 5.0 ?

**Comment by minrk** [comment]
Seems sensible enough to move the ssl import to where it's used. I just didn't know it was possible for that import to fail.
