### ISSUE TITLE
Jupyter notebook 405 HEAD /tree warning errors

### ISSUE THREAD

**Issue by garyway** [jupyter/notebook#1026]
Hi,

I am on Windows 10 Professional. Anaconda 2.4.1 (64-bit). Python 3.5.1. Conda 3.19.0. IPython 4.0.3. Jupyter 4.0.6.

I have installed Anaconda on two new machines, everything completed normally on both installs.

However, when running the Jupyter notebook from Launcher and navigating through the folders for my notebooks I repeatedly get the same error warning on both machines which you can see from the terminal screen snapshot. I have uninstalled and reinstalled several times and removed all files not removed during the uninstall each time. It doesn't make any difference. Th strange thing is that I have another install on a desktop and it works perfectly. The only things that is different is that the two machines that don't work with Anaconda are 2-in-1 laptop/tablets.

I hope someone can help on this.

Kind regards,

Gary Way
![jupyter notebook warning errors screenshot](https://cloud.githubusercontent.com/assets/16883640/12689325/0f4fc6a8-c6d4-11e5-8e0e-e42201483db3.png)

**Comment by takluyver** [comment]
I'd guess that that tablet version of IE is prefetching header information on links on the page. Is it a problem for actually using the notebook? If not, don't worry about the warnings in the command prompt.

We recommend using a browser such as Firefox or Chrome for the notebook, though I think the latest versions of IE mostly work.

**Comment by garyway** [comment]
Thanks for getting back to me so promptly Thomas. You are quite right in that the operation and functionality of the notebooks are not affected at all. I take your point about ignoring the warnings in that respect, it is just the irritation factor really. Aesthetically I don't like messages like that in the terminal window.

Your solution worked though! So many thanks Thomas.

It appears that there is a problem with Microsoft Edge, which is running on both laptop/tablets. When I switched to Internet Explorer and made it the default browser the problem went away. The problem wasn't there before so I guess Microsoft have made some untested changes to Edge. 

So problem solved. Thanks again.

Gary

**Comment by garyway** [comment]
Thanks for getting back to me so promptly Thomas. You are quite right in
that the operation and functionality of the notebooks are not affected at
all. I take your point about ignoring the warnings in that respect, it is
just the irritation factor really. Aesthetically I don't like messages like
that in the terminal window.

Your solution worked though! So many thanks Thomas.

It appears that there is a problem with Microsoft Edge, which is running on
both laptop/tablets. When I switched to Internet Explorer and made it the
default browser the problem went away. The problem wasn't there before so I
guess Microsoft have made some untested changes to Edge.

So problem solved. Thanks again.

Gary
