### ISSUE TITLE
Not able to connect to remote Jupyter Notebook from Jupyterhub

### ISSUE THREAD

**Issue by pawannrao-ebay** [jupyter/notebook#1027]
I am spawning a remote notebook on a docker container and passing the IP and port info to the spawner class, but I m not able to connect to it eventhough all the config seems right from jupyterhub and jupyter notebook stand point. I have done all the essentials like allowing all ips, trusting x-header configuration etc. Let me know if you can make sense out of this error.

The curl also works for the remote notebook:(curl http://172.X.Y.Z:PORT)

```
[I 2016-01-29 23:09:20.490 JupyterHub base:281] User test1 server took 83.033 seconds to start
[I 2016-01-29 23:09:20.491 JupyterHub orm:170] Adding user test1 to proxy /user/test1 => http://172.20.193.152:9009
[I 2016-01-29 23:09:20.511 JupyterHub log:100] 302 GET /hub/user/test1/ (test1@10.65.63.36) 83078.03ms
[I 2016-01-29 23:09:20.745 JupyterHub log:100] 302 GET /static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce (@10.65.63.36) 3.30ms
[I 2016-01-29 23:09:20.767 JupyterHub log:100] 302 GET /custom/custom.css (@10.65.63.37) 1.97ms
[I 2016-01-29 23:09:20.774 JupyterHub log:100] 302 GET /static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (@10.65.63.36) 0.68ms
[I 2016-01-29 23:09:20.786 JupyterHub log:100] 302 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c (@10.65.63.39) 0.67ms
[I 2016-01-29 23:09:20.792 JupyterHub log:100] 302 GET /static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (@10.65.63.41) 0.70ms
[I 2016-01-29 23:09:20.801 JupyterHub log:100] 302 GET /static/style/style.min.css?v=807166c81ded9672f91872a576572dcd (@10.65.63.40) 0.69ms
[W 2016-01-29 23:09:20.811 JupyterHub log:100] 404 GET /hub/custom/custom.css (test1@10.65.63.37) 3.29ms
[W 2016-01-29 23:09:20.813 JupyterHub log:100] 404 GET /hub/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (@10.65.63.36) 0.51ms
[W 2016-01-29 23:09:20.814 JupyterHub log:100] 404 GET /hub/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c (@10.65.63.39) 0.47ms
[W 2016-01-29 23:09:20.836 JupyterHub log:100] 404 GET /hub/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (@10.65.63.41) 0.68ms
[W 2016-01-29 23:09:20.841 JupyterHub log:100] 404 GET /hub/static/style/style.min.css?v=807166c81ded9672f91872a576572dcd (@10.65.63.40) 0.55ms
[I 2016-01-29 23:09:20.910 JupyterHub log:100] 302 GET /static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 (@10.65.63.36) 0.85ms
[W 2016-01-29 23:09:20.940 JupyterHub log:100] 404 GET /hub/static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 (@10.65.63.36) 0.71ms
```

**Comment by Carreau** [comment]
Edited to remove explicit ip/port number. We never know.
I'm not enough familiar with jupyterhub /docker to answer that.

**Comment by pawannrao-ebay** [comment]
Actually the request is getting forwarded to the notebook spawner and its responding back with the html. It looks like the proxy is not able to interpret the response.

test1:10 GET http://10.65.4.131:8000/hub/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c 
test1:11 GET http://10.65.4.131:8000/hub/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 
test1:25 GET http://10.65.4.131:8000/hub/custom/custom.css 
test1:16 GET http://10.65.4.131:8000/hub/static/style/style.min.css?v=807166c81ded9672f91872a576572dcd 
test1:26 GET http://10.65.4.131:8000/hub/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe 404 (Not Found)
test1:109 GET http://10.65.4.131:8000/hub/static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 404 (Not Found)

**Comment by minrk** [comment]
It looks like the single-user server is not getting its base URL set correctly, because it's prompting requests for `/static` instead of `/user/:name/static`, which it shouldn't do.

Is your single-user server Dockerfile available somewhere?

**Comment by pawannrao-ebay** [comment]
Thank you for your swift response. Yes Minrk, I figured it out and things are working fine. The essentials of base url wasnt quite clearly in notebook documentation. I was assuming the proxy would always send any user/username/* request to notebook server as a GET "/" request by default.
