### ISSUE TITLE
Overriding ssl_options protocol and forcing TLSv1 

### ISSUE THREAD

**Issue by tucif** [jupyter/notebook#1028]
Current code in [notebook/notebookapp.py#init_webapp](https://github.com/jupyter/notebook/blob/807f4501a2c507ee99076e9c724852519ca74412/notebook/notebookapp.py#L878) overrides user setting of ssl protocol version "ssl_version" and forces it to be TLSv1, so whatever the user configures in the jupyter_notebook_config file for this field will be ignored, and also some browsers like Chrome will say the connection uses an "obsolete cipher" when looking into the connection details.

A better approach for the whole ssl_context handling could be taking advantage of  an SSLContext object created through [ssl.create_default_context(*)](https://docs.python.org/3/library/ssl.html#ssl.create_default_context).
This function already provides safer defaults, which allows for protocol negotiation according to client/server capabilities while also declining SSLv2 and SSLv3. 

If it's not possible to use, due to SSLContext being on Python3.2+ and tornado that only allows a frozenset of keywords in the ssl_options dict, then it could be manually set to the user given value, as long as it is greater than [PROTOCOL_SSLV23](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_SSLv23), which has a value of 2, so the more modern protocols will always have a greater value, like TLSv1_2 which is 5.

This last suggestion would be a simple and extensible fix. 
I'd be happy to submit a PR with such, after hearing your feedback on the issue.

**Comment by Carreau** [comment]
> , so whatever the user configures in the jupyter_notebook_config file for this field will be ignored,

From a quick that seem untrue as the line you link to is executed only a the config is empty, but I might be missing something :

```python
        if not ssl_options:
    ...
        else:
    ...
            ssl_options['ssl_version'] = ssl.PROTOCOL_TLSv1
```

I would be fine with looking at the SSLContext patch you propose.

**Comment by minrk** [comment]
The override can be fixed by changing

```python
ssl_options['ssl_version'] = ssl.PROTOCOL_TLSv1
```

to

```python
ssl_options.setdefault('ssl_version', ssl.PROTOCOL_TLSv1)
````

If you want to open a PR using the context stuff when Python 3 is available, that would be AOK, but we can also start with the simpler direct fix.
