### ISSUE TITLE
Error loading notebook (parsing blanks in the url)

### ISSUE THREAD

**Issue by lucaventurini** [jupyter/notebook#1029]
Today jupyter has suddenly stopped serving my notebooks.

The error is `No such file or directory: YAQI/YAQI%%20-%%20Yet%%20Another%%20Quality%%20Index.ipynb`.

I suspect this has to do with the blanks in the title, since if I copy (from terminal) the .ipynb removing the blanks, the copy works as usual.

Moreover, in the url the title is `YAQI/YAQI%20-%20Yet%20Another%20Quality%20Index.ipynb`, thus in the error message there's an extra %.

I don't know if this is a bug, but up to yesterday it never complained of blanks or special characters. I'm sorry I don't remember if I updated anything recently.

**Comment by takluyver** [comment]
Sounds like something's being double escaped. Did  you recently update anything? Is this happening when you click on the notebook name from the dashboard page, or are you getting to it another way?

**Comment by lucaventurini** [comment]
It happens from both the dashboard page and running notebooks page.

**Comment by takluyver** [comment]
And what version of the notebook server are you running?

**Comment by lucaventurini** [comment]
4.1.0

**Comment by jvalhondo** [comment]
I'm facing exactly the same issue. Everything was working fine until I updated every pip package as follows:
`pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U`

I found it suggested here [http://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip](url)

Moreover, notebook server version is also the same 4.1.0

**Comment by gebetix** [comment]
+1

**Comment by minrk** [comment]
It certainly does look like double-escaping, though `%%20` isn't exactly what that should look like. That ought to be `%2520`. This makes some sense, since notebook-4.1*fixed* some double-escaping bugs in 4.0. I just tested a clean install of current stable of everything (new virtualenv, `pip install --upgrade notebook`), and URLs with spaces are all working correctly. Can you share your versions of everything (including Python, browser, and OS)? Do you have any custom templates or configuration?

My impression is that somehow you have a *partial* install of 4.1, and it's mixing some files from 4.0, causing inconsistent escaping behavior.

**Comment by lucaventurini** [comment]
If you say some commands for the *everything* you want, I'll post the
output here.


2016-03-14 13:51 GMT+01:00 Min RK <notifications@github.com>:

**Comment by minrk** [comment]
@lucaventurini sorry:

```bash
python -V
python -m platform
pip list
```

**Comment by jvalhondo** [comment]
Here is my output @minrk , thanks a lot:
python -V
Python 3.4.3
python -m platform
Linux-3.19.0-30-generic-x86_64-with-Ubuntu-14.04-trusty
pip list
aplazame-math (0.0.1)
aplazame-sdk (0.2.6)
backports-abc (0.4)
bokeh (0.11.1)
brain-sdk (0.0.1)
charts (0.4.6)
cycler (0.10.0)
decorator (4.0.9)
elasticsearch (2.3.0)
elasticsearch-dsl (2.0.0)
Flask (0.10.1)
ipdb (0.9.0)
ipykernel (4.3.1)
ipython (4.1.2)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
itsdangerous (0.24)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.1.1)
jupyter-console (4.1.1)
jupyter-core (4.0.6)
jupyterhub (0.4.1)
lightning-python (1.2.1)
lxml (3.5.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
mistune (0.7.2)
nbconvert (4.1.0)
nbformat (4.0.1)
notebook (4.1.0)
numpy (1.10.4)
pamela (0.2.1)
pandas (0.18.0)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.6)
pip (8.1.0)
plotly (1.9.6)
ptyprocess (0.5.1)
py (1.4.31)
Pygments (2.1.3)
pyparsing (2.1.0)
pytest (2.9.0)
python-dateutil (2.5.0)
pytz (2016.1)
PyYAML (3.11)
pyzmq (15.2.0)
qtconsole (4.2.0)
requests (2.9.1)
scikit-learn (0.17.1)
scipy (0.17.0)
setuptools (20.2.2)
simplegeneric (0.8.1)
simplepam (0.1.5)
six (1.10.0)
SQLAlchemy (1.0.12)
terminado (0.6)
tornado (4.3)
traitlets (4.1.0)
urllib3 (1.14)
Werkzeug (0.11.4)
wheel (0.29.0)

**Comment by jvalhondo** [comment]
BTW, I've just remove the underscores ( _ ) that I inserted for replacing white spaces, and I've just realized it's working fine.
Therefore, I guess my previous comment is not useful anymore

**Comment by minrk** [comment]
Oh, that reminds me: Can you:

1. make sure you have restarted the notebook server after the upgrade
2. do a force-refresh to clear the cache and/or test in an incognito/private tab?

The mixed-version nature of the bug means it's most likely to be mismatched Python and javascript, resulting from either upgrading the package without relaunching the server, or just stale, cached javascript in the browser.

**Comment by lucaventurini** [comment]
@minrk oh, you were right. I never restarted the notebook after the upgrade, and probably not even Chrome.

Now it works perfectly. Thanks!
