### ISSUE TITLE
add a scheduler so notebook can run automatically like crontab

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#1034]

**Comment by minrk** [comment]
I'm not sure what you mean by this. Can you elaborate?

**Comment by cailiang9** [comment]
Add a time scheduler so the notebook can run as a cronjob. We can see zeppelin

**Comment by willingc** [comment]
@minrk Did a search on Zeppelin's Apache Incubation project (https://github.com/apache/incubator-zeppelin/search?utf8=%E2%9C%93&q=cron). Here's the API implementation for their cron support:
incubator-zeppelin/zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/CronRequest.java

**Comment by takluyver** [comment]
You can execute a notebook from the command line using nbconvert. So if you want to do something like cron... what's wrong with using cron? ;-)

For any kind of scheduled task, cron has several advantages over something cron-like reimplemented in the notebook server:

- Cron is running by default, so your scheduled tasks won't stop when your notebook server is shut down
- There's no need for us to design and manage a new on-disk format to store scheduled tasks across a restart.
- You can run more than one notebook server simultaneously, so we would presumably need some logic to ensure that the same scheduled task is not being run by two servers at once.

**Comment by Carreau** [comment]
ping @yuvipanda, IIRC wikimedia lab want that as a notebook extension: a notebook dropdown that have `daily`, `hourly`, `weekly`, and a content manager that will set/remove the entry from cron on save. 

Though it is likely that this will **not** be part of core notebook, and will need to be an extension.

**Comment by yuvipanda** [comment]
https://phabricator.wikimedia.org/T124972 is our ticket for tracking this functionality. We're using kubernetes as our spawner, and kubernetes is in the process of adding a distributed cron functionality. Once that's done, I'll write this nbextension that does this. It'll probably be tied to kubernetes though - but should be extensible enough to run with a real cron.

I agree this shouldn't be part of core notebook but an extension.

**Comment by samthebest** [comment]
@takluyver  My understanding is that `nbconvert` only works for python notebooks.  What if a zeppelin notebook has a bunch of different languages?

**Comment by takluyver** [comment]
> My understanding is that nbconvert only works for python notebooks.

nbconvert works with any Jupyter notebook file, regardless of the language. Here's a [Julia example](http://nbviewer.jupyter.org/url/jdj.mit.edu/~stevenj/IJulia%20Preview.ipynb) on nbviewer (which uses nbconvert).

> What if a zeppelin notebook has a bunch of different languages?

Zeppelin is a completely separate notebook system, nothing to do with our technologies.

**Comment by samthebest** [comment]
@takluyver  DOH! I thought this was the zeppelin github. My bad.

**Comment by elgalu** [comment]
@yuvipanda did you have a chance to write that nbextension for scheduling notebooks through Kubernetes [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) ?

**Comment by prashant2k15** [comment]
What is the process to start jupyterhub automatically? 
I have installed a jupyterhub on my subdomain. Whenever I have to use jupyterhub I have to run a command **jupyterhub** on ubuntu terminal if it is closed we are not able to access it.

**Comment by takluyver** [comment]
@prashant2k15 you need to configure it as a service - see https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service#ubuntudebian-anaconda3-with-systemd
