### ISSUE TITLE
[MathJax] unsupported user configurations

### ISSUE THREAD

**Issue by pkra** [jupyter/notebook#1035]
We had a bug filed upstream at https://github.com/mathjax/MathJax/issues/1347 which seems to come down to Jupyter Notebooks not shipping all MathJax components, in particular not all output options.

If our educated guess is correct, we'd suggest to disable the corresponding MathJax UI elements to avoid users from accidentally breaking things for themselves.

**Comment by minrk** [comment]
#1036 disables the renderer menu. Do you think we should do something else?

**Comment by minrk** [comment]
@pkra what would be the API for limiting the renderer menu to the available output formats, if we wanted to allow NativeMML, for instance?

**Comment by pkra** [comment]
The quick and easy way would be to configure `showRenderer: false` to disable the renderer submenu, see http://docs.mathjax.org/en/latest/options/MathMenu.html.

To modify the content, would needs some configuration work, e.g.,

```javascript
MathJax.Hub.Register.StartupHook("End Config", function () {
          MathJax.Hub.Register.StartupHook("MathMenu Ready", function () {
            MathJax.Menu.menu.items[2].submenu.items[3].submenu.items[3].disabled = true;
           });
        });
```

would disable the menu entry for NativeMML output. (Note: there are hidden menus which influence the counting, see https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/MathMenu.js)

**Comment by milindsmart** [comment]
Related : https://github.com/jupyter/notebook/issues/1037

**Comment by minrk** [comment]
I did `showRenderer: false` in #1036. I think we'll wait until there's an option like:

```javascript
{
  MathMenu: {
    renderers: ["NativeMML", "HTML-CSS"],
  }
}
```

for specifying the available renderers before we re-enable the menu.

**Comment by dpvc** [comment]
I would recommend that you no use the indices directly, but use the `Find()` method to locate the menu that you want.  This will work even if other menus are added or removed.  E.g., 

```
MathJax.Hub.Register.StartupHook("MathMenu Ready", function () {
  var renderers = MathJax.Menu.menu.Find("Math Settings").submenu.Find("Math Renderer").submenu;
  renderers.Find("SVG").disabled = true;
  renderers.Find("Fast HTML").disabled = true;
  renderers.Find("PlainSource").disabled = true;
});
```
Add any renderers that you don't include.  If you don't provide the AssistiveMML or Fast Preview code, then you should disable those as well.

**Comment by pkra** [comment]
> I think we'll wait until there's an option like [...]

You might want to chime in when we redesign the menu in v3.0. But it's unlikely for 2.x, I think.

**Comment by minrk** [comment]
I think we can get away with Find for now; it's not exactly a fast-moving target. It would be great if part of slimming a MathJax install could include telling MathJax what output formats are available.
