### ISSUE TITLE
Wrong terminal width on window start

### ISSUE THREAD

**Issue by maver1ck** [jupyter/notebook#1038]
Hi,
I have following issue.
When I'm opening terminal windows it's starting width is too low. (as on attached screen)
![jupyter](https://cloud.githubusercontent.com/assets/4006010/12749186/48c9ebe2-c9af-11e5-93b6-4a2750307724.png)

What could be wrong ?

**Comment by takluyver** [comment]
Is there anything in the browser's JS console when you do that?

**Comment by maver1ck** [comment]
Just: resize to : 36 rows by  40 columns / main.js:43

I found the reason of this behaviour. I have custom.css with this line:
`.container { width:90% !important; }`

**Comment by takluyver** [comment]
So if you take the custom CSS away, it works?

**Comment by maver1ck** [comment]
Yes.

But I'd like to have custom notebook width.

**Comment by takluyver** [comment]
Someone who's more familiar with the CSS layout (@Carreau?) can either tell you a better way to do that, or devise a better if there isn't currently one.

**Comment by Carreau** [comment]
```
.notebook_app .container {
    width:70%; !important
}
```

will target only the notebook page. 

```
.terminal-app .container {
...
}
```

Will target only the terminal page (yeah for consistency, - vs _ )

**Comment by takluyver** [comment]
Thanks @Carreau !

**Comment by maver1ck** [comment]
Thanks. It works.
But how change width for terminal ? Is it possible ?

**Comment by takluyver** [comment]
Does the snippet @Carreau posted above not work?

**Comment by maver1ck** [comment]
When I added 
```
.notebook_app .container {
    width:90%; !important
}
```
everything is OK.

After adding
```
.terminal-app .container {
    width:90%; !important
}
```
problem came back.

**Comment by takluyver** [comment]
I guess the 90% sizing is relative to something unexpected. Myeh, CSS.

**Comment by Carreau** [comment]
> I guess the 90% sizing is relative to something unexpected. Myeh, CSS.

Ah, no my guess is he terminal is sized by JS (col times row):

So reduce the width of container -> reduce terminal size
reduce terminal size -> container have enough space to shrink
start looping until terminal get min width.

**Comment by takluyver** [comment]
The only thing more 'fun' than CSS is when your CSS is interacting with your javascript.

**Comment by maver1ck** [comment]
Is there any way to force resizing of terminal window from JS ?

**Comment by zxweed** [comment]
Does anybody found the solution for fix terminal width with custom container css?

**Comment by joshuria** [comment]
I'm using Chrome, and this is my solution: 
```javascript
jQuery(function() {
    if (typeof(terminal) === 'undefined')   return;
    function handler() {
        if (jQuery(terminal.term.viewportElement).is(':visible'))
            onresize();
        else
            setTimeout(handler, 1000);
    }
    setTimeout(handler, 1000);
});
```
Put this in `.jupyter/custom/custom.js`.
