### ISSUE TITLE
"edit" URLs for .js files

### ISSUE THREAD

**Issue by michaelsbradleyjr** [jupyter/notebook#1040]
In the Jupyter front-end, I can use `New -> Text File` and give the file a name which has a `.js` extension, edit and then save it. If I navigate away from the editor, the URL to that file looks like:

[http://localhost:8888/files/mydir/myfile.js](http://localhost:8888/files/mydir/myfile.js)

And when I click it, the file is served up raw, rather than it being opened in the editor.  But the URL to, say, a python file looks like:

[http://localhost:8888/edit/mydir/myfile.py](http://localhost:8888/edit/mydir/myfile.py)

Note the `files` segment in the first URL vs the `edit` segment in the second one.  If I manually load the URL to the `.js` file, changing `files` to `edit`, then it is opened in the editor as desired.

A workaround is to name my JavaScript files, which I want to edit in the Jupyter front-end, with a different extensing, e.g. `.javascript`. But that's not so great.

**Comment by Carreau** [comment]
Oops. Thanks, we;ll try to fix that in a 4.2

@captainsafia , @parleur want to give it a try ? I  know you did poke around the JS not so long ago.

**Comment by Carreau** [comment]
(marking as sprint-friendly, but not sure if it's really is)
