### ISSUE TITLE
Cell split during quiet notebook migration breaks the functionality of a custom extension we built

### ISSUE THREAD

**Issue by kylepolich** [jupyter/notebook#1042]
We've encountered a bug (seems like a pretty small one), and we have a workaround, but I thought it would be worth coming here to mention. Either we're extending Jupyter in ways you would prefer we didn't (in which case, we'd like to know best practices) or perhaps our extension is fine and this is just an FYI about how we are using Jupyter.

This appears to have occurred when we recently migrated to the latest version of Jupyter.  Formerly, I think we were 2-3 version back.  I can find out precise details if it's important.

We inject metadata into notebooks, here's a notebook that was created on an older version of ipython:

```
 {
      "cell_type": "markdown",
      "metadata": {
        "_datascience": {
          "keep": true,
          "summary": true
        }
      },
      "source": [
        "### Key Defintion: XXXXX",
        "> We define XXXXX by US County."
      ]
    },
```

We recently upgraded to the latest, and the cells were quietly migrated to look this way:

```
     {
      "cell_type": "markdown",
      "metadata": {
        "_datascience": {
          "keep": true,
          "summary": true
        }
      },
      "source": [
        "### Key Defintion: XXXXX"
      ]
    },
    {
      "cell_type": "markdown"
      },
      "source": [
        "> We define XXXXX by US County."
      ]
    },
```

I think it probably relates to the change in types of cells.  It did break the markdown perfectly well into two separate cells, that part is fine.  But our expectation was that our "metadata" that was injected should have also been copied.

Is this a bug, or should we not be storing additional data in this way?

**Comment by takluyver** [comment]
I think storing additional data that way is fine, it's just something we neglected to consider when writing the notebook migration code. It's also not obvious that copying the metadata is always the right thing to do, though I suspect it is in more cases than not.

I'm also not sure exactly why we split the cells up like that. It's probably something to do with the removal of heading cells as a separate cell type - but you weren't using heading cells in the original, so I'm not sure why we'd do anything with it.

**Comment by minrk** [comment]
I cannot find where we would be splitting the cell on upgrade (it doesn't make sense to ever split on upgrade, only split on downgrade if we wanted to restore heading cells, which I checked and we don't do).

Can you provide more information on what versions were used before upgrading and after, and ideally a complete notebook that reproduces the issue?

**Comment by kylepolich** [comment]
I'll ask my colleague who uncovered the problem if she has a reproducible example.  Thanks!

**Comment by kylepolich** [comment]
Oops, didn't mean to close it.

**Comment by kylepolich** [comment]
I talked to the team about making this discretely reproducible and the thought was that we'd have to roll back to an old version of ipython, create similar notebooks to the ones that have been upgraded, and migrate forward.  All in all, given the effort compared to minor nature of this bug, it doesn't seem like a good use of our time to generate or yours to review.  I think we can just close this one out.

We'd appreciate any guidelines on how to build plugins that are as future proofed as possible.
