### ISSUE TITLE
Intermittent problem with tests hanging after completion

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#1043]
I'm not sure that this bug is actually in notebook, but so far I've only seen it from running the notebook test suite. Something goes wrong in the cleanup process after the tests, which results in the test process never exiting. I've seen this on Jenkins and now on Circle CI - it hangs until the CI system gives up on the build and fails it. IIRC, @Carreau has also seen this error running the tests locally.

Investigating now, but any suggestions are welcome.

```
............................................../usr/local/lib/python3.4/dist-packages/nbformat/validator.py:147: UserWarning: No schema for validating v2 notebooks
  warnings.warn("No schema for validating v%s notebooks" % version, UserWarning)
...............................................................S..........Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.4/site.py", line 78, in <module>
    import os
  File "/usr/lib/python3.4/os.py", line 57, in <module>
    import posixpath as path
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1940, in find_spec
  File "<frozen importlib._bootstrap>", line 1914, in _get_spec
  File "<frozen importlib._bootstrap>", line 2050, in find_spec
KeyboardInterrupt
........................................................................S
----------------------------------------------------------------------
Ran 193 tests in 13.701s

OK (SKIP=2)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/history.py", line 755, in writeout_cache
    self._writeout_input_cache(conn)
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/history.py", line 739, in _writeout_input_cache
    (self.session_number,)+line)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139968591865600 and this is thread id 139968726718272
```

**Comment by takluyver** [comment]
Turned out to be easier than I feared - jupyter/nbconvert#229. We'll probably want to either do a new release of nbconvert soon, or run the notebook tests with development versions of nbconvert until we do.

**Comment by takluyver** [comment]
Annoyingly, it seems that the traceback and the hanging were two separate problems - we resolved the traceback, but the tests are still hanging after completion on Jenkins.

**Comment by takluyver** [comment]
...running the tests in verbose mode appears to prevent them from hanging. I don't know how that makes sense, but my debugging didn't really get anywhere, so at least it's a way to avoid the issue.

**Comment by takluyver** [comment]
Myeh, so much for that theory. The tests just hung again on Jenkins. :confused:

**Comment by takluyver** [comment]
This is happening quite frequently on Travis and Jenkins, but so far I haven't managed to reproduce it anywhere where I can begin to debug what's going on. :angry:

**Comment by willingc** [comment]
@takluyver It's a bit odd in the output where pip 7.x is being removed. Is it possible to run the ``pip install --upgrade pip`` or ``python -m pip install --upgrade pip`` separately before upgrading/installing other packages?

**Comment by takluyver** [comment]
Yup, running that on Jenkins now to see what happens.

**Comment by minrk** [comment]
Ha, pretty sure I found it! It is indeed a zmq-related bug (though it's in this repo). After spending most of my day on this, If I'm right, the patch is two characters, adding a missing `()`. PR incoming, once I make some changes that would make this a bit easier to notice.
