### ISSUE TITLE
Vertical bar at the end of equations

### ISSUE THREAD

**Issue by rgap** [jupyter/notebook#1053]
I have installed Jupyter 4.0.6 and in the last version of Chrome, it doesn't display equations correctly and  it works ok in Firefox and Safari, the problem is just in Chrome. Some screenshots:
![0](https://cloud.githubusercontent.com/assets/1432440/12862721/2a1c26d0-cc3c-11e5-930e-f6cc922e04ad.png)

Then

![1](https://cloud.githubusercontent.com/assets/1432440/12862722/2a2202b2-cc3c-11e5-865e-b00fa4f867c5.png)

As it can be seen it's solved by removing the "span".

![2](https://cloud.githubusercontent.com/assets/1432440/12862723/2a2263a6-cc3c-11e5-8ad0-223a3b35a99e.png)

**Comment by willingc** [comment]
@rgap Thanks for reporting the issue and offering a suggestion. We appreciate it.

This issue has been reported in #1010 and resolved in #1032. The current development release 4.2 has a solution for this issue, and we hope to backport the fix. If you wish to stay on 4.0.6, please use a FF or Safari.

I'm going to close this issue. Feel free to reopen if needed. Thanks!
