### ISSUE TITLE
importing matlplotlib takes 100X longer in notebooks 

### ISSUE THREAD

**Issue by sg-s** [jupyter/notebook#1054]
Hi,

I observe the following which I believe is a bug. I'm running python3 on Mac OS X, everything installed manually from homebrew or pip3 

1) When I launch python3 in the terminal, and run the following:

```python3
from pyplot import *
show(plot([1,2,3]))
```

it plots instantly. 

2) When I launch `jupyter notebook`, then open a new terminal in the webbrowser, and run the same command, it also makes the plot instantly. 

3) When I try to open a notebook, and run the same set of commands in a notebook, it takes ~2min to *just import pyplot*

What I see is the "Python" icon for the GUI bounce in the dock endlessly for a very long time, before being ready. 

Please help me fix the strangely long start up time in the notebooks.

**Comment by takluyver** [comment]
What are `sys.executable` and `sys.path` in your terminal and in a notebook?

Does it make a difference if that is the first thing you run in a notebook, compared to if you have already finished running something else in the notebook?

**Comment by sg-s** [comment]
hi, thanks for the response. from my terminal running python3:

``` python
>>>import sys
>>> sys.executable
'/usr/local/opt/python3/bin/python3.5'
>>> sys.path
['', '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python35.zip', '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5', '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin', '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/site-packages']
```

and from a notebook, the sys. exectuable is the same, but the sys.path is:

```
['',
 '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python35.zip',
 '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5',
 '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin',
 '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages',
 '/usr/local/lib/python3.5/site-packages/IPython/extensions',
 '/Users/sg-s/.ipython']
```

**Comment by takluyver** [comment]
OK, that confirms it's running the same copy of Python, and looking in the same place to find matplotlib.

You said it takes a long time just doing the import. Just to confirm, you have split the two lines up, and it's the import, not the plot, that is slow?

While it's doing whatever it's doing, can you interrupt it? Click the 'stop' button on the notebook toolbar. If that works, you should get a traceback ending with `KeyboardInterrupt`. Do that a few times, and you can get an idea of what part of the code it's being slow in.

`pyplot` is not a standard top-level module. Are you importing `from matplotlib.pyplot`, `from pylab`,  or do you have another module called `pyplot`?

**Comment by sg-s** [comment]
hi @takluyver  thanks for the feedback. 

> You said it takes a long time just doing the import. Just to confirm, you have split the two lines up, and it's the import, not the plot, that is slow?

yes, the import is slow. just running 

```
from matplotlib.pyplot import *
```

causes the problem.

interestingly, using just `from matplotlib import *` works OK

so it's something specific to pyplot. 

i tried stopping the kernel using the stop button, but it didn't do anything apart form telling me that it was stopping the kernel. it also flashed a message on the terminal:

```
Kernel interrupted: bd4f986c-ce7c-477a-84f3-df7f0a167bc3
```

**Comment by sg-s** [comment]
Hi, after some further digging, i found a workaround. while the issue persists, it doesn't bother me anymore, so please feel free to close this if you want. 

for the record, what I did was go to the [try jupyter](https://try.jupyter.org/) page and used `%matplotlib inline`, this made the plots inline, and is instantanoues. 

so using:

```
%matplotlib inline
from matplotlib.pyplot import *
show(plot([1,2,3]))
```

worked for me.

**Comment by takluyver** [comment]
I believe importing `matplotlib.pyplot` initialises a backend, which just importing matplotlib doesn't. Using `%matplotlib inline` makes it use the IPython inline backend, so the problem is probably with whichever backend it's picking otherwise.

Can you try `matplotlib.get_backend()` both in a terminal and a notebook, and see what the results are?

@tacaswell, any ideas why setting up the backend would take much longer in an IPython kernel?

**Comment by tacaswell** [comment]
Maybe a poor interaction between a gui frame work and the kernel communication framework? What is your default backbend?  It looks like you are on a mac? I wonder if there are also frame work vs non frame work build issues? Does it depend on browser?

I would also like to ask you not to import * and try using `%matplotlib notebook` instead of inline.

**Comment by sg-s** [comment]
hi, running
```
import matplotlib as matplotlib
matplotlib.get_backend()
```

 on a notebook or from the terminal (outside jupyter) gave the same result:

```
'MacOSX'
```

using 

```
%matplotlib notebook
from matplotlib.pyplot import plot
show(plot([1,2,3]))
```

worked great too, and made the plot instantly. 

it doesn't seem to depend on the browser (tested on Chromium and Firefox)

**Comment by tacaswell** [comment]
How about  `%matplotlib tk` ?

**Comment by sg-s** [comment]
cool! 
```
%matplotlib tk
from matplotlib.pyplot import *
show(plot([1,2,3]))
```
launched the GUI instantly and made the plot (just like in the terminal, outside of jupyter)
