### ISSUE TITLE
Line wrapping

### ISSUE THREAD

**Issue by hellpanderrr** [jupyter/notebook#106]
I've updated ipython-notebook to Jupyter and noticed that code wrapping in cells is turned off now. In previous version you could turn it on by adding line
``` IPython.Cell.options_default.cm_config.lineWrapping = true;```
to the custom.js, but now this doesn't help. Javascript console shows that there no such parameters as lineWrapping (and lineNumbers also) for the cm_config. 
Was this feature moved somewhere (or removed) or is this a problem with my installation?

**Comment by Carreau** [comment]
Well, it does work for me, but you are probably hitting a race condition as you are accessing the `IPython` global. 

1) it is better to change module values by actually requiring them, to be sure they are loaded in custom,js:

```
require(['notebook/js/cell'], function(cell){cell.Cell.options_default.cm_config.lineWrapping = true})
```

2) the better option woudl be to persist the config of line wrapping through the API (in flux):

```
IPython.notebook.get_cell(0).class_config.set('cm_config',{'lineWrapping':true})
```

@takluyver we don't seem to expose the class_config on the class which prevent to do `require([codecell], function(modify config))`. Am I mistaking? Should we allow that ?

**Comment by takluyver** [comment]
I don't think there's a good way to expose it on the class, because it relies on the `ConfigSection` instance created by `main.js` and passed in when instantiating `Cell`. In this case, `class_config` means 'config relevant to instances of this class', not 'config which is accessed on the class object'.

**Comment by minrk** [comment]
@takluyver @Carreau does this work if specified via the frontend-config API?

**Comment by Carreau** [comment]
I'm not sure I'll try to have a look, assigning to myself.

**Comment by Carreau** [comment]
> @takluyver @Carreau does this work if specified via the frontend-config API?

> `IPython.notebook.get_selected_cell().class_config.set('cm_config',{'lineWrapping':true}) // or false`

Yes it does work independently for markdown cells and code cell and end up as the following in config:

```
{
  "MarkdownCell": {
    "cm_config": {
      "lineWrapping": false
    }
  },
  "CodeCell": {
    "cm_config": {
      "lineWrapping": false
    }
  },
}
```

**Comment by scharfmn** [comment]
IPython.notebook.get_selected_cell().class_config.set('cm_config',{'lineWrapping':true}) // or false

Does not work for me.  
IPython 4.0.0 
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42)

**Comment by Carreau** [comment]
> Does not work for me.

Where did you do that ?
Did it gave errors?
  - in the js console ?
  - in the terminal ?

Did you reload the page ?
Did you restart the server ?

**Comment by scharfmn** [comment]
I put this
    IPython.notebook.get_selected_cell().class_config.set('cm_config',{'lineWrapping':true}) // or false

into custom.js, as in the old version.

I did restart the server. What happened was: no wrapping, but then when I would try to execute cells that had long lines, I would get a python syntax error where there wasn't one before, with the interpreter giving the same kind of complaint as when one does a line-break without a `\`.

**Comment by Carreau** [comment]
No you need to execute that only once in the js console of the browser. Not in custom.js

**Comment by scharfmn** [comment]
Got it - thank you very much indeed.

**Comment by DieselAnalytics** [comment]
Is it possible to turn line wrapping on via the %config magic? If so could you please share the code to do so?

**Comment by JRKelly** [comment]
>> No you need to execute that only once in the js console of the browser. Not in custom.js

That browser console says it does not recognize Ipython.  Not being familiar with that environment, how do I make it aware of IPython?

**Comment by takluyver** [comment]
- Ensure you are on a tab with a notebook open
- It is case sensitive
- At some point in the future, you may need to use `Jupyter` instead of `IPython`. For the moment, `IPython` still works, at least for me, as an alias.
