### ISSUE TITLE
Rename "cut cell" and other shortcuts to take selections into account

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/notebook#1060]
Currently the shortcut name for cutting a selection of cells is "cut cell". I imagine this stemmed from when multicell selection wasn't possible, but now when I selected something and then saw the cut cell action name, I hesitated to do this with selection not knowing if it would apply to only the cursor cell or the entire selection.

Given that it does apply to the selection I figured something like "cut selected cells" or "cut selection". would work. I also think this applies to other shortcut names (e.g., "copy cell").

**Comment by minrk** [comment]
Thanks! #1061 should pluralize the ones I noticed.
