### ISSUE TITLE
[Feature request] Make notebook focus follow notebooks cells when they are moved up/down

### ISSUE THREAD

**Issue by ericdill** [jupyter/notebook#1065]
Would it be possible for the notebook view to follow notebook cells when you are moving cells up/down?  It is difficult to move cells to the correct place when you cannot tell exactly where the cell has ended up once it has moved out of the field of view without manually scrolling the window.

**Comment by ericdill** [comment]
[edit] updated original comment because I hastily hit 'enter'

**Comment by ericdill** [comment]
Also worth noting is that I have little javascript development experience, but am willing to learn!  If this feature request is interesting to you all and someone is willing to point me in the right direction, I would be interested in attempting to implement this

**Comment by takluyver** [comment]
There's actually already a proposed fix for this at #1071, but if you're interested in getting involved with some JS development, that'd be great. Have a look at the [issues tagged sprint friendly](https://github.com/jupyter/notebook/issues?q=is%3Aopen+is%3Aissue+label%3Asprint-friendly). Or somebody who's more familiar with that part of the code than me may be able to give you some idea where to start.

**Comment by ericdill** [comment]
Oh, great!  Thanks @takluyver I'll bookmark that link and come back when I have some spare cycles.  I'll go ahead and close this issue since there is already jupyter/jupyter#105 and #1071.
