### ISSUE TITLE
Code sells overflow right-edge in Chrome 48 (OSX?)

### ISSUE THREAD

**Issue by parente** [jupyter/notebook#1067]
New Jupyter Notebook 4.0.x and 4.1.0  behavior starting in Chrome 48. Tested on OSX. Not sure about other platforms.

![chrome](https://cloud.githubusercontent.com/assets/153745/12898402/8d00772a-ce7a-11e5-95ec-dbb23e6eff85.png)

Any code cell with text that runs longer than the width of the notebook document container exhibits this problem.

For comparison, Safari still has the following original (correct) behavior:

![safari](https://cloud.githubusercontent.com/assets/153745/12898403/8d05414c-ce7a-11e5-9518-9d2d36eb9e56.png)

**Comment by ellisonbg** [comment]
I see this too :(

On Mon, Feb 8, 2016 at 1:31 PM, Peter Parente <notifications@github.com>
wrote:

> New Jupyter Notebook 4.0.x and 4.1.0 behavior starting in Chrome 48.
> Tested on OSX. Not sure about other platforms.
>
> [image: chrome]
> <https://cloud.githubusercontent.com/assets/153745/12898402/8d00772a-ce7a-11e5-95ec-dbb23e6eff85.png>
>
> Any code cell with text that runs longer than the width of the notebook
> document container exhibits this problem.
>
> For comparison, Safari still has the following original (correct) behavior:
>
> [image: safari]
> <https://cloud.githubusercontent.com/assets/153745/12898403/8d05414c-ce7a-11e5-9518-9d2d36eb9e56.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/1067>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by parente** [comment]
Dupe of #1003
