### ISSUE TITLE
mpi4py causes problems with jupyter (python kernel) notebook

### ISSUE THREAD

**Issue by andyfaff** [jupyter/notebook#1069]
I have been happily using miniconda and jupyter notebook. However, I've just `conda install mpi4py`. This installs mpi4py and openmpi and now the jupyter notebook doesn't work at all:

    [I 12:04:33.423 NotebookApp] Serving notebooks from local directory /Users/anz/Documents/examples
    [I 12:04:33.424 NotebookApp] 0 active kernels 
    [I 12:04:33.424 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
    [I 12:04:33.424 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    [I 12:04:37.085 NotebookApp] Kernel started: 2073ac9e-b4e2-4760-b526-b22b07dcda0c
    --------------------------------------------------------------------------
    Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
    But I couldn't open the help file:
    /opt/anaconda1anaconda2anaconda3/share/openmpi/help-opal-runtime.txt: No such file or directory.      Sorry!
    --------------------------------------------------------------------------
    [p0006m:95766] [[INVALID],INVALID] ORTE_ERROR_LOG: Error in file runtime/orte_init.c at line 79
    --------------------------------------------------------------------------
    Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
    But I couldn't open the help file:
    /opt/anaconda1anaconda2anaconda3/share/openmpi/help-mpi-runtime: No such file or directory.  Sorry!
    --------------------------------------------------------------------------
    *** An error occurred in MPI_Init_thread
    *** on a NULL communicator
    *** MPI_ERRORS_ARE_FATAL: your MPI job will now abort
    [p0006m.:95766] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
    [I 12:04:43.085 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 2073ac9e-b4e2-4760-b526-b22b07dcda0c restarted

I am running with ipython 4.1.1, openmpi 1.6.3, mpi4py 2.0.0. If I uninstall mpi4py and openmpi then Jupyter notebook works again.

I'm using miniconda on OSX 10.9.5, installing into a Py3.4 virtualenv

**Comment by willingc** [comment]
I was able to duplicate the issue with miniconda, jupyter 4.1, openmpi and mpi4py using a conda environment with Python 3.5 and OSX 10.11.3.

It looks like the mpi4py google group has a solution for mpi4py that is causing the errors [here](https://groups.google.com/forum/#!topic/mpi4py/PTKq6abLpNQ).

**Comment by willingc** [comment]
@andyfaff I was able to get mpi4py running with the notebook in a python 2.7 virtualenv by:
```
brew install mpich
export ARCHFLAGS='-arch x86_64'
pip install mpi4py
pip install jupyter
jupyter notebook
```

**Comment by takluyver** [comment]
That you;re seeing `/opt/anaconda1anaconda2anaconda3` in the error suggests there's a problem with the conda package for mpi4py - that should be replaced by the path to your conda env.

Ping @ilanschnell

**Comment by ilanschnell** [comment]
Thanks, I'll take a look.
