### ISSUE TITLE
Can't shutdown notebook when select all

### ISSUE THREAD

**Issue by MathiasDesch** [jupyter/notebook#107]
The option to shutdown notebooks is not displaying when we are choosing to select the notebooks through select all tab. We should be able to shut them down if they are all running, no ? Instead it is needed to select all the notebooks to shutdown,  one by one.

**Comment by Carreau** [comment]
It does work here, moreover you have the select-all-running option.
Can you check your IPython version ?

![screen shot 2015-05-21 at 13 04 50](https://cloud.githubusercontent.com/assets/335567/7754363/0daa2d20-ffba-11e4-802a-a230824d4603.png)
![screen shot 2015-05-21 at 13 04 56](https://cloud.githubusercontent.com/assets/335567/7754364/0dacbdd8-ffba-11e4-99c5-0ae631b860ac.png)
![screen shot 2015-05-21 at 13 05 02](https://cloud.githubusercontent.com/assets/335567/7754365/0dad7084-ffba-11e4-8836-6b6b574694ac.png)

**Comment by MathiasDesch** [comment]
Indeed it was a problem with my ipython version. Thanks
