### ISSUE TITLE
pprinting inconsistent: sympy.subs() with noncommutative symbols 

### ISSUE THREAD

**Issue by huberfelix0** [jupyter/notebook#1070]
pprinting (init_printing()) gives inconsistent output when confronted when using sympy.subs() with noncommutative symbols:

Inconsistent behavior with pprinting:
`import sympy as sp`
`sp.init_printing()`
`a  = sp.symbols('a')`
`b  = sp.symbols('b',  commutative=False)`
`c  = sp.symbols('c')`
`ex = - a`
`ex.subs(a, b + c)`
'−c+b'
expected: '- (b + c)'

Expected and correct behavior without pprinting :
`import sympy as sp`
`a  = sp.symbols('a')`
`b  = sp.symbols('b',  commutative=False)`
`c  = sp.symbols('c')`
`ex = - a`
`ex.subs(a, b + c)`
`-(b + c)`

The issue does not arise when using commutative symbols. In similar fashion one gets more unexpected behavior (double minus sign):
'import sympy as sp'
'sp.init_printing()'
'a  = sp.symbols('a')'
'b  = sp.symbols('b',  commutative=False)'
'c  = sp.symbols('c')'
'ex = - a'
'ex.subs(a, -b - c)'
'−−c−b'

This again does not appear without the init_printing() statement. Again, the noncommutative part does not pick up the minus sign. However, If both b and c are noncommutative, one of them will still show the correct sign, be it accidental or not. In any case, the internal representation seems to be correct, as the issue disappears when turning of init_printing()

versions:
Jupyter notebook 4.1.0
Python 2.7.6
Sympy 0.7.6

**Comment by takluyver** [comment]
ping @asmeurer - I don't think this can be a notebook issue.

**Comment by asmeurer** [comment]
Yes, this is a SymPy issue. Please open an issue at https://github.com/sympy/sympy/issues (and use the code formatting button above the issue form to format your code).

**Comment by takluyver** [comment]
Thanks Aaron, closing here. Do drop a link to the sympy issue once it's created, for anyone who finds this in the future.

**Comment by huberfelix0** [comment]
I opened a ticket on [sympy] (https://github.com/sympy/sympy/issues/10561).

**Comment by takluyver** [comment]
Thanks!
