### ISSUE TITLE
Help ! Shortcuts in jupyter notebook don't work. (TAB and SHIFT+TAB)

### ISSUE THREAD

**Issue by LeoWongTaiwan** [jupyter/notebook#1075]
Hello guys, really need help in this. I'm a new python user an is using Jupyer Notebook for coding.

I found out some of the shortcuts are not working. Like pressing TAB to pop out the "code completion or indent".nothing happens when I press it now... (I press TAB after the dot)

![image](https://cloud.githubusercontent.com/assets/12297358/12939664/db08c084-cffc-11e5-909b-347895823f57.png)

And also, tooltip didn't pop out either when I press SHIFT+TAB...

I've restart my browser, and switch from chrome, chrome canary, and IE, but still not working. Is there any solutions?

Thanks a lot! Really need your help!

**Comment by takluyver** [comment]
With that code, it can't inspect L until you've run the cell, because L hasn't been created until you run that code. We don't want to try to run your code in order to do completions.

If you define L in one cell, and run that, tab completions should work in the next cell.

We've got plans to use some better completion machinery (jedi) that might be able to complete in that case by doing static analysis, but that's still some way off.

**Comment by smcinerney** [comment]
The workaround is to put the code in a separate cell, and execute it.
This also happens on more complex expressions, the workaround I found is to assign the intermediate result to a temporary, at least while you're writing code:

```
tmp = pd.crosstab(tr['gender'], tr['status'])
tmp.<shift-tab completion works here>
```

**Comment by mxplusb** [comment]
Is there any update on when this will be implemented?

**Comment by takluyver** [comment]
The relevant machinery is in the kernel. We tried to use jedi for IPython 5, but found some problems and turned it off again. We hope to be able to turn it back on and fix the issues for IPython 6, but there's a lot of things people are doing.

**Comment by singsuyash** [comment]
Any further updates on this feature?

**Comment by AkiraCharles** [comment]
I am having a similar problem at times.

tmp = pd.crosstab(tr['gender'], tr['status'])

tmp.<shift-tab completion works here>

If i try the above syntax....the method list doesnt appear

**Comment by Light--** [comment]
> The workaround is to put the code in a separate cell, and execute it.
> This also happens on more complex expressions, the workaround I found is to assign the intermediate result to a temporary, at least while you're writing code:
> 
> ```
> tmp = pd.crosstab(tr['gender'], tr['status'])
> 
> tmp.<shift-tab completion works here>
> ```

what is "tr" ?

**Comment by ghuname** [comment]
tr is a pandas dataframe

**Comment by Tarun-Rawat** [comment]
> Hello guys, really need help in this. I'm a new python user an is using Jupyer Notebook for coding.
> 
> I found out some of the shortcuts are not working. Like pressing TAB to pop out the "code completion or indent".nothing happens when I press it now... (I press TAB after the dot)
> 

I am in the same shoes(new to programming/python), in my case, restarting the Kernel helped.
Go to Kernel, then restart, Wait for few seconds/steps(shown in jupyter), then try it again.

**Comment by Berkat0789** [comment]
If you are using jupyter notebooks and anaconda create a new environment. Will fix the issue

**Comment by salpevir5** [comment]
In the Google Colab environment, I fixed it as follows: 
Tools | Settings | Editor |uncheck Automatically trigger code inspection. 
Then, Tab and Shift-Tab worked as expected.

**Comment by ramyaelineni5** [comment]
> Hello guys, really need help in this. I'm a new python user an is using Jupyer Notebook for coding.
> 
> I found out some of the shortcuts are not working. Like pressing TAB to pop out the "code completion or indent".nothing happens when I press it now... (I press TAB after the dot)
> 
> ![image](https://cloud.githubusercontent.com/assets/12297358/12939664/db08c084-cffc-11e5-909b-347895823f57.png)
> 
> And also, tooltip didn't pop out either when I press SHIFT+TAB...
> 
> I've restart my browser, and switch from chrome, chrome canary, and IE, but still not working. Is there any solutions?
> 
> Thanks a lot! Really need your help!

Restart Kernal it will be worl

**Comment by mgupta182** [comment]
pressing Esc key worked for me, try it once. It is used to enable command mode.

**Comment by lsbprithvi** [comment]
It is a simple thing just see no the top of the notebook u will see 
File
Edit
View
Insert
Cell
Kernel
Widgets -------------- open this and click on Embed Widgets and go to the cell check by pressing TAB 2 times.
Help

**Comment by lsbprithvi** [comment]
> Hello guys, really need help in this. I'm a new python user an is using Jupyer Notebook for coding.
> 
> I found out some of the shortcuts are not working. Like pressing TAB to pop out the "code completion or indent".nothing happens when I press it now... (I press TAB after the dot)
> 
> ![image](https://cloud.githubusercontent.com/assets/12297358/12939664/db08c084-cffc-11e5-909b-347895823f57.png)
> 
> And also, tooltip didn't pop out either when I press SHIFT+TAB...
> 
> I've restart my browser, and switch from chrome, chrome canary, and IE, but still not working. Is there any solutions?
> 
> Thanks a lot! Really need your help!

It is a simple thing just see no the top of the notebook u will see
File
Edit
View
Insert
Cell
Kernel
Widgets -------------- open this and click on Embed Widgets and go to the cell check by pressing TAB 2 times.
Help

**Comment by raffaem** [comment]
> The relevant machinery is in the kernel. We tried to use jedi for IPython 5, but found some problems and turned it off again. We hope to be able to turn it back on and fix the issues for IPython 6, but there's a lot of things people are doing.

Looks like support for Jedi was introduced in [IPython 6](https://ipython.readthedocs.io/en/stable/whatsnew/version6.html#ipython-6-0).

This can be closed?

**Comment by jtpio** [comment]
Closing as the classic notebook UI has now been moved to https://github.com/jupyter/nbclassic.

Feel free to open a new issue there if it is still relevant, thanks!
