### ISSUE TITLE
Is there any roadmap for releasing Jupyter packages?

### ISSUE THREAD

**Issue by ricardoduarte** [jupyter/notebook#108]

**Comment by Carreau** [comment]
When ready. Hopefully before SciPy.

**Comment by minrk** [comment]
The main tasks we have between us and release:

- setting up config migration
- coordinated documentation
- widget installation

There will be features and changes in the release, as there always are, but none are officially planned.

The rough order will be:

1. traitlets
2. jupyter-core
3. nbformat
4. jupyter-client
5. nbconvert

Then, to preserve things like `ipython[all]`, we will need to release the rest together.

**Comment by ricardoduarte** [comment]
Ok, thanks for the fast answer.

I'll be watching the repo time to time for any news.
