### ISSUE TITLE
Segmentation fault when my extension/scipy.optimize.fmin_l_bfgs_b has printf and run with jupyter notebook under Ubuntu 14.04

### ISSUE THREAD

**Issue by hyliu1989** [jupyter/notebook#1082]
Hi guys,
    I encounter a segmentation fault when running my C++ extension of python on jupyter notebook. I have tested my python code and C++ extension module on ipython terminal. They ran well without any problem. However when I run the same code in the jupyter notebook, it just crashed. I believe this segmentation fault is not due to my code because I can work around this problem by adding `#define printf PySys_WriteStdout` into my C++ code. I guess the stdout for the environment running C extension is not valid.
   Sorry the error screen is gone so I do not post the error message in the post. Here is the information from jupyter help

```
Server Information:

You are using Jupyter notebook.

The version of the notebook server is 4.0.6 and is running on:
Python 3.4.4 |Anaconda 2.3.0 (x86_64)| (default, Jan  9 2016, 17:30:09) 
[GCC 4.2.1 (Apple Inc. build 5577)]

Current Kernel Information:

Python 3.4.4 |Anaconda 2.3.0 (x86_64)| (default, Jan  9 2016, 17:30:09) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.
```

**Comment by Carreau** [comment]
is this **only** with the notebook ? Or can you reproduce using `jupyter qtconsole` or `jupyter console` ? Python stdout when using an IPython kernel  will be a ZMQ stream, but there is no reason for writing to normal stdout to segfault. 

Can you give a bit more info on the extension you are using ?

**Comment by hyliu1989** [comment]
Sorry i am currently busy. I will give more information next week. I have not had jupyter qtconsole and jupyter console installed yet.

**Comment by hyliu1989** [comment]
Hi Carreau, 
I try another function in scipy that prints also to the console, fmin_l_bfgs_b with display turned on (iprint=1). The same problem happened. And this time I use **jupyter-console**.

```
from  scipy.optimize import fmin_l_bfgs_b
import numpy as np

def foo(x):
    return x**2
def grad_foo(x):
    return 2*x

res = fmin_l_bfgs_b(func=foo, fprime=grad_foo, x0=np.array([0,0]), iprint=1)
```
result
```
In [7]: res = fmin_l_bfgs_b(func=foo, fprime=grad_foo, x0=np.array([0,0]), iprint=1)
kernel died, restart ([y]/n)? y
```

**Comment by takluyver** [comment]
I ran that example in Jupyter console and it completed successfully, with no segfault.

**Comment by minrk** [comment]
I ran it as well, and it succeeded. However, it looks like PySys_WriteStdout writes to `sys.__stdout__`, not `sys.stdout`, so the output will appear in the terminal, not in the notebook.

**Comment by JamiesHQ** [comment]
@hyliu1989 : We're doing a little housekeeping on our issue log and noticed this thread from 2016. Has this issue been resolved to your satisfaction and can it be closed? thanks!

**Comment by hyliu1989** [comment]
I think this is a computer architecture problem that is probably not controllable by the Jupyter project. 
I still don't know why writing to terminal would make the crash.

**Comment by JamiesHQ** [comment]
Ok, thanks @hyliu1989 ! I hope a fix materializes for you!
