### ISSUE TITLE
Dialogs not opening

### ISSUE THREAD

**Issue by laerus** [jupyter/notebook#1089]
Nothing happens when clicking on menu bar options like "Rename" "Search and Replace" "Keyboard Shortcut"

Debugger doesn't seem to print anything

tried on debian testing with python 3.5
with and w/o virtualenv

**Comment by takluyver** [comment]
When you say 'debugger', do you mean the browser Javascript console? If not, can you check that for any errors?

If you've recently updated, you may need to force refresh (Ctrl-F5) a few times to clear old JS out of the browser's cache.

**Comment by laerus** [comment]
yes firefox js console and also started jupyter-notebook with --debug option
when i press one of the options that have dialogs console doesn't output anything
but i get a lot of errors in js console when the notebook loads

[notebook-log.txt](https://github.com/jupyter/notebook/files/129956/notebook-log.txt)

**Comment by laerus** [comment]
apparently there was something wrong with firefox, i updated firefox and now it seems to work fine

**Comment by takluyver** [comment]
OK, I'm glad it's working now. How old a version were you on before?

**Comment by laerus** [comment]
its not long since i've switched to debian testing from stable, but it's been some weeks since the last time iceweasel got upgraded iirc, can't remember version though.
on a second thought the problem may have been on one of the plugins.
