### ISSUE TITLE
Long lines extend cells without horizontal scrolling

### ISSUE THREAD

**Issue by foebu** [jupyter/notebook#1093]
Hi,
I noticed with the new release that long lines extend the cell on the foreground (if this makes sense). Was this a wanted behaviour to write more readable code... or?
[This is what I mean.](http://imgur.com/o9E7dN0)

**Comment by takluyver** [comment]
IIRC this is a Chrome bug. I think there's a workaround in master.

**Comment by minrk** [comment]
Chrome has reintroduced this bug in a way that we don't have a workaround. This is already open as #1003, though.
