### ISSUE TITLE
Scratchpad

### ISSUE THREAD

**Issue by Phyks** [jupyter/notebook#1094]
Hi,

Very often, when editing (and debugging) my notebook, I change temporarily the value of a variable. It is not always a good solution to change it in a cell, as I often forget about the temporary change, and could forget to revert it back. My current solution is to have a "scratchpad section" at the end of the notebook, with cells that I only execute to tweak the value of a variable without altering it in its cell, which I expect to remain correct.

What about offering the ability to type some instruction live, in a scratchpad cell (that could be triggered by a shortcut and discarded after execution)?

**Comment by eronlloyd** [comment]
Do you wish to have a temporal code cell that is deleted, or are you instead looking for a better way to use inputs to control the code execution? Also, would it be better to instead be able to _hide_ the scratch pad when not in use, but retain its contents as code parameters?

**Comment by Phyks** [comment]
These are two different behaviours which can be discussed. Personnally, I would tend to think the best idea would be to have a "scratchpad" panel, with cells whose code would be retained. A bit like a notebook in a notebook. However, this could be much more difficult and complex to implement and maintain than just a splash input _à la_ "Alt+F2" (usual shortcut to call a launcher for apps in WM for instance).

**Comment by Carreau** [comment]
Interesting idea, I also though about ti a few time. I would expect getting the behavior right and the UI obvious to be harder than expected. That will likeley be more doable once the current Phosphor refactor is done.

**Comment by Phyks** [comment]
I have just found https://github.com/minrk/nbextension-scratchpad which is pretty new, but seems to do just what I wanted. Will give it a try.
