### ISSUE TITLE
Allowing variable references in Markdown cells

### ISSUE THREAD

**Issue by eronlloyd** [jupyter/notebook#1098]
Having access to kernel runtime variables to insert into markdown cells (or other non-code cells/widgets) would be an excellent enhancement for notebooks, particularly when including detailed narrative that describes the results of the code and research. Before posting this, I looked around and found references that lead back to [earlier discussions around this on the ipython repo](https://github.com/ipython/ipython/issues/2958), and it seemed like there was interest in getting this implemented.

I searched and didn't see anything already covering this in the jupyter/notebook issue list, so I felt I should raise it here as well, in case key issues like this have not also been migrated along with the code to the new repo. Please see [the original issue](https://github.com/ipython/ipython/issues/2958) for a great discussion on this matter, as well as some ideas and implementation estimates.

Since Jupyter now is focused on a more language-neutral approach, I'm sure that complicates the design, but having this functionality, even starting with just Python-based notebooks, would be an attractive addition. I'd like to help move this forward in any way that I can.

**Comment by cranmer** [comment]
+1

**Comment by fbob** [comment]
yep +1

**Comment by mrcinv** [comment]
+1

**Comment by tbittner** [comment]
+1

**Comment by icaromedeiros** [comment]
+1

**Comment by dannyeuu** [comment]
+1

**Comment by JamiesHQ** [comment]
@gnestor : Depending on the status of this issue, the associated [ipython issue](https://github.com/ipython/ipython/issues/2958) may be of interest to you. This is also marked with the "Dev Meeting" label - just in time!

**Comment by gnestor** [comment]
It looks like the ipython issue has more discussion so let's close this for now and move discussion there...
