### ISSUE TITLE
ggplot plots from one cell are shown in the next cells output area, but only on run all

### ISSUE THREAD

**Issue by janschulz** [jupyter/notebook#1099]
I've a notebook, which I can reliable trigger to show plots of one cell in the output area of the next cell. 

In this case it is a long ggplot + matplotlib call (in a loop for three plots) in cell 1 and a seabon call in cell 2 (again in a loop for 3 plots). Both plots (6 overall) are then shown in output area of the second cell.

I can only trigger this with `Run all` (e.g. not by two fast shift enter in these two cells). It also doesn't happen if the cells are reversed (first seaborn, then ggplot).

As the ggplot cell contains a `gg.draw()` and then manipulates the current figure, so I'm pretty sure that the proper matplotlib thingies are called to create a figure in that cell.

Is there any way to debug such things?

**Comment by JanSchulz** [comment]
The notebook is from conda: 
```
notebook                  4.1.0                    py34_0    defaults
```

, the kernel is:
```
C:\Users\jschulz
[sc] λ conda list |grep "ipython"
ipython                   4.0.0                    py27_1    defaults
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_3    defaults
ipython_genutils          0.1.0                    py27_0    defaults

C:\Users\jschulz
[sc] λ conda list |grep mat
matplotlib                1.5.1               np110py27_0    defaults
``` 

(the kernel runs in a different environment than the server...)

**Comment by minrk** [comment]
What matplotlib backend?

**Comment by JanSchulz** [comment]
`%matplotlib inline`

**Comment by minrk** [comment]
Do you have an example notebook? I'm guessing that ggplot is maybe not triggering the matplotlib draw calls that are expected and trigger automatic display.

**Comment by JanSchulz** [comment]
I've created this: https://gist.github.com/JanSchulz/6efa69d64e6bc63e770a

**Comment by minrk** [comment]
There have been a lot of changes in ggplot, so this may be fixed. I'm guessing it was a missing call to draw/show in ggplot itself. Can you reproduce this with ggplot 0.9.4?

**Comment by janschulz** [comment]
Unfortunately I have no ggplot installed anymore (neither the old version nor the new one). I'm closing, sorry...

**Comment by minrk** [comment]
No problem, feel free to reopen if you run into it again.
