### ISSUE TITLE
Jupyter notebook

### ISSUE THREAD

**Issue by anand0523** [jupyter/notebook#1101]
Hi All,

I want to install Jupyter Notebook on an Amazon EC2 instance and want to connect it to an Amazon EMR Spark cluster.
i.e. whenever i run any code on Jupyter notebook installed on EC2, the code should get executed on Amazon EMR Spark cluster and results should be returned back to the Jupyter notebook on EC2 machine.

Any help would be of great value.

Thanks,
Anand Agrawal

**Comment by eronlloyd** [comment]
Hello anand0523,

The best way to get assistance would be to post your message to jupyter@googlegroups.com or on stackoverflow.com. This here is for bug reports or improvement requests of the the product, not specific implementation help.

**Comment by Carreau** [comment]
You should have a look at the Jupyter [Spark Kernel](https://github.com/apache/incubator-toree) and ask the authors. Installing the notebook on EC2 should not be that hard. After you just need to set-up your kernel spec to spawn a spark cluster and run code on it. The park people will likely be much more aware on how to do that.

**Comment by Carreau** [comment]
(closing , feel free to keep asking question though and thanks for pitching in @eronlloyd )
