### ISSUE TITLE
Create a command line tool for troubleshooting installation

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#1103]
@takluyver @minrk @carreau If we don't already have it, it may be helpful to create a command line tool that the end user could run to check their installation and report the most important information that is typically needed to assist them. 

In addition or alternatively, a notebook that would display to the user all of the parameters that they currently have configured might be useful for them too as something that could visually display the settings. We have some of this in the Help menu but having it as a notebook might be helpful for the user in self debugging.

**Comment by blink1073** [comment]
Spyder has a "Help > Report Issue..." option that generates a new issue on Github and pre-fills it with the appropriate data.

https://github.com/spyder-ide/spyder/blob/5f4613d5f05e679b53e0a43468d3afa8fe14901f/spyderlib/app/spyder.py#L2327

**Comment by minrk** [comment]
that's a good idea! I'm not aware of such a thing. Things we are generally interested in:

- `PATH`
- `sys.path`
- `sys.executable`
- `sys.version`
- `python -m platform`
- `which -a jupyter`
- `pip list` (and/or `conda list`)

**Comment by takluyver** [comment]
`IPython.sys_info()` provides some of that information, but not all of it.

**Comment by willingc** [comment]
@Carreau Thanks for marking sprint friendly :) @blink1073 @minrk @takluyver Good comments all around. Didn't know that Spyder did that but might be a nice future addition to the Help menu. 

On a different but related note, do any of you know how to scrape or export all the Google Group messages? I would be interested in running some of it through nltk and/or using elasticsearch on the content.

**Comment by TomAugspurger** [comment]
If it's useful, pandas has [this script](https://github.com/pydata/pandas/blob/358da5663a68d9b03ac86ff2f50d57de309a8f65/pandas/util/print_versions.py), which is imported in the top-level namespace as `show_versions`.

**Comment by willingc** [comment]
@TomAugspurger Thanks for passing along the script :smile:

**Comment by nymoorland** [comment]
An even greater idea would be to improve user documentation( to make it more user-friendly and practical. ie. common install issues, trouble shooting. I could hardly find answers to these things in the docs when I recently upgraded or answers to other common other issues. @Carreau, do you have a doc writer or are the individual devs doing their own due to their technical knowledge? I would make a request to the appropriate person.

**Comment by takluyver** [comment]
We all pitch in on docs, but @willingc has been putting in some especially good work on them recently.

However, I still think a tool of some kind would be useful as well, as a way to report all the relevant factors for other people to help with troubleshooting.

**Comment by willingc** [comment]
@nymoorland We're always open to specific suggestions on improving user documentation. The developers have been writing the documentation. While I'm a developer, I really enjoy improving documentation since it benefits all of us. Please feel free to ping me or file a separate issue on documentation with as much detail as possible. Pull requests welcome too :-)

This issue is focused on providing a tool to help the end user troubleshoot installation/configuration and enable our developers to more easily assist end users.

**Comment by nymoorland** [comment]
Awesome, I think that data gathered from the tool will also help improve documentation.

**Comment by rmanly** [comment]
I think I'll work on this for JupyterDay Chicago.

Where would you want something like this to "live"? notebook/scripts/?

**Comment by takluyver** [comment]
I think all of the data it would collect is pretty general, not notebook specific, so I'd suggest starting with it as a completely separate piece of code - we could either package it up independently, or put it into something like jupyter_core.
