### ISSUE TITLE
[docs] Add instruction to install node with brew.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1105]
The [devdocs](https://jupyter-notebook.readthedocs.org/en/latest/development_js.html) give the command for APT. Brew is also a common way of installing node. 

This should be pretty easy for a new (mac os) contributor to add.

**Comment by willingc** [comment]
@carreau Good suggestion :+1:

**Comment by TheWitnesses** [comment]
Hey, I'm working on this.

**Comment by captainsafia** [comment]
Hey @TheWitnesses — Sorry I didn't get a chance to check in with you on this during JupyterDay. Let me know if you are still interested in working on it and I guide you through the process!

**Comment by TheWitnesses** [comment]
Hi Safia, 

I'd still be interested in working through the process. 

Have a good day, 
Zack Kerr 

----- Original Message -----

**Comment by captainsafia** [comment]
Closing because this was addressed in #1208.
