### ISSUE TITLE
Support for editing JSON files

### ISSUE THREAD

**Issue by maver1ck** [jupyter/notebook#1106]
Hi,
Right how, I'm unable to edit json file.
When I choose one from Files panel new window with plain text appears.

I'd like to have possibility to edit same like for txt files.

**Comment by takluyver** [comment]
In the URL, changes `/files/` to `/edit/` and it should work. Unfortunately there isn't a reliable way to know whether something is a text file - IIRC, we check for a `text/*` mimetype, but json is under `application/`.

**Comment by maver1ck** [comment]
Could you point me to code that have this logic ?

**Comment by takluyver** [comment]
https://github.com/jupyter/notebook/blob/620fb2919229d1c0b5e79087edcaaf95b770473b/notebook/static/tree/js/notebooklist.js#L632

**Comment by maver1ck** [comment]
We could just add 'application/json' to this line.
Is it good idea?

**Comment by takluyver** [comment]
We could, but that only solves the problem for that one specific mime type, and there are lots of others.

I think we talked at some point about adding an 'edit' button to the UI so you could try to edit any file.

**Comment by maver1ck** [comment]
Yep.
The same case is for application/xml

**Comment by takluyver** [comment]
Closing as we now have an 'edit' button in the UI, which should let you edit these files.
