### ISSUE TITLE
cannot "download as IPython notebook" a read-only notebook

### ISSUE THREAD

**Issue by adl** [jupyter/notebook#1112]
When I open a read-only ipython notebook I cannot download it as an ipynb file, even if it hasn't been modified.

Steps to reproduce:
  1. make some existing `*.ipynb` file readonly on your file system
  2. open it with jupyter notebook (the editor will flash "auto-save disabled" and show a small logo "this notebook is read-only")
  3. select   File > Download as > IPython notebook (*.ipynb) (this just opens a blank page, does not download anything, and shows no error on the console)

Context: I'm trying to setup a public Jupyter installation where users can test some of my tools.  In this installation I have some example notebooks that I have marked as read-only because I don't want them to be modified by mistake, but I'd still like them to be downloadable.

**Comment by takluyver** [comment]
I think it should work if you haven't modified the notebook. If the notebook has changed, we try to save it before downloading so that it gets the expected file.

**Comment by adl** [comment]
Could it be the case that a freshly loaded notebook is considered dirty until its first save?  If I step into the "download as IPython" callback using a js debugger, I can see that `that.notebook.dirty` is true, so a save is attempted.

**Comment by takluyver** [comment]
I don't think it should be, but maybe something in the frontend is modifying it just after load. @minrk @Carreau: any suggestions?

**Comment by willingc** [comment]
@takluyver I did a quick test and found the following:

1. chmod 444 existingnb.ipynb

2. Screen shot of UI correctly indicates on right the read-only file status:
<img width="1209" alt="screen shot 2016-02-19 at 9 23 01 am" src="https://cloud.githubusercontent.com/assets/2680980/13183223/aab478de-d6ea-11e5-9c2e-d861b8cc1958.png">

3. Tried to download the file using the menus where the options are active:
<img width="463" alt="screen shot 2016-02-19 at 9 23 11 am" src="https://cloud.githubusercontent.com/assets/2680980/13183255/d46feaaa-d6ea-11e5-950f-ab43942cc7dd.png">

4. If selected Download as ipynb, a blank tab opens with no output. Going back to the notebook there is an orange "This notebook is read only" indicator on the right side of the UI.

Unsure what desired behavior is, but this is what I'm seeing with the latest notebook version.

**Comment by willingc** [comment]
If trying to save using the left hand side button, the button triggers the Notebook is read-only indicator.
<img width="1212" alt="screen shot 2016-02-19 at 9 34 51 am" src="https://cloud.githubusercontent.com/assets/2680980/13183544/28ebbcca-d6ec-11e5-94af-24cbbe6ee6e7.png">

**Comment by takluyver** [comment]
That's expected when you explicitly try to save - read only means no saving.

When you try to download as ipynb, if anything has changed since the last save, it tries to save it before downloading. The issue here is seemingly that something changes as soon as you open it. Thinking about it, I realise that's probably the kernel info in notebook metadata, which is updated when the kernel starts.

**Comment by willingc** [comment]
@takluyver Sounds reasonable about the kernel info.

**Comment by adl** [comment]
@takluyver Dirty-on-load seems to be one issue (at least in the context of read-only files), but I see a second one: even if saving does fail for a good reason (e.g., we actually modified the notebook but the file is read-only), the "Download as IPython notebook" still creates a confusing blank window (because [that window](https://github.com/jupyter/notebook/blob/22761eeb15f314044a7572e6664b55ab02e176da/notebook/static/notebook/js/menubar.js#L121) is created before attempting to save).  If the blank window was not created in that case, it would be easier to see the "Notebook is read-only" warning appear as a response to download attempts.

**Comment by takluyver** [comment]
Yes, we should catch failure to save and close the window again.

(The obvious strategy is to open the window when you know save has completed, but unfortunately browser pop-up blockers don't allow us to do that)
