### ISSUE TITLE
Long title moves on save

### ISSUE THREAD

**Issue by jakirkham** [jupyter/notebook#1129]
Sadly I have some notebooks with long titles to keep track of what data they are working on and what I am trying to do with them. If the filename is very long, then I sometimes see this minor UI annoyance on saves where the title moves. Depending on the title length, this behavior can become time dependent on the time of the last save. One thought might be to move the location of language icon so the title can't run into its space. Though there are plenty of other reasonable ideas. Sorry to trouble with such a minor issue.

![long_notebook_name](https://cloud.githubusercontent.com/assets/3019665/13226424/538ae47c-d95f-11e5-8a2c-4fde879d7a64.gif)

**Comment by JamiesHQ** [comment]
cc: @gnestor

**Comment by gnestor** [comment]
I just submitted a PR that should fix this: https://github.com/jupyter/notebook/issues/2448

It enforces a `max-width: 100%` and uses `display: flex` on the save_widget container and uses a `text-overflow: ellipsis` to clip the title if it overflows.
