### ISSUE TITLE
Windows PDF export bug

### ISSUE THREAD

**Issue by palewire** [jupyter/notebook#1131]
nbconvert is failing with an "environment can only contain strings" on a Windows 8 machine I've tried to configure. I've seen similar bugs reported on other python libraries [here](https://github.com/nvie/pip-tools/issues/209) and [here](https://github.com/mitsuhiko/werkzeug/issues/467).

**Comment by takluyver** [comment]
Fixed by jupyter/nbconvert#165, fix will be in nbconvert 4.2 when it's released.

**Comment by palewire** [comment]
Thank you! Is there a way to upgrade now and now wait?

**Comment by takluyver** [comment]
If you're comfortable dealing with this stuff, you can run from the development version of nbconvert:
https://github.com/jupyter/nbconvert

**Comment by palewire** [comment]
I installed it from the source and now I'm getting a new error. I click the export to PDF button, it opens a new Windows tab, and it just hangs and hangs and hangs. Here are the last things in the command-line log.

```bash
[I 13:56:40.776 NotebookApp] Saving file at /Untitled.ipynb
[I 13:56:41.230 NotebookApp] Writing 13874 bytes to notebook.tex
[I 13:56:41.230 NotebookApp] Building PDF
[I 13:56:41.237 NotebookApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
```

**Comment by etiennedm** [comment]
How long did you wait? The dev version is working for me, although it does take 20 seconds to generate the pdf file.

**Comment by jdeboer** [comment]
Thank you, installing the latest dev version of nbconvert worked for me. It took a few minutes for me to generate the PDF.
