### ISSUE TITLE
setup js does not reliably install webpack

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#1137]
Webpack was recently added as a development dependency, but when I went to run `setup js`, it did not get installed.

Looking at `setupbase.py`, it appears that it only considers running `npm install` if it's also going to run bower. I suspect this is wrong, but I don't know how these pieces fit together.

**Comment by minrk** [comment]
Should be fixed by #1139, removing the conditional logic for running npm/bower. It's not worth saving 1-2 seconds that npm/bower no-ops take. I think this used to take longer and/or require a network connection.
