### ISSUE TITLE
Untrusted notebook user experience

### ISSUE THREAD

**Issue by Phyks** [jupyter/notebook#1146]
Hi,

I got some issues with `%matplotlib notebook` which was discarding my figures when reloading the notebook, and replacing them with `<IPython.core.display.Javascript object>`. I could not figure out why, and I discovered it was due to the fact that my notebook was not trusted.

Maybe it could be a good idea to add a big warning bar on top of the notebook if running in untrusted mode, stating something like "this notebook runs in untrusted mode, some features will be disabled.", and it could improve user experience a lot.

Thanks

**Comment by Phyks** [comment]
I am having a quick look at it and think I can make a PR to handle it, if it can be useful.

I am wondering what is the best implementation:
* Either to check for the `trusted` status of the notebook, and display a banner on top of the page, as described initially in this issue.
* Or handle it at the `OutputArea` level (https://github.com/jupyter/notebook/blob/932f85c7593b2eada7a2095bd1f30d3f6ea48115/notebook/static/notebook/js/outputarea.js#L558) and append a banner in sanitized output areas.

What do you think?

**Comment by minrk** [comment]
If you would like to mock up an example of a better UI for untrusted output, that would be great! My first inclination would be the single global indicator, not per-output.

cc @ellisonbg @cameronoelsen

**Comment by juhasch** [comment]
I added a trusted/not trusted indicator (checkmark or cross) for notebooks in the [python-markdown](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/python-markdown) extension:
![](https://raw.githubusercontent.com/ipython-contrib/IPython-notebook-extensions/master/nbextensions/usability/python-markdown/trusted.png)

Not saying it should be done like this, but it might give an idea how it could looke like.

**Comment by Phyks** [comment]
:+1: This looks like the perfect thing to do for me. @juhasch Maybe you want to handle a PR yourself? or want me to extract it from your extension?

**Comment by juhasch** [comment]
You are welcome to strip out the indicator an make a PR for the notebook.

**Comment by Phyks** [comment]
UI is far from perfect, but I started a PR at https://github.com/jupyter/notebook/pull/1293.

I think we can discuss there of UI improvements. Thanks!

**Comment by gnestor** [comment]
Merged https://github.com/jupyter/notebook/pull/1658#issuecomment-237954619

Thanks @Phyks for your contribution.
