### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by arvindgupta29** [jupyter/notebook#1148]
I have just started learning Python using http://openedx.seas.gwu.edu/courses/GW/MAE6286/2014_fall/about which recommends using Anaconda, and jupyter notebook as the editor. I have installed Anaconda but it fails to launch jupyter notebook on the browser. I tried enabling the Windows feature IIS but it doesn't work still. Kindly help.
I use Windows 7. Here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/17402494/13349599/019781e4-dca1-11e5-9ac9-ec85a90ce1c8.png)

**Comment by takluyver** [comment]
Can you try replacing `localhost` in the URL with `127.0.0.1`?

**Comment by arvindgupta29** [comment]
Thanks for your reply. I did the same, it works now. Just one issue, it
doesn't work on chrome. I am using notebook on Firefox.


Thanks.
Arvind

**Comment by takluyver** [comment]
When you say it doesn't work on Chrome, are you seeing the same issue, or is it not working in a different way?

Do you have a proxy server configured? If so, you should configure it not to use the proxy for localhost or 127.0.0.1. Here are the settings in Firefox:

![screenshot from 2016-02-27 09-34-40](https://cloud.githubusercontent.com/assets/327925/13372276/6fa10900-dd35-11e5-88db-c5c5d80aa812.png)

I think Chrome might use the system proxy config.

**Comment by arvindgupta29** [comment]
Thanks a lot. :) It works everywhere now.

**Comment by takluyver** [comment]
Great!
