### ISSUE TITLE
[CLI] --generate-config option doesn't work

### ISSUE THREAD

**Issue by benjaminabel** [jupyter/notebook#115]
When using the master branch with python 3.4 in ubuntu 14.04, `jupyter notebook --generate-config` doesn't seems to do anything except running the notebook.

**Comment by minrk** [comment]
With my time machine, this is fixed by #114.

**Comment by benjaminabel** [comment]
Thanks I'll test this tomorrow.

**Comment by benjaminabel** [comment]
Thanks. Now it works. the config file is generated in `~/.jupyter/jupyter_notebook_config.py`.
