### ISSUE TITLE
Running program in background

### ISSUE THREAD

**Issue by gracehllee** [jupyter/notebook#1152]
I am using magic command %run file in cell.
When it running, no other cell can be run.
in Jupyter notebook, any command run the file in background ?

**Comment by takluyver** [comment]
IPython doesn't have any way to do that directly, but if it's a separate file and you don't want to access its variables inside IPython, you can run it in a subprocess using Python's normal subprocess functionality. And if you do want it to be in the same process, you can run a thread (with the `threading` library), being careful about anything that is shared between threads.

**Comment by gracehllee** [comment]
In system, I run "./file &", then "tail log" .
is it possible in jupiter notebook, "%run file" in cell, and "!tail log" in next cell ?

**Comment by takluyver** [comment]
Not using `%run`. You can run it using the subprocess module, in which case it won't block execution.

**Comment by gracehllee** [comment]
Thanks @takluyver , you help me figure out an useful way.
The subprocess module solve my problems.
Thanks a lot~~

Grace Lee

**Comment by takluyver** [comment]
Great, I'm glad that worked for you.
