### ISSUE TITLE
"Close and Halt" not closing the page in master

### ISSUE THREAD

**Issue by fperez** [jupyter/notebook#1159]
On current master (216793eb), "close and halt" doesn't close the tab, it only kills the kernel.  I'm pretty sure this is a recent regression, though I haven't bisected it.

**Comment by takluyver** [comment]
Works for me in both Firefox and Chrome.

**Comment by minrk** [comment]
```javascript
if (user === 'fperez') {
    all_the_buggs.trigger();
}
```

@fperez does it make a difference if you save immediately before hitting it?

**Comment by fperez** [comment]
No kidding!!!

But yes, it does make a difference: if I save and close/halt immediately, it works (i.e. kernel killed and tab closed). If I try to close/halt a long-open nb, it kills the kernel but doesn't close the tab.

**Comment by minrk** [comment]
That suggests it's to do with the dirty flag, which, when set, should show you a dialog to confirm navigation away from the page. Do you see any dialog when you hit close & halt? If not, when you make some changes and close immediately, does it let you, or does it prompt that you are going to lose unsaved changes?

**Comment by fperez** [comment]
If I have unsaved changes it does prompt me. The only misbehavior I'm seeing is the failure to close the browser tab after the kernel shuts down.

**Comment by minrk** [comment]
Can you check browser(s) version(s) where this happens?

Just to reiterate: you do get the confirmation dialog, click "Leave this page", and then you stay on the page? That dialog is provided by `window.onbeforeunload`, which I *thought* meant we weren't even allowed to keep you on the page if we wanted to.

**Comment by fperez** [comment]
It's tricky to replicate, b/c it seems to only happen with notebooks that have been left open for a while, so they've been checkpointed already.

1. If I have recent changes, then the 'do you want to save' dialog does pop up, and if I say "leave", I do go away as you describe.

1. If I've saved manually, then the close happens as expected.

But I've seen multiple instances (so far on Chrome) where I'm left with a kernel-less but open notebook...

Anyway, if it's an "fperez special", let's ignore it for now. I'll keep trying to find the conditions to trigger it...

**Comment by minrk** [comment]
Is there any chance you have accidentally clicked "Stay on this Page" instead of "Leave this Page"? Because that's exactly what would happen: kernel is shutdown, but page close aborted, so you have a page open with no kernel.

**Comment by fperez** [comment]
No, it happened multiple times, without the dialog coming out in those
cases. It simply shut down the kernel and stayed on the page.

**Comment by minrk** [comment]
If there's no dialog, then it's something else. We shutdown the session and hook up the close-window function as both a success and failure callback, so it must not be getting to that point. I'm not sure how that could happen, though, without the server hanging and never responding.

**Comment by fperez** [comment]
This seems weird enough, and enough of a corner case, that I think it's OK if we just leave it for now, and try to debug it in-person when you guys visit. Let's not worry about it for now...

**Comment by fperez** [comment]
And thanks for all the efforts!
