### ISSUE TITLE
Output Prompts

### ISSUE THREAD

**Issue by blink1073** [jupyter/notebook#1162]
In the current notebook (running from master), it appears as if there is no consistency in whether output prompts are shown (see screen shot below).  I believe this should be all-or-none, and would vote for "all" to coincide with the Jupyter console behavior.

<img width="417" alt="screen shot 2016-03-02 at 3 33 36 pm" src="https://cloud.githubusercontent.com/assets/2096628/13476301/cdcfd93e-e08c-11e5-931d-656396c72584.png">

**Comment by blink1073** [comment]
Ah, I see the distinction now, only when an actual execution result is returned do we get a prompt, both for the console and the notebook.

<img width="417" alt="screen shot 2016-03-02 at 3 33 36 pm" src="https://cloud.githubusercontent.com/assets/2096628/13476508/cbb50b00-e08d-11e5-85c5-2f80ca103f1f.png">

**Comment by takluyver** [comment]
Yep, you've got it. Note that in the IPython kernel, you can also use `Out[3]` to access a previous result.

**Comment by blink1073** [comment]
Yeah, it made sense in hindsight ;)
