### ISSUE TITLE
Copy/paste multiple cells between notebooks

### ISSUE THREAD

**Issue by leventbayindir** [jupyter/notebook#1163]
As far as I see it is not possible to copy/paste cells between different notebooks.

This can be a very time saving feature for someone who needs to edit multiple notebooks at the same time (e.g. creating new notebooks from existing ones). 

As an example, I am using Jupyter as a lecturer. When I restructure course materials (notebooks), I have to recreate cells for the new notebook(s) even if those cells are already in my existing notebooks.

**Comment by psychemedia** [comment]
I've a couple of hacks for generating or updating bits of one notebook using another:

  - [creating subnotebooks from a single monolithic notebook](https://blog.ouseful.info/2015/08/21/authoring-multiple-docs-from-a-single-ipython-notebook/)
  - [inserting 'canned' feedback from one notebook into another](https://gist.github.com/psychemedia/06c265e0a173a260a13d231d3275d6de).

They're both a bit crude, particularly the canned feedback includer. But they're something to talk around..

**Comment by takluyver** [comment]
In master, it is now possible to copy and paste cells between notebooks in Chrome and Firefox.

**Comment by lucaventurini** [comment]
@takluyver is this feature in the latest release?

**Comment by takluyver** [comment]
I don't think so, unfortunately. I've marked this issue for 4.3 in the hope that someone will have a look at it, but I don't know what the plans are for releasing the next versions.

**Comment by Carreau** [comment]
This works for me on master/chrome/os-x, so I'm going to close this. 

We have someone working on pushing notebook 4.3 out, so I hope to have the release in a month-ish. 

Closing as this will be in 4.3.

**Comment by gyermolenko** [comment]
Can someone tell how to copy cell from one notebook to another?
I couldn't do that ..

**Comment by uweschmitt** [comment]
does not seem to work for the development version from github !?

**Comment by takluyver** [comment]
Have you definitely got the development version installed, including rebuilding the js (which requires npm)? Have you cleared your browser cache? What browser are you using? Do you see anything on the page or in the JS console when you try to copy and paste?

Note that both the to- and from- notebooks need to be running with the development version for copying and pasting between them to work.

**Comment by madanh** [comment]
Does not work for me in 4.3 on firefox. Nothing on Ctrl+C in JS console.

**Comment by dpsanders** [comment]
Doesn't seem to be working in 4.3 on Chrome on MacOS.

**Comment by takluyver** [comment]
I don't think the clipboard code is in 4.3. We're hoping to do 5.0 before
too long...

**Comment by dpsanders** [comment]
It's not working on master either.

**Comment by takluyver** [comment]
It works on master here, although I noticed an issue where it doesn't work if the first cell you copy is empty.

You may be getting cached Javascript. There are various ways round this; one I like is to run the notebook server on a different port from normal (e.g. `--port 8931`).

**Comment by dpsanders** [comment]
Hmm, tried that but still no good apparently.

**Comment by takluyver** [comment]
Anything in the JS console when it fails? What browser are you using?

**Comment by dpsanders** [comment]
Chrome 55.0.2883.95 on MacOS 10.12

No JS error when it fails; the only JS error in the console is the following (not sure if related):
```

http://localhost:8888/nbextensions/nbpresent/js/nbpresent.deps.min.js.js Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:165 Uncaught Error: Script error for "nbpresent-deps"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:165)
    at HTMLScriptElement.onScriptError (require.js:1732)
makeError @ require.js:165
onScriptError @ require.js:1732
```

**Comment by takluyver** [comment]
Probably not related, but maybe some extension is interfering somehow. It's working for me on Firefox and Chromium.

**Comment by dpsanders** [comment]
Not working on Firefox either unfortunately (and with no error messages in the JS as far as I can tell). I'm not sure how to debug this.

**Comment by takluyver** [comment]
Is it possible you're trying the wrong thing to test it? You need to be in command mode and then use Ctrl-C/Ctrl-V to copy and paste (or Cmd- on a Mac, I guess).

**Comment by dpsanders** [comment]
Thanks for checking, but that is what I'm trying, yes.

**Comment by dpsanders** [comment]
Ah, no, I was indeed checking the wrong thing. I was doing `Ctrl-m v`, as I would in a single notebook. Apologies

**Comment by dpsanders** [comment]
It's *really* neat with `Cmd-c / cmd-v`!

**Comment by takluyver** [comment]
:-) Thanks!

It has to be the native copy/paste shortcuts for this, because that's the only way the browser gives us access to the system clipboard.

**Comment by dpsanders** [comment]
I see. I assumed there was some notebook internal state or whatever. I don't see that this is documented in the keyboard shortcuts though?

**Comment by takluyver** [comment]
I think the shortcuts help thing is generated from our own shortcuts registry. We don't register these shortcuts, because we have to let the browser catch them and turn them into clipboard events. Maybe there's some way we can put them in the shortcuts dialog without actually registering them.

@Carreau, that seems like something you'd know about?

**Comment by clstaudt** [comment]
Not working for me with notebook-4.3.1. This would be a really useful and basic feature for collaborative work - I'm surprised it is not there yet.

**Comment by Carreau** [comment]
> @Carreau, that seems like something you'd know about?

That's some things I have thought about.  We should first auto-register display all of codemirror shortcuts, but I haven't had the time to work on it. 

I would also **really** like the menu layout to be declarative to send some of that to native menu, but again, no time to work on it, and anyway we'll have to re discuss that with the people building JupyterLab.


> Not working for me with notebook-4.3.1. This would be a really useful and basic feature for collaborative work - I'm surprised it is not there yet.

There only so much we can do with all the project we maintain and the number of dev we have.
There are also limitation of browsers that don't always give you the choice. 

Help is always appreciated.

**Comment by takluyver** [comment]
> Not working for me with notebook-4.3.1. 

This feature is currently marked for 5.0 (see the milestone on the right), so we don't expect it to work in any 4.x release.

**Comment by edoardovivo** [comment]
Hello, 
I also cannot copy/paste cells from different notebooks. Here is my "pip list | grep jupyter":
```
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-contrib-core (0.3.0)
jupyter-contrib-nbextensions (0.2.1)
jupyter-core (4.2.1)
jupyter-nbextensions-configurator (0.2.2)
```
I'm working on Chrome and the machine OS is a CentOS 7.
The copy/paste is not working either with CTRL+C/CTRL-V or with the "copy/paste cells" from the edit menu.

Any help is kindly appreciated. Thanks!

**Comment by takluyver** [comment]
The relevant package is just called `notebook`.

**Comment by edoardovivo** [comment]
Thanks for the heads up. The notebook package is version 4.3.1 and it's the latest.
Is it supposed to work?

**Comment by takluyver** [comment]
No, sorry, the feature is currently slated for 5.0. We'll try to get that out before too long.

**Comment by ggrrll** [comment]
So @takluyver, as you wrote before,   is it still for firefox/chrome?
(is it normal that it doesn't work in safari? )

(I am on `Version: 5.0.0b1` )

**Comment by takluyver** [comment]
It still appears to be working for me on Firefox. I've no idea about Safari; I don't use a Mac, so I can't test that.

The preact thing is a bit concerning, but I don't think it's related to this. Can you file a separate issue about it?

**Comment by ggrrll** [comment]
ok - I does work fine indeed on Firefox, also for me

**Comment by esiabri** [comment]
not working on the notebook 5.0.0, is it added?

**Comment by cjw296** [comment]
Hmmm, copy and paste multiple cells isn't working for me with notebook 5.0.0.
What am I likely to be doing wrong?

```
$ conda env export | grep notebook
- ipython-notebook=4.0.4=py27_0
- notebook=5.0.0=py27_0

$ conda env export | grep jupyt
- jupyter=1.0.0=py27_3
- jupyter_client=4.2.2=py27_0
- jupyter_console=5.2.0=py27_0
- jupyter_core=4.1.0=py27_0
  - jupyter-client==4.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.1.0
```

**Comment by cjw296** [comment]
Ah, right, the *one* thing I didn't try was the keyboard shortcuts... Will try this evening, but that's quite an odd restriction. Chatting to a front end person here, the suggestion was to go through the server to make this work properly. Having it *only* work with keyboard shortcuts is pretty poor UX...

**Comment by takluyver** [comment]
We know it's poor UX, but we have to live with what's possible from a browser. The only way around it is to rely on Flash, which is not a road we want to go down (but someone could make an extension if they want).

I think doing it through the server would be even more confusing, given that the server might be on a different machine.

**Comment by cjw296** [comment]
I think doing it through the server would be the least confusing thing for me as an end user.

However, the front end dev in question, @romgain, also pointed me to this, which suggests it's all possible on the client side:

https://stackoverflow.com/questions/2236828/javascript-communication-between-tabs-windows-with-same-origin/12514384#12514384

**Comment by takluyver** [comment]
We want it to be possible to copy and paste between different servers (for which doing it server side wouldn't work) and between different browsers (for which localstorage wouldn't work; it probably also doesn't work to & from private windows).

**Comment by takluyver** [comment]
Also, I now recall that localstorage also wouldn't work between different servers, because it's separated by domain.

**Comment by cjw296** [comment]
I'm afraid the choice to cater for c'n'p between servers has compromised the UX to the point where I wonder if this was worth the hassle to implement? Should I open a new issue for better UX in the case of c'n'p between notebooks from the same server? (which is all I've ever wanted...)

**Comment by louis925** [comment]
I don't understand why Jupyter notebook have to invent their own copy past for the cells at the beginning? Why not just use the system clipboard to copy and paste cells? It is also really unnecessary to distinguish between command mode and edit mode. You don't have this kind of issue when using any other software like Word, Mathematica, ....

**Comment by Carreau** [comment]
> This copy and paste isn't really working.. It only copy the code but not the cell structure.
> I don't understand why Jupyter notebook have to invent their own copy past for the cells at the beginning? Why not just use the system clipboard to copy and paste cells? It is also really unnecessary to distinguish between command mode and edit mode. You don't have this kind of issue when using any other software like Word, Mathematica, ....

Thanks for the question and the comments. 

You have to understand that one of the limitation of Jupyter notebook is that it runs within a browser, thus there are limitation:
  - Not complete API to do copy past. 
  - Some shortcuts that can't be take (for example we can't intercept Ctrl-W to close tab. ...etc.
We thus have to make compromises. Hopefully the web api and browser implementation eveolve so we can push thing further with time. 

You will be happy to learn that since this issue was opened, new copy-past API have been developed and that – if you are on a system that have these APIs – you should be able use regular copy past, and there are even newer API that should make things works better – you are welcome to send PRs to use them.
Now for other users, we do have to provide solutions.

For the edit-command mode, let's put aside the fact that a lot of people like it and are efficient with it we have a coule of data points and historical references:
  -  initial versions of Jupyter (when it was till IPython) used to not have a non modal system, it was way clunkier than what we have now.
  - We are cornered by the limitation of the web API to get keyboard shortcuts. My guess is that it's not the modality that bother you, but that you actually need to be in command mode for most.
  - Many interfaces are modal, you just don't realize it, like while writing this, if I press Ctrl-F and type thing it's suddenly not writing in this text area.


Now, most of what I've said above has already been said earlier in the thread, and there are [other frontends](https://nteract.io/) with different restrictions, and this is an open-source software, provided for free. You are welcome to contribute to it. If you can do better, than that would improve your workflow as well as other peoples ! That would be a win-win situation !

**Comment by ackalker** [comment]
Thanks to all for the very helpful comments above, and lucky me for searching the issue tracker to find out that c'n'p between notebooks is really possible.
May I ask you, with some urgency, to include this feature prominently in the relevant documentation? It is very important to those of us who regularly need to copy large chunks of complicated code between notebooks. Yes I know that it is possible to use `%load file.py` magic to include pieces of Python code, but sometimes we need to copy chunks of preformatted text, formulas, etc. as well. Thanks in advance!

**Comment by matanster** [comment]
So in summary, I believe the supported flow is:
select cells, copy, then paste in the target notebook (not using the notebook's edit menu but the keyboard)

**Comment by richdevboston** [comment]
Matanster's comment is correct.  It just needs to work as expected for selected groups of cells for the most common Windows, Mac and Linux keyboard shortcuts (e.g., Copy = Control-C, Paste = Control-V on Windows).  

The rest of the discussion is nice-to-know narrative.  We need to get it working as expected!!

All the other odd-ball keyboard shortcuts across Win, Mac, Linux OSes don't matter as much. Let the wiz-bang geeks create their own private keyboard shortcuts, but make the standard-installation defaults work as expected for copy and paste.

**Comment by AkhilPenta** [comment]
This feature has been introduced in [Jupyter Notebook 5.0](https://jupyter-notebook.readthedocs.io/en/latest/changelog.html#other-additions). 
Use pip install notebook --upgrade to upgrade to the latest release.

Note that the old shortcuts C, V and X work only for copying and pasting inside one notebook. In order to do it across tabs, you should use Ctrl-C and Ctrl-V (Cmd-C and Cmd-V on Mac).

**Comment by myidealab** [comment]
Not working in Firefox based on the current config:

Windows 10.0.14393 
Firefox 70.0.1 (64-bit)

jupyter core     : 4.5.0
jupyter-notebook : 5.7.8
qtconsole        : 4.4.3
ipython          : 7.7.0
ipykernel        : 5.1.2
jupyter client   : 5.3.1
jupyter lab      : 1.0.2
nbconvert        : 5.5.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.2
