### ISSUE TITLE
Trouble switching between (Python) kernels in docker images

### ISSUE THREAD

**Issue by jakirkham** [jupyter/notebook#1166]
If I create a Python 2 notebook and then change kernels to Python 3, it seems the Python 3 kernel never starts. Attempts to restart the kernel fail (possibly due to still holding information to the old kernel). This will still happen if I go the other direction (Python 3 to Python 2) and it may affect other kernel transitions. Closing and reopening the notebook will properly restarts the newly selected kernel. Looking in the log will show something like this. Video below.

```
[I 18:19:15.469 NotebookApp] Kernel started: a38e083b-df30-4f26-992f-3d57187a43b3
[I 18:19:30.916 NotebookApp] Kernel shutdown: a38e083b-df30-4f26-992f-3d57187a43b3
[I 18:19:30.985 NotebookApp] Kernel started: 4f4fbc3d-cf22-4bd5-a321-0f7d1e513adb
[E 18:20:34.759 NotebookApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/notebook/services/kernels/handlers.py", line 88, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/opt/conda/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 109, in restart_kernel
        self._check_kernel_id(kernel_id)
      File "/opt/conda/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 169, in _check_kernel_id
        raise web.HTTPError(404, u'Kernel does not exist: %s' % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: a38e083b-df30-4f26-992f-3d57187a43b3)
```

![notebook_kernel_switch_issue](https://cloud.githubusercontent.com/assets/3019665/13505500/70d6ba16-e147-11e5-85ec-8b2c2002f854.gif)

**Comment by minrk** [comment]
Do you see anything in the terminal while you are waiting?

**Comment by minrk** [comment]
Duh, it's right there. Reading again and rethinking...

**Comment by minrk** [comment]
The log suggests to me that the Restarter is not actually being stopped as part of the shutdown sequence, so it's triggering a restart of the kernel that has been removed, causing a bit of confusion. What is `conda list` for the notebook repo?

And double-checking: Both Python 2 and Python 3 kernels are working, as long as the page starts that way?

**Comment by jakirkham** [comment]
No worries. Was thinking I might have done a bad job structuring the issue. The image is a bit distracting from some of the content.

Ah, so this was done with the recent version of the `jupyter/datascience-notebook` docker image. I suppose there is a valid question as to whether there isn't something weird going on with docker here, but the log made me think that was not the case. Though I suppose it is worth rechecking.

Yes, both kernels work as long as the notebook was started with that kernel whether it be Python 2 or Python 3.

**Comment by jakirkham** [comment]
So, I went back and checked to see if I could reproduce this outside of a docker container and I am not able to. Though I don't think it is specific to the `jupyter/datascience-notebook` docker image as I created my own docker image with jupyter and two kernels and ran into a similar issue.

**Comment by minrk** [comment]
I can't think of a way for docker to be interfering, but that's useful info. Do you see any differences in `conda list` between the two contexts? My intuition suggests that this should be a more straightforward bug, either in the notebook or juptyer_client code.

**Comment by jakirkham** [comment]
So, there were a couple of things that were out of date in `jupyter/datascience-notebook` that seemed relevant. Namely, `ipython`, `ipykernel`, and (maybe not directly relevant) `openssl`. I created a new docker image with these things updated, but it yielded the same problem.

**Comment by jakirkham** [comment]
Sorry, I should have brought this to your attention ages ago, @parente.

**Comment by parente** [comment]
I can't reproduce on our tmpnb site here http://jupyter.cloudet.xyz/ which is using the image + tag doc'ed here: https://github.com/jupyter-incubator/dashboards_setup/blob/master/tmpnb_deploy/Dockerfile#L4

What tag are you using @jakirkham ?

**Comment by jakirkham** [comment]
Sorry, not sure what caused this. That being said, it does seem to be fixed using a recent version of the notebook.
