### ISSUE TITLE
Test failure in tests/notebook/roundtrip.js

### ISSUE THREAD

**Issue by jakirkham** [jupyter/notebook#1173]
Output from test failure:

```
In /home/travis/build/jakirkham/notebook/notebook/tests/notebook/roundtrip.js:51

  Untitled suite in /home/travis/build/jakirkham/notebook/notebook/tests/notebook/roundtrip.js

    assert: undefinedCell 0 has no output #0 (0 total)

______________________________________________________________________

Test suite completed for system with the following information:

Python version: 3.5.1 (default, Dec 17 2015, 01:11:06) [GCC 4.6.3]

sys.executable: /home/travis/virtualenv/python3.5.1/bin/python

Platform      : Linux-3.13.0-40-generic-x86_64-with-debian-wheezy-sid

Tools and libraries available at test time:

   casperjs phantomjs

Tools and libraries NOT available at test time:

   slimerjs

Status: ERROR - 1 out of 1 test groups failed (notebook). Took 274.595s.

You may wish to rerun these, with:

  python -m notebook.jstest notebook
```

Here is the failure as shown in Travis CI. ( https://travis-ci.org/jakirkham/notebook/jobs/113720967#L1523-L1546 )

**Comment by Carreau** [comment]
That seem like a random failure, rerun the specifc item in the build matrix that failed by clicking the rerun button in the travis interface.

**Comment by jakirkham** [comment]
That may be. Figured I should share it anyways in case there was something more to it.

**Comment by Carreau** [comment]
> That may be. Figured I should share it anyways in case there was something more to it.

Sure, things like that happen regularly on pull requests and on the master branch, the Travis build can also Timeout for a reason we have not determined yet.  When this is the case we often just Kick the build to restart to be sure. If you figure out why that would be great, but it seem like the restarting every now and then is less annoying that spending a week to try to figure out why it does that.

Anyway, It's not like computer are perfectly deterministic machines than only execute instruction they are given in order and without room for interpretation. They have a life on their own, and act depending on their mood.
