### ISSUE TITLE
Import error for module unicodecsv in ipython notebook

### ISSUE THREAD

**Issue by sreesindhusruthiyadavalli** [jupyter/notebook#1174]
Hi,

import unicodecsv throws import error while running in ipython canopy.

**Comment by takluyver** [comment]
This is unlikely to be a notebook issue. It probably means it's failing to find the module for some reason. Maybe it's not installed, or you're running in a different Python installation to the one it is installed in. Check `sys.executable` to see which Python you're in, and `sys.path` to see where it looks for modules.
