### ISSUE TITLE
Is it possible that notebook autosave the output when the page closed?

### ISSUE THREAD

**Issue by Lmaths** [jupyter/notebook#1177]
Before a program which will consume a lot of time and print some information along with time finished, I closed the jupyter notebook page.  And the kernel is still running.  But the ouput of the program not autosaved when I open the page again. I can't get any information of the output even the output generated before I closed the page.

**Comment by minrk** [comment]
Not at this point, no. Currently, 100% of document authoring happens in the browser, and the server is just ferrying messages back and forth between the kernel and the browser. We do plan to move awareness of open documents and document state to the server-side as part of real-time collaboration. One aspect of this will be documents getting output when the browser is not running.
