### ISSUE TITLE
Silent death of IPython Kernel?

### ISSUE THREAD

**Issue by eryshev** [jupyter/notebook#1178]
I launch my **Jupyter 4.0.6** on **Windows 10 x32** system and when I try to execute a following piece of code 

    %matplotlib inline
    import numpy as np
    X=np.linspace(0,np.pi,5)
    import matplotlib.pyplot as plt
    plt.plot(X,np.sin(X))`

my **IPython Kernel 4.1.2** dies silently without any error message.
Jupyter and **Python 3.5.1** were installed via **Anaconda 2.5.0** so my conda list is in attachements.
[conda-list.txt](https://github.com/jupyter/notebook/files/160585/conda-list.txt)
My Jupyter Kernel Spec:

    Available kernels:
      python3    C:\Anaconda3\lib\site-packages\ipykernel\resources

For debug it firstly I tried to use `%xmode Plain` and secondly I ran my IPython kernel separetly with --debug and I attached jupyter in mode qtconsole with --existing option and despite all of that I still don't know why my kernel dies.
So is there a way to have more useful error message? 
Or somebody could help me to fix it?

**Comment by takluyver** [comment]
You say it died silently: what did you see or not see that makes you believe its dead? Do you get the 'dead kernel' dialog in the notebook? Does it hang?

Can you break that cell up and see which line kills it?

My guess would be that it's some sort of bug or incompatibility with matplotlib/numpy/python that's causing an error. IPython itself normally can't cause silent crashes.

**Comment by eryshev** [comment]
I see the dialog 'kernel is dead and will be restarted automaticly' and it restarts successfully. 
I figured out that it dies at the last line plt.plot(X,np.sin(X)). 
If i skip evaluation of the magic `%matplotlib inline` then plotting will return something as [<matplotlib.lines.Line2D at 0x7f779a07fe48>] and kernel don't die.
Thx.

**Comment by takluyver** [comment]
Hmm, odd. Plenty of people do plotting much like that without any problems. @tacaswell, any ideas?

**Comment by tacaswell** [comment]
I suspect that this is the same issue as https://github.com/matplotlib/matplotlib/issues/6075

**Comment by willingc** [comment]
@minrk @takluyver I wonder if the recent change this weekend to Jupyter client and timeouts might be related to this, and is perhaps solved by updating.

**Comment by eryshev** [comment]
If it could be solved by updating it's nice but i still don't know how can I obtain additional debug information in cases like that:)
P.S. As i can find latest version in conda repo is 4.0.6 and it was uploaded 1 month ago.

**Comment by takluyver** [comment]
@tacaswell it doesn't sound the same: that's closing figures after a delay when using the notebook backend on OS X. This is killing the kernel instantly using the inline backend on Windows. Maybe there's some common underlying cause, but it's pretty well hidden if so!

@eryshev Just to check, there's no relevant output in the terminal where you started it, right? If not, I think you've done everything you can do to get debug information for something like this, and it's just a weird bug.

**Comment by tacaswell** [comment]
Gah, sorry for not reading carefully enough...

**Comment by eryshev** [comment]
@takluyver No, there's not any relevant output in the terminal, neither with standart or debug level of logging.

**Comment by Donal-Flanagan** [comment]
I'm having the exact same problem but on Ubuntu 15.10. Did you ever figure out what's happening?

**Comment by Donal-Flanagan** [comment]
Update: The bug occurs when I run Jupyter notebook from vagrant but not when I run it on my normal system. My assumption would be that X-forwarding is not enabled so the vagrant can't access my screen to render the image, I might be totally off base though.

**Comment by takluyver** [comment]
Are you using `%matplotlib inline`? If you haven't already, try running that in a separate cell before plotting. Inline plots (or nbagg plots from `%matplotlib notebook`) shouldn't do anything that involves X.

**Comment by Donal-Flanagan** [comment]
Yes, that fixed it. Thanks very much.

**Comment by doomsplayer** [comment]
Works for me, Thanks!

**Comment by willingc** [comment]
**Resolution** 

> Are you using %matplotlib inline? If you haven't already, try running that in a separate cell before plotting.

**Comment by che769776082** [comment]
I think you need to add 'plt.show()' in the end!

**Comment by eryshev** [comment]
So far I have updated my Jupyter and it turns out my matplotlib "is not Win32 application". This is strange because it came with my 32x Anaconda but at least I have an error:)  I had to reinstall matplotlib from 32 bits wheel and it works!

**Comment by swapme** [comment]
> 

> 

> `dcdvv`
