### ISSUE TITLE
No syntax highlighting for the iTorch kernel in master branch

### ISSUE THREAD

**Issue by eulerreich** [jupyter/notebook#1179]
So under the master branch (d3ff8d69de4299a9aecbeac5e126d7af02df4e5f), python has syntax highlighting but the iTorch kernel doesn't. In the 4.1.0 release, both have syntax highlighting.

I'm guessing this is a jupyter issue, so I'm posting this here.

**Comment by bnaul** [comment]
I just came across the same problem with the IRKernel. For example, (https://github.com/IRkernel/IRkernel/blob/master/example-notebooks/Demo.ipynb)[this notebook] has highlighting in 4.2 (and here on GitHub) but not on master.

**Comment by minrk** [comment]
Merging into #1439 which has more info.
