### ISSUE TITLE
nicer default styling for tables

### ISSUE THREAD

**Issue by janschulz** [jupyter/notebook#1182]
Compared to what knitr produces for tables, the tables in the notebook look horrible:

e.g. pander tables in an R markdown document converted to html:
![2016-03-08_134713](https://cloud.githubusercontent.com/assets/890156/13602029/4d9c6186-e534-11e5-8b52-7fd01b8742c7.png)

compared to similar code (the notebook doesn't understand the pandoc markdown table syntax :-( and therefore the pandoc step to convert it to html) in the jupyter notebook:

![2016-03-08_135209](https://cloud.githubusercontent.com/assets/890156/13602117/fc0ce042-e534-11e5-9002-47acff1414ce.png)

I also tried to include bootstrap styling (which knitr used for html), but this does not seem to work, as it seems the default styling overwrites it(?):

``` R
library(pander)
library(dplyr)
library(broom)
library(IRdisplay)
panderOptions("table.split.table", 200)
nice_pander <- function(...){
    t = capture.output(pander(...))
    mdFile <- tempfile(fileext=".md")
    cat(paste(t, collapse="\n"), file=mdFile)
    htmlFile <- knitr::pandoc(input = mdFile, format = "html")
    t = readr::read_file(htmlFile)
    #print(t)
    display_html(paste(t, collapse="\n"))
   display_html("<link rel='stylesheet' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'>
<script src='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'></script>
<script>$('tr.header').parent('thead').parent('table').addClass('table table-condensed');</script>
")
}
df <- data.frame(a=0:20, 
                 b=factor((0:20) %% 2, levels=c(0,1), labels=c("a", "b")), 
                 c=factor((0:20) %% 3, levels=c(0,1,2), labels=c("x", "y", "z")))
nice_pander(df %>% group_by(c) %>% do(tidy(t.test(a~b, data = .))))
```

-> It would be nice if the notebook could change the default styling for tables to something nice :-)

**Comment by flying-sheep** [comment]
wait, which one looks horrible in your eyes?

the first one is really pretty, and the second one sucks imo.

**Comment by flying-sheep** [comment]
i came up with this, but it’s only a workaround. the fix is in above comment.

```r
display_html('<style>table.table, table.table tr, table.table td, table.table th {border: 0}</style>')
nice_pander <- function(...){
    t <- capture.output(pander::pander(...))
    mdFile <- tempfile(fileext = '.md')
    cat(paste(t, collapse='\n'), file=mdFile)
    htmlFile <- suppressMessages(knitr::pandoc(input = mdFile, format = 'html'))
    t <- readr::read_file(htmlFile)
    t <- gsub('<table>', '<table class="table table-condensed">', t)
    display_markdown(paste(t, collapse="\n"))
}
df <- data.frame(a = 0:20, 
                 b = factor((0:20) %% 2, levels = c(0,1),   labels = c("a", "b")), 
                 c = factor((0:20) %% 3, levels = c(0,1,2), labels = c("x", "y", "z")))
nice_pander(df %>% group_by(c) %>% do(tidy(t.test(a~b, data = .))))
```

**Comment by JanSchulz** [comment]
@flying-sheep Nice, thanks!

I now modified that to 

```
bootstrapify_tables <- function(){
    display_html('<style>table.table, table.table tr, table.table td, table.table th {border: 0}
table.table-nonfluid {width: auto !important;}</style>')
    display_html('<script>
bootstrapify = function(){
   // a table which was handled by pandoc
   $("tr.header").parent("thead").parent("table").addClass("table table-condensed table-nonfluid");
   // a markdown table as it appears in a markdown cell
   $("div.text_cell div.inner_cell div.rendered_html table").addClass("table table-condensed table-nonfluid");
};
$([IPython.events]).on("notebook_loaded.Notebook", bootstrapify);
$([IPython.events]).on("kernel_ready.Kernel", bootstrapify);
$([IPython.events]).on("output_appended.OutputArea", bootstrapify);
$([IPython.events]).on("rendered.MarkdownCell", bootstrapify);
</script>')
}
bootstrapify_tables()

# ---

library(pander)
library(dplyr)
library(broom)
library(IRdisplay)
nice_pander <- function(...){
    panderOptions("table.split.table", 200)
    t = capture.output(pander(...))
    mdFile <- tempfile(fileext=".md")
    cat(paste(t, collapse="\n"), file=mdFile)
    htmlFile <- suppressMessages(knitr::pandoc(input = mdFile, format = "html"))
    t = readr::read_file(htmlFile)
    t <- gsub('<table>', '<table class="table table-condensed">', t)
    display_html(paste(t, collapse="\n"))

}

# ---
 
df <- data.frame(a=0:20, 
                 b=factor((0:20) %% 2, levels=c(0,1), labels=c("a", "b")), 
                 c=factor((0:20) %% 3, levels=c(0,1,2), labels=c("x", "y", "z")))
nice_pander(df %>% group_by(c) %>% do(tidy(t.test(a~b, data = .))))
```

Now both markdown tables and pander ones are nice...

If would be nice if the notebook contained something similar to the `bootstrapify_tables` event calls by default.

**Comment by minrk** [comment]
A PR for better default table styling would be great. I don't see anything wrong with that. I think the general scope that applies to both markdown cells and html output is `.rendered_html`.

**Comment by JanSchulz** [comment]
@minrk Is there any way to only target the current inserted output? The above is run on every insert, so if there are a few tables, it will take a bit...

**Comment by minrk** [comment]
Not with strict CSS, I don't think, but with some Javascript you could either write style attributes or add a custom CSS class to the output div.

If you have control over the HTML output on the kernel-side, the easiest solution is probably to add a class there.

**Comment by JanSchulz** [comment]
@minrk The current solution is based on the bootstrap table styler, which only kicks in when a `table` class is assigned to a `table`. So the current solution either needs some javascript to add that class or a change in the bootstrap css to add it unconditionally.

Is there actually a way to have a handle to the output in one of these event:

```
$([IPython.events]).on("output_appended.OutputArea", bootstrapify);
$([IPython.events]).on("rendered.MarkdownCell", bootstrapify);
```

**Comment by JanSchulz** [comment]
Another strange thing is that it seems that at the time the `$([IPython.events]).on("output_appended.OutputArea", bootstrapify);` event is run, the function can't get a handle to the actuall code:

```
funny <- function(){
    js <- '<script>
$([IPython.events]).on("output_appended.OutputArea", function(){alert($(".FUNNY_Whatever").length)});
</script>'
    IRdisplay::display_html(js)
}
funny()
```

and then three alerts which show `0,0,1` instead of `0,1,1`

```
IRdisplay::display_html("<span>Not Funny</span>")
IRdisplay::display_html("<span class='FUNNY_Whatever'>Not Funny</span>")
IRdisplay::display_html("<span>Not Funny</span>")
```

**Comment by jcb91** [comment]
@JanSchulz this (the timing issue) is down to the fact that the event is fired when markdown rendering is called, but the DOM elements are then created asynchronously, potentially _after_ any event callbacks...

**Comment by JanSchulz** [comment]
Somehow this still smells like a bug: if the event signals that something is appended, and then the should-be-appended thing isn't there, it's kind of useless :-(

**Comment by flying-sheep** [comment]
@JanSchulz it’s hard to read your code. please add highlighting: ```` ```r ``` it’s just a single letter for R!

**Comment by jcb91** [comment]
Well, the appended event does include some additional data (see [outputarea.js#L577](https://github.com/jupyter/notebook/blob/41ede3ec5687fa915f0b49cde4472432759288eb/notebook/static/notebook/js/outputarea.js#L577)). The markdown rendered event is somewhat different, though, it seems. I can't say I have a complete grasp of how this works!

**Comment by JanSchulz** [comment]
@jcb91 I looked at the arguments by which `bootstrapify` was called in  `$([IPython.events]).on("output_appended.OutputArea", bootstrapify);` and couldn't makse sense of it (but my js debugging foo is beginner at best :-( -> `alert(jsonify(arguments))`). Is there any way to add breakpoints to inserted HTML which contain JS in chrome?

**Comment by jcb91** [comment]
Hmm, I'm not sure of an obvious way to do it, as it's dynamically-created javascript. I'd probably go about it by creating a small extension with a dummy function registered in the `window` namespace, e.g. 

```javascript
window.my_debugging_capturer = function () {
    console.log('my_debugging_capturer');
}
```

then, set a breakpoint on that function in the sources tab of chrome's devtools.

Then, the inserted HTML can call the window function, as 

```javascript
window.my_debugging_capturer()
```

to hit the breakpoint, and you can step up the stack frames in the devtools to find the callback frame... does that make sense?

**Comment by JanSchulz** [comment]
Your idea about inserting code to go to a breakpoint brought me to the idea to google if there is a way to include a breakpoint in code (similar to the python debugger can be triggered). And yes, there is: https://stackoverflow.com/questions/10050465/set-a-javascript-breakpoint-in-code-in-chrome

Wow, thanks!

**Comment by jcb91** [comment]
Aha, good spot! :+1:

**Comment by JanSchulz** [comment]
And now it works:

* Adds the stuff during the loading of the notebook -> NB which have this included have bootstrap tables after load
* For each md render and for each output, also checks the output for tables and adds the required classes -> New content automatically gets the bootstrap styles...
* The md tables are no left aligned (before centered) like the normal tables.

```
bootstrapify_tables <- function(){
    html <- '<style>table.table, table.table tr, table.table td, table.table th {border: 0;}
table.table-nonfluid {width: auto !important;}
table.table { margin-left: 0; margin-right: 0;}</style>'
    js <- '<script>
bootstrapify = function(){
   debugger;
   args = arguments;
   $(".rendered_html table").addClass("table table-condensed table-nonfluid");
   n_pandoc = $("tr.header").parent("thead").parent("table").length;
   n_md = $("div.text_cell div.inner_cell div.rendered_html table").length
   n_rendered = $(".rendered_html table").length
   console.log ("beautified "+ n_pandoc + " + " + n_md + " + " + n_rendered + " tables (pandoc + md + rendered) ...");
};
bootstrapify_output = function(){
   debugger;
   arguments[4].find( "table" ).addClass("table table-condensed table-nonfluid");
   n = arguments[4].find( "table" ).length;
   console.log ("beautified "+n+" tables in output...");
};
bootstrapify_mdcell = function(){
   debugger;
   arg2 = arguments[1];
   c = arg2.cell;
   ele = c.element;
   tbls = ele.find("table");
   tbls.addClass("table table-condensed table-nonfluid");
   n = tbls.length;
   console.log ("beautified "+n+" tables in md...");
};

$([IPython.events]).on("notebook_loaded.Notebook", bootstrapify);
$([IPython.events]).on("kernel_ready.Kernel", bootstrapify);
$([IPython.events]).on("output_appended.OutputArea", bootstrapify_output);
$([IPython.events]).on("rendered.MarkdownCell", bootstrapify_mdcell);
</script>'
    IRdisplay::display_html(html)
    IRdisplay::display_html(js)
    cat("Added bootstrap code to beautify tables...\nRemember to 'File > Trust' the notebook to make this available on the next load.")
}
bootstrapify_tables()
```

**Comment by JanSchulz** [comment]
And a lesson learned: having errors in one of the js code during nb loading prevents the rest of the cells form showing up and then saving the nb destroys the notebook content for all cells after... Would probably only fixable by removing the content from the ipnb file directly...

**Comment by minrk** [comment]
Yikes, that really shouldn't happen. I keep fixing bugs like that, but they keep turning up.

**Comment by JanSchulz** [comment]
@minrk The above was simple a "var is not initialized", as far as I remember like this:

```js
bootstrapify_mdcell = function(){
   debugger;
   arg2 = arguments[1];
   c = arg2.cell;
   ele = element; // missing the `c.` in front of element
   tbls = ele.find("table");
   tbls.addClass("table table-condensed table-nonfluid");
   n = tbls.length;
   console.log ("beautified "+n+" tables in md...");
};
$([IPython.events]).on("rendered.MarkdownCell", bootstrapify_mdcell);
```

-> display as js, add a md table in the second cell in the nb, add more cells below, save, reload notebook, see it break :-/

**Comment by JanSchulz** [comment]
So, I will add that js somewhere that it is run in every notebook of mine and then look what it does with pandas tables and how using styled tables affects my working ... if I get this d*** extension working https://github.com/ipython-contrib/IPython-notebook-extensions/pull/524

**Comment by JanSchulz** [comment]
There is now a notebook extension, which does this: https://github.com/ipython-contrib/IPython-notebook-extensions/pull/524

**Comment by minrk** [comment]
@gnestor while there is an extension, I think there's still plenty of room for improving the default table style. @janschulz do you want to make a PR based on your experience with the extension so far?

**Comment by minrk** [comment]
Weird, this Issue should have the wishlist milestone, but it appears to be gone. Marking as backlog for now, though I don't know what that means.

**Comment by gnestor** [comment]
@minrk Ok, sorry for assuming it had been resolved. 

@ellisonbg renamed the *wishlist* milestone to *backlog* (as in agile development backlog) for this repo and ipywidgets.

**Comment by minrk** [comment]
OK. I guess we should add the wishlist milestone back, then? To me, backlog (not dealt with yet, needs triage) doesn't mean what we meant by wishlist (no immediate plans to deal with, volunteer contribution welcome). In fact, it seems a bit opposite in terms of what it means for where I should be focusing my attention.

**Comment by janschulz** [comment]
@minrk Sorry, I won't have time in the near future to work on this :-/

**Comment by TomAugspurger** [comment]
I don't have much time at the moment either, but for some guidance on what would be nice from pandas' prospective. Ideally with this small patch to pandas

```diff
diff --git a/pandas/formats/format.py b/pandas/formats/format.py
index e508998..fa866b9 100644
--- a/pandas/formats/format.py
+++ b/pandas/formats/format.py
@@ -992,7 +992,7 @@ class HTMLFormatter(TableFormatter):
         indent = 0
         frame = self.frame
 
-        _classes = ['dataframe']  # Default class.
+        _classes = ['dataframe', 'table', 'table-condensed']  # Default class.
         if self.classes is not None:
             if isinstance(self.classes, str):
                 self.classes = self.classes.split()
```

we'd get the nicely formatted output. With that patch, I see

![screen shot 2016-09-14 at 4 46 55 pm](https://cloud.githubusercontent.com/assets/1312546/18534674/45ceb6e2-7ab3-11e6-9707-cb9b66d87dac.png)

From poking around most of the styling comes from `.rendered_html tr, .rendered_html th, .rendered_html td, .rendered_html table, tr`. Hope that helps.

**Comment by gnestor** [comment]
I'm working on PR to update table styles to match JupyterLab: https://github.com/jupyter/notebook/pull/1776

**Comment by takluyver** [comment]
Closing as #1776 improved the default table style.
