### ISSUE TITLE
Bug in markdown handling of tables

### ISSUE THREAD

**Issue by janschulz** [jupyter/notebook#1183]
The following (straight from http://www.tablesgenerator.com/markdown_tables) produce a wrong html table (only two content rows):

```
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |
```

![2016-03-08_165013](https://cloud.githubusercontent.com/assets/890156/13606830/defbc590-e54d-11e5-8c56-c2229442cdbf.png)

**Comment by JanSchulz** [comment]
The problem seems to be the dollar...

**Comment by takluyver** [comment]
Dollar signs are used to delimit Latex maths expressions. You probably need to escape them (somehow) to use a literal dollar sign. I think this is a ~inevitable consequence of using a concise, not completely specified syntax.

**Comment by JanSchulz** [comment]
even over a linebreak? Anyway, it seems that pandoc agrees with your assessment: https://github.com/jgm/pandoc/issues/1127

**Comment by JanSchulz** [comment]
This works:
```
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | \$1600 |
| col 2 is |    centered   |   \$12 |
| col 3 is | right-aligned |    \$1 |
```
