### ISSUE TITLE
Markdown attachement broken by saving.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1185]
in a markdown cell 
- drag image
- cut content of markdown cell, 
- save or wait for autosave
- past content. 

Image is broken. 

Likely the cussing of the resources is modifying the state of the cell, while it should likely only affect the saved copy ?

**Comment by julienr** [comment]
I think this is because unused attachments are garbage collected on notebook save (this should only happen for manual save though).
I'm not sure how to fix that, short of trying to determine if an attachment is present in the clipboard.

**Comment by Carreau** [comment]
> I'm not sure how to fix that, short of trying to determine if an attachment is present in the clipboard.

you could garbage collect only what is sent on the wire, not what is in memory in the frontend. 

it's probably a matter of using `copy` at the right place.

**Comment by julienr** [comment]
The garbage collection is done on the JS side. So as soon as you cut the content from the markdown cell, there is now way for the JS to know if it was erased or put in the clipboard. 

The solution I see is to have the garbage collection happen on the python side, so the attachments are kept in memory on the JS side until the tab is closed. If I understand correctly, this is the solution you proposed.

**Comment by Carreau** [comment]
> The solution I see is to have the garbage collection happen on the python side, so the attachments are kept in memory on the JS side until the tab is closed. If I understand correctly, this is the solution you proposed.

No you don't need to, just don't mutate that current state client side and send a cleaned **copy** of the json. 

```
Notebook.prototype.save = function(){
    var json = this.to_json()

    var cleaned_json = remove_garbage(json)

    this.content.manager.save(cleaned_json)
}
```

**Comment by julienr** [comment]
Ah that's smart ! Will do this, thanks.
