### ISSUE TITLE
Add indication that file drop in MD cell will work.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1186]
When you are dropping a file in an MD cell, the UI that the file will be attached (or not) is too subtil. 
Would it be possible to add a specific class to the cell when dragging is in the right place ? 

We can Bikeshed on the style later.

**Comment by julienr** [comment]
This should be doable, I'll look into it.

**Comment by Carreau** [comment]
> This should be doable, I'll look into it.

Great ! Thanks !
