### ISSUE TITLE
Decision: --enable in nb/serverextension path spec?

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/notebook#1195]
> Note, this shouldn't be seen to hold up #879, or as encroachment on anything planned for 5.0

After #879, notebook 4.x users will may have to run between two and three commands (in addition to package installation) for each package they wish to "unpack":

``` shell
jupyter serverextension enable --py the_module # and/or...
jupyter nbextension install  --py the_module # and/or...
jupyter nbextension enable  --py the_module # and/or...
```

This opinion is such to support the freedom that a user has to control what javascript they are served in addition to what python they have... and indeed, in the case of custom widgets, where only the kernel will care where these frontend assets are, and the backend contract still stands.

However, this is somewhat odious for developers who want to make their install as simple as possible for users.

By adding an "enable" member to the nbext path spec, a developer can already inform the user of _their_ preference:

``` shell
jupyter nbextension install --py the_package
> Installing the_package...
> Copying...
> the_ext/index will always load in the `tree` app
```

after specifying: 

``` python
{
  "src": "static",
  "dest": "the_ext",
  "enable": True,
  "require": "the_ext/index
}
```

Similarly, if a user installs something that also has a serverextension, this would be nice:

``` shell
jupyter serverextension install --py the_package
> Configuring...
> the_package contains nbextensions...
> Copying...
> ... the_ext/tree will always load in the `tree` app
> ... the_ext/notebook will always load in the `notebook` app
```

After specifying:

```
{
  "module": "the_package.TheExtension",
  "nbextensions": True
}
```

**Comment by gnestor** [comment]
@bollwyvl Any new thoughts on this subject? If not, should we close this?

**Comment by bollwyvl** [comment]
I think `conf.d`, as suggested in #3116 would answer this without requiring a change to the API... unless it only covers nbextensions... but yeah, we can close this...

**Comment by maartenbreddels** [comment]
It should work for all, not just nbextensions.
