### ISSUE TITLE
Body css setting, why absolute?

### ISSUE THREAD

**Issue by cqcn1991** [jupyter/notebook#1202]
Not sure if this is the right place to post it, please correct me if I post it wrong.

I'm developing a sidebar for Ipython Notebook (https://github.com/ipython-contrib/IPython-notebook-extensions/issues/532):
![toc](https://cloud.githubusercontent.com/assets/2425141/13720167/a7f8a058-e83c-11e5-8e84-4ebda0c660dc.gif)

I want to use **Twitter Bootstrap**'s scrollspy (http://getbootstrap.com/javascript/#scrollspy), but it requires the `body` css `position:relative`. And I took a look at the code, it isn't. 

I'm wondering why set `body` to `position:absolute`? And is it possible to change it?

**Comment by ellisonbg** [comment]
I don't remember the details, but the page-wide CSS in the notebook tends
to be really brittle in order to get everything to work across all
browsers. It *may* be fine to remove, it may also break certain things.

I should mention that the new JupyterLab page will have a much more
flexible layout system that is designed exactly for things like this.

On Sat, Mar 12, 2016 at 6:55 PM, cqcn1991 <notifications@github.com> wrote:

> Not sure if this is the right place to post it, please correct me if I
> post it wrong.
>
> I'm developing a sidebar for Ipython Notebook (
> ipython-contrib/IPython-notebook-extensions#532
> <https://github.com/ipython-contrib/IPython-notebook-extensions/issues/532>
> ):
> [image: toc]
> <https://cloud.githubusercontent.com/assets/2425141/13720167/a7f8a058-e83c-11e5-8e84-4ebda0c660dc.gif>
>
> I want to use *Twitter Bootstrap*'s scrollspy (
> http://getbootstrap.com/javascript/#scrollspy), but it requires the body
> css position:relative. And I took a look at the code, it isn't.
>
> I'm wondering why set body to position:absolute? And is it possible to
> change it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/1202>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cqcn1991** [comment]
Really? Never heard of this. Where can I see the progress?

**Comment by ellisonbg** [comment]
JupyterLab is being developed in a set of separate JavaScript repos and npm
packages, but the alpha version of everything is available in the master
branch of:

https://github.com/jupyter/notebook

The main js package that lists all the deps is here:

https://github.com/jupyter/jupyter-js-plugins/blob/master/package.json

While we have been working on this for a while now, it is just starting to
land in master in a usable form. Parts of the code base are pretty stable,
but other parts are under very active development. If you have specific
questions, I would create an issue on the jupyter/notebook repo and
@mention me (ellisonbg).

On Sun, Mar 13, 2016 at 4:41 PM, cqcn1991 <notifications@github.com> wrote:

> Really? Never heard of this. Where can I see the progress?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/1202#issuecomment-196083626>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cqcn1991** [comment]
@ellisonbg And where exactly is the `flex layout`? I want to see if there is anything I can help.

**Comment by ellisonbg** [comment]
All of our layout is done using phosphor.js:

http://phosphorjs.github.io/

The best example to have a look at is the dock panel:

http://phosphorjs.github.io/examples/dockpanel/



On Sun, Mar 13, 2016 at 5:50 PM, cqcn1991 <notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> And where exactly is the flex
> layout? I want to see if there is anything I can help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/1202#issuecomment-196091246>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
As far as I remember there are weird interaction with the header and the pager. 
If you change to `position:relative` it breaks the scrolling when clicking on header links/anchor URL, that either scroll behind the header, or make it impossible to correctly open the pager.

**Comment by JamiesHQ** [comment]
Hi @cqcn1991 : We're doing a little housekeeping on our issue log and noticed this thread from 2016. Is this still an open request? thanks!
