### ISSUE TITLE
Ungraceful failure for code blocks from unknown languages

### ISSUE THREAD

**Issue by bnaul** [jupyter/notebook#1209]
In a markdown cell, a code block with an unknown language renders as "Type Markdown and LaTeX: α^2" instead of (as one would expect) just printing the code with no highlighting.

**Comment by willingc** [comment]
@bnaul Would you be able to provide a specific code snippet and its output? Thanks.

**Comment by bnaul** [comment]
[This](https://www.dropbox.com/s/u093qmye7693fua/MissingLanguage.ipynb?dl=0) notebook renders locally as:

![screenshot 2016-03-14 14 42 01](https://cloud.githubusercontent.com/assets/903655/13760995/34624e42-e9f3-11e5-93f7-b93864fbda91.png)

**Comment by willingc** [comment]
Hmm...I see a few things:

1. If nbconvert raw is selected for the cell type, I believe that it renders the way that you expected it would if the cell was Markdown with an unknown language.

2. I'm seeing errors in the console log as follows:
<img width="707" alt="screen shot 2016-03-14 at 3 14 34 pm" src="https://cloud.githubusercontent.com/assets/2680980/13761711/8dbc9d9a-e9f7-11e5-845d-7dd16878a49e.png">

3. There's a CORS error and an error with `replace`. @carreau, @jfreder Any thoughts on the JS side of things?

**Comment by Carreau** [comment]
No that's not a `raw` thing, as raw is meant only for nbconvert, and here it's an issue in the notebook.. (@bnaul is on the feet 10 feet from me)

My guess is it's dynamic mode loading for codemirror which is broken. 
using  single quote instead of backticks:

    '''pyhton
    blah
    '''

Works

    '''matlab
    blah
    '''

(`matlab` for example) does not. 


I **think** that the `require(mode)` return `undefined`, we **should** fallback on `plain/text` but don't.

**Comment by willingc** [comment]
@carreau Thanks for the detailed explanation. (Nice to know that @bnaul is at Berkeley, perhaps we'll meet later this month when I am up there.)

Do we want to mark this as Sprint Friendly and/or URAP?

**Comment by Carreau** [comment]
> Nice to know that @bnaul is at Berkeley, perhaps we'll meet later this month when I am up there.

Yes, he is not working **on** jupyter, but is in BIDS often. 

> Do we want to mark this as Sprint Friendly and/or URAP?

Too subtle to fix IMHO , maybe sprint friendly though.
