### ISSUE TITLE
Bizarre double output effect

### ISSUE THREAD

**Issue by fperez** [jupyter/notebook#1210]
I don't really know how this happened, I'm running `4a48cad` of the notebook and was executing our Lorenz attractor example to take a screenshot, when my output area ended up looking like this:

![image](https://cloud.githubusercontent.com/assets/57394/13767653/fa38ad9c-ea29-11e5-9a2b-38f98bae4e7c.png)

It actually has this really odd double output area, with the output in each one of them chopped up and dual scroll bars.  I figured the problem might go away on update (I'll try later), but at least I wanted to capture the issue and report it in case we ever see it again, or in case someone else has seen something similar.

**Comment by minrk** [comment]
Browser and version? Does resizing the window pop it back into place? Most often when I see things like this it's an overzealous browser rendering optimization not properly blanking things that are gone. I haven't seen this particular one, but I see things like this more often when I'm on Chrome's beta or dev channel.

**Comment by fperez** [comment]
Chrome Version 48.0.2564.116 (64-bit) on OSX El Cap.

Resizing the window doesn't fix it, but when I open the same notebook in a different tab (I'm not reloading the original tab so I can keep experimenting with it), I see the following in that cell:

![image](https://cloud.githubusercontent.com/assets/57394/13797360/34ae5922-eaca-11e5-86c8-b575610c1c2e.png)

Two images but no widget controls.  Oddly, in the cell *above that*, which should have a similar widget, instead I get multiple copies of the controls. Interesting-looking:

![image](https://cloud.githubusercontent.com/assets/57394/13797388/746f1a56-eaca-11e5-9bf0-f8b788c34c4a.png)

I don't think we need to lose sleep over this, but it looks really weird :)

**Comment by minrk** [comment]
Ah, so they are really there. Interesting! cc @jdfreder for possible widget weirdness

**Comment by jdfreder** [comment]
Interact displays the return value of the function by default, so if you explicitly display inside the function in addition to returning the object with the rich repr, you will see it displayed twice.  Are you returning something in the function @fperez ?  

The dual controls is probably a bug in the page reload widget persistence code, but it could also be something related to the way the rich display system is being used.  Did that happen after the page reload?  Prior to the page reload did you run the cell N times (it looks like N==3)?

**Comment by fperez** [comment]
No, I changed the function to not return anything (to avoid displaying the long arrays the original returned).

The multi-control case happened just on opening of the page in a new tab, straight out.  But I don't recall how many times I'd run the code in the first place, that was days ago.

**Comment by fperez** [comment]
Closed by [ipywidgets #429](https://github.com/ipython/ipywidgets/pull/429), let's see if something like this reappears again but for now will close.
