### ISSUE TITLE
Missing SVG config for mathjax

### ISSUE THREAD

**Issue by goerz** [jupyter/notebook#1213]
It appears that the bundled mathjax installation is missing the config files for SVG rendering. When right-clicking on a mathjax formula , and choosing Math Settings > Math Renderer > SVG, I get a an error

    404 GET /static/components/MathJax/jax/output/SVG/config.js?rev=2.5.3

Indeed it is easy to verify that the underlying directory in `site-packages` only contains `HTML-CSS/config.js`, but not `SVG/config.js`. The problem is that the choice for the SVG renderer is cached by the browser. As a result, viewing any subsequent notebooks results in the `404` error (which is generally not visible to the user) and completely deactivates the mathjax capabilities (a markdown cell with LaTeX  will not be rendered at all). This is then permanent; the only way to recover from the bug is to clear the browser cache.

I would strongly advocate to include the SVG renderer in the bundled mathjax installation, not only in order to avoid the above bug, but also because I still find that SVG-rendered mathjax looks nicer for operators with hats (as are commonly used in quantum mechanics).

**Comment by minrk** [comment]
Fixed by #1055
