### ISSUE TITLE
Option to toggle header in edit mode.

### ISSUE THREAD

**Issue by Summersa** [jupyter/notebook#1214]
#1215
I think there should be an option to toggle the header in edit mode.

This is currently what the view option have in the edit page.

![headheaderbefore](https://cloud.githubusercontent.com/assets/15676683/13789970/eb4655be-eaab-11e5-8b6e-b68b666ecd1e.png)

**Comment by Carreau** [comment]
#1215 should have fixed that. 

Thanks !
