### ISSUE TITLE
character count per line implementation

### ISSUE THREAD

**Issue by johnn3** [jupyter/notebook#1217]
Would it be wise to implement a feature such as this within the notebook's editting environment? During edits I usually try to keep consistent with such things (80 chars) but I haven't encountered documentation if it does already existed otherwise?

**Comment by minrk** [comment]
You can do this with a CodeMirror [rulers addon](https://codemirror.net/demo/rulers.html) and there's an [extension](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/ruler) to turn this on in the notebook. duplicate of #160

**Comment by jpeacock29** [comment]
To update links, this is in [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) as the [Ruler](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/ruler) extension.
