### ISSUE TITLE
Dashboard sorting status 'by last modified' gets lost

### ISSUE THREAD

**Issue by michaelaye** [jupyter/notebook#1218]
When I click on "Last Modified" to have the notebooks listed by their last modified time-tag, and then open any file that is offered by the Dashboard, it loses it's status of being sorted by "last modified".

Version: GH master (3feea618027713a53e540b6f7eb1e3abef57dc03)
Browser: Safari on OSX 10.10.5

**Comment by captainsafia** [comment]
Thanks for opening this! I'll look into it!

The last modified sorting is a little buggy so feel free to open issues if you experience other problems and @ me.

**Comment by michaelaye** [comment]
I'd like to be able to configure that the last modified sorting is default for a newly started notebook server. Should I create a new issue for that or is that already possible?

**Comment by captainsafia** [comment]
That's not yet possible — so go ahead and open an issue.

**Comment by captainsafia** [comment]
@michaelaye — So I'm testing this out and when you say that a file is no longer sorted by last modified I assume that you have saved the file and it is no longer in the appropriate position at the top/bottom of the list since it is the most recently modified?

**Comment by michaelaye** [comment]
Is this feature still in master? I would like to help debugging it so that it could be released.

**Comment by michaelaye** [comment]
I'm repeating above question: Is this feature still in master? It's still not appearing in the releases, it seems. Unless I have to activate it somehow?

**Comment by takluyver** [comment]
I don't think we have any features that you have to activate, so if it's not yet in a release, it's presumably in master.

**Comment by rgbkrk** [comment]
This one is targeted for 5.0 and is in master.

**Comment by michaelaye** [comment]
I confirmed that this bug is still active in master.

**Comment by michaelaye** [comment]
Seems that this feature is not active in master anymore. :(

**Comment by jorisvandenbossche** [comment]
I also encountered this issue. When doing a certain action (like shutting down a kernel from within the Files view), the 'last modified' status gets reset.

Even when things happen in the background, for example a notebook in another tab is saved, the view gets reset.

**Comment by takluyver** [comment]
@captainsafia I've unassigned you as it's been a while since you were active here, but if you'd still like to tackle this, let us know.
