### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#122]
@jdfreder volunteered to start this off.

There are some docs already there. We should:

- [x] Update stuff (like `ipython notebook` -> `jupyter notebook`)
- [x] Remove docs that will live elsewhere (nbformat, nbconvert)
- [x] Document config options (I have machinery for this in IPython, can duplicate it or put part in traitlets)
- [ ] API docs - I think the public Python API is pretty small, but there should at least be enough to describe:
  - Extensions adding handlers
  - Custom contents managers, checkpoint managers, etc.
  - Save hooks
  - Probably some other stuff I'm not thinking of right now
- [ ] ??? Some amount of documentation of the JS APIs?
- [x] Docs should build on RTD

**Comment by jdfreder** [comment]
Thanks for the checklist : )

**Comment by ssanderson** [comment]
@takluyver @jdfreder I'm happy to help with the docs for custom Contents/Checkpoints.

**Comment by takluyver** [comment]
Thanks @ssanderson , I think you've probably spent the most time dealing with that interface.

**Comment by ssanderson** [comment]
@takluyver is there a specific place where those docs would go?

**Comment by takluyver** [comment]
Beyond putting them in the docs/ folder, I don't think we've worked out the structure we'll want for this repo yet. I've been starting with the simpler packages - [traitlets](http://traitlets.readthedocs.org/en/latest/), [nbformat](http://nbformat.readthedocs.org/en/latest/) and [jupyter_client](http://jupyter-client.readthedocs.org/en/latest/).

I guess how we structure it will depend on how many of these points there are where we specify an API for third parties to implement. I know there are many points where that's technically possible, but I don't know how many of those we should be documenting and encouraging people to use.

**Comment by takluyver** [comment]
I've moved most of the machinery for documenting config options into the traitlets package, so it should be simple now to reuse that to document the notebook config.

**Comment by jdfreder** [comment]
> I've moved most of the machinery for documenting config options into the traitlets package, so it should be simple now to reuse that to document the notebook config.

Awesome, when I get there I'll ping you.

> @takluyver @jdfreder I'm happy to help with the docs for custom Contents/Checkpoints.

@ssanderson that would be great!  When I'm done with #124 it should be clear where those can go.

**Comment by jdfreder** [comment]
@takluyver what's this note mean: "Docs should build on RTD" ?
RTD - http://acronyms.thefreedictionary.com/RTD

**Comment by jdfreder** [comment]
Ah Read the Docs?

**Comment by takluyver** [comment]
Yep, Read The Docs. Sorry, I guess that's not a standard acronym.

Side note: the readthedocs maintainers also have rtfd.org as a redirect, so you can link people to e.g. http://jupyter-client.rtfd.org :-)

**Comment by takluyver** [comment]
Reopening because there's still a few bits to add.

**Comment by jdfreder** [comment]
Since the last bit is all new content, I moved it into it's own issue with a checklist for each sub item. #476
