### ISSUE TITLE
Extending Cell Selection Seems Unintuitive

### ISSUE THREAD

**Issue by blink1073** [jupyter/notebook#1222]
I had expected the extend selection shortcut to preserve the current active cell, instead of switching to the other cell.

![notebook-expand](https://cloud.githubusercontent.com/assets/2096628/13816474/8b70160a-eb5c-11e5-8745-fb764f4c4536.gif)

**Comment by blink1073** [comment]
I can submit a PR if there is agreement.

**Comment by takluyver** [comment]
I expect it to work as it does. It's analogous to selecting text or spreadsheet cells - you are moving the cursor as you select, so the cursor ends up at the most recently selected item.

**Comment by blink1073** [comment]
I was attempting to merge cells.  I would expect to select the target cell first, then expand the selection to the others.

**Comment by takluyver** [comment]
When you merge cells, it doesn't matter which way the selection goes, right? It merges n selected cells into one selected cell, regardless of where the cursor is with respect to the selection.

**Comment by blink1073** [comment]
The mode of the original cell is the one that is preserved, and the order of the text will be different.

**Comment by takluyver** [comment]
The order of the text definitely shouldn't be affected - if it is, that's a bug.

Maybe we should change how merging decides what to do with cells of different types so it doesn't depend on selection order (e.g. always inherit from the topmost selected cell, or make a code cell unless all selected cells are markdown, or turn markdown cells into comments when merging them into a code cell, or...). I don't think we should change the selection mechanics for this, however.

**Comment by ellisonbg** [comment]
When we designed the multiple selection, we iterated through a couple of
different models, some quite different than what we settled on. It turned
out to be one of the more difficult UX and interaction design questions we
have tackled. There were some really subtle problems that came up with
other designs of this, so my preference is to keep what we have unless
there is a super strong pattern of difficulty that emerges from people
using it (I haven't seen that yet).

On Wed, Mar 16, 2016 at 9:00 AM, Thomas Kluyver <notifications@github.com>
wrote:

> The order of the text definitely shouldn't be affected - if it is, that's
> a bug.
>
> Maybe we should change how merging decides what to do with cells of
> different types so it doesn't depend on selection order (e.g. always
> inherit from the topmost selected cell, or make a code cell unless all
> selected cells are markdown, or turn markdown cells into comments when
> merging them into a code cell, or...). I don't think we should change the
> selection mechanics for this, however.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/1222#issuecomment-197397684>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
Understood, thank you both.
