### ISSUE TITLE
PDF failing on Docker Container

### ISSUE THREAD

**Issue by achinault** [jupyter/notebook#1226]
The notebook fails to export notebooks to pdf even on trivial notebooks(singe markup cell).  The error shows in the log citing "LaTex Error: File 'ulem.sty' not found." 

This appears to be a DockerFile omission, as after a bit of troubleshooting it looks like updating apt-get and installing texlive-generic-recommended fixes this missing file issue.

Version: notebook:stable and notebook:latest

**Comment by Carreau** [comment]
We'll remove the dockerfile which is mostly unmaintained.

**Comment by Carreau** [comment]
Closing as we removed the docker container. 

Thanks !
