### ISSUE TITLE
Is it possible to add this extension into notebook?

### ISSUE THREAD

**Issue by cqcn1991** [jupyter/notebook#1228]
I want to add a sidebar to jupyter notebook, something like this:

![toc](https://cloud.githubusercontent.com/assets/2425141/13720167/a7f8a058-e83c-11e5-8e84-4ebda0c660dc.gif)

I've discussed here https://github.com/ipython-contrib/IPython-notebook-extensions/issues/532
It's just a demo and still in dev yet, but I still want to know if it is possible to add it into the main notebook repo? Or what specific requirement I have to met?

**Comment by ellisonbg** [comment]
We are interested in things like this being in the main notebook, but for now I think it makes sense for this to be an extension. Starting to do more complex layout in the existing notebook is sort of opening a can of worms. I really prefer to avoid that and instead start to do work involving more complex layout in JupyterLab instead.

One result of the dev meeting we had last week though is that we are going to come up with a good migration plan for existing nbextensions to transition to JupyterLab. More details soon...

**Comment by cqcn1991** [comment]
@ellisonbg That's OK. So JupyterLab is the Jupyter version of original nbextensions? 
I think it would be great if we can make the extension system works just like `rubygem`, where you can install things simply by specifying it in a file and run a install command. Now the `nbextension` is just very hard to install, you need to download the file by hand, put them in the right place etc, and hard to update.

**Comment by ellisonbg** [comment]
Did you see the documentation for nbextensions (this is the new 4.2 APIs to be released soon):

https://jupyter-notebook.readthedocs.org/en/latest/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html

JupyterLab is a the notebook UI we are building - it will have some equivalent way of creating extensions. nbextensions are the extensions for the existing notebook.

**Comment by ellisonbg** [comment]
Also, a lot of the pain you mention with installing and activating nbextensions is fixed in the upcoming 4.2 release (see those docs).

**Comment by jtpio** [comment]
Closing as fixed in Notebook 7 (currenly in RC), which includes a Table of Contents panel by default:

![image](https://github.com/jupyter/notebook/assets/591645/1c4e3b6a-f75e-4d30-ae14-7de645af4949)

Also linking to https://github.com/jupyter/notebook/issues/672 as related.

Thanks all!
