### ISSUE TITLE
Feature request DragNdrop files from Finder to create paths

### ISSUE THREAD

**Issue by michaelaye** [jupyter/notebook#123]
OS X: Would it not be nice if one could drag a folder or file from Finder into a Jupyter cell and then have the path show up in the cell? This works really nice with iTerm2, don't know if this would be possible with Jupyter?

**Comment by Carreau** [comment]
I guess it is a browser limitation, you have to figure out what to do on drag. 
Note that this does not make sens if  the kernel is not on local machine.

**Comment by minrk** [comment]
I'm not sure browsers get access to local file paths when you drag/drop. I think it only gets the base filename.

**Comment by Carreau** [comment]
On chrome you do, everything is somethings like `C:\fakepath\<filename>.<ext>`

**Comment by rgbkrk** [comment]
I don't even have a C:\ drive, that's awesome!
