### ISSUE TITLE
Wishlist: Usability of new "Find and Replace" dialog for finding strings

### ISSUE THREAD

**Issue by andram** [jupyter/notebook#1238]
I really like the new "Find and Replace" dialog for _replacing_ strings in jupyter 4.1. 

However, I use _find_ more often than _replace_, and, unfortunately, the dialog is not optimal for quickly searching specific terms in a notebook and then jump to those points where the search pattern matches. 

For example, I often search for a specific variable name in a longer notebook, just to see where it is used, etc. With the current dialog I only get the matching lines listed, but without context and no obvious way to click on them to jump to the corresponding position in the notebook. 

I therefore still often need to resort to Ctrl-f from the browser, which is not ideal as it also searches through output cells and other stuff. 

It would be great if the "Find and Replace" dialog could be improved in the following way: Keep the dialog small, as long as no replace string is entered. In this case the assumption should be that the user wants to _find_ a term and therefore matches should be highlighted directly in the notebook, if possible. Then offer arrows / shortcuts to jump to previous / next matches in notebook. Essentially this could be an improved version of the browser's ctrl-f dialog, which however knows about cells and regex. 

Once the user insert a string in the replace box, return to the current behaviour of listing the consequence of the replace.

**Comment by Carreau** [comment]
Hi, 

Thank for the idea, it is something we considered and would like to have. We are just mainly missing the bandwidth to 
  1. Dig out the API in codemirror and the browser to allow scrolling highlighting. 
  2. Write the relevant code. 

I would suggest to look at https://github.com/ipython-contrib/ipython-notebook-extensions they might have something along these lines, and if so at some point someone shoulf try to bring the code over into the core of Jupyter notebook.

**Comment by JamiesHQ** [comment]
cc @gnestor

**Comment by gnestor** [comment]
I'm marking this as "JupyterLab" because the majority of core developer resources are focused on lab now vs. classic notebook. I agree that the find and replace functionality of the notebook could be greatly improved but the work required to do so is not trivial. I'll also add a "New Contributor" label just in case someone would like to take this on–I'd be more than willing to assist.

**Comment by jibraniqbal666** [comment]
hello @gnestor I would love to work on this feature could you assist me, this will going to be my first ever contribution to open source community.

**Comment by gnestor** [comment]
Hi @jibraniqbal666! Great to have you and I am happy to help you with your first contribution! Let me know if you need anything from me to get started 👍

**Comment by jibraniqbal666** [comment]
@gnestor just couple of newbie questions.
 i have installed everything as contributor guide suggested, i just don't where to start this feature from particularly which file, because i don't know the overall architecture.

**Comment by jibraniqbal666** [comment]
@gnestor any hint please
?

**Comment by gnestor** [comment]
Hi @jibraniqbal666, I'm sorry to keep you waiting...

First, take a look at the notebook implementation: https://github.com/jupyter/notebook/blob/702b67d15e05ec5a36a0e6422c918cca89c309e3/notebook/static/notebook/js/searchandreplace.js

You also want to take a look at CodeMirror's search and replace: https://codemirror.net/demo/search.html

Ping me if you have any other questions 👍

**Comment by cmoralesmx** [comment]
hi @gnestor, I would like to work on this one if it is available. I will take a look at both the current implementation and the CodeMirror's search and replace.

**Comment by gnestor** [comment]
Thanks a bunch @cmoralesmx! 👍

**Comment by joshz123** [comment]
Is this issue still open? If so I am new to open source and would like to work on it

**Comment by yash112-lang** [comment]
Hello, @gnestor I am new to open source and liked this feature a lot I want to know if this issue is still open?

**Comment by gnestor** [comment]
I haven't contributed to Project Jupyter in over a year so I would suggest looking in the jupyterlab repo. I know that there is a comprehensive find feature in lab but I'm not sure about find and replace.

**Comment by yash112-lang** [comment]
Okay, so @gnestor can you please suggest to me **another repo** related to python to start my journey to open source. By the way Thanks.

**Comment by gnestor** [comment]
@yash112-lang https://github.com/jupyterlab/jupyterlab

**Comment by jtpio** [comment]
The search replace feature from JupyterLab will be available in the next Notebook 7 major release:

https://user-images.githubusercontent.com/591645/193763736-318566c6-19f6-4c72-a0ba-8940e3f5d205.mp4

There is also a third-party `search-replace` extension for JupyterLab which should be compatible with Notebook 7 as well: https://github.com/jupyterlab-contrib/search-replace
