### ISSUE TITLE
Wait for kernel/session to be added to database before returning?

### ISSUE THREAD

**Issue by blink1073** [jupyter/notebook#1239]
Creating a kernel or a session yields a future that adds the entry into the database.
This means that we create the kernel or session object on the client but don't know when it will show up in a REST call to list the running kernels/sessions.  Any objection to making this synchronous?  
My use case is starting a session for a notebook, then updating the "running session" indicator in the file browser, which depends on a REST call to list running sessions.  Currently it misses the session starting.

https://github.com/jupyter/notebook/blob/master/notebook/services/sessions/sessionmanager.py#L75

**Comment by minrk** [comment]
Starting a kernel does have to be async, and since sessions start kernels that may be hard to avoid for the sessions API. I'm not sure I understand what's going wrong in your example, since the list of running sessions will include the session if it's started, and won't if it hasn't yet.

**Comment by minrk** [comment]
Question: when you say async, are you seeing that the session isn't listed after the REST call *finishes*? If that's true, it's an async bug missing a yield, because the session should certainly finish existing by the time it replies to the API call.

**Comment by blink1073** [comment]
Yes, we POST to `/sessions`, and get an ID back, then GET `/sessions`, and that id is not listed.  I'll double check, but that is what I saw yesterday.

**Comment by blink1073** [comment]
False alarm, confirmed the bug is on my end, sorry for the noise!

```
***session started a5d6ea8f-a7be-48f0-8890-04c6e81583f5
bundle.js:44025 **got ids [Object]0: Objectid: "a5d6ea8f-a7be-48f0-8890-04c6e81583f5"kernel: Objectnotebook: Object__proto__: Objectlength: 1__proto__: Array[0]
```

**Comment by minrk** [comment]
Okay, great. I asked because it's an easy bug to introduce: one missing yield, and you can end up with the HTTP handler returning before its actions have completed.
