### ISSUE TITLE
Define a Python class across multiple cells

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1243]
This issue is both Notebook & IPython, but I guess could be solved here only with an extension. 

Again, requested during JupyterDays:

For education purpose, it would be nice to be able to define a class across many cells., in particular 1 method/cell. 

I think it is possible by peeking at next/previous coed cells, and if the all body of a cell is indented by at least 4 spaces, "join" the content of each cell before sending a single execution request. 

we could "mark" joined executed cells with a specific prompt. 

Ping @ellisonbg

**Comment by ellisonbg** [comment]
Could you edit the title of this issue - at first I thought you were
talking about CSS classes or something in the UI. Maybe something like
"Define a Python class across multiple cells?"

On Tue, Mar 22, 2016 at 11:56 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> This issue is both Notebook & IPython, but I guess could be solved here
> only with an extension.
>
> Again, requested during JupyterDays:
>
> For education purpose, it would be nice to be able to define a class
> across many cells., in particular 1 method/cell.
>
> I think it is possible by peeking at next/previous coed cells, and if the
> all body of a cell is indented by at least 4 spaces, "join" the content of
> each cell before sending a single execution request.
>
> we could "mark" joined executed cells with a specific prompt.
>
> Ping @ellisonbg <https://github.com/ellisonbg>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/1243>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Title updated.

**Comment by takluyver** [comment]
We currently dedent code if it's all indented, because it's not uncommon to copy some code from the middle of a method or function with the intention of running it directly.

I'm happy to help someone build an extension for this, but:
- I don't think it's likely to be smooth or seamless enough to go into IPython/Jupyter itself
- I'd probably do it with cell magics, e.g. `%%addtoclass FooBar`. Explicit is better than implicit, etc.

**Comment by Carreau** [comment]
We dedent it in IPython, I'm thinking a Js extension can likely handle submitting all cells at the same time.

**Comment by takluyver** [comment]
I'm not quite sure what you're envisaging, but I can't see anything in the frontend solving this in a nice way.

**Comment by minrk** [comment]
js can group the cells input and send it as a single execution, rather than executing the cells separately.

**Comment by Carreau** [comment]
```
Cell.prototype.execute = function(){
   if(this.all_indented){
      this.kernel.execute(this.previous.cell.source + this.cell.source)
   } else {
      this.kernel.execute(this.cell.source)
  }
}
```

**Comment by takluyver** [comment]
That feels like something that could be really confusing, so I wouldn't want it on by default. But if it's an optional extension, then it's very easy for people using it to create notebooks that won't work for anyone without the extension, and will fail in mysterious and confusing ways.

**Comment by Carreau** [comment]
> That feels like something that could be really confusing, so I wouldn't want it on by default. But if it's an optional extension, then it's very easy for people using it to create notebooks that won't work for anyone without the extension, and will fail in mysterious and confusing ways.

Yep, seem about right.

**Comment by janschulz** [comment]
There is an nbextension which adds such a button: https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/usability/toggle_all_line_numbers/main.js

It looks like it reimplements the action instead of only adding a button... -> CC:  @jcb91

**Comment by Henry-E** [comment]
An explicit cell magics for this would be nice

**Comment by aaronmyatt** [comment]
My humble vision for this sort of feature is the ability to create 'subcells'. Perhaps even automatically convert doc strings and other inline comments into these 'subcells'. 

I am trawling the documentation now to prepare myself for contributing plugins/fixes. However, if someone can kindly point me in the right direction I will gladly take a stab at implementing this. What is the feasibility of my suggestion? Would it need to be a plugin?

**Comment by alexhagen** [comment]
I made a magic for this exact purpose, I'm calling it ``jdc`` - or Jupyter dynamic classes.  It's super simple, but basically it allows you to type

```python
%%add_to our_class
def our_method(self, our_variable):
    print our_variable
```
and that method will be added to the class ``our_class`` (and all objects of that type) with access to self.  You can also add it to only a single object with

```python
%%add_to our_object
def our_method(self, our_variable):
    print our_variable
```

Documentation is at [https://alexhagen.github.io/jdc](https://alexhagen.github.io/jdc).  I hope this helps

**Comment by jasongrout** [comment]
@alexhagen - @jzf2101 just pointed out your solution to this issue. Solving this with a package like yours looks like a great solution to this issue. Do you plan to release this as a python package on pypi?

I think this issue can be closed as solved with this package. @Carreau - what do you think?

**Comment by alexhagen** [comment]
I'll put it up on PyPi this week.

**Comment by jzf2101** [comment]
@gnestor Is this issue still open?

**Comment by takluyver** [comment]
i'd say that @alexhagen's jdc package is as 'solved' as this is going to get, so we should close this issue.

**Comment by dsblank** [comment]
Just to point out that you can do this in regular Python, without resorting to any extra magic:

Cell 1:
```python
class MyClass():
    def method1(self):
        print("method1")
```
Cell 2:
```python
class MyClass(MyClass):
    def method2(self):
        print("method2")
```
Cell 3:
```python
instance = MyClass()
instance.method1()
instance.method2()
```
That is, you can define a class recursively, cell by cell. I don't think the final class is any different from one defined all in one cell. So you don't need an extra package to "solve" this problem.

**Comment by syockit** [comment]
> That is, you can define a class recursively, cell by cell. I don't think the final class is any different from one defined all in one cell. So you don't need an extra package to "solve" this problem.

Under the hood, this creates a hierarchy of classes with the same name.
```python
import inspect
inspect.getmro(MyClass)
```
```
(__main__.MyClass, __main__.MyClass, object)
```
I don't know if there's a limit to the number of superclasses, but for a typical notebook it shouldn't be a problem.

**Comment by andsmi97** [comment]
> Just to point out that you can do this in regular Python, without resorting to any extra magic:
> 
> Cell 1:
> 
> ```python
> class MyClass():
>     def method1(self):
>         print("method1")
> ```
> 
> Cell 2:
> 
> ```python
> class MyClass(MyClass):
>     def method2(self):
>         print("method2")
> ```
> 
> Cell 3:
> 
> ```python
> instance = MyClass()
> instance.method1()
> instance.method2()
> ```
> 
> That is, you can define a class recursively, cell by cell. I don't think the final class is any different from one defined all in one cell. So you don't need an extra package to "solve" this problem.

Well, that wouldn't work if I want to comment my class methods using Text Cells

**Comment by alexhagen** [comment]
Thanks to @dsblank for pointing out that this can be done without a package.  I'll add that to the readme, a really clever way to do it.  I still prefer the syntax of jdc, so I'm going to keep it as a package, but it's always interesting to see different ways to get the same result.
