### ISSUE TITLE
Impossible to close/move `notebook tutorial` in lab

### ISSUE THREAD

**Issue by akhmerov** [jupyter/notebook#1248]
Observed on 7174d9d

To reproduce:
1. Select "notebook tutorial" from the command palette.
2. Verify that the tab with the tutorial can only be resized but not closed or moved around.

Desired outcome:
It should be possible to close the notebook tutorial.

**Comment by blink1073** [comment]
Thanks for the report @akhmerov, this issued has been fixed in `jupyter-js-plugins`, but I still need to make a PR to add that functionality here.
