### ISSUE TITLE
[Docs] Fail if document not included in any toctree.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1252]
Also figure out a way to make a team-wide notification if there is a build failure. 

Do that maybe on all github repos....

**Comment by willingc** [comment]
We should have a doc build test run in Travis as well as a daily build all the docs job on Jenkins. I monitor this http://willingc.github.io/doc_helper/ on a regular daily basis too.

**Comment by takluyver** [comment]
We have a Jenkins job that builds the IPython docs, but I think @willingc's page is the best thing for this - RTD is already building the docs on each commit, so we may as well make use of that.

I don't know if there's an easy way to control what are warnings vs errors in Sphinx. Things like the 'document not in any toctree' are a warning, so they don't cause the build to fail, but if we turn all warnings from Sphinx into errors, I think people are going to get very frustrated with docs constantly failing to build.

**Comment by Carreau** [comment]
Yeah, let's add Sphinx to the list of Project we should rewrite.

**Comment by minrk** [comment]
Closed by #1255
