### ISSUE TITLE
Using different favicon's would make navigation easier

### ISSUE THREAD

**Issue by jasongrout** [jupyter/notebook#1254]
Migrating from https://github.com/jupyter/jupyter/issues/118:

Since we are tending toward a full OS in the browser... ;-) I think it would help to be able to differentiate the jupyter-js-filebrowser, jupyter-js-editor, jupyter-js-terminal and jupyter-js-notebook navigation tabs from the favicon.

CC @dubourg

**Comment by JamiesHQ** [comment]
Hey @jasongrout : is this still an open issue? thanks!

**Comment by jasongrout** [comment]
I think it's fine to leave it open as a sprint friendly issue for the classic nnotebook, or close it since development is shifting to lab. Either one.

**Comment by JamiesHQ** [comment]
thanks Jason! I'll leave that up to @gnestor

**Comment by jasongrout** [comment]
It is still an unresolved issue, so sure, leave it open. My guess is that we'll close a lot of issues when we sunset the notebook.

**Comment by gnestor** [comment]
Check out https://github.com/jupyter/notebook/pull/2452

**Comment by JamiesHQ** [comment]
^^ @jasongrout ^^
