### ISSUE TITLE
Vertical line next to latex equations

### ISSUE THREAD

**Issue by arokem** [jupyter/notebook#1257]
Anyone else seeing these?

<img width="399" alt="screen shot 2016-03-24 at 12 31 32 pm" src="https://cloud.githubusercontent.com/assets/118582/14028910/61b2d300-f1bc-11e5-938a-dee60407ec06.png">

<img width="203" alt="screen shot 2016-03-24 at 12 24 51 pm" src="https://cloud.githubusercontent.com/assets/118582/14028900/518ff4b2-f1bc-11e5-9793-fed03bce617e.png">

I'm using v4.1.0 from conda, with Chrome Version 49.0.2623.87 (64-bit)

**Comment by auneri** [comment]
Seems like the bug reported in #1010, which was fixed in #1032.

**Comment by arokem** [comment]
Oops. Failed to find that. Closing.
