### ISSUE TITLE
Firefox 45 does not show comments in code cells

### ISSUE THREAD

**Issue by lstagner** [jupyter/notebook#1262]
Works in Chrome
![firefox_jupyter_bug](https://cloud.githubusercontent.com/assets/4305891/14039554/e5430588-f21a-11e5-81ce-269c8a782248.gif)

**Comment by takluyver** [comment]
That's very odd. Did Firefox 45 just come out? I use Firefox, and I'm sure
I would have noticed this.

**Comment by lstagner** [comment]
According to my logs my version of Firefox(45.0+build2-0ubuntu0.15.10.1) was updated on 3-10-16. 2 days after the official release.

**Comment by willingc** [comment]
@takluyver I'm using Firefox (45.0.1) on OS X and comments and markdown are working as expected. Perhaps a Julia kernel or OS specific issue?

**Comment by takluyver** [comment]
Ah, I missed that it was with Julia. It could be an issue with the Julia
mode codemirror is using.

Can you reproduce this in a Python notebook, or only when using Julia?

**Comment by lstagner** [comment]
Yes it fails in a Python notebook as well.

**Comment by takluyver** [comment]
That's very odd. I've just double checked that comments do indeed work for me, and I'm also using Firefox 45 on Linux with Gnome 3 (Fedora).

Is there anything peculiar about your system that could conceivably affect this? Any Firefox extensions? Could it be a caching issue (try running the notebook server on a different port, with `--port 8239`, to avoid the cache)? Are you running a released version of jupyter_notebook, or from master? What version?

**Comment by lstagner** [comment]
I started Firefox in safe mode (all extensions and addons disabled) using a different port and the problem persists.

I installed the notebook(version 4.1.0) using Anaconda

**Comment by takluyver** [comment]
I am grasping at straws here, but is there anything odd in the JS console when this happens? Can you use the DOM inspector (right click, inspect element) to investigate what might be causing it?

**Comment by lstagner** [comment]
I've looked at the JS console and DOM inspector and I didnt notice anything out of the ordinary. (Not that I'm an expert) Below is what the JS console says when I comment and then uncomment the line. 

```
reflow: 3.94ms function textHeight, main.min.js line 3024
reflow: 1.97ms function leftButtonSelect, main.min.js line 3822
reflow: 0.66ms function updateHeightsInViewport, main.min.js line 875
reflow: 0.61ms function paddingVert, main.min.js line 2579
reflow: 1.49ms function textHeight, main.min.js line 3024
reflow: 0.6ms function paddingTop, main.min.js line 2578
reflow: 0.7ms function updateHeightsInViewport, main.min.js line 875
reflow: 0.69ms function paddingVert, main.min.js line 2579
reflow: 0.29ms function visibleLines, main.min.js line 639
reflow: 2.22ms function visibleLines, main.min.js line 639
reflow: 2.62ms function updateHeightsInViewport, main.min.js line 875
reflow: 1.36ms function visibleLines, main.min.js line 639
reflow: 0.61ms function visibleLines, main.min.js line 639
reflow: 0.72ms function updateHeightsInViewport, main.min.js line 875
reflow: 0.07ms function visibleLines, main.min.js line 639
reflow: 0.34ms function visibleLines, main.min.js line 639
```

**Comment by takluyver** [comment]
What did the DOM inspector say the colour and visibility of that comment text should be? Does it show up in the DOM?

Do you have, or have you previously had, any kind of custom CSS or JS that might have affected the notebook?

**Comment by lstagner** [comment]
I haven't had any custom CSS or JS. This is a fresh install of everything. Below is a screen shot of what the DOM inspector says when I have commented out code. 
![screenshot from 2016-03-29 14-04-23](https://cloud.githubusercontent.com/assets/4305891/14123887/7b94d71a-f5b7-11e5-95ae-8b9d116dad3d.png)

**Comment by takluyver** [comment]
The actual code style is in the `CodeMirror-scroll` div a few lines down in the inspector. Can you drill into that?

If you go to https://try.jupyter.org/ , can you reproduce the same thing? i.e. is it an issue with your browser or with your server?

**Comment by lstagner** [comment]
It doesn't work on https://try.jupyter.org/ either. 

I looked at the DOM and when I comment out the line the element changes classes from the `cm-variable` to `cm-comment` which I suspect is the right behaviour. It also seems to correctly changes the computed color to the right value. 

This seems to indicate that something is wrong with my browser. I've actually run into other weird problems as well. I seem to be the only one experiencing this problem so don't kill yourself trying to solve this. You certainty have better things to do.

**Comment by takluyver** [comment]
Well, we like a technical challenge. But yeah, if you can see it on try.jupyter.org too, I think it must be something to do with your browser, and I don't think we can do anything about that. It's really odd, though. I don't know what could be causing that, and I'm pretty sure we've never heard of such a problem before.

**Comment by takluyver** [comment]
In case you didn't already, check whether you have customised any options in Firefox - fonts, accessibility settings, and the like.

**Comment by lstagner** [comment]
I dont believe I do but here are my font settings
![screenshot from 2016-04-03 12-37-53](https://cloud.githubusercontent.com/assets/4305891/14234503/043d8884-f999-11e5-92c9-49c6ee93a893.png)

Just for fun I booted up from the live image I used to install Ubuntu Gnome and the problem went away. So it must of been something unique to my system. Its not the only problem I have with Firefox. For instance, when I search for something on a documentation site I'm making [lstagner.github.io](http://lstagner.github.io/search.html?q=line+of+sight) I get nonsense
![screenshot from 2016-03-29 15-58-23](https://cloud.githubusercontent.com/assets/4305891/14234518/7ec07cc4-f999-11e5-81a8-05ff559af348.png)

But no else does

**Comment by takluyver** [comment]
If you go to the view menu, what is selected under 'text encoding'?

**Comment by lstagner** [comment]
UTF-8 on locally running notebook and my website
windows-1252 on try.jupyter.org

**Comment by takluyver** [comment]
Not sure why it's different on try.jupyter, but I don't think either of those settings should cause the result you see :confused:
