### ISSUE TITLE
Unhelpful error logs from config API on failing to decode JSON

### ISSUE THREAD

**Issue by jcb91** [jupyter/notebook#1269]
From https://github.com/ipython-contrib/IPython-notebook-extensions/issues/555, it would be nice if, when the config API runs into bad JSON and hence fails to load a file from disk, it could include an error log to let the user know which file had the bad JSON in...

**Comment by minrk** [comment]
Migrated to ipython/traitlets#203

**Comment by minrk** [comment]
It certainly should! (I moved the issue over to ipython/traitlets)
