### ISSUE TITLE
getpass. randomise number of dot stored in ntebook.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#127]
Prompted by ipython/ipython/8496,

We don't store getpass but leak length of typed password.

cross link https://github.com/ipython/ipython/issues/8497

**Comment by takluyver** [comment]
Rather than properly randomising, it should probably be a fixed length (30 characters, to make people feel insecure?) so that it doesn't change each time you rerun/resave the notebook.

**Comment by Carreau** [comment]
We already do that. the password I tried was just the same lenght as what we store... :-(

**Comment by alfredo-gimenez** [comment]
Digging this issue back up: is there a way to hide the password length (the character dots) from the notebook browser output?

**Comment by Carreau** [comment]
The number of for stored/shown is always 6 (or 8 I would have to check). So
there is no information leaked there. If that's not the case then this is a
bug.

**Comment by alfredo-gimenez** [comment]
Sorry, I meant from the interactive dialog box. When I type in a password, someone over my shoulder can see the number of dots.

**Comment by takluyver** [comment]
We create a standard `<input type="password">` in the browser; it's your browser that chooses to display dots or not. It's quite common for password fields to show one dot per character - that's the UI I'm used to everywhere except terminals.

**Comment by alfredo-gimenez** [comment]
That makes sense, thanks for the response! It's also helpful to run `clear_output` after `getpass` FWIW
