### ISSUE TITLE
Using global npm modules

### ISSUE THREAD

**Issue by eugenesvk** [jupyter/notebook#1274]
I was trying to use jupyter notebook with a plotly JS addon [plotly-notebook-js](https://github.com/plotly/plotly-notebook-js) to be able to draw plotly charts locally using
[IJavascript engine](https://github.com/n-riesco/ijavascript)

However, I realized that it requires this addon to be installed locally in the path I launch `jupyter notebook` from (see this [issue](https://github.com/plotly/plotly-notebook-js/issues/1#issuecomment-203008741) for more details)

Is it possible for the notebook to be also able to read globally installed modules (`npm -g`) so I don't have to install `npm install plotly-notebook-js` in every place I have a notebook in.

**Comment by captainsafia** [comment]
Thanks for opening this, @eugenesvk! The Notebook isn't actually the interface responsible for importing JavaScript modules, the IJavascript kernel takes care of this. If you open this issue in the IJavascript kernel repository, the maintainer should be able to help you!

**Comment by eugenesvk** [comment]
Thank you for a prompt response! Opened an issue there.
