### ISSUE TITLE
notebook.json key remappings seem to not be taking effect

### ISSUE THREAD

**Issue by rkpatel33** [jupyter/notebook#1276]
Can't for the life of me figure this out.

My json is confirmed to live at `~/.jupyter/nbconfig/notebook.json`:

```
(global)[17:06:02] rishi:.jupyter $ cat ~/.jupyter/nbconfig/notebook.json
{
  "keys": {
    "command": {
        "unbind": [
            "0,0",
            "R"
        ],
        "bind": {
            "0,0": "jupyter-notebook:confirm-restart-kernel-and-clear-output",
            "R": "jupyter-notebook:run-cell-and-select-next"
        }
    }
  }
}
```

And looks like:

```
{
  "keys": {
    "command": {
        "unbind": [
            "0,0",
            "R"
        ],
        "bind": {
            "0,0": "jupyter-notebook:confirm-restart-kernel-and-clear-output",
            "R": "jupyter-notebook:run-cell-and-select-next"
        }
    }
  }
}
```

I got the command name from a module in the repo. Am I missing something?

**Comment by captainsafia** [comment]
Thanks for opening this issue, @rkpatel33! Have you tried implementing your modified keyboard configuration [as a notebook extension](https://jupyter-notebook.readthedocs.org/en/latest/extending/frontend_extensions.html#modifying-key-bindings)? If not, I can help you get started with this and that should do the trick.

**Comment by rkpatel33** [comment]
Thanks for that but not I have not tried it. I figure it was a bit of
overkill for some small keyboard adjustments. Also, I am wondering if I am
going to run into similar issues with extensions if I can't get the built
in key mapper to work.

But thanks for the link, I'll look more. Any ideas on the problem at hand
though?

______________________________________
Rishi K. Patel
​, ​
Founder
​,
www.docnavapp.com
*​*
​
rishi@docnavlab.com
​,
917-647-0892​
LinkedIn <https://www.linkedin.com/in/rkpatel33>, @docnavlab
<https://twitter.com/docnavlab>

**Comment by jcb91** [comment]
There is in fact already a configurable keyboard shortcut remapper at https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/keyboard_shortcut_editor

I'm afraid I didn't even know about the built-in mapper until I read this issue, though, so can;t help you there yet...

**Comment by rkpatel33** [comment]
Yup, I saw that. Wish there was a H1 boldface link in the main repo README to this one as its super helpful.

**Comment by Carreau** [comment]
marking as 5.0. Damn some of these extensions should be in the notebook by default.

**Comment by takluyver** [comment]
@Carreau now that the keyboard shortcut editor is there in master, can this be closed?

**Comment by Carreau** [comment]
> @Carreau now that the keyboard shortcut editor is there in master, can this be closed?

Yes, and that works for me on master. Closing

https://github.com/jupyter/notebook/pull/2104 shoudl make finding the editting capabilities easier.
