### ISSUE TITLE
Tab complete bug?

### ISSUE THREAD

**Issue by brianbreitsch** [jupyter/notebook#128]
This might be a bit difficult to explain, so I'll try my best..

When I use tab complete and a word is the only possible word, everything works fine:

    from package import m

followed by `<tab>` yields

    from package import module

if `package` only contains `module`. But if `package` contains `module1` and `module2`, the popup yields:

    module1
    module2

with `module1` highlighted. Then if I press tab to complete, I end up with something like:

    from package import moduleodule

This isn't necessarily limited to imports. It happens generally as far as I can tell.

IPython version: 3.0.0, running Jupyter notebook
As far as I can tell, my IPython profile does not appear to make any changes related to this behavior.

**Comment by Carreau** [comment]
Are you a fast typist ? does it behave like that if you press keys one after the other ?
If it's the case than it's a race condition we are aware of.

**Comment by brianbreitsch** [comment]
Hmm--no I don't think that's it--it's very specific.
I played around with it some more and I have a better idea of how to recreate it.
Try to import `asarray_chkfinite`.
Type in `asarray`.
Tab will bring up `asarray` and `asarray_chkfinite`.
Add `_` to reduce the list to `asarray_chkfinite`.
Tab, according to my understanding, should enter `asarray_chkfinite`, but I get `asarray_chkfinitechkfinite`

**Comment by Carreau** [comment]
Can you check on 3.1 ? because slowly I can definitively not reproduce. I know that with latency you can to `m<tab>` , type `plotlib`, completion get back then you get `matplotlibplotlib`. I can sometime have it, but I need to be relatively fast on the `tab-underscore-tab`.

Are you on a slow network maybe ?

**Comment by brianbreitsch** [comment]
Oh--doesn't do it anymore in 3.1.
My bad..maybe if someone else has the same issue, this'll remind them to update.
Thanks for investigating!

**Comment by Carreau** [comment]
Yep that seem like https://github.com/ipython/ipython/pull/7889 fixed that, I vaguely remember writing that ...
