### ISSUE TITLE
Native kernel (python2) not available

### ISSUE THREAD

**Issue by majure** [jupyter/notebook#1280]
Jupyter notebook has broken for me, despite about a month of smooth use and no major changes to my setup. I have ipython 2.7.6 installed, and it still works. When I run `jupyter notebook` I get an error saying 'Native kernel (python2) is not available'. I have not found many solutions online that seem applicable to this situation.

**Comment by takluyver** [comment]
I don't know how you've got there, but that error message means that it can't import `ipykernel`. If you install that package, it should work.

**Comment by majure** [comment]
`pip install ipykernel
Requirement already satisfied (use --upgrade to upgrade): ipykernel in /usr/local/lib/python2.7/dist-packages
Cleaning up...
`
Pip claims it is already there. Is there an alternate way I should try to install it?

**Comment by takluyver** [comment]
Maybe it's something that depends on that is missing. In a Python shell, can you try:

```python
from ipykernel.kernelspec import RESOURCES
```

**Comment by majure** [comment]
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-69c17dfa3e50> in <module>()
----> 1 from ipykernel.kernelspec import RESOURCES

/usr/local/lib/python2.7/dist-packages/ipykernel/__init__.py in <module>()
      1 from ._version import version_info, __version__, kernel_protocol_version_info, kernel_protocol_version
----> 2 from .connect import *

/usr/local/lib/python2.7/dist-packages/ipykernel/connect.py in <module>()
     12 
     13 from IPython.core.profiledir import ProfileDir
---> 14 from IPython.paths import get_ipython_dir
     15 from ipython_genutils.path import filefind
     16 from ipython_genutils.py3compat import str_to_bytes

ImportError: No module named paths
`

**Comment by takluyver** [comment]
That means it's finding an old version of IPython somewhere - try uninstalling and reinstalling the IPython package. If you've installed IPython with something like apt, uninstall that copy.

**Comment by majure** [comment]
I don't know how that showed up or why it wasn't a problem a few days ago, but that was it. `sudo apt-get remove --purge ipython` worked.

**Comment by takluyver** [comment]
I would guess that something got installed using setuptools, it created one
of its horrible .pth files and messed up your sys.path, making the system
installed IPython take precedence over the newer version you have. That is
a long-standing issue with setuptools.

**Comment by majure** [comment]
Thanks.

**Comment by ducha-aiki** [comment]
@majure thank you very much!

**Comment by borisbolliet** [comment]
Thank you @majure, this worked for me too.

**Comment by xiaoyun4** [comment]
Thank you @majure, it worked for me.

**Comment by gregroberts** [comment]
If anyone is still having this issue, for me it was solved by simply running

    pip install --upgrade ipykernel

without the need for uninstalling ipython entirely

**Comment by lifematrix** [comment]
@gregroberts it works for me too. Thanks!

**Comment by otayeby** [comment]
Thank you @gregroberts , I just want to note that this worked for me when I had the same error on PyCharm.
