### ISSUE TITLE
kernel doesn't receive initial kernel_info_request

### ISSUE THREAD

**Issue by FilippoPolo** [jupyter/notebook#1281]
Hi all,
I'm trying to get to the bottom of a nagging problem with the IFSharp kernel. Basically, I'm always getting "timeout waiting for kernel_info reply" whenever I start the kernel. It still works, but the kernel doesn't receive that first request. This is annoying because it means I can't set the protocol version, and I'd really like to be able to tell Jupyter that I want to use a previous version of the protocol.

So far, the only interesting thing I was able to find is that Jupyter seems to attempt to open the shell socket very quickly after launching the kernel process. I'm fairly sure that by that time the shell socket is not open yet. I've tried running the kernel with a debugger, and I'm not receiving any messages until the timeout happens.

Here's the --debug log.

[D 16:29:45.534 NotebookApp] Found kernel ifsharp in C:\Users\____\AppData\Roaming\jupyter\kernels
[D 16:29:45.537 NotebookApp] Native kernel (python3) available from C:\Anaconda3\lib\site-packages\ipykernel\resources
[D 16:29:45.540 NotebookApp] Starting kernel: ['C:/Users/____/Source/Repos/IfSharpLocal/src/IfSharpConsole/bin/x64/Debug/ifsharp.exe', 'C:\\Users\\____\\AppData\\Roaming\\jupyter\\runtime\\kernel-d2f14505-29fb-4370-ba43-2aab9384e3f0.json']
[D 16:29:45.550 NotebookApp] Connecting to: tcp://127.0.0.1:44368
[I 16:29:45.557 NotebookApp] Kernel started: d2f14505-29fb-4370-ba43-2aab9384e3f0
[D 16:29:45.559 NotebookApp] Kernel args: {'kernel_name': 'ifsharp', 'cwd': 'C:\\Users\\____\\Desktop'}
[D 16:29:45.562 NotebookApp] 201 POST /api/sessions (::1) 139.11ms
[D 16:29:45.566 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_selection.js?v=20160330162937 (::1) 2.00ms
[D 16:29:45.572 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_selectioncontainer.js?v=20160330162937 (::1) 1.00ms
[D 16:29:45.577 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_string.js?v=20160330162937 (::1) 1.00ms
[D 16:29:45.581 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_controller.js?v=20160330162937 (::1) 1.00ms
[D 16:29:45.585 NotebookApp] Found kernel ifsharp in C:\Users\____\AppData\Roaming\jupyter\kernels
[D 16:29:45.587 NotebookApp] Native kernel (python3) available from C:\Anaconda3\lib\site-packages\ipykernel\resources
[D 16:29:45.591 NotebookApp] Serving kernel resource from: C:\Users\____\AppData\Roaming\jupyter\kernels\ifsharp
[D 16:29:45.594 NotebookApp] 200 GET /kernelspecs/ifsharp/kernel.js?v=20160330162937 (::1) 9.01ms
[D 16:29:45.597 NotebookApp] Initializing websocket connection /api/kernels/d2f14505-29fb-4370-ba43-2aab9384e3f0/channels
[D 16:29:45.604 NotebookApp] Requesting kernel info from d2f14505-29fb-4370-ba43-2aab9384e3f0
[D 16:29:45.606 NotebookApp] Connecting to: tcp://127.0.0.1:44365
[D 16:29:45.611 NotebookApp] 200 GET /static/custom/fsharp.css (::1) 1.00ms
[D 16:29:45.614 NotebookApp] 200 GET /static/custom/ifsharp_logo.png (::1) 1.00ms
[D 16:29:45.617 NotebookApp] 200 GET /static/components/codemirror/addon/mode/loadmode.js?v=20160330162937 (::1) 1.00ms
[D 16:29:45.622 NotebookApp] 200 GET /static/custom/fsharp.js?v=20160330162937 (::1) 1.00ms
[D 16:29:45.627 NotebookApp] 200 GET /static/custom/webintellisense.js?v=20160330162937 (::1) 1.00ms
[D 16:29:45.632 NotebookApp] 200 GET /static/components/backbone/backbone-min.js?v=20160330162937 (::1) 2.00ms
[D 16:29:45.636 NotebookApp] 200 GET /static/custom/webintellisense-codemirror.js?v=20160330162937 (::1) 1.00ms
[D 16:29:45.648 NotebookApp] 304 GET /nbextensions/widgets/widgets/css/widgets.min.css (::1) 1.00ms
[D 16:29:46.372 NotebookApp] 304 GET /static/components/jquery-ui/themes/smoothness/images/ui-icons_222222_256x240.png (::1) 1.00ms
[W 16:29:55.622 NotebookApp] Timeout waiting for kernel_info reply from d2f14505-29fb-4370-ba43-2aab9384e3f0
[D 16:29:55.625 NotebookApp] Opening websocket /api/kernels/d2f14505-29fb-4370-ba43-2aab9384e3f0/channels
[D 16:29:55.627 NotebookApp] Connecting to: tcp://127.0.0.1:44365
[D 16:29:55.630 NotebookApp] Connecting to: tcp://127.0.0.1:44366
[D 16:29:55.632 NotebookApp] Connecting to: tcp://127.0.0.1:44367

Any ideas?

**Comment by takluyver** [comment]
> Jupyter seems to attempt to open the shell socket very quickly after launching the kernel process. I'm fairly sure that by that time the shell socket is not open yet.

This shouldn't be an issue with ZMQ sockets, though it's always possible that something is not working correctly. The server does not need to bind the socket before the client connects to it - the client can connect, and the connection will be made when the server binds to the socket.

**Comment by FilippoPolo** [comment]
That's what I thought too, but I can't find anything else. I'd love to have some other hypothesis to test.

**Comment by minrk** [comment]
If it's not getting the request at all, then something is probably wrong, on one side or the other, in terms of which sockets/ports are in use. Wrong socket types or incorrectly loading port info is a possible cause.

**Comment by FilippoPolo** [comment]
Everything is fine on the kernel side as far as I can tell. If it was binding to the wrong port, then it wouldn't work at all. As for the socket type, it's a "router socket". I'm not terribly familiar with NetMQ, but it sounds like the correct type.

**Comment by pblasucci** [comment]
I realize this is kind of silly but: have you tried a longer timeout setting on the client?

Also, is there a minimal reproduction sample? Seems like one shouldn't need the whole shebang to explore this. Alternately, can you link to the code in question?

**Comment by FilippoPolo** [comment]
How do I increase the client timeout setting?

Regarding reproduction, as far as I can tell this happens reliably in every instance of using the IFSharp kernel. The code that prepares the sockets is at the beginning of https://github.com/fsprojects/IfSharp/blob/master/src/IfSharp.Kernel/Kernel.fs

**Comment by pblasucci** [comment]
Hmm... If memory serves, `NetMQ` provides overloaded sending and receiving methods which allow you to specify a timeout.

**Comment by FilippoPolo** [comment]
The client is Jupyter. I can't change that; I mean, I could in theory but in practice I'm not a Python developer. Also, Jupyter can connect with other kernels fine, so the problem is not there. I don't know if Jupyter has an option to influence timeouts.

The expected protocol is the Jupyter protocol (specifically, I'm talking about the kernel_info request). I'm using a router socket; as far as I'm aware of, that's the correct type.

**Comment by takluyver** [comment]
The kernel_info timeout does not appear to be configurable at the moment, but if you think your kernel might be taking more than 10 seconds to start responding, you can try changing the code in

```
notebook.services.kernels.handlers.ZMQChannelsHandler.kernel_info_timeout
```

**Comment by FilippoPolo** [comment]
The kernel is not taking more than 10 seconds to start. It's just not receiving that initial kernel_info_request at all. So it starts and sits there.

**Comment by pblasucci** [comment]
It's almost certainly an issue with the F# Kernel. I was merely suggesting a possible work-around and trying to determine what level of debugging (if any) you'd done thus far.

As to the actual problem:

+ Where is the Jupyter protocol documented (esp. the `request_info` message flow)?
+ The log you posted seems to be from the broker; do you have any sort of logs from the kernel?

**Comment by FilippoPolo** [comment]
I'm getting documentation from here: http://jupyter-client.readthedocs.org/en/latest/messaging.html#kernel-info
I've followed the kernel via debugger. I'll add logs so I have something to post.

**Comment by FilippoPolo** [comment]
I've finally identified and fixed the problem. Thanks for all your suggestions. The fixed version is at https://github.com/fsprojects/IfSharp/tree/jupyter

**Comment by KelvinJin** [comment]
@FilippoPolo Hey. I wonder how did you fix this issue at the end? I might have the same issue with a swift kernel I'm building. It would be nice to know your solution to this. Thanks!

**Comment by FilippoPolo** [comment]
Hi! Sorry for not answering sooner. I've found 
https://github.com/jupyter/notebook/issues/2118 and I assume that's your 
issue? I see you found out about the identity issue yourself; that was 
indeed the same problem we had in the F# kernel. More precisely, if I 
recall correctly, in our case the kernel was making assumptions on the 
format of the identity strings. Those assumptions no longer held true 
with more recent versions of ZMQ, and as a result it was sending back 
the wrong strings.

Cheers,

     Filippo


Il 03/02/2017 01.23, Jin Wang ha scritto:

**Comment by KelvinJin** [comment]
@FilippoPolo Aha, thank you so much for your reply. I actually looked at your code and realised that there might be something wrong with the identity stuff. I didn't really understand the problem though since there's no error printed by Jupyter. But anyway, the initial reply can be received now after I followed your changes. So thanks!

I'm now stuck at the message signature. I just can't get it work...can't even rebuild it using python...I might have a look at your code again to figure out. Even the spaces inside the serialised JSON strings will effect the encryption result...`"{"value": "key"}"` is different from `"{"value":"key"}"` where the former has a space there...There little things have driven me crazy...

**Comment by takluyver** [comment]
Signatures are tricky, especially because you can only see 'is this right' - there's no way to know what is wrong, or how close you are.

The trick with JSON serialisation is that you need to serialise your messages, sign the serialised version, and then send that. Don't serialise it twice. Your serialisation doesn't have to match how Python would serialise it, because we check the signature on the serialised message before parsing it.

In pseudocode:

```
serialised = json(msg)
signature = sign(serialised)
send(signature, serialised)
```

Have a look at the code in [simple_kernel](https://github.com/dsblank/simple_kernel/blob/c5ae07ed4912c37b701eda35ff26bd747d0627d7/simple_kernel.py), which reimplements a kernel in Python without all of our libraries.
