### ISSUE TITLE
matplotlib nbagg backend skips over cell directly after plotting cell

### ISSUE THREAD

**Issue by michaelaye** [jupyter/notebook#1284]
Hm, the link for 'guidelines for contributing' does not help (anymore?) with how I should create a new issue on Github. Anyhow, hope I assemble all that's required.

What happens is that when going through notebook cells with Shift-Enter, while the `%matplotlib nbagg` backend is active, the cell right after a plot would be selected, but then pressing Shift-Enter on it does not execute it.

As a little proof, I link [here a notebook](https://gist.github.com/michaelaye/3d87e5a0714fa8c5a32604b7bb714463) where I first cleared all output and then run through it with Shift+Enter. As one can see the cell after the plot is being skipped over.

I remember that before (weeks ago) the backend even insisted on clicking somewhere before one at all can go further, which is also not so nice, but it seems that there was progress on this to be able to do things without going to the mouse while going through, maybe introducing this little problem?

Here are my versions:
OSX 10.10.5, using Safari 9.1, pandas 0.18 for the plot in above notebook

```bash
┌─( ~/D/s/pyuvis λ:master | ✱ ◼ ff447a5 )─────────────────────────────────────────────( @macd2860 )─┐
(stable)└─❱❱❱ conda list|grep matplotlib                                              +4573 14:11 ❰─┘
matplotlib                1.5.1               np110py35_0    defaults

┌─( ~/D/s/pyuvis λ:master | ✱ ◼ ff447a5 )─────────────────────────────────────────────( @macd2860 )─┐
(stable)└─❱❱❱ conda list|grep notebook                                                +4574 14:11 ❰─┘
notebook                  4.1.0                    py35_2    defaults
```

**Comment by jorisvandenbossche** [comment]
I think this is a duplicate of what I reported here: https://github.com/jupyter/notebook/issues/1124

**Comment by michaelaye** [comment]
Agreed.
