### ISSUE TITLE
ENH: allow Markdown footnotes

### ISSUE THREAD

**Issue by stsievert** [jupyter/notebook#1287]
Several times I've desired footnotes while typing up notebooks, typically in the form of homeworks/labs. These footnotes could be used as citations/references/sidenotes/etc.

Of course, it'd be nice to have a return link in the footnote in the form of ↩, similar to the [footnotes on marco.org](https://marco.org/2016/03/14/overcast25#fn:pmvn03Klkuploads).

**Comment by willingc** [comment]
Hi @stsievert, Thanks for submitting this enhancement issue. Let me ping @Carreau who may have some insights on what could be done now and in the future.

**Comment by Carreau** [comment]
Hi @stsievert , 

Unfortunately  footnotes are not in the markdown or commonmark spec, and there is a lot of requests for markdown extension: Footnote, TOC, label, reference, , which each having multiple syntax... And the team does not have the bandwidth to maintain the multiple parser and formatter to support all of that. 

So for now the response we give to any proposal to extend the markdown syntax beyond basic markdown is : "Not before the CommonMark spec and implementation does not have a way to extend markdown, and enough packages support these features". 

Sorry to respond by negative, hope we can revisit in a year or so.

**Comment by stsievert** [comment]
Footnotes are in the kramdown spec, which also has Github-flavored markdown. Maybe this would be worth switching to in the future… it seems pretty widely used. Github-flavored markdown doesn’t seem to be going anywhere and kramdown has good support (jekyll’s new default, etc).



On April 1, 2016 at 11:45:22 AM, Matthias Bussonnier (notifications@github.com) wrote:

Hi @stsievert ,

Unfortunately footnotes are not in the markdown or commonmark spec, and there is a lot of requests for markdown extension: Footnote, TOC, label, reference, , which each having multiple syntax... And the team does not have the bandwidth to maintain the multiple parser and formatter to support all of that.

So for now the response we give to any proposal to extend the markdown syntax beyond basic markdown is : "Not before the CommonMark spec and implementation does not have a way to extend markdown, and enough packages support these features".

Sorry to respond by negative, hope we can revisit in a year or so.

**Comment by Edenharder** [comment]
Then I'd like to know, is it possible to change to another renderer of markdown. If it's possible, some users can create or find the renderer they want by themselves, and will not trouble the project members to do that.

**Comment by syoungs67** [comment]
Its been over a year, and I am experiencing a similar desire. Is the footnote extension supported as of yet @Carreau?

**Comment by Carreau** [comment]
> Its been over a year, and I am experiencing a similar desire. Is the footnote extension supported as of yet @Carreau?

No, we are currently trying to formalize our markdown spec. Then we might start to introduce features. It will take a wile as we still have low manpower. Sorry for the waiting.

**Comment by HEHenson** [comment]
I too would love to see a footnote like feature in Jupyter notebooks.  It could take the form of a link to a small bubble similar to some of the comment features you see in other packages.

**Comment by dsblank** [comment]
You might be able to use, or adapt our bibtex reference extension from our Calysto Document Tools. It is now found here: https://github.com/Calysto/notebook-extensions I think it would be pretty easy to make a footnote version.

You can see an example video here: https://www.youtube.com/watch?v=86FTd1pcoZ4

And here is a picture after clicking the Reference button. The secret is in the `#cite-` reference in the markdown.

![screenshot from 2017-08-09 19-48-12](https://user-images.githubusercontent.com/168568/29148550-2f231b40-7d3c-11e7-8cd4-6d9dbe5e2232.png)

**Comment by HEHenson** [comment]
That could be ideal.  Then it might be possible to share old bibtex files with Jupyter Notebooks!

**Comment by trevery** [comment]
Here is my way:

This is a example of footnote[<sup>1</sup>](#fn1). Another footnote[<sup>2</sup>](#fn2).


---
Footnote

<span href="#fn1"> footnote 1</span>
<span href="#fn2"> footnote 2 </span>

just use markdown `[](#any_name)` and a little html `<span href="#any_name" footnote content </span>`
```
This is a example of footnote[<sup>1</sup>](#fn1). Another footnote[<sup>2</sup>](#fn2).

<span href="#fn1"> footnote 1</span>
<span href="#fn2"> footnote 2 </span>
```

**Comment by casperdcl** [comment]
> just use markdown `[](#any_name)` and a little html `<span href="#any_name" footnote content </span>`

lol when markdown becomes markup

**Comment by HTenkanen** [comment]
Any updates on this? Would ❤️ if the support for footnotes would be added to Notebooks.

**Comment by jamesowers-ch** [comment]
> > just use markdown `[](#any_name)` and a little html `<span href="#any_name" footnote content </span>`
> 
> lol when markdown becomes markup.
> 
> If you don't mind hover tooltips:
> 
> ```lisp
> This is a example of footnote and tooltip[<sup>1</sup>](#fn1 "footnote and tooltip 1").
> Another footnote[<sup>2</sup>](#fn2).
> Another tooltip[<sup>3</sup>](#_blank "tooltip 3").
> 
> <span id="fn1">footnote and tooltip 1</span>
> <span id="fn2">footnote 2</span>
> ```
> 
> This is a example of footnote and tooltip[1](#fn1).
> Another footnote[2](#fn2).
> Another tooltip[3](#_blank).
> 
> [1](#fn1) footnote and tooltip 1
> [2](#fn2) footnote 2

This example doesn't print the leading sup 1 or 2 in the footnotes for me - I copy pasted your code into a markdown cell in a jupyter notebook. Does it still work for you?

**Comment by casperdcl** [comment]
> This example doesn't print the leading sup 1 or 2 in the footnotes for me - I copy pasted your code into a markdown cell in a jupyter notebook. Does it still work for you?

Ah just a minor mistake on my part not syncing the raw code snippet. Updated comment.

**Comment by jamesowers-ch** [comment]
Oh that's lovely, thank you!

**Comment by tonyfast** [comment]
This feature will exist as a community extension in the future Notebook v7 release using the https://github.com/executablebooks/jupyterlab-myst .

For more information about this new release, checkout the [Notebook v7 Enhancement Proposal](https://github.com/jupyter/enhancement-proposals/blob/master/79-notebook-v7/notebook-v7.md).
