### ISSUE TITLE
Version number Missing in about dialog.

### ISSUE THREAD

**Issue by korniichuk** [jupyter/notebook#129]
Jupyter notebook: *Help* -> *About*

About Jupyter Notebook
Server Information:
You are using Jupyter notebook.
The version of the notebook server is **-5c18ecb** and is running on:

**Comment by Carreau** [comment]
i don't  understand the question...

**Comment by korniichuk** [comment]
It's not a question. It's info about bug, mistake.
"version of the notebook server is **-5c18ecb**" -- is it normal version format?!

**Comment by Carreau** [comment]
ah, depends on how you instsall it, it should show `X.y.z-<commitish>` with `<commitish>`  only if you install from git. `X.y.z` missing is not normal.

**Comment by minrk** [comment]
Fixed by #132. It was a remnant of the renaming leaving out the notebook version.
