### ISSUE TITLE
tab in empty function parens should bring up better completitions

### ISSUE THREAD

**Issue by janschulz** [jupyter/notebook#1296]
add a function call into a cell and put the cursor into the empty parens and press tab: you get the completions for globals (Mostly Exceptions), but not the competitions for the functions (ok you get them, but they are down after a lot of other stuff...). I always have to press shift-tab to get information what the function accepts. Please, please, if there is any way, please, change it so that lists the function parameters first (they are visible as "parameter=", so this could even be done as postprocessing in the notebook...).

Another thing: clicking on the scollbar to drag it down will close the popup -> I have to scroll via arrow key or mouse scrolling...

[Interestingly, the r kernel only displays the function arguments in that situation, so yay R kernel!]

**Comment by Carreau** [comment]
First part is likely an IPython thing. Would [the issue about Jedi](https://github.com/ipython/ipython/issues/8606) solve that ?

Second seem to be a UI bug, we'll investigate.

**Comment by takluyver** [comment]
Jedi may improve matters, but we may also need to be smarter about prioritising completions - at the moment, I think we mostly display it in alphabetical order with little regard for what's most likely to be used (except for demoting things starting with underscore).

**Comment by janschulz** [comment]
IMO it would be a big improvement, if the completer would simple sort everything which has a `"="` in the last place of the item to the front: if request is in a function call, this will be the parameter to the function call and if not, there won't be such items.

**Comment by Carreau** [comment]
> IMO it would be a big improvement, if the completer would simple sort everything which has a "=" in the last place of the item to the front: if request is in a function call, this will be the parameter to the function call and if not, there won't be such items.

That's should now be done if you are on master.

**Comment by JamiesHQ** [comment]
Hi @janschulz : Me again! Is this still an open request? thanks!

**Comment by janschulz** [comment]
Both of the reported problems seems to be gone with the latest ipykernel from conda forge. Thanks a lot!
