### ISSUE TITLE
js build tool.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#13]
Would a gulp-file, or any other js-based tool that is usefull be accepted here ? 
Something like watching js/css file and build or are we still in a everything-should-be-in-setup.py ?

**Comment by minrk** [comment]
I'm not sure, let's talk about it tomorrow.

**Comment by Carreau** [comment]
Added on notes.

**Comment by jdfreder** [comment]
From the meeting - let's give gulp a go.
