### ISSUE TITLE
Is it possible to add notebook metadata, like a description which shows up in the notebook file view?

### ISSUE THREAD

**Issue by minad** [jupyter/notebook#130]
This would be great for try.jupyter.org and for bundled/containerized notebook archives. Alternatively render the README.md from the current directory under the file view as github does it.

**Comment by Carreau** [comment]
That would require to open/read/parse each file in a directory which we don't want to do. 
Try-jupyter is "just" the notebook app, we probably won't add features that don't apply to local server.

**Comment by minad** [comment]
Well, it needs some effort. But I think it could also be done in a performant way using ajax and by only parsing the first <n> bytes of the ipynb file, which is not a problem unless you have like thousands of ipynb files in a directory, which nobody should have ;)

I would also like to have it for the local server/containers and not only for try.jupyter.org.

**Comment by minad** [comment]
I think for like a few hundred files you wouldn't even notice if the information is loaded with all the other data. Also you could cache the data in the server.

**Comment by Carreau** [comment]
1) Problem is many people do run notebooks on NFS filesystems, so you would notice the difference. People already have issues. 

2) The data ordering in json is not guarantied, the bytes would be the last bytes of the fileformat curently, unless people add keys in which case the metadata could be somewhere else. 
It also break the storage layer as we don't assume things are on disk. 

Cache is not a solution,  people do use other application to modify `.ipynb` and you don't get notified when the file change. 

We did speak about things like that for several hours, like in person at our dev meeting. 
There is no reasonable solution as far as we can tell, or the complexity and requirement are probably not worth the gain.

**Comment by minad** [comment]
Maybe low-priority-background thread or caching+mtime-checking could be the way to handle this. I mean this is not a critical thing it wouldn't be a problem if it loads slowly or shows obsolete information from time to time.

The question about complexity vs. gain is always the question :)

**Comment by takluyver** [comment]
For now we want to steer clear of anything putting anything from the files' contents in the directory listing.

It's too slow to do synchronously - I just clocked reading+parsing 10 fairly small ipynb files at 0.5s, and even just opening and reading 500 bytes from each with no parsing at 0.3s. It definitely wouldn't be unreasonable to have several dozen notebooks in one directory, and listings should work into the hundreds of notebooks, whether or not we think it's a good idea to arrange things like that.

As you say, it's possible to do this with smart caching and background threads or processes to update the cache. And we might want to do that at some point. But that sounds like significant extra complexity, and I think there are other things we want to focus on for now.
