### ISSUE TITLE
Running Notebooks/Terminals - Shutdown automatically after specified time

### ISSUE THREAD

**Issue by shamsulbuddy** [jupyter/notebook#1300]
I am using Jupyter notebook in a multiuser mode , means many people are running their notebooks in their specified folders in a shared environment. One problem which I can see is that even if they logged out , their notebooks/terminals keeps on running forever , so every now and then I have to go the running tabs and "Shutdown" the notebooks and terminals manually. Is there a way with which we can shutdown the notebooks and terminal after a specified time ?

**Comment by takluyver** [comment]
Do you mean you're using Jupyterhub? If so, there is a script here which can cull idle servers periodically:

https://github.com/jupyter/jupyterhub/blob/master/examples/cull-idle/cull_idle_servers.py

**Comment by shamsulbuddy** [comment]
No its not Jupyterhub .. its just a normal single instance of Jupyter which is password protected and our whole team login to it using https://server-ip:8888/tree

**Comment by takluyver** [comment]
OK. Then no, at present there is nothing like that, but we're talking about adding some functionality to make it possible, in #1241.

**Comment by JamiesHQ** [comment]
@shamsulbuddy : We're doing a little housekeeping on our issue log and noticed this thread from 2016. Has this issue been resolved to your satisfaction and can it be closed? thanks!

**Comment by nabriis** [comment]
Hi,

I think this functionality should be implemented.
We are also running a multi user envoirment, with JupyterHub and shutting down idle servers.
However, if people keep working during the day, the number of open notebook kernels stacks up quite high.

Maybe a flag that could be set such that kernels for which there is no current browser tab open shuts down after a while. My experience is that most people shut down the browser tab and excpect the kernel to stop from this.

**Comment by takluyver** [comment]
Culling idle kernels is coming in 5.1, see #2215.

**Comment by takluyver** [comment]
Also #2498 for extra config options.

**Comment by bhavintandel** [comment]
@nabriis May I know, how exactly are you culling idle servers ?
