### ISSUE TITLE
Missing Command Toolbar

### ISSUE THREAD

**Issue by Exid87** [jupyter/notebook#1301]
Hello,

I'm missing the command toolbar that has Play/Stop/Etc.. on the top of the notebook.
![upload](https://cloud.githubusercontent.com/assets/18270082/14260042/70927182-fa5e-11e5-9e1b-3c05254ba095.png)

**Comment by takluyver** [comment]
That's not a notebook, that's a text file. We supply a simple editor for text files, but it's quite limited. There are many other text editors available.

Notebooks are the files with `.ipynb` extensions.
