### ISSUE TITLE
EXIF Viewer extension for Chrome have a conflict with Jupyter Notebook

### ISSUE THREAD

**Issue by alejandrobll** [jupyter/notebook#1302]
While not a problem related to Jupyter Notebook itself, I find useful to report that the Google Chrome extention "EXIF Viewer" by Aruna prevents Chrome from rendering the Notebook interface. It makes me think that there are probably other extensions that can affect Jupyter Notebook as well. Any idea on what can cause it?

**Comment by takluyver** [comment]
What do you see when you try?

**Comment by alejandrobll** [comment]
I actually see nothing. When trying to connect to the notebook server, I only see a white screen on Chrome. I realized that this was a problem with the extensions and the notebook loaded correctly when using "incognito mode". I tried switching on each extension one by one and it turns out that the problematic one was "EXIF Viewer". 

The error I see in the Console is:

require.js?v=640929d…:166 Uncaught Error: Mismatched anonymous define() module: function (){return $}
http://requirejs.org/docs/errors.html#mismatch
makeError @ require.js?v=640929d…:166
intakeDefines @ require.js?v=640929d…:1229
(anonymous function) @ require.js?v=640929d…:1416

**Comment by Carreau** [comment]
That seem like an issue with Exif Viewer itself. THoug I can find many extension named "Exif Viewer" so it's hard to go further than that. Seeing the error message, IPython notebook is not the only thing it will create issue with, so not sure what we can do except trying to contact the author.

**Comment by alejandrobll** [comment]
Yes, it seems to be an issue of the extension rather than notebook. I just thought that you could probably learn something from that behaviour. Just in case, I attach an image of the extension icon:

![image](https://cloud.githubusercontent.com/assets/7341581/14265770/58e2735e-fabb-11e5-826f-6c97d4c8e2c4.png)

**Comment by JamiesHQ** [comment]
@alejandrobll : We're doing a little housekeeping on our issue log and noticed this thread from 2016. Is this still an open request and is there anything else we can do to help you try to resolve it? thanks!

**Comment by alejandrobll** [comment]
@JamiesHQ It is not an issue for me anymore. Not sure whether the issue is still present, but nothing to worry about, I guess.

**Comment by JamiesHQ** [comment]
Ok, thanks @alejandrobll !
