### ISSUE TITLE
run all cells stops when except occurred

### ISSUE THREAD

**Issue by ruoyu0088** [jupyter/notebook#1303]
Currently "run all" command will stop executing if one of the cells raise exception. I am writing a book by using notebook, sometimes I will show some code that raise except intended. 

I want to known are there any method to allow continue executing when exception raised.

**Comment by takluyver** [comment]
Currently there is nothing that I know of to do this in the notebook, though it may be possible to write an extension to do it.

If you run notebooks with nbconvert, there is an option to allow exceptions and carry on (`ExecutePreprocessor.allow_errors`).

**Comment by juhasch** [comment]
The `runtools` extension from https://github.com/ipython-contrib/IPython-notebook-extensions supports this. 

The actual code is shown below with the relevant part being `cell.execute(false)'
```Javascript
    var execute_all_cells_ignore_errors = function () {
        for (var i=0; i < IPython.notebook.ncells(); i++) {
            IPython.notebook.select(i);
            var cell = IPython.notebook.get_selected_cell();
            cell.execute(false);
        }
    };
```

**Comment by takluyver** [comment]
Thanks Juergen :)

**Comment by ruoyu0088** [comment]
Thanks, I forgot to check the IPython notebook extensions.

**Comment by sumendar** [comment]
Hi, where we should add this code to work this feature?

**Comment by juhasch** [comment]
Using runtools you can click the `Execute all cells, ignore exceptions` button.
Or you can paste the code above in your browser Javascript console, and type
`execute_all_cells_ignore_errors()` in you browser Javascript console to execute all cells.

**Comment by sumendar** [comment]
Thank you @juhasch,  I forgot to mention that i am using R script in ipython notebook, it seems to be runtools only working for python code, bcz i tested on sample python code its working pretty good!, but the button is not executing my R scripts cell with error exception. any suggestions

**Comment by juhasch** [comment]
Runtool doesn't know about the used language. I guess this feature is just not implemented in the R Jupyter kernel.

**Comment by takluyver** [comment]
I think this PR should address it: https://github.com/IRkernel/IRkernel/pull/468

**Comment by shzhng** [comment]
i'll add a test to that PR and get it in
