### ISSUE TITLE
ReadTheDocs not rendering notebook after a recent PR

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#1305]
@takluyver Would you mind checking if it is rendering on your system?

<img width="691" alt="screen shot 2016-04-05 at 6 36 26 pm" src="https://cloud.githubusercontent.com/assets/2680980/14303220/8d1d0fc4-fb5d-11e5-963d-57dddef75409.png">

**Comment by willingc** [comment]
Checking if PR #1266 or #1304 introduced a new issue.

**Comment by willingc** [comment]
Looks like the CSS changes (two commits: b3788c283fecf7a68f2d054ada12eaa5339d9323 and 9c56f4577db0b9c823d4f34c3350f982ef835368) in #1266 is the cause of RTD to display as above. The commits build fine locally and pass as green on RTD yet the rendering is incorrect. I will modify if I can in a new PR within an hour; otherwise, I will revert #1266

**Comment by willingc** [comment]
@mgeier I'm not sure why the custom CSS did not render properly on RTD. Thanks for your work on PR #1266. I only backed out the code that was giving RTD trouble.

**Comment by mgeier** [comment]
I suspect that this is actually a RTD bug: https://github.com/rtfd/readthedocs.org/issues/2116.

**Comment by willingc** [comment]
@mgeier I agree. Thanks for filing the issue on RTD. :cake:

**Comment by mgeier** [comment]
@willingc There was a response at https://github.com/rtfd/readthedocs.org/issues/2116, but I don't like the proposed solution (because it is IMHO a work-around and no real solution).
I also asked at Sphinx: https://github.com/sphinx-doc/sphinx/issues/2442

Any opinions on that?

**Comment by mgeier** [comment]
@willingc Did you have an opportunity to look into this?

I could really need somebody to support me on https://github.com/rtfd/readthedocs.org/issues/2116!

**Comment by mgeier** [comment]
@willingc FYI: the problem solved itself because I included the CSS fixes directly into `nbsphinx`.

I still think the original problem is a bug in RTD and Sphinx ...

**Comment by willingc** [comment]
@mgeier Thanks for the update. I will see some of the RTD folks in 2 weeks. I'll see if I can have them look at in person.

**Comment by mgeier** [comment]
@willingc Did you have a chance to talk to the RTD people?
I don't know what to answer to https://github.com/rtfd/readthedocs.org/issues/2116#issuecomment-209159076, I think I've already said everything ...

Currently, I'm discussing this on a Sphinx issue, see https://github.com/sphinx-doc/sphinx/issues/2442#issuecomment-224007281.

It would really be nice to get your opinion on this (be it for or against my statements).

**Comment by willingc** [comment]
@mgeier Traveling today. Just left some comments here: https://github.com/sphinx-doc/sphinx/issues/2442#issuecomment-224011721
