### ISSUE TITLE
User Configuration of UI buttons

### ISSUE THREAD

**Issue by jackjameshoward** [jupyter/notebook#1315]
After updating Jupyter notebook, the UI restart button in the toolbar changed functionality. 
The button used to allow restart-kernel-and-clear-output, however the option has now changed to just restart-kernel. This has changed the my work flow somewhat. I think this changed due to issue #465.

Would it be possible to allow the user to configuring the notebook front-end to change the functionality of this button?
Right now, whether it’s the right way or not, I’ve been editing the` main.min.js` file in this directory-
`\Lib\site-packages\notebook\static\notebook\js\main.min.js`
And I’ve been changing following
`jupyter-notebook:confirm-restart-kernel   #line no 28260`
to 
`jupyter-notebook:confirm-restart-kernel-and-clear-output   #line no 28260`
and I’ve been adding 
```
jupyter-notebook:confirm-restart-kernel-and-clear-output   #line no 30068
            icon: 'fa-repeat',    # new line no 60069
            help_index : 'hb',    # new line no 60070

```
I've also changed the short cut function of `00` so that it also calls `confirm-restart-kernel-and-clear-output`. Can this also be more easily configured?

**Comment by Carreau** [comment]
> Can this also be more easily configured?

Yes on master (5.0) you can easily change shotcuts:
<img width="1010" alt="screen shot 2016-06-16 at 17 32 40" src="https://cloud.githubusercontent.com/assets/335567/16137462/73b26732-33e8-11e6-8b47-c4f5a09d24f0.png">

You can already do that by writing a bit of js in your `custom.js` (google is your friend), that can help you to change/add to the toolbar, and the shortcuts.
