### ISSUE TITLE
Copy Past issues

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1316]
With the recent introduction of copy-past by @takluyver, there are a few issues: 

1) cannot copy past call output. 

(screen cast 1 whwre I press Ctrl-C on keyboard after selecting)

![cv](https://cloud.githubusercontent.com/assets/335567/14360304/90c96296-fcaa-11e5-8125-8ab87352f519.gif)

2) cannot past in debugger prompt field:

![debug](https://cloud.githubusercontent.com/assets/335567/14360344/c948c8c8-fcaa-11e5-9b15-0108d647b7f9.gif)

**Comment by Carreau** [comment]
Just as a side note, I am happy that we merged @takluyver quick as it allowed us to **discover** bugs that we would have missed otherwise.

**Comment by takluyver** [comment]
Fix coming up

**Comment by Carreau** [comment]
Reopening 2, not fixed.
