### ISSUE TITLE
python2 kernel problem

### ISSUE THREAD

**Issue by aytekinar** [jupyter/notebook#1320]
Hey,

I have a weird problem I cannot solve myself. I am using two different systems, both having Arch Linux installed with the same python2 and python3 packages. However, when I run `jupyter notebook` in both of them, I get the python2 kernel running in one of them, whereas the other gives the following error messages and freezes:
```python
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/lib/python2.7/site-packages/IPython/__init__.py", line 49, in
<module>
from .terminal.embed import embed
File "/usr/lib/python2.7/site-packages/IPython/terminal/embed.py",
line 16, in <module>
from IPython.core.interactiveshell import DummyMod
File
"/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py",
line 31, in <module>
from pickleshare import PickleShareDB
File "/usr/lib/python2.7/site-packages/pickleshare.py",
line 41, in <module>
from path import path as Path
File "/usr/lib/python2.7/site-packages/path.py",
line 126, in <module>
except pkg_resources.DistributionNotFound:
NameError: name 'pkg_resources' is not defined
```

Both of the machines are able to run Julia and python3 kernels successfully.

I'd appreciate if you helped me solve this weird behaviour.

Thanks!

P.S: I have installed the python2 and python3 packages using `pacman`, the package manager of the operating system.

**Comment by takluyver** [comment]
This looks like a bug in [path.py](https://github.com/jaraco/path.py), that it's not correctly catching when pkg_resources is not available.

**Comment by aytekinar** [comment]
Sorry, I am not good in python, either. Is it not weird that the behaviour is different it two different machines even though they are using the same package manager to install the same packages with the same versions? Any suggestions to solve the issue?

**Comment by takluyver** [comment]
Reported as jaraco/path.py#111

**Comment by aytekinar** [comment]
The [corresponding][1] commit fixes the problem, apparently. I am not having the same error anymore.

[1]: https://github.com/jaraco/path.py/commit/41a1149e647bca532db0c7bc8c0062363034bf4e

**Comment by takluyver** [comment]
We also changed pickleshare, so if you've updated that, IPython is no longer trying to load `path.py`.

**Comment by aytekinar** [comment]
I am not sure if I am using that --- I have not issued `pip install pickleshare` myself. But, thanks, good to know!
