### ISSUE TITLE
matplotlib 2.x sometimes requires %matplotlib before plotting

### ISSUE THREAD

**Issue by thomasaarholt** [jupyter/notebook#1322]
Running a fresh git clone of jupyter notebook and matplotlib 2.x, I find that I need to run iPython's `%matplotlib` before the plot window appears.
I'm only plotting from within a python module that has already set the matplotlib backend to qt4, so I'm not entirely sure where the fault lies. I thought I'd raise it here, in case others experience the same.

**Comment by takluyver** [comment]
Did you explicitly call show()? AIUI, you have to call show unless matplotlib is in interactive mode (which is one of the things that our magic enables).

Pinging @tacaswell for mpl related stuff.

**Comment by thomasaarholt** [comment]
It is in interactive mode :)

**Comment by tacaswell** [comment]
With out seeing the code I am mostly guessing, but the behavior should be:

 - the interactive state of mpl is controlled via an rcparam (our global module level state) and can be checked via `mpl.is_interactive()` and controlled via `plt.ion()` and `plt.ioff()`
  - if mpl is in 'interactive mode', then when a figure is created, then the gui backend has it's `show` method called.  This relies on the `PyOS_inputhook` to spin the GUI event loop and keep it 'active'.  If you have not run the IPython magic which ever wrapping of qt you are using (pyside vs qt) may have installed it's hook and IPython may or may not be calling the input hook from the kernel. 
   - if mpl is _not_ in interactive mode, then `plt.show()` (which is different than the figure's show) is blocking (!) and runs the GUI event loop until you close all of the open figures.

**Comment by thomasaarholt** [comment]
Thanks for the comments, chaps. I'll experiment a bit more and see what's going on.
