### ISSUE TITLE
Read-only notebooks can't be unlocked for editing

### ISSUE THREAD

**Issue by PrinterOperator** [jupyter/notebook#1324]
This issue is open in the ipython project [here](https://github.com/ipython/ipython/issues/8323), and it doesn't appear like it's been migrated to jupyter.

As mentioned in that thread, it would be great to either have a "Save As" feature or to not allow editing of a read-only file.

**Comment by MikeDacre** [comment]
Has there been any further work on this?

I accidentally extensively edited a notebook that was read-only on the disk and my changes are permanently lost it seems; despite having the window open I can find no mechanism other than copying and pasting every cell to save my changes, even after the notebook is made writable on the disk.

**Comment by benjaminleighton** [comment]
I had a file on disk with read-only permissions and I modified it to be able it to be written but I was still not able to save my notebook after extensive edits. As a workaround, using the web browser debugger, I put a break point in Notebook.prototype.save_notebook and set `this.writable = true`. I was then able to save the notebook and retain my changes.

**Comment by Madhu94** [comment]
@gnestor @takluyver I noticed that the copy handler does accept a 'to_path', but the POST calls from contents.js on the client side only set the ``copy_from``. Would you be open to accepting a PR for the Save as feature ? 

 I'm thinking of adding a modal that lets the user enter a path, checks if the user has permissions to write to that path and if so, save it there.

This would be great for copying shared read-only notebooks as well.

**Comment by takluyver** [comment]
Yes, I think so. There's a PR here, but it seems to have stalled: https://github.com/jupyter/notebook/pull/3071

**Comment by toonijn** [comment]
This is still an issue.

Is someone working on this?
Else I will implement this myself, with inspiration from: https://github.com/pangeo-data/helm-chart/pull/44#issuecomment-399151464
