### ISSUE TITLE
fail to include coffeescript in notebook pages

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#133]
%%HTML
<  script src="//cdn.bootcss.com/coffee-script/1.9.1/extras/coffee-script.js" > </  script>

The ipynb is already trusted. No idea why there's no global Coffeescript 
there's no error message.

**Comment by Carreau** [comment]
1) drop the first space after the `<`
2) ERR_SSL_VERSION_OR_CIPHER_MISMATCH over https.
3) require is loaded on the page, coffee-script does not inject itself in the page if require availlable.
