### ISSUE TITLE
Cannot paste into input() on Mac

### ISSUE THREAD

**Issue by thomasaarholt** [jupyter/notebook#1330]
The following worked on stable (pip install jupyter), but does not work on the clone I made a few days ago. Running latest Mac OS.

In a notebook cell, if I run:
`my_string = input("Test: ")`
I cannot paste into the resulting cell either by right click (the "paste" option *is* available) or from the keyboard shortcut. 

At present, my workaround is to paste (I'm pasting file paths) the path into the address bar in the browser, and then *drag* the string from the address bar and into the input bar.

Could someone attempt this on theirs?

**Comment by minrk** [comment]
I *think* this was fixed recently by #1319. Can you make sure your js is up-to-date (A fresh `pip install -e .` should do it)?

**Comment by thomasaarholt** [comment]
Ah, I'm sure you're right! I searched in the issues field, but forgot to
include closed issues. Thanks!

**Comment by thomasaarholt** [comment]
Yep, all good. Thanks!

**Comment by minrk** [comment]
Great, thanks for testing!
