### ISSUE TITLE
iPython Notebooks to Jupyter Notebook Error

### ISSUE THREAD

**Issue by atallahw** [jupyter/notebook#1335]
I want to preface this by saying this is my first time posting on here, so if I'm missing any information let me know and I'll fill it in. I don't know much about this program to begin with so I apologize if this is a silly one!

A colleague and I have used iPython-Notebooks to create a cluster server to run five computers on the same network in parallel. All computers are running Windows 7. After updating to Python 3.4.4-4 and Anaconda 4.0, we started to run into some errors. To start the cluster server, initially I would run the command `start ipcontroller --=*`, then continue to Anaconda Launcher, launch IPython Notebooks, and run my notebooks. Since IPython Notebooks has been replaced with Jupyter Notebook (after the update), the `start ipcontroller --ip=*` command keeps failing, stating that "Windows cannot find ipcontroller. Make sure you typed the name in correctly, then try again."

Any idea with how to move forward? Thanks in advance.

Waleed Atallah

**Comment by minrk** [comment]
Try:

    conda install ipyparallel

to make sure you have the IPython parallel package that provides `ipcontroller`.
