### ISSUE TITLE
4.2.0b1 - Overriding base_url duplicates that path on startup

### ISSUE THREAD

**Issue by briehl** [jupyter/notebook#1336]
Congrats on the beta! But I found a little bug:

Starting up with a different base url opens a browser with the new path duplicated before appending the tree path. For example, if I use the command line tag `--NotebookApp.base_url=new_path`, it opens the browser pointing at `http://localhost:port/new_path/new_path/tree`. The server's at the right place (pasted a startup console log below), it just sends the browser to the wrong place.

Tested this with both the command-line configuration and a config file.  
(Mac OSX 10.11.3, installed both with pip and from source)

```
(jupyter)wjriehl:[jupyter-4.2.0b1]> jupyter notebook --NotebookApp.base_url=new_path
[I 17:00:05.669 NotebookApp] Serving notebooks from local directory: /Users/wjriehl/Projects/jupyter-4.2.0b1
[I 17:00:05.670 NotebookApp] 0 active kernels 
[I 17:00:05.670 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/new_path/
[I 17:00:05.670 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 17:00:05.982 NotebookApp] 404 GET /new_path/new_path/tree (::1) 18.75ms referer=None
```

**Comment by minrk** [comment]
Indeed, should be fixed by #1338. Thanks for testing!
