### ISSUE TITLE
Backport changes to the sessions handler?

### ISSUE THREAD

**Issue by blink1073** [jupyter/notebook#1340]
Specifically, #1235 and #1237?

cc @minrk 

I had attempted to run `jupyter-js-services` against the beta release of v4.2 but hit errors due to this missing functionality.  I am happy to make the PR.

https://travis-ci.org/jupyter/jupyter-js-services/builds/122543757#L2138

**Comment by minrk** [comment]
I wasn't planning on backporting those. I figured jupyter-js-services was targeting 5.0 as a baseline. Since we've already cut the beta, I'd probably rather not backport them now, unless there's a big reason to have jupyter-js-services running against 4.x.

**Comment by blink1073** [comment]
Other applications are trying to use `jupyter-js-services` beside JupyterLab, is my concern.

**Comment by minrk** [comment]
Are those the only patches needed?

**Comment by blink1073** [comment]
Yes.

**Comment by minrk** [comment]
Looks like they depend on #1206, too. I can do those, since they still apply cleanly.

**Comment by minrk** [comment]
Backported.

**Comment by blink1073** [comment]
Thank you sir!

**Comment by minrk** [comment]
Can you test jupyter-js-services against 4.x now to verify that it's enough?

**Comment by blink1073** [comment]
Was about to say that ;)

**Comment by blink1073** [comment]
`13 passing (9s)`  :tada:

**Comment by minrk** [comment]
🍰
