### ISSUE TITLE
Jupyter fails in freshly create conda environment

### ISSUE THREAD

**Issue by Prooffreader** [jupyter/notebook#1344]
When I create a new conda environment for Python 2.7, e.g.

    conda create -n tempenv anaconda python=2.7

And install jupyter with

    conda install jupyter

When I run

    jupyter notebook

I get an error message saying to install jsonschema, which was installed alongside jupyter, and a dependency problem with ``ImportError: No module named functools32``.

If I install functools32 with

    conda install functools32

The above error becomes ``ImportError: No module named _version``.

This was replicated in both Red Hat Linux and Ubuntu 14.04

Error trace follows:

```
(tempenv)david@nyx:~$ jupyter notebook
Traceback (most recent call last):
  File "/home/david/anaconda3/envs/tempenv/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/home/david/anaconda3/envs/tempenv/lib/python2.7/site-packages/notebook/notebookapp.py", line 61, in <module>
    from .services.contents.manager import ContentsManager
  File "/home/david/anaconda3/envs/tempenv/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 16, in <module>
    from nbformat import sign, validate, ValidationError
  File "/home/david/anaconda3/envs/tempenv/lib/python2.7/site-packages/nbformat/__init__.py", line 33, in <module>
    from .validator import validate, ValidationError
  File "/home/david/anaconda3/envs/tempenv/lib/python2.7/site-packages/nbformat/validator.py", line 21, in <module>
    raise ImportError(str(e) + verbose_msg)
ImportError: No module named functools32

    Jupyter notebook format depends on the jsonschema package:
    
        https://pypi.python.org/pypi/jsonschema
    
    Please install it first.
```

**Comment by Prooffreader** [comment]
Error resolved by using

    pip install jsonschema

instead of conda install.

**Comment by takluyver** [comment]
That sounds like a problem with the conda packaging of jsonschema and/or functools32. But also, if you have previously pip install-ed something over a conda installed package, it can corrupt the conda package even in other environments, because conda hard links files across environments to save space.

**Comment by Lionardo** [comment]
I have the same issue and after 
`pip install jsonschema`
i get this

> Requirement already satisfied: jsonschema in ./anaconda/lib/python2.7/site-packages

I tried to uninstall notebook and install it again but nothing changes.

`ImportError: No module named _version

    Jupyter notebook format depends on the jsonschema package:
    
        https://pypi.python.org/pypi/jsonschema
    
    Please install it first.`

**Comment by Lionardo** [comment]
I resolved the issue with
`pip install -U jsonschema`

**Comment by maxmax44** [comment]
All this command lines didn't work for me.

"sudo pip --upgrade" on any of this packages returns me a "requirement already satisfied".

"Conda upgrade jsonschema", instead, made upgrades where pip don't.

**Comment by takluyver** [comment]
You probably don't want to use `sudo` with pip.
