### ISSUE TITLE
XDG compliance

### ISSUE THREAD

**Issue by teto** [jupyter/notebook#1355]
Hi,

I noticed when starting jupyter notebook this line:
```
[JupyterQtConsoleApp] Copying /home/teto/.config/ipython/profile_default/ipython_qtconsole_config.py -> /home/teto/.jupyter/jupyter_qtconsole_config.py
```
with version 'Jupyter QtConsole 4.2.1'.
Is there any plan (couldn't find through github's tracker) to support the linux XDG specs so that the files are saved as for instance "$XDG_CONFIG_HOME/jupyter/jupyter_qtconsole_config.py"
It's quite practical to switch between configurations or backup them (also it doesn't clutter your $HOME).

**Comment by minrk** [comment]
We had many long discussions about whether to follow XDG for config on Linux, and ultimately decided against it. There was a period of time when IPython followed XDG, but people found it more confusing that the location varied across platforms (XDG is inappropriate on OS X and Windows, for instance), and reverted back to consistently using `~/.ipython`. Following that experience, we decided against adopting XDG for config in Jupyter. We do follow XDG for data/runtime files.

If you prefer XDG behavior, you can set:

    JUPYTER_CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/jupyter

and it should work how you like.

**Comment by teto** [comment]
Thanks for the detailed answer. I have added an export as you advise.
