### ISSUE TITLE
Update Session to take an arbitrary name?

### ISSUE THREAD

**Issue by blink1073** [jupyter/notebook#1358]
We talked today at the JupyterLab meeting about how the Session would map to a source code file or a console.  We could just set the `notebook:path` to be a file path or a console session name, but it would be more generic to have a session id take this interface:

```typescript
interface ISessionId {
  id: string;
  path: string;  
  type: string;   // one of { notebook, file, console }
  kernel: {
    id: string;
    name: string;
  }
}
```

For text files and notebooks, the path is the full path to the file.  For a console, the path is the cwd directory of the console (at startup).

**Comment by blink1073** [comment]
cc @ellisonbg @jasongrout @minrk

**Comment by minrk** [comment]
Mostly makes sense. I think we do want it to be identifiably a notebook, so maybe add a `type: str` field.

**Comment by blink1073** [comment]
Yep, sounds fair.  This would result in the current version of `jupyter-js-services` being the officially supported version for notebook 4.2, and then start relying on this and other new features.

**Comment by minrk** [comment]
Sounds good.

**Comment by blink1073** [comment]
I updated the API to include a path, to mirror the contents API and to allow a console to establish an initial cwd.

**Comment by blink1073** [comment]
On second thought, I renamed it to directory, so the unique name is `os.path.join(directory, name)`.

**Comment by blink1073** [comment]
Upon third thought, it makes more sense for the `path` to be one attribute, and the path to a console is the cwd of the kernel with a file "name" being the name of the console session, cleaning up the implementation itself greatly.

**Comment by jasongrout** [comment]
Initial cwd? Because the cwd can change...

**Comment by blink1073** [comment]
This is the cwd that the kernel starts up in, you can change it by sending a `POST`.

**Comment by blink1073** [comment]
er, `PATCH`
