### ISSUE TITLE
json schema 2.5 broke notebook.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#136]
The wheel broke notebook on 3.x a few days ago, but now it is broken on 2.7 since wheel has been removed. It does not install `functools32`. At least on Travis.

**Comment by takluyver** [comment]
A new release should be coming up - see Julian/jsonschema#231

**Comment by Carreau** [comment]
let's give it 24h. and if not make a temporary workaround on our side otherwise it makes all PRs agains notebook fail.

**Comment by jhamrick** [comment]
Having the same problem on nbgrader, too :-(

**Comment by Carreau** [comment]
2.5.1 is out. Closing.
