### ISSUE TITLE
Review installation instructions with Anaconda 4.0 release

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#1362]
Recent release of Anaconda 4.0 :smile: https://www.continuum.io/blog/developer-blog/anaconda-4-release

Navigator is new and Launcher is deprecated. Review Windows installation with Anaconda for possible improvements or simplifications.

**Comment by Carreau** [comment]
Good idea, and OMG I'm feeling like I'm back using windows 98 and I'm customizing the color of my windows toolbar.

**Comment by willingc** [comment]
@Carreau [GUIs of the past](http://www.guidebookgallery.org/screenshots/full) Somewhat amusing how many I've used. Favorite is still [happy mac](http://www.guidebookgallery.org/screenshots/macos11) which just edges out my [childhood friend](http://www.guidebookgallery.org/screenshots/apple2desktop11)

**Comment by takluyver** [comment]
Those tiles do look bizarrely ugly...

I don't immediately see anything that would require us to change our installation instructions.

**Comment by jzf2101** [comment]
Is this issue still live?

**Comment by willingc** [comment]
@jzf2101 Nope. Let's close.
