### ISSUE TITLE
Protect against bad custom.js

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1363]
if custom.js has a bad require, (eg require something only available on 5.x , like `require('notebook')`) all hell break loose and the page do not load. 

That should not be the case.

Marking as 4.3 as it is a bit annoying to debug each time you revert to an older version.

**Comment by minrk** [comment]
I swear, I keep fixing this bug, and it keeps coming back.

**Comment by Carreau** [comment]
> I swear, I keep fixing this bug, and it keeps coming back.

One of your clones is faulty.

**Comment by dsblank** [comment]
"I swear, I keep fixing this bug, and it keeps coming back."

I need a t-shirt that says this :crying_cat_face:
