### ISSUE TITLE
Use <base> tag for baseUrl ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1364]
Apparently there is [`<base>` tag](https://developer.mozilla.org/fr/docs/Web/HTML/Element/base) which is ment to set the base url for a webpage. That might be what we are hacking around with "our" `baseUrl`, I guess. Not sure if it works only with a domain, or if the base can have a subdirectory. It should also be the URL which is use to resolve relative href by browsers.

We should likely investigate how it behaves.

I guess it might be useful for JupyterHub also.

**Comment by minrk** [comment]
From the docs:

> The base URL to be used throughout the document for relative URL addresses.

I don't think that's the same thing. That would be different for every page, and would be the full URL of every page. It does not appear to be the base URL of the application as a whole.
