### ISSUE TITLE
node/bower required?

### ISSUE THREAD

**Issue by grivescorbett** [jupyter/notebook#1366]
When running pip install against version 4.2.0 I get the following error output:

    Running setup.py install for notebook ... error
    Complete output from command /home/ubuntu/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-0dtiHa-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tgQif8-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running jsversion
    running css
    running jsdeps
    npm unavailable
    > bower install --allow-root --config.interactive=false
    Failed to run bower: [Errno 2] No such file or directory
    You can install js dependencies with `npm install`
    rebuilding js and css failed. The following required files are missing: ['notebook/static/components', 'notebook/static/notebook/js/main.min.js', 'notebook/static/tree/js/main.min.js', 'notebook/static/edit/js/main.min.js', 'notebook/static/terminal/js/main.min.js', 'notebook/static/auth/js/main.min.js', 'notebook/static/style/ipython.min.css', 'notebook/static/style/style.min.css']
    error: [Errno 2] No such file or directory

Installing node and bower appeared to fix it but that is not stated as a requirement in the README.

**Comment by minrk** [comment]
Are you installing from git? When I `pip install notebook` on a machine without npm, I get 4.2.0 and it never tries to run npm.

**Comment by Carreau** [comment]
closing as this is likely due to an install from source that likely then does require npm, bower ...

**Comment by qhan1028** [comment]
just install `git` before installing notebook.
`apt-get install -y git`
