### ISSUE TITLE
Is it possible to add a coffeescript magic (simillar to javascript magic)

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#137]
It's convenient for us to write plot (highcharts, dygraphs, etc) options.
And we can provide csv data in another cell by python.

**Comment by Carreau** [comment]
Magics are IPython specific, not notebook, and are purely python function that takes a string as input and return a python object. There is no need for IPython to include them, you just have to publish a python package that define your function and the load_ipython_extension function. 

You can get inspired by [that](https://gist.github.com/bollwyvl/de3b4ca8b6ed8bb28f86) that I found by just googling `IPython cofeescript magic`, first result.
