### ISSUE TITLE
Node De-Duplication

### ISSUE THREAD

**Issue by blink1073** [jupyter/notebook#1373]
Npm v3+ installs are maximally flat by default, but versions before that require `npm dedupe` to ensure that two versions of the same package with the same version are not installed.  This is a problem when a module stores module-private data structures that are meant to be shared and loaded only once.

I propose that the version of npm be checked on install, and if it is 3+, install with no modification.  Otherwise, attempt to run `npm dedupe` after `npm install`.  If that fails (as has been seen due to file permissions [issues](https://github.com/jupyter/atom-notebook/issues/32#issuecomment-184922403)), prompt the user to install npm 3+.  

I can make the necessary changes to `setupbase.py`.

**Comment by minrk** [comment]
seems okay to me
