### ISSUE TITLE
Dockerfile runs the notebook as root user

### ISSUE THREAD

**Issue by bomgar** [jupyter/notebook#1375]
Hi,

the dockerfile runs the jupyter notebook with root privileges. The [docker security documentation](https://docs.docker.com/engine/security/security/) states: 
> Docker containers are, by default, quite secure; especially if you take care of running your processes inside the containers as non-privileged users (i.e., non-root).

The possibility to run arbitrary code as root via http is a concern even in a cgroup environment.

**Comment by willingc** [comment]
@bomgar Thanks. Here are some security documents about configuring the the server and notebook for security in a production environment:
- [Notebook Server Security](https://jupyter-notebook.readthedocs.org/en/latest/public_server.html#notebook-server-security)
- [Security in Jupyter notebooks](https://jupyter-notebook.readthedocs.org/en/latest/security.html)
- [Running a Public notebook server](https://jupyter-notebook.readthedocs.org/en/latest/public_server.html#running-a-public-notebook-server)

I hope you will find these helpful in illustrating the project's commitment to security importance and flexibility for users facing a variety of situations from closed trusted networks to a public deployment.

Thanks!
Carol

cc/ @minrk @rgbkrk

**Comment by rgbkrk** [comment]
> The possibility to run arbitrary code as root via http is a concern even in a cgroup environment.

In all the [docker-stacks images](https://github.com/jupyter/docker-stacks), the base user is `jovyan`. For the Dockerfile in here, since people almost always have to install additional packages and may have their own user setup we don't change the default user. This is a base image, like other base images.
