### ISSUE TITLE
The concept about top n accuracy!

### ISSUE THREAD

**Issue by yechaochen** [jupyter/notebook#1376]
Resently,I have read some papers that some of them refer to a concept about top n accuracy.But  i've never heard of the term, nor can find it using google.

Can someone give me a definition or point me somewhere? Tell me what does it mean.

**Comment by takluyver** [comment]
I'm not sure why you're asking here - this is the issue tracker for the Jupyter Notebook. However, out of curiosity, I searched for the term, and here's the first thing that came up:

http://stats.stackexchange.com/questions/95391/what-is-the-definition-of-top-n-accuracy
