### ISSUE TITLE
Widgets 5.0 warns that to upgrade notebook to 4.2 even with 4.2 installed

### ISSUE THREAD

**Issue by jenshnielsen** [jupyter/notebook#1377]
I.e. I get
```
/usr/local/lib/python3.5/site-packages/widgetsnbextension/__init__.py:30: UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
```
yet:
```
/private/tmp pip3 list | egrep 'notebook|widgets'
ipywidgets (5.0.0)
notebook (4.2.0)
widgetsnbextension (1.0.0)
```

This seems to be because the code hack in notebookapp.py still calls `widgets.find_static_assets` even when widgets 5.0 is installed. 
Comparing https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L276
to https://github.com/jupyter/notebook/blob/4.x/notebook/notebookapp.py#L236 It seems like the HACK on the 4.x branch has not been fully backported from master?

**Comment by hmeine** [comment]
I got the same problem with up-to-date MacPorts, with even newer versions:

    % pip list | egrep 'notebook|widgets'
    ipywidgets (5.1.3)
    notebook (4.2.0)
    widgetsnbextension (1.2.2)

**Comment by minrk** [comment]
@SylvainCorlay what's the right thing for notebook 4.x to do, here? Right now, the 4.x notebook has a hardcoded bit to load widgets with `find_static_assets()`. However, widgets 5.0 has a warning when this method is called that "notebook 4.2" should be used, which is clearly misleading because notebook 4.2 is calling this method. Should notebook 4.2 not be calling this? If so, what should it be calling in its place?

**Comment by SylvainCorlay** [comment]
This seems to be a change to be made in ipywidgets.
Btw we must release notebook 4.2.1 with the fix #1399 for #1386.

**Comment by minrk** [comment]
@SylvainCorlay yes, we'll release 4.2.1 with that fix, but I don't want to release 4.2.1 before we figure this out. Should:

- `.find_static_assets()` be fixed to not show this message, or
- notebook 4.2 be updated to use a different bit of code to load the widgets, to avoid the deprecated function

?

**Comment by minrk** [comment]
@SylvainCorlay should 4.2 be looking for widgetsnbextension like 5.0 does, or should ipywidgets change its deprecation message to stop indicating that users should upgrade to 4.2 when `find_static_assets` is called, which 4.2 calls? This is the only thing blocking the 4.2.1 release.

**Comment by SylvainCorlay** [comment]
Sorry for the late reply. I spent the last 10h in a plane. I will look at
it today.
S.

**Comment by minrk** [comment]
@SylvainCorlay no problem, safe travels! I just know you are eager for 4.2.1 to get out, so hopefully we can finish it up soon.

**Comment by SylvainCorlay** [comment]
I think that notebook 4.2 should do the same as 5.0, that is to attempt fist to import widgetsnbextension.

On another note, I find the code in ipywidgets a bit too complicated!

**Comment by hainm** [comment]
In my opinion, `notebook 4.2` should be 5.0. Jupyter project keeps getting confusing and I wasted lots of time to debug my programs and try to understand why things did not work. There are always good reason to break API and a bunch of packages keep breaking API make such a pain. Developers know best about their programs and you though it's easy to adapt but as an regular user, it's not easy at all.
