### ISSUE TITLE
How to stop the iPython notebook to run the command line, run only python code

### ISSUE THREAD

**Issue by nicky1108** [jupyter/notebook#138]
I am using iPython notebook build a online interactive teaching website, but I don't want users to run command line, any idea how to remove iPython notebook command line function? Is there any configuration or something? 

![img1](https://cloud.githubusercontent.com/assets/4279283/8039290/3e304e5e-0e3b-11e5-9479-d8b4f93ee147.png)

**Comment by takluyver** [comment]
Let's continue this on ipython/ipython#8514

**Comment by Carreau** [comment]
And please don't open issues twice.
