### ISSUE TITLE
Markdown cell editor assumes wrong linktext

### ISSUE THREAD

**Issue by janschulz** [jupyter/notebook#1382]
In the following markdown cell, the assumed link text (which will get blue underlines) is wrongly shown as going from the first `[` to the second `]`:

```
text [...] text [link](http://www.yahoo.de)
```

![2016-04-21_112146](https://cloud.githubusercontent.com/assets/890156/14704081/40f975d0-07b3-11e6-9d36-53acec0479b9.png)

In the final rendered version, it's right (only "link" will be a link):

![2016-04-21_112315](https://cloud.githubusercontent.com/assets/890156/14704124/73dcf436-07b3-11e6-8d05-f8b1ebeb51d5.png)

**Comment by minrk** [comment]
This would be a bug in CodeMirror's markdown mode, right? That's what determines the highlighting patterns.

**Comment by takluyver** [comment]
Yep, I can reproduce it on http://codemirror.net/mode/markdown/index.html

**Comment by takluyver** [comment]
https://github.com/codemirror/CodeMirror/issues/3981

**Comment by janschulz** [comment]
ok, thanks!
