### ISSUE TITLE
Kernel not ready after restarting

### ISSUE THREAD

**Issue by MerlinSmiles** [jupyter/notebook#1383]
If I want to restart the notebook and run the first cells manually, I keep hitting <shift><return> too early. The kernel isn't ready yet and maybe cell 3 or 4 gets excecuted.

It would be nice if the <shift><return> commands would be put in a queue for execution when the kernel is ready again :)

**Comment by takluyver** [comment]
What version are you using - this should have been resolved in notebook 4.2.0 by #1002.

**Comment by MerlinSmiles** [comment]
Thats embarrasing, Thank you!
