### ISSUE TITLE
Destination not used when installing nbextensions

### ISSUE THREAD

**Issue by jhamrick** [jupyter/notebook#1384]
The `destination` variable isn't used when installing nbextensions, even though the `install_nbextension` function supports it, and it's defined in the InstallNBExtensionApp class:

https://github.com/jupyter/notebook/blob/master/notebook/nbextensions.py#L703

It looks like it was removed in #879 here:

https://github.com/jupyter/notebook/pull/879/files#diff-720744abca8751e2ff12988ac308c604L308

**Comment by minrk** [comment]
Fixed by #1391
