### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by wernight** [jupyter/notebook#1387]
Just like https://github.com/jupyter/nbviewer/commit/316665e5d7eee4cba9010d12803df94bf993fc40 it'd be good to have a default `robots.txt`.

**Comment by Carreau** [comment]
I'm unsure, the notebook is supposed to be behind login, so no robot should be able to crawl it.
Should not be too hard though. 
I guess a no-index nofollow could be good too. Just to avoid indexing potential open notebook on the web.

**Comment by wernight** [comment]
It's not to allow crawling but for two things:

 * Because it's a good practice to just be explicit.
 * Because it can be used for example to get the Kubernetes Ingress controller working.

Possibly together, a [`humans.txt`](http://humanstxt.org/) wouldn't be a bad idea for you guys.

**Comment by go-bears** [comment]
Is this issue still open? I can help. Do you want a  robots.txt file and/or a <meta> tag on the page.html template?

**Comment by wernight** [comment]
I'm using Nginx Ingress Controller which doesn't require those files.

`robots.txt` and/or `humans.txt` may help others, or just as a common practice.

**Comment by minrk** [comment]
It is. It would be good to add these (possibly not as files, just hardcoded Handlers).

**Comment by takluyver** [comment]
Fixed by #2579.
