### ISSUE TITLE
Embed inside Django framework

### ISSUE THREAD

**Issue by datomnurdin** [jupyter/notebook#1388]
Hi, is there anyway to embed jupyter notebook (.ipynb) inside Django framework?

Please advice. Thanks.

**Comment by minrk** [comment]
There is not, really. The notebook is a tornado application. If you want to embed it in a django site, you would probably need to run an additional tornado server, and then load notebooks in an IFrame. Perhaps there is a better way of running two webservers together than I am not aware of.
