### ISSUE TITLE
Semantic highlighting. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#139]
I came across that : http://brooks.io/syntax-highlight/

Which basically highlight the variables name a a function of the hash of their name. Which make detecting typos almost trivial `alongvaraiblename` would be green-ish and `alongvariablename` could be red-ish. 

This seem like it would help a lot for teaching/presenting. 

@ellisonbg , @jhamrick , @fperez  thoughts ?

**Comment by rkern** [comment]
As someone who is red-green colorblind, that sounds utterly horrifying. ;-)

**Comment by Carreau** [comment]
Well, that would probably not be on by default, maybe an extension, and the colorscheme is (even for not colorblind) definitively up for discussion.

Also with currently linked implementation. it even colors the builtins/keyword this way which is horrific.

**Comment by jhamrick** [comment]
Huh, that's a cool idea. It would definitely be neat to try out, though I'd
be a bit worried that there would just be too many colors floating around
and that I still wouldn't notice typos because there's so many colors to
begin with.

**Comment by ellisonbg** [comment]
There are some *really* nice ideas there. I like how it styles code
comments. However, I think that for now we have a lot more pressing design
related to to tackle...

On Mon, Jun 8, 2015 at 10:01 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> I came across that : http://brooks.io/syntax-highlight/
>
> Which basically highlight the variables name a a function of the hash of
> their name. Which make detecting typos almost trivial alongvaraiblename
> would be green-ish and alongvariablename could be red-ish.
>
> This seem like it would help a lot for teaching/presenting.
>
> @ellisonbg <https://github.com/ellisonbg> , @jhamrick
> <https://github.com/jhamrick> , @fperez <https://github.com/fperez>
> thoughts ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/139>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> There are some *really* nice ideas there. I like how it styles code
> comments. However, I think that for now we have a lot more pressing design
> related to to tackle...

Sure that's why I open an issue, to keep track of it in the long term. 
Each of us has a different question on "pressing" question, and pushing won't help.

**Comment by JamiesHQ** [comment]
Hi folks- is this still something we'd like to do (or perhaps it has been implemented since June 2015)?

**Comment by ellisonbg** [comment]
I think I would target this to the JupyterLab milestone and eventually migrate it over there into the Backlog. Interesting ideas still that are working things about.

**Comment by JamiesHQ** [comment]
Sounds good. @blink1073 @afshin @jasongrout  see ^^ above ^^

**Comment by blink1073** [comment]
Migrated to https://github.com/jupyterlab/jupyterlab/issues/2105.
