### ISSUE TITLE
ie11 enters command mode unexpectedly 

### ISSUE THREAD

**Issue by deedubbu** [jupyter/notebook#1395]
I found a situation in ie11 that causes the notebook to go into command mode even though focus should be in the output area and edit mode enabled. Steps to reproduce:
1. Create a notebook (I used Python kernel) with two cells that each have an html input tag:
   
   ```
   %%html
   <input type='text' />
   ```
   
   ```
   %%html
   <input type='text' />
   ```
2. Run all cells.
3. Click into first input field and type some text.
4. Click into second input field and type `h`. Notice that the keyboard shortcut popup is displayed instead of an `h` being entered into the input field. _Note that I picked the letter `h` because the popup makes it easy to confirm the issue has occurred, but the point is that the notebook for some reason is in command mode._

**Comment by takluyver** [comment]
I think some JS needs to call `Jupyter.keyboard_manager.register_events()` on any output elements that you want to be focusable for keyboard input. The widget framework does this for the elements it creates, for instance. Once this is done, our keyboard manager is disabled when you focus the text box, and disabled when you leave it, so our shortcuts don't fire while you're typing in it.

**Comment by deedubbu** [comment]
@Carreau Tried to find some information on the `no action` milestone but didn't see it described anywhere. Looking at the other issues in that milestone it seems like things that won't be fixed. I've noticed that ie11 is listed as an [unsupported browser](http://jupyter-notebook.readthedocs.org/en/latest/notebook.html#browser-compatibility). Is that the reason for the `no-action`?

**Comment by takluyver** [comment]
We do consider IE unsupported, but I think the reason @Carreau has applied it in this case is that we consider it up to whoever/whatever constructs the HTML to take care of calling `register_events()` on it.

Maybe it would be possible to scan HTML output for elements that should be focusable and automatically call `register_events` on them, but I don't know how reliable that would be. Someone more familiar with the HTML & JS side of things may be able to chime in.
