### ISSUE TITLE
run '!ipython' inside jupyter notebook

### ISSUE THREAD

**Issue by ShaoLinMonk** [jupyter/notebook#1398]
When type '!ipython' in jupyter nb, the cell runs and wait for input, however I cannot interact with that cell and the other cells wait for that command. 

Sorry to ask this silly question. But I am confused with notebook. You can run ipython inside ipython, and the interaction works pretty good. But you cannot do that way in Jupyter NB

**Comment by takluyver** [comment]
No, you can't run subprocesses that expect input at a terminal: there isn't a reliable way for us to recognise when they're waiting for input, so they will just sit there not doing anything.

You can do `!python some_script.py` - or any other command that will run to completion by itself. But you can't use anything interactive with `!` in the notebook (or any other jupyter frontends).

**Comment by ShaoLinMonk** [comment]
Many thanks for your quick reply. It clears my confusion.
