### ISSUE TITLE
about.js get sys_info from global namespace.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1404]
1) It might not be defined and we should check for that. 
2) it does not always work (like iframing on try.jupyter.org) 
3) It make the "about" menu do nothing and it's hard to debug.

**Comment by captainsafia** [comment]
I think this should be closed or the persistent issues should be split into new, smaller issues.

**Comment by Carreau** [comment]
Do you want to open sub issues, referencing this and closing this one once the other issues are created?

**Comment by captainsafia** [comment]
Yep.
