### ISSUE TITLE
.sh file won't open in text editor?

### ISSUE THREAD

**Issue by jessehoff** [jupyter/notebook#1408]
Trying to open a text file with .sh extension. Other text files of various extension open fine.
When I try open the .sh file it tries to download
Working on chrome in a mac with a server side notebook.

**Comment by takluyver** [comment]
On my system, shell files have mimetype `application/x-sh` - our rule for when to try to edit things is to check for the `text/` media type. We think the most general solution is to have *edit* and *view/download* buttons for all file types (possibly with a blacklist of definitely-not-text filetypes like image/png that we know we can't edit).

**Comment by captainsafia** [comment]
There was discussion related to this with respect to #1143. I'm working on a more permanent solution for this as we speak!

**Comment by minrk** [comment]
This was fixed by #1413

**Comment by kxiluri** [comment]
Hello everyone, i have the problem you describe here, but i do not know how to fix it.
Could anyone please help.
When i click on a .txt file it renders fine in the text editor, but when i click on .sh it does nothing.
Kind Regards
kiriaki

**Comment by frankr6591** [comment]
Same here... I am on mac and when I click on .sh ... it starts Xcode... want to edit inside jupyter.

**Comment by kxiluri** [comment]
i had figured it out it i will try to remember
stay tuned
k

Sent from my iPad

On Aug 26, 2017, at 8:30 AM, frankr6591 <notifications@github.com<mailto:notifications@github.com>> wrote:


Same here... I am on mac and when I click on .sh ... it starts Xcode... want to edit inside jupyter.

**Comment by takluyver** [comment]
There were some further changes to this for 5.1, which we're just getting ready to release. If you want to help us test the release candidate, you can upgrade to it:

```
pip install --upgrade --pre notebook
```
