### ISSUE TITLE
Add "Save and Commit" menu item under File

### ISSUE THREAD

**Issue by Tagar** [jupyter/notebook#1410]
As discussed on http://stackoverflow.com/questions/18734739/using-ipython-notebooks-under-version-control
it would be great to have a separte "Save and Commit" menu item under File.

It does two things:
- saves .ipynb without cells output content;
- calls a predefinied script for a CVS system commit (e.g. git commit).

**Comment by jtpio** [comment]
Closing as this would be a feature to this extension if it does not exist already: https://github.com/jupyterlab/jupyterlab-git
