### ISSUE TITLE
Kernel not starting

### ISSUE THREAD

**Issue by wiso** [jupyter/notebook#1414]
after having updated jupyter the kernel is not starting anymore. I get: "Kernel starting, please wait"

![schermata da 2016-05-02 11-42-59](https://cloud.githubusercontent.com/assets/143389/14951689/389abfb0-105b-11e6-89a4-158d81154cad.png)

from the terminal I get:

    /usr/lib/python2.7/site-packages/widgetsnbextension/__init__.py:30:` UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update the Jupyter notebook to version 4.2 or later.
    the Jupyter notebook to version 4.2 or later.""")
    [I 11:39:46.371 NotebookApp] Serving notebooks from local directory: /home/turra
    [I 11:39:46.371 NotebookApp] 0 active kernels 
    [I 11:39:46.371 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
    [I 11:39:46.371 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    È stata creata una nuova finestra nella sessione corrente del browser.
    [I 11:39:51.430 NotebookApp] Creating new notebook in 
    [I 11:39:52.575 NotebookApp] Kernel started: a58f5dbf-0f20-4970-88ed-9dbe5f79d6ac
    [W 11:39:52.694 NotebookApp] 404 GET /static/components/bootstrap/js/tooltip.js?v=20160502113946 (127.0.0.1) 9.95ms referer=http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=python2
    [W 11:39:52.736 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160502113946 (127.0.0.1) 1.64ms referer=http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=python2
    [I 11:41:53.035 NotebookApp] Saving file at /Untitled6.ipynb
    [W 11:57:33.507 NotebookApp] 404 GET /static/components/bootstrap/js/tooltip.js?v=20160502115727 (127.0.0.1) 2.88ms referer=http://localhost:8888/notebooks/Untitled7.ipynb?kernel_name=python2
    [W 11:57:35.024 NotebookApp] 404 GET /api/kernels/a58f5dbf-0f20-4970-88ed-9dbe5f79d6ac/channels?session_id=4EB7CBF31C914006B2C342155E65CC8E (127.0.0.1): Kernel does not exist: a58f5dbf-0f20-4970-88ed-9dbe5f79d6ac
    [W 11:57:35.025 NotebookApp] 404 GET /api/kernels/a58f5dbf-0f20-4970-88ed-9dbe5f79d6ac/channels?session_id=4EB7CBF31C914006B2C342155E65CC8E (127.0.0.1) 5.23ms referer=None

while from chrome I get:

    Raw Cell Format toolbar preset loaded.
    main.min.js:24264 Slideshow extension for metadata editing loaded.
    main.min.js:29052 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
    main.min.js:12154 load_extensions 
    Arguments[5]
    main.min.js:23418 Session: kernel_created (47b83fa8-324a-4e3f-ada7-bbc34bf11f27)
    main.min.js:22709 Starting WebSockets: ws://localhost:8888/api/kernels/a58f5dbf-0f20-4970-88ed-9dbe5f79d6ac
    main.min.js:12131 Loading extension: publishing/gist_it/main
    main.min.js:12131 Loading extension: usability/help_panel/help_panel
    main.min.js:12131 Loading extension: config/config_menu/main
    main.min.js:12131 Loading extension: usability/toggle_all_line_numbers/main
    main.js:71 toggle_all_linenumbers enabling hotkey: Alt-N
    main.min.js:12131 Loading extension: usability/spellchecker/main
    http://localhost:8888/static/components/bootstrap/js/tooltip.js?v=20160502113946 Failed to load resource: the server responded with a status of 404 (Not Found)
    http://localhost:8888/nbextensions/widgets/notebook/js/extension.js?v=20160502113946 Failed to load resource: the server responded with a status of 404 (Not Found)
    main.min.js:33954 Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
    main.js:147 [spellchecker] toggled on

I am using:

    jupyter 4.1.0
    ipython 4.2.0
    google-chrome 50
    fedora 23

**Comment by methodds** [comment]
I have the exact same problem.

**Comment by takluyver** [comment]
Did Chrome just get an update? That's three people saying they have this issue within an hour. On #1415, the reporter says it works in Firefox.

**Comment by wiso** [comment]
@takluyver: you are right, in firefox it works

**Comment by willingc** [comment]
@takluyver Notebook v4.2 appears to work on Chrome with Python 3 on OS X 10.11.4. See #1415

**Comment by willingc** [comment]
Posting resolution that has worked for others here:
https://github.com/jupyter/notebook/issues/1415#issuecomment-216230780

**Comment by wiso** [comment]
@willingc: right, it works

**Comment by shanmugavel28** [comment]
as said. closed browser and restarted. now it works.
