### ISSUE TITLE
Temporary disabling autosave / in-memory copy of a notebook

### ISSUE THREAD

**Issue by Phyks** [jupyter/notebook#1419]
Hi,

Very often, I open a notebook which is in a stable state, and want to rerun some cells with some tweaks with some variables or something like this, but mostly in a prototype way, and I want to discard the result afterwards.

If I open my notebook and directly edit it, the autosaving feature stores the changes definitely, and I lose my previous values and parameters.

If I clone the notebook, I need to have a copy in the same folder, which is not practical either for a temporary test.

So I propose to either offer a menu entry to disable autosave feature temporarily. As an (even better?) alternative, it would be awesome to be able to have in-memory copy of a notebook. Then, "copy" notebook menu entry would make an in-memory copy, and the user would be free to save it whenever he wants.

Thanks!

**Comment by Phyks** [comment]
By the way, as I version my notebooks with Git, my current workaround is to commit when I have a stable version, and to `git checkout` the notebook when I want to return to the stable state, after having played with variables.

Maybe introducing "stable revisions" of a notebook (_à la_ starred revisions in Etherpad) would be interesting for some users, but that is also something that external tools (such as Git) handle very well.

**Comment by takluyver** [comment]
There is already a checkpoint when you manually save, so you can revert anything that has been autosaved since then. You can access it from the File menu.

**Comment by Phyks** [comment]
Indeed, I do not know how I could completley miss it :/ Truely sorry for the noise =(

**Comment by takluyver** [comment]
No worries, it's still useful to hear how people are using it and where the frustrations are!
