### ISSUE TITLE
Don't force 80x25 terminal size

### ISSUE THREAD

**Issue by vincent-legoll** [jupyter/notebook#1425]
I'm trying to run some commands in a bash jupyter-notebook, and the output of those commands is tailored to the terminal size.

It appears that the terminal emulation layer of jupyter (terminado) defaults to 80x25 which is not always the right size.

Jupyter-notebook should try to have sensible values, so that the output is not line-mangled when not needed.

see screen capture here :

https://bugs.launchpad.net/python-openstackclient/+bug/1577368/+attachment/4655196/+files/Capture%20du%202016-05-04%2008%3A40%3A00.png

You can see the difference in this picture, as the "openstack" command has a specific CLI parameter to make it workaround such automagic behaviour shortcomings. But I don't want to sprinkle all my notebook (which is for a basic user training) with unrelated parameters as that would confuse the students, and be ugly.

I would like the one without "--max-width" to display as it would with that parameter.

This may also be related to https://github.com/jupyter/notebook/issues/46

**Comment by takluyver** [comment]
This is not related to terminado, which is what's used when you click 'New > Terminal' from the dashboard.

We have to specify *some* size for subprocesses running in a pseudoterminal, and 80x25 is a common default. It's also better to default to too small, which tends to make cramped output, than too big, which can completely break things like tables.

We could do something hackish to calculate a width from the JS and send it to the kernel every time it changes, but the existing output would still be wrong as soon as the notebook was displayed at a different width, so it doesn't seem worth the added complexity.

In kernels that can do so, a better approach is to produce an HTML table rather than ASCII art, which can be displayed neatly in the frontend. There isn't currently a way to display HTML from bash_kernel, though.

**Comment by vincent-legoll** [comment]
I respectfully disagree, but will stop arguing now.

Could you point me to where this is implemented ?

**Comment by ellisonbg** [comment]
The other issue is that there can be multiple frontends attached to a kernel, each of which could have a different width. But @takluyver what about giving the `%%bash` command a flag to set this option?

**Comment by takluyver** [comment]
The `%%bash` magic certainly could have such an option, though I think in this case Vincent was using bash_kernel, where it would be trickier to add that kind of thing. For many programmes you can also override it by setting the `ROWS` and `COLUMNS` environment variables, which may offer another workaround.

**Comment by vincent-legoll** [comment]
COLUMNS, in that particular case, is not a solution, openstack client is based on the cliff sub-project which actively avoids COLUMNS usage, see commit message here : 
https://git.openstack.org/cgit/openstack/cliff/commi/?id=e7c3c622759d4e9af09947dfb8a7faf52edaad07

I'm actually pursuing a solution on the other end, by making cliff support an environment variable to avoid trying to guess/use line length to split output.

But the question remains on the jupyter-notebook front, whether it could be useful for other to be able to do that, I don't know...

**Comment by vincent-legoll** [comment]
The other end (openstack/cliff) workaround / fix is tracked [here](https://bugs.launchpad.net/python-openstackclient/+bug/1577368)

**Comment by vincent-legoll** [comment]
@takluyver: care to explain what you meant by "can completely break things like tables", because my experience (which led to this bug report) is the opposite. My tables are actually broken, and I want to fix them by allowing overrides to the default values, which will never be always right...

**Comment by takluyver** [comment]
The full sentence:

> It's also better to default to too small, which tends to make cramped output, than too big, which can completely break things like tables.

If we guess a size smaller than the width that can be displayed, an ascii art table will be unnecessarily cramped, and may be split into two chunks, as in your screenshot. If we  guess a size *bigger* that the width that can be displayed, and it renders a table wider than can be displayed, the lines will wrap and the ascii art becomes a horrible mess. So where we don't know the width available to display monospace characters, we should err on the small side for picking a default. As we do.

**Comment by vincent-legoll** [comment]
I have no problem with the way jupyter guess what should be the default, but as it can only be a best effort guess, there will be cases where this guessing goes wrong, and there ought to be a way to manually fix it up for those cases.

Anyway, you can close this bug report as wont-fix, the other side's workaround has been accepted:

https://git.openstack.org/cgit/openstack/cliff/commit/?id=c59f04465cff2d2d147491d5ec521e8b769bd377

So I have a way around this bug.

Thanks

**Comment by takluyver** [comment]
Thanks; I'm glad you got a workaround.

**Comment by vors** [comment]
I was looking for workarounds, thank you @takluyver for pointing out this

> For many programmes you can also override it by setting the ROWS and COLUMNS environment variables, which may offer another workaround.

One small correction: it's `COLUMNS` and `LINES`.
