### ISSUE TITLE
Auto-closing brackets/parentheses

### ISSUE THREAD

**Issue by bnaul** [jupyter/notebook#1431]
Per [this question](http://stackoverflow.com/a/33015443/233293), I have been using the following in `~/.jupyter/custom/custom.js` to disable auto-closing parentheses:

```
require(['notebook/js/codecell'], function (codecell) {
      codecell.CodeCell.options_default.cm_config.autoCloseBrackets = false;
})
```

Under `notebook==4.2.0` this works, but upgrading to `5.0.0.dev0` the default behavior is back. Is this a bug, or just a change in the way that this parameter is configured?

**Comment by takluyver** [comment]
@Carreau I think you recently changed how cells use the frontend config. Can you work out how to set something like this?

**Comment by Carreau** [comment]
> @Carreau I think you recently changed how cells use the frontend config. Can you work out how to set something like this?

I haven't [merged it yet](https://github.com/jupyter/notebook/pull/1423), but will investigate.

**Comment by Carreau** [comment]
Ok, so that will be really hard to fix. 

It's due to webpack. The module instance you get by `require()` in the custom JS is actually a completely different one that the one which is bundled by webpack. 

That is to say you actually have 2 complete version of CodeCell that are in the minified files....

**Comment by rainwoodman** [comment]
I suggest adding a maintained configuration file parameter for users who find this completion behavior strange to turn it off. 

While a great feature for slow typists to save some keystrokes, the latent surprise factor of this feature really clogs the mind-keyboard unity of fast typists.

**Comment by takluyver** [comment]
We're planning to back away from webpack, so the custom.js snippet above will hopefully start working again.
