### ISSUE TITLE
Disable all keyboard shortcuts

### ISSUE THREAD

**Issue by clb1992** [jupyter/notebook#1437]
I have a widget that features a dialog box in my notebook. However, I can't type in the box without a shortcut key being triggered.

I found documentation stating that I should remove them like so:

```
%%javascript

Jupyter.keyboard_manager.command_shortcuts.remove_shortcut('h');
Jupyter.keyboard_manager.command_shortcuts.remove_shortcut('m');
```

but I get an error stating that these are non-existent shortcuts.

Any suggestions?

**Comment by Carreau** [comment]
> I found documentation stating that I should remove them like so:

I'm curious where you found that. 

You need to call `keyboard_manager.register_events(yourelement)` to ignore any keypress that would be done in your custom input. That should be taken care of when you use widgets though.

**Comment by clb1992** [comment]
It's listed [here](https://github.com/jupyter/notebook/blob/41d6da235cbf3bcf6d7f818e11a066e0fd12ff8b/docs/source/examples/Notebook/Custom%20Keyboard%20Shortcuts.ipynb) on this repository

**Comment by Carreau** [comment]
This documentation does not state that you **should** remove them, this documentation is for each individual user to customize their keymap. We'll try to clarify. 

I see you closed so I guess my above answer solved it for you. 

Thanks.

**Comment by Gigan86** [comment]
I wonder if there is any way to remove all keyboard shortcuts. It seems that text input ipywidgets will activate all sorts of shortcuts just by typing something in. And if the shortcuts can only be removed one line at a time for each letter/number, I will need a lot of lines.

**Comment by takluyver** [comment]
ipywidgets should use the `register_events()` function,  which temporarily disables all keyboard shortcuts while they're focussed. If that's not working, please open an issue on ipywidgets.
