### ISSUE TITLE
Forward-port https://github.com/ipython/ipython/pull/8524

### ISSUE THREAD

**Issue by ssanderson** [jupyter/notebook#144]
Making an issue so I don't forget

**Comment by ssanderson** [comment]
https://github.com/ipython/ipython/pull/8524

**Comment by ssanderson** [comment]
Someone with access to such things can feel free to assign this to me.

**Comment by takluyver** [comment]
Thanks! Unfortunately, Github only lets us assign to people with push access to the repo, as far as I know.

**Comment by ssanderson** [comment]
Welp...I totally forgot about this.  Thanks for picking up my slack @takluyver.

**Comment by takluyver** [comment]
No worries. I had forgotten too, I just opened up issues with the 4.0 milestone and saw this. Thanks for filing it - it would definitely have got lost if you hadn't.
