### ISSUE TITLE
Kernel restarts automatically in Windows 10

### ISSUE THREAD

**Issue by vinayprabhu** [jupyter/notebook#1440]
My development workflow heavily revolves around jupyter notebooks. Things were picture perfect till I switched to a new laptop that came with pre-installed Windows 10.

I installed Anaconda 4.0.0  - Anaconda2-4.0.0-Windows-x86_64  (PYTHON 2.7 version) on Windows 10, with the following jupyter related specs:

- ipykernel	4.3.1
- jupyter	1.0.0	Jupyter metapackage / BSD	
- jupyter_client	4.2.2	Jupyter protocol implementation and client libraries / BSD	
- jupyter_console	4.1.1	Jupyter terminal console / BSD	
- jupyter_core	4.1.0	base package on which Jupyter projects rely / BSD

After about 2 hours of bug free running, the following 'KernelRestarter' error appears:

[I 15:32:21.026 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 7d78d41e-53e2-4730-97d4-c99356664bc3 restarted

![anaconda_error](https://cloud.githubusercontent.com/assets/7390549/15165247/4140df72-16c9-11e6-8e74-504cf58b6c79.png)

Any suggestions?

**Comment by takluyver** [comment]
Is there anything in the command prompt just before that KernelRestarter message that might indicate why it's crashed? I don't think we've heard of anything like this before. Could it be running out of memory?

**Comment by vinayprabhu** [comment]
As for memory, I have 16GB of memory and was running some light-weights scripts. 
I switched to Python 3.5 but still get the same error.

When I run the notebook server via the Anaconda prompt, this is the error message I get before the connection is reset:

[I 19:19:18.291 NotebookApp] Saving file at /Documents/Python Scripts/test.ipynb
Assertion failed: Software caused connection abort (bundled\zeromq\src\signaler.cpp:181)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:181)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:181)

**Comment by takluyver** [comment]
That sounds like it's ZMQ that's failing. @minrk might be able to suggest something.

**Comment by minrk** [comment]
That does sounds like a zmq problem, possibly with the conda zmq package. What version of the `pyzmq` and `zeromq` packages do you have?

**Comment by vinayprabhu** [comment]
The latest versions (I'd reckon):
zeromq=4.1.3
pyzmq=15.2.0

Update on the larger picture: 
I now have two Win 10 Laptops, ASUS GLV552-DH74 and Dell Inspiron 15 7559, running the same version of the OS (version 1511, Build 10586). Jupyter notebooks installed via Anaconda2-4.0.0-Windows-x86_64 (Both 2.7 and 3.5) work perfectly off the shelf in the Dell Inspiron laptop while the ASUS one croaks up after 2-3 hours *exactly* as described here:

https://github.com/ipython/ipython/issues/9236 
https://github.com/zeromq/libzmq/issues/1808

I have tried downgrading pyzmg to 14.x and with the anti-virus turned off and firewall disabled.
So far, nothing seems to work with the ASUS laptop.

**Comment by minrk** [comment]
It's possible that reinstalling zeromq and pyzmq will help. I'm not sure.

**Comment by fperez** [comment]
It looks like this isn't a notebook bug per-se, closing for now. It can be reopened on zmq if needed or if more information arises.

**Comment by shubhamgoel27** [comment]
I'm facing the exact same problem on Windows 10. 

I assume this does not just happen with the Jupyter notebooks. My Spyder IDE also crashes after an hour or so.

**Comment by VanitarNordic** [comment]
@shubhamgoel27 

Hi man. Could you solve your problem with Spyder crashing?

**Comment by shubhamgoel27** [comment]
@VanitarNordic 

Hi. Don't think I managed to. Are you facing a similar issue?

**Comment by VanitarNordic** [comment]
Yes
