### ISSUE TITLE
Command Palette and Tab key

### ISSUE THREAD

**Issue by EgZvor** [jupyter/notebook#1442]
I'm on Windows 10 with Chrome. When using Command Palette I can't complement by Tab, it just selects button.
![command_palette_issue](https://cloud.githubusercontent.com/assets/11237935/15188172/1207c178-17ad-11e6-81fe-4d0809b58849.png)

**Comment by fperez** [comment]
This isn't a bug, we don't have tab-based completion implemented at all on any platform.

I'll mark it as a wishlist item, but it's not something we're prioritizing right now for implementation soon. In the upcoming [JupyterLab](https://github.com/jupyter/jupyterlab), the system does support tab completion for commands, so this may have to wait til that comes out of alpha.
