### ISSUE TITLE
[docs] No screenshot on RTD

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1443]
RTD seem to have notebook embedded screenshot not available:

http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Notebook%20Basics.html

**Comment by willingc** [comment]
Thanks @Carreau for the heads up. Will look at Sphinx and nbsphinx.

Oddly, it looks good in GitHub. Including the link to the rendered doc on GitHub for others: https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb

**Comment by takluyver** [comment]
I'm not seeing any warnings in the doc build: https://readthedocs.org/projects/jupyter-notebook/builds/3992427/ . Might be an issue with nbsphinx.

**Comment by fperez** [comment]
This is a limitation of nbsphinx: it only supports images embedded with `![alt](path)` syntax, not with `<img src="path">` raw html syntax.

I'm closing this here and opening it on the nbsphinx repo. In the meantime, it means that if we want images in our docs from markdown cells, we must limit ourselves to the more basic syntax (which precludes custom size hints).  So we can use that workaround for now, until nbsphinx adds this feature.
