### ISSUE TITLE
[docs] Update keyboard customisation

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1444]
[Custom Keyboard Shortcuts.ipynb](https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Custom%20Keyboard%20Shortcuts.ipynb) is still relevant for fully custom action, but now there is the keyboard shortcut editor. 

You can edit via GUI, or the json directly (not recommended)

**Comment by Carreau** [comment]
See #2104

**Comment by takluyver** [comment]
Closed by #2104.
