### ISSUE TITLE
highlight selected word

### ISSUE THREAD

**Issue by Tagar** [jupyter/notebook#1449]
It would be really awesome to have Jupyter notebook 
to highlight selected word everywhere in the current cell.

This feature found in many IDEs. 

In some cells with lots of code or big chunk of output, it helps to visually help
other instances of that selected word.

**Comment by takluyver** [comment]
@juhasch @jcb91 - is this something that could be done in an extension? Is there already an extension that does it?

**Comment by jcb91** [comment]
I'm sure it _could_ be done, though I'm not aware of any current implementation (haven't looked specifically). It also sounds like the kind of thing which may have been implemented as a CodeMirror plugin. I'll have a look.

**Comment by jcb91** [comment]
something like https://codemirror.net/demo/matchhighlighter.html

**Comment by takluyver** [comment]
Good find, that's exactly it.

**Comment by jcb91** [comment]
now available packaged as a jupyter notebook extension at [jcb91/jupyter_highlight_selected_word](https://github.com/jcb91/jupyter_highlight_selected_word)

**Comment by takluyver** [comment]
Thanks @jcb91 !
