### ISSUE TITLE
Kernel Restarting..

### ISSUE THREAD

**Issue by jstitlow** [jupyter/notebook#1452]
Kernel dies every time I try to run scripts in jupyter notebook. 

Worked the first time, then failed the next 1,000 times I have tried. 

New jupyter install on OSX El Capitan version 10.11.4 using new Anaconda installation (Python 2.7)
Web app is running in Chrome (also fails in Safari and Firefox)

```
I 19:13:55.621 NotebookApp] Kernel started: c35a22e7-6c2f-42a4-9cd0-955a14d7bc00
[I 19:14:16.622 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel c35a22e7-6c2f-42a4-9cd0-955a14d7bc00 restarted
```

Any ideas?

**Comment by takluyver** [comment]
What are you running? Does it die if you run something trivial like `a=2`?

**Comment by jstitlow** [comment]
Doesn't die when running a=2. It was my code, thanks takluyver. 

Removing quit() from the code helped. Maybe quit() kills the kernel?

**Comment by takluyver** [comment]
> Maybe quit() kills the kernel?

That seems likely! ;-)
