### ISSUE TITLE
Cannot change kernel if current kernel broken.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1454]
`Notebook Dashboard` > `New Notebook` > `broken/missing kernel` (like I missclick on a missing conda-env kernel).

I now cannot change kernel anymore, well it **says** it changed, but does not. 
Even after save/reload.

**Comment by gnestor** [comment]
@Carreau How can I reproduce the broken/missing kernel part?

**Comment by Carreau** [comment]
hey, I would duplicate and existing kernelspec and just replace the executable by gibrish
```
$ jupyter kernelspec list
Available kernels:
  ...
  python3      /usr/local/share/jupyter/kernels/python3
```

```
$ cd /usr/local/share/jupyter/kernels
$ cp -r python3/ brokenkernel
$ sed -i bkp s/ython/broken/g brokenkernel/*.json  # missing p for Python on purpose as kernel name start with uppercase P. 
```

Does that make sens ?
