### ISSUE TITLE
Kerberos support in Jupyter

### ISSUE THREAD

**Issue by iyerrb** [jupyter/notebook#1460]
The requirement here is for Jupyter to be able to run in a Kerberos cluster where the authentication is performed at the cluster Gateway.

**Comment by SherryNJU** [comment]
Hi, Minrk, I see community close this requirement, does it mean community drop this feature and does not want to enable Jupyter with  Kerberos closet. @minrk

**Comment by minrk** [comment]
I believe people are able to use Jupyter with Kerberos via JupyterHub. @parente put together this example: https://github.com/jupyterhub/jupyterhub-example-kerberos

**Comment by SherryNJU** [comment]
Thanks Min, got that, will try with JupyterHub later.
