### ISSUE TITLE
Split input/output in separate files

### ISSUE THREAD

**Issue by Peque** [jupyter/notebook#1464]
I know [it has been discussed before](https://mail.scipy.org/pipermail/ipython-dev/2011-November/008351.html). Adding the possibility of separating input and output into different files would be a great advantage for version control in notebooks.

I would like to know if you reached an agreement against implementing separate input/output files or rather this feature was simply not implemented because nobody wanted to help (or maybe somebody is currently working on it or has worked on it before).

@minrk (pinging as you participated in that discussion back then, I think)

**Comment by takluyver** [comment]
We are planning to add a companion file. By default, that will be used for widgets, but I think we will add config options to put some or all output into the companion file rather than the notebook file. More details here: https://github.com/jupyter/roadmap/blob/master/companion-files.md

**Comment by blink1073** [comment]
@jasongrout and I were talking about this yesterday because we have the unfortunate situation that view data such as `collapsed` and `scrolled` are stored in the document itself, making it impossible to share a document between different views or users without also sharing that state.

https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json#L160

**Comment by Peque** [comment]
@takluyver That is really good news! I would love to have that possibility. :blush:

Is there a PR or Issue tracking that feature? or not yet? (just to subscribe so that I can receive updates)

**Comment by takluyver** [comment]
I've just created an issue to track it: https://github.com/jupyter/notebook/issues/1465

**Comment by yuvipanda** [comment]
There's also https://github.com/mwouts/jupytext, which does *some* of this work. The issues referred to from here have more info on ongoing work as well.

Going to close this one as there hasn't been any activity for a while, feel free to re-open if needed!
