### ISSUE TITLE
Migrate bundler mini-API from jupyter-incubater/contentmanagement to notebook

### ISSUE THREAD

**Issue by parente** [jupyter/notebook#1469]
Testing the waters here to see if I take the time to migrate all or part of the bundler ability out of the incubator project into a PR against notebook if it will past muster for inclusion.
## Current implementation doc

https://github.com/jupyter-incubator/contentmanagement#write-bundlers
## Use case

As a notebook user, I want to extend the available options under the File menu for transforming and/or packaging a notebook for download or deployment.
## Problem
1. The options under `File -> Download As` is fixed on both the server and client.
2. As an extension author, I have to implement both a server extension and a client extension to add one or more options.
## Solution already implemented in the incubator
1. Provide a reusable REST resource on the server that takes a bundler name, the name of a notebook, and invokes a well-defined API (function) in the named bundler's Python module).
2. Provide a Jupyter nbextension and config-based mechanism for registering bundlers from the `jupyter` command line.
3. Provide a resuable JS module that creates bundler entries under _Download As_ or _Deploy As_ in the notebook File menu based on the registered bundler metadata, and makes the appropriate XHR calls to the server-side bundler resource.
## Note

This feature is used heavily in the dashboards projects (e.g., by https://github.com/jupyter-incubator/dashboards_bundler) but has applicability beyond dashboards (e.g., bundle notebook-associated local files in a zip for download, https://github.com/jupyter-incubator/kernel_gateway_bundlers).

**Comment by Carreau** [comment]
I think the feature is more or less reasonable. I've marked is as 5.0.

**Comment by parente** [comment]
Thanks for having a look @Carreau.

**Comment by ellisonbg** [comment]
Fine with this, but because this makes a change to the server (which is also used for jupyterlab), we need to make sure that the server side of this will work with both notebook and jupyterlab. We definitely don't want to get into a situation where we have two server.

@fperez @jasongrout

**Comment by parente** [comment]
> we need to make sure that the server side of this will work with both notebook and jupyterlab.

I'm planning on making a first pass through porting what currently exists over nearly verbatim and only enabling it against the existing notebook UI to start. I hope then we can more easily see what needs to be adapted to fit jupyterlab, assuming we want to enable the idea of bundlers there too as well.

I believe the server side is pretty agnostic as to the UI. The client side JS will surely need translation to fit jupyterlab vs the current notebook.

**Comment by takluyver** [comment]
@parente can this be closed, as #1579 was merged?

**Comment by parente** [comment]
Yes. Thanks @takluyver . Didn't realize this was still lurking.
