### ISSUE TITLE
I can't run jupyter notebook via Terminal.app

### ISSUE THREAD

**Issue by crcrpar** [jupyter/notebook#1472]
I use Mac OSX el capitan.

When trying to `jupyter notebook` in  Terminal.app, they throw the error
> Native kernel (python2) is not available

I reffered [this issue](https://github.com/jupyter/notebook/issues/1280) and re-install `ipykernel`.
but couldn't solve.

**Comment by takluyver** [comment]
This is probably related to either which Python `jupyter` runs on, or something in the environment variables. Check `which jupyter`, look at the first line of that file to see the Python it runs with. Launch that Python in a terminal and try to import `ipykernel`.

**Comment by gnestor** [comment]
@crcrpar If you're still having issues running notebook, I highly suggest that you just install Anaconda which will install Python, Jupyter, and most of the libs that you might use with Jupyter. See the installation docs for more info.

**Comment by crcrpar** [comment]
I forgot to leave comment.
After that, I installed Anaconda.
I use jupyter notebook everyday.
Thank you
