### ISSUE TITLE
Notebook file can not be saved when file size is over 80MB

### ISSUE THREAD

**Issue by jianixrabbit** [jupyter/notebook#1478]
I plot some examples in the ggplot-package  with buildin datasets in IRkernel.
And the notebook file can not be saved when it's file size is more than 80MB+.
Then notebook server complains like this:

    [W 05:01:43.408 NotebookApp] Notebook bug/7.2 ggplot.ipynb is not trusted
    [I 05:01:46.356 NotebookApp] Kernel started: c2d9d14b-6e6d-4dfb-acde-a8678ea9614d
    [1] "Got unhandled msg_type:" "comm_open"              
    [I 05:02:42.302 NotebookApp] Malformed HTTP message from 192.168.11.100: Content-Length too long
    [I 05:02:42.303 NotebookApp] Malformed HTTP message from 192.168.11.100: Content-Length too long
    [I 05:02:42.304 NotebookApp] Malformed HTTP message from 192.168.11.100: Content-Length too long
    [I 05:02:42.305 NotebookApp] Malformed HTTP message from 192.168.11.100: Content-Length too long
    [I 05:02:42.307 NotebookApp] Malformed HTTP message from 192.168.11.100: Content-Length too long
    [I 05:02:42.308 NotebookApp] Malformed HTTP message from 192.168.11.100: Content-Length too long
    [I 05:02:42.309 NotebookApp] Malformed HTTP message from 192.168.11.100: Content-Length too long

Is this a bug?
Or is  there any setting concerned about updoad file size upper limit?

Sorry for my chinglish.

**Comment by takluyver** [comment]
It looks like tornado has a maximum body size of 100MB by default, and I don't think we override that anywhere:
https://github.com/tornadoweb/tornado/blob/a97ec9569b1995d8aa3da0a7f499510bffc006a3/tornado/iostream.py#L154

**Comment by yuvipanda** [comment]
Should we bump it up by default or just make it a configurable?

**Comment by yuvipanda** [comment]
Related? https://github.com/jupyter/notebook/issues/650

**Comment by takluyver** [comment]
Yep, that looks the same, thanks for the link. That already has quite a bit of discussion, so I'll close this one for now, and we can continue the discussion there.
