### ISSUE TITLE
Not showing math equations in Chrome/Firefox desktop

### ISSUE THREAD

**Issue by shahinism** [jupyter/notebook#1479]
The `mathjax` script is loading, but in equation places, it shows nothing (empty space). It has no problem in Android Chrome! I suggested font load problem, and manually installed fonts on my computer (mathjax otf fonts). Nothing changed. 

Python 3.4.1
Jupyter 4.2.0
mathjax 2.6.0 (Also tried latest version from CDN)
Google Chrome 50

**UPDATE:** 
I've tried the equation in [try.jupyter](https://try.jupyter.org), it works fine. I also tried it with Gnome web browser and it works with no problem either. 

**UPDATE 2**
The notebook is accessible from an `nginx` server with enabled ssl, here is configuration:

```
    location / {
            proxy_pass http://localhost:8888;

            proxy_set_header X-Real_IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;
            proxy_set_header Host $http_host;

            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
    }
```

Also the `jupyter` is configured as follow:

```

import sys
sys.path.append('/root/.local/share/jupyter/extensions')
c.NotebookApp.allow_origin = '*'
c.NotebookApp.ip = 'localhost'
c.NotebookApp.open_browser = False
```

**Comment by Carreau** [comment]
:-( that's weird I have no idea. Can you open the javascript console of your browser and check for errors ?

**Comment by shahinism** [comment]
Here is total output:
![selection_147](https://cloud.githubusercontent.com/assets/698857/15969901/4a29ab28-2f47-11e6-9707-ba2d938a98ad.png)

**Comment by Carreau** [comment]
You seem to have some extensions enabled, can you try to disable them and see if it persists ? I'm unsure what can be causing that.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Let us know if this issue persists after you've disabled extensions.

Thanks everyone and happy hacking! :bowtie: @
