### ISSUE TITLE
Unrecognized JSON config file version

### ISSUE THREAD

**Issue by michaelaye** [jupyter/notebook#1480]
Since notebook v4.2 I see this at the launch of my notebook server:
```bash
[W 15:03:41.744 NotebookApp] Unrecognized JSON config file version, assuming version 1
```
What could this be? Disclaimer: I'm using `nb_conda_kernels`, just in case that can mess things up?

System: OSX 10.10.5, conda python 3.5 env, all up-to-date

**Comment by minrk** [comment]
It's a harmless and largely meaningless warning about unused metadata. The warning is removed in current master of traitlets, and will go away with the next traitlets release.

**Comment by Gideonamani** [comment]
And when is the next traitlets release going to be..?

**Comment by michaelaye** [comment]
On July 1st there was 4.2.2 but the error is still there?

**Comment by Gideonamani** [comment]
Yeaah I can still see it in my prompt whenever I start notebook.

**Comment by minrk** [comment]
Hopefully soon. I'm working on the traitlets 4.3 release now.

**Comment by Gideonamani** [comment]
Thank you.

**Comment by ophite** [comment]
still see this

**Comment by minrk** [comment]
@ophite traitlets 4.3 should ship this week.

**Comment by andrebeu** [comment]
I'm still getting this
