### ISSUE TITLE
support for Shiny R

### ISSUE THREAD

**Issue by steverweber** [jupyter/notebook#1484]
support for Shiny R would be nice.

seems zeppelin might also work on this.
https://github.com/elbamos/Zeppelin-With-R/issues/18

**Comment by takluyver** [comment]
This would mainly be an issue for [IRkernel](https://github.com/IRkernel/IRkernel), though there might be some architectural considerations - from the linked issue, it sounds like shiny expects a direct network connection from the browser to the kernel, which isn't necessarily easy with Jupyter.

**Comment by elbamos** [comment]
@takluyver Yes that's correct. 

I thought it would require considerable effort.

On the other hand, it might also make sense as a collaboration between the folks who work on IRkernel, and me on the Zeppelin side.  Perhaps we could convince RStudio to put in whatever hooks are necessary to facilitate working with notebook interfaces.

**Comment by Carreau** [comment]
> On the other hand, it might also make sense as a collaboration between the folks who work on IRkernel, and me on the Zeppelin side. 


> Perhaps we could convince RStudio to put in whatever hooks are necessary to facilitate working with notebook interfaces. Considering that rstudio now has its own R notebook interface, perhaps this won't be a hard ask.

Maybe, I don't think we would be against. It's probably a hard sell, usually the RStudio user community tend to be divided from the Jupyter one. Someone could still try to have the 2 groups discussing.

**Comment by steverweber** [comment]
the spirit of the opensource should bring us together.

perhaps @jjallaire one of the most active users at https://github.com/rstudio/rstudio could drop a line.

**Comment by jjallaire** [comment]
Yes, as you said we're currently working on our own notebook interface based on R Markdown. It would indeed be cool to be able to host multiple types of notebooks within RStudio but there would considerable architectural issues to surmount so not something we can pursue in the short term.

**Comment by elbamos** [comment]
I don't think we want to host other notebooks within RStudio. Rather, we want to make it possible for people using other notebooks to run shiny apps in their notebooks.

**Comment by jjallaire** [comment]
Ah, got it! I don't think there is anything in principle that would prevent integrating Shiny with other notebooks (the shiny package is entirely decoupled from RStudio). One problem (which is shared by the RStudio IDE notebook) is that running a Shiny application currently blocks the console/UI entirely. This isn't a problem when you are running a standalone Shiny application but of course is a a problem when you want to use Shiny as an embedded component within an interactive session.

We have some work we are planning to enable "background" execution of Shiny applications (i.e. still running on the main thread but not blocking the REPL). Once this is done it should be straightforward for all notebook interfaces to take advantage of.

**Comment by elbamos** [comment]
That's exactly what we're looking for - thanks! Can you let us know when there's testing code?

**Comment by jjallaire** [comment]
Yes, will do!

**Comment by saahilguptaq** [comment]
Hi
Any updates on R Shiny integration with Zeppelin? Is it possible now?
Help will be greatly appreciated @elbamos  @jjallaire  @takluyver @Carreau

**Comment by takluyver** [comment]
This is a Jupyter issue tracker, not Zeppelin.

**Comment by saahilguptaq** [comment]
Posted it in a wrong group! My bad..

**Comment by yuvipanda** [comment]
When https://github.com/jupyterhub/nbrsessionproxy/pull/25 gets merged it'll support running Shiny from within the RStudio spawned by it. This isn't direct integration with notebooks, but seems more than good enough for most JupyterHub / Binder deployments!

**Comment by yuvipanda** [comment]
You can test this out just now at https://mybinder.org/v2/gh/yuvipanda/binder-1/master?urlpath=rstudio

**Comment by cgpu** [comment]
> When [jupyterhub/jupyter-rsession-proxy#25](https://github.com/jupyterhub/jupyter-rsession-proxy/pull/25) gets merged it'll support running Shiny from within the RStudio spawned by it. This isn't direct integration with notebooks, but seems more than good enough for most JupyterHub / Binder deployments!

@yuvipanda Any update on that? Is this feature functional? I understand that this is too much of a stretch for a Jupyter Notebook, but! For teaching `ggplot2` with [dreamRs/esquisse](https://github.com/dreamRs/esquisse) this would be dreamy!

**Comment by yuvipanda** [comment]
@cgpu yep it works. Check this out: https://github.com/binder-examples/r

**Comment by cgpu** [comment]
> @cgpu yep it works. Check this out: https://github.com/binder-examples/r

Woah this is awesome! 🎉 Thanks @yuvipanda.

**Comment by yuvipanda** [comment]
yw, @cgpu. 

I'm going to close this. If you'd like Shiny support in the R kernel, please open an issue in the [IRKernel repo](https://github.com/IRkernel/IRkernel).

**Comment by heisenbug47** [comment]
Hello people, 

It is an old thread, but just checking if it is possible to run shiny apps in Jupyter notebook yet ?

Out of blues I am asked to run an existing shiny app in Jupyter notebook by client and I dont know how to do it or is it possible or not :( 

Any small guidance is appreciated.
