### ISSUE TITLE
Jupyter notebook wont save to PDF if i use ijulia dataframes

### ISSUE THREAD

**Issue by Shaun1818** [jupyter/notebook#1485]
The jupyter notebook will not save as a "pdf via latex" when i am using the data frames package for ijulia.

I get the following error

![image](https://cloud.githubusercontent.com/assets/19259454/15523726/89ce7eea-2270-11e6-951f-015414c7021f.png)

Not sure if this is a jupyter, ijulia or dataframe issue, so thought i would post here first.

**Comment by minrk** [comment]
Closing in favor of https://github.com/jupyter/nbconvert/issues/314
