### ISSUE TITLE
no module

### ISSUE THREAD

**Issue by SERA-PHIM** [jupyter/notebook#1486]
I got an import error when I tried to run python locally.
> ImportError: No module named IPython.core.display

I googled and found the issue quite similar to an existed one (https://github.com/jupyter/notebook/issues/270) except that the path is correct.

`pip list` gives me `ipython (4.0.0)` and
`python -m IPython --version` gives me `No module named IPython`.

I installed jupyter with `pip` and I'm pretty sure it's updated. Did I miss something?

**Comment by takluyver** [comment]
There are most likely separate copies of Python installed in different locations. Try `which python` and `which pip`, and look at the first line of the `pip` script to see what Python it's using.

**Comment by SERA-PHIM** [comment]
Oh! That must be it. I installed both python 3.4 and python 3.5. But pip is using 3.5.
`/Library/Frameworks/Python.framework/Versions/3.5/bin/pip`
Shall I uninstall 3.4?

**Comment by takluyver** [comment]
OK, closing this as it doesn't seem to be an issue for us to fix.
