### ISSUE TITLE
`base_url` is unencoded in `notebook/jstest.py`

### ISSUE THREAD

**Issue by jcb91** [jupyter/notebook#1489]
From #295 and #472, the base_url parameter is always treated as already-encoded. In [notebook/tests/launchnotebook.py#L46](https://github.com/jupyter/notebook/blob/4e359c921fb503ba3782a67cbd5ed221b081a478/notebook/tests/launchnotebook.py#L46), the base_url parameter was fixed in #472, but it seems that [notebook/jstest.py#L227](https://github.com/jupyter/notebook/blob/4e359c921fb503ba3782a67cbd5ed221b081a478/notebook/jstest.py#L227), got missed, as it's still set unencoded.

**Comment by minrk** [comment]
`@` is a safe character in encoded URLs, so I think this was intentional. Perhaps it would be clearer if base_url were `'a@%20b'`.

**Comment by jcb91** [comment]
Mmm, ok, I think I follow. This whole issue got rapidly confusing for me, as `@` is a reserved character of gen-delim type in URIs, along with `:`, `/`, `?`, `#`, `[`, and `]`
`(https://tools.ietf.org/html/rfc3986#page-12), and as such shouldn't be used in components of a scheme which rely on it as a delimiter. Trying to decide which delimiters were ok and which weren't eventually led me to [this SO question/answer](http://stackoverflow.com/questions/2366260/whats-valid-and-whats-not-in-a-uri-query) which finally cleared it up for me: `@` _is_ ok in http[s] scheme URLs, even though it may not be ok in URIs for other schemes, depending on how those schemes use it.

I ran into this as a problem when building testing for extensions, and presumably got confused over [`encodeURI`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) vs [`encodeURIComponent`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), as the former doesn't escape the `@`, while the latter (as used in `utils. encode_uri_components` in [notebook/static/base/js/utils.js#L541](https://github.com/jupyter/notebook/blob/4e359c921fb503ba3782a67cbd5ed221b081a478/notebook/static/base/js/utils.js#L541)) does.

I guess it would make the intent a little clearer to add an escaped character as well!
