### ISSUE TITLE
Nice printing of pandas.Series

### ISSUE THREAD

**Issue by mhooreman** [jupyter/notebook#1491]
Hello,

If we generate a pandas.DataFrame at the end of a cell, that DataFrame will be nicely shown.

If we do the same with a pandas.Series, it is shown as text. To have the nice display, we have to make a DataFrame of that Series.

Would it be possible to implement the nice printing for Series?

Thanks a lot!

**Comment by jorisvandenbossche** [comment]
@mhooreman this is the responsibility of the pandas library, not the notebook, I think.

And there are some issues on this: https://github.com/pydata/pandas/issues/5563, https://github.com/pydata/pandas/issues/8750, https://github.com/pydata/pandas/pull/10300. 
Providing a `_repr_html_` for series is not difficult, but the question is also how it should look like to be able to distinguish it from a one column dataframe.

**Comment by Carreau** [comment]
Thanks for responding @jorisvandenbossche , you can also register your own display formatter without patching Pandas. 

Closing as this is not something to do here.

**Comment by mhooreman** [comment]
Thanks for your replies
