### ISSUE TITLE
Cannot delete files or folders from web ui when when running from docker

### ISSUE THREAD

**Issue by ylaizet** [jupyter/notebook#1492]
Hello,

in the webUI tree view, folders and files are listed. From a pip installation of jupyter notebook, I can delete any file or folder by clicking on the bin icon and confirm the deletion. If now, I run jupyter notebook from the docker image, after confirming the deletion of the file/folder, nothing happens.

Would you have a clue of the problem?

Thanks

EDIT : renaming works perfectly but not delete

EDIT2: I pushed a little further and I figured out that the problem exist in the latest tagged docker container of jupyter notebook (version with the move button in the webUI) but not in the stable tagged version (without the move button).

**Comment by Carreau** [comment]
The docker image is not maintained, we shoudl likely remove it

**Comment by ylaizet** [comment]
Hi,

what a pity. This was pretty straight forward to use it quickly. By the way, just changing the version of the revision made the trick for me.
Thanks anyway for the answer.

**Comment by takluyver** [comment]
We still maintain docker files for running the notebook server - just not in this repo. You can find them in the docker-stacks repo:
https://github.com/jupyter/docker-stacks

Closing this issue because #1553 removed the docker file from this repo.
