### ISSUE TITLE
library problem with ImageMagick

### ISSUE THREAD

**Issue by poldrack** [jupyter/notebook#1493]
I have a notebook that worked several months ago but is now failing, due to problems with the ImageMagick library being read by the wand package.  Same problems occur for both python 2.7 and 3.5 (using anaconda).  The following works fine in ipython console:

```
(py3k)Russells-MBP:$ ipython
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55)
IPython 4.2.0 -- An enhanced Interactive Python.

In [1]: import wand.api

```

(no errors reported)

However, running the same import command under Jupyter (4.1.0) notebook I get the following error:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/Users/poldrack/anaconda/envs/py3k/lib/python3.5/site-packages/wand/api.py in <module>()
    178 try:
--> 179     libraries = load_library()
    180 except (OSError, IOError):

/Users/poldrack/anaconda/envs/py3k/lib/python3.5/site-packages/wand/api.py in load_library()
    133         return libwand, libmagick
--> 134     raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
    135 

OSError: cannot find library; tried paths: []

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-a5cdecdc3dd8> in <module>()
----> 1 import wand.api

/Users/poldrack/anaconda/envs/py3k/lib/python3.5/site-packages/wand/api.py in <module>()
    203     raise ImportError('MagickWand shared library not found.\n'
    204                       'You probably had not installed ImageMagick library.\n'
--> 205                       'Try to install:\n  ' + msg)
    206 
    207 #: (:class:`ctypes.CDLL`) The MagickWand library.

ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  brew install freetype imagemagick
```

I have confirmed that both are running the same executable using sys.executable

It seems that the library is visible to the ipython console:

In [4]: ctypes.util.find_library('MagickWand-6.Q16')
Out[4]: '/usr/local/lib/libMagickWand-6.Q16.dylib'

but not to jupyter (no output from same command).

**Comment by poldrack** [comment]
forgot mention OS - Mac OS X 10.11.5

**Comment by takluyver** [comment]
I can't think of any obvious reason why those would be different other than running different Pythons, which you've already checked. Can you dig deeper inside `ctypes.util.find_library()` to see where the difference is?

**Comment by JamiesHQ** [comment]
@poldrack : We're doing a little housekeeping on our issue log and noticed this thread from 2016. Were you able to find a solution to your issue? Please let us know! We'll close this issue if you found what you need. thanks!

**Comment by poldrack** [comment]
I don't think it was ever solved, but I just gave up on using the wand library which obviated it for me :-)

**Comment by JamiesHQ** [comment]
Ok, thanks @poldrack ! I'll close the issue. Feel free to re-open the issue if you ever want to give it another go and experience the same problem.
