### ISSUE TITLE
JS error with notebook master on Windows

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter/notebook#1495]
When trying to run the `jupyter notebook` from source I get a blank page and the following error in the console:
![image](https://cloud.githubusercontent.com/assets/881019/15594465/fd49aa0a-23f8-11e6-96ef-96484613df2d.png)

Being a JS noob I'm not sure how to debug this but am happy to provide any further info if required...

**Comment by Carreau** [comment]
Hi there, sorry for the delay. Can you try to issue a `npm run build` from the root of the source directory ?

**Comment by dhirschfeld** [comment]
Just tried with the latest:
```
git pull
npm run build
python setup.py js css
pip install -e .
```
...but it fails with the same error
![image](https://cloud.githubusercontent.com/assets/881019/16140896/ff86d6ac-3498-11e6-853c-29c75fbab364.png)

**Comment by Carreau** [comment]
hum... can you force refresh, go to the `...` > `settings` of the developper panel and check  `enable source maps`. That might give more information on which file it comes from .

**Comment by dhirschfeld** [comment]
Sorry, pretty low bandwidth for this at the moment - I *think* it may be something to do with incompatible settings or possible the fact that I'm running from a different base_url.  Hopefully I'll have time to revisit it shortly...

**Comment by dhirschfeld** [comment]
Closing because this is pretty old so I doubt it's relevant anymore...
