### ISSUE TITLE
DOC: Trust secret key location wrong?

### ISSUE THREAD

**Issue by michaelaye** [jupyter/notebook#1499]
The current (4.x) [security docs](http://jupyter-notebook.readthedocs.io/en/4.x/security.html) say this about the location of my secret key:
>![screenshot 2016-05-28 22 24 07](https://cloud.githubusercontent.com/assets/69774/15631355/41ffb3a8-2523-11e6-83c3-9913a164f362.png)

But I just trusted some notebooks and I don't have this folder.
So, I thought, `jupyter` doesn't have profiles anyway, to my knowledge, so they must mean  `.ipython/profile_default/security`, b/c that folder I actually have. But also no success, no `notebook_secret` file there either.
Then I searched my computer (OSX) and was successful:
`/Users/klay6683/Library/Jupyter/notebook_secret`
which happens to be $(jupyter --data-dir)/notebook_secret, so should this be changed in the docs?

**Comment by takluyver** [comment]
Yep, that doc is wrong, thanks for spotting it!

**Comment by minrk** [comment]
#1503 should update it a bit
