### ISSUE TITLE
Cell not executing ~ every other time:

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1502]
In jupyter lab:

![exec-wrong](https://cloud.githubusercontent.com/assets/335567/15684254/250ee22e-271b-11e6-95dd-d9cbaa080076.gif)

**Comment by Carreau** [comment]
PIng @ellisonbg , actually looking at the gif, it seem that the cell does not get focus as it is not green, when I change back `b` to `a`.

**Comment by ellisonbg** [comment]
I am having trouble following the gif. Looks like you never defined b, so you get a name error? But I think you are saying there is something else going on right?

Previously, running a cell only worked in edit mode - not sure if that has been fixed yet. May be that issue.

**Comment by Carreau** [comment]
Sorry 

```
a=1
a
```

All great, 

```
a=1, 
b
```

Name error b not defined

```
a=1
a
```
Name Error, b not defined. 

So the Third time as execute, the second version of the cell is sent to the kernel.

**Comment by ellisonbg** [comment]
Opened up this on the jupyter-js-notebook repo:

https://github.com/jupyter/jupyter-js-notebook/issues/226
