### ISSUE TITLE
Calling `%qtconsole` in a notebook generates a qtconsole without a prompt

### ISSUE THREAD

**Issue by aweinstein** [jupyter/notebook#1505]
Calling `%qtconsole` in a notebook generates the qtconsole windows, but there is no prompt in the qtconsole. See attached screenshot.

I'm running jupyter 4.1.0, with Python 3.5 (Anaconda installation).

![screenshot from 2016-06-02 13 27 51](https://cloud.githubusercontent.com/assets/123405/15754376/4dff4dcc-28ce-11e6-851d-a0590cd1e323.png)

**Comment by takluyver** [comment]
I can reproduce it, but if I hit enter, I see a prompt. Does that work for you too?

I think this is more likely to be a qtconsole bug than a notebook bug - pinging @ccordoba12 .

**Comment by aweinstein** [comment]
@takluyver Yes! I see the prompt after hitting enter.
