### ISSUE TITLE
Remove dockerfile. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1514]
See discussion in https://github.com/jupyter/notebook/pull/1468.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:

**Comment by willingc** [comment]
Oops!

**Comment by minrk** [comment]
closed by #1553
