### ISSUE TITLE
Equivalent to MATLAB's Workspace?

### ISSUE THREAD

**Issue by cqcn1991** [jupyter/notebook#1516]
Is there any Matlab workspace equivalent in Jupyter Notebook that I can directly check for the variables that I'm using? And I can also easily copy them out for other use?

In MATLAB, the workspace look like this:

[![enter image description here](http://i.stack.imgur.com/XyTKP.png)](http://i.stack.imgur.com/XyTKP.png)

Or, if there is none, is there any related resources that I can read, so I can make one on my own?

**Comment by Carreau** [comment]
You are likely looking for somehting like [this](https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Variable%20Inspector.ipynb)

**Comment by cqcn1991** [comment]
@Carreau Thanks! This looks amazing. Is there any more finished code that I can use? For example, show the list, matrix in table so people can copy and paste things into things like excel.

**Comment by Carreau** [comment]
I'm not sure. We are pretty low on manpower, so there is not a lot of work in this area. 
It should be pretty easy to pick up and improve though.

**Comment by ellisonbg** [comment]
There is pretty strong interest in building this as a jupyterlab (https://github.com/jupyter/jupyterlab) plugin.

**Comment by JamiesHQ** [comment]
@ellisonbg : should this issue be ported over to the JLab org? thx!

**Comment by janschulz** [comment]
This is now implemented as a plugin for the notebook in http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/ -> variable explorer
