### ISSUE TITLE
Github problem displaying some gadfly graphs

### ISSUE THREAD

**Issue by kescobo** [jupyter/notebook#1521]
This may not be the right place to bring this up - I think this is a problem with github rendering of a notebook, but don't know where else to comment.

I have a [notebook](https://github.com/kescobo/gender-comp-bio/blob/name_stats/src/gender_stats.ipynb) uploaded to github with julia code that has a number of graphs plotted in `Gadfly`. Many of the graphs display correctly, but for a couple of them I get a broken SVG image and some code:

```
",b=!1);m.innerHTML=c;if(c=m.getElementsByTagName("svg")[0])if(b)a=c;else for(;c.firstChild;)a.appendChild(c.firstChild);m.innerHTML=aa;return new l(a)};l.prototype.select=e.prototype.select;l.prototype.selectAll=e.prototype.selectAll;a.fragment=function(){for(var c=Array.prototype.slice.call(arguments,0),b=G.doc.createDocumentFragment(),m=0,e=c.length;m
```
![screen shot 2016-06-07 at 3 52 40 pm](https://cloud.githubusercontent.com/assets/3502975/15872531/f191bd88-2cc7-11e6-8e6d-54210133f10f.png)

I can't see anything obvious about why these two graphs are different (they're all bar graphs with very similar plotting instructions). They also display correctly when I open the notebook in my browser locally. 

I tried to fix by re-running every cell and then re-committing to the repository, but the same two graphs are broken

**Comment by Carreau** [comment]
My guess is that for security reason. GitHub will sanitise the svgs (for good reason) and is likely overprotective. 

It [will render fine on nbviewer](https://nbviewer.jupyter.org/github/kescobo/gender-comp-bio/blob/name_stats/src/gender_stats.ipynb). 

You can try to contact GitHub Support if you like, but I doubt they can do anything.

**Comment by kescobo** [comment]
Makes sense, thanks!

**Comment by kescobo** [comment]
I sent the issue to github support, but for now I can use nbviewer.
