### ISSUE TITLE
Notebook terminal broken

### ISSUE THREAD

**Issue by ian-r-rose** [jupyter/notebook#1528]
In recent builds of the notebook, the making a new terminal window fails.
Nothing is shown in the browser window, and the javascript console gives the error 

``require.js:140 Uncaught Error: Module name "codemirror/lib/codemirror" has not been loaded yet for context: _. Use require([])``

01ffff7 does not work, a5ad979 is working.

**Comment by fperez** [comment]
Thanks @ian-r-rose! This is pretty serious, confirming here on master...

**Comment by Carreau** [comment]
And that was introduced when fixing syntax highlighting in #1490  by @blink1073

**Comment by blink1073** [comment]
Argh!  I'll try and come up with a non whack-a-mole solution...

**Comment by Carreau** [comment]
> Argh! I'll try and come up with a non whack-a-mole solution...

No problem, we don't blame you. We probably do need the same modif for the terminal, 
you showed us the way we might be able to see the light on our own !
