### ISSUE TITLE
Shutdown/Restart Server menu item: Feature Request

### ISSUE THREAD

**Issue by GadgetSteve** [jupyter/notebook#1530]
Many times when running Jupyter notebooks I find myself wishing for a quick clean mechanism to cleanly shutdown &/or restart the server without having to go to the command window that it is running in and hit control-C and without the risk of not having saved and shutdown all kernals that may be running at the time.

Giving it some thought this feature needs a mechanism for disabling &/or hiding it on Jupyter servers that the user should not be able to shutdown or as a configuration item that on a specific machine this is enabled or not so that on a server the configuration would, _normally_, be **no** shutdown/restart entries - _possibly with the command line option of starting a server with them enabled for testing_ - but on a personal machine the option could be set to enable them, and possibly to hide the command window.

**Comment by Carreau** [comment]
I **think** we can consider that covered by jupyterhub:

<img width="761" alt="screen shot 2016-06-16 at 16 32 54" src="https://cloud.githubusercontent.com/assets/335567/16136519/043b06a0-33e0-11e6-9655-d1fd82df8c36.png">

Which is reasonable to use even on a local machine. 

Though it will **not** warn you if you have multiple notebook/kernels running.

**Comment by GadgetSteve** [comment]
@Carreau I suspect that many users would find running jupyterhub a little intimidating - certainly at work I only use Jupyter a part of the time so would not wish to have the hub running all of the time.

**Comment by takluyver** [comment]
I do think it makes sense to have a way to shut down notebook servers besides interrupting them in a terminal. [Nbmanager](https://github.com/takluyver/nbmanager) is one tool I wrote to do this. It probably needs some updates by now to work with Jupyter, but that should be easy enough if anyone's interested.

**Comment by JamiesHQ** [comment]
@GadgetSteve : We're doing a little housekeeping on our issue log and noticed this thread from 2016. Did you try [nbmanager](https://github.com/takluyver/nbmanager) and were you able to find a solution to your issue? Please let us know! We'll close this issue if you found what you need. thanks!

**Comment by GadgetSteve** [comment]
@JamiesHQ : Thanks for pointing out nbmanager but I would have expected server shutdown to be a part of the core functionality of Jupyter rather than an external utility, or using Control-C in the shell/command window.
@takluyver : It is helpful that nbmanager shows the users currently running notebooks - I wonder if it wouldn't be possible to hook it into a button next to the jupyter logout, (with it defaulting to the current server selected).

**Comment by takluyver** [comment]
We've also recently added a `jupyter notebook stop <portno>` command - #2388.

**Comment by GadgetSteve** [comment]
@takluyver so from another terminal, or a desktop shortcut, I can effectively send a control-c to the running server? That does help in the case where a server has been started without a terminal window to press control-c in but still means leaving the Jupyter UI.

**Comment by takluyver** [comment]
Yup. I think I actually tried to add a 'shutdown server' button years ago when the notebook was quite new, but people didn't want it. Maybe it would be more welcome now. It goes to the tension between the notebook as a local application and as a web server.

**Comment by JamiesHQ** [comment]
@GadgetSteve : @gnestor is leading the classic notebook development these days. Copying him here. Thanks!

**Comment by taion** [comment]
This is relevant for us – we currently run Jupyter notebook instances through SGE (actually inside Docker containers), and it would be nice to be able to shut down those notebook servers through the web front end, rather than issuing a `qdel` to terminate them.

**Comment by takluyver** [comment]
#2507 would add an HTTP handler so you can shut down the server with a POST request to `/api/shutdown`. I haven't tried to build UI for it yet.

**Comment by nthiery** [comment]
+1 on a shutdown UI, especially for local use. Beginners often are unfamiliar with using the terminal, and get confused why they need to close/quite two things (experience gathered at the occasion of large classes or training workshops).
As an aside, with such a UI, one often could just hide that terminal (e.g. if jupyter is started through an icon).

**Comment by gyzmau** [comment]
+ for the shutdown in the UI.
My need is as well for a local use.
It might been put it as an option, disabled by default. In this way persons who really need it , will activate it in the options.

**Comment by gnestor** [comment]
Ok it looks like there's some demand for this feature so see https://github.com/jupyter/notebook/pull/3004 for an implementation 👍

![](http://g.recordit.co/clpbqxgy2s.gif)

**Comment by nthiery** [comment]
Looking forward to the next Jupyter release :-)
Thank you guys!
