### ISSUE TITLE
How to auto close brackets and quotes in .py and other text file.

### ISSUE THREAD

**Issue by AndreWin** [jupyter/notebook#1531]
Hello!

I opened .py file in Jupyter Notebook. I type `print(` and expect that bracket will close automatically. But it is missed. Other case: I selected some text in .py file, for example `x1`, and pressed `"` (double quote). My text is removed and double quote is typed.

I know that codemirror is used in Jupyter, but how to set up it?

Best regards, Andrey.

**Comment by Carreau** [comment]
I don't think there is any simple option to do that, you will likely need to create a `custom.js` files that modify the configuration of the page on the fly. That's not really documented APi thoughs.

**Comment by gnestor** [comment]
I'm going to close this due to inactivity in the interest of getting our issues under control.
