### ISSUE TITLE
Directory listing should not show hidden or system files

### ISSUE THREAD

**Issue by mkoske** [jupyter/notebook#1532]
Hello,

if a file is hidden (or is system file) by operating system in OS's file browser, it should be hidden also in Jupyter's file / directory listing.

This happens at least on my Windows 8 system, when I launch notebook and go to browser, it shows hidden and system files in the listing.

**Comment by Carreau** [comment]
We do have [logic](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L273-L277) that hides these files. The probable cause is tha the [`is_hidden(...)`](https://github.com/jupyter/notebook/blob/master/notebook/utils.py#L82) function is broken. 

If you can figure out why it does not work, and/or what should be added, that would be great, as none of us has windows machine, it's hard to narrow down.

**Comment by mkoske** [comment]
@Carreau I looked at it and I think it might be because when comparing return value from `GetFileAttributesW`, it is compared only against 0x02, which is hidden-attribute. But when the file is also system file at same time, it probably should be taken into account, right? At least this comparision against 0x02 seems to return 0 for files which has both system and hidden attributes.

Like this:
```python 
_win32_FILE_ATTRIBUTE_HIDDEN = 0x02 | 0x04 # 0x04 means system file
# ...
if attrs > 0 and attrs & _win32_FILE_ATTRIBUTE_HIDDEN:
# ...
```

**Comment by takluyver** [comment]
I think that would only hide files that are both hidden and system. You probably need something like:

```
if attrs > 0 and ((attrs & HIDDEN) or (attrs & SYSTEM)):
```

**Comment by mkoske** [comment]
@takluyver ok, but hope the idea was correct

**Comment by mkoske** [comment]
Here's the list of file attribute constants:
- https://msdn.microsoft.com/en-us/library/windows/desktop/gg258117(v=vs.85).aspx

**Comment by takluyver** [comment]
I think the idea is probably correct - I'm not very familiar with Windows file attributes, but it sounds reasonable.

**Comment by mkoske** [comment]
Hello again! I looked at it more, and noticed, that I was wrong. System files seems to be hidden also, so just checking if it has hidden attribute should work. But [here](https://github.com/jupyter/notebook/blob/master/notebook/utils.py#L131) the `path`-variable is modified and it contains only directory name and is always the same. And after modifying, it is used to get attributes for that `path`, which is always the same. You should check [here](https://github.com/jupyter/notebook/blob/master/notebook/utils.py#L135) the `abs_path`-variable. Changing this line to use `abs_path`, it works as it should.

**Comment by takluyver** [comment]
Good catch, do you want to make a PR?

**Comment by mkoske** [comment]
Done.

**Comment by rgerkin** [comment]
I am currently in a situation where I would like the hidden files to be shown (at least certain ones), so that I could edit them in the Jupyter editor, or screenshot a directory listing showing a hidden file (which happens to be a configuration file I'd like to highlight).  

Is there any interest in a configuration option that would show hidden files?
