### ISSUE TITLE
iframe does not display from within indented structure

### ISSUE THREAD

**Issue by poldrack** [jupyter/notebook#1537]
the following works within a jupyter notebook (jupyter 1.0, ipython 4.2.0, python 3.5):

IFrame('https://web.stanford.edu/group/poldracklab/fmri-handbook-2e-data/figures-1e/Figure_1_1.pdf',width=300,height=300)

but this does not (i.e. same call but emebedded in an if structure):

if 1:
    IFrame('https://web.stanford.edu/group/poldracklab/fmri-handbook-2e-data/figures-1e/Figure_1_1.pdf',width=300,height=300)

**Comment by takluyver** [comment]
Both create an `IFrame` object, but it's only automatically displayed if it's the last thing in the cell. You can explicitly display it with the `IPython.display.display()` function.

This is exactly the same as seeing output when you do:

```python
a = 4
a
```

But not when you do:

```python
a = 4
if 1:
  a
```

**Comment by poldrack** [comment]
thanks!
