### ISSUE TITLE
Dockerfile CMD contains unsupported flag --allow-root

### ISSUE THREAD

**Issue by jsnowacki** [jupyter/notebook#1539]
The `jupyter/notebook` base Dockerfile contains line:
```
CMD ["jupyter", "notebook", "--no-browser", "--allow-root"]
```
which causes an error:
```
[36mjupyter_1  | [0m [C 14:51:25.484 NotebookApp] Bad config encountered during initialization:
[36mjupyter_1  | [0m [C 14:51:25.484 NotebookApp] Unrecognized flag: '--allow-root'
```
It seems that the flag has been removed from Jupyter, as removing the offending flag `--allow-root` fixes the issue and the Docker image seems to work fine.

Cheers,

Jakub

**Comment by takluyver** [comment]
It was only added less than a month ago  - #1468. The `--allow-root` flag was a recent addition (#1115), not a recent removal.

**Comment by jsnowacki** [comment]
Thanks for the clarification. The bottom line is that if you pull docker image from the docker hub, i.e. https://hub.docker.com/r/jupyter/notebook/, it throws the above error. I'm currently using the docker-stack images, i.e. https://github.com/jupyter/docker-stacks, and, indeed, they work fine.

**Comment by takluyver** [comment]
I'm not exactly sure how docker hub works, but it sounds like you're getting a released version of the notebook code with the master version of the Dockerfile. Since they're in the same repo, they ought to be used in sync. I see on #1468 a suggestion about removing the Dockerfile from this repo entirely in favour of docker-stacks, though.

**Comment by Baughn** [comment]
The instructions in the github README still causes this error. How am I practically speaking intended to install this?

**Comment by minrk** [comment]
@Baughn the docker bit in the README should have been removed; it's gone in #1603. The notebook can be installed with `pip install notebook`. A developer install can be made from master with:

    git clone https://github.com/jupyter/notebook
    cd notebook
    pip install -e .

If you want to build an image that includes a release of the notebook, start from one of the [docker-stacks]( https://github.com/jupyter/docker-stacks).
