### ISSUE TITLE
Error starting jupyter notebook

### ISSUE THREAD

**Issue by tritemio** [jupyter/notebook#154]
I installed  the jupyter notebook on OSX (anaconda 64, python 2.7) following [The Big Split" post](https://blog.jupyter.org/2015/04/15/the-big-split/):

```
git clone https://github.com/jupyter/notebook  
cd notebook  
pip install -r requirements.txt -e .  
```
 And when launching the notebook I get the following error:
```
$ jupyter notebook
[I 19:09:14.865 NotebookApp] Serving notebooks from local directory: /Users/anto/src/jupyter/notebook
[I 19:09:14.865 NotebookApp] 0 active kernels 
[I 19:09:14.865 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 19:09:14.865 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 19:09:15.338 NotebookApp] Could not open static file ''
[W 19:09:15.388 NotebookApp] 404 GET /static/style/style.min.css (::1) 4.15ms referer=http://localhost:8888/tree
[W 19:09:15.390 NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css (::1) 1.18ms referer=http://localhost:8888/tree
[W 19:09:15.392 NotebookApp] 404 GET /static/tree/js/main.min.js (::1) 1.13ms referer=http://localhost:8888/tree
[W 19:09:15.405 NotebookApp] 404 GET /static/components/es6-promise/promise.min.js (::1) 0.74ms referer=http://localhost:8888/tree
[W 19:09:15.407 NotebookApp] 404 GET /static/components/requirejs/require.js (::1) 1.65ms referer=http://localhost:8888/tree
[W 19:09:16.901 NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css (::1) 1.87ms referer=http://localhost:8888/tree
[W 19:09:16.907 NotebookApp] 404 GET /static/style/style.min.css (::1) 1.09ms referer=http://localhost:8888/tree
[W 19:09:16.910 NotebookApp] 404 GET /static/components/es6-promise/promise.min.js (::1) 1.18ms referer=http://localhost:8888/tree
[W 19:09:16.922 NotebookApp] 404 GET /static/components/requirejs/require.js (::1) 0.96ms referer=http://localhost:8888/tree
[W 19:09:16.923 NotebookApp] 404 GET /static/tree/js/main.min.js (::1) 0.91ms referer=http://localhost:8888/tree
[W 19:09:17.257 NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css (::1) 1.24ms referer=http://localhost:8888/tree
[W 19:09:17.259 NotebookApp] 404 GET /static/components/es6-promise/promise.min.js (::1) 1.12ms referer=http://localhost:8888/tree
[W 19:09:17.261 NotebookApp] 404 GET /static/components/requirejs/require.js (::1) 1.22ms referer=http://localhost:8888/tree
[W 19:09:17.264 NotebookApp] 404 GET /static/style/style.min.css (::1) 1.09ms referer=http://localhost:8888/tree
[W 19:09:17.277 NotebookApp] 404 GET /static/tree/js/main.min.js (::1) 1.91ms referer=http://localhost:8888/tree

```
A bare page is shown in the browser but with no style/images.

**Comment by Carreau** [comment]
Didi you get any error ? do you have gulp, npm, node installed ?

**Comment by tritemio** [comment]
No I only installed the python packages as mentioned in the post and the installation didn't give any error.

**Comment by tritemio** [comment]
Here it is a screenshot:

![screen shot 2015-06-13 at 11 46 55](https://cloud.githubusercontent.com/assets/4156237/8145573/0f25f2dc-11c2-11e5-9ab8-72e61d8e514a.png)

**Comment by tritemio** [comment]
Do I have to create a configuration dir manually?

**Comment by Carreau** [comment]
This is typical of you not having node installed. 
Install nodejs, check that npm is installed. The installation shoudl fail is node/npm is not installed. 
try to run manually in notebook folder (in order)
 - npm install 
 - bower install 
 - gulp js
 - gulp css

**Comment by tritemio** [comment]
How do I install those on OSX? Are this new dependencies?

I currently use run ipython notebook 3.1 from Anaconda.

**Comment by takluyver** [comment]
They're development dependencies - you need them if you want to run from git master. When we release the next version of the notebook, you'll be able to install it from PyPI without needing any of these. If you're not sure how to install them, I recommend you stick with IPython 3.1 for now. There are no major new features for 4.0 in any case.

**Comment by Carreau** [comment]
Agreed with @takluyver, if you are not sure what any of theses are and how to install them, you should probably stay off master for the time being. Though is you are adventurous to try:

- bower is a package manager for front end javascript you can install it with npm, 
- npm is a js package manager for node, it comes with node that you can install with brew. 
- [brew](http://brew.sh/) is a package manager for OS X

Closing the issue but feel free to continue asking questions if you like.
