### ISSUE TITLE
Cannot import matplotlib: "Python is not installed as a framework."

### ISSUE THREAD

**Issue by masnick** [jupyter/notebook#1540]
I have followed [these instructions](http://matplotlib.org/faq/virtualenv_faq.html) for getting `matplotlib` to work in a virtualenv.

The following works fine:

```
$ frameworkpython -m IPython
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib.pyplot as plt

In [2]:
```

But this does not, even though the notebook server was started with `frameworkpython -m jupyter notebook`:

<img width="759" alt="screen shot 2016-06-13 at 4 31 11 pm" src="https://cloud.githubusercontent.com/assets/110426/16025383/4482c198-3184-11e6-9d40-27b11366dbba.png">

This leads me to believe that Jupyter is doing something different than IPython, and thus that the issue is with Jupyter and not matplotlib.

This happens on OS X 10.11.5 with Python 2.7.11 installed from Homebrew, system Python 2.7.10 used by the `frameworkpython` hack, and Jupyter 4.1.0.

**Comment by Carreau** [comment]
Do an `import sys` , `sys.executable`. 

The interpreter that run the notebook is **likely** different than the one that run the **kernel**. 

`frameworkpython -m jupyter notebook` is roughly useless as you run the jupyter command with `frameworkpython`, it shells out, so the interpreter of notebook can perfectly be not the framework one (and heck the notebook could be written in go you wouldn't notice) , then it's start the kernel which could again be in another language or interpreter.

You **likely** want to do : 
```
$ frameworkpython -m ipykernel install --name 'frameworkpython'
```
 to get a new available frameworkpython kernel, or just drop the `--name 'frameworkpython'` to replace the default python kernel. Using `%matplotlib inline`  might also help as then it does not try to use the osx backend.

**Comment by theChumpus** [comment]
Thank you @Carreau - this worked for me.

**Comment by Carreau** [comment]
> Thank you @Carreau - this worked for me.

Great !
