### ISSUE TITLE
dashboard 'running' filter is not showing running in other folders

### ISSUE THREAD

**Issue by michaelaye** [jupyter/notebook#1541]
Not sure this is a bug or a feature request, but I just noticed that when I use the dashboard to navigate around in a folder structure, and I have a notebook running in a subfolder, and go one folder up, then click on the "Running" filter to show me only currently running notebooks, then it wouldn't show me the notebook running in the subfolder.
I understand that this is strictly speaking not a filter on the current folder display (so I guess this is a feature request), but I think it's nevertheless quite useful to have a possibility to show all currently running notebooks with the current server?

Version: jupyter 4.10, notebook 4.2.1, on OSX, conda python 3.5

**Comment by takluyver** [comment]
Are you sure about the situation? Could the kernel have been stopped even if the notebook was still open? Did you click the little in-page refresh button on the running tab? It certainly should be showing all running kernels that the server knows about, and that's what I see on master.

**Comment by michaelaye** [comment]
Yes, just verified. Also refreshing did not help.

**Comment by takluyver** [comment]
Weird. I've just tested on 4.2.1 and it's working as I'd expect.

**Comment by Carreau** [comment]
Running **filter** or running **tab** ?

TAB
![screen shot 2016-06-14 at 11 45 17](https://cloud.githubusercontent.com/assets/335567/16055279/7dd220c8-3225-11e6-918b-d5ecf97b17c9.png)

Filter 

![screen shot 2016-06-14 at 11 45 11](https://cloud.githubusercontent.com/assets/335567/16055282/7f534530-3225-11e6-89d6-40dde88ea20d.png)

**Comment by michaelaye** [comment]
filter.

**Comment by takluyver** [comment]
No worries. Thanks Matthias for working out the disconnect here.
