### ISSUE TITLE
Use "requirejs" instead of "require"

### ISSUE THREAD

**Issue by mangecoeur** [jupyter/notebook#155]
Wishlist item: some time ago I worked on a desktop wrapper for iPython - https://github.com/mangecoeur/ipython-desktop . One problem I ran into was that I embed the page into a nodeJs based desktop container (originally NodeWebkit, since shifted to github's Atom runtime). Node uses "require" to load modules, but this require is totally different from the AMD "requirejs" system. When you try to blend the browser and server code you get a name conflict which in theory could be fixed with some monkey patching, but in practice it's so flaky I never got it to work properly.

However, requirejs allows you to use `requirejs` function instead of `require`. From a quick overview of the code, it seems the root "require" function is only used in a few places - changing these might make the notebook more friendly to interact with from nodejs programs.

**Comment by Carreau** [comment]
We could I don't see any hard in that. Though we will still have to expose require in the namespace for compatibility with user custom.js.

How do we switch from require to requirejs ?

**Comment by mangecoeur** [comment]
requirejs already supports it - you simply write "requirejs" where you currently use "require" (you can check the requirejs 2.0 api guide, 3rd code example -  http://requirejs.org/docs/api.html)

**Comment by JamiesHQ** [comment]
@gnestor : do you know the plan for implementing this change?

**Comment by gnestor** [comment]
@mangecoeur @Carreau I believe that this change would break any extensions that use `require` to refer to RequireJS?

**Comment by takluyver** [comment]
I don't think that the change proposed would break extensions - it's just to use `requirejs` in our code, not to remove `require`.

Extensions relying on `require` would still break in @mangecoeur's node embedded environment, but that's a separate issue.

However, I guess that anyone who wants a desktop notebook interface built with Node is now looking at nteract rather than wrapping our notebook code, so it might be moot.

**Comment by Carreau** [comment]
+1 to @takluyver we can still do it that's should be a mater of search and replace for a new contributor.

**Comment by jzf2101** [comment]
@fenwickipedia

**Comment by rgbkrk** [comment]
I wouldn’t mind if we expose requirejs as requirejs and convince extension authors to use that. It would allow me to work around require vs requirejs shimming.

**Comment by mpacer** [comment]
Could a script to automate such a change ala futurize for py2/py3 (but more
complete) be distributed to reduce the load on extension maintainers?

That way when they discover this breaking, we can just point them to the
tool and there won't be much negative impact on the community… then it
means people will have to upgrade their extensions when they upgrade the
notebook. That's less onerous than requiring a complete tear down and
reinstallation.

I just don't know webpack enough to know if this is possible.

**Comment by fenwickipedia** [comment]
@jzf2101 I'm taking a look. @here I've got 41 hits for "require(" in the project. Does it just need a find and replace with "requirejs(" for all those occurrences?

**Comment by takluyver** [comment]
Yup, the find and replace is probably about it. I'm surprised it's  only 41, but I guess we use `define()` in more cases. I don't think the `define()` calls need to be changed - someone correct me if I'm wrong.

**Comment by blink1073** [comment]
Correct, node does not have a native `define()` function.

```javascript
$ node
> define
ReferenceError: define is not defined
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
```

**Comment by gnestor** [comment]
I figured that I should just submit a PR to start this process: https://github.com/jupyter/notebook/pull/3097

I think that covers all uses of `require` in this repo. As for providing a _simple_ way for extensions authors/maintainers to do the same, here's a sampling of `require` usage across many extensions: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/search?utf8=%E2%9C%93&q=require&type=

The patterns looks like:

```js
define([ 'require' ], function(require) {
  ...
})
```

In some (including the cookiecutters), there is also:

```js
/**
 * Configure requirejs.
 */
if (window.require) {
  window.require.config({
    map: {
      '*': {
        'jupyterlab_json': 'nbextensions/jupyterlab_json/index'
      }
    }
  });
}
```

So replacing `require` with `requirejs` in those contexts should cover most cases. If we want to provide a comprehensive solution, we can use [jscodeshift](https://github.com/facebook/jscodeshift) which uses and AST-based approach. Here's an example of a codemod that replaces `require` statements with `import` statements: https://github.com/cpojer/js-codemod/blob/master/transforms/rm-requires.js

**Comment by gnestor** [comment]
And here's a PR on ipython-contrib/jupyter_contrib_nbextensions: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/1165

**Comment by sargense** [comment]
Switching require to requirejs also does not work just require code blocks have stopped working.

**Comment by gnestor** [comment]
@sargense Can you provide more context? Ideally provide an example notebook via GitHub gist, Dropbox, Google Drive, etc. I am running master and `require` is still available globally.

**Comment by sargense** [comment]
I experienced what seemed like this bug when attempting to run this code.
https://gist.github.com/disarticulate/d06069ff3e71cf828e5329beab8cb084

I ran something very similar for D3 which I think worked fine.  I ended up approaching and solving the problem differently than via require JS.
