### ISSUE TITLE
Add a disable extensions option to easily run the notebook without any extensions

### ISSUE THREAD

**Issue by minrk** [jupyter/notebook#1550]
Extensions are frequently the cause of problems in the notebook. The first step to checking this is re-launching with extensions disabled, but this is pretty hard to do, as they can come from so many places.

We should add a flag that does:
- ignore custom.js
- skip loading serverextensions
- skip loading nbextensions

for more easily checking whether an extension is the culprit, or if it's a bug in the notebook itself.

**Comment by takluyver** [comment]
I think jupyter/jupyter_core#96 provides for this. Please reopen if there's something more to add.
