### ISSUE TITLE
GitHub flavored Markdown text not being processed correctly

### ISSUE THREAD

**Issue by eskirk** [jupyter/notebook#1556]
<img width="1222" alt="screen shot 2016-06-17 at 3 30 49 pm" src="https://cloud.githubusercontent.com/assets/7052378/16167029/73152996-34a5-11e6-8189-00a35749e4dc.png">

While comparing formatting between lab and notebook I realized that the syntax highlighting/processing of GitHub flavored Markdown text was either (in the case of the lab) not being colored correctly or (in the case of the notebook) was being completely ignored/not processed at all. (down in the bottom left/right)

Moving further up the image, there is a discrepancy between table styles.

Furthermore, towards the top of the image you can see a difference in the rendered HTML of the lab and the notebook.

**Comment by Carreau** [comment]
Hi ! Thanks for the report. 

Header **have to** have a space after hashes to be rendered. Can you share the markdown that does not render for you so that I can test ?

**Comment by eskirk** [comment]
The only reason I marked `##issues` is for myself so I didn't forget about it :octocat: 

Here's the file in question, it should be down towards the bottom. 
[Typography.ipynb.zip](https://github.com/jupyter/notebook/files/326234/Typography.ipynb.zip)

**Comment by Carreau** [comment]
HUm.. in the notebook, I get the last markdown cell rendering correctly.

Which version of notebook? 

can you open the Developer console and check for JS error messages ?

**Comment by eskirk** [comment]
When I try to process the last markdown cell (the cell in the picture) I get this error message in the console: `Uncaught TypeError: Cannot read property 'replace' of undefined  mathjaxutils.js:198 `

I seem

**Comment by Carreau** [comment]
Ok thanks ! Leaving open for the issues in JupyterLab !

**Comment by gnestor** [comment]
I just tested this notebook in notebook and lab and markdown rendering looks consistent, however maths are not being full renderered in lab:

![image](https://user-images.githubusercontent.com/512354/33742335-c16fd276-db5c-11e7-8153-00a800ec35a8.png)

![image](https://user-images.githubusercontent.com/512354/33742373-eb614344-db5c-11e7-92ca-fbf644af77fa.png)

Ping @ellisonbg @blink1073

**Comment by blink1073** [comment]
Hmm, it is rendering fine for me with Notebook 5.3.0dev and JupyterLab 0.30.1:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/2096628/33795640-f65f5480-dcaa-11e7-8347-04c141d3cad9.png">

I set a debug point in `notebookapp.py` in `NotebookApp.start()`:

```python
(Pdb) self.mathjax_url
'static/components/MathJax/MathJax.js'
(Pdb) self.mathjax_config
'TeX-AMS-MML_HTMLorMML-full,Safe'
```

**Comment by gnestor** [comment]
If it's rendering correctly for @blink1073 then it's probably an environment issue on my end. Closing this as the original issue is resolved.
