### ISSUE TITLE
bash scripts run with --bg and --proc give wrong process id, can't kill process

### ISSUE THREAD

**Issue by j2kun** [jupyter/notebook#1559]
**Reproduction steps:**

Open a new Jupyter notebook, and run it with the following three cells

```
%%writefile myfile.py

while True:
    pass
```

```
%%bash --bg --proc bg_proc
python myfile.py
```

```
print(bg_proc.pid)
bg_proc.kill()
```

**Expected:**

Process id matches actual process id, and process is killed

**Actual:**

Process id as reported by Jupyter appears to always be 1 greater than the actual process id, and the process is not killed.

The final cell prints

```
55875
```

Whereas the output of `ps aux | grep python` includes the line:

```
jeremy          55876  91.9  0.1  2417988   5984   ??  R     6:36PM   0:11.49 python myfile.py
```

**Comments:**

I have tried this in a few different notebooks in a few different ways, and it's always 1 more than the actual process id, and I've never been able to successfully kill a process from within the notebook.

**Comment by takluyver** [comment]
The PID it stores and acts on is for bash itself. You're running Python from bash, so that's a subprocess.

```
ipython
 └ bash
    └ python (in this example)
```

**Comment by j2kun** [comment]
@takluyver Is there a way to get the child process id into a python or bash variable to be used later in the notebook? The use case I'm envisioning is: cell 1 starts a simple local webserver, cell 2 invokes that webserver, cell 3 kills the webserver.

**Comment by takluyver** [comment]
If you just want to run something, use Python's native `subprocess` module, rather than a magic i.e.

```python
proc = subprocess.Popen(['python', 'myfile.py'])
```

(Of course, you can wrap this in a function for users to call if you like).

If you need to do it through bash for some reason, [this SO answer](http://stackoverflow.com/a/1911387/434217) describes how to save the PID of a background job.

**Comment by j2kun** [comment]
I need to do it through bash, because the the notebook is converted to an online tutorial that focuses on bash, while the contents are run during integration tests.

The SO answer you linked to does not work, because Jupyter notebook silently ignores the `&` to spawn background processes from within a bash cell. For example, the following cell hangs indefinitely:

```
%%bash --out bg_pid
python myfile.py&
echo $!
```

Moreover, putting the same code into `%%bash --bg --out bg_pid` also hangs (in the background), so that `bg_pid` is an `_io.BufferedReader`, waiting for `python myfile` to finish before the `echo` starts.

I don't mean to pester, but it does seem like a bug in the notebook (or the bash kernel?) that if you run a python script from a `%%bash --bg` cell, that child process is lost forever. I'd be happy to submit a PR that adds `preexec_fn=os.setsid` as a kwarg to the bash magic, if you'd point me to where these kwargs are set.

**Comment by j2kun** [comment]
Alternatively, I would be happy with a way to kill all child processes spawned by the jupyter notebook as a whole. But even when the notebook exits, spawned child processes persist.

**Comment by j2kun** [comment]
To be sure, I have a fine hacky bash workaround, using the following as a cleanup script:

```
ps aux | grep 'myfile.py' | grep -v 'grep' | awk '{print $2}' | xargs kill
```

I am just looking for something more stable.

**Comment by takluyver** [comment]
I'll try to look into the issue with `&` tomorrow. This is in IPython, not bash_kernel - if you were using bash_kernel there would be no need for or option to use the `%%bash` cell magic.

**Comment by minrk** [comment]
If your code is as simple as this, you could also use `exec` to replace the bash process with the Python process:

    exec python myfile.py

You could also use the `%%python` magic to run a Python script instead of `%%bash`:

    %%python
    execfile('myscript.py')

But there may be a reason that you used `%%bash` that is not evident in the minimal example.

**Comment by Carreau** [comment]
That's  will need to be migrated to ipython/ipython as this is not directly a notebook issue.
