### ISSUE TITLE
How do I tell many jupyter notebooks where to look for global project resources?

### ISSUE THREAD

**Issue by j2kun** [jupyter/notebook#1566]
I have a project with, say, a hundred tutorials that is organized roughly like this:

```
    ├── a-dir
    │   ├── sub-dir
    │   │   └── sub-sub-dir
    │   │       ├── tutorial1
    │   │       │   ├── tutorial1.ipynb
    │   │       │   └── assets
    │   │       │       └── ...
    │   │       ├── tutorial2
    │   │       │   ├── tutorial2.ipynb
    │   │       │   └── assets
    │   │       │       └── ...
                .
                .
                .
    └── tests
        ├── test_tutorials.py
        ├── tutorials_utils.py
        ├── custom_extension.py
        └── custom_preprocessor.py
```

I want to run a test suite that iterates through all the tutorials, runs them, converts them to markdown (which will then be displayed on a website), and fails if any notebook raises an error while running.

My tutorials directories each have a subdirectory of assets that are used in the notebooks and the resulting markdown files, so it seems natural to put those files there. However, I also need the tutorial notebooks to be able to load a custom extension I wrote in `custom_extension.py`, and to have access to some helper functions I wrote in  `tutorials_utils.py`.

It seems that all of Jupyter's imports are relative to the directory where the notebook is saved. How can I additionally tell Jupyter to look in the `tests` directory?

I want to do this in two ways:

 1. During automated integration testing, using the Python API for nbconvert or something similar (what exactly is the best way to "just" run a jupyter notebook from the command line?).
 2. During development, i.e., from within the notebook browser GUI. I'm currently loading notebooks with, e.g., `jupyter notebook a-dir/sub-dir/sub-sub-dir/tutorial1/tutorial1.ipynb`. What options would I need to add to this to point it to `tests/`? I tried various values for `--NotebookApp.nbserver_extensions=<Dict>` but I can't figure out the proper syntax for passing a Dict to the CLI

I would prefer not to put a `sys.path.append` line in every single jupyter notebook, since there are so many, and the directory structure may change in the future, requiring hundreds of updates.

**Comment by takluyver** [comment]
You may be able to have your test runner set the PYTHONPATH environment variable.

**Comment by j2kun** [comment]
That seems to work from within my test runner. I also was able to get a command line invocation via

```
PYTHONPATH=../../../tests jupyter notebook my_notebook.ipynb
```

Is PYTHONPATH still considered unstable (as opposed to PATH? Which does python use again?)

**Comment by takluyver** [comment]
> Is PYTHONPATH still considered unstable (as opposed to PATH? Which does python use again?)

PATH is used to find commands you run at the command line, like `ls` or `ipython`. PYTHONPATH is used to find Python modules when you `import foo`.

PYTHONPATH is stable and has been around for a long time, but it's not a very elegant way to solve problems, and can cause problems if it's around when you're not expecting it.

**Comment by j2kun** [comment]
This works well. Thanks.
