### ISSUE TITLE
vertical centering of output after calling IPython.display.display(Image())

### ISSUE THREAD

**Issue by caseyjlaw** [jupyter/notebook#1567]
I am interested in iteratively displaying images from a large list of images. However, the way the notebook manages the centering of the output (i.e., the browser scrollbar) makes this difficult. Any input would be appreciated.

I am using the display function to show an image from a url. I use ipywidgets to interact the single image and then call  a function to display a new one. The problem is that calling display causes the browser to place the cell output at the bottom of the browser window. Ideally it would center the new image in the browser. That is, when running this:

    from IPython.display import display, Image
    display(Image(url=url, width=width))

... the image is shown low in the browser. This makes it awkward to iterate through a large number of images, since I need to manually center the image with my mouse each time.

In my testing, I can see that this happens when running the display(Image()) function alone (without ipywidgets), so it seems to be an issue with display or with how the notebook deals with scrolling. Note that the output of the cell is not "scrolled"; I am referring to how the notebook scrolls the browser to center the cell vertically.

It would be nice to either have control this centering of the output in notebook or IPython.display. But it is not clear to me yet (1) where the issue arises and (2) whether it is intended behavior.

**Comment by Carreau** [comment]
Unfortunately this is mostly a problem with how browser handle scrolling, and there is close to nothing we can do (except maybe with as much resource as Google create our own scrolling engine or browser). 

Ask on the `ipython/ipywidgets` repo, there might be a way to display widgets in a floating div explicitelty,  so you won't have this issue.

**Comment by caseyjlaw** [comment]
Ok, thanks. I'll look around.
