### ISSUE TITLE
Formatting Cell to Markdown Incredibly Slow

### ISSUE THREAD

**Issue by mansweet** [jupyter/notebook#1571]
When converting a cell in the notebook to 'markdown' from code, it is very slow and blocks any additional actions to be executed on the notebook.

**Comment by Carreau** [comment]
That's seem weird. 
Which browser ? Any particular content in the markdown cell ? A lot of math expressions ?

**Comment by mansweet** [comment]
On a Chrome Browser using El Capitan.

This is just rendering a cell to be markdown without any content inside. 
> On Jun 27, 2016, at 3:46 PM, Matthias Bussonnier <notifications@github.com> wrote:
> 
> That's seem weird. 
> Which browser ? Any particular content in the markdown cell ? A lot of math expressions ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/jupyter/notebook/issues/1571#issuecomment-228898633>, or mute the thread <https://github.com/notifications/unsubscribe/AHZJpsn5v61C7ziXavo7_LBIKOol8TFKks5qQFLDgaJpZM4I_Y9C>.
> 

<><><><><><><><><><><><><><>
Michael Mansour
Data Scientist & Graduate Student @ Galvanize
IBM Blockchain Labs
(650) 773-7974
Twitter: @sourmansweet

**Comment by takluyver** [comment]
Any browser extensions?

**Comment by mansweet** [comment]
Enabled:
google docs/sheets/hangouts/slides
okta 
rapportive 
uBlock Origin (ad blocking, but turned off for notebooks)


> On Jun 28, 2016, at 3:39 AM, Thomas Kluyver <notifications@github.com> wrote:
> 
> Any browser extensions?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/jupyter/notebook/issues/1571#issuecomment-229013859>, or mute the thread <https://github.com/notifications/unsubscribe/AHZJpqji-No-z2X11A8HfddGyWe7AkJKks5qQPnXgaJpZM4I_Y9C>.
> 

<><><><><><><><><><><><><><>
Michael Mansour
Data Scientist & Graduate Student @ Galvanize
IBM Blockchain Labs
(650) 773-7974
Twitter: @sourmansweet

**Comment by takluyver** [comment]
Can you try with another browser and/or in 'safe mode' with extensions disabled?

**Comment by jtpio** [comment]
Closing as this seems to be fixed in the latest Notebook 7 release:

https://github.com/jupyter/notebook/assets/591645/189cae55-649a-4b30-b99b-459be96a5a78

Don't hesitate to open a new issue if needed, thanks!
