### ISSUE TITLE
Behaviour for unimplemented messages in messaging spec?

### ISSUE THREAD

**Issue by gibiansky** [jupyter/notebook#1574]
I am currently working on cleaning up how IHaskell handles the communication with Jupyter to be cleaner and more principled.

What is the intended behaviour expected from a kernel when it does not support a given message? For example, the messaging spec has a [history request](https://jupyter-client.readthedocs.io/en/latest/messaging.html#history) that IHaskell currently does not implement. What is the _right_ thing for IHaskell to do when it requests a `history_request`?

In these cases, is the right thing to do reply with an empty list? Or what? 

This aspect of the messaging protocol could be documented explicitly in the spec, which would be helpful for future kernel authors.

**Comment by takluyver** [comment]
In most cases, kernels that don't implement something simply don't respond to the message at all, but I'm not sure that we've ever consciously decided that's how it should work. If there's an obvious empty answer, as for history or completions, that will probably be OK too.

**Comment by gibiansky** [comment]
The more precise and unambiguous the messaging spec is, the easier it will be for different clients and kernels to interoperate. I would suggest addressing this in a future revision of the spec -- it's not a major point, but these small things add up, and as kernels and clients proliferate having the spec be very specific in all edge cases will really be a boon to kernel and client authors :)

I don't have a strong opinion about how it's resolved – just as long as there is some official word on what to expect from kernels on this matter.

**Comment by takluyver** [comment]
See jupyter/jupyter_client#236
