### ISSUE TITLE
Clarify inspect_reply fields in messaging spec

### ISSUE THREAD

**Issue by gibiansky** [jupyter/notebook#1576]
In the `inspect_request` and `inspect_reply` [documentation](https://jupyter-client.readthedocs.io/en/latest/messaging.html#introspection) there are 3 fields: `found`, `data`, `metadata`.

It is not 100% clear whether, on an error, it is required for the `found`, `data`, and `metadata` keys to be absent, or whether it is expected that they exist and are `false`, empty, and empty, respectively. 

I would suggest clarifying that those fields should exist *only* if `status` is `ok` (or at least clarify that those fields are only required if `status` is `ok`). (Or, if there is a reason that those fields should exist when the status is `err`, clarify that those fields *must* exist in all cases, as that would be somewhat unintuitive)

(As with the [other](https://github.com/jupyter/notebook/issues/1575) [issues](https://github.com/jupyter/notebook/issues/1574) I filed recently, this isn't necessarily anything serious or urgent, but having a strict spec will be really helpful for developers outside the core notebook and jupyter project in the long term! :) )

**Comment by minrk** [comment]
All `status: 'error'` replies should have the same fields, and any fields present when `status: 'ok'` may be omitted. I'll have to check if IPython actually does this for execute_reply, but it should be the case for all the other requests.

**Comment by gibiansky** [comment]
Does this mean that `status: 'abort'` is also acceptable for inspect and complete?

**Comment by minrk** [comment]
@gibiansky yes
