### ISSUE TITLE
Import Errors on Jupyter notebook ; while spyder (from Anaconda) Works Fine on Mac OS

### ISSUE THREAD

**Issue by QLQLQL** [jupyter/notebook#1580]
Hi everyone!

I'm new to python, and learning Tensorflow recently. I've successfully installed Anaconda on my Mac OS (Python version: 2.7.11). Then I installed Tensorflow by following the official guide from tensorflow.org (by installation method: "Anaconda Installation" ). 

Then I open the spyder (from anaconda), and run some lines of codes, everything goes fine. Tensorflow, as well as other modules can be successfully imported. While I open the Jupyter notebook (also from anaconda), tensorflow can be imported too, but some other modules, like matplotlib, scipy... cannot be imported, I keep receiving message: "error: no module name XXX"

I searched on web and found the same problem has been encountered previously by others: #https://github.com/jupyter/notebook/issues/1524
@carreau @takluyver @thirumalaipm have posted valuable information but I still cannot solve the problem.

Then I checked the system and found:
**In spyder, sys.executable is "/Users/abc/anaconda/bin/python";
In Jupyter, sys.executable is "/Users/abc/anaconda/envs/tensorflow/bin/python"** (no matter whether I activate tensorflow in terminal)

It seems that the spyder and Jupyter run two different built-in Python (version of both are 2.7.11), one from anaconda, and the other from tensorflow. Now I want Jupyter to run with the anaconda python. Could anyone please instruct me how to do this?

Any hint will be appreciated. Thank you very much!

**Comment by takluyver** [comment]
They're both running in Anaconda Python, but in different environments. You may have installed an IPython kernelspec with that environment active, or you may have launched Jupyter inside that environment.

Either way, you should be able to make it use the root environment (the same one Spyder is using) by [installing the kernelspec](http://ipython.readthedocs.io/en/stable/install/kernel_install.html) without activating any environment. The command for that is:

```
python -m ipykernel install --user
```

**Comment by Carreau** [comment]
Also no need to post twice, we saw [the comment on the other thread](https://github.com/jupyter/notebook/issues/1524#issuecomment-229572759) it can just take timefor us to respond.

**Comment by QLQLQL** [comment]
Problem has been solved! Thank you very much!

**Comment by Carreau** [comment]
> Problems solved! Thank you very much!

Thanks, closing.

**Comment by mesutyang97** [comment]
> They're both running in Anaconda Python, but in different environments. You may have installed an IPython kernelspec with that environment active, or you may have launched Jupyter inside that environment.
> 
> Either way, you should be able to make it use the root environment (the same one Spyder is using) by [installing the kernelspec](http://ipython.readthedocs.io/en/stable/install/kernel_install.html) without activating any environment. The command for that is:
> 
> ```
> python -m ipykernel install --user
> ```


This actually broke down my entire Jupyter Notebook... Now I find it very difficult to undo the damange
