### ISSUE TITLE
Where is documentation for kernelspec files?

### ISSUE THREAD

**Issue by gibiansky** [jupyter/notebook#1581]
I'm looking to find the complete documentation on which files can be included in a kernelspec. I am aware of `kernel.json` (of course), `kernel.js`, and `logo-64x64.png`. These are the only ones IHaskell uses for the time being.

It looks like the primary point of documentation for that should be [here](http://jupyter-client.readthedocs.io/en/latest/kernels.html#kernelspecs), but it mentions only `kernel.json`. 

Is this simply a case of some missing docs or am I missing the place? (Googling and searching across a random selection of Jupyter / IPython docs has not been helpful here.)

**Comment by willingc** [comment]
@gibiansky I believe that you have found the most user facing documentation on kernelspec (https://jupyter-client.readthedocs.io/en/latest/kernels.html). As a developer of IHaskell, you are likely on the leading edge here (thanks for the excellent blog post that the docs refer to).

@takluyver @minrk If you can field this question for @gibiansky, I'll add the response to the documentation.

Thanks!

**Comment by takluyver** [comment]
Partly missing docs, partly that it's open ended to allow for extra files in the future.

I think the three files you mention are the only ones we use at present. As the logo filename hints, we've anticipated the need for other logo sizes. I could also envisage including e.g. a Python module to declare an extra pygments style.

**Comment by gibiansky** [comment]
Great, good to know!

Would be great to mention the two other files on that page then and say that no other files are currently used and that this may change in the future.

Thanks!

**Comment by willingc** [comment]
@gibiansky @takluyver PR opened in jupyter/jupyter_client
