### ISSUE TITLE
Change wording on stdin socket messages

### ISSUE THREAD

**Issue by gibiansky** [jupyter/notebook#1585]
Continuing my minor trend of documentation nits to fix...

The section on [stdin messages](https://jupyter-client.readthedocs.io/en/latest/messaging.html#messages-on-the-stdin-router-dealer-sockets) is incredibly Python-specific in its language, making reference to `sys.stdin` and `raw_input`. Since the messaging spec is now almost fully language-agnostic, it would be helpful to make the primary language used here also language agnostic (and perhaps either remove mention of Python-specific features or relegate them to a subnote.)

**Comment by takluyver** [comment]
BTW, the messaging spec docs are in the jupyter_client repo - not a big deal, but it's best to file issues there.

**Comment by takluyver** [comment]
https://github.com/jupyter/jupyter_client

**Comment by takluyver** [comment]
See jupyter/jupyter_client#165

**Comment by gibiansky** [comment]
Thank you! I looked around the repos to try to figure out where to best file these but didn't find anything concrete -- will keep in mind for future (sorry!).
