### ISSUE TITLE
jupyter notebook dies when loading ROOT, console is fine

### ISSUE THREAD

**Issue by iljabek** [jupyter/notebook#1590]
when executing the following code
```
import sys
sys.path.append('/home/data/usr/root/lib/root')
import ROOT
```
python 2 notebook kerned dies after a second or two with:
"Kernel Restarting\n The kernel appears to have died. It will restart automatically."

if executing the same in console all is fine:
```
$ jupyter console
Jupyter Console 4.1.1
In [1]: import sys
In [2]: sys.path.append('/home/data/usr/root/lib/root')
In [3]: import ROOT
In [4]: ROOT
Out[4]: <module 'ROOT' from '/home/data/usr/root/lib/root/ROOT.pyc'>

```

how do I debug this issue?

Edit: 
Root version 5.34/34

**Comment by minrk** [comment]
There might be some information logged to the terminal where the notebook server is running that could point the way. If it's dying on import, it is likely a C-level error, which doesn't generally propagate all the way to the notebook.

I'm not sure what would be the difference between the notebook and `jupyter console`, but you might compare `sys.path` and `os.environ` in the two cases, to see what might be different.

**Comment by iljabek** [comment]
I started the notebook server in Ubuntu via `<Alt-F2>`, instead of starting it in a terminal. As a result some variables were not taken over from .bashrc. After killing the server and restarting from terminal `import ROOT` reliably worked. 

after fiddling some more with terminal I could reproduce the crash being caused by 
absence of:
`export LD_LIBRARY_PATH=$ROOTSYS/lib/root:$LD_LIBRARY_PATH`
so the issue is not with Jupyter.

Thank you for the hint with the terminal. This should be the preferred way to start servers.
I'd consider issue closed.

**Comment by takluyver** [comment]
Thanks. Yes, it's unfortunate that the common ways to set environment variables only affect things started from a terminal.
