### ISSUE TITLE
Some codemirror shortcuts should be listed in the help dialog

### ISSUE THREAD

**Issue by jdfreder** [jupyter/notebook#1593]
Hi all,

Someone emailed me recently asking me to open an issue that said:

```
In Notebook the Help, Keyboard shortcuts window should have instructions for toggling comments
command+/
```

I think the shortcut is missing because it's one built into codemirror.  I agree with him that it makes sense to list this keyboard shortcut in the help dialog.  I also think it makes sense, from a user point, to list some of the other CodeMirror shortcuts too, if they are not already listed.

**Comment by minrk** [comment]
Good call. We should see if the CodeMirror list is discoverable somewhere.

**Comment by flying-sheep** [comment]
that would be really cool as i plan to add some in jupyter/help/issues/71

**Comment by jasongrout** [comment]
The relevant file for the help dialog is here: https://github.com/jupyter/notebook/blob/f75e591bd68d4a6d201a0883a5c3a60694055313/notebook/static/notebook/js/quickhelp.js#L175

**Comment by GadgetSteve** [comment]
Looking at the code in https://github.com/codemirror/CodeMirror/tree/master/keymap it looks like that specific shortcut is only defined in sublime mode. Presumably Jupyter notebooks are in sublime mode but is that the default or all of the time?

_There is not much worse than the help telling you about a really useful shortcut and then it not working._

Looking at https://codemirror.net/doc/manual.html#commands with keyboard shotcuts there are a lot of commands _that are mostly standard platform commands_ that would probably be overkill for a **short** help.

**Comment by gnestor** [comment]
I added the few Codemirror shortcuts that were missing (based on https://github.com/codemirror/CodeMirror/tree/master/keymap) from the Keyboard Shortcuts dialog. See https://github.com/jupyter/notebook/pull/2696 for an example of how to add new keymaps...

**Comment by flying-sheep** [comment]
hi, is there a way to add new shortcuts dynamically (i.e. from kernel.js)?

**Comment by takluyver** [comment]
Yes, I think it should be something like this:

```javascript
Jupyter.keyboard_manager.command_shortcuts.add_shortcut('w,w', 'jupyter-notebook:show-command-palette')
```

First argument is the shortcut, second is an action name. It looks like you can also give it a function in place of the command name.

**Comment by flying-sheep** [comment]
OK. currently, IRkernel [uses the codemirror keymap](https://github.com/IRkernel/IRkernel/blob/aa5c133ad3220713ab3ab1709ceb4a7faafba52d/inst/kernelspec/kernel.js#L20-L25).

but it might be actually better to do it this way and just to retrieve the currently selected cell’s CodeMirror instance, like that:

```js
const extra_map = {
	['Alt--'](cm) {
		code_mirror.replaceSelection(' <- ')
	},
	[`Shift-${cmd_key}-M`](cm) {
		cm.replaceSelection(' %>% ')
	},
	F1(cm, cell) {
		const {anchor, head} = cm.findWordAt(cm.getCursor())
		const word = cm.getRange(anchor, head)
		
		const callbacks = cell.get_callbacks()
		const options = {silent: false, store_history: false, stop_on_error: true}
		cell.last_msg_id = cell.notebook.kernel.execute(`help(${word})`, callbacks, options) 
	},
}

const add_edit_shortcut = (notebook, shortcut, callback) =>
	Jupyter.keyboard_manager.command_shortcuts.add_shortcut(shortcut, () => {
		if (notebook.mode !== 'edit') return
		const cell = notebook.get_selected_cell() 
		callback(cell.code_mirror, cell)
	})

define(['base/js/namespace'], ({notebook}) =>
	Object.keys(extra_map).forEach(shortcut =>
		add_edit_shortcut(notebook, shortcut, extra_map[shortcut])))
```

**Comment by flying-sheep** [comment]
questions:

1. will the `add_shortcut` callback receive any arguments?
2. is the `notebook.mode !== 'edit'` check necessary, or will the callbacks in `keyboard_manager.edit_shortcuts` only be called when in edit mode anyway?

**Comment by takluyver** [comment]
1. Yes, two parameters called `env` and `event`. Details of either are not obvious - I'm just finding out by reading the code. :-(
2. `edit_shortcuts` should only be called in edit mode, so you don't need to check that inside the handler. `command_shortcuts` are called in command mode.
3. There are no comprehensive docs for this, unfortunately. We never really declared the Javascript API stable, though it kind of is now. These pages might provide some relevant information:
  * http://jupyter-notebook.readthedocs.io/en/stable/extending/frontend_extensions.html#modifying-key-bindings
  * http://jupyter-notebook.readthedocs.io/en/stable/extending/keymaps.html

**Comment by flying-sheep** [comment]
thank you!

i’m sorry but i think it was a mistake that you didn’t write API docs from the very start even if it wasn’t to become stable anytime soon. kernel.js and other (documented) extension mechanisms rely on the JS API, but without a friendly environment (docs & a discussion platform), most potential plugin developers were probably scared off.

**Comment by takluyver** [comment]
Yeah, in hindsight it was probably a mistake. Part of the aim was to convey that it wasn't stable, but you need plugin developers to work out what the API should be.

I believe that part of the plan for Jupyterlab is a reliable JS API, but I don't know what it is or where to point you.
