### ISSUE TITLE
ambiguous/contradictory instructions under CONTRIBUTING.rst

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/notebook#1594]
Under 

> #Setting up a development environment

it says: "For general installation instructions have a look at the [Project Jupyter Installation Guide](https://jupyter.readthedocs.io/en/latest/install.html)"

but later it also says:

> #Installing the Jupyter Notebook

> Once you have installed the dependencies mentioned above, use the following steps:

    pip install setuptools pip --upgrade --user
    git clone https://github.com/jupyter/notebook
    cd notebook
    pip install -e . --user

Should the first sentence be removed? It would seem that "general installation" instructions might not be appropriate. If someone wants to develop on this project, they will need an editable install, if they first followed the instructions to leave the `CONTRIBUTING.rst` doc, they would spend time doing irrelevant and possibly counter-productive things to their install. 

What might be better is a guide on how to create two separate environments (e.g., `stable` and `dev`) for those who want to also have a version of Jupyter that will simply *work* (which is why I presume the general installation instructions were included) as well as a version that links to master on which they can base their development.

**Comment by willingc** [comment]
Sounds reasonable. Let's remove the first line for "general installation".
