### ISSUE TITLE
Add column rulers to codemirror input cells

### ISSUE THREAD

**Issue by robcross** [jupyter/notebook#160]
There is a codemirror addon called "rulers.js" that allows you to add vertical lines into the editor. This would be useful to gauge how far you are on an 80/100/120 column limit. In fact it looks like the addon is already packaged into IPython.

```
site-packages » find ./ -name rulers.js                ~/.venv/lib/python2.7/site-packages  
./IPython/html/static/components/codemirror/addon/display/rulers.js
```

From http://codemirror.net/doc/manual.html#addons :
> [display/rulers.js](http://codemirror.net/addon/display/rulers.js)
>    Adds a rulers option, which can be used to show one or more vertical rulers > in the editor. The option, if defined, should be given an array of {column [, className, color, lineStyle, width]} objects >or numbers (wich indicate a column). The ruler will be displayed at the column indicated by the number or the column property. The className property can be used to assign a custom style to a ruler. [Demo here](http://codemirror.net/demo/rulers.html).
> 
> http://codemirror.net/demo/rulers.html

**Comment by minrk** [comment]
We could add a frontend-config value that's `codemirror_addons`, and load the list.

**Comment by Carreau** [comment]
you don't [need to](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/ruler) apparently.

**Comment by Carreau** [comment]
Closing as you can do that through an extension.

**Comment by jpeacock29** [comment]
To update links, this is in [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) as the [Ruler](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/ruler) extension.
