### ISSUE TITLE
ImportError: cannot import name anneal

### ISSUE THREAD

**Issue by csnap001** [jupyter/notebook#1600]
I'm trying to use lmfit to improve on a gaussian fit that I have done before, but I keep getting the above error whenever I try to import lmfit.  I've installed lmfit v. 0.7.4 and I've installed the latest versions of numpy, scipy, and ipywidgets. I cannot figure out what is wrong with this. I'm trying to run lmfit using the spyder IDE from anaconda (python 2.7).  I was wondering if there is a path issue, but I'm not sure how to troubleshoot for that or how to fix that issue if it exists.  has anyone had a similar issue?

**Comment by minrk** [comment]
Can you include the traceback (the full error, not just the last bit)? What OS?

**Comment by csnap001** [comment]
sure thing,
Traceback (most recent call last):

  File "<ipython-input-1-7fbec1989fc6>", line 1, in <module>
    runfile('C:/Users/owner/Documents/.spyder2/temp.py', wdir='C:/Users/owner/Documents/.spyder2')

  File "C:\Users\owner\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Users\owner\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/owner/Documents/.spyder2/temp.py", line 9, in <module>
    import lmfit as fit

  File "c:\users\owner\anaconda2\lib\site-packages\lmfit-0.7.4-py2.7.egg\lmfit\__init__.py", line 18, in <module>

  File "c:\users\owner\anaconda2\lib\site-packages\lmfit-0.7.4-py2.7.egg\lmfit\minimizer.py", line 23, in <module>

ImportError: cannot import name anneal


and the operating system is windows 10

**Comment by takluyver** [comment]
Looks like lmfit is trying to import `scipy.optimize.anneal`, which was removed in Scipy 0.16. You need a newer lmfit or an older scipy.

**Comment by csnap001** [comment]
Okay, so I downgraded scipy to version 0.13 (which also required me to downgrade numpy to 1.8), but now my spider IDE won't open.  When I try to open it I see the loading screen very briefly and then it doesn't continue to load.  Is there some conflict between these packages?

**Comment by csnap001** [comment]
I get this error when I run spyder --show-console:
![spyder error](https://cloud.githubusercontent.com/assets/10412412/16665516/c502bc30-4438-11e6-999d-12256128eeb8.png)

**Comment by takluyver** [comment]
No idea. You might have better luck asking on a spyder mailing list.

**Comment by csnap001** [comment]
Thanks,  I got it working. I updated lmfit to 0.9.2 and I updated scipy to the latest version, so now everything is working properly. If anyone else has a similar issue with anaconda I used conda install -c astropy  lmfit=0.9.2 to update lmfit (looking for it using conda commands didn't bring this up as an option for download on my system).
