### ISSUE TITLE
to develop one mode like rtutor

### ISSUE THREAD

**Issue by yuuuxt** [jupyter/notebook#1601]
Prof. Kranz developed a R package which looks nice: https://github.com/skranz/RTutor
Since jupyter is working on widgets and extensions, is it possible to have something similar in the future?

**Comment by gnestor** [comment]
It's possible to create quiz-like widgets using [ipywidgets](https://github.com/ipython/ipywidgets) or [declarativewidgets](https://github.com/jupyter-incubator/declarativewidgets). See the [widget-cookiecutter](https://github.com/jupyter/widget-cookiecutter) project for an example of how to create a custom Jupyter widget. 

I am going to close this issue. If you have specific questions about how build such a widget, please see the [ipywidgets Gitter](https://gitter.im/ipython/ipywidgets).
