### ISSUE TITLE
[Feature Request] Live NBViewer 

### ISSUE THREAD

**Issue by jdetle** [jupyter/notebook#1609]
## Issue

In situations like tutorials, tutorial leaders often provide jupyter notebooks to be followed along with while also using a master notebook themselves. Oftentimes these master notebooks can be subjected to changes and the changes are not easily legible in the tutorial environment. A tutorial participant being able to view that notebook live on their machine from a website would be of huge use to those struggling to keep up with changes to a master notebook. 
## Proposal

I'm not entirely sure how it would work. I have talked to someone who has had this issue and wrote a shell script to continuously `git add` `git commit` the master notebook he is working on, while users can keep refreshing the rendering of the github hosting of the notebook. Maybe there are some technical limitations, but wrapping the entire rendering of the master notebook in an iframe would prevent viewers of the master notebook from using it (I think?) This master notebook would have to be hosted somewhere, and be able to communicate with the instance of the master notebook being live edited by a tutorial teacher. This is really beyond my skill level.

Anyways, this feature would be really nice, I was encouraged by some Cal Poly students to post an issue and I hope it makes sense!

**Comment by mjbright** [comment]
I wonder why you closed this issue?

If I understood your proposal you see the need for a multiple "synchronized" view of a notebook as the master version is modified.

It seems like a good idea to me, for a classroom/tutorial setting.

I'm not aware of such an existing "real time" capability.

**Comment by jdetle** [comment]
Hi! Sorry I just posted it in Jupyter/help because I didn't know where the
issue was appropriate. Feel free to reopen it!
On Thu, Jul 14, 2016 at 3:10 PM Mike BRIGHT <notifications@github.com>
wrote:

> I wonder why you closed this issue?
>
> If I understood your proposal you see the need for a multiple
> "synchronized" view of a notebook as the master version is modified.
>
> It seems like a good idea to me, for a classroom/tutorial setting.
>
> I'm not aware of such an existing "real time" capability.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/notebook/issues/1609#issuecomment-232777839>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKcARsvzDb_HWaYTXW5riHKcNkTSVApUks5qVpfBgaJpZM4JMuNC>
> .
>
-- 
Have a wonderful day,
John J. Detlefs

**Comment by jdetle** [comment]
Hey all, sorry I was vascillating on where I should put this but I'm going to make a decision and post it here.

**Comment by takluyver** [comment]
No worries. Most of the team's busy at Scipy this week, but it is a good idea, and it fits in with the real-time collaboration stuff that @Carreau has planned.

**Comment by Carreau** [comment]
We did not spoke a lot about RTC, but that should be doable with JLab to "share" a RO view.

**Comment by jdetle** [comment]
Thanks @Carreau. I'll look into trying to do something this weekend.

**Comment by yuvipanda** [comment]
https://github.com/jupyterlab/jupyterlab/issues/5382 and issues linked from there pointing to ongoing work in this area. mybinder.org is also a 'live' nbviewer, but in a different sense :)

Going to close this one as there hasn't been any activity for a while, feel free to re-open if needed!
