### ISSUE TITLE
Advertise names of existing actions for keyboard shortcuts

### ISSUE THREAD

**Issue by fsaad** [jupyter/notebook#1611]
From the documentation page on [custom keyboard shortcuts](http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Custom%20Keyboard%20Shortcuts.html):

> Of course we provide name for majority of existing action so that you do not have to re-write everything, > here is for example how to bind r back to it’s initial behavior:

I could not find the list of existing actions in the documentation, and [looked up the source](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/keyboardmanager.js) to find the name of the action that I was looking for (`jupyter-notebook:show-command-palette`). I suggest making these names more visible, maybe right after the quoted paragraph.

**Comment by Carreau** [comment]
These should be visible if you hover the shortcut area with the  mouse:
![screen shot 2016-07-20 at 16 06 18](https://cloud.githubusercontent.com/assets/335567/17006208/fb86c39a-4e93-11e6-92c4-54a6ffa42c15.png)

**Comment by fsaad** [comment]
@Carreau thanks for the follow-up. I cannot reproduce that pop-up on Chrome Version 51.0.2704.106 (64-bit), Ubuntu 14.04, python 2.7.6, latest pip version. Arguably even if I could, it still is very subtly advertised.

**Comment by Carreau** [comment]
> Arguably even if I could, it still is very subtly advertised.

Yes I know and you can't copy and paste. The tooltip might be only on master, which also have a nice dialog to bind/remove new keyboard shortcuts:

![screen shot 2016-07-20 at 16 40 41](https://cloud.githubusercontent.com/assets/335567/17006859/d11fca5c-4e98-11e6-9fe4-9bedf33b867d.png)

**Comment by Carreau** [comment]
I'm pondering whether we should promote that for the current notebook, or make it a JupyterLab only thing. Maybe even update the current action names to match the futures-one form JupyterLab with deprecation warnings.

**Comment by takluyver** [comment]
@Carreau is there anything you want to do here for 5.0?

**Comment by Carreau** [comment]
> @Carreau is there anything you want to do here for 5.0?

Hum, check if the keyboard shortcut editor still works.

**Comment by Carreau** [comment]
> @Carreau is there anything you want to do here for 5.0?

#2104 should be enough and close this.
