### ISSUE TITLE
Output rerenders randomly

### ISSUE THREAD

**Issue by GreySage** [jupyter/notebook#1612]
I am using the Python notebook. I am using d3's force libraries to simulate spring and repulsion forces between nodes to layout a graph.

After I execute the cell containing the code to make and layout the graph, some time later the graph will rerender, going through the relaxation process again as if from the beginning. In addition, changes will be present in the graph, as if the notebook is running the code in later cells.

How can I turn off these rerenders, or at least control when they happen?

**Comment by Carreau** [comment]
would that be when notebook autosaves ? Have you updated ipywidgets ?

**Comment by GreySage** [comment]
It could be autosave induced, it is hard to tell. I don't think I have updated ipywidgets since I installed everything 1.5 months ago. Would that change something?

**Comment by Carreau** [comment]
Yes please, try to update ipywidget and corresponding extension.

**Comment by GreySage** [comment]
I found and followed this: http://stackoverflow.com/questions/25631344/turn-off-autosave-in-ipython-notebook
and so far it's been working.

**Comment by Carreau** [comment]
Ok, so then it is likely the ipywidgets issue. 

I would **strongly** recommend to update ipywidgets as if you have the version with that bug, you are **extremely likely** to be affected with a similar bug that can end up in permanent data-loss or worse. And this whether or not autosave have been turned off.

**Comment by GreySage** [comment]
How do I update ipywidgets?

**Comment by Carreau** [comment]
From the [documentation](http://ipywidgets.readthedocs.io/en/latest/user_install.html) I would say:

```
pip install ipywidgets --upgrade
jupyter nbextension enable --py widgetsnbextension
```

**Comment by GreySage** [comment]
Its working better now, and it no longer re-renders when I save. Thanks for the help.

**Comment by Carreau** [comment]
Great ! Happy that solves it for you. 

@gnestor  I updated your permissions, can you try to close this issue ? That will allow us to check that you can press the "Close and comment button" and that everything works as expected.

**Comment by gnestor** [comment]
👌

**Comment by Carreau** [comment]
> 👌

Great welcome to the team !
