### ISSUE TITLE
Broken "Try JupyterLab" link if JupyterLab is not installed

### ISSUE THREAD

**Issue by staeiou** [jupyter/notebook#1615]
I just installed the master branch of Jupyter Notebook, but have not installed JupyterLab. When I click on the "Try JupyterLab" image, it goes to http://localhost:8888/jupyter/lab, which is a broken URL. To resolve this, the image could either be hidden if JupyterLab is not installed, or it could instead link to the JupyterLab GitHub URL.

**Comment by blink1073** [comment]
Hi @staeiou, you found a vestige of when JupyterLab was contained *within* this repository (a few weeks ago).  The plan is for the jupyterlab extension to add the button itself.

**Comment by ellisonbg** [comment]
We have decided that the notebook package will *depend* on JupyterLab so it will never happen that JLab will be missing if that button is shown.

**Comment by jasongrout** [comment]
We should make it depend right now, then.

**Comment by jasongrout** [comment]
But the other issue is that the extension should provide the button so that it appears in notebook 4.2 when you have the extension installed. I think once we have that, we should follow through and remove the hard-coded button in notebook dev master.

**Comment by parente** [comment]
> We have decided that the notebook package will depend on JupyterLab so it will never happen that JLab will be missing if that button is shown.

If I'm reading this right, this implies the kernel_gateway package, which depends on notebook for the API definition, will now also pull in the jupyterlab package?

**Comment by Carreau** [comment]
one of the other issue is that if the extension is still there, but the js extension is there you still get teh link, but it's broken....

**Comment by takluyver** [comment]
I no longer see the 'Try Jupyterlab' button in the notebook, so can this be closed now?
