### ISSUE TITLE
no vertical scroll bar for very long output cell

### ISSUE THREAD

**Issue by yiannissakk** [jupyter/notebook#1619]
Hello,

I have a notebook in which a code cell outputs a very long output. However, when I open it with anaconda the output is toggled but in github its not. You can find the notebook here: https://github.com/yiannissakk/XML-Parsing/blob/master/XML-Parsing.ipynb. 

Thanks!

**Comment by Carreau** [comment]
GitHub does static rendering of notebooks with no javascript, for security reasons. So collapse is not possible.  We have no control of how they render it. Sorry about that.
