### ISSUE TITLE
Notebook can only be used on root URL directory /

### ISSUE THREAD

**Issue by dashboardsfhi** [jupyter/notebook#1621]
All of the links in notebook are hardcoded to the root / of the URL.

So basically, it expects that the notebook is being run at: localhost:8888/

I have been trying to tunnel notebook through a nginx reverse proxy, so that I can access the notebooks at: localhost/p/

However, this does not work, as notebook does not acknowledge that it is being loaded at localhost/p/ as the base URL.

For example, when I try to load localhost/p/, notebook automatically redirects me to localhost/tree (instead of localhost/p/tree). Where localhost/p/api should work, notebook will only call localhost/api.

This means that notebook is impossible to incorporate into a larger system, as it demands a number of very important directories! It demands /static, /api, /custom, among others.

If notebook removed the leading "/" from its calls, making it location agnostic, then it would be easier to incorporate it into a larger system. e.g. localhost/p/ for notebook, localhost/r/ for rstudio, localhost/prod/ for production shiny apps, etc etc.

**Comment by dashboardsfhi** [comment]
My bad, should have read the docs better:

http://jupyter-notebook.readthedocs.io/en/latest/public_server.html

**Comment by ellisonbg** [comment]
Should we close this then?
