### ISSUE TITLE
javascript-python communication not working when "Run All" cells

### ISSUE THREAD

**Issue by e2raptor** [jupyter/notebook#1622]
Hi everyone, I have a notebook with this:

<img width="482" alt="screenshot_2016_07_18_16_03_56" src="https://cloud.githubusercontent.com/assets/16085308/16930334/576da7c6-4d01-11e6-9887-59295a9654ce.png">

It turns out that it works well (the last print for num shows 43) but only when I execute this cell by cell. But if I execute it by clicking the "Run All" menu, or by calling in a js file the "notebook.execute_all_cells()" function, the num variable is never modified from the js code.  

The idea is that I have some special notebooks where I need to execute every cell when it loads, but some cells depend on a python variable filled from javascript.  I've tried to delay the last cell execution time enough so the previous cell is finished, but since the cells execution is linear, I don't think this could solve my problem.

Can someone point me a way on how to do this?

**Comment by takluyver** [comment]
>  the num variable is never modified from the js code. 

It probably is, but only after the cell printing it has run.

Depending on what you need it for, you may be able to define a function in Python that receives the value, and then call that function from the Javascript.

**Comment by e2raptor** [comment]
> It probably is, but only after the cell printing it has run.

No, actually is not modified, because in that case, after every cell is executed, the modification should be available let's say on a new cell, or if I re-execute the last cell, but it isn't.  And calling a defined python function from javascript, in my case, does not work either, because the data I need comes only from javascript (is a json object), and I'll have to pass it as a parameter to the function, which is the same thing that storing it into a python var.

**Comment by michelmetran** [comment]
Hello!,
I have the same problem.
Were you able to resolve it in any way?

When I try to apply a "Run All" ... it interrupts the script when it reads the magic line %%javascript.

Tks!

**Comment by TimoFriedri** [comment]
*Bump*,

I have the same issue. I get the Notebook name in a Javacript function for archiving of the notebook as html. But for me also only the cell by cell execution works.

**Comment by adamraudonis** [comment]
I'm having the exact same issue! Any idea how this can be fixed?

**Comment by siwing** [comment]
Is there a way to solve this issue now?

**Comment by Crypto-Spartan** [comment]
Having the same issue as well. Tried adding this in the cell after my %%javascript
```
while 'my_var' not in locals():
    await asyncio.sleep(1)
```

Unfortunately, this didn't work, the code was just in an indefinite await period. Definitely looking for a solution to this.

**Comment by kevin-bates** [comment]
I believe this issue is more about [`ipykernel`](https://github.com/ipython/ipykernel) and its internal state/context than notebook and you might have better traction opening an issue in that repo.
