### ISSUE TITLE
Outputting to LaTeX

### ISSUE THREAD

**Issue by YPares** [jupyter/notebook#1625]
Being able to generate a PDF is great, but often I want to include this output into a bigger report or article.

Could it be possible to propose a "Write to LaTeX" option that just outputs the latex code without building any PDF?

**Comment by takluyver** [comment]
It's not currently exposed in the 'Download as' menu - though it's a totally reasonable request - but you can already do this at the command line:

```
jupyter nbconvert --to latex MyNotebook.ipynb
```

**Comment by YPares** [comment]
Thanks a lot! I didn't know you could do that

2016-07-20 14:51 GMT+02:00 Thomas Kluyver <notifications@github.com>:

**Comment by gnestor** [comment]
@YPares I'm going to close this issue. We welcome and invite PRs to support a "Download as LaTeX" feature.
