### ISSUE TITLE
When opening a notebook file, the browser displays a blank screen

### ISSUE THREAD

**Issue by chetan-guevara** [jupyter/notebook#1627]
I'm a bit perplexed by the issue I'm having. I type "jupyter notebook" at the CLI and I get normal directory view. Everything works here ... the text file creator, the terminal window, and the file browser. However when I create a new notebook file or open an existing one, I get a totally blank screen in my browser. 
This problem appeared when I installed jupyter. Beforehand, my ipython notebok was working just fine. So I uninstalled anaconda and then re-installed it. I also updated Chrome, and rebooted my computer and the problem still persists. 

Haven't been able to see this problem spoken about online.
Screenshots attached. Any thoughts on what could be happening? 
<img width="1280" alt="screen shot 2016-07-21 at 9 38 51 pm" src="https://cloud.githubusercontent.com/assets/3173623/17046808/14c2aa60-4f8c-11e6-8de9-8b37e231206e.png">
<img width="1280" alt="screen shot 2016-07-21 at 9 39 00 pm 2" src="https://cloud.githubusercontent.com/assets/3173623/17046807/14beb694-4f8c-11e6-98ac-0801db9e9363.png">

**Comment by takluyver** [comment]
Can you look in the browser's JS console for any error messages? Also, any errors in the terminal where you started the notebook?

**Comment by chetan-guevara** [comment]
Thanks for getting back to me Tak. I got it figured out. I had edited custom.js in my previous iPython notebook to allow for emacs bindings. Once I deleted those lines, the Jupyter notebook started working.

FYI, there were no relevant error messages that popped up in my JS console.

**Comment by takluyver** [comment]
OK, I'm glad you got it figured out - though it's a bit disconcerting that problems in custom.js can stop the whole thing from loading and not give any error message. I'll leave this open for now in case anyone wants to look into making that more robust.

**Comment by Carreau** [comment]
> OK, I'm glad you got it figured out - though it's a bit disconcerting that problems in custom.js can stop the whole thing from loading and not give any error message. I'll leave this open for now in case anyone wants to look into making that more robust.

I **think** in master it is taken care of, but it's quite complicated to get it right in JS with webpack + require.

**Comment by takluyver** [comment]
Is this fixed (or easier to fix) now that we've dropped webpack?

**Comment by Carreau** [comment]
On master with an invalid (SyntaxError) custom JS, notebooks loads. So I'll consider as fixed and close.

**Comment by aisuryanayak** [comment]
I have same issue !! can't solve the issue .i have written the errors coming in console.


Uncaught SyntaxError: Invalid or unexpected token
index.js:1 Uncaught SyntaxError: Invalid or unexpected token
index.js:1 Uncaught SyntaxError: Invalid or unexpected token
require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900 ReferenceError: preact is not defined
    at shortcuteditor.js:15
    at Object.execCb (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690)
    at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865)
    at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177)
    at Object.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1550)
    at Module.<anonymous> (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1162)
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131
    at each (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56)
    at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1114)
    at Object.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1550)
check @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900
setTimeout (async)
(anonymous) @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1809
localRequire @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1442
requirejs @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1791
(anonymous) @ main.js:23
require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900 TypeError: Cannot read property 'ShortcutEditor' of undefined
    at notebook.js:64
    at Object.execCb (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690)
    at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865)
    at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177)
    at Object.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1550)
    at Module.<anonymous> (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1162)
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131
    at each (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56)
    at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1114)
    at Module.init (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:783)
check @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900
setTimeout (async)
(anonymous) @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1809
localRequire @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1442
requirejs @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1791
(anonymous) @ main.js:23
require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900 TypeError: Cannot read property 'Notebook' of undefined
    at main.js:120
    at Object.execCb (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690)
    at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865)
    at Module.<anonymous> (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140)
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1190
    at each (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56)
    at Module.emit (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1189)
    at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:940)
    at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177)
check @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900

**Comment by manojkumar1412** [comment]
same issue as @aisuryanayak . did anyone figure out?

**Comment by vigneshwaran** [comment]
Solved:
I had no mathjax.js file in my system(fedora). I pasted mathjax folder uder javascript, now it works fine.

**Comment by ron221** [comment]
I cleared all the browsing history and cookies in Chrome, and the problem is solved.

**Comment by tiborkiss** [comment]
It was enough to clear the cache only. At least for me it was safe to keep cookies and browsing history.

**Comment by adibaliga** [comment]
I'm also facing same error when i tried to open notebook, internet explorer blank screen appears

**Comment by selimbin** [comment]
I also face the same issue, and when I oppened the js console this was written:Uncaught TypeError: "#element".tooltip is not a function
    at VM12 tree:362

**Comment by hokiwood-geek** [comment]
> I'm a bit perplexed by the issue I'm having. I type "jupyter notebook" at the CLI and I get normal directory view. Everything works here ... the text file creator, the terminal window, and the file browser. However when I create a new notebook file or open an existing one, I get a totally blank screen in my browser.
> This problem appeared when I installed jupyter. Beforehand, my ipython notebok was working just fine. So I uninstalled anaconda and then re-installed it. I also updated Chrome, and rebooted my computer and the problem still persists.
> 
> Haven't been able to see this problem spoken about online.
> Screenshots attached. Any thoughts on what could be happening?
> <img alt="screen shot 2016-07-21 at 9 38 51 pm" width="1280" src="https://cloud.githubusercontent.com/assets/3173623/17046808/14c2aa60-4f8c-11e6-8de9-8b37e231206e.png">
> <img alt="screen shot 2016-07-21 at 9 39 00 pm 2" width="1280" src="https://cloud.githubusercontent.com/assets/3173623/17046807/14beb694-4f8c-11e6-98ac-0801db9e9363.png">

another way probably solve which needn't delete the history and cache of chrome, instead delete the all file cache in file:///C:/Users/86133/AppData/Roaming/jupyter/runtime
As soon as I deleted it, it login in immediately...
