### ISSUE TITLE
The '_' in the Ipython

### ISSUE THREAD

**Issue by GeekTemo** [jupyter/notebook#1628]
Hi!
     When I import some third library, I find a problem.  When I use the "Fn.py",  then import  "_"  and run a row code.   

    In [5]: from fn import _

    In [6]: map(_ * 2, range(5))
    Out[6]: [0, 2, 4, 6, 8]

    In [7]: filter(_ < 10, [9,10,11])
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-7-04b50578862b> in <module>()
    ----> 1 filter(_ < 10, [9,10,11])

    TypeError: 'bool' object is not callable。

I found the `_` of "Fn.py" is conflict with the Ipython's  `_`.  Has a method to solution the conflict ?

**Comment by takluyver** [comment]
`_` is a convention in the plain Python shell as well as IPython, so you can't set it to something else when working interactively. You can work around this by doing:

```python
from fn import _ as _x
```

**Comment by Carreau** [comment]
we should be able to  detect in IPython if `_` is `In[-1]` or not, and not reset it if set. 
That's how the normal Python interpreter behave,

**Comment by Carreau** [comment]
See https://github.com/ipython/ipython/pull/9825, that could be further improved , and need to be tested.

**Comment by Carreau** [comment]
Marking as "Non notebook", as this is not really a notebook issue, and keep the maintainer of this repo with a smaller list of issue.
