### ISSUE TITLE
Refactoring facilities

### ISSUE THREAD

**Issue by InonS** [jupyter/notebook#163]
One of the most significant features still missing, for example: Rename (context-sensitive 'replace all').
Other, less used facilities, such as Generate (getters and setters, etc.)

I've been using Jupyter, as it came with my IPython installation, but I whole-heartedly support the decision to separate the projects. Until Jupyter is able to keep up, and hopefully lead, I'm tempted to IDEs with IPython notebook integration such as Spyder, Ninja-IDE, or PyCharm (Community edition).

**Comment by rdipietro** [comment]
+1 :)

**Comment by JamiesHQ** [comment]
@blink1073 @gnestor : is this functionality provided in JupyterLab and does it make sense to port the issue to the JLab org?

**Comment by blink1073** [comment]
Migrated to https://github.com/jupyterlab/jupyterlab/issues/2104.
