### ISSUE TITLE
Python 3 kernel shown as "Python [Root]"

### ISSUE THREAD

**Issue by fonnesbeck** [jupyter/notebook#1630]
After installing the Notebook via `conda`, my default Python 3 kernel is shown as `Python [Root]` instead of `Python 3`. 

![](http://dsh.re/f2eae)

I wouldnt care, except that notebooks saved under this kernel will not work without manually changing the kernel.

Running Anaconda Python 3.5.1 on OS X 10.11.5.

**Comment by takluyver** [comment]
If you just want to get back to the regular kernels mechanism, I think that uninstalling `nb_conda_kernels` should do it.

**Comment by fonnesbeck** [comment]
That fixed the issue, thanks.

**Comment by AnakinShieh** [comment]
after uninstalling ```nb_conda_kernels```, it just rasies 
```
[C 02:02:39.584 NotebookApp] Bad config encountered during initialization:
[C 02:02:39.584 NotebookApp] The 'kernel_spec_manager_class' trait of <notebook.notebookapp.NotebookApp object at 0x0000
01B7078F8A20> instance must be a type, but 'nb_conda_kernels.CondaKernelSpecManager' could not be imported
```
How can I solve it?

**Comment by Carreau** [comment]
> after uninstalling nb_conda_kernels, it just rasies
> 
> [C 02:02:39.584 NotebookApp] Bad config encountered during initialization:
> [C 02:02:39.584 NotebookApp] The 'kernel_spec_manager_class' trait of <notebook.notebookapp.NotebookApp object at 0x0000
> 01B7078F8A20> instance must be a type, but 'nb_conda_kernels.CondaKernelSpecManager' could not be imported
> How can I solve it?

You need to find the configuration file that conda modified, and remove the `NotebookApp.kernel_spec_manager_class` setting.

**Comment by damianavila** [comment]
Just to let you know, several people have been working in a solution for the original issue and we will have the updated package (containing the fix) available from the default channels by early next week.

**Comment by Carreau** [comment]
> Just to let you know, several people have been working in a solution for the original issue and we will have the updated package (containing the fix) available from the default channels by early next week.

Thanks a lot @damianavila !

**Comment by damianavila** [comment]
Pasting general answer here as well:

We've released versions of `nb_conda`, `nb_conda_kernels` and `nb_anacondacloud` through the official Anaconda conda repos that should resolve the issues you are seeing!
```
conda update nb_conda nb_conda_kernels nb_anacondacloud
```
As-installed kernel names that are eligible for being default (e.g. python2, python3, ir, etc.) will be maintained unmodified, so they should always appear there.

The downside is as many as three options for the current env, i.e. if you are in root, you will see Python 2 and Python [root] and Python [default], you can now reproducibly capture which environment your kernel should run against.

meta: Anaconda-Platform/anaconda-nb-extensions#166

**Comment by AnakinShieh** [comment]
I have tried to update ```nb_conda```. 
but after I update, there stills shows ```python[root]``` in the jupyter notebook, and cannot find any python kernels, even I have tried to use ```python -m ipykernel install --user ```, and in 'kernels' folder, there did exist a python3 kernelspec file. But jupyter cannot load it.
```
[W 15:02:20.478 NotebookApp] Unrecognized JSON config file version, assuming version 1
[I 15:02:21.048 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 15:02:21.538 NotebookApp] \u2713 nbpresent HTML export ENABLED
[W 15:02:21.539 NotebookApp] \u2717 nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 15:02:21.544 NotebookApp] [nb_conda] enabled
[I 15:02:21.605 NotebookApp] [nb_anacondacloud] enabled
[I 15:02:22.175 NotebookApp] Serving notebooks from local directory: C:\Users\Anakin
[I 15:02:22.175 NotebookApp] 0 active kernels
[I 15:02:22.175 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 15:02:22.190 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 15:02:25.228 NotebookApp] Creating new notebook in
[W 15:02:25.814 NotebookApp] 404 GET /kernelspecs/Python%20[Root]/logo-64x64.png (::1) 8.00ms referer=http://localhost:8
888/notebooks/Untitled2.ipynb?kernel_name=Python%20[Root]
[W 15:02:25.882 NotebookApp] Kernel not found: Python [Root]
[E 15:02:25.882 NotebookApp] {
      "Host": "localhost:8888",
      "Cache-Control": "no-cache",
      "Content-Type": "application/json",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0
 Safari/537.36 Edge/13.10586",
      "Content-Length": "83",
      "Connection": "Keep-Alive",
      "Accept-Language": "en-US,en;q=0.8,zh-Hans-CN;q=0.5,zh-Hans;q=0.3",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=Python%20[Root]",
      "X-Requested-With": "XMLHttpRequest"
    }
[E 15:02:25.908 NotebookApp] 501 POST /api/sessions (::1) 80.02ms referer=http://localhost:8888/notebooks/Untitled2.ipyn
b?kernel_name=Python%20[Root]
```

**Comment by fonnesbeck** [comment]
I get the following collision warnings during the install of these packages, and when I subsequently run notebooks:

```
Collisions detected in jupyter_notebook_config.py and jupyter_notebook_config.json config files. jupyter_notebook_config.json has higher priority: {
      "NotebookApp": {
        "nbserver_extensions": "{'jupyter_nbextensions_configurator': True, 'ipyparallel.nbextension': True, 'jupyterlab': True, 'nb_conda': True, 'nbpresent': True, 'nb_anacondacloud': True} ignored, using {'jupyter_nbextensions_configurator': True, 'jupyterlab': True}"
      }
    }
```

**Comment by fonnesbeck** [comment]
Are the new packages still supposed to have names like this:

![](http://dsh.re/1f20a)

These make sharing notebooks a bit of a pain because it requires all users to have kernels with the same name.

**Comment by Carreau** [comment]
> These make sharing notebooks a bit of a pain because it requires all users to have kernels with the same name.

Notebook should fall back on a similar python env, or at least ask use to chose a matching env if this is the case. 

Can you open a separate issue for the collision ?

**Comment by damianavila** [comment]
> Notebook should fall back on a similar python env, or at least ask use to chose a matching env if this is the case.

That's right... additionally, we have been thinking about this and there is some nice ideas on this thread to solve this one and other issues: https://github.com/Anaconda-Platform/nb_conda_kernels/issues/42#issuecomment-236173104

**Comment by damianavila** [comment]
One more clarification, if you use `python [default]` and share that notebook with another one without `nb_conda_kernels` installed you will be fine, because `python [default]` use the Jupyter's default kernels name. If you try to share a notebook with a `conda...` kernel in it, in that case, the notebook will ask you to select a kernel (from the available ones) to start the notebook if you have several kernels installed, otherwise it should default to the native one.

**Comment by jzf2101** [comment]
I installed the latest version of anaconda3 and have similar issues

**Comment by damianavila** [comment]
> I installed the latest version of anaconda3 and have similar issues

Can you describe the issues? I guess it is related with other issue: https://github.com/jupyter/notebook/issues/1716

Thanks!

**Comment by Stibbons** [comment]
Same problem. On my system, "Python [Root]" and Python [default]" are the same. I propose to avoid duplication (#48)

**Comment by damianavila** [comment]
>Same problem. On my system, "Python [Root]" and Python [default]" are the same. I propose to avoid duplication (#48)

 The correct link is : https://github.com/Anaconda-Platform/nb_conda_kernels/pull/48 :wink: for people interested.

Cheers.

**Comment by JustinShenk** [comment]
Installing with `conda install nb_conda_kernels` fixed it for me.
