### ISSUE TITLE
CSP Documentation quoting

### ISSUE THREAD

**Issue by bindernet** [jupyter/notebook#1639]
The doc https://github.com/jupyter/notebook/blob/master/docs/source/public_server.rst gives the following example:

```
c.NotebookApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors 'https://mywebsite.example.com' 'self' "
    }
}
```

Having the URL in single quotes doesn't seem to work for me
i.e this **works**

```
c.NotebookApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors * 'self' "
    }
}
```

This **doesn't**:

```
c.NotebookApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors '*' 'self' "
    }
}
```

**Comment by Carreau** [comment]
that is strange, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives) single quotes are **required** for some of these.  We'll have to check that. 

Thanks a lot for you detailed investigation.

**Comment by bindernet** [comment]
The keywords e.g 'self' need quotes the URLs don't. Kind of the opposite to python code.
self without quotes would mean a hostname self.
I'll try and find some definitive documentation - w3c mentions that you need the quotes for keywords but not that they are superfluous for URLs.

Try it - my results above were with the latest firefox (47.0)

**Comment by takluyver** [comment]
@Carreau does this want a docs change for 5.0?

**Comment by Carreau** [comment]
I think we can bump to a 5.1, but it woudl be nice to have that on stable docs.

**Comment by takluyver** [comment]
Anyone got time to update the docs, or is it going to be bumped again?

**Comment by gnestor** [comment]
Is this all that's needed?: https://github.com/jupyter/notebook/pull/2695/files
