### ISSUE TITLE
when set ignore_minified_js with true the jquery will not load.

### ISSUE THREAD

**Issue by Anne623** [jupyter/notebook#1641]
Hi, all, I use notebook 4.2.1, when i set `c.NotebookApp.ignore_minified_js = True`， load home page will be error:

![image](https://cloud.githubusercontent.com/assets/10845504/17204839/507958f8-54da-11e6-9bd7-526de9b6943a.png)

![image](https://cloud.githubusercontent.com/assets/10845504/17204863/823bef72-54da-11e6-9dab-e7f7d6bca503.png)

the browser console is :

```
require.js?v=6da8be3…:900 TypeError: $ is not a function(…)check @ require.js?v=6da8be3…:900enable @ require.js?v=6da8be3…:1177init @ require.js?v=6da8be3…:783callGetModule @ require.js?v=6da8be3…:1204completeLoad @ require.js?v=6da8be3…:1583onScriptLoad @ require.js?v=6da8be3…:1711
require.js?v=6da8be3…:900 TypeError: Cannot read property 'extend' of undefined(…)check @ require.js?v=6da8be3…:900(anonymous function) @ require.js?v=6da8be3…:1140(anonymous function) @ require.js?v=6da8be3…:131(anonymous function) @ require.js?v=6da8be3…:1190each @ require.js?v=6da8be3…:56emit @ require.js?v=6da8be3…:1189check @ require.js?v=6da8be3…:940enable @ require.js?v=6da8be3…:1177init @ require.js?v=6da8be3…:783callGetModule @ require.js?v=6da8be3…:1204completeLoad @ require.js?v=6da8be3…:1604onScriptLoad @ require.js?v=6da8be3…:1711
require.js?v=6da8be3…:900 TypeError: Cannot read property 'proxy' of undefined(…)
```

did i miss some configuration?

**Comment by minrk** [comment]
I believe you can only use this flag when running from a git repo (`cd /to/notebook/repo && pip install -e .`)

**Comment by Anne623** [comment]
@minrk Thank you for your reply. :)
Actually, I deploy a develop env for jupyter notebook as below:
![image](https://cloud.githubusercontent.com/assets/10845504/17210027/dcfe5bf8-54f2-11e6-9935-440c0fa67575.png)

and I run notebook from source。 I clone source code from github:
![image](https://cloud.githubusercontent.com/assets/10845504/17210068/1814f738-54f3-11e6-8b28-c9f6b350cf64.png)

**Comment by minrk** [comment]
What do you get from `python -c 'import notebook; print(notebook.__file__)'`?

**Comment by takluyver** [comment]
Yep, if you've cloned from Github, the project is a git repo.

Check the `notebook/static/components` subdirectory to make sure that you've got the notebook's javascript dependencies; these are still needed even with `ignore_minified_js`, and I think someone recently found `pip install -e .` didn't get them.

If that directory is empty, run `python setup.py jsdeps` to fetch the necessary JS libraries.

**Comment by Carreau** [comment]
With the recent webpack/requires modification it might be --ignore_minified_js does not work anymore.

**Comment by Anne623** [comment]
@takluyver  I check the  ```notebook/static/components``, it has javascript dependencies.
![image](https://cloud.githubusercontent.com/assets/10845504/17234609/0fa5b630-556d-11e6-9b7a-d609feae03cb.png)

I thank if the subdirectory is empty, the console will be throw 404 status, but it not.

**Comment by Anne623** [comment]
I delete the code in in ```/notebook/templates/page.html```
```
 define("bootstrap", function () {
          return window.$;
      });

      define("jquery", function () {
          return window.$;
      });

      define("jqueryui", function () {
          return window.$;
      });

      define("jquery-ui", function () {
          return window.$;
      });
```
 
It works well. 

By the way, I find in ```/notebook/templates/page.html```,  js dependcy ```typeahead: 'components/jquery-typeahead/dist/jquery.typeahead'``` is wrong path, because in ```components/jquery-typeahead/dist/``` only has ```jquery.typeahead.min.js```, no ```jquery.typeahead.js```

I checkout the source code from tag 4.2.1

**Comment by Carreau** [comment]
> By the way, I find in /notebook/templates/page.html, js dependcy typeahead: 'components/jquery-typeahead/dist/jquery.typeahead' is wrong path, because in components/jquery-typeahead/dist/ only has jquery.typeahead.min.js, no jquery.typeahead.js

I **think** it might be using a search path, so `min.js`  or `.js` should not matter. 

Thanks a lot for diving into that and making a detailed bug report. 

I'll assign myself and try to see what's happening there, I have a bit of backlog to go through first, so I might not get to dig into that soon.
