### ISSUE TITLE
[Feature Request] ctrl+g and ctrl+h shortcut for Greek and Hebrew while in Edit Mode

### ISSUE THREAD

**Issue by Ricyteach** [jupyter/notebook#1644]
Greek and Hebrew letters are used a lot in scientific computing. Jupyter added a shortcut feature for typing Greek letters, like so: 

`\alpha`, `<TAB>`

This is helpful, but it could be better. It would be nice, when in Edit Mode, to be able to type like this, such as in Mathcad (which has had this feature for a long time... >20 years I believe):

`a`, `<ctrl+g>` ('g' for 'Greek', obviously)

The same could be done for Hebrew letters as well with `ctrl+h.` 

This would cut down on a lot of typing for people in the civil engineering profession like me, who are attempting to use something like Jupyter rather than Mathcad.

**Comment by takluyver** [comment]
In general, we avoid Ctrl- shortcuts because they clash with browser shortcuts (both Ctrl-G and Ctrl-H are already bound on my system, for instance).

@Carreau is the shortcut editor released yet?

**Comment by Carreau** [comment]
> @Carreau is the shortcut editor released yet?

No it's only on master for now, and it would still need a custom extension to add such an action. 

Note that the `\alpha<tab>` is taken care of by **IPython** note the notebook, as it is an actual kernel completions that will work only on CodeCell. If it would be useful I think developing an extension should not be too hard, but it will likely need to extend codemirror. 

I would strongly recommend a custom keyboard layout use something like [ukelele](https://www.macupdate.com/app/mac/14495/ukelele)  on mac, you can set up a dead-key/compose key to type any unicode caracters or abbreviation. it has the advantage of working in all applications.

**Comment by jtpio** [comment]
Closing as the classic notebook UI has now been moved to https://github.com/jupyter/nbclassic.

Feel free to open a new issue there if it is still relevant, thanks!
