### ISSUE TITLE
Keyboard shortcuts help document lists commands in uppercase

### ISSUE THREAD

**Issue by dickfeynman** [jupyter/notebook#1648]
This is probably trivial, but might be relevant for first-time users. (It certainly tripped me up for a few minutes)
'Help -> Keyboard Shortcuts' lists all alphabets in the shortcut in upper case so maybe it's worth mentioning on top that they're not case sensitive, and one need not use 'Shift+<char>' unless explicitly mentioned.

**Comment by Carreau** [comment]
Hi @dickfeynman 

The appearance of keyboard shortcuts should be following platform conventions, [At least on Windows and  Mac OS], so it seem weird that you got confused, isn't that the case for you ? But thanks for the data point.

**Comment by dickfeynman** [comment]
@Carreau: I'm surprised; I wasn't aware of such a thing. I'm using Arch Linux (kernel 4.6.4-1) with gnome-shell v3.20.3, and I've attached a screenshot of what I see.
![jupyterkeyboardshortcuts](https://cloud.githubusercontent.com/assets/1929464/17345781/a8a5e812-58d5-11e6-88ae-0749ae973b11.png)

**Comment by Carreau** [comment]
Can you screenshot native menus for comparison ? e.g, on Mac os, native shortcut are uppercase, always. [And APple Human Guideline interface ask for them to be upper case. 

![screen shot 2016-08-02 at 15 45 14](https://cloud.githubusercontent.com/assets/335567/17347961/1fd2c06c-58c8-11e6-9948-a807fb78eea9.png)

**Comment by dickfeynman** [comment]
You're right, my desktop environment seems to be following the same upercase convention. I guess it's been a long time since I looked up keyboard shortcuts on my system.

Thanks for the responses. My bad.

**Comment by Carreau** [comment]
> You're right, my desktop environment seems to be following the same upercase convention. I guess it's been a long time since I looked up keyboard shortcuts on my system.
> 
> Thanks for the responses. My bad.

No problem, you are not the first one to make the remark. I guess the thing that threw you off was that there is **no** modifiers, so your brain desperately fills-in a modifier by thinking "Oh it's uppercase I have to press shift". There are case where shortcut appear lower case, like GMail for example. But even putting shortcut lowercase does confuse people who are looking for a modifier.

**Comment by takluyver** [comment]
On most keyboards, the key caps also have uppercase letters, so I have a Q key rather than a q key. ;-)

I've just checked the applications I have open (on Linux) and they all use uppercase letters in shortcut descriptions - including apps built in XUL, Qt, Gtk and Electron.
