### ISSUE TITLE
Multiple selection issues.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1654]
The Shift-Down command mode multiple selection seem to have some defects:

See here when I'm shift-downing from the header cell, they don't get selected; though they are with shift-Up. 

THe "up selection" should then contract to a single selection when I press down at the end, but 2 cells still have a blue background. 

![multiple-cin](https://cloud.githubusercontent.com/assets/335567/17381878/11b07a90-5983-11e6-876e-7f1dc6f0fddc.gif)

**Comment by takluyver** [comment]
See also #1589

**Comment by Carreau** [comment]
> See also #1589

Oh yes, thanks !

**Comment by takluyver** [comment]
I think this was fixed by #1891
