### ISSUE TITLE
Jupyter installation is not working with python 2.7+ on MacOS 10.11.6

### ISSUE THREAD

**Issue by shyamalschandra** [jupyter/notebook#1663]
![image](https://cloud.githubusercontent.com/assets/9545735/17462724/0d8924b6-5c7c-11e6-8c6f-949497424a88.png)

I am getting errors when I run 

`sudo pip install jupyter`

on my MacOS 10.11.6 machine with python 2.7+.

Do you have any idea what is going on?  What should I do?

![image](https://cloud.githubusercontent.com/assets/9545735/17462755/d5593990-5c7c-11e6-8747-b6bdb11d846d.png)

With notebook, I am getting the same problem.  What is going on?

**Comment by willingc** [comment]
@shyamalschandra We don't recommend using sudo to install on OS X. I would recommend using the Anaconda distribution as described in the Jupyter documentation http://jupyter.readthedocs.io/en/latest/install.html. Alternatively, what is the full output if you type ``pip install jupyter``?

**Comment by shyamalschandra** [comment]
I now used 

`pip install --user jupyter`
`pip install --user notebook`

but when I do a `jupyter notebook`, jupyter says the following:
```
Shyamals-iMac-174:session-2 shyamalchandra$ jupyter notebook
jupyter: 'notebook' is not a Jupyter command
```

What do I do to solve this problem?

**Comment by takluyver** [comment]
I would guess that the location it's installed scripts to (probably `~/.local/bin`) is not on `$PATH`. We usually solve this by modifying PATH in something like  `~/.bashrc`.

**Comment by shyamalschandra** [comment]
I don't see `~/.local/bin` in Mac OSX.  Do I need to create the directory?

Thanks!

**Comment by takluyver** [comment]
Maybe it's a different location on Macs, someone else will have to advise you on that.

**Comment by gnestor** [comment]
@shyamalschandra I highly suggest that you just install Anaconda which will install Python, Jupyter, and most of the libs that you might use with Jupyter. Otherwise, installing Jupyter can get complicated. See the [installation docs](http://jupyter.readthedocs.io/en/latest/install.html#installing-jupyter-using-anaconda-and-conda) for more info.

**Comment by pashupati123** [comment]
Try this its working for me

python -m pip install --upgrade pip --user
pip install --upgrade --force-reinstall --no-cache-dir jupyter --user
To run the jupyter notebook:-> python -m notebook

**Comment by bunbunbun777** [comment]
@pashupati123 Thank You

**Comment by PythonTobil** [comment]
> Try this its working for me
> 
> python -m pip install --upgrade pip --user
> pip install --upgrade --force-reinstall --no-cache-dir jupyter --user
> To run the jupyter notebook:-> python -m notebook

it works for me!
