### ISSUE TITLE
Firefox 48 (Electrolysis disabled) short cuts not captured

### ISSUE THREAD

**Issue by gyphub** [jupyter/notebook#1666]
On Firefox 48 shortcuts like Ctrl-t and Ctrl-n are not captured within the Notebook (neither in command nor in edit mode). So instead of triggering the bound Jupyter actions, tabs and windows are opened. Firefox 48 ships with the new Electrolysis feature which might have something to do with this. However in this case it is not enabled.

jupyter                   1.0.0       py35_3
jupyter_client         4.3.0       py35_0
jupyter_console     5.0.0       py35_0
jupyter_core          4.1.0       py35_0
notebook               4.2.2       py35_0

**Comment by takluyver** [comment]
We don't use Ctrl-T or Ctrl-N as shortcuts, precisely because they conflict with browser shortcuts. We only use a couple of Ctrl- shortcuts where the browser option wouldn't make sense - I've just checked Ctrl-S (save) and Ctrl-V (paste dialog) in Firefox 48, and they both work.

**Comment by gyphub** [comment]
I noticed this because I had added a shortcut:
Jupyter.keyboard_manager.edit_shortcuts.add_shortcut('Ctrl-t', 'jupyter-notebook:scroll-cell-top');

Ctrl-n is useful when using CodeMirror in Vim mode. It triggers completions and one can select from drop-down suggestions. (with Ctrl-p too, I think)

These three had worked fine until the update to Firefox 48, so I assumed Jupyter is capturing these shortcuts somehow.

**Comment by takluyver** [comment]
Aha, OK. If I run that line in the JS console, it also doesn't affect the shortcut, whereas it does if I use Ctrl-B instead. However, I get the same behaviour in Chromium, and it [appears they deliberately](https://bugs.chromium.org/p/chromium/issues/detail?id=33056) block overriding certain shortcuts like Ctrl-N and Ctrl-T. I haven't found any information about Firefox doing it, but I'd guess they've gone down the same route.

**Comment by gyphub** [comment]
Yes, turns out you are right.
https://bugzilla.mozilla.org/show_bug.cgi?id=1291706
