### ISSUE TITLE
Source maps in Chrome DevTools

### ISSUE THREAD

**Issue by gnestor** [jupyter/notebook#1668]
I'm trying to get source maps to work in Chrome Dev Tools. Here's what I've tried:
- Build the notebook: `npm run build:watch`
- Run the notebook: `jupyter notebook`
- Open in Chrome Dev Tools
- Add the notebook project directory to workspace
- Create network mapping (e.g. `notebook/static/notebook/js/notebook.js` to `localhost:8888/static/notebook/built/main.min.js`)

I've also tried fiddling with the Webpack config (the devtool option) and no luck...

**Comment by gnestor** [comment]
@Carreau Another thing: If I reload the page with devtools open, it loads a blank page and closes devtools. If I open devtools up again, it reads: "DevTools was disconnected from the page. Once page is reloaded. DevTools will automatically reconnect." Is anyone else experiencing this?

**Comment by blink1073** [comment]
We switched to `inline-source-map` in JupyterLab because it was misbehaving: https://github.com/jupyter/jupyterlab/blob/master/jupyterlab/webpack.conf.js#L20

**Comment by gnestor** [comment]
@blink1073 Thanks for the quick response! I tried that but I'm still not able to breakpoint within the source files, etc. Did you need to do networking mapping or anything else within devtools?

**Comment by blink1073** [comment]
Here's what I had (and I just realized I had source maps turned off, duh):

<img width="303" alt="screen shot 2016-08-09 at 1 17 10 pm" src="https://cloud.githubusercontent.com/assets/2096628/17528139/bfdb1a58-5e33-11e6-9fbe-2f8032c541f5.png">

**Comment by gnestor** [comment]
Ok I just upgraded to Chrome 52 and that fixed the devtools disconnecting on reload issue. I then [reset my devtools](http://stackoverflow.com/a/21911933/2217533) and re-mapped my network resources. I think you have to map your local resources to network resources in order to set breakpoints and debug files.

**Comment by Carreau** [comment]
> Ok I just upgraded to Chrome 52 and that fixed the devtools disconnecting on reload issue. I then reset my devtools and re-mapped my network resources. I think you have to map your local resources to network resources in order to set breakpoints and debug files.

Hum that's weird, I didn't had to map files... Happy this worked for you. maybe the disconnection is because you have a detached debugger window ? 

I'm reopening so that we write some of this process on the documentation at some point. 

Thanks both for investigating !

**Comment by gnestor** [comment]
I should say:
> I think you have to map your local resources to network resources in order to set breakpoints and debug *local* files.

Please correct me if I'm wrong, but I don't know how else devtools would know how network files (e.g. `webpack:///./notebook/static/notebook/js/notebook.js`) map to local files (e.g. `notebook/static/notebook/js/notebook.js`).

**Comment by Carreau** [comment]
Ok, yes, sure; make sens.
