### ISSUE TITLE
Handle MathML output

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#1670]
Follow on from #1565.

The mimetype for MathML appears to be `application/mathml+xml` ([source](https://www.w3.org/TR/MathML2/chapter7.html)).

**Comment by gnestor** [comment]
@takluyver I'd be happy to look into this. A couple questions:

* Where are mime types defined in this repo?
* Where are handlers for mime types defined?

**Comment by takluyver** [comment]
This file should be the most relevant one: https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/outputarea.js

**Comment by gnestor** [comment]
Thanks @takluyver! Here is an initial implementation https://github.com/jupyter/notebook/pull/1672.

**Comment by gnestor** [comment]
Merged with https://github.com/jupyter/notebook/pull/1672
