### ISSUE TITLE
Single config dir suggestion

### ISSUE THREAD

**Issue by klonuo** [jupyter/notebook#1679]
I hit this problem while trying to install custom nbextension. Previously I wasn't aware of complicated config folder structure in this already complex and diverse project.

I'd appreciate if someone suggest me how to use single folder (~/.jupyter) for all config/data/runtime etc folders. So I want to set all these to single location preferably w/o defining env variables.

Thanks

**Comment by takluyver** [comment]
You could configure the data dir and the runtime dir to be the same location as the config directory. The easiest way to do that is by setting environment variables (`JUPYTER_DATA_DIR` and `JUPYTER_RUNTIME_DIR`). But I wouldn't really recommend it: information that refers to the normal locations will be confusing, and if any tools assume the standard location without checking the environment variables, they won't work for you.
