### ISSUE TITLE
Create a keyboard shortcut to show Keyboard shortcuts

### ISSUE THREAD

**Issue by btzo** [jupyter/notebook#1684]
I was thinking about something simple, like typing <kbd> shift </kbd> + <kbd> / </kbd> , which is equivalent to type <kbd> ? </kbd> at the end, while in Commando Mode.

**Comment by Carreau** [comment]
Hi there, thanks for the proposal, we are aware that we need a better way to show shortcuts to users. 

Keyboard shortcuts being extremely scarce when using a browser, I'm worried it  would not such a good idea to reserve one more for this action. 

Note that on current master, the command palette (Ctrl-P) doe show the shortcut associated with each actions, and that the help menu now allows you to redefine your shortcuts. 

Jupyterlab now also introduce the shortcuts in the menu as well; so a shortcut to show shortcut seem a bit too much.

Technically I guess with the shortcut configurable you can define one one your own if you like, and there is also the chicken and egg problem; how do use fing the shortcut to shop the shortcut help...

What do you think ? Do you think the current development on master resolve some of what you are trying to propose ? Do you see any improvement on what's available ?

**Comment by gnestor** [comment]
+1 for using the command pallette.

Screenshot: 

![screenshot](http://g.recordit.co/9ORsJLordR.gif)

**Comment by mikebotazzo** [comment]
The command palette is very effective and should be added in the *User Interface Tour*, in my opinion. 
Despite this, I still consider adding the <kbd> ?  </kbd>  shortcut to show the *Keyboard Shortcut* menu pertinent. 

More than that, it could be interesting to emphasize the *open the command palette* option.

**Comment by ggrrll** [comment]
@mikebotazzo isn't' 'h' what you were looking for?   - maybe you can close this?
