### ISSUE TITLE
Upgrade codemirror in 4.x

### ISSUE THREAD

**Issue by jasongrout** [jupyter/notebook#1686]
Upgrading Codemirror in 4.x and releasing will help with https://github.com/jupyter/help/issues/71#issuecomment-240233633

**Comment by gnestor** [comment]
@jasongrout I'd be happy to work on this. What version do you suggest we upgrade to? Latest? And are you aware of any test notebooks that can be used to test all the different syntaxes?

**Comment by oxinabox** [comment]
Can we have the latest code mirror? `~5.21`

This has https://github.com/codemirror/CodeMirror/issues/4356

That will fix:

 -  https://github.com/JuliaLang/IJulia.jl/issues/484
 -  i.e. https://github.com/jupyter/jupyter/issues/214

**Comment by flying-sheep** [comment]
cool, that would also contain my [newer fixes in 5.20](https://github.com/codemirror/CodeMirror/commit/0e4c156a9ab63dcbc5fa9f60ada54e3c5d5ad03b)

**Comment by minrk** [comment]
Sure thing. 5.21 in #1921.
