### ISSUE TITLE
kernel.language_info probably doesn't match CodeMirror's

### ISSUE THREAD

**Issue by myyc** [jupyter/notebook#1689]
Apologies in advance if this is not an actual issue. I am a steady Jupyter/Python3 user, syntax has never been an issue until the `@` operator and the `f` string literal.

`get_ipython().kernel.language_info` shows I'm using Python 3; no idea to check which version `parserConf` is picking up but I am clearly seeing Python 2 highlighting.

This happens with the current master but not with 4.2.

**Comment by takluyver** [comment]
What does the whole of `language_info` say?

**Comment by myyc** [comment]
{'codemirror_mode': {'name': 'ipython', 'version': 3},
     'file_extension': '.py',
     'mimetype': 'text/x-python',
     'name': 'python',
     'nbconvert_exporter': 'python',
     'pygments_lexer': 'ipython3',
     'version': '3.6.0a4'}

It's the same with both versions.

**Comment by takluyver** [comment]
That all looks as I'd expect. `codemirror_mode` is what tells it the syntax highlighting to use. I see some bizarre effects with f-strings too (it acts as if the rest of the cell is an f-string). Maybe we need to upgrade the version of Codemirror we use.

**Comment by takluyver** [comment]
Upgrading Codemirror didn't help, but I think I found a bug in Codemirror for f-strings: codemirror/CodeMirror#4182.

To check if it's trying to use Python 3 syntax, put these three lines in a cell:

```python
raise
print
zip
```

If it's treating it as Python 3, `print` will be highlighted like `zip`. If it's treating it as Python 2, `print` will be highlighted like `raise`.

**Comment by myyc** [comment]
It's using python 2 as `@` doesn't get highlighted like `+`

**Comment by takluyver** [comment]
Right, but maybe that's a bug. I'm seeing that as well, even though the `print` test indicates that it's using Python 3 highlighting.

**Comment by myyc** [comment]
OK my bad. `print` does get highlighted like `zip`. The bug is definitely in Codemirror.

**Comment by takluyver** [comment]
Actually, thinking about it a bit more, I bet the `@` bug is ours. We define the 'ipython' mode, including redefining the operators here: https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/codemirror-ipython.js#L27

We need to update that for the `@` operator.

**Comment by takluyver** [comment]
The @ operator was fixed by #1763, and the `f` prefix should be fixed in Codemirror 5.18, which we use as of #1764.

**Comment by myyc** [comment]
Hey. This bug reappeared, `@` and `raise print zip` tests pass, but `f""` doesn't get parsed properly.

```
{'codemirror_mode': {'name': 'ipython', 'version': 3},
 'file_extension': '.py',
 'mimetype': 'text/x-python',
 'name': 'python',
 'nbconvert_exporter': 'python',
 'pygments_lexer': 'ipython3',
 'version': '3.6.0'}
```

**Comment by takluyver** [comment]
Annoyingly, we reverted to an old version of Codemirror to work around an issue with Safari. @gnestor and @minrk are keeping an eye on it so we can go back to a newer version of Codemirror at some point.

**Comment by myyc** [comment]
OK thanks! Is there a way to manually select a newer version for the time being?

**Comment by takluyver** [comment]
If you [install the notebook from source](http://jupyter-notebook.readthedocs.io/en/latest/contributing.html#setting-up-a-development-environment), you can select it by editing `bower.json` before you build it.

**Comment by myyc** [comment]
OK thanks exactly what I was looking for! Done, works as expected :)

**Comment by gnestor** [comment]
We're tracking this bug here: https://github.com/jupyter/notebook/issues/2037

**Comment by takluyver** [comment]
Thanks @gnestor :-)
