### ISSUE TITLE
Spacing in ol/ul in rendered markdown is still off

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#1691]
I know there was a bug that lead to no space between a paragraph and a list, but it still seems to be here in master. This is fixed now in JupyterLab, but I haven't been able to track down the difference.

JupyterLab (fixed):

<img width="426" alt="screen shot 2016-08-18 at 6 20 29 pm" src="https://cloud.githubusercontent.com/assets/27600/17795822/7edcadb6-6570-11e6-85c3-f641c18ef878.png">

notebook master:

<img width="325" alt="screen shot 2016-08-18 at 6 20 37 pm" src="https://cloud.githubusercontent.com/assets/27600/17795825/87564cae-6570-11e6-8182-356f2ea33435.png">

**Comment by gnestor** [comment]
@ellisonbg Can you share your markdown text here?

This is what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/512354/17796670/adfdbf5e-657f-11e6-8702-5c6df933a4dd.png)

**Comment by ellisonbg** [comment]
Are you running a dev version of Chrome? I am on latest Chrome stable. I will try again to make sure though...

**Comment by gnestor** [comment]
Ya, I'm using vanilla Chrome 52.

**Comment by ellisonbg** [comment]
OK, did an npm clean, etc, cleared cache and everything is fine. Sorry about the noise...closing
