### ISSUE TITLE
terminado not found

### ISSUE THREAD

**Issue by charleshauser** [jupyter/notebook#1696]
Hi

I'm running python3.4, and receive the error that terminado can't be found: 

charlesh@csbinf01:$ jupyter notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2953, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2939, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2966, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 635, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 943, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'terminado>=0.3.3' distribution was not found and is required by notebook

I upgraded terminado:  sudo pip3 install --upgrade terminado
and still get same error when I attempt to run jupyter notebook.

I installed jupyter using:
pip3 install jupyter

Charles

**Comment by takluyver** [comment]
It looks like you may have an old version of pip, which could be causing problems. I'd recommend that you upgrade pip and then reinstall notebook:

```
pip3 install --upgrade setuptools pip
pip uninstall notebook
pip install notebook
```

**Comment by charleshauser** [comment]
Thanks - progress
I ran the above and now have notebook running in terminal (not browser), but it requires activation of javascript. 
![screenshot](https://cloud.githubusercontent.com/assets/13242613/17833710/fe1b6c04-66ea-11e6-9510-19daaabe5885.png)

**Comment by charleshauser** [comment]
sorry - did not intend to close issue
Can you suggest how to activate JavaScript?

**Comment by charleshauser** [comment]
I think the problem is I have to ssh to get onto server that is running notebook

**Comment by takluyver** [comment]
The default browser it has found is a terminal browser, which won't be able to display the notebook. You can:

1. Set the environment variable $BROWSER to a graphical browser (e.g. Firefox)
2. Configure the notebook to use a different browser ([config docs](http://jupyter-notebook.readthedocs.io/en/latest/config_overview.html#notebook-server)).
3. If you're running the notebook server on a separate machine for the browser, start with `--no-browser` to skip opening the browser on launch. There's also a config option for this.

**Comment by charleshauser** [comment]
Great - that explains it.

Charles
