### ISSUE TITLE
Cannot access Jupyter, commands only recognize IPython3

### ISSUE THREAD

**Issue by evanbiederstedt** [jupyter/notebook#1698]
I've installed `jupyter` and `notebook` via `pip`, and I even use several languages with the Jupyter notebooks (R, Python, Julia, Scala, Haskell, etc.)

However, I don't understand how to stop using `ipython3 notebook` as the in-terminal command. Somehow, installing the other jupyter notebook software doesn't "override" this, and I don't see any paths in the bash file. 

With the command: `$ jupyter notebook`

I get the output: `-bash: jupyter: command not found`

**Comment by takluyver** [comment]
It's the `jupyter_core` package that provides the `jupyter` command. It should have been installed automatically as a dependency of notebook, but double check that it is. If it is, it may have installed the executable file to a location that's not on your default $PATH (e.g. a `--user` install on Linux puts it in `~/.local/bin`). If that's the case, you'll need to update PATH from a file like `~/.profile`.

**Comment by evanbiederstedt** [comment]
Right, figured out the issue. 

On Mac OSX 10.11.6, all installations via MacPorts are in `/opt/local/bin`. Users must specify which version of `jupyter` they are using, e.g. `jupyter-2.7 notebook` is the correct command. 

Feel free to close---apologies for the confusion.

**Comment by takluyver** [comment]
That's rather ugly. It shouldn't be necessary to install jupyter on each
Python version, because one jupyter installation can be told about multiple
python kernels.

**Comment by evanbiederstedt** [comment]
Agreed, but I think that's how MacPorts makes us play the game. 

I have nothing in my ` ~/.local/bin` except the default version of Python. Everything else is in `/opt/local/bin`.
