### ISSUE TITLE
multiprocess works in Ipython console but not in notebook

### ISSUE THREAD

**Issue by YassineAbdelouadoud** [jupyter/notebook#1703]
The following code works fine in Ipython console

```
from multiprocess import Process, Queue

def f(q):
    q.put('hello world')

q = Queue()
p = Process(target=f, args=[q])
p.start()
print q.get()
p.join()
```

but hangs at the line print q.get() in jupyter notebook. 

Configuration : Windows 10 64 bits, python 2.7.1.2, ipython 4.1.2, jupyter notebook obtained as part of anaconda 4.0.0 distribution, multiprocess 0.70.4

**Comment by takluyver** [comment]
Not sure what would do this, but multiprocessing in interactive interpreters on Windows is well known to be a bit dodgy.

**Comment by YassineAbdelouadoud** [comment]
Thanks for taking interest in this issue. I think you may have read the post a bit too fast : I am not using multiprocessing (I am well aware of its issues in interactive interpreter on Windows) but rather multiprocess, a fork of multiprocessing replacing pickle by dill for the serialization (see [http://stackoverflow.com/questions/27932987/multiprocessing-package-in-interactive-python](url) with the answer from the multiprocess author). This works very well in an ipython console (built-in multiprocessing does not) so I thought this would translate to the notebook but it does not. I guess that, if you could point me to differences between the ipython console and notebook interpreters, I might be able to find a workaround. BTW, this is not a critical issue, but rather a nice side benefit that I was hoping to get from going with multiprocess.

**Comment by minrk** [comment]
The main difference between the notebook and the terminal is that a tornado eventloop is running and some zmq sockets are listening. There are also some extra threads running for things like forwarding stdout, stderr.

**Comment by topsun888** [comment]
It should work under a main function of def __main__, otherwise the system does not know which is the main process and which is the subprocess.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for many months and no longer applies to recent notebook releases. Thanks! 🌻
