### ISSUE TITLE
Completion doesn't support click or scrolling using the scroll bar

### ISSUE THREAD

**Issue by dmadeka** [jupyter/notebook#1707]
When I try to click on any option below:

![image](https://cloud.githubusercontent.com/assets/7892382/17911556/14b0ea2a-695c-11e6-9d7b-618d20d11173.png)

The autocomplete div disappears. The same also happens if you try to scroll with the mouse. All the keyboard behavior seems consistent.

**Comment by dmadeka** [comment]
@jasongrout @SylvainCorlay Do you know where the code for this is? I can try to have a look

**Comment by gnestor** [comment]
@dmadeka I can verify that mouse scrolling does not toggle between suggestions (and I don't believe it is intended to). I can also verify that click to select a suggestion is working for me using Chrome on OS X. What browser/OS are you using?

See https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/completer.js for introspection/autocomplete code.

Screenshot:

![screenshot](http://g.recordit.co/KOY10nE4Qi.gif)

**Comment by jtpio** [comment]
Closing as selecting the scrollbar and clicking on selection with the mouse seems to be working as expected with the latest Notebook 7 release:
 
https://github.com/jupyter/notebook/assets/591645/fd414725-8f13-4fcf-a6e2-4cb4371fbd1e
