### ISSUE TITLE
Clarify that the best way to run a public server is via JupyterHub

### ISSUE THREAD

**Issue by fperez** [jupyter/notebook#1712]
Our docs mention [running a public server](http://jupyter-notebook.readthedocs.io/en/latest/public_server.html#running-a-public-notebook-server).  Now that JupyterHub exists, we should add a note in this section:

- [ ] pointing users to JupyterHub as the official way to run a public, multi-user server (and clarifying that it's *nix only).
- [ ] indicating that if they choose to run a public nb server in this fashion, it's still a *single user* process, and hence all who log into it are effectively sharing that same user, potentially colliding and overwriting each other.
- [ ] therefore, this should only be done by someone who wants remote access to their personal machine and who fully understands the limitations and security implications.

**Comment by michaelpacer** [comment]
#1713 closes this.
