### ISSUE TITLE
don't print full environment in error messages when starting a new kernel

### ISSUE THREAD

**Issue by jasongrout** [jupyter/notebook#1714]
We just had someone post an error log from starting up a kernel that had their full environment variables listed. This often can contain sensitive security-related information (like passwords, private tokens, etc.), so we shouldn't list all of their environment by default (maybe just their path, which is often relevant?). The problem is that people will try to be helpful and post their logs, not realizing that they contain sensitive information.

I think to reproduce this, modify a kernelspec so that it won't start, or points to a nonexistent file, and then try starting a new notebook. Look at the server logs for the "Failed to run command".

**Comment by jasongrout** [comment]
CC @minrk

**Comment by jasongrout** [comment]
(cf. https://github.com/jupyter/jupyterlab/issues/771)

**Comment by minrk** [comment]
Makes sense. I don't think we can reasonably do anything in between everything and just PATH, even though things like PYTHONPATH, etc. might be useful for Python kernels.
