### ISSUE TITLE
Jupyter hub shows python [conda root] and python [default ] as kernel names instead of python 3

### ISSUE THREAD

**Issue by aries89** [jupyter/notebook#1716]
I did try uninstalling nb_conda_kernels, but then the spawner started failing with a bad request error.

I also tried 
[root@jup-nr jupyteruser]# conda update nb_conda nb_conda_kernels nb_anacondacloud
Fetching package metadata .......
# All requested packages already installed.
# packages in environment at /opt/anaconda3:
#
nb_anacondacloud          1.2.0                    py35_0
nb_conda                  2.0.0                    py35_0
nb_conda_kernels          2.0.0                    py35_0

But I am still facing the same issue.

Can anyone please let me know the fix for this ?

**Comment by takluyver** [comment]
@damianavila ?

**Comment by damianavila** [comment]
Can you paste the output of `conda list`

How did you try to uninstall the conda packages?

Can you also provide the output of `jupyter nbextension list` and `jupyter serverextension list`

Thanks!

**Comment by aries89** [comment]
@damianavila 

[root@jup-nr ~]# jupyter serverextension list
config dir: /opt/anaconda3/etc/jupyter
    nbpresent  enabled
    - Validating...
      nbpresent  OK
    nb_conda  enabled
    - Validating...
      nb_conda  OK
    nb_anacondacloud  enabled
    - Validating...
      nb_anacondacloud  OK
[root@jup-nr ~]#


I used conda uninstall command.

**Comment by damianavila** [comment]
Let's try `conda remove _nb_ext_conf` (it will remove all the extensions but `conda remove nb_conda` should be the same because it removes all the extension bundle as well) and please post the output of `jupyter nbextension list` and `jupyter serverextension` list to see if they are disabled as expected.
Additionally the content of  `/opt/anaconda3/etc/jupyter/jupyter_notebook_config.json` to see if nb_conda_kernel reference was removed.

Thanks!

**Comment by aries89** [comment]
[root@jup-nr ~]# jupyter nbextension list
Known nbextensions:
  config dir: /root/.jupyter/nbconfig
    notebook section
      config/config_menu/main  enabled
      - Validating: OK
      toc/main  enabled
      - Validating: OK
      sidebar/main  enabled
      - Validating: OK

	  
[root@jup-nr ~]# jupyter serverextension list
[root@jup-nr ~]#

./opt/anaconda3/pkgs/_nb_ext_conf-0.3.0-py35_0/etc/jupyter/jupyter_notebook_config.json


{
  "NotebookApp": {
    "kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager",
    "nbserver_extensions": {
      "nb_conda": true,
      "nb_anacondacloud": true,
      "nbpresent": true
    }
  }
} 

./opt/anaconda2/pkgs/_nb_ext_conf-0.3.0-py27_0/etc/jupyter/jupyter_notebook_config.json

{
  "NotebookApp": {
    "nbserver_extensions": {
      "nbpresent": true,
      "nb_conda": true,
      "nb_anacondacloud": true
    },
    "kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager"
  }
}

./opt/anaconda2/etc/jupyter/jupyter_notebook_config.json


{
  "NotebookApp": {
    "nbserver_extensions": {
      "nbpresent": true,
      "nb_conda": true,
      "nb_anacondacloud": true
    },
    "kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager"
  }
}

**Comment by damianavila** [comment]
`./opt/anaconda2/etc/jupyter/jupyter_notebook_config.json`

Do you have anaconda2 installed alongside with anaconda3?

In any case, if you start jupyterhub in your anaconda3 env, I don't see how this could affect unless the Spawner is using notebook server from the anaconda2 env (although I did not play to much with jupyterhub yet and maybe I am missing something else). 

What happens if you remove the extensions from the anaconda2 installation as well?

**Comment by jzf2101** [comment]
I'm having similar issues from switching from python2 to python3

**Comment by damianavila** [comment]
> I'm having similar issues from switching from python2 to python3

What do you mean? For instance you don't need anaconda2 to have python2 kernels... can you clarify how is your setup? Thanks!

**Comment by aries89** [comment]
[root@jup-nr ~]# /opt/anaconda2/bin/jupyter nbextension list
Known nbextensions:
  config dir: /root/.jupyter/nbconfig
    notebook section
      sidebar/main  enabled
      - Validating: OK
      config/config_menu/main  enabled
      - Validating: OK
      toc/main  enabled
      - Validating: OK
[root@jup-nr ~]# /opt/anaconda2/bin/jupyter serverextension list
[root@jup-nr ~]#

It works fine now. I can see the kernels as R, Python 2 and Python3.

So just to summarize

I would need to do the following to fix the issue right ?
/opt/anaconda2/bin/conda remove _nb_ext_conf
/opt/anaconda3/bin/conda remove _nb_ext_conf

Did I miss any step ?

**Comment by aries89** [comment]
Does the remove command affect user defined jupyter notebook extensions ?

**Comment by damianavila** [comment]
> Did I miss any step ?

I think you are OK now... interesting to see that you have both anaconda installed alongside... curious about the setup and why you put them together...

> Does the remove command affect user defined jupyter notebook extensions ?

Removing _nb_ext_conf will remove the extensions provided by default by Anaconda but it should not affect other jupyter extensions defined by the user...

**Comment by aries89** [comment]
Thanks.

Would I have to always run the remove command or in the next jupyter updates this issue would be fixed?

**Comment by damianavila** [comment]
>Would I have to always run the remove command or in the next jupyter updates this issue would be fixed?

The Anaconda distribution is shipping some nbextensions by default. So anytime you use Anaconda, if you don't want those extension, you need to remove it.
But, just to be clear, this is something specific from Anaconda. 
You can always have the native jupyter experience, creating new environments with just the notebook on it, removing the extensions as I mentioned before or using other alternatives installations as the Jupyter docs explain in details.

Cheers.

**Comment by laurikoobas** [comment]
Just to follow up on this - the "conda remove _nb_ext_conf" command output is scary..

```
$ conda remove _nb_ext_conf
Fetching package metadata .......
Solving package specifications: ..........

Package plan for package removal in environment /opt/anaconda3:

The following packages will be REMOVED:

    _nb_ext_conf:     0.3.0-py35_0
    anaconda:         4.2.0-np111py35_0
    ipywidgets:       5.2.2-py35_0
    jupyter:          1.0.0-py35_3
    nb_anacondacloud: 1.2.0-py35_0
    nb_conda:         2.0.0-py35_0
    nb_conda_kernels: 2.0.0-py35_0
    nbpresent:        3.0.2-py35_0

```

It seems like removing jupyter and ipywidgets and.. anaconda itself(?) would have a detrimental effect on the whole jupyter notebook experience.

**Comment by takluyver** [comment]
I remember being confused by similar things. `jupyter` and `anconda` are *metapackages*: they contain no (or very little) code themselves, but they depend on a lot of other packages, so you can conveniently install a bunch of things by doing `conda install jupyter`. So removing them is not actually as big a problem as it sounds.

**Comment by damianavila** [comment]
@laurikoobas see my comment here: https://github.com/jupyter/notebook/issues/1805#issuecomment-251237272

**Comment by damianavila** [comment]
@takluyver, I think this can be closed, the thread have enough information for anyone hitting the same issue/question. Thanks!

**Comment by diego898** [comment]
Maybe I missed something, but I just have anaconda3 installed, and still see two kernel entries for conda root, and default as opposed to just python 3. I can't seem to parse here or on #1805 

1. why this is the case (seems to be 'an extension'?) and 
2. how to prevent it on a new install? I teach a lot of new users with ipython+anaconda and this is another major source of confusion.
3. how to correct it on an existing install, without removing all extensions?

**Comment by damianavila** [comment]
> why this is the case (seems to be 'an extension'?) and

Yes, it is the nb_conda_kernels extension that provide kernelspec on the fly for your conda envs: https://docs.continuum.io/anaconda/jupyter-notebook-extensions#notebook-conda-kernels

>how to prevent it on a new install? I teach a lot of new users with ipython+anaconda and this is another major source of confusion.

This is shipped by default with Anaconda, you can create one environment with the plain jupyter to have the native experience, or alternative, remove the extension from your root environment with `conda remove nb_conda_kernels`. Notice this will also remove other extension provided with Anaconda and listed here: https://docs.continuum.io/anaconda/jupyter-notebook-extensions# 

>how to correct it on an existing install, without removing all extensions?

You can disabling instead of removing the extension, see this link: https://docs.continuum.io/anaconda/jupyter-notebook-extensions#uninstall (check the second paragraph, not the removal of nb_conda).

Hope this helps!
