### ISSUE TITLE
Terminal unavailable in Jupyter Notebook

### ISSUE THREAD

**Issue by piltu007** [jupyter/notebook#172]
Hi,
I am running Jupyter in Chrome browser on Windows 8.1PC. I can't open a terminal in the notebook. Is it possible to open a terminal in notebook on Windows? If possible, please help.

**Comment by rgbkrk** [comment]
I'm afraid not. The terminal is only supported on *nix machines (Linux, OS X, FreeBSD).

**Comment by ellisonbg** [comment]
This is because Windows does not have TTY based terminal support.

On Thu, Jun 25, 2015 at 2:06 PM, Kyle Kelley <notifications@github.com>
wrote:

> I'm afraid not. The terminal is only supported on *nix machines (Linux, OS
> X, FreeBSD).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/172#issuecomment-115398608>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by piltu007** [comment]
Okay, thanks.

**Comment by AlbinB** [comment]
is it possible to get it working wiht PuTTY?

**Comment by ph03** [comment]
Or cygwin?

**Comment by michaelsbradleyjr** [comment]
[winpty](https://github.com/rprichard/winpty) might be a viable option, as well.

**Comment by takluyver** [comment]
We've looked at winpty. It might do what's necessary, but take a look at the instructions to build it - "Winpty requires two g++ toolchains...". We definitely don't want to support or recommend something that complex.

I think the best hope for this is that apparently Microsoft put an ssh server for powershell into Windows 10. I'm not exactly sure how that works, but if it's robust, we might be able to use it. Has anyone tested that out? What do you have to do to get it to work? Can you e.g. run the Python shell inside it?

**Comment by Zhang-O** [comment]
I have tried a lot of ways including installing lots of modules ,and all failed.
oh,I want a pc of macos .

**Comment by moonclearner** [comment]
installed terminado can't fix

**Comment by Zhang-O** [comment]
now i suggest you to install anaconda,not terminado.it installs with a lot of pakages which will save you much time and miss a lot of pakage error.

**Comment by glyphx** [comment]
I got it to work on windows 10, mingw, visual studio 2015. 
![image](https://cloud.githubusercontent.com/assets/3673651/22023558/a5ef7a3c-dc94-11e6-9936-23f486abcf94.png)

**Comment by timjavins** [comment]
Microsoft put a bash terminal in Windows 10 (or rather, an easy way to install Ubuntu inside Windows 10).
1. Turn on Developer Mode
![image](https://user-images.githubusercontent.com/7596365/27806698-e7ab4034-5ff0-11e7-9e4c-4b1e7db19b1b.png)

2. Run Command Prompt as Admin or PowerShell as Admin

3. type `bash` and hit [enter], which will install Ubuntu
![image](https://user-images.githubusercontent.com/7596365/27806744-3b2a1744-5ff1-11e7-8a10-942cc122e351.png)
![image](https://user-images.githubusercontent.com/7596365/27806782-7b0927a6-5ff1-11e7-85a1-78660e9a2eb7.png)

4. reboot

5. Inside the Windows terminal/PowerShell/whatever, type `bash` to switch
![image](https://user-images.githubusercontent.com/7596365/27807150-dc51ae0a-5ff3-11e7-8c8b-efa7270681a5.png)

Proof:
![image](https://user-images.githubusercontent.com/7596365/27807255-88636800-5ff4-11e7-9d9b-b899d5f03999.png)

I provide this as a resource for anyone who is trying to get a Jupyter terminal to run "inside Windows". I'm now going to see if I can get my Jupyter terminal to become available and perhaps (eventually) get Anaconda for Windows to launch it. It is open source, after all. ;)

**Comment by takluyver** [comment]
I think that if you install Anaconda for Linux inside the Ubuntu environment and launch Jupyter notebook from there, terminals should work.

We've had a couple of reports of issues running Jupyter inside the Ubuntu-on-Windows environment. They may be resolved now; I haven't kept track of them.

**Comment by fenderrex** [comment]
so still no GPU support is that right? ill try tty with winpty. so many dependencys

**Comment by takluyver** [comment]
@andfoy was doing some work on a Windows backend at https://github.com/jupyter/win-tornado-terminals . I don't know how far along that is.

**Comment by Oaklight** [comment]
Since now in Windows10 there is OpenSSH built-in, if it possible to make the terminal work?

**Comment by swap2ag** [comment]
Installing winpty package fixed the problem for me in windows 10. Install it by-
`conda install winpty`

It opens windows powershell when terminal is opened as shown in the figure below-
![jupyter terminal for windows 10](https://user-images.githubusercontent.com/26693005/83975717-d833cb80-a912-11ea-8e70-61d77f6c17a5.PNG)

**Comment by weiscloud** [comment]
I soved this problem according to this video [https://youtu.be/d1NK83vve6c](url)
