### ISSUE TITLE
Custom path to MathJax not working

### ISSUE THREAD

**Issue by juhasch** [jupyter/notebook#1721]
If I specify the MathJax url in `jupyter_notebook_config.py` using
```Python
c.NotebookApp.mathjax_url = '/static/components/mathjax/mathjax.js'
```
MathJax will not work, even though it is the built-in MathJax version of Jupyter.
I don't get an error message when loading a notebook (I would get one if MathJax itself is not found).
But I do get errors like
```
[W 09:26:07.328 NotebookApp] 404 GET /extensions/MathMenu.js?rev=2.6.1 (127.0.0.1) 9.00ms referer=http://127.0.0.1:8888/
notebooks/test.ipynb
[W 09:26:08.526 NotebookApp] 404 GET /extensions/MathZoom.js?rev=2.6.1 (127.0.0.1) 8.00ms referer=http://127.0.0.1:8888/
notebooks/test.ipynb
```
So it looks like there is a wrong path here. Any ideas what is going on here ?

This is with notebook 4.2.1 and Python3 using Anaconda under Windows.

**Comment by takluyver** [comment]
If you look at the source of the page in the browser, what does the `<script>` tag loading Mathjax have for the `src` URL?

**Comment by juhasch** [comment]
Without `c.NotebookApp.mathjax_url`:
```
<script type="text/javascript" src="/static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured" charset="utf-8"></script>

<script type="text/javascript">
// MathJax disabled, set as null to distingish from *missing* MathJax,
// where it will be undefined, and should prompt a dialog later.
window.mathjax_url = "/static/components/MathJax/MathJax.js";
</script>
```

With `c.NotebookApp.mathjax_url = '/static/components/mathjax/mathjax.js'`:
```
<script type="text/javascript" src="/static/components/mathjax/mathjax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured" charset="utf-8"></script>

<script type="text/javascript">
// MathJax disabled, set as null to distingish from *missing* MathJax,
// where it will be undefined, and should prompt a dialog later.
window.mathjax_url = "/static/components/mathjax/mathjax.js";
</script>

```

**Comment by takluyver** [comment]
So that looks like it is taking effect correctly in the template. Maybe we need to do something else to set where it loads extensions from?

**Comment by juhasch** [comment]
It is strange.
Works: `c.NotebookApp.mathjax_url = '/static/components/MathJax/MathJax.js'`
Works: `c.NotebookApp.mathjax_url = '/static/components/mathjax/MathJax.js'`
Does not work: `c.NotebookApp.mathjax_url = '/static/components/mathjax/mathjax.js'`

So I guess this is a MathJax issue rather than a Jupyter notebook issue.

**Comment by takluyver** [comment]
Aha, I bet it's looking for `MathJax.js` at the end when constructing the path to extensions.

**Comment by juhasch** [comment]
Yes, looks like you are right. Now it is working :-)
