### ISSUE TITLE
Web terminals are not being rendered properly

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#1724]
Ping @yuvipanda who was working on this. I just tried opening a terminal in the web interface on master, and got this:

![screenshot from 2016-08-31 15-47-27](https://cloud.githubusercontent.com/assets/327925/18133419/6d614cfa-6f92-11e6-9bb6-1de77dc2b04a.png)

**Comment by takluyver** [comment]
Unfortunately not fixed by #1701. I've replicated this in Firefox and Chromium, rebuilt the JS (`python setup.py css js`) and ensured that it's not browser caching.

**Comment by blink1073** [comment]
We had to update some CSS in JupyerLab to accommodate the version change: https://github.com/jupyter/jupyterlab/pull/800

**Comment by yuvipanda** [comment]
Interestingly, this seems to be happening no matter which version I set it to, even 0.33.0.

**Comment by yuvipanda** [comment]
nvm, git bisect tells me it happened in the bump to 1.0. investigating.

It's strange, since I'm running it with 1.0 in paws.wmflabs.org and it works fine...

**Comment by yuvipanda** [comment]
@takluyver can you try https://github.com/yuvipanda/notebook/tree/fix-xtermjs?
