### ISSUE TITLE
Initialized events not being caught on custom.js on 4.2.2

### ISSUE THREAD

**Issue by lgfa29** [jupyter/notebook#1730]
Hi,

I am having an issue with version `4.2.2` where my `custom.js` file needs to listen for the `app_initialized.NotebookApp` event and do some work.

Until `4.2.1` this always worked, but after the update it seems like the order how things are loaded changed, so the event is being fired before `custom.js` is loaded.

I tried listening for `notebook_loaded.Notebook ` as well, but I had the same issue.

**Version:** 4.2.2
**Steps to reproduce**

- create a `~/.jupyter/custom/custom.js` file with:
```js
define(['base/js/events'], function(events) {

    console.log('loaded custom.js');

    events.on('app_initialized.NotebookApp', function() {
        console.log('app_initialized.NotebookApp fired');
    });

    events.on('notebook_loaded.Notebook', function() {
        console.log('notebook_loaded.Notebook fired');
    });
});
```

- start Jupyter
- open a notebook
- check the browser console

**Expected result**
Up until `4.2.1` you would see this:
<img width="776" alt="screen shot 2016-09-01 at 12 13 12 pm" src="https://cloud.githubusercontent.com/assets/775380/18175109/0530e044-703e-11e6-92c9-10466d3a6e63.png">

But on `4.2.2` we get this:
<img width="775" alt="screen shot 2016-09-01 at 12 11 57 pm" src="https://cloud.githubusercontent.com/assets/775380/18175131/16b3158a-703e-11e6-8094-90ec77b8fa1f.png">

**Comment by minrk** [comment]
Thanks for the report! A fix meant to catch errors in custom.js (#1378) ended up moving the load time to a later point, which will be definitely after app_initialized and *possibly* after notebook_loaded (it generally still sees notebook_loaded for me). #1732 should catch errors in a way that doesn't delay custom.js loading.

**Comment by lgfa29** [comment]
Thanks @minrk! Just tested your fix and confirmed it works.

**Comment by gnestor** [comment]
Closed with https://github.com/jupyter/notebook/pull/1732
