### ISSUE TITLE
Mathjax blocks are not highlighted correctly in 4.2.2

### ISSUE THREAD

**Issue by randy3k** [jupyter/notebook#1733]
The math equations inside `$$ $$` are not highlighted.

![screen shot 2016-09-02 at 2 08 41 pm](https://cloud.githubusercontent.com/assets/1690993/18213552/c8741f20-7116-11e6-893e-b082dd61c3e1.png)

By interestingly, `\[ \]` is highlighted but not rendered.

![screen shot 2016-09-02 at 2 10 03 pm](https://cloud.githubusercontent.com/assets/1690993/18213588/f72997a0-7116-11e6-9674-1a9808938bf3.png)

![screen shot 2016-09-02 at 2 10 16 pm](https://cloud.githubusercontent.com/assets/1690993/18213596/feaf844e-7116-11e6-8fb7-326537ca3872.png)
# 

The version of the notebook server is 4.2.2 and is running on:
Python 3.5.2 | packaged by conda-forge | (default, Jul 26 2016, 01:32:08) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

**Comment by michaelpacer** [comment]
This is probably related to differences between the code mirror lexer and the underlying JSON parser:

Code mirror probably expects standard LaTeX formatting, which \[…\] is(technically you aren't supposed to use $$…$$ if you're writing LaTeX as it is a classic TeX command that has nonstandard spacing… which I'm guessing has been explicitly excluded from activating highlighting for that reason.) 

However js sees \[ as just escaping the [ so it won't render, but \\[ … \\]will. I guess this would qualify as a bug but I don't know if the place to fix it is on the Jupyter end… it might be I'm just not sure.

**Comment by randy3k** [comment]
If I am correct, Mathjax uses `$$ ... $$` in default.

**Comment by gnestor** [comment]
https://github.com/jupyter/notebook/pull/1757 fixes an issue regarding CodeMirror config for text (markdown and raw) cells. I've tested and syntax highlighting is working for math inside of `$` brackets but still not for `$$` brackets. The question is: was highlighting of math inside of `$$` brackets ever supported? @minrk Do you know?
