### ISSUE TITLE
[Feature] Multiselection/Multicursor

### ISSUE THREAD

**Issue by hellpanderrr** [jupyter/notebook#174]
Is there any documentation for this thing? I stumbled upon it by accident and found only a discussion in the CodeMirror repository.
![bandicam 2015-06-26 19-14-07-408](https://cloud.githubusercontent.com/assets/2708297/8382078/b44a1240-1c38-11e5-8b2e-b2f8ab661235.gif)
(it's Alt for multiline selection and Ctrl for multicursors)

**Comment by Carreau** [comment]
This is a [codemirror](http://codemirror.net/doc/manual.html) thing, you have to search codemirror manual, we do not do anything specific for that to happen.

**Comment by takluyver** [comment]
We probably do want to eventually document things like this somewhere - we shouldn't expect end users to work out what JS text editor we're using and go and look up its documentation. But I don't think we really have the bandwidth to do that at the moment.

Consider it a hidden bonus feature ;-)

**Comment by Carreau** [comment]
Once we upgrade to codemirror 5.4 we can just point user to Cm docs.
