### ISSUE TITLE
Docs don't specify the actual path where `custom.js` is supposed to go

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/notebook#1741]
The docs don't say where the `custom.js` file is, just that it is in the "Jupyter dir" but that could mean a few different things. 
https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/JavaScript%20Notebook%20Extensions.ipynb

I think this should be replaced with saying the `custom.js` file is to be found at `~/.jupyter/custom/custom.js`, but that I wasn't sure if that is platform agnostic.

**Comment by dvigneshwer** [comment]
![image](https://cloud.githubusercontent.com/assets/5075497/18266447/60dc5ef2-7438-11e6-84df-6abac0ccf221.png)

There is no custom folder in my config directory, How do I generate it ?
