### ISSUE TITLE
Markdown cells no longer soft wrap lines in master

### ISSUE THREAD

**Issue by fonnesbeck** [jupyter/notebook#1743]
After updating notebook with the current master this evening, I noticed that markdown cells no longer soft wrap long lines. This makes it very difficult to edit markdown cells. This occurs both with Safari and Chrome.

![screen shot 2016-09-05 at 8 25 51 pm](https://cloud.githubusercontent.com/assets/81476/18259214/2f0186c8-73a7-11e6-9e27-b5eeb7b7b1eb.png)

Running 5.0.0.dev on OS X 10.12 and Python 3.5.

**Comment by fonnesbeck** [comment]
Am I the only one seeing this? I noticed also that the Markdown syntax highlighting has disappeared.

**Comment by minrk** [comment]
I see the same thing. Not sure what happened.

**Comment by minrk** [comment]
https://github.com/jupyter/notebook/pull/1676/commits/14089ce13941cc110a37993a700b1e1d242baf3d seems to have disabled the mechanism for loading the markdown cell default codemirror config.

**Comment by minrk** [comment]
Seems to be fixed by #1757
