### ISSUE TITLE
Errors on Read the Docs build after recent PR

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#1746]
After #1742 Read the Docs is now erroring:

https://readthedocs.org/projects/jupyter-notebook/builds/4374465/

**Comment by willingc** [comment]
Receiving json error when trying to open the changed notebook. Notebook will not open.

**Comment by willingc** [comment]
So the error was that there were two versions of Python listed in the "metadata" https://github.com/jupyter/notebook/pull/1742/commits/ec632df150309c3c7ba861fdaae8bcdb0d75c8ed#diff-dd2b9f636222197ec2b761794b5dfc1dR600

Removing one of the versions solves the build problem. What's odd is that the "metadata" saved the second version and "anaconda cloud" a few lines before (bug?).

cc/ @minrk @michaelpacer

**Comment by michaelpacer** [comment]
Is there a way to get Travis to include a docs build as part of the testing suite? If so, we might want to incorporate that so there are fewer cases of tiny changes breaking docs builds that require entirely new PRs.

**Comment by willingc** [comment]
I've done Travis builds for docs on other projects. I haven't done it with notebooks in docs but I agree it would be good to have the docs build tested.
