### ISSUE TITLE
Add docs testing to Travis

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#1749]
Based on discussion with @michaelpacer in #1746 and #1748, it would be a good idea to add docs to the testing that is done by Travis on each PR. We do this currently on nbgrader.

**Comment by gnestor** [comment]
@willingc Let me know how I can help!

**Comment by captainsafia** [comment]
I'm helping @jiaqi216 with this at W/S/C!

**Comment by jzf2101** [comment]
I tried assigning you @jiaqi216 but I couldn't figure out how to do it

**Comment by takluyver** [comment]
Thanks @captainsafia and @jiaqi216!

@jzf2101 I think you can only assign someone who's a member of the Github organisation; it's an unfortunate limitation in Github's design.
