### ISSUE TITLE
Enhancement - Is it possible to add highlighting of selected characters in the notebook?

### ISSUE THREAD

**Issue by toasteez** [jupyter/notebook#1751]
Is it possible to add highlighting of multiple occurrences of selected characters in the notebook?

e.g. if I highlight a variable of xyz all occurrences of xyz are highlighted in yellow in the notebook.

**Comment by gnestor** [comment]
You can accomplish this by using Chrome's Find feature:

![image](https://cloud.githubusercontent.com/assets/512354/18453589/d89eceb4-78f4-11e6-851f-225252fa1ead.png)

**Comment by gnestor** [comment]
There is also a Jupyter Notebook extension that does exactly this: https://github.com/jcb91/jupyter_highlight_selected_word

**Comment by Brambor** [comment]
Now, to disable jupyter find feature to use Chrome find feature I found this thread useful:
https://superuser.com/questions/1407209/how-can-i-disable-searching-in-a-jupyterlab-cell
