### ISSUE TITLE
separate edit and view links

### ISSUE THREAD

**Issue by minrk** [jupyter/notebook#1752]
Some files, e.g. `.html` files, can logically be both viewed (via `/files/`) and edited (via `/edit/`). Currently, we have just the one link that goes to `/edit/` or `/files/`, depending on the file type. We don't currently have separate links to these to URLs for files, but we probably should.

One option is to add view, edit to the list of actions along with delete, rename. Another is to add the links inline, perhaps on hover.

JupyterLab doesn't have this issue since it has an Open With... dialog, so if we take much longer to get around to this one, pointing to JupyterLab may end up being the solution.

I know this has been discussed a few places, but I can't find a dedicated issue for it, so opening here. If someone finds a duplicate, we can close this one.

cc @dsblank for interest, @ellisonbg for UI

**Comment by takluyver** [comment]
This is in progress in #1905, but we have identified a security concern with viewing HTML files, so we're bumping it to 5.0.
