### ISSUE TITLE
IPython with Django

### ISSUE THREAD

**Issue by venkateshpatil1** [jupyter/notebook#1756]
I'm new to jupyter/ipython and django. I have Django 1.9.5 installed on Ubuntu 16.04 and my application is running fine. I want to configure iPython(version 5.1.0) to be used with my Django application. Basically trying to call the iPython notebook (browser) from django which later can be used extensively in the application through a user interface.

When I try to run the command below

$./manage.py shell_plus --notebook

I get an error:

[W 13:46:39.247 NotebookApp] Unrecognized JSON config file version, assuming version 1
[I 13:46:41.082 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 13:46:41.114 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 13:46:41.399 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 13:46:41.399 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 13:46:41.409 NotebookApp] [nb_conda] enabled
[I 13:46:41.507 NotebookApp] [nb_anacondacloud] enabled
**CommandError: No notebook (Python) kernel specs found**

To resolve this I tried: ipython2 kernelspec install-self --user

Under home directory .local/share/jupyter/kernels folder there is a kernel.json file

I'm not sure why I'm still getting the same error. Any suggestion will be very helpful in resolving this issue. Thank you.

To achieve launching iPython notebook from Django I tried the following:

>>Installed the django-extensions: pip install django-extensions
>>In django settings.py file added the line django_extensions to INSTALLED_APPS
>>Ran ipython profile create and uncommented this line :  c.InteractiveShellApp.extensions = ['django_notebook']

**Comment by takluyver** [comment]
@damianavila - sounds like the conda kernels thing might be interfering here.

**Comment by venkateshpatil1** [comment]
Hi Thomas Kluyver,
Is there anything that you see I might be missing in my settings for django with IPython. 
Thanks,
Venkatesh Patil

**Comment by takluyver** [comment]
Nothing that I see, but I don't know Django.

**Comment by venkateshpatil1** [comment]
I'm not sure why I get the error : CommandError: No notebook (Python) kernel specs found
when Under home directory .local/share/jupyter/kernels folder there is a kernel.json file

**Comment by takluyver** [comment]
`kernel.json` should be another level down, inside a folder with the kernel name. I.e.

```
$ ls ~/.local/share/jupyter/kernels/python3/
kernel.json
```

**Comment by venkateshpatil1** [comment]
Sorry, It is under python2 folder: 
~/.local/share/jupyter/kernels/python2/kernel.json

**Comment by takluyver** [comment]
Then I'd guess it is the conda kernels thing interfering. Pinging @damianavila again.

**Comment by damianavila** [comment]
Sorry to be late... @venkateshpatil, I don't know how Django work with the notebook, but as a preventive measure, you can disable the nb_conda_kernels and the other extensions, or alternative, remove them.
See this section for more info: https://docs.continuum.io/anaconda/jupyter-notebook-extensions#uninstall

I can not debug your scenario now, but at least what I referenced above would help you to keep working... if the nb_conda_kernels is the interfering thing... 

Let's us know how it goes.

Cheers.

**Comment by venkateshpatil1** [comment]
Hi Damian,
Thank you so much for your suggestion. It worked now after uninstalling the extensions.
$ python manage.py shell_plus --notebook
[I 09:09:19.586 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 09:09:19.831 NotebookApp] Serving notebooks from local directory: /home/venkateshpatil1/data-platform/data-platform/SourceCode
[I 09:09:19.832 NotebookApp] 0 active kernels
[I 09:09:19.832 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 09:09:19.833 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 09:09:19.833 NotebookApp] No web browser found: could not locate runnable browser.
[I 09:10:56.789 NotebookApp] 302 GET / (::1) 3.85ms
[I 09:11:21.718 NotebookApp] Creating new notebook in
[I 09:11:23.978 NotebookApp] Kernel started: 61acd360-64fd-423e-85c3-c41e2ef725b1
[I 09:13:23.901 NotebookApp] Saving file at /Untitled.ipynb
[I 09:17:23.889 NotebookApp] Saving file at /Untitled.ipynb

**Comment by damianavila** [comment]
@venkateshpatil1 thanks for the report. Eventually, it would be nice to research into the issue but, for now, glad you have it working. @takluyver, I think you can close this one for now.

**Comment by takluyver** [comment]
Thanks Damian :-)
