### ISSUE TITLE
Terminal styles broken on master?

### ISSUE THREAD

**Issue by gnestor** [jupyter/notebook#1758]
The terminal styles are broken (for me) on master.

To reproduce:

1. Run notebook
2. Create a new terminal

Screenshot:

![image](https://cloud.githubusercontent.com/assets/512354/18444996/5a68dc66-78d0-11e6-9fb0-44fbd1e1defa.png)

**Comment by gnestor** [comment]
@Carreau @minrk Can you reproduce?

**Comment by minrk** [comment]
Yup, I see this, too. Maybe related to the recent xterm change?
