### ISSUE TITLE
Jupyter Notebook: Permission denied after changing Windows 7 user password

### ISSUE THREAD

**Issue by JRocki** [jupyter/notebook#1761]
I am receiving an error: Permission denied: path\notebook.ipynb, when I try to save my notebook.  I have already checked a notebook into Perforce 5 previous times with no issues, so I do not believe that this error is because of Perforce.  The only recent change I have made on my computer was changing the user login password.  I am using Windows 7 and using Anaconda.  I have seen similar questions about about the permission denied error, but they do not fit my current issue.

Is there a fix/work around/override?

**Comment by gnestor** [comment]
Have you checked the access permissions of the notebook file or parent directory? The "permission denied" error message is the result of an `EPERM` or `EACCES` error: https://github.com/jupyter/notebook/blob/6dcfc4d35284eee9ce3e39e1d04d469ce7c2614d/notebook/services/contents/fileio.py#L232

**Comment by JRocki** [comment]
I found in my directory there was a copy of the notebook, MyCode.ipynb, that appeared as .~MyCode.ipynb.  I don't know what the prefix .~ means.  There was also checkpoint file.  I deleted both the file with the .~ and the checkpoint and it now seems to work.

Thanks for responding to my question.  If you happen to know what was going on, I'd still be interested in finding out.

**Comment by gnestor** [comment]
@minrk Do you know about `.~notebook.ipynb` files?

**Comment by JRocki** [comment]
No, I'm still pretty new to Jupyter, although I really like it.

**Comment by minrk** [comment]
`.~` is the autosave intermediate, which will only be left on-disk if autosave fails to write the actual intended file. The prefix is chosen as one that is known to be ignored by some things like dropbox.

**Comment by JRocki** [comment]
Interesting, that file must have been conflicting with my save permissions.  Appreciate the help!

**Comment by gnestor** [comment]
@minrk Thanks for clarifying!

@JRocki Feel free to close this if the issue is resolved.
