### ISSUE TITLE
Can't rename the filename in Jupyter notebook.

### ISSUE THREAD

**Issue by Akelio-zhang** [jupyter/notebook#1762]
Here is the message from Chrome.
![image](https://cloud.githubusercontent.com/assets/10846194/18462703/3afb4fca-79b7-11e6-86f1-71320648eb59.png)

**Comment by minrk** [comment]
That's very strange indeed. What OS? What do you get from `pip list` or `conda list` in the environment where the notebook server is running?

Is the notebook server running locally, or do you have a remote server?

**Comment by gnestor** [comment]
@minrk If the server is running locally, could the invalid header be inspected in the server's logs?

**Comment by Akelio-zhang** [comment]
@minrk The notebook is running locally and I get it from `pip list`. My PC OS is Windows 8.1. And I tried to rename the file on IE11, but it did not work well either.

**Comment by minrk** [comment]
There should be an error in the logs. What's strange is that I couldn't find the error message in either the tornado or Jupyter source, so I don't know what is producing it. Perhaps a proxy?

**Comment by Akelio-zhang** [comment]
I can't find the error in CMD log, either. 
I'm not a professional programmer but a student who uses it for something interesting. What else can I offer to fix this problem?

**Comment by minrk** [comment]
It seems like it has to be something in between your browser and the server. Does restarting the notebook server work? Can you save *any* notebooks at all, in any browser?

Do you have any proxy configuration, firewall, or AV software running? If so, you might try temporarily disabling it to see if that is the culprit.

**Comment by Akelio-zhang** [comment]
I find the answer ---- I delete hosts then I can rename in browser. The host file change IP for localhost, I think.
Now notebook works well. Thank you for your help.

**Comment by gnestor** [comment]
@Akelio-zhang Great! Feel free to close 👌

**Comment by jyokako** [comment]
@Akelio-zhang 
could you tell me how to delete hosts?

**Comment by Akelio-zhang** [comment]
@jyokako 
It depends on your OS which determines your hosts file's location. Also, you may try to close any proxy configuration, firewall, or AV software running to fix this problem as minrk said.

**Comment by cdlwhm1217096231** [comment]
@Akelio-zhang 
hi，please tell me how to delete hosts,thank you!

**Comment by gnestor** [comment]
On macOS/Unix, it's located at `/etc/hosts` (file:///etc/hosts) and for Windows (I believe) it's `C:\Windows\System32\Drivers\etc\hosts`
