### ISSUE TITLE
Vetabim (output) block not wrapped in pdf/LaTeX export

### ISSUE THREAD

**Issue by louwers** [jupyter/notebook#1766]
When there is a lot of output, it runs off the page in pdf export. This is due to the vetabim package not supporting wrapping long lines.

A different way to show non-formatted code should be sought, one that does support line-wrapping.

**Comment by gnestor** [comment]
[nbconvert](https://github.com/jupyter/nbconvert) is responsible for exporting to PDF, I suggest submitting an issue there...

**Comment by louwers** [comment]
Thanks for the heads-up. Will do that.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
