### ISSUE TITLE
API to detect if an extension is installed

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1767]
Prompt by @jakevdp in [this comment](https://github.com/vega/ipyvega/issues/56#issuecomment-246421456)

It's not easy as the Server and Kernel might be on different machines so the kernel system might not have the JS but the server might have access to it...

**Comment by jtpio** [comment]
Closing as this was referring to the classic notebook `nbextension` system.

Now Notebook 7 uses the JupyterLab extension system.
