### ISSUE TITLE
Shell escapes should send stderr to stderr

### ISSUE THREAD

**Issue by akimd** [jupyter/notebook#1771]
Hi all,

Running `!echo foo >&2` and (in Python) `print('foo', file=sys.stderr)` yield different results: in the first case `foo` is considered to belong to stdout.

This is troublesome on several regards:
- the display is misleading (the red for stderr is really a neat feature)
- I use my notebooks for test cases, and sometimes tools emit warnings on stderr, but they appear on stdout, which completely messes the Python script that compares the expected output with the effective one.

Thanks!

**Comment by takluyver** [comment]
`!` in the notebook uses Pexpect, which creates a pty; this is necessary to get programmes like `ls` to behave as they would in a terminal. However, it means that the process' stdout and stderr are combined into a single stream before we ever see them, so we can't treat them differently.

**Comment by akimd** [comment]
Gosh :(  That's really a pain in the neck :(

Are there alternatives to `!`, say magic commands, that would rather rely on subprocess or so?  TIA!

**Comment by takluyver** [comment]
I don't think so, but you could easily [make your own magic](http://ipython.readthedocs.io/en/stable/config/custommagics.html) which runs a command with `subprocess`.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
