### ISSUE TITLE
Minimum height on new cells

### ISSUE THREAD

**Issue by conormdurkan** [jupyter/notebook#1772]
I'm currently experiencing an annoying issue where all new cells are three lines in height, but the cell still acts as if it contains a single line when navigating with keys. I believe this has something to do with nbextensions, as I didn't have the problem before installing that, but having since removed it, the problem still persists.

**Comment by gnestor** [comment]
Can you run `jupyter nbextension list` and paste the output here?

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
