### ISSUE TITLE
Run server in background or minimize to service tray?

### ISSUE THREAD

**Issue by LindyBalboa** [jupyter/notebook#1773]
Is this possible? I have yet to have a use for the information in the server terminal window and I find it adds to clutter on my desktop.

Thanks

**Comment by jozjan** [comment]
I guess you refer to using a Notebook server on Windows.
You can try to execute the Notebook server with a VSB script:

```vbs
Dim oShell
Set oShell = WScript.CreateObject ("WScript.Shell")
oShell.run "C:\Anaconda\python.exe C:\Anaconda\Scripts\ipython-script.py notebook", 0
Set oShell = Nothing
```

Setting `intWindowStyle` parameter of the `object.Run(strCommand, [intWindowStyle], [bWaitOnReturn]) ` to 0 results in hiding the window. [Details for Windows Script Host](https://msdn.microsoft.com/en-us/library/d5fk67ky(v=vs.84).aspx)

The only drawback is that you will need to kill the notebook server using a Task Manager (loop for the Python executable) or using pskill or similar.

**Comment by LindyBalboa** [comment]
Yes, I meant on Windows. Thanks this is fine. I want to switch back to linux but one program is holding me back at the moment. I plan on forking a project to suit my needs but till then I am stuck with stupid and clunky windows.

**Comment by vevek-git** [comment]
Does this mean i have to change ipynb files to .py to be able to use this?
