### ISSUE TITLE
Kernel automatically dies, xdg-open issue: 

### ISSUE THREAD

**Issue by evanbiederstedt** [jupyter/notebook#1775]
I have suddenly begun to have issues using jupyter notebook remotely with the following error. I am able to open `*.ipynb` files but cannot run them, as the kernel dies immediately. 

The problem does not appear to be `xdg-open`:

`$ xdg-open --version` is `xdg-open 1.1.0 rc1`

Here is the error I receive: 

```
bash$:~ 56 $ jupyter_run
[I 16:23:22.601 NotebookApp] Serving notebooks from local directory: /gpfs/commons/home/USERNAME/notebooks
[I 16:23:22.601 NotebookApp] 0 active kernels 
[I 16:23:22.602 NotebookApp] The Jupyter Notebook is running at: http://server:portID/
[I 16:23:22.602 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
START /usr/bin/firefox "http://server:portID/tree"
Error: cannot open display: :99
xdg-open: no method available for opening 'http://server:portID/tree'
[I 16:23:57.441 NotebookApp] 302 GET / (10.3.81.208) 0.74ms
[W 16:24:03.432 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160920162321 (10.3.81.208) 10.08ms referer=http://server:portID/notebooks/filename.ipynb
[I 16:24:17.092 NotebookApp] Kernel started: d1bb323f-b209-46e8-a83b-c5c8d6eeb7b0
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  : 
  unable to start device PNG
Calls: <Anonymous> ... evaluate -> dev.new -> do.call -> <Anonymous> -> ok_device
In addition: Warning message:
In ok_device(filename, ...) : unable to open connection to X11 display ''
Execution halted
[I 16:24:23.091 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel d1bb323f-b209-46e8-a83b-c5c8d6eeb7b0 restarted
```

Why would this error suddenly occur?

**Comment by takluyver** [comment]
That looks like an IRkernel error - I think I recall seeing similar things before. Sometimes the png device seems to require a running X server. I can't remember the solution, though. @flying-sheep @janschulz ?

**Comment by evanbiederstedt** [comment]
@takluyver @janschulz @flying-sheep 

> Sometimes the png device seems to require a running X server. 

In that case, perhaps this just needs some sort of flag before running `jupyter notebook`?

**Comment by takluyver** [comment]
From a @flying-sheep's PR IRkernel/IRkernel#409, could you try adding this line to your `~/.Rprofile`:

```R
options(bitmapType='cairo')
```

**Comment by flying-sheep** [comment]
this will only work if `capabilities('cairo')` is `TRUE`. if R is compiled with neither cairo nor X11 capabilities, it has to be recompiled.

**Comment by evanbiederstedt** [comment]
@takluyver @flying-sheep So, I'm a bit confused by the solution mentioned above and the other thread: 

I will add `options(bitmapType='cairo')` to `~/.Rprofile:`.

> this will only work if capabilities('cairo') is TRUE. if R is compiled with neither cairo nor X11 capabilities, it has to be recompiled.

Do you mean that current version of R should be reinstalled globally? I'm slightly confused what it means to reconfigure a "misconfigured R system", or why this issue suddenly started if cairo or X11 capabilities weren't set previously---perhaps the sysadmin reset previous setttings? 

Apologies for bothering you two

**Comment by flying-sheep** [comment]
sorry, i could have been clearer:

you can use `./configure` to set several options during compilation, among them X11 and cairo support.

one of both is needed on any (non-OSX) system. if there’s none available, `png()` won’t work, a state that i consider broken and which is unsupported by IRkernel. here, only recompiling R works.

likewise, the *runtime* configuration for `png()` is broken if R was compiled with exactly one of both, but the `bitmapType` option is set to the unavailable one. here the Rprofile solution works.

and no need to apologize!

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
