### ISSUE TITLE
Shared dependencies between npm and bower

### ISSUE THREAD

**Issue by gnestor** [jupyter/notebook#1778]
The following dependencies are declared by both npm and bower:
- es6-promise
- moment

And the following are declared as npm `devDependencies`:
- requirejs
- underscore

@blink1073 @takluyver Does it make sense to clean this up? I tried moving them from bower to npm in https://github.com/jupyter/notebook/issues/1765 and I ran into multiple issues with Travis and Appveyor builds specifically around https://github.com/jupyter/notebook/blob/master/setupbase.py#L133.

**Comment by blink1073** [comment]
Sounds good to me.   I'd say you can just remove those explicit checks since we're not shipping any code from node_modules.

**Comment by takluyver** [comment]
This is an educated guess, but I think it may be that npm dependencies are used for build & development tooling, and bower dependencies are what we package into the notebook. If that's the case, it's probably OK for there to be some packages in both.

**Comment by blink1073** [comment]
My impression is that bower is used for things that must be used as script tags, and npm for things that can be bundled.  The number of things that must be used as script tags is shrinking, and may be reduced to MathJax and RequireJS.  Even those can be npm installed and then moved from node_modules to a known location for serving.

**Comment by blink1073** [comment]
I would say wait until we have implemented something like https://github.com/jupyter/notebook/issues/1554#issuecomment-245144140 to start exploring this.

**Comment by minrk** [comment]
Until webpack was adopted, client-side js exclusively came from bower, and build utilities (e.g. bower itself, less) exclusively came from node_modules. The use of webpack has mixed this up quite a bit, as now *some* client-side js comes from node_modules (eventually, after building), while *most* comes from bower.

**Comment by gnestor** [comment]
Right, webpack allows us to bundle npm modules along with our source in such a way that it can be loaded in the browser. If we decide to stick with webpack vs. abandoning it and returning to strictly RequireJS, then we could potentially ditch bower all together seeing as though even [mathjax](https://www.npmjs.com/package/mathjax) is available as an npm module.

**Comment by gnestor** [comment]
I've created a PR to start trying things out because my attempts in https://github.com/jupyter/notebook/pull/1765 were breaking Travis and Appveyor left and right.

**Comment by minrk** [comment]
Frontend deps are no longer provided by npm.
