### ISSUE TITLE
Notebook not showing traceback until hard refresh

### ISSUE THREAD

**Issue by SamLau95** [jupyter/notebook#1780]
I'm running `ipython 5.1.0-py35_0`, `notebook 4.2.3-py35_0`, and `ipykernel 4.3.1-py35_0` on a fresh Anaconda install on OSX.

I notice that when an error occurs, only the error message gets shown without showing a traceback, or where the error happened.

![](https://www.dropbox.com/s/d2qqr6787wzjj77/Screenshot%202016-09-21%2016.38.38.png?dl=1)

However, if I hard refresh the browser window, the traceback appears once again.

![](https://www.dropbox.com/s/lqstr4r7yl0udd6/Screenshot%202016-09-21%2016.39.40.png?dl=1)

Is this a problem with my configuration / package versions or with `notebook`?

I do notice that the traceback is included in the `.ipynb` JSON:

```
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-2-70475fc083df>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-2-70475fc083df>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    1 +\u001b[0m\n\u001b[0m       ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "1 +"
   ]
  },
```

**Comment by takluyver** [comment]
That's weird. What browser are you using? I can't replicate it with Firefox on notebook master.

**Comment by SamLau95** [comment]
I'm using a recent version of Chrome (version 53). It seems to be a problem with my local installation because if I use a JupyterHub instance (eg. https://data8.berkeley.edu) the traceback is present as it should be.

I'll give the master branch a try.

**Comment by juhasch** [comment]
Do you have any notebook extensions installed, namely skip-traceback, which does exactly what you describe?

**Comment by SamLau95** [comment]
@juhasch Thanks for the pointer! I was having some problems with an old install of `jupyter_contrib_nbextensions` since I upgraded `notebook`. Uninstalling and reinstalling nbextensions from `master` fixed my issue.
