### ISSUE TITLE
How can execute a command while every session of terminal

### ISSUE THREAD

**Issue by jai11** [jupyter/notebook#1784]
Need to execute a command ir respective of user on every terminal opening how can i do that..

**Comment by minrk** [comment]
shell-level files such as `/etc/profile` or `/etc/bashrc` can be used for this kind of thing. Is that what you are after?

**Comment by jai11** [comment]
@minrk I have tried both files but the command are executing only when I login from server not on notebook terminal.

Notebook terminal are non-login ones. Need to know from where they are loading bashrc file or profile.

Or is there any thing we can do in spawner to run a particular command when terminal are fist started.

**Comment by minrk** [comment]
You can change the command that the Spawner launches:

```python
c.Spawner.cmd = ['/path/to/my/launch.sh']
```

where that launch.sh has:

```bash
#!/usr/bin/env bash -l

export PATH="whatever:$PATH"
# other env setup, startup actions

# actually launch the single-user server
# - exec replaces the current process (avoids extra intermediate process)
# - $@ passed through arguments, so this script behaves the same as the default command
exec jupyterhub-singleuser $@
```

**Comment by jai11** [comment]
@minrk 
I want to disable tab in notebook terminal for that I want to execute > bind 'set disable-completion on'
command whenever notebook terminal open. I am not able to set that in users bashrc or profile file for the user.

**Comment by jai11** [comment]
Thanks @minrk for launch.sh but when I open terminal , terminal dont starts . I can see error i logs file for jupyterhub.

**Comment by jai11** [comment]
@minrk can you please explain more about lauch.sh ..

Currently in my system it is adding in the single server command but .. single server not getting started as getting error for permission denied.

**Comment by jai11** [comment]
@minrk The issue is solved for running command in terminal.

However you can share your thoughts on launch.sh permission denied issue and can close this.

Very thankful to you.

**Comment by minrk** [comment]
If the command is just `/path/to/launch.sh`, you need to set the execute permissions on that file (`chmod +x launch.sh`). Otherwise, you can make the command `bash /path/to/launch.sh`

**Comment by jai11** [comment]
@minrk  Thanks please close this.

**Comment by jai11** [comment]
your help is really very helpful and your responses are very fast .. really appreciate it.

**Comment by minrk** [comment]
Happy to help!
