### ISSUE TITLE
Error: package or namespace load failed

### ISSUE THREAD

**Issue by nmeraihi** [jupyter/notebook#1790]
I tried to install a package named _ChainLadder_ on my .ipynb _install.packages("ChainLadder", "/Users/mymac/anaconda/lib/R/library")_ and I have this message when I load "library(ChainLadder)"
any idea?
thanks!

> Error: package or namespace load failed for ‘ChainLadder’
> 
> Traceback:
> 1. library(ChainLadder)
> 2. stop(gettextf("package or namespace load failed for %s", sQuote(package)),
> 
> . call. = FALSE, domain = NA)

**Comment by takluyver** [comment]
For issues with R code, it's best to ask on the [IRkernel repo](https://github.com/IRkernel/IRkernel). I have no idea about that error, I'm afraid.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
