### ISSUE TITLE
Firefox captures key bindings before Jupyter

### ISSUE THREAD

**Issue by aiguofer** [jupyter/notebook#1794]
I've been playing around with the CodeMirror emacs keybindings and trying to create a good Emacs mode within jupyter (see [here](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/750)), but it seems like Firefox captures some keys before they get to Jupyter. The main problem I'm having is adding:
```
                    "ctrl-n": "jupyter-notebook:select-next-cell",
                    "ctrl-p": "jupyter-notebook:select-previous-cell"
```
to command_shortcuts and getting the `ctrl-n` binding to work inside edit mode (this is included in the CodeMirror keyMap). They seem to work fine in Chrome, but not in Firefox.

Is there anything that can be done about this?

Thanks!

**Comment by Carreau** [comment]
Unfortunately no. It is a security measure set up by browser. They won't let the pages context get shortcuts. In some OS the window manager even intercept the shortcut and the browser never receive it. 

You _might_ be able to get around using browser extensions, but that's unsure.

**Comment by aiguofer** [comment]
Aww that's what I was thinking :( I guess I'll just use Chrome for now... I might at some point look into an extension.

I do find it strange that `ctrl-n` doesn't work `edit_mode` but `ctrl-p` does.

**Comment by takluyver** [comment]
There's a specific set of shortcuts that Firefox no longer lets us capture, and Ctrl-N (new window) is one of them. They're deemed too important to browser operation for websites to mess with. I think Ctrl-T (new tab) and Ctrl-W (close tab) are in the same category.

I think Chrome has been doing the same for longer than Firefox.

**Comment by aiguofer** [comment]
Ohh, that's odd, it currently works fine in Chrome Version 53.0.2785.116 (64-bit) on Fedora 24.

**Comment by takluyver** [comment]
Maybe Chrome allows them under certain circumstances, or maybe it has changed back. A few years ago, people [were saying](http://stackoverflow.com/a/7296303/434217) that Chrome didn't let you capture those.

**Comment by aiguofer** [comment]
Ahh, yeah in there it says they changed it at some point. I'll try to dig a bit more into whether anything can be done through browser extensions.

Thanks!

**Comment by yelled1** [comment]
I love this prj, as well. Along with my blue switch keyboards. Actually https://addons.mozilla.org/en-US/firefox/addon/keybinder/?src=search works! Which means Ctrl-n can be disabled for Firefox. Ctrl-Shift-n works. A little annoying but it's a work around for now.

**Comment by aiguofer** [comment]
Thanks for the suggestion! Unfortunately, this did not work for me. It successfully removes the C-n key binding for creating a new window, but it still doesn't let the keys bubble down to the notebook, so C-n still doesn't take me to the next line.

Btw, if you're on Chrome on Linux, most of they key shortcuts work as expected.

**Comment by yelled1** [comment]
Actually, it (Chrome Version 55.0.2883.87 (64-bit) & Lubuntu 16.04) does not have this right either. Ctrl-n opens up new Brower windows. Was there some add-on or setting u had to do?
Thanks,

**Comment by aiguofer** [comment]
Oh :( it seems that it's due to having global Emacs keybindings enabled in Gnome (which I believe is actually implemented in GTK). You could try [enabling Emacs mode for GTK](http://shallowsky.com/blog/linux/gtk3-emacs-key-theme.html) and then setting Chrome to use GTK, but YMMV, especially since you're on LXDE.

**Comment by yelled1** [comment]
Actually, thank you but above did not work as u suspected. But I found this add-on "Menu Wizard" and I just disabled the Control-n from it and it now "Ctrl-n" works as down key! Be sure to reboot the browser after installing it & shit Shift-Alt-M to launch it. Hit the Tool thingy (wrench icon) & and disable the Keyboard shortcut. It's now better than Chrome, which I had problem with Keras update. I will share more as I figure it out, but now the main issue is solved.
I still have issues with Ctrl-Shft-_ splitting the cell & few others but... this is much better

**Comment by aiguofer** [comment]
Awesome!! thanks a lot!

I actually took a few of the existing Emacs and Vim keybinding extensions available and added it to https://github.com/ipython-contrib/jupyter_contrib_nbextensions, just enable the `select_keymap` extension there. That should take care of the `Ctrl-Shit-_`. It also fixes `Ctrl+Y` to not highlight, and adds "Ctrl+n/p" navigation to move around cells.

I'll add to the documentation about that extension for firefox users :)

**Comment by yelled1** [comment]
Excellent! Thank u a lot as well. Just be sure to create a non-using key to replace the C-n short cut. I attempt to blank it out and ctrl-n returns when I restart a new browser. So, I just assigned to a key I would never use.

**Comment by yelled1** [comment]
A Bit embarrassing, but can u tell me how to use select_keymap? I installed it but 
(Py3) ~$ jupyter nbextension enable select_keymap=emacs
Enabling notebook extension select_keymap=emacs...
      - Validating: problems found:
        - require?  X select_keymap=emacs
(Py3) ~$ jupyter nbextension enable select_keymap='emacs'
Enabling notebook extension select_keymap=emacs...
      - Validating: problems found:
        - require?  X select_keymap=emacs
gives errors. Thanks,

**Comment by yelled1** [comment]
$ jupyter nbextension list
Known nbextensions:
  config dir: /home/hyoon/.jupyter/nbconfig
    notebook section
      select_keymap=emacs  enabled 
      - Validating: problems found:
        - require?  X select_keymap=emacs
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      jupyter_emacskeys/init  enabled 
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: /opt/miniconda3/envs/Py3/etc/jupyter/nbconfig
    notebook section
      nb_conda/main  enabled 
      - Validating: OK
      nb_anacondacloud/main  enabled 
      - Validating: OK
      nbpresent/js/nbpresent.min  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
    tree section
      nb_conda/tree  enabled 
      - Validating: OK

Hi:

As seen above.
I do have: select_keymap=emacs  enabled but I still get split screen when I hit Ctrl+Shit+_ 
Let me know if this is a bug.
Thanks,

**Comment by aiguofer** [comment]
Hey, sorry you enable it with:
```
jupyter nbextension enable select_keymap/main
```

then when you're in a notebook you can select they keymap you want in the `Edit` menu. The selection will persist on your browser.

**Comment by vlad17** [comment]
Hello everyone, trying to get Ctrl-n to work in chrome has been a pain (Chrome, unlike Firefox, is not W3C compliant, so it the above does not work). This fix is for Firefox, but I think Chrome users might see this PR on google when they look for a fix (like myself). [This PR for ipython-contrib](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/845) and this [jupyter-emacskeys issue](https://github.com/rmcgibbo/jupyter-emacskeys/issues/3) are related.

The only fix I've found is to (1) activate Jupyter via command line (2) open a notebook as usual, starting the kernel [here, using Ctrl-n would create a new window in chrome instead of going to the next line with the emacs binding] (3) copy the URL (4) close that window (without killing the kernel) (5) navigate to the copied page in app mode: `google-chrome --app=http://localhost:8888/notebooks/some-nb.ipynb`

**Comment by chesterroh** [comment]
> Hello everyone, trying to get Ctrl-n to work in chrome has been a pain (Chrome, unlike Firefox, is not W3C compliant, so the above does not work). This fix is for Firefox, but I think Chrome users might see this PR on google when they look for a fix (like myself). [This PR for ipython-contrib](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/845) and this [jupyter-emacskeys issue](https://github.com/rmcgibbo/jupyter-emacskeys/issues/3) are related.
> 
> The only fix I've found is to (1) activate Jupyter via command line (2) open a notebook as usual, starting the kernel [here, using Ctrl-n would create a new window in chrome instead of going to the next line with the emacs binding] (3) copy the URL (4) close that window (without killing the kernel) (5) navigate to the copied page in app mode: `google-chrome --app=http://localhost:8888/notebooks/some-nb.ipynb`

this tip really helped me. I spent so much time to figure out how to avoid Ctrl+n / Ctrl+k key overriding by Chrome :) Thanks!
