### ISSUE TITLE
custom.js ignored

### ISSUE THREAD

**Issue by tachim** [jupyter/notebook#1795]
I'm trying to get line numbering working by default but none of the versions of custom.js online work. Current version is:

```javascript
define([
    'base/js/namespace',
    'base/js/events'
    ],
    function(IPython, events) {
        //events.on("app_initialized.NotebookApp",
        events.on("notebook_loaded.Notebook",
            function () {
                require("notebook/js/cell").Cell.options_default.cm_config.lineNumbers = true;
            }
        );
    }
);
```

**Comment by gnestor** [comment]
Your code looks good. Does it appear like custom.js is being loaded before the notebook (try adding a log statement in custom.js and verify that the log statement is the first one in the console when loading the notebook)? If not, then you either need to:

* Upgrade notebook to 4.2.3
* If you're running notebook from source, there is an [outstanding issue affecting master](https://github.com/jupyter/notebook/pull/1770)

If it's not loading first, then setting the cell default config (as you are in your code example) after the config has been loaded will have no effect. 

If it is loading first, then let me know and I will do some investigating.

FYI, line number toggle status is persisted to nbconfig, so if you show line numbers in one notebook, they should show in any other notebooks you open on your computer.

**Comment by minrk** [comment]
I think this is the webpack problems with custom.js that are fixed by removing webpack.

**Comment by gnestor** [comment]
@minrk I tested and with the following custom.js:

```js
define([
    'base/js/events',
], function(events) {
    console.log('custom.js');
    events.on('app_initialized.NotebookApp', function () {
        console.log('app_initialized.NotebookApp');
    });
})
```

I am seeing `custom.js` being logged first (which is expected) but no `app_initialized.NotebookApp`.

**Comment by tachim** [comment]
Oops, missed these notifs. @gnestor, are the steps you suggested in https://github.com/jupyter/notebook/issues/1795#issuecomment-251822448 still the right things to try?

**Comment by gnestor** [comment]
> Upgrade notebook to 4.2.3

The current release is 4.3.1, so I suggest upgrading...

> If you're running notebook from source, there is an outstanding issue affecting master

This should no longer be an issue.
