### ISSUE TITLE
Failed to change MathJax font in Jupyter

### ISSUE THREAD

**Issue by boathit** [jupyter/notebook#1796]
When writing mathematics equations in Jupyter with markdown, MathJax renders the equations in STIX-Web fonts. I tried to change the STIX-Web to TeX-Web fonts in `notebook/static/custom/custom.js` with the following code, but it did not work.

```
MathJax.Hub.Config({
  "HTML-CSS": {
    availableFonts: [],
    preferredFonts: "TeX",
    webFont:"",
    imageFont:"",
    undefinedFamily:"'Arial Unicode MS',serif"
  }
});
```

**Comment by Atcold** [comment]
Any solution to this?
