### ISSUE TITLE
[meta] Accessibility

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#180]
Ping  @ellisonbg I found this libs that visually highlight issues on pages.

http://khan.github.io/tota11y/

**Comment by ellisonbg** [comment]
Thanks for posting this link. I know we will eventually have to cross the
accessibility bridge at some point.

On Tue, Jun 30, 2015 at 11:50 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Ping @ellisonbg <https://github.com/ellisonbg> I found this libs that
> visually highlight issues on pages.
>
> http://khan.github.io/tota11y/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/180>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by gvwilson** [comment]
Any more thoughts on accessibility support in the Notebook? We have a visually impaired learner in a Software Carpentry workshop this weekend, and have some learners with physical challenges as well.

**Comment by Carreau** [comment]
> Any more thoughts on accessibility support in the Notebook

There haven't been a lot of work for current notebook. I haven't been involved that much but I suppose that is taken care of in JupyterLab. @jasongrout & @ellisonbg  might be more aware.

**Comment by ellisonbg** [comment]
We have talked to some of our collaborators from IBM about their doing an
accessibility study of the notebook. But that hasn't happened and our core
devs are swamped with other things. I don't think the work is too
difficult, but it will require sustained effort (probably a year) by
someone who knows that area.

On Thu, Jun 9, 2016 at 8:41 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Any more thoughts on accessibility support in the Notebook
>
> There haven't been a lot of work for current notebook. I haven't been
> involved that much but I suppose that is taken care of in JupyterLab.
> @jasongrout <https://github.com/jasongrout> & @ellisonbg
> <https://github.com/ellisonbg> might be more aware.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/notebook/issues/180#issuecomment-225086397>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0OCJmuWtqzHHpjoVy0uREkofHJ01ks5qKNz0gaJpZM4FPN7l>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jasongrout** [comment]
cf. https://github.com/jupyter/enhancement-proposals/pull/10, where the current internationalization discussion is going on currently.

**Comment by JamiesHQ** [comment]
See #https://github.com/jupyterlab/jupyterlab/issues/911 as well

**Comment by gnestor** [comment]
Update:

* RTL support: https://github.com/jupyter/notebook/pull/2357
* Internationalization support: https://github.com/jupyter/notebook/pull/2140

There are ongoing accessibility efforts now. Let's close this and open more specific issues (e.g. #3102 and #3103 which propose improving out workflow for building translation and contributing translations.

**Comment by takluyver** [comment]
While translations do help with some kinds of 'accessibility', the term when applied to software usually includes accessibility for people with visual impairment. A key part of that is how well it works for someone using a screenreader.

So I'm going to reopen this, because there are important aspects that are not covered by the translation work.

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
