### ISSUE TITLE
deleted notebook appears again 

### ISSUE THREAD

**Issue by jai11** [jupyter/notebook#1808]
open notebook in different tab.

navigate to jupyter dash board

delete the notebook. as autosave saves the notebook it will again appear in the dash board.

**Comment by takluyver** [comment]
I'd consider that expected behaviour, though I can see how it would be a bit frustrating if you didn't know you'd still got the notebook open.

**Comment by jai11** [comment]
thanks for the reply..  but say it was opened and left in some other tab and I want to delete it. but after some time I am seeing it in my dashboard. It will question jupyter functionality. Any was to disable that .. we can disable auto save . but any luck to tackle the thing.

More .. what is the prons of the functionality.

**Comment by Carreau** [comment]
The pros of the functionality is to not lose work if your browser crash. 

It's the same behavior as most editor. If you open a file, leave the window open and delete the file from the file system your program will resave the file at some point.

**Comment by jai11** [comment]
Thank you .. Please close this.
