### ISSUE TITLE
Bug: when editing text, quote should only skip if it's the second of a matched pair.

### ISSUE THREAD

**Issue by themrmax** [jupyter/notebook#1810]
I like the auto-insert of matching quotes, and I think it's the desired behaviour to have pressing quote skip over the second of a matching pair, but it's not good (also non-standard afaik, at least in emacs it doesn't do this) to have it for the first, it makes it hard to insert new elements in arrays of strings. To illustrate:

Desired:
```
    ['i want the cursor to skip over the quote when i'm done']
                                              cursor ->    ^
```
Undesired:

    ['<-- i am trying to insert a new string in my array to the left here']
    ^ <- cursor

**Comment by takluyver** [comment]
I see the same in [this Codemirror demo](http://codemirror.net/demo/closebrackets.html).

Codemirror is the editor component we use in cells. We have only limited control over the editing behaviour from the outside, so for something like this you probably need to take it up [with Codemirror](https://github.com/codemirror/CodeMirror/) and then get a new version included in the notebook.

**Comment by themrmax** [comment]
Cool i'll raise an issue there, thanks.

**Comment by themrmax** [comment]
https://github.com/codemirror/CodeMirror/issues/4287
