### ISSUE TITLE
How can we limit print limit in notebook

### ISSUE THREAD

**Issue by jai11** [jupyter/notebook#1813]
@minrk  I read your article 

https://github.com/ipython/ipython/issues/6516

for limited print values in notebook. I placed it in file /opt/anaconda2/lib/python2.7/site-packages/notebook/static/custom/custom.js

But not getting desired output. Can you please share your thoughts.

Test code is 

import time
start = time.time()
i=0
while time.time() - start < 3:
    i=i+1
    print(time.time())
    print (i)

**Comment by minrk** [comment]
You don't generally want to overwrite files in `site-packages`. If you want to use custom.js, the place to put it is `~/.jupyter/custom/custom.js`. What version of the notebook are you using?

**Comment by jai11** [comment]
Notebooks version is 4.2.2

**Comment by jai11** [comment]
I placed the code as per you blog in ~/.jupyter/custom/custom.js and restarted jupyterhub and ran my test code as stated above. It gave me 62k lines. I need to limit output to 1k only.

**Comment by jai11** [comment]
just an update I ran the code on notebook version ~ 4.2.1

**Comment by jai11** [comment]
Any pointer on this.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
