### ISSUE TITLE
Displaying results for long lists is messy.

### ISSUE THREAD

**Issue by gnublet** [jupyter/notebook#1815]
For example, type `[1,2,3,4]*100` in the input box and press `Ctrl+Enter` you will see a long vertically formatted list: 

```
[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
...
```

This can be improved by displaying the list on multiple columns like `ls`.

**Comment by takluyver** [comment]
Thanks, this is already tracked as ipython/ipython#8741 (the way lists display is part of IPython, not the notebook). Unfortunately we have not yet found a good general fix that doesn't mess things up for things like lists of lists or lists of dicts.
