### ISSUE TITLE
Optional function arguments

### ISSUE THREAD

**Issue by alexmarder** [jupyter/notebook#1817]
I'm not sure if this is an ipython bug or unique to jupyter notebooks. When a function I've defined -- and imported (defined in a .py file) -- has an optional parameter that would be passed by reference, and a variable in the notebook has the same name, the default value is not used.

As an example, let's say I've defined the function f as,

```
def f(s=[]):
    s.append(2)
    return s
```

and I have defined the variable `s=[4, 3]`. If I call the function `f()`, I expect it to return `[2]`, but it instead returns `[4, 3, 2]`.

This does not always happen, but I've seen it happen enough that I not have to pass all optional parameters for every call to my own functions, or else I risk running into this problem.

**Comment by Carreau** [comment]
Hi there !

Can you provide a self contained example notebook ? I have difficulty reproducing this. 
Or are you falling in the trap of python's "[mutable default arguments](http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments)" which is a classic misunderstanding of how default arguments works[1].

Here is what I did:

```
%%writefile testpy.py

def g(s=[]):
    s.append(2)
    return s
```

```
def f(s=[]):
    s.append(2)
    return s
```
```
from testpy import g
```
```
s = [3,4]
```
```
g() # [2]

f() # [2]
```

Same if I define `s=[3,4[` first.

[1]: Default arguments implementation is tricky to understand and rarely correctly explained, one can question question why it has been chosen to be this way.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
