### ISSUE TITLE
Jupyter notebook front end architecture

### ISSUE THREAD

**Issue by YogeshTayal** [jupyter/notebook#1818]
The front end code of jupyter notebook doesn't seem to have an SPA architecture i.e it doesn't have a routing mechanism, URLs are modified manually. Also, it opens up a new tab whenever you click on an .ipynb file. It is still following the old Javascript-JQuery approach. I tried extending it for my use but found it tough to do that. Also, I could not find any good documentation on the UI part of the code. Please correct me if I am wrong. If the front end code actually needs an upgrade then is anyone working on it already?

**Comment by takluyver** [comment]
There's a total rewrite of the frontend code going on under the name [Jupyterlab](https://github.com/jupyter/jupyterlab).

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
