### ISSUE TITLE
Jupyter Notebook insists on running Python 3

### ISSUE THREAD

**Issue by petered** [jupyter/notebook#1819]
I'm running a Jupyter notebook from a venv.  I have Python and IPython version 2.7.6. 

Proof:

```
(venv) wcw-self-145-109-125-132:plato peter$ python -c "import sys; print sys.version"
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
(venv) wcw-self-145-109-125-132:plato peter$ ipython -c "import sys; print sys.version"
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
```

But when I launch jupyter notebook, It insists on running python 3 (even when I explicitly start a Python 2 notebook, even when it says "Python 2 " in the corner):

```
import sys
print(sys.version)
-----
3.5.1 (default, Apr 18 2016, 03:49:24) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

**Comment by petered** [comment]
I removed `~/.jupyter`, buyt the problem persists.   I then found found the python3 version that it was running (from some old project) and deleted it, and now it just gives 'cannot find interpreter' errors.  pip uninstalling/reinstalling jupyter doesn't work.

**Comment by takluyver** [comment]
There are kernelspecs installed pointing to that. Run `jupyter kernelspec list` to see where they are.

http://ipython.readthedocs.io/en/stable/install/kernel_install.html

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
