### ISSUE TITLE
iopub rate limits should not be unlimited by default

### ISSUE THREAD

**Issue by jasongrout** [jupyter/notebook#1821]
Since we live in a finite world with limited resources, we should pick reasonable defaults for these limits that were introduced in #931:

https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L918

And thus disarm yet another foot-gun.

Thanks to @williamstein for conversations about this.

**Comment by jasongrout** [comment]
Also, it would be good to insert an iopub message that says that further iopub messages were limited, so that the error is stored in the notebook and it is clear to the end user. Right now only the server operator gets to see what the problem was.

**Comment by williamstein** [comment]
Thanks.  I frequently have to manually edit ipynb files using vim to remove huge output that users of SageMathCloud generate.  These are often students who are first time Python/Jupyter users, so epically large unintentional output is not uncommon.

**Comment by jasongrout** [comment]
Thanks for bringing that up. For the record, the rate limits here don't address performance problems that may come up with rendering files that already have many outputs.

**Comment by gnestor** [comment]
@jasongrout @Carreau @minrk Any suggestions as to what a good default value would be?

**Comment by minrk** [comment]
I agree 100%, but I don't know how to pick a sensible default other than human testing. My guess is that message rate limit should be between 100-1k per second. I have less of a sense of the flow rate limit. I'll play with some values and come back with something to start with.

**Comment by minrk** [comment]
I've played around a bit, and I'm having difficulty coming up with reasonable default numbers. With almost any value, I can cause problems in the browser with certain output patterns, but also be annoyingly restrictive with others, using the same values.

Right now, I'm looking at:

- data_rate = ~1M
- msg_rate = 500-1000
- rate_limit_window = 2-3

**Comment by williamstein** [comment]
>  I can cause problems in the browser with certain output patterns, but also be annoyingly restrictive with others, using the same values.

I don't know how you guys implemented things, but in SMC at least, whenever rate limitation happens, there is a big clear message saying it happened with instructions about how to raise/lift the limitation.

**Comment by minrk** [comment]
Yup, we've got a big clear message saying that rate limit has been hit and how to raise it. It's still really unpleasant when it happens, so I don't want the default limit to be too low.

**Comment by gnestor** [comment]
I guess that the best way to test this is to merge into master and start using it ourselves. I just submitted a PR. Have a look and let's merge and start testing...
