### ISSUE TITLE
Can not upload files

### ISSUE THREAD

**Issue by iteratorlee** [jupyter/notebook#1823]
I rebuilt js and css, but when I open a window in the browser and to upload a csv file to notebook, it can not work, the local console displayed as below:

```
[I 23:32:28.795 NotebookApp] Uploading file to /data.csv
[W 23:32:28.803 NotebookApp] Permission denied: data.csv
[W 23:32:28.804 NotebookApp] 403 PUT /api/contents/data.csv (127.0.0.1) 20.91ms referer=http://localhost:8888/tree
```

**Comment by takluyver** [comment]
What folder did you start the notebook in? Does your user account have permission to write files there? Does `data.csv` already exist in that folder?

**Comment by iteratorlee** [comment]
Oops!!! I forgot the permission matter... It looks like that I didn't use sudo option...
But another question occured. After I run sudo jupyter notebook --allow-root, the console remind me as follow:
[1013/192242:ERROR:nss_util.cc(94)] Failed to create /home/iterator/.pki/nssdb directory.
Aborted (core dumped)
so why ...
Thank you for your reply.

**Comment by takluyver** [comment]
We do not recommend running the notebook as root or with `sudo`. I would guess it fails because some environment variable still refers to your home directory, and root can't write to that.
