### ISSUE TITLE
Jupyter notebook doesn't work

### ISSUE THREAD

**Issue by Eduardo28th** [jupyter/notebook#1824]
Hello I am trying to open jupyter notebook but it doesn't work anymore. It worked last time but after I closed it and try to open again this error appears. I have already reinstalled, but it doesn't work. Could some one give me an advice how to solve the problem?

U:>jupyter notebook
[I 19:54:44.878 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 19:54:45.374 NotebookApp] [nb_anacondacloud] enabled
[I 19:54:45.379 NotebookApp] [nb_conda] enabled
[I 19:54:45.419 NotebookApp] \u2713 nbpresent HTML export ENABLED
[W 19:54:45.419 NotebookApp] \u2717 nbpresent PDF export DISABLED: No module nam
ed 'nbbrowserpdf'
[I 19:54:45.512 NotebookApp] Serving notebooks from local directory: U:\
[I 19:54:45.512 NotebookApp] 0 active kernels
[I 19:54:45.512 NotebookApp] The Jupyter Notebook is running at: http://localhos
t:8888/
[I 19:54:45.513 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\Scripts\jupyter-notebook-script.py", line 5,
in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Program Files\Anaconda3\lib\site-packages\jupyter_core\application.py
", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\config\applicatio
n.py", line 653, in launch_instance
    app.start()
  File "C:\Program Files\Anaconda3\lib\site-packages\notebook\notebookapp.py", l
ine 1131, in start
    self.write_server_info_file()
  File "C:\Program Files\Anaconda3\lib\site-packages\notebook\notebookapp.py", l
ine 1105, in write_server_info_file
    with open(self.info_file, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '\\tholos.itserv.scss.
tcd.ie\Pgrad\munozmae\AppData\jupyter\runtime\nbserver-2052.json'

**Comment by takluyver** [comment]
I suspect that it's some issue with `%APPDATA%` pointing to a UNC path (starts with `\\`). Can you check for the folder it's trying to write to, both interactively and in Python?

```python
os.path.exists('\\tholos.itserv.scss.tcd.ie\Pgrad\munozmae\AppData\jupyter\runtime\')
```

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
