### ISSUE TITLE
Make sliders possible for logspace

### ISSUE THREAD

**Issue by shashi** [jupyter/notebook#183]
as discussed in https://github.com/JuliaLang/Interact.jl/issues/2 Currently the sliders work only for linearly increasing ranges. But it would be nice to have sliders work for `logspace(-3, +3)`.

**Comment by Carreau** [comment]
Seem like one could "just" use a normal slider and use `10^value` no ?

**Comment by shashi** [comment]
Yes but this is just a nice-to-have.

**Comment by jasongrout** [comment]
Shashi, thanks for the issue!  Can you open an issue on the ipython widgets repo?  https://github.com/ipython/ipywidgets

And also, could you be a bit more descriptive?  I'm not sure exactly what `logspace(-3,+3)` is.  Are you saying you want the labels and values on the slider to change?  Could a slider that takes arbitrary text labels and associated values work?

**Comment by JamiesHQ** [comment]
@jasongrout : Greetings! Has this been resolved by either your recent jupyter widgets release(s) and or your hangouts with @shashi (see https://github.com/jupyter-widgets/ipywidgets/issues/573) ? Can we close this particular issue? thanks!

**Comment by gnestor** [comment]
Created an issue on ipywidgets: https://github.com/jupyter-widgets/ipywidgets/issues/1847
