### ISSUE TITLE
Long string input crashing kernel

### ISSUE THREAD

**Issue by romainjln** [jupyter/notebook#1839]
Hi,

It seems that a long string input makes the kernel crash, or at least takes a very very long time to process.
For example, a string containing a hundred thousand characters takes some minutes to be evaluated.
One with two hundred thousand characters tends to make the kernel crash.

I am generating my string using this python script:
with open('test.txt', 'w') as f:
    for _ in range(200000):
        f.write('a')

**Comment by gnestor** [comment]
I tried both our sample code and the following:

```python
str = ''
for _ in range(200000):
    print(str + 'a')
```

It evaluated surprisingly fast for me (~1.5s). If you're still having an issue with this, please provide more info like the version of notebook (`pip show notebook`), version of Python, OS, etc.

**Comment by romainjln** [comment]
Hi,

Sorry for my late answer . Here are the info :

```
Metadata-Version: 2.0
Name: notebook
Version: 4.2.3
Summary: A web-based notebook environment for interactive computing
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
Installer: pip
License: BSD
Location: c:\users\romain.julien\dev\python\lib\site-packages
Requires: tornado, ipython-genutils, nbformat, jupyter-core, jupyter-client, ipykernel, traitlets, jinja2, nbconvert
Classifiers:
  Intended Audience :: Developers
  Intended Audience :: System Administrators
  Intended Audience :: Science/Research
  License :: OSI Approved :: BSD License
  Programming Language :: Python
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
Entry-points:
  [console_scripts]
  jupyter-nbextension = notebook.nbextensions:main
  jupyter-notebook = notebook.notebookapp:main
  jupyter-serverextension = notebook.serverextensions:main
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command
```


But I just have updated pip and Jupyter to their newest version (9.0.1 & 4.2.0) and I do not have this problem anymore

Romain
