### ISSUE TITLE
Sort (sorting) order of files in notebook list (enhancement/feature request)

### ISSUE THREAD

**Issue by temmeand** [jupyter/notebook#184]
It would be helpful to be able to change the sort order of files in the notebook list. I would like it to be alphabetical for all file types and not case sensitive. Directories can appear before files or within the files.

(Hope I got this in the correct place. Let me know if I didn't)
-Extra Info
Currently my list is sorted as follows: - Directories (starting with upper case) - directories (starting with lower case) - IPython notebooks (starting with upper case) - ipython noteooks (starting with lower case) - Other files (starting with upper case) - other files (staring with lower case)

I'm using Jupyter 3.0.0-f75fda4

**Comment by Carreau** [comment]
> I'm using Jupyter 3.0.0-f75fda4

Upgrade to 3.2 which is an important security fix.

And yes we know that a better dashbord with filtering, ordering would be nice.  We just need  someone to write it.

**Comment by alimanfoo** [comment]
Can I also add a feature request to be able to sort folder contents in reverse order. I name all my notebooks starting with a datestamp (e.g., 20151202_some_work.ipynb) and it would be most useful to have these sorted in reverse order because I usually reopen the most recent notebooks (e.g., to continue working on them). Currently I have to scroll all the way to the bottom to find my most recent notebooks.

**Comment by gnestor** [comment]
Similar https://github.com/jupyter/notebook/issues/1267

**Comment by DSLituiev** [comment]
sorting by modification date will be highly appreciated

**Comment by gnestor** [comment]
This was implemented 1/16/16 by https://github.com/jupyter/notebook/pull/943 but it's marked for a 5.0 release, which may not happen for a few months. If you install notebook from master by following [these directions](https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.rst#setting-up-a-development-environment), you can take advantage of the feature now.

**Comment by takluyver** [comment]
Closing as this got implemented in #943.

**Comment by michaelaye** [comment]
This feature is not active in master?

**Comment by gnestor** [comment]
I see it in master:

![screencap](http://g.recordit.co/uZaOqraygZ.gif)

**Comment by michaelaye** [comment]
so sorry. had a clashing conda package that sneaked in and overruled the GH install.

**Comment by Carreau** [comment]
> so sorry. had a clashing conda package that sneaked in and overruled the GH install.

See https://github.com/fperez/conda-edev , relatively recent. Should avoid these kind of issues by providing pip-install as a conda "overlay".

**Comment by slagtermaarten** [comment]
I would highly appreciate the possibility to configure a default file sorting method and/or store a default method per directory. This is currently not possible, correct?

**Comment by MarkMoretto** [comment]
@slagtermaarten Hi, I'm not sure if you're still looking for a solution here. One thing I've tried is some jQuery in the custom.js folder.  Per this documentation, that should be located in the following folder:

`~/.jupyter/custom/custom.js`

On Windows, that is something like:

`C:\Users\%USERNAME%\.jupyter\custom\custom.js`

For my purposes, I wanted to sort by last modified descending (newest to oldest).  For that, I added a function to delay *clicking* the Last Modified button by ~1 second after the DOM finishes loading.  You can adjust that if your system is faster/slower at loading things.  The sort is retained for the session.

Anyway, at the bottom of the custom.js file, I added the following snippet:

```js
$(function(){
  function change_order(){
    $("#last-modified").click(); // Click to sort ascending 
    $("#last-modified").click(); // Click again to sort descending
  };
  window.setTimeout( change_order, 1000 ); // 1 second delay after DOM ready
});
```

Clicking the button twice results in sorting by newest and the button looks like the following:

![image](https://user-images.githubusercontent.com/25012707/82579038-39118480-9b5b-11ea-936d-631eec770028.png)

The IDs are found if you right-click on your button and select 'inspect element'.  If you know some HTML, the id tag should be easy to find.

Hope this helps!
