### ISSUE TITLE
[macOS] Websockets fail to connect over TLS on non-443 or 8443 port

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/notebook#1849]
System configuration:
- macOS Sierra
- Chrome 54.0.2840.59

If a notebook server is configured over TLS on a nonstandard port (not 443 or 8443), websockets will fail to connect. Went ahead and launched https://tmp59.tmpnb.org:9001/ to demonstrate.
- https://tmp59.tmpnb.org/ ✅ 
- https://tmp59.tmpnb.org:8443/ ✅ 
- https://tmp59.tmpnb.org:9001/ ❌ 

Reproduction steps (mostly listed here for Chromium developers):
- Be on macOS Sierra with Chrome ~54.0.2840.59
- Visit https://tmp59.tmpnb.org:9001/
- Click "Welcome to Python" from the list of notebooks or New (upper right)

Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=657791

**Comment by Carreau** [comment]
I think it's more widespread than websocket. It's even "some browser refuse tls on non 443 and 8443. I have submitted a patch on PyPI (`https://github.com/pypa/pypi-legacy/pull/536`) which allow to set the port just for this reason.

**Comment by rgbkrk** [comment]
Odd. I'm only having problems with websockets. All regular ol' HTTP 1 over TLS is working just fine.

**Comment by Carreau** [comment]
I'm on Chrome dev.

**Comment by Carreau** [comment]
Or at least Beta (54.0.2840.59 beta )

**Comment by minrk** [comment]
This seems related to the Safari won't connect websockets with self-signed certs issue, in that browsers don't seem to reliably use the same configuration for websockets as regular connections. Sad!

There's probably nothing for us to do other than keep this here as a known issue and report upstream to chromium.

**Comment by rgbkrk** [comment]
Looks like I was wrong about Safari being able to connect. I can't connect with Safari either.

**Comment by rgbkrk** [comment]
Uh oh, Firefox isn't working either now. Additionally, El Capitan no longer works (with security updates yet not using Sierra).

How does one even file a bug with Apple?

**Comment by rgbkrk** [comment]
Filed an issue with Apple.

**Comment by rgbkrk** [comment]
Update: Firefox and Safari seem fine again. Nevermind me there.

**Comment by rgbkrk** [comment]
<img width="586" alt="screen shot 2016-10-28 at 4 54 57 pm" src="https://cloud.githubusercontent.com/assets/836375/19825545/6b9cb150-9d2f-11e6-86be-1adfb8ccee3a.png">

This definitely doesn't seem like a self signed certs issue!

Try doing:

```
$ openssl s_client -showcerts -connect apple.com:443
CONNECTED(00000003)
59594:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/ssl/s23_clnt.c:593:
```

**Comment by cpres** [comment]
I'm receiving the same error with openssl. Have you found a solution?
`6516:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/ssl/s23_clnt.c:593:`

**Comment by rgbkrk** [comment]
What's your full macOS version number?

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
