### ISSUE TITLE
What are the differences between [conda root] and python [default ]

### ISSUE THREAD

**Issue by Boussarhane** [jupyter/notebook#1850]
Hello, 

I installed the latest version of anaconda on Ubuntu Linux. I have a pre-installed version of Python "Python 2.7".

When I launch Jupyter and I want to create a new Notebook, it suggests for me to choose between **[conda root]** and **python [default ]**. But I dont know which one I have to choose.

I'm new to Python in general and Anaconda particularly.

Can someone please help me to understand this philosophy and choose the correct kernel name?

Thank you.

**Comment by takluyver** [comment]
They will probably be the same. Conda is making kernels corresponding to conda environments on your computer; if you haven't created any manually, then the only environment will be the 'root environment' that Anaconda sets up by default.

**Comment by damianavila** [comment]
Yep, there are also other possibilities when you start the notebook server from one environment to run kernels in other environments... in that case, if you are not starting the notebook server in the root environment, the conda root and the python default kernels will point to different python executables... BUT this is not the most common case (I think) and most of the cases, as Thomas said, both will be pointing to the very same python executable.

**Comment by yunyundong** [comment]
what can we do to display or view their difference? or can we find where the different kernels points to? @damianavila

**Comment by damianavila** [comment]
>what can we do to display or view their difference? or can we find where the different kernels points to?

A simple `import sys; sys.executable` will tell you what python executable are you pointing at with the current kernel.

**Comment by yunyundong** [comment]
Thank you very much. After I run your support codes, the `sys.executable` are really the same.
Now, I have another question that why my jupyter notebook has 0 active kernel?  In the process of starting, the output information show 2 kernels found, but 0 active. I am new to jupyter notebook, how can I fix the problem?

**Comment by yunyundong** [comment]
Now, I have a problem that when I open a jupyter Notebook, there is a hint message:

> I couldn't find a kernel matching Python [Root]. Please select a kernel:

how should I set a default kernel for all the jupyter notebook? @damianavila

**Comment by damianavila** [comment]
>Now, I have another question that why my jupyter notebook has 0 active kernel? In the process of starting, the output information show 2 kernels found, but 0 active. I am new to jupyter notebook, how can I fix the problem?

What do you mean with 0 active kernels? Having kernels "enabled" means you have them available to run when you start a notebook with a specific one. I don't see a problem to fix...

>by the way, how to list the installed packages for a specific environment?

`conda list -n your_env` should list the packages in `your_env`.

> why there is a blank line starting with the symbol "#"?

No problem with that... just formatting.

> Now, I have a problem that when I open a jupyter Notebook, there is a hint message:

You probably create that notebook with an old version of `nb_conda_kernels`... next time you open it, it should be OK... and any new notebook should work OK.

**Comment by iamchiragsharma** [comment]
![capture](https://user-images.githubusercontent.com/29746593/43672231-4d194f06-97c7-11e8-8c50-c6be383a0743.PNG)


Can anyone explain me why three env are created and which is which?
