### ISSUE TITLE
Default cell width should be 79 characters or 99 characters

### ISSUE THREAD

**Issue by JasonSanchez** [jupyter/notebook#1853]
[PEP 8](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) says the maximum line width should be 79 characters or 99 characters.

Currently the max width is 119 characters. Reducing the width of the browser window causes the cell to snap to 95 character width and then to 75 character width before getting arbitrarily smaller. It would be much preferred if it snapped to 119 characters and then 99 characters and then 79 characters.

**Comment by Carreau** [comment]
Hi there, 

Thanks for the suggestion, pep 8 also says:

> A Foolish Consistency is the Hobgoblin of Little Minds
> One of Guido's key insights is that code is read much more often than it is written. The guidelines provided here are intended to improve the readability of code and make it consistent across the wide spectrum of Python code. As PEP 20 says, "Readability counts".

So pep8 is mostly a guideline, and is often recommended to be applied in spirit, see for example [this talk](https://www.youtube.com/watch?v=wf-BqAjZb8M) from Raymond Hettinger one of core Python developer. 

Also the notebook is not only for Python so we can't (and won't) enforce python-only rules. 
Some extensions allow you to show a ruler to help you organize your code. 

We can try to keep that as a suggestion though and might refine the snapping on future revisions.

Thanks.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days and an answer was provided. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
