### ISSUE TITLE
add /health_check for load balancers

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#1857]

**Comment by takluyver** [comment]
I'm not quite sure what this means - is it related to tmpnb or jupyterhub, perhaps?

**Comment by cailiang9** [comment]
Thanks! we have our own docker spawner which is hard to integrate with tmpnb. So I run notebook directly and need a /health_check.

**Comment by takluyver** [comment]
I'm still not sure what you're after. What information would be in the response of `/health_check`? What are you trying to load balance? Sorry if this is obvious relative to tmpnb or something - I don't know much about that part of the project.

**Comment by ellisonbg** [comment]
Are you interest in a /health_check REST endpoint that a load balancer can hit to get the status of the notebook server?

**Comment by danielfrg** [comment]
I +1 a `/health` endpoint. This is useful in also for some schedulers for example for a liveliness check for Kubernetes (https://lukemarsden.github.io/docs/user-guide/liveness/).

I personally like what Elasticsearch does: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html - but in general a return code of 200 would be good enough in most cases.

**Comment by gsemet** [comment]
would be really useful

**Comment by afaq404alam** [comment]
Do we have any updates on this? It would be really useful to have a `/heatlh` endpoint which just simply returns status `200`.

**Comment by skully** [comment]
Any update regarding this issue?

**Comment by mgax** [comment]
For a quick-and-dirty solution, the `/static/favicons/favicon.ico` URL always returns a 200 response.

**Comment by FlorinAndrei** [comment]
> For a quick-and-dirty solution, the `/static/favicons/favicon.ico` URL always returns a 200 response.

I've tried that with the latest version and I get 404.

Having a plain, dumb URL that always returns code 200 would be really useful.

**Comment by afshin** [comment]
You can hit `/api` and it will return a JSON response that contains the `version` of the `notebook` package and it does not require authentication.

**Comment by FlorinAndrei** [comment]
> You can hit `/api` and it will return a JSON response that contains the `version` of the `notebook` package and it does not require authentication.
> 
> cf.
> 
> https://github.com/jupyter/notebook/blob/6fe9755971dba3357054766806d56cb8c6c1bca7/notebook/base/handlers.py#L851-L855

That does it. Folks, we have a solution. A good endpoint to check the health of a Jupyter Notebook instance is simply `/api` - it returns 200 OK and not much else.

```
# curl -v http://localhost:8888/api
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /api HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: TornadoServer/6.1
< Content-Type: application/json
< Date: Fri, 25 Jun 2021 18:50:32 GMT
< X-Content-Type-Options: nosniff
< Content-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'
< Etag: "846b4f8f33764576d6b3026face5fa7e4d0bd57b"
< Content-Length: 20
```

**Comment by kevin-bates** [comment]
Thanks for the tip @afshin - closing.
