### ISSUE TITLE
The handler for /kernelspec/name needs to unescape

### ISSUE THREAD

**Issue by blink1073** [jupyter/notebook#1859]
In `jupyterab/services`, we are url encoding the name of the kernel spec, but the server is not using `utils.url_unescape` on the name, resulting in a 404 if there are escaped characters.

cf https://github.com/jupyterlab/jupyterlab/issues/1018#issuecomment-257007599

**Comment by takluyver** [comment]
@blink1073 do you have time to make a pull request for this?

**Comment by blink1073** [comment]
Yep, #1895.
