### ISSUE TITLE
Fenced code indentation issues with $.

### ISSUE THREAD

**Issue by mforbes** [jupyter/notebook#186]
In a notebook, the following indented code cell is not properly rendered:

``````
1. This code is in a enumerated list so the block needs to be indented:

   ```bash
   laptop ~$ ssh-agent bash
   laptop ~$ ssh-add
   ``` # This comment required to prevent github from treating this as the closing fence.

2. If the previous block is not indented, this will restart as number 1.
``````

This renders roughly as as

```
1. This code is in a enumerated list so the block needs to be indented:

    laptop ~$ ssh-agent bash
        laptop ~$ ssh-add
...
```

where the second code line is indented.  It has something to do with the `$`.  The indented block is probably not being registed as a proper code block to whatever looks for equations.

**Comment by hellpanderrr** [comment]
It's the dollar sign.  You can use the "＄" sign instead or try this:
```
1. This code is in a enumerated list so the block needs to be indented:

   ```bash
   laptop ~```$``` ssh-agent bash
   laptop ~```$``` ssh-add
   ``` # This comment required to prevent github from treating this as the closing fence.

2. If the previous block is not indented, this will restart as number 1.
```

**Comment by Horta** [comment]
Thanks for the ＄ substitute. Works for now =)

**Comment by JamiesHQ** [comment]
@mforbes : We're doing a little housekeeping on our issue log and I noticed this thread from 2015. Has this issue been resolved to your satisfaction and can it be closed? thanks!

**Comment by mforbes** [comment]
It appears to still be an issue with notebook server is 5.0.0.

**Comment by JamiesHQ** [comment]
thanks @mforbes ! 

cc'ing @gnestor who is leading notebook development.

**Comment by gnestor** [comment]
@mforbes The notebook uses the [marked](https://github.com/chjj/marked) library to render markdown, so I think that an issue should be opened there. Here is a similar issue that's currently open on marked: https://github.com/chjj/marked/issues/712
