### ISSUE TITLE
Create AppVeyor account for Jupyter

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/notebook#1862]
It currently runs on @Carreau's account and I'm unable to retrigger the builds.

Side note: I paid for extra workers on the nteract account, which didn't seem too bad compared to the pain and time it saves per day. :smile:

**Comment by Carreau** [comment]
I'm confused . It runs on me?

**Comment by rgbkrk** [comment]
https://ci.appveyor.com/project/Carreau/notebook/build/1.0.92

The project namespace on appveyor is under Carreau.

**Comment by Carreau** [comment]
> https://ci.appveyor.com/project/Carreau/notebook/build/1.0.92
> 
> The project namespace on appveyor is under Carreau.

I have no clue why this is. I have no clue what to do.

**Comment by Carreau** [comment]
I clicked on a lot of places. Does it work ?

**Comment by rgbkrk** [comment]
Went ahead and created a jupyter org account, added a few people as admins (feel free to add more): https://ci.appveyor.com/project/jupyter/notebook

I'll be back in a bit.

**Comment by Carreau** [comment]
> Went ahead and created a jupyter org account, added a few people as admins (feel free to add more): https://ci.appveyor.com/project/jupyter/notebook
> 
> I'll be back in a bit.

Cool, I was unable to do it for whatever reason.

**Comment by rgbkrk** [comment]
> Cool, I was unable to do it for whatever reason.

[AppVeyor has a lot of setup to get an org account configured](https://www.appveyor.com/docs/team-setup/).

**Comment by minrk** [comment]
Thanks!
