### ISSUE TITLE
Document comms

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#1869]
Answering a SO question, I realised that we don't appear to have any docs on how to use comms.

**Comment by rgbkrk** [comment]
It is pretty open ended.

**Comment by takluyver** [comment]
It is! I'd be happy to close it once we have

- [ ] some explanation of what comms are
- [ ] how to register targets in Python, connect them from JS, and send messages both ways.
- [ ] link to the messaging spec docs about comm messages for authors of other kernels.

**Comment by willingc** [comment]
Hey @takluyver, Thinking this was the SO question: http://stackoverflow.com/questions/40352628/messaging-and-jupyter-notebooks

If you or others want to do a detailed outline, that would be a helpful start. Alternatively links to the above 3 points in the code or other docs. Thanks.

**Comment by rgbkrk** [comment]
I'm _very_ happy to pair on this or even explore it from a protocol level (see https://github.com/jupyter/jupyter_client/issues/198). I'm not a good one to speak to for the JS APIs on jupyter/notebook for comms as we're taking a slightly different approach in nteract: https://github.com/nteract/nteract/pull/840

**Comment by takluyver** [comment]
I'm going to try to make some basic docs now. If you want to take it further, that would be great.

**Comment by willingc** [comment]
@takluyver If you make bullets, I'm happy to wordsmith. We can certainly iterate 👍

**Comment by takluyver** [comment]
Closing as we now have some docs - that doesn't stop us improving them more!
