### ISSUE TITLE
JSmol context menu does not function in Jupyter notebook

### ISSUE THREAD

**Issue by paulmasson** [jupyter/notebook#1872]
I noticed in August in the context of a SageMath [question](https://ask.sagemath.org/question/34559/how-to-export-a-3d-plot-to-a-jpgpng-file-osx/) that the right-click context menu for JSmol does not expand to reveal options for a Jupyter notebook open in Safari. The context menu does expand properly in the legacy SageMath notebook, so this does not appear to be an issue with JSmol itself.

To replicate the problem, create any 3D plot such as

    parametric_plot3d([cos(x),sin(x),x/10],(x,0,10))

right click on the resulting image and hover over any context menu item.

Is this a known problem?

**Comment by takluyver** [comment]
It's not a known problem, as far as I recall. I don't think any of us are familiar with JSmol. Can you look into:

- Are there any errors in the JS console when the JSmol thing is displayed or when you right click?
- What does it do in Javascript to set up a context menu? I don't know much about that stuff, but maybe other people will recognise an issue with what it's doing.

**Comment by paulmasson** [comment]
No messages in the console regarding JSmol.

I don't know much about JSmol myself, but there is an active [SageMathCell discussion](https://groups.google.com/forum/#!topic/sage-cell/-g1AMBs0SdE) regarding encoding issues for languages other than English. It appears that the context menu is set up server side using PHP.

**Comment by takluyver** [comment]
That appears to be about a Java implementation called Jmol (as opposed to JSmol).

**Comment by paulmasson** [comment]
SageMath does use the Java version from the command line, but the one embedded in Jupyter notebooks is the JavaScript version. The JavaScript version has PHP and Java files as part of its underlying source, and the maintainer of SageMathCell has been able to get things to (mostly) work in the pages served up. Perhaps this issue has to do more with how the SageMath backend translates things than the Jupyter notebook itself.

**Comment by takluyver** [comment]
Sorry, I don't properly understand the relations between Jmol, JSmol and SageMath. I think you'll need to talk to the developers of at least one of those projects to work out what's going on with right click menus and how Jupyter might be breaking it.

**Comment by takluyver** [comment]
Feel free to follow up here once there's more info about what is going
wrong. :-)

**Comment by dimpase** [comment]
any progress on this? It breaks animations in Sage with Python 3

**Comment by dimpase** [comment]
@paulmasson - could you perhaps re-open this issue?
