### ISSUE TITLE
Timeout waiting for kernel_info reply from .... Windows 10 Bash

### ISSUE THREAD

**Issue by Carpetfizz** [jupyter/notebook#1876]
Installed Jupyter Notebook via conda. Started Jupyter notebook in a folder and navigated to `localhost:8888` on Google Chrome. Tried making a new notebook using `Python [conda root]` and `Python [default]`, both fail with the following error:

```
[I 14:52:11.617 NotebookApp] Creating new notebook in
[I 14:52:13.240 NotebookApp] Kernel started: 41cd4ec6-cba6-426c-8286-fbd393553576
Invalid argument (src/tcp_address.cpp:172)
[I 14:52:16.239 NotebookApp] KernelRestarter: restarting kernel (1/5)
Invalid argument (src/tcp_address.cpp:172)
[I 14:52:19.337 NotebookApp] KernelRestarter: restarting kernel (2/5)
[W 14:52:23.570 NotebookApp] Timeout waiting for kernel_info reply from 41cd4ec6-cba6-426c-8286-fbd393553576
```

Running Windows 10, executed all commands from Ubuntu Bash for Windows 10. Notebook inside folder on Windows 10 filesystem from Bash.

**Comment by takluyver** [comment]
See #1331. There are ways to make it work in Linux-on-Windows if you're keen to do so, but in general I'd still recommend installing Jupyter on Windows directly for most users.
