### ISSUE TITLE
Assignment 1 Data Programming Irene Volpe

### ISSUE THREAD

**Issue by irefox** [jupyter/notebook#1878]
[assignment 1 saved.pdf](https://github.com/jupyter/notebook/files/577877/assignment.1.saved.pdf)

**Comment by takluyver** [comment]
Hi! It looks like you're trying to submit work for a class. This is not the right place to do that. Unfortunately, I can't help you find the right place; I don't know what class you're taking or even what school you're at. If you're having trouble finding the submission site, please ask someone at your school.

This site is for reporting bugs in the Jupyter Notebook software. If you think there is a bug which is affecting your assignment, please describe it.
