### ISSUE TITLE
ipython notebook import error

### ISSUE THREAD

**Issue by wlsherica** [jupyter/notebook#188]
I have installed python2.7 and pyzmq jinja2 tornado mistune jsonschema pygments terminado on mac osx.
After I typed ipython notebook in terminal, I got this error,
ImportError: No module named jupyter_notebook.notebookapp

Do anybody know how to fix this? Thanks

**Comment by takluyver** [comment]
That sounds like you've got some unreleased version of ipython from git.

If you want to use IPython, we'd recommend using version 3.2 (the latest release) for now - we're splitting pieces up, so it's trickier to install from master until we've released them all.

If you're interested in working on IPython/Jupyter itself, you need to get the latest version of all the pieces. See the instructions [in the README of this repository](https://github.com/jupyter/notebook#jupyter-notebook) to get started.

**Comment by wlsherica** [comment]
@takluyver  Thank you for your reply.
It means it's better to use IPython with python3.2? 
I'm interested in IPython Jupyter notebook. Should I need to delete them all then rebuild all packages again?

**Comment by takluyver** [comment]
Sorry, I meant IPython 3.2, not Python 3.2 (I know this is confusing). IPython currently works with Python 2.7 and Python 3.3 or higher.

For now, the easiest way to install it is to `pip install ipython[notebook]` (see [the install page](http://ipython.org/install.html)).

'Jupyter' is the name of the next version of IPython, but we're still working on that, so it's not easy to install at the moment. It will initially look and work a lot like the current version of IPython.
