### ISSUE TITLE
latex error not shown with %matplotlib notebook

### ISSUE THREAD

**Issue by mfittere** [jupyter/notebook#1881]
Hello, 

In case of an error in a latex formula,e.g.
`plt.ylabel(r'$\thet$') # as \thet is not known as a command`
no error is reported instead the notebook switches constantly to mode "busy" and back. This only occurs with
`%matplotlib notebook`
Instead with
`%matplotlib inline`
the following error message is shown:
```
ValueError:
\thet
^
Unknown symbol: \thet (at char 0), (line:1, col:1)
```
Is it possible to also post the error message in interactive mode, explicitly with `%matplotlib notebook`?

**Comment by takluyver** [comment]
Pinging @tacaswell

**Comment by tacaswell** [comment]
I have a good guess as to what is going wrong and it is due to the auto-redraw on stale logic.

post-execute event checks if any figures are stale -> figure is stale -> triggers redraw -> redraw fails -> the figure is still stale ->  post-execute event checks if any figures are stale -> ...

**Comment by takluyver** [comment]
So that would be a mpl issue? Feel free to use this thread to work out the details, and let us know if we can do anything on our side.

**Comment by tacaswell** [comment]
What are the conditions when 'post_execute' hook is called?  

Fixing the infinite loop is relatively strait forward (just mark the figure as not stale, even if drawing failed), but I am not fully convinced _correct_.

Getting the exception to propagate across is going to be more difficult an the draw is run via a callback from the js side via a comm we have set up (this is the same reason of the other issues where tracebacks and `print` calls from mouse / keyboard events do not make it back out to the notebook.  These issues _should_ be addressed by `ipympl`.
