### ISSUE TITLE
Can the look of jupyter notebook be customized in any way according to kernel status?

### ISSUE THREAD

**Issue by BoPeng** [jupyter/notebook#1883]
I have developed a [Script of Scripts](https://github.com/BoPeng/SOS) kernel that allows switching between different kernels using magics such as `%use R`, and `%with R`. It is working reasonably well but there is a small problem with the current implementation, namely there is no hint that which kernel is currently active. Is it possible to, for example, change the background of notebook according to current kernel? 

In addition, it would be useful if I can mark each cell with the kernel used so that I can get a notebook with cells in different colors. For example

```
[white SoS cell]
    import pandas as pd
    data = pd.read_excel('data.xls')
[purple R cell]
    %with R -i data -o m
    m <- apply(data, 1, median)
[white SoS cell]
    print(m)
```

I have a feeling that this could be done in javascript, but I currently have no idea how the browser (javascript) interacts with the kernel. Any suggestion or code example would be greatly appreciated.

**Comment by BoPeng** [comment]
I have tried but could not find any answer on how the jupyter client and server (kernel) work.

1. How to manipulate cell `metadata`? I can see that some nbextensions can set metadata and the metadata could be saved in `.ipynb`, but I am not sure how the kernel can access cell meta information.
2. How does `user_expressions` work? I mean, how the frontend determines which `user_expressions` to evaluate? The `user_expressions` looks to me the only way for the front and backend to exchange meta information, but I am not sure how to control the frontend.

In the end, what I would like to do, in the context of [Script of Scripts](http://vatlab.github.io/SOS) is to **store and use kernel information in each cell**. More specifically,

1. The frontend reads `metadata` of a cell, and send the kernel information to `do_execute` (via `user_expression`). If this is possible, the frontend can also use different color to display cells created by different kernels.
2. The kernel decides which subkernel to use to evaluate the `code` (current active kernel for new cells and creating kernel for existing cells), and send result, as well as `kernel` information to frontend (through `user_expression`)?
3. The frontend saves kernel info in `metadata` of a cell. The information will be used when the cell is executed again.

I would appreciate it if anyone can let me know if these are at all possible and point me to relevant documentation or source code. Thanks.

**Comment by takluyver** [comment]
> How to manipulate cell metadata? I can see that some nbextensions can set metadata and the metadata could be saved in .ipynb, but I am not sure how the kernel can access cell meta information.

The kernel can't directly manipulate cell metadata: by design, it doesn't know about the document the code is part of. You can display Javascript output which will manipulate cell metadata, or even set up a comm to exchange data between the frontend and the kernel.

> How does user_expressions work? I mean, how the frontend determines which user_expressions to evaluate? The user_expressions looks to me the only way for the front and backend to exchange meta information, but I am not sure how to control the frontend.

I don't think the notebook uses `user_expressions`, and I'm not even sure that any of our frontends do. It was specified in the protocol to allow custom prompts in the frontend,  but we never got round to implementing that, and it hasn't proved very useful for anything else, as far as I know.

You might be best off looking into [comms](http://jupyter-notebook.readthedocs.io/en/latest/comms.html) to allow custom messages between the frontend and the kernel.

**Comment by BoPeng** [comment]
Great! Thank you very much for your info and I can now send information from the kernel to frontend, update frontend style accordingly and save to metadata. This will greatly increase the usability of the SoS kernel.

I have two related issue though, hopefully you have some quick answers for them.

1. The SoS kernel uses magic `%use R` etc to switch kernel so I can only know which kernel was actually used after the completion of the execution. When I send the 'actual used kernel' information to the frontend, I am having trouble finding the cell that was just executed. `IPython.notebook.get_selected_cell()` does not have to be the just executed cell, using `execution_count` or `code` to look up cell do not work well because `execution_count` might not be immediately available in the frontend after execution, and multiple cells might have the same `code`. Is there an easy way to find the just executed cell so that I can set metadata to the right one? The cells have field `last_msg_id` but I am not sure what id it is (is it for the `execution_result` message?) and how to get the ID from the kernel.

2. How can I send metadata to the kernel when I execute a cell? Do I have to hijack the frontend `execution` code to insert metadata to the code executed? It would be nice to have some `event` that can trigger the frontend to send the metadata to kernel through `Comm`.

3. I am also having trouble setting the cell style from cell metadata, but I suppose I can learn it from nbextensions such as [exercise2](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/exercise2).

Thank you again for your help, you know, a simple hint to the right direction can save me hours of searching and code digging.

**Comment by takluyver** [comment]
Maybe it would actually be better to use the metadata in `execute_request` and `execute_reply` messages. All Jupyter messages have a metadata part where you can put any information you want. The downside is that that may be a bit trickier to access from an extension in the frontend. I don't know that code very well, unfortunately.

**Comment by BoPeng** [comment]
I think the `execute_request` is triggered by the [frontend execute function](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/codecell.js#L303) so we have to insert the metadata in that function. The particular feature I want to do is that if a cell was execute by R and has `cell.metadata.kernel="R"`, I need to wrap the code with

```
%with R
code
```

to make sure the code is re-executed in the `R` kernel. I will see if I can override [CodeCell.prototype.get_text](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/codecell.js#L491) to achieve this.

**Comment by BoPeng** [comment]
Because overriding `CodeCell.prototype.get_text`has a number of side effects (e.g. the added meta information would be saved to notebook), I ended up modifying `cell.kernel.execute` as follows

```
        var my_execute = function (code, callbacks, options) {
            "use strict"
            var cells = IPython.notebook.get_cells();
            for (var i = cells.length - 1; i >= 0;  --i ) {
                // cells being executed would have input prompt '*' according
                // to this.set_input_prompt('*') before execute is called.
                // Also, because a cell might start executing without a previous cell
                // being finished, we should start from reverse and check actual code
                // A magic is used to send meta information and cell index to the kernel
                if (cells[i].input_prompt_number == '*' && code == cells[i].get_text()) {
                   return this.orig_execute(
                        "%softwith " + cells[i].metadata.kernel + " --cell " + i.toString() + "\n" + code,
                        callbacks, options)
                }
            }
        }
        // override kernel execute with the wrapper.
        IPython.notebook.kernel.orig_execute = IPython.notebook.kernel.execute
        IPython.notebook.kernel.execute = my_execute
```

The code also sends cell index to the kernel which also solves problem 1 (locate just executed cell). It is a hack and it is not particularly efficient (search notebook for each `execute` call) also I would be happy to switch if there is a better way to send meta data to kernel for execution (it looks like `user_expression` could be used for this).

**Comment by quinot** [comment]
Hi, for some solutions to pass code cell metadata to the kernel, you may be interested in PR #3391.
