### ISSUE TITLE
list running servers occasionally gives wrong information

### ISSUE THREAD

**Issue by jim22k** [jupyter/notebook#1886]
`notebook.notebookapp.list_running_servers()` will occasionally give wrong information, listing servers which are no longer running.

I traced this down to having outdated nbserver-xxxx.json info files in my runtime dir. It seems that there is a bug in the `os.unlink` call which tries to remove these old files.

Normally, having the old files hanging around isn't a problem, but on the rare chance that the pid becomes active again from another process, list_running_servers will show that outdated information as a currently running server. This becomes a problem for things like `nbopen()` which attempt to use existing servers rather than spawn new ones.

**Comment by takluyver** [comment]
Fixed by #1887
