### ISSUE TITLE
Interrupt only stops current cell and remaining ones are still executed

### ISSUE THREAD

**Issue by MarcelSimon** [jupyter/notebook#1889]
Suppose I executed all cells in a Jupyter Notebook, and want to interrupt the computation in the middle. "Kernel interrupt" only interrupts the execution of the current cell, but then immediately continues with all remaining cells. Instead, I do not want to execute all remaining cells after hitting "Kernel interrupt". This seems to be a bug.

I am running version 4.2.3 with Python 3.5.2, packaged by conda-forge

**Comment by takluyver** [comment]
Thanks! We're at a meeting this week, so it might be a few days before we get to it. If you don't hear anything in a week or so, ping us to remind us about it.

(Background for other people reading this - Marcel asked this as a [question](http://stackoverflow.com/questions/40554446/how-to-stop-execution-of-all-cells-in-jupyter-notebook) on SO, and I asked him to make it an issue)

**Comment by MarcelSimon** [comment]
I'd like to add a simple way to reproduce: open https://try.jupyter.org/ and open a python notebook. Add a cell with `while True: pass` followed by another cell containing `print 'not interrupted'`. Execute both and hit the interrupt button

**Comment by takluyver** [comment]
I see it on try.jupyter, but doing exactly the same thing in my local notebook, it works as expected (the second cell is not run). Do you also see it somewhere other than try.jupyter?

@minrk @rgbkrk - is there anything about the tmpnb architecture that might affect this?

**Comment by minrk** [comment]
I believe it's [this one](https://github.com/ipython/ipykernel/pull/190), fixed in 4.5.1, but try.jupyter is still using ipykernel-4.5.0.

**Comment by takluyver** [comment]
Thanks, Min. @MarcelSimon, if you're seeing this locally, can you upgrade to ipykernel 4.5.1 and see if it's fixed?

**Comment by MarcelSimon** [comment]
Indeed, ipykernel 4.5.1 fixed that problem. Thanks!
