### ISSUE TITLE
Change tab icon, title, while running a task

### ISSUE THREAD

**Issue by ghost** [jupyter/notebook#1893]
I am running ML algorithms on ipython notebooks frequently and since my system is not so up to date it takes some time. During this time I switch to other tasks of mine and switch tab frequently.

I would like to know whether a task is being executed still or finished its execution by only looking to the tab icon, title or even color.

Wdytk?

**Comment by takluyver** [comment]
In #1837, we added machinery to change the tab icon when the kernel is busy. That's currently slated to land in notebook 5.0.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
