### ISSUE TITLE
Blank screen when starting notebook

### ISSUE THREAD

**Issue by JCEmmons** [jupyter/notebook#1894]
When running from the latest source from github ( as of 2016-11-14 ),  when starting up the notebook, instead of the main screen, I get a blank screen.  Examination of the JS debugging info yields the error:

```
TypeError: root is undefined
Looks to be in function function __webpack_require__(moduleId) {
```

Is there some piece that I am missing here that isn't documented? I've tried this on 2 different machines with the same result.

**Comment by takluyver** [comment]
How did you install it? We have a Javascript build step now, so it doesn't run directly from source without some kind of installation. See the [contributor guide](http://jupyter-notebook.readthedocs.io/en/latest/contributing.html) if you want to set up a development copy from Github.

**Comment by JCEmmons** [comment]
I followed the instructions on the contributor guide - per http://jupyter-notebook.readthedocs.io/en/latest/contributing.html#installing-the-jupyter-notebook .  I've run development copies in the past with no problems. So I'm trying to figure out what changed.....

**Comment by JCEmmons** [comment]
I also rebuilt the js and css with "python setup.py js css" - no help....

**Comment by takluyver** [comment]
Maybe @Carreau or @minrk will have an idea.

```
TypeError: root is undefined
```

**Comment by minrk** [comment]
I haven't seen that one. For me, it's "when in doubt, clean up and try again", which would be:

    git clean -xfd # deletes everything not tracked by git
    git pull # update
    pip install -vv -e . # redo dev install

**Comment by JCEmmons** [comment]
Did all this - still no help.  BTW, I can run 4.2.3 from source with no problems, so it's got to be something between then and now.

**Comment by JCEmmons** [comment]
Someone please help me on this, as I'm stumped.  The stack trace leads to the following in static/tree/js/built/1.main.min.js

```javascript
	//     Underscore.js 1.5.2
	//     http://underscorejs.org
	//     (c) 2009-2013 Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors
	//     Underscore may be freely distributed under the MIT license.
	
	(function () {
	
	  // Baseline setup
	  // --------------
	
	  // Establish the root object, `window` in the browser, or `exports` on the server.
	  var root = this;
	
	  // Save the previous value of the `_` variable.
	  var previousUnderscore = root._; 
```

The error says "root is undefined"....  I find all this a bit curious since npm thinks my underscore.js is at 1.8.3, not 1.5.2.

**Comment by Carreau** [comment]
You might have a global [cache of npm modules](https://docs.npmjs.com/cli/cache), so `npm install` get the wrong version... You probably want to clean your install aggressively (pip uninstall several time to be sure) then search your hard drive for `notebook` (and `node_modules` ?) and nuke relevant things if needed.

Then I would try to reinstall. But I'm baffled as to why you would get the wrong underscore version, and how that's possible, but I haven't keep up with npm in a long time. 

@blink1073 have you seen something similar on JupyterLab ?

**Comment by blink1073** [comment]
I've noticed that `npm install` has recently stopped automatically rectifying itself with `package.json`, though haven't yet figured out why.  I've been manually removing the offending package from `node_modules`.

**Comment by JCEmmons** [comment]
This is the same issue as reported in #1495 .  I think I may have a fix.....
