### ISSUE TITLE
 Jupyter notebook kernels do not launch in notebook's directory

### ISSUE THREAD

**Issue by MathieuSchopfer** [jupyter/notebook#1897]
(Following a [discussion](http://stackoverflow.com/questions/40403700/jupyter-notebook-kernels-do-not-launch-in-notebooks-directory) on stackoverflow.)

The notebook application starts correctly and in the correct directory. But when I open a notebook, the python kernel is launched in `~/user` and not in the notebooks directory (as it used to be).

This problems seems to be happening since I encrypted my home folder.

Configuration:
- Jupyter 4.2.0
- notebook 4.2.3
- Linux Mint 18

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
