### ISSUE TITLE
setup.py develop for nbconvert  'gnutls_handshake() failed: Handshake failed'

### ISSUE THREAD

**Issue by Dumbris** [jupyter/notebook#190]
Environment:
Ubuntu 14.10
Python 2.7.6 (default, Mar 22 2014, 22:59:56)

I am trying to install your project. But I am stuck on step "pip install -r requirements.txt -e ."

```
 running css
    Failed, trying again with PycURL to avoid outdated SSL.
    Failed to download css from https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css: (35, 'gnutls_handshake() failed: Handshake failed')
    Downloading CSS: https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css
    error: Need Notebook CSS to proceed: nbconvert/resources/style.min.css
```

rycurl is installed 
also i have tring different ssl libs with no success.
export PYCURL_SSL_LIBRARY=[openssl|gnutls|nss]

I understand this is gnutls + rycurl + python problem. I am just searching for workaround.

**Comment by minrk** [comment]
This is due to a security bug in old versions, and should be avoided if you have pycurl installed, or have a reasonably secure version of Python 2.7. Is your system up to date? WHen did you install pycurl?

You can fetch the file manually:

```bash
curl https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css > nbconvert/resources/style.min.css
```

**Comment by Dumbris** [comment]
Issue solved after Ubuntu upgrade
