### ISSUE TITLE
Question: How do I profile performance bottlenecks?

### ISSUE THREAD

**Issue by Winterflower** [jupyter/notebook#191]
Hello Jupyter community, 
apologies for asking this here. I've been trying to find some information about performance profiling online but my googling skills have failed me. 
I use the Jupyter notebook daily to plot and analyse timeseries (mainly using seaborn and pandas).
Sometimes when the number of datapoints exceeds a certain amount, the kernel starts to hang (10+ minutes) or dies. 
Have there been any efforts to document the performance of the kernel for large scale data visualization/analysis? I would like to establish some guidelines to help me decide when plotting something using the notebook is not a good idea.

**Comment by minrk** [comment]
Depending on what you are doing, mostly standard Python profiling tools should work, such as the stdlib [profile](https://docs.python.org/3/library/profile.html) module, and [line_profiler](https://github.com/rkern/line_profiler).

Some operations may cause hanging in the *browser* (e.g. SVG plots with too many elements), in which case using the browser's own profiler tools is a good idea.

**Comment by Carreau** [comment]
Closing as nothing to do here.
