### ISSUE TITLE
What should I do if I want to open csv file with a new approach

### ISSUE THREAD

**Issue by iteratorlee** [jupyter/notebook#1913]
I want to add a new approach to open csv file using pandas. What should I do just by adding a plugin without modifying source code such as fileio.py->_read_file()

**Comment by ellisonbg** [comment]
Hi, the best place to ask this questions is likely over on the pandas GitHub org, but maybe we can help a bit. Do you have pandas installed? If so, you can read a data from as such:

```python
import pandas as pd

df = pd.read_csv('filename.csv)
```

This notebook may also help:

http://nbviewer.jupyter.org/github/jvns/pandas-cookbook/blob/v0.1/cookbook/Chapter%201%20-%20Reading%20from%20a%20CSV.ipynb
