### ISSUE TITLE
Allow code to be executed in markdown blocks and insert result

### ISSUE THREAD

**Issue by theideasmith** [jupyter/notebook#1915]
I was thinking that for researchers who are doing analysis from within jupyter it would be really nice if the results from some computation could be automatically pasted into the textual discussion of the results. Assuming the delimiter \& is used 

**Example**
Consider the following function: 

```
from math import sin, pi
def f(x): return sin(x)
```

Let us now compute \&`f(pi)`\& `=> 0`

Here we've actually called a function from within a markdown block and inserted its result in place of the function call.

**Comment by takluyver** [comment]
We've discussed this multiple times, and there's an [extension](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/python-markdown/readme.html) that tries to do it. We don't want to implement it in the notebook directly until CommonMark agrees on a decent extension syntax for Markdown, so we're not just introducing extra ad-hoc additions to the markdown syntax.

**Comment by theideasmith** [comment]
Ok thanks so much!

**Comment by gnestor** [comment]
One other option is to use `IPython.display.Markdown` in a code cell:

![image](https://cloud.githubusercontent.com/assets/512354/25464012/f434c52c-2aae-11e7-9171-541fb0f6601e.png)

```py
from IPython.display import Markdown

one = 1
two = 2
three = one + two

Markdown("# Title")
Markdown("""
# Math
## Addition
Here is a simple addition example: {one} + {two} = {three}
""".format(one=one, two=two, three=three))
```

There is an active discussion happening on ipython (https://github.com/ipython/ipython/issues/2958) so let's close this and move the discussion over there.

**Comment by drorata** [comment]
@takluyver Is there any update from the CommonMark front?

**Comment by kitaev-chen** [comment]
I think you need this:

neuron for Visual Studio Code
https://marketplace.visualstudio.com/items?itemName=neuron.neuron-IPE
https://www.youtube.com/watch?v=amuV0z9eVg4

it's powerful but still a little bit hard to use. hopefully, it can be better in the future so we can write jupyter notebook in vs code.
