### ISSUE TITLE
Possibility to launch notebook via .desktop file

### ISSUE THREAD

**Issue by tomspur** [jupyter/notebook#1922]
There is a current feature request at Fedora (see [bugzilla bug](https://bugzilla.redhat.com/show_bug.cgi?id=1275800), were a `.desktop` file is proposed to start the notebook:

```
[Desktop Entry]
Name=Jupyter
Exec=sh -c "ipython notebook"
Terminal=false
Type=Application
Icon=jupyter-sq.png
Categories=GNOME;GTK;
StartupNotify=true
```

Do you think this is a good idea and would you like to support this also when installing this package?

**Comment by minrk** [comment]
Do you mean the Fedora package, or the Python package? I think it would be great for this to be part of the fedora/debian package (note: it should be `jupyter notebook` not `ipython notebook`).

**Comment by takluyver** [comment]
For reference, I have a .desktop file in nbopen, which is principally to support opening .ipynb files from a GUI file explorer (so it doesn't actually show up in the menu):

https://github.com/takluyver/nbopen/blob/master/nbopen/nbopen.desktop

**Comment by tomspur** [comment]
I mean the Python package. I would prefer using a desktop file with an proposed and supported startup method by you. Maybe something like the `nbopen.desktop` file would work in this case too.
(yes, that bug and the Fedora ipython package is a bit older, it will be `jupyter` and not `ipython` at the end :))

**Comment by minrk** [comment]
Adding `jupyter notebook %f` would be good for launching a notebook server in a given directory. It would be even better if it did what nbopen does, and launches IFF one doesn't already exist, and opens if not.

**Comment by Amr-Ibra** [comment]
This issue is now closed by https://github.com/jupyter/notebook/pull/6010 and https://github.com/jupyter/notebook/pull/6099.

**Comment by kevin-bates** [comment]
Good point - thank you @Amr-Ibra!
