### ISSUE TITLE
Add 'Clear current cell' to Keyboard shortcuts

### ISSUE THREAD

**Issue by abast** [jupyter/notebook#1925]
I frequently have to delete the output of cells (e.g. if I interrupt a calculation using multiprocessing, which usually leads to a very long error stack) and therefore use the following clickpath:

`Cell --> Current Outputs --> Clear`

It would be great to have a keyboard shortcut to this functionality, since it would speedup something users might do quite frequently. ([It has also been requested on stackoverflow some time ago](https://stackoverflow.com/questions/39924826/keyboard-shortcut-to-clear-cell-output-in-jupyter-notebook))

**Comment by arundasan91** [comment]
@abast , This would be so great. I come across that a lot too !

One way I get through it is to press `ESC` then `R` to make the cell Raw and then `Y` to make it a code cell again.

Now, `ESC` -> `R` -> `Y` is natural to me whenever I want to delete the outputs of the cell :)

Would love to have a shortcut or a click-path as you mentioned !

**Comment by takluyver** [comment]
@Carreau has been working on an interface to allow easily setting up custom keyboard shortcuts. Matthias, is that going to be in 5.0?

**Comment by Carreau** [comment]
It is (see help menu) but I think it is broken right now.

**Comment by bribroder** [comment]
It would be awesome to have a shortcut for clearing all cells as well as a single cell

**Comment by Carreau** [comment]
In current master you can setup your own shortcut in the UI. 
Example of Ctrl-O, Ctrl-Shift-O for one cell/ all cells:
![screen shot 2017-02-06 at 12 31 55](https://cloud.githubusercontent.com/assets/335567/22665089/5418f5f6-ec68-11e6-8501-1c0fa5008fd9.png)

Closing as customisable now.
