### ISSUE TITLE
Newline at end of data-dir string

### ISSUE THREAD

**Issue by DancingQuanta** [jupyter/notebook#1937]
I have encountered a problem on cygwin on Windows where I ran the following command
```
mkdir -p $(jupyter --data-dir)/nbextensions
```
which is supposed to create the directory `%APPDATA%/jupyter/nbextensions`.
However the resulting directory is `%APPDATA%/'jupyter'$'\r'/nbextensions`.
This looks like a newline got attached to end of path string which you can see if you redirect the output of `jupyter --data-dir` to file 
```
jupyter --data-dir > test.txt
```
and viewing the file in Notepad shows that there are two lines instead of one.

Please remove this newline as it is not a good practice.

**Comment by takluyver** [comment]
Not quite sure what it depends on (maybe the shell?), but on a Linux system this is handled correctly as is:

```
$ echo $(jupyter --data-dir)/foo
/home/takluyver/.local/share/jupyter/foo
```

**Comment by DancingQuanta** [comment]
On my system, Jupyter is installed on Windows and I use Cygwin to interact with Jupyter with hardly any issues except this one.
Echoing is not the same as making the directory.

My echoes are
```
$ echo $(jupyter --data-dir)/foo
/foosers\andre\AppData\Roaming\jupyter
$ echo $(jupyter --data-dir)
C:\Users\andre\AppData\Roaming\jupyter
```
As shown above the newline caused foo go to the front.
I honestly never see this case before and so I assume that the path string never need a newline or EOL in most cases.

**Comment by ellisonbg** [comment]
I am not sure what we need to do on this one...let us know if you are able to make any progress with it...
