### ISSUE TITLE
Switching away from sorted files tab unseats list of files

### ISSUE THREAD

**Issue by fonnesbeck** [jupyter/notebook#1942]
Running notebook-4.2.3 installed via pip from master on Python 3.5.2 (Anaconda) on macOS 10.12.

Steps to reproduce:

1. Navigate to file tab on notebook
2. Sort files by last modified
3. Switch browser tabs
4. Switch browser tab back to Jupyter notebook 

The files will now be sorted alphabetically again. Hence, the selected sort order is lost simply by looking at another browser tab.

**Comment by ellisonbg** [comment]
I am not seeing this in master, but I do see that when I refresh the file browser view it does reset the sorting.
