### ISSUE TITLE
Erroneous double-spacing when typing in markdown ell

### ISSUE THREAD

**Issue by fonnesbeck** [jupyter/notebook#1943]
Running notebook-4.2.3 installed via pip from master on Python 3.5.2 (Anaconda) on macOS 10.12.

Steps to reproduce:

1. Create new markdown cell in notebook
2. Begin typing prose

I notice that occasionally typing a single space will enter two spaces instead. Backspacing a single backspace will remove both spaces, but re-entering a space will add back two spaces. I can verify that they are two spaces by using the arrow key. 

This occurs often, but irregularly.

**Comment by blink1073** [comment]
Hi @fonnesbeck, this may be related to https://github.com/jupyterlab/jupyterlab/issues/522, are you using Safari < 10.0 by chance?

**Comment by fonnesbeck** [comment]
I am using Safari, but I am on 10.0.2. 

Here is an animation of the behavior:

![](http://d.pr/i/kjFK+)

**Comment by blink1073** [comment]
Bummer, that is the same symptom we saw in JupyterLab, but switching to 10.0 on Safari fixed it for me.

**Comment by blink1073** [comment]
Do you mean that you installed from a source checkout?  If so, what is the output of `git describe`?

**Comment by fonnesbeck** [comment]
I've installed from git master via pip this afternoon:

     pip install -U git+https://github.com/jupyter/notebook.git

**Comment by blink1073** [comment]
What does `jupyter notebook --version` say?

**Comment by fonnesbeck** [comment]
4.2.3

**Comment by blink1073** [comment]
When I run the same command from a fresh conda env I get `5.0.0.dev`.  It looks like something else is shadowing version you tried to install this afternoon.

**Comment by blink1073** [comment]
In either case, I can't reproduce the issue from either `5.0.0.dev` or `4.2.3` from PyPI, both in fresh environments using Safari 10.0.1.  Hopefully someone else has further ideas.

**Comment by fonnesbeck** [comment]
I'm on `5.0.0.dev` now, and the behavior persists. Editing markdown cells is not viable on Safari.

**Comment by gnestor** [comment]
Moving the conversation to https://github.com/jupyter/notebook/issues/1967
