### ISSUE TITLE
##ImportError: No module named pulp in Jupyter

### ISSUE THREAD

**Issue by kevinsnapshow** [jupyter/notebook#1946]
I use Mac OS and I had a import Error when I try to input import pulp or from pulp import *.

import networkx as nx
import pulp
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f6be38c68a2c> in <module>()
      1 import networkx as nx
----> 2 import pulp

ImportError: No module named pulp

**Comment by takluyver** [comment]
You probably need to install pulp. If you think you've already installed it, it was probably in a different Python or a different environment from the one in which your kernel is running.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
