### ISSUE TITLE
Checking by command line if Jupyter server is running

### ISSUE THREAD

**Issue by arita37** [jupyter/notebook#1950]
Sometimes we launched Jupyter and we crash it.
It would be good to have a command line to list of Jupyter kernel running like : 
      jupyter listall

It can be checked by checking the name 'jupyter' in the process list and terminate it by : 
    jupyter terminate id / all

**Comment by takluyver** [comment]
[nbmanager](https://github.com/takluyver/nbmanager) is similar to what you want. It provides a GUI rather than a command line interface, but the module `nbmanager.api` is general purpose and could be reused to make command line UI.

**Comment by arita37** [comment]
sometimes, we manage Jupyter through SSH on remote server..... no GUI

**Comment by minrk** [comment]
There is a `jupyter notebook list` command for listing running notebooks. There isn't a corresponding terminate, though.

**Comment by MichaelChirico** [comment]
@arita37 Taken from here:

https://stackoverflow.com/a/32745046/3576984

For an SSH'd terminal, we can just run:

`kill $(pgrep jupyter)`

To kill terminals that we can't CTRL+C.

**Comment by takluyver** [comment]
There is also now a `jupyter notebook stop` command that takes a port number and shuts down the corresponding notebook server.

From 5.1, you will also be able to shut a server down if you have HTTP access to it by making a POST request to `/api/shutdown`.

**Comment by jjpr-mit** [comment]
@takluyver Is `jupyter notebook stop` available in 5.0.0?  I get a `No such file or directory` error:  

```
$ jupyter notebook --version
5.0.0
$ jupyter notebook stop 8888
[C 10:02:38.220 NotebookApp] No such file or directory: /Users/jjpr/stop
```

**Comment by takluyver** [comment]
Oops, sorry. It's new in 5.1, added by #2388.

**Comment by AbhishekSen** [comment]
> There is a `jupyter notebook list` command for listing running notebooks. There isn't a corresponding terminate, though.

`asen@asen-5356:~$ jupyter notebook list
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1571, in start
    super(NotebookApp, self).start()
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 483, in start
    serverinfo_list = list(list_running_servers(self.runtime_dir))
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1667, in list_running_servers
    info = json.load(f)
  File "/opt/conda/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/conda/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
`

**Comment by yochem** [comment]
Same issue as mentioned above.

**Comment by jtpio** [comment]
> There is a `jupyter notebook list` command for listing running notebooks. There isn't a corresponding terminate, though.

Closing as there is now also a command to stop a Jupyter Server:

![image](https://github.com/jupyter/notebook/assets/591645/33169dc2-cd3d-42a0-bf70-29744b9b68d2)

- `jupyter server list`: list the running servers
- `jupyter server stop <port>`: stop the Jupyter server running on the given port

Thanks all!
