### ISSUE TITLE
4.3 release

### ISSUE THREAD

**Issue by gnestor** [jupyter/notebook#1951]
@Carreau @takluyver There are no more issues or PRs marked with 4.3 milestone, so it looks like it's release time! I'd like to use this issue to track the release and document the process.

* [x] UX test 4.x branch
  * [x] [Widget List.ipynb](https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20List.ipynb)
* [x] Run tests against 4.x branch: https://github.com/jupyter/notebook/blob/4.x/CONTRIBUTING.md#running-tests
* [x] Confirm that all closed PRs marked with 4.3 have been backported: https://github.com/jupyter/notebook/pulls?q=is%3Apr+milestone%3A4.3+label%3A%22needs+backport%22
  * [x] https://github.com/jupyter/notebook/pull/1947
  * [x] https://github.com/jupyter/notebook/pull/1939
  * [x] https://github.com/jupyter/notebook/pull/1938
  * [x] https://github.com/jupyter/notebook/pull/1949
* [x] Review all closed PRs marked with 5.0 and confirm that there are no 4.x-compatible bug fixes or improvements that should be included in 4.3
  * [x] https://github.com/jupyter/notebook/pull/1739
* [x] Merge open PRs marked with 4.3: https://github.com/jupyter/notebook/pulls?q=is%3Aopen+is%3Apr+milestone%3A4.3
* [x] Update changelog in the docs with most significant changes: https://github.com/jupyter/notebook/pull/1955

Resources:

*  Current release docs: https://jupyter-notebook.readthedocs.io/en/latest/development_release.html
* (For what it's worth) GH Project for 4.3: https://github.com/jupyter/notebook/projects/2

**Comment by takluyver** [comment]
I've added updating the changelog to the checklist. :-)

**Comment by gnestor** [comment]
JS test results:

```
grant:notebook grant$ python -m notebook.jstest

Test group: base
Running tests with notebook directory '/var/folders/wg/yhdj316j4hs2_z5s0_5_k0tc0000gp/T/tmpgyx_ksqq'

Test group: mockextension
Running tests with notebook directory '/var/folders/wg/yhdj316j4hs2_z5s0_5_k0tc0000gp/T/tmpl_s_px4h'

Test group: notebook
Running tests with notebook directory '/var/folders/wg/yhdj316j4hs2_z5s0_5_k0tc0000gp/T/tmpfjgom03o'

Test group: services
Running tests with notebook directory '/var/folders/wg/yhdj316j4hs2_z5s0_5_k0tc0000gp/T/tmpcx163ln8'

Test group: tree
Running tests with notebook directory '/var/folders/wg/yhdj316j4hs2_z5s0_5_k0tc0000gp/T/tmplz40_ce3'

______________________________________________________________________
Test suite completed for system with the following information:
Python version: 3.5.2 | packaged by conda-forge | (default, Jul 26 2016, 01:37:38) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)]
sys.executable: /Users/grant/anaconda/bin/python
Platform      : Darwin-16.1.0-x86_64-i386-64bit

Tools and libraries available at test time:
   casperjs phantomjs

Tools and libraries NOT available at test time:
   slimerjs

Status: OK (5 test groups). Took 9.663s.
```

**Comment by gnestor** [comment]
Python test results:

```
Ran 219 tests in 29.641s

OK (SKIP=1)
```

**Comment by gnestor** [comment]
@Carreau @takluyver I am ready to cut a release! Let me know if there is anything else we should do before....

**Comment by Carreau** [comment]
I would just send a mail to the mailing list warning that it's their last change to complain. 

Or just do it. We can still do 4.3.1 if things go south.

**Comment by gnestor** [comment]
I think we should call it for this release and not accept any more commits and then we can always release patches and potentially another minor release before 5.0. I assume that this release will require a blog post? We can share the blog post with the mailing list once it's live.

Do you know how to test a `wheel` and an `sdist` locally?

**Comment by Carreau** [comment]
Yes, you can just `pip install <path to wheel>` or `<path so sdist>`, technically `<path to sdist>` now build a wheel and install the wheel if possible.

**Comment by gnestor** [comment]
Ok, that worked, although I'm not sure if I'm testing the wheel now or my dev install... How can I tell?

It looks like don't have push privileges for notebook on PyPI: 

`HTTPError: 403 Client Error: You are not allowed to upload to 'notebook'. for url: https://upload.pypi.org/legacy/`

Can you give me permissions?

**Comment by rgbkrk** [comment]
Added @gnestor on PyPI

**Comment by gnestor** [comment]
@Carreau Ok, I've done everything except upload to PyPI and push the tag to GH. Would you like to have the honors of uploading and I'll push the tag after it's uploaded and tested and working?

**Comment by Carreau** [comment]
I'm mostly in meeting this afternoon, please feel free to push, and tag.

You did all the work!

**Comment by gnestor** [comment]
GH: https://github.com/jupyter/notebook/releases/tag/4.3.0
PyPI: https://pypi.python.org/pypi/notebook/4.3.0

**Comment by gnestor** [comment]
Thanks everybody here and elsewhere (we need a @jupyter/notebook team for this instance) who contributed to this release!

When you have a chance, please install from PyPI and test. Everything seems to be working fine for me...

@Carreau Do we need to publish a blog post about this? Or publish anywhere else?

**Comment by jasongrout** [comment]
Wait! I have some major bugfixes I'm working on right now necessary to implement an Output widget.

**Comment by jasongrout** [comment]
Or we can release 4.3.1 immediately, I suppose.

**Comment by jasongrout** [comment]
There are some subtle problems with async and comm messages that I'm fixing right now.

**Comment by takluyver** [comment]
@gnestor are you sure those JS tests actually ran? 10 seconds seems suspiciously short; on Travis they take multiple minutes. I know Travis is quite slow, but that seems like a big disparity.

**Comment by Carreau** [comment]
> @Carreau Do we need to publish a blog post about this? Or publish anywhere else?

We do send a message on the jupyter mailing list, we can also post something on the Ghost Blog. 

let's give jason a chance to @jasongrout to fix things. And also warn @willingc that a minor revision is out.

**Comment by gnestor** [comment]
@jasongrout Standing by...

@takluyver I just tried running again and I'm getting a lot more output than originally (above), so maybe they didn't run 😮. I did receive a Travis notification that the [4.3.0 build passed](https://travis-ci.org/jupyter/notebook/builds/182420340). I will report the results when they finish...

**Comment by gnestor** [comment]
@takluyver My tests are are all timing out for some reason:

```
FAIL 9 tests executed in 51.493s, 0 passed, 9 failed, 0 dubious, 0 skipped.     

Details for the 9 failed tests:

In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/utils.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js
    uncaughtError: ".CodeMirror-code" still did not exist in 10000ms
```

**Comment by jasongrout** [comment]
It would be great if we could get #1956 and #1958 reviewed and in.

**Comment by jasongrout** [comment]
I just made a 4.3.1 milestone and added the two PRs above to it.

**Comment by minrk** [comment]
@jasongrout #1958 is a new feature, and the related display_id changes aren't targeted for 4.x, so I'd probably say #1958 should be in 5.0, not 4.4.

**Comment by damianavila** [comment]
So, are we going to wait for 4.3.1 to make in ANN in the list or a blog post?

**Comment by gnestor** [comment]
@damianavila It sounds like that's the plan. I'm tracking the 4.3.1 release here: https://github.com/jupyter/notebook/issues/1974

**Comment by damianavila** [comment]
Thanks for the info @gnestor!
