### ISSUE TITLE
remove widgets hardcoded hack

### ISSUE THREAD

**Issue by ivanov** [jupyter/notebook#1960]
https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L275-L291 is causing issues like ipython/ipywidgets#569 - it seems unnecessary now.

**Comment by takluyver** [comment]
@SylvainCorlay can you verify whether [this code](https://github.com/jupyter/notebook/blob/ba7e7186cf00287747a2681a9c36955eccdc0102/notebook/notebookapp.py#L284-L300) is now redundant? I'm trying to aim for a 5.0 release.

**Comment by SylvainCorlay** [comment]
Wow, I had no idea this was still around.

**Comment by takluyver** [comment]
So I take it widgets hasn't needed it for some time, then? Do you know what version of widgets will be the minimum supported if that code is removed?

**Comment by SylvainCorlay** [comment]
5.x are will be required.

**Comment by takluyver** [comment]
#2093 removes it

**Comment by soamaven** [comment]
Hi everyone. I am using `notebook v5.0.0` via conda install. I am getting this error due to the hard coding. Any clues or guidance?

**Comment by soamaven** [comment]
Found the issue -- Jupyter was reading a notebook.json in the anaconda root dir, rather than user or env dir, which I didn't know about. Not sure why it is doing that though... Hopefully this is solved. Thanks for the help!
