### ISSUE TITLE
Mathjax with double dollar signs not rendered on notebook hosted on Github

### ISSUE THREAD

**Issue by miroli** [jupyter/notebook#1962]
I'm new to Mathjax/Latex/MathML etc, so sorry if this is due to some basic misunderstanding from my part. I have a local notebook with Mathjax expressions and everything renders correctly on my machine. But all the Mathjax expressions within double dollar signs breaks when the notebook is rendered on Github (the inline expressions render as expected). I tried using the `\[\]` notation but that didn't work either.

Here's an example, the expression is under the "Measures of central tendency" header.

https://github.com/miroli/notebooks/blob/master/statistics/Statistics.ipynb

**Comment by takluyver** [comment]
For security reasons, Github doesn't allow Javascript in rendered notebooks, and I guess that extends to not loading Mathjax. So for some notebooks, you still need to view them on nbviewer (which has no interesting data to steal, so XSS attacks don't matter). Here's your notebook:

http://nbviewer.jupyter.org/github/miroli/notebooks/blob/master/statistics/Statistics.ipynb

**Comment by gnestor** [comment]
Related: https://github.com/jupyter/help/issues/21

**Comment by gnestor** [comment]
I created a test notebook rendering Mathjax from a code cell and markdown cell and both seem to be rendering correctly: https://gist.github.com/gnestor/da5f48983bc510b501f3ae358affad0e

**Comment by ellisonbg** [comment]
I would report this to Github.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
