### ISSUE TITLE
Cannot Rename in Chrome55: Invalid Header from client

### ISSUE THREAD

**Issue by a2232189** [jupyter/notebook#1963]
I cannot Rename my notebook files in Chrome55, it said that "Invalid Header from client" when I summit the new name in Chrome. However, rename action can be done in the same PC in Edge.

**Comment by a2232189** [comment]
Chrome doesn't have permission to rename the notebooks files. I reran Chrome with permission, and rename action worked well.

**Comment by takluyver** [comment]
I'm not sure what you mean about permissions. It's the notebook server that actually renames the file, the browser just sends an HTTP request asking to rename it. So it shouldn't matter what browser it is. But I'm glad you got it working.

**Comment by a2232189** [comment]
Sorry for giving wrong solution. The true reason is I have used a proxy based on privoxy, which have some bugs, leading to the consequence that I saw. Since I closed the proxy, I have played happily with notebook.
