### ISSUE TITLE
"Notebook validation failed" (tensorflow, "metadata" attribute)

### ISSUE THREAD

**Issue by MatthewKleinsmith** [jupyter/notebook#1964]
### The bug

An error box pops up whenever Jupyter tries to save [the 1_hello_tensorflow notebook](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/notebooks/1_hello_tensorflow.ipynb).

### Environment info
Ubuntu 16.04.1
Python 3.5.2
Jupyter 4.2.1

### Minimal reproducible example

```
wget https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/docker/notebooks/1_hello_tensorflow.ipynb
jupyter notebook --port=8889 1_hello_tensorflow.ipynb
```

### Logs

```
[E 11:41:58.708 NotebookApp] Notebook JSON is invalid: Additional properties are not allowed (u'metadata' was unexpected)
    
    Failed validating u'additionalProperties' in stream:
    
    On instance[u'cells'][3][u'outputs'][0]:
    {u'metadata': {},
     u'name': u'stdout',
     u'output_type': u'stream',
     u'text': u'result:  [ 3.  3.  3.  3.]\n'}
```
![screenshot from 2016-12-11 03-50-33](https://cloud.githubusercontent.com/assets/8968171/21079898/059c7ab4-bf55-11e6-8986-d8238f90cdcc.png)

### Docker version of the issue
https://github.com/tensorflow/tensorflow/issues/6252

**Comment by MatthewKleinsmith** [comment]
The errors go away if you rerun all the cells. Closing.

**Comment by takluyver** [comment]
This means that something has saved an invalid notebook at some point in the past. 'stream' outputs are not meant to have metadata. When you re-run the notebook, it deletes the saved outputs and recreates the correctly. So there is or was a bug somewhere. I don't think the Jupyter Notebook application has ever had that particular bug, so it's likely that someone saved the notebook with another application (like Nteract or Pycharm).

**Comment by rgbkrk** [comment]
nteract has never had that bug explicitly, though we do fold in whatever comes in off the message spec, assuming the kernel reports valid fields.

**Comment by takluyver** [comment]
That's a good point, it could be a kernel getting it wrong.

**Comment by takluyver** [comment]
ah, good catch

**Comment by LuoHuifen** [comment]
i solved the problem by adding "## coding=utf-8".

**Comment by craigcitro** [comment]
Yep, that looks like a colab notebook that hasn't been updated since I stopped us from saving `stream` metadata everywhere.

I'll fix this upstream in the TF repo.

**Comment by craigcitro** [comment]
Actually, @MatthewKleinsmith where are you loading these notebooks from?

It looks like these were already dropped in [this commit](https://github.com/tensorflow/tensorflow/commit/26a244c8f8c0352cc8f90e4e4af2dcc314279b93), and I can confirm that colab isn't re-introducing them.

**Comment by rgbkrk** [comment]
I summoned you a little late Craig, figured I'd let you know though. :smile:

**Comment by craigcitro** [comment]
😀  thanks for letting me know! I started the convo with you that led to https://github.com/jupyter/nbformat/issues/84 after realizing that Colab was setting erroneous metadata here.

This one's probably OK to close.
