### ISSUE TITLE
Multiple carriage returns are not handled correctly in v4.3

### ISSUE THREAD

**Issue by auneri** [jupyter/notebook#1970]
Steps to reproduce:
```
>>> print('1\r2')  # yas!
2
>>> print('1\r2\r3')  # wat?
23
```

Potential culprit: pull request #1836

**Comment by takluyver** [comment]
Thanks, I can reproduce that.

**Comment by gnestor** [comment]
@lgeiger Any ideas?

**Comment by minrk** [comment]
@gnestor looks like it was the `+` on the end being too greedy. #1982, #1983 should fix it.
