### ISSUE TITLE
I create a script in a new folder. But It's doesn't work.

### ISSUE THREAD

**Issue by zhoufankai** [jupyter/notebook#1971]
My work environment is window 10.
If I work in root directory. I can import pandas.
But if I work in a inside directory. It'does't work.
How can I solve it?
![work](https://cloud.githubusercontent.com/assets/13163736/21126280/3788ac78-c126-11e6-8e94-de1bf0a03a60.png)

![cannot work](https://cloud.githubusercontent.com/assets/13163736/21126269/2c2ee8ec-c126-11e6-9139-089e5f63ddd8.png)

**Comment by zhoufankai** [comment]
I think this is a problem.
I printed jupyter executable path.
It not my designated python path.
```
import sys
sys.executable
out::'C:\\Users\\zhoufankai\\AppData\\Local\\Continuum\\Anaconda2\\python.exe'
```
I have search internet for help. But I don't get some solves.
How can I change my jupyter executable path? 
Thanks in advance.

**Comment by takluyver** [comment]
The problem is most likely that you have a file in that folder called `numpy.py`. If you rename that (and remove the cached `numpy.pyc`), it should work.

If you want to run the kernel with a different Python executable, you'll need to [install a kernel spec](http://ipython.readthedocs.io/en/stable/install/kernel_install.html) from that Python.

**Comment by zhoufankai** [comment]
Thank you for you advice. 
It almost solved my problems.
But I have a question about the different Python executable. 
I installed kernel, But the imported package is not the same as the specified Python package.
Below is the command.
`conda create -n ipykernel_py2 python=2 ipykernel
source activate ipykernel_py2    # On Windows, remove the word 'source'
python -m ipykernel install --user`
How can I import packages in 'conda' environments as same as specific Python?

**Comment by takluyver** [comment]
To install a kernelspec from any given Python environment, run this bit with the Python you want to use:

```
python -m ipykernel install --user
```

If you want to use a conda environment, you can `activate` that environment, and then use `conda install foo` or `pip install foo` to install packages into that environment.

I'm not quite sure what you're stuck on, but does that information help?
