### ISSUE TITLE
Dev install fails on OSX 10.11.6

### ISSUE THREAD

**Issue by michaelaye** [jupyter/notebook#1977]
I was following the instructions in CONTRIBUTING.rst and it fails at the `pip install`, using conda's nodejs, on OSX 10.11.6 in a python3 env:

```bash
(mpl2) └─❱❱❱ pip install -e .                                            +7144 16:32 ❰─┘
Obtaining file:///Users/klay6683/Dropbox/src/notebook
Requirement already satisfied: jinja2 in /Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: tornado>=4 in /Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: ipython_genutils in /Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: traitlets>=4.2.1 in /Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: jupyter_core in /Users/klay6683/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: jupyter_client in /Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: nbformat in /Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: nbconvert in /Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: ipykernel in /Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: terminado>=0.3.3 in /Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: MarkupSafe in /Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/site-packages (from jinja2->notebook==5.0.0.dev0)
Installing collected packages: notebook
  Running setup.py develop for notebook
    Complete output from command /Users/klay6683/miniconda3/envs/mpl2/bin/python -c "import setuptools, tokenize;__file__='/Users/klay6683/Dropbox/src/notebook/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    /Users/klay6683/.local/lib/python3.5/site-packages/setuptools/dist.py:332: UserWarning: Normalizing '5.0.0.dev' to '5.0.0.dev0'
      normalized_version,
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/klay6683/Dropbox/src/notebook/setup.py", line 199, in <module>
        main()
      File "/Users/klay6683/Dropbox/src/notebook/setup.py", line 196, in main
        setup(**setup_args)
      File "/Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/distutils/dist.py", line 973, in run_command
        cmd_obj.ensure_finalized()
      File "/Users/klay6683/miniconda3/envs/mpl2/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/Users/klay6683/.local/lib/python3.5/site-packages/setuptools/command/develop.py", line 54, in finalize_options
        easy_install.finalize_options(self)
      File "/Users/klay6683/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 332, in finalize_options
        self.index_url, search_path=self.shadow_path, hosts=hosts,
      File "/Users/klay6683/.local/lib/python3.5/site-packages/setuptools/package_index.py", line 306, in __init__
        and (ca_bundle or ssl_support.find_ca_bundle())
      File "/Users/klay6683/.local/lib/python3.5/site-packages/setuptools/ssl_support.py", line 248, in find_ca_bundle
        return certifi.where()
    AttributeError: module 'certifi' has no attribute 'where'

    ----------------------------------------
Command "/Users/klay6683/miniconda3/envs/mpl2/bin/python -c "import setuptools, tokenize;__file__='/Users/klay6683/Dropbox/src/notebook/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/klay6683/Dropbox/src/notebook/
```

**Comment by gnestor** [comment]
I'm not sure what the cause of this issue may be, but what happens if you `pip install certifi` and retry?

**Comment by michaelaye** [comment]
yep, it runs through then. i didn't expect it so simple, thought that a `pip install -e .` would grep anything that's missing?

**Comment by michaelpacer** [comment]
I'm pretty sure `pip install -e .` just follows the commands in `setup.py` via `python setup.py develop`, and there's no explicit dependency on `certifi` listed in `install_requires`.

**Comment by gnestor** [comment]
@minrk @Carreau Should `certifi` be an explicit dependency? I suspect the issue might be that @michaelaye is using miniconda vs. regular conda?

**Comment by michaelpacer** [comment]
It sounds like it is an explicit dependency if it doesn't build successfully without it? Suppose someone wasn't using conda at all, they would have the same problem.

**Comment by michaelaye** [comment]
erm, what is `regular conda`?

**Comment by michaelpacer** [comment]
I think he means a anaconda vs. miniconda both of which install `conda`, but whereas anaconda has a bunch of scientific python packages baked in its install, miniconda only installs python and conda and the packages they depend on. 

More info [here](http://conda.pydata.org/docs/).

**Comment by michaelaye** [comment]
anaconda is just a meta-package that is pre-installed, right. But there's only one conda.

**Comment by michaelpacer** [comment]
I'm not sure what you mean by pre-installed. But I think you've got the general idea.

Yes, there is only one `conda`. But it's often used as a shorthand for anaconda.

**Comment by michaelaye** [comment]
All what an anaconda install does is to install conda and execute 'conda install anaconda'. And the statement that 'conda' is used as a shorthand for anaconda is new to me, that's why I asked above and it's certainly not only confusing, but also incorrect, as 'anaconda' is only a meta-package pointing to all the required conda packages. (Not that I'm a big fan on how these names are all confusingly interwoven, but that's why it's helpful to be precise here.)

**Comment by michaelpacer** [comment]
Did not know that that was the explicit command sequence. Thank you for explaining!

Agreed, I don't think it's an endorsed shorthand, and it is potentially confusing for those who already know the distinction. 

However, the alternative (always distinguishing anaconda from conda) can also be more confusing to those who haven't encountered the distinction between anaconda and miniconda before, since they probably have installed from anaconda (being the strongly more marketed option) and they will rarely need to type the characters `anaconda` again, whereas they will need to type `conda` all the time. Thus, anaconda gets the unofficial shorthand "conda".

**Comment by minrk** [comment]
What's in your `conda list`? Does it work if you create a new env? `certifi` ought to be in all conda envs by default, since it's a dependency of setuptools. It's not a direct dependency of the notebook, so we shouldn't depend on it here.

**Comment by michaelaye** [comment]
This is so weird, I checked the dependency list of setuptools, and the version one gets with the defaults channel set on highest priority (I also have conda_forge at a lower prio), I get version 27.2 from the default channel, which is **THE ONLY ONE** that has certifi missing in its dependencies, and **only** on the defaults channel, while conda-forge has it, see screenshot:
![screenshot 2016-12-16 09 11 46](https://cloud.githubusercontent.com/assets/69774/21269473/15441e6c-c370-11e6-9413-483199c4de9d.png)
Sorry to create noise here for a conda problem...

**Comment by michaelaye** [comment]
But this is the set one currently receives with a new env:
![screenshot 2016-12-16 08 51 38](https://cloud.githubusercontent.com/assets/69774/21269548/5a2a2a44-c370-11e6-8fba-c2d118e09694.png)

**Comment by michaelaye** [comment]
27.2 is the latest version available on the defaults channel. reporting it.

**Comment by Carreau** [comment]
> It sounds like it already is an explicit dependency, given that it doesn't build successfully without it.

I guess that "explicit" means in setup.py as a dependency. Right now _we_ don't rely on certify directly it is an implicit dependency.
