### ISSUE TITLE
Notebook suddenly started to ask for a password?

### ISSUE THREAD

**Issue by tschm** [jupyter/notebook#1979]
I assume there is an entry in the config file somewhere? How can I deactivate the password explicitly...
Thank you

thomas

**Comment by skycaptain** [comment]
Some issue here after upgrading to 4.3.0.

**Comment by gnestor** [comment]
This is the result of https://github.com/jupyter/notebook/pull/1831 which makes notebook servers authenticated by default. 

My login page looks like:

![image](https://cloud.githubusercontent.com/assets/512354/21231954/e27a8d6c-c29e-11e6-80d7-60cd48c3fb72.png)

If you run `jupyter notebook list`, you will see something like `http://localhost:8888/?token=6d48d4d8990d2adf9c0313fec7d462b5e265fe227452a273`, so just copy and paste that into the browser and you will be _logged in_.

**Comment by takluyver** [comment]
While it is possible to disable this, we don't recommend it. Using authentication by default was done to close a security hole, and disabling it opens that hole back up. See #1944 and [this security doc](http://jupyter-notebook.readthedocs.io/en/latest/security.html) for more details.

We know this change will cause some disruption; we're doing our best to minimise that, and if you tell us more about what you're doing, we'll see if there's any way to make things easier. But security is important for something that can execute code on your computer.

**Comment by skycaptain** [comment]
@gnestor: Thanks. All I'm seeing on my login page is a password field. No description. With having the password option commented out in the jupyter options this was very confusing. Thanks, also @takluyver for clearing things up.

![](https://cloud.githubusercontent.com/assets/1119641/21259342/3215e0dc-c381-11e6-8706-0975dfa27925.png)

**Comment by minrk** [comment]
@skycaptain indeed, there's supposed to be info on that page explaining about tokens, but I mixed up some logic so it's never shown in 4.3.0. The login page looks like this in 4.3.1:

<img width="609" alt="screen shot 2016-12-16 at 15 13 50" src="https://cloud.githubusercontent.com/assets/151929/21265546/46db2a2e-c3a2-11e6-9f15-8704cf13bf53.png">

**Comment by gnestor** [comment]
I'm closing this as it's fixed in 4.3.1, which we will try to release in the next couple days.

**Comment by tanayag** [comment]
@minrk 
Thanks, pasting the token worked for me.

**Comment by MissOgra** [comment]
Hi, for some reason, I cannot see any token.

**Comment by gnestor** [comment]
@MissOgra Are you running notebook 4.3 or above (`jupyter notebook version`)?

**Comment by malliwi88** [comment]
hello, I have problems because `jupyter notebook list` doesn't show token :/

![seleccion_028](https://cloud.githubusercontent.com/assets/5307894/24633284/638221f6-188d-11e7-8193-dce8a3008b2e.png)

Can anyone help me with this issue?

**Comment by takluyver** [comment]
That most likely means that it's finding an older version of the notebook package than the version you're running the server from. Try tracking that down and upgrading or removing the old version.

**Comment by plouismarie** [comment]
There is also an other use case, when you have too many notebook already open, it will just ask you for the password, whatever you have in the config file
**workaround for me was to close some of them**

[I 00:18:58.205 NotebookApp] The port 8888 is already in use, trying another port.
[I 00:18:58.205 NotebookApp] The port 8889 is already in use, trying another port.
[I 00:18:58.206 NotebookApp] The port 8890 is already in use, trying another port.
[I 00:18:58.215 NotebookApp] Serving notebooks from local directory: /Users/plouismarie/Documents/deep-learning/dcgan-svhn
[I 00:18:58.215 NotebookApp] 0 active kernels 
[I 00:18:58.215 NotebookApp] The Jupyter Notebook is running at: http://localhost:8891/
[I 00:18:58.215 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 00:18:58.428 NotebookApp] 302 GET /tree (::1) 1.22ms

**Comment by woodrujm** [comment]
Sometimes my jup note asks for a password and sometimes it doesn't. I have commented out the entire config file (setting the password/token in there did not work for me). In addition, sometimes when I open a notebook it will ask for password , I will close it then reopen on a different port and it opens without requesting a password. Very confused.

**Comment by takluyver** [comment]
With the default settings,  it's always using the authentication token. But when you start the notebook server and it opens the browser for you, it passes the token automatically, so you don't see the password page.

Once it has authenticated, it relies on cookies to stay authenticated. So make sure that your browser allows cookies.

**Comment by woodrujm** [comment]
I'm not sure I understand; when I open it the first time it asks for a password. Closing this page, then opening again (from command line with "jupyter notebook") it does not ask for a password. Are you saying the initial command sets cookies (even though it still asks for a password), then closing and opening again uses the previous token (even though I didn't type a password/token in)?

**Comment by gnestor** [comment]
When running the notebook server, you will see output that looks like:

```
[C 19:07:26.417 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=d227d9d83bd9dc5b58a4100106f3c753fc422aed713ea64f
```

If you don't use the `--no-browser` flag when running `jupyter notebook`, it will open that URL in the browser (and then remove the token parameter from the URL after authenticating).

**Comment by takluyver** [comment]
And the cookies should only be set once you are authenticated. I don't understand what would lead to the circumstances you describe. Is it possible you're running more than one notebook server on different ports?

**Comment by woodrujm** [comment]
$ jupyter notebook list
Currently running servers:
http://localhost:8889/ :: C:\Users\-----\desktop\TF_book\example_code\ch_10
http://localhost:8888/ :: C:\Users\------\desktop\TF_book\example_code\ch_10
http://localhost:8891/ :: C:\Users\-----\desktop\TF_book\example_code\ch_11
http://localhost:8890/ :: C:\Users\------\desktop\TF_book\example_code\ch_11

I would say that is possible.... I still don't understand why that would change the authentication though

**Comment by takluyver** [comment]
The authentication is for each server, so part of why you're randomly seeing authentication screens might be to do with switching between servers. I don't know why the list isn't showing you tokens, though - maybe it's running with an older version of the notebook package.

**Comment by gserra75** [comment]
Hi guys
I can't use jupyter Python because of this "Token authentication is enabled".
Unfortunately, I am not able to run either the command "Jupyter notebook list" because I am using windows in a business environment, hence, no command prompt available either. 
The IT desktop support installed Python Anaconda but they don't have any clue how to provide me with a token or a password.
Do you mind please help me with some workaround or simple hints to share with the IT support?
PS: the IT desktop support, already went through all info in https://jupyter-notebook.readthedocs.io/en/stable/public_server.html without understanding what actually they have to do for help.
Thank you in advance.

**Comment by gnestor** [comment]
You can read about alternative to the token-base authentication here: http://jupyter-notebook.readthedocs.io/en/stable/security.html#alternatives-to-token-authentication

You can ask your IT person to run `jupyter notebook password` and set a password that can be shared with you and anyone else using the Jupyter notebook server.

**Comment by gserra75** [comment]
@gnestor thank you! All guys for all advise, probably they are going to enable me using the command prompt that makes everything easier, cross finger 👍

**Comment by akhileshravi** [comment]
You will get this message in the terminal when you start Jupyter:
```
Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=a2f3bd.........................................
```
(I added the dots myself)
Copy that link from your terminal and you will be able to use Jupyter without typing any password or token

**Comment by Naviden** [comment]
No token is displayed when I start the jupyter notebook:
![image](https://user-images.githubusercontent.com/16959102/52340244-8ffb5500-2a0f-11e9-8705-8f8c399b414d.png)

neither `jupyter notebook list `gives me something:
![image](https://user-images.githubusercontent.com/16959102/52340298-b4573180-2a0f-11e9-8b11-fbc394fe6d86.png)

any idea?

**Comment by gnestor** [comment]
@Naviden What version of jupyter notebook are you running (run `jupyter notebook --version`)? 

Do you see a `token` or `password` entry in your notebook config (usually at `~/.jupyter/jupyter_notebook_config.json` but you can run `jupyter --paths` to find out where your config directories are, you might have config in more than one!).

**Comment by Naviden** [comment]
Thanks @gnestor . yes it has a password:

```
{
  "NotebookApp": {
    "password": "sha1:5c4ee3a53a51:7dc5ac1aec7fd334df619ca32180c12abc5628aa"
  }
}
```
which doesn't work:
![image](https://user-images.githubusercontent.com/16959102/52416378-b8578200-2ae9-11e9-9a52-d9fdfef3c102.png)

**Comment by gnestor** [comment]
That's surprising!! The only thing that I think of is that you may have a password set in another config file. Try running `jupyter --paths` and then inspecting the `jupyter_notebook_config.json` files in those other config directories.

**Comment by takluyver** [comment]
N.B. The `sha1:...` value is *not* the password it's expecting. That's the salted hash of the password. If you don't know what password was set, either delete that file or run `jupyter notebook password` to pick a new password.

**Comment by ozars** [comment]
It was prompting password on localhost although I had upgraded jupyter/notebook to latest versions (4.4.0/5.7.8) through pip. I realized that was due to me having default configuration created by previous versions in `~/.jupyter` directory. I just removed that directory as I didn't have much customization yet on that machine and it was fixed in next run as it created default configuration again.

That was kind of obvious, but it took some time for me as I overlooked it. Just noting here in case someone ends up with this issue like I did.

**Comment by AmirTIQK** [comment]
> It was prompting password on localhost although I had upgraded jupyter/notebook to latest versions (4.4.0/5.7.8) through pip. I realized that was due to me having default configuration created by previous versions in `~/.jupyter` directory. I just removed that directory as I didn't have much customization on that machine and it was fixed in next run as it created default configuration fresh.
> 
> That was kind of obvious, but it took some time for me as I overlooked it. Just noting here in case someone ends up with this issue like I did.

This worked for me too, thanks @ozars!

**Comment by maxiriva92** [comment]
If jupyter notebook is set just for testing and compiling (non productive environment) I recommend to run:
sudo visudo

and then modify the etc/sudoers file to:
$sys ALL=(ALL) NOPASSWD: ALL

I strongly recommend doing this in non-production environments

**Comment by Tazinym** [comment]
> It was prompting password on localhost although I had upgraded jupyter/notebook to latest versions (4.4.0/5.7.8) through pip. I realized that was due to me having default configuration created by previous versions in `~/.jupyter` directory. I just removed that directory as I didn't have much customization on that machine and it was fixed in next run as it created default configuration fresh.
> 
> That was kind of obvious, but it took some time for me as I overlooked it. Just noting here in case someone ends up with this issue like I did.

HI,

Which directory did you remove? Can you elaborate?

**Comment by ozars** [comment]
> Which directory did you remove? Can you elaborate?

`~/.jupyter`: `.jupyter` directory in user's home directory in a linux system. Not sure where it is located in Windows (in `C:/Users/<username>` perhaps? dunno.)

**Comment by KBor69** [comment]
I had the same problem and removed C:/Users/<username>/.jupyter directory. (I am running jupyter in conda environment under Windows 10). It fixed the problem for me.

**Comment by ryan-williams** [comment]
This suddenly started happening to me: no token printed on `jupyter notebook` start, password-only prompt in browser, no token printed by `jupyter notebook list`.

Things that I did, which didn't work:
- `mv jupyter_notebook_config.json{,.bak}` (disable `jupyter_notebook_config.json`)
- `pip uninstall jupyterlab{,-server}`

I moved some files from `~/.jupyter/` to `~/tmp/` (`lab/`, `migrated`, `beakerx.json`, `jupyter_notebook_config.json.bak`), and then started seeing the normal behavior again.

However, moving those files back, I still see the normal behavior, so it's not clear what actually unstuck me.

Some relevant versions:

```
ipykernel          5.2.1
jupyter            1.0.0
jupyter-client     6.1.3
jupyter-console    6.1.0
jupyter-core       4.6.3
notebook           6.0.3
```

**Comment by prashil2792** [comment]
@ryan-williams use `jupyter notebook password` command to set the new password and then try your new password.

**Comment by senthilkumarIRTT** [comment]
> N.B. The `sha1:...` value is _not_ the password it's expecting. That's the salted hash of the password. If you don't know what password was set, either delete that file or run `jupyter notebook password` to pick a new password.

Your suggestion is working Thank u. Dr.R.Senthilkumar, Assistant Professor, Department of Electronics and Communication Engineering, Institute of Road and Transport Technology, Erode, Tamilnadu

**Comment by senthilkumarIRTT** [comment]
> @ryan-williams use `jupyter notebook passwoYour suggestion is working Thank u. Dr.R.Senthilkumar, Assistant Professor, Department of Electronics and Communication Engineering, Institute of Road and Transport Technology, Erode, Tamilnadurd` command to set the new password and then try your new passwo

**Comment by senthilkumarIRTT** [comment]
> @ryan-williams use `jupyter notebook password` command to set the new password and then try your new password.

Your suggestion is working Thank u. Dr.R.Senthilkumar, Assistant Professor, Department of Electronics and Communication Engineering, Institute of Road and Transport Technology, Erode, Tamilnadu

**Comment by Hernevans** [comment]
Run the following code on the cmd terminal to create a password.

`jupyter notebook password`

Then re-launch notebook with`jupyter notebook`

**Comment by TanjaNY** [comment]
Tunneling from an aws ec2 ubuntu instance and getting:

![0_Seite_02](https://user-images.githubusercontent.com/32233040/110216716-f71aba80-7eb0-11eb-8308-e77f6c1a965c.jpg)

**Comment by tom-foster-wcc** [comment]
> Tunneling from an aws ec2 ubuntu instance and getting again and again. Jupyter Notebook on the instance 5.7.10
> my local installation 6.1.4
> 
> ![0_Seite_02](https://user-images.githubusercontent.com/32233040/110216716-f71aba80-7eb0-11eb-8308-e77f6c1a965c.jpg)

Getting this issue too, tunneling on red hat / azure

**Comment by jleagle94** [comment]
> Tunneling from an aws ec2 ubuntu instance and getting again and again. Jupyter Notebook on the instance 5.7.10
> my local installation 6.1.4
> 
> ![0_Seite_02](https://user-images.githubusercontent.com/32233040/110216716-f71aba80-7eb0-11eb-8308-e77f6c1a965c.jpg)

I am having the same issue. It even has the :: //Users/you/notebooks when its truly :: /data
```
(fermi) [fermi@7dd28e2b5d6a ~]$ jupyter notebook list
[NbserverListApp] WARNING | Config option `kernel_spec_manager_class` not recognized by `NbserverListApp`.
Currently running servers:
http://00.00.00.00:8888/?token=2cb47bc3acc590fd8227a2f799bd40c899c256dc00a14322 :: /data
```

**Comment by RorisangSitoboli** [comment]
Hi, all. Late to the party-but better than never. I solved this after two hours  following another inconclusive Github thread where the conveners failed to explain a simple concept and ended up locking  the thread because they were being grilled! Glad I found this still open. One of my problems is that I am a predominantly Linux/Ubuntu user. 

In Windows:

- Open Anaconda Navigator (Windows button then Run as administrator).
- Click 'Jupyter Notebook'.
- Click 'CMD.exe Prompt' (within the Navigator). Your prompt will read like 'C:\Users\User>'.
- To see a list of running instances of Jupyter Notebooks plus their tokens, type 'jupyter notebook list'.
- To set a password type 'jupyter notebook password' in the command prompt you instantiated above.
- Enter a password of your choice at the prompt 'Enter password'.
- Verify password at 'Verify password'.
- You might see '[NotebookPasswordApp] Wrote hashed password to C:\Users\User\.jupyter\jupyter_notebook_config.json'.
- To view the 'hashed' password follow the given path (above, likely in C: drive), use Notepad or VSCode (any other editor, Emacs, Nano, etc'.
- Now enter the password you created and verified earlier (first few lines above) and you are good to go (click 'login', after entering the password). 
- Important: Do not copy and paste the hashed password when prompted for password by Jupyter Notebook.
- If you get the 'incorrect password\login', shutdown all notebooks and restart Anaconda-not PC. You will be ready to work with the password protected Jupyter Notebooks until the next bug/poor (jokes!) tutorial from the developers swamping Github pages.

I hope this saves you time, inconvenience and a lot of pain! (I like to think I am of average or just below average intelligence and so need clear instructions, instead of being told to work it out myself-wastes so much time reinventing the wheel)

**Comment by ahmedbr** [comment]
The following worked for me:

1- Run: `jupyter notebook password`
2- Set and confirm a password.
3- Run: `jupyter notebook`
4- On browser, when it asks you for the password, enter the one you set earlier in step 2 and it you'll be ready to go.
