### ISSUE TITLE
The kernel type is not saved in the notebook when it is created

### ISSUE THREAD

**Issue by asmeurer** [jupyter/notebook#198]
If you create a notebook with an "alternate" kernel, like R, then kill the kernel without saving, the notebook file will be created, but if you then open it again, the kernel is reset to the default (Python 3). It's a little odd that the UI for "create notebook with this kernel" doesn't actually save the kernel in the notebook when it creates it.

**Comment by minrk** [comment]
I think triggering autosave on setting the kernel should address this.

**Comment by takluyver** [comment]
Or could we do it more directly, giving the kernelspec to the contents manager to create the notebook file with that in from the start?
