### ISSUE TITLE
pip installed builds of notebook ignore conda environments; calls kernel from root env

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/notebook#1989]
I ran into weird situations where I was installing modules and not finding them available in the notebook. 

I suspected something environment related. But when I checked pip from inside the notebook, it didn't line up with any of what was returned when I `pip list`ed from the terminal in my environments. I thought to uninstall notebook from the root environment, thinking that would stop the `jupyter-notebook` command from being intercepted by an overeager path. That did nothing to change the situation, except that once I opened a notebook, and tried import notebook, it would tell me that it had no notebook module. From that I surmised that it was correctly executing the command, but somehow when activating the kernel, it's going to the wrong place.

So I uninstalled ipykernel from my root environment so that if it was trying to grab the kernel from there it would just fail. 

And lo, so it did.

But if this has been an issue for a while, why hadn't I noticed it by now. I'd been using the notebook a lot while I was writing my dissertation. That made me think that it was an issue on master but nothing else.

So, just to check the pervasiveness of this, I created 5 new environments: one environment that uses the notebook from conda (which is still on 4.2.3), 4 environments where I installed the notebook using pip: one editable install on master, and then one of each 4.3, 4.2.3, 4.2.0. 

On all of the pip installs I get the error message

    ~/anaconda3/bin/python3: No module named ipykernel

when it should be calling python from 

    ~/anaconda3/envs/testing_env/bin/python

What was weird was that I have no trouble accessing my ipython kernels as long as I install the notebook using conda. Somehow, it seems to get the correct `python` from the correct environment with access to the correct set of modules as long as you built the notebook with `conda install`.

Remembering that I had recently updated pip to 9.0.1, thinking that that was a plausible commond cause. But it turns out that this is a problem using both pip v9.0.1 and pip v8.1.2.

The one additional thought that I had was that perhaps conda was doing something different with how it was handling path resolution which was appropriately changed in the conda release of the notebook but not in the pip release. Thus it's not an interaction with pip (per se) but an interaction between the fact that I'm trying to use conda as a virtual environment manager and both pip and conda as package managers. But that also didn't sound quite right and I'm not sure how/if to pursue that further.

**Comment by michaelpacer** [comment]
@Carreau this is the kind of bug that you're good at figuring out, so "ping".

**Comment by Carreau** [comment]
You use several things to help diagnose what's happening.

1) `import sys; sys.executable` will tell you what is your curent python
2) from within a notebook `!{sys.executable} -m pip` will use the pip of currentkernel.
3) Conda-installed' notebook have their own patch with condakernels (not sure about the name) that autodetect environments. It does though break nbconvert --execute


> That did nothing to change the situation, except that once I opened a notebook, and tried import notebook, it would tell me that it had no notebook module. From that I surmised that it was correctly executing the command, but somehow when activating the kernel, it's going to the wrong place.

That kind-of make sens (or at least it does not not-make-sens) as the server may be on a different machine so the env you see is the kernel's one, not the notebook one. The question is:
Should the notebook only see envs restricted to where it's installed, or all the system envs. Both case make sens, but the one we choose (IIRC) is that a notebook see all kernels. Indeed you might want to install notebook with py3, and kernel with Py2. Plus the notion of "envs" is often Python specific. Ence while kernels are regularly machine-wide. 

I don't remember either if ipykernel install the specs at install time or need to be triggered manually. We can resolve that in person later and investigate, but I would expect it to be a corner case of developing the notebook.

**Comment by michaelpacer** [comment]
Solved: it was a kernelspec problem.
