### ISSUE TITLE
[Improvments] Terminal cut - copy - paste 

### ISSUE THREAD

**Issue by yarmenti** [jupyter/notebook#1990]
Hi,

Is that possible to have these functionalities when opening a new terminal:
- cut
- copy
- paste

?

Indeed, (for example) if one wants to clone some git repo, you have to write it down manually, which can be long.

Thanks a lot for the fantastic job guys,

**Comment by takluyver** [comment]
Right click and paste works for me. Clipboard events are a bit tricky in the browser, though. If you're not already on Notebook 4.3, then please update, because we switched the terminal package from term.js to xterm.js, which is an actively maintained fork.

**Comment by yarmenti** [comment]
Ok perfect, I used the v 4.2 (docker-stacks). I'll try to update that.
Thanks,
