### ISSUE TITLE
Cannot save notebooks with a '%' sign anywhere

### ISSUE THREAD

**Issue by jfemiani** [jupyter/notebook#1995]
So on an Ubuntu 14.04 machine with Jupyter from Anaconda2,  I cannot save notebooks that include a '%' sign in any cell.

Screenshots:

* This one works:
![thisworks](https://cloud.githubusercontent.com/assets/2800407/21321091/59152c4e-c5e1-11e6-8f8d-ad85c7b14f9e.png)

* This one fails (note the URI error, and the 'Autosave Failed' message)
![this fails](https://cloud.githubusercontent.com/assets/2800407/21321093/5b75de16-c5e1-11e6-9746-c5ca471d0fa5.png)

* This one fails as well 
![thisfailstoo](https://cloud.githubusercontent.com/assets/2800407/21321097/62d8f148-c5e1-11e6-8bb1-6639a3b091f8.png)

Jupyter works in my office (also Ubuntu 14.04) but not on this machine. It fails on Chromium and also on Chrome. 

I have to delete the percent signs (I replace them with the word MODULO) in order to save my work. 
I have a number of them scattered throughout (as magics, formatting, and modulo operations)

I do not know enough about the NB system to know why it happens only on this machine. I have reinstalled Anaconda, Chromium, Chrome, etc. 

If the environment is helpful it is
[my_environment.txt](https://github.com/jupyter/notebook/files/661639/my_environment.txt)

**Comment by takluyver** [comment]
Do you have the Lastpass extension? See #1966.

**Comment by jfemiani** [comment]
Yup -- That was it.  I tried to look for it but I think my search for tickets must have been limited to 'open' issues. Sorry for the noise and thanks for the help!

**Comment by takluyver** [comment]
No worries. Searching for punctuation is hard in any case. I can find it easily because I remembered it and searched for Lastpass. ;-)
