### ISSUE TITLE
Notebooks containing `%` cannot be saved.

### ISSUE THREAD

**Issue by psigen** [jupyter/notebook#2010]
Adding the character `%` to a notebook prevents it from being able to be saved.  This can be easily reproduced by doing the following:

1. Create a new notebook using `File`>`New Notebook`>`Python2`
2. Add the following to a cell:
    ```python
    20 % 10
    ```
3. Attempt to save the notebook using `Ctrl+S`

The following error appears in the toolbar:
`URIError: URI Malformed`

The following console message appears in Chrome:
`API request failed (0): URIError: URI malformed - utils.js:623`

----
From `Help`>`About`:

**Server Information:**

You are using Jupyter notebook.

The version of the notebook server is 4.2.0 and is running on:
```
Python 2.7.9 |Anaconda 2.2.0 (x86_64)| (default, Dec 15 2014, 10:37:34) 
[GCC 4.2.1 (Apple Inc. build 5577)]
```

**Current Kernel Information:**
```
Python 2.7.9 |Anaconda 2.2.0 (x86_64)| (default, Dec 15 2014, 10:37:34) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

**Comment by takluyver** [comment]
You're using the Lastpass Chrome extension, see #1966 and #1995.

**Comment by psigen** [comment]
Argh, I think the bigger bug here is Github's inability to handle punctuation or exact text searches.

Thanks for the quick response!

**Comment by takluyver** [comment]
Yup, Github search is pretty poor, and searching for punctuation is hard at the best of times.

**Comment by psigen** [comment]
For anyone that comes across this thread, LastPass claims the issue should be fixed in the next update:
https://forums.lastpass.com/viewtopic.php?f=12&t=236645&start=10
