### ISSUE TITLE
Is there any way to detect whether the notebook server is working well?

### ISSUE THREAD

**Issue by Huang77** [jupyter/notebook#2012]
I have a problem that , the notebook server process is not dead, but the server doesn't reponse to any requests.. so, if there is any way to detect whether  the server is working well?? Therefore, when the server is not available, i can restart it automatically.

Thanks a lot~~

**Comment by takluyver** [comment]
I don't think there's any dedicated API for that. Is it sufficient to just make periodic HTTP requests and see if it responds within (for example) 5 seconds?

**Comment by Huang77** [comment]
ok, thank you~
