### ISSUE TITLE
Defining __getattr__ breaks _repr_html_

### ISSUE THREAD

**Issue by mcleonard** [jupyter/notebook#2014]
I created a class where I am storing rows of data with column headers. I want to display the contents in an HTML table in notebooks, so I'm using `_repr_html_`. I'd also like to access columns using the headers as attributes, like `foo.column1`. However, defining `__getattr__` stops `_repr_html_` from being called and the notebook falls back to `__repr__`. This shouldn't happen because `_repr_html_` is defined in the class instance, so `__getattr__` shouldn't be called. I checked if `__getattr__` is being called and it appears that `_ipython_canary_method_should_not_exist_` is being called and then it falls back to the normal `__repr__`.

Here's an example:
<img width="747" alt="screen shot 2016-12-24 at 5 48 26 pm" src="https://cloud.githubusercontent.com/assets/1200974/21469452/f5e67700-ca03-11e6-9dfb-24270fab3447.png">

<img width="746" alt="screen shot 2016-12-24 at 5 48 40 pm" src="https://cloud.githubusercontent.com/assets/1200974/21469451/f05b4162-ca03-11e6-9100-82b32f274bd6.png">

**Comment by mcleonard** [comment]
Ah, nevermind. I needed to raise `AttributeError` in `__getattr__`.

**Comment by connerxyz** [comment]
Okay but what's the solution?

**Comment by connerxyz** [comment]
If it checks for permissive attribute handling to mitigate potentially *not* having a `__repr_html__` implementation, why doesn't it check for the `__repr_html__` implementation itself?

**Comment by zlatko-minev** [comment]
So what is the resolution? I have the same issue

**Comment by kechan** [comment]
> So what is the resolution? I have the same issue

In my def __getattr__(self, attr), I just did this:

    if attr == '_ipython_canary_method_should_not_exist_':
      return

to suppress that message. This is a hack I don't know any unintended consequence. For my case, I will post back if i see any weird behavior downstream.
