### ISSUE TITLE
Jupyter jquery version problems in nbextension

### ISSUE THREAD

**Issue by riedelcastro** [jupyter/notebook#2027]
I am developing a simple SVG drawing extension here:

https://github.com/uclmr/egal

Things are working well, but I have a problem with the jquery version that comes installed with jupyter. From what I can tell it is `2.0.3` which has some problems when it comes to handling SVG trees. Is there a way to define my own jquery version in the nbextension, or the possibility for a general upgrade? I have been trying various things using `require` but with no luck so far. Maybe there is a standard way to do this?

**Comment by gnestor** [comment]
Ping @Carreau
