### ISSUE TITLE
Accessing jupyter notebook via ssh tunneling ec2

### ISSUE THREAD

**Issue by emptyr1** [jupyter/notebook#2029]
Hi. I have jupyter notebook running on port 8888 on an aws ec2 instance. I have been trying to access jupyter notebook UI from my OSX using **Dynamic port forwarding** using the -D flag in the ssh command.. The AWS Blog describes this http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-ssh-tunnel.html  which I have been trying consistently. 
I know there is one way of editing the config file and changing the `c.NotebookApp.ip='*'` which works but that's not what I want. Is there any other setting I need to change to make this work? Has anybody tried this? I've followed the steps in the blog, tried using foxy-proxy in chrome as well as firefox, but no luck :(

**Comment by minrk** [comment]
I typically set up tunnels with:

```bash
ssh -L 9999:127.0.0.1:8888 aws-host
```

then open `127.0.0.1:9999` on my computer, which is forwarded to `127.0.0.1:8888` on the remote machine. This has worked for me with AWS and other remote services.
