### ISSUE TITLE
File type association

### ISSUE THREAD

**Issue by amueller** [jupyter/notebook#2031]
It would be great if double click on a notebook would open a notebook for "all OSs".
There seems to be an issue for linux (?) #1922.

I think Windows is actually more important, as windows users typically work more gui-driven.
Is it possible to associate file-types via the conda (or even the pip) package?

**Comment by takluyver** [comment]
Have you had a look at [nbopen](https://github.com/takluyver/nbopen)?

I don't think we can associate file types directly on installing a pip/conda package, because it requires changes outside the environment those tools install to.

**Comment by amueller** [comment]
I have not.
I'm looking for a way to make it easier for first-time jupyter users to follow a tutorial.
Anything from the console won't really help the windows users, and installing an additional package that's not included in Anaconda also makes it harder.

The change proposed in #1922 seems to make a change outside the environment, right? Is that considered "dirty"? I guess I'll open a ticket at anaconda and see if we could change it there - it does put stuff in the .rc file and into the start menu...

**Comment by takluyver** [comment]
We may provide the necessary data, but I don't think we'll ever make it so that a `pip install` sets up the association automatically. What happens if you install it in multiple environments? It's going to get confusing. Anaconda might; that has the notion of a defined 'root environment'. Though it could still get confusing if you install two copies of Anaconda.

**Comment by amueller** [comment]
Yeah if you install two copies of anaconda, I think a bunch of things might be confusing (you change the bin PATH on install usually).

I usually try to report issues in the most upstream place possible, but I agree with you that you might not be the right place to solve this issue.
Feel free to close or keep (to track possible solutions for opt-in solutions).

**Comment by gnestor** [comment]
I should add that [nteract](https://nteract.io/), being a desktop app, provides this functionality.

**Comment by gnestor** [comment]
I'm going to close this but let us know if you figure out a way to enable this 👍
