### ISSUE TITLE
Splitting and Merging Cells ?

### ISSUE THREAD

**Issue by stuaxo** [jupyter/notebook#2052]
It would be great if you could right click and split a cell into two at some point.

Similarly, being able to control-click to pick adjacent cells of the same type and then have some way of merging them would be useful.

**Comment by takluyver** [comment]
Ctrl+Shift+- while editing a cell should split it at the cursor. We've not yet gone down the road of custom right-click menus.

You can use Shift+(up/down) to select a range of cells, and then Shift+M to merge them.

**Comment by stuaxo** [comment]
Cheers - I see I should have checked in the help to see the awesome cheatsheet.

Some UI at some point in the future would definitely be nice for this.
