### ISSUE TITLE
Python 3.6 underscores in numeric literals are not highlighted correctly

### ISSUE THREAD

**Issue by Nagasaki45** [jupyter/notebook#2053]
Python 3.6 supports underscores in numeric literals (PEP 515). They are currently not highlighted correctly:

![Problematic highlighting of numberic literal with underscore](https://cloud.githubusercontent.com/assets/2564187/22121982/f5cd895a-de7d-11e6-94be-19bf46d458fb.png)

```
✗ python --version
Python 3.6.0
✗ jupyter --version
4.2.1
✗ jupyter-notebook --version
4.3.1
```

**Comment by themrmax** [comment]
@Nagasaki45 the code highlighting is provided by [CodeMirror][1], can you please raise this issue in their bug tracker?

[1]:https://github.com/codemirror/CodeMirror/

**Comment by Nagasaki45** [comment]
Hi @themrmax, I would definitely do this, but I couldn't find which version of CodeMirror I'm using. Do you know the exact version (based on the information I provided above) or suggest a way to check it?

**Comment by takluyver** [comment]
The version the notebook uses is encoded in [bower.json](https://github.com/jupyter/notebook/blob/master/bower.json). You can check that at the tag of the version you have installed. In master we're currently back on an older release to avoid a Safari bug.

You can also test on [this CodeMirror demo page](http://codemirror.net/mode/python/index.html), which should be more up to date.

**Comment by Nagasaki45** [comment]
CodeMirror issue added: https://github.com/codemirror/CodeMirror/issues/4506.

**Comment by themrmax** [comment]
Cool Martin has fixed this in codemirror/master, we should bump our codemirror version when he marks a new version
https://github.com/codemirror/CodeMirror/commit/39ad3b619ba9ea481f2847fb85aed647b67d17d1

**Comment by takluyver** [comment]
This appears to have just missed Codemirror 5.23, which is the latest release at the moment, so I've bumped it to notebook 5.1. If there's a new Codemirror release soon, we can bring it back to 5.0.

**Comment by takluyver** [comment]
#2601 upgraded us to CM 5.27, fixing this.
