### ISSUE TITLE
Flaky ligatures in Python code

### ISSUE THREAD

**Issue by bogdanteleaga** [jupyter/notebook#2054]
As can be seen in the image, some ligatures do not show up in Python code, while they do work in the comments, javascript or markdown parts. Seems to happen because `!`, `<`, `>` are highlighted, while `=` is not. Is there any simple way to fix this?

![image](https://cloud.githubusercontent.com/assets/6207800/22129893/06da9c80-dea9-11e6-8317-8ef8e87fd22d.png)

**Comment by bogdanteleaga** [comment]
Fixed it by editing the codemirror js.

**Comment by takluyver** [comment]
Can you describe in more detail what you changed? Other people might be interested in making those ligatures work too.

**Comment by bogdanteleaga** [comment]
Sure, I edited [this](https://github.com/codemirror/CodeMirror/blob/39ad3b619ba9ea481f2847fb85aed647b67d17d1/mode/python/python.js#L45) line, by adding the ligatures I needed in there.
