### ISSUE TITLE
fresh installation fails on current master with "No such file or directory"

### ISSUE THREAD

**Issue by dkrenn** [jupyter/notebook#2056]
`git clone ...` and `pip install -e . --user` fails on current master `58c66ef45 Merge pull request #1984 from jasongrout/resize` with
`error: [Errno 2] No such file or directory: '/local/dakrenn/sage/jupyter-notebook/node_modules/proptypes'`.
It works with the 4 days older `68a514a29 Merge pull request #2033 from vlimant/master`.

**Comment by takluyver** [comment]
I don't get this error, nor the one you describe in #2057. Are you still experiencing them? Can you provide more details about your system (OS, Python version, pip version)?

**Comment by gnestor** [comment]
It looks like you need to do an `npm install` and `npm run build`, then `pip install -e .`.

**Comment by dkrenn** [comment]
@gnestor: `npm run build` seems to be called by my `pip install ...` because, typing in this manually as you suggested gives the same error as mentioned at the top.

**Comment by dkrenn** [comment]
@takluyver: Yes, still experiencing these problems. I use Linux Mint 17.3, Python 2.7.6 (same troubles with Python 3.4.3), pip 9.0.1.

**Comment by gnestor** [comment]
@dkrenn `error: [Errno 2] No such file or directory: '/local/dakrenn/sage/jupyter-notebook/node_modules/proptypes'` suggests that `proptypes` has not be installed. notebook still depends on a couple npm packages, namely `preact` and `preact-compat` and `proptypes` is a dependency of `preact-compat`:

```
grant:notebook grant$ npm list
jupyter-notebook-deps@4.0.0 
├── bower@1.8.0
├─┬ less@2.7.1
│ ├─┬ errno@0.1.4
│ │ └── prr@0.0.0
│ ├── graceful-fs@4.1.11
│ ├── image-size@0.5.0
│ ├── mime@1.3.4
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ promise@7.1.1
│ │ └── asap@2.0.5
│ └── source-map@0.5.6
├── preact@7.1.0
├─┬ preact-compat@3.11.0
│ ├─┬ preact-render-to-string@3.4.1
│ │ └── pretty-format@3.8.0
│ ├── preact-transition-group@1.1.0
│ ├── proptypes@0.14.3
│ └── standalone-react-addons-pure-render-mixin@0.1.1
└── requirejs@2.3.2
```

**Comment by akaihola** [comment]
I had the same issue. I just ran

    npm install proptypes

and then re-run

    pip install -e .

in my virtualenv, and the install went through smoothly. This is master commit 9dd3818 from 2016-02-22.

**Comment by gnestor** [comment]
Ok, good. [This PR](https://github.com/jupyter/notebook/pull/2011) significantly refactored the notebook's use of npm and it's possible that it resolved this issue. It looks like it was merged 2 days after you opened this issue, so if you were installing the notebook via `pip install notebook` vs. cloning the repo and installing, then you would've been installing a previous version (4.3.2).

**Comment by annabuyevich** [comment]
When installing, I also just ran into this (on MacOSX). 

```
    Staging /Users/annab./notebook/node_modules/proptypes -> /Users/annab./notebook/notebook/static/components/proptypes
    /Users/annab./.local/lib/python3.6/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '5.0.0.dev' to '5.0.0.dev0'
      normalized_version,
    rebuilding js and css failed. The following required files are missing: ['notebook/static/notebook/js/main.min.js', 'notebook/static/tree/js/main.min.js', 'notebook/static/edit/js/main.min.js', 'notebook/static/terminal/js/main.min.js', 'notebook/static/auth/js/main.min.js', 'notebook/static/style/ipython.min.css', 'notebook/static/style/style.min.css']
    error: [Errno 2] No such file or directory: '/Users/annab./notebook/node_modules/proptypes'
```

Running `npm install proptypes` fixed the issue.

**Comment by gnestor** [comment]
@annabuyevich Have you installed notebook from source before? If so, is this the first time you've noticed this issue? I'm just wondering if this bug was introduced recently?

**Comment by dkrenn** [comment]
I can confirm that running additionally `npm install proptypes` fixes this issue. Thus, one fix would be to include this dependency somewhere in the installation script. (Or simply document it in the file `CONTRIBUTING.rst`)

**Comment by dkrenn** [comment]
Btw, tried with pip version `9.0.1` as well; same issue.

**Comment by gnestor** [comment]
> (This is on https://github.com/jupyter/notebook/releases/tag/5.0.0-rc.1 )

@dkrenn Are you encountering this with rc1? Have you tried uninstalling notebook and reinstalling rc1?

**Comment by dkrenn** [comment]
@gnestor Actually, I've installed it (5.0.0-rc.1) on a new system, so no notebook was present before.

**Comment by gnestor** [comment]
We merged https://github.com/jupyter/notebook/pull/2319 which hopefully resolves this. We will release rc2 with this change. @dkrenn I will follow up with you when it's available and I will greatly appreciate you giving it a try because we don't want to release 5.0 with this issue.

**Comment by gnestor** [comment]
I just released notebook 5.0.0rc2. Can those of you who encountered this give it a try? 

```
pip install --pre notebook
```

**Comment by dkrenn** [comment]
@gnestor: Installation in the repository-directory with `pip install --user -e .` completed without any error (but on a system that already had some of the requirements updated; I will try on a different, untouched system tomorrow.)

However, I get an error, when starting the notebook server:
```
[E 18:17:43.636 NotebookApp] Could not open static file ''
[W 18:17:43.824 NotebookApp] 404 GET /static/components/preact/index.js (127.0.0.1) 9.43ms referer=http://localhost:8888/tree?token=4bff232ca596d7df18ce0aea8dfa677db01a62898720c219
[W 18:17:43.827 NotebookApp] 404 GET /static/components/preact-compat/index.js (127.0.0.1) 2.34ms referer=http://localhost:8888/tree?token=4bff232ca596d7df18ce0aea8dfa677db01a62898720c219
[W 18:17:43.842 NotebookApp] 404 GET /static/components/preact/index.js (127.0.0.1) 1.36ms referer=http://localhost:8888/tree?token=4bff232ca596d7df18ce0aea8dfa677db01a62898720c219
[W 18:17:43.850 NotebookApp] 404 GET /static/components/preact-compat/index.js (127.0.0.1) 1.45ms referer=http://localhost:8888/tree?token=4bff232ca596d7df18ce0aea8dfa677db01a62898720c219
```
but `http://localhost:8888/tree` shows what it should; when trying to open a notebook in there is the (same) error
```
[W 18:17:47.061 NotebookApp] 404 GET /static/components/preact/index.js (127.0.0.1) 2.32ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
[W 18:17:47.065 NotebookApp] 404 GET /static/components/preact-compat/index.js (127.0.0.1) 2.21ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
[W 18:17:47.210 NotebookApp] 404 GET /static/components/preact/index.js (127.0.0.1) 1.98ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
[W 18:17:47.220 NotebookApp] 404 GET /static/components/preact-compat/index.js (127.0.0.1) 1.57ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
```
At the moment, I have no glue why.

**Comment by takluyver** [comment]
I saw some errors like that, but when I cleaned out `notebook/static/components` and re-ran `setup.py js` it resolved itself.

**Comment by dkrenn** [comment]
@takluyver indeed, this solved the problem for me. Thanks.

**Comment by gnestor** [comment]
In our installation scripts, bower will skip installation of a library if it already exists. In your case, it existed because it was copied there from `node_modules`. When upgrading a dev install of the notebook, it's usually good practice to `git clean -xfd` and `pip install -e .` to prevent issues like these.

**Comment by dkrenn** [comment]
@gnestor Overall, installation of 5.0.0rc2 went fine on a fresh Linux Mint. 

I went throught [CONTRIBUTING.rst](https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.rst) to install, but "missed" that `npm' had to be installed. Not too long ago, `sudo apt-get install nodejs-legacy npm` was written on this page, but has been removed. (Why?). What I needed finally was `sudo apt-get install npm python-dev`, i.e., the Python headers were missing as well (and IMO are not mentioned somewhere, although obviously needed)

**Comment by takluyver** [comment]
You shouldn't generally need the Python headers to install Jupyter. The only case I can think of where you'd need them is if you had to build pyzmq from source, but binary packages for pyzmq should be available from a package manager near you.

**Comment by minrk** [comment]
@dkrenn as it says on that page, where `apt install nodejs` used to be:

> be aware that the nodejs or npm packages included in the system package repository may be too old to work properly

This has been replaced with a link to the official node.js installation instructions, which seems like a better recommendation.

**Comment by dkrenn** [comment]
@minrk: I see, somehow I did not catch the link, but it is clearly there :)

**Comment by dkrenn** [comment]
@takluyver Not sure, what exactly needed this. 
As said, I've worked on a fresh system (Linux Mint) and just followed the instructions and `python-dev` was what I needed to complete this.

**Comment by ChandaniM123** [comment]
I am following this https://jupyter-notebook.readthedocs.io/en/stable/contributing.html to set up a development environment. But running into issues when the set up reaches this step:

bower install bower xterm.js-css#*                     EHTTP Status code of 500
    rebuilding js and css failed. The following required files are missing: ['notebook/static/components', 'notebook/static/notebook/js/main.min.js', 'notebook/static/tree/js/main.min.js', 'notebook/static/edit/js/main.min.js', 'notebook/static/terminal/js/main.min.js', 'notebook/static/auth/js/main.min.js', 'notebook/static/style/ipython.min.css', 'notebook/static/style/style.min.css']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/volturnus/notebook/setup.py", line 174, in <module>
        main()
      File "/opt/volturnus/notebook/setup.py", line 171, in main
        setup(**setup_args)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/volturnus/notebook/setupbase.py", line 634, in run
        raise e
      File "/opt/volturnus/notebook/setupbase.py", line 623, in run
        self.distribution.run_command('js')
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/volturnus/notebook/setupbase.py", line 565, in run
        self.run_command('jsdeps')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/volturnus/notebook/setupbase.py", line 414, in run
        env=env
      File "/opt/volturnus/notebook/setupbase.py", line 338, in run
        return check_call(cmd, *args, **kwargs)
      File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['bower', 'install', '--allow-root', '--config.interactive=false']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/opt/volturnus/notebook/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /opt/volturnus/notebook/--allow-root --config.interactive=false



I'm sure I meet the basic requirements of having python3.5, nodejs(node -v gives v8.15.1) and xterm.js-css#*npm(6.4.1). Looks like there is some issue with Bower itself as it's giving a HTTP 500 error for  xterm.js-css#*

Is anyone seeing similar issues? Any workarounds?

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
