### ISSUE TITLE
fresh installation fails on recent master with "Promise is not defined"

### ISSUE THREAD

**Issue by dkrenn** [jupyter/notebook#2057]
`git clone ...` and `pip install -e . --user` fails on recent master `68a514a29 - Merge pull request #2033 from vlimant/master` with
`ModuleBuildError: Module build failed: ReferenceError: Promise is not defined`.
It works with 4.3.1.

**Comment by gnestor** [comment]
Same as https://github.com/jupyter/notebook/issues/2056, try `npm install` and `npm run build`.

**Comment by gnestor** [comment]
`ModuleBuildError` sounds like a webpack error. We recently removed webpack from notebook, so if your local copy if up-to-date with upstream master (double-check!) and you're still seeing this, try `git clean -xfd` and `pip install -e .`.

**Comment by dkrenn** [comment]
This seems to be solved on https://github.com/jupyter/notebook/releases/tag/5.0.0-rc.1

**Comment by gnestor** [comment]
Great! Let's close this and re-open if you encounter it again.
