### ISSUE TITLE
Cycle among findings in search box

### ISSUE THREAD

**Issue by ggrrll** [jupyter/notebook#2058]
Hi,

another important feature that should be added is the possibility to cycle through all the results returned, after I search for something in the search box - in the _notebook editing mode_.

For now, by pressing 2 times <kbd>return</kbd>, you are  able to comment the cell - therefore actually deleting what you searched for. 

In the end you should  be asked, for instance, if you want to start the search again from the 'beginning of the document' or go back to type, like what happens for instance in many other editors.

**Comment by gnestor** [comment]
I agree that this would be better and the current workaround is to use the browser's native find feature by just clicking outside of the CodeMirror text field and pressing CMD+F (or CTRL+F). Given that, we may be better off just disabling the CodeMirror find feature (except its regex search feature is nice).

**Comment by jtpio** [comment]
Closing as the classic notebook UI has now been moved to https://github.com/jupyter/nbclassic.

Feel free to open a new issue there if it is still relevant, thanks!
