### ISSUE TITLE
Request functionality

### ISSUE THREAD

**Issue by nunocalaim** [jupyter/notebook#206]
I really don't know if this should be posted here:

Is there any way of creating a keyboard shortcut for the "run all" command?

It would be super useful for me, because I am forced to restart the kernel whenever I update my custom external library

**Comment by Carreau** [comment]
I'm trying to write some docs about that here : 

http://carreau.gitbooks.io/jupyter-book/content/Jsextensions.html

It is also what of the things we demoed in our tutorial last week: 

https://github.com/jupyter/scipy-advanced-tutorial/blob/master/Part1/04-notebook-extensions.md 

and the video : 

https://www.youtube.com/watch?v=38R7jiCspkw

Feel free to ask more questions if you can't make it to work (or make PRs if things are not clear and you think you can express them better)
