### ISSUE TITLE
Cycle among 'find' results 

### ISSUE THREAD

**Issue by ggrrll** [jupyter/notebook#2067]
Hi, 

in the script viewer (when I open for instance a .py file - _not a notebook_), after typing the string you are looking for in the search-box, you should be able to _cycle among instances until you reach the one you wanted_ , 
and not being able directly to edit after the 2nd time you press the 'return' key - like in other editors.

Thanks as usual for the support.

**Comment by ggrrll** [comment]
the solution might be similar to the one for  #2058

**Comment by gnestor** [comment]
I'm going to close this as it's a duplicate of https://github.com/jupyter/notebook/issues/2058
