### ISSUE TITLE
Errors on 'Custom front-end extensions' docs

### ISSUE THREAD

**Issue by kikocorreoso** [jupyter/notebook#2069]
Hi all,

Reference: http://jupyter-notebook.readthedocs.io/en/latest/extending/frontend_extensions.html#custom-front-end-extensions

I'm updating some of my stuff and I was re-reading some docs. When I arrive to this [example](http://jupyter-notebook.readthedocs.io/en/latest/extending/frontend_extensions.html#defining-and-registering-your-own-actions) I think there are some issues:

* In the line below I think `name` should be `action_name`:

```javascript
        var full_action_name = Jupyter.actions.register(action, name, prefix); // returns 'my_extension:show-alert'
```

* Also, the line above in conjunction with the line below are not adding the action and the button:

```javascript
        Jupyter.toolbar.add_buttons_group([full_action_name]);
```

I had to modify this:

```javascript
    function load_ipython_extension() {

        var handler = function () {
            alert('this is an alert from my_extension!');
        };

        var action = {
            icon: 'fa-comment-o', // a font-awesome class used on buttons, etc
            help    : 'Show an alert',
            help_index : 'zz',
            handler : handler
        };
        var prefix = 'my_extension';
        var action_name = 'show-alert';

        var full_action_name = Jupyter.actions.register(action, name, prefix); // returns 'my_extension:show-alert'
        Jupyter.toolbar.add_buttons_group([full_action_name]);
    }
```
with
```javascript
    function load_ipython_extension() {

        var handler = function () {
            alert('this is an alert from my_extension!');
        };

//        var action = {
//            'icon': 'fa-comment-o', // a font-awesome class used on buttons, etc
//            'callback' : handler,
//            'label': 'Kaka kaka kaka',
//            'id': 'idKaka'
//        };
//        var prefix = 'my_extension';
//        var action_name = 'show-alert';

//        var full_action_name = Jupyter.actions.register(action, action_name, prefix); // returns 'my_extension:show-alert'
//        Jupyter.toolbar.add_buttons_group([{full_action_name}]);
        Jupyter.toolbar.add_buttons_group(
              [{
                  'icon': 'fa-comment-o',
                  'callback' : handler,
                  'label': 'Kaka kaka kaka',
                  'id': 'idKaka'
              }]
        );
    }
```
to make it work.

Also, in this [section](https://github.com/jupyter/notebook/blob/master/docs/source/extending/frontend_extensions.rst#installing-and-enabling-extensions), this line:

`jupyter nbextension install path/to/my_extension/ [--user|--sys-prefix]`

should be:

`jupyter nbextension install path/to/my_extension [--user|--sys-prefix]`

i.e., without the final '/' in the path.

I can prepare a quick PR to solve these issues in case I'm not wrong.

**Comment by takluyver** [comment]
> In the line below I think name should be action_name:

Yup, I agree. PR welcome for that.

> Also, the line above in conjunction with the line below are not adding the action and the button:
>        Jupyter.toolbar.add_buttons_group([full_action_name]);

Looking at the code, I think that should work, so if it's going wrong, there's an issue in the code. @Carreau may want to investigate.

> without the final '/' in the path.

I think it should work with either - unless it has a specific significance, I think that code should ignore a trailing slash on paths. So if you want to make a PR for that, I'd rather it was fixed in the code than the docs.

**Comment by kikocorreoso** [comment]
Just to provide some context, all my tests were made in a new conda env, installing jupyter from conda and tested on Linux and windows 7 (32bits). The extensions were always installed using `--sys-prefix` option. Here is a list of the packages installed in the conda env in the w7 box:

```
# packages in environment at d:\users\someone\AppData\Local\Continuum\Miniconda3
\envs\jupytest:
#
ca-certificates           2016.9.26                     0    conda-forge
certifi                   2016.9.26                py35_0    conda-forge
colorama                  0.3.7                    py35_0    conda-forge
cycler                    0.10.0                   py35_0    conda-forge
decorator                 4.0.10                   py35_0    conda-forge
entrypoints               0.2.2                    py35_0    conda-forge
freetype                  2.6.3                    vc14_1  [vc14]  conda-forge
ipykernel                 4.5.2                    py35_0    conda-forge
ipython                   5.1.0                    py35_2    conda-forge
ipython_genutils          0.1.0                    py35_0    conda-forge
ipywidgets                5.2.2                    py35_2    conda-forge
jinja2                    2.8                      py35_1    conda-forge
jpeg                      9b                       vc14_0  [vc14]  conda-forge
jsonschema                2.5.1                    py35_0    conda-forge
jupyter-contrib-core      0.3.0                     <pip>
jupyter-highlight-selected-word 0.0.7                     <pip>
jupyter-latex-envs        1.3.6                     <pip>
jupyter-nbextensions-configurator 0.2.3                     <pip>
jupyter_client            4.4.0                    py35_0    conda-forge
jupyter_contrib_core      0.3.0                    py35_1    conda-forge
jupyter_core              4.2.1                    py35_0    conda-forge
jupyter_highlight_selected_word 0.0.7                    py35_0    conda-forge
jupyter_latex_envs        1.3.6                    py35_0    conda-forge
jupyter_nbextensions_configurator 0.2.3                    py35_0    conda-forge

libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libpng                    1.6.28                   vc14_0  [vc14]  conda-forge
libtiff                   4.0.6                    vc14_7  [vc14]  conda-forge
libxml2                   2.9.3                    vc14_9  [vc14]  conda-forge
markupsafe                0.23                     py35_1    conda-forge
matplotlib                2.0.0               np111py35_0    conda-forge
mistune                   0.7.3                    py35_0    conda-forge
mkl                       2017.0.1                      0
nbconvert                 4.2.0                    py35_0    conda-forge
nbformat                  4.2.0                    py35_0    conda-forge
notebook                  4.3.1                    py35_0    conda-forge
numpy                     1.11.3                   py35_0
openssl                   1.0.2h                   vc14_3  [vc14]  conda-forge
pickleshare               0.7.3                    py35_0    conda-forge
pip                       9.0.1                    py35_0    conda-forge
prompt_toolkit            1.0.9                    py35_0    conda-forge
psutil                    4.3.0                    py35_0    conda-forge
psutil                    5.0.1                     <pip>
pygments                  2.1.3                    py35_1    conda-forge
pyparsing                 2.1.10                   py35_0    conda-forge
pyqt                      4.11.4                   py35_2    conda-forge
python                    3.5.2                         5    conda-forge
python-dateutil           2.6.0                    py35_0    conda-forge
pytz                      2016.10                  py35_0    conda-forge
pyyaml                    3.11                     py35_0    conda-forge
PyYAML                    3.12                      <pip>
pyzmq                     16.0.2                   py35_0    conda-forge
qt                        4.8.7                    vc14_6  [vc14]  conda-forge
setuptools                33.1.0                   py35_0    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
sip                       4.18                     py35_1    conda-forge
six                       1.10.0                   py35_1    conda-forge
tornado                   4.4.2                    py35_0    conda-forge
traitlets                 4.3.1                    py35_0    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
wheel                     0.29.0                   py35_0    conda-forge
widgetsnbextension        1.2.6                    py35_3    conda-forge
win_unicode_console       0.5                      py35_0    conda-forge
wincertstore              0.2                      py35_0    conda-forge
yaml                      0.1.6                    vc14_0  [vc14]  conda-forge
zlib                      1.2.8                    vc14_3  [vc14]  conda-forge
```
> Also, the line above in conjunction with the line below are not adding the action and the button:
> `Jupyter.toolbar.add_buttons_group([full_action_name]);`

Tested in both, linux and windows and I can't see an error but the button is not in the frontend. I've tried some small modifications in the 'official' doc example, `handler` <-> `callback`, not providing `action_name` and `prefix`,... Also, defining and `action` object and trying to use it in the function was not working ¿?, e.g.:

```javascript
          //...
          action = {
                  'icon': 'fa-comment-o',
                  'callback' : handler,
                  'label': 'Kaka kaka kaka',
                  'id': 'idKaka'
              }
          Jupyter.toolbar.add_buttons_group([action]);
          /...
```

Regarding

> `without the final '/' in the path.`

In case I have:
```
my_extension1/
  main.js

my_extension2/
  main.js
```
And I want to install both when I use the trailing '/' `jupyter nbextension install my_extension1/` will copy the files inside the folder and not the folder so when I install the second extension, `my_extension2`, `main.js` of the first extension would be overwritten (as well as other files with same names. Also, There are problems with the uninstallation. Again, tested in both, linux and windows.

**Comment by Carreau** [comment]
I've added that on my looong todo list. If someone can get it first, please do.

**Comment by takluyver** [comment]
@kikocorreoso if you have time, could you:

1. Open a doc PR for the `action_name` fix - I think that's simple and correct.
2. Work out what's going on with nbextension install and the trailing slash. I think that specifying a directory with a trailing slash should work exactly as specifying it without the trailing slash. If you can find what's going wrong, a PR to fix that would be welcome.

Then if you're feeling keen, try to dig into the JS to see what's going wrong with adding toolbar buttons - there's definitely code there to handle adding them as an array of action names.

**Comment by kikocorreoso** [comment]
@takluyver @Carreau 

Sent a [PR](https://github.com/jupyter/notebook/issues/2077) for "1. Open a doc PR for the `action_name` fix - I think that's simple and correct."

Regarding the trailing slash (2.), Reading the [docs](https://github.com/jupyter/notebook/blob/master/notebook/nbextensions.py#L91):

```python
    path : path to file, directory, zip or tarball archive, or URL to install
        By default, the file will be installed with its base name, so '/path/to/foo'
        will install to 'nbextensions/foo'. See the destination argument below to change this.
        Archives (zip or tarballs) will be extracted into the nbextensions directory.
```

I think the problem is [here](https://github.com/jupyter/notebook/blob/master/notebook/nbextensions.py#L168):

```python
        if not destination:
            destination = basename(path)
```

If I do:

```python
In [1]: import os

In [2]: os.path.basename('my_extension/')
Out[2]: ''

In [3]: os.path.basename('my_extension')
Out[3]: 'my_extension'
```
I don't get the same. In the first case I would write the extension to the root of the `nbext` dir but in the second case I would include the complete folder for the extension. I don¡t know if this is the expected but for me it is weird and can drive to overwrite other files with same names.

**Comment by takluyver** [comment]
That does look likely to be the issue. I think calling `os.path.normpath()` on the path before passing it to basename should fix it; among other normalisations, that removes a trailing slash from the path.

No worries if you don't have time to get to the JS. I don't think any of us are very excited about trying to debug it!
