### ISSUE TITLE
Tree > Open a text file (or any editable file other than ipynb) > Blank page

### ISSUE THREAD

**Issue by gnestor** [jupyter/notebook#2071]
This appears to be a regression in 4.2 or 4.2.1. Possibly related to https://github.com/jupyter/notebook/commit/11bd42c35322b7914fdc7e7097b1a5b8a0623c7f.

https://github.com/jupyter/notebook/blob/master/notebook/static/edit/js/main.js#L46

```
 ReferenceError: contents is not defined     require.js?v=6da8be3…:900
    at main.js:46
    at Object.execCb (require.js?v=6da8be3…:1690)
    at Module.check (require.js?v=6da8be3…:865)
    at Module.<anonymous> (require.js?v=6da8be3…:1140)
    at require.js?v=6da8be3…:131
    at require.js?v=6da8be3…:1190
    at each (require.js?v=6da8be3…:56)
    at Module.emit (require.js?v=6da8be3…:1189)
    at Module.check (require.js?v=6da8be3…:940)
    at Module.enable (require.js?v=6da8be3…:1177)
```

**Comment by minrk** [comment]
That commit makes sense that it could cause such an error, but it wouldn't affect 4.2, since that commit is only in master. Can you see this error in a 4.2 release?

**Comment by gnestor** [comment]
Yes, I only see this is master. I tried the 4.2 branch and it works as expected.

**Comment by minrk** [comment]
Mark as 5.0, not 4.3, then?

**Comment by minrk** [comment]
#2073 ought to do it.
