### ISSUE TITLE
Cannot edit .rb files from the notebook dashboard

### ISSUE THREAD

**Issue by glampr** [jupyter/notebook#2072]
While clicking on all other files, opens them in an editor page, when clicking on *.rb files the browsers downloads the file instead of opening it in an editor.
The *.rb don't have any special permissions or chmod settings, i.e. txt, py, etc. files with the exact permissions and settings open in the editor.

Is there a way to configure which extensions to open in the editor?

**Comment by gnestor** [comment]
I can't reproduce using notebook 4.3.2 or master. I click on a `.rb` it open in the editor.

![screencap](http://g.recordit.co/yYErksOnJP.gif)

**Comment by glampr** [comment]
Using notebook 4.3.1 via JupyterHub 0.7.2 (just upgraded), and the problem is still there.
Even happens when I create new text file from the Jupyter web UI, the moment I save it as .rb file, it won't open in the editor anymore.

Is this something that was fixed from 4.3.1 -> 4.3.2 ?

What could cause this?
Is there a setting in jupyter regarding which extension/file types to view in editor or download?
Or it has to do with something on the file system?

**Comment by takluyver** [comment]
Probably to do with what mimetype the system tells us .rb files are. Can you try (in Python):

```python
import mimetypes
mimetypes.guess_type('foo.rb')
```

If it doesn't get a `text/something` mimetype, we won't try to edit it.

**Comment by glampr** [comment]
You are correct, python replies with ```('application/x-ruby', None)```.

Solution was to use the output of ```mimetypes.knownfiles``` and check the contents of these files for the mapping ```('application/x-ruby', None)``` which I replaced with ```('text/x-ruby', None)``` and now editing works!

Thanks for pointing me to the right direction.
