### ISSUE TITLE
Can't upload into a mounted dir

### ISSUE THREAD

**Issue by fbertsch** [jupyter/notebook#2074]
We use Jupyter Notebooks on EMR clusters to do analysis with Spark. I'm playing around with EFS mounted directories. When I have jupyter notebook running on a mounted dir, I can't upload a file (though I can open and run files just fine.)

**Comment by gnestor** [comment]
Ping @rgbkrk

**Comment by rgbkrk** [comment]
What happens when you try to upload a file?

**Comment by fbertsch** [comment]
So the process is:
1. I click upload, select my file from the directory viewer
2. Try and press "Upload" next to the file to be uploaded

I get the following:
```
Object { readyState: 4, getResponseHeader: .ajax/T.getResponseHeader(), getAllResponseHeaders: .ajax/T.getAllResponseHeaders(), setRequestHeader: .ajax/T.setRequestHeader(), overrideMimeType: .ajax/T.overrideMimeType(), statusCode: .ajax/T.statusCode(), abort: .ajax/T.abort(), state: .Deferred/r.state(), always: .Deferred/r.always(), then: .Deferred/r.then(), 12 more… }  main.min.js:13026:9
API request failed (403): Permission denied: android-events.ipynb  main.min.js:13028:9
Error: Permission denied: android-events.ipynb  main.min.js:13074:29
```

Looking at this, I'm *guessing* there's nothing you can do...

**Comment by fbertsch** [comment]
Alright, this is my fault. I just need to give the directory permissions. For any others that see this, just run `sudo chmod 777 $DIR` and things should work.
