### ISSUE TITLE
Error Installing Jupyter Notebook

### ISSUE THREAD

**Issue by AmirIvry-aka-AI** [jupyter/notebook#2081]
Hey,

I downloaded anaconda exactly according to the site instructions. The installatoin was marked completed.

When typing "Jupyter notebook" or "jupyter notebook" in the cmd I got an error (screenshot attached).

Also, when trying to use pip, as in "pip install jupyter", it is writen "requirement already satisfied: jupyter in c:\users\dell\anaconda2\lib\site-packages"

Thank you
![error](https://cloud.githubusercontent.com/assets/22732198/22402922/89a5f560-e610-11e6-814d-cd9d273317cd.JPG)

**Comment by takluyver** [comment]
If you run `conda list`, what version does it show for `notebook`. Try `conda update notebook` to make sure you have the latest. If you've got the latest version (4.3.1) and it's still showing that error, that sounds like an Anaconda packaging problem.

**Comment by minrk** [comment]
This is likely a problem with conda packages. You might try:

- conda remove notebook
- conda clean -tipsy
- conda install notebook
