### ISSUE TITLE
View and edit buttons show up when nothing is selected

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#2097]
Ping @gnestor 

![screenshot from 2017-01-31 14-45-55](https://cloud.githubusercontent.com/assets/327925/22469477/0ec38532-e7c4-11e6-9787-28a541e21f93.png)

**Comment by gnestor** [comment]
I've seen this before but I think it's an artifact of switching between branches. Try `npm run build` and hard-refreshing. That fixes it for me.

**Comment by takluyver** [comment]
You're right, sorry about that.
