### ISSUE TITLE
Getting help with ? when use in assignment duplicate the cell

### ISSUE THREAD

**Issue by Nagasaki45** [jupyter/notebook#2107]
When a cell with an assignment that include ? is evaluated the cell is duplicated. Here's an example:
![notebook_bug](https://cloud.githubusercontent.com/assets/2564187/22491651/dcc21bee-e81c-11e6-8ed3-fccad9499891.gif)

**Notebook version:** 4.3.1
**IPython version:** 5.1.0
**Python version:** 3.6.0

**Comment by Carreau** [comment]
Wow. Pretty sure that's an IPython bug. Not a notebook one. 

Good catch !

**Comment by takluyver** [comment]
This is in IPython, though it's actually a deliberate feature for the terminal that doesn't make much sense in the notebook.
