### ISSUE TITLE
Where should we be storing frontend config?

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#211]
- I thought we had agreed frontend config would go in platform specific directories (because users won't normally edit it directly), e.g. `~/.config/jupyter/nbconfig/` on Linux.
- Migration puts it in `~/.jupyter/nbconfig/`
- The notebook server looks for the files just in `~/.jupyter/`

We definitely need to ensure that the migration tool and the notebook server use the same folder for it. I think it's the notebook server that's wrong, because those files should have their own folder namespace.

**Comment by minrk** [comment]
> I thought we had agreed frontend config would go in platform specific directories

And I thought we had agreed that all config goes in .jupyter, because separating config based on how it's *likely* to be read/written is more confusing than "config goes here".

I think you are right that it's the notebook server looking in the wrong place, and migration is putting it in the right place.

**Comment by ellisonbg** [comment]
My memory agrees with Min's. I think that the nature of config is that
users may at one point or another need to edit it and that all of it should
go into the same place in .jupyter, not the platform specific places. I
think the "config goes here" idea is really important.

On Sun, Jul 19, 2015 at 12:58 PM, Min RK <notifications@github.com> wrote:

> I thought we had agreed frontend config would go in platform specific
> directories
>
> And I thought we had agreed that all config goes in .jupyter, because
> separating config based on how it's *likely* to be read/written is more
> confusing than "config goes here".
>
> I think you are right that it's the notebook server looking in the wrong
> place, and migration is putting it in the right place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/211#issuecomment-122698251>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
