### ISSUE TITLE
Terminals broken

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#2113]
When I start a terminal, I don't see any prompt or other text in the black area, and I can't type anything, but this appears in the lower left corner:

![screenshot from 2017-02-01 17-44-14](https://cloud.githubusercontent.com/assets/327925/22518868/2c60498a-e8a6-11e6-8e67-a0c94ac98282.png)

I've rebuilt the JS and CSS, made sure I'm not hitting the browser cache, and tested it in both Firefox and Chromium, with the same results. I also tried upgrading xtermjs to 2.2.3, the latest release, and still saw the same. I guess that maybe some of our CSS/JS is clashing with that of xtermjs? @yuvipanda , you've done stuff with terminals recently, do you have a chance to look at it?

There are no errors in the terminal, and nothing that looks relevant in the JS console:

```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Learn More]
resize to : 57 rows by  138 columns
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
resize to : 41 rows by  138 columns
```

**Comment by takluyver** [comment]
$SHELL is set to `/bin/bash`.

**Comment by Carreau** [comment]
I think that's more than CSS, the `div.xtem-rows` is actually outside of the `div.xterm-scroll-area`, while it should be in it.

**Comment by gnestor** [comment]
I can confirm that 4.x branch does not have this issue...

**Comment by gnestor** [comment]
Likely culprit: https://github.com/jupyter/notebook/commit/47d44519584f894c0b8bac55a2e234d532bb14db

**Comment by gnestor** [comment]
It looks like we were requiring `xterm/src/xterm.css` but now that we don't have webpack, how should we include xterm's CSS?

**Comment by blink1073** [comment]
IIRC they have a bower package.

**Comment by blink1073** [comment]
I'll look into this tomorrow morning.

**Comment by blink1073** [comment]
Nevermind, Hrant already fixed it. ;)
