### ISSUE TITLE
Make "Find and Replace" cell only by default?

### ISSUE THREAD

**Issue by Jessime** [jupyter/notebook#2115]
I use the Find and Replace function quite a bit, but I don't think I've every intentionally used it on the whole notebook. I'm always trying to modify a single cell. Unfortunately, I have used it on my entire notebook by accident multiple times (by forgetting to click the "replace in selected cells" button). So, I have a multi-part question:

1. Is there a way I can turn that button on by default to avoid this mistake in the future?
2. Do other people have this problem? If so, is it worth considering making this the default setting for everyone? Making the opposite mistake (of only changing in a single cell) seems much less significant.
3. If there's no feasible way to accomplish 1 or 2, what's the best way to undo this mistake? Ctrl+Z doesn't really work. 

Thanks!

**Comment by Carreau** [comment]
> Is there a way I can turn that button on by default to avoid this mistake in the future?

I don't believe there is a simple way to do that. 

> Do other people have this problem? If so, is it worth considering making this the default setting for everyone? Making the opposite mistake (of only changing in a single cell) seems much less significant.

I have not heard people complaining. You point of making it the default is a good one. 


> If there's no feasible way to accomplish 1 or 2, what's the best way to undo this mistake? Ctrl+Z doesn't really work.

None that I know of. Let's tag that as 5.0 to decide. it should not be hard to change.

**Comment by Carreau** [comment]
We'll be happy if you want to attempt sending a PR !

**Comment by Jessime** [comment]
It's in my calendar to take a look at it this weekend! The bad news is: I've never made a PR before, and have a only written a handful of functions in JS. So this may not go well, but I'll give it a shot.

**Comment by Carreau** [comment]
> The bad news is: I've never made a PR before

Well I have a good news then, we'll be happy to guide you through it, and don't worry you can't really screw up. We'll also be honored to receive your first contribution on GitHub.

![beeea97c622c5614a80371eb0aece7082a3ff1b50421cf5acae3125c65ba5d8f](https://cloud.githubusercontent.com/assets/335567/22537732/c7a251fc-e8c1-11e6-9148-2a1b0cc4b099.jpg)

Don't hesitate to ask !

**Comment by Jessime** [comment]
So here's what I've done so far:

1. I forked and cloned the project.
2. I made the necessary changes and manually tested them. Everything looked good.
3. I tried running the JS tests by doing `npm install -g casperjs phantomjs@1.9.18` then running `python -m notebook.jstest` in the notebook directory. 

There's a lot of output, much of which I can't interpret. But it seems a lot of things are failing because: `".CodeMirror-code" still did not exist in 10000ms`. I've attached the rest of the output. I can't find any clues in the [Contributing](https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.rst) and don't know where else to look. 

Any thoughts? And thanks for offering to help me out with this!

**Comment by Carreau** [comment]
Don't worry too much about testing locally, it is relatively hard with the
notebook.

What you can do is commit, and push on your fork on a new branch. Then
submit a pull request. Even if not done completly it's OK, you can change
afterward.

Travis will take care of testing and we can start reviewing.

I can give you more details instructions but I'm on my phone for now

**Comment by blink1073** [comment]
I'm calling this one fixed by #2131, feel free to reopen if anyone disagrees.

**Comment by tlqtangok** [comment]
I also find I need find and replace in only one cell
