### ISSUE TITLE
Header auto-id generation overwrites ids applied with explicit html

### ISSUE THREAD

**Issue by mpacer** [jupyter/notebook#2117]
If you include the following in a markdown cell, it will respect the color information, but it will overwrite the header's manually specified id. 

```html
<h1 id="my_id" style="color: red">anything</h1>
```
will create  a dom element with 

```html
<h1 id="anything" style="color: red">anything<a class="anchor-link" href="#anything">¶</a></h1>
```

cc @Carreau @ian-r-rose

**Comment by Carreau** [comment]
We figured it out.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
