### ISSUE TITLE
The first kernel_info_reply is not received and timeout.

### ISSUE THREAD

**Issue by KelvinJin** [jupyter/notebook#2118]
I'm building a Swift kernel for Notebook. This issue has been there since day one. The socket library I'm using is https://github.com/Zewo/ZeroMQ.git.

I run notebook using `jupyter-notebook --Session.key="b''" --Session.debug=True --debug`. According to the logs printed, the first `kernel_info_request` was received by my kernel and the `kernel_info_reply` is sent successfully (based on the return value of the zmq's `zmq_send` method) by my kernel as well. However, it's still timeout on Notebook end.

I briefly looked through the implementation related to this and found [this](https://github.com/jupyter/notebook/blob/master/notebook/services/kernels/handlers.py#L234). The code looks okay to me so I'm confused.

I know this might be an issue on my end, but I'm sure the `kernel_info_reply` message has been sent successfully (at least according to the zmq's return value.) I wonder if you guys have seen such issue before?

BTW, the kernel i'm writing is also open source at [here](https://github.com/KelvinJin/iSwift.Linux) but you probably don't want to look at it...

---

One thing to note is that after the timeout, the session continues and somehow sends another `kernel_info_request`. This time the `kernel_info_reply` is received successfully.

Also, the first `kernel_info_request` and the subsequent one are different in terms of the `msg_id` and `username`.

_First one_

```
[b'<IDS|MSG>',
 b'',
 b'{"username":"owenwj","version":"5.0","msg_type":"kernel_info_request","session":"F0A7C01E6F3646FE85C64B578CEC04A3","msg_id":"2b839758-157f-4ec9-9fec-bf9e32817113","date":"2017-02-02T13:55:06.587925"}',
 b'{}',
 b'{}',
 b'{}']
[]
```

_Second one_

```
[b'<IDS|MSG>',
 b'',
 b'{"username":"username","session":"F0A7C01E6F3646FE85C64B578CEC04A3","msg_id":"A0A42472F9CA48F98A86692F38532D0E","version":"5.0","msg_type":"kernel_info_request"}',
 b'{}',
 b'{}',
 b'{}']
[]
```

**Comment by takluyver** [comment]
> the kernel_info_reply is sent successfully (based on the return value of the zmq's zmq_send method)

I don't know if it's relevant, but 'sending' a message with zmq actually puts it in a queue, and a background thread zmq is running sends it out at some point later. So the return value of `zmq_send` doesn't necessarily mean that it's actually sent OK. I think that would only affect you if there was a bug in the ZMQ bindings you're using, though.

**Comment by KelvinJin** [comment]
@takluyver Thanks for your reply. It's really weird given that the second reply is received. I wonder if there is any difference between how the replies are expected in the first and second situations. 

Also, for zmq, I can use the `zmq_sendmsg` to send a `message` instead of a `string`. Not sure if they're different though.

**Comment by takluyver** [comment]
That is weird. I'd guess that the first `kernel_info_request` is coming from the notebook server and the second from the Javascript in the browser.

**Comment by KelvinJin** [comment]
@takluyver wait...So the Javascript are connecting to the kernel directly or via the server? If directly then, that might be the reason why these two have different behaviours.

**Comment by takluyver** [comment]
No, the JS connects via the server. It uses websockets to communicate from the browser to the server, and the server than sends those messages on over zmq. It may well explain why the username field is different, though.

**Comment by KelvinJin** [comment]
@takluyver `username` Indeed. I tried on three different machines/systems (macos and linux), the results are the same. Is there a way to debug local tcp data transportation? As if I can see what data is tranferring between the ports...

**Comment by takluyver** [comment]
Have you tried your kernel with `jupyter console` or `jupyter qtconsole`? There's less going on there, so it may be easier to debug things. I think the `--debug` flag on the Qt console shows what messages it sends and receives.

**Comment by KelvinJin** [comment]
@takluyver Ha, finally we got something. Thanks for the suggestion. So when I ran `jupyter console --Session.key="b''" --debug --Session.debug=True --kernel=MyKernel`, it seems that the server sent out two `kernel_info_request`s immediately. And my kernel actually received both and replied both. And this time, both replies are received! It's weird though...

I wonder if I should wait for several seconds before I reply to the first `kernel_info_request`. I'll try tomorrow when I have time. Meanwhile, if you have any thoughts, please let me know!

**Comment by takluyver** [comment]
That's weird. I don't think any of the other kernels need a wait to respond to kernel_info_request messages...

**Comment by KelvinJin** [comment]
@takluyver Setting a delay didn't work. I wonder why there were two `kernel_info_request`s sent out when the `jupyter console` started.

The logs can be found [here](https://gist.github.com/KelvinJin/50393936c62c871bc3731d32040927be)

So, the console received both replies somehow and the notebook didn't...I'm really confused now.

**Comment by KelvinJin** [comment]
#1281 It might be related to this issue to be honest. I'll have a look!

**Comment by KelvinJin** [comment]
This is solved. It was my issue. I guess it's related to the `identity` (aka u-u-i-d) field of the message. I was always using the session id of the header to be the identity. I replaced it with the `identities` from the request, it seems to work now! (Note that there might be several _identities_.)

**Comment by takluyver** [comment]
Great! Yes, identities are something zmq uses to deliver replies corresponding to a request.

**Comment by jondoesntgit** [comment]
Is there a way to configure the amount of time that Jupyter waits for a kernel to start before timing out? I have a kernel that takes 40 seconds to start (external kernel on a very small linux box that Jupyter ssh into)
