### ISSUE TITLE
Command palette not working in Chrome

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#2122]
I can make it appear, and type into it, but no actions come up, and if I press enter, the page reloads.

![screenshot from 2017-02-02 10-27-31](https://cloud.githubusercontent.com/assets/327925/22545843/5b58cf78-e932-11e6-97fe-0f8bd0c692fd.png)

**Comment by takluyver** [comment]
I've gone through the usual steps of rebuilding JS and dodging any browser caching issues.

**Comment by gnestor** [comment]
I can't reproduce on master...

**Comment by takluyver** [comment]
Once I added a shortcut to avoid #2121, I got exactly the same symptoms on Firefox.

Am I using it wrong? I assumed I would just start typing and commands would appear below. Is there something specific I should type? I've been trying obvious things like 'restart' and 'insert'.

Am I rebuilding CSS/JS wrong? I use `python setup.py css js`, which seems to work correctly. I can change the JS, rebuild it and see the changes take effect.

**Comment by gnestor** [comment]
Your screenshot seems to suggest that your JS/CSS if out-of-whack. And I can't reproduce in Chrome or Firefox. So you can always try a `git clean -xfd` and `pip install -e .`.

**Comment by takluyver** [comment]
I deleted my clone of the repo, re-cloned it and installed notebook afresh. Still there. I have found, though, that if I press `p` at some point while the page is still loading, I do get a functional command palette. If I wait for it to finish loading, I get the broken version. Even if I get it functional, dismissing it and re-showing it breaks it.

This makes me suspect that an extension has broken it.

**Comment by takluyver** [comment]
Yep, it's a collision with `cite2c`, which also uses typeahead. I think that it currently ships its own copy of typeahead; maybe it should be using the one in jupyter instead.

**Comment by takluyver** [comment]
Oh crap.

- Typeahead used by command palette: https://github.com/running-coder/jquery-typeahead
- Typeahead used by cite2c: https://github.com/twitter/typeahead.js/

They both add the `.typeahead()` method to jQuery objects. Similar, but incompatible methods.

I hate Javascript.

**Comment by takluyver** [comment]
I found a workaround in cite2c to deconflict the methods.

**Comment by gnestor** [comment]
@takluyver Javascript: You can't live with it, you can't live without it. I'm glad you figured this out!
