### ISSUE TITLE
Is there a way to piggyback on the heartbeat message from a custom kernel ?

### ISSUE THREAD

**Issue by uditabose** [jupyter/notebook#2125]
I am aware that there is no cron-like feature with Jupyter. There is an issue that was with similar request is in closed status - https://github.com/jupyter/notebook/issues/1034. From the Kernel API itself I can't find any function that gets called repeatedly by the kernel manager. I wanted to know if there is a way I can utilize the heartbeat call.

**Comment by takluyver** [comment]
The notebook already doesn't use the heartbeat, and we're moving away from it in general, so I wouldn't rely on it.

**Comment by takluyver** [comment]
But if your kernel is based around an event loop, there should be some way to do a periodic callback using that.

**Comment by uditabose** [comment]
Hi @takluyver thanks for the suggestion - I will give it a try.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
