### ISSUE TITLE
Stopping Jupyter Notebook server with Ctrl-C raises error

### ISSUE THREAD

**Issue by akapocsi** [jupyter/notebook#2126]
Recently, whenever I stop a Jupyter Notebook server with Ctrl-C it raises the following error:

![image](https://cloud.githubusercontent.com/assets/8197282/22554902/d5dac038-e92f-11e6-8d15-2b6a266bc5e4.png)
Here is the full traceback text:

[I 09:54:20.827 NotebookApp] Shutting down kernels
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1247, in start
    self.io_loop.start()
  File "C:\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 862, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "C:\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "C:\Anaconda3\lib\site-packages\zmq\sugar\poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll (zmq\backend\cython\_poll.c:2186)
  File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq_poll (zmq\backend\cython\_poll.c:2036)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\_poll.c:2418)
    PyErr_CheckSignals()
  File "C:\Anaconda3\lib\site-packages\conda\gateways\signals.py", line 15, in conda_signal_handler
    raise CondaSignalInterrupt(signum)
conda.exceptions.CondaSignalInterrupt: Signal interrupt SIGINT

I am operating on Windows 10 and here is my conda package list:

_license=1.1=py35_1
_nb_ext_conf=0.3.0=py35_0
alabaster=0.7.9=py35_0
anaconda=4.3.0=np111py35_0
anaconda-clean=1.0.1=py35_0
anaconda-client=1.6.0=py35_0
anaconda-navigator=1.4.3=py35_0
argcomplete=1.0.0=py35_1
astroid=1.4.9=py35_0
astropy=1.3=np111py35_0
babel=2.3.4=py35_0
backports=1.0=py35_0
beautifulsoup4=4.5.3=py35_0
bitarray=0.8.1=py35_1
blaze=0.10.1=py35_0
bokeh=0.12.4=py35_0
boto=2.45.0=py35_0
bottleneck=1.2.0=np111py35_0
bzip2=1.0.6=vc14_3
cffi=1.9.1=py35_0
chardet=2.3.0=py35_0
chest=0.2.3=py35_0
click=6.7=py35_0
cloudpickle=0.2.2=py35_0
clyent=1.2.2=py35_0
colorama=0.3.7=py35_0
comtypes=1.1.2=py35_0
conda=4.3.8=py35_0
conda-build=2.0.10=py35_0
conda-env=2.6.0=0
conda-verify=2.0.0=py35_0
configobj=5.0.6=py35_0
console_shortcut=0.1.1=py35_1
contextlib2=0.5.4=py35_0
cryptography=1.7.1=py35_0
curl=7.52.1=vc14_0
cycler=0.10.0=py35_0
cython=0.25.2=py35_0
cytoolz=0.8.2=py35_0
dask=0.13.0=py35_0
datashape=0.5.4=py35_0
decorator=4.0.11=py35_0
dill=0.2.5=py35_0
docutils=0.13.1=py35_0
dynd-python=0.7.2=py35_0
entrypoints=0.2.2=py35_0
et_xmlfile=1.0.1=py35_0
fastcache=1.0.2=py35_1
filelock=2.0.7=py35_0
flask=0.12=py35_0
flask-cors=3.0.2=py35_0
freetype=2.5.5=vc14_2
get_terminal_size=1.0.0=py35_0
gevent=1.2.1=py35_0
greenlet=0.4.11=py35_0
h5py=2.6.0=np111py35_2
hdf5=1.8.15.1=vc14_4
heapdict=1.0.0=py35_1
icu=57.1=vc14_0
idna=2.2=py35_0
imagesize=0.7.1=py35_0
inflection=0.3.1=py35_0
ipykernel=4.5.2=py35_0
ipython=5.1.0=py35_0
ipython_genutils=0.1.0=py35_0
ipywidgets=5.2.2=py35_1
isort=4.2.5=py35_0
itsdangerous=0.24=py35_0
jdcal=1.3=py35_0
jedi=0.9.0=py35_1
jinja2=2.9.4=py35_0
jpeg=9b=vc14_0
jsonschema=2.5.1=py35_0
jupyter=1.0.0=py35_3
jupyter_client=4.4.0=py35_0
jupyter_console=5.0.0=py35_0
jupyter_core=4.2.1=py35_0
kerberos-sspi=0.2=py35_0
lazy-object-proxy=1.2.2=py35_0
libdynd=0.7.2=0
libpng=1.6.27=vc14_0
libtiff=4.0.6=vc14_3
llvmlite=0.15.0=py35_0
locket=0.2.0=py35_1
lxml=3.7.2=py35_0
markupsafe=0.23=py35_2
matplotlib=2.0.0=np111py35_0
menuinst=1.4.4=py35_0
mistune=0.7.3=py35_0
mkl=2017.0.1=0
mkl-service=1.1.2=py35_3
more-itertools=2.2=py35_0
mpmath=0.19=py35_1
multipledispatch=0.4.9=py35_0
nb_anacondacloud=1.2.0=py35_0
nb_conda=2.0.0=py35_0
nb_conda_kernels=2.0.0=py35_0
nbconvert=4.2.0=py35_0
nbformat=4.2.0=py35_0
nbpresent=3.0.2=py35_0
networkx=1.11=py35_0
nltk=3.2.2=py35_0
nose=1.3.7=py35_1
notebook=4.3.1=py35_1
numba=0.30.1=np111py35_0
numexpr=2.6.1=np111py35_2
numpy=1.11.3=py35_0
numpydoc=0.6.0=py35_0
odo=0.5.0=py35_1
openpyxl=2.4.1=py35_0
openssl=1.0.2k=vc14_0
pandas=0.19.2=np111py35_1
partd=0.3.7=py35_0
path.py=10.0=py35_0
pathlib2=2.2.0=py35_0
patsy=0.4.1=py35_0
pep8=1.7.0=py35_0
pickleshare=0.7.4=py35_0
pillow=4.0.0=py35_0
pip=9.0.1=py35_1
pkginfo=1.4.1=py35_0
plotly=1.12.9=py35_0
ply=3.9=py35_0
prompt_toolkit=1.0.9=py35_0
psutil=5.0.1=py35_0
py=1.4.32=py35_0
pyasn1=0.1.9=py35_0
pycosat=0.6.1=py35_1
pycparser=2.17=py35_0
pycrypto=2.6.1=py35_5
pycurl=7.43.0=py35_2
pyflakes=1.5.0=py35_0
pygments=2.1.3=py35_0
pylint=1.6.4=py35_1
pyodbc=3.0.10=py35_1
pyopenssl=16.2.0=py35_0
pyparsing=2.1.4=py35_0
pyqt=5.6.0=py35_2
pyreadline=2.1=py35_0
pytables=3.2.2=np111py35_4
pytest=3.0.5=py35_0
python=3.5.2=0
python-dateutil=2.6.0=py35_0
pytz=2016.10=py35_0
pywin32=220=py35_2
pyyaml=3.12=py35_0
pyzmq=16.0.2=py35_0
qt=5.6.2=vc14_3
qtawesome=0.4.3=py35_0
qtconsole=4.2.1=py35_2
qtpy=1.2.1=py35_0
quandl=3.0.1=py35_0
requests=2.12.4=py35_0
requests-kerberos=0.8.0=py35_0
rope=0.9.4=py35_1
ruamel_yaml=0.11.14=py35_0
scikit-image=0.12.3=np111py35_1
scikit-learn=0.18.1=np111py35_1
scipy=0.18.1=np111py35_1
seaborn=0.7.1=py35_0
setuptools=27.2.0=py35_1
simplegeneric=0.8.1=py35_1
singledispatch=3.4.0.3=py35_0
sip=4.18=py35_0
six=1.10.0=py35_0
snowballstemmer=1.2.1=py35_0
sockjs-tornado=1.0.3=py35_0
sphinx=1.5.1=py35_0
sphinx_rtd_theme=0.1.9=py35_0
spyder=3.1.2=py35_0
sqlalchemy=1.1.5=py35_0
statsmodels=0.6.1=np111py35_1
sympy=1.0=py35_0
tk=8.5.18=vc14_0
toolz=0.8.2=py35_0
tornado=4.4.2=py35_0
traitlets=4.3.1=py35_0
unicodecsv=0.14.1=py35_0
vs2010_runtime=10.00.40219.1=2
vs2015_runtime=14.0.25123=0
wcwidth=0.1.7=py35_0
werkzeug=0.11.15=py35_0
wheel=0.29.0=py35_0
widgetsnbextension=1.2.6=py35_0
win_unicode_console=0.5=py35_0
wrapt=1.10.8=py35_0
xlrd=1.0.0=py35_0
xlsxwriter=0.9.6=py35_0
xlwings=0.10.2=py35_0
xlwt=1.2.0=py35_0
zlib=1.2.8=vc14_3

**Comment by takluyver** [comment]
Thanks, this is already tracked as #2110.
