### ISSUE TITLE
The new view button for html file is not working

### ISSUE THREAD

**Issue by randy3k** [jupyter/notebook#2143]
<img width="759" alt="screen shot 2017-02-06 at 9 33 12 pm" src="https://cloud.githubusercontent.com/assets/1690993/22675490/0c8ff13e-ecb4-11e6-8cbc-638aabdad9f3.png">

while the url `..../user/randy3k/files/foo.html` still works.

It is possibly due to https://github.com/jupyter/notebook/commit/224294c2743df1df2855ea511ad4f612080472b0
or it is an issue for jupyterhub.

**Comment by takluyver** [comment]
@minrk can you take a look at this?

**Comment by minrk** [comment]
On it.

**Comment by minrk** [comment]
#2145 should do it.
