### ISSUE TITLE
Wonky alignment in shortcut editor in Firefox

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#2147]
@Carreau could you take a look? It seems to affect rows immediately below ones with a shortcut defined.

![screenshot from 2017-02-07 15-21-05](https://cloud.githubusercontent.com/assets/327925/22697400/3c14078e-ed49-11e6-9590-2835af6d62f7.png)

**Comment by Carreau** [comment]
I'm pretty sure I don't see it.
FF ? Which version ?

**Comment by takluyver** [comment]
51.0.1. Maybe it's another issue with an extension interfering with something, I'll check.

**Comment by takluyver** [comment]
I've disabled extensions, rebuilt css & js on master (fc2e03a781b39306d9ce257d32ad927e759bb7ee) and running with a different port to avoid the cache. I still see it.

**Comment by Carreau** [comment]
Nah, I see it. wait for a PR soon.

**Comment by takluyver** [comment]
Awesome, thanks :-)
