### ISSUE TITLE
keyboard shortcuts for navigating file tree

### ISSUE THREAD

**Issue by niole** [jupyter/notebook#215]
Has anyone thought of/implemented keyboard shortcuts for navigating the notebook's file tree? Maybe a hjkl or arrow-key navigation option would be nice to have.

**Comment by Carreau** [comment]
Yes, it is planned, in a global rewriting of the dashboard. Though it is a non negligeable amount of work which does not have priority. Unless someone start working on it.

**Comment by JamiesHQ** [comment]
@Carreau @gnestor @blink1073 : what is the status of implementing this kind of functionality? Thanks!

**Comment by gnestor** [comment]
Closing this for now. @niole Feel free to re-open if you would like to continue work on https://github.com/jupyter/notebook/issues/217.
