### ISSUE TITLE
4.4 Release Schedule

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#2161]
See discussion here: #2022 

I think we should make a 4.4 release to enable ipywidgets 6.0 to move forward.

Github Project: https://github.com/jupyter/notebook/projects/3

* [x] Merge open PRs marked with 4.4: https://github.com/jupyter/notebook/pulls?q=is%3Aopen+is%3Apr+milestone%3A4.4
* [x] Backport all merged PRs marked with 4.4
* [x] Update changelog
  * https://github.com/jupyter/notebook/pull/2163
* [x] UX test 4.x branch
  * [Widget List.ipynb](https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20List.ipynb)
* [x] Run tests against 4.x branch: https://github.com/jupyter/notebook/blob/4.x/CONTRIBUTING.md#running-tests
* [x] Cut a release and upload build to PyPI: https://jupyter-notebook.readthedocs.io/en/latest/development_release.html

**Comment by jasongrout** [comment]
@SylvainCorlay - did you want to look into that queued execution thing that you say is causing problems with nbextensions? I'm happy to sit down with you and try to think it through - I'm still don't quite understand how those are conflicting.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay - did you want to look into that queued execution thing that you say is causing problems with nbextensions? I'm happy to sit down with you and try to think it through - I'm still don't quite understand how those are conflicting.

I have been trying to reproduce it with notebook 5 and could not trigger the faulty behavior. I would be happy to discuss this tomorrow.

**Comment by SylvainCorlay** [comment]
Thanks @ellisonbg for opening this. This would be super helpful to go ahead with the ipywidgets release.

**Comment by gnestor** [comment]
Ok, does everyone agree that we should push 4.4 out today with just https://github.com/jupyter/notebook/pull/2022?

**Comment by ellisonbg** [comment]
We should confirm with @minrk @takluyver first as they have been doing lots of the work for 5.0. But I am +1

**Comment by minrk** [comment]
I'm fine with 4.4 with just this. Since 4.3 introduced the token stuff, it could be logical to include [`jupyter notebook password`](https://github.com/jupyter/notebook/pull/2007) in the backport, since it is related to making notebook auth easier. But since 5.0 is quite soon as well, I don't think it needs a backport.

**Comment by ellisonbg** [comment]
I am fine either way with the `jupyter notebook password`. If it is easy and quick to backport sounds good, otherwise, no worry.

**Comment by gnestor** [comment]
I just UX tested `Widget List.ipynb` and everything appears to be working properly

**Comment by gnestor** [comment]
JS test results: 

```
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/utils.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js
    uncaughtError: ".CodeMirror-code" still did not exist in 10000ms
```
None of these seem related to https://github.com/jupyter/notebook/pull/2022, but please chime in if anything looks suspicious. I will run Travis against 4.x branch before releasing.

**Comment by minrk** [comment]
It's a relatively easy backport. There are docs that specifically reference 'new in 5.0' that would need to be updated, though, so it might not be worth the bother.
