### ISSUE TITLE
4.4.1

### ISSUE THREAD

**Issue by minrk** [jupyter/notebook#2167]
From the PyPI logs, it looks like @gnestor uploaded 4.4.0 and then deleted the release an hour later. This led to some confusion, as `pypi.org` had notebook at 4.4.0, but `pypi.python.org` only had 4.3.2 (it turns out pypi.python.org was the one in the correct state). This means if we want a 4.4 release, we have to make 4.4.1.

**Comment by gnestor** [comment]
I just pinged @Carreau about this... Last night, the 4.x Travis build passed so I published 4.4.0 to PyPI. I then received an email that another 4.x build errored, so I went to PyPI and removed the 4.4.0 version, just to be safe. I did some reading and it appears that 4.4.0 is now locked out! So it appears that we have to release under a different version, e.g. 4.4.1 (or can we do 4.4.0.1)?

**Comment by minrk** [comment]
You can never re-upload files on PyPI, so removing a release is a big deal. Hiding it is a safer action. If 4.4.0 needs to be changed after uploading to PyPI, the only option is to make a new 4.4.1 release.

**Comment by gnestor** [comment]
Ya, now I know. DON'T DELETE RELEASES FROM PYPI. Sorry about that all...

**Comment by gnestor** [comment]
I'm building 4.4.1 now...

**Comment by jasongrout** [comment]
Thanks!

**Comment by SylvainCorlay** [comment]
Thanks!

**Comment by gnestor** [comment]
One other question: I backported the release notes with https://github.com/jupyter/notebook/pull/2164 but the [commit history on 4.x](https://github.com/jupyter/notebook/commits/4.x) reads "Merge branch '4.x' of https://github.com/jupyter/notebook into jupyte…". Any idea why?

**Comment by minrk** [comment]
@gnestor no problem, I did the same thing with pyzmq a while ago, which is how I learned about these things.

**Comment by gnestor** [comment]
Ok wait a minute! @minrk I'm seeing 4.4.0 on pypi.python.org again!

**Comment by minrk** [comment]
@gnestor ignore that, I was messing around to see if I could reinstate 4.4.0. I could re-upload the tarball as `.tgz` to get around the re-upload enforcement, but can't do the same with the wheel.

**Comment by minrk** [comment]
I don't know what the weird merge commit would be, but I wouldn't worry about it. The actual content looks fine.

**Comment by gnestor** [comment]
Ya, ok 👌

**Comment by gnestor** [comment]
Ok, 4.4.1 is live: https://pypi.python.org/pypi/notebook

**Comment by minrk** [comment]
Thanks, @gnestor!

**Comment by gnestor** [comment]
Thank you @minrk

**Comment by jasongrout** [comment]
@gnestor - please don't forget to push the commit changing the version number to 4.4.1.

**Comment by gnestor** [comment]
Done!: https://github.com/jupyter/notebook/commits/4.x

**Comment by Carreau** [comment]
Thanks all for taking care of this !

**Comment by minrk** [comment]
@gnestor did you forget to push the tag for 4.4.1?

**Comment by gnestor** [comment]
It looks as though I did...it's pushed now.
