### ISSUE TITLE
Token Authentication - Not seeing any token.

### ISSUE THREAD

**Issue by MissOgra** [jupyter/notebook#2180]
Hello all,

I'm having a lot of trouble since I updated Jupyter. I want to open a notebook and I keep getting a field to enter a password or token. I read about it in the documentation, my problem is I enter `jupyter notebook list ` but I can't see any token:

```
Last login: Sun Feb 12 21:57:17 on ttys000
Carolinas-MacBook-Pro:~ MissOgra$ jupyter notebook list
Currently running servers:
http://localhost:8888/ :: /Users/MissOgra
```

What can I do in this case? I'd highly appreciate your help.

Thank you in advance. 

Carolina.

**Comment by takluyver** [comment]
What does `jupyter notebook --version` give you? It's possible that the version it's finding in the terminal is older than the version you're running the notebook server with.

**Comment by MissOgra** [comment]
Thank you for your answer. I get 4.2.3

**Comment by takluyver** [comment]
Yep, the token authentication by default was added in 4.3, so you've got two different versions installed somewhere. `which jupyter-notebook` might show you where it's launching from. Can you update it to the latest release?

**Comment by MissOgra** [comment]
I ran your command and I get /Users/MissOgra/anaconda3/bin/jupyter-notebook I tried updating with conda and pip, and the version is still the same. It keeps telling me that it's up to date.

**Comment by takluyver** [comment]
There should be newer versions than that available. Maybe try uninstalling with both tools and then install it anew with just one of them? Check `conda list` and `pip list` to see what versions they think are installed. Unfortunately the two tools can mess things up for each other sometimes. Or activate the conda env your notebook server runs from and try running `jupyter notebook list` in there.

**Comment by MissOgra** [comment]
It worked, you were right. Thank you very much for your help :)

**Comment by Toseef99** [comment]
I am facing the same issue, though `pip ` and  `conda ` lists are showing the version of `jupyter`. A quick help will be appreciated. Thank you.

**Comment by Archviz360** [comment]
same here i cant see my token and that causes me to not being able to connect to google collab :( is there anyone here that can help me????
