### ISSUE TITLE
After changing font size, cursor position is incorrect on current line  in jupyter notebook.

### ISSUE THREAD

**Issue by shanhaiying** [jupyter/notebook#2183]
As the title says,  the cursor can not display normally when font size is changed.
See the following  screencap:

![exam](https://cloud.githubusercontent.com/assets/1595652/22891344/fd007694-f249-11e6-8ca5-358db6ebe168.gif)

**Comment by gnestor** [comment]
What version of the notebook are you running (`jupyter notebook --version`)? What browser?

**Comment by shanhaiying** [comment]
![image](https://cloud.githubusercontent.com/assets/1595652/22908176/e6223208-f287-11e6-92ce-1768d4676337.png)
I have  tested it in Firefox, Chrome and Safari. The cursor can not display correctly in those browsers.

**Comment by takluyver** [comment]
I'd guess that this is a bug of some kind in Codemirror. Can you experiment with the demos here? http://codemirror.net/mode/python/index.html

For reference, here's the notebook cell to reproduce it as text (can't copy/paste from a screenshot):

```
%%html
<style type='text/css'>
#notebook-container {
    font-size: 15x;
    -webkit-transform-origin-x: 0;
    -webkit-transform: scale(0.90);
}
</style>
```

I can reproduce it using that, but zooming the browser in or out works correctly. So to my mind this is low priority - if you apply custom CSS to the notebook interface, you have the power to break stuff.

**Comment by shanhaiying** [comment]
In the post [Incorrect cursor positioning after changing CodeMirror-lines font-size #150](https://github.com/codemirror/CodeMirror/issues/150),  the bug of  Codemirror was mentioned.

@takluyver ,  Are you run the following code in code cell of jupyter notebook?
```
%%html
<style type='text/css'>
#notebook-container {
    font-size: 15x;
    -webkit-transform-origin-x: 0;
    -webkit-transform: scale(0.90);
}
</style>
```
After the code executed, the font size of the text in div #notebook-container will be changed.
Then the bug occurs. 
I have tried it in the jupyernotebook in sagemath/anacanda in different browsers.

**Comment by takluyver** [comment]
Yep, when I run that I see the bug.

**Comment by gnestor** [comment]
> The best way to change the font is to set a font-family/font-size in the .CodeMirror class, that will ensure the whole editor is using the same font. I've updated the manual to be clearer about this.

from https://github.com/codemirror/CodeMirror/issues/150

If you would like to increase/decrease the font size in the cells, then run the following code instead:

```py
%%html
<style type='text/css'>
.CodeMirror{
    font-size: 17px;
</style>
```

![screencap](http://g.recordit.co/zxynkbN4o6.gif)

If you would like to increase the font size for all element in the notebook, I suggest using the browser's zoom function (`CMD+=` or `CTRL+=` on Windows in Chrome).

**Comment by shanhaiying** [comment]
@gnestor  Thank you very much!  I find that it the following code  causes the problem:
`-webkit-transform: scale(0.90);`

Without it, the code:

```
<style type="text/css">
#notebook-container{width: 210mm;!important;
 font-size:120%;
}  
```
works as expected.

**Comment by gnestor** [comment]
You're welcome. Closing this now 👍
