### ISSUE TITLE
Escape does not close keyboard shortcut editor

### ISSUE THREAD

**Issue by mpacer** [jupyter/notebook#2187]
I see in the editor that it identifies <kbd>Esc</kbd> as mapping to "close pager". I'm not sure what does and doesn't count as a pager, but I would have thought that it would close the modal dialog.

@carreau @gnestor happy to fix, just point me in the right direction.

**Comment by Carreau** [comment]
The pager is the pager: 

![close-p](https://cloud.githubusercontent.com/assets/335567/22946793/5a74745c-f2ad-11e6-8cf9-dccaf9d0b607.gif)

Escape does close the dialog, if the dialog is focused, I'm going to guess your vim-bindigs interfere. 
![close-d](https://cloud.githubusercontent.com/assets/335567/22946866/b09bcbd2-f2ad-11e6-838a-65bca5ae61bb.gif)

**Comment by michaelpacer** [comment]
I don't have any vim bindings for the notebook. But strangely it's now working, so I'll close this.

**Comment by michaelpacer** [comment]
I figured out what happened. If you click into an editing box, and then click out of the box (thereby eliminating focus) it will not close the dialog.

**Comment by takluyver** [comment]
Bumping to 5.1 as it's not urgent, but I suspect it's a fairly easy fix for someone familiar with the JS.

**Comment by takluyver** [comment]
This seems to be general to various dialogs - once you have clicked in the body of the dialog, Esc does not work to dismiss it.

**Comment by takluyver** [comment]
Not as obvious as I thought. Bumping to backlog.

**Comment by jtpio** [comment]
Closing as the classic notebook UI has now been moved to https://github.com/jupyter/nbclassic.

Feel free to open a new issue there if it is still relevant, thanks!
