### ISSUE TITLE
"Enter command mode" has no function in keyboard shortcut editor 

### ISSUE THREAD

**Issue by mpacer** [jupyter/notebook#2190]
The keyboard shortcut editor seems to only apply to keys that are pressed while in command mode. So the "enter command mode" shortcut is not really meaningful. It also doesn't pick up either of the two explicitly bound ways to enter command mode <kbd>Esc</kbd> and <kbd>⌃M</kbd>.

This isn't needed for the beta, but it should be addressed at some point.

**Comment by minrk** [comment]
Good catch, thanks @michaelpacer

**Comment by jtpio** [comment]
Closing as this is unlikely to be documented here in this repo anymore, as Notebook 7+ is now built on top of JupyterLab.

For those still interested, a good place to follow-up might be https://github.com/jupyter/nbclassic.

Thanks!
