### ISSUE TITLE
Specification for shortcut combining keys is not order invariant

### ISSUE THREAD

**Issue by mpacer** [jupyter/notebook#2191]
"Ctrl-E" works and creates keyboard shortcut: <kbd>⌃</kbd><kbd>E</kbd>
"E-Ctrl" does not work, creates keyboard shortcut: <kbd>E</kbd><kbd>⌃</kbd>

For more than 2 combinations of characters (e.g., <kbd>⌃</kbd><kbd>⇧</kbd><kbd>E</kbd>) this is both a UI and a functionality issue:

"Ctrl-Shift-E" works and creates: <kbd>⌃</kbd><kbd>⇧</kbd><kbd>E</kbd>
"Shift-Ctrl-E" works and creates: <kbd>⌃</kbd><kbd>⇧</kbd><kbd>E</kbd>
"Ctrl-E-Shift" does not work, creates: <kbd>⌃</kbd><kbd>E</kbd><kbd>⇧</kbd>
"Shift-E-Ctrl" does not work, creates: <kbd>E</kbd><kbd>⇧</kbd><kbd>⌃</kbd>
"E-Ctrl-Shift" does not work, creates: <kbd>⌃</kbd><kbd>E</kbd><kbd>⇧</kbd>
"E-Shift-Ctrl" does not work, creates: <kbd>E</kbd><kbd>⇧</kbd><kbd>⌃</kbd>

I did not test for greater order numbers, this is not beta blocking.

**Comment by takluyver** [comment]
I always see shortcuts specified with modifier keys first, so I think that as long as those work, this is lower priority.

**Comment by michaelpacer** [comment]
Agreed about being lower priority, but it should be in place for 5.0.1 if not 5.0.0.

**Comment by Carreau** [comment]
Bumping as 5.1 we can for now document that modifiers should be first. But indeed it's probably not taking care of. 

Have you tried modifiers many time ? Like Shift-Shift-E ?

**Comment by michaelpacer** [comment]
Ok including in documentation per #2153. Oooh good call. Didn't test that!

**Comment by takluyver** [comment]
I'm bumping this to backlog - feel free to move it back if you (anyone) intend to work on it soon.

**Comment by jtpio** [comment]
Closing as the classic notebook UI has now been moved to https://github.com/jupyter/nbclassic.

Feel free to open a new issue there if it is still relevant, thanks!
