### ISSUE TITLE
Deleting some custom keyboard commands in the editor doesn't result in persistent deletion

### ISSUE THREAD

**Issue by mpacer** [jupyter/notebook#2192]
I've been testing keyboard command editor behaviour which involved generating lots of commands that we invalid (but were accepted by the UI). I discovered that after starting new notebook server, all the accepted invalid key bindings were resurrected even though they had been deleted during my original notebook session.

My guess is that something is assuming only valid key bindings are able to be deleted using the current machinery, we may want to ensure that we use the same machinery for validating both additions and deletions of key bindings from the persistent state. That way even we don't catch all the invalid and valid cases, at least it will be able to clean itself up appropriately.

**Comment by takluyver** [comment]
Marked as 5.0 so we can have a look into it, but if it's not easy to fix I'm happy for it to be bumped.

**Comment by takluyver** [comment]
@Carreau do you think this is likely to be an easy fix?

**Comment by Carreau** [comment]
Probably hard enough that's not worth it for 5.0. Likely more complicated and less critical than other things already put as 5.1.

**Comment by gnestor** [comment]
@mpacer Can you share an example of an invalid keyboard shortcut that I can use to reproduce?

I would like to release notebook 5.1 this week and I'm not sure how to resolve this one, so I'm going to bump to 5.2.

**Comment by jtpio** [comment]
Closing as the classic notebook UI has now been moved to https://github.com/jupyter/nbclassic.

Feel free to open a new issue there if it is still relevant, thanks!
