### ISSUE TITLE
Segfault opening a notebook (I'm sure this is my issue, not a jupyter issue, but am stumped)

### ISSUE THREAD

**Issue by gtuckerkellogg** [jupyter/notebook#2193]
I recently fired up jupyter noteook on my office machine (Ubuntu 16.04), and what worked before is now giving a segfault the moment I try to open or create a notebook, thus:

    gtk@gtk-office
    [~] jupyter notebook
    [I 10:50:50.583 NotebookApp] Serving notebooks from local directory: /home/gtk
    [I 10:50:50.583 NotebookApp] 0 active kernels 
    [I 10:50:50.583 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
    [I 10:50:50.583 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    Created new window in existing browser session.
    [I 10:51:02.077 NotebookApp] Creating new notebook in 
    [W 10:51:03.771 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170215105050 (127.0.0.1) 9.49ms referer=http://localhost:8888/notebooks/Untitled9.ipynb?kernel_name=python3
    Segmentation fault
    
    gtk@gtk-office
    [~] jupyter --version
    4.2.0
    
    gtk@gtk-office
    [~] jupyter notebook --version
    4.2.3
    

I expect this is from something I did, not a problem in jupyter itself, but I've tried re-installing and uninstalling everything I can think of, and nothing seems to work.  Has anyone come across this before, or could offer some suggestions? The segfault only happens when opening or creating a notebook, not when starting up jupyter.

**Comment by takluyver** [comment]
I don't remember any issue like that. But when it starts a kernel, it will have to set up pyzmq sockets to communicate with the kernel; pyzmq is a compiled library, so it might be causing a segfault. Try uninstalling and reinstalling that and libzmq (the library it depends on).
