### ISSUE TITLE
Error when rebuilding javascript and css 

### ISSUE THREAD

**Issue by samarsultan** [jupyter/notebook#2196]
Hello ,

I get this errors when I'm trying to rebuild the js and less code with this command :
 **npm run build:watch** .

![rebuild js css](https://cloud.githubusercontent.com/assets/20149645/22975729/583dfd0a-f390-11e6-87de-5f6b0af59cf6.png)

But running : **npm run build** doesn't give errors and also doesn't reflect any modification.

![productuion build](https://cloud.githubusercontent.com/assets/20149645/22975903/158efe72-f391-11e6-9fdc-8dfa751a49bf.png)

**Note:** It was working few days before when rebuilding with this command : python setup.py js css , but now it is the same as running npm run build.

I have installed the latest version of node.js and npm .

Any help or advice  !

**Comment by takluyver** [comment]
The error in the first screenshot appears to be that `build:watch` assumes a Unix-y system.

What have you modified that it should pick up when you run `npm run build` (or `python setup.py js css`)?

**Comment by samarsultan** [comment]
I am using Windows 7, node v6.9.5 and npm v4.2.0 .

I created a folder under notebook/ static to wrap my work .
The files that I was trying to modify : 

     - .less files that are located in  : [notebook/static/ ] :  (ex. base/less/ page.less ,  notebook/less/menubar.less , etc..) 

     - .js files that are located in the same place : [notebook/static/ ]  : (ex. base/js/page.js)  .

**Comment by samarsultan** [comment]
@takluyver , any update ?

**Comment by takluyver** [comment]
It should rebuild them if the modified time of the built files is older than the modified time of any of the sources. I don't know why that would have gone wrong, but you can force it to rebuild the JS with `python setup.py js --force`.

**Comment by samarsultan** [comment]
Solved by reinstalling Anaconda .
