### ISSUE TITLE
Update PyPI dependency for traitlets > 4.0

### ISSUE THREAD

**Issue by acdha** [jupyter/notebook#2197]
I just had a user on a Chromebook using Ubuntu Precise trying to start a Jupyter notebook. Since this system is ARM-based the package selection was more limited and we ended up needing to use miniconda's Python 3.4 and installed Jupyter manually using pip. This failed out of the box with an error that `defaults` could not be imported from traitlets.

This was fixed simply by doing a `pip install --upgrade traitlets` so it looks like the fix could be as simple as having the PyPI release require traitlets>=4.3.

**Comment by Carreau** [comment]
It seem like something is wrong on your system. 

The Notebook 4.x branch does not use traitlets' `default` and master/5.x already requires traitlets `>4.2.1`. So it is likely another package that raised. 

For me a fresh install in 3.4 with pip pull traitlets 4.3 and AFAICT all packages using traitlets express the correct dependencies.

Can you provide the error message ?

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
