### ISSUE TITLE
R Kernel Dies with loading packages via library()

### ISSUE THREAD

**Issue by DevinRouth** [jupyter/notebook#2200]
Hi there,

Unfortunately, my R kernel continues to crash every time I attempt to load certain packages via the library() function. In this case, I'm attempting to load "dplyr". See here:

<img width="1214" alt="screen shot 2017-02-16 at 10 35 50 pm" src="https://cloud.githubusercontent.com/assets/20073005/23051644/98467e14-f498-11e6-9f1b-32ddaca05353.png">

Are there perhaps dependencies that are not being loaded and thus causing trouble? I'm new to using R within a Jupyter Notebook. What should I do?

Thanks!
Devin

**Comment by takluyver** [comment]
Pinging @flying-sheep - any ideas why R could be crashing like that?

**Comment by flying-sheep** [comment]
what’s the console output of jupyter?

**Comment by DevinRouth** [comment]
My apologies for the delay in responding—after reinstalling Jupyter and the R kernel, I no longer received the error.

Thanks!

**Comment by takluyver** [comment]
OK, closing with status MYSTERY ;-)
