### ISSUE TITLE
Design of the cell tags UI

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#2205]
Doing UI/UX review for 5.0 #2142...

Yeah, so nice to see the cell tags UI! This is something we have wanted/needed for a long time and it is so nice to see working and about to be released. Awesome!

Some design feedback on it:

The UI of tags that already exist makes it a bit difficult to see which "X" goes with which tag:

![screen shot 2017-02-19 at 11 38 25 am](https://cloud.githubusercontent.com/assets/27600/23105222/8821361c-f698-11e6-8b6f-73e41ecdc593.png)

I would put some sort of enclosing div with a shading/border to group each tag name and the close "X" together.

Also, the "X" on hover gets an underscore as though they are hyperlinks. Let's remove that:

![screen shot 2017-02-19 at 11 40 31 am](https://cloud.githubusercontent.com/assets/27600/23105226/ad11b5dc-f698-11e6-9e24-6ec9498807dc.png)

Lastly, it looks like this is just a capital "X" character. Can we use a font awesome close icon?

Feedback on the R hand side UI:

![screen shot 2017-02-19 at 11 39 49 am](https://cloud.githubusercontent.com/assets/27600/23105232/e30888fa-f698-11e6-8400-bb810f1b282a.png)

1. We try to not use the default browser blue glow for text areas that are focused.
2. The horizontal spacing between the three components isn't consistent. The "..." and textarea have a wider spacing that the textarea and button. I would use the larger spacing of the two.
3. The vertical spacing between the UI elements and the enclosing cell toolbar isn't symmetric. For most cell toolbar UI, we use smaller UI controls, to leave more room above/below and make it symmteric. Here is an example from another cell toolbar:

![screen shot 2017-02-19 at 11 40 56 am](https://cloud.githubusercontent.com/assets/27600/23105247/403aaa30-f699-11e6-9d83-255684ec698a.png)

**Comment by takluyver** [comment]
@vidartf do you have time to look into these things?

**Comment by vidartf** [comment]
Sure, but I need feedback on the focus highlighting bit, see #2210 ( @ellisonbg ).

**Comment by takluyver** [comment]
Closing as resolved by #2210
