### ISSUE TITLE
Deleting multiple files in file browser errors

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#2206]
Trying to delete multiple files in the file browser (checkbox on all of them, click the red trash button) causes the following error dialog to pop up for each deleted file:

![screen shot 2017-02-19 at 11 53 01 am](https://cloud.githubusercontent.com/assets/27600/23105282/1b5eef68-f69a-11e6-86d6-51935851dc0b.png)

The delete works though.

**Comment by ellisonbg** [comment]
Single file delete works without any problems.

**Comment by takluyver** [comment]
The error is coming from the selector we use on [this line](https://github.com/jupyter/notebook/blob/c305d8fda3b5f8bfb8c1ce520c0a6927f56261a1/notebook/static/tree/js/notebooklist.js#L1027). The [`:data` selector](https://api.jqueryui.com/data-selector/) is part of jquery-ui, which we're seemingly not using in the file browser view any more. Raw jQuery doesn't like it.

We're using jQuery's `.data()` storage, not `data-` attributes on the HTML element, so we can't select with e.g. `[data-path]`. I don't know whether it's better to load jQuery UI so the `:data` selector works, or change to doing the selection another way.

**Comment by minrk** [comment]
Should be fixed by #2206 - we can iterate over the list items directly, we don't need to ask for all items on the page with path data.
