### ISSUE TITLE
Undo after merge operation results in loss of cell

### ISSUE THREAD

**Issue by adelq** [jupyter/notebook#2207]
After merging cells with `shift-m`, the expected behavior for undo (`C-z`) is to split the cells back apart again.

However, the actual displayed behavior is that the newly merged cell's code is removed, with no new cells created. Thus, the code that was merged in is lost.

So, 2 cells are merged into 1 with the code of both, undo results in a single cell that has the code of just 1 cell.

**Comment by takluyver** [comment]
We don't have a great undo mechanism at the moment. Each cell has its own undo history, and this is what's deleting the code that came from the second cell. We also have a simple undo mechanism to restore deleted cells. I think this should be available in the edit menu after you merge cells.

**Comment by Carreau** [comment]
We can clear CM history on merge, it will prevent undo beyond merge point.

**Comment by takluyver** [comment]
@Carreau you milestoned it for 5.0 - would you like to work on it?

**Comment by Carreau** [comment]
Bumping to 5.1, even if Ctrl-Z undo Ctrl-Shift-Z should redo so that's not critical. 
It should be a 1 line fix in the right place (likely the Merge command). But it will take me an afternoon to re-dive in this code.

**Comment by gnestor** [comment]
@Carreau What 1 line are you thinking of? Here is the `merge_cells` function: https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/notebook.js#L1740-L1787

**Comment by Carreau** [comment]
Yes, if you call, [`doc.clearHistory()`](https://codemirror.net/doc/manual.html#clearHistory), it should prevent to Ctrl-Z to before the merge to an empty state.
