### ISSUE TITLE
Highlight wrong when using literal string interpolation.

### ISSUE THREAD

**Issue by szsdk** [jupyter/notebook#2218]
![_014](https://cloud.githubusercontent.com/assets/6657200/23261786/e29db886-fa12-11e6-9e73-0bf94d177d6c.png)

**Comment by takluyver** [comment]
This should be fixed (by using a newer version of Codemirror) when we release 5.0 soon. You can help us test 5.0 now by installing it with `pip install --pre --upgrade notebook`.

**Comment by szsdk** [comment]
@takluyver Thanks. I'd love to test the new version.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
