### ISSUE TITLE
'find and replace' gets stuck 

### ISSUE THREAD

**Issue by ggrrll** [jupyter/notebook#2222]
Hi, 

I have a problem with 'find and replace' feature: it takes too long (after all, it's a simple editor task) and my laptop heats up .
It never worked very fast, but in the last few days it takes really too much (~1 min)

Thanks for your support.

ps: I am on:
- mac os 10.12.3
- notebook Version: 4.4.1

**Comment by takluyver** [comment]
That's weird. Is the notebook you're using it on particularly long? Do you have an example that we can test to try to reproduce it? Have you got time to try with master?

**Comment by takluyver** [comment]
Actually, easier than trying with master, you can test 5.0 beta1 using:

```
pip install --upgrade --pre notebook
```

**Comment by ggrrll** [comment]
yeah, it's quite long - at least longer than the usual ones I worked on ...so maybe that's the reason 
But still, I find weird that it takes so much for just find and replace...

(I will work with the beta version and see how it goes)

**Comment by takluyver** [comment]
Thanks. It is a bug if it's noticeably slow on any notebook that's a practical size to work with, but it's quite possible that it has some abysmal performance characteristics that we didn't test.

**Comment by ggrrll** [comment]
f&r  seems to work fine in the new version 

(on the other hand, can we already give feedbacks on the _beta version_ with _new issues_?)

**Comment by takluyver** [comment]
> f&r seems to work fine in the beta version

Great, thanks. :-)

> (on the other hand, can we already give feedbacks on the beta version with new issues?)

Absolutely, yes.

**Comment by ggrrll** [comment]
Hi, 

it just took ~ 1 min to replace a string in 13 instances - too long... - and  fan speed of my laptop (mac) increased too (clearly cpu overload, I would say...)

(the notebook is quite heavy - for an average notebook: ~ 6.9 MB)

**Comment by takluyver** [comment]
With the 5.0 beta? Is the notebook something you're willing to share so we can experiment with it? Or can you reproduce it with another notebook you're prepared to share?

**Comment by ggrrll** [comment]
(yes, on the beta v)

ok..no rush for now - I can work on the next weeks and see how/if I can reproduce the issue on other notebooks and browsers

**Comment by takluyver** [comment]
Added to 5.0 milestone so we at least have a look at it - it can be bumped if it's not easy to fix.

**Comment by gnestor** [comment]
I'm not able to reproduce, so I'm bumping to 5.1. 

@ggrrll Can you provide an example notebook (as a Gist) that we can use to reproduce?

**Comment by ggrrll** [comment]
sorry, I don't have something I can share yet...
- if you don't encounter it in heavy notebooks (as I said, ~ 6.9 MB), I wouldn't mind if you prefer to close the issue - I will post eventually something, if/when I will have a reproducible example

**Comment by gnestor** [comment]
I unfortunately don't have any example notebook that large. Let's close this for now and please do reopen if you can provide a reproducible example.
