### ISSUE TITLE
issue with "arch" in jupyter

### ISSUE THREAD

**Issue by amrivas** [jupyter/notebook#2227]
Hi - I'm having issues importing arch for use in my python code. Here's what I've done:
I installed "arch" via anaconda using the following in cmd prmt:

conda install -c https://conda.binstar.org/bashtage arch

I'm using python 2.7 and when I run this in Jupyter:
from arch import arch_model

I get this error: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-3d8a1af3ecc2> in <module>()
----> 1 from arch import arch_model

ImportError: No module named 'arch'

**Comment by viveksinghnalwa** [comment]
can you tell me what resolved this error?
