### ISSUE TITLE
issues running: from contextlib import redirect_stdout

### ISSUE THREAD

**Issue by amrivas** [jupyter/notebook#2228]
i'm trying to import the following in Jupyter (using python 2.7):

from contextlib import redirect_stdout

and getting this error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-e20a294be54c> in <module>()
----> 1 from contextlib import redirect_stdout

ImportError: cannot import name redirect_stdout

**Comment by Carreau** [comment]
See [Python 3 documentation](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout), `redirect_stdout` is only in python 3.4 and above. (Tip these info are always at the end of the section).

CLosing as there is not much we can do.

Thanks.
