### ISSUE TITLE
Provide a file download button

### ISSUE THREAD

**Issue by dov** [jupyter/notebook#2236]
Currently there is  `IPython.display.Image` that embeds an image in the html output. I suggest that a similar widget be provided called `IPython.display.downloadbutton(filename)` (or something similar) that shows a button for downloading a file. 

A use case of this functionality is if pandas created a data frame that should be provided to the user for downloading. The user could then do:

    df.to_csv(filename)
    IPython.display.downloadbutton(filename)

This may of course be wrapped in some syntactic sugar for shorter access.

**Comment by takluyver** [comment]
Have you seen `IPython.display.FileLink`?

**Comment by dov** [comment]
Thanks! I missed that. It really provides the functionality that I was looking for.

Of course, it would imo be a nice syntactic sugar to provide a button for downloading the file instead of the right clicking on the file link, but that is a minor issue.

**Comment by mpacer** [comment]
You could probably write a display class that changes the file link into a
button for downloading. My guess is you'd need to use the _repr_html_ or
_repr_javascript_ methods to get enough richness to display a button with
those properties. FileLink
<https://github.com/ipython/ipython/blob/master/IPython/lib/display.py#L299>
uses
_repr_html_.
