### ISSUE TITLE
Hitting "Command" Key on Terminal Scrolls to Bottom

### ISSUE THREAD

**Issue by cancan101** [jupyter/notebook#2238]
Using a terminal and scrolling up, hitting the command key causes the terminal to scroll back to the bottom. This is problematic when trying to use command+c to copy to clipboard.

**Comment by michael-wise** [comment]
Disclaimer: I'm not very familiar with jupyter but I was poking around tonight. Would it be a safe and working solution to add to `var keyNames {224 : 'OSkey'}` and to change [isModifierKey](https://github.com/jupyter/notebook/blob/393a04d1b0c583a613fe11f0ca38adf2c5e2ee66/tools/patches/codemirror.js#L6421) from
```javascript
function isModifierKey(value) {
  var name = typeof value == "string" ? value : keyNames[value.keyCode]
  return name == "Ctrl" || name == "Alt" || name == "Shift" || name == "Mod"
}
```
to
```javascript
function isModifierKey(value) {
  var name = typeof value == "string" ? value : keyNames[value.keyCode]
  return name == "Ctrl" || name == "Alt" || name == "Shift" || name == "Mod" || name =="OSkey"
}
```
?

**Comment by takluyver** [comment]
I don't think that would affect it; that code is in CodeMirror, the editor component we use for cells in the notebook. Keyboard events in the terminal are handled separately - see [xterm.js](https://xtermjs.org/).

**Comment by michael-wise** [comment]
Ah pretty cool thanks! I'll try n poke around within the next week for a hint.

**Comment by cancan101** [comment]
I think this is now fixed.
