### ISSUE TITLE
Is is possible to simplify notebook architecture to reduce main.min.js? 1.6M would be too big.

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#2241]
If we want it be widely used all over the world(any kind of network), this is important.

**Comment by minrk** [comment]
MathJax and CodeMirror would probably be the things you would have to thin out most for a light version.

**Comment by cailiang9** [comment]
mathjax.js is in another file. If simply gzip, it's about 400KB. Plus: it is weird that I found some files are gzipped. some are not gzipped.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
