### ISSUE TITLE
Command not found: jupyter

### ISSUE THREAD

**Issue by 3rd3** [jupyter/notebook#2247]
I've installed Jupyter via `pip3` and Python 3.6 via Homebrew on OS X. For some reason the `jupyter` command is not linked. It did install `jupyter-notebook`, `jupyter-run` and so, but there does not seem to be a way to call `jupyter console` because `jupyter-console` does not exist.

```
$ jupyter-run --version
5.0.0
$ jupyter-notebook --version
4.4.1
$ cat `which jupyter-notebook`
#!/usr/local/opt/python3/bin/python3.6

# -*- coding: utf-8 -*-
import re
import sys

from notebook.notebookapp import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

What is going on?

**Comment by takluyver** [comment]
I'm not quite sure, but the `jupyter` command is part of the `jupyter_core` package, and `jupyter-console` comes from `jupyter_console`. You may want to try uninstalling and reinstalling those packages.

**Comment by 3rd3** [comment]
That solved it, thanks!

**Comment by arilwan** [comment]
@takluyver thanks, it helps.
