### ISSUE TITLE
Browser flag ignored if default browser and specified browser both open

### ISSUE THREAD

**Issue by roomthily** [jupyter/notebook#2253]
I have Chrome set as my default browser (mac 10.x) but generally use Firefox for working in Jupyter notebook (jupyter 4.1).

If both browsers are open when I fire up notebook with the browser flag set to firefox, it opens the Home tab in Chrome regardless. Bit of unexpected behavior.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
