### ISSUE TITLE
How to change jupyter start command in pycharm?

### ISSUE THREAD

**Issue by nolan57** [jupyter/notebook#2255]
I want to use jupyter notebook in pycharm,but when start jupyter,i got a error:.../jupyter --no-browser--,....
 obviously，i need to change ".../jupyter --no-browser-- ..." to".../jupyter  **notebook** --no-browser-- ..." ,but i don't know how in pycharm...

**Comment by gnestor** [comment]
I'm not a PyCharm user, so I can't answer this myself, but it appears that PyCharm has built-in Jupyter Notebook support: https://www.jetbrains.com/help/pycharm/ipython-jupyter-notebook-support.html

If that doesn't answer your question, I would direct your question to StackOverflow or the Jupyter Gitter 👍
