### ISSUE TITLE
Copying Multi Line from Terminal Inserts Line Breaks

### ISSUE THREAD

**Issue by cancan101** [jupyter/notebook#2256]
When I copy text from a jupyter notebook terminal session that spans multiple lines, line breaks are inserted.

**Comment by takluyver** [comment]
Can you describe a bit more the results and what you expected? Thanks.

**Comment by cancan101** [comment]
I run:
```
# python -c 'print("M"*455)'
```
And I get (notice the line breaks when I copy out of the terminal):
```
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
```

**Comment by takluyver** [comment]
I think that's not unusual for terminal emulators, although modern ones (including Gnome terminal, which I use) preserve it without the linebreaks. If you want to chase it up, the terminal component we use is [xterm.js](https://github.com/sourcelair/xterm.js), so that's where it would need to be changed. See maybe sourcelair/xterm.js#404.

**Comment by cancan101** [comment]
I think this is the upstream issue: https://github.com/sourcelair/xterm.js/issues/443.

**Comment by cancan101** [comment]
This has now been fixed in: https://github.com/sourcelair/xterm.js/pull/693

**Comment by takluyver** [comment]
Thanks @cancan101 . We should remember to update our version of xterm when there's a release with that fix.

**Comment by cancan101** [comment]
Okay, 2.8.0 has been released with the fix: https://github.com/sourcelair/xterm.js/releases/tag/2.8.0
