### ISSUE TITLE
UX Bug: command palette uses confusing labeling

### ISSUE THREAD

**Issue by colllin** [jupyter/notebook#2259]
![screen shot 2017-03-07 at 12 33 45 pm](https://cloud.githubusercontent.com/assets/185923/23674213/5a440796-0332-11e7-82fa-dbfe77f4de20.png)

I saw the label _(command)_, which is also the name of a key on a Mac keyboard, so I attempted to run a cell using `command+shift+enter`, which didn't do anything.  The correct command was just `shift+enter`.

A few possible solutions:

- remove the _(command)_ label.  What is it? Who cares about it?
- Move it away from the shortcuts. Maybe to the left side of the row?
- rename the _(command)_ label to _(commands)_
- use more words to clarify, e.g. _type:command_ or _(runs a command)_ or _(cell command)_
- use a synonym for _command_, e.g. _directive_ or _instruction_

**Comment by takluyver** [comment]
*command* means that the shortcut is active in *command mode*, as opposed to *edit mode*. I agree that's not clear, though.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days and recent versions of Notebook now display _(command mode)_. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
