### ISSUE TITLE
TypeError: IPython.load_extensions is not a function

### ISSUE THREAD

**Issue by ofenerci** [jupyter/notebook#226]
Dear All,

I am some problems about extensions. I have installed Jupyter as described in "https://github.com/jupyter/notebook" but when I try to install some extensions installed inside "~/.jupyter/nbextensions", I get an error 
--------------------------------------------->--------------------------------------------------------
ln [1]: %%javascript
IPython.load_extensions('IPython-notebook-extensions-master/usability/python-markdown/main');

Javascript error adding output!
TypeError: IPython.load_extensions is not a function
See your browser Javascript console for more details.

------------------------------------------<------------------------------------------------------------------------
I don' know what could be a problem and am lost in the ocean of Jupyter. 

Ozhan

**Comment by takluyver** [comment]
We're still getting Jupyter released - if you're feeling lost with the development version, please install the stable version of IPython, which includes the notebook, using:

    pip install ipython[notebook]

It looks like we no longer put `load_extensions()` in the interactive namespace, so now you'll need to do something like:

```javascript
require(['base/js/utils'],
function(utils) {
    utils.load_extensions('...');
});
```
