### ISSUE TITLE
Copy/paste cells between notebooks not working on safari

### ISSUE THREAD

**Issue by ggrrll** [jupyter/notebook#2264]
When trying to copy paste cells in safari between notebooks,  I got this error in the console:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8888/static/components/preact/dist/preact.min.js.map
```

(I am on  notebook `Version: 5.0.0b1`  and Safari 10.0.3)

(issue suggested by #1163 )

**Comment by ggrrll** [comment]
still an issue in `v. 5.4.1`

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
