### ISSUE TITLE
Can't connect to jupyterhub

### ISSUE THREAD

**Issue by DivyaThomas1** [jupyter/notebook#2266]
I've set up jupyterhub on a remote server using the install procedures listed here: https://github.com/jupyterhub/jupyterhub/wiki/Installation-of-Jupyterhub-on-remote-server

Everything works up until step #7.  On the remote server I run jupyterhub I get the following output:

```
[I 2017-03-08 12:26:38.784 JupyterHub app:724] Loading cookie_secret from /home/starsky/jupyterhub_cookie_secret
[W 2017-03-08 12:26:38.817 JupyterHub app:365] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2017-03-08 12:26:38.821 JupyterHub app:864] No admin users, admin interface will be unavailable.
[W 2017-03-08 12:26:38.821 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2017-03-08 12:26:38.821 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
[I 2017-03-08 12:26:38.834 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[W 2017-03-08 12:26:38.837 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2017-03-08 12:26:38.837 JupyterHub app:1176] Starting proxy @ http://*:8000/
12:26:38.988 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
12:26:38.991 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2017-03-08 12:26:39.041 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/
```

However, when I try going to http://localhost:8000/ or http://<my_ip>:8000/ I get an error saying This site can’t be reached
localhost refused to connect.
ERR_CONNECTION_REFUSED

What am I doing wrong?  I'm not running on a proxy and I've added chrome to the list of application exceptions for my firewall.  

Are you sure the ports on the remote server are publicly accessible? Can you access any other servers run on the machine (e.g. `python3 -m http.server`)?

**Comment by JamiesHQ** [comment]
@minrk @willingc : should this be ported over to [JupyterHub](https://github.com/jupyterhub/jupyterhub)?

**Comment by willingc** [comment]
Hi @DivyaThomas1, I'm going to go ahead and close this issue as it's been a while since it was opened. If you are still having an issue, please ask for assistance on the JupyterHub gitter channel or file a new issue on the [JupyterHub repo](https://github.com/jupyterhub/jupyterhub). Thanks!
