### ISSUE TITLE
shell-init error in the release assignment notebook

### ISSUE THREAD

**Issue by praveen049** [jupyter/notebook#2267]
I have created a release assignment following the instructions : Workflow example: Instructor generating an assignment release

When i try to print something in any of the cells,  i get shell-init error.

As a simple example:

![image](https://cloud.githubusercontent.com/assets/24820914/23736204/a4a7abd2-04c5-11e7-8635-a8d55888dccf.png)

What am I doing wrong?

**Comment by takluyver** [comment]
Are you in a working directory that has been deleted?

**Comment by praveen049** [comment]
No, the current directory still exists. 

By the way, i am running the browser remotely on a different computer and not the box  where the jupyter notebook is running.

In this setup, the notebook where the assignment is being created (in the source folder) i am able to execute commands on the system shell with ! prefix.
But cannot execute the same command on the release notebook.

**Comment by takluyver** [comment]
Pinging @jhamrick - question involving nbgrader.

**Comment by jhamrick** [comment]
@praveen049 it's possible this might cause an error if you have done the following:

1. Run `nbgrader assign`
2. Open the release notebook
3. Rerun `nbgrader assign --force`
4. Try to execute cells in the release notebook

It should fix the problem to restart the kernel of the release notebook.

**Comment by praveen049** [comment]
@jhamrick 

Thanks. With --force it's working fine.
