### ISSUE TITLE
Markdown syntax highlighting problem in Unordered list

### ISSUE THREAD

**Issue by Cooper-Yang** [jupyter/notebook#2271]
Jupyter version 4.3.0

Problem describe in pictures down below

![screenshot from 2017-03-10 15 16 16](https://cloud.githubusercontent.com/assets/17451826/23785853/b74da5d6-05a4-11e7-94ee-dfc9b88f6c28.png)

![screenshot from 2017-03-10 15 16 33](https://cloud.githubusercontent.com/assets/17451826/23785859/bedee5f8-05a4-11e7-8fea-6f10c30f74bd.png)

**Comment by takluyver** [comment]
Can you try with the 5.0 beta release? `pip install --upgrade --pre notebook`

**Comment by Cooper-Yang** [comment]
> Can you try with the 5.0 beta release? `pip install --upgrade --pre notebook`

@takluyver Just did. This problem already been fixed in beta, thanks very much.

**Comment by takluyver** [comment]
Thanks :-)
