### ISSUE TITLE
splitting a slide cell results in one non-slide cell and one slide cell

### ISSUE THREAD

**Issue by parmentelat** [jupyter/notebook#2273]
After using 'split cell' in the middle of a cell marked as 'slide', what I end up with is

* a first cell **not** marked as slide
* and a second cell *marked** as slide

I would expect it the other way around; but maybe that's just me ?

I'm using 'jupyter notebook' with jupyter-4.3.0  on macos

**Comment by takluyver** [comment]
Pinging @damianavila who's probably interested.

**Comment by parmentelat** [comment]
I just witnessed that the same behaviour happens with a cell marked as 'split', so it suggests it's the complete metadata that gets attached to the second cell rather than to the first.

Trying to setp back a little, I would see 3 policies here
1. either we decide statically that the metadata should be duplicated; not optimal but at least simple to grasp
1. or we arbitrarily choose one the 2 resulting slides as the recipient for the whole package; my conjecture is that's what is done now, and the recipient is the second
1. or we decide it's more complicated and cannot be done while ignoring the various semantics; arguing that e.g. the slide tag probably is better attached to cell (a), while split cell should copied to (a) and (b)

Of course 3. is clearly a pandorra box; maybe giving a try at option 1. would make sense...

Just thinking aloud here, it's not really a big deal

**Comment by takluyver** [comment]
Your conjecture is correct - splitting works by inserting a new cell above, and moving some of the text to it. [Here's the code](https://github.com/jupyter/notebook/blob/94122d6f8c7881fd8cd87fd82e23a0b6d1e04fd4/notebook/static/notebook/js/notebook.js#L1692-L1706). I agree that copying the metadata is probably a more reasonable approach.

**Comment by parmentelat** [comment]
fine thanks I’ll send a pull request when I have a chance

**Comment by damianavila** [comment]
> I agree that copying the metadata is probably a more reasonable approach.

I agree as well.
