### ISSUE TITLE
kernel will dead when import SimpleITK

### ISSUE THREAD

**Issue by EinsteinInIct** [jupyter/notebook#2275]
When I import SimpleITK like following:

"import SimpleITK as sitk", the kernel will dead and say "Kernel Restarting: The kernel appears to have died. It will restart automatically".

My environment:
OS: macos X EI Capitan
python: 2.7.12 Anaconda custom (x86_64)
notebook server: 4.2.1
IPython: 5.1.0

**Comment by takluyver** [comment]
Look for errors in the terminal where you started the notebook. Usually the kernel dying like this means that some compiled code has caused a segfault or similar fatal error.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
