### ISSUE TITLE
Why I cannot do POST to jupyter tornado http server

### ISSUE THREAD

**Issue by itismewxg** [jupyter/notebook#2276]
I used to make a url extension under localhost:8888/my_extension_baseurl
and registered some request handler their for POST action.

but in jupyter4.3, I just notice I cannot do any POST action if I turned the authentication down

**Comment by takluyver** [comment]
Can you show us your code, and describe in a bit more detail what happens? There were some changes to authentication in 4.3 that might have affected it.

**Comment by itismewxg** [comment]
here is the stuff: in jupyter_notebook_config.py, I put the extension there:
-----
import sys 
sys.path.append("/opt/app/myproject/jupyter/extension")

c.NotebookApp.server_extensions = [ "services" ]
c.NotebookApp.tornado_settings = { 'headers': { 'Content-Security-Policy': "" } } 

import notebook.nbextensions
notebook.nbextensions.install_nbextension('/opt/app/myproject/jupyter/extension/javascripts/sthCool.js', user=True)

from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update('notebook', {"load_extensions": {"sthCool": True}})
-----

And in the /opt/app/myproject/jupyter/extension/service.py 

I have the code as to register a handler to tornado web server, processing some input, record sth in the memory as long as the tornado server is alive

it seems that, I always need a token to visit the tornado server app,

**Comment by takluyver** [comment]
We enabled authentication by default in 4.3, but it should be transparently handled by cookies. You can see here how the notebook frontend code makes a POST request to start a new session:
https://github.com/jupyter/notebook/blob/b93820bf4c1648262a6b82902ba6d24e86d11bed/notebook/static/services/sessions/session.js#L102

And here's the server code that handles that:
https://github.com/jupyter/notebook/blob/b93820bf4c1648262a6b82902ba6d24e86d11bed/notebook/services/sessions/handlers.py#L34

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
