### ISSUE TITLE
colorize test output. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#2282]
Test output can be hard to read, it would be nice to colorize them. 
it should be a matter of `pip install rednose` and add  `--rednose` as an option for nose in `.travis.yml`

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it looks like the more recent versions of Notebook have indeed included colorized test output. However, please feel free to reopen this issue if it still needs to be addressed. Thank you!
