### ISSUE TITLE
print colors in a notebook cell's output

### ISSUE THREAD

**Issue by Fandekasp** [jupyter/notebook#2284]
Googling about it, it appears like the notebook should support ANSI colors, but I cannot get it to work.
I just want to print colored statements from within my functions.

![2017-03-14_15-24-40](https://cloud.githubusercontent.com/assets/260983/23888288/9224dea4-08ca-11e7-8d6d-92d857e43582.png)

Any idea what's wrong? The problem persists after disabling all nbextensions.

**Comment by takluyver** [comment]
![screenshot from 2017-03-14 15-39-36](https://cloud.githubusercontent.com/assets/327925/23908634/77feea18-08cc-11e7-807f-a5246ed8498e.png)

Don't use `colorama.init()`. Colorama is intended to turn the ANSI colour codes into Windows console API calls, but it will detect that you're not in a Windows console and strip the ANSI codes out entirely, so the notebook doesn't see them.

**Comment by Fandekasp** [comment]
Great, thank you @takluyver !

**Comment by krishnachouhan** [comment]
Importing **tqdm** affects the colors if anyone still using that thing.

**Comment by jolespin** [comment]
@krishnachouhan why is that?

**Comment by krishnachouhan** [comment]
Not sure @jolespin.
Here is the opened issue..
https://github.com/tqdm/tqdm/issues/678
