### ISSUE TITLE
jupyter notebook list has empty output if run from remote

### ISSUE THREAD

**Issue by yifeim** [jupyter/notebook#2288]
I have a ubuntu terminal running notebook server and a remote client that connects by ssh port forwarding. The local ubuntu server can see the tokens, but the remote cygwin cannot. Am I missing something?

I started the server by simply `jupyter notebook`

The client was started by `ssh -L8888:localhost:8888 server`

If I open another terminal on the server, I can find the token by `jupyter notebook list`. However, on my client nothing was displayed. Exporting `$DISPLAY` does not help.

Couldn't find an answer elsewhere. Thanks.

**Comment by takluyver** [comment]
`jupyter notebook list` relies on files on the filesystem to discover running servers - run `jupyter --runtime-dir` to see where they're stored on your system. So it can't currently discover a server that you're connected to by an SSH tunnel.

**Comment by yifeim** [comment]
Thank you. I was able to find `notebook_dir` in `sudo cat /run/user/1000/jupyter/nbserver-20160.json`. The ssh file directory is under `$HOME/.local/share/jupyter/runtime`.

On a side note, if I set a password, then my ssh directory will be the same as the `1000` directory. Not sure why the difference.

**Comment by takluyver** [comment]
I'm not exactly sure how the difference arises, but the directory starting with `/run` is specified by an environment variable `XDG_RUNTIME_DIR`. The alternative under your home directory is our fallback if XDG_RUNTIME_DIR is not set.

**Comment by yifeim** [comment]
I am pretty happy with what I have got so far. Bottom line is: if I can't find the connection, I will look in the `/run/user/` directory. Thanks.

**Comment by yifeim** [comment]
Just to also comment, the one with password is in a CentOS system, whereas the one without is in a Ubuntu system, if it has any significance.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
