### ISSUE TITLE
Fontawesome some Icons are not rendered

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyter/notebook#2289]
I am writing some Notebook extensions and am trying to find good icons for their buttons. For that, I use an action like the following:

    var action = {
        icon: 'graduation-cap', // a font-awesome class used on buttons, etc
        help    : 'toggles',
        help_index : 'zz',
        handler : handler
    };

However, the icon is not rendered. Only some icons work, for example `fa-check-square-o`.

Is there a list of the icons, which work and which do not? Or is it about the version of [fontawesome](http://fontawesome.io/icons/), which is included in the notebook?

**Comment by takluyver** [comment]
It's probably just about the version we include. I don't think we cut any icons out.

**Comment by louise-davies** [comment]
@ZelphirKaltstahl isn't it because you are referencing `graduation-cap` rather than `fa-graduation-cap`? When I use `fa-graduation-cap` it appears just fine for me

**Comment by ZelphirKaltstahl** [comment]
@louise-davies Ha! You hit the nail on the head! That was the problem. Does the `fa` stand for font awesome? Probably. I guess there would have been collisions with other stuff if simply using the original names?

**Comment by abeboparebop** [comment]
I seem to be having the same issue. In my case `fa-clock-o` works but `fa-stop-circle-o` does not (Jupyter core version 4.2.0). It would be great to get a list of usable icons programmatically.

**Comment by takluyver** [comment]
(N.B. The `jupyter_core` version is not relevant to this - it's the `notebook` package that bundles FA)

**Comment by abeboparebop** [comment]
Thanks @takluyver. My `notebook` version is 4.2.3.

**Comment by takluyver** [comment]
There may be more icons in 5.0.

**Comment by 0x0L** [comment]
fontawesome is [pinned to version 4.2](https://github.com/jupyter/notebook/blob/master/bower.json#L10) while current version is 4.7.
I can't think of any reason not to upgrade

**Comment by vidartf** [comment]
I think this one got fixed?

**Comment by jasongrout** [comment]
Yes, I think so.
