### ISSUE TITLE
Saving failed for jupyter notebook

### ISSUE THREAD

**Issue by SiqiLiu-647** [jupyter/notebook#2291]
Hi, I managed to save the jupiter notebook with the save and checkpoint button on the web server and the autosave extension enabled. However, it is not responding, and from the command line in terminal, there is also no documentation on the saving command. I deleted the .ipython_checkpoint sub-folder. I was wondering if anyone know the reason why the notebook cannot be saved properly? Thanks!

**Comment by ThusithaDeepal** [comment]
I had the same issue,i tried these methods unfortunately it doesn't work.
At last i found a method 

1. Copy your filename.ipynb file manully to same directory
 
2. Rename it with filename at about 5 characters. Then open it in jupyter notebook , and it can be saved successfully .

 
3. After that you can rename it to any name you want !

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
