### ISSUE TITLE
html image tag relative path level up not importing in markdown cell

### ISSUE THREAD

**Issue by kehey** [jupyter/notebook#230]
Hi,

I found that using the following tag in a markdown cell failed:

```html
<img src="../img/test.png" width=400px>
```

while using the same tag (changing the path then of course) when the image is either in the same folder as the notebook or a subfolder, succeeds. So apparently, this import can not deal with going a level up.

Interestingly, if you convert the notebook to an HTLM page using nbconvert, the HTML page shows the image perfectly, since the browser has no problem using a relative path that first goes up (and the html code is this correct). So this seems to be a notebook problem.

I agree this is not a deal-breaker, but it might be something easy to change, and I use this folder structure to keep notebooks and results separated.

Any thoughts on whether this could be looked into?

**Comment by minrk** [comment]
what's the URL for the notebook? Is it at the top-level of the notebook directory? If so, the notebook server will not serve any files outside that directory.

**Comment by kehey** [comment]
Okay, got it. Just need to launch my notebook in the level above the notebook and images folder. it works now. Thanks!
