### ISSUE TITLE
Feature Request: Enhanced Markdown Support For Graphs

### ISSUE THREAD

**Issue by schlichtanders** [jupyter/notebook#2300]
Dear Jupyter-Notebook-Team,

I just got to know [an awesome atom markdown extension](https://github.com/shd101wyy/markdown-preview-enhanced) which includes many useful graphing tools not available yet in jupyter-notebook markdown (at least to my knowledge):

[copied from <https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/README.md>]
- [mermaid](https://github.com/knsv/mermaid) to render flowchart and sequence diagram.  
	- code block with `mermaid` (or `@mermaid`) notation will be rendered by [mermaid](https://github.com/knsv/mermaid)  
	- check [mermaid doc](http://knsv.github.io/mermaid/#flowcharts-basic-syntax) for more information about how to create flowchart and sequence diagram   
	- ![mermaid](https://cloud.githubusercontent.com/assets/1908863/23383956/5c8cb37e-fd0e-11e6-8a22-f3946841bbbd.gif)
- [PlantUML](http://plantuml.com/) to create multiple kinds of graph. (**Java** is required)  
	- code block with `puml` or `plantuml` or (`@puml` or `@plantuml`) notation will be rendered by [PlantUML](http://plantuml.com/).  
- [Viz.js](https://github.com/mdaines/viz.js) to render [dot language](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) graph.  
	- code block with `viz` (or `@viz`) notation will be rendered by [Viz.js](https://github.com/mdaines/viz.js).
    - add `engine:[engine_name]` at the first line of code block to choose different render engine. For example `engine:dot`. Engine `circo`, `dot`, `neato`, `osage`, or `twopi` are supported. Default engine is `dot`.   
- [WaveDrom](http://wavedrom.com/) to create digital timing diagram.  
	- code block with `wavedrom` (or `@wavedrom`) notation will be rendered by [wavedrom](https://github.com/drom/wavedrom).

I adapted the order to match my personal prioritized wish list.

Questions:
- Any plans to include such features?
- Maybe it is possible to create some nbextensions dealing with these features separately? Hints / suggestions how to do this?

**Comment by schlichtanders** [comment]
so this is not possible at the moment by implementing a respective nbextension?

**Comment by lautjy** [comment]
Been definitely looking for something like this for a while now.

**Comment by shafiemukhre** [comment]
Yeah, this is actually a good add-on if we have it, do we have it yet?

**Comment by gustavz** [comment]
any news on this feature request? It would be awesome!

**Comment by stdhi** [comment]
+1

**Comment by sharootonian** [comment]
any updates on this?

**Comment by tonyfast** [comment]
This feature will exist as a community extension in the future Notebook v7 release using the https://github.com/agoose77/jupyterlab-markup .

For more information about this new release, checkout the [Notebook v7 Enhancement Proposal](https://github.com/jupyter/enhancement-proposals/blob/master/79-notebook-v7/notebook-v7.md).

**Comment by Jabi7** [comment]
Any updates as of now?
