### ISSUE TITLE
missing depedencies for fresh installation from repo

### ISSUE THREAD

**Issue by dkrenn** [jupyter/notebook#2303]
I've installed jupyter-notebook 5.0.0-rc.1 on a fresh system (Linux Mint 17.3) according to `CONTRIBUTING.rst` works, but running `jupyter-notebook` works only if the following missing dependencies were installed before manually  via `pip`:

- terminado
- ipython
- mistune
- bleach
- pandocfilters
- entrypoints
- testpath
- jsonschema
- pyzmq
- python-dateutil
- enum34

IMO, this should be installed automatically or, at least, be documented in `CONTRIBUTING.rst` so that installation works as claimed on this page.

**Comment by minrk** [comment]
These are installed automatically if pip is working correctly. Can you show the output of your install command?

**Comment by minrk** [comment]
Also, what's your `pip` version? It should be ≥ 9.

**Comment by dkrenn** [comment]
@minrk Here the output:
[jupyter-notebook-install-20170317.txt](https://github.com/jupyter/notebook/files/850494/jupyter-notebook-install-20170317.txt)
It seems that only `terminado` is not installed (not sure about the remaining; they seem to be installed; maybe some kind of global/local-issue of these other packages)

**Comment by dkrenn** [comment]
```
dakrenn@pc72-math /local/dakrenn/sage/jupyter-notebook $ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by minrk** [comment]
I would definitely expect pip 1.5 to fail in a variety of ways, for this and plenty of other packages. There are several package specifications, conditional dependencies, and other features that pip 1 does not support.

I would *highly* recommend upgrading pip:

    pip install --upgrade setuptools pip

especially if you ever encounter installation issues.

**Comment by dkrenn** [comment]
@minrk Thanks; works (tested on another, similar machine). The problem was/is, that I have had run `pip install --upgrade setuptools pip` before, but with `--user` as suggested on `CONTRIBUTING.rst`. However, the three lines later `pip install -e . --user` does not have used the new upgraded pip but still the system wide (old) pip.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
