### ISSUE TITLE
Documentation missing images on readthedocs

### ISSUE THREAD

**Issue by peterjc** [jupyter/notebook#2304]
Viewing this page on readthedocs, I see no images:

http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Notebook%20Basics.html

Viewing the source on GitHub the images are shown:

https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb

Tested using Chrome  56.0.2924.87 (64-bit) or Safari Version 10.0.3 (12602.4.8) on macOS

**Comment by takluyver** [comment]
@mgeier does nbsphinx handle images included using Markdown?

**Comment by mgeier** [comment]
It handles images that are using Markdown syntax `![alt text](image_link.png)`, but it currently doesn't parse HTML `<img>` tags, which are used in the abovementioned example notebook.

See also https://github.com/spatialaudio/nbsphinx/issues/52.

**Comment by takluyver** [comment]
Aha, thanks. So as Fernando said on that image, we should stick to the Markdown syntax for now.

**Comment by takluyver** [comment]
Made #2313 to convert to Markdown syntax.

**Comment by danzimmerman** [comment]
Just to be clear, <img> tags **used** to work fine in nbconvert of Jupyter notebooks to HTML but now this is broken?

I just wanted to verify that this is the issue I'm having, and there's no workaround besides using Markdown syntax images... and that if I re-run old notebooks, I will have to edit all the <img> tag code in my MD cells?

This is the behavior I'm getting now:

![image](https://cloud.githubusercontent.com/assets/4365714/24115539/08bfdf60-0d7a-11e7-86ff-96ac92b1f6e3.png)

![image](https://cloud.githubusercontent.com/assets/4365714/24115677/827dc40c-0d7a-11e7-85cd-460cdc0fd04d.png)

Jupyter 4.3.1


![image](https://cloud.githubusercontent.com/assets/4365714/24115560/1d61e8a0-0d7a-11e7-9681-941d1a577f1b.png)

**Comment by takluyver** [comment]
HTML tags should still work in *nbconvert* - make sure both that and the `mistune` package are up-to-date, and if so file an nbconvert issue. This issue is about *nbsphinx*, which integrates notebooks into Sphinx docs.
