### ISSUE TITLE
In single-tab mode, Download as > Notebook(.ipynb) menu still opens a new tab

### ISSUE THREAD

**Issue by emilyz-github** [jupyter/notebook#2310]
I have set up environment using single-tab mode. I confirm the set up is working, at least if I click a notebook title, it will open the notebook at the same web browser. No new tab is opened. 

However, If I click on Download as > Notebook(.ipynb) menu, a new tab is still opened. 

Steps to reproduce:
1. Open a notebook
2. File > Download as > Notebook(.ipynb)

Just as a reference, If I click File > Download as > HTML(html), no new tab is opened.

**Comment by takluyver** [comment]
I think this means that [this function](https://github.com/jupyter/notebook/blob/94122d6f8c7881fd8cd87fd82e23a0b6d1e04fd4/notebook/static/notebook/js/menubar.js#L175) needs to use `this._new_window()`, as some functions above already do.

**Comment by gnestor** [comment]
It looks like "Download as .ipynb" was using different logic than the rest, which used `this._new_window(url);`

```js
var w = window.open('');
var url = utils.url_path_join(
    base_url, 'files', notebook_path
) + '?download=1';
if (that.notebook.dirty && that.notebook.writable) {
    that.notebook.save_notebook().then(function() {
        w.location = url;
    });
} else {
    w.location = url;
}
```

I just tested with single-tab mode and it works.
