### ISSUE TITLE
Question mark before comment (docstrings) [enhancement proposal]

### ISSUE THREAD

**Issue by mhooreman** [jupyter/notebook#2311]
Hello,

Quite often, I start calling a function/method, and I forgot the arguments.

In that case, I start writing the code and, when I realize I forgot something, I'd like to push a question mark, and then a comment mark before the parenthesis. For example:
`myDataFrame.to_excel?  # (excel_writer=myWriter,`

Unfortunately, this leads to an error in Jupyter notebook, instead of showing me the docstring.

So, I must delete what I've already written after the parenthesis in order to have a "clean" line like:
`myDataFrame.to_excel?`

Would it be possible to improve that behavior?

Thanks a lot.

**Comment by takluyver** [comment]
It may be possible, but do you know about Shift-tab? Put the cursor in `to_excel`, press shift-tab, and you should get a tooltip with information about it. Press shift-tab more times to expand the tooltip or move it to the pager at the bottom of the window.
