### ISSUE TITLE
Traitlets 4.3.1 gives me: DeprecationWarning: metadata {'config': True} was set from the constructor

### ISSUE THREAD

**Issue by tomdz** [jupyter/notebook#2314]
I'm getting this warning from traitlets 4.3.1:
```
DeprecationWarning: metadata {'config': True} was set from the constructor. With traitlets 4.1, metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
```
It looks like it comes from this code:
https://github.com/jupyter/notebook/blob/master/notebook/extensions.py#L59-L61

**Comment by gnestor** [comment]
What version of the notebook are you running?

**Comment by tomdz** [comment]
I got this with 5.0.0b2 from pypi

**Comment by gnestor** [comment]
@minrk I see that there were some deprecations in traitlets 4.3. Do we need to update the notebook to reflect these?

**Comment by minrk** [comment]
This particular one was deprecated in 4.1, but I've reverted the deprecation of `config` in the constructor in 4.3.2, so it should be fine to leave these.

**Comment by gnestor** [comment]
@tomdz I'm going to close this one as the deprecation message should go away after upgrading to traitlets 4.3.2.
