### ISSUE TITLE
Traitlets 4.3.1 gives me: DeprecationWarning: object.__init__() takes no parameters

### ISSUE THREAD

**Issue by tomdz** [jupyter/notebook#2316]
Traitlets 4.3.1 gives me:
```
DeprecationWarning: object.__init__() takes no parameters
  super(HasTraits, self).__init__(*super_args, **super_kwargs)
```
which seems to come from https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1046-L1050 where a `ConfigManager` is created with a `config_dir ` argument, which is passed on to `LoggingConfigurable` and `Configurable`, neither of which support it.

**Comment by gnestor** [comment]
Related https://github.com/jupyter/notebook/issues/2314

**Comment by minrk** [comment]
This one's a real bug #2347
