### ISSUE TITLE
Unable to load default logo when launch jupyter notebook

### ISSUE THREAD

**Issue by Amasics** [jupyter/notebook#2320]
After I installed root kernel from https://github.com/root-project/root/tree/master/bindings/pyroot/JupyROOT#python-rootbook, my jupyter notebook tries to load the custom.css from that kernel instead of the default jupyter logo every time I launch it with just `jupyter notebook` in the base url localhost:888. However, if I launch it in another url it works fine. I checked the .jupyter directory and $user/Library/Jupyter directory but could not find anything that has been changed. How does Jupyter determine which custom.css to load when it launches, and where is its default logo stored?

![image](https://cloud.githubusercontent.com/assets/15698673/24131552/aff29f8e-0dc5-11e7-9e8e-461ceec9d9f5.png)

![image](https://cloud.githubusercontent.com/assets/15698673/24131640/43c51b6a-0dc6-11e7-9916-edab5bd5bf13.png)

**Comment by takluyver** [comment]
The custom css is stored in `~/.jupyter`, but it would be the same for all URLs. The fact that it's specific to the default port sounds like it might be a browser caching issue. Can you try launching on that port and then using a different browser?

**Comment by Amasics** [comment]
It is a browser caching issue. I clear the cache and the issue is gone now. Thanks.
