### ISSUE TITLE
changing env as different python versions in anaconda, jupyter still invokes wrong root

### ISSUE THREAD

**Issue by peeyushpashine** [jupyter/notebook#2322]
I change enviroment in anaconda from 3.5 to 2.7 python version.
when I type jupyter Notebook in windows cmd, in the invoked ipython python default and python root is still 3.5.

**Comment by takluyver** [comment]
The quickest way is to install `jupyter` into each environment you use.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
