### ISSUE TITLE
guidance ref programmatically adding cell metadata / manually adding on classic nb works

### ISSUE THREAD

**Issue by Analect** [jupyter/notebook#2334]
Apologies for cross-posting from [here](https://github.com/jupyter/help/issues/149), but I'm not sure there's that much traffic through there.

Adding: 
jupyterlab==0.17.5
notebook==5.0.0b2

This is a modified version of one the [file-save hooks](https://jupyter-notebook.readthedocs.io/en/latest/extending/savehooks.html) to handle adding meta-data to the notebook as well as to each of the cells ... the idea being that it ignores adding the meta-data if it pre-exists.  While adding the notebook meta-data is straight-forward (first part of script below), programmatically adding the cell meta-data is failing.  It seems the cell meta-data isn't getting persisted back to the `model`, although I can see correctly generated cell UUIDs, if I open the notebook in the jupyterlab text editor.  The problem arises when it comes to adding new cells and re-saving, it ends up generating new IDs for each cell (when it should have disregarded those with this info already in place, only generated IDs for new cells).

```py
def add_metadata_pre_save(model, **kwargs):
    """adds basic notebook meta-data"""
    # only run on notebooks
    if model['type'] != 'notebook':
        return
    # only run on nbformat v4
    if model['content']['nbformat'] != 4:
        return
    # determine if notebook metadata pre-exists
    # if it does not, then let's add some.
    if 'nb_test' not in  model['content']['metadata']:
        nb_metadata = {'id': str(uuid.uuid4()), 'ProjectId': '12345'}
        model['content']['metadata']['nb_test'] = nb_metadata
    # now let's ensure each cell has some identifiers
    for i, cell in enumerate(model['content']['cells']):
        print(cell)  #just for troubleshooting
        # check if cell meta-data pre-exists
        if not 'test_cell_metadata' in model['content']['cells'][i]['metadata']:
            cell_metadata = {'cell_uuid': str(uuid.uuid4())}
            model['content']['cells'][i]['metadata']['test_cell_metadata'] = cell_metadata
            print('test_cell: '+ json.dumps(model['content']['cells'][i]['metadata']))  # just for troubleshooting
c.FileContentsManager.pre_save_hook = add_metadata_pre_save
```

The only way I can get this script above to work currently is by manually adding cell meta-data via the classic notebook.

![image](https://cloud.githubusercontent.com/assets/4063815/24084954/7e9de734-0ceb-11e7-9441-04e60801d18a.png)

If I do that, then the first three cells remain fixed (ie. no identifiers are regenerated), but the last cell below I haven't added manually, so it keeps regenerating a different UUID.

```
{'metadata': {'test_cell_metadata': {'cell_uuid': '1234'}}, 'source': 'test', 'cell_type': 'markdown'}
{'metadata': {'test_cell_metadata': {'cell_uuid': '5678'}}, 'source': 'another', 'cell_type': 'markdown'}
{'metadata': {'test_cell_metadata': {'cell_uuid': '9012'}}, 'source': 'one', 'cell_type': 'markdown'}
{'metadata': {}, 'source': 'now', 'cell_type': 'markdown'}
test_cell: {"test_cell_metadata": {"cell_uuid": "85823e9d-fb61-44a9-8ef6-d169d6581cb7"}}
```
If I try to alter the meta-data using the cell tool in jupyterlab, then it fails to save changes when clicking on the save icon.

![image](https://cloud.githubusercontent.com/assets/4063815/24084966/ab31ffb0-0ceb-11e7-8587-324847a5c314.png)

I'd appreciate any guidance here .. it could be that my python dictionary manipulation skills are just bad! ... and if it's a case that any of these are bugs, I'm happy to add as issues to the relevant repo.

**Comment by Analect** [comment]
@blink1073 ... happy to add problem ref meta-data not getting saved in jupyerlab ... but is this likely fixed by this [PR](https://github.com/jupyterlab/jupyterlab/pull/1986)?

**Comment by blink1073** [comment]
That was the goal ;).  Sorry, forgot to cross-link back.

**Comment by Analect** [comment]
@gnestor ... sorry, but could you reopen this.  

While the last part of the issue relating to jupyterlab may have been resolved, I haven't been able to resolve the part relating to how cell meta-data is failing to persist back to `model`  (the main purpose of the issue)  when using file_save hooks.  If it's a case that I am just doing this wrong, then if someone better informed could point me in the right direction, that would be great.

**Comment by gnestor** [comment]
@Analect Sorry about that, I'm doing _Spring cleaning_ on this repo. Your hook looks fine to me. Deferring to @takluyver who wrote the docs on the subject 👍

**Comment by gnestor** [comment]
@Analect Sorry about that, I'm doing _Spring cleaning_ on this repo. Your hook looks fine to me. Deferring to @takluyver who wrote the docs on the subject 👍

**Comment by Analect** [comment]
@takluyver 
Would you have any thoughts on what I might be doing wrong here.  It seems when I push updates to the `model` cell meta-data programmatically, they don't persist ... or somehow on loading, `model` isn't loading the cell meta-data, when it has been added programmatically, as per my UUID example above. Thanks.

**Comment by Analect** [comment]
@takluyver 
Still struggling with this.  Would you have any pointers as to what I might be doing wrong ... or suggest someone else who might be able to help.  Thanks.

**Comment by Analect** [comment]
@takluyver or @minrk 
Sorry to rattle on about this, but I can't rationalise this behaviour in the notebook.  Can you shed any light on what might be happening here?

As per the [top of this thread](https://github.com/jupyter/notebook/issues/2334#issue-216507596), I have a very basic post-save hook that adds cell meta-data (a UUID) to each cell, where it should skip over cells that already have a UUID (ie. NOT overwrite these with a new UUID).

I have a pre-existing sample notebook (screenshot below) that I open up in Jupyterlab.  I add a new cell to the end of the notebook (red rectangle on lower left) ... and this generates the new cell with a new UUID in 'B', while leaving the existing cells (A) intact (ie. A = A1).  This is the expected behaviour.

![image](https://cloud.githubusercontent.com/assets/4063815/26770761/608c804a-49b1-11e7-8ed5-fbf52c18818b.png)

However, if I now create a new notebook in the jupyterlab environment (it hasn't pre-existed) and incrimentally add a series of cells, checking the ipynb file structure along the way, it ends up regenerating UUIDs for existing cells, so that A=!A1 and B=!B1. This is NOT the expected behviour.

![image](https://cloud.githubusercontent.com/assets/4063815/26770664/80741504-49b0-11e7-80d7-e54ac7b9dea0.png)

Am I missing something in my 'hook' that requires me to somehow re-initialise the `juptyer_notebook_config.py` file when new files are added to the compute environment.  The fact that the code works for a pre-existing notebook and not for a newly-generated one has me baffled.  Both notebooks are nbformat v4.2, as per the meta-data below.

```
"metadata": {
  "eolas": {
   "eolasProjectId": "12345",
   "gitlabProjectId": 142,
   "id": "99ae4211-d313-463c-9524-cdc695824db7"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by blink1073** [comment]
I think issue here is that the frontend doesn't expect its contents to have changed on disk.  What I would have expected is that when it tries to auto-save it would see that the file on disk is different and give you the option to choose what is in the front end or merge.  It could be that the post save hook is not modifying the timestamp by enough time.  A way to test this fact would be to add a delay to the post save hook.  

Another thing to check is whether it works in the classic notebook.  From reading the autosave [source](https://github.com/jupyter/notebook/blob/e1ba0075f6c5d901f67918e41f434b1788d592f8/notebook/static/notebook/js/notebook.js#L2661) I'd expect the same friction between a post save hook on the server and the front end data model.

**Comment by minrk** [comment]
Adding metadata in the pre-save hook doesn't modify the model on the page, which seems to be the source of the problem. So on every save, every cell gets a new UUID, at least until the next time the file has been loaded from disk. Changes made in this way can only get to the page if one does save followed by reload. If you want to create persistent cell IDs in the notebook, I think the only way to do it reliably is via a javascript extension, rather than a pre-save hook.

The timestamp check doesn't help because the file written by the hook *is* the file written by the request (some transform was allowed). A post-save hook, on the other hand, could modify the timestamp and cause the "file changed on-disk" dialog (not a pleasant one, but at least it would indicate that the page and file are out of sync).

**Comment by Analect** [comment]
@minrk ... 
> Adding metadata in the pre-save hook doesn't modify the model on the page, which seems to be the source of the problem.

Thanks for confirming this behaviour ... although I do notice that the notebook level (rather than the cell-level) meta-data does appear to modify the model ... as that gets set once and stays that way.  Is there any way that the cell-level meta-data could be set up to work the same way?

> Changes made in this way can only get to the page if one does save followed by reload. 

Is there any way to achieve this within the hook ...so that the model can be 'forced' to update ..  without disturbing things on the front-end, since the notebook is still likely to be open.

> If you want to create persistent cell IDs in the notebook, I think the only way to do it reliably is via a javascript extension

I don't have much experience with these.  Would you happen to have a worked example?  Does this approach also seek to introspect the json representation of a notebook and append values?  Would it be loaded using the new jupyterlabextension mechanism?

Thanks ... your insights are always valuable.

@blink1073 
> What I would have expected is that when it tries to auto-save it would see that the file on disk is different and give you the option to choose what is in the front end or merge.

I can't seem to reproduce now ... but I do sometimes get a warning dialogue on the front-end ... that the data has changed on disk (ie. when the cell meta-data has been added, presumably) ... and whether I should 'revert' (reload from file, I think) or 'discard' ... I can live with that and select 'revert' to preserve the added meta-data.

The other thing that doesn't work (until I close and reopen the workbook) is that the cell meta-data editor doesn't expose new meta-data added to the underlying file ... but that's also something I can live with.

**Comment by minrk** [comment]
> Thanks for confirming this behaviour ... although I do notice that the notebook level (rather than the cell-level) meta-data does appear to modify the model ... as that gets set once and stays that way. Is there any way that the cell-level meta-data could be set up to work the same way?

This is not accurate. Any metadata set on save will not take effect until the notebook is re-opened. Any changes on the notebook are treated the same way.

> Is there any way to achieve this within the hook ...so that the model can be 'forced' to update .. without disturbing things on the front-end, since the notebook is still likely to be open.

Only by making the changes in javascript instead of a pre-save hook.

> Would you happen to have a worked example? Does this approach also seek to introspect the json representation of a notebook and append values? Would it be loaded using the new jupyterlabextension mechanism?

There are several examples [here](https://github.com/ipython-contrib/jupyter_contrib_nbextensions), though I'm not sure about JupyterLab extensions. You would probably want to trigger an event to set metadata on creation of new cells, rather than on the save event.

**Comment by Analect** [comment]
@minrk @blink1073 
> This is not accurate. Any metadata set on save will not take effect until the notebook is re-opened. 

Either I'm not fully comprehending what's happening here ... but I'm NOT seeing the different types of meta-data act in the same way, as you suggest above.

You can reproduce this for yourself.
Create a new notebook in jupyterlab, add a single markdown cell, observe the structure of the saved notebook (see FIRST SAVE below) by opening the file with the editor.
Add another cell(s) and resave, observe the structure (SECOND SAVE below).
With the notebook remaining open in jupyterlab between saves, the cell meta-data UUIDs (blue squares) keep getting replaced, HOWEVER the notebook meta-data id (red squares) does NOT.

If I close and reopen the notebook and then add a new cell, then the pre-existing cell meta-data will remain in place, but cell meta-data generated against any new cells will get replaced on each save.

![image](https://cloud.githubusercontent.com/assets/4063815/26831699/0aa1fce0-4ac5-11e7-9a97-6d38fbd988b1.png)

What might be happening ... and which perhaps could explain the seemingly different treatment of meta-data above is that a pre-save hook is applying the notebook-level meta-data before jupyterlab opens the file for the first time ... ie. after you fill the dialogue to rename from 'untitled' and select a kernel.  Below is the structure of notebook at that point .. before any content/cell has been added.

![image](https://cloud.githubusercontent.com/assets/4063815/26834972/e558dfc6-4ace-11e7-84d6-50c443f00eca.png)

@blink1073 ... @minrk is suggesting a javascript notebook extension as a better way of setting cell meta-data.  He has pointed towards [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions).  Are these types of extensions likely to work in a jupyterlab context?  If not, are you able to point to a sample extension that might emulate how I might set cell-level meta-data? Thanks.

**Comment by blink1073** [comment]
@Analect, yes, we ask the server to create a new file to start, and then load that file from disk, which explains the notebook level metadata being there.  The JavaScript APIs in JupyterLab are not compatible with those of the Notebook (there was explicitly no stable public API), so none of the existing extensions will work in a JupyterLab context.  We don't yet have an example of an extension that demonstrates interacting with the notebook model in JupyterLab.  Do you mind opening an issue asking there asking for one?

**Comment by takluyver** [comment]
As far as I can tell, you're not missing anything. There shouldn't be any difference between saving a notebook you've loaded versus one you created in this session.

**Comment by takluyver** [comment]
Ah, sorry, I missed reading several more recent messages in this thread. Disregard my last message.

**Comment by takluyver** [comment]
> If I close and reopen the notebook and then add a new cell, then the pre-existing cell meta-data will remain in place, but cell meta-data generated against any new cells will get replaced on each save.

This makes sense now - the save hook modifies the notebook that's being written to disk, but those changes don't go back to the notebook you have loaded. So the open notebook in memory doesn't have the cell IDs, and when you save it again, the save hook generates new IDs for those cells.

As others have suggested, you may be better off with an nbextension, which can modify the notebook in memory.

**Comment by Analect** [comment]
Thanks @takluyver  ... yes .. just not sure how to go about such an extension in a jupyterlab context ... eventhough @blink1073 left a few suggestions left [here](https://github.com/jupyterlab/jupyterlab/issues/2377).  I don't have a good enough grasp of the code-base, especially as it pertains to the notebook component with lab.  Hoping for a few more working implementations out there to get a better handle on it.

**Comment by takluyver** [comment]
I can't give you much help myself, but maybe some of these examples are useful: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/

**Comment by Analect** [comment]
@takluyver thanks ... I'm aware of those examples .. but I don't believe (as per [comment](https://github.com/jupyter/notebook/issues/2334#issuecomment-306524938) above) that any of those are compatible with the notebook in a jupyterlab context.

**Comment by p2ya** [comment]
@Analect  Is there anyway to get access to notebook metadata inside the notebook ?
I need to rewrite some part of metadata based on read parameters from a notebook cell.

**Comment by gnestor** [comment]
@p2ya I assume you mean programmatic access of notebook metadata? See the NotebookModel class: http://jupyterlab.github.io/jupyterlab/classes/_notebook_src_model_.notebookmodel.html

**Comment by p2ya** [comment]
@gnestor how can I use this to get the notebook metadata within the notebook ?

**Comment by gnestor** [comment]
AFAIK it's not possible to access to JupyterLab API from within a notebook like you can with the classic notebook (by just running JS code in the browser console or in a code cell using the `%javascript` magic) since JupyterLab doesn't expose globals to the JS context. 

What you can do it right-click a notebook in JupyterLab's file browser and open with "Editor." This will allow you to edit the notebook metadata.

![](http://g.recordit.co/sprYQi8HxH.gif)

**Comment by p2ya** [comment]
@gnestor I use jupyter notebook, is it possible in that ?

**Comment by gnestor** [comment]
Yes, see Edit > Edit Notebook Metadata in the notebook menu:

![image](https://user-images.githubusercontent.com/512354/35369538-297a4c10-013d-11e8-845d-c0d341b9ade0.png)
