### ISSUE TITLE
core.magics.display.Javascript not working but magic does

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyter/notebook#2335]
I have the following Python code cell:

    from ipywidgets import widgets
    from IPython.core.magics.display import Javascript
    submit_button = widgets.Button(description='submit')
    
    def button_function(elem):
        print('hello')
        Javascript("alert('TEST')")
        
    submit_button.on_click(button_function)
    
    submit_button

It is supposed to render a button (which it does) and when I click the button, it is supposed to run JS code. Somehow it does not do it. It does print the `hello` though, as if the JS is simply ignored. However, when I use the magic directly or call the `Javascript` function directly as in the following two cells:

    %%javascript
    alert('Test')

and

    Javascript('alert("hello world")')

it works fine. Is this a notebook issue or an issue of the widgets?

**Comment by ZelphirKaltstahl** [comment]
I found the mistake shortly after posting:

One has to use `display(Javascript(...))` in the button function.

**Comment by takluyver** [comment]
`Javascript()` creates a javascript display object. If you call it at the end of a cell, it is displayed automatically, like putting `2+2` at the end of a cell will display 4. If it's not the last thing in the cell, or it's inside a function, you need `display()`, equivalent to putting `print(2+2)`.
