### ISSUE TITLE
Accepting cookies is required but no useful warning is given

### ISSUE THREAD

**Issue by Wrzlprmft** [jupyter/notebook#2337]
I tried to open a Jupyter Notebook today and got the error message “Error loading notebook” without any further details. After some digging and guesswork, I found out that the problem was that I did not accept cookies from `localhost`. I suggest that the Notebook checks for this and sends a reasonable warning, if cookies are not accepted.

**Comment by gnestor** [comment]
@Carreau Thoughts?

**Comment by Carreau** [comment]
Hum, I'm not even sure how to check for this. I agree that we should try to have a better error message if we can detect it. Or at least having it in the FAQ.

**Comment by rosaswaby** [comment]
Hi @ckilcrease and I were hoping to contribute this issue but we are not able to re-create it. We are both using the chrome browser and we have disabled the cookies in settings and we are both getting the same result which you can see below but it is not giving us the error that you received initially. Would you be able to give any more details on how to re-create the error message. 

<img width="1255" alt="screen shot 2018-03-27 at 11 45 15 am" src="https://user-images.githubusercontent.com/9499838/37978586-6159c794-31b4-11e8-93f7-23a0e049b111.png">

<img width="855" alt="screen shot 2018-03-27 at 11 36 28 am" src="https://user-images.githubusercontent.com/9499838/37978647-78611438-31b4-11e8-8cb2-a2217ec1d6c6.png">

**Comment by takluyver** [comment]
Educated guesswork here, but if you've got an existing notebook file, try running `jupyter notebook my_notebook.ipynb` to launch Jupyter and open the file.

**Comment by ckilcrease** [comment]
Thanks, we were able to recreate it when running with an existing notebook file. We were thinking one approach might be checking if the user has cookies enabled, and if not, adding a warning message describing this. Does this sound like a good approach?

**Comment by takluyver** [comment]
Yep, that sounds reasonable.

**Comment by rosaswaby** [comment]
Thank you for your help! We (me and @ckilcrease) were working on the issue and we managed to detect if the cookies and enabled and produce the correct error message. Do you have any preference for how we should format the error message in the modal?

**Comment by takluyver** [comment]
If you've got something that works, feel free to open a pull request - that's a good format for discussing the specific details, because we can point to particular bits of code.

**Comment by takluyver** [comment]
Closed by #3511.
