### ISSUE TITLE
Rendering issues with IPython. Equations not properly renderd

### ISSUE THREAD

**Issue by skanti** [jupyter/notebook#2338]
Hi,
with **Ubuntu 17.04** and **Firefox 50.1 / Chrome 57.0** and **Jupyter 4.2.1** I get wrongly rendered equations. 

The surprising part is, that the second after I hit the `Enter` button, the rendering looks right. Then after some more seconds the renderer decides to mess everything up. Does this behavior sound familiar?

**BTW**: the github renderer looks right.

![logo](http://i.imgur.com/tqRHhH3.png)

**Comment by takluyver** [comment]
That behaviour does not sound familiar. Can you try with the 5.0 release candidate? `pip install --upgrade --pre notebook`

**Comment by skanti** [comment]
@takluyver I did. No difference really.

I think the most unusual part is that when I start up `jupyter notebook` and view a `.ipynb` file then it will render correctly. But as soon as I edit that file, then I get this delayed garbage as I mentioned in my first post.

**Comment by takluyver** [comment]
So normally maths is initially unrendered, and then it reappears rendered a second later once Mathjax has done its thing. It sounds like something is going wrong with the Mathjax rendering. Are there any errors in your browser's Javascript console?

**Comment by skanti** [comment]
I found a fix for the error:

1. Uninstall `jupyter-notebook` and `jupyter-core` from APT (because I had it installed)
2. Install newest version of jupyter with `pip3 install (--pre) jupyter`
3. Run with `ipython notebook`

For my part, this issue can be closed.

**Comment by takluyver** [comment]
Ah, OK. Probably Debian packaging has broken Mathjax :angry:
