### ISSUE TITLE
terminal function docstring/arguments not shown with shift+tab

### ISSUE THREAD

**Issue by EnviousElitist** [jupyter/notebook#2345]
I'm on 5.3.0

```
In [2]: import numpy as np
In [3]: np.array 
```

Using shift+tab does not show any function arguments or docstring in the terminal.  Works fine as a tooltip in jupyter notebook and in qtconsole.  Not sure if this is expected or if there is an alternate method of showing the function arguments/docstring in the terminal, other than the monolithic "np.array?"

Tab completion and argument completion works fine once the open parens is given.

EDIT: just noticed I submitted this to jupyter notebook instead of ipython, but I will leave this open in case anyone wants to comment

**Comment by gnestor** [comment]
Closing as this is in ipython jurisdiction...
