### ISSUE TITLE
finished_execute.CodeCell event triggered multiple times

### ISSUE THREAD

**Issue by juhasch** [jupyter/notebook#2352]
If I execute this snippet with notebook *5.0.0rc2*, I get a log whenever a codecell is executed:
```
%%javascript

require(['base/js/events'], function(events) 
    {
    events.on('finished_iopub.Kernel', function(evt){ console.log('finished_iopub.Kernel', evt)})
    events.on('finished_execute.CodeCell', function(evt){ console.log('finished_execute.CodeCell', evt)})
    })
```
If I execute any codecell now, `finished_execute.CodeCell` is triggered an increasing number of times.
So first execution of any codecell, `finished_execute.CodeCell` is triggered once. Second execution twice, etc.

Any idea why this is happening ?

**Comment by gnestor** [comment]
It looks like a new event listener is added on `CodeCell.execute` which would explain why you get _n_ number of events triggered for _n_ number of executes called. I think the simplest fix is to use `events.one` which will remove the event listener after the first event is handled.

**Comment by gnestor** [comment]
FYI @dkrenn:

Using [`events.on`](http://api.jquery.com/on/) will create a new event listener every time a cell is executed. [`events.one`](http://api.jquery.com/one/) will also create a new event listener, but then dispose itself after the first event is handled.

**Comment by gnestor** [comment]
@juhasch If you get a chance, can you checkout this PR and confirm the it fixes this issue:

```
git fetch jupyter pull/2354/head:pr/2354
git checkout pr/2354
pip install -e .
````

**Comment by dkrenn** [comment]
@gnestor Ok, thank you (I didn't know).

**Comment by juhasch** [comment]
Tried it, looks good 👍 
Thanks for the quick fix!
