### ISSUE TITLE
.gnupg doesn't exist. 

### ISSUE THREAD

**Issue by toqduj** [jupyter/notebook#2356]
Whenever I use Jupyter notebook on OSX, Safari (currently 10.1), I get messages indicating that it's trying to access my .gnupg directory. This directory is a symlink to the same on a mounted drive, and is therefore not always available. 

However, I'm wondering why jupyter notebook needs or seeks access to my GPG keys to begin with? Should I be suspicious?

When the directory isn't available, I get the following error message:
[W 14:01:15.947 NotebookApp] /Users/brian/.gnupg doesn't exist

Any insight appreciated.

**Comment by takluyver** [comment]
We don't do anything with GPG. Do you have any config that might affect it?

**Comment by toqduj** [comment]
I have never configured Jupyter or Safari to do anything with GPG either, which is why it raises my eyebrows.

**Comment by takluyver** [comment]
Ah, looking at the code, it's coming as it tries to list the directory for the dashboard. It will give that warning for any broken symlink in the directory where you launch it. It's just trying to check if it's a directory or not, not doing anything with the contents.

**Comment by toqduj** [comment]
Ok, that is a fair explanation. Thanks for digging that up!
