### ISSUE TITLE
F-String highlight problem

### ISSUE THREAD

**Issue by flaviodrt** [jupyter/notebook#2358]
Hi,
I started using F-String and I realized that the notebook could not highlight correctly the line.
Here some examples:

Without F-String formatting:
![captura de tela de 2017-04-02 13-02-38](https://cloud.githubusercontent.com/assets/79948/24588763/585619ce-17a5-11e7-99cc-b718ef40d9b4.png)

With raw string formatting:
![captura de tela de 2017-04-02 13-02-59](https://cloud.githubusercontent.com/assets/79948/24588769/6f23285e-17a5-11e7-8ef4-dab39f23e819.png)

With F-String formatting:
![captura de tela de 2017-04-02 13-03-38](https://cloud.githubusercontent.com/assets/79948/24588770/7b66dd04-17a5-11e7-9d5a-47cd69ba4af9.png)

Server Information:
```
You are using Jupyter notebook.

The version of the notebook server is 4.3.1 and is running on:

Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
```

My Firefox version: 50.0
I have tested with Google Chrome 57 and had the same behavior.

If you give the path, I would be happy fixing this.
Thank you.

**Comment by gnestor** [comment]
Hi @flaviodrt! This issue was fixed by https://github.com/jupyter/notebook/pull/2066, so simply upgrade the notebook to 4.4.1 (`pip install notebook --upgrade`).

Please confirm that this resolves it for you 👌

**Comment by gnestor** [comment]
You can now upgrade to 5.0 👍

**Comment by flaviodrt** [comment]
Hi @gnestor, thank you for your attention!
I'm sorry about that, I've searched for an issue about f-string but apparently I've failed in my search.
I've downloaded a fresh anaconda install from anaconda's website about one month ago and I thought that it was up to date.

Updating my notebook solved this problem!
Thank you again!

**Comment by mileserickson** [comment]
Note: Anaconda users may prefer `conda update notebook`
