### ISSUE TITLE
Jupyter ipython kernel crashing when running %pylab magic

### ISSUE THREAD

**Issue by abalter** [jupyter/notebook#2360]
I installed jupyter with conda. When I run the `%pylab` magic, it runs without comment, but after a moment or two the kernel died restarting popup appears. I've done a number of experiments to help identify the problem. None of them had the kernel crash.

1. Test the [equivalent code](https://ipython.org/ipython-doc/3/interactive/magics.html)

        import numpy
        import matplotlib
        from matplotlib import pylab, mlab, pyplot
        np = numpy
        plt = pyplot
    
        from IPython.display import display
        from IPython.core.pylabtools import figsize, getfigs
    
        from pylab import *
        from numpy import *

1. ipython at the terminal
1. jupyter_console at the terminal

Is there a log file I could look at somewhere that would give me some insight?

Cross-posted [here](http://stackoverflow.com/questions/43171126/jupyter-ipython-kernel-crashing-when-running-pylab-magic)

**Comment by takluyver** [comment]
What about the `%matplotlib` magic? You can see the code for what it does starting here: https://github.com/ipython/ipython/blob/3f95541b52f650ab0cf0009f64370ea4cdd4f557/IPython/core/magics/pylab.py#L94

Anything that's logged goes to the terminal where you launched the notebook. If there's no error message there, that usually means something is crashing at the C level.

**Comment by abalter** [comment]
This is all I get:

```
QXcbConnection: Could not connect to display
[I 09:16:50.576 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 5259113a-81d1-4102-94c4-77647c7c7bf9 restarted
```

**Comment by ccordoba12** [comment]
The default Matplotlib backend in Anaconda is Qt5, which requires an X server. Since it seems you don't have one, you need to set the backend to inline, with

    %matplotlib inline

I don't know if

    % pylab inline

works too. @takluyver?

**Comment by abalter** [comment]
`%pylab inline` worked! Maybe add to documentation?

But why don't other people have this problem? Why don't I have the same problem on my desktop? I know the server is running an X server.

**Comment by ccordoba12** [comment]
I don't know why Qt5 is not detecting your X server. Maybe you started the notebook as a service (with systemd), or in a container, or in any other way that is not in a running graphical session.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
