### ISSUE TITLE
Transparency in Search and replace box for text editor

### ISSUE THREAD

**Issue by xNok** [jupyter/notebook#2362]
As you can see in the image below the search and replace div in jupyter`s editor is unusable due to its transparency (we don`t see what we are typing).

![image](https://cloud.githubusercontent.com/assets/9772542/24625045/c463e2d2-187b-11e7-84ab-cb2f2670a49b.png)

**Comment by gnestor** [comment]
Good catch @xNok! I just submitted a PR that should fix this :+1:
