### ISSUE TITLE
[feature request] add "Pause" button to Notebook

### ISSUE THREAD

**Issue by andreas-h** [jupyter/notebook#2363]
I was wondering if there is a way to pause/suspend a running Jupyter kernel from the Notebook interface?  I was looking for a "Pause" button but couldn't find any.

Use case:  Imagine you're working on a laptop, and have a long-running computation at work.  Then it would be nice to suspend the kernel's activity when the battery gets drained.

**Comment by takluyver** [comment]
Thanks for filing. I think this should be straightforward on Unix systems, using SIGSTOP (or SIGTSTP if we want to give the kernel the option to ignore it) and SIGCONT. These could be exposed as kernel actions in the REST API, like interrupt and restart already are. I don't know if Windows has an equivalent, but if someone builds a Unix-only solution and leaves the actions as no-ops on Windows, I don't think we'd hold it up.

**Comment by vidartf** [comment]
Maybe relevant for Windows side: https://msdn.microsoft.com/en-us/library/windows/desktop/ms686342(v=vs.85).aspx

**Comment by Madhu94** [comment]
I ll check this out, if no one is working on it.

**Comment by takluyver** [comment]
I don't think anyone is. The place to start will be in the jupyter_client package, adding API functions to pause and continue a kernel's execution.

**Comment by sunpope** [comment]
Hey, I see there hasn't been any update on this in a while. I've been checking out the jupyter_client package and working out where to add the API pause/continue functions. However, could anyone point me towards the right directory to go about adding a new button to the top bar of a notebook? I think the best way to do it is to have a separate button controlling SIGTSTP and SIGCONT and leave the current Run and Interrupt buttons as is.

**Comment by takluyver** [comment]
I probably wouldn't put this in the toolbar for now: it's likely to be Unix only, and I'm not sure how reliably it will work. In terms of the UI, I'd probably start by making it an action (see `actions.js`) so that people can assign it custom shortcuts. But the APIs have to be built before anyone can add UI for it.

**Comment by sunpope** [comment]
Understandable, I'll go there and check it out. Is there a preference between having one action that both suspends the process if it is running AND continues the process if it has been suspended, or two separate actions to achieve the same thing?

**Comment by takluyver** [comment]
It's not a strong preference, but I'd lean towards two separate actions. We can always add a separate toggle action afterwards.

**Comment by stas00** [comment]
Any updates on this one? @sunpope and @Madhu94 - has either of you made any progress on this?

**Comment by arovit** [comment]
Guys, I have worked on this and filed [PR 3739](https://github.com/jupyter/notebook/pull/3739). Thanks.

**Comment by stas00** [comment]
@arovit, I tested https://github.com/jupyter/notebook/pull/3739 with some pytorch/cuda long running code - seems to pause and resume just fine.

Thank you!

**Comment by arovit** [comment]
Thanks @stas00 for testing out and sharing this great feedback.
I agree with your suggestions (toggle button and some kind of notifier for kernel pausing) and will start making frontend changes. Right now, I am not 100% sure about what's the best/right thing to do when a user is trying to execute cells on a paused kernel, so for now I will keep this open ended while implementing first two.

**Comment by stas00** [comment]
>   I am not 100% sure about what's the best/right thing to do when a user is trying to execute cells on a paused kernel

I thought of changing the background of all cells to a different color indicating this different state. But then I remembered the [themes extension](https://github.com/dunovank/jupyter-themes), which would make this complicated, as unless that extension is brought in sync with such change, some color conflict may happen.

Probably, for now leaving the cells as they are is fine -  as it is will just turn [*] waiting/busy flag on and perhaps, that'd be enough.

It'd be good to hear an opinion from the developers so that you don't waste time designing something that won't be accepted at the end. 

Thank you for your work, Arovit.

**Comment by vinay9986** [comment]
@arovit: Thank you for the amazing contribution and @stas00: thank you for taking the time for testing the changes out.

@takluyver: Can you please tell us when can we have this feature rolled out?

**Comment by takluyver** [comment]
We're on the cusp of releasing notebook 5.6, so I don't want to merge a new feature like this just before a release. After the release is done, hopefully quite soon.

**Comment by arovit** [comment]
Guys, I just updated the changes based on all the great feedbacks I received. Updates are to disable these options on Windows, toggle between pause and resume option and showing a notification for paused kernel in the notification bar. As always, looking forward to the feedbacks.

<img width="1022" alt="screen shot 2018-07-20 at 4 35 08 pm" src="https://user-images.githubusercontent.com/4410397/43029922-a29728c4-8c3f-11e8-94de-77390caa37da.png">

<img width="1138" alt="screen shot 2018-07-20 at 4 36 11 pm" src="https://user-images.githubusercontent.com/4410397/43029924-a6fd4fb0-8c3f-11e8-916f-dd600596350a.png">

**Comment by arovit** [comment]
Thanks @stas00 . I just pushed a commit which adds a selenium testcase for testing this feature and also made changes to have pausing/resume options right next to Interrupt in the kernel submenu. Please let me know if there is anything else I need to work on. Thanks.

**Comment by arovit** [comment]
Hello, Just a gentle ping to get some traction on the PR. Thanks !

**Comment by ideascidata** [comment]
Just for reference, I found that if I wanted to pause the script running in Jupyter notebook and resume it later, CTRL+S ended up working well for me (although this must be performed in the Anaconda terminal). 

Thanks

**Comment by githubpsyche** [comment]
just chiming to say i googled how to pause a notebook and ended up here! hope the feature's live sometime!

**Comment by MaxGhenis** [comment]
From the Linux shell, you can do Ctrl+Z to pause, then `fg jupyter notebook` to resume.

**Comment by vinay9986** [comment]
@arovit thank you for implementing the feedback.
@stas00 thank you for testing and sharing feedback.

@arovit I see that there is some merge conflict on your PR (on the test case), that is probably what is delaying your PR to be merged.

Eagerly waiting for this feature to be released.

**Comment by juliuskittler** [comment]
@arovit and @stas00 Thanks a lot for this feature! I was wondering if you are also planning to implement this for jupyter lab? On jupyter lab, there does not seem to be a `Pause` and  `Resume` option. Thanks in advance for a quick reply!

<img width="279" alt="Screen Shot 2019-05-11 at 19 31 34" src="https://user-images.githubusercontent.com/39234739/57573095-8a087c00-7423-11e9-94ab-f95983490ef1.png">

**Comment by BlkPingu** [comment]
In which version of jupyter notebooks is this implemented? I just checked because I have this issue with a time consuming process and I would love to have this feature.
I'm in MacOS 10.14.5

**Comment by vidartf** [comment]
This work is still WIP: https://github.com/jupyter/notebook/pull/3739

**Comment by dbrucknr** [comment]
Hi everyone,

I'm seeking a project to contribute to for one of my college courses. I was curious if there is anything going on in this feature that I could help with? I use Anaconda/Jupyter all the time and would really appreciate the opportunity to give back.

**Comment by devanshgoenka97** [comment]
Is this still being worked on? If not I am happy to step in and contribute...
