### ISSUE TITLE
displayed no kernel

### ISSUE THREAD

**Issue by SakuragiYoshimasa** [jupyter/notebook#2366]
when i reboot the jupyter notebook and open the ipyth file, 
immediately, kernel died and cant' restart, displayed "No Kernel"

**Comment by takluyver** [comment]
Do you know what kernel it's trying to use? Is there any error message in the terminal where you started the notebook that might indicate why the kernel died?

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
