### ISSUE TITLE
Scrollbar Bug in Notebook 5.0?

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter/notebook#2369]
As can be seen in the screenshot below the cells have scrollbars instead of expanding to fit the contents of the cell. This is on a brand new install on a clean Azure VM.

![image](https://cloud.githubusercontent.com/assets/881019/24699254/b1c68924-1a36-11e7-9b60-1a8ee9cd897b.png)

![image](https://cloud.githubusercontent.com/assets/881019/24699294/de89ef14-1a36-11e7-8934-86f115f41e9d.png)

**Comment by dhirschfeld** [comment]
Looks fine in Internet Explorer 11.953.14393.0
![image](https://cloud.githubusercontent.com/assets/881019/24699864/cd1c9e28-1a38-11e7-84a0-90cabdf9590a.png)

...but not in Chrome 57.0.2987.133 as shown originally

**Comment by dhirschfeld** [comment]
Anyone else seeing this?

**Comment by takluyver** [comment]
I don't see this in either Firefox or Chromium. :confused:

**Comment by dhirschfeld** [comment]
That could make it difficult to track down. On a different PC I also don't notice the problem :|

**Comment by gnestor** [comment]
Can anyone else reproduce?

@dhirschfeld Have you tested in Chrome ^59? That's what I'm currently running and cells appear as expected...

**Comment by dhirschfeld** [comment]
I can't repro now so I'll close. Can always reopen if necessary...
