### ISSUE TITLE
JS script less-watch is installed with setup.py install

### ISSUE THREAD

**Issue by hroncok** [jupyter/notebook#2373]
[less-watch](https://github.com/jupyter/notebook/blob/5.0.0/scripts/less-watch) is installed to bindir (such as `/usr/bin`) with `setup.py install`. According to @takluyver, it is [not desired](https://github.com/jupyter/notebook/commit/75835e4ca8e45e71f49724abe41f07e2e6218401#commitcomment-21638624).

The reason for the installation is [a glob in `setup.py`](https://github.com/jupyter/notebook/blob/5.0.0/setup.py#L79) that takes all files from the `scripts` dir. Please either move that file somewhere else or change the glob to only include `pjoin('scripts', 'jupyter-*')`. Thanks

**Comment by gnestor** [comment]
Thanks for catching this, @hroncok. It looks like this script is no longer being used so I just submit a PR to remove it.

**Comment by hroncok** [comment]
Removing the entire script?

**Comment by gnestor** [comment]
Removing `less-watch`, yes.
