### ISSUE TITLE
cant type right bracket ']'

### ISSUE THREAD

**Issue by steboc** [jupyter/notebook#2379]
i cant type right bracket 

Jupyter 5.01
Windows 7 ( French version ) and  windows 10 ( french)
Chrome 57.0.2987.133

edit : work with firefox

**Comment by flothesof** [comment]
I have the same problem and incidentally the same setup: Windows 7 French, Notebook 5.0.0, Chrome 57.0.2987.133. Typing "]" inside a cell does not work.

**Comment by gnestor** [comment]
Hmmm....

@Carreau @minrk

**Comment by Carreau** [comment]
Can you remind me what's the key combinaison on French keyboard for ] ?
AltGR-0 ? Does it do nothing ? Or insert something else? Can you try on
codemirror.net demo?

**Comment by steboc** [comment]
its AltGr + (key below f9 on the picture )
http://www.vallons.fr/cours-pc/Clavier_Azerty.jpg

**Comment by KevinBaudin** [comment]
Got the same issue with Jupyter (Anaconda 2) since last update 2 days ago
on Google Chrome Version 57.0.2987.133 (64-bit)

French keyboard (and yes, it s indeed AltGr + ")", two keys left from backspace)

Doing ] with Alt+93 from now, but quite annoying.

Ask me anything if you want further informations to fix this

**Comment by Carreau** [comment]
I've tried with my mac, setup with french keyboard and unfortunately I can't reproduce. So I'll have to find an actual windows machine and likely a Physical french keyboard layout (with altgr) and see what we can do.

How does it behave in codemirror directly ? 

http://codemirror.net/

**Comment by KevinBaudin** [comment]
Nothing wrong on codemirror for me.
Still got the issue on Jupyter though.

**Comment by gatsu** [comment]
Got the exact same problem, french azerty layout, win10, chrome. Using firefox "solve" the problem.

**Comment by KevinBaudin** [comment]
Anything new? 
Any clue to fix this ?

**Comment by Carreau** [comment]
> Anything new?
> Any clue to fix this ?

No, without a windows machine with the bug to actually track it down I can't narrow down the issue. 
@SylvainCorlay you are in France  maybe you have access to that ? I should be back in France this summer, I might have one machine available to do that. Unfortunately I stopped using French keyboard a couple of years ago and there is none available here.

**Comment by SmirnovAnton** [comment]
Confirming this issue with a German QWERTZ layout, Windows 7, Chrome version 58.0.3029.81 (64-bit), Jupyter version 4.3.0, Jupyter Notebook version 5.0.0. 

Am trying to type a backslash in a Markdown cell of an R notebook using AltGr + ß, nothing happens. The @ and € symbols both work (AltGr+Q, AltGr+E). Same behaviour in a code cell or a Python 3 notebook. 

Have just upgraded to Notebook version 5.0.0 and pip version 9, did not see the problem before the upgrade.

**Comment by takluyver** [comment]
> Have just upgraded to Notebook version 5.0.0 and pip version 9, did not see the problem before the upgrade.

Hmm, that's interesting. Maybe our use of a newer Codemirror version broke something. Does anyone have time to git bisect the `notebook` repo to find the first commit affected?

**Comment by takluyver** [comment]
If you're bisecting JS issues, by the way, you'll need to rebuild the JS at each step - see [Setting up a development environment](http://jupyter-notebook.readthedocs.io/en/latest/contributing.html#setting-up-a-development-environment) - and try to avoid your browser loading cached Javascript.

**Comment by floriangeigl** [comment]
Same here - can't type a \ in Chrome & IE. However, it works fine in Firefox.

**Comment by gempel** [comment]
Same \\ problem here on German keyboard, Win10 and Chrome. Works in Firefox.

I used git bisect and found https://github.com/jupyter/notebook/commit/1c8437a1231d86711d4cb2ad0070b24c8b556a26. The problem comes from the 'indentAuto' command in cell.js. In Chrome pressing the backslash-key-combo in a jupyter cell does indeed auto-indent . Removing the two 'indentAuto' lines and rebuilding the project fixes it. 

The backslash-key-combo is incorrectly indentified as 'Ctrl-Alt-['. Should be 'Ctrl-Alt-\\' or any of 'ß ? \\'. 

The Key-Event for the German backslash-key-combo in Chrome:

> key: '\\'    
> keyCode: 219
> which: 219

Firefox:

> key: '\\'    
> keyCode: 63
> which: 63

**Comment by marcolivierarsenault** [comment]
"[" on the Canadian french keyboard does not work

**Comment by fbilbao** [comment]
The same problem with an spanishLAT keyboard. [https://www.goodtyping.com/teclatLAT.png](url) Pressing AltGr+'  turn the cursor in a cross instead of write a backslash.

**Comment by bobocharbo** [comment]
I got the same problem on french keyboard, windows 7 pro, and jupyter  version 4.3.0.
I only tried in chrome thought.

**Comment by Birion** [comment]
I can confirm this problem on Czech QWERTY keyboard with "[". Exactly the same result as @fbilbao. Windows 10, jupyter 4.3.0, Chrome 58.0.3029.110 (64-bit).

**Comment by ruboerner** [comment]
I can confirm the "\" problem as well. Windows 10, Anaconda3, Chrome 58.0.3029.110 (64-bit).

Workaround: Prior to pressing AltGr-ß, type "´"!

**Comment by gnestor** [comment]
I just submitted [a PR](https://github.com/jupyter/notebook/pull/2535) that should fix this for both French and German keyboards. Since I don't have an English keyboard, I can't test myself, so I need someone here to help test.

```
git fetch jupyter pull/2535/head:pr/2535
git checkout pr/2535
npm run build
```

**Comment by gempel** [comment]
I tested the PR in a new environment and can confirm, that it works (German, \ problem).

**Comment by gnestor** [comment]
Can any Mac users confirm if <kbd>Cmd-Alt-[</kbd> or any other combination of <kbd>Cmd-Alt-*</kbd> is causing this issue?

**Comment by takluyver** [comment]
The change to fix it hasn't been released yet - we're aiming to make a 5.1 release this week which should have the fix in.

**Comment by habet700** [comment]
Ah, then sorry to bother you and i am looking forward to the release :)

**Comment by hroser** [comment]
Hi, should the 5.1 release already be available using "conda upgrade notebook"? I still get 5.0.0. I have the ALT+ key issue using a german keyboard. Thanks

**Comment by takluyver** [comment]
No, sorry, we're still trying to work out an issue some people have reported with the release candidates: #2747.

**Comment by matlabat** [comment]
Hi, 
I got the same issue too ("]" doesn't work)
I also have a french keyboard, windows 10, jupyter 4.3.0 with chrome.

**Comment by gnestor** [comment]
@matlabat https://github.com/jupyter/notebook/pull/2535 should fix this. Try installing the 5.1 release candidate and let us know if it resolves the issue for you: `pip install notebook --upgrade --no-deps --force-reinstall --pre`

**Comment by vberlier** [comment]
Thanks, I can now type "]" using french keyboard/windows 10/chrome

**Comment by gnestor** [comment]
@vberlier Excellent! Thanks for letting us know.

**Comment by ChristianTremblay** [comment]
How should I process with conda ? Using Anaconda I guess the version 5.1 is not part of the repo yet...

**Comment by blink1073** [comment]
It is available on conda-forge: `conda install -c conda-forge notebook`.

**Comment by ChristianTremblay** [comment]
Found out that `conda install -c conda-forge notebook` will make it.
I confirm it solves the problem on my side too (french canadian keyboard)

**Comment by fbilbao** [comment]
I confirm that `conda install -c conda-forge notebook` solve de Latam keyboard problem too.

**Comment by matlabat** [comment]
@gnestor : Sorry for the late. 
with 
`pip install notebook --upgrade --no-deps --force-reinstall --pre`
I confirm that it works perfectly now
Thanks a lot!

**Comment by NairolfS** [comment]
does this also work for jupyter lab?

**Comment by blink1073** [comment]
@NairolfS, coming soon: https://github.com/jupyterlab/jupyterlab/pull/3129

**Comment by kiranbaradur** [comment]
> Got the same issue with Jupyter (Anaconda 2) since last update 2 days ago
> on Google Chrome Version 57.0.2987.133 (64-bit)
> 
> French keyboard (and yes, it s indeed AltGr + ")", two keys left from backspace)
> 
> Doing ] with Alt+93 from now, but quite annoying.
> 
> Ask me anything if you want further informations to fix this

I am also facing issue that keyboard will stop working while using jupyter notebook.
Is there any solution to fix it...?
