### ISSUE TITLE
tooltip with shift-tab broken in 5.0.0

### ISSUE THREAD

**Issue by jbwhit** [jupyter/notebook#2383]
Shift-tab does not bring up the tooltip in 5.0.0 -- if I hold shift and hit tab 4 times I can, however, still get the bottom help screen to come up.

The version of the notebook server is 5.0.0 and is running on:

```
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]

Current Kernel Information:

Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

**Comment by wikiped** [comment]
I noted that it is actually shown just in the wrong place. Always at the very top of the page. I.e. if you press shift-tab and then scroll up by dragging side scrollbar or using mouse (without pressing ESC) you will see tooltip somewhere in the top part of the page. Which does not make it less of an issue, of course...

**Comment by jbwhit** [comment]
Good catch! I can confirm what @wikiped just said. The tooltip appears, but it's near the top of the page. I've reproduced this behavior on both Chrome and Firefox.

**Comment by gnestor** [comment]
It's working as expected for me on 5.0.0:

![](http://g.recordit.co/tEdojRKMel.gif)

Do you have any extensions installed (`jupyter nbextension list`)?

**Comment by jbwhit** [comment]
Can you do this in a lower cell and get the same behavior? 

```
$ jupyter nbextension list
Known nbextensions:
  config dir: /Users/jonathan/.jupyter/nbconfig
    notebook section
      collapsible_headings/main  enabled
      - Validating: OK
      codefolding/main  enabled
      - Validating: OK
      toc2/main disabled
      nbextensions_configurator/config_menu/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
  config dir: /Users/jonathan/miniconda3/envs/py3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
    tree section
      nb_conda/tree  enabled
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    tree section
      ipyparallel/main  enabled
      - Validating: OK
```

**Comment by jbwhit** [comment]
Here is what it looks like on my setup: 

![example](http://g.recordit.co/KyUQ5iuJdv.gif)

**Comment by Jessime** [comment]
As far as I can see, shift tab produces no result for me, anywhere on the screen.

My setup is:

notebook : 5.0.0
CPython : 2.7.13
IPython : 5.3.0
system : Linux
browser : Chrome

**Comment by gnestor** [comment]
It works as expected at the bottom of the page for me:

![](http://g.recordit.co/prjnjN5NAz.gif)

Try disabling one extension at a time (remember to restart the server after enabling/disabling extensions for it to take effect) and test whether that fixes your issue. I have a hunch that codefolding might be affecting it...

**Comment by Jessime** [comment]
@gnestor For me, the "Collapsible Headings" is both necessary and sufficient to cause the tooltip to quit showing up.

**Comment by wikiped** [comment]
Same here "Collapsable Headings" is causing the issue. And reading from the description of the extension:

  > <code>Tooltip._show</code> is patched to toggle the <code>div.cell { position:relative; }</code>
css rule of while the tooltip displays, as otherwise it interferes with the
tooltip's position-determining logic. Since this method is not part of the
public API (leading underscore), this may break in future, but it should
degrade in a non-catastrophic manner, with the result that the tooltip will
appear at the top of the notebook document, rather than where the cursor is
currently.

It seems clear why this is happening. Should have seen this earlier :-)
It would probably make sense to raise this issue in [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) as well.

**Comment by gnestor** [comment]
> It would probably make sense to raise this issue in jupyter_contrib_nbextensions as well.

Ya, close this one and open one there :+1:

**Comment by edurenye** [comment]
The version of the notebook server is: 5.7.8
I just have RISE installed using conda.
And the tooltip with shift-tab does not work.
