### ISSUE TITLE
Plots not rendering at all?

### ISSUE THREAD

**Issue by soamaven** [jupyter/notebook#2399]
I just upgraded to notbook 5, and mpl 2, and now my notebooks aren't display plots, just a little dot. Anyone have any clue what may be happening? Here is a screen shot:
![screenshot1](https://cloud.githubusercontent.com/assets/14949210/24932733/b84a04b6-1ec7-11e7-8566-ec57efd2496c.png)

**Comment by soamaven** [comment]
Its a firefox thing... probably one of my extensions. Closing.

**Comment by takluyver** [comment]
BTW, if you work out which extension, please leave a comment here - it might help someone else who one day has the same problem. Thanks!
