### ISSUE TITLE
problems starting notebook; doesn't see existing files and will not allow creation of new ones

### ISSUE THREAD

**Issue by doolingdavid** [jupyter/notebook#2400]
Out of nowhere today, when I start a new kernel / server
> jupyter notebook
a window opens up in the browser as usual, but none of the files are visible and I can't create a new one either.

I shut down my computer and updated anaconda and juypyter and tried again, but the problem persists.
I don't understand at all! I am using jupyter notebook version 4.4.1

**Comment by gnestor** [comment]
Are you seeing an notebook server errors in the terminal? Are you starting the server in the same directory as before? Can you try upgrading to notebook 5 to see if that helps?

**Comment by doolingdavid** [comment]
Thanks; I did some googling and realized something new: the authenticition / token feature. I cut and pasted as directed and. Is things work. I work in a health care environment so there is all kinds of encryption so I do not know if that is the culprit but I noticed that now with the new token methods of starting the server for the first time; it takes a few minutes for things to appear and run. But then it's as usual! Thanks .

**Comment by gnestor** [comment]
Ya, this was introduced with notebook 4.3.0 so that explains it! Here is some info about the token-based authentication: http://jupyter-notebook.readthedocs.io/en/latest/changelog.html#release-4-3

**Comment by takluyver** [comment]
If Jupyter opens the browser, it should automatically pass the token in for you. It's weird that that's apparently not happening.

**Comment by docian** [comment]
same problem for me...

**Comment by siebenbrunner** [comment]
I had this start happening yesterday as well. No files nor folders shown regardless of which directory I started the notebook in and couldn't open a new Notebook, pasting a token link didn't work for me either.

I found out the issue for me was I had to replace the tornado package with an older version for installing a different package. I updated tornado to the latest version, now everything is working again.

**Comment by ltalirz** [comment]
Just to add some more specifics: this occurs when using `notebook>=6`  with `tornado<5`

**Comment by maaarleila** [comment]
Had the same issue a few days ago. I couldn't see any folders or files. I tried to update Tornado first, then Anaconda completely. Even a new installation did not help. 

Solution for me: It was not a package or Anaconda itself, but the adblocker... (I use Opera version: 65.0.3467.78)

**Comment by Amberjay18** [comment]
maybe guys have a try to downgrade the notebook to 5.7.5 use commond:
pip install notebook==5.7.5

**Comment by olawaleibrahim** [comment]
Downgrading jupyter notebook worked for me. I used: conda install 'notebook<6'

**Comment by rallen10** [comment]
I can confirm, this still a problem with `notebook==6.0.3`. Using `conda install notebook<6` as recommended by @olawaleibrahim worked for (i.e. it installed version `5.7.10` which did not exhibit this issue)

**Comment by ogkdmr** [comment]
Just try conda update --all. Updating all the packages took less than 3 minutes and solved the problem for me. You should not need to downgrade your software to solve an issue.
