### ISSUE TITLE
How to access actions "properly"

### ISSUE THREAD

**Issue by louise-davies** [jupyter/notebook#2401]
I've been working on building an extension and I've noticed I've been consistently getting a warning from Jupyter:

`accessing "actions" on the global IPython/Jupyter is not recommended. Pass it to your objects contructors at creation time`

Yet the documentation for building frontend extensions, specifically the [part about registering custom actions](http://jupyter-notebook.readthedocs.io/en/latest/extending/frontend_extensions.html#defining-and-registering-your-own-actions),  accesses `actions` on the global `Jupyter` object like I've been doing. Is the documentation wrong, and if so what is the "proper" way to register a custom action; or can the warning be ignored?

**Comment by takluyver** [comment]
@Carreau , I'm not sure what's a good alternative to this?

**Comment by Carreau** [comment]
Meh, yes the documentation is out of date. I should fix that but haven't use this code in a while so need to dig into it. 

What is your extension doing ? Does it have access to a notebook instance ? If so grab the `notebook.keyboard_manager.actions` instance is cleaner as it remove some global state.

**Comment by louise-davies** [comment]
@Carreau

Ah, I didn't realise that you could access them via `notebook.keyboard_manager.actions`. I'll refactor my code to access it that way if that's cleaner - thanks!
