### ISSUE TITLE
custom.js no longer triggering on app_initialized.NotebookApp

### ISSUE THREAD

**Issue by andyneff** [jupyter/notebook#2403]
Using notebook 5.0.0, my custom.js files is no longer triggering app_initialized.NotebookApp. 

1. Add the following to `custom.js`

```javascript
define(['base/js/events'], function(events) {
    events.on('app_initialized.NotebookApp', function () {
        console.log('app_initialized.NotebookApp');
    });
});
```

2. Open a notebook and 'app_initialized.NotebookApp' is never logged. However, code outside the 'app_initialized.NotebookApp' callback will be called.

**Comment by AndreWin** [comment]
Hello!

I have a similar problem. My code has stoped to work in notebook 5.0.0:

```js
define([
    'base/js/namespace',
    'codemirror/keymap/sublime', // Это тоже js файл!
    'base/js/events'
    ], 
    function(IPython, sublime_keymap, events) {
        events.on("app_initialized.NotebookApp", 
            function () {
                console.log("Load settings for codemirror cells")
                var cell = require("notebook/js/cell").Cell;
                cell.options_default.cm_config.lineNumbers = true;
                cell.options_default.cm_config.keyMap = 'sublime';
                cell.options_default.cm_config.lineWrapping = true;
                cell.options_default.cm_config.autoCloseBrackets = true;
            }
        );
    }
);
```
How can I fix this?

**Comment by AndreWin** [comment]
Outside of `events.on()` my code will be run, but too late...

**Comment by takluyver** [comment]
We should really have a promise for one-time events like this, so you can easily have code that waits for it, without worrying whether it already fired.

**Comment by scott-vsi** [comment]
Is there any workaround for this issue?

**Comment by takluyver** [comment]
This is kind-of fixed by #2710 (coming in notebook 5.1). The idea is that code that was previously using the `app_initialized` event can now use a promise instead:

```javascript
define([
        'base/js/namespace',
        'base/js/promises'
     ], function(Jupyter, promises) {
         promises.app_initialized.then(function(appname) {
             if (appname === 'NotebookApp') {
                 do_stuff()
             }
         });
     });
```

Unlike events, if the promise has already been resolved before you do this, then your code is run immediately. With events, it sits waiting for the event to fire again, which this one never does.

I think that's as solved as this is likely to get, so I'm going to close the issue.

**Comment by didiercrunch** [comment]
It would be nice to update the documentation: https://github.com/jupyter/notebook/blob/4.0.x/notebook/static/custom/custom.js

**Comment by jason-s** [comment]
Is there a workaround for Jupyter 5.0?

**Comment by takluyver** [comment]
It definitely should have newer versions that 5.0; we're up to 5.4.1 now, and Anaconda usually packages a new version within a few days of a release.
