### ISSUE TITLE
Difference when running notebook from console and shortcut.

### ISSUE THREAD

**Issue by AC130USpectre** [jupyter/notebook#2405]
Hi. I'am using Win 10, anaconda with mainly installed python3. However, I have environment with python 2.7. Inside this environment I have Jupyter notebook also. I want to use theano inside notebook. When I run Jupyter using shortcut (which executes this: `D:\Anaconda3\envs\python2\python.exe D:\Anaconda3\cwp.py D:\Anaconda3\envs\python2 "D:/Anaconda3/envs/python2/python.exe" "D:/Anaconda3/envs/python2/Scripts/jupyter-notebook-script.py"`) I cannot use theano cause `import theano` leads to some errors. But when I use console, switch to the environment with _python2_ and use command `jupyter notebook` from console, everything works good. Please, explain the difference between these two methods. I asked similar question to theano group, but for now it seems like the problem not in theano (as it works good when I use usual python console or even ipython console).

**Comment by takluyver** [comment]
I think you might be better off asking in an Anaconda forum - I don't know what their cwp script does, for instance. You could also try comparing environment variables (`os.environ`) between the case where it works and the case where it doesn't.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
