### ISSUE TITLE
Jupyter not working under nohup after connection is closed

### ISSUE THREAD

**Issue by martinosorb** [jupyter/notebook#2406]
I'm trying to leave a notebook server running on a remote machine. `nohup jupyter notebook` does work, but as soon as I close the connection, jupyter becomes unable to read from disk, so only shows blank screens on the browser, even if the server is running. The error message reads:

```
    PermissionError: [Errno 13] Permission denied: '[my home directory]/.local/lib/python3.4/site-packages/notebook/tree.html'
```

I suspect this is because of AFS, the remote machine stops talking to the AFS when I logout, so it can't access my home directory, even if the notebooks are indeed available, being on the local disk.

Is there any workaround, or can I only install jupyter on the local disk through virtualenv?

**Comment by takluyver** [comment]
No workaround comes to mind; Jupyter does need access to its own install directory as it runs, so if that gets cut off...

Maybe there's a way to trick the machine into thinking you're always logged in so that it keeps your files accessible.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
