### ISSUE TITLE
jupyter trust command not working correctly

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyter/notebook#2407]
First I am going to describe my setup, since it is a bit complex.

I got a complex notebook, with many extensions inside an Anaconda environment. For example and importantly the initialization cells. The notebook also contains initialization cells. Those initialization cells provide Python functions for displaying things, which will be used later on in the notebook. I also got the extension for hidden cells, since I want the user to focus on the actual matter, rather than the details of how I rendered a PDF in a notebook cell for example. Of course I am aware, that the user could simply unhide the cells and look at that, if they wanted to. It is not about really making things disappear, but rather about not cluttering up the notebook from the user's perspective. It might be, that in the future I can use a backend extension to provide these Python functions, so that it is completely out of the notebook. Anyway, at the moment the initialization cells are in the concept.

To share the notebook with people, I want to put it into a Docker container and deploy that on a server somewhere. In my local attempts and tests, it turns out, that the notebook is not trusted (for a user accessing it on `localhost:8888`), when I run it inside the Docker container. I searched around a bit and figured, that this makes sense, since the user inside the Docker container is not the same as the user on the host machine, for whom the notebook is trusted.

In order to solve this, I found the command `jupyter trust notebook.ipynb` in the [documentation](https://jupyter-notebook.readthedocs.io/en/latest/security.html#explicit-trust). This I add to the Dockerfile creating the Docker image for the container. It runs without errors.

Now the actual problem. When I then run the notebook as a Docker container and open the notebook from the tree view, I get the following message:

![screenshot_2017-04-13_12-50-06](https://cloud.githubusercontent.com/assets/11130348/25002363/52ee2366-204a-11e7-9fe8-31de07b03f42.png)

So to me it seems now, that the `jupyter trust` command did something wrong inside the notebook file. Or rather wrong according to the 5.0.0 specifications or assumptions about the notebook files. So I checked which versions of the parts I got installed in my Anaconda environment inside the Docker container:

    # packages in environment at /opt/conda:
    #
    blas                      1.1                    openblas    conda-forge
    bleach                    1.5.0                    py36_0    conda-forge
    cffi                      1.9.1                    py36_0  
    conda                     4.3.11                   py36_0  
    conda-env                 2.6.0                         0  
    cryptography              1.7.1                    py36_0  
    cycler                    0.10.0                   py36_0    conda-forge
    dbus                      1.10.10                       3    conda-forge
    decorator                 4.0.11                   py36_0    conda-forge
    entrypoints               0.2.2                    py36_1    conda-forge
    expat                     2.1.0                         2    conda-forge
    fontconfig                2.12.1                        4    conda-forge
    freetype                  2.7                           1    conda-forge
    gettext                   0.19.7                        1    conda-forge
    glib                      2.51.4                        0    conda-forge
    gmp                       6.1.2                         0    conda-forge
    gst-plugins-base          1.8.0                         0    conda-forge
    gstreamer                 1.8.0                         1    conda-forge
    html5lib                  0.999                    py36_0    conda-forge
    icu                       58.1                          1    conda-forge
    idna                      2.2                      py36_0  
    ipykernel                 4.6.1                    py36_0    conda-forge
    ipython                   5.3.0                    py36_0    conda-forge
    ipython_genutils          0.2.0                    py36_0    conda-forge
    ipywidgets                6.0.0                    py36_0    conda-forge
    jinja2                    2.9.5                    py36_0    conda-forge
    jpeg                      9b                            0    conda-forge
    jsonschema                2.5.1                    py36_0    conda-forge
    jupyter                   1.0.0                    py36_0    conda-forge
    jupyter_client            5.0.1                    py36_0    conda-forge
    jupyter_console           5.1.0                    py36_0    conda-forge
    jupyter_contrib_core      0.3.0                    py36_1    conda-forge
    jupyter_contrib_nbextensions 0.2.6                    py36_0    conda-forge
    jupyter_core              4.3.0                    py36_0    conda-forge
    jupyter_highlight_selected_word 0.0.11                   py36_0    conda-forge
    jupyter_latex_envs        1.3.8.2                  py36_1    conda-forge
    jupyter_nbextensions_configurator 0.2.4                    py36_0    conda-forge
    libffi                    3.2.1                         1  
    libgfortran               3.0.0                         1  
    libiconv                  1.14                          4    conda-forge
    libpng                    1.6.28                        0    conda-forge
    libsodium                 1.0.10                        0    conda-forge
    libxcb                    1.12                          1    conda-forge
    libxml2                   2.9.4                         4    conda-forge
    markupsafe                0.23                     py36_1    conda-forge
    matplotlib                2.0.0               np112py36_3    conda-forge
    mistune                   0.7.4                    py36_0    conda-forge
    nbconvert                 5.1.1                    py36_1    conda-forge
    nbformat                  4.2.0                    py36_0    conda-forge
    notebook                  5.0.0                    py36_0    conda-forge
    numpy                     1.12.1          py36_blas_openblas_200  [blas_openblas]  conda-forge
    openblas                  0.2.19                        1    conda-forge
    openssl                   1.0.2k                        0  
    pandas                    0.19.2              np112py36_1    conda-forge
    pandoc                    1.19.2                        0    conda-forge
    pandocfilters             1.4.1                    py36_0    conda-forge
    pcre                      8.39                          0    conda-forge
    pexpect                   4.2.1                    py36_0    conda-forge
    pickleshare               0.7.3                    py36_0    conda-forge
    pip                       9.0.1                    py36_1  
    prompt_toolkit            1.0.14                   py36_0    conda-forge
    psutil                    5.2.1                    py36_0    conda-forge
    ptyprocess                0.5.1                    py36_0    conda-forge
    pyasn1                    0.1.9                    py36_0  
    pycosat                   0.6.1                    py36_1  
    pycparser                 2.17                     py36_0  
    pydotplus                 2.0.2                    py36_0    conda-forge
    pygments                  2.2.0                    py36_0    conda-forge
    pyopenssl                 16.2.0                   py36_0  
    pyparsing                 2.2.0                    py36_0    conda-forge
    pyqt                      5.6.0                    py36_0    conda-forge
    python                    3.6.0                         0  
    python-dateutil           2.6.0                    py36_0    conda-forge
    pytz                      2017.2                   py36_0    conda-forge
    pyyaml                    3.12                     py36_1    conda-forge
    pyzmq                     16.0.2                   py36_1    conda-forge
    qt                        5.6.2                         1    conda-forge
    qtconsole                 4.3.0                    py36_0    conda-forge
    readline                  6.2                           2  
    requests                  2.12.4                   py36_0  
    ruamel_yaml               0.11.14                  py36_1  
    scikit-learn              0.18.1          np112py36_blas_openblas_200  [blas_openblas]  conda-forge
    scipy                     0.19.0          np112py36_blas_openblas_200  [blas_openblas]  conda-forge
    setuptools                27.2.0                   py36_0  
    simplegeneric             0.8.1                    py36_0    conda-forge
    sip                       4.18                     py36_1    conda-forge
    six                       1.10.0                   py36_0  
    sqlite                    3.13.0                        0  
    terminado                 0.6                      py36_0    conda-forge
    testpath                  0.3                      py36_0    conda-forge
    tk                        8.5.18                        0  
    tornado                   4.4.3                    py36_0    conda-forge
    traitlets                 4.3.2                    py36_0    conda-forge
    wcwidth                   0.1.7                    py36_0    conda-forge
    webencodings              0.5                      py36_0    conda-forge
    wheel                     0.29.0                   py36_0  
    widgetsnbextension        2.0.0                    py36_0    conda-forge
    xorg-libxau               1.0.8                         3    conda-forge
    xorg-libxdmcp             1.1.2                         3    conda-forge
    xz                        5.2.2                         1  
    yaml                      0.1.6                         0  
    zeromq                    4.2.1                         1    conda-forge
    zlib                      1.2.8                         3  

I'll strip this of all probably unrelated libraries and just keep the jupyter stuff or the things I think are related with the problem:

    ipywidgets                        6.0.0                    py36_0    conda-forge
    jupyter                           1.0.0                    py36_0    conda-forge
    jupyter_client                    5.0.1                    py36_0    conda-forge
    jupyter_console                   5.1.0                    py36_0    conda-forge
    jupyter_contrib_core              0.3.0                    py36_1    conda-forge
    jupyter_contrib_nbextensions      0.2.6                    py36_0    conda-forge
    jupyter_core                      4.3.0                    py36_0    conda-forge
    jupyter_highlight_selected_word   0.0.11                   py36_0    conda-forge
    jupyter_latex_envs                1.3.8.2                  py36_1    conda-forge
    jupyter_nbextensions_configurator 0.2.4                    py36_0    conda-forge
    nbconvert                         5.1.1                    py36_1    conda-forge
    nbformat                          4.2.0                    py36_0    conda-forge
    notebook                          5.0.0                    py36_0    conda-forge
    widgetsnbextension                2.0.0                    py36_0    conda-forge

The command used to install them all is in the Dockerfile and is:

    RUN conda install -c conda-forge --yes --quiet \
     jupyter \
     ipywidgets \
     pandas \
     scikit-learn \
     matplotlib \
     numpy \
     pydotplus \
     jupyter_contrib_nbextensions \
     && conda clean -tips --yes

The only thing being version "4+something" in the libraries are `jupyter_core` and `nbformat`. One of these is probably responsible for the error.

Could it be that one of them provides the `jupyter trust` command and that that is not up to date yet with notebooks in version 5 and that this is, why it did mess up the notebook format?

Do I need to use a different way of installing libraries and the notebook in my Anaconda env, to work around this problem? Maybe specifying a development/beta version of some jupyter related library?

Alternatively: Is it a better approach in this case to copy the `nbsignatures.db` and `notebook_secret` to inside the Docker container instead of using the `jupyter trust` command? Where exactly would I need to copy them? I think it would have to be `/home/user/.local/share/jupyter/` + `nbsignatures.db` and `notebook_secret`.

Note: When I do not run the `jupyter trust` command, the notebook will load fine, only that it says that there are initialization cells in an untrusted notebook, sort of forcing the users to run them themselves, which would lead to unnecessary distraction.

**Comment by takluyver** [comment]
The latest nbformat is 4.3 - I'm not quite sure why it's giving you 4.2. I don't remember any bug like that before, though. Is the notebook something you're willing to share? Can you give us a copy (e.g. in a gist) of the file after it gets corrupted?

**Comment by ZelphirKaltstahl** [comment]
@takluyver I'd rather not share it yet. It will be shared later for free and everyone (once it is working and deployed on a server and so on), who wants to test it and I'll need test users, but that is later and it is still in the development late phase. It will be used to get some test results for a master thesis, and I am not so sure about testing principles and how sharing early could affect testing results or the number of test users I will find.

I now put into my `jupyter_notebook_config.py` the following additional lines:

    c.NotebookNotary.data_dir = "/home/" + os.getenv('NB_USER') + "/.local/share/jupyter/"
    c.NotebookNotary.db_file = "/home/" + os.getenv('NB_USER') + "/.local/share/jupyter/nbsignatures.db"
    c.NotebookNotary.secret_file = "/home/" + os.getenv('NB_USER') + "/.local/share/jupyter/notebook_secret"

And copied my files into the container instead of running the `jupyter trust` command. So far it did not work, but it might be I copied not up to date files in. In the process I destroyed my Anaconda env somehow, so I'll have to recreate it and then see where it creates these signature and secret files, in order to test again if I can go that route. However, the trust command would be better, since it involves no manual steps in the process, except once writing it into the Dockerfile.

Maybe I can manually install `nbformat 4.3`? I might try it once I get my env up again, thanks for mentioning, that there is a newer version, maybe that will be the key later.

**Comment by ZelphirKaltstahl** [comment]
I've got an idea for why it might give me version `4.2` of `nbformat`: Maybe it is because I am using Python 3.6?

**Comment by ZelphirKaltstahl** [comment]
After recreating the Anaconda environment with the dependencies installed, I simply tried to `conda upgrade nbformat` and indeed, it gives me the possibility to upgrade to `4.3.0-py36_0`. So I'll try that in the Dockerfile and see how it goes then.

**Comment by ZelphirKaltstahl** [comment]
@takluyver It works! It seems it was really about a version issue. I have no idea either, why the conda command initially offers `nbformat 4.2.0` but an additional `conda upgrade` in the Dockerfile, plus using the `jupyter trust` command did the trick. Thanks for again great support and pinpointing the issue!

**Comment by takluyver** [comment]
Great, glad it's working.
