### ISSUE TITLE
Paste menu items do not trigger paste actions 

### ISSUE THREAD

**Issue by acrule** [jupyter/notebook#2415]
I'm building an extension that listens for actions in the notebook so I track how notebooks are used and evolve over time.

One of the actions I listen for is `paste-cell-below`. This action is triggered when the user hits the paste button in the toolbar, but not when they select the "Paste Cell Below" item in the Edit menu. I believe this is due to the `enable_paste` function on [line 1566 of Notebook.js](https://github.com/jupyter/notebook/blob/f5f2eadd923f689336345ecacfdfd2592685a8e0/notebook/static/notebook/js/notebook.js#L1566) which links the menu items directly to functions. I think this may need to set each of the onclicks to call the relevant action (which will in turn call the function) rather than call the paste functions directly.

**Comment by takluyver** [comment]
Sounds reasonable if you want to make a PR.
