### ISSUE TITLE
Failure to authenticate API endpoints should raise 403 instead of redirect

### ISSUE THREAD

**Issue by minrk** [jupyter/notebook#2428]
Tornado's `@web.authenticated` redirects to `login_url` on failed authentication, but this isn't appropriate for the REST API. We should be raising a simple 403 instead of redirecting.

**Comment by edmundhenley-mo** [comment]
Hi @minrk - found this when digging into https://github.com/jupyter/nbdime/issues/749.
In case useful (sorry for noise if not!), has this been superseded by https://github.com/jupyter-server/jupyter_server/pull/1392 ?

**Comment by minrk** [comment]
I _think_ it hasn't, but it does get part way there.

**Comment by minrk** [comment]
ha, this was fixed by #2853 ... 7 years ago.
