### ISSUE TITLE
View .html in Jupyter

### ISSUE THREAD

**Issue by shannonekj** [jupyter/notebook#2436]
I have an .html file and when I click the <file>.html it goes into edit mode in the notebook. 

What I want is to view  http://localhost:8000/files/work/index.html (see **files**)
and what I get is to edit 
http://localhost:8000/edit/work/index.html (see **edit**)

Is there a way to make this a feature of the Jupyter notebook Files interface?

**Comment by takluyver** [comment]
If you have notebook version 5.0, when you select a notebook in the files list, there should be a *View* button at the top of the list.
