### ISSUE TITLE
White box at top of Jupyter notebook when scrolling

### ISSUE THREAD

**Issue by NickMcNutt** [jupyter/notebook#2437]
This issue seems to be new with v5 of the notebook.  Scrolling behavior doesn't seem to be as smooth as it previously was (there is a bit of a lag) and there is also a white box that jitters at the top of the screen.  The faster I scroll, the greater the height of the box.  I have tested this on multiple computers to make sure it is not just mine.

I have included a screenshot to demonstrate the problem:

[http://imgur.com/a/7Gz9Q](http://imgur.com/a/7Gz9Q)

**Comment by takluyver** [comment]
That doesn't look like the standard notebook. Do you have some custom theme? Or is the Julia kernel restyling the page? Or something else.

**Comment by Carreau** [comment]
I've seen in on Chrome (some time ago). It's the browser that have difficulty following and repainting. AFAICT it's a browser bug/limitation.

**Comment by NickMcNutt** [comment]
I removed the custom theme (I was using jupyter-themes) and found that the problem mostly disappeared but was still present when scrolling quickly enough.  So then I switched browsers to Safari and the problem is completely gone.  It must be a Chrome rendering issue (a rather bad one at that).  I would say close this issue.  Thanks!

**Comment by takluyver** [comment]
Thanks for the follow up :-)

**Comment by Carreau** [comment]
If you can share your custom theme it is likely to be something that changes the the `display: .... ` of somethings. You can try to enable [paint rectangles](https://developer.chrome.com/devtools/docs/rendering-settings) on Chrome to see what's the bottleneck.
