### ISSUE TITLE
Notebook not printing intermediate values

### ISSUE THREAD

**Issue by pylang** [jupyter/notebook#2441]
I run the following code in ipython and get the expected result, a printed countdown of numbers and a final message:

```python
import time
import random

def countdown(s):
    """Print the remaining seconds."""
    while s:
        print("{}".format(s), end="\r")
        time.sleep(1)
        s -= 1

def run(s=5):
    """Return a winner from a pool given."""
    countdown(s)
    print("Done")
    

run()
# 4 3 2 1 Done
```

In the notebook for `ipykernel` > 4.2.2, the cell hangs until `'Done'` is printed without intermediate numbers.  I do not notice any output to the console as suggested in #111.

**Comment by takluyver** [comment]
Can you try adding `flush=True` to your print call?

Running your code (without that addition), I do see the intermediate values printed in the notebook, using master of ipykernel and notebook.

**Comment by gnestor** [comment]
I can also confirm that your code is working as expected in notebook 5.0.0 with ipykernel 4.3.1.

**Comment by pylang** [comment]
`flush=True` ensures that the intermediates do NOT print.

All but my newest kernel presents this issue.   I'll close it for now until I have time to run tests in an isolated environment.  Thanks for the confirmation.
