### ISSUE TITLE
Shift + Tab no longer extending the documentation

### ISSUE THREAD

**Issue by HintikkaKimmo** [jupyter/notebook#2443]
I just updated Jupiter notebook to the newest conda version and encountered an issue that is a bit annoying when working in small screen. 

Earlier versions you could open method documentation with shift + Tab in mac and hit it 3 times,  It would extend to cover the whole lower screen. The command is referred as a tooltip in docs. 
⇧⇥ : tooltip

Seems that now shift + tab no longer does this but + icon with the mouse still works. I would hope shift + tab functionality could be brought back, or is there a way to adjust the keys on my own profile? 

Conda Jupiter version info. 

jupyter                   1.0.0                    py36_3
jupyter_client            5.0.1                    py36_0
jupyter_console           5.1.0                    py36_0
jupyter_contrib_core      0.3.0                    py36_1    conda-forge
jupyter_contrib_nbextensions 0.2.4                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0
jupyter_highlight_selected_word 0.0.7                    py36_0    conda-forge
jupyter_latex_envs        1.3.7.1                  py36_1    conda-forge
jupyter_nbextensions_configurator 0.2.3                    py36_0    conda-forge

**Comment by takluyver** [comment]
Hitting shift-tab multiple times still works for me in the latest version.

1. Open tooltip
2. Expand tooltip
3. Make tooltip 'sticky' while you type for a few seconds
4. Move to pager

**Comment by HintikkaKimmo** [comment]
Seems like turning it on and off again did the trick again. Closing this one
