### ISSUE TITLE
Remove utils functions existing in codemirror.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#245]
These [two](https://github.com/jupyter/notebook/blob/master/notebook/static/base/js/utils.js#L492-L528) utils functions seem to exist [in codemirror](https://github.com/codemirror/CodeMirror/blob/master/lib/codemirror.js#L7572-L7590) 

I guess they are more reliable.

**Comment by takluyver** [comment]
Because the line numbers on master are liable to change: the functions in our code are `{to,from}_absolute_cursor_position`, and in CodeMirror, `posFromIndex` and `indexFromPos`. +1 to removing ours if we can.

**Comment by minrk** [comment]
:+1: to removing our own implementations if they are redundant.
