### ISSUE TITLE
adding syntax highlighting for CodeMirror-supported language to notebook cell magic

### ISSUE THREAD

**Issue by lebedov** [jupyter/notebook#2453]
I'm trying to activate syntax highlighting for one of the languages supported by CodeMirror in a custom magic provided by an extension. The magic is not associated with a new language kernel; it just sends the entered text to some Python code that passes it through an interface to another package that processes it. It seems like folks [have managed to get this to work](http://stackoverflow.com/questions/43641362/adding-syntax-highlighting-to-jupyter-notebook-cell-magic) for older versions of the notebook; however, that approach doesn't seem to work for notebook 5.0. How would one go about doing so for the newer version?

**Comment by takluyver** [comment]
I've put a comment on the SO post - try using `options_default` in the code in place of `config_defaults`.

**Comment by lebedov** [comment]
@takluyver - modifying the JS as indicated doesn't seem to have any different effect, i.e., the color of the sql code I enter on the line after typing `%%sql` remains the same as if I entered it into a new cell alone.

**Comment by takluyver** [comment]
Any error messages in the JS console when you do this?

**Comment by takluyver** [comment]
The modified code from the SO answer appears to work for me:

```javascript
IPython.CodeCell.options_default.highlight_modes['magic_text/x-mssql'] = {'reg':[/^%%sql/]} ;
console.log('AAAAA');
IPython.notebook.events.one('kernel_ready.Kernel', function(){
    console.log('BBBBB');
    IPython.notebook.get_cells().map(function(cell){
        if (cell.cell_type == 'code'){ cell.auto_highlight(); } }) ;
});
```

(You could also now replace `IPython` with `Jupyter` throughout that code - `IPython` still works as an alias for now.

**Comment by takluyver** [comment]
![screenshot from 2017-04-28 15-51-42](https://cloud.githubusercontent.com/assets/327925/25534062/9c745abe-2c2a-11e7-8f8d-0121a47119e1.png)

**Comment by lebedov** [comment]
I see the following error in the console associated with `custom.js`:
```
TypeError: IPython.CodeCell is undefined
```
Apart from notebook 5.0.0, are there any other minimum versions of other Jupyter-related packages I ought to have installed?

**Comment by takluyver** [comment]
Try making the code like this:

```javascript
require(['notebook/js/codecell'], function(codecell) {
  codecell.CodeCell.options_default.highlight_modes['magic_text/x-mssql'] = {'reg':[/^%%sql/]} ;
  console.log('AAAAA');
  Jupyter.notebook.events.one('kernel_ready.Kernel', function(){
      console.log('BBBBB');
      Jupyter.notebook.get_cells().map(function(cell){
          if (cell.cell_type == 'code'){ cell.auto_highlight(); } }) ;
  });
});
```

I don't think any other packages are relevant to this.

**Comment by lebedov** [comment]
That did it the trick! The error is gone and the syntax appears to be adjusted within the magic:
![screen shot 2017-04-28 at 11 10 17 am](https://cloud.githubusercontent.com/assets/218546/25534851/2b45c43a-2c03-11e7-8d28-82edefc97c5e.png)

**Comment by takluyver** [comment]
Great :-). I'll close this issue. Feel free to add a new answer to SO with the modified code as well.

**Comment by lebedov** [comment]
Thanks, @takluyver!

**Comment by lebedov** [comment]
When I tried running the above JS code within the constructor of the class that defines my magic (via `IPython.core.display.display_javascript(js, raw=True)`), I see the AAAAA in the console after loading the extension containing the magic, but not the BBBBB when I enter %%sql followed by sql code. Should there be any difference in the code if I only wish to run it when an extension is loaded?

**Comment by takluyver** [comment]
The `kernel_ready.Kernel` event may already have fired before your extension loads, so you may need to take the code out of that.
