### ISSUE TITLE
Terminal does not understand tab/arrow keys inside docker

### ISSUE THREAD

**Issue by yebrahim** [jupyter/notebook#2457]
I run Jupyter inside docker. When I open a terminal window in Jupyter in this case, pressing Tab sends the cursor to the next tab stop immediately instead of performing autocomplete. Also arrow keys just print values like `^[[A` instead of actually moving cursor, or showing command history.

I'm not sure if this is a Jupyter or xterm.js issue, does anyone know what's causing this? It only happens inside docker (tried both `ubuntu` and `debian` images).

**Comment by takluyver** [comment]
The symptoms you describe sound like it's running a plain `sh` instead of `bash`. `sh` is the default shell if the $SHELL environment does not point to something else.

**Comment by yebrahim** [comment]
`$SHELL` is set to `/bin/bash` in the container though.

**Comment by takluyver** [comment]
I'm not sure, then. Certainly those symptoms sound like a shell that's not using readline.

**Comment by yebrahim** [comment]
You're right actually. Even though doing `echo $SHELL` inside the container gives me `/bin/bash`, doing it inside the Jupyter terminal shows it's unassigned, thus the dumb behavior.

Can Jupyter execute `export SHELL=/bin/bash` for new terminals?

**Comment by takluyver** [comment]
Jupyter is using the `SHELL` environment variable to pick the shell to start, so you'd need to set that before starting Jupyter. Alternatively, the `NotebookApp.terminado_settings` config option can override it.

**Comment by yebrahim** [comment]
Thanks for the pointer, I fixed the issue by explicitly setting the `SHELL` env var to `/bin/bash` as part of the Dockerfile.
Closing this one.

**Comment by Febin-kg** [comment]
@yebrahim - Could you please tell me how you did it ?
I've set the shell ENV variable in my Dockerfile to point to /bin/bash.
However, when i `docker exec -it container_id sh`, it still is sh which is being loaded. The tab isn't 
being recognised.
echo $SHELL does give me the output as /bin/bash.
I can alternately perform `docker exec -it container_id /bin/bash`, but I'm trying to default the shell to /bin/bash

**Comment by changec** [comment]
I use the tensorflow/tensorflow image to open the jupyter,but the default terminal was sh.
can you tell me how to rewrite the dockerfile?
I want to open the bash terminal,thank you.

**Comment by nithincninan** [comment]
Added environmental path 

- [ ] SHELL=/bin/bash

 in windows and the issue is resolved.

![Add-Sell-Env-variable](https://user-images.githubusercontent.com/2525741/54068452-de03b280-4272-11e9-9bd4-1cac365dac11.png)
