### ISSUE TITLE
can't activate cypher mode in notebook cell

### ISSUE THREAD

**Issue by lebedov** [jupyter/notebook#2462]
As per https://github.com/jupyter/notebook/issues/2453, I tried activating CodeMirror's cypher mode syntax highlighting in cells starting with `%%cypher` using the following `~/.jupter/custom/custom.js`:
```javascript
require(['notebook/js/codecell'], function(codecell) {
  codecell.CodeCell.options_default.highlight_modes['magic_application/x-cypher-query'] = {'reg':[/^%%cypher/]} ;
  console.log('AAAAA');
  Jupyter.notebook.events.one('kernel_ready.Kernel', function(){
      console.log('BBBBB');
      Jupyter.notebook.get_cells().map(function(cell){
          if (cell.cell_type == 'code'){ cell.auto_highlight(); } }) ;
  });
});
```
Although the JS is evidently executed (judging by the console log), it doesn't appear to have any effect:
<img width="693" alt="screen shot 2017-04-30 at 2 17 41 pm" src="https://cloud.githubusercontent.com/assets/218546/25566846/235789d0-2db0-11e7-87c1-b7ae6629b9f8.png">

Any thoughts why? I'm using notebook 5.0.0.

**Comment by takluyver** [comment]
It looks like it's already highlighting some sort of query language - is that based on the kernel in use, or is there another bit of JS affecting highlighting? Is there anything in frontend config (`~/.jupyter/nbconfig/notebook.json`)?

**Comment by lebedov** [comment]
Aha - this was in `~/.jupyter/nbconfig/notebook.json`, so cypher mode for `%%cypher` cells was already being activated regardless of whether I loaded my extension:
```javascript
{
  "CodeCell": {
    "highlight_modes": {
      "magic_application/x-cypher-query": {
        "reg": "^%%cypher"
      }
    }
  }
}
```
Thanks!
