### ISSUE TITLE
Conda Env, TensorFlow, Bad config encountered during initialization

### ISSUE THREAD

**Issue by timjim333** [jupyter/notebook#2463]
Hi,

I'm having trouble running a Jupyter notebook when I have activated a Conda environment (for TensorFlow) under Windows 10. It starts up fine when the TensorFlow env is not activated. I should add that I have also installed GoogleDrive Integration - I'm not sure if this is the problem though. The error message I get when I try to run `jupyter notebook`, after all the boilerplate, is the following:

[C 11:56:00.251 NotebookApp] Bad config encountered during initialization:
[C 11:56:00.251 NotebookApp] The 'contents_manager_class' trait of <notebook.notebookapp.NotebookApp object at 0x000001EC4AE9AB38> instance must be a type, but 'jupyterdrive.clientsidenbmanager.ClientSideContentsManager' could not be imported

Have I made a mistake with my setup? Thanks for the thoughts.

**Comment by takluyver** [comment]
Your jupyter config is pointing to the GoogleDrive integration, but it's not installed inside the env. You could:

- [Install a kernelspec](http://ipython.readthedocs.io/en/stable/install/kernel_install.html) for the Tensorflow env, and then run the notebook outside the env, pointing it to the kernel in the env.
- Install jupyterdrive inside the env
- Remove the config (disabling the GoogleDrive integration).

**Comment by timjim333** [comment]
Hi, thanks for your advice. As I'd like to keep my Google Drive integration, I will try your first two suggestions.  I attempted to follow the instructions you linked for a kernelspec however, I was unsure of the following line:
`/path/to/kernel/env/bin/python -m ipykernel install --prefix=/path/to/jupyter/env --name 'python-my-env'`

For the paths above, which python and which jupyter env should I be pointing at? Jupyter is working under the root env but not for my created tensorflow env. If it helps to clarify, I have pasted the paths I get from running `jupyter --paths` under each env below. Thanks.

**For the root env**
config:
    C:\Users\timmy\.jupyter
    C:\ProgramData\Anaconda3\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\timmy\AppData\Roaming\jupyter
    C:\ProgramData\Anaconda3\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\timmy\AppData\Roaming\jupyter\runtime

**For the tensorflow env**
config:
    C:\Users\timmy\.jupyter
    C:\ProgramData\Anaconda3\envs\tensorflow\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\timmy\AppData\Roaming\jupyter
    C:\ProgramData\Anaconda3\envs\tensorflow\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\timmy\AppData\Roaming\jupyter\runtime

**Comment by takluyver** [comment]
> For the paths above, which python and which jupyter env should I be pointing at?

It should be like this

```
/path/to/anaconda/envs/tensorflow/bin/python -m ipykernel install --prefix=/path/to/anaconda --name="tensorflow env"
```

Then launch Jupyter *without* activating the tensorflow env, and the 'New' menu should give you an option to create a new notebook using Python in the tensorflow env. You can also open existing notebooks and switch the kernel to the tensorflow env.

**Comment by timjim333** [comment]
Ok, I didn't realise that you needed to start it from outside of the environment. Thanks. As it turns out, something I tried earlier also managed to install the kernel it seems, and I can see it in the dropdown list.

Just out of interest, I also gave the command you posted a go to create another kernel in that env with a different name. This also produced another option in the Juypter notebook page, but interestingly, I could no longer import the modules I installed in that environment. For future reference, can I confirm that the prefix path is just to anaconda and no the env itself?

How should I remove a kernel I no longer need? Thanks again.

**Comment by takluyver** [comment]
> For future reference, can I confirm that the prefix path is just to anaconda and no the env itself?

Yep. The first path (`.../bin/python`) is where the kernel will run. The prefix path is to the Python where you want to launch Jupyter: it will add info in that prefix to allow it to find the kernel. In this case, that's your Anaconda root environment.

> How should I remove a kernel I no longer need? Thanks again.

At the moment, just remove the kernelspec directory. You can see the location by running `jupyter kernelspec list`.
