### ISSUE TITLE
how to disable the jupyter notebook server auth token and enable password

### ISSUE THREAD

**Issue by jdhao** [jupyter/notebook#2466]
## Problem description
I am using jupyter notebook in the Pycharm community edition. I found that each time, when I want to run an newly opened notebook, I have to manually enter an auth token once. I have read the issue #1944 , #1979  and the [official documentation](http://jupyter-notebook.readthedocs.io/en/latest/security.html) and know that this behavior is intended for security. I enabled password  by setting `c.NotebookApp.password_required = True  ` in  file jupyter_notebook_config.py and set a password according to the documentation. But when I run a newly opened notebook again in Pycharm, I still need to enter an auth token. 
What am I doing wrong here? Can you give an official guide on the exact steps.

## Version info
- jupyter notebook: 5.0.0
- Pycharm: Community Edition 2017.1.2

**Comment by takluyver** [comment]
I don't know how PyCharm's interface with Jupyter works - you might need to ask JetBrains what it's doing. I didn't think it used our server at all.

For our interface, setting a password in the config file should be enough to remove the need for a token.

**Comment by acerock6** [comment]
I tried setting a password in the config JSON file but when I input the password and click on Log In, its does not prompt anything!
