### ISSUE TITLE
The upload button doesn't work as expected

### ISSUE THREAD

**Issue by mpolacec** [jupyter/notebook#2474]
*STR:*
Press the upload button and select a file.
Press Cancel button
Press the upload button and select the same file

*Expected result(s):*
The upload and cancel buttons should be displayed.
*Actual result(s):*
Nothing happens, the upload and cancel buttons are not displayed.

jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
