### ISSUE TITLE
Incorrect error message displayed when saving a file with blank name

### ISSUE THREAD

**Issue by mpolacec** [jupyter/notebook#2475]
*STR:*
Navigate to gallery folder
Create a new text file 
Delete the filename and leave it blank
Press the OK button

*Expected result(s):*
User should not be able the press the OK button, because there is no name on the field; the field is empty. There should be an error message like 'You must type a file name' displayed
*Actual result(s):*
Error message 'File already exists: gallery' is displayed

jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0

**Comment by takluyver** [comment]
See #2478
