### ISSUE TITLE
The user can't view the content of a file which is inside a folder that contains a space

### ISSUE THREAD

**Issue by mpolacec** [jupyter/notebook#2476]
*STR:*
Create a new folder with a name which contains space (e.g. Folder One)
Open the folder which was created
Create a new text file
Select the file and click on the "View" option

*Expected:*
The file content should be displayed.

*Actual:*  
The file content is not displayed, instead error message is displayed (Error 404: Not Found) 

jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0

**Comment by takluyver** [comment]
Looks like the URL is getting doubly encoded, so the space appears as `%2520` (correct encoding would be `%20`).

**Comment by takluyver** [comment]
#2477 should fix this.
