### ISSUE TITLE
jupyter-bundlerextensions.exe not present in Scripts directory

### ISSUE THREAD

**Issue by schoolie** [jupyter/notebook#2483]
While attempting to install [Jupyter Dashboards Bundlers](https://github.com/jupyter-incubator/dashboards_bundlers/blob/761e0f1c2c23a7a2ab0d1d23c571e0fee630cb11/README.md), I executed the following command and received an error:

```
> jupyter bundlerextension enable --sys-prefix --py dashboards_bundlers
Error executing Jupyter command 'bundlerextension': [Errno 'jupyter-bundlerextension' not found] 2
```
I checked the Scripts folder in my Anaconda3 installation, and jupyter-bundlerextensions.exe was not present.

I was able to work around the issue for now by running:

> > 

```
> python
Python 3.5.2 |Anaconda custom (32-bit)| (default, Jul  5 2016, 11:45:57) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from notebook.bundler.bundlerextensions import main
>>> main(['enable', '--sys-prefix', '--py', 'dashboards_bundlers'])
Enabling dashboards_server_upload bundler dashboards_bundlers.server_upload...
Enabling dashboards_server_download bundler dashboards_bundlers.server_download...
>>>
```

*Environment:*
Windows 7
```
> conda --version
conda 4.3.17
```

```
> python --version
Python 3.5.2 :: Anaconda custom (32-bit)
```
```
> jupyter --version
4.3.0
```
```
> jupyter notebook --version
5.0.0
```
Uninstalled and reinstalled by running:
```
conda uninstall notebook
conda install notebook
```

**Comment by schoolie** [comment]
Just a quick follow-up - I completely uninstalled Anaconda, reinstalled, and the command worked. I assume running `conda install notebook` at any time should create the appropriate executables, so I think this still might be an issue?

**Comment by markjay4k** [comment]
the work around worked for me. thanks

**Comment by spetrenk** [comment]
This worked for me. Thank you for the tip.

**Comment by PerAkeMattias** [comment]
Thank you.  The workaround worked for me too.

- Windows 7
- conda 4.3.23
- Python 3.6.1 :: Anaconda 4.4.0 (64-bit)

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
