### ISSUE TITLE
Getting error while installing jupyter via pip

### ISSUE THREAD

**Issue by pandyakavi** [jupyter/notebook#2486]
I have python version 2.7.6
When I try to install jupyter through pip I am getting below shown error. Need help in resolving it.

**Comment by pandyakavi** [comment]
kavi@kavi-Inspiron-N5050:~$ pip install jupyter
Downloading/unpacking jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl
Downloading/unpacking ipywidgets (from jupyter)
  Downloading ipywidgets-6.0.0-py2.py3-none-any.whl (46kB): 46kB downloaded
Cleaning up...

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 45, in <lambda>
    next = lambda o: o.next()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'widgetsnbextension ~=2.0.0', 'at', ' ~=2.0.0')

**Comment by takluyver** [comment]
Please upgrade pip and setuptools:

```
pip install --upgrade setuptools pip
```

**Comment by pandyakavi** [comment]
Thanks, Thomas.
Errors are resolved after the upgrdation using the mentioned command

**Comment by sampath1992331** [comment]
get same error when upgarde setup tools

**Comment by BRajesh1995** [comment]
I have python version 3.9
When I try to install jupyter through pip I am getting below shown error. Need help in resolving it.


 ERROR: Command errored out with exit status 1:
   command: 'c:\users\himakernani\appdata\local\programs\python\python39\python.exe' 'c:\users\himakernani\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\HIMAKE~1\AppData\Local\Temp\tmp8ldhmne8'
       cwd: C:\Users\HIMAKERNANI\AppData\Local\Temp\pip-install-m2s59uta\argon2-cffi
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\argon2
  copying src\argon2\exceptions.py -> build\lib.win-amd64-3.9\argon2
  copying src\argon2\low_level.py -> build\lib.win-amd64-3.9\argon2
  copying src\argon2\_ffi_build.py -> build\lib.win-amd64-3.9\argon2
  copying src\argon2\_legacy.py -> build\lib.win-amd64-3.9\argon2
  copying src\argon2\_password_hasher.py -> build\lib.win-amd64-3.9\argon2
  copying src\argon2\_utils.py -> build\lib.win-amd64-3.9\argon2
  copying src\argon2\__init__.py -> build\lib.win-amd64-3.9\argon2
  copying src\argon2\__main__.py -> build\lib.win-amd64-3.9\argon2
  running build_clib
  building 'argon2' library
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for argon2-cffi
Failed to build argon2-cffi
ERROR: Could not build wheels for argon2-cffi which use PEP 517 and cannot be installed directly

**Comment by kevin-bates** [comment]
This link might be helpful: https://discuss.codecademy.com/t/having-trouble-installing-jupyter-notebooks/537292

I've also seen various posts indicating that `setuptools` be upgraded: `pip install --upgrade setuptools`

**Comment by BRajesh1995** [comment]
> This link might be helpful: https://discuss.codecademy.com/t/having-trouble-installing-jupyter-notebooks/537292
> 
> I've also seen various posts indicating that `setuptools` be upgraded: `pip install --upgrade setuptools`

Thank you so much Kevin
