### ISSUE TITLE
[UX] have space between last cell and bottom of page

### ISSUE THREAD

**Issue by jibe-b** [jupyter/notebook#2487]
## Actual behaviour

The last cell is stuck to the bottom of the UI, as soon as there is enough cells.

## Improvement suggestion

Enable to have space between the last cell and the bottom of the UI. Similar behaviour is `Ctrl+L` or `clear` in _bash_.

**Comment by jtpio** [comment]
Closing as fixed in Notebook 7:

![image](https://github.com/jupyter/notebook/assets/591645/fb8ed2fc-0894-4fab-aa7d-e7a3fc4368d0)

Notebook 7 also has a "Click to add cell" button after the last cell to easily add a new cell.
