### ISSUE TITLE
Performance issue due to websocket compression

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter/notebook#2490]
After benchmarking the transfer of large amounts of (binary) data ( https://github.com/jupyter-widgets/ipywidgets/issues/1339 ) I found out profiling the notebook server, that quite some time is spend on compressing the data in tornado. For 4MB of data (1 million 32bit floats), 0.7 second is spend on compression. 
The compression was enabled in this PR: https://github.com/jupyter/notebook/pull/1261
I think this should be reverted, since most use cases will involve running the notebook and the browser on the same machine, and then compression will only lead to a performance decrease.
I think compression should only be enabled for notebook servers that are expected to be only approached over the web.
cc @minrk @jasongrout @Carreau

**Comment by jasongrout** [comment]
I think it makes a lot of sense to make the defaults for the localhost case, and provide an option to enable compression if you're serving over the web.

It'd be nice if we could have an option to discern between the two options too (the compression settings are returned from a function, after all - does it have access to the URL used for the request?).

**Comment by maartenbreddels** [comment]
Yes, thought about that too, possible, I printed out the request object in that method, and it gives me:
```
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/1d193eb6-1814-4542-aa7e-75d83e09d6fb/channels?session_id=1D77B3BA106445C78D23CAE0EA10C0AB', version='HTTP/1.1',
remote_ip='::1', headers={'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits', 'Origin': 'http://localhost:8888', 'Upgrade': 'websocket', 'Host': 'localhost:8888',
'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Cookie': '_xsrf=2|17df2fef|7e6c9bdf39fac5eb385a86f0e9ebd7c0|1491566862; username-localhost-8888="2|1:0|10:1494252756|23:username-localhost-8888|44:ZjQ4OGY0NTI5NzA4NGQ4M2IwMTJlNzk1MGEwYjNjYmI=|47478563e289677985b4ee5110a9a631795dd69ae1b9f3b59157bd6bc1eaad9b";
username-localhost-8890="2|1:0|10:1494253131|23:username-localhost-8890|44:Y2M2ZDljNWUxODRkNGY0M2IyZGJkMzhjOTA0ZjY1YmY=|55640d60d4508934e5008d500991ea91dfd9c12893f5acc0c08e445cb372d719"', 'Accept-Language': 'en-US,en;q=0.8,nl;q=0.6,de;q=0.4', 'Connection': 'Upgrade', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Key': 'PdPn1PW9TDHxXyrhE4S32Q==', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36'})
```
The `remote_ip='::1',` means localhost (ipv6), so we can recognize on that, that should work, but will mess up smart routing, ssh tunneling etc. So maybe there should be an option 'auto'/'off'/'on' (None/False/True)

**Comment by minrk** [comment]
Even 'over the web' with a decent connection, compression may often cost more than it saves. My first inclination is to make `websocket_compression_options` a passthrough to the return value of this method with a default of `None` for no compression (#2492). I'm certainly open to `auto` being the default behavior if it's likely to really help in common cases, but it will guess wrong in some relatively common situations, such as local notebooks in containers, LAN deployments, and ssh-tunneled connections.

**Comment by maartenbreddels** [comment]
I'm also in favor of no compression by default, 'smart' things may not always behave as expected. Lets first keep it simple. That PR has my blessing.

**Comment by takluyver** [comment]
👍 to not trying to be too smart with the default.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/speed-up-notebook-saving-loading-if-working-on-remote-servers-compression/7076/1
