### ISSUE TITLE
browse tab-completion options with C-n/C-p

### ISSUE THREAD

**Issue by themrmax** [jupyter/notebook#2496]
I would love to be able to browse the tab completion options without taking my hands off the home row to go to the arrow keys. Would this be an easy thing to implement ?

**Comment by takluyver** [comment]
If you can find the necessary CodeMirror commands, the place to put them would be here: https://github.com/jupyter/notebook/blob/73f26bf047da79cbe847ffa7f16301cdc374eb4a/notebook/static/notebook/js/codecell.js#L128

**Comment by themrmax** [comment]
cool thanks @takluyver

**Comment by takluyver** [comment]
Did you get it working? What commands did you need? The details of what you did could be useful to other people who come to this page wanting the same thing.

**Comment by hikarubw** [comment]
I'd like to achieve this topic.
I found  the codes processing moves in completion window.
https://github.com/jupyter/notebook/blob/f8d4d6ad2dcaaed68851483db1a4efe742b52278/notebook/static/notebook/js/completer.js#L358-L374
This codes ignore CodeMirror. So, we may not resolve this issue with CodeMirror configuration.
I haven't tried that yet.
I'm new to Jupyter and Github. I need advice. How can I achieve that? Should I modify the codes above?
