### ISSUE TITLE
Minor highlighting problem

### ISSUE THREAD

**Issue by damontallen** [jupyter/notebook#2497]
This is not as big of a deal as the f string highlighting issue but the keyword "continue" is showing up in red in Notebook version 5.0.  I have not seen mention of it in the codemirror repo but again the red color is confined to that single key word.  I'm running Python 3.6.

    for i in range(8):
        if 3 <= i <= 6:
           continue
        print("i =", i)
    print("Done")

![image_selection_125](https://cloud.githubusercontent.com/assets/3960738/26131337/599701f6-3a67-11e7-9f16-644c4e1af43a.jpg)

**Comment by takluyver** [comment]
Interesting!

![screenshot from 2017-05-17 12-47-32](https://cloud.githubusercontent.com/assets/327925/26152495/0f33f5b8-3aff-11e7-8228-139c5e1308ba.png)

Spot the difference? One the first one, `continue` is indented by 7 spaces; on the second one, 8 spaces. It seems like Codemirror likes you to indent each block by four spaces more than the outer block. I can reproduce this in the [Codemirror Python demo](http://codemirror.net/mode/python/index.html), and it doesn't seem to be specific to `continue`:

![screenshot from 2017-05-17 12-52-53](https://cloud.githubusercontent.com/assets/327925/26152665/c39b4880-3aff-11e7-8ed2-c9b2e08b212f.png)

(`if` in red, indented 3 spaces)

**Comment by damontallen** [comment]
That is odd since I thought I had seen an error raised due to inconsistent indenting when a cell was executed when this occurred on previous occasions.  I don't recall pressing a backspace but I'm glad it was just a user error.  I'll mark this as closed.

**Comment by takluyver** [comment]
I don't think it's entirely user error - 3 space indentation is valid Python code, if unusual, so the bold red text doesn't seem entirely warranted. I think Google's Python style guide uses 2-space indentation. But I think it would need to be changed in Codemirror.

**Comment by damontallen** [comment]
Just to play devil's advocate, PEP8 indicates "Use 4 spaces per indentation level" which might be what Codemirror is working off of.

**Comment by takluyver** [comment]
It probably is, but that's a guideline rather than a rule. I think it would
be reasonable to ask codemirror about this if someone wanted to.

**Comment by damontallen** [comment]
Now that I know what the cause is I'm not sure if I still think of it as a flaw so much as a poorly designed feature.  Highlighting the line will a different color would be better than simple turning reserved words red but having a visual cue indicating a deviation from the style guidelines is useful in my opinion.
