### ISSUE TITLE
notebook.json path

### ISSUE THREAD

**Issue by juhasch** [jupyter/notebook#250]
When doing a `jupyter notebook install myextension`, the extension is activated in
`/Users/juhasch/.jupyter/nbconfig/notebook.json`.

The notebook itself (Javascript part) gets it's configuration from `/Users/juhasch/.jupyter/notebook.json`

Shouldn't they be the same ?

**Comment by minrk** [comment]
they certainly should. Someone's not looking in the right path.

**Comment by takluyver** [comment]
Have you pulled recently? This sounds like the same issue I fixed in #213.

**Comment by juhasch** [comment]
Yep, it is the most recent master with #213.
The code path addressed in #213 never gets called for me.
`self.config_manager.config_dir` is `/Users/juhasch/.jupyter`
