### ISSUE TITLE
Enhancement: Add line break after The Jupyter Notebook is running at:

### ISSUE THREAD

**Issue by GadgetSteve** [jupyter/notebook#2502]
[I 13:47:40.278 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=b5d714ae8bd101fd251053ddc55add86fafb8e0c1ddd690f
is displayed in the console on starting jupyter notebook and if the browser has not been set or cannot be found the user needs to copy and paste this into a browser.

The trouble is that the standard console or command window width is 80 characters while the message is 142 which, on many systems, results in the text wrapping which is not convenient for copy and paste. 

Splitting the message over 2 lines should enable the entire text that needs to be copied to appear on a single line.  If some other tools use the output format adding a backslash at the end of the first line should satisfy most if not all of them.

**Comment by takluyver** [comment]
That sounds reasonable, do you want to make a PR?

**Comment by GadgetSteve** [comment]
PR #2505 Added.

**Comment by remram44** [comment]
This is fixed!

**Comment by takluyver** [comment]
Thanks for the reminder!
