### ISSUE TITLE
WindowsError: [Error 5] Access is denied

### ISSUE THREAD

**Issue by patel0070** [jupyter/notebook#2504]
I am trying to run HMD Designer GUI for steamVR tracking HDK. It works for 2D plots and 3D simulation but it gives me this error when I try to open Output SCAD from there. I tried a lot of options but the error is not going away.  can somebody help me with this problem?

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
