### ISSUE TITLE
ImportError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by sharonaire** [jupyter/notebook#2506]
Hi, 
I use anaconda in OS, when using Jupyter notebook, I always get ImportError: No module named 'matplotlib'. And actually not only for matplotlib, numpy does't work as well. 

([Full Traceback ](https://pastebin.com/3tiYKHN4))
I've tried the methods mentioned in [here](https://github.com/jupyter/notebook/issues/270),  but still can't fix it.
version of python is 3.6
I've removed all other environments I created before.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ef9bfe22c51a> in <module>()
----> 1 get_ipython().magic('pylab inline')
      2 get_ipython().magic('matplotlib')
      3 import pandas as pd
      4 
      5 x = arange(-1, 1, 0.1)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

<decorator-gen-105> in pylab(self, line)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/magics/pylab.py in pylab(self, line)
    154             import_all = not args.no_import_all
    155 
--> 156         gui, backend, clobbered = self.shell.enable_pylab(args.gui, import_all=import_all)
    157         self._show_matplotlib_backend(args.gui, backend)
    158         print ("Populating the interactive namespace from numpy and matplotlib")

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py in enable_pylab(self, gui, import_all, welcome_message)
   2986         from IPython.core.pylabtools import import_pylab
   2987 
-> 2988         gui, backend = self.enable_matplotlib(gui)
   2989 
   2990         # We want to prevent the loading of pylab to pollute the user's

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   2935         """
   2936         from IPython.core import pylabtools as pt
-> 2937         gui, backend = pt.find_gui_and_backend(gui, self.pylab_gui_select)
   2938 
   2939         if gui != 'inline':

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/pylabtools.py in find_gui_and_backend(gui, gui_select)
    270     """
    271 
--> 272     import matplotlib
    273 
    274     if gui and gui != 'auto':

ImportError: No module named 'matplotlib'

**Comment by takluyver** [comment]
It sounds like you're trying an import in two different installations of Python, or two different environments. Check `sys.executable` to see which Python and environment you're running in, and `sys.path` to see where it looks to import modules.

Python packages must be installed separately for each copy of Python you use, and if you are using virtualenvs or conda envs, packages must be installed into each environment where you need them. Either the package is not installed in one, or a different version of the package is installed.

To install packages to a particular Python installation or environment using pip, you can run it like this:

```shell
path/to/python -m pip install ...
# Replace path/to/python with the path of the Python executable (sys.executable)
```

If you are using conda environments, you can install packages from conda like this:

```shell
source activate myenv  # On Windows, just 'activate myenv' (no 'source')
conda install ...
```

[ This is a saved reply because I answer similar questions often - sorry if it doesn't exactly fit your case ]

**Comment by sharonaire** [comment]
@takluyver Thank you so much!

I've fixed it!
Thank you again!

**Comment by nsb007** [comment]
@sharonaire Hey! I'm facing the same problem. I have installed python 2.x via anaconda but I created a python 3.x environment and fired up the jupyter notebook but I am getting the same error as yours though I installed the required libraries. 
How did you get it through? Thanks.

**Comment by sharonaire** [comment]
I did exactly what takluyver advised.
It’s like that you installed the library automatically in the 2.x environment. So you need to switch to the 3.x environment first and then install it again.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
