### ISSUE TITLE
Make text files load in editor instead of downloading when clicking in Home

### ISSUE THREAD

**Issue by invisibleroads** [jupyter/notebook#2510]
Clicking on a text file in Home currently results in the file being downloaded instead of opening in a text editor. By text file, I mean files whose content is text even though the extension might be something different.

I can work on this issue during the sprints at PyCon.

**Comment by takluyver** [comment]
I think this is tricky because:

1. We don't know if the file is editable text except by reading the whole thing.
2. For some file types, you may want to download it even though it's UTF-8 text.

We did add an *Edit* button in the file list, so you should be able to select the file you want and click Edit.

**Comment by invisibleroads** [comment]
As of a82a51019993d0ef0d5bb785484d0ea4c64963c8, I can confirm that shell scripts open properly in a text editor instead of being downloaded. 

@agermanidis, I saw that you defined `get_content_type` using `mimetypes.guess_type`, which is the approach I was thinking of taking during PyCon. But could you please pinpoint which code causes the file to be opened in the editor? I think it is https://github.com/jupyter/notebook/pull/2656/commits/a82a51019993d0ef0d5bb785484d0ea4c64963c8#diff-aa5d3e97b16f9c0253d881fdec65c8c3R30 but I don't understand how it works.

**Comment by takluyver** [comment]
I think the code that actually determines what opens in the editor is in the Javascript, probably this bit: https://github.com/jupyter/notebook/blob/38b789a7d8fa521266b3aba85c2d49bf104e3622/notebook/static/tree/js/notebooklist.js#L547

**Comment by invisibleroads** [comment]
Aha, thanks!
