### ISSUE TITLE
error on saving notebooks whose path contains %5C (\)

### ISSUE THREAD

**Issue by jan-glx** [jupyter/notebook#2512]
On windows, when a notebook in a sub directory is opened with an url in which `\` (backslash) escaped as `%5C` is used instead of `/` (slash) as path separator, jupyter throws the following error upon save:

> Unexpected error while saving file: B\notebook.ipynb [Errno 2] No such file or directory: 'C:\\A\\.ipynb_checkpoints\\B\\notebook.ipynb'

Where `jupyter notebook` runs in directory A and the notebook files lives in its sub-directory B.

Likely bc the file should be: `C:\\A\\B\\.ipynb_checkpoints\\notebook.ipynb`
Leads to error: `http://localhost:8888/notebooks/B%5Cnotebook.ipynb`
Does not: `http://localhost:8888/notebooks/B/notebook.ipynb`
This is an real issue because nbopen opens files using backslash paths (could easily be changed there, but I believe a fix here is much more appropriate). Best, J

**Comment by takluyver** [comment]
I actually think the appropriate fix is in nbopen. Jupyter 'API paths' are specified to always use `/` as the directory separator. I'm slightly surprised it works at all with `\` in the URL.

**Comment by takluyver** [comment]
takluyver/nbopen@31a17f95fafbcdb1592e226844c1216e4ccdf457 should do it - can you test?

**Comment by jan-glx** [comment]
I see, thanks for tackling the issue. 31a17f9 did not do it but I submitted [a PR](https://github.com/takluyver/nbopen/pull/42) that does.

**Comment by erihanse** [comment]
Similar issue, see also https://github.com/jupyter/notebook/issues/2512.

When I open a notebook within a subdirectory of my home directory (using nbopen), I receive the following: 
![image](https://user-images.githubusercontent.com/9251274/30163267-a17dbeb8-93d8-11e7-8a7d-654d65f29f34.png)

I see that the url is the following:
> http://localhost:8888/notebooks/Documents%5CUntitled.ipynb

I saw somewhere else that we were supposed to be able to set default program for .ipynb files to be nbopen, but this will open the file in the above url (containing %5C). The notebook is displayed, but saving is not possible, resulting in above error. 

Another issue is that sometimes, when I try to open the file, it says that an existing server is already present:
> C:\Users\eriha\Documents>nbopen Untitled1.ipynb
> Using existing server at C:\Users\eriha
> [W 14:43:14.351 NotebookApp] server_extensions is deprecated, use nbserver_extensions

when no server is running, resulting in browser showing a 404.
