### ISSUE TITLE
Use tag to set stop_on_error for CodeCell (Enhancement) 

### ISSUE THREAD

**Issue by mscuthbert** [jupyter/notebook#2516]
I use Jupyter notebook w/ Python a lot for writing documentation (which I later use nbconvert on).  One of the problems that arises is that I want to run all cells to compare output to previous output, but I also like to demonstrate "what *not* to do", which often raises errors.  These errors mean that Run All does not fully execute the code.

I think that if a standardized way were defined that marked a code cell as expected to error, it would be a big help to me.  I think that Jupyter 5.0's tags could do so.

For instance, in js/codecell.js we find this method fragment:

```
    CodeCell.prototype.execute = function (stop_on_error) {
        if (!this.kernel) {
            console.log("Can't execute cell since kernel is not set.");
            return;
        }

        if (stop_on_error === undefined) {
            stop_on_error = true;
        }
```

I believe that a fix might be as simple as something like:

```
        if (stop_on_error === undefined) {
            if (cell.metadata.tags !== undefined && cell.metadata.tags.indexOf('expected-failure') !== -1) {
                stop_on_error = false;
            } else {
                stop_on_error = true;
            }
        }
```

Would this be of interest and on the right track?  If so I'm happy to make a pull request.

**Comment by takluyver** [comment]
This seems like a good use case for cell tags, and your idea about implementing it looks about right, at least on a quick glance. Go for it! :-)

**Comment by mscuthbert** [comment]
Thanks!  I'll call it "raises-exception" because that's what nbval uses and allow for either 'raises-exception' or 'nbval-raises-exception'

**Comment by mscuthbert** [comment]
I have a patch which works great for me, but I'm unclear about what the best way to run tests for the notebook -- if anyone is interested in helping me on how to write tests/regression tests for Jupyter notebook, I'd appreciate it.
