### ISSUE TITLE
[feature request] Naming a cell and running a cell from other cell

### ISSUE THREAD

**Issue by changcw83** [jupyter/notebook#2517]
I think it'd be wonderful if we could have some magic that can name a cell and running a cell from other cell for example
=====CELL 1=========
%%namecell a

=====CELL 2=========
%runcell a

=====CELL 3=========
for i in range(10):
   %runcell a

Do anyone here knows a workaround or feels the same way as me that it will be a useful feature to have?

**Comment by changcw83** [comment]
Ok i realise I can use %%writefile magic

**Comment by takluyver** [comment]
The `%macro` system can also do something kind of similar.
