### ISSUE TITLE
Notebook 5: Config option `cull_idle_timeout` not recognized by `MappingKernelManager`

### ISSUE THREAD

**Issue by ghazpar** [jupyter/notebook#2519]
Hi,

Wanted to try the new culling feature in Notebook 5.0, but got the above message (see title).
```
ghazpar$ jupyter notebook --version
5.0.0
ghazpar$
```

This is strange because the feature is [documented](https://jupyter-notebook.readthedocs.io/en/latest/config.html) and appears [implemented](https://github.com/jupyter/notebook/blob/master/notebook/services/kernels/kernelmanager.py). Am I doing something wrong? Here is my config file:
```
c = get_config()
c.MappingKernelManager.cull_idle_timeout = 300
```
How should I activate this?

**Comment by takluyver** [comment]
It's in master. The links for the released version look like this:

https://github.com/jupyter/notebook/blob/5.0.0/notebook/services/kernels/kernelmanager.py
https://jupyter-notebook.readthedocs.io/en/stable/config.html

If you want to try the development version out, see the instructions here: http://jupyter-notebook.readthedocs.io/en/latest/contributing.html

**Comment by ghazpar** [comment]
Ok, so I was mistaking the latest for the stable version of the documentation. Sorry.

I will try to take the master for a spin...

**Comment by rolweber** [comment]
Could you please close this issue then?

**Comment by ghazpar** [comment]
I have tried the feature and it seems to work. The kernel are indeed culled after the specified timeout (approximately). This is great because I have many users (through jupyterhub) that work on many notebooks, and they rarely take the time to shutdown their kernels before moving on to the next notebook. Thus the server eventually runs out of memory... but sometimes they need to come bak to a previous notebook.

I noticed that if the user leaves his notebook opened, he is not alerted that his kernel is gone. Is this normal behavior? Isn't there some kind of heartbeat mechanism where the opened notebook is suppose to ask the user if he wants to restart the kernel?

**Comment by takluyver** [comment]
Ping @parente @kevin-bates - is it practical to notify the user in the notebook UI that the kernel has been culled? Is there a mechanism that should already be doing this? Or can we easily add one?

**Comment by kevin-bates** [comment]
The heartbeat mechanism is between the Notebook server and kernel and a kernel's culling shuts down the kernel - so no heartbeat.  That said, sending a notification back to the user that the kernel is being culled seems practical, although I don't know what's involved in implementing such a notification.

**Comment by takluyver** [comment]
We don't actually use the heartbeat mechanism when the notebook server starts kernels, but as you say, it's not relevant here.

The frontend already has a way to detect if it loses the websocket connection to the kernel and try to reconnect. I guess that the culling must shut it down in a way that suppresses that. But I think the frontend Javascript should already be able to see when the server closes the websocket.

**Comment by parente** [comment]
> The frontend already has a way to detect if it loses the websocket connection to the kernel and try to reconnect. I guess that the culling must shut it down in a way that suppresses that. But I think the frontend Javascript should already be able to see when the server closes the websocket.

The kernels are shutdown through a typical call to shutdown in the kernel manager. I would expect the notebook UI to show a "disconnected from kernel" or even a "kernel died" message. I have not tested that situation myself yet, but will report back when I do.
