### ISSUE TITLE
Support multiline edit

### ISSUE THREAD

**Issue by guillaume-chevalier** [jupyter/notebook#2527]
I would love the support of multiline edit in the web notebook cells, like what can be done in Atom, Sublime, and many other IDEs.

**Comment by Carreau** [comment]
Would you mind describing in better detail or show an example ? Because I'm unsure about what "Multiline Edit" means.

![multiline](https://cloud.githubusercontent.com/assets/335567/26532860/ae773fd4-43c1-11e7-9c5f-6d811fa243b3.gif)

**Comment by guillaume-chevalier** [comment]
What's done in your image is exactly what I need. I searched for keyboard shortcuts and I also tried to use a nbextention, but all of that didn't work. 

How did you do that?

**Comment by Carreau** [comment]
on Mac Cmd+Click on various location, not sure on windows/linux. 
When you use sublime there is a shortcut (Cmd-D I think) that select next identical token.
But all these shortcuts are [Codemirror shortcuts](http://codemirror.net/) duplicating all the documentation of codemirror would be a lost battle so if you want to know more you'll have to see there. 

I believe alt-click-drag should allow selection of rectangular block for edition. 

Closing, feel free to keep commenting.

**Comment by guillaume-chevalier** [comment]
Thanks a lot. I discovered that I had a chrome binding with a plugin for CTRL+CLICK overriding it and that was a part of the problem.

**Comment by yacineMTB** [comment]
Wait, so how do we get this binded to a keyboard shorcut? I don't use a mouse

**Comment by mczxy** [comment]
> Wait, so how do we get this binded to a keyboard shorcut? I don't use a mouse

Ctrl + Alt + Click

**Comment by ddivittorio** [comment]
> on Mac Cmd+Click on various location, not sure on windows/linux.
> When you use sublime there is a shortcut (Cmd-D I think) that select next identical token.
> But all these shortcuts are [Codemirror shortcuts](http://codemirror.net/) duplicating all the documentation of codemirror would be a lost battle so if you want to know more you'll have to see there.
> 
> I believe alt-click-drag should allow selection of rectangular block for edition.
> 
> Closing, feel free to keep commenting.

To do on Windows: Alt + Click
