### ISSUE TITLE
Persisting notebooks in version control (e.g. git)

### ISSUE THREAD

**Issue by praveen-srinivasan** [jupyter/notebook#253]
Hi,
I was wondering if there were any plans to be able to commit a notebook to a git repository when someone hits "save"?

**Comment by takluyver** [comment]
There are a couple of ways you could do something like this:

- Configure a post-save hook that runs git commit every time a notebook is saved. I don't think that sees a distinction between a user-initiated save and an autosave, though.
- Write a [contents manager](http://jupyter-notebook.readthedocs.org/en/latest/extending/contents.html) (@ssanderson: thanks for those docs) to store notebooks in Git.

I don't think we have any plans to do this ourselves.

**Comment by flying-sheep** [comment]
it would also be great to have a simple way to ignore cell outputs in your VCS. e.g. by doing something like this:

1. create a copy of the notebook
2. clear outputs in original
3. commit
4. restore version with outputs

ideally also integrated in `git status` and the like.

idk if that’s even possible…

**Comment by Carreau** [comment]
That's what VCS hooks are for. For git these are `clean` and `smudge` filters.

**Comment by flying-sheep** [comment]
the “output” key must exist right? so cleaning would simply do `cell['output'] = []` for every cell, and smudge would either do nothing (i.e. checkouts would remove outputs) or do something smart like memorizing the outputs of the working directory version, and inserting them into the to-be-checked-out version if it has the same number of cells (else do nothing and checkout the output-less version because we have no idea what cells were added or deleted)

**Comment by JanSchulz** [comment]
See here for a git filter version of stripping output: https://gist.github.com/minrk/6176788

 with that:
* only the inputs are commited
* `git diff` is without output

**Comment by JanSchulz** [comment]
@Carreau would it be acceptable to push such an example to this repo? 

Like `examples/git-filter.{txt,py}`

**Comment by Carreau** [comment]
> @Carreau would it be acceptable to push such an example to this repo?
> 
> Like examples/git-filter.{txt,py}

I have no objections with that.

**Comment by flying-sheep** [comment]
ah it already exists! great!
