### ISSUE TITLE
[Question] How to highlight code just like this

### ISSUE THREAD

**Issue by SphericalHarnomics** [jupyter/notebook#2538]
Newbie to Jupyter notebook,  I can now use HTML or Markdown grammar to highlight them, but have no idea how others could highlight the source code in "code cell" (partially rendered """ comment, # comment etc).

Below are two examples.
[Example 1](https://www.dropbox.com/s/u0ar5jslazr55ng/Screen%20Shot%202017-06-01%20at%2009.06.33.jpg?dl=0)
[Example 2](https://www.dropbox.com/s/z2i53b7ryy2i5px/Screen%20Shot%202017-06-01%20at%2009.06.45.jpg?dl=0)

**Comment by takluyver** [comment]
Discussion is on the mailing list, closing here.
