### ISSUE TITLE
Illegal creation times of files lead to unusable notebook

### ISSUE THREAD

**Issue by crstnbr** [jupyter/notebook#2539]
OS: Windows 10

**Bug report:**
If you try to start the jupyter notebook in a folder which contains files with empty or illegal (e.g. negative) creation timestamps the jupyter notebook isn't usable at all. It starts but instead of listing the files in the directory it displays the following error message. No notebooks can be opened/created etc.

```
Server error: Traceback (most recent call last):
File "C:\Users\carsten\Anaconda2\lib\site-packages\notebook\base\handlers.py", line 503, in wrapper
result = yield gen.maybe_future(method(self, *args, **kwargs))
File "C:\Users\carsten\Anaconda2\lib\site-packages\tornado\gen.py", line 1015, in run
value = future.result()
File "C:\Users\carsten\Anaconda2\lib\site-packages\tornado\concurrent.py", line 237, in result
raise_exc_info(self._exc_info)
File "C:\Users\carsten\Anaconda2\lib\site-packages\tornado\gen.py", line 285, in wrapper
yielded = next(result)
File "C:\Users\carsten\Anaconda2\lib\site-packages\notebook\services\contents\handlers.py", line 124, in get
path=path, type=type, format=format, content=content,
File "C:\Users\carsten\Anaconda2\lib\site-packages\notebook\services\contents\filemanager.py", line 356, in get
model = self._dir_model(path, content=content)
File "C:\Users\carsten\Anaconda2\lib\site-packages\notebook\services\contents\filemanager.py", line 246, in _dir_model
model = self._base_model(path)
File "C:\Users\carsten\Anaconda2\lib\site-packages\notebook\services\contents\filemanager.py", line 212, in _base_model
created = tz.utcfromtimestamp(info.st_ctime)
File "C:\Users\carsten\Anaconda2\lib\site-packages\notebook\services\contents\tz.py", line 41, in utc_method
dt = unaware(*args, **kwargs)
ValueError: timestamp out of range for platform localtime()/gmtime() function
```

After consulting Google I read that this behavior has appeared to users when some of the creation times were negative. In my particular case they are empty (checking right click -> Properties). The reason seems to be that I try to start the jupyter notebook in a folder that is mounted (using SFTP and Mountain Duck). It is mounted such that for all applications it appears as just any other local folder (except for the creation times apparently)

**Expected/Suggested behavior**
I think that a creation timestamp shouldn't be so crucial to the notebook. Therefore I would expect to maybe get a warning but still be left with a functional notebook.

**Comment by crstnbr** [comment]
Dirty fix:

In `notebook/services/contents/filemanager.py` just fake every files creation time to be utcnow() as follows (line 211):

Change
```python
        last_modified = tz.utcfromtimestamp(info.st_mtime)
        created = tz.utcfromtimestamp(info.st_ctime)
```

to 

```python
        last_modified = tz.utcfromtimestamp(info.st_mtime)
        # created = tz.utcfromtimestamp(info.st_ctime)
        created = tz.utcnow()
```

and everthing is back to normal as far as I can tell.

**Comment by takluyver** [comment]
The many and varied ways computers find not to work. I think we can do it cleaner by catching the error.

**Comment by takluyver** [comment]
#2540 should fix it by falling back to 1 Jan 1970, aka the Unix epoch.

**Comment by crstnbr** [comment]
I think this is a reasonable fix. Thank you!

I guess there is no reason to keep this issue open. Otherwise please reopen.

**Comment by takluyver** [comment]
Generally you can leave an issue like this open - when we merge the pull request, it will be closed automatically. Probably not important in this case, though, as I imagine it will be merged soon enough.
