### ISSUE TITLE
Vertical and horizontal scrollbar not both visible in toggled output

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyter/notebook#254]
When displaying a large pandas DataFrame, you get some scrollbars. And starting from pandas 0.16.2, we leave the overflowing fully to the notebook itself (we removed `style="max-width:1500px;overflow:auto;"` from the html output, see https://github.com/pydata/pandas/pull/10232).

But I noticed another issue: when having a wide frame that does not fit the notebook width, you get horizontal scrollbar at the bottom of the output. When you also use the 'scroll output' feature, you get a vertical scrollbar as well. But the horizontal is only visible when you first scroll down to the bottom. To illustrate:

![nb2](https://cloud.githubusercontent.com/assets/1020496/9037638/97ebdac0-39ed-11e5-8a04-fae8927bded9.png)

![nb1](https://cloud.githubusercontent.com/assets/1020496/9037639/9a86b5fc-39ed-11e5-89c5-57865b47760f.png)

So if you want to see all columns of the first rows, you first have to scroll down, to be able to scroll right, then scroll up again to see the rows.

I suppose the one scrollbar belongs to the output itself, and the other to the toggled ouput area, but would it be possible to have them both on the toggled output area?

**Comment by captainsafia** [comment]
I'll take a look at this. Feel free to assign me, @minrk.

**Comment by minrk** [comment]
@captainsafia thanks, assigned.

**Comment by jasongrout** [comment]
@captainsafia or @jorisvandenbossche, can you test my fix at #535?

**Comment by captainsafia** [comment]
Tested.

**Comment by jasongrout** [comment]
@captainsafia, sorry!  I didn't realize you were working on this.  I saw that it had no updates for over a week, and figured people got busy and I could help out.

**Comment by willingc** [comment]
@jasongrout Rumor has it @captainsafia likes really cool cat gifs and emojis. Perhaps offer to pair on a future issue. :sunflower:

**Comment by captainsafia** [comment]
@jasongrout — No worries! I got a little busy with coursework and didn't have the chance to follow through on this until 3 hours before you did (ha!) None the less, the bug is squashed and peace prevails for a moment.

![giphy-5](https://cloud.githubusercontent.com/assets/1857993/10327971/0aac8f7e-6c74-11e5-847f-95e281da002f.gif)
