### ISSUE TITLE
"Make a copy" no longer works on read-only notebooks

### ISSUE THREAD

**Issue by dietmarw** [jupyter/notebook#2541]
When editing a read-only jupyter notebook (made read-only via file system) I noticed that I can no longer use the "Make a copy" feature. All that happens is that a new empty tab is opened. 

I played a bit around to find out when this happens exactly. 

1. One can get lucky if one is quick enough to hit the button before Jupyter is finished rendering the notebook. 
 2. I could only reproduce this issue when the Jupyter Notebook is served via a port reroute (using iptables from port 443 or 80 to 8888) via web. On a local installation this does not happen. 
 
As a note this did not use to be an issue like half a year ago were I ran the same set of Jupyter Notebooks with the exact same set up. I can be sure of that since I used the same docker setup.

I can supply a running live server where this can tested out if needed.

**Comment by takluyver** [comment]
I'm not sure why the port rerouting would affect it, but if the JS considers that the notebook is dirty (changed since last save), it tries to save it before copying. I think the issue is likely that when the kernel starts, it updates the kernel metadata and marks the notebook as dirty. Maybe we should just not count that change as dirty-ing the notebook.

**Comment by dietmarw** [comment]
Yes I'm not to sure about the influence of port reroute myself. I tested it again disabling the reroute to port 443 and accessing it directly via the default port 8888 gives the same (non-working) result.

**Comment by dietmarw** [comment]
Just tested it again and the issue still present.

**Comment by minrk** [comment]
Yeah, we have a few 'save first' actions (trust was just addressed recently in #2718) that should probably be "save first unless readonly".

**Comment by Madhu94** [comment]
I'll check this.

**Comment by dietmarw** [comment]
Any update on this issue?

**Comment by dietmarw** [comment]
Excellent, thanks!
