### ISSUE TITLE
Why is Jupyter 5.0.0 labeled as "Pre-release"

### ISSUE THREAD

**Issue by charlie718y** [jupyter/notebook#2542]
Hi,

I'm just wondering why is Jupyter 5.0.0 release page labels it as "Pre-release". 

Thanks,
Charlie

**Comment by takluyver** [comment]
You mean the [GitHub release page](https://github.com/jupyter/notebook/releases/tag/5.0.0)? That was an oversight, I've just updated it.

**Comment by charlie718y** [comment]
Right. That's it. Thanks for the update.
