### ISSUE TITLE
matplotlib DPI settings for %inline backend inconsistent

### ISSUE THREAD

**Issue by amueller** [jupyter/notebook#2544]
Using Jupyter notebook with ``%matplotlib inline`` I get the following:
```python
plt.rcParams['savefig.dpi'] = 300
plt.figure(dpi=70)
```
shows a 300 dpi figure, while
```python
import matplotlib.pyplot as plt
%matplotlib inline
plt.figure(dpi=70)
```
shows a 70 dpi figure.

That's pretty unexpected. Why does setting the rc overwrite the setting in the figure?
I'm using
```
notebook                  5.0.0                    py35_0  
```
from the main conda repo.

Code to reproduce:
```python
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

plt.rcParams['savefig.dpi'] = 300
plt.figure(dpi=70)
plt.plot(np.sin(np.linspace(-3, 3)))
```

Thanks!

**Comment by amueller** [comment]
hm ok the issue is that I'm setting ``savefig.dpi`` not ``figure.dpi`` but that's a bit tricky.... hm.

**Comment by amueller** [comment]
So I tried doing
``with matplotlib.rc_context(rc={'savefig.dpi': 70}):``
but that also seemed to have no effect... I guess because the rendering is outside the with?

It seems like setting ``figure.dpi`` doesn't have an effect in the notebook (or only sometimes does?)

**Comment by minrk** [comment]
what versions of ipython and ipykernel? There was a change to how we set the DPI, which should work better, but I believe you need IPython ≥ 5.4 and ipykernel ≥ 4.5 for it to fully work right, where `fig.dpi` takes precedence over `rc['savefig.dpi']`. In particular, I seem to recall there being a regression if only one of those has been upgraded but not the other, but I don't recall the details.

cf https://github.com/ipython/ipykernel/pull/176 https://github.com/ipython/ipython/pull/9868

**Comment by amueller** [comment]
Ok, I updated to
```
ipykernel                 4.6.1                    py36_0
ipython                   6.1.0                    py36_0  
```
and now ``savefig.dpi`` has no effect on the figures inline, but if I change it to ``figure.dpi``, it works, and I can overwrite it by explicitly setting ``plt.figure(dpi=...)``.
So the behavior changes are a bit confusing, but now it seems to work as expected.
