### ISSUE TITLE
Browser is unresponsive when one cell outputs a lot

### ISSUE THREAD

**Issue by Jamesits** [jupyter/notebook#2545]
If a cell outputs really fast, browser process may slow down or stop responding completely.

Server Information:

You are using Jupyter notebook.

The version of the notebook server is 5.0.0.dev and is running on:
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

Current Kernel Information:

Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

**Comment by takluyver** [comment]
Please upgrade IPython and ipykernel - we added some rate limiting to help with that problem

**Comment by Jamesits** [comment]
Okay. I'll contact system administrator for that.
