### ISSUE TITLE
Cannot copy cell(s) on Microsoft Edge

### ISSUE THREAD

**Issue by yuntan** [jupyter/notebook#2551]
I cannot copy cell(s) on Microsoft Edge.

[![https://gyazo.com/eea93a74d9cd84a11449f2045750d000](https://gyazo.com/eea93a74d9cd84a11449f2045750d000/raw)](https://gyazo.com/eea93a74d9cd84a11449f2045750d000)

I can reproduce the issue on

- jupyter notebook 5.0.0, Microsoft Edge 40, Windows 10
- jupyter notebook master branch 9cd249ef7f3cf97f5f87fb5888a61833d8988a53, Microsoft Edge 40, Windows 10

This issue is only about copying. Pasting functionary works (e.g. copy cell on Chrome, paste it on Edge).

**Comment by takluyver** [comment]
Sorry, we don't try to support Edge.

**Comment by yuntan** [comment]
OK, I hope this issue would help to find which functionary doesn't work on Edge.
