### ISSUE TITLE
%%sql does not work

### ISSUE THREAD

**Issue by ravikafle** [jupyter/notebook#2557]

**Comment by rgbkrk** [comment]
What language is your notebook file in? Which kernel?

**Comment by ravikafle** [comment]
i am learning mysql in coursera. THey have the exercises in Jupyter....

**Comment by rgbkrk** [comment]
Do you have a link to the course, notebook? This isn't much to go on. It would probably good to reach out to the instructor(s) on coursera as well, since we don't know how they're using it and `%%sql` isn't built into the Python interpreter / magics.

**Comment by ravikafle** [comment]
Its working fine now. I tried rerunning after a while and it seems to work fine now. 
Thank you for your concern.
