### ISSUE TITLE
Kernel info not updated completely till kernel restart

### ISSUE THREAD

**Issue by jdfreder** [jupyter/notebook#256]
Quote from @jasongrout on the ipython/ipywidgets gitter channel:

> When I just do Kernel | Change Kernel to python 3, then save, the diff looks like this:
> ```diff
diff --git a/examples/Widget List.ipynb b/examples/Widget List.ipynb
index 11915b4..fc21a4c 100644
--- a/examples/Widget List.ipynb        
+++ b/examples/Widget List.ipynb        
@@ -621,9 +621,9 @@
  ],
  "metadata": {
   "kernelspec": {
-   "display_name": "Python 2",
+   "display_name": "Python 3",
    "language": "python",
-   "name": "python2"
+   "name": "python3"
   },
   "language_info": {
    "codemirror_mode": {
```
> however, when I restart the kernel after changing the kernel (Kernel | restart | clear output and restart), then save, I get a bigger diff
```diff
diff --git a/examples/Widget Events.ipynb b/examples/Widget Events.ipynb
index e47b7f9..be47d18 100644
--- a/examples/Widget Events.ipynb      
+++ b/examples/Widget Events.ipynb      
@@ -359,21 +359,21 @@
    ]
   ],
   "kernelspec": {
-   "display_name": "Python 2",
+   "display_name": "Python 3",
    "language": "python",
-   "name": "python2"
+   "name": "python3"
   },
   "language_info": {
    "codemirror_mode": {
     "name": "ipython",
-    "version": 2
+    "version": 3
    },
    "file_extension": ".py",
    "mimetype": "text/x-python",
    "name": "python",
    "nbconvert_exporter": "python",
-   "pygments_lexer": "ipython2",
-   "version": "2.7.10"
+   "pygments_lexer": "ipython3",
+   "version": "3.4.3"
   }
  },
  "nbformat": 4,
```
> It appears that the language_info, the version, and the pygments_lexer aren't being appropriately updated when just doing a kernel change.
> My worry is that, for example, the codemirror isn't set, so someone opening up the notebook will see the wrong syntax highlighting

**Comment by jasongrout** [comment]
As you can see in the diff above, it's not just the pygments_lexer that is stale, but also the codemirror mode and the version keys.

**Comment by takluyver** [comment]
`language_info` should be set on the `kernel_ready.Kernel` event. I guess that's somehow not getting fired when you change kernel. It should be, IMO.

**Comment by Carreau** [comment]
Made #437 to fix that.

**Comment by Carreau** [comment]
So actually with of without #437 just changing the kernel does update the language info for me. So I either cannot reproduce, or it is already fixed.
