### ISSUE TITLE
Improving Markdown code highlighting

### ISSUE THREAD

**Issue by Faur** [jupyter/notebook#2561]
The Markdown code highlight (when you use `) is not very clear. Would it be possible to make the code stand out more, perhaps similar to the gray boxes you get on Stack Exchange?

Jupyter as it is right now:
![image](https://user-images.githubusercontent.com/8115763/26925397-a0f1b27e-4c84-11e7-95df-066c496a53f0.png)

___
Example of clearer code highlighting (from Stack Exchange)
![image](https://user-images.githubusercontent.com/8115763/26925408-a9a98bbc-4c84-11e7-86f1-07b4b9a873b9.png)

**Comment by takluyver** [comment]
Sounds reasonable to me. This should be something a new contributor could have a go at.

http://jupyter-notebook.readthedocs.io/en/latest/contributing.html

**Comment by vidriduch** [comment]
Hi, I'm new contributor and I tried to address this issue in #2571. It should add a gray background under a single ` in the text. Bigger block of code (surrounded by ```) should be formatted as before with white background. I believe that should resemble the Stack Exchange style of formatting. Please, do let me know what do you think.

**Comment by takluyver** [comment]
BTW, with visual changes it's a good idea to provide a screenshot of what it looks like (even better: before and after comparison).

**Comment by vidriduch** [comment]
Sorry, I added images of before and after comparison to the commit message.

**Comment by takluyver** [comment]
Can I be picky and ask for an after image from Jupyter, rather than (or as well as) the 'this is what I'm after' from Stackoverflow? See the instructions [here](http://jupyter-notebook.readthedocs.io/en/latest/contributing.html) if you've not yet rebuilt the CSS with your changes.

**Comment by vidriduch** [comment]
Sorry again, the previous images where taken from Jupyter I just trimmed the important part. I changed them so now images show the entire notebook. If I misunderstood something please do let me know.

**Comment by takluyver** [comment]
Ah, sorry, I was mistakenly looking at the images on this issue instead of the images on your PR. Yes, those look fine. Maybe you want to add a couple of pixels of padding so the grey box is a little bit bigger?

**Comment by vidriduch** [comment]
Good idea, I added 1px padding from top and bottom and 5px from left and right to again resemble Stack Exchanges formatting.

**Comment by Faur** [comment]
@vidriduch I think the results look really good now. Thanks for the quick work.

**Comment by minrk** [comment]
This should be in 5.1, which is likely to be the next release, so there will likely not be an earlier one.

**Comment by gnestor** [comment]
Closing this as it appears it was resolved by https://github.com/jupyter/notebook/pull/2571 👍
