### ISSUE TITLE
failing to create a 2D plot after a 3D with "%matplotlib notebook" magic

### ISSUE THREAD

**Issue by cid0rz** [jupyter/notebook#2568]
Hello Devs, thank you for all your dedication in this fantastic tool.  When I try on a notebook after using:
```python
%matplotlib notebook
```
I plot some data wiht:
```python
fig=plt.figure()
axes = mplot3d.Axes3D(fig)
axes.plot3D(projAla[:,0], projAla[:,1], projAla[:,2])
scale = projAla.flatten(-1)
axes.auto_scale_xyz(scale, scale, scale)
```
this i repeat in some cells getting correct 3d plots. Then I try:
```python
newfig=plt.plot(pathnew5[:,0],pathnew5[:,1])
xmax = np.max(pathnew5[:,0])
ymax = np.max(pathnew5[:,1])
xmin = np.min(pathnew5[:,0])
ymin = np.min(pathnew5[:,1])
def rp (number):
    return len(str(abs(number)).split('.')[0])-1
def roundax (number):
    return round(number, -rp(number))
plt.axis([roundax(xmin) ,roundax(xmax), roundax(ymin) , roundax(ymax)])
```
to get a 2D plot below this cell but I get instead the last 3D plot updated out of scale. 

With `%matplotlib inline` on the other hand i get all the static 3D plots and the 2D correct as well. This is what I'm using now but thought maybe is some bug useful to fix

I hope it is not that i did something wrong, I started to use the notebook recently so I may be missing something, please excuse me in that case.

**Comment by takluyver** [comment]
@tacaswell is there something special about 3D plots in mpl?

**Comment by tacaswell** [comment]
This is the expected and correct behavior, `plt.plot` adds to the current axes (which is this case is the 3D axes above).  You would get the same behavior in a terminal + a GUI backend.

It only looks like it works with inline because the display processes closes the figure and destroys the axes so getting the current axes always creates a new one.

**Comment by takluyver** [comment]
Thanks!

**Comment by cid0rz** [comment]
Thank you and forgive my ignorance then ^^
