### ISSUE TITLE
locating instructions for installing could be clearer

### ISSUE THREAD

**Issue by mikedewar** [jupyter/notebook#257]
So I scrolled up and down on the jupyter home page looking for an install button or link or something - its absence seemed sort of odd. Poking about I find the README in the notebook repo which is great but sorta terse (though to be honest worked great on OSX) and also found this link:

    http://ipython.org/ipython-doc/dev/install/install.html#installnotebook

which was a lot less than helpful, which I found by following the link at the top of the Jupyter docs:

    http://jupyter-notebook.readthedocs.org/en/latest/notebook.html#introduction

Seems like making INSTALL.md at the root of `jupyter/notebook` and linking to it from the homepage, or making a jupyter specific installation section in the `jupyter-notebook.readthedocs.org` would both be cool until a super smooth install process has been figured out...

Apologies if I missed an obvious link somewhere...

**Comment by takluyver** [comment]
Jupyter isn't officially released yet - for the moment, you should [install IPython](http://ipython.org/install.html).

We're preparing an [install overview page](http://jupyter.readthedocs.org/en/latest/install.html) for Jupyter.

**Comment by mikedewar** [comment]
I guess that, as Jupyter is (rightly) generating a lot of attention, I'm suggesting being clear about either how to install it or that one shouldn't install it just yet, right up front on the homepage.

**Comment by minrk** [comment]
That's a good point. We've been trying to get the docs ready for the imminent release, so their current contents are based on the state we will be in very shortly, where the current version of everything is 4.0. But it would have been a good choice for the docs in the intervening period to include a note about that being still in the future.

**Comment by takluyver** [comment]
I added a warning box to the install docs about that; it probably makes sense to do it on the website too

**Comment by minrk** [comment]
There's now an install link at the top of jupyter.org, which I think is prominent enough.
