### ISSUE TITLE
Logo alignment off on tree page

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#2575]
On master I see this:

![screen shot 2017-06-13 at 2 16 32 pm](https://user-images.githubusercontent.com/27600/27105040-f4ef703e-5042-11e7-9834-b3409a469a7a.png)

**Comment by takluyver** [comment]
I see this as well. `git bisect` points to 945a973da511d612aea282c1911f768ffc60caaf. @gnestor can you take a look?
