### ISSUE TITLE
Include floating sidebar w/dynamic Table of Contents

### ISSUE THREAD

**Issue by aok1425** [jupyter/notebook#2577]
## Pain point
When I do my exploratory data analysis in a notebook, I find that I want to go back up to a certain section, then go return to the cell I'm currently working on. To do this, I need to manually use the scroll bar and remember my previous and current positions.

## Feature request
Make a sidebar in the notebook that dynamically populates based on headings in my notebook. When I click on a sidebar heading, the notebook scrolls to that section.

Another idea is to have a Back functionality so that when I scroll up to the section I was in, I can hit Back to bring me back to the cell I'm currently working on. Not sure about how this would look UI-wise though.

## Misc
Advance apologies if this is already in Jupyterlab or the roadmap--I didn't see it when I took a quick look.

**Comment by avishapiro** [comment]
This had been part of the Jupyter notebook extensions for a while. There are quite a few other extensions that improve the notebook experience at https://github.com/ipython-contrib/jupyter_contrib_nbextensions.

**Comment by aok1425** [comment]
Ah, thank you.
