### ISSUE TITLE
Jupyter notebook not launching

### ISSUE THREAD

**Issue by dkendi** [jupyter/notebook#2580]
Very new to python, but have been using Jupyter notebook for last several months. Today it wouldn't launch. First line of error in Terminal (running this on Mac OS) is: [W 08:53:19.786 NotebookApp] Unrecognized JSON config file version, assuming version 1. Then several lines ending in: 0:42: execution error: "http://localhost:8889/tree" doesn’t understand the “open location” message. (-1708). Help?

**Comment by takluyver** [comment]
Apple broke something. Have a look at #2438.
