### ISSUE TITLE
Cannot save a notebook on a VPN connection

### ISSUE THREAD

**Issue by pwl** [jupyter/notebook#2583]
When I'm running a jupyter notebook server and connecting to it locally everything works fine but when I'm trying to connect to the same server remotely through a VPN strange things begin to happen.  As long as the notebook has only a single cell in it I can save/checkpoint it just fine but after I add another cell I can no longer saves the notebook.  There is no specific error showing, it just stops responding to the save button.

My config file is rather simple:

```
c.NotebookApp.ip = '*'                                                                
c.NotebookApp.open_browser = False                                                    
```

The logs I'm getting from the server:

```
$ jupyter notebook                                                                           
[W 09:53:01.059 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 09:53:01.073 NotebookApp] Serving notebooks from local directory: /home/pawel
[I 09:53:01.073 NotebookApp] 0 active kernels 
[I 09:53:01.073 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/?token=d8d4bbe970e7acfbb9d21304f8de73c01e6febce02385be8
[I 09:53:01.073 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:53:01.073 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=d8d4bbe970e7acfbb9d21304f8de73c01e6febce02385be8
[I 09:53:47.169 NotebookApp] Kernel started: d6c4225e-e5c3-457c-9b8a-4443130a71e9
[I 09:59:56.322 NotebookApp] Adapting to protocol v5.0 for kernel d6c4225e-e5c3-457c-9b8a-4443130a71e9
[W 10:01:01.348 NotebookApp] 404 GET /static/components/preact/preact.min.js.map (192.168.255.6) 2.27ms referer=None
[W 10:01:01.351 NotebookApp] 404 GET /static/components/proptypes/index.js.map (192.168.255.6) 2.23ms referer=None
[W 10:01:01.353 NotebookApp] 404 GET /static/components/preact-compat/preact-compat.min.js.map (192.168.255.6) 2.02ms referer=None
[I 10:01:03.425 NotebookApp] Adapting to protocol v5.0 for kernel d6c4225e-e5c3-457c-9b8a-4443130a71e9
[W 10:01:03.577 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170618095300 (192.168.255.6) 2.49ms referer=http://192.168.255.10:8888/notebooks/Untitled.ipynb?kernel_name=python3

```

Looks like I'm missing some extensions, I guess they must be built-in because I have not enabled nor installed any extensions on my own.

In the firefox debug console, when I'm saving a notebook with a single cell I see

```
GET XHR http://192.168.255.10:8888/api/contents/Untitled.ipynb [HTTP/1.1 200 OK 32ms]
PUT XHR http://192.168.255.10:8888/api/contents/Untitled.ipynb [HTTP/1.1 200 OK 67ms]
POST XHR http://192.168.255.10:8888/api/contents/Untitled.ipynb/checkpoints [HTTP/1.1 201 Created 31ms]
```
but when I add a cell this changes to
```
GET XHR http://192.168.255.10:8888/api/contents/Untitled.ipynb [HTTP/1.1 200 OK 33ms]
PUT XHR http://192.168.255.10:8888/api/contents/Untitled.ipynb
```
so there is no response to PUT and the POST never comes.  You can find the complete logs [here](https://gist.github.com/pwl/fa8dafed0ed340ef0a40931edb5bea46).

I would be happy to send more detailed logs.  As i already mentioned it all seems to work when I'm connecting to the notebook directly from the computer serving it and it is only a problem for remote connections.

I installed jupyter notebook through an Archlinux [package](https://www.archlinux.org/packages/community/any/jupyter-notebook/) and the version number is
```
$ jupyter notebook --version
5.0.0
```

**Comment by pwl** [comment]
I also tested it with `jupyter/tensorflow-notebook` docker image, with the same result.  Now I think this could be caused by my VPN configuration, although it's not obvious to me what's going on.

**Comment by takluyver** [comment]
![wat](https://user-images.githubusercontent.com/327925/27333938-8610ac46-55bf-11e7-8e65-fea386cd1716.jpg)

The only thing I can think of is that something is imposing a really low maximum request size, e.g. 1 KB. But that would surely break loads of things.

**Comment by pwl** [comment]
I would be happy to provide more logs, just let me know what would help.

I tested it once again on a docker image with `--debug` flag on, [here](https://gist.github.com/pwl/44703b5a5615cbcf4dc8eb4b6e77196c) is what I'm getting on the jupyter server side.  You can see that at the end I saved the notebook successfully and then I added some cells (this seems to register too) and then when I try to save the notebook, the server only prints the `GET` request with `PUT` and `POST` missing, which is consistent with the firefox logs.

I am at a complete loss as to what is going on here.  The VPN connection seems very stable otherwise, I'm using ssh and other http services without any issues whatsoever.

**Comment by takluyver** [comment]
Is it possible that something blocks PUT requests? They're less common than GET and POST, but still not exactly unusual.

The GET request you see is to check the last-modified time of the file on disk against the last save, in case the file has been changed by something else. The PUT request does the actual save, and the POST request creates a checkpoint after a manual save (you shouldn't see this one after an autosave).

**Comment by pwl** [comment]
I finally fixed it by switching the openvpn configuration to a TCP protocol.  The UDP must have been losing the packets somewhere on the way.  Crazy bug, in the end unrelated to jupyter notebook.  Sorry for spamming the issue list here but it only showed up when I was using the notebook, so I reported it here.  Thanks for all the suggestions @takluyver !

**Comment by lababidi** [comment]
@pwl I'm getting a similar issue but through TCP. I'm unable to run a cell and get back an output. This happens on a print statement even.

**Comment by abast** [comment]
I also had problems saving a jupyter notebook through an UDP vpn connection. I could resolve this issue by reducing the MTU parameter in the vpn configuration.
