### ISSUE TITLE
Unfriendly default setting???

### ISSUE THREAD

**Issue by mythsman** [jupyter/notebook#2585]
When I  click on my 'foo.md' file , the default page is 'localhost:8888/view/foo.md' . 
But what I want is absolutely l'ocalhost:8888/edit/foo.md' , So I have to change it manually every time.
I referred to the documentation but I didn't find any configuration about it ....
I remember that many versions ago ,the setting is just right ...
Will anyone do me a favor ? Thanks a lot.

**Comment by takluyver** [comment]
I can reproduce this. @gnestor do you have time to investigate?

Workaround: select the .md file with the checkbox, click the edit button at the top of the list.

**Comment by mythsman** [comment]
Well , the problem is if the filename is non-ascii ,  i.e. chinese words , when i click on the edit button , i just get a 404 .....

**Comment by takluyver** [comment]
Looks like the URL is getting double-encoded.

**Comment by mythsman** [comment]
Exactly ! "３２"  --> "%ef%bc%93%ef%bc%92" --> "%25ef%25bc%2593%25ef%25bc%2592"

**Comment by takluyver** [comment]
#2588 should fix the double-encoding issue, at least.

**Comment by takluyver** [comment]
There's still the issue with clicking on `.md` files - I think they should open in the editor by default if possible.

**Comment by gnestor** [comment]
https://github.com/jupyter/notebook/pull/2449 should resolve this among several other issues related to the "View"/"Edit" buttons and default paths for opening files in the dashboard.

**Comment by takluyver** [comment]
Thanks @gnestor
