### ISSUE TITLE
Markdown cells extremely slow: too much recursion error

### ISSUE THREAD

**Issue by jhelie** [jupyter/notebook#2586]
Converting a cell to markdown (via the drop down menu) and then executing it to display the text have both become extremely slow operations (in the order of minutes).

Notebook version:
```
> jupyter notebook --version
4.4.1
```

Browser: issue seen in both firefox 54.0 and Chrome 59.0

Inspecting the console shows:
```
Exception in event handler for rendered.MarkdownCell InternalError: too much recursion
Stack trace:
[object Object] Arguments { 0: "rendered.MarkdownCell", 1: Object, 2 more… }  main.min.js:15352:13
```

**Comment by jhelie** [comment]
Closing this as the issue seems to have disappeared after upgrading to `5.0.0`

**Comment by mpacer** [comment]
Is this true for all code cells to markdown cells or only particular ones.

E.g., if you have a single line with only a python comment, does that
conversion to a header take order of minutes?

**Comment by jhelie** [comment]
@mpacer I'm on 5.0.0 and can't readily downgrade for testing this but the issue I had occurred for all cells: conversion to markdown and then execution both took several minutes regardless of content.

**Comment by mpacer** [comment]
Well I'm glad the issue is fixed!
