### ISSUE TITLE
Issue Creating New Notebooks in IE only

### ISSUE THREAD

**Issue by blakep2012** [jupyter/notebook#2594]
I have an application that is framing user servers spawned by SystemUserSpawner. The notebook servers are configured to use no-tab mode in order to keep everything within the frame.

The issue arises when a user wants to create a new notebook. Upon selecting which kernel to use for their new notebook, the user is presented with a 404 page. This only occurs if the user is using Internet Explorer. Chrome and Firefox work perfectly, as does Microsoft Edge on Win10.

The logs and network traffic indicate that there is a GET request being fired on /user/<username>/undefined. This request obviously returns a 404 because undefined doesn't exist. After this call the normal, expected POST request to create the notebook is fired, and returns successfully; however, the 404 page doesn't re-route to the new URL. The network logs are as follows:

![image](https://user-images.githubusercontent.com/2753958/27398248-be9f8c70-567e-11e7-8423-c1af8cc820bd.png)

The relevant notebook server logs are: 
```
[I 2017-06-21 16:59:47.036 [username] log:47] 302 GET /user/[username] (172.17.0.1) 0.62ms
[I 2017-06-21 16:59:47.138 [username] log:47] 302 GET /user/[username] (10.45.141.204) 0.48ms
[W 2017-06-21 16:59:58.151 [username] log:47] 404 GET /user/[username]/undefined (10.45.141.204) 6.47ms referer=None
[I 2017-06-21 16:59:58.450 [username] handlers:170] Creating new notebook in
```

In both of these examples we can see the GET firing before creation. The odd thing to me is the fact that this initial GET request is _never_ called in Chrome or Firefox.

I've also ran IE tests outside of the frame in default tabbed mode and I get the same results. The new tab that is created displays the 404 page; however, sometimes the 404 page will re-route itself to the correct URL after the notebook is created.

I've dug around in the source code to attempt to find what might be causing this rogue GET request, but I was unable to pinpoint it.

Any help on this subject would be greatly appreciated. Thanks.

**Comment by birdsarah** [comment]
Just to note that @jsignell and I are also experiencing the same issue.

**Comment by birdsarah** [comment]
This may be related to #388

**Comment by jtpio** [comment]
Closing as IE is not a supported browser anymore.

Please consider using Edge, Chrome of Firefox, thanks!
