### ISSUE TITLE
notebook functionality (cell level, basic text search, rendered view etc..)

### ISSUE THREAD

**Issue by ghost** [jupyter/notebook#261]
Some of these things got referenced in other issues but these are my collection of common things that would be nice to haves (wishlist):

So everyone talks about that latest and greatest like RT collab and widgets but getting back to basics and things that make me go arrr(literally).

-Basic search and replace - I want to rename a variable in an entire nb (frequently)
-Easily delete/move group of cells - Useful for cutting a nb into two parts
(I'm guessing in the new UI, click and drag cells around is possible??)
-Renumbering of cells - okay so I guess I could restart kernel.

Okay, so most of the above things would make workflow nicer.
-not having to open a bulky IDE
-not having to convert to a text format and back (the hacky way)

Really loving IPython/ nb. Thanks for your all your work:) Recently discovered some useful magic functions that improved my workflow too. Cheers.
# 

Edit on Aug 8:
To clarify, I am actually not opposed to IDE or IDE-like features in either a stand alone app or web interface that works well with interactive workflow.. For a lot of R work, I use the popular IDE because it's easy to go back and forth between formats while doing iterative analysis with output view and console all in one screen. Some natural workflow from writing/editing to sharing and collaboration on the web!

**Comment by hellpanderrr** [comment]
>-Basic search and replace - I want to rename a variable in an entire nb (frequently)
>-Easily delete/move group of cells - Useful for cutting a nb into two parts

Yes, that would be great.
>-Renumbering of cells - okay so I guess I could restart kernel.

You also could use Cell -> All Output -> Clear
>Recently discovered some useful magic functions that improved my workflow too.

Check out this also: https://github.com/jupyter/notebook/issues/174

**Comment by nymoorland** [comment]
Looks like this codemirror js text editor referenced in #174 has search functionality. Neat. 
http://codemirror.net/doc/manual.html#addon_search

**Comment by Carreau** [comment]
Hi, 

thanks for your mail. 

Your request is spot on, we had a (non public) meeting with a few of us, on Tuesday, and we will try to implement some of theses things for 4.1 possibly. The search and replace is tricky as it is on many codemirror instances at once. 

If some of you want to try to tackle the search and replace, we can give you hints on where to start patching the notebook.

**Comment by juhasch** [comment]
You might want to take a look at this:
https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/search-replace

**Comment by nymoorland** [comment]
@Carreau 
> Your request is spot on, we had a (non public) meeting with a few of us, on Tuesday, and we will try to implement some of theses things for 4.1 

Thanks Matthias! This will certainly help improve workflow for common tasks.

@juhasch 

> https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/search-replace

Oh I see you created this extension. I will try it out soon. In fact, thanks for pointing out that repo. I wonder if it can be patched into the 4.1 release?

@hellpanderrr 
Thanks for pointing out that codemirror site referenced.

**Comment by Carreau** [comment]
> Oh I see you created this extension. I will try it out soon. In fact, thanks for pointing out that repo. I wonder if it can be patched into the 4.1 release?

I haven't looked at the extension internals, but I'm not against it.

**Comment by nymoorland** [comment]
With respect to the interactive workflow, being able to interactively edit a document with a rendered view while working on it would be desirable. Right now, it's pretty clunky process to convert from one format, edit, make changes and convert back. I guess I should make this as a separate but known paint point. I should probably update the title to bucket wishlist/points!

**Comment by JamiesHQ** [comment]
We're doing a little housekeeping on our issue log and I noticed this thread from 2015. The original creator of this issue is showing as "deleted user" in GH and so we are closing the issue. If you are the original creator of the issue and are still following the thread under another username, please let us know if the issue been resolved to your satisfaction! thanks!
