### ISSUE TITLE
Notebooks are not shown in Files inside a folder "0"

### ISSUE THREAD

**Issue by cbrnr** [jupyter/notebook#2611]
I just stumbled upon a weird bug. To reproduce, start up `jupyter notebook` and create a new folder called `0`. Change into that folder and create a new notebook (it doesn't matter what it's called). Save the notebook and go back to the Files view. Notebooks don't show up in this `0` folder.

Here's the file structure:

    test/
      0/
        test.ipynb

So in this example, `test.ipynb` doesn't show up in the Files list.

**Comment by takluyver** [comment]
Nice find. I tracked it down to a corner case in the Javascript. It also affects a directory called `false`. #2625 should fix it.
