### ISSUE TITLE
Download large file (>5GB)

### ISSUE THREAD

**Issue by nabriis** [jupyter/notebook#2620]
Hi,

After trying to download a large zip file from the jupyter notebook UI (from a server using jupyterhub 0.7.2 and nginx proxy) i got an 504 Gateway Time-out error from nginx and now i can't access the server again.

Similar thing happends if i accidentally click on a large zip file and it opens in a new browser tab e.g.
https://[hostname.com]/user/[linuxuser]/view/largefile.zip will crash my connection to the server

Restarting the server makes me able to access the server again. Others can still access the server.

**Comment by vharsh** [comment]
Looks relevant.
#96

**Comment by nicolairiis** [comment]
The Jupyter notebook is version 5.0.0. I was using Google Chrome to test the download.

In reference to #96 , I am able to upload large files using the built in UI for uploading.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
