### ISSUE TITLE
Jittery scrolling in Safari and other browsers

### ISSUE THREAD

**Issue by AlexanderEkdahl** [jupyter/notebook#2622]
I've tracked down the reasons for the jittery scrolling. For some reason, the height on the `#site` element is set every time scrolling happens which invalidates the styles and forces a repaint and recomposition instead of just recomposition. From what I can tell this is completely unnecessary  and removing the JavaScript which does this does not have any adverse effects.

**Comment by takluyver** [comment]
Do you want to open a PR? There may be a reason the code needs to be there (browser compatibility leads to all sorts of oddities), but it will be easier to evaluate your proposal as a PR.

**Comment by AlexanderEkdahl** [comment]
I tried but ran into problem when building the project. I will give it another attempt. The `height` is there for a reason but there are other ways of achieving the same effect.

I'll give it another shot this weekend!

**Comment by takluyver** [comment]
If you haven't already seen it, the docs have a section on setting up a development environment:

http://jupyter-notebook.readthedocs.io/en/latest/contributing.html#setting-up-a-development-environment

**Comment by MatthewSteen** [comment]
I'm also experiencing poor scrolling after a recent update that lags and is slow on Chrome. Here's what I have installed.

> ipykernel                 4.5.0                    py27_0  
ipython                   5.1.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
jupyter                   1.0.0            py27h9d2e098_2  
jupyter_client            4.4.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.2.0                    py27_0

**Comment by ttpostle** [comment]
Any suggestions on how to fix this jittery scrolling issue in Chrome?
