### ISSUE TITLE
Download As Python failed

### ISSUE THREAD

**Issue by vc12345679** [jupyter/notebook#2623]
Need help for this problem

## Problem Description
1. **'Download As Python' fails**. In browsers (IE/Chrome), 'Download As Python' returns 500 Internal Server Error, saying "nbconvert failed: [Errno 13] Permission denied: '.\\\\python'".
2. **other 'Download As' items work well**. In browsers (IE/Chrome), 'Download As Notebook/HTML/Markdown/reST/LaTeX/PDF via LaTeX' all work well.
3. **nbconvert works well in console**. In console (run as administrator), `D:\Anaconda3\python3 -m nbconvert --to="python" D:\Documents\Jupyter\Untitled1.ipynb` works well.

## Environment
* Windows 10 Pro 64bit, 1073, 15063.447
* Python 3.6.1 :: Anaconda custom (64-bit) installed at 'D:\Anaconda3'
* ipython 6.1.0
* jupyter 1.0.0
* jupyter-client 5.1.0
* jupyter-console 5.1.0
* jupyter-core 4.3.0
* nbconvert 5.2.1
* nbformat 4.3.0
* Jinja2 2.9.6
* 'Jupyter Notebook' process is run as administrator, with `--notebook-dir="D:\Documents\Jupyter"`
* 'notebook-dir' directory (D:\Documents\Jupyter) is readable, writable and excutable

## Trace Log
```
[E 02:11:09.632 NotebookApp] nbconvert failed: [Errno 13] Permission denied: '.\\python'
    Traceback (most recent call last):
      File "D:\Anaconda3\Lib\site-packages\notebook\nbconvert\handlers.py", line 104, in get
        "config_dir": self.application.settings['config_dir'],
      File "D:\Anaconda3\Lib\site-packages\nbconvert\exporters\script.py", line 49, in from_notebook_node
        return exporter.from_notebook_node(nb, resources, **kw)
      File "D:\Anaconda3\Lib\site-packages\nbconvert\exporters\templateexporter.py", line 283, in from_notebook_node
        output = self.template.render(nb=nb_copy, resources=resources)
      File "D:\Anaconda3\Lib\site-packages\nbconvert\exporters\templateexporter.py", line 111, in template
        self._template_cached = self._load_template()
      File "D:\Anaconda3\Lib\site-packages\nbconvert\exporters\templateexporter.py", line 254, in _load_template
        return self.environment.get_template(template_file)
      File "D:\Anaconda3\Lib\site-packages\jinja2\environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "D:\Anaconda3\Lib\site-packages\jinja2\environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "D:\Anaconda3\Lib\site-packages\jinja2\loaders.py", line 405, in load
        return loader.load(environment, name, globals)
      File "D:\Anaconda3\Lib\site-packages\jinja2\loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "D:\Anaconda3\Lib\site-packages\nbconvert\exporters\templateexporter.py", line 75, in get_source
        return self.loader.get_source(environment, template)
      File "D:\Anaconda3\Lib\site-packages\jinja2\loaders.py", line 171, in get_source
        f = open_if_exists(filename)
      File "D:\Anaconda3\Lib\site-packages\jinja2\utils.py", line 154, in open_if_exists
        return open(filename, mode)
    PermissionError: [Errno 13] Permission denied: '.\\python'
[W 02:11:09.647 NotebookApp] 500 GET /nbconvert/script/Untitled1.ipynb?download=true (::1): nbconvert failed: [Errno 13] Permission denied: '.\\python'
```

**Comment by takluyver** [comment]
That looks like it's finding a file called `'python'` which it doesn't have permission to read. What's the working directory the notebook server is run from?

**Comment by vc12345679** [comment]
@takluyver I just started Jupyter Notebook from Start Menu shortcut, located at
"C:\Users\xxx\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)\Jupyter Notebook".

The shortcut targeted to `D:\Anaconda3\python.exe D:\Anaconda3\cwp.py D:\Anaconda3 "D:/Anaconda3/python.exe" "D:/Anaconda3/Scripts/jupyter-notebook-script.py" --notebook-dir="D:\Documents\Jupyter"`
I manually added this argument ` --notebook-dir="D:\Documents\Jupyter"` to the end.
The working directory of the shortcut was left blank.

### Two solutions

#### 1 not general
I happened to find that changing the target to `D:\Anaconda3\python.exe "D:/Anaconda3/Scripts/jupyter-notebook-script.py" --notebook-dir="D:\Documents\Jupyter"` instead could solve this problem.
But it might not be a general solution for those who want to specify interpreter or virtualenv.

#### 2 recommended
Thus I tried another solution. Setting `c.NotebookApp.notebook_dir =` in `jupyter_notebook_config.py` instead of adding `--notebook-dir=` in the shortcut target, and then 'Download As Python' worked. I did not need to modify the original shortcut anymore.

### A guess
So I suppose, adding `--notebook-dir=` argument to the original shortcut to specify startup notebook directory may lead to some unexpected mistakes.

**Comment by takluyver** [comment]
Weird, I don't know why specifying it in the command line versus the config file would make any difference to that. I'm glad you got it working, though.

**Comment by vc12345679** [comment]
Of the following two commands,
`D:\Anaconda3\python.exe D:\Anaconda3\cwp.py D:\Anaconda3 "D:/Anaconda3/python.exe" "D:/Anaconda3/Scripts/jupyter-notebook-script.py" --notebook-dir="D:\Documents\Jupyter"`
V.S.
`D:\Anaconda3\python.exe "D:/Anaconda3/Scripts/jupyter-notebook-script.py" --notebook-dir="D:\Documents\Jupyter"`

'Download As Python' in the latter one works well, while doesn't work properly in the former one. That's really weird.

**Comment by takluyver** [comment]
I bet it's something related to Anaconda's `cwp.py` script, but I'm not sure what that doe.

**Comment by vc12345679** [comment]
@takluyver After reading `cwp.py`, I find it doesn't pass the `**kargs` to the subprocess of Jupyter.
I believe that's the key to this problem. I've submitted a [issue](https://github.com/ContinuumIO/anaconda-issues/issues/2954) to Anaconda.

**Comment by BEswarKumar** [comment]
Hi I am getting below error message when running jupyter notebook.  kindly help me to resolve.

Script file 'C:\Users\BK5028313\AppData\Local\Continuum\anaconda3\Scripts\jupyter-notebook-script.py' is not present.

tried installing script file but received no packages are available.
