### ISSUE TITLE
zmq message arrived on closed channel, ... waiting for kernel to be available...

### ISSUE THREAD

**Issue by Martin729** [jupyter/notebook#2627]
I installed Anaconda and I opened Jupyter notebook in the Anaconda prompt by running `jupyter notebook`, but I could not get the output information. The information is as follows:
```
About Jupyter Notebook
Server Information:

You are using Jupyter notebook.

The version of the notebook server is 5.0.0 and is running on:
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]

Current Kernel Information:

Waiting for kernel to be available...
```
I guess something is wrong with the kenel, but I don't know how to solve the problem. Could someone help me? I would appreciate it very much.

**Comment by takluyver** [comment]
Any messages in the command prompt you launched it from that might indicate what the problem is?

**Comment by Martin729** [comment]
Yes. It says `zmq message arrived on closed channel`. I am using windows10 64bits.
```
[I 23:08:51.022 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=90f3ba9eb3d1e01310d3b1a2c201674be7985756b6b02bb4
[I 23:08:51.023 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:08:51.028 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=90f3ba9eb3d1e01310d3b1a2c201674be7985756b6b02bb4
[I 23:08:51.431 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 23:08:57.807 NotebookApp] Creating new notebook in /Desktop
[I 23:08:58.336 NotebookApp] Kernel started: 239d3d49-d716-4341-baa7-a4784259b921
[W 23:08:59.849 NotebookApp] zmq message arrived on closed channel
[W 23:09:21.226 NotebookApp] zmq message arrived on closed channel
```

**Comment by takluyver** [comment]
@minrk does that ring any bells?

**Comment by Martin729** [comment]
I solved the problem after exiting 'Kaspersky Endpoint Security 10 for Windows' as suggested in the following [link](https://stackoverflow.com/questions/35486586/jupyter-with-anaconda-on-windows-will-not-run-cells/35563597). Thanks.

**Comment by takluyver** [comment]
Ah, security software strikes again. Probably not much we can do about that.

**Comment by h3ct0rjs** [comment]
@takluyver is necesary to open a specific port?

**Comment by takluyver** [comment]
Sorry, I don't really know of a fix - we've had problems with a variety of different security packages, and probably various different versions. The problem usually seems to be that they find websocket connections suspicious for some reasson.

**Comment by h3ct0rjs** [comment]
@takluyver Actually I'm testing this in a private remote server with high security measures, my problem seems to be with zmq,I'm checking the official doc in how to handle something like this but I could'nt find anything, the only open port available are 8888 and 8000 to test jupyter

**Comment by takluyver** [comment]
It doesn't need other ports open on external interfaces, but it does use other ports on the loopback interface to talk to kernels. If the security measures block that, it would cause problems. Those ports are randomly assigned, so there's no specific number to open.

If you suspect that's the problem and you can't lower the security, it's possible to configure it to use Unix sockets to talk to the kernel, if you're on a Unix-y system. I forget how to do that, though. Min probably knows.

**Comment by gadcam** [comment]
Avira seems to have the same behavior. What should we do to solve this problem besides of disabling it ?

**Comment by h3ct0rjs** [comment]
Hi @gadcam When I was having this trouble I solved this mounting a linux container. I don't know your current arch but may be you can add a new antivirus whitelist rule.
