### ISSUE TITLE
Why no find and replace in python notebooks?

### ISSUE THREAD

**Issue by abrahamneben** [jupyter/notebook#263]
Why does the jupyter text editor have find and replace, but the python notebook does not? This is a needed feature!

**Comment by Carreau** [comment]
Please see other related issues, like #261 posted 14 h ago, which is on the top of the list. 

Search and replace on many cells at once is a little bit trickier than in only one. And as in any open source project someone have to do the work.

If you want to try to tackle it, we can give you pointer. 

(please continue comment on other issues not to keep thing spreaded),

Thanks !

**Comment by mishabello** [comment]
Yes, please, give me a pointer.

**Comment by Carreau** [comment]
ON master you can do `Ctrl-shift-P` (`cmd` on mac) filter for search and replace, then you should get a search and replace dialog. It needs improvement though. 

Once you have it working I can point you to the relevant bit of code if you want to tinker with it.

**Comment by mishabello** [comment]
I got it working and it is very nice. What improvements do you have in
mind? What part of the code needs to be changed?

**Comment by Carreau** [comment]
IIRC, one of the request was the ability to unselect each replacement individually, something like  a checkbox on the side of each replacement. 

Also there is non "pure search", it would be nice if the replacement is empty to actually just hightlight all the matchings, and have a shortcut to scroll to next match, or select next match/ select previous match.

**Comment by ggrrll** [comment]
Hi, 

(I don't know if this is the right place to ask )

is there/ do you plan to add  a quick shortcut that allows me to quickly find the selected work 
- like in sublime text, for instance - _without_ having to type 3 cmd+C, cmd+F,cmd+V

Thanks for your help

**Comment by ggrrll** [comment]
pps: another nice feature would be to make the results of the 'find-window' clickable, in a way that re-send you directly to  the corresponding line/cell in the notebook

**Comment by Arsova** [comment]
Maybe it is late to add a comment but just in case :  the command Esc+F in one of the cells will bring a simple find and replace a window in Jupyter Notebook.

**Comment by Quetzalcohuatl** [comment]
If you want to find an replace in every cell, please see this post. https://stackoverflow.com/questions/49933535/how-can-i-select-every-cell-in-an-ipython-notebook Basically, you have to click an extra button if you want to perform find+replace on every cell.

**Comment by eromoe** [comment]
How can I bind `ctrl+shift+f` to `find and replace on every cell` ???
There is only a function 

Jupyter.keyboard_manager.command_shortcuts.add_shortcut('s', 'jupyter-notebook:find-and-replace');

**Comment by matt-proof** [comment]
This became available automatically in 2016: [link](https://blog.jupyter.org/notebook-4-1-release-37d6ae621f83#:~:text=The%20new%20Find%20and%20Replace,and%20replace%20action%20you%20specify.)
