### ISSUE TITLE
Long completions: e.g. path

### ISSUE THREAD

**Issue by kehey** [jupyter/notebook#264]
Can the path completion with tab be changed so that you do not always see the complete path so far in the pop-up, but only the further options? With long paths, the end of the path (which then contains the files I need to choose from) fall off the screen or I have to start scrolling.

**Comment by JamiesHQ** [comment]
@kehey : We're doing a little housekeeping on our issue log and I noticed this thread from 2015. Has this issue been resolved to your satisfaction and can it be closed? thanks!

**Comment by kehey** [comment]
I'm not sure it was ever resolved... Unless it was done in the last version that I haven't updated to yet.

**Comment by JamiesHQ** [comment]
@gnestor : was this resolved in the 5.0 release? thanks!

**Comment by gnestor** [comment]
This is what I currently see in notebook 5.0.0:

http://g.recordit.co/SqjGZKrgWj.gif

> Can the path completion with tab be changed so that you do not always see the complete path so far in the pop-up, but only the further options?

It appears like it's working as you would expect now. I'm going to close this but feel free to re-open if need be...

**Comment by takluyver** [comment]
That GIF still looks like the issue that was reported, AIUI. If this was fixed, the last time you summon the tab-completer dropdown, it would only show you the filenames, like `victory.ipynb`, instead of `./jupyterlab_react/victory.ipynb`.

**Comment by gnestor** [comment]
Oh, I see. Ok, let's re-open and mark as contributor-friendly.

**Comment by Zanadar** [comment]
I'd like to take a look at this one.  Any objections?

**Comment by gnestor** [comment]
@Zanadar By all means!!

**Comment by gnestor** [comment]
@Zanadar Any luck with this one?

@takluyver What do you suggest for this one? How do we classify a completion match as a path vs. not a path? If they are a path, remove `/.+\//`?

**Comment by takluyver** [comment]
I'm not sure that anything related to calculating completions really belongs under the 'good first issue' tag, unfortunately.

The code in question is in IPython. The function for finding file completions is here:

https://github.com/ipython/ipython/blob/cefab40bb755260ddec63efc24d8e1ea3b6fba06/IPython/core/completer.py#L1133

But it's a mess of regexes and special cases.

**Comment by gnestor** [comment]
I have created an issue on ipython for this. I'll take a stab at it...

**Comment by gnestor** [comment]
I tried implementing this in the notebook and one of the issues with trimming the full path for display in the completer is that when you select a completion suggestion (press ENTER or click on it), it replaces what you were typing with an incomplete path:

![](http://g.recordit.co/xilgNg43fi.gif)
