### ISSUE TITLE
Document kernel.js

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#265]
I can see the code to load kernel.js, but it doesn't seem to be mentioned in any docs yet.

**Comment by ellisonbg** [comment]
Is this obsoleted by juypyter-js-services?

**Comment by blink1073** [comment]
Hopefully :smile:  https://github.com/jupyter/jupyter-js-services/pull/36

**Comment by ellisonbg** [comment]
@blink1073 can you close this issue here when you merge that?

**Comment by blink1073** [comment]
I don't have access to close it.

**Comment by ellisonbg** [comment]
Ah, OK we can, just ping us...

On Tue, Oct 6, 2015 at 3:22 PM, Steven Silvester <notifications@github.com>
wrote:

> I don't have access to close it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/265#issuecomment-145971212>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
Will do.

**Comment by blink1073** [comment]
All set!
