### ISSUE TITLE
Enhancement: Option to allow serving from hidden directory

### ISSUE THREAD

**Issue by jendas1** [jupyter/notebook#2659]
```
[I 21:48:37.098 NotebookApp] Refusing to serve hidden directory, via 404 Error
```
Since iCloud Drive folder on macOS is reachable from user folder but it goes through hidden folder, I would love to have the ability to override the hidden directory restriction so I can view it (if the jupyter server has user folder as root).

**Comment by rolweber** [comment]
There is no configuration setting. The logic is implemented in various places of the FileManager. You could implement and configure your own FileManager to allow access to (some) hidden directories.

**Comment by artonimous** [comment]
I ran into the same issue trying to work on .ipynb's and seemed to be able to work around it with the following two approaches.
**Using Jupyter-notebook:** 
1. $ cd ~/Library/Mobile\ Documents/com~apple~CloudDocs
2. $ jupyter-notebook
OR
**Using the JupyterLab Alpha Preview interface** the somewhat more recursive, solution:
1. From Anaconda Navigator launch a JupyterLab session
2. Within the lab open an terminal session
3. $ cd ~/Library/Mobile\ Documents/com~apple~CloudDocs
4. $ jupyter-lab

Initial test seem fine using either of these approaches but comments/feedback on the limitations or a more effective/stable approach would be appreciated.

**Comment by artonimous** [comment]
Forgot this is markdown - ignore the strike through on the paths in the previous comment

**Comment by takluyver** [comment]
There is now a config option `ContentsManager.allow_hidden` to allow serving hidden files. They're still hidden from the list in the dashboard, but you can access them by URL. Added in https://github.com/jupyter/notebook/pull/2819

**Comment by wenmin-wu** [comment]
starts the notebook with this command: `jupyter notebook --ContentsManager.allow_hidden=True`
