### ISSUE TITLE
Output area height is rounded when fixing height on clear

### ISSUE THREAD

**Issue by jasongrout** [jupyter/notebook#2668]
In https://github.com/jupyter/notebook/blob/5192d72c63369d7167c5472d06f87072d68ecc53/notebook/static/notebook/js/outputarea.js#L969, we use jquery to find and fix the height of an output area in order to prevent jumpiness when clearing an output area. However, the jquery `.height()` function rounds the height to the nearest integer, which causes some jitter. It would be better to use `.getBoundingClientRect().height`, which doesn't round the height.

**Comment by jasongrout** [comment]
@gnestor - is it too late for me to put in a quick PR for this before 5.1?

**Comment by gnestor** [comment]
No, go ahead, I'm still working through some remaining issues 👍
