### ISSUE TITLE
Jupyter Notebook not installed

### ISSUE THREAD

**Issue by DebasishSR** [jupyter/notebook#2669]
I am installing Anaconda3-4.4.0 in windows 10 machine. Entire suite is getting installed except Jupyter notebook and rstudio. Hence from command prompt, when I type jupyter notebook, it is unable to find it.

I opened Anaconda navigator & from there separately tried to install jupyter notebook. Installation started & at right end down corner blue coloured scroll bar started shoing some progress. But after sometime, it seem that it got stuck there as it effectively show no progress & endlessly went on. I force-closed the Anaconda navigator window & re-started it & again tried to install but again it kept trying for endless period & finally no result.

Any clue or help ?

**Comment by takluyver** [comment]
In an Anaconda command prompt, can you try `conda install jupyter` and see what happens?

**Comment by DebasishSR** [comment]
Thanks takluyver. I tried now that ('conda install jupyter' command in Anaconda command prompt. Got the below error test - 

Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001F09B0D8208>, 'Connection to repo.continuum.io timed out. (connect timeout=9.15)'))",),)

**Comment by takluyver** [comment]
Are you connected to the internet when you do this? If you are, then you'll need to ask for support with conda, e.g. https://github.com/conda/conda/issues

**Comment by DebasishSR** [comment]
OK, I just logged this issue to the portal you mentioned.

**Comment by takluyver** [comment]
Thanks! I'll link it here for other people who might read this: https://github.com/conda/conda/issues/5702

And I'll close this issue, since there's nothing we (Jupyter) can do about it.
