### ISSUE TITLE
Huge amount of requests to favicon-busy.ico

### ISSUE THREAD

**Issue by sasdf** [jupyter/notebook#2673]
Kernel switch between idle and busy status very quickly while using interactive plot(`%pylab notebook`). It will generate many http requests to `favicon-busy.ico`.  Even just move the cursor over a interactive plot can generate about 40 requests in a second.  This kind of network traffic may trigger some firewall system because it looks like we're attacking the server.

This behavior was found in current pip version, but not in the version on tmpnb.
I install jupyter by `pip3 install jupyter --user`

**Comment by takluyver** [comment]
Yikes, I had assumed the browser would cache that, but it looks like it makes a new request each time the favicon changes. Even worse, in master we're doing an animation in Javascript, so it repeatedly requests `favicon-busy-1.ico` and `favicon-busy-3.ico` in alternation while the kernel is busy.

**Comment by takluyver** [comment]
#2675 removes the animation part of it. For the main part of it, I see a few possible options:

a. Get rid of the busy favicon change entirely
b. Debounce it, so it only changes to busy if it's been busy for e.g. 1 second.
c. Find some way to change it without causing new HTTP requests, e.g. using data URLs.

**Comment by takluyver** [comment]
#2687 aims to mitigate this by only changing the icon when execution lasts > 1 second.
