### ISSUE TITLE
Terminal has misaligned header-container

### ISSUE THREAD

**Issue by invisibleroads** [jupyter/notebook#2686]
The terminal in 38b789a7d8fa521266b3aba85c2d49bf104e3622 has a header-container that is much narrower than the terminal window.

It seems to be related to the recent change to flexbox sizing for header-container.
https://github.com/jupyter/notebook/blob/master/notebook/static/base/less/page.less#L30

**Comment by takluyver** [comment]
@gnestor can you take a look? Sorry - you stand a better chance of fixing this without breaking something else than I do.

![screenshot from 2017-07-26 09-39-41](https://user-images.githubusercontent.com/327925/28612214-6b02b712-71e6-11e7-89b4-3675f53b7c4c.png)

**Comment by gnestor** [comment]
No prob! See https://github.com/jupyter/notebook/pull/2692 for a fix 👍
