### ISSUE TITLE
How to make jupyter console reuse a kernel file?

### ISSUE THREAD

**Issue by reckoner** [jupyter/notebook#2690]
When starting `jupyter console`, is there a way to make it use the same `kernel.json` file. Every time I start it creates a new random `kernel-*.json` and I would prefer it use the same file repeatedly.

**Comment by takluyver** [comment]
If you want it to share a kernel with other consoles, so it sees the same variables, use the `--existing` flag when launching it.

**Comment by reckoner** [comment]
Thank you for your response. Yes, I am aware of the `--existing` flag but that's not what I'm interested in. The kernel.json file is full of port and connectivity information and has a randomly generated filename. I'm trying to reuse an existing kernel.json when `jupyter console` starts. In other words, every time I do  `jupyter console` I want to use an *existing* kernel.json, not create a new one with a randomly generated file name. 

I hope that makes more sense.

**Comment by takluyver** [comment]
Unless I'm misunderstanding you, that's what the `--existing` flag does. Using the same connection file necessarily means you're also using the same kernel.

**Comment by reckoner** [comment]
Thank you for your patience. My understanding is that `--existing` works with a session that has already been started. I would like to start a *new* session with an existing kernel.json. Thus, there would be no pre-existing session in this case.

**Comment by takluyver** [comment]
Is the issue that it's failing to clear up the connection files when you exit the console?

**Comment by reckoner** [comment]
Suppose I did the following: 

1. start `jupyter console` 
1. do `%connect_info` and save the output in the file `my_kernel.json`. 
1. shutdown `jupyter console`

Then, the next time I fired up `jupyter console`, it would have a different output for `%connect_info`, right? That's exactly what I *do not* want. If I try to do `jupyter console --existing my_kernel.json`, then it would fail because none of the backend ZMQ processes have been organized with connection information embedded in the `my_kernel.json` file. What I *do* want is for my next session of `jupyter console` to use the port and ZMQ connection info saved in my `my_kernel.json` file. Thus, the new session would somehow have to start up ZMQ infrastructure according to the contents of the `my_kernel.json` file.

Thanks for your patience with this question.

**Comment by takluyver** [comment]
When you shut down the console, it will normally clean up the connection file it created, so it won't be there for the next kernel to refer to.

What do you want it to do if you try to start two consoles at once? Use the same kernel, or refuse to start?

I think you could write a script that does something like this:

```bash
python -m ipykernel_launcher -f my_kernel.json &
sleep 1
jupyter console --existing my_kernel.json
```

That will try to start a new kernel using your connection file, and then open a console connected to the new kernel (or the old one if one already existed).

I'm not sure why you want this, though. What are you trying to achieve? Why do the connection files matter?

**Comment by reckoner** [comment]
Thanks! This is exactly what I was looking for. I work in a very restricted network environment so I have to hopscotch  between ports and networks to reach my IPython processes. This method should make that a lot easier to work with. 

Thanks again.
