### ISSUE TITLE
Feature: Margin comments

### ISSUE THREAD

**Issue by brylie** [jupyter/notebook#272]
As a notebook collaborator,
I would like to add margin notes or comments
so that I can easily discuss specific sections of a given notebook with collaborators, in context

**Comment by juhasch** [comment]
You can take a look here:
https://github.com/ipython-contrib/IPython-notebook-extensions/tree/3.x/usability/annotations

**Comment by minrk** [comment]
Thanks, @juhasch! A great case for extensions.
