### ISSUE TITLE
file editor should warn if file changes on disk

### ISSUE THREAD

**Issue by cancan101** [jupyter/notebook#2726]
I have a file editor open for a certain file. That file changes on disk. There should be a warning of some sort in the web editor that this has happened to prevent saving over the modified data.

**Comment by minrk** [comment]
We already have exactly this check for notebooks, so doing the same for edit should be doable.

**Comment by unnamedplay-r** [comment]
Hi @minrk, I'd like to take on this issue. I'm a first time contributor here, so any pointers to relevant architecture for this issue would be great!

**Comment by minrk** [comment]
Hi @unnamedplay-r! The first step would be to look at how the notebook [implements the check_last_modified logic](https://github.com/jupyter/notebook/blob/5.0.0/notebook/static/notebook/js/notebook.js#L2653). Then the task would be to copy the relevant bits of that (or refactor it a bit to make it re-usable) to where [edit implements save](https://github.com/jupyter/notebook/blob/5.0.0/notebook/static/edit/js/editor.js#L157).

**Comment by unnamedplay-r** [comment]
Thanks for the help here @minrk. I'll give it a whirl this weekend. Should pull requests be submitted as WIP's, or submit upon completion? I can't seem to find any documentation on pull requests.

**Comment by takluyver** [comment]
Submitting a WIP is fine, just let us know in the description.

**Comment by jonalloub** [comment]
Hi, I'm @jonalloub, and I am new to contributions on open source software. I see that someone is already taking a stab at this problem, but since it is still open, can I take a stab at it as well?

**Comment by takluyver** [comment]
Hi @jonalloub! There's already an open PR for this (#2783), and it looks like it's still active, so it may be best to find another issue. We should try to help get that PR complete, though.
