### ISSUE TITLE
Jupyter launchers

### ISSUE THREAD

**Issue by PawelKozela** [jupyter/notebook#273]
Just installed the new version on a Windows machine and noticed that it doesn't create the .exe in the python/scripts directory - only the files without extension (jupyter, jupyter-notebook). Hence the jupyter notebook command doesn't work.
Tried python jupyter notebook but it cannot find the jupyter-notebook file (though it's in the scripts directory)

**Comment by takluyver** [comment]
Thanks. We'll track this one at jupyter/jupyter#15, since it affects multiple repos.

As a workaround for now, you can use `python -m jupyter`
