### ISSUE TITLE
JS services' Comm.open/close should take buffers

### ISSUE THREAD

**Issue by vidartf** [jupyter/notebook#2730]
Currently `services.kernel.Comm.send()` takes an optional `buffers` argument, but its `open()` and `close()` methods does not. It would be really useful for me if especially the open method accepted buffers, and I cannot see any reason that it should not. Buffers are well defined for general messages, and the ipykernel implementation supports buffers on both reception and sending of comm open messages.

In both the notebook and jupyterlab implementation of Comm.open/close, this seems to be simply a matter of adding the argument to the functions, and passing it along to the inner message send function (which already supports it). I can PR those changes if agreed.

For now I am able to work around this with the following function on the JS side:
```js
var commOpenWithBuffers = function(comm, content, callbacks, metadata, buffers) {
    return comm.kernel.send_shell_message(
        "comm_open", content, callbacks, metadata, buffers);
}
```

**Comment by takluyver** [comment]
That change sounds fine to me. If you want to get it in for notebook 5.1, make a PR quickly!

Should it also be exposed by `CommManager.prototype.new_comm`?
