### ISSUE TITLE
Should "Save with Widgets" be a checkbox?

### ISSUE THREAD

**Issue by dsblank** [jupyter/notebook#2735]
If I "Save with widgets" and then a regular "Save", do I lose my widgets? If so, shouldn't "Save with widgets" just be a checkbox, so that anytime a regular save is executed, it will save the widgets too?

**Comment by rolweber** [comment]
No, you don't lose your widgets. But they remain in the state they had when you did the "Save with widgets".

**Comment by dsblank** [comment]
This is definitely a confusing way of handling them. I do lose the widgets, but maybe it is because I rerun the cells that generate the widgets? If it were a checkbox, then it could save the latest widgets when I save the notebook. Maybe to make it more clear, the wording could be changed to something like "Embed and Save the Current Widgets". I couldn't find any help on these options either.

**Comment by rolweber** [comment]
Yes, if you re-run cells, that would explain why you lose the widgets.

Note that ipywidgets is a separate project. The Widgets menu is from there, not from the notebook.
https://github.com/jupyter-widgets/ipywidgets

**Comment by dsblank** [comment]
Thanks for the info... I hadn't realized that the menu came from there. I'll put a link there to here.

Does Jupyter notebook have hooks in the save operation? If so, then "Save Widgets" should be a checkbox and hook into that.

**Comment by jtpio** [comment]
> Note that ipywidgets is a separate project. The Widgets menu is from there, not from the notebook.

Closing as tracked in https://github.com/jupyter-widgets/ipywidgets/issues/3672.

For reference it is a checkbox in JupyterLab.

Thanks!
