### ISSUE TITLE
CondaValueError: Could not find environment: /anaconda 

### ISSUE THREAD

**Issue by mannocheck** [jupyter/notebook#2736]
Thanks in advance for anyone who can assist.

After having two installations of anaconda on my mac (/Users/mannocheck/anaconda and /anaconda) I decided to remove the /anaconda directory entirely as all of the env's and relevant files were on /mannocheck/anaconda. Afterwards, it resulted in the above error. 

Jupyter Notebooks returns a blank page when I try to load it directly from terminal. If I use Anaconda Navigator to launch Jupyter I get a bit more detail.

**Jupyter Errors**

/Users/mannocheck/.anaconda/navigator/a.tool ; exit;
➜  ~ /Users/mannocheck/.anaconda/navigator/a.tool ; exit;

CondaValueError: Could not find environment: /anaconda

/Users/mannocheck/anaconda/bin/activate: line 94: sed: command not found
/Users/mannocheck/anaconda/bin/activate: line 98: grep: command not found
/Users/mannocheck/anaconda/bin/activate: line 99: grep: command not found
[I 10:19:02.734 NotebookApp] The port 8888 is already in use, trying another port.
[I 10:19:02.747 NotebookApp] Serving notebooks from local directory: /Users/mannocheck
[I 10:19:02.747 NotebookApp] 0 active kernels 
[I 10:19:02.747 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/?token=d2d0844ff559464c54b5827db4e15ae5370777dce003bdf2
[I 10:19:02.747 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:19:02.750 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=d2d0844ff559464c54b5827db4e15ae5370777dce003bdf2
/bin/sh: osascript: command not found

**Launching with Python or IPython returns similar errors:**

/Users/mannocheck/.anaconda/navigator/a.tool ; exit;
➜  ~ /Users/mannocheck/.anaconda/navigator/a.tool ; exit;

CondaValueError: Could not find environment: /anaconda

/Users/mannocheck/anaconda/bin/activate: line 94: sed: command not found
/Users/mannocheck/anaconda/bin/activate: line 98: grep: command not found
/Users/mannocheck/anaconda/bin/activate: line 99: grep: command not found
Python 3.6.2 |Anaconda custom (x86_64)| (default, Jul 20 2017, 13:14:59)

My attempts to remedy the issue were to modify bash profile and config files relevant to anaconda/jupyter, then I resorted to a clean install of anaconda, completely removing it from my system using the following guide https://docs.continuum.io/anaconda/install/uninstall. Unfortunately, this did not repair the issue.

Again, thank you in advance.

**Comment by takluyver** [comment]
You've probably got a kernelspec installed somewhere that refers to it - run `jupyter kernelspec list` to see where it might be.

**Comment by mannocheck** [comment]
Running jupyter kernelspec list returns

➜  ~ jupyter kernelspec list
Available kernels:
  python3    /Users/mannocheck/anaconda/share/jupyter/kernels/python3

**Comment by takluyver** [comment]
Weird, I'm not sure where it comes from, then. :confused:

**Comment by mannocheck** [comment]
Welp, wish I had a more useful response...but a simple reboot seems to have fixed it. Thanks @takluyver , at least now I know where to check if I run into something similar :)

**Comment by takluyver** [comment]
:-)

**Comment by jamboo** [comment]
I solved similar problem by checking environment variables.
use printenv
if anaconda setting is not pointed to desired location, edit your .bash_profile, hope it works for you.

**Comment by ForeverTangent** [comment]
Is there a solution to this problem?

I reinstalled Anaconda and this has started happening for me.

```
CondaValueError: Could not find environment: /anaconda

bash: sed: command not found
bash: grep: command not found
bash: grep: command not found
```

**Comment by anderson-dan-w** [comment]
I came across these types of issues after "renaming" conda environments (cloning an environment and then deleting it). Not sure why, but even new shells would run into this problem (`Could not find environment`), but only inside `tmux`. No idea how it was happening; remade the deleted environment because it was breaking my `bashrc`.
