### ISSUE TITLE
Plain text editor formatting issues

### ISSUE THREAD

**Issue by ndrewxie** [jupyter/notebook#2737]
Hello,
  When I used the plain text editor (new -> plain text file) and selected the language C++, all C++ code I enter has a weird formatting, like this:
```
#include <iostream>
     #include <string>
```
It's very inconvenient and annoying to have to delete all of those tabs. Could you please make formatting language - specific (at least for the popular ones, like C, C++, Java, Javascript, Python, etc)? Same for the syntax highlighting.

**Comment by takluyver** [comment]
I can reproduce this. It is supposed to be language specific - it should use the Codemirror [C like mode](http://codemirror.net/mode/clike/index.html) for C++, but something seems to be going wrong.

**Comment by takluyver** [comment]
Aha, found it! It was effectively using the C mode, I think, for C++ - we need to use mime types to distinguish them.

**Comment by ndrewxie** [comment]
OK thanks. Waiting for version 5.1 :smile.
