### ISSUE TITLE
Shortcut Key in File Editor to Block Comment

### ISSUE THREAD

**Issue by cancan101** [jupyter/notebook#2740]
Many text editors (see for example [Sublime](https://stackoverflow.com/a/11443903/2638485)) have a shortcut key that block comments the selected lines of code. Given the file editor has as language selection, this language can be used to properly block comment. ie in Python this would just be prepending each line in the selection with a `#`.

**Comment by gnestor** [comment]
It looks like the file editor defaults to non-Sublime keymaps (which is not the case for the notebook). If you simply switch to Sublime Text keymaps from the Edit menu, then block comment shortcut will work.

**Comment by cancan101** [comment]
Does the choice get persisted across editors?if not is there a way to make the choice persistent? Perhaps keybindings should be made to default the same for notebook and editor?

**Comment by gnestor** [comment]
Yes it does

**Comment by gnestor** [comment]
Closing this for now... 👍

**Comment by cancan101** [comment]
Does it make sense to change the editor default for consistency?

**Comment by gnestor** [comment]
I think it does! Will submit a PR momentarily...

**Comment by gnestor** [comment]
Notebook 5.1.0rc1 is available on PyPI so please give it a try and confirm that this is resolved 👍:

`pip install notebook --pre --upgrade`
