### ISSUE TITLE
Download as HTML puts "+" symbols instead of spaces in filename

### ISSUE THREAD

**Issue by blokeley** [jupyter/notebook#2742]
Using the File > Download > As HTML... command, I would expect the downloaded HTML file to have the same filename as the Jupyter Notebook.

However, every space is replaced by a + symbol.

Versions:
Python 3.6.1
IPython 5.3.0
Jupyter 1.0.0
Windows 10 Pro x64

**Comment by gnestor** [comment]
@takluyver I assume that there is a good reason why spaces are replaced with pluses? @minrk?

**Comment by minrk** [comment]
it's probably url-escaping being applied to the wrong thing.

**Comment by gnestor** [comment]
Notebook 5.1.0rc1 is available on PyPI so please give it a try and confirm that this is resolved 👍:

`pip install notebook --pre --upgrade`
