### ISSUE TITLE
jupyter wrong with "Enter" input

### ISSUE THREAD

**Issue by lituan** [jupyter/notebook#2749]
I got a strange problem. When I hit "Enter" to start a new line in jupyter cell, it will insert a blank line and start from the third line, any one has a clue?
![image](https://user-images.githubusercontent.com/8915202/29238875-9c1de974-7f70-11e7-8043-5dd60fc6bc67.png)

**Comment by lituan** [comment]
I checked my keyboard, it works well in other editors.

**Comment by stonebig** [comment]
there may be a need to clear the browser cache: going upward or downard from Notebook-5.0 to Notebook-5.1rc1, there is odd things happening on the first notebook opened. it calms down at second try.

**Comment by lituan** [comment]
Thank you @stonebig 
I finally find the reason，I installed Tampermonky, there'are two scripts which caused the problem. After uninstalling them, everything is all right.
