### ISSUE TITLE
Error while launching a Jupyter notebook

### ISSUE THREAD

**Issue by Ross-Jo** [jupyter/notebook#2757]
I encountered with a strange error(I wasn't able to see the file TREE!!!) while executing a jupyter notebook. And the below ones are the error logs.
--------------------------------------------------------------------------------------------------------------------
```
Server error: Traceback (most recent call last):
File "C:\Users\350U2A\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 516, in wrapper
 result = yield gen.maybe_future(method(self, *args, **kwargs))
File "C:\Users\350U2A\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
 value = future.result()
File "C:\Users\350U2A\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
 raise_exc_info(self._exc_info)
File "<string>", line 4, in raise_exc_info
File "C:\Users\350U2A\Anaconda3\lib\site-packages\tornado\gen.py", line 307, in wrapper
 yielded = next(result)
File "C:\Users\350U2A\Anaconda3\lib\site-packages\notebook\services\contents\handlers.py", line 124, in get
 path=path, type=type, format=format, content=content,
File "C:\Users\350U2A\Anaconda3\lib\site-packages\notebook\services\contents\filemanager.py", line 382, in get
 model = self._dir_model(path, content=content)
File "C:\Users\350U2A\Anaconda3\lib\site-packages\notebook\services\contents\filemanager.py", line 264, in _dir_model
 model = self._base_model(path)
File "C:\Users\350U2A\Anaconda3\lib\site-packages\notebook\services\contents\filemanager.py", line 230, in _base_model
 created = tz.utcfromtimestamp(info.st_ctime)
File "C:\Users\350U2A\Anaconda3\lib\site-packages\notebook\_tz.py", line 30, in utc_method
 dt = unaware(*args, **kwargs)
OSError: [Errno 22] Invalid argument
```

![error](https://user-images.githubusercontent.com/14027563/29281572-810dbeac-815a-11e7-9739-1e58651fc8e5.JPG)
--------------------------------------------------------------------------------------------------------------------
So I've tried to solve the error with various methods, but, I wasn't able to solve one till now. 
And there are some lists what I've tried but failed to solve the problem
1) I appointed the starting location of jupyter via 'jupyter_notebook_config.py' file like this.
    -> c.NotebookApp.notebook_dir = r"C:/Users/350U2A/Desktop" 
    However, It generated the same error just like before. 

2) Deleted all the files and packages related with jupyter notebook and reinstalled the program. But it also activated the same problem

3) Modified the starting location of jupyter in 'jupyter_notebook_config.py' as 
    -> c.NotebookApp.notebook_dir = r"C:/Users/" 
    At first it seems this measure works(cause the file tree was appeared on the page), however, when I clicked the folder named '350U2A', the same problem had occurred again. As soon as I click the folder, the TREE again, wasn't displayed but some above error logs(what I wrote above).

4) Finally I just created a folder under '350U2A' directory, and named the folder as NOTEBOOK, and changed the starting directory from "C:/Users/350U2A/Desktop" to "C:/Users/350U2A/NOTEBOOK". Strangely, this time, notebook was launched with no such problem. And the file TREE was appeared appropriately on Web browser. However, when I execute jupyter notebook in higher folder, it still shows the same problem. And it means the fundamental matter is not resolved.

Is there anyone who can help me with this problem?

**Comment by takluyver** [comment]
Can you try running this and see what result it gives?

```python
import os
info = os.lstat("C:\\Users\\350U2A")
print(info.st_ctime)
```

**Comment by Ross-Jo** [comment]
Thanks! This is the result when I ran it on console.
C:\Users\350U2A>python
Python 3.5.3 |Anaconda 4.4.0 (64-bit)| (default, May 15 2017, 10:43:23) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> info = os.lstat("C:\\Users\\350U2A")
>>> print(info.st_ctime)
1500342962.3143384

**Comment by takluyver** [comment]
Hmm, that looks normal enough, and I can convert it to a datetime timestamp OK. Can you check:

```python
from datetime import datetime
datetime.utcfromtimestamp(1500342962.3143384)
```

If that's OK on your computer too, then I guess it's one of the files contained in that folder, rather than the folder itself. Can you investigate:

```python
from datetime import datetime
import os

d = "C:\\Users\\350U2A"
for filename in os.listdir(d):
    path = os.path.join(d, filename)
    info = os.lstat(path)
    print(info.st_ctime)
    datetime.utcfromtimestamp(info.st_ctime)
```

**Comment by Ross-Jo** [comment]
And the result is like this.
```
>>> from datetime import datetime
>>> datetime.utcfromtimestamp(1500342962.3143384)
datetime.datetime(2017, 7, 18, 1, 56, 2, 314338)
```

But I found a strange one which generating an error. And the error number was the same one that I saw while running a jupyter notebook. As you pointed out the reason might be a file in the directory folder. Thanks! I guess I need to find out the file :)

```
>>> import os
>>> for filename in os.listdir(d):
...     path = os.path.join(d, filename)
...     info = os.lstat(path)
...     print(info.st_ctime)
...     datetime.utcfromtimestamp(info.st_ctime)
...
1482430464.7265618
datetime.datetime(2016, 12, 22, 18, 14, 24, 726562)
1462691770.150376
datetime.datetime(2016, 5, 8, 7, 16, 10, 150376)
1484291963.0149536
datetime.datetime(2017, 1, 13, 7, 19, 23, 14954)
1482430789.5205047
datetime.datetime(2016, 12, 22, 18, 19, 49, 520505)
1451137908.351987
datetime.datetime(2015, 12, 26, 13, 51, 48, 351987)
1484964063.5981317
datetime.datetime(2017, 1, 21, 2, 1, 3, 598132)
1498614111.5493257
datetime.datetime(2017, 6, 28, 1, 41, 51, 549326)
1498614115.7020917
datetime.datetime(2017, 6, 28, 1, 41, 55, 702092)
1502609557.8724709
datetime.datetime(2017, 8, 13, 7, 32, 37, 872471)
1450697859.4326081
datetime.datetime(2015, 12, 21, 11, 37, 39, 432608)
1451184198.1005063
datetime.datetime(2015, 12, 27, 2, 43, 18, 100506)
1501549375.646629
datetime.datetime(2017, 8, 1, 1, 2, 55, 646629)
1435997194.421167
datetime.datetime(2015, 7, 4, 8, 6, 34, 421167)
1483699973.92157
datetime.datetime(2017, 1, 6, 10, 52, 53, 921570)
1451197905.7935436
datetime.datetime(2015, 12, 27, 6, 31, 45, 793544)
1484306768.353265
datetime.datetime(2017, 1, 13, 11, 26, 8, 353265)
1502609848.1281939
datetime.datetime(2017, 8, 13, 7, 37, 28, 128194)
1484292225.562089
datetime.datetime(2017, 1, 13, 7, 23, 45, 562089)
1451183118.9266517
datetime.datetime(2015, 12, 27, 2, 25, 18, 926652)
1495021705.4892633
datetime.datetime(2017, 5, 17, 11, 48, 25, 489263)
1440686923.6797452
datetime.datetime(2015, 8, 27, 14, 48, 43, 679745)
1450697859.462608
datetime.datetime(2015, 12, 21, 11, 37, 39, 462608)
1483350686.8637755
datetime.datetime(2017, 1, 2, 9, 51, 26, 863775)
1482429433.4308841
datetime.datetime(2016, 12, 22, 17, 57, 13, 430884)
1483018977.672996
datetime.datetime(2016, 12, 29, 13, 42, 57, 672996)
1502609572.910527
datetime.datetime(2017, 8, 13, 7, 32, 52, 910527)
1442128337.4381347
datetime.datetime(2015, 9, 13, 7, 12, 17, 438135)
1451198642.6176875
datetime.datetime(2015, 12, 27, 6, 44, 2, 617687)
1451183487.8048995
datetime.datetime(2015, 12, 27, 2, 31, 27, 804899)
1489716998.8534422
datetime.datetime(2017, 3, 17, 2, 16, 38, 853442)
1466730812.365101
datetime.datetime(2016, 6, 24, 1, 13, 32, 365101)
1482429802.6802652
datetime.datetime(2016, 12, 22, 18, 3, 22, 680265)
1500342962.3455887
datetime.datetime(2017, 7, 18, 1, 56, 2, 345589)
1500342962.4383793
datetime.datetime(2017, 7, 18, 1, 56, 2, 438379)
1493866019.5051067
datetime.datetime(2017, 5, 4, 2, 46, 59, 505107)
1323419765.611891
datetime.datetime(2011, 12, 9, 8, 36, 5, 611891)
1500342962.4540098
datetime.datetime(2017, 7, 18, 1, 56, 2, 454010)
1468044628.6694598
datetime.datetime(2016, 7, 9, 6, 10, 28, 669460)
1448085281.5511508
datetime.datetime(2015, 11, 21, 5, 54, 41, 551151)
-11644473599.996723
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
OSError: [Errno 22] Invalid argument
```

**Comment by takluyver** [comment]
If you add `print(filename)` inside the loop, you should see which one it is. I'll prepare a PR to catch the error.

**Comment by takluyver** [comment]
#2770 should catch that error and use a fallback.

**Comment by Ross-Jo** [comment]
```
[-11644473599.996723
Desktop
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
OSError: [Errno 22] Invalid argument]
```
hu-oh...the file which triggered the problem seems... not a minor one. As you can see the 'Desktop' folder was the reason. I will try the solution you suggested and let you know the result! 
Sincerely Thanks a lot!!! :)

**Comment by Ross-Jo** [comment]
p.s. Is it right that I manually modify the file? I found a 'filemanager.py' file under the directory of 'notebook\\services\\contents\\'. And tried to modify it, however, it seems the structure of a function and other things look bit different from what you showed in #2770.
![jupyter](https://user-images.githubusercontent.com/14027563/29392685-5ed2411e-833a-11e7-9abc-814fb2576751.JPG)

**Comment by takluyver** [comment]
The pull request is against master, which is already a bit different from the released version. If you first install the 5.1 release candidate, you should have a more similar starting point to make the change on:

```
pip install --pre --upgrade notebook
```

**Comment by Ross-Jo** [comment]
Thank you very much for your help! :)

**Comment by dcomer** [comment]
Looks like there is another bug. When I start Notebook up, I receive the following error:
Invalid ctime -11644473599.996723 for C:\Users\<my_user_name>\Desktop

So, Notebook starts fine, and is in the default root (the desktop) and displays all files/folder correctly. I tried getting around this but adding the following to jupter_notebook_config.py:
    c.NotebookApp.notebook_dir = 'C:/Users/<my_user_name>/Documents/Notebooks'
Upon staring up Notebook again, I received the same error. I suspect the error initial error causes the configuration file to be ignore. Can you point me in the direction of how to debug (I'm learning Python).

**Comment by dcomer** [comment]
Perhaps the same file as before, 'filemanager.py'?

**Comment by dcomer** [comment]
OK, sorry for the repeated posts. I went back through the help you supplied above, for the second time. It looks like it is still the Desktop. I've uninstalled Anaconda, deleted the entire directory under c:\users\<my_user_id>\AppData\Local\Continuuim\*, delete all of the dot files in my user directory that apply (e.g. .jupyter, .anaconda, .spyder-py3, .ipython) but left .condarc (needed the firewall mods), re-booted, re-installed, and reapplied the pull above. I did get a bunch of warnings about deprecated installation in the pull, as well as an error at the very end. Unfortunately, I don't have the log hand at the moment, and will need to repeat the process. I wanted to post this now so I don't mislead you. I'll await your reply before the re-re-re-install to make sure I'm not going down the wrong path.

**Comment by Ross-Jo** [comment]
After reinstalling the program, have you ever upgraded it? If you didn't, I guess the improved code might not be applied. 

I recommend you to apply the command below which is also mentioned above.
`pip install --pre --upgrade notebook`

**Comment by dcomer** [comment]
I did use the command you suggested. Below, is the log. Most note worthy is the last line.

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\my_user_id\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\setuptools-27.2.0-py3.6.egg'

RE-issuing the command has the result of no errors. I think that is masking an underlying issue though.

That has me stumped. The command you suggest was issued after a fresh install (x64 on Windows 10) followed by a reboot. Not sure why setuptools is not found. Suggestions?


Thanks,

(C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3) C:\Users\my_user_id>pip install --pre --upgrade notebook
Collecting notebook
  Using cached notebook-5.1.0rc2-py2.py3-none-any.whl
Collecting nbformat (from notebook)
  Using cached nbformat-4.4.0-py2.py3-none-any.whl
Requirement already up-to-date: jinja2 in c:\users\my_user_id\appdata\local\continuum\anaconda3\lib\site-packages (from notebook)
Requirement already up-to-date: traitlets>=4.2.1 in c:\users\my_user_id\appdata\local\continuum\anaconda3\lib\site-packages (from notebook)
Requirement already up-to-date: ipykernel in c:\users\my_user_id\appdata\local\continuum\anaconda3\lib\site-packages (from notebook)
Requirement already up-to-date: jupyter-core in c:\users\my_user_id\appdata\local\continuum\anaconda3\lib\site-packages (from notebook)
Collecting nbconvert (from notebook)
  Using cached nbconvert-5.3.0-py2.py3-none-any.whl
Collecting jupyter-client (from notebook)
  Using cached jupyter_client-5.1.0-py2.py3-none-any.whl
Requirement already up-to-date: ipython-genutils in c:\users\my_user_id\appdata\local\continuum\anaconda3\lib\site-packages (from notebook)
Collecting tornado>=4 (from notebook)
  Using cached tornado-4.5.2-cp36-cp36m-win_amd64.whl
Requirement already up-to-date: jsonschema!=2.5.0,>=2.4 in c:\users\my_user_id\appdata\local\continuum\anaconda3\lib\site-packages (from nbformat->notebook)
Collecting MarkupSafe>=0.23 (from jinja2->notebook)
Requirement already up-to-date: pygments in c:\users\my_user_id\appdata\local\continuum\anaconda3\lib\site-packages (from nbconvert->notebook)
Collecting entrypoints>=0.2.2 (from nbconvert->notebook)
  Using cached entrypoints-0.2.3-py2.py3-none-any.whl
Collecting testpath (from nbconvert->notebook)
  Using cached testpath-0.3.1-py2.py3-none-any.whl
Collecting pandocfilters>=1.4.1 (from nbconvert->notebook)
Collecting bleach (from nbconvert->notebook)
  Using cached bleach-2.0.0-py2.py3-none-any.whl
Requirement already up-to-date: mistune>=0.7.4 in c:\users\my_user_id\appdata\local\continuum\anaconda3\lib\site-packages (from nbconvert->notebook)
Collecting pyzmq>=13 (from jupyter-client->notebook)
  Using cached pyzmq-17.0.0b1-cp36-cp36m-win_amd64.whl
Collecting python-dateutil>=2.1 (from jupyter-client->notebook)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting html5lib>=0.99999999 (from bleach->nbconvert->notebook)
  Using cached html5lib-1.0b10-py2.py3-none-any.whl
Requirement already up-to-date: six in c:\users\my_user_id\appdata\local\continuum\anaconda3\lib\site-packages (from bleach->nbconvert->notebook)
Collecting setuptools>=18.5 (from html5lib>=0.99999999->bleach->nbconvert->notebook)
  Using cached setuptools-36.4.0-py2.py3-none-any.whl
Collecting webencodings (from html5lib>=0.99999999->bleach->nbconvert->notebook)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl
Installing collected packages: nbformat, entrypoints, testpath, pandocfilters, setuptools, webencodings, html5lib, bleach, nbconvert, pyzmq, python-dateutil, jupyter-client, tornado, notebook, MarkupSafe
  Found existing installation: nbformat 4.3.0
    DEPRECATION: Uninstalling a distutils installed project (nbformat) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling nbformat-4.3.0:
      Successfully uninstalled nbformat-4.3.0
  Found existing installation: entrypoints 0.2.2
    DEPRECATION: Uninstalling a distutils installed project (entrypoints) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling entrypoints-0.2.2:
      Successfully uninstalled entrypoints-0.2.2
  Found existing installation: testpath 0.3
    DEPRECATION: Uninstalling a distutils installed project (testpath) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling testpath-0.3:
      Successfully uninstalled testpath-0.3
  Found existing installation: pandocfilters 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (pandocfilters) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pandocfilters-1.4.1:
      Successfully uninstalled pandocfilters-1.4.1
  Found existing installation: setuptools 27.2.0
    Uninstalling setuptools-27.2.0:
      Successfully uninstalled setuptools-27.2.0
  Found existing installation: html5lib 0.999
    DEPRECATION: Uninstalling a distutils installed project (html5lib) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling html5lib-0.999:
      Successfully uninstalled html5lib-0.999
  Found existing installation: bleach 1.5.0
    Uninstalling bleach-1.5.0:
      Successfully uninstalled bleach-1.5.0
  Found existing installation: nbconvert 5.1.1
    Uninstalling nbconvert-5.1.1:
      Successfully uninstalled nbconvert-5.1.1
  Found existing installation: pyzmq 16.0.2
    DEPRECATION: Uninstalling a distutils installed project (pyzmq) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pyzmq-16.0.2:
      Successfully uninstalled pyzmq-16.0.2
  Found existing installation: python-dateutil 2.6.0
    Uninstalling python-dateutil-2.6.0:
      Successfully uninstalled python-dateutil-2.6.0
  Found existing installation: jupyter-client 5.0.1
    DEPRECATION: Uninstalling a distutils installed project (jupyter-client) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling jupyter-client-5.0.1:
      Successfully uninstalled jupyter-client-5.0.1
  Found existing installation: tornado 4.5.1
    DEPRECATION: Uninstalling a distutils installed project (tornado) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling tornado-4.5.1:
      Successfully uninstalled tornado-4.5.1
  Found existing installation: notebook 5.0.0
    DEPRECATION: Uninstalling a distutils installed project (notebook) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling notebook-5.0.0:
      Successfully uninstalled notebook-5.0.0
  Found existing installation: MarkupSafe 0.23
    Uninstalling MarkupSafe-0.23:
      Successfully uninstalled MarkupSafe-0.23
Successfully installed MarkupSafe-1.0 bleach-2.0.0 entrypoints-0.2.3 html5lib-1.0b10 jupyter-client-5.1.0 nbconvert-5.3.0 nbformat-4.4.0 notebook-5.1.0rc2 pandocfilters-1.4.2 python-dateutil-2.6.1 pyzmq-17.0.0b1 setuptools-36.4.0 testpath-0.3.1 tornado-4.5.2 webencodings-0.5.1
Traceback (most recent call last):
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\Scripts\pip-script.py", line 5, in <module>
    sys.exit(pip.main())
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\__init__.py", line 249, in main
    return command.main(cmd_args)
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\basecommand.py", line 252, in main
    pip_version_check(session)
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\utils\outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\my_user_id\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\setuptools-27.2.0-py3.6.egg'

(C:\Users\my_user_id\AppData\Local\Continuum\Anaconda3) C:\Users\my_user_id>

**Comment by Ross-Jo** [comment]
Sorry for late reply. I had to do some tasks these days. Umm....I've never seen such a kind of problem till now. So I've also found about the problem, and you may refer some pages below. (Of course there IS possibility that you may already searched)
The problem seems to be related with Conda.

[(https://stackoverflow.com/questions/42755160/cannot-find-file-setuptools-27-2-0-py3-5-egg)]
[https://github.com/conda/conda/issues/5447]

I hope you solve the problem as soon as poss.

**Comment by dcomer** [comment]
No problem on response time. I appreciate your time and help. I believe you have point me in the right direction. The link you provided correlates with what I have been finding. Again, thank you and all the best.

Dave

**Comment by nagaraja993** [comment]
Traceback (most recent call last):
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 457, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 62, in post
    kernel_id=kernel_id))
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_name)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\tornado\gen.py", line 285, in wrapper
    yielded = next(result)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    **kw)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Naga Raja Paidimarri\Anaconda3\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
