### ISSUE TITLE
Allow tabs / windows

### ISSUE THREAD

**Issue by ghost** [jupyter/notebook#2758]
Hello,
  While this request will take a while (probably by 5.4 or 5.5) to get done, could you please add "windows" or "tabs" onto jupyter (Fullscreen tabs that can be switched with alt + tab would be fine, but adjustable windows would be better). Instead of opening a new window for a file editor, you could create a new tab (maybe a div?) and put the window content in there. Shouldn't be too hard for fullscreen tabs (not resizable, fills whole screen, can be switched using alt + tab)

**Comment by ndrewxie** [comment]
Instead of opening a new window for a file editor, you could create a new tab (maybe a div?) and put the window content in there. Shouldn't be too hard for fullscreen tabs (not resizable, fills whole screen, can be switched using alt + tab

**Comment by ndrewxie** [comment]
I heard about jupyterlab, however, it's in a VERY (note - VERY) early stage, and making the modifications to jupyter (at least for fullscreen tabs) shouldn't be that hard. Overall, jupyterlab seems "cluttered", so hopefully full window tabs will add productivity without making it cluttered.

**Comment by takluyver** [comment]
The file editor already opens in a new browser tab with the default settings. I think this is preferable to trying to put another level of tabs/windows inside the notebook interface, at least before Jupyterlab.

**Comment by ndrewxie** [comment]
That's fine, but the interface looks "weird" if it's in different tabs. Plus, at least in opera, tabulating is very strange - it only alternates between the 2 most recent tabs, unless you spam tab. It also adds lots of junk to your browser, and gets very cluttered. Windows / Tabs aren't my biggest concern - the UI of jupyter seems clunky, inefficient and not modern.

**Comment by ezequias** [comment]
I think Juputer Lab does that. One thing I would like to see is a button for full screen in the output. Could you tell me if it is possible?

**Comment by jtpio** [comment]
Closing as fixed in JupyterLab.

JupyterLab has largely been improved since the last comment in this issue which dates back to 2018.

Also note that the soon to be released Notebook 7 allows for opening side panels (still hidden by default), for example for the Table of Contents:

![image](https://github.com/jupyter/notebook/assets/591645/094b6c2c-a3f4-4b77-add5-0023a6fadbfd)
