### ISSUE TITLE
Improve keyboard shortcut discoverability

### ISSUE THREAD

**Issue by cogwheel** [jupyter/notebook#2759]
IMO all programs with keyboard shortcuts should display them in menus or on hover tooltips. At least have this as a toggleable help option.

Right now the only way to see the keyboard shortcuts is to open a *modal dialog* on top of your notebook. If you _really_ don't want to display keyboard shortcuts in the UI, then at least open this in a separate window or allow the window to float rather than block all other actions on the page.

**Comment by gnestor** [comment]
> IMO all programs with keyboard shortcuts should display them in menus or on hover tooltips

I agree, the notebook should display keymaps inline in the menus. Most of our development bandwidth is focused on JupyterLab now so we don't have much bandwidth to add new features to the classic notebook. I'm going to mark this with "JupyterLab" and "New Contributor" meaning that this should be implemented in JupyterLab and that this would be a great opportunity for a new contributor. 

@cogwheel If you would like to take a crack at this, I will gladly help and review your PR.

**Comment by cogwheel** [comment]
I appreciate the support for the suggestion. I would probably describe my current interest in Jupyter as exceedingly cursory to begin with (I have no planned use, just toying around), and that's with the Haskell kernel, not even Python. If Jupyter becomes a bigger part of my life before someone else gets to it, then we'll see :)

**Comment by aaronmyatt** [comment]
@gnestor could you recommend some places to start exploring for this issue? I'll start trawling the source now but any course corrections welcome!

**Comment by aaronmyatt** [comment]
Ok a fair degree of progress:

<img width="200" alt="screen shot 2017-10-21 at 15 25 19" src="https://user-images.githubusercontent.com/11920225/31849418-5fa2e4d2-b674-11e7-8f6b-2e82d7383c9b.png">
<img width="169" alt="screen shot 2017-10-21 at 15 25 31" src="https://user-images.githubusercontent.com/11920225/31849419-5fd5359a-b674-11e7-8b62-9b69661bc75d.png">
<img width="171" alt="screen shot 2017-10-21 at 15 25 38" src="https://user-images.githubusercontent.com/11920225/31849420-600db898-b674-11e7-82d6-d15400b84e5f.png">
<img width="218" alt="screen shot 2017-10-21 at 15 25 44" src="https://user-images.githubusercontent.com/11920225/31849421-603f72f2-b674-11e7-90ea-6afbaaf6c801.png">
<img width="187" alt="screen shot 2017-10-21 at 15 25 52" src="https://user-images.githubusercontent.com/11920225/31849423-60720794-b674-11e7-9c71-184a696b240a.png">

To achieve this I have extended the `MenuBar` object to also add the keybinding when it loops over the `id_actions_dict`.

It's ugly, and I'm pretty sure incomplete, but I'll be glad for early feedback.

**Comment by gnestor** [comment]
@aaronmyatt Looking good! Great start. Would you like to submit a PR so that we can collaborate on it?

**Comment by aaronmyatt** [comment]
@gnestor I would be glad to make a PR! I didn't think you would want one so soon, usually I am the lone proponent of early PRs in my company!

I'll double check the contributor guidelines and get a PR up asap.

**Comment by gnestor** [comment]
Early PRs are welcome 👍

**Comment by morenoh149** [comment]
can we add the `?` shortcut, which opens up the keyboard shortcut menu. This is a fairly standard shortcut in gmail and github for example.

**Comment by takluyver** [comment]
I think that would be good.

**Comment by aaronmyatt** [comment]
@morenoh149 @takluyver agreed. I'll add that in once I'm done banging my head on the blocker in the current PR (#2968)

**Comment by prof-lupin** [comment]
Hello!
We are a group of undergrads from India who are looking to solve issues in open source repositories as a course project. Some of us(including me), being avid users of Jupyter Notebook suggested that we choose an issue in this repository.

Being new contributors we searched for issues labelled as "good first issue" and came across this issue and it really piqued our interest. We are third year CSE students with technical background in fields related to the tech stack of this repo.

We'd like to work on one of these issues at first and also, some advice regarding which issue to work on. We are really hyped to get this work done and will sincerely appreciate your guidance. Please tell us how to proceed and what we can do in this issue.

**Comment by JohannaHillebrand** [comment]
Do you still need any help with this issue?

**Comment by gnestor** [comment]
Hi @JohannaHillebrand! I believe that @prof-lupin and his group decided to work on another feature, so we still need help with this issue. Based on my recollection, the majority of the work is done but there are some build issues that are preventing us from merging the PR: #2968
