### ISSUE TITLE
Syntax for header changed. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#276]
cf https://github.com/jupyter/jupyter/issues/16

In recent marked, header need to get a space after hash, used to not be the case. 
This breaks a lot of notebooks.

**Comment by minrk** [comment]
I expect this change was on purpose, but we can ping marked about it. I'm not sure there is anything we can do unless this is optional behavior in marked.

**Comment by Carreau** [comment]
I'm going to decide that "Feature not bug" or "Wontfix" or "See upstream". 
Closing.
