### ISSUE TITLE
Allow deleting nonempty directorys

### ISSUE THREAD

**Issue by ghost** [jupyter/notebook#2760]
Hello,
  It is frequently useful to be able to delete non empty dirs, especially if there are many subfolders. Could you please add a feature for that (deleting nonempty dirs, maybe with a confirmation)?

**Comment by aaskat** [comment]
Hello, I'd like to work on this issue. I'm a new contributor here and I need some help.

**Comment by dsblank** [comment]
Now that delete will actually move to trash (coming in 5.3) we should allow Jupyter to delete non-empty directories.

**Comment by takluyver** [comment]
We should first check that send2trash actually allows you to send directories to trash on different platforms,  not just individual files.

**Comment by blink1073** [comment]
I just verified with non-empty directories on macOS 10.13, Ubuntu 16.04, and Windows 10 using `Send2Trash (1.4.1)`

**Comment by blink1073** [comment]
In all cases I was able to delete and restore the folder.

**Comment by takluyver** [comment]
Thanks @blink1073 :-)

**Comment by damianavila** [comment]
> In all cases I was able to delete and restore the folder.

Then, should be closing this one?

**Comment by jzf2101** [comment]
@takluyver is this ready to close?

**Comment by takluyver** [comment]
No, I think @blink1073 checked that the underlying code we're using is able to delete nonempty directories correctly. Someone still needs to enable that in our code before we can close it.

**Comment by hemangjoshi37a** [comment]
Has it been already solved??
