### ISSUE TITLE
Feature:  Add SFTP tab in Jupyter

### ISSUE THREAD

**Issue by arita37** [jupyter/notebook#2762]
We often need to work with remote Jupyter on a server.
There is the function upload file, it would be good to add those features :  

  1) upload folder
  2) In new tab (like conda tab) : 
       Directory tree (local)   vs  Remote tree(Jupyter remote)  
       Select Files / Folder  and Upload or Download.

It would help to update remote codes/files.

**Comment by minrk** [comment]
I don't think we can do this. Browsers don't have access to the local filesystem for security reasons, so the local tab would have to be an additional standalone webserver running on your laptop serving up files.

**Comment by arita37** [comment]
But, there is already upload function....





On 17 Aug 2017, at 16:56, Min RK <notifications@github.com> wrote:

I don't think we can do this. Browsers don't have access to the local filesystem for security reasons, so the local tab would have to be an additional standalone webserver running on your laptop serving up files.

―

**Comment by takluyver** [comment]
The browser can get access to local files if the user explicitly selects them in an upload dialog, or drags and drops them onto the page. It can't e.g. get a list of all the files in your home directory.

**Comment by arita37** [comment]
In browser, you can execute SSH
through the terminal.




On 17 Aug 2017, at 18:57, Thomas Kluyver <notifications@github.com> wrote:

The browser can get access to local files if the user explicitly selects them in an upload dialog, or drags and drops them onto the page. It can't e.g. get a list of all the files in your home directory.

―

**Comment by takluyver** [comment]
Yes, but the commands you enter in the terminal are run on the server, not the local machine where you have the browser open.

**Comment by jtpio** [comment]
Closing as unlikely to be implemented in the notebook repo.

Maybe this could be implemented as a third-party server + frontend extension: https://jupyter-notebook.readthedocs.io/en/latest/extending/index.html

Thanks all for the discussions!
