### ISSUE TITLE
`COPYING.md` to `LICENSE`

### ISSUE THREAD

**Issue by jzf2101** [jupyter/notebook#2768]
We should change the name of our license file to be consistent across repos at Project Jupyter

**Comment by rolweber** [comment]
Would that imply some re-formatting of the content? It's currently in markdown format, and probably won't be rendered as such by GitHub anymore if the file suffix changes.

Also, there's more in the file than just the license.

**Comment by danielskatz** [comment]
I was checking to see the license for this project, and was surprised not to find a license file in the repo, which led me to this issue.  It would be good if there was a LICENSE.txt file that was just a text version of the license, which doesn't mean there also can't be a COPYING.md file that has some of what is now in the file (except the license) and points to LINCENSE.txt

**Comment by sammyrTX** [comment]
Hi! Would it be okay to just copy the contents of the jupyter/LICENSE file into a jupyter/notebook/LICENSE.txt file and then updating the existing notebook/COPYING.md file to reference the new file (as suggested by @danielskatz)? Or are there any additional requirements for this issue? Thanks!

**Comment by sammyrTX** [comment]
I opened PR #4765 which is based on my previous comment. Review pending.

**Comment by jtpio** [comment]
Closing as the current `LICENSE` is aligned with the other Jupyter projects: https://github.com/jupyter/notebook/blob/main/LICENSE
