### ISSUE TITLE
opening file with backslash(%5C) fails on linux

### ISSUE THREAD

**Issue by j31d0** [jupyter/notebook#2775]
In windows there couldn't exist file which have backslash, but linux could.
I tested with version 5.0.0.
test script : 

```
:/test$ echo "foo" > test1
:/test$ echo "bar" > \\test1
```

![image](https://user-images.githubusercontent.com/8012197/29439790-1ebb83ee-83fb-11e7-8afe-8588d6c5c08f.png)
when I enter to \test1 : 
![image](https://user-images.githubusercontent.com/8012197/29439824-54e8330e-83fb-11e7-9694-d811d7fcfcce.png)

**Comment by takluyver** [comment]
Thanks, I think #2777 should fix it.
