### ISSUE TITLE
Mathjax file not loading when opening or reloading notebook

### ISSUE THREAD

**Issue by amahadevan99** [jupyter/notebook#2780]
When I open any jupyter notebook I get a small `loading MathJax` notification in the bottom left corner of the window. For most `.ipynb` files this proceeds, then says `Processing Math: 100%`, then goes away. However there is one particular notebook which behaves strangely. When I open or reload it, this text, instead of going to `Loading Math: 100%`, gives me an error `File failed to load: http://localhost:8888/static/components/MathJax/jax/element/mml/optable/SpacingModLetters.js`. I also get the following error in the Terminal: `404 GET /static/components/MathJax/jax/element/mml/optable/SpacingModLetters.js?rev=2.6.0 (::1) 17.79ms referer=http://localhost:8889/notebooks/data/filename.ipynb`. It is a small thing but still a bit annoying. Furthermore, the notebook seems to run and render fine, despite this error. And this notebook is similar to the other notebooks that do not cause this problem. Any ideas as to why I am getting this warning/error or what the missing file is supposed to do? Looks like this is related to issue #1108 .

**Comment by takluyver** [comment]
Are you willing to share the notebook that you see the error with?

**Comment by amahadevan99** [comment]
I wouldn't mind sharing the markdown cells, if that would be helpful, but I would prefer not to share the entire notebook.

**Comment by takluyver** [comment]
Does the same thing still happen if you make a copy with only the markdown cells?

**Comment by amahadevan99** [comment]
Yes -- In fact I just discovered that the offending cell is 
    Therefore the slope of the $E$ versus $q$ graphs should be the following:
    $\sim xxxx$ eV$\cdot\mathring{A}$ for no spin flip,
    $xxxx$ eV$\cdot\mathring{A}$ for $\mathbf k_p\to-\mathbf k_p$,
    $xxxx$ eV$\cdot\mathring{A}$ for $\mathbf k_s\to-\mathbf k_s$
Not sure what is wrong with it though.

**Comment by takluyver** [comment]
I copied and pasted that, and it seems to be working on my machine. Is this what it's supposed to look like?

![screenshot from 2017-08-21 16-27-58](https://user-images.githubusercontent.com/327925/29526496-d027079a-868d-11e7-8a10-dabf3b1a0113.png)

**Comment by amahadevan99** [comment]
yes, that is correct. On my machine it renders correctly, but if I reload or open the notebook with this cell, I get a 404 error in the terminal (and a notification in the lower left corner of by screen) that I documented above. It's weird that this doesn't seem to affect the rendering.

**Comment by takluyver** [comment]
I think I've found it - those files are getting left out when the notebook package is made. So I don't see it normally because I'm running the notebook directly from a development version. Once I make a package and install that, I can reproduce the error.

I've made PR #2788 to ensure those files get packaged.

**Comment by sarah13889** [comment]
Hi I am having the same error, and the notebook doesn't run.
