### ISSUE TITLE
Kernel keeps dying when PyTorch is imported

### ISSUE THREAD

**Issue by samiksome** [jupyter/notebook#2782]
I am using Ubuntu 17.04 and python 2.7.13 and whenever I run `import torch` the kernel dies. I also tried switching to python 3 (3.5.3) but I get the same problem.

EDIT: It runs without any problem when I directly use python or ipython.

**Comment by takluyver** [comment]
See if there are any error messages in the terminal where you launched the notebook when the kernel dies.

**Comment by takluyver** [comment]
Closing in favour of #2784, which was after this but has more detail.

**Comment by YanetGB** [comment]
Same problem and working from GPU
