### ISSUE TITLE
command not found: 'jupyter'

### ISSUE THREAD

**Issue by mingrammer** [jupyter/notebook#2786]
I just installed the jupyter via `pip3 install jupyter`. The installation was succeed. But when I run the `jupyter` command, my shell shows `command not found: jupyter`.

How can I fix it?

p.s. I'm using Sierra on macOS and Python 3.6 which was installed by `homebrew`

**Comment by takluyver** [comment]
The installation should have put a script file called `jupyter` in a directory called `bin` somewhere on your system. You need to make sure that the `PATH` environment variable includes that bin directory. PATH tells the shell where to look for commands.

**Comment by mingrammer** [comment]
@takluyver My `PATH` already includes the `/bin`. But, It would not be installed correctly. I can't figure out any causes ..

**Comment by catherinedodge** [comment]
In trying to repro this I installed juypter on MacOS Sierra also using 'pip3 install jupyter'.  my pip3 is installed at the following location:

```
$ which pip3
/usr/local/bin/pip3
```
And I'm able to run jupyter, its installation location is shown below:

```
$ which jupyter
/usr/local/bin/jupyter
```
When you type 'which pip3' what value does it show?

**Comment by mingrammer** [comment]
@catherinedodge I tried that way before solved, but not worked. So I've solved this problem by clean reinstalling macOS Sierra.

**Comment by catherinedodge** [comment]
Ok to mark this as resolved then?

**Comment by mingrammer** [comment]
Yes, you can. Thanks :)
