### ISSUE TITLE
Could I set font and theme in Jupyter notebook?

### ISSUE THREAD

**Issue by zhuzelong** [jupyter/notebook#279]
In IPython notebook 3, the font and theme were controlled by IPython profile. But Jupyter split IPython from notebook, I could not find any options of font and theme in Jupyter.

**Comment by Carreau** [comment]
Hi @zhuzelong, 

`$ jupyter migrate` should do the right thing:

```
$ jupyter migrate
[JupyterMigrate] Copying /Users/bussonniermatthias/.ipython/profile_default/static/custom/custom.css -> /Users/bussonniermatthias/.jupyter/custom/custom.css
```

Usually just rename `~/.ipython/profile_default/` to `~/.jupyter/` it should work the same. 

Closing, feel free to reopen if it did not work !

Thanks !
