### ISSUE TITLE
Feature: Embed Tweets

### ISSUE THREAD

**Issue by pylang** [jupyter/notebook#2790]
Is it possible to embed tweets in Jupyter notebooks?  If not, can an IPython.display option be added similar to `HTML`, `YouTubeVideo`, `IFrame`, etc.

Example 

```python
from IPython import display

display.Tweet("http://bit.ly/2vYS5ZD")
```
![2017-08-21 23_32_25-here comes the data science and it s all right _ continuum](https://user-images.githubusercontent.com/10778668/29547604-17aa4cfe-86c9-11e7-8c8b-faf91d239102.png)

**Comment by takluyver** [comment]
It's possible by embedding the relevant HTML, but there isn't a shortcut like `YouTubeVideo`.

I'd personally favour putting site-specific things like `Tweet` in third party modules which can be upgraded separately, rather than putting them all into IPython. They're really easy to define: it's just a class with a `_repr_html_` method that returns HTML:

```python
class Boo(object):
    def __init__(self, text='Boo'):
        self.text = text

    def _repr_html_(self):
        return '<h1>%s</h1>' % self.text
```

**Comment by pylang** [comment]
Thanks @takluyver.  With your help, I see how simple it is. For anyone interested, I used the embed string from a selected tweet:

Select the Embed Tweet option:

![a](https://user-images.githubusercontent.com/10778668/29736257-8825e7f2-89cd-11e7-8ff5-1a7ba7d0e707.png)

Copy/Paste the string:

![b](https://user-images.githubusercontent.com/10778668/29736259-8c13186c-89cd-11e7-87da-d2701f078156.png)


Code:

```python
class Tweet(object):
    def __init__(self, embed_str=None):
        self.embed_str = embed_str

    def _repr_html_(self):
        return self.embed_str

s = ("""
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Watch <a href="https://twitter.com/hashtag/JupyterCon?src=hash">#JupyterCon</a> keynotes live on Facebook—starts 8:50AM ET <a href="https://t.co/Z6KFG2qQzd">https://t.co/Z6KFG2qQzd</a><a href="https://twitter.com/hashtag/Jupyter?src=hash">#Jupyter</a> <a href="https://twitter.com/hashtag/datascience?src=hash">#datascience</a> <a href="https://twitter.com/ProjectJupyter">@ProjectJupyter</a> <a href="https://twitter.com/NumFOCUS">@NumFOCUS</a> <a href="https://t.co/7FrmpA3jaA">pic.twitter.com/7FrmpA3jaA</a></p>&mdash; O&#39;Reilly Media (@OReillyMedia) <a href="https://twitter.com/OReillyMedia/status/901048172738482176">August 25, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
""")
```
Output:

![c](https://user-images.githubusercontent.com/10778668/29736233-699fef26-89cd-11e7-81bd-3feec3b693b6.png)

**Comment by jankoslavic** [comment]
What about embedding Tweets directly into markdown?

Why is this not working?
![image](https://user-images.githubusercontent.com/5072664/30610906-056e6638-9d80-11e7-8867-e034fd7e0360.png)

**Comment by rgbkrk** [comment]
Markdown is sanitized to mitigate cross site scripting issues, HTML output is only shown if the notebook is trusted.

**Comment by jankoslavic** [comment]
Thanks @rgbkrk. PS: this is a result in a trusted notebook. Is there a way to show also the picture?

**Comment by jankoslavic** [comment]
I fond another way using %%html magic:
```%%html
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Watch <a href="https://twitter.com/hashtag/JupyterCon?src=hash">#JupyterCon</a> keynotes live on Facebook—starts 8:50AM ET <a href="https://t.co/Z6KFG2qQzd">https://t.co/Z6KFG2qQzd</a><a href="https://twitter.com/hashtag/Jupyter?src=hash">#Jupyter</a> <a href="https://twitter.com/hashtag/datascience?src=hash">#datascience</a> <a href="https://twitter.com/ProjectJupyter">@ProjectJupyter</a> <a href="https://twitter.com/NumFOCUS">@NumFOCUS</a> <a href="https://t.co/7FrmpA3jaA">pic.twitter.com/7FrmpA3jaA</a></p>&mdash; O&#39;Reilly Media (@OReillyMedia) <a href="https://twitter.com/OReillyMedia/status/901048172738482176">August 25, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by takluyver** [comment]
I think we actually sanitize markdown regardless of trust; whether a notebook is trusted or not only relates to output.
