### ISSUE TITLE
Inconsistent documentation on editing keyboard shortcuts

### ISSUE THREAD

**Issue by cebolan** [jupyter/notebook#2801]
The current documentation on editing keyboard shortcuts includes these two contradictory lines:
  
> * At most, one non-modifier key can exist in a key combination.
> * Multiple non-modifier key can exist in a key combination.

I guess the second line should read 'Multiple modifier keys can exist in a key combination'.

**Comment by takluyver** [comment]
Yes, I think you're right. Do you want to make a PR?
