### ISSUE TITLE
Latex Rendering Problem

### ISSUE THREAD

**Issue by Scoodood** [jupyter/notebook#2807]
Please try this on your Jupyter notebook markdown cell
```
$$x = \sqrt{\chi^2\over n}$$
```
It looks like this on my system. The square root symbol and the exponent are overlapping to each other.
![image](https://user-images.githubusercontent.com/15989924/29726057-2c9eb4b2-8983-11e7-9d19-c42485e99a5f.png)

**My Environment** 
<hr>

My system = Win7 x64 SP1
My Browser = Google Chrome Version 60.0.3112.101 (Official Build) (64-bit)
My Anaconda + Jupyter Notebook =
![image](https://user-images.githubusercontent.com/15989924/29726102-669ce26a-8983-11e7-96c5-a090ba487c7f.png)

**Comment by jtpio** [comment]
Just checked with Notebook `7.0.0rc0` and it seems to be rendering fine now:

![image](https://github.com/jupyter/notebook/assets/591645/2e294540-b962-40ff-87e4-88dd5699f0a9)

Closing as fixed, thanks for reporting!
