### ISSUE TITLE
Improve Documentation for Building Documenation

### ISSUE THREAD

**Issue by jzf2101** [jupyter/notebook#2809]
Very meta.  See #1749

Some relevant info:
docs can only be built w python 3 
page in read the docs on building docs is blank-
 info should go on this page https://jupyter.readthedocs.io/en/latest/contrib_docs/doc-build.html
see also as reference https://readthedocs.org/projects/jupyter-notebook/builds/5880632/
also note installing pandoc w brew

**Comment by lesley2958** [comment]
i've got this!

**Comment by lesley2958** [comment]
I'll take care of this!

**Comment by jtpio** [comment]
Closing the documentation for building the docs has been revamped on the latest `main`: https://jupyter-notebook.readthedocs.io/en/latest/contributing.html#documentation
