### ISSUE TITLE
Jupyter Notebook does not find the kernel created by conda.

### ISSUE THREAD

**Issue by likenji** [jupyter/notebook#2812]
The problem happens in my remote server. OS: Ubuntu 16.04
I've installed anaconda4.2.0 for Linux 64BIT.
Then I installed py2.7 using the following command.
```
set CONDA_FORCE_32BIT = 1
create -n py27_x86 python = 2.7 
```
However, when I wanted to open a new notebook with a kernel of py2.7, I could not find the option of 
> py27_x86

I found someone encounter the same problem with me.
Details at [https://stackoverflow.com/questions/41885565/jupyter-notebook-internal-server-error](url)
I guessed the problem was relevant to the error above.
But after I updated jupyter & nb_kernel to the latest version, the problem still existsed.

Since using Jupyter Notebook is the best way to edit code in local machine and execute it in remote  server, the problem that makes me unable to switch different kernels when running code in remote server bothers me a lot.
I 'd really appreciate it if anyone can offer help to me.

**Comment by takluyver** [comment]
You need to make sure `ipykernel` is installed in that conda env. Then you either need to [install a kernelspec](http://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments) from it, or use the nb_conda_kernels extension.

**Comment by likenji** [comment]
Thanks much for your advice and the problem has been solved.

I've done the following:
source activate py27_x86
conda install jupyter

And I can see 

> conda env:py27_x86
in the kernel list now!

**Comment by takluyver** [comment]
Thanks for following up with an explanation of how you solved it :-)

**Comment by feyzanurakyol** [comment]
Thanks, i solved my problem with your explanation. :)
