### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib' on Jupiter Notebook

### ISSUE THREAD

**Issue by ichiLamuchy** [jupyter/notebook#2820]
This is my first time using Jupiter Notebook. It is on OSX10.12.6, not using vertualenv. I selected python 3, then 
tried code below

%matplotlib inline
from matplotlib.pyplot import plot

plot([0,1,0,1])

It gives me error like this.
Does anyone know how to fix it? 
Do I have to install the module using pip3? I am not particularly good at using command line (learning though!) 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-6b2036e20e35> in <module>()
----> 1 get_ipython().magic('matplotlib inline')
      2 from matplotlib.pyplot import plot
      3 
      4 plot([0,1,0,1])

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2144         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2145         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2146         return self.run_line_magic(magic_name, magic_arg_s)
   2147 
   2148     #-------------------------------------------------------------------------

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2065                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2066             with self.builtin_trap:
-> 2067                 result = fn(*args,**kwargs)
   2068             return result
   2069 

<decorator-gen-107> in matplotlib(self, line)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/magics/pylab.py in matplotlib(self, line)
     97             print("Available matplotlib backends: %s" % backends_list)
     98         else:
---> 99             gui, backend = self.shell.enable_matplotlib(args.gui)
    100             self._show_matplotlib_backend(args.gui, backend)
    101 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   2916         """
   2917         from IPython.core import pylabtools as pt
-> 2918         gui, backend = pt.find_gui_and_backend(gui, self.pylab_gui_select)
   2919 
   2920         if gui != 'inline':

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/pylabtools.py in find_gui_and_backend(gui, gui_select)
    267     """
    268 
--> 269     import matplotlib
    270 
    271     if gui and gui != 'auto':

ModuleNotFoundError: No module named 'matplotlib'

**Comment by takluyver** [comment]
You need to install matplotlib by some means. If you're new to this stuff, we recommend [Anaconda](https://www.anaconda.com/download/) - it gives you a lot of useful packages in one big installation.

**Comment by ichiLamuchy** [comment]
Thank youI 
I have python 3.6 installed already for only some on-line course I have done previously. 
Shall I install and use anaconda for installing (new) python 3? Do you think it's good idea to uninstall python 3.6 for the sake of easy manage environment, default setting and  dependency?

**Comment by takluyver** [comment]
If you're comfortable with the Python installation you've already got, you can install most things you're likely to want with pip. If you still feel unsure about that, it might be easier to start over with Anaconda.

Quite a lot of scientific Python tutorials now give installation instructions using conda. It's usually possible to use pip instead, but it's an extra thing to work out.

**Comment by ichiLamuchy** [comment]
Thank you, I will probably start over, my experience python set up has been a bit of pain (means I am not so comfortable yet). What is the best way to uninstall Jupyter?

$ pip install pip-autoremove
$ pip-autoremove jupyter -y

is this the right way to get rid of all?

these are my questions
https://stackoverflow.com/questions/45986142/how-to-uninstall-jupyter-note-book-installed-by-pip3
https://stackoverflow.com/questions/45989054/what-is-the-best-way-to-set-up-jupyter-notebook-with-virtual-env-on-osx

**Comment by takluyver** [comment]
I don't know of a good way to uninstall all the packages, other than running `pip uninstall` with a list of all the packages involved (which is a lot). There might be a directory you can remove. When you install Anaconda, though, it will have its own directory of packages, so it shouldn't matter if you haven't managed to remove everything from the previous Python install.

**Comment by ichiLamuchy** [comment]
Thank you so much 
how about jupyter notebook? is it ok to uninstall jupiter notebook with above command lines?
