### ISSUE TITLE
0 active kernels

### ISSUE THREAD

**Issue by wanglongqi** [jupyter/notebook#2821]
Tried solutions in the previous bug list, e.g. reinstall pyzmq, change the port. Nothing works. 

> [I 09:13:05.921 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
> [I 09:13:06.710 NotebookApp] Loading IPython parallel extension
> [I 09:13:07.940 NotebookApp] [nb_anacondacloud] enabled
> [I 09:13:07.947 NotebookApp] [nb_conda] enabled
> [I 09:13:08.009 NotebookApp] 鉁?nbpresent HTML export ENABLED
> [W 09:13:08.009 NotebookApp] 鉁?nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
> [I 09:13:08.773 NotebookApp] 0 active kernels
> [I 09:13:08.773 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=f1b078eca09dead1037db711d48b3345137bc2fdbe8fb107
> [I 09:13:08.775 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [C 09:13:08.780 NotebookApp]
> 
>     Copy/paste this URL into your browser when you connect for the first time,
>     to login with a token:
>         http://localhost:8888/?token=f1b078eca09dead1037db711d48b3345137bc2fdbe8fb107
> [I 09:13:09.585 NotebookApp] Accepting one-time-token-authenticated connection from ::1
> [I 09:13:10.371 NotebookApp] 302 GET /api/config/tree?_=1504141990075 (::1) 1.00ms
> [I 09:13:10.375 NotebookApp] 302 GET /api/config/common?_=1504141990076 (::1) 1.00ms
> [I 09:13:10.388 NotebookApp] 302 GET /api/kernelspecs (::1) 2.00ms
> [I 09:13:10.391 NotebookApp] 302 GET /api/sessions?_=1504141990077 (::1) 2.00ms

In the browser side:

![image](https://user-images.githubusercontent.com/6874783/29901884-3a67a32a-8e2d-11e7-93e7-e1c744c10c9b.png)

QT console can start and working:

![image](https://user-images.githubusercontent.com/6874783/29901896-52416288-8e2d-11e7-950a-b21cb8f21e89.png)

**Comment by minrk** [comment]
Do you see any errors in the javascript console in your browser?

**Comment by wanglongqi** [comment]
![image](https://user-images.githubusercontent.com/6874783/29922271-7c046ee4-8e87-11e7-85a2-9a1ed2403efd.png)

**Comment by wanglongqi** [comment]
@minrk Any idea about this issue?

**Comment by minrk** [comment]
What's `jupyter notebook --version`? You might try disabling the various anaconda extensions, to see if that's the cause:

    conda remove nb_conda_kernels nb_conda nb_anacondacloud

**Comment by wanglongqi** [comment]
`jupyter notebook --version`

> 5.0.0

`conda remove nb_conda_kernels nb_conda nb_anacondacloud

> `Fetching package metadata ...........
> Solving package specifications: .
> 
> Package plan for package removal in environment C:\Python:
> 
> The following packages will be REMOVED:
> 
>     nb_anacondacloud: 1.4.0-py27_0
>     nb_conda:         2.2.0-py27_0
>     nb_conda_kernels: 2.1.0-py27_0
> 
> Proceed ([y]/n)?

`jupyter notebook`

> The Jupyter HTML Notebook.
> 
> This launches a Tornado based HTML Notebook Server that serves up an
> HTML5/Javascript Notebook client.
> 
> Subcommands
> -----------
> 
> Subcommands are launched as `jupyter-notebook cmd [args]`. For information on
> using subcommand 'cmd', do: `jupyter-notebook cmd -h`.
> 
> password
>     Set a password for the notebook server.
> list
>     List currently running notebook servers.
> 
> Options
> -------
> 
> Arguments that take values are actually convenience aliases to full
> Configurables, whose aliases are listed on the help line. For more information
> on full configurables, see '--help-all'.
> 
> --script
>     DEPRECATED, IGNORED
> --pylab
>     DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
> --debug
>     set log level to logging.DEBUG (maximize logging output)
> --no-browser
>     Don't open the notebook in a browser after startup.
> --allow-root
>     Allow the notebook to be run from root user.
> -y
>     Answer yes to any questions instead of prompting.
> --no-mathjax
>     Disable MathJax
> 
>     MathJax is the javascript library Jupyter uses to render math/LaTeX. It is
>     very large, so you may want to disable it if you have a slow internet
>     connection, or for offline use of the notebook.
> 
>     When disabled, equations etc. will appear as their untransformed TeX source.
> --no-script
>     DEPRECATED, IGNORED
> --generate-config
>     generate default config file
> --certfile=<Unicode> (NotebookApp.certfile)
>     Default: u''
>     The full path to an SSL/TLS certificate file.
> --ip=<Unicode> (NotebookApp.ip)
>     Default: 'localhost'
>     The IP address the notebook server will listen on.
> --pylab=<Unicode> (NotebookApp.pylab)
>     Default: 'disabled'
>     DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
> --log-level=<Enum> (Application.log_level)
>     Default: 30
>     Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
>     Set the log level by value or name.
> --port-retries=<Integer> (NotebookApp.port_retries)
>     Default: 50
>     The number of additional ports to try if the specified port is not
>     available.
> --notebook-dir=<Unicode> (NotebookApp.notebook_dir)
>     Default: u''
>     The directory to use for notebooks and kernels.
> --keyfile=<Unicode> (NotebookApp.keyfile)
>     Default: u''
>     The full path to a private key file for usage with SSL/TLS.
> --client-ca=<Unicode> (NotebookApp.client_ca)
>     Default: u''
>     The full path to a certificate authority certificate for SSL/TLS client
>     authentication.
> --config=<Unicode> (JupyterApp.config_file)
>     Default: u''
>     Full path of a config file.
> --port=<Integer> (NotebookApp.port)
>     Default: 8888
>     The port the notebook server will listen on.
> --transport=<CaselessStrEnum> (KernelManager.transport)
>     Default: 'tcp'
>     Choices: [u'tcp', u'ipc']
> --browser=<Unicode> (NotebookApp.browser)
>     Default: u''
>     Specify what command to use to invoke a web browser when opening the
>     notebook. If not specified, the default browser will be determined by the
>     `webbrowser` standard library module, which allows setting of the BROWSER
>     environment variable to override it.
> 
> To see all available configurables, use `--help-all`
> 
> Examples
> --------
> 
>     jupyter notebook                       # start the notebook
>     jupyter notebook --certfile=mycert.pem # use SSL/TLS certificate
>     jupyter notebook password              # enter a password to protect the server
> 
> [C 16:31:14.236 NotebookApp] Bad config encountered during initialization:
> [C 16:31:14.239 NotebookApp] The 'kernel_spec_manager_class' trait of <notebook.notebookapp.NotebookApp object at 0x0000000003138A58> instance must be a type, but u'nb_conda_kernels.CondaKernelSpecManager' could not be imported
>

**Comment by wanglongqi** [comment]
Problem of browser, do not know detail.

**Comment by didopop3** [comment]
I had similar issue. 
because jupyter notebook requires token and the browser has the cookies with the old token. 
So clearing the cookies worked for me

**Comment by amitsharma23** [comment]
I am also facing the same issue of 0 active kernels. I am not being able to execute any codes in Jupyter. I have also disabled the firewall in my system but still, the problem persists.
![capture](https://user-images.githubusercontent.com/40753294/44958844-60e23400-af03-11e8-957d-b1defec67b09.JPG)
