### ISSUE TITLE
Regression issue 

### ISSUE THREAD

**Issue by bharagavafirst** [jupyter/notebook#2835]
HI All ,

im getting below error message while running linear regression in python please help 

ValueError: could not convert string to float: 'yes'

**Comment by Yatekii** [comment]
Unfortunately that is not a Jupyter based issue but rather one with your input to the linear regression lib, which of course cannot regress strings ...

I don't know what lib you are using but I am guessing scipy/numpy. I advise to have a good second look at your data set and maybe ask in a scipy/numpy related place.

Good luck!
