### ISSUE TITLE
Can't Notebook inside an iframe

### ISSUE THREAD

**Issue by qmaxquique** [jupyter/notebook#284]
Hello,
I want to use Jupyter Notebook inside the Terminal.com IDE but looks like **I'm not allowed to show the Notebook interface inside an iframe**. Could you please tell me if that is possible somehow?

This is what I get in the browser console:
```
Refused to display 'https://qmaxquique121-8080.terminal.com/tree' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'"
```

Thank you!

**Comment by qmaxquique** [comment]
This can be done by adding something like this in the settings file:
```
c.NotebookApp.tornado_settings = { 'headers': { 'Content-Security-Policy': "frame-ancestors 'self' https://*.terminal.com" } }
```

**Comment by satendrakumar06** [comment]
Hello @qmaxquique 

I am also facing same problem with  iframe. I have tried as you have mentioned "c.NotebookApp.tornado_settings" . I didn't work.
I have tried both way:
without SSL 
```[W 16:43:55.857 NotebookApp] Content security violation: {"csp-report":{"blocked-uri":"","document-uri":"http://192.168.2.115:9999/tree","original-policy":"frame-ancestors http://192.168.2.115:9999; report-uri http://192.168.2.115:9999/api/security/csp-report","referrer":"http://192.168.2.115:9191/","violated-directive":"frame-ancestors http://192.168.2.115:9999"}}```

using SSL
```[W 16:42:20.882 NotebookApp] Content security violation: {"csp-report":{"blocked-uri":"","document-uri":"https://192.168.2.115:9999/tree","original-policy":"frame-ancestors https://192.168.2.115:9999; report-uri https://192.168.2.115:9999/api/security/csp-report","referrer":"http://192.168.2.115:9191/","violated-directive":"frame-ancestors https://192.168.2.115:9999"}}```
