### ISSUE TITLE
Turn off toolbar labels.

### ISSUE THREAD

**Issue by achampion** [jupyter/notebook#2845]
The latest update has started displaying labels with the toolbar buttons.
There doesn't seem to be a simple way to revert back to just icons. I've modified my custom.css to get the old display back:

    .toolbar-btn-label { display: none }

But this seems crude.

**Comment by zertrin** [comment]
To add some more details: this seems to have been added by PR #2433 (where only the Run button gets a label) but the author of that PR did not take into account the buttons added by some `jupyter_contrib_nbextensions`

This is what I got after upgrading to 5.1: (before the upgrade, there was no text at all)

![image](https://user-images.githubusercontent.com/1447163/31065626-82de5652-a779-11e7-8b62-c6b622b7b8d9.png)

Not sure if this is the fault of the contributors to jupyter_contrib_nbextensions or if the PR was too broad.

**Comment by takluyver** [comment]
Yeah, sorry, there are several different ways to add a button, and I failed to consider one of them that's apparently widely used. I'm reluctant to change the API now that it's released. Extensions can work around it with a change something like this:

https://github.com/takluyver/cite2c/commit/f310fb00af829664c756404c343d948ab556a2e0

**Comment by zertrin** [comment]
Just for information, the needed changes to the extensions seems to be tracked here: 
* Issue: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1102
* Pull request: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/1103

**Comment by takluyver** [comment]
Thanks for the links!

**Comment by takluyver** [comment]
Closing as I think this has been resolved by changes in extensions.
