### ISSUE TITLE
Geopy module not found when trying to install from anaconda cmd

### ISSUE THREAD

**Issue by harshinielath** [jupyter/notebook#2847]
![cn](https://user-images.githubusercontent.com/19167800/30525869-4dfa8d98-9bd5-11e7-8a69-0d20eaefeae2.PNG)

**Comment by takluyver** [comment]
That doesn't look like a Jupyter issue - try asking geopy about the installation process.

**Comment by harshinielath** [comment]
got the problem solved
i had to give the command
conda config --add channels conda-forge
and then
conda install geopy

**Comment by thisisprabin** [comment]
conda install -c conda-forge geopy works on my mac well
