### ISSUE TITLE
convert notebook (contains Chinese words) to PDF successfully but those Chinese words are missing 

### ISSUE THREAD

**Issue by linzch3** [jupyter/notebook#2848]
First, I cannot convert my notebook to PDF for the reason that Chinese words is in the notebook. And I find 
this issue https://github.com/jupyter/notebook/issues/1674, and I find the following command 

`pip install git+https://github.com/jupyter/nbconvert.git`

After using this command, It really works for me, and the notebook could be  converted to PDF。

But the problems is : **those Chinese words in notebook are missing,**  I don't know what happened.

---
take this part of my notebook as example:

![11111](https://user-images.githubusercontent.com/20380442/30532699-47a36934-9c88-11e7-8fe7-67d8b4e60816.jpg)

after being converted to PDF, It look like this:

![image](https://user-images.githubusercontent.com/20380442/30532731-75ccb5e0-9c88-11e7-83bf-9b7ce9f8c23c.png)

 **those Chinese words in notebook are missing.**

**Comment by linzch3** [comment]
Wa-wu. I just found that here: http://www.cnblogs.com/xuanyuyt/p/7471316.html is solution to this.

And although Chinese words isn't missing in the PDF, you should name you notebook'name with English, otherwise you will get a title in the first page of the PDF(look like this --> ?????)。

**Comment by zlxs23** [comment]
Yeah. I have a new way to solve **'中文不显示'**, and my platform: ubuntu 16, python3.5, ipython/jupyter intalled by pip.
1. 安装 texlive
```shell
sudo apt-get install texlive-xetex
```
2. 安装 pandoc
```shell
sudo apt-get install pandoc
```
3. 安装 微软雅黑 字体 (msyh.ttf) [其他中文字体亦可]
```shell
# download msyh.ttf
sudo cp msyh.ttf /usr/share/fonts
sudo fc-cache -f -v
```
4. 修改当前环境下的 article.tplx
```
# @article.tplx
add
\usepackage{xeCJK}
\setCJKmainfont{Microsoft YaHei}  # match font name
after
\documentclass[11pt]{article}
```
大功告成，就可以 Dowload as PDF via LaTeX 啦
参考:

[ubuntu 中文论坛](http://forum.ubuntu.org.cn/viewtopic.php?p=3078567)  #2楼
[LaTex 字体设置参考 csdn](http://blog.csdn.net/phoenixtree7/article/details/43523861)
[Windows 修改 article](http://www.cnblogs.com/xuanyuyt/p/7471316.html)

**Comment by zhuxiaoxi** [comment]
@zlxs23 用这个方法，发现不能完全解决导出tex中文乱码，导出的标题中如果含有中文，就会显示为问号，在tex文件中显示为`\title{????}`，正文中的中文可以解决。请问这个问题该如何解决到？

**Comment by zhnuaa** [comment]
> @zlxs23 用这个方法，发现不能完全解决导出tex中文乱码，导出的标题中如果含有中文，就会显示为问号，在tex文件中显示为`\title{????}`，正文中的中文可以解决。请问这个问题该如何解决到？

# 修改配置文件

`~\Anaconda3\pkgs\nbconvert-5.4.0-py37_1\Lib\site-packages\nbconvert\templates\latex\`

## artical.tplx

```latex
%===============================================================================
% Latex Article
%===============================================================================

((* block docclass *))
\documentclass{article}
	\usepackage{ctex}
	\setmainfont{STSong}
((* endblock docclass *))

```

## base.tplx

+ 注销`fontenc`

```latex
%\usepackage[T1]{fontenc}
```

+ 修改`tittl`生成规则

```latex
((* block title *))\title{((( resources.metadata.name | ascii_only | escape_latex )))}
    ((* endblock title *))
```

修改为：

```latex
((* block title *))\title{((( resources.metadata.name | escape_latex )))}((* endblock title *))
```
