### ISSUE TITLE
Copy from Terminal Selecting Wrong Value

### ISSUE THREAD

**Issue by cancan101** [jupyter/notebook#2850]
I have the following on my terminal:
```
jjia@node002-jupyter-20170918-141251:/usr/src/app$ date
Mon Sep 18 15:27:19 EDT 2017
jjia@node002-jupyter-20170918-141251:/usr/src/app$
```
but when I try to copy and then paste the first two, I end up getting:
```
Mon Sep 18 15:27:19 EDT 2017
jjia@node002-jupyter-20170918-141251
```

**Comment by cailiang9** [comment]
https://github.com/sourcelair/xterm.js/pull/910

**Comment by parente** [comment]
Quick experimentation for a hacky workaround while things get fixed upstream. Replacing this rule:

https://github.com/jupyter/notebook/blob/master/notebook/static/terminal/less/terminal.less#L24-26

with:

```
.xterm-rows {
  top: 10px;
  left: 10px;
}
```

and adding rule:

```
.xterm-selection {
  top: 10px;
  left: 10px;
}
```

seems to work around the problem with xterm 2.8.1 included in the notebook 5.1 release.

**Comment by cancan101** [comment]
@parente do you want to pr that change?

**Comment by takluyver** [comment]
Is working around it going to cause any problems when it's fixed in xterm? I don't think we have a great way to ensure that the workaround is removed when we upgrade it.

**Comment by oeway** [comment]
@cancan101 Could you please fix this issue?  sourcelair/xterm.js#910 seems ready. It's a bit annoying for copy and paste from the current terminal. Thank you.

**Comment by cancan101** [comment]
V3 hasn't been released yet. Should be any day

**Comment by cancan101** [comment]
New version of xterm (v3.0.1) has been released. That being said, they have [dropped support for bower](https://xtermjs.org/docs/guides/download/#no-more-bower-support). Any chance to pull in dependencies from npm / yarn?
