### ISSUE TITLE
How to change the autosave interval?

### ISSUE THREAD

**Issue by danqing** [jupyter/notebook#2859]
It seems that things are pretty in the flux, so I'm not sure what's the right way to set autosave interval now... Using 5.1, the following doesn't seem to work:

```js
define(['base/js/namespace', 'base/js/promises'], function(Jupyter, promises) {
  promises.notebook_loaded.then(function() {
    Jupyter.notebook.set_autosave_interval(10000);
  });
});
```

Any pointer is super appreciated. Thanks!

**Comment by takluyver** [comment]
Are there any error messages in the JS console? If you put `console.log` calls in there, can you see them getting logged?

**Comment by danqing** [comment]
There are no errors. If I put `console.log` in the promises block it is called. However, The notebook doesn't seem to be saving every 10 seconds.

How can I check/confirm the current autosave interval? Is `notebook_loaded` the right event to set the interval at?

**Comment by danqing** [comment]
@takluyver I think it uses your change here: https://github.com/jupyter/notebook/blob/master/notebook/static/base/js/promises.js

But I may not be using it correctly. Do you discern any issues above?

**Comment by takluyver** [comment]
I don't see anything wrong with that. You can check in a Javascript console with `Jupyter.notebook.autosave_interval`.

**Comment by danqing** [comment]
Hmm... If I set the interval to 10000, a notebook will autosave every 10 seconds right?

My issue is actually that I have a server that serves a notebook, but when I shut down the notebook, it doesn't contain the latest change. Is there a more "correct" way of triggering a save (without the user clicking on a button)?

Thanks!

**Comment by danqing** [comment]
Actually, looks like I can call `notebook.save_checkpoint` to trigger a save.
