### ISSUE TITLE
More than one matrix in equation are not rendered in html

### ISSUE THREAD

**Issue by RaulDurand** [jupyter/notebook#2865]
The equation below is rendered ok in the browser but when the notebook is downloaded as html the equation is not rendered properly. It shows part of the Latex code instead.

I tested with other examples and noticed that this happens when the equation has more than one matrix.
```latex
$$
\begin{bmatrix}
1 & x_1 & x_1^2 & \cdots & x_1^m \\
1 & x_2 & x_2^2 & \cdots & x_2^m \\
1 & x_3 & x_3^2 & \cdots & x_3^m \\
\vdots \\
1 & x_n & x_n^2 & \cdots & x_n^m
\end{bmatrix}
\begin{pmatrix}
a_1 \\ a_2 \\ a_3 \\ \vdots \\ a_n
\end{pmatrix}
=
\begin{pmatrix}
y_1 \\ y_2 \\ y_3 \\ \vdots \\ y_n
\end{pmatrix}
$$
```

**Comment by takluyver** [comment]
Check that you have an up to date version of the nbconvert package, which does the conversion to HTML. Older versions used a URL for mathjax that later broke.

**Comment by gnestor** [comment]
I can confirm that LaTeX is properly exported to HTML using nbconvert 5.2.1.

![image](https://user-images.githubusercontent.com/512354/30869459-0723c4f8-a296-11e7-987e-ff4fd67233a7.png)

@RaulDurand I'm going to close this but feel free to re-open if this issue persists after upgrading nbconvert to >=5.2.1.

**Comment by RaulDurand** [comment]
Indeed, the problem was solved after upgrading nbconvert.
Thanks a lot @takluyver and @gnestor.
