### ISSUE TITLE
File browser HTML view fails on spaces in directories

### ISSUE THREAD

**Issue by jeremydouglass** [jupyter/notebook#2867]
To reproduce:

1. create directory `/work/a space/`
2. create `/work/a space/index.html`
3. edit index.html -- editor launches correctly at `/edit/work/a%20space/index.html`
4. in file browser, select checkbox by index.html and hit view button
5. file browser incorrectly directs to `/view/work/a%2520space/index.html` and incorrectly displays a **404 : Not found**
6. manually correcting the path to `/view/work/a%20space/index.html` correctly displays the file

Summary: editing an HTML file on a spaced path works, viewing a file does not.

Note the %2520 -- this is a common double-encoding error, when the string is encoded once `a space` -> `a%20space` and then accidentally re-encoded `a%20space` -> `a%2520space`.

https://stackoverflow.com/a/16085190/7207622

> The version of the notebook server is 5.0.0 and is running on:  
> Python 3.6.2 | packaged by conda-forge | (default, Jul 23 2017, 22:59:30)   
> [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

**Comment by takluyver** [comment]
Can you try with notebook server 5.1? I vaguely remember fixing something like this.

**Comment by gnestor** [comment]
I can confirm that this is resolved 5.1 👍 As a result, I'm going to close this but feel free to open it again if the issue persist after upgrading to 5.1.

**Comment by jeremydouglass** [comment]
Okay -- I see that notebook 5.1.x is not yet available through any of the docker-stacks in any branch. In order to resolve this issue in a stacks notebook deployment, am I right that I would download the full docker-stacks repo?

https://github.com/jupyter/docker-stacks/

...and then modify the base notebook line from 5.0.x to 5.1.x:

https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L78

...and then build my own e.g. jupyter-datascience notebook image, and then deploy a container and test?

**Comment by gnestor** [comment]
Good catch @jeremydouglass!! I just submitted a PR to update the docker-stacks: https://github.com/jupyter/docker-stacks/pull/473

To answer your question: yes. You can wait for this PR to be merged, or you can apply the patch yourself (https://patch-diff.githubusercontent.com/raw/jupyter/docker-stacks/pull/473.patch), or clone my branch.

**Comment by jeremydouglass** [comment]
Thank you so much, @gnestor.

**Comment by jofowler** [comment]
I am having a problem in notebook 5.7.0 with very similar symptoms. I wrote that problem up in issue #5592
