### ISSUE TITLE
STATA 12 won't register

### ISSUE THREAD

**Issue by HasayeretFMG** [jupyter/notebook#2870]
Hi guys!
Full disclaimer: I am not a Python/Anaconda/Jupyter user: I am an IT Admin whose trying helping one of his users to register STATA. 
We went through all the requirements here and we made sure we have everything:
https://github.com/TiesdeKok/ipystata

What I did was opening CMD as an domain admin and navigate to the Stata folder in Program Files (X86). Then I ran the following command StataSE-64.exe. /Register.
I did not get any error message or anything and the screen looked like that:
![stata](https://user-images.githubusercontent.com/32338486/30926950-d0f21502-a384-11e7-9dda-7d7f18bc9b40.jpg)

The when we've opened Jupyter via Anaconda and hit "new" we only say "Python" but not "Stata". 
I did the same thing on a different computer and it worked fine and that computer had an earlier version of Anaconda. We tried completely removing Anaconda and re-installing it to the latest version and it didn't do the trick. 

Any idea on what's missing?

Thanks!!!

**Comment by takluyver** [comment]
I think that in the first instance you'll need to debug that with @TiesdeKok, the author of ipystata.

**Comment by TiesdeKok** [comment]
Thanks @takluyver for the heads up.  `ipystata` works as a magic function with `%%stata` so you just start a Python kernel, it doesn't add a Stata kernel. See example here: http://nbviewer.jupyter.org/github/TiesdeKok/ipystata/blob/master/ipystata/Example.ipynb

If this doesn't solve the problem, feel free to open an issue on the `ipystata` GitHub page and I am glad to help you there.

**Comment by takluyver** [comment]
Thanks Ties. I'll close this issue, then.

**Comment by HasayeretFMG** [comment]
Hi guys,

As I said, I am not really coming from this world so here's what the user who is more familiar with this told me. 

Ipystata and %%stata work fine, but the ipystata library for python is built to allow the user to execute stata syntax within a python jupyter notebook.

What I am trying to do on the desktop (and what is working on the laptop) is create a stata jupyter notebook. 

Any idea how to help with this one?

**Comment by TiesdeKok** [comment]
@HasayeretFMG a Stata kernel is beyond ipystata or the jupyter notebook. There is this: https://github.com/jrfiedler/stata-kernel but it is not actively maintained as far as I know. Hope this helps.

**Comment by HasayeretFMG** [comment]
Hi guys,

I am attaching two images: one from the desktop where you can clearly see that Python is only registered and the second one is from the laptop where you can see both Python and Stata. I tried doing the exact same thing on the desktop which is basically just running the register command as I mentioned earlier but for some reason it won't di that. Hopefully this makes more sense and if not: I apologize again! :)

![desktop](https://user-images.githubusercontent.com/32338486/31022029-9d3333ae-a505-11e7-825c-8b0b39a855d6.jpg)
![laptop](https://user-images.githubusercontent.com/32338486/31022028-9d27cece-a505-11e7-83e5-24a10fcda1a1.jpg)

**Comment by takluyver** [comment]
I think that means you have installed [stata-kernel](https://github.com/jrfiedler/stata-kernel) on the desktop at some point. That menu lists kernels, and it sounds like ipystata does not provide a kernel.

**Comment by HasayeretFMG** [comment]
Thanks for your help. So if that's the case, how do I make sure that it functions like the laptop?

**Comment by takluyver** [comment]
Install stata-kernel on the laptop? Or use the `%%stata` magic on both.

**Comment by HasayeretFMG** [comment]
It's the desktop that is missing the STATA option (that the 1st image above).

**Comment by takluyver** [comment]
Oh, sorry, I got them the wrong way round. You must have installed stata-kernel on the *laptop*. If you want the desktop to function like that, install stata-kernel on the *desktop* as well.

**Comment by HasayeretFMG** [comment]
Let me make sure that my user didn't install it but just in case she didn't, can you walk me through on how to do that?

**Comment by takluyver** [comment]
I've never seen it before Ties mentioned it, but there are instructions in its README:
https://github.com/jrfiedler/stata-kernel

;-)
