### ISSUE TITLE
nbextension enable fails with importerror

### ISSUE THREAD

**Issue by kain88-de** [jupyter/notebook#288]
See

https://github.com/ipython-contrib/IPython-notebook-extensions/issues/253

I have installed the jupyter-notebook with an upgrade from ipython as mentioned in the release blog post

```
pip install --user --upgrade 'ipython[all]'
```

Confusingly enough I can run `from notebook.services.config import ConfigManager` from a 
ipython-session. Are there any Environment-variables I should check/correct?

**Comment by minrk** [comment]
It's a bug in the import that only affects Python 2. Fixed by #289.

**Comment by kain88-de** [comment]
thanks for fixing it
