### ISSUE TITLE
Codes in f-string are not highlighted in Python 3 Notebook.

### ISSUE THREAD

**Issue by wotsushi** [jupyter/notebook#2881]
## Abstract
It would be nice if codes in f-string are highlighted in Python 3 Notebook.

## Steps to reproduce
Jupyter Notebook version: 5.1
1. Open a Python 3 Notebook.
2. Insert a code cell.
3. Input `f'{list(map(lambda x: 2 * x, [1, 2, 3]))}'` into the inserted cell.

## Actual Result
Codes in f-string are not highlighted as follows:
![2017-09-30 15 23 01](https://user-images.githubusercontent.com/15275136/31043340-ddbbb794-a5f4-11e7-9c46-e1559bdecd27.png)

## Expected Result
Codes in f-string are highlighted like follows:
![2017-09-30 15 21 48](https://user-images.githubusercontent.com/15275136/31043331-be5ea898-a5f4-11e7-95c6-a04cafa82137.png)

**Comment by takluyver** [comment]
The editor component we use is called Codemirror; support for f strings would need to be added to Codemirror, and then we'd need to upgrade to a new version.

It doesn't look like there's any issue for this yet, but you can see a previous pull request which got it to correctly tokenise strings with an f prefix: https://github.com/codemirror/CodeMirror/pull/3975

**Comment by wotsushi** [comment]
Thank you for your nice comment.
I close this issue and I'll see discussions about Codemirror.

**Comment by flying-sheep** [comment]
Fixed in codemirror/CodeMirror@30ae1edf7c2b1086a13d08cfdb35594bea39d030

**Comment by wotsushi** [comment]
Thanks for fixing the issue!
