### ISSUE TITLE
Feature request: Markdown preview on the side

### ISSUE THREAD

**Issue by ufoscout** [jupyter/notebook#2882]
Hi all,

I wonder if there is any plan to include a markdown preview panel that shows the output preview while typing. For example, this is how it is implemented in vscode (in atom there's the same feature):

![screenshot_20170930_151123](https://user-images.githubusercontent.com/960885/31046040-0336c9a8-a5f2-11e7-9b90-3e8b0e364c29.png)

The scroll of the two tabs is synchronized making the edit experience very simple; essentially, editing a doc is a matter of:
-> type -> check on the side panel -> type

On the contrary, in jupiter notebook the edit flow is like:
-> type -> click run -> check output (find the exact point you edited) -> double click to go back to edit mode -> click on the line you were editing -> type
A side panel would make it more user friendly.

**Comment by ptbrowne** [comment]
For what's it's worth, I've added a Stylish extension to Jupyter to show my code output cells on the side. I was coming on the GitHub issues to see if people had already opened this kind of issue.

Here is the content of the stylesheet:

```
#notebook-container {
    width: 100%
}

.cell {
   flex-direction: row !important;
}

.cell .input {
    width: 50%
}


.cell .output_wrapper {
    width: 50%
}
```

It is not giving you synchronized scroll but at least, Markdown should be easier to preview like that.

![image](https://user-images.githubusercontent.com/465582/31145793-0d7909e0-a885-11e7-90dd-b26ad40e97ea.png)

**Comment by keelung-yang** [comment]
@ufoscout Me too, real-time preview is nice!

**Comment by Madhu94** [comment]
@ufoscout You can also check out [nteract](nteract.io).

**Comment by lzkelley** [comment]
@ptbrowne can you explain a bit how to use this?

**Comment by ptbrowne** [comment]
1. Install the Stylish extension. https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=fr
2. Click the stylish icon, click the 3 dots menu, click Create New Style.
3. Copy paste my style, give a name, save

You now have the preview on the side.

**Comment by jcb91** [comment]
I've written a small nbextension that provides a live rendering of markdown cells while editing them - see https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/1155

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter/notebook/pull/6921.

This will be available in Notebook 7:

https://github.com/jupyter/notebook/assets/591645/73dc4854-8bfb-4bad-90fd-ada2bbf9b3dc
