### ISSUE TITLE
nbconvert failed: Could not decode for unicode trait 'texinputs' of a PDFExporter instance

### ISSUE THREAD

**Issue by rotsee** [jupyter/notebook#2885]
When trying to save a PDF, I sometimes get the error `nbconvert failed: Could not decode for unicode trait 'texinputs' of a PDFExporter instance.`. This seems to happen only when there are characters like e.g. 'å', 'ä' or 'ö' in the path name of the notebook. Renaming all such folders solves the problem.

Ubuntu 17.04
Jupyter notebook 4.2.2
IPython 5.0.0
Python 2.7.13

**Comment by takluyver** [comment]
What version of nbconvert? Try upgrading it to the latest.

**Comment by rotsee** [comment]
It seems to be on the latest version available on Ubuntu:
```
$ sudo apt upgrade jupyter-nbconvert
jupyter-nbconvert is already the newest version (4.2.0-4).
```

**Comment by takluyver** [comment]
Versions available through apt are usually out of date, and we can't do much about it. The latest nbconvert is actually 5.3.1.

We recommend installing with pip (`pip install --upgrade --user nbconvert`), or setting up a whole Python environment using [Anaconda](https://www.anaconda.com/download/#linux), which you can then keep up to date with the conda package manager it includes.
