### ISSUE TITLE
Switch to puppeteer for regression tests

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/notebook#2891]
[PhantomJS is no longer maintained](https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE) and there is a solid, stable replacement -- chrome headless. In particular, we'd probably want to use [`puppeteer`](https://github.com/GoogleChrome/puppeteer) which has a fairly similar API to casper.

I've done a tiny amount of instrumentation of jupyter notebook using puppeteer and it has been quite nice. I could make a PR but for now I'll just show what I've got:

```js
// The grand fantastic library
const puppeteer = require("puppeteer");

// My brain is 80% RxJS at this point, you'll see how I use it below
const spawnRx = require("spawn-rx");

// Will use this for coloring output
const chalk = require("chalk");

// Operators for use with the spawned notebook server
require("rxjs/add/operator/filter");
require("rxjs/add/operator/share");
require("rxjs/add/operator/toPromise");
require("rxjs/add/operator/first");

async function main() {
  // We could/should generate this, I'm just setting it here to demonstrate
  const TOKEN = "applesaucemcgee";

  const jupyter$ = spawnRx
    .spawn("jupyter", [
      "notebook",
      "--no-browser",
      `--NotebookApp.token='${TOKEN}'`
    ])
    // we keep one jupyter notebook server running, the share operator
    // allows us to subscribe to this stream multiple times while only launching
    // one server for all N subscriptions
    .share();

  // Log everything from the notebook server, dimming it for readability amongst
  // our own output
  const d1 = jupyter$.subscribe(data => console.log(chalk.dim(data)));

  // Wait for the server to be up by waiting for the "Welcome" banner
  await jupyter$
    .filter(x => /Welcome to Project Jupyter/.test(x))
    .first()
    .toPromise();
  // Note that we could have used the above filtering to get the URL of the
  // notebook server -- port, token, and all

  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  try {
    await page.goto(`http://127.0.0.1:8888/tree?token=${TOKEN}`);
  } catch (error) {
    // In case we can't connect to the notebook server, we should exit early
    console.error(error);
    d1.unsubscribe();
    return;
  }

  // Get the version!
  const version = await page.evaluate(() => {
    return Jupyter.version;
  });
  console.log("Jupyter version: ", version);

  // Take a snap!
  await page.screenshot({ path: "example.png" });

  // Clean up!
  await browser.close();
  d1.unsubscribe();
  console.log("cleaned up nicely");
}

main().catch(e => console.error("Main errored", e));
```

Terminal output:

![screen shot 2017-10-02 at 8 34 09 am](https://user-images.githubusercontent.com/836375/31085598-7c78a7ea-a74c-11e7-8a5a-fb551278ca28.png)

Screenshot that was grabbed using the API above:

![example](https://user-images.githubusercontent.com/836375/31085625-8b7c3cb6-a74c-11e7-942c-d30f3e5bc7a0.png)

**Comment by blink1073** [comment]
![magic](https://user-images.githubusercontent.com/2096628/31085812-c42ef920-a75d-11e7-872e-d430341a2824.gif)

**Comment by blink1073** [comment]
Sweet, also available for use in [karma tests](https://github.com/karma-runner/karma-chrome-launcher#headless-chromium-with-puppeteer).

**Comment by rgbkrk** [comment]
Gosh I wish we were on karma for classic. I can't recall how that went when @jdfreder did some adaptation. Maybe we bit off too much too soon.

I think I'm going to try to adapt the test suite so it _mostly_ fits in with the current way it runs. I should hopefully have it situated enough that people can tackle converting individual test cases in parallel with me.

**Comment by rgbkrk** [comment]
I've got a branch for this and I'm currently in progress on it, in case folks are wondering. If you'd like to see where things are at or want to join in, please let me know in the comments below.

Also please like and subscribe. #youtube

**Comment by takluyver** [comment]
How's the progress coming along? I think this is still blocking your PR #2884.

**Comment by rgbkrk** [comment]
I haven't been able to carve out time again for this, though I started on it in #3003.

**Comment by jtpio** [comment]
Closing as Notebook 7 developed on the `main` branch uses Playwright: https://playwright.dev/
