### ISSUE TITLE
Odd effect for markdown sublists when parent bullet has mark-up

### ISSUE THREAD

**Issue by riedelcastro** [jupyter/notebook#2893]
I am running the notebook server is 5.0.0 and have the following issue. When I create nested markdown lists where the parent bullets have markup (such as bold-face), empty space is inserted before the child list. That is

* Blah **blah**
  * Blub
  * Blub

Will look like

* Blah **blah**

  * Blub
  * Blub

I believe this is related to this line in `renderedhtml.less` (which is shown when I inspect the DOM tree at the corresponding point): 

https://github.com/jupyter/notebook/blob/82c33578e1a503d8e0799f6afdc7280b2b68a297/notebook/static/notebook/less/renderedhtml.less#L45

And indeed, inactivating this line in the browser fixes the problem temporarily. 

There must be something I configured wrongly. What could it be?

**Comment by takluyver** [comment]
Can you try upgrading to 5.1? I remember something like this which I think got fixed.

**Comment by riedelcastro** [comment]
Thanks! This worked!
