### ISSUE TITLE
How to create new `content type` or `file ext` for ContentsManager?

### ISSUE THREAD

**Issue by lab4quant** [jupyter/notebook#2895]
I'm working on a `jupyterlab-like` app, which requires to create new empty file other than `notebook`, `directory` and `file`.

I found this is controlled in notebook `ContentsManager.new_untitled()`, which validates content type, and the file extension is always '.ipynb' or '.txt'

How can I override the behavior, with notebook extension? I don't want to touch notebook code.
so that I could create new file with different file extension like '.xls', '.cal' etc ...

thanks!

**Comment by Madhu94** [comment]
You can create your own custom contents manager by subclassing the [ContentsManager](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/handlers.py#L67) class. That's what the notebook does, right [here](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L68).

I don't know if there is an easier way, let's wait for someone from the core team to respond..

**Comment by takluyver** [comment]
I would guess that the notebook server code has a pervasive assumption that there are only three basic types of file: directory, file, notebook. The main use case for subclassing ContentsManager today is to store those same kinds of things in a different way (e.g. in a database or on a cloud server).

I haven't tried this, so I may be overly pessimistic, but I suspect that it's complicated to add a new file type as things are today. I'm happy to be proven wrong, though.

**Comment by lab4quant** [comment]
@Madhu94 , @takluyver 
thanks for your update

If I need to subclass ContentsManager, can I do it in my own server extension? is there any sample code? thanks!

**Comment by Madhu94** [comment]
@lab4quant I had linked the example for subclassing the ContentsManager - https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L68

I think It's possible to give your choice of the contents manager in the [notebook's configuration](https://github.com/erdc/ipython_profile/blob/master/ipython_notebook_config.py#L75). 

But @takluyver is probably right, there may be other parts of the notebook codebase that just assume 3 types of content models - files/directory/notebook.

I'd say, give it a shot anyway:)

**Comment by lab4quant** [comment]
@Madhu94 , thanks!
