### ISSUE TITLE
Disable keyboard shortcuts when entring text in create shortcut menu

### ISSUE THREAD

**Issue by seregaxvm** [jupyter/notebook#2904]
In version 5.1.0 of notebook when entering keyboard shortcut menu from `Help->Keyboard shortcuts->Edit shortcuts` global shortcuts are not disabled.
For example, if I want to type `Ctrl-Enter` I would get only `Ct-Ente` because `r` and `l` are binded to the jupyter commands.

**Comment by takluyver** [comment]
It appears to be working correctly for me. What browser are you using? Can you describe exactly what sequence of clicks does this?

**Comment by seregaxvm** [comment]
I experience the same behavior on firefox nightly 58.0a1, surf 2.0 and ungoogled-chromium 58.
Exact key sequence is described in my previous message.
Note, that the same menu, accessed through `Help->Edit Keyboard Shortcuts` works fine.

**Comment by takluyver** [comment]
Ah, now I see it. Sorry, I skim read and was going to it directly from the help menu.

**Comment by takluyver** [comment]
Here's the relevant code: https://github.com/jupyter/notebook/blob/12592ef3bb2192b46052fd0ab6463757e8b5a49d/notebook/static/notebook/js/quickhelp.js#L285-L291

When a dialog opens, it disables our shortcuts, and when it closes, it re-enables them. But for some reason, the event from closing the first dialog fires *after* the event from opening the second one. So the shortcuts get re-enabled by the first dialog closing, even though another one is still open.

@Carreau @gnestor any ideas how to avoid that?

**Comment by Carreau** [comment]
> @Carreau @gnestor any ideas how to avoid that?

Not exactly sure; we should try to have a stack-based disablig / refcounting, but that might lead to other bugs.

**Comment by gnestor** [comment]
This seems to work for me:

```js
$(that.shortcut_dialog).on('hidden.bs.modal', function (e) {
    that.keyboard_manager.actions.call(
        'jupyter-notebook:edit-command-mode-keyboard-shortcuts'
    );
});
```

**Comment by takluyver** [comment]
Thanks @gnestor
