### ISSUE TITLE
Create notebook without kernel only for markdown editing

### ISSUE THREAD

**Issue by deebuls** [jupyter/notebook#2908]
Can a notebook be created without a coding kernel (python, r etc) just for markdown editing?
Or is there a only markdown kernel available?

**Comment by dsblank** [comment]
This would be useful. I think I would do it by just creating a Python kernel whose default cell type was Markdown, and naming it Markdown Kernel.

**Comment by shacharwize** [comment]
Hacktoberfest TLV shotgun!

**Comment by shaypal5** [comment]
> This would be useful. I think I would do it by just creating a Python kernel whose default cell type was Markdown, and naming it Markdown Kernel.

Does this mean that no actual Python kernel will be created? Because for me that's the point of such a feature.

**Comment by BoPeng** [comment]
With the new `--in` option of magic `%expand`, you can write markdown code in  [markdown kernel for Jupyter](https://github.com/vatlab/markdown-kernel) with inline expressions for Python and R directly, even in Rmarkdown style.

![image](https://user-images.githubusercontent.com/9889312/68432613-6461f280-017a-11ea-9e90-0c21a5258c10.png)

**Comment by jtpio** [comment]
> Allow me to introduce the [markdown kernel for Jupyter](https://github.com/vatlab/markdown-kernel).

Closing as fixed by this kernel, thanks @BoPeng for sharing!

Note that with Notebook 7 it's also possible to select "No Kernel" when creating a notebook:


https://github.com/jupyter/notebook/assets/591645/8b5133dd-125d-48b6-930e-2ac0812c5a8b

Thanks all!
