### ISSUE TITLE
ImportError: No module named ipywidgets

### ISSUE THREAD

**Issue by michaelaye** [jupyter/notebook#291]
I'm trying to run bokeh notebook examples with Jupyter 1.0/4.x. 
(BTW, which version is it now? (ana)conda claims it's 1.0 while `jupyter --version` says 4.0.3?)
When launching the [linked brushing example notebook](https://github.com/bokeh/bokeh/blob/master/examples/plotting/notebook/linked_brushing.ipynb) I get this in the terminal:

```bash
$ jupyter notebook .
[I 15:08:33.030 NotebookApp] The port 8888 is already in use, trying another random port.
[I 15:08:33.035 NotebookApp] Serving notebooks from local directory: /Users/klay6683/src/bokeh/examples/plotting/notebook
[I 15:08:33.035 NotebookApp] 0 active kernels
[I 15:08:33.035 NotebookApp] The IPython Notebook is running at: http://localhost:8889/
[I 15:08:33.035 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 15:08:39.781 NotebookApp] Notebook linked_brushing.ipynb is not trusted
[I 15:08:39.902 NotebookApp] Kernel started: 5be60a4c-0381-4968-9ec3-dfe264c508bf
[IPKernelApp] ERROR | Exception opening comm with target: ipython.widget
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/py27/lib/python2.7/site-packages/IPython/kernel/comm/manager.py", line 115, in comm_open
    f(comm, msg)
  File "/Users/klay6683/miniconda3/envs/py27/lib/python2.7/site-packages/IPython/kernel/zmq/ipkernel.py", line 21, in lazy_import_handle_comm_opened
    Widget.handle_comm_opened(*args, **kwargs)
  File "/Users/klay6683/miniconda3/envs/py27/lib/python2.7/site-packages/IPython/html/widgets/widget.py", line 116, in handle_comm_opened
    widget_class = import_item(msg['content']['data']['widget_class'])
  File "/Users/klay6683/miniconda3/envs/py27/lib/python2.7/site-packages/IPython/utils/importstring.py", line 42, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named ipywidgets
```

**Comment by minrk** [comment]
How did you install? What do you see from `pip list`? Does it work if you `pip install ipywidgets`?

**Comment by michaelaye** [comment]
I understand what happened: The Bokeh notebook switched the kernel to Python2 which I did not notice (because I was looking at the error message that popped up at the same time I could have looked at what kernel is running ;) ) and I had not yet installed jupyter on my conda python 2 env. After doing that, this error message disappears. Sorry for the noise.

**Comment by fhferreira** [comment]
I've runned the command below and all fixed for me
```
 pip install ipython notebook 
```

**Comment by Algabri** [comment]
the same issue 
`ImportError: No module named ipywidgets`
I tried from `sudo pip install ipywidgets`
outpot:
Requirement already satisfied: ipywidgets in ./.local/lib/python2.7/site-packages (7.4.2)
Requirement already satisfied: ipython<6.0.0,>=4.0.0; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from ipywidgets) (5.8.0)
Requirement already satisfied: ipykernel>=4.5.1 in ./.local/lib/python2.7/site-packages (from ipywidgets) (4.10.0)
Requirement already satisfied: nbformat>=4.2.0 in ./.local/lib/python2.7/site-packages (from ipywidgets) (4.4.0)
Requirement already satisfied: traitlets>=4.3.1 in ./.local/lib/python2.7/site-packages (from ipywidgets) (4.3.2)
Requirement already satisfied: widgetsnbextension~=3.4.0 in ./.local/lib/python2.7/site-packages (from ipywidgets) (3.4.2)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in ./.local/lib/python2.7/site-packages (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (1.0.15)
Requirement already satisfied: decorator in /usr/local/lib/python2.7/dist-packages (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (4.3.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python2.7/dist-packages (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (41.0.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python2.7/dist-packages (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (0.7.5)
Requirement already satisfied: pygments in /usr/lib/python2.7/dist-packages (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (1.6)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/lib/python2.7/dist-packages (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (3.1)
Requirement already satisfied: pathlib2; python_version == "2.7" or python_version == "3.3" in /usr/local/lib/python2.7/dist-packages (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (2.3.3)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (1.0.0)
Requirement already satisfied: simplegeneric>0.8 in /usr/lib/python2.7/dist-packages (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (0.8.1)
Requirement already satisfied: jupyter-client in ./.local/lib/python2.7/site-packages (from ipykernel>=4.5.1->ipywidgets) (5.2.4)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python2.7/dist-packages (from ipykernel>=4.5.1->ipywidgets) (4.5.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./.local/lib/python2.7/site-packages (from nbformat>=4.2.0->ipywidgets) (2.6.0)
Requirement already satisfied: jupyter-core in ./.local/lib/python2.7/site-packages (from nbformat>=4.2.0->ipywidgets) (4.4.0)
Requirement already satisfied: ipython-genutils in ./.local/lib/python2.7/site-packages (from nbformat>=4.2.0->ipywidgets) (0.2.0)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.3.1->ipywidgets) (1.12.0)
Requirement already satisfied: enum34; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.3.1->ipywidgets) (1.1.6)
Requirement already satisfied: notebook>=4.4.1 in ./.local/lib/python2.7/site-packages (from widgetsnbextension~=3.4.0->ipywidgets) (5.7.4)
Requirement already satisfied: wcwidth in ./.local/lib/python2.7/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (0.1.7)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets) (1.9.0)
Requirement already satisfied: pyzmq>=13 in ./.local/lib/python2.7/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets) (17.1.2)
Requirement already satisfied: python-dateutil>=2.1 in ./.local/lib/python2.7/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets) (2.8.0)
Requirement already satisfied: backports.ssl_match_hostname in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel>=4.5.1->ipywidgets) (3.7.0.1)
Requirement already satisfied: singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel>=4.5.1->ipywidgets) (3.4.0.3)
Requirement already satisfied: certifi in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel>=4.5.1->ipywidgets) (2018.11.29)
Requirement already satisfied: backports_abc>=0.4 in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel>=4.5.1->ipywidgets) (0.5)
Requirement already satisfied: functools32; python_version == "2.7" in ./.local/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets) (3.2.3.post2)
Requirement already satisfied: nbconvert in ./.local/lib/python2.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (5.4.1)
Requirement already satisfied: Send2Trash in ./.local/lib/python2.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (1.5.0)
Requirement already satisfied: prometheus-client in ./.local/lib/python2.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (0.5.0)
Requirement already satisfied: jinja2 in /usr/lib/python2.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (2.7.2)
Requirement already satisfied: ipaddress; python_version == "2.7" in ./.local/lib/python2.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (1.0.22)
Requirement already satisfied: terminado>=0.8.1 in ./.local/lib/python2.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (0.8.1)
Requirement already satisfied: entrypoints>=0.2.2 in ./.local/lib/python2.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in ./.local/lib/python2.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (1.4.2)
Requirement already satisfied: testpath in ./.local/lib/python2.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (0.4.2)
Requirement already satisfied: bleach in ./.local/lib/python2.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (3.1.0)
Requirement already satisfied: defusedxml in ./.local/lib/python2.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (0.5.0)
Requirement already satisfied: mistune>=0.8.1 in ./.local/lib/python2.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (0.8.4)
Requirement already satisfied: markupsafe in /usr/lib/python2.7/dist-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (0.18)
Requirement already satisfied: ptyprocess; os_name != "nt" in ./.local/lib/python2.7/site-packages (from terminado>=0.8.1->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (0.6.0)
Requirement already satisfied: configparser>=3.5; python_version == "2.7" in ./.local/lib/python2.7/site-packages (from entrypoints>=0.2.2->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (3.7.1)
Requirement already satisfied: webencodings in ./.local/lib/python2.7/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets) (0.5.1)


but when using pip list:
I cannt see ipywidgets

I dont know what happened!

please help me or any suggestions
