### ISSUE TITLE
PyPI has notebook 5.2.0rc1 as the default version

### ISSUE THREAD

**Issue by rolweber** [jupyter/notebook#2918]
I would expect that the stable version 5.1.0 is the default here:
https://pypi.python.org/pypi/notebook

**Comment by rolweber** [comment]
@gnestor: FYI, as you have created the [tag 5.2.0rc1](https://github.com/jupyter/notebook/releases/tag/5.2.0rc1).

**Comment by blink1073** [comment]
I believe this is a limitation of PyPI, because `pip install notebook` still points to 5.1 unless you add the `--pre` switch.

**Comment by takluyver** [comment]
I have unhidden 5.1.0 so you see both again for now. I don't think it's terribly important, though.

**Comment by rolweber** [comment]
Thanks!

**Comment by gnestor** [comment]
Should we not create git tags for releases candidates? 

Do we need to go into PyPI after publishing a release candidate and unhide the last release every time?

**Comment by takluyver** [comment]
It's definitely fine to create tags for pre-releases. We generally go in some time after the final release and delete the pre-release tags so the list doesn't grow too fast.

I don't think the default behaviour of PyPI is a problem (unless the README is significantly inaccurate for the stable version, or something).

**Comment by rolweber** [comment]
Unfortunately, a significant part of my job is to collect sets of libraries with compatible versions, and to track all version changes in order to get approvals for using the changed versions. I'm looking at PyPI way more often than I'd like to, and seeing a release candidate as the only non-hidden version of an established project is... odd. At least odd enough to open an issue the first time I encounter this situation.
It's not a big deal or showstopper in any way. But if you could change your deployment procedure (without much effort) so that new release candidates don't hide the last stable release, I'd appreciate it. 

Maybe PyPI has an option to create new releases as hidden, so that the previously visible version remains visible? Imho, that would be suitable for release candidates. Users interested in the latest release candidate could still find it tagged in GitHub, or mentioned on the Jupyter mailing list. Users not looking for release candidates specifically are most likely interested in the latest stable release.

**Comment by gnestor** [comment]
@rolweber I hear you and we will be conscientious of this in the future. I did a quick search and didn't find any simple way to not hide the latest stable release after publishing a pre-release.

**Comment by takluyver** [comment]
There's an option in the PyPI web UI to not hide old releases when you upload a new one. But it doesn't distinguish between prereleases and final releases.

I think [the view on Warehouse](https://pypi.org/project/notebook/) behaves as @rolweber wants. Warehouse is due to replace PyPI at some point in the future, so I wouldn't spend much effort trying to get it right with the current PyPI.
