### ISSUE TITLE
Nested sublists issue using LaTex

### ISSUE THREAD

**Issue by cmesro** [jupyter/notebook#2925]
I was attempting to create multiple, nested lists using LaTex but having an issue with Jupyter Notebook.  I am able to create 1 nested list, but run into issue when creating a second nested list.  This runs correctly in other LaTex applications, but is not working in jupyter notebook. I can use Markdown for a workaround, but I suspect a bug somewhere and wanted to share the issue. 

Code: 
\begin{itemize}
\item NoSub1
\item Sub1Title
    \begin{itemize}
    \item Sub1Item1
    \item Sub1Item2
    \end{itemize}
\item Sub2Title
    \begin{itemize}
    \item Sub2Num1
    \item Sub2Num2
    \end{itemize}
\item NoSub2
\end{itemize}

**Comment by gnestor** [comment]
@mpacer Any ideas?

**Comment by jfbercher** [comment]
@cmesro 
I think that this was a bug in [latex_envs](https://github.com/jfbercher/jupyter_latex_envs) nbextension, not in the notebook itself. (Actually the notebook does not render LaTeX itemize or enumerate lists). 

This was  implemented in the `latex_envs` nbextension, but I focused on a way to tackle nested environments of the same kind but forget that a given environment can include several environments of the same type at a given level; that is exactly the case you pointed above. This is corrected in the version on the repo and on pypi.

**Comment by cmesro** [comment]
Thanks for the fix!
