### ISSUE TITLE
Documentation: Explain what {section_name} is in config api endpoint

### ISSUE THREAD

**Issue by salilgupta1** [jupyter/notebook#2928]
I'm having a hard time understanding what the `{section_name}` should be in the config api endpoint. 
The swagger docs just show `/api/config/{section_name}`. Could someone please elaborate what `{section_name}` should be?

**Comment by blink1073** [comment]
Hi @salilgupta1, here is the relevant documentation: http://jupyter-notebook.readthedocs.io/en/stable/frontend_config.html#persisting-configuration-settings.

**Comment by gnestor** [comment]
Closing, feel free to reopen if this doesn't answer your question 👍
