### ISSUE TITLE
Can't edit Julia .jl files on 5.1.0

### ISSUE THREAD

**Issue by teored90** [jupyter/notebook#2933]
I just updated to version 5.1.0 and `.jl` files are not editable anymore (I can just download them). How do I add `.jl` files to the list of editable files?

**Comment by takluyver** [comment]
Try upgrading to 5.2.0, there were some more changes to this.

**Comment by teored90** [comment]
Indeed upgrading to 5.2.0 fixed the problem. Thank you!
