### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by orobsonpires** [jupyter/notebook#2935]
Hello guys,

I am running Jupyter on Ubuntu. I got the following issue:

jupyter@jupyter-VirtualBox:~$ sudo su
[sudo] password for jupyter: 
root@jupyter-VirtualBox:/home/jupyter# cd jupyterNoteBook/
root@jupyter-VirtualBox:/home/jupyter/jupyterNoteBook# clear
root@jupyter-VirtualBox:/home/jupyter/jupyterNoteBook# jupyter notebook
[W 14:25:42.244 NotebookApp] Config option `show_new_folder` not recognized by `NotebookApp`.
[W 14:25:42.245 NotebookApp] Config option `show_new_textfile` not recognized by `NotebookApp`.
[W 14:25:42.246 NotebookApp] Config option `show_terminals` not recognized by `NotebookApp`.
[W 14:25:42.247 NotebookApp] Config option `show_button_upload` not recognized by `NotebookApp`.
[I 14:25:43.490 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[W 14:25:44.254 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 14:25:44.255 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 14:25:44.275 NotebookApp] [nb_conda] enabled
[I 14:25:44.406 NotebookApp] [nb_anacondacloud] enabled
[I 14:25:44.505 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 14:25:44.505 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 14:25:44.509 NotebookApp] Serving notebooks from local directory: /home/jupyter/jupyterNoteBook
[I 14:25:44.509 NotebookApp] 0 active kernels 
[I 14:25:44.509 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:950/
[I 14:25:44.510 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 14:25:45.386 NotebookApp] Lexcorp: Killed all process jupyter kernel gateway.
[I 14:25:45.386 NotebookApp] Lexcorp: Run Notebooks: /home/jupyter/jupyterNoteBook/*.ipynb
[I 14:25:46.333 NotebookApp] Lexcorp: Running Notebooks.
[I 14:25:46.334 NotebookApp] Lexcorp: Start web services: python /root/.jupyter/custom/LexCorpJupyterServicesRest.py
[I 14:25:46.354 NotebookApp] Lexcorp: Started web services LexCorpJupyterServicesRest process: 4302
[I 14:25:46.360 NotebookApp] Lexcorp: Run CronJob: /root/.jupyter/custom/LexCorpJupyterCronJob.py
[I 14:25:46.436 NotebookApp] Lexcorp: Running CronJob.
[I 14:25:46.437 NotebookApp] Jupyter initialized...
Traceback (most recent call last):
  File "/root/.jupyter/custom/LexCorpJupyterServicesRest.py", line 29, in <module>
    execute()
  File "/root/.jupyter/custom/LexCorpJupyterServicesRest.py", line 26, in execute
    app.run(host=LexCorpUtil.WEB_SERVICES_IP, port=LexCorpUtil.WEB_SERVICES_PORT)
  File "/root/anaconda3/lib/python3.5/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/root/anaconda3/lib/python3.5/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/root/anaconda3/lib/python3.5/site-packages/werkzeug/serving.py", line 656, in inner
    fd=fd)
  File "/root/anaconda3/lib/python3.5/site-packages/werkzeug/serving.py", line 550, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/root/anaconda3/lib/python3.5/site-packages/werkzeug/serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/root/anaconda3/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/root/anaconda3/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/root/anaconda3/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address

I can create notebooks and all, however, no notebook is listed on my jupyter tree.

**Comment by takluyver** [comment]
The error appears to be coming from something called `LexCorpJupyterServicesRest.py`, which runs a separate web server using Flask. I'm not sure what that is.

**Comment by orobsonpires** [comment]
Yes, this was a problem inside of the module created by me.

**Comment by cyberwillis** [comment]
Sorry guys... earlier I sugested that I had a problem with the hostname "again" and related to this error message, but actually wasn't. Sorry to make the reference. 

Actually I was trying to turn on the jupyter notebook and accidentally have used **another IP** rather original of my machine and I got stuck with this message for some minutes without realise it.
