### ISSUE TITLE
Jupyter notebook stop - permission denied

### ISSUE THREAD

**Issue by ann-qin-lu** [jupyter/notebook#2937]
Hi, 
I just upgraded notebook to 5.2.0 and tried `_jupyter notebook stop 8888_`, but got:     
os.kill(server['pid'], signal.SIGTERM)
PermissionError: [WinError 5] Access is denied

My system is win10
I tried to run the cmd in admi mode, but still not worked.

Appreciate any helps.
Thanks!

**Comment by takluyver** [comment]
I think that feature may be written in a way that doesn't work at all on Windows. Sorry,  most of the core developers use Linux & Mac systems.

We should change it to try requesting a shutdown using the shutdown HTTP endpoint first, and only resort to signals if it hasn't shut down in a few seconds.
