### ISSUE TITLE
Question: Does jupyter expose any kind of 'activity' data?

### ISSUE THREAD

**Issue by luck02** [jupyter/notebook#2939]
I'm setting up a kubernetes based jupyter automation.

I'm using the `all-spark` docker image.  However for usage on a cluster it's really important to be able to detect if an app has gone dormant.  So when my analyst walks away, i'd like a programatic way to detect if the notebook is still active.

IE an API endpoint something along the lines of: SecondsSinceLastInteraction or similiar.  If we had that kind of telemetry I could easily set up a pass / fail based on how long it's been since the notebook was active and therefore kill it when it's not in use.

Has anything like this been discussed?  

Thanks!

**Comment by parente** [comment]
The `/api/kernels` and `/api/sessions` resources both expose fields including the last activity between the notebook server and kernel, and whether the kernel is currently busy or not. Notebook 5.1 and up have options for automatically killing kernels based on these two pieces of information.

Relevant PRs:

https://github.com/jupyter/notebook/pull/1827/
https://github.com/jupyter/notebook/pull/2215

**Comment by luck02** [comment]
Awesome, thanks!
