### ISSUE TITLE
LaTeX \boldsymbol not rendering

### ISSUE THREAD

**Issue by rlabbe** [jupyter/notebook#294]
I'm fairly sure this used to work. I upgraded 2 of my machines to IPython 4 and Jupyter via the Anaconda distribution, and left one at IPython 3. Only the IPython 4/jupyter machines exhibit the following behavior.

$\boldsymbol{..}$  no longer renders - it is displayed in red as a latex error. I tried install MathJax locally with

    from IPython.external.mathjax import install_mathjax
    install_mathjax()

but that did not help.

edit: I have mathjax 2.5.0 installed on my computer locally, and have checked that boldsymbol.js is in .ipython\nbextensions\mathjax\extensions\TeX. While opening the notebook the console displays

    404 GET /static/components/MathJax/extensions/Tex/boldsymbol.js?rev=2.5.3(::1) 9.00ms

**Comment by queru49** [comment]
I have the same problem, just after updating to Ipython 4 and Jupyter with Anaconda, like the OP, the \boldsymbol in all my notebooks stopped working.

Also, the headers in the markdown cells , like #Header_text now need an space between the # sign and the text: # Header_text

**Comment by Carreau** [comment]
1) will be fixed by https://github.com/jupyter/notebook/pull/324 

2) please keep 1 bug per issue. See https://github.com/jupyter/notebook/issues/304 the space in between `#` and text is due to marked that changed its behavior oand on which we have no control about sadly.

**Comment by Atcold** [comment]
What about `$\bm{...}$`? `$\boldsymbol{...}$ is deprecated and should be replaced by `bm`.

**Comment by AlJohri** [comment]
agreed. cc @Carreau. would love to see `\bm{...}`

**Comment by DCMMC** [comment]
but `\bm{...}` still not be implemented.

**Comment by icks** [comment]
Since @Carreau already closed this issue:
Are there any plans to implement `\bm{...}`? Should I open another issue for this?

**Comment by BlackSheepwall0305** [comment]
try `\mathbf{...}`
