### ISSUE TITLE
Add timestamp for each cell run

### ISSUE THREAD

**Issue by jakirkham** [jupyter/notebook#2940]
Would be really nice to have a time stamp included in the notebook for the time when a cell was run and the time it was completed. This can be really handy when looking back at profiling data from other sources and trying to determine the cause during one's run.

**Comment by takluyver** [comment]
The [ExecuteTime](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/execute_time/readme.html) extension can do something like this. We'd be wary of doing it by default, because it would make things worse for version controlling notebooks.

**Comment by jakirkham** [comment]
Yep, that looks exactly like what I want. Thanks for the tip. Agree this should be an optional thing.
