### ISSUE TITLE
Cell execution continues after completion of the last instruction

### ISSUE THREAD

**Issue by curziobasso** [jupyter/notebook#2948]
Hi there,

I have a strange problem that I am not able to track down to a know issue.
I am doing some data analysis on a notebook involving basic operations with pandas and numpy, and at some point every cell starts to behave like this: the kernel apparently completes all instructions in the cell, which typically ends printing out the result of the cell computations, but it remains busy (as indicated in the browser and checking the CPU) for tens of secs afterwards. 

I see no warnings/errors either in the terminal or in the browser console.

Could it be some thread still running? 

thanks for any suggestion

curzio

**Comment by takluyver** [comment]
I don't think a thread would hold it up like that.

Do you have a reproducible example that makes this happen? Does it happen in different browsers? Do you have any extensions or custom configuration that might be affecting it?

**Comment by curziobasso** [comment]
I am on macOS Sierra 10.12.6 and verified the same problem on:

- Safari Version 11.0 (12604.1.38.1.7)
- Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- Firefox 55.0.3 (64-bit)

BUT: it seems like the behaviour is due to one extension, "variable inspector". When disabled, it disappears. 

Stupid me for not thinking of the extensions, thanks for helping!

**Comment by takluyver** [comment]
No problem. I would guess that variable explorer does something after the cell to update itself. If there are some large variables, that could take a long time.
