### ISSUE TITLE
Unable to start IPython kernel with 4.0

### ISSUE THREAD

**Issue by mwaskom** [jupyter/notebook#297]
Hi, I've encountered a nasty issue after upgrading to jupyter.

Whenever I try to open a notebook and get working, it hangs. Eventually I get a popup notification that says

```
Connection failed
A connection to the notebook server could not be established. The notebook will continue trying to reconnect, but until it does, you will NOT be able to run code. Check your network connection or notebook server configuration."
```

In the terminal, I see:

```
[mlw-mbair ~]$ jupyter notebook --port 9999
[I 18:27:12.832 NotebookApp] Serving notebooks from local directory: /Users/mwaskom
[I 18:27:12.832 NotebookApp] 0 active kernels
[I 18:27:12.832 NotebookApp] The IPython Notebook is running at: http://localhost:9999/
[I 18:27:12.832 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 18:27:19.556 NotebookApp] Creating new notebook in /Desktop
[I 18:27:20.525 NotebookApp] Kernel started: 6834a152-cce8-47b9-888f-2166b86dfd2d
[I 18:27:23.524 NotebookApp] KernelRestarter: restarting kernel (1/5)
[I 18:27:26.532 NotebookApp] KernelRestarter: restarting kernel (2/5)
[I 18:27:29.539 NotebookApp] KernelRestarter: restarting kernel (3/5)
[W 18:27:30.611 NotebookApp] Timeout waiting for kernel_info reply from 6834a152-cce8-47b9-888f-2166b86dfd2d
[I 18:27:32.547 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 6834a152-cce8-47b9-888f-2166b86dfd2d restarted
Abort trap: 6
```

FWIW, I use anaconda but initially installed jupyter using pip when it was released, because I was eager to play with it. So perhaps that is the issue. However, in my attempts to remedy this, I have gone through multiple iterations of uninstalling with pip, uninstalling with conda, manually deleting everything that looks related in `site-packages` and `bin/` and yet the problem remains.

**Comment by Carreau** [comment]
This is a bug in jsonschema 2.5 see (among other) https://github.com/jupyter/notebook/issues/136, I suppose it also affect 2.4...

Try to install `functools32` ? (Or migrate to Python3, instead of still using legacy python :-) ) 

(closing, feel free to  reopen if it does not work)

**Comment by mwaskom** [comment]
Upgrading jsonschema via pip (btw 2.4 is the latest version available through conda) does fix the problem in the clean environment, but it does not fix the main issue in my default installation.

Presumably some previously existing library is interfering with the new notebook, but I am at a loss for what it might be. Any hints?

**Comment by mwaskom** [comment]
FWIW regular old console `ipython` works fine but `ipython qtconsole` pops up a window but immediately crashes with the following terminal output:

```
[mlw-mbair ~]$ ipython qtconsole
2015-08-15 19:01:04.902 python[23622:507] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/rr/svlz5yhs0tsdqnsp8g4qg65m0000gn/T/com.continuum.python.savedState
QPixmap::scaled: Pixmap is a null pixmap
/Users/mwaskom/anaconda/bin/python.app: line 3: 23622 Abort trap: 6           /Users/mwaskom/anaconda/python.app/Contents/MacOS/python "$@"
```

**Comment by mwaskom** [comment]
(I don't think I can reopen the issue as I'm not a Jupyter collaborator)

**Comment by Carreau** [comment]
`conda install functools32` ?  It seem to be "just" a missing dependency of jsonschema. 
I doubt there is anything we should do in nbformat.

**Comment by mwaskom** [comment]
I updated jsonschema in my default environment and it looks like it pulled in functools32

```
[mlw-mbair ~]$ pip install -U jsonschema
Requirement already up-to-date: jsonschema in ./anaconda/lib/python2.7/site-packages
Requirement already up-to-date: functools32 in ./anaconda/lib/python2.7/site-packages (from jsonschema)
```

I think that the issue with jsonschema in the clean environment was a red herring. For clarity I've reduced the issue to the main problem.

**Comment by mwaskom** [comment]
I just tried the following

```
[mlw-mbair ~]$ conda create -n ipython_test ipython-notebook=3.2
[mlw-mbair ~]$ . activate ipython_test
(ipython_test)[mlw-mbair ~]$ pip install -U jsonschema
(ipython_test)[mlw-mbair ~]$ pip install jupyter
```

After doing this, I was able to start the notebook with no problems. So I don't think it is quite so simple as a problem caused by pip installing jupyter over ipython that was installed by anaconda.

**Comment by minrk** [comment]
It might be an issue with the conda packages, though when I launch with a fresh conda env it appears to be working fine. What happens if you try:

    python -m ipykernel

Does it die with the same Abort trap?

Similarly, does starting with `IPYTHONDIR=/tmp/ipython jupyter notebook` work or fail in the same way?

Do you have any IPython startup or config files?

**Comment by mwaskom** [comment]
> Does it die with the same Abort trap?

Yep, looks like it does:

```
[mlw-mbair ~]$ python -m ipykernel
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-26924.json
Abort trap: 6
```

> Similarly, does starting with IPYTHONDIR=/tmp/ipython jupyter notebook work or fail in the same way?

Yep:

```
[mlw-mbair ~]$ export IPYTHONDIR=/tmp/ipython jupyter notebook
[mlw-mbair ~]$ python -m ipykernel
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-26950.json
Abort trap: 6
[mlw-mbair ~]$ jupyter notebook
[I 21:10:29.959 NotebookApp] Serving notebooks from local directory: /Users/mwaskom
[I 21:10:29.959 NotebookApp] 0 active kernels
[I 21:10:29.959 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 21:10:29.959 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 21:10:34.759 NotebookApp] Creating new notebook in
[I 21:10:36.094 NotebookApp] Kernel started: 338dc59c-934f-42da-b7d4-bfd697776999
[I 21:10:39.085 NotebookApp] KernelRestarter: restarting kernel (1/5)
[I 21:10:42.091 NotebookApp] KernelRestarter: restarting kernel (2/5)
[I 21:10:45.098 NotebookApp] KernelRestarter: restarting kernel (3/5)
[W 21:10:46.260 NotebookApp] Timeout waiting for kernel_info reply from 338dc59c-934f-42da-b7d4-bfd697776999
Abort trap: 6
```

**Comment by minrk** [comment]
Increasingly weird. What about `python -c 'import zmq; print(zmq.zmq_version(), zmq.__version__)'`?

**Comment by mwaskom** [comment]
```
[mlw-mbair ~]$ python -c 'import zmq; print(zmq.zmq_version(), zmq.__version__)'('4.1.2', '14.7.0')
```

**Comment by mwaskom** [comment]
In case it's useful, here are all the libraries in my default environment: http://pastebin.com/4jgLnic0

**Comment by minrk** [comment]
I think this has to be something to do with one of the compiled dependencies or libraries loaded at runtime. Do you have any `DYLD_LIBRARY_PATH` or related environment variables set? When you run terminal IPython, do matplotlib, pandas, etc. all work properly?

**Comment by minrk** [comment]
Also, do you see anything informative in the tail of `python -v -m ipykernel` before it dies?

**Comment by mwaskom** [comment]
> I think this has to be something to do with one of the compiled dependencies or libraries loaded at runtime. Do you have any DYLD_LIBRARY_PATH or related environment variables set?

Nope, that variable isn't set.

> When you run terminal IPython in the same env, do matplotlib, pandas, etc. all work properly?

Yes, I'm able to import numpy, matplotlib, pandas, and make basic plots from the ipython terminal.

> Also, do you see anything informative in the tail of python -v -m ipykernel before it dies?

Here's everything that gets printed to the terminal before the Abort Trap: http://pastebin.com/vmnXLrPR

**Comment by minrk** [comment]
Aha, now we are on to something. Conda's libzmq is 4.0.5, but your pyzmq is picking up 4.1.2, perhaps from homebrew (in /usr/local/lib). Try this:

    conda remove pyzmq
    pip install pyzmq

**Comment by mwaskom** [comment]
Success! pip installing didn't link to the right libzmq, but uninstalling that and then reinstalling with conda did, and now things are working. Thanks!

**Comment by kpmaynard** [comment]
Thank you very much. 
*conda remove pyzmq* and 
*conda install pyzmq*  
did it for me; jupyter notebook now runs!!!

**Comment by eric-czech** [comment]
Worked for me as well.  I saw the same initial error and ultimately fixed it with:

conda remove pyzmq
conda install pyzmq

Thanks!

**Comment by endrebak** [comment]
I on the other hand, had to reinstall conda for `2.7`. Nothing here helped, unfortunately (reinstalling did take very little time though).

**Comment by djchou** [comment]
This no longer works.  I downgraded to pyzmq=14.6.0 and it looks like the downgraded version works though.

**Comment by TitaniumDioxide** [comment]
yeah, downgrade pyzmq to version 14.6.0 works.


conda remove pyzmq
conda install pyzmq=14.6.0

**Comment by datamath28** [comment]
Thanks!  This fixed a similar issue I was having too.  It didn't even try to start after 
$ conda remove pyzmq
$ pip install pyzmq
$ ipython notebook
...
ImportError: No module named zmq.eventloop

but then I tried
$ conda install pyzmq 

and it started working again.

**Comment by philippberens** [comment]
I think I have the same problem with python 3.5 and an anaconda install updated to the latest versions. after starting a notebook, the notebook can't connect to a kernel (button on top right oscillating between green and orange). downgrading pyzmq is not possible for python 3.5. any ideas?

**Comment by willingc** [comment]
@philippberens What happens if you:
```
conda remove pyzmq
conda install pyzmq
```

**Comment by philippberens** [comment]
The Notebook still doesn't get a connection to the kernel, after a while of trying it gives up (broken chain).

**Comment by philippberens** [comment]
Is there any info that would be good to provide?

**Comment by minrk** [comment]
@philippberens do you see any info in the terminal where the notebook started?

**Comment by philippberens** [comment]
yes, it says "zmq message arrived on close channel"

**Comment by philippberens** [comment]
ok, thanks for the help, it seemed to be Kaspersky firewall blocking the port.

**Comment by willingc** [comment]
@philippberens Glad you got it resolved.

**Comment by jnvickery** [comment]
@philippberens Did you just need to unblock port 8888 from Kaspersky? I also have Kaspersky and am having the same issue with Jupyter so I'd be curious to hear any more details.

**Comment by paajake** [comment]
I am using anaconda3 and Cant seem to get jupyter notebook to run any code anymore, I get this error  when I start jupyter:
 " Timeout waiting for kernel_info reply from fd21f12c-7427-4a40-a686-918dcd8bb5dc "

I have tried uninstalling pyzmq and reinstalling it but it still wont work.... any other solutions?

**Comment by vmuriart** [comment]
This one solved it for me `pip install -U jsonschema` on two of my machines.

**Comment by bpben** [comment]
I'm having this same problem.  None of the solutions above will work.  I'm working with python 2.7.11 and Anaconda 4.  I start a notebook and it hangs on "Kernel Starting, please wait".  Any help here would be appreciated!

**Comment by takluyver** [comment]
Several people just reported a similar issue with a recent update to uBlock on Chrome. If you have that combination, try disabling it. Apparently uBlock 1.7.2 will fix it.

**Comment by bpben** [comment]
Thanks for the quick reply.  I have uBlock, but disabling didn't seem to fix it.  Any other suggestions?

**Comment by EtienneCmb** [comment]
I just got the problem with uBlock. You have to disable it from the extensions menu of chrome, and it should work again.

**Comment by drorhilman** [comment]
I have the same issue, but don't have uBlock - any other suggestions?

**Comment by takluyver** [comment]
@drorhilman I think this thread has been used to describe several similar but distinct issues - can you describe exactly what symptoms you're seeing?

The general advice falls into two categories:
- Uninstall and reinstall pieces that might be relevant.
- Check for internet security software; we've had several problems with various kinds of security software blocking websocket connections.

**Comment by skycreeper2000** [comment]
'pip uninstall pyzmq' and '
'pip install pyzmq' worked for me too on Windows 7. Thanks a lot folks!!
