### ISSUE TITLE
forgotten Jupyter notebook password

### ISSUE THREAD

**Issue by mycarta** [jupyter/notebook#2971]
Hello there,

This is a bit embarrassing. I set up a Jupyter notebook password several weeks ago when prompted the first time. If I recall, I just copied the token from the shell and pasted it at the prompt and then "followed the instructions", to be honest I do not recall. I assumed it was a one time thing; today I discovered it was not, and I do not remember the password. Is there any way to reset it? 
Thank you for your help.

**Comment by takluyver** [comment]
Run `jupyter notebook password` in the shell again and set a new password. Or find and edit the notebook config files (`jupyter_notebook_config.py` and/or `.json`).

**Comment by gnestor** [comment]
@mycarta Please close this issue if @takluyver's suggestion resolves your issue 👍

**Comment by mycarta** [comment]
It worked, thank you!

**Comment by AJohal1** [comment]
@gnestor  i can't type in anything in the prompt window ?

**Comment by bhaviksoni93** [comment]
not working

**Comment by iamgr007** [comment]
worked perfectly for me on my windows device! thanks @takluyver !

**Comment by NIC183** [comment]
i had the same problem, worked just fine. thanks @takluyver

**Comment by InajaraLopes** [comment]
Obrigado!
Funcionou comigo também.
