### ISSUE TITLE
"Programmatic" copy to clipboard don't work in Jupyter 5

### ISSUE THREAD

**Issue by Madhu94** [jupyter/notebook#2975]
Because of #1286, any extension that relies on ``document.execCommand('copy')`` for copying to clipboard don't work, as the notebook captures _all_ copy events triggered. 

For instance, if a notebook extension used clipboard.js - an invisible textarea is created whose value is set to whatever is supposed to go on the clipboard.  In that case [window.getSelection().isCollapsed](https://github.com/jdfreder/notebook/blob/72eeb99ad6f234467d561e2ebfc79343c35aa2b2/notebook/static/notebook/js/clipboard.js#L38) is set to True and the contents of the cell (not the value of the invisible textarea) is stored in the system clipboard.  

In this case, ``Ctrl+C`` would never be pressed and it is surprising for the extension users to click a button on the toolbar or access a menu-item and find that the current cell's contents are copied over.

A workaround might be to disable ``Jupyter.keyboard_manager`` and re-enable it once the extension's work is done.

Do you think the notebook can somehow try to detect explicit requests to copy (when the user hits ``Ctrl+C``) as opposed to capturing all copy events that are fired ?  

Thanks!

**Comment by Madhu94** [comment]
A solution (that I haven't really thought through) is to re-implement a little of what clipboard.js does, something like - 

1. Detect keypress of ``Ctrl+C`` or ``Cmd+C``
2. Create a temporary, invisible text area and set its value to the contents of the cells.
3. Run ``document.execCommand`` to get access to the system clipboard. 

( There is also the question of handling the plain text + json + html, also how it could affect #1321, etc)

**Comment by takluyver** [comment]
My understanding is that we can only interact with the clipboard by capturing clipboard events, so capturing keyboard shortcuts like Ctrl+C won't work.

The MDN docs for [document.execCommand](https://developer.mozilla.org/en-US/docs/Web/API/document/execCommand) say that it's only available in 'design mode', which I know ~nothing about.

**Comment by Madhu94** [comment]
@takluyver I'll try to make a WIP PR so we can talk over the code ?

**Comment by takluyver** [comment]
OK

**Comment by Madhu94** [comment]
> My understanding is that we can only interact with the clipboard by capturing clipboard events, so capturing keyboard shortcuts like Ctrl+C won't work.  

It is possible to fire off a copy event by creating a temporary invisible textarea, set its value to what  you want to copy and focussing it. Then, when the user hits ``Ctrl+C``, what is in the invisible, focussed textarea will be copied to the clipboard. This is what libraries like ``clipboard.js`` do. Look [here](https://github.com/zenorocha/clipboard.js/blob/master/src/clipboard-action.js#L56).

Another instance of this issue popped up recently - https://github.com/twosigma/beakerx/issues/6227
You can see that they worked around it the way I had suggested in the first update - by disabling and enabling the keyboard manager.

Do you think we can have an "escape hatch" for the notebook's copy feature ? Similar to how MathJax provides a ``tex2jax_ignore`` class. Notebook widgets/extensions/js libraries sometimes do need a  copy to clipboard feature.  Maybe a ``notebook-ignore-copy`` class like [this](https://github.com/Madhu94/notebook/commit/083f2c8b66d0a893642aa04b67a9e0aa05809169).

**Comment by Madhu94** [comment]
@takluyver @gnestor Please let me know what you think of the last part of my previous comment -

> 
> Another instance of this issue popped up recently - twosigma/beakerx#6227
> You can see that they worked around it the way I had suggested in the first update - by disabling and enabling the keyboard manager.
> 
> Do you think we can have an "escape hatch" for the notebook's copy (It is a really good feature btw) feature? Similar to how MathJax provides a tex2jax_ignore class. Notebook widgets/extensions/js libraries som etimes do need a copy to clipboard feature. Maybe a notebook-ignore-copy class like this.

**Comment by takluyver** [comment]
If you can see how to implement it, PRs are welcome! I'm a bit hazy on what we can do with the clipboard - I thought we could only respond to clipboard events generated by the browser, but it sounds like `document.execCommand` can get around that.

**Comment by blink1073** [comment]
We have a function for this in [@jupyterlab/apputils](https://github.com/jupyterlab/jupyterlab/blob/a270e407a78386ead8b347ca82077ca672fa3624/packages/apputils/src/clipboard.ts#L37).

**Comment by Madhu94** [comment]
@takluyver Thanks, I'll give it a shot. But do you see any issue with adding a workaround - something like https://github.com/Madhu94/notebook/commit/083f2c8b66d0a893642aa04b67a9e0aa05809169 ?

**Comment by takluyver** [comment]
If that works, it looks fine. I don't know how `event.target` works. Have you tried it on a few different browsers?
