### ISSUE TITLE
CSS question - How to remove menu links?

### ISSUE THREAD

**Issue by rwmajor2** [jupyter/notebook#2976]
Can someone quickly point me to where I would remove the following links?  I am not a CSS wizard so looking for a starting point.

![image](https://user-images.githubusercontent.com/3799165/32003258-8734e5b8-b96c-11e7-9d8a-94d4f00f65a7.png)

**Comment by HimanshuAwasthi95** [comment]
You want to remove links which you highlighted

**Comment by rwmajor2** [comment]
Appears edits to the following file accomplishes this:

https://github.com/jupyter/notebook/blob/f81fb46ff68323f9652d638a325e9ccc46f62e83/notebook/templates/tree.html#L65-L77
