### ISSUE TITLE
'notebook' in heading renders differently

### ISSUE THREAD

**Issue by juhasch** [jupyter/notebook#298]
Not sure what to make of this. A heading with the word 'notebook` renders differently in the notebook.
Unrendered:
<img src = "https://cloud.githubusercontent.com/assets/2445216/9292293/115a9818-43f0-11e5-8eb5-791e2123c4b6.png" width="30%" />
Rendered:
<img src = "https://cloud.githubusercontent.com/assets/2445216/9292294/14b81dc8-43f0-11e5-8c9b-a8f526c86f7a.png" width="30%" />

This is with the Jupyter/IPyton4 conda package and only happens exactly for `notebook`.

**Comment by minrk** [comment]
That's crazy. Maybe it has to do with an id collision, since there is already a div with id=notebook on the page?

**Comment by juhasch** [comment]
That was fast. Thanks :+1:
