### ISSUE TITLE
Autocomplete doesn't work when splitting Python function calls into several lines

### ISSUE THREAD

**Issue by xoelop** [jupyter/notebook#2996]
Apparently I can't get autotomplete in Jupyter Notebooks when I split a function call into several lines. For example, if I type 'head' and press TAB, Jupyter autocompletes it to header= in this first example
![image](https://user-images.githubusercontent.com/8508402/32191519-ad4d3734-bdb1-11e7-9dd8-c64f903881fe.png)

But if I had inserted a new line, as in the next pic, autocomplete doesn't work and the word 'head' never become 'header=' after pressing TAB.
![image](https://user-images.githubusercontent.com/8508402/32191608-fad937be-bdb1-11e7-853a-5764a399ed72.png)

Is there any parameter that I don't have well set up or is there an error?

Thanks for your help!
Xoel

**Comment by xoelop** [comment]
In the case it helps,
 
`import IPython`
`print(IPython.sys_info())`

returns

> {'commit_hash': 'd86648c5d',
 'commit_source': 'installation',
 'default_encoding': 'cp1252',
 'ipython_path': 'C:\\Anaconda3\\lib\\site-packages\\IPython',
 'ipython_version': '6.1.0',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.15063-SP0',
 'sys_executable': 'C:\\Anaconda3\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.6.3 |Anaconda custom (64-bit)| (default, Oct 27 2017, '
                '12:22:41) [MSC v.1900 64 bit (AMD64)]'}

**Comment by takluyver** [comment]
I think IPython tab completion may not be smart enough to look across multiple lines. Hopefully @Carreau's work to integrate jedi for completions will improve this.

**Comment by Carreau** [comment]
Hum. Yeah, we don't do anything specific in this case. I'll have to find time to dive into more recent Jedi stuff.

**Comment by jtpio** [comment]
Closing as this seems to be working in Notebook 7.1 and JupyterLab 4.1:

![image](https://github.com/jupyter/notebook/assets/591645/45b31ffa-3764-4812-92e5-209420b37c27)

Thank all!
