### ISSUE TITLE
Error configuring ipyparallel for Clusters tab on Windows

### ISSUE THREAD

**Issue by therriault** [jupyter/notebook#302]
Upgrading to 4.0 today on my Windows 8 machine (coincided with a fresh install of the latest version of Anaconda), and saw that the Clusters tab of the notebook said to follow the ipyparallel instructions for enabling clusters. I installed ipyparallel and used the `c.NotebookApp.server_extensions.append('ipyparallel.nbextension')` setting in the config file as instructed, but it doesn't seem to be working. The Clusters tab hasn't changed, and the following errors arise when starting the notebook:

```
c:\Anaconda>jupyter notebook

c:\Anaconda>symlink C:\Users\TherriaultA\AppData\Roaming\jupyter\nbextensions\ipyparallel -> c:\Anaconda\lib\site-packages\ipyparall
el\nbextension\static
[W 14:32:13.122 NotebookApp] Error loading server extension ipyparallel.nbextension
    Traceback (most recent call last):
      File "c:\Anaconda\lib\site-packages\notebook\notebookapp.py", line 992, in init_server_extensions
        func(self)
      File "c:\Anaconda\lib\site-packages\ipyparallel\nbextension\handlers.py", line 72, in load_jupyter_server_extension
        install_nbextension(static, destination='ipyparallel', symlink=True, user=True)
      File "c:\Anaconda\lib\site-packages\notebook\nbextensions.py", line 200, in install_nbextension
        os.symlink(path, full_dest)
    AttributeError: 'module' object has no attribute 'symlink'
symlink C:\Users\TherriaultA\AppData\Roaming\jupyter\nbextensions\ipyparallel -> c:\Anaconda\lib\site-packages\ipyparallel\nbextensi
on\static
[W 14:32:13.122 NotebookApp] Error loading server extension ipyparallel.nbextension
    Traceback (most recent call last):
      File "c:\Anaconda\lib\site-packages\notebook\notebookapp.py", line 992, in init_server_extensions
        func(self)
      File "c:\Anaconda\lib\site-packages\ipyparallel\nbextension\handlers.py", line 72, in load_jupyter_server_extension
        install_nbextension(static, destination='ipyparallel', symlink=True, user=True)
      File "c:\Anaconda\lib\site-packages\notebook\nbextensions.py", line 200, in install_nbextension
        os.symlink(path, full_dest)
    AttributeError: 'module' object has no attribute 'symlink'
symlink C:\Users\TherriaultA\AppData\Roaming\jupyter\nbextensions\ipyparallel -> c:\Anaconda\lib\site-packages\ipyparallel\nbextensi
on\static
[W 14:32:13.138 NotebookApp] Error loading server extension ipyparallel.nbextension
    Traceback (most recent call last):
      File "c:\Anaconda\lib\site-packages\notebook\notebookapp.py", line 992, in init_server_extensions
        func(self)
      File "c:\Anaconda\lib\site-packages\ipyparallel\nbextension\handlers.py", line 72, in load_jupyter_server_extension
        install_nbextension(static, destination='ipyparallel', symlink=True, user=True)
      File "c:\Anaconda\lib\site-packages\notebook\nbextensions.py", line 200, in install_nbextension
        os.symlink(path, full_dest)
    AttributeError: 'module' object has no attribute 'symlink'
[I 14:32:13.138 NotebookApp] Serving notebooks from local directory: C:/ATworking/GitHub/DataSci/notebooks_at_local
[I 14:32:13.138 NotebookApp] 0 active kernels
[I 14:32:13.138 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 14:32:13.138 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

Any idea what's going on here? I followed the instructions to the letter, so either there's a configuration bug or the instructions are missing something. Thanks.

**Comment by Carreau** [comment]
o_O

can you do  in python:

```
import os
os.symlink
os.__file__
```

Here is what I get for example.

```
$ python
Python 3.4.3 |Anaconda 2.3.0 (x86_64)| (default, Mar  6 2015, 12:07:41)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.symlink
<built-in function symlink>
>>> os.__file__
'/Users/bussonniermatthias/anaconda3/lib/python3.4/os.py'
>>>

```

**Comment by therriault** [comment]
Here's what it gives me (note windows + python 2.7, if it matters):

'''
c:\Anaconda>python
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import os
>>> os.symlink
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'symlink'
>>> os.__file__
'c:\\Anaconda\\lib\\os.pyc'
>>>
'''

**Comment by Carreau** [comment]
Grahhhhh `os.symlink` does not exist on 2.7 and windows.... :rage:.

**Comment by therriault** [comment]
Well there's your problem...

**Comment by Carreau** [comment]
Ping @minrk if he does not do it I'll fix that tomorrow. I'm jumping in a plane right now. 

You can also try to  send a PR that replace `os.symlink` on the above line to `shutils.copytree`  if `os.symlink` does not exist.

**Comment by therriault** [comment]
Thanks! Will see what I can do, though the usual "better user than developer" caveats apply. But that sounds like a simple fix.

**Comment by Carreau** [comment]
Good thing to do for a first fix ! Looking forward to your PR !

**Comment by therriault** [comment]
Think I got it figured out---does that look like a reasonable solution?

**Comment by minrk** [comment]
And I also noticed this a bit ago, and set symlink to False on Windows in ipython/ipyparallel#24.

**Comment by therriault** [comment]
So I guess we just fixed the same problem two different ways simultaneously?

**Comment by minrk** [comment]
Yup! I shouldn't have been trying to use symlinks unconditionally in ipyparallel, and since it's very common for symlinks to be unavailable (Windows py2) or *probably* unavailable (Windows py3), it makes sense to the install command to ignore the request for symlinks if it won't work.

**Comment by therriault** [comment]
Whatever works (though I have a purely sentimental attachment to my fix, just because it's my first Jupyter PR!).

**Comment by minrk** [comment]
Both fixes are the right thing to do, even though only one is needed for this particular issue. Welcome to the project!

**Comment by Carreau** [comment]
Can we close this one ?
