### ISSUE TITLE
Securing Jupyter password info is not helping/

### ISSUE THREAD

**Issue by Flybynite** [jupyter/notebook#3027]
Sorry I'm pretty new to all of this. But the info below that is on the website is not helping.
 
"Securing a notebook server
You can protect your notebook server with a simple single password by configuring the NotebookApp.password setting in jupyter_notebook_config.py."

^ I want to set a pw.And this looks like great info but what if you are really new and don't know where to begin to look for the "jupyter_notebook_config.py."  Is it somewhere on the localhost/8888 site or in the command prompt or in the anaconda command prompt and what do I enter to find it? 

It would greatly help if the info above was presented in a "step by step" manner for completely new students..

**Comment by jcb91** [comment]
Although more documentation would still be a good idea, for notebook 5.0 and newer, you can use the command

    jupyter notebook password

To do this much more conveniently. You can get more information with the command's help flag too:

    jupyter notebook password --help

**Comment by akshaysuresh4793** [comment]
I am new to Open Source. I would like to take on this issue. What are the steps to be followed?

**Comment by takluyver** [comment]
Looking at http://jupyter-notebook.readthedocs.io/en/stable/security.html#alternatives-to-token-authentication , I think this has already been improved, so I'm closing the issue. Thanks @akshaysuresh4793
