### ISSUE TITLE
SVG output not included in notebook

### ISSUE THREAD

**Issue by gkvoelkl** [jupyter/notebook#3038]
I create SVG output in a cell. It works correctly.
If I reopen the notebook on another day, there is only the text

> <IPython.core.display.SVG object> 

After evaluating the cell again, I can see the SVG graphic.

Is it a bug or did I something wrong?

Best regards

Gerhard

**Comment by takluyver** [comment]
It sounds like your notebook is not trusted for some reason. Untrusted notebooks can't display output like SVG or HTML which may be able to run Javascript code.

There's more detail here:
http://jupyter-notebook.readthedocs.io/en/latest/security.html#Security-in-notebook-documents

**Comment by gkvoelkl** [comment]
That works. 👍

**Comment by callegar** [comment]
The security.html document does not actually mention svg. To the best of my understanding, browsers should anyway protect themselves from code that could be embeded in svg images: SVG documents added to the page as images will have their JavaScript ignored. Not having a good vector-image format enabled is actually a big loss. Unless I am missing something, could this be reconsidered? and if I am missing something, may I suggest that reasons for excluding SVG are explicitly mentioned in the security.html document?
