### ISSUE TITLE
Why the title tag '#' need a blank before the title on Notebook?

### ISSUE THREAD

**Issue by muxuezi** [jupyter/notebook#304]
When I use IPython 3.2.1 Notebook, following `h2` title tag is ok:

```markdown
##Starting to Crawl
```
However, it's a mistake at IPython 4.0.0 Notebook, I had to add a blank to separate the `##` tag and text.
```markdown
## Starting to Crawl
```

Please excuse my ignorance. Is this necessary for any reason?
New version nbconvert was also failed when I build ipynb with [Nikola blog generator](https://github.com/getnikola/nikola)

**Comment by minrk** [comment]
I believe this was a deliberate change in the [marked](https://github.com/chjj/marked) javascript markdown implementation that we use.

**Comment by costerwi** [comment]
Surprised me too.  Discussion here: https://github.com/chjj/marked/issues/201

**Comment by costerwi** [comment]
#276

**Comment by minrk** [comment]
@costerwi thanks, closing as duplicate.
