### ISSUE TITLE
matplotlib figures scale weirdly / can't get a nice small figure

### ISSUE THREAD

**Issue by cod3licious** [jupyter/notebook#3041]
I'm using Jupyter notebook with anaconda and yesterday updated the iPython kernel.
Before, when I plotted something by default I got a fairly small figure like below:
<img width="1147" alt="fig_before" src="https://user-images.githubusercontent.com/1093567/32691703-ff70babe-c70b-11e7-86b6-1be9830aa0a5.png">
Suddenly, the figures now are really big (by default take up the whole width of the browser) and I can't really scale them down, at least not in a pretty way. I'm using `%matplotlib inline` and for example when I specify `plt.rcParams['figure.figsize'] = (10,6)` I get a nice large figure as below:
<img width="1131" alt="fig_10_6" src="https://user-images.githubusercontent.com/1093567/32691721-3bf8fcbc-c70c-11e7-90da-a316b274126c.png">
However, if I'm trying to make the figure smaller, e.g. with `plt.rcParams['figure.figsize'] = (2,1.2)`, while I do get a smaller figure, it looks awful as it doesn't scale accordingly:
<img width="1135" alt="fig_2_12" src="https://user-images.githubusercontent.com/1093567/32691727-5e763750-c70c-11e7-9b6b-ba0aa11a7eb4.png">

the code that's used to generate the figures is the following:
```
def plot_mnist(X, y, X_test=None, y_test=None, title=None):
    plt.figure()
    colorlist = get_colors(10)
    # Scale and visualize the embedding vectors
    x_min, x_max = np.min(X, 0), np.max(X, 0)
    if (X_test is not None) and (y_test is not None):
        x_min, x_max = np.min(np.array([x_min, np.min(X_test, 0)]), 0), np.max(np.array([x_max, np.max(X_test, 0)]), 0)
        X_test = (X_test - x_min) / (x_max - x_min)
    X = (X - x_min) / (x_max - x_min)
    if (X_test is not None) and (y_test is not None):
        for i in range(X_test.shape[0]):
            plt.text(X_test[i, 0], X_test[i, 1], str(y_test[i]),
                     color=colorlist[y_test[i]],
                     fontdict={'weight': 'medium', 'size': 'smaller'},
                     alpha=0.4)
    for i in range(X.shape[0]):
        plt.text(X[i, 0], X[i, 1], str(y[i]),
                 color=colorlist[y[i]],
                 fontdict={'weight': 'medium', 'size': 'smaller'},
                 alpha=1.)
    plt.xticks([]), plt.yticks([])
    plt.xlim(-0.05, 1.05)
    plt.ylim(-0.05, 1.05)
    if title is not None:
        plt.title(title)
```
and since there are no absolute specifications for font size etc I would expect it to scale down accordingly.... Am I doing something wrong here or is there a bug somewhere?
Since the figures scale nicely when I decrease the width of the browser window, I'm assuming the nice way to specify the size of the figures would be to tell the notebook how much of the default width of the browser window it should use for the figure but I'm not sure if or where I could find such a setting?

**Comment by takluyver** [comment]
Are you using a `%matplotlib` magic command to set the backend?

cc @tacaswell

**Comment by cod3licious** [comment]
@takluyver no, I'm only using `%matplotlib inline` and my default matplotlib backend on mac os x is qt4agg.

**Comment by tacaswell** [comment]
I am not sure what is going on with the initial size change.  Did you change from a normal to 'hi-dpi' display?  All of the layers try to helpfully do the re-scaling and can step on each other's toes.

The second behavior is the correct and expected behavior.  The font size is always specified in absolute points (1/72 in).   Setting it to 'smaller' is just a scaling factor relative to the default font size.   If you count the size in pixels of the text in the underlying png the text should be the same size (assuming the same dpi).

I think in the 'big' case Jupyter is scaling the png down (as it is not 5 times wider in your screen shots than the 'small' one) by telling the browser to make it smaller in pixels than it really is.  This is also what gives you the apparent scaling when you narrow the width of the browser.

**Comment by cod3licious** [comment]
@tacaswell I had a hi-dpi display (retina macbook as well as UHD external display) all along, but never specified that anywhere in the config files or anything... as I said, I started seeing this when I upgraded my ipykernel (from I think 4.3.x to 4.6.1), but I'm a bit surprised that this has such an effect on the notebook graphics. I really do like the scaling down effect when making the browser window narrower, but it would be really great, if you could set an initial width and/or height for the figures displayed in the notebook, i.e. of the div or whatever that contains the final drawn figure. maybe even independent of the matplotlib figure sizes, which someone might want to set differently for saving the figures.

**Comment by tacaswell** [comment]
Those request I think would be best handled by the jupyter/IPyhton teams as the 'inline' backend lives in the IPython source tree and matplotlib know nothing about the divs in the browser.

**Comment by cod3licious** [comment]
ok, thanks, I [reposted the issue in ipykernel](https://github.com/ipython/ipykernel/issues/279), so I guess this one can be closed then.
thank you!

**Comment by dsblank** [comment]
That appears to be the same issue reported here: https://github.com/matplotlib/matplotlib/issues/9606
