### ISSUE TITLE
Wrong size for some interface buttons in the tree view with Firefox

### ISSUE THREAD

**Issue by ferdas** [jupyter/notebook#3044]
![screen](https://user-images.githubusercontent.com/8852116/32812029-3abf8af2-c9a3-11e7-9c77-e5785d35f42f.png)

Using Firefox, there are a lot of small sizing problem across the whole UI.
The ones highlighted in the screenshot above are the among the most annoying since they appear often in the daily usage.

I'll send a pull request later on to fix them :)

**Comment by takluyver** [comment]
I also notice this, so I'm looking forward to your PR :-)

**Comment by ferdas** [comment]
I was busier than I expected but finally I made it :)

I hope give more contribution in the future!

Thank you

**Comment by ferdas** [comment]
Thanks :)
