### ISSUE TITLE
Tooltip icons not showing in Firefox 58

### ISSUE THREAD

**Issue by jagmoreira** [jupyter/notebook#3047]
Recently, the tooltip that you get from Shift+Tab stopped showing icons:

<img width="649" alt="tooltip" src="https://user-images.githubusercontent.com/13685125/32861772-65d0f780-ca1b-11e7-9129-a22ca195fc27.png">
<img width="1197" alt="pager_tooltip" src="https://user-images.githubusercontent.com/13685125/32861771-65b95788-ca1b-11e7-8049-cb6bd8feb0ef.png">

After updating jupyter to the latest version and trying a couple of browsers I realized that *this only happens in Firefox*.

**I'm running Firefox Developer Edition 58.0b1 on macOS 10.12.6**. The browser console shows this interesting warning:
<img width="1176" alt="console" src="https://user-images.githubusercontent.com/13685125/32861922-fbb74d6c-ca1b-11e7-84a8-73359843d4ef.png">

> accessing "actions" on the global IPython/Jupyter is not recommended. Pass it to your objects contructors at creation time

This is a warning that does not show up in the Chrome console btw.

**Comment by takluyver** [comment]
It's still working for me in Firefox 57. Do you have any extensions installed in Firefox?

**Comment by jagmoreira** [comment]
That's a good point!

So, turns out it was probably one of my extensions that was interfering with jupyter: [KeePassHttp-Connector](https://github.com/smorks/keepasshttp-connector) 😞 
After I disabled it, the icons returned!

The extension was actually updated a few days ago with a new version of [jquery](https://github.com/smorks/keepasshttp-connector/releases/tag/v1.0.5). Could that be it?

**Comment by takluyver** [comment]
I guess it's possible - I don't know much about how an extension like that interacts with the page. If it offers a way to blacklist domains, you might want to try blacklisting localhost.
