### ISSUE TITLE
jupyter-themes

### ISSUE THREAD

**Issue by dunovank** [jupyter/notebook#305]
I'm terribly sorry if this is the wrong forum for this. But I just thought I'd put these out in the world for anyone interested: https://github.com/dunovank/jupyter-themes 

Some different Jupyter NB themes (poorly crafted css on my part, not a web developer by any stretch). If there's a more appropriate place to post this or if it's not of interest, please let me know or feel free to promptly discard. 

Very best,
kd

**Comment by Carreau** [comment]
Hi, 

you can also post this on the jupyter-project google group. 

You can also find more theme here : https://github.com/nsonnad/base16-ipython-notebook and here: http://www.damian.oquanta.info/posts/48-themes-for-your-ipython-notebook.html

And look at previous discussions:
https://github.com/ipython/ipython/issues/7931

Thanks !

**Comment by dunovank** [comment]
Awesome, thanks!

**Comment by hainm** [comment]
@dunovank `oceans16` looks really nice in the notebook. thanks.

<img width="1114" alt="screen shot 2016-06-29 at 1 16 10 am" src="https://cloud.githubusercontent.com/assets/4451957/16441284/2070a2ec-3d97-11e6-935a-1371d77fc546.png">

**Comment by dunovank** [comment]
Thanks, glad you like it!

On Wednesday, June 29, 2016, Hai Nguyen <notifications@github.com> wrote:

> @dunovank <https://github.com/dunovank> oceans16 looks really nice in the
> notebook. thanks.
>
> [image: screen shot 2016-06-29 at 1 16 10 am]
> <https://cloud.githubusercontent.com/assets/4451957/16441284/2070a2ec-3d97-11e6-935a-1371d77fc546.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/notebook/issues/305#issuecomment-229262461>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADqqzqkaAE5WyWfKMvr-qhb1Q0mxmd1Zks5qQgbzgaJpZM4FsmgA>
> .
>


-- 
Sent from my iPhone

**Comment by JamiesHQ** [comment]
thanks @dunovank really nice work! I'm going to close this as an issue and have marked it as a reference for future queries. 

@minrk : you marked this as a wishlist item in Sept. 2015- please re-open if there are plans to add  this issue to the development roadmap. thanks!
