### ISSUE TITLE
Warning for too long `print()` command

### ISSUE THREAD

**Issue by balzer82** [jupyter/notebook#306]
Sometimes, I just `print` out something, which is so much, that I have to restart the kernel, because it will _never_ finish. Would be nice, if the notebook could tell me something like:

`Hey, you are tryin' to print out 10million lines in this cell, which could take some time. Sure?`

**Comment by minrk** [comment]
This is an issue some people do encounter, and there are two levels to it:

1. the cost of sending the text to the browser
2. the cost of putting the text on the page and adding it to the document

(1) can be prevented only by adding a prompt at a low level in the kernel (in sys.stdout.write or flush), whereas (2) can be done in js on the client-side. It won't protect the most egregious cases, but it is often the javascript that's the biggest problem, and not the network traffic.

**Comment by damianavila** [comment]
>(2) can be done in js on the client-side. It won't protect the most egregious cases, but it is often the javascript that's the biggest problem, and not the network traffic.

Probably useful for you: https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/limit_output

**Comment by jasongrout** [comment]
@williamstein pointed out how he does limitations with SageMathCloud on the server side:  https://github.com/sagemathinc/smc/blob/master/salvus/sage_server.py#L454

**Comment by JamiesHQ** [comment]
@balzer82 : We're doing a little housekeeping on our issue log and I noticed this thread from 2015. Has this issue been resolved to your satisfaction and can it be closed? I plan to mark it as a reference issue since there are some useful links provided. Let us know if there's anything else you need. thanks!

**Comment by takluyver** [comment]
We do now have rate limiting for printed output, so I think this can be closed.
