### ISSUE TITLE
symbol on top of other symbol (hat, tilde, vec) puts it in superscript position

### ISSUE THREAD

**Issue by mbakker7** [jupyter/notebook#3062]
The functions `$\hat{x}$`, `$\tilde{x}$`, `$\vec{x}$` put the hat, tilde and vector in the superscript position rather than on top in a markdown cell. I also noticed this behavior on, for example, http://data-blog.udacity.com/posts/2016/10/latex-primer/

Strangely enough `$\widehat{h}$` does work and puts a (wide) hat on top of x. So why doesn't `$\hat{x}$` do that?

Is this a mathjax limitation (which would be odd), bug (I think so), something that can be easily fixed (I hope so). 

Jupyter 5.0.0, Python 3.6, Safari 11.0.1

Thanks, Mark

**Comment by biaojiang** [comment]
I met this problem as well when rendering equations using Sphinx. However, only the web file has this problem, after having compiled it to .pdf file, it is OK.

So, I think it is the Mathjax bug, you can report it to Mathjax.

**Comment by mbakker7** [comment]
Are you using Safari? A colleague couldn't duplicate it on a PC (Chrome I
think, but not sure).

**Comment by biaojiang** [comment]
Yes, I use Safari. I just tested it on PC that IE and Chrome don't have this problem.

**Comment by mbakker7** [comment]
Seems to be a mathjax problem on Safari. Will report the bug to mathjax.

**Comment by JesseBausell** [comment]
You can try '$\~{x}$' and '$\^{x}$' for tilde and hat....

**Comment by JesseBausell** [comment]
You can try '$\~{x}$' and '$\^{x}$' for tilde and hat....
