### ISSUE TITLE
How to hide the notebook app interface before it appears?

### ISSUE THREAD

**Issue by ghazpar** [jupyter/notebook#3068]
Hi,

Just upgraded from 4.4.1 to 5.2.1. 

In 4.4.1, using custom.js, I used to be able to get some custom.js code running in between `app_initialized.NotebookApp` and `notebook_loaded.Notebook` events. In 5.2.1, using promises, my custom.js code always runs much later, after the notebook interface has been displayed by the browser.

I would like to hide the `header-container`, `menubar`, and `maintoolbar-container` divs before anything is displayed (currently the divs briefly appear before my custom.js is able to hide them). **Is there a mechanism that I can use to hide these divs before they are shown**?

I also tried to make a notebook extension, but in the test that I made, the extension got called even later than the custom.js. So what are my options?

Many thanks in advance for any advise.

**Comment by takluyver** [comment]
Maybe it's possible to use custom css, rather than javascript, if you always want them hidden?

**Comment by ghazpar** [comment]
Ok, did that and it worked. Thanks!
