### ISSUE TITLE
Use the History API

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/notebook#307]
At least for the dashboard/file system browser, it would be a much cleaner ("no flicker") experience if, when clicking through the file system on our dashboard, we used the [history API](http://diveintohtml5.info/history.html) and manipulated the DOM directly. We do use the contents API for the directory listing, so the dashboard is probably one of the easiest spots to use `history.pushState` and _only_ update the view of the current directory.

`history.pushState`, `history.popState`, and `history.replaceState` are [all well supported across browsers](http://caniuse.com/#search=pushstate) now a days (and have been for a while).

/cc @jdfreder

**Comment by rgbkrk** [comment]
As long as people are comfortable with this ideology, I'd like to see what tackling this would be like.

**Comment by minrk** [comment]
I think it's a good idea. I've wanted the dashboard refactor to happen before doing things like this, but since that's been on the horizon for at least two years now, I don't think it makes any sense to wait for it for anything anymore.

**Comment by ellisonbg** [comment]
I think this makes a lot of sense with our existing dashboard.

**Comment by JamiesHQ** [comment]
Hi there @rgbkrk - is this still an active request? Thanks!

**Comment by rgbkrk** [comment]
The way I'd implement has sure changed, now that I've worked with several "routers" :smile:. It's still worth doing as it helps users with slower connections especially. We already have the APIs in place. _Technically_ nteract has already done exactly this in commuter. It's intention was for public sharing rather than the notebook server though.

**Comment by gnestor** [comment]
I submitted a PR because this was a relatively easy thing to do... We'll see other think 👍
