### ISSUE TITLE
Command Palette won't open

### ISSUE THREAD

**Issue by Paul-Yuchao-Dong** [jupyter/notebook#3074]
I am working in with current version of Jupyter notebook. And I encountered a weird problem - the command palette won't open, even if I click on the icon just below the menu bar.

> Server Information:
> 
> You are using Jupyter notebook.
> 
> The version of the notebook server is: 5.2.1
> The server is running on this version of Python:
> Python 3.5.4 |Anaconda custom (64-bit)| (default, Oct 27 2017, 11:35:13) [MSC v.1900 64 bit (AMD64)]
> 
> Current Kernel Information:
> 
> Python 3.5.4 |Anaconda custom (64-bit)| (default, Oct 27 2017, 11:35:13) [MSC v.1900 64 bit (AMD64)]
> Type 'copyright', 'credits' or 'license' for more information
> IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

The chrome console gave below error message:
![capture](https://user-images.githubusercontent.com/7532271/33160744-c6027d1a-d059-11e7-9639-b8db5971cf58.JPG)

it seems `new commandpalette.CommandPalette(this)` called Jed.gettext which throw the error.

I've re-installed jupyter, but the problem persists. 

Appreciate any help!

**Comment by takluyver** [comment]
That sounds like the translation machinery throws an error if it can't find
a translation, rather than falling back to the English string, which is
what I'd assumed it would do. @JCEmmons any ideas?

In the meantime, a workaround might be to set english (`en`) as the first
language in your browser preferences. That's obviously not a solution, but
it might get it working until the real issue is worked out.

**Comment by Paul-Yuchao-Dong** [comment]
Many thanks for your time on this issue. For additional information, I am using Chrome Version 62.0.3202.94 (Official Build) (64-bit). 

I have set the language to English and restarted chrome as below, yet the prolem persists. 

![image](https://user-images.githubusercontent.com/7532271/33192077-cbe693c8-d0fa-11e7-9559-903602aaf07e.png)

**Comment by JCEmmons** [comment]
It should always fall back to the English if it can't find the 
translation.


Regards,

John C. Emmons
Globalization Architect & Unicode CLDR TC Vice Chairman
IBM Globalization Team
e-mail: emmo@us.ibm.com

**Comment by takluyver** [comment]
Any ideas why it might be failing? Or how to debug it? The error shown is definitely coming from Jed.

**Comment by uduse** [comment]
Having the same problem here, on both Chrome and Safari. I work remotely on a notebook that runs on a server. Most other keys are fine, but no matter what I try I can't get the command palette show up. Not even a sign.

I tried remapping `jupyter-notebook:show-command-palette` to another shortcut and the same problem persists. 

Any help will be appreciated.

**Comment by takluyver** [comment]
Do you see the same error in the Javascript console?

**Comment by uduse** [comment]
@takluyver yep, exact the same.

**Comment by takluyver** [comment]
@JCEmmons do you have time to investigate this further? It's definitely coming from the translation machinery, and you're most familiar with that.

**Comment by uduse** [comment]
Just to provide more information: my Jupyter runs on a Ubuntu server and I remotly access it on my mac. I am wondering if it is an operating system discrepancy problem.

**Comment by takluyver** [comment]
There may be some discrepancies in the UI: parts of the translations are loaded depending on the environment variables on the server, and parts depending on the language you set in the browser preferences. But they shouldn't cause an issue like this.

**Comment by JCEmmons** [comment]
Unfortunately I'm swamped with other work through the end of the year.


Regards,

John C. Emmons
Globalization Architect & Unicode CLDR TC Vice Chairman
IBM Globalization Team
e-mail: emmo@us.ibm.com

**Comment by takluyver** [comment]
I think I've worked it out - hopefully #3122 will fix it.
