### ISSUE TITLE
Katex for mathjax

### ISSUE THREAD

**Issue by amilapsn** [jupyter/notebook#3094]

**Comment by XavierOwen** [comment]
Thanks, jupyter notebook team.
And there has long been a problem that it takes *a lot of* time to render MathJax expression.
And I just get to know about this KaTeX.
And it is really fast, Lightning-fast.
And I believe that Jupyter would be better with KaTeX implemented.
So is it possible that in future release KaTeX would be available to use in Jupyter Notebook?
Or maybe works as an alternative to MathJax?
Thanks!

**Comment by ian-r-rose** [comment]
KaTeX rendering is available in JupyterLab by installing the labextension `@jupyterlab/katex-extension`, FYI.

**Comment by XavierOwen** [comment]
Err, way too hard to get many extensions go with the current version of jupyterLab...
Gotta rest for a while :joy: 
Cheers!

**Comment by jtpio** [comment]
> KaTeX rendering is available in JupyterLab by installing the labextension `@jupyterlab/katex-extension`, FYI.

Closing as this extension can also be used with Notebook 7 now.

Thanks!
