### ISSUE TITLE
Changing the notebook metadata won't mark the notebooks as changed

### ISSUE THREAD

**Issue by parmentelat** [jupyter/notebook#3095]
a very minor inconvenience, but after doing a change in the notebook metadata with *Edit -> Edit Notebook Metadata*, the notebook is not considered changed

that is, if you save the notebook (displays: `(autosaved)`), and edit metadata, it will still show `(autosaved)` and no warning will be issued if you reload the page (typically to see the effect of the change)

so if you forget to save you're losing the metadata change

**Comment by gnestor** [comment]
Good observation!

@minrk Is this intentional? There is a similar discussion at https://github.com/jupyter/notebook/issues/2123. However, when I edit the notebook's metadata (even if I replace the whole thing with `{}`), I don't see an unsaved changes notification.
