### ISSUE TITLE
How to disable notebook mobile version? I wanna use destop version only on my server.

### ISSUE THREAD

**Issue by 99040712** [jupyter/notebook#3099]
How to disable notebook mobile version? I want to use destop version only on my phone and pad.

**Comment by takluyver** [comment]
What mobile version?

**Comment by 99040712** [comment]
webpage mobile version.
I setup jupyter notebook on my server... and wanna force to use destop version.

**Comment by takluyver** [comment]
Sorry, I was being flippant. As far as I know, we don't have a mobile version. There is only one version, and it's mainly designed for use on desktops and laptops.

There are a few elements that change with screen size using CSS media queries, but not very many.

**Comment by 99040712** [comment]
thanks. solved.
