### ISSUE TITLE
Add a 'list' option to the nbextension subcommand

### ISSUE THREAD

**Issue by kain88-de** [jupyter/notebook#311]
This is a feature request.  It would be nice to have a `list` option for nbextension which prints a list of installed extensions to the terminal and shows which ones are enabled. A simple thing like this would be enough.

```
Active       Name
   x         codefolding
             macro-cell
   x         hide-input
   x         spell-check
```

This would make it easy to check if an extension was correctly installed and which ones are activated
and should show up in the browser.

**Comment by JamiesHQ** [comment]
@kain88-de : We're doing a little housekeeping on our issue log and noticed this thread from 2015. Have you seen a resolution to this issue since you posted it and do you still require this functionality? thanks!

**Comment by kain88-de** [comment]
[fixed](https://github.com/jupyter/notebook/blob/90d30d2963da61137121b4118ce2db5d5a829a15/notebook/nbextensions.py#L837)
