### ISSUE TITLE
'print' highlighting different in notebook vs editor

### ISSUE THREAD

**Issue by tylerlekang** [jupyter/notebook#3118]
Extremely small issue, but just noticed that in notebook if you type a print it gets bold highlighted (similar to: for, return, etc.) whereas in editor if you type a print it is unbold highlighted (similar to a python built-in function). Is there a reason it can't be the same on both? Or is it a setting I need to set.

**Comment by takluyver** [comment]
In the notebook, it *should* depend on whether you're using Python 3 or 2 to run the code - though I haven't checked recently if that works correctly. In Python 3, `print` is a function, whereas in Python 2 it's a keyword.

In the text editor, it's not connected to a kernel to run code, so I guess it uses the Python 3 highlighting for any Python code.

**Comment by tylerlekang** [comment]
That makes sense, then. Is there a way to switch to Python 2 highlighting in the text editor?

**Comment by takluyver** [comment]
Not really. It's probably doable in Javascript if you fiddle with `Jupyter.editor.set_codemirror_mode`, but I'm not sure what you'd have to pass it.

**Comment by tylerlekang** [comment]
Ok fair enough. Thanks for the replies
