### ISSUE TITLE
defunct c.NotebookApp.open_browser

### ISSUE THREAD

**Issue by flying-sheep** [jupyter/notebook#312]
In my `~/.jupyter/jupyter_notebook_config.py`, i have a line reading `c.NotebookApp.open_browser = False`, yet every time i execute `jupyter notebook some_notebook.ipynb`, it opens a browser

**Comment by Carreau** [comment]
I'm confused of what you expect it  to do. `jupyter notebook some_notebook.ipynb` is ment to open `some_notebook.ipynb` in a browser, it would strictly do nothing otherwise...

**Comment by flying-sheep** [comment]
apparently i’m the confused one. this makes sense of course!

**Comment by Carreau** [comment]
No problem. If it ever make sens again, feel free to reopen.
