### ISSUE TITLE
JS services test failure on Python 2.7

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#3127]
Tests on Python 2.7 on Travis are failing like this:

```
FAIL one kernel running
#    type: assertEquals
#    file: /home/travis/build/jupyter/notebook/notebook/tests/services/kernel.js
#    subject: 2
#    expected: 1
```

```
FAIL one session running
#    type: assertEquals
#    file: /home/travis/build/jupyter/notebook/notebook/tests/services/session.js
#    subject: 4
#    expected: 1
```

@blink1073 was starting to investigate on #3120, but we haven't worked it out yet.

**Comment by blink1073** [comment]
Is Python 2.7 dead yet?   Oh what a happy day that would be....

**Comment by takluyver** [comment]
I was thinking of aiming for notebook 6.0 and requiring Py 3 next year. But I think we'll need to figure this out one way or the other.

**Comment by blink1073** [comment]
Agreed on both

**Comment by takluyver** [comment]
It looks like for some reason it's starting a python3 kernel as well as the python2 one. :-/

**Comment by takluyver** [comment]
I think I know where it's coming from. Investigating using #3128.

**Comment by takluyver** [comment]
It wasn't where I was thinking - it turns out it was actually a problem with ipykernel: https://github.com/ipython/ipykernel/issues/288 . I've made a workaround in #3128.
