### ISSUE TITLE
socket_stream.cc(210)] Closing stream with result -100

### ISSUE THREAD

**Issue by Roychenlei** [jupyter/notebook#3134]
Seem there is a bug when trying to open jupyter.

**Comment by takluyver** [comment]
That sounds like a zeromq error. Does this prevent you from launching Jupyter, or does it show this and carry on?

**Comment by Roychenlei** [comment]
With this error, I can launch Jupiter. but I can't open that file.

**Comment by Roychenlei** [comment]
I think I just find out the reason. I look that file meta info, the input data is a kind of too big. the size is about 1MB. When I deleted that input data, everything is fine.
