### ISSUE TITLE
Whats is the best way to pass information from the method load_jupyter_server_extension to a Handler?

### ISSUE THREAD

**Issue by orobsonpires** [jupyter/notebook#3144]
Hey,

So, I've created my server extension,  and I would like to give some information from the method load_jupyter_server_extension to the Handler, following you can see my code:

```python
def load_jupyter_server_extension(nb_app):
    web_app = nb_app.web_app
    host_pattern = '.*$'
    # I want to give the value of nb_app.notebook_dir to HelloWorldHandler
    print("test" + nb_app.notebook_dir)
    route_pattern = url_path_join(web_app.settings['base_url'], '/hello')
    web_app.add_handlers(host_pattern, [(route_pattern, HelloWorldHandler)])`
```

Thanks in advance!

**Comment by takluyver** [comment]
You can add a third element in the `(route_pattern, HandlerClass)` tuple, which is a dictionary of keyword arguments to pass to an `initialize()` method on the handler class. Have a look at how I've used that in another extension:

https://github.com/takluyver/cite2c/blob/09e04ec8820a1f1aad9c4889cd8bc58edfbd54bc/cite2c/handlers.py#L17-L35

Tornado docs: http://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.initialize

**Comment by orobsonpires** [comment]
That worked perfect to me. Thanks a lot!
