### ISSUE TITLE
code completion showing each attribute twice

### ISSUE THREAD

**Issue by maajdl** [jupyter/notebook#3145]
Hello,

A few weeks ago, I installed Anacond, PyCharm and several Python packages (Pyomo, qrid, objectbrowser, ...° .
I worked for some weeks without paying much attention to details.
Recently, I observed that code completion shows each attribute twice in the drop down list.
Can't guess since when this is so.

Would you have a suggestion about that?

Thanks,

PS: Already posted on "Project Jupyter", was informed this is already an issue in JupiterLab.

**Comment by akaitake** [comment]
I've got the same problem as @maajdl.
I installed only jupyer by pip under venv environment (pip instsall jupyer) but this problem occurred in "jupyter console".

**Comment by fletchjeff** [comment]
I'm having the same issue:

![screen shot 2017-12-21 at 4 02 35 pm](https://user-images.githubusercontent.com/5757642/34258829-76c3595c-e668-11e7-94b0-0a6b12787a8c.png)

**Comment by AlexBella365** [comment]
Same thing here:
![image](https://user-images.githubusercontent.com/22292468/34548062-945ba5f0-f13a-11e7-82cf-1e5089bc59f2.png)

**Comment by takluyver** [comment]
The bug is actually coming from IPython - we're discussing it on https://github.com/ipython/ipython/issues/10960

**Comment by jtpio** [comment]
Closing as this should now be fixed in Notebook 7.
