### ISSUE TITLE
dev install fails on Windows

### ISSUE THREAD

**Issue by blitzd** [jupyter/notebook#315]
The current master branch is failing to run through setup on Windows. The issue appears to be with the commands that are being called like 'npm install', or 'lessc', etc - they're not actually being executed, they're only being output to the screen and then the next step of the build is run. So despite having node set up correctly, I'm not able to get past the point of 'npm install'. Running it manually works fine though, however it then fails on the next step with the 'bower install'.

**Comment by minrk** [comment]
Running `npm install` works locally? What about `npm run bower`?

**Comment by blitzd** [comment]
Tracked down the issue, check_call needs to be run with shell=True on windows.

https://github.com/jupyter/notebook/blob/47cced4ab94a46174731e72bd66281de9cd22fc5/setupbase.py#L298

Swithching that line to:

```
    return check_call(cmd, shell=True, *args, **kwargs)
```

...results in a working build/setup. I'm not sure what effect it would have on other targets though, I'm not particularly familiar with setuptools.

**Comment by minrk** [comment]
I think running with shell=True should be okay on any system.

**Comment by minrk** [comment]
#321 should add shell=True. Can you verify that this works for you?

**Comment by darshanime** [comment]
Hello, I am facing an installation issue too and did not wish to create a new issue for my problem. I have been using ipynb for a long time now before I decided to update and got stuck. 

[Here](https://gist.github.com/darshanime/f94d2b8f4dbe1c49dc3e) is my stack. I am running Ubuntu 14.04 and the commands I ran prior this one are : 
```python
sudo apt-get install nodejs-legacy npm python-virtualenv python-dev
# ensure setuptools/pip are up-to-date
pip install --upgrade setuptools pip
git clone https://github.com/jupyter/notebook.git
cd notebook
pip install --pre -e .
```

**Comment by Carreau** [comment]
Seem like github was unreachable at the time you installed :+1: 
```
    bower font-awesome#~4.2.0      ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/components/font-awesome.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.128]: errno=Connection timed out

```

**Comment by darshanime** [comment]
That's what I thought too initially. But I tried to run this many times and
each time it failed; even when I could browse and surf fine.
I'll retry though.

**Comment by Carreau** [comment]
hum, what if you `bower install font-awesome` manualy ?

**Comment by darshanime** [comment]
That seems like a good idea. Only, I have to run many times `pip install --pre -e .`, look for what I not get and run a separate command for the same; guess I can live with that as long as I get the notebook in the end !

**Comment by Carreau** [comment]
You can also drop the `--pre`. And once you get the python part installed we can try to get the JS by hand. which is : 
 - npm 
 - bower
 - then minify, and it should be ok.

**Comment by darshanime** [comment]
What can be the problem in your opinion ?

Also, running separate `git ls-remote --tags --heads git://github.com/components/underscore.git` gives me lines of `reference-tags?` : 
`
e2072705f6e2acd303430d1525b6278ace4372b2	refs/tags/1.5.1
38a139ff4aee2c57413aa4611137563474c45ac7	refs/tags/1.5.2
`
What exactly is this ?

**Comment by Carreau** [comment]
> On Aug 21, 2015, at 17:04, Darshan Chaudhary <notifications@github.com> wrote:
> 
> What can be the problem in your opinion ?
> 
> Also, running separate git ls-remote --tags --heads git://github.com/components/underscore.git gives me lines of reference-tags? : 
> 
> e2072705f6e2acd303430d1525b6278ace4372b2 refs/tags/1.5.1
> 38a139ff4aee2c57413aa4611137563474c45ac7 refs/tags/1.5.2
> 
> What exactly is this ?
> 

I would guess that this tells you that tag 1.5.1 link to commit e2072... and 1.5.2 to ....
tags are mutable and hash are not, so this does not actually tell you anything except that if you install 
1.5.1 which specific commit you install.

**Comment by darshanime** [comment]
Working now ! Thanks

**Comment by Carreau** [comment]
Great, if you figured out what was wrong, feel free to add a comment here !

**Comment by darshanime** [comment]
It could be that the firewall is blocking the git protocol. Replacing `git://...` with 'https://...` fixed it for me.

Also, thank you for the notebook. I can't deny I wasn't sulking when the notebook was gifted to people outside the Python community. For me, ipynb was like this special utility only developers loyal to Python got to enjoy !

**Comment by Carreau** [comment]
> On Aug 21, 2015, at 17:21, Darshan Chaudhary <notifications@github.com> wrote:
> 
> It could be that the firewall is blocking the git protocol. Replacing git://... with 'https://...` fixed it for me.
> 
have a look at git insteadOf (would give you link but bad connexion, google is your friend)
you can tell git yo always use https:// instead of git:// or mirror.something.com <http://mirror.something.com/> instead of git.github.com <http://git.github.com/> ... etc.
it will save you a few headache. 
> Also, thank you for the notebook. I can't deny I wasn't sulking when the notebook was gifted to people outside the Python community. For me, ipynb was like this special utility only developers loyal to Python got to enjoy !
> 

Alway happy to get more non-python people. 
What kernel are you using ?

Always looking for feedback and help from other communities.

**Comment by blitzd** [comment]
@minrk The #321 change appears to work for me in jupter/notebook:master when I add it, but I couldn't get the fork you had to work - something about nbformat not matching the version required.
