### ISSUE TITLE
Problem with redirect for newly created notebook file.

### ISSUE THREAD

**Issue by orobsonpires** [jupyter/notebook#3150]
Hi, I am trying to create, and then redirect to this newly created notebook, this is part of my code:

```python
nb = nbformat.v4.new_notebook();
now = datetime.datetime.now()
notebook_file_name = customerId + 'Empty_notebookname' + str(int(round(time.time() * 1000)))
nbformat.write(nb, self.root_dir + '/' + notebook_file_name + '.ipynb')
self.redirect('/notebook/' + notebook_file_name + '.ipynb')
```

The file is created, however, I just get a 404 page. I thought this would be enough to create and run my notebook. Am I missing somethin?

**Comment by takluyver** [comment]
Try changing `/notebook/` to `/notebooks/`

**Comment by orobsonpires** [comment]
ohh that was really newbie from my side. Thanks a lot.
