### ISSUE TITLE
Reload of .ipynb is extremely slow

### ISSUE THREAD

**Issue by avriLee** [jupyter/notebook#3155]
_Description_:

Since we need to show many images(_coding in base64_) in one cell's output area, the reload of _.ipynb_ file will be extremely slow. While the outputs of the cell might contain other useful messages that must be left, _only_ a part of outputs needs to be cleared up. 
```python
def _create_nb_img(tag_id, data):
    display(HTML("<img id='{}' src='data:image/png;base64,{}'/>".format(tag_id, data)))


def _replace_nb_img(tag_id, data):
    js = "$('#{}').attr('src', 'data:image/png;base64,{}')".format(tag_id, data.replace("\n", ""))
    display(Javascript(js))

# usage
# get_image_data() will load a new image every time
_create_nb_img(tag_id, get_image_data(0))
for i in range(1, 1000):
    _replace_nb_img(tag_id, get_image_data(i))
```

_**Notice**: As the visual effects to the user are similar to the video via picture replacement, and the output of images files might and even must be especially huge, the reload of notebook is not user-friendly..._
  
So our demands are: 
- Keep other messages(_outputs_) ;
- When facing the video-similar way to display images, we must save the first msg like: 
 ```json
{
     "data": {
      "text/html": [
       "<img id='img-video-1' src='data:image/png;base64,....../>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
},
```
and the last msg: 
```json
{
     "data": {
      "application/javascript": [
       "$('#img-video-1').attr('src', 'data:image/png;base64,......')"
      ],
      "text/plain": [
       "<IPython.core.display.Javascript object>"
      ]
},
```
- While others related to images must be not stored into _.ipynb_ file.

Btw, [my informal and immature solution now](https://github.com/ipython/ipython/issues/10954), and the [Limit Output by _ConfigManager_](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/limit_output/readme.html) is not suitable here.

**Is there a better way to deal with it?**

Thanks for your time and looking forward to receiving your reply!

**Comment by the-sea** [comment]
I have the same problem, is there any idea?

**Comment by takluyver** [comment]
Aha, now that I understand what you're after, I think there is a better way. The display machinery allows for 'updating' a display object, which basically replaces the one that was there before. There are a couple of ways to use it - this is the one I'd recommend:

```python
from IPython.display import display, Image
display_handle = display(Image(get_image_data(0), format='png'), display_id=True)
for i in range(1, 1000):
    display_handle.update(Image(get_image_data(i), format='png'))
```

(Using the `Image` class, you don't need to base64-encode your data - IPython will do this for you.)

That should do basically the same as your code, but it will save and reload the final output correctly.

**Comment by avriLee** [comment]
Hi, @takluyver the destination you recommended works me exactly via updating the version! 
Thanks for your method!

_While_, if i want to remove the last image, is there any interface or function to do this?

**Comment by takluyver** [comment]
A hacky way to do it would be to update it again with an object that doesn't display anything:

```python
class Invisible(object):
    def __repr__(self):
        return ''

display_handle.update(Invisible())
```

We could probably add a `DisplayHandle.clear()` method if that's useful.

Another way is to call `IPython.display.clear_output()`, but that removes all output from the current cell.

Finally, you could do it by processing the notebook file - e.g. it would be straightforward to load a notebook file, remove all png outputs, and save it again.

**Comment by avriLee** [comment]
Yes, working as expected! That was more convenient! Thanks! @takluyver
