### ISSUE TITLE
Failed to start the kernel

### ISSUE THREAD

**Issue by vijaysaimutyala** [jupyter/notebook#3157]
I had an installation of Anaconda 3 with Python 3.5.2. Jupyter notebook was working fine till last night. Today when i try creating a new notebook or run an existing notebook, I receive the following log.

I tried a clean install of Anaconda 3 with Python 3.6.3 but still see the same issue. I checked the kernel.json file with jupyter kernelspec list but everything looks good.

I've installed google cloud api engine libraries in the morning which I dont think would have affected this function of Jupyter.

> Traceback (most recent call last):
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
>     value = obj._trait_values[self.name]
> KeyError: 'session'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\session.py", line 522, in _check_packers
>     packed = pack(msg)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\session.py", line 103, in <lambda>
>     ensure_ascii=False, allow_nan=False,
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\utils\jsonapi.py", line 40, in dumps
>     s = jsonmod.dumps(o, **kwargs)
> AttributeError: module 'simplejson' has no attribute 'dumps'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\base\handlers.py", line 516, in wrapper
>     result = yield gen.maybe_future(method(self, *args, **kwargs))
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
>     value = future.result()
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
>     yielded = self.gen.throw(*exc_info)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 75, in post
>     type=mtype))
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
>     value = future.result()
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
>     yielded = self.gen.throw(*exc_info)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
>     kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
>     value = future.result()
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
>     yielded = self.gen.throw(*exc_info)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
>     self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
>     value = future.result()
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 307, in wrapper
>     yielded = next(result)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 94, in start_kernel
>     super(MappingKernelManager, self).start_kernel(**kwargs)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
>     km.start_kernel(**kwargs)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\manager.py", line 238, in start_kernel
>     self.write_connection_file()
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\connect.py", line 426, in write_connection_file
>     transport=self.transport, ip=self.ip, key=self.session.key,
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
>     return self.get(obj, cls)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
>     value = self._validate(obj, dynamic_default())
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\connect.py", line 344, in _session_default
>     return Session(parent=self)
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\session.py", line 482, in __init__
>     self._check_packers()
>   File "C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\session.py", line 530, in _check_packers
>     msg.format(packer=self.packer, e=e, jsonmsg=jsonmsg)
> ValueError: packer 'json' could not serialize a simple message: module 'simplejson' has no attribute 'dumps'
> zmq.utils.jsonapi.jsonmod = <module 'simplejson' (namespace)>

**Comment by takluyver** [comment]
Have you made a folder called `simplejson`?

**Comment by takluyver** [comment]
Check which version of `ipykernel` you have installed - if it's older than 4.6, can you try upgrading (and reinstalling the kernelspec)? We made a change to how the kernel launches, which should reduce this kind of issue (https://github.com/ipython/ipykernel/pull/209 ).

**Comment by vijaysaimutyala** [comment]
The ipykernel version is 4.7.0

![image](https://user-images.githubusercontent.com/7084628/34260262-4503b182-e68b-11e7-82b2-c4c3ec13276d.png)

**Comment by vijaysaimutyala** [comment]
@takluyver No I dont have any simplejson folder. Do I have to create one?

**Comment by vijaysaimutyala** [comment]
@takluyver Thanks for pointing out that simplejson. Somehow I don't have the simplejson module installed.  I installed the module via pip and the kernel is up and running now. I didn't get how the module was missing. 

For anyone returning here with a similar issue where simplejson was pointed out, try installing simplejson via pip.

> pip install -U simplejson

One more solution could be removing the simplejson from the 

> priority = ['simplejson', 'jsonlib2', 'json']

list in the file jsonapi.py which is usually under

> C:\Users\mutyalavijay_Sai\AppData\Local\Continuum\anaconda3\Lib\site-
packages\zmq\utils\jsonapi.py

**Comment by takluyver** [comment]
simplejson isn't required, but from the error it looks like it's finding a `simplejson` folder somewhere. You can find out where it is by running:

```python
import simplejson
print(implejson.__path__)
```

(Now that you've installed the simplejson package, it will find that instead)
