### ISSUE TITLE
localhost This site can’t be reached

### ISSUE THREAD

**Issue by overlapjho** [jupyter/notebook#3161]
Every time I launch the Jupyter notebook
    `jupyter notebook`
I always get 
   ` This site can’t be reached The connection was reset.`

This occurs with all browsers I use:
How to solve this problem?

I already tried turning off anti virus and firewall, reinstall anaconda and deselect "Use a proxy server for your LAN" in chrome but it all didn't worked.

**Comment by takluyver** [comment]
Do you have any internet security software installed? Some such products
have caused issues.

**Comment by overlapjho** [comment]
I checked my installed programs there is no other  internet security software installed I only use windows defender for security

**Comment by overlapjho** [comment]
It looks like my jupyter_nbextensions_configurator has the problem, I solve it by reinstalling jupyter_nbextensions_configurator.
