### ISSUE TITLE
Unable to launch jupyter notebook

### ISSUE THREAD

**Issue by grvjn06** [jupyter/notebook#3162]
ran this :  jupyter-notebook port=7000

![screen shot 2017-12-25 at 4 00 34 pm](https://user-images.githubusercontent.com/29071460/34338249-c750d490-e98c-11e7-8583-a842741a25f5.png)

**Comment by grvjn06** [comment]
![screen shot 2017-12-25 at 4 02 14 pm](https://user-images.githubusercontent.com/29071460/34338270-06f533de-e98d-11e7-90b7-cbc5b5897181.png)

**Comment by grvjn06** [comment]
Used to work fine, but suddenly it shows up this when I launch it.

**Comment by Madhu94** [comment]
@grvjn06 Are you using a virtualenv ? What version of the notebook and traitlets package are you using ?

```
In [2]: import notebook

In [3]: notebook.__version__
Out[3]: '5.3.0.dev0'

In [4]: import traitlets

In [5]: traitlets.__version__
Out[5]: '4.3.2'
```

**Comment by grvjn06** [comment]
yes, i am using virtualenv
notebook version - 5.0.0
traitlets - 4.0.0

**Comment by Madhu94** [comment]
Seems similar to https://github.com/ipython/traitlets/issues/388 and https://github.com/jupyter/notebook/issues/2317, can you try re-installing ?

**Comment by takluyver** [comment]
First error: it should be `--port=7000` (you missed the `--`)

Second error: do you have a `traitlets.py` file in the working directory? Or a `traitlets` folder?

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
