### ISSUE TITLE
Cant run jupyter-qtconsole.exe

### ISSUE THREAD

**Issue by AntonGridushko** [jupyter/notebook#3167]
Hello everyone!
My problem is:
![2017-12-28_03-01-49](https://user-images.githubusercontent.com/17615939/34396593-164aab50-eb7e-11e7-8c71-44a1f32620d9.png)

What should I do?((
Help me, please....

**Comment by takluyver** [comment]
Try uninstalling and reinstalling IPython. The `IPython.core.release` module certainly should be there.

**Comment by AntonGridushko** [comment]
COOL ADVISE!! THANK U A LOT !!! takluyver!!!!

**Comment by takluyver** [comment]
You're welcome!
