### ISSUE TITLE
Cannot install jupyter with Python 3.6.4

### ISSUE THREAD

**Issue by unknown867** [jupyter/notebook#3169]
when i typing pip3 install jupyter on administrator cmd an error occured packs are collecting but cannot installing:

    Installing collected packages: tornado, six, wcwidth, prompt-toolkit, parso, 
    jedi, simplegeneric, pickleshare, ipython-genutils, decorator, traitlets, 
    ipython, pyzmq, jupyter-core, python-dateutil, pluggy, py, attrs, pytest, 
    jupyter-client, ipykernel, MarkupSafe, jinja2, testpath, pandocfilters, 
    webencodings, html5lib, bleach, entrypoints, mistune, jsonschema, nbformat, 
    nbconvert, notebook, widgetsnbextension, ipywidgets, qtconsole, jupyter-
    console, jupyter
      Running setup.py install for simplegeneric ... error
    Exception:
    Traceback (most recent call last):
      File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-
    packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 53: 
    invalid start byte

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-
    packages\pip\basecommand.py", line 215, in main
        status = self.run(options, args)
      File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-
    packages\pip\commands\install.py", line 342, in run
        prefix=options.prefix_path,
      File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-
    packages\pip\req\req_set.py", line 784, in install
        **kwargs
      File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-
    packages\pip\req\req_install.py", line 878, in install
        spinner=spinner,
      File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-
    packages\pip\utils\__init__.py", line 676, in call_subprocess
        line = console_to_str(proc.stdout.readline())
      File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-
    packages\pip\compat\__init__.py", line 75, in console_to_str
        return s.decode('utf_8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 53: invalid start byte

**Comment by unknown867** [comment]
can anyone help me pls

**Comment by stonebig** [comment]
the "™" character  in your profile "casper™" may be the problem. Did you try with a profile not containing this character ?

**Comment by unknown867** [comment]
Yes i changed my profile with casperPC and it works. I setup jupyter.Thank you
