### ISSUE TITLE
Jupyter does not respect the default nbconvert template

### ISSUE THREAD

**Issue by t-makaro** [jupyter/notebook#3172]
By adding the line
```
c.LatexExporter.template_file = 'my_template.tplx'
```
to the jupyter_nbconvert_config.py file, I've set nbconvert to default to my template for latex and pdf conversions. However, when I use the "export as pdf" option from within Jupyter notebook it still tries to use the default "article.tplx" template.

**Comment by takluyver** [comment]
Config files are per-application, so you could try copying that line into `jupyter_notebook_config.py`

**Comment by t-makaro** [comment]
Thank you very much! That worked. I've been looking for a way to change this default template for so long. I couldn't find any documentation saying that I could use nbconvert configuration settings as notebook settings.
