### ISSUE TITLE
How to config i18n in jupyter notebook?

### ISSUE THREAD

**Issue by lifubang** [jupyter/notebook#3174]
Hello.
I want to use zh_CN language in web ui, but I don't know how to config it. Would you please help me.
My process:
pip install notebook
LANG=zh_CN jupyter notebook

But I can't see chinese in chrome.

The version is notebook-5.2.2

Thanks.

**Comment by takluyver** [comment]
In Chrome's settings, the languages options look like this:

![screenshot from 2018-01-03 12-27-20](https://user-images.githubusercontent.com/327925/34520668-88e8540c-f081-11e7-9758-0e01e9971b3e.png)

**Comment by yshkk** [comment]
Still doesn't work after setting in Chrome.
![image](https://user-images.githubusercontent.com/9150795/34673020-c4486bde-f4bb-11e7-8443-46522400b236.png)

**Comment by hikui** [comment]
I have the same problem. I tried setting LANG to zh_CN.UTF-8 and switched the system language to Chinese, but the web UI is still in English.

I'm pretty sure the browser settings is not an issue as the `Accept-Language` header was correctly set to zh_CN.

I saw the Chinese translation was done by @jianzi123 last year. Perhaps he could explain how to correctly configure the translation?

**Comment by jianzi123** [comment]
I use notebook in Chinese with chrome not config anything in chrome.

**Comment by jtpio** [comment]
Closing as fixed in Notebook 7, which uses the same internationalization feature as in JupyterLab:


https://github.com/jupyter/notebook/assets/591645/6275e3cf-eb86-4ce1-83b2-7a96e7bfdf48
