### ISSUE TITLE
when session killed from other tab, notebook UI doesn't reflect change

### ISSUE THREAD

**Issue by jfsny** [jupyter/notebook#3178]
Repro steps:
1. Open notebook in tab 1.
2. In another tab, visit the "Open" page, navigate to the "Running" tab.
3. Observe currently running notebook process under "Notebooks" and click "Shutdown" button.

Expected: Kernel status in tab 1 shows "Kernel is not running", "No kernel" notification appears.
Actual: Kernel status in tab 1 shows "Kernel idle", no notifications. If a cell is run, it just stays pending forever.

Under the hood, if a cell is running in tab 1 when the kernel is interrupted, there is no "shutdown_reply" message on iopub. If a cell is not running in tab 1, there is a "shutdown_reply" but it is (apparently) ignored.

**Comment by jtpio** [comment]
Checking with the latest Notebook `7.0.0rc0`, it seems like this is now working as expected:

https://github.com/jupyter/notebook/assets/591645/5eb6dd04-1d70-4cc1-8aab-7de91ee83b8c

Closing as fixed, but feel free to re-open if you still want to discuss it or open a new issue if you have more questions. Thanks!
