### ISSUE TITLE
Fatal Python error: Py_Initialize: can't initialize sys standard streams

### ISSUE THREAD

**Issue by blitzd** [jupyter/notebook#318]
On attempting to stop the notebook server with the typical Control-C I often times (not always) receive the following error and a crashed python.exe process:

```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\Anaconda3\envs\jupyter\lib\encodings\__init__.py", line 97, in search_function
    mod = __import__('encodings.' + modname, fromlist=_import_tail,
KeyboardInterrupt
[I 10:11:21.521 NotebookApp] Interrupted...
[I 10:11:21.521 NotebookApp] Shutting down kernels
```

This is in an isolated anaconda environment just for Jupyter 4:

```
{'commit_hash': 'f534027',
 'commit_source': 'installation',
 'default_encoding': 'cp1252',
 'ipython_path': 'C:\\Anaconda3\\envs\\jupyter\\lib\\site-packages\\IPython',
 'ipython_version': '4.0.0',
 'os_name': 'nt',
 'platform': 'Windows-8-6.2.9200',
 'sys_executable': 'C:\\Anaconda3\\envs\\jupyter\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, '
                '12:06:10) [MSC v.1600 64 bit (AMD64)]'}
```

packages are:

```
certifi==14.5.14
decorator==4.0.2
ipykernel==4.0.3
ipython==4.0.0
ipython-genutils==0.1.0
ipywidgets==4.0.2
Jinja2==2.8
jsonschema==2.4.0
jupyter==1.0.0
jupyter-client==4.0.0
jupyter-console==4.0.0
jupyter-core==4.0.4
MarkupSafe==0.23
mistune==0.7
nbconvert==4.0.0
nbformat==4.0.0
-e git+https://github.com/jupyter/notebook.git@47cced4ab94a46174731e72bd66281de9cd22fc5#egg=notebook-master
numpy==1.9.2
pandas==0.16.2
path.py==0.0.0
pickleshare==0.5
Pygments==2.0.2
pyreadline==2.0
python-dateutil==2.4.2
pytz==2015.4
pyzmq==14.7.0
qtconsole==4.0.1
scipy==0.16.0
simplegeneric==0.8.1
six==1.9.0
tornado==4.2.1
traitlets==4.0.0
wheel==0.24.0
```

It could be a version mismatch between notebook-master and other Anaconda versions of jupyter/ipython, but I do believe I was receiving the error before I tried notebook-master (and was using the version Anaconda currently has) as well.

**Comment by blitzd** [comment]
Each time I go to run jupyter I end up with a hung jupyter-notebook.exe process for an extended period of time. On the command line the process will return to the command prompt right away, and I can see via process explorer that jupyter-notebook.exe is in fact running, but it doesn't appear to do anything. 

If I run it again from the same command line I will then get the typical informational messages saying that the server is running - I do not know if this is from the first or second process - but it happens shortly after the second is run.

I suspect this is what is causing the crash when exiting via Control-C, as both processes are stopped when that occurs (and python.exe crashes).

If I had to guess I'd say it has something to do with running the command appearing to execute disconnected from the cmd.exe process that launched it (i.e., it instantly returns to the command line) - that never used to be how ipython worked, it would remain connected and blocking the cmd.exe process (which in this case is "C:\Windows\System32\cmd.exe" /k "C:\Anaconda3\Scripts\anaconda.bat").

**Comment by Carreau** [comment]
that seem weird this is a C-level error, and i'm not experienced enough with windows to know why it would do that. Have you try pinging Continuum ?

**Comment by blitzd** [comment]
I think you're right - I tried standard cpython from python.org and didn't run into the issue, it also didn't drop back to the command line right after it was run. I've notified Continuum.
