### ISSUE TITLE
Display issue for val in stdout or stderr with _ (_ not always correctly displayed)

### ISSUE THREAD

**Issue by Naereen** [jupyter/notebook#3193]
Hi! 🎉 Merry new year!

## Issue
Here is an example of a weird display issue:
![bug_display_out_value_with_underscore_in_its_name](https://user-images.githubusercontent.com/11994719/34725551-91c1feaa-f551-11e7-92dc-cef9a4bf301e.png)
(The variable `ex1_1` but displayed `ex1 1`. On Firefox 57, Ubuntu 17.10)

Another example, showing the difference between stdout and stderr output:
![bug_display_out_value_with_underscore](https://user-images.githubusercontent.com/11994719/34725968-ebded114-f552-11e7-9f19-d94e406fc2cd.png)

## Reason
It's a bug probably coming from the style in `outputarea.less:96`.
https://github.com/jupyter/notebook/blob/179bb24fbf79d153812858126127a91431da3319/notebook/static/notebook/less/outputarea.less#L98

It can be fix by forcing a `padding-bottom: 1px;` rule for `div.output_area pre`:
![bug_display_out_value_with_underscore_in_its_name2](https://user-images.githubusercontent.com/11994719/34725685-fa6d5120-f551-11e7-8542-63dfbe2f9352.png)

I will submit the PR to fix this.

**Comment by takluyver** [comment]
Thanks for the investigation! @gnestor do you think the fix is OK to slip into 5.3?

**Comment by Naereen** [comment]
@takluyver Thanks for your quick feedback.

**Comment by gnestor** [comment]
I don't see why not! Thanks @Naereen!

**Comment by Naereen** [comment]
This was merged right (#3194), so I close this issue.

**Comment by takluyver** [comment]
Thanks :-)

For future reference, you can put `Closes #3194` in the commit message, and then merging the PR will automatically close the issue.

**Comment by Naereen** [comment]
I use this for personal projects, but I didn't know that it would work when the PR is merged, thanks!
