### ISSUE TITLE
Problem signing out of Jupyter Notebooks if c.NotebookApp.base_url is set (cookie not cleared)

### ISSUE THREAD

**Issue by leontp587** [jupyter/notebook#3196]
This is a bug report.

Versions tested:
- Notebook 5.2.2 on python 2.7 on RedHat Enterprise Linux 6.9 and Windows 7
- Notebook 5.2.1 on python 2.7 on Windows 7

Reproduce steps:
1) Install Jupyter notebooks with "pip installing jupyter"
2) Generate a config file with "jupyter notebook --generate-config"
3) Set a password in c.NotebookApp.password in .jupyter/jupyter_notebook_config.py
4) Set a base URL in c.NotebookApp.base_url in .jupyter/jupyter_notebook_config.py
5) Run "jupyter --notebook"
6) Login with password, and click logout, then login again. You'll see the user isn't logged out. Closing the browser doesn't help. The cookie is still present.

If I don't set a base_url (step 4 above), then the logout and cookie clearing works normally.

Can someone confirm this behavior? I tried on both Windows and Linux in my environment and hit this bug.

**Comment by leontp587** [comment]
After looking at the code: the problem is in notebook/base/handlers.py

def clear_login_cookie(self):
        cookie_options = self.settings.get('cookie_options', {})
        path = cookie_options.setdefault('path', self.base_url)
        **self.clear_cookie(self.cookie_name, path=path) // first clear_cookie**
        if path and path != '/':
            # also clear cookie on / to ensure old cookies
            # are cleared after the change in path behavior.
            **self.clear_cookie(self.cookie_name) // second clear_cookie**

The problem is in the last line where I've marked //second clear_cookie. Commenting this out fixes the problem.

The issue is that clear_cookie is implemented by the Tornado backend on the server side by marking the cookie as expired. Cookies don’t actually expire on the server though, they are implemented by the client browser on the http response. Cookies have paths, the first call to clear_cookie on the line where I marked // first clear_cookie has a path set correctly, and the Tornado backend sets the cookie for expiration. The second call to clear_cookie inside the if block has no path set, so the Tornado backend gets confused and messes up the cookie expiration from the first call. So when the browser gets the response, it doesn’t clear the cookie.

The reason this doesn’t happen if Jupyter doesn’t have a base_url is because in that case path=’’, so the two clear_cookie calls are equivalent.

The easiest fix it to comment out the second call to clear_cookie, if we don't care about accounting for the behavior of cookies from old Jupyter versions. I'm not sure what a full fix is yet.

This is in some ways really a Tornado bug with dealing with cookies with paths rather than a Jupyter bug.

**Comment by takluyver** [comment]
#3207 fixes it for me, but it's a bit of a hackish workaround.

**Comment by leontp587** [comment]
thanks for getting it fixed so quickly!
