### ISSUE TITLE
Add how to print version / environment data to the contribution guideline

### ISSUE THREAD

**Issue by medihack** [jupyter/notebook#3198]
In many of the issue messages I often see something like the below environment report. How do I get this? It should be somehow explained on the first page of the [contributing guidelines](https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.rst) that are linked at the top the new issue form.

<pre>
{'commit_hash': '51ce9d73b',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.0.0',
 'os_name': 'posix',
 'platform': 'Darwin-16.5.0-x86_64-i386-64bit',
 'sys_executable': '/usr/local/opt/python3/bin/python3.6',
 'sys_platform': 'darwin',
 'sys_version': '3.6.1 (default, Apr  4 2017, 09:40:21) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]'}
</pre>

**Comment by takluyver** [comment]
I think that format comes from `print(IPython.sys_info())` in Python. You can also get similar information by running `jupyter troubleshoot` at the command line.

**Comment by jtpio** [comment]
Closing as answered, thanks!
