### ISSUE TITLE
how to disable static magic commands

### ISSUE THREAD

**Issue by stczwd** [jupyter/notebook#3199]
I have defined a custom kernel and several magics. I want to disable all static magic commands from the notebook to prevent users running illegal commands within a notebook. How can I do?

**Comment by takluyver** [comment]
What do you mean by 'static magics'? If you have written your own kernel, it should only process the magics you've programmed into it. Magics are part of the IPython kernel; they don't automatically apply for other kernels.

**Comment by stczwd** [comment]
static magics: the magics provided by IPython kernel
My kernel inherits from IPythonkernel, I just want to keep part of magics.

**Comment by takluyver** [comment]
Can you point us to your code?

If you're doing this as a security measure, be aware that anything the user can do via magic commands, they can also do with regular Python code. It's basically impossible to do effective sandboxing by trying to restrict what code users can run. If you don't trust the users, you need to run the notebook inside some kind of container so they can only affect their own container.

**Comment by stczwd** [comment]
OK,I know what I should do now.Thanks for your advice.
