### ISSUE TITLE
Class methods listed twice

### ISSUE THREAD

**Issue by Dpananos** [jupyter/notebook#3208]
When I hit tab on variables which are of a certain type (like numpy arrays) I get all the methods listed twice. See below

<img width="267" alt="screen shot 2018-01-12 at 5 08 03 pm" src="https://user-images.githubusercontent.com/20362941/34902638-92080a0a-f7ed-11e7-8bc9-e2986c0ae4e4.png">

I've uninstalled and reinstalled jupyter and the problem persists.  

Any ideas?

**Comment by takluyver** [comment]
It's an issue in IPython - see https://github.com/ipython/ipython/issues/10960 . It should be fixed when we release IPython 6.3.
