### ISSUE TITLE
I can't start Jupyter Notebook

### ISSUE THREAD

**Issue by jaylaaaa** [jupyter/notebook#3209]
**I just installed jupyter notebook on a non root sudo account using digital ocean's guides on google cloud.
Heres the error**
`Traceback (most recent call last):
  File "/home/jupyter/environments/my_env/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/jupyter/environments/my_env/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/jupyter/environments/my_env/lib/python3.5/site-packages/notebook/nbextensions.py", line 32, in <module>
    from traitlets.config.manager import BaseJSONConfigManager
  File "/home/jupyter/environments/my_env/lib/python3.5/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/home/jupyter/environments/my_env/lib/python3.5/site-packages/traitlets/config/application.py", line 120, in <module>
    class Application(SingletonConfigurable):
  File "/home/jupyter/environments/my_env/lib/python3.5/site-packages/traitlets/config/application.py", line 291, in Application
    def initialize(self, argv=None):
TypeError: catch_config_error() missing 1 required positional argument: 'app'`
**Here is my package list:**
accountsservice                                 install
acl                                             install
acpid                                           install
adduser                                         install
apparmor                                        install
apport                                          install
apport-symptoms                                 install
apt                                             install
apt-transport-https                             install
apt-utils                                       install
at                                              install
base-files                                      install
base-passwd                                     install
bash                                            install
bash-completion                                 install
bcache-tools                                    install
bind9-host                                      install
binutils                                        install
bsdmainutils                                    install
bsdutils                                        install
btrfs-tools                                     install
build-essential                                 install
busybox-initramfs                               install
busybox-static                                  install
byobu                                           install
bzip2                                           install
ca-certificates                                 install
cloud-guest-utils                               install
cloud-init                                      install
cloud-initramfs-copymods                        install
cloud-initramfs-dyn-netconf                     install
command-not-found                               install
command-not-found-data                          install
console-setup                                   install
console-setup-linux                             install
coreutils                                       install
cpio                                            install
cpp                                             install
cpp-5                                           install
cron                                            install
cryptsetup                                      install
cryptsetup-bin                                  install
curl                                            install
dash                                            install
dbus                                            install
debconf                                         install
debconf-i18n                                    install
debianutils                                     install
dh-python                                       install
diffutils                                       install
distro-info-data                                install
dmeventd                                        install
dmidecode                                       install
dmsetup                                         install
dns-root-data                                   install
dnsmasq-base                                    install
dnsutils                                        install
dosfstools                                      install
dpkg                                            install
dpkg-dev                                        install
e2fslibs:amd64                                  install
e2fsprogs                                       install
eatmydata                                       install
ed                                              install
eject                                           install
ethtool                                         install
fakeroot                                        install
file                                            install
findutils                                       install
fonts-ubuntu-font-family-console                install
friendly-recovery                               install
ftp                                             install
fuse                                            install
g++                                             install
g++-5                                           install
gawk                                            install
gcc                                             install
gcc-5                                           install
gcc-5-base:amd64                                install
gcc-6-base:amd64                                install
gce-compute-image-packages                      install
gdisk                                           install
geoip-database                                  install
gettext-base                                    install
gir1.2-glib-2.0:amd64                           install
git                                             install
git-man                                         install
gnupg                                           install
google-cloud-sdk                                install
google-compute-engine-oslogin                   install
gpgv                                            install
grep                                            install
groff-base                                      install
grub-common                                     install
grub-gfxpayload-lists                           install
grub-pc                                         install
grub-pc-bin                                     install
grub2-common                                    install
gzip                                            install
hdparm                                          install
hostname                                        install
ifenslave                                       install
ifupdown                                        install
info                                            install
init                                            install
init-system-helpers                             install
initramfs-tools                                 install
initramfs-tools-bin                             install
initramfs-tools-core                            install
initscripts                                     install
insserv                                         install
install-info                                    install
iproute2                                        install
iptables                                        install
iputils-ping                                    install
iputils-tracepath                               install
isc-dhcp-client                                 install
isc-dhcp-common                                 install
iso-codes                                       install
kbd                                             install
keyboard-configuration                          install
klibc-utils                                     install
kmod                                            install
krb5-locales                                    install
language-selector-common                        install
less                                            install
libaccountsservice0:amd64                       install
libacl1:amd64                                   install
libalgorithm-diff-perl                          install
libalgorithm-diff-xs-perl                       install
libalgorithm-merge-perl                         install
libapparmor-perl                                install
libapparmor1:amd64                              install
libapt-inst2.0:amd64                            install
libapt-pkg5.0:amd64                             install
libasan2:amd64                                  install
libasn1-8-heimdal:amd64                         install
libasprintf0v5:amd64                            install
libatm1:amd64                                   install
libatomic1:amd64                                install
libattr1:amd64                                  install
libaudit-common                                 install
libaudit1:amd64                                 install
libbind9-140:amd64                              install
libblkid1:amd64                                 install
libbsd0:amd64                                   install
libbz2-1.0:amd64                                install
libc-bin                                        install
libc-dev-bin                                    install
libc6:amd64                                     install
libc6-dev:amd64                                 install
libcap-ng0:amd64                                install
libcap2:amd64                                   install
libcap2-bin                                     install
libcc1-0:amd64                                  install
libcilkrts5:amd64                               install
libcomerr2:amd64                                install
libcryptsetup4:amd64                            install
libcurl3:amd64                                  install
libcurl3-gnutls:amd64                           install
libdb5.3:amd64                                  install
libdbus-1-3:amd64                               install
libdbus-glib-1-2:amd64                          install
libdebconfclient0:amd64                         install
libdevmapper-event1.02.1:amd64                  install
libdevmapper1.02.1:amd64                        install
libdns-export162                                install
libdns162:amd64                                 install
libdpkg-perl                                    install
libdrm-common                                   install
libdrm2:amd64                                   install
libdumbnet1:amd64                               install
libeatmydata1:amd64                             install
libedit2:amd64                                  install
libelf1:amd64                                   install
liberror-perl                                   install
libestr0                                        install
libevent-2.0-5:amd64                            install
libexpat1:amd64                                 install
libexpat1-dev:amd64                             install
libfakeroot:amd64                               install
libfdisk1:amd64                                 install
libffi-dev:amd64                                install
libffi6:amd64                                   install
libfile-fcntllock-perl                          install
libfreetype6:amd64                              install
libfribidi0:amd64                               install
libfuse2:amd64                                  install
libgcc-5-dev:amd64                              install
libgcc1:amd64                                   install
libgcrypt20:amd64                               install
libgdbm3:amd64                                  install
libgeoip1:amd64                                 install
libgirepository-1.0-1:amd64                     install
libglib2.0-0:amd64                              install
libglib2.0-data                                 install
libgmp10:amd64                                  install
libgnutls-openssl27:amd64                       install
libgnutls30:amd64                               install
libgomp1:amd64                                  install
libgpg-error0:amd64                             install
libgpm2:amd64                                   install
libgssapi-krb5-2:amd64                          install
libgssapi3-heimdal:amd64                        install
libhcrypto4-heimdal:amd64                       install
libheimbase1-heimdal:amd64                      install
libheimntlm0-heimdal:amd64                      install
libhogweed4:amd64                               install
libhx509-5-heimdal:amd64                        install
libicu55:amd64                                  install
libidn11:amd64                                  install
libisc-export160                                install
libisc160:amd64                                 install
libisccc140:amd64                               install
libisccfg140:amd64                              install
libisl15:amd64                                  install
libitm1:amd64                                   install
libjson-c2:amd64                                install
libk5crypto3:amd64                              install
libkeyutils1:amd64                              install
libklibc                                        install
libkmod2:amd64                                  install
libkrb5-26-heimdal:amd64                        install
libkrb5-3:amd64                                 install
libkrb5support0:amd64                           install
libldap-2.4-2:amd64                             install
liblocale-gettext-perl                          install
liblsan0:amd64                                  install
liblvm2app2.2:amd64                             install
liblvm2cmd2.02:amd64                            install
liblwres141:amd64                               install
liblxc1                                         install
liblz4-1:amd64                                  install
liblzma5:amd64                                  install
liblzo2-2:amd64                                 install
libmagic1:amd64                                 install
libmnl0:amd64                                   install
libmount1:amd64                                 install
libmpc3:amd64                                   install
libmpdec2:amd64                                 install
libmpfr4:amd64                                  install
libmpx0:amd64                                   install
libmspack0:amd64                                install
libncurses5:amd64                               install
libncursesw5:amd64                              install
libnetfilter-conntrack3:amd64                   install
libnettle6:amd64                                install
libnewt0.52:amd64                               install
libnfnetlink0:amd64                             install
libnih1:amd64                                   install
libnuma1:amd64                                  install
libopts25:amd64                                 install
libp11-kit0:amd64                               install
libpam-modules:amd64                            install
libpam-modules-bin                              install
libpam-runtime                                  install
libpam-systemd:amd64                            install
libpam0g:amd64                                  install
libparted2:amd64                                install
libpcap0.8:amd64                                install
libpci3:amd64                                   install
libpcre3:amd64                                  install
libperl5.22:amd64                               install
libpipeline1:amd64                              install
libplymouth4:amd64                              install
libpng12-0:amd64                                install
libpolkit-agent-1-0:amd64                       install
libpolkit-backend-1-0:amd64                     install
libpolkit-gobject-1-0:amd64                     install
libpopt0:amd64                                  install
libprocps4:amd64                                install
libpython-stdlib:amd64                          install
libpython2.7-minimal:amd64                      install
libpython2.7-stdlib:amd64                       install
libpython3-dev:amd64                            install
libpython3-stdlib:amd64                         install
libpython3.5:amd64                              install
libpython3.5-dev:amd64                          install
libpython3.5-minimal:amd64                      install
libpython3.5-stdlib:amd64                       install
libquadmath0:amd64                              install
libreadline5:amd64                              install
libreadline6:amd64                              install
libroken18-heimdal:amd64                        install
librtmp1:amd64                                  install
libsasl2-2:amd64                                install
libsasl2-modules:amd64                          install
libsasl2-modules-db:amd64                       install
libseccomp2:amd64                               install
libselinux1:amd64                               install
libsemanage-common                              install
libsemanage1:amd64                              install
libsepol1:amd64                                 install
libsigsegv2:amd64                               install
libslang2:amd64                                 install
libsmartcols1:amd64                             install
libsqlite3-0:amd64                              install
libss2:amd64                                    install
libssl-dev:amd64                                install
libssl-doc                                      install
libssl1.0.0:amd64                               install
libstdc++-5-dev:amd64                           install
libstdc++6:amd64                                install
libsystemd0:amd64                               install
libtasn1-6:amd64                                install
libtext-charwidth-perl                          install
libtext-iconv-perl                              install
libtext-wrapi18n-perl                           install
libtinfo5:amd64                                 install
libtsan0:amd64                                  install
libubsan0:amd64                                 install
libudev1:amd64                                  install
libusb-0.1-4:amd64                              install
libusb-1.0-0:amd64                              install
libustr-1.0-1:amd64                             install
libutempter0:amd64                              install
libuuid1:amd64                                  install
libwind0-heimdal:amd64                          install
libwrap0:amd64                                  install
libx11-6:amd64                                  install
libx11-data                                     install
libxau6:amd64                                   install
libxcb1:amd64                                   install
libxdmcp6:amd64                                 install
libxext6:amd64                                  install
libxml2:amd64                                   install
libxmuu1:amd64                                  install
libxtables11:amd64                              install
libyaml-0-2:amd64                               install
linux-base                                      install
linux-gcp                                       install
linux-gcp-headers-4.13.0-1006                   install
linux-headers-4.13.0-1006-gcp                   install
linux-headers-gcp                               install
linux-image-4.13.0-1006-gcp                     install
linux-image-gcp                                 install
linux-libc-dev:amd64                            install
locales                                         install
login                                           install
logrotate                                       install
lsb-base                                        install
lsb-release                                     install
lshw                                            install
lsof                                            install
ltrace                                          install
lvm2                                            install
lxc-common                                      install
lxcfs                                           install
lxd                                             install
lxd-client                                      install
make                                            install
makedev                                         install
man-db                                          install
manpages                                        install
manpages-dev                                    install
mawk                                            install
mdadm                                           install
mime-support                                    install
mlocate                                         install
mount                                           install
mtr-tiny                                        install
multiarch-support                               install
nano                                            install
ncurses-base                                    install
ncurses-bin                                     install
ncurses-term                                    install
net-tools                                       install
netbase                                         install
netcat-openbsd                                  install
ntfs-3g                                         install
ntp                                             install
open-iscsi                                      install
open-vm-tools                                   install
openssh-client                                  install
openssh-server                                  install
openssh-sftp-server                             install
openssl                                         install
os-prober                                       install
overlayroot                                     install
parted                                          install
passwd                                          install
pastebinit                                      install
patch                                           install
pciutils                                        install
perl                                            install
perl-base                                       install
perl-modules-5.22                               install
plymouth                                        install
plymouth-theme-ubuntu-text                      install
policykit-1                                     install
pollinate                                       install
popularity-contest                              install
powermgmt-base                                  install
procps                                          install
psmisc                                          install
python                                          install
python-apt-common                               install
python-boto                                     install
python-chardet                                  install
python-crcmod                                   install
python-google-compute-engine                    install
python-minimal                                  install
python-pip-whl                                  install
python-pkg-resources                            install
python-requests                                 install
python-six                                      install
python-urllib3                                  install
python2.7                                       install
python2.7-minimal                               install
python3                                         install
python3-apport                                  install
python3-apt                                     install
python3-blinker                                 install
python3-boto                                    install
python3-cffi-backend                            install
python3-chardet                                 install
python3-commandnotfound                         install
python3-configobj                               install
python3-cryptography                            install
python3-dbus                                    install
python3-debian                                  install
python3-dev                                     install
python3-distupgrade                             install
python3-gdbm:amd64                              install
python3-gi                                      install
python3-google-compute-engine                   install
python3-idna                                    install
python3-jinja2                                  install
python3-json-pointer                            install
python3-jsonpatch                               install
python3-jwt                                     install
python3-markupsafe                              install
python3-minimal                                 install
python3-newt                                    install
python3-oauthlib                                install
python3-pip                                     install
python3-pkg-resources                           install
python3-prettytable                             install
python3-problem-report                          install
python3-pyasn1                                  install
python3-pycurl                                  install
python3-requests                                install
python3-serial                                  install
python3-setuptools                              install
python3-six                                     install
python3-software-properties                     install
python3-systemd                                 install
python3-update-manager                          install
python3-urllib3                                 install
python3-venv                                    install
python3-wheel                                   install
python3-yaml                                    install
python3.5                                       install
python3.5-dev                                   install
python3.5-minimal                               install
python3.5-venv                                  install
readline-common                                 install
rename                                          install
resolvconf                                      install
rsync                                           install
rsyslog                                         install
run-one                                         install
screen                                          install
sed                                             install
sensible-utils                                  install
sgml-base                                       install
shared-mime-info                                install
snapd                                           install
software-properties-common                      install
sosreport                                       install
squashfs-tools                                  install
ssh-import-id                                   install
sshguard                                        install
strace                                          install
sudo                                            install
systemd                                         install
systemd-sysv                                    install
sysv-rc                                         install
sysvinit-utils                                  install
tar                                             install
tcpd                                            install
tcpdump                                         install
telnet                                          install
time                                            install
tmux                                            install
tzdata                                          install
ubuntu-cloudimage-keyring                       install
ubuntu-core-launcher                            install
ubuntu-keyring                                  install
ubuntu-minimal                                  install
ubuntu-release-upgrader-core                    install
ubuntu-standard                                 install
ucf                                             install
udev                                            install
ufw                                             install
uidmap                                          install
unattended-upgrades                             install
update-manager-core                             install
update-notifier-common                          install
ureadahead                                      install
usbutils                                        install
util-linux                                      install
uuid-runtime                                    install
vim                                             install
vim-common                                      install
vim-runtime                                     install
vim-tiny                                        install
vlan                                            install
wget                                            install
whiptail                                        install
xauth                                           install
xdg-user-dirs                                   install
xfsprogs                                        install
xkb-data                                        install
xml-core                                        install
xz-utils                                        install
zerofree                                        install
zlib1g:amd64                                    install
zlib1g-dev:amd64                                install

**Comment by artygrand** [comment]
+1 for this error now

**Comment by triyangle** [comment]
Getting same issue using Anaconda distribution on macOS 10.13.2 and as well as for ipython. Maybe related to https://github.com/ipython/ipython/issues/10981?

**Comment by YairMazor** [comment]
+1 experiencing the same error on Ubuntu.
Stack trace comes from /traitlets/config/application.py, line 291.

**Comment by takluyver** [comment]
Yup, looks like the same as ipython/ipython#10981. A dependency broke something. We'll try to have it fixed soon, but in the meantime you'll want to install an older version of the `decorator` package.

**Comment by takluyver** [comment]
Aha, it turns out this was broken by decorator 4.2.0, but fixed again in decorator 4.2.1. So it should be OK again now.
