### ISSUE TITLE
Copy/Paste between notebooks gets stuck at "Press Ctrl-V again to paste" message

### ISSUE THREAD

**Issue by mojones** [jupyter/notebook#3214]
Apologies if this is a double, I've seen a bunch of other similar issues but not this exact one. I'm trying to copy/paste cells from one notebook to another, which I believe is supported on version 5. I highlight the cells in the "from" notebook, hit ctrl+c, then switch to the destination notebook and hit ctrl+v. I get this popup:

![selection_001](https://user-images.githubusercontent.com/893512/34992020-9bb8e26c-fac3-11e7-9562-556a20ec757d.png)

Hitting ctrl+v again at this point has no effect. The only action I can take is to hit "cancel" and close the popup. 

Versions information below:

```
Server Information:

You are using Jupyter notebook.

The version of the notebook server is: 5.2.2
The server is running on this version of Python:

Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

Current Kernel Information:

Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
```

Any suggestions on how I could go about debugging this problem would be appreciated; I'm using jupyter for teaching and this would be a massive help to me when putting together material with jupyter.

**Comment by takluyver** [comment]
Are there any errors in the JS console after you press Ctrl-V the second time?

**Comment by mojones** [comment]
No, no error messages in the console after pressing the second etc. times. 

I just noticed while checking, that this behaviour also occurs when copying and pasting within the same jupyter notebook. So let me know if I should edit the issue title to reflect that.

**Comment by takluyver** [comment]
If you're using Ctrl-C/V, it's the same code running whether you copy between notebooks or within one notebook. The toolbar buttons use a separate copy/paste mechanism which only works within a notebook.

**Comment by takluyver** [comment]
What browser are you using, and does it work if you try a different one?

**Comment by mojones** [comment]
This is on Firefox 57.0.4 (64-bit). I've just tried on Chromium and copy-paste works fine both within and between notebooks.

**Comment by takluyver** [comment]
It's working for me on Firefox. Do you have any extensions or custom configuration? Either for Jupyter or for Firefox?

**Comment by mojones** [comment]
I have lastpass and ublock extensions for firefox, but have just tried again with both disabled and no change. The only custom configuration I have for jupyter is some css.

**Comment by takluyver** [comment]
Sorry, I'm out of ideas for now. You can see the code that produces that dialog here:

https://github.com/jupyter/notebook/blob/fe2502d81ee7563f463a9c769632747df9ebbf1b/notebook/static/notebook/js/clipboard.js#L98

**Comment by mojones** [comment]
Ah, just figured it out - I had this setting in my `about:config` changed:

`dom.event.clipboardevents.enabled;false`

to force enable pasting passwords in websites that normally disable it, and this was preventing copy+paste from working. Changing it back to true allows it to work. So I guess that the work around will probably involve me setting up a separate firefox profile for working with jupyter notebooks. Thanks for helping me track this down!

**Comment by takluyver** [comment]
Aha! Thanks for posting what it was, that might help someone else if they encounter the same issue.

**Comment by EricThomson** [comment]
dom.event.clipboardevents.enabled is set to true for me and I still get this  popup in firefox.
