### ISSUE TITLE
Notebook cannot connect to kernel

### ISSUE THREAD

**Issue by JudSchneider** [jupyter/notebook#322]
I seem to be having an issue connecting to the jupyter notebook kernel.  I am running jupyter on a local vagrant centos VM and other webapps connect fine.  I can start the server, load the home screen, however, when I start a notebook, any of which have run perfectly fine before a couple of days ago, the kernel will not connect to the notebook.  I get the following messages in chrome's debugger about javascript resources:

```
[I 14:03:21.940 NotebookApp] Kernel started: 811c8162-8043-45c3-8bbf-d4df80f372bc
[W 14:03:53.473 NotebookApp] 404 GET /static/components/underscore/underscore-min.map (10.0.2.2) 1.98ms referer=None
[W 14:03:53.478 NotebookApp] 404 GET /static/components/backbone/backbone-min.map (10.0.2.2) 1.98ms referer=None
```

Furthermore, the notebook loads, just never connects to the kernel.  The websocket tries to connect several times but times out.

The python kernel I am using is 2.7 and works fine on the vm.

**Comment by Carreau** [comment]
hum, the missing `.min.map` files are ok, and are not errors, they are fetched y chrome that assume you want to debug the JS files when you open the dev tools. 

Also the error you pasted seem to be the one from the terminal, not the chrome dev tools.
It look like something preventing websocket connexion, but not sur why.

**Comment by JudSchneider** [comment]
yes, you are right the error is from the terminal, sorry about that.  there dont seem to be any port conflicts with 8888.  I was getting this terminal error for a while:

```[E 13:38:31.501 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/tornado/http1connection.py", line 691, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 810, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/lib64/python2.7/site-packages/tornado/http1connection.py", line 166, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol
```

However, that went away after I upgraded tornado.

**Comment by JudSchneider** [comment]
Just to update.  I ended up refreshing some libraries on the vm and that seems to have solved the issue.  unclear why it was caused in the first place but now it works again.  Thanks
