### ISSUE TITLE
I can't get into Jupyter

### ISSUE THREAD

**Issue by arian-siddiqi** [jupyter/notebook#3231]
I was asked for a Token, after reading some of the problem, similar to mine, people had. I pasted the link I got in the terminal into a different browser and set up my password. Now, I still have the problem of not able to run Jupyter and don't see the link in my terminal which pops up every time I run Jupyter.

**Comment by arian-siddiqi** [comment]
<img width="882" alt="screenshot 2018-01-17 21 14 32" src="https://user-images.githubusercontent.com/22612350/35067377-9a082398-fbcb-11e7-9462-d470ab411821.png">

This is the screenshot of my terminal after running Jupyter.

**Comment by takluyver** [comment]
What version of the `notebook` package have you got? Did you configure a password? If you've set a password, then put that in when it asks for a token.

**Comment by arian-siddiqi** [comment]
the version of the notebook is 5.0.0. Yes, in the terminal I was asked to give a password and I did, but now neither do I get the token link nor asks for a token, as you can see in the screenshot above that is all I get.

**Comment by takluyver** [comment]
Does it not open a browser page for you? If not, open your browser and go to the address it shows in the terminal - then it should ask you for your password.

**Comment by arian-siddiqi** [comment]
Yes, it does open a browser where there is a list of my folders and applications including anaconda, but not asks for my password.

**Comment by takluyver** [comment]
Oh, that sounds like it's working! The page in your browser should have a 'New' button. Click that, and click the option for a new Python notebook.

**Comment by arian-siddiqi** [comment]
Thank you very much!!! It is working now for me as I could not work out to click the 'New' button.

**Comment by takluyver** [comment]
No problem. We have been meaning to make creating a new notebook more obvious.
