### ISSUE TITLE
Jupyter notebook will not launch after upgrade to version 5.3.1

### ISSUE THREAD

**Issue by djross2222** [jupyter/notebook#3242]
After upgrading Jupyter notebook to version 5.3.1, it will not launch.

I'm using a Windows 7 PC, with Jupyter notebook installed as part of Anaconda (version 1.6.12)

Jupyter notebook will not launch from either Anaconda Navigator or from the command line.
In either case, it produces the same error message:
    Traceback (most recent call last):
        File "C:\Users\djross\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
            from notebook.notebookapp import main
        File "C:\Users\djross\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in 
            from .nbextensions import install_nbextension
        File "C:\Users\djross\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 27, in 
            from jupyter_core.utils import ensure_dir_exists
    ImportError: cannot import name 'ensure_dir_exists'

**Comment by takluyver** [comment]
Update the package `jupyter_core` as well.

The conda packaging is being fixed: https://github.com/conda-forge/notebook-feedstock/pull/27

**Comment by gnestor** [comment]
Did this resolve your issue, @djross2222?

**Comment by djross2222** [comment]
Yes, that solved the issue.

Thanks-

**Comment by OscarSouth** [comment]
I followed the instruction and have fully updated Anaconda and all parts of jupyter (according to the info on this in various places) and am still getting the same problem.  Is there any action I can take to get jupyter back into a usable state?

**Comment by takluyver** [comment]
If you're still seeing that error, it means it's importing an older version of `jupyter_core`. You need to ensure it can load version 4.4.

**Comment by OscarSouth** [comment]
Thanks for the quick reply.  Here are my jupyter versions:

![image](https://user-images.githubusercontent.com/32574713/36038164-da3ca63a-0db6-11e8-973b-d04e29d06a7e.png)

And attempting to run:

![image](https://user-images.githubusercontent.com/32574713/36038223-004acfbe-0db7-11e8-92b4-0c8659edb550.png)

**Comment by OscarSouth** [comment]
Ah thanks very much, I didn’t realise this.  I’ll tey it when I get home later.

**Comment by Scoodood** [comment]
Hi @takluyver, I am having the same issue, here is my traceback, 
![screen shot 2018-03-02 at 10 14 50 am](https://user-images.githubusercontent.com/15989924/36914552-936ad694-1e02-11e8-9c11-fa8b333c6e2c.png)

But my lib folder was somehow installed under the `anaconda3` folder. 
Should I just delete it like this?
`rm -rf /Users/JC/anaconda3/lib`

**Comment by takluyver** [comment]
It shouldn't be necessary to delete that directory (and you'll probably need to reinstall Anaconda if you do). Try upgrading jupyter_core.

**Comment by sachindeshpande** [comment]
Not sure if the issue is open. Would like to share the root cause in my case.
This was occurring for me because I installed Anaconda for "all users". After installing for the active user only the problem did not occur again (Not sure why that is the case)
