### ISSUE TITLE
Just ran "conda upgrade notebook" to get .5.3.1 now notebook won't start

### ISSUE THREAD

**Issue by dartdog** [jupyter/notebook#3247]
Running anaconda (Ubunti 16.04) of course, but have been using for some time so there may be some accumulated cruft?

Got no error on the upgrade but get this now when trying to run notebook so I'm stuck!
Some sort of config issue?
Help appreciated!

tom@tomServal:~$ jupyter notebook
Traceback (most recent call last):
  File "/home/tom/anaconda3/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/home/tom/anaconda3/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/tom/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

**Comment by dartdog** [comment]
Since this is my primary dev environment I'd be happy a bit of guidance on just replacing the whole install within conda? So I can get back to work? I tried conda install jupyter with no effect..

**Comment by sarmoho** [comment]
Try to force to install notebook to the previous version
 ` conda install notebook=5.0.0`

The version come from this link [(https://docs.anaconda.com/anaconda/packages/py3.6_linux-64)]

**Comment by dartdog** [comment]
Further discussion and details:
if you want to see in google groups https://groups.google.com/d/topic/jupyter/4_FJmLWBbmI/discussion

**Comment by dartdog** [comment]
Going to hold off a bit on trying to downgrade, afraid that could complicate things as it seems now configuration rather than code?

**Comment by takluyver** [comment]
The original error should be fixed in the latest conda-forge package: https://github.com/conda-forge/notebook-feedstock/pull/27 

Mac packages may lag the other platforms a bit, because the builds get stuck in a queue:
https://travis-ci.org/conda-forge/notebook-feedstock/builds

**Comment by gnestor** [comment]
Yes, it sounds like your jupyter_core and/or jupyter_client need to be updated: `conda update jupyter_core jupyter_client` or `pip install jupyter_core jupyter_client --upgrade`.

Let us know if that resolves your issue, @dartdog 👍

**Comment by dartdog** [comment]
There is still one more issue related to the NB conda kernels... @minrk has it in hand...
