### ISSUE TITLE
v5.3.1 keeps creating notebooks at toplevel dir (notebook_dir) regardless of location.

### ISSUE THREAD

**Issue by draperjames** [jupyter/notebook#3248]
I've seen this problem manifest on Linux Mint 18.3, Windows 7 and Windows 10 running FireFox 57.0.4 (64-bit). 

When I start Jupyter Notebook my browser launches to http://localhost:8888/tree then I navigate to a subdir let's call it `my_notebooks` when I the `New` button and select the type of notebook I want the notebook is created back at the toplevel dir http://localhost:8888/tree. 

This might not be connected but I noticed that the [changelog](https://github.com/jupyter/notebook/blob/4179d60e4912f6badd4ac34927edc7d47bb862aa/docs/source/changelog.rst#id10) 
 has this line:
> - Use DOM History API for navigating between directories in the file browser (:ghpull:`3115`).

I have Firefox's privacy settings set to never remember history. Would that break the new navigation method?

**Comment by sarmoho** [comment]
I have the same problem in chrome with Windows10  since `conda update notebook --update-dependencies` from defaul notebook version of Anaconda3(notebook v5.0.0)

**Comment by draperjames** [comment]
@sarmoho I find that down-grading to v5.2.1 fixes the problem right away. I think that I use the following commands from a administrator prompt;

    conda uninstall notebook
    pip install notebook==5.2.1

**Comment by takluyver** [comment]
You were quite right about PR #3115 being the culprit, but the issue is there even with the default browser settings. #3263 should fix it.
