### ISSUE TITLE
Feature request: Token based-api endpoint authorization

### ISSUE THREAD

**Issue by episodeyang** [jupyter/notebook#325]
I am writing an iPython client for my lab that allows people to share ipython notebooks as part of a rich text editor and work on them together. Since the server will be hosted on a separate domain, and all the users will connect to the server via a uri, the cookie-based authentication won't work.

I have looked through the issues and PRs. What is the status on the PAM? patching the code is relatively easy, but since this would be needed by any third-party client, it might make sense to have a repo for a token-based PAM that could be configured in the profile_config.py file.

The docker repo is awesome btw!

Ge

---------------- Careu's comment pasted below from [#8765](https://github.com/ipython/ipython/issues/8765) --------------------------
I think you might want to open that on jupyter/notebook repo as IPython is now only purely the python-kernel part.

That being said, if you have a patch for the code that would allow easier configuration, and if it's already written please send a PR.

though in a multi-user context I think you want to authenticate with https://github.com/jupyter/jupyterhub not with Notebook, as hub deals with multi-user.

**Comment by minrk** [comment]
We don't have any plans to integrate PAM into the single-user notebook, though you can do it with external code and some custom authentication hooks. We should improve the documentation coverage of custom login logic.

**Comment by episodeyang** [comment]
Hi Minrk, 

Is it possible to update the current cookie based authentication to a token based authentication mechanism? This way the problem of cross-domain authentication would be completely solved.

**Comment by minrk** [comment]
We could add it, sure. Of course we couldn't entirely replace cookie auth with token auth, except on API endpoints.

**Comment by episodeyang** [comment]
Thanks @minrk! So you are saying that you would add token auth along side of cookie auth, and make this configurable?

I finished my real-time collaborative jupiter client! Right now I am making some demo videos to explain what you can do with it, since the design is very different from coLab and jupyter so it needs some explanation to go with it.

**Comment by minrk** [comment]
Yes, I think we should add token auth to the notebook, and use it on API endpoints (perhaps exclusively). We still need cookie auth to get the pages to the browser, but I don't think we need it on the API endpoints.

**Comment by episodeyang** [comment]
So with that I should be able to `POST` to `/api/kernels/:kernelId/ `, `/api/sessions/` , and initiate the web socket connection on `/api/channels/:kernelId` right?

**Comment by minrk** [comment]
yes.

**Comment by episodeyang** [comment]
got it, Thanks!

**Comment by rgbkrk** [comment]
Approach for this is in #1831 by the way @episodeyang.

**Comment by damianavila** [comment]
#1831 was merged, I guess this one could be closed, thoughts?
