### ISSUE TITLE
update to mathjax 2.7.2

### ISSUE THREAD

**Issue by mbakker7** [jupyter/notebook#3250]
Is there a way to update to mathjax 2.7.2 (or higher).
Version 2.7.1 (and before, I don't know how far before) has a problem with putting a vector or tilde on top of a symbol in Safari. This is reportedly fixed in 2.7.2.

**Comment by takluyver** [comment]
I think it needs to be updated in this repository: https://github.com/components/MathJax

And then in this file: https://github.com/jupyter/notebook/blob/master/bower.json

**Comment by harrywang** [comment]
Hope this can be done soon. I am having the same issue as @mbakker7 stated in https://github.com/mathjax/MathJax/issues/1913

**Comment by mbakker7** [comment]
Is this really fixed?
And if so, what do I need to do to get it to work?
Is Jupyter now based on mathjax 2.7.2?
The link also suggests it is a Safari problem. Has it been fixed in Safari?

**Comment by goerz** [comment]
Is there currently a way to make jupyter use either the Mathjax CDN, or a locally installed version, as a workaround?

I'm also suffering from unreadable equations, and trying to use the SVG renderer results in `[Math Processing Error]` (which hopefully would also be fixed by updating mathjax)

**Comment by goerz** [comment]
So I figured out how to use a local MathJax installation, based on the comments on other issues (see https://github.com/jupyter/notebook/issues/2607#issuecomment-401140786).

That seems to solve the issue with the broken hats and tildes on Safari 11.1.1, but not in the Fluid app (https://fluidapp.com) that I use as a wrapper, which reports to be Safari 10.0.1

At least the SVG renderer now works, though, and that renders the accents correctly (Actually, I find the SVG rendering infinitely superior to the HTML/CSS in all cases, so I'm not sure why SVG isn't the default)

**Comment by mgeier** [comment]
It looks like currently version `^2.7.4` is used:

https://github.com/jupyter/notebook/blob/4b2e849e83fcf9ffbe0755d38d635e34e56a4fea/bower.json#L18

So I guess this issue can be closed?

**Comment by Zsailer** [comment]
Thanks, @mgeier. :+1: Closing.
