### ISSUE TITLE
Notebook doesn't respond if I try to use 'Raw nbconvert' cell type + cell toolbar

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/notebook#3255]
Notebook version: 5.3.1

How to reproduce:

1. Set an empty cell's type to 'Raw NBConvert' from the menu
2. Show raw cell format with 'View -> Cell Toolbar -> Raw Cell Format'
3. Select 'custom' in the cell toolbar

This makes a black overlay across the entire notebook, like a modal is going to open. But a modal never opens, and the notebook UI is inaccessible. I need to refresh page to fix this.

**Comment by onnodb** [comment]
I also observed this issue today, both in version 6.0.3 and in the current master. As far as I can see, the issue is with the underlying JavaScript code. I've submitted a PR that addresses the issue, see jupyter/notebook#5385.
