### ISSUE TITLE
Dead kernel with python virtual environment

### ISSUE THREAD

**Issue by whitecoffee** [jupyter/notebook#3257]
I work with ubuntu 16.04 which contains python 3.5 & python 2.7 naturally. 
Inside the python package I create a virtual environment (named env)  and install the jupyter in my env.
But I got dead kernel (the kernel named python3) in browser.

I type the `which python3` and got `/home/my_name/package_name/env/bin/python3`
ANYONE has an idea to fix it???

**Comment by takluyver** [comment]
When this happens, is there any error message in the terminal where you launched the notebook?

**Comment by whitecoffee** [comment]
All right, I fix it with code `ipython kernel install --user`
Thanks for your attention @takluyver
