### ISSUE TITLE
creating new notebook files not respecting current directory location unless browser refresh

### ISSUE THREAD

**Issue by steverweber** [jupyter/notebook#3263]
```
# ubuntu 17.10
python3 -m pip install --upgrade notebook
jupyter-notebook --version
5.3.1
```

after login im in my home directory '/tree'

- use [new] > folder  "foo"
- click on folder "foo"
- click [new] > 'notebook' lets use python.. any notebook would work for this example

the new untitled notebook opens .. but discover it's not in the folder "foo" its in the root of my home directory.

If i repeat this process but use [new] > 'text file' the correct directory is used,

To workaround the issue
- use [new] > folder  "foobar"
- click on folder "foobar"
- refresh the browser F5
- creating a new notebook file now goes into the correct directory.

**Comment by takluyver** [comment]
I can reproduce this, working on a PR.

**Comment by gnestor** [comment]
Similar: https://github.com/jupyter/notebook/issues/3248

**Comment by sargense** [comment]
Ticket should be reopened. Still experiencing this issue on 5.3.0

**Comment by Linlinzhao** [comment]
I am having the same issue on 5.3.0 on Manjaro

**Comment by gnestor** [comment]
Please upgrade to notebook 5.6.0
