### ISSUE TITLE
Can't create new python 2.7 kernel in sub-directory

### ISSUE THREAD

**Issue by lopolipop** [jupyter/notebook#3266]
I can't create new python 2.7 kernel in sub-directory. It always create at working directory only.

Describe problems encountered.
https://giphy.com/gifs/xUOwFUOIENq7vTNgkw/fullscreen

**Comment by lopolipop** [comment]
Okay. I found solution right now.

conda uninstall notebook
pip install notebook==5.2.1 

but why conda have this problem?

**Comment by takluyver** [comment]
Should be fixed by #3264.
