### ISSUE TITLE
Feature request: education mode that supress all automatic outputs

### ISSUE THREAD

**Issue by ischurov** [jupyter/notebook#3270]
The request: add a possibility to turn on special "education mode" that disables automatic printing of the last expression in the cell.

### Rationale

I do a lot of teaching using Jupyter. It is great environment for education. However, one feature, which is very useful for production use, is really bad in education: automatic output printing.

At the very beginning of Python lessons we study data types, variables and so on. So it is natural to do something like.

```
[In]: x = 5
      y = x + 1
[In]: y
[Out]: 6
```

We also study `print` function and do something like

```
[In]: x = 5
      y = x + 1 
      print("x =", x)
      print("y =", y)
      
      x = 5
      y = 6
```

After that, we usually study functions, and here our problems begin. Consider the following example.

```
[In]
def print_xsquare(x):
    print(x ** 2)
def return_xsquare(x):
    return x ** 2
[In]
print_xsquare(4)
16
[In]
return_xsquare(4)
[Out]: 16
```
<img width="265" alt="Screenshot with the code written above" src="https://user-images.githubusercontent.com/2717321/35476207-3f1eac96-03bd-11e8-9ee8-7da2534f4b20.png">

The students become confused: there is a lot of misundestanding on the difference between these two examples. As the visible outputs of functions `print_xsquare` and `return_xsquare` are so similar in Jupyter (you have to notice small `[Out]` word to get the difference), and the concept of function is new to most of my students, they tend to believe that `print` and `return` are somewhat similar operations. And it demands lot of efforts to explain the difference.

It happens every single time we teach functions. So I finally come to conclusion that it is better to temporary turn off automatic outputting in Jupyter at the beginning of the the course and activate it only when functions, return values, values of expressions and so on are well understood.

So I'm asking for this feature and I belive it will be useful for all of us, who teach Python to novices in software programming with Jupyter.

**Comment by dsblank** [comment]
It is already an option. You can set this in a cell:

```python
%config ZMQInteractiveShell.ast_node_interactivity = "none"
```
or in a config file. The values are 'all', 'last', 'last_expr', 'none', or 'last_expr_or_assign'

The last one may not be released yet. Note that I do teach intro students, and I find that little "Out[]" is adequate for making this important distinction.

**Comment by ischurov** [comment]
@dsblank Cool, thanks! I'll close it.
