### ISSUE TITLE
Cmd/Ctrl clicking folders no longer opens in new tabs in 5.3

### ISSUE THREAD

**Issue by parente** [jupyter/notebook#3276]
Instead, the file browser navigates to the folder in the current browser pane.

Probably related to the new history navigation feature. JS might be eating the hotkey modifier preventing the default browser behavior.

**Comment by takluyver** [comment]
Oh, I hadn't checked that because I use middle click to open in a new tab. I think you're right about the cause.

**Comment by parente** [comment]
No worries. One of our users caught it after we rolled it out internally.

**Comment by takluyver** [comment]
Want to do a PR? The handler is here:

https://github.com/jupyter/notebook/blob/3de5e501f3f1eb16d89830b658d03b9c3e1a4c8b/notebook/static/tree/js/notebooklist.js#L836

And we should probably do the same with the breadcrumb handlers:

https://github.com/jupyter/notebook/blob/3de5e501f3f1eb16d89830b658d03b9c3e1a4c8b/notebook/static/tree/js/notebooklist.js#L367-L391

**Comment by parente** [comment]
I was planning to dig into it tomorrow evening. If someone else gets to it before me, no worries.
