### ISSUE TITLE
Folder Name does not change HTML title until refresh of folder's page (in 5.3)

### ISSUE THREAD

**Issue by msheffey** [jupyter/notebook#3277]
HTML title is only updated to be the folder name when the page is refreshed, not when originally navigating to the folder's page.

After clicking on a folder:  
![image](https://user-images.githubusercontent.com/5440274/35528463-e53e7702-04fb-11e8-8699-830636600ae5.png)

Then, refreshing that page:
![image](https://user-images.githubusercontent.com/5440274/35528566-41a7bc1a-04fc-11e8-8eb7-b337311e104d.png)

**Comment by takluyver** [comment]
Thanks! The code for that is here:

https://github.com/jupyter/notebook/blob/3de5e501f3f1eb16d89830b658d03b9c3e1a4c8b/notebook/static/tree/js/notebooklist.js#L402-L407
