### ISSUE TITLE
ImportError when import module in the same folder

### ISSUE THREAD

**Issue by Hclmaster** [jupyter/notebook#3281]
Hi, I meet a trouble that is very strange, I want to import a module called data_prep, and the data_prep code was put in the same folder with the code that I run.
![image](https://user-images.githubusercontent.com/16880879/35601117-547320a2-066c-11e8-82da-19b45443d173.png)
![image](https://user-images.githubusercontent.com/16880879/35601127-633c0f36-066c-11e8-9fea-9621678801b2.png)

The data_prep code works fine.
![image](https://user-images.githubusercontent.com/16880879/35601143-728e4dd2-066c-11e8-806c-80dee70becd5.png)

But when I want to import this code, it gives me the error as follows:
![image](https://user-images.githubusercontent.com/16880879/35601160-8651a6a2-066c-11e8-90e9-2b2b45d3daf4.png)

Can you please help me why this was happening, it seems I had tried several methods, but won't work for me. And thank you very much.

**Comment by takluyver** [comment]
Notebooks are not normally importable modules - you should put code in a `.py` file if you want to use it as a module.

There is an [experimental tool](https://pypi.python.org/pypi/ipynb) that lets you import a notebook, but we don't currently recommend that as a standard way of working.

**Comment by dsblank** [comment]
I think you can do what you want by simply changing your "import data_prep" to "%run data_prep.ipynb". That will "run" the notebook, which is the same thing as importing in this context, I believe.
