### ISSUE TITLE
notebook corrupted after ssh connection lost

### ISSUE THREAD

**Issue by dejmail** [jupyter/notebook#3285]
Hi everyone

I'm a bit mystified by the loss of a fairly large workbook. I was running a Jupyter frontend in Chrome (Linux) through a ssh connection using port forwarding on my local host. The ssh connection was through a VPN. The connection to the jupyter server, which was running in browserless mode was lost. It was running in the foreground , which has happened in the past without incident.

This time however the entire notebook was lost i.e. it went from roughly 400kb to 0kb in size.

Any ideas as to why this might have happened? What did I do wrong?

On the screenshot are the messages I received which don't reveal much I'm afraid.

![screenshot](https://user-images.githubusercontent.com/1876487/35629891-12618f12-06a0-11e8-8039-cb4d367deffe.png)

**Comment by takluyver** [comment]
It doesn't sound like you're doing anything wrong.

Is the directory where you saved it on NFS, or synced by something like Dropbox? If the problem recurs, you could try setting `FileManagerMixin.use_atomic_writing = False` in config.

If you need to recover the file, there may be a copy saved with a `.~` prefix (this is made as part of the 'atomic' saving), or a copy in the `.ipynb_checkpoints` folder from an earlier save.

**Comment by dejmail** [comment]
The directory is on a CentOS machine, and has no Dropbox connection. I'll try your suggestions in future if it happens again. 

Yes, I forgot to update my issue, I managed to recover it from both of the files that you suggest. Thanks for getting back to me, I realise the issue is rather random.
