### ISSUE TITLE
Is checking links on Travis too aggressive?

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#3292]
We recently adding to Travis a job that builds the docs, so we can be sure they build without errors. This includes a check of links in the docs.

Our docs have a lot of links, and they may break for reasons unrelated to any pull request - e.g. we link to the Github account of every contributor, and someone appears to have just deleted their account, so every Travis build will fail. It doesn't seem reasonable for all other development to be disrupted until we go and remove the link.

I think doing the link check is still useful, but maybe we could do it in a separate daily/weekly build, rather than on every PR.

**Comment by damianavila** [comment]
> I think doing the link check is still useful, but maybe we could do it in a separate daily/weekly build, rather than on every PR.

Sound like a good idea to decouple things.

**Comment by takluyver** [comment]
I think this could be done using a [Travis Cron job](https://docs.travis-ci.com/user/cron-jobs/). One of us will need to configure Travis to run something weekly, but someone else could check the environment variable in the Travis config.

**Comment by ashleytqy** [comment]
Hi! Can I try to work on this?

**Comment by takluyver** [comment]
Please do! Are you clear on what is involved?

**Comment by ashleytqy** [comment]
@takluyver is it right to say that i have to make changed to the travis config file to such that this line only runs only weekly: https://github.com/jupyter/notebook/blob/dc1eeab2f385c1869844219e8aff867ed38d462e/.travis.yml#L75

**Comment by takluyver** [comment]
Yup, that's the idea. If you can configure it to only run when the build is triggered by a Travis cron job, we can set up the cron job to happen weekly.

**Comment by takluyver** [comment]
Closed by #3493
