### ISSUE TITLE
Endpoint docs?

### ISSUE THREAD

**Issue by petergarbers** [jupyter/notebook#3296]
I've noticed that there is this endpoint `/api/nbconvert` (source: https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API). However I cannot find any specifications on how to specify which file and format to run nbconvert on.

I have tried many variations that all give the same response:

```
curl --request GET \
  --url 'http://localhost:8888/api/nbconvert?path=TestMongoDB.ipynb%3Fdownload%3D1&format=text%2Fhtml' \
  --header 'authorization: token 9bda3d2c039583a10f4e4090d8975e3eb24cfc6e3ea1b372' \
  --cookie 'username-localhost-8888=%222%7C1%3A0%7C10%3A1517534146%7C23%3Ausername-localhost-8888%7C44%3AZGI3MzJhYzUzZTZlNDQzZWJiYjRhZmY4ZjcwYWNlYzI%3D%7Ca028155e1997d1725c4dcae200d702c893fb78b757385b7ee29b06e1d8e506a9%22; _xsrf=2%7C1a14fd1d%7C56ef251a45189d4e6e8ea9738b19508e%7C1517447429' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   446  100   446    0     0  44066      0 --:--:-- --:--:-- --:--:-- 44600
{
  "custom": {
    "output_mimetype": ""
  },
  "html": {
    "output_mimetype": "text/html"
  },
  "slides": {
    "output_mimetype": "text/html"
  },
  "latex": {
    "output_mimetype": "text/latex"
  },
  "pdf": {
    "output_mimetype": "text/latex"
  },
  "markdown": {
    "output_mimetype": "text/markdown"
  },
  "python": {
    "output_mimetype": "text/x-python"
  },
  "rst": {
    "output_mimetype": "text/restructuredtext"
  },
  "notebook": {
    "output_mimetype": "application/json"
  },
  "script": {
    "output_mimetype": ""
  }
}
```

Could anyone offer some guidance? I will update the docs to reflect how this works

**Comment by takluyver** [comment]
`/api/nbconvert` only gives you information about available formats. `/nbconvert/html/path/to/my_notebook.ipynb` will actually do the conversion.

The most up to date API docs are [here](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml), based on [this file](https://github.com/jupyter/notebook/blob/master/notebook/services/api/api.yaml)... though they still don't mention nbconvert.

**Comment by takluyver** [comment]
Closing in favour of https://github.com/jupyter/jupyter/issues/318 .

It's best to open an issue on just one repository, in general - mostly the same group are going to respond whichever one you choose, but opening it on two different ones means the conversation can get split.
