### ISSUE TITLE
How automaticly run cell when notebook is open

### ISSUE THREAD

**Issue by orobsonpires** [jupyter/notebook#3312]
Hi,

How could I make certain cell automatically run when a notebook is open?

**Comment by takluyver** [comment]
For yourself, you could do this with a [javascript extension](http://jupyter-notebook.readthedocs.io/en/stable/extending/frontend_extensions.html). You can't make the cells run automatically for someone else, because that would be a security problem.

**Comment by orobsonpires** [comment]
Thanks!
