### ISSUE TITLE
Jupyter notebook slow to render computational results even with very short computational timings

### ISSUE THREAD

**Issue by Coleej** [jupyter/notebook#3313]
My notebooks are very slow to output the results of code. Using the ExecuteTime plugin, I can see that some code takes 1 - 2 ms to complete, but the cell output doesn't render for 60s or more.

Also, occasionally the output will show at the time of execution, but running the cell doesn't complete and move to the next cell for a few seconds longer.

This can be extremely trivial code, but the results are the same. The "running" asterix will show in the prompt for many magnitudes longer than the actual computation takes. 

I have a number of plugins install, they all come from the nbextensions package and additionally the VIM bindings plugin. I have tested this on the Brave browser and Firefox. I'm running Ubuntu Gnome 16.04.

**Comment by takluyver** [comment]
Does it still happen if you disable all the plugins? Also check any browser extensions.

**Comment by Coleej** [comment]
It seems like one or a combination of the plugins. Execution time and cell completion are synchronized and normal without any enabled.

I'll bring them back one by one and post an issue with those packages.
