### ISSUE TITLE
404 GET

### ISSUE THREAD

**Issue by stoicaandrei** [jupyter/notebook#3317]
`404 GET /sw.js (::1)`

I get this error every time I open the jupyter notebook. Some advice?

**Comment by takluyver** [comment]
It looks like `sw.js` is a convention for a [service worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers). We don't use service workers. Maybe some browsers request it automatically, or maybe you have previously run something on `localhost:8888` which did, and your browser remembers that it was there.

I think you can safely ignore it, but if you're using Chrome, there are some instructions here that might help clear it: https://github.com/react-boilerplate/react-boilerplate/issues/1606
