### ISSUE TITLE
How would be the best approach to hide a cell output?

### ISSUE THREAD

**Issue by orobsonpires** [jupyter/notebook#3318]
Hi,

I have a cell that outputs a json object, however, I would like to hide this output as this is used only when read the notebook file and also would not like to show that to the user. What would be the best approach to hide this output after running the cell?

**Comment by danagilliann** [comment]
I don't think this is possible. You could collapse and shorten the cell's output by pressing the left side of the output, and you can also rearrange the order of the cells to put this output at the bottom. You can could also just delete the cell, but have the command present. Hope this helps!

**Comment by takluyver** [comment]
What are you trying to do with it when you read the notebook file?

**Comment by karanj1** [comment]
`# to hide output of this cell in jupyter notebook
%%capture
# Install tools needed for visualization
!apt-get install python3-pydot graphviz`

**Comment by lenka-cizkova** [comment]
https://jupyterbook.org/features/hiding.html#Hiding-outputs
