### ISSUE TITLE
Stylesheet warning: bad value on "boxplot.medianprops.color     : 'C1'

### ISSUE THREAD

**Issue by MoritzImendoerffer** [jupyter/notebook#3320]
I am using matplotlib version '2.1.2' (anaconda, windows 7, python 3.6) and adapted a  stylesheet from this official [source](https://matplotlib.org/tutorials/introductory/customizing.html?highlight=customizing%20matplotlib)

when I uncomment line 148:
`boxplot.medianprops.color     : 'C1'`

I do get following warning (regardless of the backend):
    `UserWarning: Bad val "'C1'" on line #148
    Key boxplot.medianprops.color: 'C1' does not look like a color arg`

**Comment by takluyver** [comment]
Maybe you want to ask [matplotlib](https://github.com/matplotlib/matplotlib) about this? It doesn't sound like it's related to anything Jupyter does.

**Comment by MoritzImendoerffer** [comment]
Damnit. I am sorry. This was the wrong repository. Sorry for that.
