### ISSUE TITLE
Jupyter Notebook not launching from Anaconda Navigator

### ISSUE THREAD

**Issue by laurenldowning** [jupyter/notebook#3329]
I have installed Anaconda Navigator and have had no success in launching Jupyter Notebook from the user interface. 

I have successfully got Jupyter Notebook to run using Anaconda Prompt and the Windows shortcut (after adding double quotations around %USERPROFILE% in the path). However, I have had no luck in launching it from the Anaconda Navigator UI itself.

When I select "Launch" for Jupyter Notebook 5.0.0 in Anaconda Navigator (v. 1.6.9), the loading bar appears at the bottom of the screen saying "Launching notebook", but after a while it just goes away and nothing happens. I am using Windows 10 64-bit.

Any help in resolving this issue would be greatly appreciated.

**Comment by takluyver** [comment]
Try on [anaconda-issues](https://github.com/ContinuumIO/anaconda-issues/) - it sounds like a problem with Anaconda Navigator, which we don't have any control over.
