### ISSUE TITLE
strange svg rendering when glyph names are shared

### ISSUE THREAD

**Issue by simonbyrne** [jupyter/notebook#333]
I don't know enough about the svg format to know if this is a problem with the notebook or something else, but I'm seeing some odd behaviour when I display multiple svg files which have defs elements that overlap ids.

For example, this notebook:
https://gist.github.com/simonbyrne/47b27e6113df84c81fd8

It seems to render okay in github, but when I use notebook viewer (or use jupyter locally), the letters (which are actually symbols defined as defs, blame R's svg export) display incorrectly:
http://nbviewer.ipython.org/gist/simonbyrne/47b27e6113df84c81fd8
the second image looks like this:
<img width="817" alt="screen shot 2015-08-25 at 15 11 54" src="https://cloud.githubusercontent.com/assets/1692009/9468841/b2eb0170-4b3b-11e5-81d4-5340332b03a7.png">

If I manually rename the ids to be unique in both files, the problem goes away. It could be a browser problem, but I see the same in both Chrome and Safari.

**Comment by simonbyrne** [comment]
Never mind, this is a problem with inline svg rendering:
http://stackoverflow.com/questions/16123721/how-to-use-local-defs-in-svg

**Comment by mykelk** [comment]
TikzPictures.jl does some search and replace tricks of the svg in the `writemime` function [here](https://github.com/sisl/TikzPictures.jl/blob/master/src/TikzPictures.jl) to handle this issue in Jupyter notebooks.

**Comment by simonbyrne** [comment]
I ended up doing something similar:
https://github.com/JuliaStats/RCall.jl/blob/74e5af3670ab0d51217bdba3e281d906602802af/src/IJulia.jl#L43-L44

**Comment by mykelk** [comment]
@simonbyrne, you might need to do something similar for clip, image, linear, etc. in addition to glyph, depending on what kinds of svgs you're generating.
