### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by prateek781995** [jupyter/notebook#3345]
![same](https://user-images.githubusercontent.com/36201865/36344279-c928c346-143d-11e8-8d8f-fa8eacd4cdb6.png)
 
Tried everything that too many times. Please someone help me as soon as possible. I really need it.

**Comment by takluyver** [comment]
Try [anaconda-issues](https://github.com/ContinuumIO/anaconda-issues/). We don't maintain the Anaconda installer.
