### ISSUE TITLE
interoperability with libraries that attempt writing to stdout/stderr

### ISSUE THREAD

**Issue by FabioLuporini** [jupyter/notebook#3349]
Jupyter captures stdout/stderr which causes the ``click`` library to break when used from within a notebook. Presumably other libraries might suffer from this issue as well.

The issue, alongside a potential (local) fix, was pointed out here: https://github.com/pallets/click/pull/918

This, however, should be fixed here in ``jupyter/notebook``.

**Comment by takluyver** [comment]
That would probably be an IPython issue (IPython is the backend that runs your Python code), but it's not obvious what the problem is. `sys.stdout.write()` certainly does work.

**Comment by mitsuhiko** [comment]
The issue is that `sys.stdout.writable()` return `False`. The issue does not occur in IPython as such.

**Comment by takluyver** [comment]
https://github.com/ipython/ipykernel/pull/316
