### ISSUE TITLE
How to load extension via command line in Notebook

### ISSUE THREAD

**Issue by limodou** [jupyter/notebook#335]
In Ipython, there is a option about 

```
--ext=<Unicode> (InteractiveShellApp.extra_extension)
    Default: ''
    dotted module name of an IPython extension to load.
```
and I can use it to load extension when starting ipython.

But in jupyter notebook this option can't be used any more, and I tried with:

```
jupyter notebook --NotebookApp.server_extensions=some_module
```

and I got:

```
[C 14:50:26.561 NotebookApp] Bad config encountered during initialization:
[C 14:50:26.561 NotebookApp] The 'server_extensions' trait of a NotebookApp instance must be a list, but a value of type 'unicode' (i.e. u'some_module') was specified.
```

And I know the NotebookApp.server_extensions should be a list, but I don't know if its value can be passed via command line option. 

So how to load extension via command line in Notebook?

**Comment by Carreau** [comment]
Hi @limodou 

You can either set a list in your `~/.jupyter/jupyter_notebook_config.py`, or you can pass the list by quoting it in the shell. The following should work :

```
jupyter notebook --NotebookApp.server_extensions="['some_module']"
```

I'll try to find the relevant part of the docs.

**Comment by limodou** [comment]
Thanks a lot, the second way seems work, but I write some print statement in it, but I can't see the output, so I don't know if the extension is called. The extension seems like:

```
def load_ipython_extension(ipython):
    print '************'
```

**Comment by Carreau** [comment]
You might want to use `logging` to print to console.

See [here](https://github.com/jupyter/scipy-advanced-tutorial/blob/master/Part1/extensions/server_ext_full.py) that also have in parent folder some instruction on how to set up.

**Comment by limodou** [comment]
I tried, but it seems no work, my test code just like:

```
def load_ipython_extension(ipython):
    import logging
    logging.basicConfig(level=logging.DEBUG)
    logging.info('############')
```

But I can't see the output which I expected. I don't know what I'm wrong.

**Comment by limodou** [comment]
I found the answer, the function should be `load_jupyter_server_extension` but not `load_ipython_extension`
