### ISSUE TITLE
Upload multiple files usability issue

### ISSUE THREAD

**Issue by donghwicha** [jupyter/notebook#3351]
Hello.
As I tested, if I want to upload 1000 JPG files with Jupyter, 
then I have to click upload buttons 1000 times. 

Is there any option with which I can upload at once? 

https://github.com/ipython/ipython/issues/9580

**Comment by hy84besu** [comment]
Having the same issue.

**Comment by donghwicha** [comment]
I used jupyter lab, and I could make it work.

**Comment by kamilhark** [comment]
$(".upload_button").click()

**Comment by donghwicha** [comment]
@kamilhark this issue is closed. Don't add comment. Please.
