### ISSUE TITLE
5.0.0 documentation disappeared from readthedocs

### ISSUE THREAD

**Issue by wstomv** [jupyter/notebook#3354]
We still use Jupyter 5.0.0 (as part of the Anaconda 4.4.0 installation) in a course with over 2000 (two thousand) students (disk images for their laptops were prepared earlier last year, well before Anaconda 5.0 came out).

However, on https://jupyter-notebook.readthedocs.io, the 5.0.0 documentation for Jupyter Notebook disappeared. There is still a link to 4.x, and the next one is 5.2.0 and up.

Would it be possible to reinstate the 5.0.0 documentation on https://jupyter-notebook.readthedocs.io?

**Comment by gnestor** [comment]
The docs have changed very little since 5.0.0, so using the 5.4.0 docs should be fine. Nonetheless, I have added back 5.0.0 and every minor version release to ReadTheDocs 👍

**Comment by wstomv** [comment]
Thanks.  Highly appreciated.
