### ISSUE TITLE
Navigation feature request

### ISSUE THREAD

**Issue by Jeitan** [jupyter/notebook#3355]
Would it be possible to add a way to move the active cell *with the keyboard* by more than one cell at a time?  I.e. "scroll" the notebook but also move the active cell along with the view. Currently you can scroll around the notebook easily but only with the view - the selected cell doesn't change.  I don't know how feasible it is to make it match the browser scroll, but even just a keyboard shortcut that would "skip" N number of cells (maybe where N is configurable) would be *awesome*.

The use case - I open a long notebook with a lot of cells in it; some are markdown for labeling but most are code.  There is a section at the bottom that I want to go to right away.  Right now I have two options: 1) scroll down there with Space or PageDown, then use the mouse to click on the cell I want or 2) hit J or Down Arrow a gazillion times (in actuality probably ~80).  Obviously option 2 is really inconvenient and slow, and I *really* don't like doing option 1.

Some context - I have bad shoulder problems, and because of that I use the keyboard as much as is humanly possible because using the mouse actually hurts.  Not being able to jump around the notebook (**with the active cell, not just the view**) is the foremost issue I have with the Notebooks (which I otherwise love!).

If there is already a way to do this, please tell me how!  And I apologize if this is a duplicate or has been discussed and rejected ... searching for "scroll" or "focus" seemed to just turn up lots of stuff about scrolling within cells.

**Comment by juhasch** [comment]
You can try the notebook extension here https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/navigation-hotkeys/readme.html
This extension changes the cell focus when scrolling using page up/down.

**Comment by Jeitan** [comment]
@juhasch Thanks for that wonderful tip!  I just tried it and it's exactly what I want.  Now I have a related question - do you know if there is any way to accomplish this same thing without using an extension? The system I use for 95% of my work is offline, always at least 3 releases behind the current, and nigh impossible to get new things installed, especially open source things (I have no control over its configuration, *sadly*).  I am already using a custom kernelspec on the relevant machine, would it work to put those Javascript customizations into a custom kernel.js?

**Comment by juhasch** [comment]
You could copy the extension JavaScript into your local custom.js.

**Comment by Jeitan** [comment]
Since there is a custom.js workaround for this that I've been using successfully, I figured I'd close this to remove the clutter.
