### ISSUE TITLE
Allow notebooks to automatically load custom latex macros, on a per-notebook basis

### ISSUE THREAD

**Issue by ketch** [jupyter/notebook#3358]
I would like to be able to set a notebook metadata value to tell it to load a particular Mathjax configuration (in order to set up custom latex macros).  I think that being able to tell it to load a .js file would be sufficient.

I know that I can modify custom.js, but that would affect all of my notebooks and would not affect the desired notebook for other users.

I know that I can define latex macros in markdown cells, but this has to be done in every notebook and breaks when converting to latex/PDF.

I would be willing to write an nbextension to do this, if that's the only way.

**Comment by takluyver** [comment]
By design, untrusted notebooks cannot run code when they are loaded. They used to a few years ago, but we realised that it's a security issue: Javascript code on a notebook page can interact with the notebook server and its kernels, so it's not effectively sandboxed like Javascript code normally is.

So asking all your users to install an extension is probably the only way to do this.

**Comment by ketch** [comment]
Thanks for your attention to this, @takluyver .  I think it's one of the major obstacles to developing a large project like a book in Jupyter.

Okay, I've renamed the issue since I don't really need to execute code.  I just need to add latex macros; this can currently be accomplished by "running" a markdown cell, so there must not be any security issue with that.  I merely want to be able to do it through notebook metadata rather than through a markdown cell.

Could you please reopen the issue?  Or should I raise a new one instead?

**Comment by takluyver** [comment]
Can you elucidate more on what defining them in markdown cells breaks for conversion to latex with nbconvert?

cc @mpacer

**Comment by ketch** [comment]
>Can you elucidate more on what defining them in markdown cells breaks for conversion to latex with nbconvert?

In a regular latex document, one typically defines macros outside of any math environment; the macros are then in effect throughout the document.  In the jupyter notebook (though I think this is a mathjax "feature") one instead defines macros inside a math environment (so that the parser picks them up as a math thing, I guess) and they are somehow made to have effect throughout the notebook.

When nbconvert converts a notebook to latex, it (naturally) leaves the macros inside a math environment.  But in the latex document, that means the macros take effect **only within that particular math environment; i.e., between the surrounding delimiters only**.

That's the main problem when dealing with a single notebook.  One may fix it manually by removing the math delimiters around sets of macros in the .tex file.  

When dealing with a set of notebooks that will be merged into a single .tex document, the workaround just mention fails, since repeated definitions of the same macro are not allowed (and one would typically redefine certain macros in multiple notebooks).

I've also tried using an nbconvert template to insert my macros, but again I get errors because the macros are redefined by the commands copied from the notebook.

**Comment by ketch** [comment]
By the way, the same thing has been requested [here](https://groups.google.com/forum/#!topic/jupyter/Wlu-eS5LlTo) and (essentially) [here](https://github.com/jupyter/nbconvert/issues/312).  I strongly suspect that this is a significant issue for a fairly large number of people.

**Comment by jfbercher** [comment]
@ketch Perhaps can you have a look at [latex_envs](https://github.com/jfbercher/jupyter_latex_envs/). 

For the problem mentioned, *if I understand well*, it enables to load a user defined file `latexdefs.tex` of latex macros in live notebooks, essentially [this function](https://github.com/jfbercher/jupyter_latex_envs/blob/master/src/latex_envs/static/initNb.js#L50-L60). 

It also provides a custom exporter, which directly includes the `latexdefs.tex` in the template when exporting to LaTeX, or reload the defs in "mathjax style" when exporting to html or html slides, using [these lines](https://github.com/jfbercher/jupyter_latex_envs/blob/master/src/latex_envs/latex_envs.py#L201-L213).

**Comment by ketch** [comment]
@jfbercher Thanks!  I had seen latex_envs, but couldn't get it to do this (and still can't).  I've installed and enabled it, and put some macros in a file call `latexdefs.tex` (which I've tried copying to various directories, but to no avail.  Looking through the extension, I don't see where this function gets called.  I also can't find any mention of it in the various versions of the documentation for latex_envs.  Do you know how to get it to work?

**Comment by jfbercher** [comment]
This is mentioned [here](https://rawgit.com/jfbercher/jupyter_latex_envs/master/src/latex_envs/static/doc/latex_env_doc.html#Configuration-toolbar) in the doc -- Yes, there are lot of things and it could be indicated better. The function in called in [initNb.js](https://github.com/jfbercher/jupyter_latex_envs/blob/master/src/latex_envs/static/initNb.js#L50-L60) where the various options are defined/updated. 

You have to push the wrench on the main toolbar to show the latex configuration toolbar. Then toggle on "LaTeX user definitions" (it is off by default). The file must reside in the same directory as the notebook. 

![image](https://user-images.githubusercontent.com/7596356/36945047-5e99d490-1fa8-11e8-955c-de32d47d7bf7.png)

**Comment by ketch** [comment]
Thanks, that worked!

I don't think this solves the issue that I have, though:

- It looks like the user will need to manually enable the macros (using the "Toggles" menu) for each notebook.  Is that correct?
- After al the math is rendered correctly, If I save the notebook, close it, and reopen it, the macros do not render unless I manually trigger the math to be re-rendered.
- The latex_env extension seems to invoke Mathjax a huge number of times.  At least, when I open a notebook with it enabled, it takes >10s to finish rendering all the math, and in the meantime there is a lot of flickering as it changes what appears in the places where there is math.  This is repeated when re-rendering math.

Perhaps I can extract just the `loadlatexuserdefs` function to have something more lightweight that does what I need.  Would that be okay with you, @jfbercher ?  And do you know if there is a way to have the notebook automatically run that function when loading?

Thanks so much for your help.

**Comment by ketch** [comment]
Also, I notice that the `latex_env` extension cause a lot of my math to not get rendered properly at all (it seems to be getting rendered as markdown instead).  Is this a known issue?

**Comment by jfbercher** [comment]
> -  It looks like the user will need to manually enable the macros (using the "Toggles" menu) for each notebook. Is that correct?

Yes.

> After al the math is rendered correctly, If I save the notebook, close it, and reopen it, the macros do not render unless I manually trigger the math to be re-rendered.

This is not normal. The macros are automatically reloaded once they have been defined (the state is saved in the notebook's metadata). You shouldn't have to manually retrigger rendering, this is done automatically.   

> The latex_env extension seems to invoke Mathjax a huge number of times. At least, when I open a notebook with it enabled, it takes >10s to finish rendering all the math, and in the meantime there is a lot of flickering as it changes what appears in the places where there is math. This is repeated when re-rendering math.

That is the price to pay to have all equations, environments like theorems, definitions, remaks, etc automatically numbered document-wide. 10s is really huge though. 
There is usually a small overload at loading, but not that important! Connected to the fact that not all your maths are rendered (your last comment), I think that your notebook might be very big (is it?) and you may experiment a bug in the notebook itself, cf https://github.com/jupyter/notebook/issues/2075

> Perhaps I can extract just the loadlatexuserdefs function to have something more lightweight that does what I need. Would that be okay with you, @jfbercher ? And do you know if there is a way to have the notebook automatically run that function when loading?

yes, no problem. 
This is easy to do: essentially the nbextension could be something like (haven't tried it)
```
define(function(require, exports, module) {
    var Jupyter = require('base/js/namespace');

function loadLatexUserDefs() { ...}

function rerenderMaths() { // probably something like that
        MathJax.Hub.Queue(
          ["PreProcess", MathJax.Hub], ["Reprocess", MathJax.Hub]
        );
}

function load_ipython_extension() {
     "use strict";
   
    if (Jupyter.notebook._fully_loaded) {  
        loadLatexUserDefs();       
        rerenderMaths(); 
    } else {
        $([Jupyter.events]).on("notebook_loaded.Notebook", function() {
                   loadLatexUserDefs();   
                  rerenderMaths();  
        })
    }
return {
        load_ipython_extension: load_ipython_extension,
    };
})
```
If/when it works, please upload it to https://github.com/ipython-contrib/jupyter_contrib_nbextensions/

If you need to continue the discussion, may be [here](https://github.com/jfbercher/jupyter_latex_envs/issues=?)

**Comment by ketch** [comment]
Thanks for the help, @jfbercher !  I've posted a PR to nbextensions, and this issue is resolved.
