### ISSUE TITLE
Document how to access IPython.CodeCell.options_default['cm_config']

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#336]
Reminder for me to respond t andrew and write that somewhere. 

> What is the right way to access cm_config now? I'm getting the message "accessing cm_config directly is deprecated" and "IPython.CodeCell.options_default['cm_config']['mode'] = 'ihaskell';" doesn't seem to work
> Actually, running that in the browser works, just not in kernel.js...
> Any ideas?
> It seems like anything IPython.CodeCell.options_default is being overridden from the values set in kernel.js as of 4.0
> Ugh, I wish the JS API stabilized and was documented already, dealing with this and frustrated users on every release is a nightmare
> You originally helped write this kernel.js, any ideas?

**Comment by Carreau** [comment]
@gibiansky, your kernel.js seem to work for me, and you do not seem to access `Cell.cm_config` directly, so I don't see the warning. 

What you seem to do in `kernel.js` with cm_config seem to be unnecessary. IIRC closebracket is one by default, and you can set the codemirror mode in your kernel.json with the `"codemirror_mode":"ihaskell"` key.

**Comment by willingc** [comment]
@Carreau Let me know if you need help on this. Happy to take a rough file or notes from you and put together a ``.rst`` file

**Comment by Carreau** [comment]
Think it can go with the [other doc update](https://github.com/Carreau/jupyter_notebook/commit/2b79f882a837fcd0e95130166ad0fc10127aa72a) about indent units which fix another issue I don't remember the number. I'm happy for you to take over, I'm planning my traveling for next week and the week after so my bandwidth is close to 0.

**Comment by gnestor** [comment]
@Carreau Is this already resolved in https://github.com/jupyter/notebook/blob/master/docs/source/frontend_config.rst?

**Comment by Carreau** [comment]
Yes indeed ! Thanks !
