### ISSUE TITLE
Search And Replace Feature

### ISSUE THREAD

**Issue by Seenivasanseeni** [jupyter/notebook#3364]
Having feature that can enable users to search their notebooks and files in the jupyter interface home page will be useful. My say is to have a search feature in this page.
![screenshot from 2018-02-22 17-31-08](https://user-images.githubusercontent.com/20085943/36537530-7080f6c0-17f6-11e8-83b2-73326a8af426.png)

**Comment by sat28** [comment]
@Seenivasanseeni you can check this out [Tree Filter Extension](https://github.com/jdfreder/jupyter-tree-filter) which provides the same functionality.

**Comment by Seenivasanseeni** [comment]
Can't we ship extension with our release itself?
