### ISSUE TITLE
ImportError: cannot import name PY36

### ISSUE THREAD

**Issue by sanjivsoni** [jupyter/notebook#3369]
I am runnning jupyter notebook on AWS EC2. When I import pandas inside notebook I am getting this error. Its running fine when I directly import pandas from python console.

**Inside jupyter notebook**
`import pandas as pd`

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-30-f763911ceade> in <module>()
      1 import numpy as np
----> 2 import pandas as pd
      3 import matplotlib.pyplot as plt
      4 get_ipython().magic(u'matplotlib inline')

/home/ec2-user/anaconda2/lib/python2.7/site-packages/pandas/__init__.pyc in <module>()
     40 import pandas.core.config_init
     41 
---> 42 from pandas.core.api import *
     43 from pandas.core.sparse.api import *
     44 from pandas.stats.api import *

/home/ec2-user/anaconda2/lib/python2.7/site-packages/pandas/core/api.py in <module>()
      6 
      7 from pandas.core.algorithms import factorize, unique, value_counts
----> 8 from pandas.core.dtypes.missing import isna, isnull, notna, notnull
      9 from pandas.core.categorical import Categorical
     10 from pandas.core.groupby import Grouper

/home/ec2-user/anaconda2/lib/python2.7/site-packages/pandas/core/dtypes/missing.py in <module>()
      7 from .generic import (ABCMultiIndex, ABCSeries,
      8                       ABCIndexClass, ABCGeneric)
----> 9 from .common import (is_string_dtype, is_datetimelike,
     10                      is_datetimelike_v_numeric, is_float_dtype,
     11                      is_datetime64_dtype, is_datetime64tz_dtype,

/home/ec2-user/anaconda2/lib/python2.7/site-packages/pandas/core/dtypes/common.py in <module>()
      2 
      3 import numpy as np
----> 4 from pandas.compat import (string_types, text_type, binary_type,
      5                            PY3, PY36)
      6 from pandas._libs import algos, lib

ImportError: cannot import name PY36

`which python`
~/anaconda2/bin/python

```
from sys import executable
print(executable)
```
/home/ec2-user/anaconda2/bin/python

**Comment by sanjivsoni** [comment]
Restarting the EC2 instance solved this.

**Comment by BenjaminPoilve** [comment]
Same issue for me, running a notebook on the Bitfusion AMI. Reboot solved it as well.
