### ISSUE TITLE
The deployment for remote access is terribly complicated!!!

### ISSUE THREAD

**Issue by OnlyBelter** [jupyter/notebook#3370]
I spent three days to deploy Jupyter Notebook! I followed https://jupyter-notebook.readthedocs.io/en/latest/public_server.html#running-a-notebook-server, but it is very frustrated. Now I still cannot open Notebook on my browser.

I set all the following parameters:
```
# Set options for certfile, ip, password, and toggle off
# browser auto-opening
c.NotebookApp.certfile = u'/absolute/path/to/your/certificate/mycert.pem'
c.NotebookApp.keyfile = u'/absolute/path/to/your/certificate/mykey.key'
# Set ip to '*' to bind on all interfaces (ips) for the public server
c.NotebookApp.ip = '*'
c.NotebookApp.password = u'sha1:bcd259ccf...<your hashed password here>'
c.NotebookApp.open_browser = False

# It is a good idea to set a known, fixed port for server access
c.NotebookApp.port = 9999
```

But I cannot change the whole website to `https` connection, I can only give `mycert.pem` and `mykey.key` files created by `openssl`. Then I try to access the port, not work.

**Comment by takluyver** [comment]
Using SSL is somewhat complicated, but running a publicly accessible server without it is a security risk. There are other options, such as running it remotely but not publicly accessible, using SSH tunnels or similar to connect to it. Maybe we should document those more clearly. But beyond that, I don't know what we can do to make it simpler.

**Comment by OnlyBelter** [comment]
I'm sorry for the complaint, it is just a little bit complex for me.

Actually I can deploy `RStudio Server` in 5 minutes ^_^.

I usually use Pycharm. We got a new web server in cloud (similar to AWS, but in Alibaba Cloud) recently, so I think somehow I can use it in remote...

Could you give more details about `SSH tunels`? I don't know if it is suitable for my situation. I cannot convert all websits to `https`.

**Comment by OnlyBelter** [comment]
Jupyterhub shoud be a better choice. Follow this tutorial: https://github.com/jupyterhub/jupyterhub-the-hard-way/blob/HEAD/docs/installation-guide-hard.md
