### ISSUE TITLE
Jupyter launches, but can't run any code or create notebooks.

### ISSUE THREAD

**Issue by kcostya** [jupyter/notebook#3378]
Hey! 
I'm launching the Jupyter notebook from Google Cloud VM. The Jupyter opens in the browser, but I can't create new notebook:
![image](https://user-images.githubusercontent.com/34856477/36691970-7361305c-1b3f-11e8-91d6-b9c7b4743ab8.png)
Nor can I open a terminal from it. It closed in a fraction of a second. The existing notebooks open but the code doesn't run.
Please help to fix this!

**Comment by cloga** [comment]
Do you use custom subdomain or IP? I faced some issue when using subdomain.

**Comment by kcostya** [comment]
[ISSUE SOLVED] Clearing the cookies and browser cache has solved the issue.
