### ISSUE TITLE
how to run git clone https://.... in jupyter notebook

### ISSUE THREAD

**Issue by isalirezag** [jupyter/notebook#3395]
I am new to jupyter
In python i can easily run ```git clone https://github.....``` and it runs and work
My question is how I can do it in jupyter because when i cpy and paste it in jupyter and run it it gives me error that:

```
  File "<ipython-input-4-4d4c63f65776>", line 1
    git clone https://github.com/tensorflow/models"
            ^
SyntaxError: invalid syntax
```

Also can you tell me how I can do ```cd Desktop/...``` in jupyter notebook

Thanks

**Comment by takluyver** [comment]
`git` is a shell command - you'd normally run it in a terminal or command prompt, not inside Python.

As a special convenience in Python notebooks, you can run shell commands by putting `!` before them, like `!git clone ...`

**Comment by romanojr** [comment]
Retornou a mensagem abaixo
'git' nÆo ‚ reconhecido como um comando interno
ou externo, um programa oper vel ou um arquivo em lotes.

**Comment by gpandi007** [comment]
> `git` is a shell command - you'd normally run it in a terminal or command prompt, not inside Python.
> 
> As a special convenience in Python notebooks, you can run shell commands by putting `!` before them, like `!git clone ...`

after clone the project how to run the model ? how to access the project folders ?
any sample code ?

**Comment by Nushaine** [comment]
I'm not sure which model you're referring to? Can you send me the link to
the repo?

**Comment by abbaskhan2702** [comment]
if for example i want to install excalibur  https://excalibur-py.readthedocs.io/en/master/user/install.html. How can I clone the repo using terminal, Can anyone please demonstrate an example? Many thanks.

**Comment by pagosantoshmaher** [comment]
!git clone https://github.com/

**Comment by pagosantoshmaher** [comment]
Try likewise URL for git clone in jupyter notebook.

**Comment by olimatgit** [comment]
For me " !git clone " doesnot work , jupyter tell me " git is not recognized as an internal command "
I want to use a new repository (module) published on github.
I downloaded the zip folder and extracted it. , but I don’t know how to use this module with jupyter (on windows 10).
How can I import or use  this module into jupyter .
