### ISSUE TITLE
A very terrible problem:-bash: /home/simy/.local/bin/jupyter: No such file or directory

### ISSUE THREAD

**Issue by SimingYan** [jupyter/notebook#3403]
Background: The path of global jupyter is /usr/local/bin/jupyter

I am not a root user. And I installed jupyter by "pip install jupyter --user". But after that I found that there was something wrong [My another problem](https://github.com/jupyter/notebook/issues/3402) So I tried to uninstall it by "pip uninstall jupyter --user", but it didn't work. 
Then I found the path of my jupyter was "/home/simy/.local/bin/jupyter". **And then I stupidly manually removed jupyter files from /home/simy/.local/bin/.**

Now, when I type "which jupyter" in terminal. It output "/usr/local/bin/jupyter"
But when I type"jupyter notebook". It output "-bash: /home/simy/.local/bin/jupyter: No such file or directory"
What should I do?

**Comment by takluyver** [comment]
The easiest thing is usually to close and reopen the terminal. If you don't want to do that, run `hash -r` in bash.

Bash caches the paths of executables (like `jupyter`). Either of those methods will clear the cache so it should find jupyter in the other directory.

**Comment by SimingYan** [comment]
Thank you! The problem is solved.
