### ISSUE TITLE
Intermediate notebook.tex file used to generate PDF remains after export ends

### ISSUE THREAD

**Issue by WinglessPegasus** [jupyter/notebook#3408]
When Jupyter Notebook attempts to export the notebook into PDF, it will first export it to LaTeX first, generating an intermediate `notebook.tex` file, and then use LaTeX to compile it into PDF format. However, after the PDF is produced, the `notebook.tex` remains and is not deleted as it should.

**Comment by takluyver** [comment]
I think this should be fixed by https://github.com/jupyter/nbconvert/pull/768 . We'll need to do a new release of nbconvert.

**Comment by WinglessPegasus** [comment]
Thank you!
