### ISSUE TITLE
Importing Seaborn no longer changes plot appearance by default

### ISSUE THREAD

**Issue by elmerehbi** [jupyter/notebook#3410]
I used to simply import seaborn and get instant change to the plot appearances. However this no longer happens unless I explicitly run `sns.set()`. Is that something new to seaborn or something to do with jupyter?

**Comment by takluyver** [comment]
[Seaborn 0.8 release notes](https://seaborn.pydata.org/whatsnew.html#v0-8-0-july-2017):

> The default style is no longer applied when seaborn is imported. It is now necessary to explicitly call set() or one or more of set_style(), set_context(), and set_palette(). Correspondingly, the seaborn.apionly module has been deprecated.

**Comment by elmerehbi** [comment]
Thanks for the clarification.
