### ISSUE TITLE
Iframe strange behavior, duplicates full notebook inside a cell

### ISSUE THREAD

**Issue by sauln** [jupyter/notebook#3414]
Hi! Thanks for taking a look at this, and apologies ahead of time if this is problem is caused by something I shouldn't be doing in the first place rather an issue with notebook. I was unable to find a similar issue, nor a work around.

I am trying to display some HTML within a notebook. To compartmentalize the CSS, I am using an iframe.  Because I want to construct the HTML in the notebook rather than load it from a file, I am using the `IPython.display.HTML` function rather than `IPython.display.IFrame`. 

Whenever I click an interactive component, the entire notebook appears to be copied within the output cell. 

A minimal example is
``` Python
import IPython
import html

raw_html = '''
<html>

<head>

<h1>Some HTML In an iframe</h1>

<div id="control">
  <a href="#"><small>[-]</small></a>
</div>

</body>
</html>

'''

# In my actual case, this JS runs when the [-] is clicked. It is not necessary to reproduce this issue though.
# d3.select("#meta_control").on("click", function() {
#   d3.select("#meta").style("display", "none");
# });
 
iframe = f'''<iframe srcdoc="{html.escape(raw_html)}" width=100%% height=250></iframe>'''
IPython.display.HTML(iframe)
```

The output for this will look like
![before_click](https://user-images.githubusercontent.com/5808961/37236883-6d320f14-23c1-11e8-8096-2a61e02d1600.png)

and after clicking the `[-]` link, it looks like
![after_click](https://user-images.githubusercontent.com/5808961/37236885-6ff70b00-23c1-11e8-8ecf-0970eee850bd.png)

This issue does not happen if I load the same html from a file using either this method:
``` Python
iframe = '<iframe src=test.html width=100%% height=800 frameBorder="0"></iframe>'
IPython.core.display.display(IPython.core.display.HTML(iframe))
```
or this method 
``` Python
IPython.core.display.display(IPython.display.IFrame('test.html', width=500, height=500))
```

where `test.html` contains the `raw_html` string defined above. 

I would be interested in contributing a fix and working more on this if someone with more understanding of the project could help me figure out what is going on.

Thank you!

Here is a notebook with all this code: [http://nbviewer.jupyter.org/gist/sauln/b4e5847d503f5760ab8c8683a5119ba3](http://nbviewer.jupyter.org/gist/sauln/b4e5847d503f5760ab8c8683a5119ba3)

**Comment by mondeja** [comment]
This is not an issue. See in your first code example `<a href="#"><small>[-]</small></a>` you are creating a link pointing to this same url (that means `#`) and is pointing to the current notebook. Inside the iframe, the link is loaded and your notebook is shown.

**Comment by takluyver** [comment]
I guess that it happens because when you're using `srcdoc=`, the document inside the iframe doesn't have its own URL, so the browser uses the URL of the parent document.

If you have a Javascript handler for clicking a link, you often want to prevent the default action from running, so the browser doesn't go to the link URL. The correct way to do this is `event.preventDefault();`, though you'll see quite a bit of code using `return false;` for this purpose.

**Comment by sauln** [comment]
I was able to prevent this behavior by setting `d3.event.preventDefault()`.

Thank you @mondeja and @takluyver for your help. Sorry for bringing a nonissue.
