### ISSUE TITLE
Opening Comm from kernel to unregistered front end target

### ISSUE THREAD

**Issue by SpencerPark** [jupyter/notebook#3422]
This issue is about how the front end should handle the case when a Comm is opened from the back end (ipython kernel for example) to  a target that is unregistered.

Consider opening a Comm with the standard code from the wiki with an added `on_close` handler:

```python
from ipykernel.comm import Comm
my_comm = Comm(target_name='my_comm_target')
@my_comm
def _close(msg):
    print('Closed')
```

I would expect that if the `target_name` `my_comm_target` is not registered on the front end that my `_close` callback would be called to indicate that the peer is not connected but this is not the case. The Comm remains open unless closed from the kernel.

**Note**: The behavior described above is the way the ipython kernel currently handles unregistered targets when a front end comm is opened.

```javascript
comm = Jupyter.notebook.kernel.comm_manager.new_comm('my_comm_target');
comm.on_close((msg) => console.log(msg));
```

Looking at [services/kernels/comm.js#L84](https://github.com/jupyter/notebook/blob/7dc9439af78dadffcf6070c4b351d2d622f1d36e/notebook/static/services/kernels/comm.js#L84), the `Comm` should be created before looking up the target and if the lookup fails (the `load_class` promise is rejected) the comm should be closed. See [ipykernel/comm/manager.py#L75](https://github.com/ipython/ipykernel/blob/0a6898a153c66e2c2ade8cf3e0f199c102fbf33e/ipykernel/comm/manager.py#L75) for the back end implementation that I would like the front end to mirror.

**Comment by jtpio** [comment]
Closing as the classic notebook frontend has now been moved to https://github.com/jupyter/nbclassic.

Please open a new issue here or in https://github.com/jupyterlab/jupyterlab if needed, thanks!
