### ISSUE TITLE
 asyncio.ensure_future error after upgrade - notebook won't run

### ISSUE THREAD

**Issue by davorh** [jupyter/notebook#3426]
After upgrade to notebook (5.4.0) I got this error (I have standard clean virtualenv installation)

Traceback (most recent call last):
  File "bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "lib/python3.4/site-packages/notebook/notebookapp.py", line 44, in <module>
    from zmq.eventloop import ioloop
  File "lib/python3.4/site-packages/zmq/eventloop/__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "lib/python3.4/site-packages/zmq/eventloop/ioloop.py", line 78, in <module>
    while _IOLoop.configurable_default() is not _IOLoop:
  File "lib/python3.4/site-packages/tornado/ioloop.py", line 350, in configurable_default
    from tornado.platform.asyncio import AsyncIOLoop
  File "lib/python3.4/site-packages/tornado/platform/asyncio.py", line 25, in <module>
    from tornado.gen import convert_yielded
  File "lib/python3.4/site-packages/tornado/gen.py", line 1295, in <module>
    _wrap_awaitable = asyncio.ensure_future
AttributeError: 'module' object has no attribute 'ensure_future'

list of installed packages

absl-py (0.1.11)
astor (0.6.2)
backports-abc (0.5)
backports.weakref (1.0.post1)
bleach (2.1.3)
coniii (0.2.5)
cycler (0.10.0)
Cython (0.28)
decorator (4.2.1)
dill (0.2.7.1)
entrypoints (0.2.3)
enum34 (1.1.6)
gast (0.2.0)
grpcio (1.10.0)
html5lib (1.0.1)
ipykernel (4.8.2)
ipython (6.2.1)
ipython-genutils (0.2.0)
ipywidgets (7.1.2)
jedi (0.11.1)
Jinja2 (2.10)
joblib (0.11)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.2.3)
jupyter-console (5.2.0)
jupyter-contrib-core (0.3.3)
jupyter-contrib-nbextensions (0.4.0)
jupyter-core (4.4.0)
jupyter-highlight-selected-word (0.1.0)
jupyter-latex-envs (1.4.4)
jupyter-nbextensions-configurator (0.4.0)
Keras (2.1.5)
kiwisolver (1.0.1)
llvmlite (0.22.0)
lxml (4.2.0)
Markdown (2.6.11)
MarkupSafe (1.0)
matplotlib (2.2.0)
mistune (0.8.3)
multiprocess (0.70.5)
nbconvert (5.3.1)
nbformat (4.4.0)
notebook (5.4.0)
numba (0.37.0)
numpy (1.14.2)
pandas (0.22.0)
pandocfilters (1.4.2)
parso (0.1.1)
patsy (0.5.0)
pexpect (4.4.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
protobuf (3.5.2)
ptyprocess (0.5.2)
Pygments (2.2.0)
pyparsing (2.2.0)
python-dateutil (2.7.0)
pytz (2018.3)
PyYAML (3.12)
pyzmq (17.0.0)
qtconsole (4.3.1)
rpy2 (2.9.2)
scikit-learn (0.19.1)
scipy (1.0.0)
Send2Trash (1.5.0)
setuptools (38.5.2)
simplegeneric (0.8.1)
six (1.11.0)
sklearn (0.0)
statsmodels (0.8.0)
tensorboard (1.6.0)
tensorflow-gpu (1.6.0)
tensorflow-tensorboard (1.5.1)
termcolor (1.1.0)
terminado (0.8.1)
testpath (0.3.1)
tigramite (3.0b0)
tornado (5.0)
traitlets (4.3.2)
typing (3.6.4)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.14.1)
wheel (0.30.0)
widgetsnbextension (3.1.4)

**Comment by davorh** [comment]
Downgraded tornado to 4.5.3 got the system running. pyzmq (17.0.0) so other recommendations to upgrade this package are not applicable in this case.

**Comment by minrk** [comment]
This is tornado 5, where tornado is running on top of asyncio. This means that instantiating asyncio inside a cell won't work anymore because asyncio is already running. To use asyncio, while we wait to implement better asyncio support in IPython itself, you need to run asyncio in a thread to get control of the eventloop. See [this issue on the matter](https://github.com/ipython/ipython/issues/11030).
