### ISSUE TITLE
search and replace toolbar icon ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#343]
Do we want a toolbar icon for search and replace ? We already have magnifying glass for command palette, but we can change.

**Comment by Carreau** [comment]
cc @parleur, @captainsafia, I think that @Achifaifa also might be looking for some easy fixes/features. 
( I try to tag easy fixes with sprint-friendly)

**Comment by ellisonbg** [comment]
I am +1 on that.

On Wed, Aug 26, 2015 at 8:07 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> cc @parleur <https://github.com/parleur>, @captainsafia
> <https://github.com/captainsafia>, I think that @Achifaifa
> <https://github.com/Achifaifa> also might be looking for some easy
> fixes/features.
> ( I try to tag easy fixes with sprint-friendly)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/343#issuecomment-135054175>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by captainsafia** [comment]
Sounds good. Feel free to cc me on any issues I should look into.

@parleur, here is a Github search query you can use to find all sprint-friendly issues across the Jupyter ecosystem.

`is:open is:issue is:sprint-friendly user:ipython user:jupyer user:phosphorjs user:nteract`

**Comment by Achifaifa** [comment]
Thanks for the ping :)

I asusme this is a GUI issue? This looks like a very interesting thing to work on, but my design skills are next to null. 

Maybe I can find an open source icon that fits (Not sure if it's a good idea?), but I'd like to know where the current ones come from so I can find something similar or from the same place.

**Comment by Carreau** [comment]
There is no design skill needed.
You just have to pick an icon from
https://fortawesome.github.io/Font-Awesome/icons/

I think we could use
http://fortawesome.github.io/Font-Awesome/icon/keyboard-o/ for Command
palette, and use magnifying glass for search and replace.

**Comment by Achifaifa** [comment]
Oh, cool. I'll work on it.

**Comment by minrk** [comment]
closed by #358
