### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by pruthvi94** [jupyter/notebook#3432]
HI Team,

While running the build, I am getting the below error, Please help.
  
File "C:\Users\pruthviraj.hs\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\finder.py", line 435, in _LoadModule
    module.code = compile(codeString, path, "exec")
ValueError: source code string cannot contain null bytes

Thanks,
Pruthvi

**Comment by takluyver** [comment]
You probably need to ask about it on the cx_Freeze mailing list or issue tracker: https://anthony-tuininga.github.io/cx_Freeze/

**Comment by pruthvi94** [comment]
Thank you, I will do that

**Comment by takluyver** [comment]
Great, closing here.
