### ISSUE TITLE
Can't start jupyter notebook due to missing module of 'zmq.eventloop'

### ISSUE THREAD

**Issue by xiaoshir** [jupyter/notebook#3433]
C:\bw2-python\Scripts>jupyter notebook
Traceback (most recent call last):
  File "c:\bw2-python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\bw2-python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\bw2-python\Scripts\jupyter-notebook.EXE\__main__.py", line 5, in <mod
ule>
  File "c:\bw2-python\lib\site-packages\notebook\notebookapp.py", line 42, in <m
odule>
    from zmq.eventloop import ioloop
ModuleNotFoundError: No module named 'zmq.eventloop'

Jupyter was working fine for me before, but recently I cleaned up/reorganized my folders a bit, then my nbextension didn't work. After I reinstalled it, my jupyter didn't work, and now I  got the error message above. I tried conda install zmq, but still getting the same error. 

Can any one help?

**Comment by takluyver** [comment]
From the that same directory, run `python -c "import zmq; print(zmq)"` to see where it's finding zmq.

**Comment by xiaoshir** [comment]
<module 'zmq' from 'C:\\bw2-python\\envs\\newproject\\lib\\site-packages\\zmq\\_
_init__.py'>

**Comment by takluyver** [comment]
That looks like the kind of path I'd expect.

The simplest thing might be to remove Anaconda entirely and install it again. It uses the same packages in different environments, which saves space but can make it hard to recover by uninstalling and reinstalling one package.

**Comment by xiaoshir** [comment]
Ok after I uninstalled miniconda and reinstalled it, this issue was gone.
