### ISSUE TITLE
jupyter kernal keeps dying

### ISSUE THREAD

**Issue by DanEran1988** [jupyter/notebook#3434]
I am trying to work with jupyter notebook, but when I open a file I receive the following error:

The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

In the CMD I see the following:

(base) C:\Users\Dan Eran>jupyter notebook [W 19:05:33.006 NotebookApp] Error loading server extension jupyterlab Traceback (most recent call last): File "C:\Users\Dan Eran\AppData\Roaming\Python\Python36\site-packages\notebook\notebookapp.py", line 1451, in init_server_extensions mod = importlib.import_module(modulename) File "C:\Anaconda3\lib\importlib__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 994, in _gcd_import File "", line 971, in _find_and_load File "", line 953, in _find_and_load_unlocked ModuleNotFoundError: No module named 'jupyterlab' [I 19:05:33.122 NotebookApp] Serving notebooks from local directory: C:\Users\Dan Eran [I 19:05:33.122 NotebookApp] 0 active kernels [I 19:05:33.122 NotebookApp] The Jupyter Notebook is running at: [I 19:05:33.122 NotebookApp] http://localhost:8888/?token=99a355c23c6617857e387f53d0af607ae26b89c20598336e [I 19:05:33.122 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation). [C 19:05:33.122 NotebookApp]

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=99a355c23c6617857e387f53d0af607ae26b89c20598336e
[I 19:05:33.247 NotebookApp] Accepting one-time-token-authenticated connection from ::1 [I 19:05:42.699 NotebookApp] Creating new notebook in [I 19:05:43.563 NotebookApp] Kernel started: 1433cbbf-f4b9-4dd3-be19-e91d7ee3d82f Traceback (most recent call last): File "C:\Anaconda3\lib\runpy.py", line 193, in run_module_as_main "main", mod_spec) File "C:\Anaconda3\lib\runpy.py", line 85, in run_code exec(code, run_globals) File "C:\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Anaconda3\lib\site-packages\ipykernel__init.py", line 2, in from .connect import * File "C:\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in from IPython.core.profiledir import ProfileDir ModuleNotFoundError: No module named 'IPython' [I 19:05:46.555 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports Traceback (most recent call last): File "C:\Anaconda3\lib\runpy.py", line 193, in run_module_as_main "main", mod_spec) File "C:\Anaconda3\lib\runpy.py", line 85, in run_code exec(code, run_globals) File "C:\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Anaconda3\lib\site-packages\ipykernel__init.py", line 2, in from .connect import * File "C:\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in from IPython.core.profiledir import ProfileDir ModuleNotFoundError: No module named 'IPython' [I 19:05:49.591 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports Traceback (most recent call last): File "C:\Anaconda3\lib\runpy.py", line 193, in run_module_as_main "main", mod_spec) File "C:\Anaconda3\lib\runpy.py", line 85, in run_code exec(code, run_globals) File "C:\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Anaconda3\lib\site-packages\ipykernel__init.py", line 2, in from .connect import * File "C:\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in from IPython.core.profiledir import ProfileDir ModuleNotFoundError: No module named 'IPython' [I 19:05:52.620 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports Traceback (most recent call last): File "C:\Anaconda3\lib\runpy.py", line 193, in run_module_as_main "main", mod_spec) File "C:\Anaconda3\lib\runpy.py", line 85, in run_code exec(code, run_globals) File "C:\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Anaconda3\lib\site-packages\ipykernel__init.py", line 2, in from .connect import * File "C:\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in from IPython.core.profiledir import ProfileDir ModuleNotFoundError: No module named 'IPython' [W 19:05:53.595 NotebookApp] Timeout waiting for kernel_info reply from 1433cbbf-f4b9-4dd3-be19-e91d7ee3d82f [I 19:05:55.632 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports WARNING:root:kernel 1433cbbf-f4b9-4dd3-be19-e91d7ee3d82f restarted Traceback (most recent call last): File "C:\Anaconda3\lib\runpy.py", line 193, in run_module_as_main "main", mod_spec) File "C:\Anaconda3\lib\runpy.py", line 85, in run_code exec(code, run_globals) File "C:\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Anaconda3\lib\site-packages\ipykernel__init.py", line 2, in from .connect import * File "C:\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in from IPython.core.profiledir import ProfileDir ModuleNotFoundError: No module named 'IPython' [W 19:05:58.671 NotebookApp] KernelRestarter: restart failed [W 19:05:58.671 NotebookApp] Kernel 1433cbbf-f4b9-4dd3-be19-e91d7ee3d82f died, removing from map. ERROR:root:kernel 1433cbbf-f4b9-4dd3-be19-e91d7ee3d82f restarted failed! [W 19:05:58.705 NotebookApp] 410 DELETE /api/sessions/fd456273-adb3-48cd-92f8-d531c9b8f7a8 (::1): Kernel deleted before session [W 19:05:58.709 NotebookApp] Kernel deleted before session [W 19:05:58.709 NotebookApp] 410 DELETE /api/sessions/fd456273-adb3-48cd-92f8-d531c9b8f7a8 (::1) 4.00ms referer=http://localhost:8888/notebooks/Untitled11.ipynb?kernel_name=python3

I have tried to uninstall and then reinstall ipykernel ipython, jupyter_client, jupyter_core, traitlets and ipython_genutils, as mentioned in https://github.com/jupyter/notebook/issues/1892. However, I was not able to solve the problem. any ideas? THANKS!!

**Comment by takluyver** [comment]
It looks like the crucial bit of that is `ModuleNotFoundError: No module named 'IPython'`. It can't find IPython when it tries to import it. It might be installed on a different version of Python or in a different environment.
