### ISSUE TITLE
Trouble saving Sublime text .py files on my MacBook Pro

### ISSUE THREAD

**Issue by ThomasKirkatrick** [jupyter/notebook#3438]
Having a bit of trouble saving my .py scripts on sublime text. Any advice? I am sure I am just making a simple mistake.

Thanks,

Thomas

**Comment by takluyver** [comment]
Does that involve Jupyter?

**Comment by ThomasKirkatrick** [comment]
Pardon, I should have sent this email to my instructor at Udemy.

Thomas
