### ISSUE TITLE
Jupyter Notebook- Import Error No module named Paths

### ISSUE THREAD

**Issue by konsbn** [jupyter/notebook#344]
I tried using jupyter notebook command and I got this
```Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 83, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named paths```

pip list gives me Ipython version 3.2.1 so does python -m IPython --version. I also removed the .pth files ```/usr/local/lib/python2.7/dist-packages```

**Comment by Carreau** [comment]
if you have jupyter-notebook, you should have IPython 4.0. 

how did you install ?

**Comment by konsbn** [comment]
I had IPython 4.0 but I had to downgrade it because some of the Julia's libraries were not working. ipython notebook however opens up the Jupyter Notebook perfectly fine

**Comment by Carreau** [comment]
Well but if you have 3.2.x , `ipython notebook` will not open the same application than `jupyter notebook`.

I'm not sure what in IPython can prevent julia from working...

**Comment by konsbn** [comment]
No in the ipython notebook Interact,jl works perfect but in jupyter notebook (Ipython 4.0.0) it doesn't.

**Comment by Carreau** [comment]
Ah yes, the require thing. Then stick with IPython notebook until Interact is fixed, there is not real new feature yet anyway.

**Comment by konsbn** [comment]
shucks. Thanks. @Carreau

**Comment by Carreau** [comment]
Sorry about that. Hope to get more people involved in notebook 5.x to have earlier fixes and less frustration for users like you !

**Comment by drevicko** [comment]
Commenting here rather than making a new issue, as it's related..

I just installed jupyter in a python3 virtualenv with --use-system-sitepackages. The system has ipython 3.0 for python 3, but the jupyter install didn't think to install ipython 4.x, so when I ran `jupyter notebook` I got the above error.

Seems to me something is wrong - ipython 4.x should have been a dependency and thus installed?

**Comment by takluyver** [comment]
Yes, [it should](https://github.com/ipython/ipykernel/blob/256cd3f6ac9fe35d6b438b5c497581121ee1b80f/setup.py#L83). Did ipykernel get installed?

**Comment by drevicko** [comment]
I believe so. Here's some snippets from the `pip install jupyter` output:

    Installing collected packages: ptyprocess, backports-abc, MarkupSafe, jsonschema, decorator, pyzmq, mistune, pygments, ipython-genutils, jupyter-core, terminado, tornado, jinja2, 
nbformat, traitlets, jupyter-client, ipykernel, qtconsole, nbconvert, notebook, ipywidgets, jupyter-console, jupyter
    ...
    Successfully installed MarkupSafe-0.23 backports-abc-0.4 decorator-4.0.6 ipykernel-4.2.2 ipython-genutils-0.1.0 ipywidgets-4.1.1 jinja2-2.8 jsonschema-2.5.1 jupyter-1.0.0 jupyter-
client-4.1.1 jupyter-console-4.0.3 jupyter-core-4.0.6 mistune-0.7.1 nbconvert-4.1.0 nbformat-4.0.1 notebook-4.0.6 ptyprocess-0.5 pygments-2.0.2 pyzmq-15.1.0 qtconsole-4.1.1 termin
ado-0.6 tornado-4.3 traitlets-4.0.0

Note that that's actually `pip3` as it's a python3 virtualenv.

**Comment by drevicko** [comment]
Looks to me like setuptools is getting confused?

**Comment by drevicko** [comment]
Looks to me like setuptools is getting confused? Both traitlets and jupyter-client (the other two dependencies alongside ipython>=4.0.0) are installed. Ipython 4.0 is not installed elsewhere on the system as far as I'm aware. Odd...

**Comment by drevicko** [comment]
Not sure if this is relevant: I upgraded ipython in the virtalenv to fix the problem. When I run jupyter, however, my default python kernel is python2!? I find that surprising when the default python is python3..

**Comment by takluyver** [comment]
What version of pip do you have in your virtualenv?

**Comment by drevicko** [comment]
Yes, it was 6.0.8. Current is 7.1.2
Perhaps the culprit.. 
If it still seems odd, I can repeat the process, updating pip first, to see if it still happens.
