### ISSUE TITLE
Create narrative, user-focused documentation about the nbextension system

### ISSUE THREAD

**Issue by jasongrout** [jupyter/notebook#3445]
I can't find a good user-friendly doc that tells users how the nbextension system works, how to install (with various options), enable, uninstall, and disable extensions, as well as how to troubleshoot common problems (such as extensions at different levels overriding other levels).

This issue is about creating such a doc.

**Comment by jtpio** [comment]
Closing as `nbextensions` are deprecated and Notebook 7 uses the same extension system as JupyterLab.

JupyterLab has a nice tutorial for creating an extension: https://jupyterlab.readthedocs.io/en/latest/extension/extension_tutorial.html

There is also the extension example repo: https://github.com/jupyterlab/extension-examples

Thanks!
