### ISSUE TITLE
#3304 is not part of the Jupyter 5.4.1 point release

### ISSUE THREAD

**Issue by charlieeeeeee** [jupyter/notebook#3449]
Hi,

I noticed you guys released Jupyter 5.4.1, it claims the following fix is part of the release,

#3304  Don't trash files on different device to home dir on Linux

however, after checking the filemanager.py, it seems it's not part of the Jupyter 5.4.1 package. Is it missed?

Thanks,
Charlie

**Comment by takluyver** [comment]
What is making that claim? The [release notes](http://jupyter-notebook.readthedocs.io/en/stable/changelog.html) describe just one security fix, and #3304 is milestoned for 5.5.

We're still hoping to release 5.5 soon; 5.4.1 was done especially to fix a security vulnerability.

**Comment by charlieeeeeee** [comment]
@takluyver  Sorry this is my bad. I misread the release tag.

116 commits to master **since this tag**.

I guess this fix is not in 5.4.1. Sorry for the confusion. Is there an estimated date for 5.5 release?

**Comment by takluyver** [comment]
I'm aiming for 'soon', but I'm also moving to another country on Saturday, so I'm a bit preoccupied. @gnestor @Carreau and @minrk are the other people who can help make a release happen.

There [a list of open issues marked for 5.5](https://github.com/jupyter/notebook/milestone/27). But it's usually not all that accurate: we may bump things off that list to a later release if it's too hard to get them sorted, and we may add things to it if they're important or easy to get fixed.
