### ISSUE TITLE
Run notebook app from source?

### ISSUE THREAD

**Issue by ericjang** [jupyter/notebook#345]
What's a good development workflow for running the notebook from source, so I can avoid re-running ```pip install --pre -e .``` every time I make some changes?

http://jupyter-notebook.readthedocs.org/en/latest/development.html

**Comment by Carreau** [comment]
If you `pip install -e .` (no need for the `--pre`), you can just restart the server, and it should work. No need to reinstall. If you touch the js or css, you might need to rebuild it.

On master and developpement install you can add the `--NotebookApp.ignore_minified_js=True` flag that avoid to rebuild some JS. 

Where did you saw the `--pre` thing ?

**Comment by ericjang** [comment]
Thank you.
I saw the ```--pre``` thing at 
https://github.com/jupyter/notebook/blob/master/README.md

**Comment by Carreau** [comment]
Ok, thanks ! Happy patching, looking forward to your pull requests. I'll update the readme
