### ISSUE TITLE
Timeout waiting for kernel to reply, slow kernal starting takes 5 minutes.

### ISSUE THREAD

**Issue by pjanowski** [jupyter/notebook#3455]
I am facing this issue similar but different to what others have posted on the "timeout waiting for kernel to reply". When I spin up a new or open an exisiting notebook, it takes about 5 minutes for the kernel to be ready. 

```
[I 10:13:58.952 NotebookApp] Creating new notebook in
[I 10:14:46.786 NotebookApp] Kernel started: 82839c78-e0e4-4add-9ec9-4eedbf377f44
[I 10:15:07.699 NotebookApp] Saving file at /Untitled.ipynb
[W 10:15:17.162 NotebookApp] Timeout waiting for kernel_info reply from 82839c78-e0e4-4add-9ec9-4eedbf377f44
[I 10:16:17.706 NotebookApp] Saving file at /Untitled1.ipynb
[I 10:17:41.304 NotebookApp] Adapting to protocol v5.1 for kernel 82839c78-e0e4-4add-9ec9-4eedbf377f44
```
At first the notebook is responsive but running cells does nothing. After the "timeout waiting for kernel_info" message, running cells get the * symbol and appear to be running and notebook seems to be busy. Only after the "Adapting to protocol v5.1" message do the cells execute and notebook functions properly.

This is miniconda on Windows 10 executing both via Command Prompt, Powershell and Git Bash. I tried to reinistall both jupyter and all of Anaconda but still the same.

**Comment by leviboyles** [comment]
I'm also seeing issues like this; on Win10, already tried reinstalling anaconda/jupyter.  I've also seen this exception:

```
[E 14:16:56.891 NotebookApp] Exception restarting kernel
    Traceback (most recent call last):
      File "C:\Users\leboyles\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\kernels\handlers.py", line 85, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "C:\Users\leboyles\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\Users\leboyles\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
    tornado.gen.TimeoutError: Timeout waiting for restart
[E 14:16:56.901 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|d691f518|f3c86c75e7236cb9d2dab41149464224|1521665945",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36",
      "Referer": "http://localhost:8888/notebooks/Documents/BayesianOptHighDimGaussianHallucinatingNeutral-Copy6.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|d691f518|f3c86c75e7236cb9d2dab41149464224|1521665945; username-localhost-8888=\"2|1:0|10:1521666542|23:username-localhost-8888|44:NjhlYjgzNGU0YWE1NGU3NWI0M2IxOGEzODUzMzA5ZjM=|fb220ddab09310512904d7f6e9724a4189066e77df79f8b03f5c2435a544e80a\""
    }
```

**Comment by takluyver** [comment]
Do you have any security software running? Various security packages have caused mysterious problems for Jupyter's connections.

**Comment by pjanowski** [comment]
I'm sure there is company stuff running in the background but nothing explicit besides Windows Defender that I am aware of. In any case, after experiencing this difficulty for about 2 weeks, it resolved itself on it's own. Happened on a Tuesday too, so go figure.

**Comment by takluyver** [comment]
That reminds me of the infamous [printing on Tuesdays](https://bugs.launchpad.net/ubuntu/+source/cupsys/+bug/255161) bug.

**Comment by pjanowski** [comment]
LOL, yeah. I think it's correlated to a Windows update which get pushed on Tuesdays in this case though.

**Comment by stmax82** [comment]
I'm constantly running into this problem on my home system.. exact same errors. I have no security software except Windows Defender..
