### ISSUE TITLE
Feature Request: Open current folder in Finder

### ISSUE THREAD

**Issue by hongshaoyang** [jupyter/notebook#3460]
Wouldn't it be nice to have a button that just opens the current working folder in Finder? 

Say I want to navigate to some other folder not currently visible to Jupyter Notebook. For e.g. you've reached the root directory but this other file is in some other folder that isn't visible to Jupyter. It would be nice to have a small, non-intrusive button at the side where you just click it, and it opens up a Finder window at the current working folder. Then just navigate from there.

**Comment by takluyver** [comment]
This would be convenient, but maybe as an extension. I don't know of a good way to do the equivalent thing in a cross platform way, and it may not be easy for Jupyter to tell whether it's running on your local computer or on a remote server.
