### ISSUE TITLE
Pass system variables in kernel.json

### ISSUE THREAD

**Issue by npavlovikj** [jupyter/notebook#3469]
Hi,

I am working on a Linux platform and I want to pass system variable as part of the environment variables I set for the kernel, _kernel.json_, e.g. _$USER_:
**"env": { "PREFDIR": "/tmp/$USER/prefs" }**

I was wondering if this is possible, and if so, how can I do that ?

Thank you,
Natasha

**Comment by takluyver** [comment]
It's not possible with `kernel.json`. You'll need to run some code when the kernel starts to update the environment variables. If it's an IPython kernel, you can do that with a [startup file](http://ipython.readthedocs.io/en/stable/interactive/tutorial.html#startup-files). For other kernels, you'll need to figure out a way to run code when it starts. If you're writing your own kernel, it should be easy.

**Comment by npavlovikj** [comment]
Thanks @takluyver - this is helpful!
