### ISSUE TITLE
jupyter / notebook pandas importation error

### ISSUE THREAD

**Issue by Arturo9561** [jupyter/notebook#3472]
Hey, I am an windows os user and need help of the execution of this file. I pretty much do not understand this tool unfortunately. At the bottom is the error message I get after writing this code.

    In[1] : import pandas pd
    ----------------------------------------------
    Error message :File "<ipython-input-1-6bfc1f40d5ca>", line 1
    --------------------------------------

Thanks from now

**Comment by takluyver** [comment]
I think you meant `import pandas as pd`.

**Comment by Arturo9561** [comment]
Yes, I meant what you said actually. I fixed the problem, there was a mismatch of the path that I was supposed to work, with my current directory.
Thanks
