### ISSUE TITLE
UX Bug when uploading multiple large files

### ISSUE THREAD

**Issue by mckev-amazon** [jupyter/notebook#3473]
Hello!  I noticed a bug when attempting to upload more than 1 large file using the Jupyter UI.

Steps to reproduce:

1. Open Jupyter home page (/tree)
2. Click Upload
3. In the browser's file upload dialog box, select two large files simultaneously, and then click OK/Open.
4. Jupyter will ask to confirm "Large file size warning" twice, once for each file, click OK to each.
5. Observe that two new entries are displayed in the list, with Upload/Cancel buttons next to them, but both entries are for the FIRST file.  (The second file is not listed.)

Expected:

5. Both files should be displayed in the tree with Upload/Cancel buttons.  There should be no duplication.

Thank you!

**Comment by takluyver** [comment]
Thanks - I think #3477 should fix this.
