### ISSUE TITLE
Token authentication broken?

### ISSUE THREAD

**Issue by whllnd** [jupyter/notebook#3480]
Hi all,

token authentication for Chrome seems to be broken on my machine. After executing "jupyter notebook" it directly opens a tab showing the document content. On Firefox, I am prompted to input a token or password first, as expected.

If this is already known or not an issue at all, because I am too stupid, my apologies.

Using Ubuntu 14.04, jupyter 4.4.0, Chrome 65.0.3325.181, Firefox 59.0.2.

**Comment by takluyver** [comment]
Hi @whllnd !

That sounds like what it's expected to do. When you run `jupyter notebook` and it opens a browser for you, it passes the token to that browser in the URL (actually it's a separate token which only works a single time). The browser uses the token to get a cookie, and a redirect means you can't see the token in the address bar.

When you open it in a second browser, it's not authenticated, so you see the login page.

If you right click on the Jupyter logo in the browser that is already authenticated, you can use 'copy link' to get a link which includes the token. Paste that into another browser, and it bypasses the login page.

**Comment by whllnd** [comment]
Ok, cool! Then apologies for my ignorance!

**Comment by takluyver** [comment]
np, we're all ignorant of something ;-)
