### ISSUE TITLE
Can't create any new python 2/3 file in jupyter notebook by clicking on new tab in jupyter notebooks

### ISSUE THREAD

**Issue by Sumit-Kap** [jupyter/notebook#3483]
Hi, 
I have created a virtual environment and installed anaconda with python 3.5 after installing that when i am trying to open jupyter notebooks using command line it get's open on port 8888 but I am not able to perform any action on clicking any anchor tag or button on jupyter notebook page and I get the following error when I navigate to my terminal
[I 13:21:31.804 NotebookApp] [nb_conda_kernels] enabled, 4 kernels found
[I 13:21:31.819 NotebookApp] Writing notebook server cookie secret to /run/user/1001/jupyter/notebook_cookie_secret
[I 13:21:32.505 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 13:21:32.505 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 13:21:32.534 NotebookApp] [nb_conda] enabled
[I 13:21:34.447 NotebookApp] [nb_anacondacloud] enabled
[I 13:21:34.479 NotebookApp] Serving notebooks from local directory: /home/shopclues/Desktop/Python
[I 13:21:34.480 NotebookApp] 0 active kernels 
[I 13:21:34.480 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 13:21:34.480 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Fontconfig warning: "/etc/fonts/fonts.conf", line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
[4797:4838:0330/132135.300003:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
Created new window in existing browser session.

I am using ubuntu 16.04 os.

**Comment by takluyver** [comment]
None of those messages sound like they should cause the problem you describe. Are there any errors in the browser's Javascript console when you try clicking on things?

**Comment by Sumit-Kap** [comment]
I am getting this error-:
An error occurred while retrieving installed packages.
EnvironmentLocationNotFound: Not a conda environment: /home/shopclues/anaconda/envs/anaconda

I can understand that this error corresponds to anaconda not being installed in my system but because of this issue i created other virtual environment in which python 3.5 was installed but still nothing was happening when i was clicking on the buttons present on the jupyter notebook page.

**Comment by takluyver** [comment]
That sounds like it might be a problem with some of anaconda's integration - Jupyter doesn't do anything with conda directly. It might be worth asking on anaconda-issues: https://github.com/ContinuumIO/anaconda-issues/

**Comment by Sumit-Kap** [comment]
Okay Thanks,
will raise the issue there.

**Comment by takluyver** [comment]
Here's the follow up issue: https://github.com/ContinuumIO/anaconda-issues/issues/9065
