### ISSUE TITLE
Multiple user access to their ipython notebook

### ISSUE THREAD

**Issue by vinayakumarr** [jupyter/notebook#3488]
We have to conduct an online exam. We have to provide an ipython notebook. Each student can only be able to see their notebooks. How to do this?

**Comment by takluyver** [comment]
[JupyterHub](http://jupyterhub.readthedocs.io/en/latest/) is probably what you're looking for if you want to host it yourself. You can use it with [nbgrader](http://nbgrader.readthedocs.io/en/stable/) for managing assignments if that fits with how your exam works.

If you prefer to pay for someone else to run the systems, [CoCalc](https://cocalc.com/) is a hosted service that offers similar features. It's not affiliated with Jupyter, but we know the person who runs it.

**Comment by williamstein** [comment]
> the person who runs it.

I'm the person who runs it, and I'm happy to answer any questions.  The free version of CoCalc provides enough functionality for just running an exam...    

You would:

1. Ceate a project in Cocalc
2. Make a new course (+New --> Course)
3. Add the students by email -- right when you do this, (a) the students will get emailed invites, and (b) each will get their own project created for them (which is a Docker image).
4. Create an assignment folder containing the ipynb file(s) for the exam, and click a button to push it out. 
5. Let students work on exam.  NOTE: Cocalc has its own rewrite of jupyter, which you get by default if you open an ipynb file.  However, you can also go to a project, click "Settings", then click "Plain Jupyter Server" and just get the 100% standard Jupyter project version of Jupyter, in case there is something different.   We also provide many preconfigured kernels.
6. Collect the assignment, grade it, and return it.

See https://tutorial.cocalc.com/ for more details.  The above will all work for free.
