### ISSUE TITLE
LaTeX \newcommand no longer seems to work

### ISSUE THREAD

**Issue by dialkforkaushik** [jupyter/notebook#349]
I upgraded to IPython 4.0.0 and (correspondingly) now use `jupyter notebook` to work with my Notebooks. However, I find that my Markdown cells with LaTeX `\newcommand` no longer seems to set up a reusable macro. (This was absolutely fine in IPython 3.4 from which I had migrated.) What am I missing? Or, is this some bug? Any help would be appreciated! Thanks!

Here's a very simple Notebook markdown and its output.

````$\newcommand{innerproduct}[2]{\langle #1, #2 \rangle}$````

![jupyternb_nwcmmnd_mnwe](https://cloud.githubusercontent.com/assets/5288070/9505329/537f16f0-4c07-11e5-9370-9cd1763471b0.png)

**Comment by Carreau** [comment]
does https://github.com/jupyter/notebook/pull/324 fix it ?

**Comment by Carreau** [comment]
Assuming closed by #324 as now we ship `newcommand.js`

**Comment by fabiofortkamp** [comment]
This does not seem to be really fixed. I'm running Jupyter 4.0.6 (installed with Anaconda) and I can't define new commands. The cell were it is defined has the same strange output mentioned by @dialkforkaushik and the cells were the newly defined macro is used are not rendered; I just get the command name in red, like an error.

**Comment by hlin117** [comment]
It looks like this post implies that `\newcommand` doesn't work anymore. I think the documentation here needs to be updated:
http://jupyter-notebook.readthedocs.org/en/latest/notebook.html#markdown-cells

**Comment by goerz** [comment]
So how does `newcommand.js` work? How exactly do I define a new TeX macro in a notebook?
