### ISSUE TITLE
Terminal session redirects main page

### ISSUE THREAD

**Issue by bastorer** [jupyter/notebook#3496]
Hello,

Opening a terminal session (New -> Terminal) redirects the main Jupyter page to home (~), which is also the starting location of the terminal. Would it be possible to have the main page remain at its location and set the starting directory for the terminal be the current directory of the main page?

**Comment by takluyver** [comment]
Redirecting the dashboard is definitely a bug that we should fix.

Launching the terminal in the current directory would be a handy feature, though I don't think it's currently easy to implement.

**Comment by takluyver** [comment]
#3497 fixes the part where it resets the file browser. We've already got issue #2018 for opening a terminal in the current directory, so the PR will close this issue when it's merged. Thanks for pointing it out before we made the next release!

**Comment by bastorer** [comment]
That's great, thanks!
