### ISSUE TITLE
Support recursive directory creation on PUT/POST `/api/contents/{path}`

### ISSUE THREAD

**Issue by calbach** [jupyter/notebook#3498]
Would be nice if there were a request option [here](https://github.com/jupyter/notebook/blob/5fd7d52ec2ab5bb25b16eb9f9a4ab93b93af421f/notebook/services/api/api.yaml#L199) to recursively create any parent directories which do not yet exist.

Use case: I currently have some code (running outside the notebook server), where I'd like to create a file nested under a particular folder structure (two folders). Currently I need to make 3 serial Jupyter Server PUT requests to achieve this.

**Comment by jtpio** [comment]
Closing as the Jupyter Server now lives in its own repo: https://github.com/jupyter-server/jupyter_server

You may want to open the issue there if still relevant, thanks!
