### ISSUE TITLE
In markdown cell, How to "link" to open txt file in the notebook file editor ?

### ISSUE THREAD

**Issue by davidtrem** [jupyter/notebook#350]
Hello,
In markdown cell [file](./file.txt) allows to visualize a file cliquing the rendered link.
Is there any way or syntax to open the file within the notebook file editor
rather than just visualizing it ?
Thanks in advance,
David

**Comment by Carreau** [comment]
No, not yet. We are thinking on how we could do it, but that's far from easy to do.

**Comment by mauro3** [comment]
Just using the link to the file in the file-browser may work, e.g. `http://localhost:8888/edit/some-file.txt`.  Although, this will not work on all setups, but should be ok for local notebooks.

**Comment by mebersole** [comment]
@mauro3 is it possible to pass the language type to open the file with using the `http://localhost:888/edit/somefile` method?

**Comment by gnestor** [comment]
I'm going to close this due to inactivity and in the interest of getting our issues under control. @mebersole Feel free to open a new issue regarding:

> is it possible to pass the language type to open the file with using the http://localhost:888/edit/somefile method?
