### ISSUE TITLE
unable to start Jupyter notebook

### ISSUE THREAD

**Issue by EmilioSantias** [jupyter/notebook#3503]
Hi, I can't launch neither Anaconda Navigator nor Jupyter Notebook, How can I fix that? THANKS IN ADVANCE.
dlopen(/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/constants.cpython-36m-darwin.so, 2): Symbol not found: __ZNKSt11logic_error4whatEv
  Referenced from: /anaconda3/lib//libc++.1.dylib
  Expected in: /usr/lib/libc++abi.dylib
 in /anaconda3/lib//libc++.1.dylib

**Comment by takluyver** [comment]
If you can't launch anaconda navigator either, it's probably something wrong in Anaconda. Try here: https://github.com/ContinuumIO/anaconda-issues/

**Comment by takluyver** [comment]
For anyone else encountering a similar problem, the follow up was here: https://github.com/ContinuumIO/anaconda-issues/issues/9109

Sadly It looks like the Anaconda team are getting rather short tempered with anyone who doesn't fill out the issue template.
