### ISSUE TITLE
Regarding naming a specific name for jupyter notebook and different versions of notebook

### ISSUE THREAD

**Issue by cy16f01** [jupyter/notebook#3506]
Hello,
In the terminal, if i type jupyter notebook, it will connect to a server and opens an untitled.ipynb and if i want to close the kernel, then in the terminal if  i type cntrl+c and then y, the kernel closes. Next time if i want to open a new notebook, then it will be automatically named as Untitled1.ipynb.
So,
1) How can i assign a specific name for the notebook i want to run (such that if i name each .ipynb files differently, it is easy for identification...)
2) For running jupyter notebook, it should connect every time to the server only..?? Is there no possibility to just open within the system (if opened in the server there is a chance of data breaching..??) or sometimes if there is no internet, then it is not possible to run the jupyter notebook right.?

How do i solve these issues..??

Any suggestions are appreciated.

Thank you.

**Comment by takluyver** [comment]
When you're in a notebook, you can click on the name (*Untitled*) at the top of the page to change it.

It opens in your browser, but it is actually running on your own computer. The URL should start with something like `http://localhost:8888` - *localhost* means your own computer. It's convenient for us to use HTML for the interface.

**Comment by cy16f01** [comment]
Thank you sir,
And i have a new question,
I have installed latest version of conda, pip as:-
```
workstation1@Dilip:~$ python --version
Python 3.6.4 :: Anaconda, Inc.
workstation1@Dilip:~$ conda --version
conda 4.4.10
workstation1@Dilip:~$ pip --version
pip 9.0.3 from /home/workstation1/anaconda3/lib/python3.6/site-packages (python 3.6)
```

Now my questions are, 
In older versions
```
workstationx@abc:~$ python --version
Python 3.6.3 :: Anaconda, Inc.
workstationx@abc:~$ conda --version
conda 4.4.34
workstationx@abc:~$ pip --version
pip 9.0.1 from /home/workstation1/anaconda3/lib/python3.6/site-packages (python 3.6)
```
1] The environment is different, and in the older versions if i type in terminal "jupyter notebook", it will open a new kernel. And if there is huge data printed, it forms a background stuff (the whole data will be within a space unlike the new one.) where i can scroll down within a certain space....
2] In the newer version, if i give run the code for water dynamics, i am unable to see the % status which defines how much has the code run as in(" MDAnalysis.analysis.hbonds: INFO     Starting analysis (frame index start=0 stop=10001, step=1)
MDAnalysis.analysis.hbonds: INFO     Starting analysis (frame index start=0 stop=10001, step=1)
HBonds frame 100: 100/10001 [10.0%]" as an example.)

How do i solve this issue..?? Here are the two kernels (old and new).

For eg, in ln 67, in the code:-
```python 
import pandas as pd
df = pd.DataFrame.from_records(h.table)
print (df)
```
The output values are written, but in newer one it fills up the whole page, whereas in old one it goes in background, and i can scroll down without consuming the whole page....

http://localhost:8889/lab  --> corresponds to latest version of pip, conda installed
http://localhost:8888/notebooks/Untitled1.ipynb#  --> corresponds to old version of pip, conda installed

My jupyter versions are jupyter 4.3.0 (old one) and 4.4.0

Any suggestions are appreciated.

Thank you.

![old](https://user-images.githubusercontent.com/30516979/38414815-388d742c-39ad-11e8-83de-9617de3f844e.png)
![new1](https://user-images.githubusercontent.com/30516979/38414816-38e4c92a-39ad-11e8-9347-723ea8d3adce.png)
![new](https://user-images.githubusercontent.com/30516979/38414818-3916f81e-39ad-11e8-911a-c0d108e16ce4.png)

**Comment by takluyver** [comment]
The new interface you're using there is JupyterLab, which is in beta. If you need to switch back to the classic interface, you can change the URL from `/lab` to `/tree`.

**Comment by cy16f01** [comment]
Running ```jupyter notebook <filename.ipynb>``` launches it in lab, while ```jupyter notebook``` launches the classic notebook.
Is it possible to restore the default behaviour of ```jupyter notebook <filename.ipynb>``` command, i.e. starting classic jupyter notebook, not jupyter lab?
Or every time i give  ```jupyter notebook <filename.ipynb>``` i should change the URL from ```/lab``` to ```/tree```...?? and if i run any code/do any modifications and save it will it be saved correctly..??

Any suggestions...?

Thank you.

**Comment by takluyver** [comment]
Sorry, I don't know. Whatever code is changing that is in [jupyterlab](https://github.com/jupyterlab/jupyterlab).
