### ISSUE TITLE
Feature request: a way to type in file paths

### ISSUE THREAD

**Issue by Yurlungur** [jupyter/notebook#351]
When in Jupyter notebook, the file tree starts in the current working directory. Navigating into a deeper subdirectory can be very tedious. And navigating to a directory higher up in the system than the current working directory is impossible at the moment. It would be extremely nice to have:
1. A ".." link in the current working directory, even if it is the directory where jupyter notebook was called.
2. A way to type the path of a file or directory you'd like to access, meaning you don't have to click the links to get there.

**Comment by Carreau** [comment]
1) No for security reason, the notebook is chrooted on purpose where it is launched and will issue 404 on any hidden directory. 

2) Yes, but someone have to implement it. A dashboard overhaul in general would be nice.

**Comment by Yurlungur** [comment]
Hi Carreau,

Thanks for the reply. I can understand that. (1) would be much less cumbersome if (2) were implemented anyway. I don't know if I have the skills (or time) to help overhaul the dashboard. But if someone decides to push that, I'd be happy to help in any way I can.

**Comment by Carreau** [comment]
> Thanks for the reply. I can understand that. (1) would be much less cumbersome if (2) were implemented anyway. I don't know if I have the skills (or time) to help overhaul the dashboard. But if someone decides to push that, I'd be happy to help in any way I can.

Sure no problem, some IBM dev did a demo yesterday of search/indexing of notebook [on video](https://youtu.be/SJiezXPhVv8).

We are looking in bringing that into the core. 

Thanks for your feedback !

**Comment by david-zwicker** [comment]
Would it be (or is it already?) possible to show the current path in the notebook dashboard? I tend to use multiple servers started from different directories, which then look all alike in the browser windows. It would be easier to distinguish the different notebook dashboards if their root directory was mentioned somewhere. I could open a separate feature request if it doesn't fit here.

**Comment by Carreau** [comment]
> Would it be (or is it already?) possible to show the current path in the notebook dashboard?

That's what the discussion in https://github.com/jupyter/notebook/issues/422 is for. But there are some security/implementation details to be discussed.

**Comment by JamiesHQ** [comment]
Jupyter team: what's the next step on this issue? Is there development work to be done? Thanks!

cc: @gnestor

**Comment by gnestor** [comment]
There is potential for suggestion #2. This would be a good one for a first-time contributor...

**Comment by gnestor** [comment]
@Yurlungur A lazy solution is to type the path in the address bar of the browser. You can even get autocomplete if you have navigated to the path before and your browser supports history-based autocomplete.

**Comment by Yurlungur** [comment]
@gnestor ah, I see. Thanks for the tip!

**Comment by gnestor** [comment]
Sure thing! You can also use your browser's bookmarks to bookmark specific directories or notebooks, as discussed in https://github.com/jupyter/notebook/issues/545#issuecomment-297188047.

**Comment by rainwoodman** [comment]
Keep me up to date on this. I think being able to type a path in the notebook interface is much more convenient than in the URL bar, especially we have the potential to add true auto-completion with in the Notebook UI for unvisited notebooks.

**Comment by gnestor** [comment]
The core development team is focused mainly on JupyterLab nowadays so new features like this (to the classic notebook) will need to come from the community, so would you like to give this a shot, @rainwoodman?

**Comment by rainwoodman** [comment]
Unlikely -- it is not a feature that I can't live without. I will take a look when I gather sufficient momentum. But if the future is in JupyterLab I don't see a good reason to spend time improving the traditional notebook interface neither.

**Comment by Madhu94** [comment]
@Carreau @gnestor  Is this still open ? I would like to work on this.

**Comment by gnestor** [comment]
@Madhu94 Absolutely!

**Comment by Madhu94** [comment]
@gnestor Great! I'll start looking into it, this will be my first PR to Jupyter..

**Comment by Madhu94** [comment]
Please assign this to me.

**Comment by gnestor** [comment]
It looks like I can't assign you unless you are in the jupyter org. No worries, just go ahead and submit the PR and we will add you afterwards :+1: Thanks for your help!!!

**Comment by Madhu94** [comment]
@gnestor Sure!
