### ISSUE TITLE
Error loading notebook

### ISSUE THREAD

**Issue by msseibel** [jupyter/notebook#3510]
When I try to load [this](https://github.com/sthalles/blog-resources/blob/master/dcgan/DCGAN.ipynb) notebook Im receiving the following error:

beginning of error log
Unreadable Notebook: path_to_notebook\DCGAN.ipynb UnicodeDecodeError('utf8', '{\r\n "cells": [\r\n {\r\n "cell_type":... 

....
"nbformat_minor": 2\r\n}\r\n', 5316, 5317, 'invalid start byte') 
end of error log

It does not seem, that the notebook is the source of the error, since I could start it on another device. 
Im using python35 and jupyter notebook --version is 5.4.1

Any idea where to start looking for the error?
thanks in advance

**Comment by msseibel** [comment]
I tried to convert the notebook into .pdf via
jupyter nbconvert --to pdf path_to_notbook\DCGAN.ipynb
and received more information about the error:
...
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 15892: invalid start byte

Some unknown reason replaced this sign  ' with ` (0x91) and ´(0x92). 
Notebook is now working, but
 any ideas why this bug appeared?

**Comment by takluyver** [comment]
Is it possible that the notebook had been opened and saved in a word processor at some point? These programs often automatically convert 'simple quotes' to `fancy quotes´, which makes code invalid. If you need to see or change the raw data of a notebook file, use a proper text editor (like Atom, or Notepad++, or 1001 other options), not a word processor.

**Comment by msseibel** [comment]
yes, that caused the error .
