### ISSUE TITLE
Custom front-end extensions Issue

### ISSUE THREAD

**Issue by dabuside** [jupyter/notebook#3517]
Following the [official guide](https://jupyter-notebook.readthedocs.io/en/latest/extending/frontend_extensions.html) ,extension only get loaded when notebook page but not in dashboard(file broswer)
add --section='common' to the guide

**Comment by takluyver** [comment]
Do you want to make a PR? The source of that page is here: https://github.com/jupyter/notebook/blob/master/docs/source/extending/frontend_extensions.rst

**Comment by takluyver** [comment]
Closed by #3525
