### ISSUE TITLE
notebook not showing matplotlib plot

### ISSUE THREAD

**Issue by ggrrll** [jupyter/notebook#3523]
Hi, 

in the last days I started  to have issues with my notebooks not showing some plots - I get outputs like `[<matplotlib.lines.Line2D at 0x16b6dc2e8>]` (similarly to #1620 )

In particular, I have a plot disappearing when I add labels such as `plt.xlabel`  - without that it's shown regularly 

I always run `%matplotlib inline`  at the beginning of my notebooks

Any idea of what is happening?

Thanks for your support.

ps: on safari 11.0.3 and notebook 5.4.1

**Comment by ggrrll** [comment]
ok,  it seems that this problem disappear when I comment (do not run)

```
# from IPython.core.interactiveshell import InteractiveShell
# InteractiveShell.ast_node_interactivity = "all"
```

 - which I actually really like, as I don't have to `print(my_out)`  at every line ...anyways

... any idea if there is a conflict there and how to avoid it?

Thanks

**Comment by junhaowww** [comment]
Hi. I like to set it "all". Finally, I found that you can put a semicolon after "plt.show()"......... That's great.

**Comment by ggrrll** [comment]
ok,

`plt.show();` seem to solve the issue (for now) – thanks @junhaowww  !

**Comment by ggrrll** [comment]
well, 


apparently `plt.show();` doesn't seem to work always...no idea what's going on...

**Comment by junhaowww** [comment]
I see. You can add `;` to the last line of codes. For example:

1. normal case
``` python
a = 1
b = 1
# do plotting
plt.show();
```
2. special case
``` python
a = 1
b = 1
# do plotting
plt.show()
# if plt.show() is not on the last line
a = 2;       # like this
```

**Comment by ggrrll** [comment]
as soon as I add other plotting commands such as `plt.xlabel` no plot is shown with both 
`plt.show()` or `plt.show();`

... there must be some sort of conflict with those commands and the interactiveshell...

**Comment by ggrrll** [comment]
ok, it seems to be unrelated to those shell settings. It's probably related to the matplotlib backend settings

I usually use:

```python 
%matplotlib inline
sns.set_context('notebook')
%config InlineBackend.figure_format = 'retina'
```

in a simple example I am working for instance, 

`plt.hist(my_panads_series) ` did not work, while `my_panads_series.hist()` did ... again, no idea ...

**Comment by takluyver** [comment]
Unfortunately, I think this is the downside of trying to make plot displaying 'just work' - when it doesn't work, it can be pretty mystifying to figure out what's going wrong. I don't have any great ideas at the moment, sorry. :-(

**Comment by ggrrll** [comment]
@takluyver thanks anyway :) – I will update it in case  I figure out something more

**Comment by nazariyv** [comment]
I cannot plot with axes as well. axes.plot() return a list with a Lines object... No idea what is going on...

**Comment by manujchandra** [comment]
Splitting matplotlib statements into multiple Jupyter input cells may cause nothing to appear. Check if all your statements are in the same cell.

**Comment by shanshiner** [comment]
> multiple
Yes! Put all in one cell and the pic came out!

**Comment by lionlhy** [comment]
hi,@ggrrll, have you solved this problem yet ?
I met this problem recently when using the plt.hist() for the histgram, and the dataset read from mysql. Hoping for your reply. :)

**Comment by ggrrll** [comment]
The problem was solved after few weeks since then (no idea how),  but I still left it open in case other people had similar issue ... -- we can close  I guess

**Comment by alanflanders** [comment]
+1
This all worked fine just this morning and then suddenly getting an issue while working on the EDX DAT 228 course for Azure ML.
![image](https://user-images.githubusercontent.com/10327561/58355741-9b458580-7e32-11e9-847b-635ad0f71068.png)

**Comment by ugurkanates** [comment]
I still does this problem , charts appear but values does not.
empty charts simply

**Comment by deichdeich** [comment]
I'm having a similar problem.  When I do `fig = plt.figure()`, a blank figure pops up, and then I try to add things to it, and nothing happens when I do a `plt.show()` at the end.

**Comment by lionlhy** [comment]
Your plot has been export successfully but without showing in jupyter. %matplotlib inline , insecting this will make it .




            
            
                
                    
                            
                                
                            
                            
                                xiyu lin
                            
                    
                        
                            
                                    邮箱：lionlhy@gmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 09/24/2019 00:14, profPlum wrote: Hey I'm experiencing this issue still. This issue appears not to be resolved. I'm using the latest version of python and when I try to get plots it either doesn't show or gives a textual description of the plot!d


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jupyter/notebook/issues/3523?email_source=notifications\u0026email_token=AI2YGEGZKF7OZCYW2OEWU7DQLDTQBA5CNFSM4EZZ3ILKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7LNBZQ#issuecomment-534171878",
"url": "https://github.com/jupyter/notebook/issues/3523?email_source=notifications\u0026email_token=AI2YGEGZKF7OZCYW2OEWU7DQLDTQBA5CNFSM4EZZ3ILKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7LNBZQ#issuecomment-534171878",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rafaelgdp** [comment]
Man, this issue is not resolved... I'm facing this nonsense today!!! November 27th, 2019!! I have no idea why the plots won't show! I'm using matplotlib in a colab notebook. :/

**Comment by rafaelgdp** [comment]
I take it back. I just tried @lionlhy suggestion with the "%matplotlib inline" thing and it miraculously worked! Thanks! :P

**Comment by chourasiaankur1** [comment]
if you are using %matplotlib notebook
do use-
%matplotlib inline

**Comment by formazione** [comment]
In jupyter notebook it works, in jupiter lab it does not... why???

**Comment by danielmlow** [comment]
An issue with plt.bar() is that if there are too many bars, they are not visible. Try increasing the figure size:
plt.figure(figsize=(20,17))

 or reduce x,y to see if they start appearing

**Comment by CBD88** [comment]
> I take it back. I just tried @lionlhy suggestion with the "%matplotlib inline" thing and it miraculously worked! Thanks! :P

Where you have used "%matplotlib inline"? Just above the "python run_file.py"?

**Comment by raihan010204** [comment]
[
![Screenshot (1)](https://user-images.githubusercontent.com/60668460/73775923-0a8cbb00-47b1-11ea-83eb-a12c425fe812.png)
](url)
My plt.xlabels and plt.ylabels is not working .may i know ??why

**Comment by fsc137** [comment]
Try putting all plotting commands in one cell, with the last command in the cell being:

plt.show()

Sometimes this is not necessary --- the plot will show regardless, but it seems to fix the problem for me.

**Comment by ihamieh** [comment]
I'm having the same issue... when I make a change of the parameters the plots wont change and when I rerun or reload... i lose all the plots on Jupyter! 

![Screenshot from 2020-03-27 13-51-45](https://user-images.githubusercontent.com/593494/77785243-482ff680-7032-11ea-948b-59b11987c665.png)

**Comment by formazione** [comment]
> I'm having the same issue... when I make a change of the parameters the plots wont change and when I rerun or reload... i lose all the plots on Jupyter!
> 
> ![Screenshot from 2020-03-27 13-51-45](https://user-images.githubusercontent.com/593494/77785243-482ff680-7032-11ea-948b-59b11987c665.png)

what version of python are you using?

**Comment by ihamieh** [comment]
> > I'm having the same issue... when I make a change of the parameters the plots wont change and when I rerun or reload... i lose all the plots on Jupyter!
> > ![Screenshot from 2020-03-27 13-51-45](https://user-images.githubusercontent.com/593494/77785243-482ff680-7032-11ea-948b-59b11987c665.png)
> 
> what version of python are you using?

I have Python 2 & 3 installed on my computer. It's showing Python 2 on the top right corner on my figure same as yours!

**Comment by Lotfey** [comment]
this link is useful, It worked for me
https://github.com/matplotlib/ipympl

**Comment by Klaviersonate** [comment]
> > I take it back. I just tried @lionlhy suggestion with the "%matplotlib inline" thing and it miraculously worked! Thanks! :P
> 
> Where you have used "%matplotlib inline"? Writing just above the command line of google colab where i run the file "!python run_file.py" is not worked for me. What may be the solution for google colab?

**Comment by Klaviersonate** [comment]
> > I take it back. I just tried @lionlhy suggestion with the "%matplotlib inline" thing and it miraculously worked! Thanks! :P
> 
> Where you have used "%matplotlib inline"? Writing just above the command line of google colab where i run the file "!python run_file.py" is not worked for me. What may be the solution for google colab?

I'm having the same issue，how did you solve it，looking forward to your reply

**Comment by gengishkhan** [comment]
I got this issue  in my environment. When I combine code in all cells into one. It works! But I believe that this issue is not yet solved.

**Comment by lminer** [comment]
I have this issue. Using the semicolon after `plot` "fixes" it, but seems like a bug if that's the workaround.

**Comment by nesergen** [comment]
Mr. Lotfey is right. The link helped ( https://github.com/matplotlib/ipympl )

**Comment by theprofessor000** [comment]
> Splitting matplotlib statements into multiple Jupyter input cells may cause nothing to appear. Check if all your statements are in the same cell.

Doesn't work for me
