### ISSUE TITLE
XSS vulnerabilities in Jupyter 

### ISSUE THREAD

**Issue by ranjitiyer** [jupyter/notebook#3529]
Hello Community Members:

Are there any known, unresolved XSS vulnerabilities in the current version of Jupyter?

Thanks!
Ranjit

**Comment by takluyver** [comment]
We are not currently aware of any unfixed vulnerabilities. If you think you've found one, you can report it privately to security@ipython.org . [More info about reporting security issues](http://jupyter-notebook.readthedocs.io/en/stable/security.html#reporting-security-issues)
