### ISSUE TITLE
Setting or getting a Jupyter Notebook URL token

### ISSUE THREAD

**Issue by apache8080** [jupyter/notebook#3530]
I am working on a project where I am starting up jupyter notebooks from a python script and redirecting users to that url. Currently, I have a python script calling notebook.list_running_servers() until it gets a notebook object with the token in it. This doesn't work too well since the json file that notebook.list_running_servers() is pulling from isn't updated right away when the jupyter notebook is started. Is there any way for me to programmatically set the token for a jupyter notebook or is there a better way to get the token?

**Comment by takluyver** [comment]
You can set it when launching the server with `--NotebookApp.token="iojeijngkwnmerpkweroijeoij"` (randomly generate some long string to go there). But launching it and then waiting for the file should work - this is what we do for testing:

https://github.com/jupyter/notebook/blob/97b3b96f3dbec25390502a1bf1d4f113b6d16b59/notebook/tests/selenium/conftest.py#L17-L31
