### ISSUE TITLE
How to grep code from ipynb files?

### ISSUE THREAD

**Issue by Fangyh09** [jupyter/notebook#3531]
How to grep code from ipynb files? Are there any parser tools?
```bash
grep -r "np.transpose()" *.ipynb
```

**Comment by takluyver** [comment]
`grep` should work - the output will be somewhat messier because of the JSON container, but it will still find the code. Or I just googled nbgrep, and sure enough,  someone has written it: https://gist.github.com/jbarratt/fa1d3473048e5f856aeb

**Comment by chongchonghe** [comment]
I would recommend [nbcommands](https://github.com/vinayak-mehta/nbcommands/). It has a command `nbgrep`.
