### ISSUE TITLE
question about extension-defined actions 

### ISSUE THREAD

**Issue by parmentelat** [jupyter/notebook#3549]
Hey folks

I’m facing an issue about an extension that defines actions
(all this is with the classic notebook and the RISE extension)

What is happening is that:

* users can see those actions in the ‘Edit Keyboard Shortcuts’ UI
* from this UI they can also bind the actions to keystrokes
* and that works fine for the current session
* it is also properly saved in nbconfig/notebook.json
* but then if they come back later on in a new notebook session, this error shows up in the console:

```
Uncaught (in promise) Error: does not know how to deal with : RISE:toggle-note
    at ShortcutManager.add_shortcut (keyboard.js:457)
    at ShortcutManager.add_shortcuts (keyboard.js:475)
    at keyboardmanager.js:80
``` 

which of course suggests that keybinding takes place before the extension is loaded

It seems like a pretty standard situation, so I wonder if I did something wrong in the way I defined these actions; 

where should I start looking to see how folks handle that in other extensions ?

**Comment by takluyver** [comment]
It is a reasonable thing to do, and other people have run into the same roadblock (#2954). It's waiting for someone to dig in and figure out a fix. Maybe a way to register shortcuts without checking their names, and then trigger a check of all names after extensions have loaded?

**Comment by takluyver** [comment]
If you've got time to test, can you check that #3561 fixes it? There are instructions on installing from source here: http://jupyter-notebook.readthedocs.io/en/stable/contributing.html#setting-up-a-development-environment

**Comment by parmentelat** [comment]
as an aside, I see this attached to the 5.5 milestone, is there any known indication about when this would be released, even approximative ? 
Just to get a sense of the best pace for addressing this..

**Comment by takluyver** [comment]
The best way to get a sense is [how many other things are in the milestone](https://github.com/jupyter/notebook/milestone/27) - at the moment there are just a handful, and that's because I'd like to get 5.5 ready in the next few days. :-)

**Comment by parmentelat** [comment]
I struggled a bit to get in position, but as far as I can tell, using takluyver:i3549 indeed solves the issue, the registered action does not trigger any message upon reloading, and the shortcut triggers as expected, so we should be fine

Thanks a lot!

-----
PS. I'd like to add that on the mac I had to explicitly run

```
brew install bower
```

in addition to what was mentioned in the contributing doc that you quoted; this was required before I could run 

```
pip3 install -e .
```

from my local notebook repo, that attempted to run `bower` which was not installed

**Comment by takluyver** [comment]
Thanks!

It's meant to use npm to install bower, but I guess it may have installed it somewhere that wasn't on $PATH. Installing stuff is hard! :-(

**Comment by parmentelat** [comment]
agreed ;)
