### ISSUE TITLE
remove --no-mathjax flag (or not) ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#355]
Mathjax should be bundled, but distrib might make it optional.

Cf discussion in https://github.com/jupyter/notebook/issues/352. 

Should we 

A) re-introduce what was removed by https://github.com/jupyter/notebook/pull/323, but with a placeholder for distributions ? 

B) Remove the --no-mathjax flag ?

---

Personally +0.5 for A) and -0.5 for B)

**Comment by minrk** [comment]
I think making it clearer that MathJax is now considered a true dependency (normal installation cannot succeed without it) is the way to go. There's no longer a very sensible reason to have the notebook without mathjax.

**Comment by captainsafia** [comment]
@Carreau — I can give this one a go as well. Seems simple enough.

**Comment by Carreau** [comment]
Can you try to see if you can (even with read only permission) assign yourself ?

**Comment by captainsafia** [comment]
I can't. :cry:

**Comment by captainsafia** [comment]
Do you want to remove this from the 4.1 milestone?

**Comment by minrk** [comment]
Yes

**Comment by minrk** [comment]
Going through backlog for 5.0. I think the current situation makes the most sense to me:

1. mathjax can still be disabled for deployments with mathjax security concerns
2. The notebook cannot be *installed* without mathjax, so the removal in #323 was correct (distros installing without mathjax should be considered broken)

But if we do want to remove the ability to run without mathjax, I'm also fine with reopening and merging #436 as-is.

**Comment by takluyver** [comment]
That sounds OK. So is there anything left to do, or can this be closed?

**Comment by Carreau** [comment]
Ok, let's leave the --no-mathjax for one more release, we can make it an error when running `lab` or once the server separation has been done by @SylvainCorlay.

Bumping as "JupyterLab".

**Comment by takluyver** [comment]
I think Min's argument is that the `--no-mathjax` flag should be kept indefinitely, as people might want to disable it for security reasons. However, my priority in commenting was just to get it out of the 5.0 queue, which you've now done. :-)

**Comment by gnestor** [comment]
I'm going to close given:

> I think Min's argument is that the --no-mathjax flag should be kept indefinitely, as people might want to disable it for security reasons.
