### ISSUE TITLE
Adding a "output_updated.OutputArea" event

### ISSUE THREAD

**Issue by philippjfr** [jupyter/notebook#3557]
The ``display`` function provides a very convenient way of updating output using the ``display_id`` and the resultant display handle. The updates take a very different codepath to regular ``display_data`` and ``execute_result`` messages however, and therefore do not provide a way to subscribe to a general event which makes the whole mime bundle and the OutputArea available.

In JupyterLab this is possible because the ``renderModel`` method of any registered custom mime renderers is given the whole mime bundle. It would be quite convenient to have an equivalent mechanism, which could easily be implemented by adding an ``output_updated``  event for ``OutputArea``. If this idea sounds reasonable I'd be happy to put together a PR.

**Comment by takluyver** [comment]
Sounds reasonable :-)

**Comment by takluyver** [comment]
Closed by #3560
