### ISSUE TITLE
Jupyter Notebook - R Not Working

### ISSUE THREAD

**Issue by gburzikas** [jupyter/notebook#3558]
Jupyter Notebook works great for Python...But I am having issues when i switch to R. 

I get these errors...Any thoughts?

[I 13:05:26.044 NotebookApp] Kernel started: 7178206d-83f5-4201-b8ff-abec9708037b
Error: .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: @rpath/libzmq.5.1.2.dylib
  Referenced from: /anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
Execution halted
[I 13:05:29.047 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Error: .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: @rpath/libzmq.5.1.2.dylib
  Referenced from: /anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
Execution halted
[I 13:05:32.054 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Error: .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: @rpath/libzmq.5.1.2.dylib
  Referenced from: /anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
Execution halted
[I 13:05:35.064 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Error: .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: @rpath/libzmq.5.1.2.dylib
  Referenced from: /anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
Execution halted
[W 13:05:36.053 NotebookApp] Timeout waiting for kernel_info reply from 7178206d-83f5-4201-b8ff-abec9708037b
[I 13:05:38.075 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
WARNING:root:kernel 7178206d-83f5-4201-b8ff-abec9708037b restarted
Error: .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: @rpath/libzmq.5.1.2.dylib
  Referenced from: /anaconda3/lib/R/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
Execution halted
[

Thanks Grant

**Comment by takluyver** [comment]
You could try on the [IRkernel repo](https://github.com/IRkernel/IRkernel), but it looks like some problem with the R library pdbZMQ. Maybe try uninstalling/reinstalling that.

**Comment by gburzikas** [comment]
Thanks...Strange enough when i ran:

```
install.packages(c('repr',` 'IRdisplay', 'pbdZMQ', 'devtools'))
devtools::install_github('IRkernel/IRkernel')`
IRkernel::installspec()`

```
It worked.

It updated pbdZMQ, even tho i did this yesterday (perhaps a new build) and the dev tools command said it was installed.  The third line seemed to clean it up all...

Appreciate your help!
Grant

**Comment by takluyver** [comment]
OK, glad it's working now. :-)

**Comment by Randee77** [comment]
> Thanks...Strange enough when i ran:
> 
> ```
> install.packages(c('repr',` 'IRdisplay', 'pbdZMQ', 'devtools'))
> devtools::install_github('IRkernel/IRkernel')`
> IRkernel::installspec()`
> ```
> It worked.
> 
> It updated pbdZMQ, even tho i did this yesterday (perhaps a new build) and the dev tools command said it was installed. The third line seemed to clean it up all...
> 
> Appreciate your help!
> Grant

Hello gbourzikas, i got the same problem, I tried reinstalled the pbdZMQ package via Anaconda or create a new environment with R, neither works. May I know from where I can run the three lines of code you recommended here? Thanks a lot!
