### ISSUE TITLE
Stripping outputs in Jupyter notebook, UnicodeDecodeError issue. 

### ISSUE THREAD

**Issue by FMCumhaill** [jupyter/notebook#3559]
I have .ipynb file that won't seem to open anymore, I suspect it's might be an issue with an extremely long output cell (1.5 million pandas rows). 

I've tried running some scripts to remove the outputs [minrk among others](https://gist.github.com/minrk/3719849)

I keep getting the following issue. The output file is created, but gives a 400 bad error when I try and open it. 

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 122550: character maps to <undefined>`

**Comment by minrk** [comment]
specify that the encoding is `utf8`:

```python
with io.open('file.ipynb', 'r', encoding='utf8') as f:
    ....
```

Notebooks are always utf8-encoded.

**Comment by FMCumhaill** [comment]
Yes that worked! Thank you! 

Opening it in Google colab also worked... it was smart enough to automatically close large outputs.
