### ISSUE TITLE
Downlad as PDF with custom template

### ISSUE THREAD

**Issue by jakobgager** [jupyter/notebook#356]
Is there a way to specify a custom template to be used when clicking download as PDF?
It feels odd to modify the original article.tplx file to get customized output.
thx

**Comment by minrk** [comment]
Not in the UI, but if it has been specified in your config file, it should work.

**Comment by jakobgager** [comment]
Thanks for the hint! Adding 
```python
c = get_config()
c.LatexExporter.template_file = 'mytemplate'
```
to `ipython_config.py` works fine if the template is located at the same location as the notebook.
However, I have some troubles with custom filters. Where do I have to place these modules so nbconvert can find it? I've added to the config file
```python
c.LatexExporter.filters = {'htmlimage': 'myfilter.htmlimage'}
```
and placed `myfilter.py` with the method htmlimage in the same directory as `mytemplate.tplx` but I always get the error _Could not construct Exporter: No module named myfilter_.

**Comment by Carreau** [comment]
myfilter should be a globally importable python module.

**Comment by jakobgager** [comment]
Thx, I finally found a solution with ``sys.path``. Initially, it doesn't worked but now (with jupyter 4) it works fine. I just wondered why there is no option like ``LatexExporter.filter_path``.

**Comment by jakobgager** [comment]
Just a quick follow up... can I specify the config options (e.g. template) from within a notebook? This way I could assign the appropriate template to be used for a particular notebook directly in the notebook. It would be even more interesting to use metadata this issue.

**Comment by minrk** [comment]
Not at the moment. There are security issues (*sigh*) with allowing the specification of certain nbconvert options as part of notebook metadata. But it could be done, and could be folded into the existing trust mechanism before being allowed.

**Comment by jakobgager** [comment]
OK, thanks for the info!
