### ISSUE TITLE
Strip logging tokens with "[secret]"

### ISSUE THREAD

**Issue by elgalu** [jupyter/notebook#3564]
We noticed secret tokens get logged. This is problematic in enterprise systems.

Could we have something similar to what JupyterHub does:
https://github.com/jupyterhub/jupyterhub/blob/0561968fac88dd7ffae94c99dd49cab85ffcd6a8/jupyterhub/log.py#L58

I guess this should be implemented somewhere in:
https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1251

**Comment by georghildebrand** [comment]
I can confirm this issue. I think the solution would just be to wrap the uri the same way as its done in the hub source

**Comment by takluyver** [comment]
What specific tokens are you seeing?

**Comment by elgalu** [comment]
sorry my bad, we double checked and the problem is in JupyterHub
