### ISSUE TITLE
Resolve general security questions and fears running notebooks in browsers

### ISSUE THREAD

**Issue by fkdesouza** [jupyter/notebook#3566]
This issue concerns the general understanding and documentation of jupyter/notebooks running in browsers or browser-like software. For unexperienced users the question arise about "_How can I be sure that running a notebook within my browser does not send any data or information to external servers via the internet_"? It's not clear why and how this can be completely ruled out. As a result, people working perhaps with sensitive data may be afraid using these kind of tools.

Adding a clear statement about this matter into the documentation would be beneficial.

**Comment by takluyver** [comment]
I've had a go at this in #3571 - can you read that and see if you think it would help?

**Comment by fkdesouza** [comment]
Thanks, I think this should already help to satisfy the general concerns.

**Comment by takluyver** [comment]
Thanks :-)
