### ISSUE TITLE
ipython4+sympy0.7.6+mathjax do not render latex

### ISSUE THREAD

**Issue by kamijawa** [jupyter/notebook#357]
I have update ipython notebook from v3.2 to v4.0.4 and found that all latex form in my notebook output as "raw" text. After I try out many times and finally I find an easy way to solve it, that is :remove sympy 0.7.6 and install sympy0.7.7-dev0 from it's repository in github.Can this tip be helpful to somebody?

**Comment by minrk** [comment]
SymPy 0.7.6.1 fixes this.
