### ISSUE TITLE
Can't rename a file name to a non-ascii string

### ISSUE THREAD

**Issue by shnmng** [jupyter/notebook#3576]
![2018-04-27 17-15-02](https://user-images.githubusercontent.com/6242038/39355047-b56e36ec-4a3e-11e8-9f99-a494c97f0a29.png)
When I want to rename filename to a chinese string , an error raised.

**Comment by takluyver** [comment]
What platform are you on, and how are you launching the notebook? The filesystem encoding is defined by the locale, but on most modern systems it should be UTF-8 (which means any character is allowed).

**Comment by shnmng** [comment]
I use linux , I launch notebook by systemd script ( jupyter.service file from [here](https://gist.github.com/whophil/5a2eab328d2f8c16bb31c9ceaf23164f) ),and locale is :
LANG=zh_CN.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=

**Comment by takluyver** [comment]
I would guess that systemd starts it without your locale set. Check `os.environ['LANG']` inside a notebook to see if that's the case. I think adding `Environment=LANG=zh_CN.UTF-8` to the service file might work.

Here's the relevant systemd docs: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment

**Comment by shnmng** [comment]
@takluyver
Thank you very much !
I's just the problem .
I added Environment=LANG=zh_CN.UTF-8 to systemd service file and it's ok now .

**Comment by takluyver** [comment]
Great!

For anyone else reading this: programmes running on Linux without a locale set (which can be the case when they run as a system service, or a cron job, for instance) use the default locale, which uses the ascii encoding for things like filenames. On almost all modern systems it's safe to configure it like this to use UTF-8 instead. The bit before that identifies the language and country (zh_CN = China, de_DE = Germany, etc.).

**Comment by GameHoo** [comment]
> @takluyver
> Thank you very much !
> I's just the problem .
> I added Environment=LANG=zh_CN.UTF-8 to systemd service file and it's ok now .

where is the service file ?
