### ISSUE TITLE
Upgrading or uninstalling notebook via conda crashes Windows

### ISSUE THREAD

**Issue by jengelman** [jupyter/notebook#3587]
Python version: 3.6.5
conda version: 4.5.1
OS: Windows 7

Tried to upgrade notebook and the following happened:

```$ conda install --verbose --force notebook
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Anaconda3

  added / updated specs:
    - notebook


The following NEW packages will be INSTALLED:

    pywinpty:   0.5.1-py36_0
    send2trash: 1.5.0-py36_0
    terminado:  0.8.1-py36_1
    winpty:     0.4.3-4

The following packages will be UPDATED:

    notebook:   5.0.0-py36_0 --> 5.4.1-py36_0

Proceed ([y]/n)? y

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... ===> UNLINKING PACKAGE: defaults::notebook-5.0.0-py36_0 <===
  prefix=C:\Anaconda3
```

The console then hangs and the installer spawns hundreds of processes until the machine crashes. 

Looking at Windows Task Manager, the spawning process is the following:
` pythonw.exe -c "import menuinst; menuinst.install('C:\\Anaconda3\\Menu\\ipython.json', True, C:\\Anaconda3')"`

Tried running `conda uninstall notebook` and `conda remove notebook`, and got the same result.  I also tried uninstalling and reinstalling menuinst, which didn't help.   I tried manually deleting the notebook folder from site-packages and nothing changed.  Given dependencies, this also prevents upgrading ipython. .

**Comment by takluyver** [comment]
Sorry, you'll have to [ask Anaconda](https://github.com/ContinuumIO/anaconda-issues/) about that - menuinst is not something we control.

**Comment by jengelman** [comment]
@takluyver will do, thanks!
