### ISSUE TITLE
Urr.... ipython notebook  is not reading the profile

### ISSUE THREAD

**Issue by episodeyang** [jupyter/notebook#359]
I upgraded my ipython notebook this morning via

```
sudo pip install --upgrade ipython jupyter
```
and everything was fine. 

Then I realized that when I do

```
ipython notebook --profile=default
```
the console shows the following error message:
```bash
$ ipython notebook --profile=default
[W 08:15:20.133 NotebookApp] Unrecognized alias: '--profile=default', it will probably have no effect.
```

Uhm is there a verbose mode to see what's going on? 

```bash
$ ipython --version
4.0.0
```

**Comment by episodeyang** [comment]
saw that now you should use 

```
ipython notebook --config="path"
```

**Comment by minrk** [comment]
@episodeyang yup, sorry for the confusion. As of 4.0, `ipython notebook` is a deprecated alias for `jupyter notebook`. You can see more info about The Big Split on [the blog](https://blog.jupyter.org/2015/08/12/first-release-of-jupyter/), and the [jupyter docs](https://jupyter.readthedocs.org/en/latest/system.html#config-dir) about Jupyter's configuration directories.
