### ISSUE TITLE
Regarding "Not Trusted" jupyter notebook when copied from one system to another and running it

### ISSUE THREAD

**Issue by cy16f01** [jupyter/notebook#3604]
I have a jupyter notebook (say abc.ipynb) in one computer and i transferred the file to another computer and i am running the abc.ipynb notebook in the later computer.
When i open the notebook in the top right, it is showing "Not Trusted" and if i am saving it (cntrl+s), in terminal i am getting as shown in the screenshot image (in green colour letter it says saved, but in brown colour letter it says not trusted).
![3](https://user-images.githubusercontent.com/30516979/39870396-dc06f254-547e-11e8-88cd-874cf19d23d3.png)
But if i have opened the notebook (def.ipynb) in the computer where it was originally created, in the top right it shows as "Trusted" and when i save the notebook in terminal it will be saved (with green colour code letters) as in screenshot image attached here..
![x](https://user-images.githubusercontent.com/30516979/39870625-b136a3ac-547f-11e8-8dc7-ae31ac89f1e8.png)

So, why is the notebook when copied from other system and running it in the later system shows not trusted..??

Any suggestions.?
Thank you.

**Comment by takluyver** [comment]
Do the docs here clarify this?

http://jupyter-notebook.readthedocs.io/en/stable/notebook.html#trusting-notebooks

**Comment by cy16f01** [comment]
Yes, It was really helpful.
Thank you @takluyver .....
