### ISSUE TITLE
can't install jupyter

### ISSUE THREAD

**Issue by curtischong** [jupyter/notebook#3609]
Everytime I install Jupyter (with pip) I receive the following error:

```tensorflow 1.8.0 requires tensorboard<1.9.0,>=1.8.0, which is not installed.
awscli 1.15.19 has requirement colorama<=0.3.7,>=0.2.5, but you'll have colorama 0.3.9 which is incompatible.
Installing collected packages: terminado
  Found existing installation: terminado 0.6
Cannot uninstall 'terminado'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

This stops my installation. Do you know how I can install Jupiter with pip?

**Comment by jtpio** [comment]
Closing as this should be fixed with the latest versions.

If you are still experiencing this with the `terminado` package, please open a new issue on this repo: https://github.com/jupyter/terminado

Thanks!
