### ISSUE TITLE
Notebook starts running again after cell execution

### ISSUE THREAD

**Issue by kdoroschak** [jupyter/notebook#3619]
I am not certain if this is a bug or some weird one-off issue that is happening on my end. 

Sometimes my notebook will start running again after executing a cell. It will not run other queued cells unless I manually interrupt the kernel, meaning that I have to wait for a cell to finish, interrupt the kernel, and then run the next cell.

This behavior begins sometime randomly after being restarted, never immediately after opening a notebook. Once the behavior starts, it continues until the notebook is restarted.

I have tried narrowing down the cause (is it a particular cell? library? size of data? garbage collection?), but have not been able to consistently reproduce the behavior. The same notebook can run for longer or shorter without the issue coming up, but it almost inevitably happens at some point.

This is VERY frustrating and I would appreciate any help at all, however big or small. Guidance on finding a way to reproduce this would also be wonderful, as I've tried the obvious things and am still stuck.

Thank you so much!

**Comment by takluyver** [comment]
Are you using any extensions? It sounds a little bit like a problem some people had with a variable inspector extension.

**Comment by kdoroschak** [comment]
Yes, and I am indeed using a variable inspector extension. I'll see if disabling it works. Thank you!

**Comment by kdoroschak** [comment]
Amazing, looks like that was it. Thank you again for your help! You've saved me many hours of frustration fighting with my notebooks. :)
