### ISSUE TITLE
The token string appears twice in the url in the console when running jupyter notebook

### ISSUE THREAD

**Issue by rs2** [jupyter/notebook#3620]

**Comment by tiangolo** [comment]
I think I'm experiencing the same issue.

I'm using Jupyter Notebooks from a Docker container.

Steps to reproduce:

With a `Dockerfile` with:

```Dockerfile
FROM python:3.6

RUN pip install jupyter
EXPOSE 8888
```

Build:

```bash
docker build -t jup .
```

Start a bash session:

```bash
docker run -it -p 8888:8888 jup bash
```

Start a Jupyter Notebook:

```bash
jupyter notebook --ip=0.0.0.0 --allow-root
```

The output is like:

```
[I 16:32:53.474 NotebookApp] Serving notebooks from local directory: /
[I 16:32:53.474 NotebookApp] 0 active kernels
[I 16:32:53.474 NotebookApp] The Jupyter Notebook is running at:
[I 16:32:53.474 NotebookApp] http://4db43b31b8ad:8888/?token=d85ad5a1f5327cf823326826dcc54119c5a3920620eab5b2
[I 16:32:53.474 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 16:32:53.474 NotebookApp] No web browser found: could not locate runnable browser.
[C 16:32:53.474 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://4db43b31b8ad:8888/?token=d85ad5a1f5327cf823326826dcc54119c5a3920620eab5b2&token=d85ad5a1f5327cf823326826dcc54119c5a3920620eab5b2
```

The expected output in the last section would be:

```
Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://4db43b31b8ad:8888/?token=d85ad5a1f5327cf823326826dcc54119c5a3920620eab5b2
```

But the `token` parameter is repeated. And using it that way in something different than a browser, e.g. Visual Studio Code Jupyter extension, it doesn't work and throws an error.

**Comment by glebashnik** [comment]
I have double token issue with JupyterLab, running from Docker.

What about ip, why it's docker container id instead of the ip? A feature or a bug?

**Comment by takluyver** [comment]
#3656 eliminates the double token.

The thing with the docker container ID thing is separate. It's meant to be a feature, but it doesn't work very well with docker. See #3605 for more about that.
