### ISSUE TITLE
Importing Python2 modules in jupyter serverextension

### ISSUE THREAD

**Issue by apsknight** [jupyter/notebook#3625]
Hello,

While developing a server extension for Jupyter, I need to import a Python module which is not yet compatible with Python3 and thus on importing it in server extension python file, I am getting error on importing module. Is there any way so that I can tell Jupyter to run my serverextension using Python2 rather than Python3.

**Comment by takluyver** [comment]
You would have to install the notebook server as a whole on Python 2. Be aware that we're going to drop Python 2 support at some point in the next few months, so you might want to look at porting the module to Python 3 or finding an alternative.
