### ISSUE TITLE
gouraud shading bug with matplotlib svg backend

### ISSUE THREAD

**Issue by CorbinFoucart** [jupyter/notebook#3626]
When the matplotlib backend is set to 'SVG', it seems that the notebook can't render 'gouraud' shading correctly. 

I've uploaded a minimal example of my problem here:
https://nbviewer.jupyter.org/github/CorbinFoucart/FEMexperiment/blob/master/app/mpl_bug.ipynb

This is my Jupyter Notebook information:
<img width="628" alt="screen shot 2018-05-18 at 12 42 06" src="https://user-images.githubusercontent.com/4095293/40247277-dad8a884-5a99-11e8-84b2-f12d914d2d5e.png">

In the virtual environment which I used to create the kernel:
```
jupyter-client==5.2.3
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
matplotlib==2.1.2
```

And my operating system is OS X El Capitan 10.1.6

**Comment by CorbinFoucart** [comment]
I have also checked on a Linux Machine -- The problem is still present on Ubuntu 16.04 LTS

The virtual environment details there are:
```
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
jupyter-client==5.2.3
jupyter-core==4.4.0
matplotlib==2.2.2
```

![screenshot from 2018-05-18 14-47-52](https://user-images.githubusercontent.com/4095293/40252499-7d8416f8-5aaa-11e8-9ea7-6843e3f51cc2.png)

**Comment by takluyver** [comment]
AFAIK the notebook doesn't really do anything with the SVG. We ask matplotlib to generate it, and then we hand it to the browser to display.

So if the wrong SVG is being generated, talk to matplotlib. If the right SVG is generated and it's displayed incorrectly, that's probably up to your browser.

**Comment by CorbinFoucart** [comment]
After saving the output to file, it seems that the SVG is simply being generated incorrectly. This is the case on both firefox and chrome. So I suppose you're right; this belongs in Matplotlib.
