### ISSUE TITLE
Incorrect sizing of brackets/parentheses in math input

### ISSUE THREAD

**Issue by jonathanunderwood** [jupyter/notebook#3628]
Something seems to have broken with respect to correctly sizing brackets in expressions. 

With the input show in this screenshot:

![screenshot from 2018-05-20 14-56-29](https://user-images.githubusercontent.com/992114/40279684-a63d8364-5c3e-11e8-8583-4777ac875f0d.png)

This is what I see when rendering that cell:
![screenshot from 2018-05-20 14-56-47](https://user-images.githubusercontent.com/992114/40279698-de9b1276-5c3e-11e8-826e-f1d3cc606508.png)

Notice how the parentheses in the rendered maths are incorrectly sized.

I am using the following packages on Fedora 28:
```
python3-jupyter-client-5.2.3-1.fc28.noarch
python3-notebook-5.4.0-2.fc28.noarch
mathjax-typewriter-fonts-2.7.1-2.fc27.noarch
mathjax-sansserif-fonts-2.7.1-2.fc27.noarch
mathjax-size4-fonts-2.7.1-2.fc27.noarch
mathjax-math-fonts-2.7.1-2.fc27.noarch
mathjax-main-fonts-2.7.1-2.fc27.noarch
mathjax-size3-fonts-2.7.1-2.fc27.noarch
mathjax-size2-fonts-2.7.1-2.fc27.noarch
mathjax-size1-fonts-2.7.1-2.fc27.noarch
mathjax-caligraphic-fonts-2.7.1-2.fc27.noarch
mathjax-script-fonts-2.7.1-2.fc27.noarch
mathjax-ams-fonts-2.7.1-2.fc27.noarch
mathjax-winie6-fonts-2.7.1-2.fc27.noarch
mathjax-2.7.1-2.fc27.noarch
mathjax-winchrome-fonts-2.7.1-2.fc27.noarch
mathjax-fraktur-fonts-2.7.1-2.fc27.noarch
```

**Comment by jonathanunderwood** [comment]
I see the same thing in Chromium, and in Firefox with extensions disabled. The weird thing is, when the notebook first loads, the maths renders correctly for a few seconds, and then reverts to the wrongly proportioned version.

I notice this in the console that I launch jupyter from:

```
[I 21:54:13.796 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 21:54:16.677 NotebookApp] Notebook mirror_trading.ipynb is not trusted
[W 21:54:16.720 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180521215413 (::1) 8.05ms referer=http://localhost:8888/notebooks/mirror_trading.ipynb
[I 21:54:17.074 NotebookApp] Kernel started: 072c7e3b-559b-4bb7-8665-c9db10dd9a05
[I 21:54:17.559 NotebookApp] Adapting to protocol v5.1 for kernel 072c7e3b-559b-4bb7-8665-c9db10dd9a05
[W 21:54:17.636 NotebookApp] 404 GET /static/components/MathJax/fonts/HTML-CSS/STIX-Web/woff/STIXMathJax_Main-Italic.woff?V=2.7.1 (::1) 1.24ms referer=http://localhost:8888/notebooks/mirror_trading.ipynb
[W 21:54:17.644 NotebookApp] 404 GET /static/components/MathJax/fonts/HTML-CSS/STIX-Web/otf/STIXMathJax_Main-Italic.otf?V=2.7.1 (::1) 1.33ms referer=http://localhost:8888/notebooks/mirror_trading.ipynb
```

**Comment by jgubmll** [comment]
Have confirmed that running jupyter from a virtualenv installed via pip doesn't manifest this problem, so it looks like something specific to the Fedora 28 packaging. I'll close this. Have reported it here:

https://bugzilla.redhat.com/show_bug.cgi?id=1581899

**Comment by jonathanunderwood** [comment]
Oops, wrong account.
