### ISSUE TITLE
Token authentication is enabled is drive me crazy

### ISSUE THREAD

**Issue by gserra75** [jupyter/notebook#3632]
Hi guys
I can't use jupyter Python because of this "Token authentication is enabled".
Unfortunately, I am not able to run either the command "Jupyter notebook list" because I am using windows in a business environment, hence, no command prompt available either. 
The IT desktop support installed Python Anaconda but they don't have any clue how to provide me with a token or a password.
Do you mind please help me with some workaround or simple hints to share with the IT support?
PS: the IT desktop support, already went through all info in https://jupyter-notebook.readthedocs.io/en/stable/public_server.html without understanding what actually they have to do for help.
Thank you in advance.

**Comment by takluyver** [comment]
The `jupyter notebook list` command calls [this Python function](https://github.com/jupyter/notebook/blob/5.5.0/notebook/notebookapp.py#L1684), which reads data from some JSON files. If you can figure out a way to read those, you can get the token without the command prompt.

Alternatively, if you configure a password for Jupyter yourself, that replaces the default token authentication: https://jupyter-notebook.readthedocs.io/en/stable/public_server.html?highlight=password#securing-a-notebook-server

**Comment by gserra75** [comment]
@takluyver 
First thank you for your answer, but I am sorry, still missing few crucial details.
Let stay stick to the second option, where I can alternatively configuring a password by myself, mainly because in the real world even the IT desk supports is not able to support everything.
I, therefore, read what advised in the below link:
https://jupyter-notebook.readthedocs.io/en/stable/public_server.html?highlight=password#securing-a-notebook-server
But my question is How can I set up a password by "entering a token" if I don't know where I can get the token that I need for?
Thank you in advance
Giuseppe

**Comment by takluyver** [comment]
All of the recommended ways to set the password either require you to have got the token once, or to run things at the command prompt. I've never come across an environment where the command prompt is disabled before.

In the absence of a command prompt, you probably need to start from [this section](https://jupyter-notebook.readthedocs.io/en/stable/public_server.html?highlight=password#preparing-a-hashed-password), and create a new config file by hand with just the `c.NotebookApp.password = ...` line in.

**Comment by gserra75** [comment]
@takluyver problem solved, many thanks
