### ISSUE TITLE
Access Jupyter notebook from Docker Container

### ISSUE THREAD

**Issue by YiouZuo** [jupyter/notebook#3639]
I started a container with jupyter in it, linked the ports between host and container but when I launch a Jupyter kernel inside the container, the provided url doesn't work. I have to change the serial numbers  before ':8888' to 'localhost' and it will work. This happened only recently.

<img width="1570" alt="screen shot 2018-05-26 at 3 57 26 pm" src="https://user-images.githubusercontent.com/15369109/40579789-e928afe6-60fd-11e8-8a0b-0ab4f7d7a28f.png">

**Comment by forbxy** [comment]
I think it is ok,  serial numbers is the container's host name.To avoid it,  specified ip to 127.0.0.0 or 0.0.0.0 if your container network is host mode

**Comment by takluyver** [comment]
See also #3605. I'll close this one as a duplicate; feel free to follow up on that issue.

**Comment by YiouZuo** [comment]
Neither 127.0.0.0 nor 0.0.0.0 worked. I'm following #3605 now. Thanks!
