### ISSUE TITLE
serious numpy numerical errors/inconsistencies

### ISSUE THREAD

**Issue by cod3licious** [jupyter/notebook#3641]
I get very very strange numerical inconsistencies like these:
<img width="789" alt="screen shot 2018-05-27 at 0 29 08" src="https://user-images.githubusercontent.com/1093567/40580834-df8b364e-6147-11e8-9b4d-4f6aa0300643.png">
I could only reproduce this in jupyter notebook, not in ipython, so I guess it's a notebook issue. Here is a gist with [code to reproduce the error](https://gist.github.com/cod3licious/d2926e0bdc1355f0a921ac083d2799eb) (at least on my system). (Note that you need to download and unzip a file first and then appropriately copy your value of `vec_x` to `a`.)

My system specs:
macOS 10.13.4 (17E202) 
Python 3.6.4 :: Anaconda custom (64-bit)
jupyter-notebook 5.4.0
numpy 1.14.2
gensim 3.4.0

The code works as expected on Linux with the same package versions, so I really don't know what is going on here, but it is kind of freaking me out...

**Edit:** after a restart I could also reproduce the error in ipython on my macbook (ipython version 6.2.1), so it might also be a numpy error.

**Comment by takluyver** [comment]
Unexpected results like this basically can't be a bug in IPython/Jupyter. We don't deal with your code in any way that could change the result, as far as I know. There might be a difference in the environment that exposes some bug in numpy or the way Anaconda compiles it, but Jupyter should be just running the code you give it.

**Comment by cod3licious** [comment]
ok, thanks, then I'll close the issue for now and hope it gets resolved at another place! :)

**Comment by cod3licious** [comment]
@takluyver Ok, just fyi after some discussions in the numpy issue: It kind of does seem to be related to IPython, at least the error doesn't happen in the regular python shell, only in IPython/Jupyter notebook. But it's probably still an anaconda/MLK issue. The simplest example to reproduce an error like this in regular Python is with the following code:
```python
import IPython                   # or PyQt5.QtWidgets
import numpy as np
a = np.random.randn(2)
print(a.dtype)                   # float64
print(np.linalg.norm(a))         # 7.523412005985283 or some other real number
b = np.array(a, dtype=np.float32)
print(np.linalg.norm(b))         # nan / 0.0 / 6074001000.0 / 1.4142135 (i.e. not the right answer)
```
And in IPython the error happens without importing IPython first (as it is imported at startup).
I really don't know what in the world importing another library would do to mess up numerical results like this, but yeah, I guess there is still not really anything that you can do about it...
