### ISSUE TITLE
Javascript: No action on second click

### ISSUE THREAD

**Issue by kvedes** [jupyter/notebook#3648]
I'm trying to create a table using javascript which is updated by making a python callback. The result of the callback should be rendered in place of the existing table. The call back is triggered when the header of the table is clicked. I can make this work the first time I click but the second time, the click is not registered. This means that when I render the new table clicks are no longer registered, how can this be?

I'm using Jupyter Notebook version 4.4.0 with a python kernel running 3.5.2.

The python code:
```
import numpy as np
def create_table():
    a = np.random.randint(1,2000, 3)
    return """<table id="tab0"><tr><th>Col0</th><th>Col1</th></tr><tr><td>{}</td><td>{}</td></tr></table>""".format(a[0], a[1]) 
```
The cell rendering the HTML:
```
from IPython.core.display import HTML
HTML("""
    <div id="divouter">
    <table id="tab0">
                    <tr>
                        <th>Col0</th><th>Col1</th>
                    </tr>
                    <tr>
                        <td>100</td><td>100</td>
                    </tr>
              </table>
    </div>
    <script>
    $(document).ready(function(){
        $("#divouter table tr th").click(function() {     
            console.log("Click");
            
            // Load python kernel
            var kernel = IPython.notebook.kernel;
            
            // Set callback
            var callback = { 'iopub' : {'output' : redrawTable}};
            
            // Get output from python
            var html_table = kernel.execute("create_table()", callback, {silent:false});
        });
    });
    
    function redrawTable(out){
        // Get div
        var in_div = document.getElementById("divouter");
        
        // Get html code from python call
        var content = out.content.data["text/plain"];
        
        // Remove quotes in the beginning and end
        var length = content.length;
        var content_final = content.substr(1,length - 2);
        
        console.log(content_final);
        
        // Set html in div
        in_div.innerHTML = content_final;
    }
    </script>
""")
```

**Comment by takluyver** [comment]
This is an educated guess, but when you do `$("#divouter table tr th").click(...)`, I suspect it finds all those elements on the page and adds a click handler to them. But when you replace the table, you make new elements, which do not have that click handler.

So I think you need to reattach the click handlers each time you replace the table.

**Comment by kvedes** [comment]
Thank you very much, that fixed the problem. Sorry for posting something that turned out not to be related to Jupyter, but rather lack of javascript experience.

**Comment by takluyver** [comment]
No problem.
