### ISSUE TITLE
Error loading package in notebook

### ISSUE THREAD

**Issue by alealv** [jupyter/notebook#3649]
Hi, I'm having a problem trying to load opencv package inside jupyter notebook.

The thing is that outside jupyter (python or ipython) the package loads correctly.
![screenshot from 2018-05-29 11-48-51](https://user-images.githubusercontent.com/9395091/40666552-64f5da42-6336-11e8-8c38-e4e6ea61c6b1.png)

But when loading from the jupyter notebook a link error is raised telling a dependent library is not found.
![screenshot from 2018-05-29 11-42-58](https://user-images.githubusercontent.com/9395091/40666405-004dd446-6336-11e8-906b-d08291d4f27a.png)

I've also printed the environ properties, and they differ.

There are some **related issues**, but they were not helpful.
https://github.com/jupyter/notebook/issues/2359
https://github.com/jupyter/notebook/issues/1290

Another important detail is that jupyter is running with jupyter-hub on a server, and I'm using a virtual environment.

**Comment by takluyver** [comment]
Can you try to figure out what differences in the environment might be relevant?

**Comment by alealv** [comment]
I think maybe **LD_LIBRARY_PATH** and **LIBRARY_PATH**, because the have the paths to */opt/intel/tbb*

```
"LD_LIBRARY_PATH": "/opt/intel/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.2.199/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2018.2.199/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/opt/intel/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64_lin/gcc4.7:/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin:/usr/local/lib:/usr/local/cuda/lib64:/usr/local/computecpp/lib:/usr/local/nccl/lib:",
```

and 

```
"LIBRARY_PATH": "/opt/intel/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.2.199/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2018.2.199/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/opt/intel/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64_lin/gcc4.7:/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin",
```

**Comment by takluyver** [comment]
Those do sound likely to be relevant. Maybe they need to be set before the kernel process starts. How are you starting Jupyter?

**Comment by alealv** [comment]
Because I use Jupyter-hub, It starts as a service and I log in with my user. We've also tried to add the env-variables to the Spawner whitelist, but it didn't work.

c.Spawner.env_keep = ['PATH', 'PYTHONPATH', 'CONDA_ROOT', 'CONDA_DEFAULT_ENV', 'VIRTUAL_ENV', 'LANG', 'LC_ALL', 'LD_LIBRARY_PATH', 'LIBRARY_PATH']

**Comment by alealv** [comment]
Ok, we solved the problem with a very ugly hack. We just paste the environment variables to the jupyter-hub script and now is working.

**Comment by takluyver** [comment]
Closing because this is an environment variable issue rather than a bug in notebook. Maybe the spawner you're using needs to make some changes to how it handles environment variables, but it's tricky to get this sort of thing right 100% of the time - e.g. some modifications only take effect in an interactive terminal.
