### ISSUE TITLE
How to load extension automatically after a new notebook tab created?

### ISSUE THREAD

**Issue by limodou** [jupyter/notebook#365]
I searched in google for several days but found nothing can resolve my problem, so I have to ask in here.

In IPython Notebook 2.X I can pass `--ext` parameter to `ipython notebook` command line to automatically load an extension so that I can do some initialization work. Just like `ipython notebook --ext=mymodule.extention`. 

But when I upgrade to new jupyter 4.X, this way is not work any more, it'll say `Unrecognized alias: '--ext=mymodule.extension', it will probably have no effect.` But when I ceate a new notebook, I exactly can load the extension via `%load_ext mymodule.extension` .

So my question is what should I do if I want my extension be loaded automatically after the new notebook tab created, not jupyter server started.

Please note, the extension here is python code(ipython extension) but not js.

**Comment by minrk** [comment]
This is the result of the split between IPython and Jupyter. The notebook server is Jupyter, but the kernel you are using happens to be IPython (as opposed to IJulia, etc.). You should add the extension to your extensions to be loaded by IPython, which is most easily done via IPython configuration: In `~/.ipython/profile_default/ipython_kernel_config.py` add

```python
c.IPKernelApp.extensions = ['mymodule.extension']
```

**Comment by limodou** [comment]
Oh, I see. But I want to know if where is a way to add extension dynamically, but not written in config file, just like `--ext` parameter or something else worked in IPython notebook 2.x version.

**Comment by minrk** [comment]
There is not a way to specify kernel arguments on the notebook server command-line, because you can have many different kernels. You can, however, modify kernelspecs a little bit easier with [a2km](https://github.com/minrk/a2km), which means you can change the kernel args without ever restarting the notebook server.

**Comment by daf** [comment]
Is this still valid advice?  Running notebook 4.4.1 / ipykernel 4.5.2 / ipython 5.2.2 (ergh, this is an odd mix of versions), I can't for the life of me get the kernel process to respect any configuration that I leave in `~/.ipython/profile_default/ipython_kernel_config.py` - specifically trying to get it to automatically load a kernel extension.

strace confirms it opens that file and reads it, but inspecting the configuration (via `get_config()`, both in the notebook itself and injected in to `[InteractiveShellApp.load_extensions](https://github.com/ipython/ipython/blob/5.2.2/IPython/core/shellapp.py#L232-L238)`.  It only shows me:

```python
{'IPKernelApp': {'connection_file': '/run/user/1001/jupyter/kernel-28c991fb-e6cc-4d4d-a2e2-6658285bf1db.json'}}
```

Maybe I'm looking in the wrong location, but I can't seem to get files on disk to modify this config at all.  Any thoughts?

**Comment by takluyver** [comment]
Yup, should still work. Does `ipython_config.py` affect it? Feel free to open a new issue about it on the ipykernel repo.

**Comment by daf** [comment]
Thanks, done ipython/ipykernel#273

**Comment by praveenkanamarlapudi** [comment]
@minrk If we want to load the extension in system level instead of touching all user directories, is there any option in jupyterhub config or somewhere else?

Appreciate your help!

**Comment by minrk** [comment]
@praveenkanamarlapudi yes, you can put config in `/etc/ipython` and it will be loaded by all users by default.

**Comment by praveenkanamarlapudi** [comment]
@minrk Thanks for the info.
