### ISSUE TITLE
Font-awesome icons are not displayed

### ISSUE THREAD

**Issue by elimohl** [jupyter/notebook#3653]
My jupyer-notebook currently looks like this:
![2018-06-01-211131_3179x153_scrot](https://user-images.githubusercontent.com/10729543/40856409-74fe255a-65e0-11e8-9e78-037fbaf43935.png)
It says `404 GET /static/components/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0 (::1)`
My system is Debian Sid.
`fonts-font-awesome` package is installed.

**Comment by takluyver** [comment]
Did you install it through Debian packages, or with pip/conda? We recommend installing it with pip/conda; it's possible that Debian packaging has broken the use of fontawesome.

**Comment by n2718281** [comment]
The issue can be solved by downgrading from v5 (sid) to v4 (testing) for example.

**Comment by elimohl** [comment]
Now icons are displayed with the Debian packaged jupyter notebook too.

**Comment by maximilianduell** [comment]
On my debian system I could get the icons with standard debian packages by installing

   sudo apt-get install fonts-font-awesome python3-xstatic-font-awesome
