### ISSUE TITLE
Windows: calling 'jupyter notebook' does not 'block' the command prompt

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyter/notebook#367]
Don't know how to clearly specify this issue in the one line title, but I am seeing the following issue on Windows:

- Open a command prompt
- call `jupyter notebook`
- the notebook starts correctly, no problem with that
- but, you can still type in the command prompt; eg `ls` will list all files and dirs. So the command line is not 'blocked', it returns back to the prompt.

By itself, this seems not really a problem (everything works for the rest), but it is a) inconsistent with how it was before on Windows, b) inconsistent with how it is on eg linux and c) finally, can be a bit confusing (eg because it takes a few seconds before jupyter launches, the `C:\Users\username>` prompt already appears before there is any output of jupyter, giving the impression for a few seconds that it didn't work)

Using notebook 4.0.4, jupyter_client 4.0.0, jupyter_core 4.0.4, ipykernel 4.0.3, ipython 4.0.0

**Comment by Carreau** [comment]
o_O I suppose Ctrl-C does not stop the notebook ?

**Comment by jorisvandenbossche** [comment]
That still works! :-) (although not very clear it would ..)

As I said, everything seems to work correctly, but is just very strange ..

**Comment by Carreau** [comment]
indeed.

**Comment by juhasch** [comment]
The reason is jupyter_core uses `execvp()` to launch subcommands. Replacing the call with `subprocess.call()`.

This makes `jupyter nbconvert` annyoing and `jupyter console` unusable under Windows.

**Comment by damianavila** [comment]
>The reason is jupyter_core uses execvp() to launch subcommands.

This is no longer true, the fix was merged: https://github.com/jupyter/jupyter_core/pull/54

**Comment by juhasch** [comment]
Great! Thanks.
