### ISSUE TITLE
how to disable or hide default kernel

### ISSUE THREAD

**Issue by forbxy** [jupyter/notebook#3674]
thank u

**Comment by minrk** [comment]
It depends a bit on what exactly you want.

Normally, the kernelspec manager lists all kernels that you have installed. You can remove kernelspecs from the system with `jupyter kernelspec remove NAME`. This will prevent them from showing up in the list.

If you want to make only specific kernels available but don't want to uninstall kernelspecs, you can set the kernelspec whitelist, which will filter out any installed kernelspecs not in the set:

```python
c.KernelSpecManager.whitelist = {'julia-0.6', 'cling'}
```

One extra bit is that Jupyter will include the 'default' kernel, that of the current Python that the notebook is running, even if the kernelspec is not installed. This is governed by `c.KernelSpecManager.ensure_native_kernel`. So if you set

```python
c.KernelSpecManager.ensure_native_kernel = False
```

*and* uninstall the default kernelspec, it won't show up but all others will.

**Comment by forbxy** [comment]
Thanks for you reply.
Our goal is to isolate the running environment of user code from the running environment of the notebook. 
c.KernelSpecManager.ensure_native_kernel = False ,this code worked

**Comment by Nikhilpy77** [comment]
Hi @minrk could you tell me where to find the c.KernelSpecManager.ensure_native_kernel = False ...please

**Comment by kevin-bates** [comment]
This option would be set in the notebook configuration file.  When reading responses that reference configuration options, those prefixed with `c.` imply its a configuration file setting.  Those options are also available as command line arguments by replacing the `c.` prefix with `--` and removing spaces around the `=`.  For example, you could disable the native kernel from the command line using: `jupyter notebook --KernelSpecManager.ensure_native_kernel=False <other options>`.

You can read more about Notebook configuration options [here](https://jupyter-notebook.readthedocs.io/en/latest/config.html).
