### ISSUE TITLE
What is the process to start jupyterhub automatically?

### ISSUE THREAD

**Issue by prashant2k15** [jupyter/notebook#3677]
I have installed a jupyterhub on my subdomain. Whenever I have to use jupyterhub I have to run a command jupyterhub on ubuntu terminal if it is closed we are not able to access it.

SO, is there any way to start jupyterhub automatically when system start?

Version: 
UBUNTU 16.4, 
Anaconda 5.1.0,
Jupiter notebook --version 5.4.0.

**Comment by takluyver** [comment]
Just answered in another thread, but see https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service#ubuntudebian-anaconda3-with-systemd

There's a separate issue tracker for Jupyterhub if you need to ask further questions about it: https://github.com/jupyterhub/jupyterhub/issues
