### ISSUE TITLE
Can not upload files

### ISSUE THREAD

**Issue by uphy** [jupyter/notebook#3706]
Can not upload files with IE11 due to the lack of JavaScript API(Array.from) from Jupyter Notebook 5.5.0.
9e72e054 changes JavaScript native `for ` to `Array.from(..).forEach()` and broke the behavior in IE.

I know Jupyter Notebook [doesn't support IE](http://jupyter-notebook.readthedocs.io/en/stable/notebook.html#browser-compatibility), but my company still using IE unfortunatelly...

Can you revert from `Array.from(..).forEach()` to `for loop`?

**Comment by takluyver** [comment]
That was the fix for [another issue](https://github.com/jupyter/notebook/issues/3473), and as you say, we don't aim to support IE. Sorry.

**Comment by uphy** [comment]
Thank you for your response!
I will change the code personally.
