### ISSUE TITLE
Python 3 Kernel won't start in Notebook (Fresh Conda Env Install)

### ISSUE THREAD

**Issue by stevebissett** [jupyter/notebook#3708]
Hi, 

I am running on Mac OS 10.13.4 (High Sierra). 
I added a fresh Python 3 environment with `conda` and installed Anaconda. 

```
conda create -n py3homedev python=3
```

`conda info` returns: 

```
               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.8.2
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /Users/<user_name>/anaconda  (writable)
    default environment : /Users/<user_name>/anaconda/envs/py3_homedev
       envs directories : /Users/<user_name>/anaconda/envs
          package cache : /Users/<user_name>/anaconda/pkgs
```

```
anaconda                  4.4.0               np112py36_0
```

```
(py3_homedev) ➜  homedev  python --version
Python 3.6.1 :: Anaconda 4.4.0 (x86_64)
```

I tried to run a Jupyter Notebook with: 
```
jupyter notebook
```
The notebook application boots, but the Kernel doesn't:
I get this error: 

<img width="1176" alt="screen shot 2018-06-23 at 18 08 10" src="https://user-images.githubusercontent.com/5316630/41811467-73571928-7710-11e8-9efc-44003f322e55.png">

```
Traceback (most recent call last):
  File "/Users/<user_name>/anaconda/envs/py3_homedev/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'session'
```

I've found a few older scenarios like this, of which I have tried the suggestions with no result. 
Is there something obvious that I am missing? 

Any help would be appreciated to find out what may be the issue.

**Comment by stevebissett** [comment]
I was able to come right with this by doing a fresh condas install, and then adding multiple kernels here: 

https://stackoverflow.com/questions/30492623/using-both-python-2-x-and-python-3-x-in-ipython-notebook

```
conda create -n py27 python=2.7
source activate py27
conda install notebook ipykernel
ipython kernel install --user

conda create -n py36 python=3.6
source activate py36
conda install notebook ipykernel
ipython kernel install --user
```

**Comment by itsermin** [comment]
updating jupyter worked for me
pip install -U jupyter
