### ISSUE TITLE
ENH: Implement an enhancement badge/tag (nb functionality, Spark, real-time collaboration, dashboards, and more etc...)

### ISSUE THREAD

**Issue by ghost** [jupyter/notebook#371]
I believe this might be beginning to be addressed and here are my thoughts. As Github does not currently have this much-needed feature fully implemented(AFAIK), I think that having some mechanism for feature requests, ideas, suggestions, and enhancements would be very useful. Just going through my own repo, it seems that I've given some input on notebook functionality https://github.com/jupyter/notebook/issues/261 and  https://github.com/ipython/ipython/issues/8223 , PySpark integration https://github.com/jupyter/docker-demo-images/issues/41, real time collaboration https://github.com/jupyter/tmpnb/issues/139 , dashboards and more as have many other users/contributors. Features/ideas need to be easily locatable. It would be very useful to have a place or mechanism for discussion on Github of important and pending features and enhancements. 

It could be something as simple as active use of an enhancement tag/badge as I've seen in other scientific Python repos like Pandas(green color) or something like a repo for ideas where discussion would be in the comments. The subject header could include “ENH”. Also, there needs to be some delineation between major ideas(a few groupings-- see PR header) and enhancement/implementation fixes(possibly many). So, maybe two different tags for this. Or something more formalized from other discussions... Thoughts?

**Comment by captainsafia** [comment]
Thanks for your comment @nymoorland! Something like this has actually come to existence recently. You can head over to [jupyter/enhancement-proposals#2](https://github.com/jupyter/enhancement-proposals/pull/2) for more information on the new enhancement proposal process. Feel free to read through the document there.

**Comment by Carreau** [comment]
We should have a list of badges already available on all repos. Usually "sprint-friendly" for new contributors/easy fixes. We should advertise tag more. 

If you don't have the right to tag an issue, you can just add a comment "Can you tag as <...>" and one of us will do it.

**Comment by rgbkrk** [comment]
If at the level of enhancement request, it can probably still be an issue with a tag. Looking above, it seems I need to cover my own corner on tmpnb. These requests should impact the proposals and implementauons put together

**Comment by nymoorland** [comment]
@Carreau @rgbkrk Hey, thanks for the feedback and comments. Yeah, this sort of mechanism could be useful in parallel to the formal proposals for things that don't necessarily require a full-on and day to day stuff that pops up too.  Github calls these things "labels" while I was calling them tags. :octocat: \0/

> If you don't have the right to tag an issue, you can just add a comment "Can you tag as <...>" and one of us will do it.

@Carreau Great idea.

**Comment by JamiesHQ** [comment]
This issue seems like it has been resolved and the user account used in the original post is no longer on github. Please re-open if this is not the case. thanks!
