### ISSUE TITLE
the function append doesn't work

### ISSUE THREAD

**Issue by KiwiSeth** [jupyter/notebook#3721]
Hi Everyone,

I'm new and I just installed the Anaconda yesterday. The function append didn't work when I was studying the List on the Jupyter Notebook. Please help me with it. Thank you!

a = {44, 9, -10}

print(a)
{9, 44, -10}

a.append(1)

AttributeError                            Traceback (most recent call last)
<ipython-input-4-da0a5ad497c3> in <module>()
----> 1 a.append(1)

AttributeError: 'set' object has no attribute 'append'

**Comment by KiwiSeth** [comment]
I just found out the problem is from the first code and it should be:

a = [9, 44, -10]

**Comment by Tanyazwantig** [comment]
Hi, I am facing the same problem, can you kindly assist me?

a = (2, 4, 5)

print(a)

(2, 4, 5)
a.append(6)

this is what I keep getting
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-a09ce8848fdf> in <module>()
----> 1 a.append(6)

AttributeError: 'tuple' object has no attribute 'append'

**Comment by Tanyazwantig** [comment]
Thank you so much. It worked.

**Comment by yuvipanda** [comment]
Glad you got it worked out, @KiwiSeth / @Tanyazwantig! In the future, questions about Python itself might get better help on [StackOverflow](https://stackoverflow.com), since this repository is specific to questions about the Jupyter Notebook itself.
