### ISSUE TITLE
Tab Completion Accessibility

### ISSUE THREAD

**Issue by stas00** [jupyter/notebook#3727]
I have two related questions about the Tab Completion functionality.

Please consider this jupyter notebook screen snapshot:

![snap3](https://user-images.githubusercontent.com/10676103/42128900-aef03f78-7c6a-11e8-95e1-fc7af77ccec7.png)

1. Is it possible to make the dropdown with completion options "circular" - i.e. so that it'd be possible to jump to the last bottom option by hitting the Up Key, rather than needing to scroll all the way down. I ask because often there are long lists to go through and it's faster to go the other way if the target is towards the end of the list.

2. Occasionally, as it can be seen in the attached snapshot, one of the items is highlighted in blueish tint. Often it's the item that I want. Is this some kind of *locality*/*frequency* analysis that suggests the most likely candidate? And how can I jump to it directly in one keystroke, if at all possible, once the dropdown element has been presented?

Thank you.

notebook version: 5.5.0

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
