### ISSUE TITLE
ipynb download error 

### ISSUE THREAD

**Issue by maver1ck** [jupyter/notebook#3734]
Hi,
When I trying download notebook as ipynb I'm getting strange behaviour.
2 tabs is being open:
1) Where notebook is downloading
2) With 500 - internal server error and address:
https://serves/user/user_name/nbconvert/ipynb/notebook_name.ipynb?download=true

The problem is only with "download as notebook"

I'm using most recent version of Notebook and JupyterHub

**Comment by vkumra-broad** [comment]
I am seeing the same error, any idea on what the fix is.

Thanks

**Comment by KKulma** [comment]
same here - I get this error when trying to download a feather object.
