### ISSUE TITLE
Module not found error in Jupyter Notebook

### ISSUE THREAD

**Issue by tanuj178** [jupyter/notebook#3737]
I am getting a module not found error while using sklearn in Jupyter Notebook when I run it through Anaconda prompt whereas when I run it through CMD, the error message is not there. What could be the reason behind this?

**Comment by melaanya** [comment]
Same problem

**Comment by nvspavan007** [comment]
is the issue resolved ? or shall I help?

**Comment by nvspavan007** [comment]
Are you not able to import sklearn library in jupyter notebook?

**Comment by kevin-bates** [comment]
More information is required to resolve this.  From the current description, we cannot determine if this is occurring from within the notebook, during the launch of the notebook kernel, or something else.

Given the history of this issue, I'm closing for lack of information.
