### ISSUE TITLE
Add ability to upload many files

### ISSUE THREAD

**Issue by morenoh149** [jupyter/notebook#3747]
previous issue https://github.com/jupyter/notebook/issues/3351

I'm using notebooks in the cloud, in this environment the easiest way to get access to my dataset would be to upload the files using the notebook's filesystem explorer. However you can only upload one file at a time. This SO answer suggests zipping the file and unzipping it https://stackoverflow.com/questions/34734714/ipython-jupyter-uploading-folder

This feature is not too difficult to implement afaict and would go a long way towards improving notebook's usability in different environments.

**Comment by TangeniThePyGuru** [comment]
I currently have a folder worth 350GB+, Zipping and unzipping this directory is not an efficient alternative plus i don't have the storage space to zip it to in the meantime.

My point it that the ability to add uploading an entire directory would be a great feature to solve this situation.

I think issue mentioned above could be similar to mine.

**Comment by Aresyash01022000** [comment]
I have used your method and extracted the zip file and it contain 520 VM data in .csv extension but now how should i use the data ????

**Comment by jtpio** [comment]
Closing as fixed in Notebook 7:

https://github.com/jupyter/notebook/assets/591645/fb9c21fa-329e-46b3-ae9b-4d5707c8ebde

Note it is also possible to drag and drop multiple files in the file browser to upload them.
