### ISSUE TITLE
[Feature Request] Name/label for Jupyter cells

### ISSUE THREAD

**Issue by jolespin** [jupyter/notebook#3749]
I know that it is possible to use a cell above with markdown for labeling but this gets messy very quickly if cells are moved around or if new cells are being created.  Would it be possible to have an option for setting a name/label for each cell in future versions?  I've been doing one of two things: (1) creating a markdown code above; and (2) commenting the top of code.  The first method has some inconveniences as I mentioned above and the 2nd blends in with the rest of the code unless the comments are stylized with ascii characters surrounding them.  

This would make notebooks look very clean and would help workflow in general if this was an option.  

Just a suggestion, but I feel that it would be useful for the community. Thoughts?

**Comment by achampion** [comment]
Any reason not to use tagging? `View -> Cell Toolbar -> Tags` allows you to create tags for each cell.

**Comment by jolespin** [comment]
I'm not seeing it there in Jupyter Lab.  Would I need to migrate this to them? 

![image](https://user-images.githubusercontent.com/9061708/43233819-0d903152-902d-11e8-8078-9d008678f3c1.png)

**Comment by jolespin** [comment]
Sorry, I thought Jupyter lab used jupyter notebooks in the backend but it looks like it’s different
