### ISSUE TITLE
Running Jupyter notebook but instead get jupyter lab?

### ISSUE THREAD

**Issue by daudryc** [jupyter/notebook#3757]
I've been using jupyter lab for a while and I love it, but I want to use jupyter notebook presentation extension (I'm aware that there are developers who are working on this). However, everytime I run jupyter notebook, I get jupyter lab running on my machine. How can I run jupyter notebook as jupyter notebook and jupyter lab as jupyter lab?

**Comment by idoDavid** [comment]
Why did you closed this? I'm getting this as well.
