### ISSUE TITLE
Environment variable `DYLD_FALLBACK_LIBRARY_PATH` removed from instance of kernel

### ISSUE THREAD

**Issue by kdheepak** [jupyter/notebook#3774]
On macOS Sierra Version 10.12.6, using jupyter version 4.4.0, when I run a jupyter notebook or run jupyter lab and then start a notebook, the instance of a language kernel does not have the `DYLD_FALLBACK_LIBRARY_PATH` environment variable and its value in it. I've tested this with Python 3.6.4 and Julia v0.6.3. Any thoughts on what might be going on here? I first discovered this issue and posted it [here](https://github.com/JuliaOpt/Xpress.jl/issues/21). Are other people having the same issue or is this isolated to my computer?

**Comment by takluyver** [comment]
How are you starting the notebook? It's fairly common to set environment variables in a file like `.bashrc`, but if you don't launch the notebook from bash, it doesn't inherit variables set that way.

**Comment by kdheepak** [comment]
@takluyver Thanks for the quick reply. Starting `jupyter` from `bash` and it seems to work! Starting from `zsh` however it does not. I have the following in my `~/.zshrc`.

```bash
source ~/.bash_profile
```

My `~/.bash_profile` has the following

```bash
if [ -f $HOME/.bashrc ]; then
        source $HOME/.bashrc
fi
```

And my `~/.bashrc` has the following

```bash
export DYLD_FALLBACK_LIBRARY_PATH=${XPRESSDIR}/lib:${DYLD_FALLBACK_LIBRARY_PATH}
```

It does seem like this is isolated to my computer, and specifically just the shell I'm using. Thanks for your comment, I didn't think to check that. I'll be able to figure it out now, I'm just going to have to debug my environment variables scripts.

**Comment by kdheepak** [comment]
I think I have to reopen this issue. On my Mac, when I run `jupyter notebook` there is no issue. However when I run `jupyter lab`, regardless of whether I use the notebook or the lab interface, the `DYLD_FALLBACK_LIBRARY_PATH` is unset. Proof with screenshots. On the left, I'm running `jupyter notebook` (highlighted) which opens `localhost:8888` and on the right I'm running `jupyter lab` (highlighted) which open `localhost:8889`.

<img width="1680" alt="screen shot 2018-07-17 at 2 35 29 pm" src="https://user-images.githubusercontent.com/1813121/42844030-06353e84-89cf-11e8-8bd5-53d9a43b2f48.png">

The following is screenshots from all combinations. I use the same version of Python (version 3.6.2) to get the value of the environment variable `DYLD_FALLBACK_LIBRARY_PATH`. 

<img width="1680" alt="screen shot 2018-07-17 at 2 34 53 pm" src="https://user-images.githubusercontent.com/1813121/42844122-3c00725e-89cf-11e8-82e3-6dad2fe6a573.png">

In the instances of the notebook and the lab that was started by running `jupyter lab`, the value of the envrionment variable is set to `None`.

**Comment by kdheepak** [comment]
I've opened an issue on the jupyterlab repository instead.
