### ISSUE TITLE
Jupyter Notebook Not Launching

### ISSUE THREAD

**Issue by Shrey-Viradiya** [jupyter/notebook#3779]
I installed jupyter notebook on my laptop about a month ago. It was working fine till now. But today when I tried to start jupyter notebook it is not launching. Just nothing happens.

Note that I installed Jupyter Notebook on my machine, not using Anaconda Distribution.

![screenshot 29](https://user-images.githubusercontent.com/40735908/42881584-43d94410-8ab5-11e8-8925-ff2ec814c560.png)

**Comment by Shrey-Viradiya** [comment]
I also updated pip

**Comment by pranaynagpure321** [comment]
you can use pycharm to create jupyter notbook, but if you still want to continue first you should type a command
-> which juyter 
then it will show the location of files, and go to that directory then try launching it form there.

**Comment by qyj2006** [comment]
> you can use pycharm to create jupyter notbook, but if you still want to continue first you should type a command
> -> which juyter
> then it will show the location of files, and go to that directory then try launching it form there.

hi，could you tell me how to start the notebook project on pycharm?
which file below should i run?
setup.py?
setupbase.py?
__init__.py?
__main__.py?
