### ISSUE TITLE
Kernel restart and then core dump

### ISSUE THREAD

**Issue by slochower** [jupyter/notebook#378]
When opening an existing notebook or starting a new one, the kernel automatically restarts and then crashes. The dashboard view is stable.

New Ubuntu 15.04 installation. Installed jupyter version 4.0.4 through pip.

```bash
user@host:~/$ jupyter notebook
[I 15:00:25.876 NotebookApp] Serving notebooks from local directory: /home/user
[I 15:00:25.876 NotebookApp] 0 active kernels 
[I 15:00:25.876 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 15:00:25.876 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

(process:16373): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
[I 15:00:30.538 NotebookApp] Kernel started: 838ef42a-2cd4-46de-a691-d47cabafe7da
[I 15:00:33.539 NotebookApp] KernelRestarter: restarting kernel (1/5)
[W 15:00:40.964 NotebookApp] Timeout waiting for kernel_info reply from 838ef42a-2cd4-46de-a691-d47cabafe7da
[I 15:00:42.544 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 838ef42a-2cd4-46de-a691-d47cabafe7da restarted
*** stack smashing detected ***: /usr/bin/python terminated
Aborted (core dumped)
```

**Comment by Carreau** [comment]
Ouch, a coredump of python is bad. Any other error from the crashed kernel ?

Can you try:

Update libzmq/pyzmq though apt ?
Try to force reinstall the python kernelspec ? (`$ ipython kernelspec install-self`)

**Comment by rgbkrk** [comment]
This looks eerily familiar to a Firefox bug.

**Comment by slochower** [comment]
Interesting, I was using Firefox 40.0.3.

No other errors from the crashed kernel and I can't find the core dump.

Updated libzmq-dev and python-zmq through apt. Installed kernelspec using ` ipython kernelspec install-self`.

Now I don't get a core dump, but Firefox says "Dead Kernel" and the command line says
```bash
[I 08:23:06.534 NotebookApp] Kernel started: 8ac639ac-afff-48c6-82bc-f9849b4b225c
[I 08:23:09.537 NotebookApp] KernelRestarter: restarting kernel (1/5)
[W 08:23:16.880 NotebookApp] Timeout waiting for kernel_info reply from 8ac639ac-afff-48c6-82bc-f9849b4b225c
[I 08:23:18.542 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 8ac639ac-afff-48c6-82bc-f9849b4b225c restarted
```
...and then just hangs.

If I go to http://localhost:8888 in google-chrome then I get a core dump.

**Comment by dwillmer** [comment]
@slochower - @rgbkrk is correct, this is usually a 'firefox-on-ubuntu' bug, see here:

https://groups.google.com/forum/#!topic/jupyter/b9yeX4zfefw

if you're seeing a core dump when using chrome, then chances are that's a different error (although i can't tell from what you've written above) - could you please post the stack trace from the chrome error?

if it's the same error, then are you using a custom linux kernel with jemalloc instead of the standard libc alloc?

**Comment by slochower** [comment]
@dwillmer I assumed the `g_slice_set_config` output was unrelated after skimming this old thread where they said it was "harmless" https://bugzilla.mozilla.org/show_bug.cgi?id=672671#c21.

If I run `jupyter notebook --no-browser` so it doesn't open a tab in Firefox automatically and then open http://localhost:8888 in google-chrome, I get the same behavior after opening a notebook: automatic kernel restart and then core dump.

```bash
[I 08:50:44.863 NotebookApp] 0 active kernels 
[I 08:50:44.863 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 08:50:44.864 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 08:51:15.040 NotebookApp] 302 GET / (127.0.0.1) 0.78ms
[I 08:51:20.461 NotebookApp] Kernel started: 971538c7-5307-4a4a-9163-19a9dba3670f
[I 08:51:23.463 NotebookApp] KernelRestarter: restarting kernel (1/5)
[W 08:51:30.511 NotebookApp] Timeout waiting for kernel_info reply from 971538c7-5307-4a4a-9163-19a9dba3670f
[I 08:51:32.469 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 971538c7-5307-4a4a-9163-19a9dba3670f restarted
*** stack smashing detected ***: /usr/bin/python terminated
Aborted (core dumped)

```

**Comment by dwillmer** [comment]
ok, excellent, in which case you've confirmed the python core dump is definitely unrelated.

could you let us know which python version your kernel is running on? and do you have any custom modifications to any of the python libraries?

**Comment by slochower** [comment]
Python version 2.7.9

As far as I know, no custom modifications. Any way to check? The only thing I can think of that would be atypical is that python (and its dependencies) were installed by apt and jupyter (and its dependencies) were installed by pip.

**Comment by dwillmer** [comment]
Hmm... that shouldn't make a difference, but we can't rule it out yet.

I'll try to reproduce here with 2.7.9, in the meantime, are you familiar enough with gdb to attach it to the process and find out where it's crashing?

**Comment by minrk** [comment]
As a pyzmq dev, my first suspicion on this one is libzmq mismatch. What do you get from `python -c 'import zmq; print(zmq.zmq_version(), zmq.__version__)'` and `jupyter kernelspec list --json`

**Comment by slochower** [comment]
@dwillmer I've run gdb on C processes before, but when I try to attach it to jupyter notebook it tells me jupyter is not in executable format: file format not recognized. 

@minrk Here is the output of the two commands:
`('4.1.2', '14.7.0')`
and
```bash
{
  "kernelspecs": {
    "python2": {
      "resources_dir": "/usr/local/share/jupyter/kernels/python2", 
      "spec": {
        "language": "python", 
        "display_name": "Python 2", 
        "env": {}, 
        "argv": [
          "/usr/bin/python", 
          "-m", 
          "ipykernel", 
          "-f", 
          "{connection_file}"
        ]
      }
    }
  }
}

```

**Comment by minrk** [comment]
And `head -n 1 $(which jupyter-notebook)`?

**Comment by slochower** [comment]
#!/usr/bin/python

**Comment by minrk** [comment]
and `env | grep LIBRARY`?

**Comment by slochower** [comment]
...nothing. Apparently there's no LIBRARY in env.

**Comment by minrk** [comment]
That's a good thing :) It's a common source of problems, which is why I asked.

**Comment by slochower** [comment]
@dwillmer @minrk I didn't figure out how to attach gdb to the process, but I got the Ubuntu crash dialog to pop up and it looks like it's related to pyzmq. 

![screenshot from 2015-09-03 15 33 16](https://cloud.githubusercontent.com/assets/5393995/9672640/3168fb58-5251-11e5-9dc2-655596aaed06.png)

**Comment by minrk** [comment]
@slochower does it help to uninstall and reinstall pyzmq?

**Comment by slochower** [comment]
@minrk I used `dpkg -l | grep zmq` to find the zmq packages installed on my machine: libzmq-dev:amd64, libzmq1:amd64, libzmq3:amd64, python-zmq. I then purged and reinstalled them using apt. That had no effect.

But I also checked with `pip freeze | grep zmq` and I see `pyzmq==14.7.0` there. I uninstalled pyzmq from pip.

Now the notebook works in Firefox! Excellent. So maybe there was an issue with having python-zmq installed via apt and pyzmq installed with pip. I'm not sure how that happened. Is it possible that installing jupyter notebook via pip pulled in pyzmq, even though it was already installed via apt?

**Comment by minrk** [comment]
@slochower yes, it's definitely possible for there to be conflicts with different versions of pyzmq and libzmq on the system at the same time. Since pyzmq was installed with pip, one likely scenario:

1. libzmq was installed via apt
2. pyzmq installed with pip, linked libzmq
3. libzmq upgraded out from under pyzmq

This can cause the symptoms you described.
