### ISSUE TITLE
Funny but big bug - UI moving

### ISSUE THREAD

**Issue by projetmbc** [jupyter/notebook#379]
The following code will move anything of the UI of the notebook. I found this bug when testing HTML and CSS output with a code from the web.

    %%html 

    <!DOCTYPE html>
    <html>
    <head>
    <style> 
    div {
        width: 100px;
        height: 100px;
        background-color: red;
        position: relative;
        -webkit-animation-name: example; /* Chrome, Safari, Opera */
        -webkit-animation-duration: 4s; /* Chrome, Safari, Opera */
        -webkit-animation-iteration-count: infinite; /* Chrome, Safari, Opera */
        animation-name: example;
        animation-duration: 4s;
        animation-iteration-count: infinite;
    }

    /* Chrome, Safari, Opera */
    @-webkit-keyframes example {
        0%   {background-color:red; left:0px; top:0px;}
        25%  {background-color:yellow; left:200px; top:0px;}
        50%  {background-color:blue; left:200px; top:200px;}
        75%  {background-color:green; left:0px; top:200px;}
        100% {background-color:red; left:0px; top:0px;}
    }

    /* Standard syntax */
    @keyframes example {
        0%   {background-color:red; left:0px; top:0px;}
        25%  {background-color:yellow; left:200px; top:0px;}
        50%  {background-color:blue; left:200px; top:200px;}
        75%  {background-color:green; left:0px; top:200px;}
        100% {background-color:red; left:0px; top:0px;}
    }
    </style>
    </head>
    <body>

    <p><b>Note:</b> This example does not work in Internet Explorer 9 and earlier versions.</p>

    <div></div>

    </body>
    </html>

**Comment by Carreau** [comment]
I'm not quite sure why yon consider this a "bug" :-) The html magic allow you to inject arbitrary html/js/css on the page, so you can do whatever you like with the UI. And as you inject top level css it takes precedence.

That's how people [theme their notebooks](http://nbviewer.ipython.org/github/wrobstory/bearcart/blob/8a65684830f4f0d63b455120ae329c3ebb479572/examples/bearcart_examples.ipynb)


I think what you want is to try wrapping all in the iframe to isolate the CSS :-) 

closing, feel free to continue commenting if you have more questions/feedback.

**Comment by projetmbc** [comment]
Ok. Maybe a safe mode could allow to avoid this kind of things.


*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French math teacher in a "Lycée" **and **Python **amateur developer*

2015-09-02 9:23 GMT+02:00 Matthias Bussonnier <notifications@github.com>:

**Comment by projetmbc** [comment]
Hello.

I know that user can change CSS for all the Jupiter notebook even if I do
not know how to do that.

I think that it could be very useful to have an easy way to set the theme
of Jupiter. The screenshot joined shows that some output can be confusing
when using %%html for example, or other description language.

Best regards.

*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French math teacher in a "Lycée" **and **Python **amateur developer*

**Comment by Carreau** [comment]
> The screenshot joined shows that some output can be confusing
> when using %%html for example, or other description language.

Attached images don't work by e=mail, you have to go through github UI to post screenshots. 


> I know that user can change CSS for all the Jupiter notebook even if I do
> not know how to do that.

You "just" need to drop a file name `custom.css` in you `.jupyter/custom/` folder.

**Comment by projetmbc** [comment]
Thanks for the custom.css

I put the picture for the history...


*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French math teacher in a "Lycée" **and **Python **amateur developer*

2015-09-07 14:39 GMT+02:00 Matthias Bussonnier <notifications@github.com>:

**Comment by Carreau** [comment]
Well, the issue you encounter here, is that having exactly the same rendering is expected in many case, and is what users want to have.  %%HTML  is a [minimal wrapper](https://github.com/ipython/ipython/blob/master/IPython/core/magics//display.py#L49-L52) around the display protocol. You can if you like redefine it to wrap your output in a div with a border to make it clear:

```
from IPython.display import HTML, display
from IPython.core.magic import register_cell_magic

@register_cell_magic
def html(line, cell):
    display(HTML("<div style='border:thin solid red'>"+cell+"</div>"))
```

**Comment by projetmbc** [comment]
Thanks a lot for this solution.

The problem in my case is that markdown is used to formate a document about
HTML and the HTML output example is not expected to be the document output.

I will play with the css you iodinate to me just to add some background
color.


*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French math teacher in a "Lycée" **and **Python **amateur developer*

2015-09-07 15:13 GMT+02:00 Matthias Bussonnier <notifications@github.com>:

**Comment by Carreau** [comment]
> The problem in my case is that markdown is used to formate a document about
> HTML and the HTML output example is not expected to be the document output.

I don't get this part. 

> I will play with the css you iodinate to me just to add some background
> color.

iodinate seem to be autocorrect being overzealous.

**Comment by projetmbc** [comment]
In a cell, we can use Markdown qo


*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French math teacher in a "Lycée" **and **Python **amateur developer*

2015-09-07 17:45 GMT+02:00 Matthias Bussonnier <notifications@github.com>:

**Comment by Carreau** [comment]
well, `%%html` is really meant as a convenience to try things, it was not really design to teach, but more the try out what some html would do before writing some code. 

The fact that the style of output, and markdown cell is the same is on purpose, as it is actually a feature most people want. 

With css you should be able to style the notebook for your student for the distinction to be clearer.

**Comment by projetmbc** [comment]
I understand. I will add and explain how the hack works to my student.
