### ISSUE TITLE
Jupyter TLS configuration to disable TLS versions

### ISSUE THREAD

**Issue by charlieeeeeee** [jupyter/notebook#3790]
Hi,

Is there a way to only enable TLS v1.2 for Jupyter webserver? Currently Jupyter webserver starts with support of 1.0 and 1.2. We want to disable TLS v1.0 and only use v1.2.

Thanks,
Charlie

**Comment by charlieeeeeee** [comment]
I think I found a potential solution, inside the jupyter_notebook_config.py, there is a `ssl_options` field where it's a dictionary for additional ssl options for sslcontext creation, setting `ssl_version` to `5`, which is the ssl.PROTOCOL_TLSv1_2 will only support TLSv1.2.

**Comment by jordangarrison** [comment]
Hi @charlieeeeeee, were you able to successfully force TLS1.2 for the jupyternotebook? My attempts shown below have not allowed communication on that protocol, it still defaults to TLSv1.

Below is inside my jupyter_notebook_config.py
```python
c.NotebookApp.ssl_options = {
    'ssl_version': ssl.PROTOCOL_TLSv1_2
}
```

When attempting to connect via open ssl
```bash
open_ssl s_client -connect myhost:8888 -tls1_2
```
Returns the following error in my log
```
SSL Error on ******** [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:720)
```

I also attempted using ssl_version as 5 as you stated before which unfortunately did not allow the server to start.

Versions:
```bash
jupyter notebook --version
5.0.0

python --version
Python 3:5:3 :: Anaconda custom (64-bit)
```

I apologize for posting on a closed issue, just wanted to know how you were able to resolve this.

**Comment by hirayaku** [comment]
@jordangarrison You should probably import the ssl module first in jupyter_notebook_config.py.

**Comment by rouckas** [comment]
@jordangarrison , you need to set
```
c.NotebookApp.ssl_options = {
        "ssl_version": 5,
        }
```
This worked for me

> Hi @charlieeeeeee, were you able to successfully force TLS1.2 for the jupyter notebook? My attempts shown below have not allowed communication on that protocol, it still defaults to TLSv1.
> 
> Below is inside my jupyter_notebook_config.py
> 
> ```python
> c.NotebookApp.ssl_options = {
>     'ssl_version': ssl.PROTOCOL_TLSv1_2
> }
> ```
