### ISSUE TITLE
Password change doesn't affect open connections

### ISSUE THREAD

**Issue by findesgh** [jupyter/notebook#3794]
Here's the procedure:
- start server with old password
- log in in browser
- kill server
- change password and bring server back up
- continue working in browser without having to enter new password (old kernels are gone of course)

Is this intended behavior? Can I reset such open connections when I change the password on my server?

I couldn't find anything on Google, by maybe I don't know what to look for.
Thanks.

**Comment by takluyver** [comment]
What version of the notebook are you using? This should have been changed for notebook 5.3 in pull request #3009.
