### ISSUE TITLE
swap alt-enter and ctrl-enter because there's no alt on right side of MacBook keyboard

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#380]
and frequently we want to rerun and present results only, not both hands are on keyboard. when we want new cell, often both hands are on keyboard, so ctrl enter can both be reached

**Comment by Carreau** [comment]
by default we will most likely not change the keyboard shortcut are they have been historically like that for too long.

If you like to swap these you can unbind/rebind your shortcut in shortcuts in custom.js, 
you could even have execute in place which is only one key, or bound to a remote if you like.
