### ISSUE TITLE
Getting the source of an object defined in a Jupyter Notebook

### ISSUE THREAD

**Issue by spott** [jupyter/notebook#3802]
Usually, if you want to get the source of an object, you can get it via the inspect module:

```
import inspect
inspect.getsource(MyObject)
```

However, in a Jupyter notebook, this doesn't work:

```
import inspect

class Foo:
    def __init__(self, info):
        self.info = info

inspect.getsource(Foo)
```

Throws a TypeError: `TypeError: <module '__main__'> is a built-in class`.  This is because `__file__` isn't defined in jupyter notebooks.

Is there a way to inspect an object to get its source in a Jupyter notebook?  The only way that comes to mind is something like `get_ipython` and then walking the history until you find the class definition you want.  Is there another way?

**Comment by spott** [comment]
This might be a ipython problem, rather than a Jupyter problem...  I'm going to cross post it there as well, until someone tells me otherwise.

**Comment by PhilipMay** [comment]
Interesting question. Is there a solution?

**Comment by kevin-bates** [comment]
Yes - this would be something dealt with in IPython and not an issue for this repository.  
Here's the cross-posted issue for reference: https://github.com/ipython/ipython/issues/11249

**Comment by PhilipMay** [comment]
Thanks
