### ISSUE TITLE
how to read dataset from local computer file in jupyter notebook

### ISSUE THREAD

**Issue by suri199507** [jupyter/notebook#3805]
in which place keep our download dataset can any one can help me and please give instructions to load and read dataset in jupyter note book
import pandas as pd 
df=pd.read_csv('../input/Accounts.csv')
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-9-4305e6d3f45e> in <module>()
      1 import pandas as pd
----> 2 df=pd.read_csv('../input/Accounts.csv')

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    676                     skip_blank_lines=skip_blank_lines)
    677 
--> 678         return _read(filepath_or_buffer, kwds)
    679 
    680     parser_f.__name__ = name

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    438 
    439     # Create the parser.
--> 440     parser = TextFileReader(filepath_or_buffer, **kwds)
    441 
    442     if chunksize or iterator:

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    785             self.options['has_index_names'] = kwds['has_index_names']
    786 
--> 787         self._make_engine(self.engine)
    788 
    789     def close(self):

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
   1012     def _make_engine(self, engine='c'):
   1013         if engine == 'c':
-> 1014             self._engine = CParserWrapper(self.f, **self.options)
   1015         else:
   1016             if engine == 'python':

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   1706         kwds['usecols'] = self.usecols
   1707 
-> 1708         self._reader = parsers.TextReader(src, **kwds)
   1709 
   1710         passed_names = self.names is None

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: File b'../input/Accounts.csv' does not exist

​

**Comment by staeiou** [comment]
Hi, that is the right way to use pandas, but it looks like you're using a relative path -- the "../" to mean one directory up. Try using the full path  (`/home/username/input/Accounts.csv` or `C:\Users\Documents\input\Accounts.csv`) and see if that works. You can also run a cell with `!pwd` to see your current working directory, which is what will be used to look for relative paths.

**Comment by suprsankr** [comment]
@staeiou Hi, is it necessary  to reset csv reader to the beginning of the file if file read happens in a loop ? 
I have a csv file (stored in librecalc) with 50K+ columns but only 1024 of them are read after the first time. I have tried stopping the notebook, interrupting the kernel, resetting the file pointer with f.seek(0) but nothing works. What is the right way to do read.csv() ? 

I have checked the csv file also.Is there a way to standardize the csv file before using read.csv ?

**Comment by thevinils** [comment]
@staeiou thank you!

**Comment by dipanshi08** [comment]
can anyone provide the solution for .wav files

**Comment by ONEROMYLIME** [comment]
In addition if you are still getting a SyntaxError: (unicode error) 'unicodeescape'   
Just put  r  before your normal string it converts normal string to raw string:
 ( r ' C:\Users\Documents\input\Accounts.csv')

**Comment by jeevanthask** [comment]
df = pd.read_csv(r"C:\Users\nandika\Desktop\homeprices.csv") use this way

**Comment by rishikeshF** [comment]
> Hi, that is the right way to use pandas, but it looks like you're using a relative path -- the "../" to mean one directory up. Try using the full path (`/home/username/input/Accounts.csv` or `C:\Users\Documents\input\Accounts.csv`) and see if that works. You can also run a cell with `!pwd` to see your current working directory, which is what will be used to look for relative paths.

hey, thanks this worked for me

**Comment by dkm17113034** [comment]
data=pd.read_csv(r'C:\Users\dell\Desktop\Machine Learning A-Z Template Folder\Part 2 - Regression\Section 4 - Simple Linear Regression\salary_data.csv')

try like this

**Comment by Bikashiitbhu** [comment]
> df = pd.read_csv(r"C:\Users\nandika\Desktop\homeprices.csv") use this way

thanku, this helped.

**Comment by ShrishtiHore** [comment]
Just add a "r" like this:

df=pd.read_csv(r'C:\Users\Shrishti D Hore\Downloads\master.csv')

It works for me every time !!!!!

**Comment by kmair** [comment]
Get the current directory as:
`import os`
`os.getcwd()`
Say it gives: 'C:\\...\\usr' and your file is located in: 'C:\\...\\usr\\data\\csv_file.csv' 

Then write:
`pd.read_csv('data/csv_file.csv')`

If it's not located in the same route, then write:
`pd.read_csv('path/../to/../data/csv_file.csv')`

**Comment by HavinRaj** [comment]
> df = pd.read_csv(r"C:\Users\nandika\Desktop\homeprices.csv") use this way

it worked...Yay!
BTW wat does that r mean here - _csv(r"C:\

**Comment by SPScientist** [comment]
> Just add a "r" like this:
> 
> df=pd.read_csv(r'C:\Users\Shrishti D Hore\Downloads\master.csv')
> 
> It works for me every time !!!!!

Thanks , it's working for me.

**Comment by tnbie** [comment]
> data=pd.read_csv(r'C:\Users\dell\Desktop\Machine Learning A-Z Template Folder\Part 2 - Regression\Section 4 - Simple Linear Regression\salary_data.csv')
> 
> try like this

this solve my little problem. really nice.

**Comment by mplatt7** [comment]
I am having trouble with this on a Mac. I've searched for hours, read the above and tried everything I can think of. Why won't the following work (I get the FileNotFound error)?

df = pd.read_excel(r"C:\Users\MPlatt\Downloads\TorontoPostcodes.xls")

Also, if you import the excel file into your Notebook space, do you have to prefix the file name somehow for the code the recognize it? The following does not work either for a file that has been uploaded:

df = pd.read_excel("TorontoPostcodes.xls")

**Comment by Akashdhas** [comment]
> Hi, that is the right way to use pandas, but it looks like you're using a relative path -- the "../" to mean one directory up. Try using the full path (`/home/username/input/Accounts.csv` or `C:\Users\Documents\input\Accounts.csv`) and see if that works. You can also run a cell with `!pwd` to see your current working directory, which is what will be used to look for relative paths.

**Comment by mplatt7** [comment]
Thanks, I’ll try this

**Comment by kevin-bates** [comment]
Lots of successes, thank you for the great responses!

**Comment by umakolluru98** [comment]
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import math
from sklearn.metrics import roc_auc_score
import numpy as np

train_data=r'C:\data bd_train.csv'
test_data=r'C:\data bd_test.csv'
cd_tr=pd.read_csv(train_data)
cd_te=pd.read_csv(test_data)
#5399 after running this code getting the error as below
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-28-4fbd7e4fe13b> in <module>
----> 1 cd_tr=pd.read_csv(train_data)
      2 cd_te=pd.read_csv(test_data)

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    683         )
    684 
--> 685         return _read(filepath_or_buffer, kwds)
    686 
    687     parser_f.__name__ = name

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    455 
    456     # Create the parser.
--> 457     parser = TextFileReader(fp_or_buf, **kwds)
    458 
    459     if chunksize or iterator:

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)

**Comment by B-Tejaswini214** [comment]
please tell how to fix ir
![Screenshot (129)](https://user-images.githubusercontent.com/63362338/80910020-79df6000-8d4a-11ea-8cf6-a95504a9b077.png)

**Comment by quique123** [comment]
I tried all these and none worked.  I had to move the csv into my jupyter notebook folder

**Comment by nagarajungh** [comment]
File not found error 

Import pandas as pd
df = pd.read_csv(r"C:\User\99666\raju\datafile")

Am getting file not found error 
Am trying get my datafile of type csv , from my local machine to Jupyter notebook

**Comment by nagarajungh** [comment]
> I tried all these and none worked. I had to move the csv into my jupyter notebook folder

Hi 
Please help me if u r able to solve similar issue

**Comment by nagarajungh** [comment]
> please tell how to fix ir
> ![Screenshot (129)](https://user-images.githubusercontent.com/63362338/80910020-79df6000-8d4a-11ea-8cf6-a95504a9b077.png)

Hi,
What's ur issue here, r u looking formatted output?

**Comment by d-coder-hub** [comment]
I was having the same problem...but then i tried launching jupyter by anaconda prompt and i am glad that works.
**Steps**
1.Run anaconda prompt as run as administrator
2. change directory to where your dataset is stored and the command  to change directory is cd "filepath". It will be easy if can save your dataset and your ipnyb file(jupyter notebook file on which u are working) into one folder and specify this folder path by cd "filepath".
3. Launch jupyter and for that write jupyter notebook and press enter.
4.import pandas as pd
iris=pd.read_csv('iris.csv')


![Capture](https://user-images.githubusercontent.com/75610388/104819135-84e30d80-5851-11eb-85e3-21ca52db4a03.PNG)
