### ISSUE TITLE
Cannot set profile from command line

### ISSUE THREAD

**Issue by Zaharid** [jupyter/notebook#381]
For the most recent Anaconda release of the stack (4.0), if I cannot set a custom profile from command the command line even with the command explicitly suggested by the help:

````
zah@zah-XPS13-9333 ~ $ ipython notebook --profile pbs
...

To see all available configurables, use `--help-all`

Examples
--------

    ipython notebook                       # start the notebook
    ipython notebook --profile=sympy       # use the sympy profile
    ipython notebook --certfile=mycert.pem # use SSL/TLS certificate

[C 18:43:59.260 NotebookApp] Bad config encountered during initialization:
[C 18:43:59.260 NotebookApp] Unrecognized flag: '--profile'
zah@zah-XPS13-9333 ~ $ ipython notebook --profile=pbs
[W 18:44:14.994 NotebookApp] Unrecognized alias: '--profile=pbs', it will probably have no effect.
...
````

**Comment by Carreau** [comment]
closed 3 weeks ago by #277. 

Thanks.

**Comment by rodrigofarnhamsc** [comment]
So how is a custom profile passed in now?

**Comment by takluyver** [comment]
The notebook is now part of [Jupyter](http://jupyter.org/), which doesn't have profiles - though you can still switch to a different config directory by setting an environment variable.

The IPython kernel can still use profiles - you'd need to create a kernelspec for each profile and edit the arguments in kernel.json to tell it which profile to launch in.

**Comment by Carreau** [comment]
See [the docs](https://jupyter.readthedocs.org/), in particular how to [migrate](https://jupyter.readthedocs.org/en/latest/migrating.html, more especially [what hapend to `profile`](https://jupyter.readthedocs.org/en/latest/migrating.html#profiles)
