### ISSUE TITLE
[Feature Request] List hidden files if ContentsManager.allow_hidden=True

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter/notebook#3812]
***xref:*** https://github.com/jupyterlab/jupyterlab/issues/2049

**Comment by dhirschfeld** [comment]
Not sure if this should be implemented here or in https://github.com/jupyter/jupyter_server?

**Comment by atamahjoubfar** [comment]
+1

**Comment by liuderchi** [comment]
+1

**Comment by pawbz** [comment]
+1

**Comment by JiaweiZhuang** [comment]
+1 on this...

**Comment by zhouyangnk** [comment]
+1
and files like xxx.so also invisible
