### ISSUE TITLE
One unique ID per notebook

### ISSUE THREAD

**Issue by adrianschneider94** [jupyter/notebook#3820]
Hi everyone!

For a project i need to store data in the notebook itself. However, as far as I found, this is not possible, am I right?

I don‘t know exactly why this design decision was made, but maybe it would be ok, that every notebook get‘s one unique ID, which can be accessed? Then I could store the notebook-specific data in a database.

Why do I need this?

I‘m planning a technical design software. For this I want to build a GUI with ipywidgets. When the design is finished, it‘s saved to a database.
But as I want that side calculations are possible specifically for every design, I want one Notebook per design.
That means, that every notebook must be associated with one design which gets loaded from the database when the Design GUI is started. For this one-to-one relationship I need to identify the notebook somehow. This is why I need an ID.

Best wishes
Adrian Schneider

**Comment by adrianschneider94** [comment]
I found a solution:
https://github.com/adrianschneider94/notebook_id

This nbextension stores a UUID in the notebook metadata and loads it into python when the notebook loads or the kernel is restarted.

**Comment by takluyver** [comment]
Unique IDs are tricky. If you store it in the metatadata, then copying the file means your ID is no longer unique.

**Comment by adrianschneider94** [comment]
That‘s absolutely right 🤔

My solution was just the shortest path to what I wanted to achieve and it works well enough for my problem.

I would definitely prefer that jupyter handles this — so that one can truly identify one notebook as unique.
I guess it‘s possible with inodes. But it‘s OS dependent and rather cumbersome to write.

**Comment by takluyver** [comment]
Unfortunately, I'm not sure there's any way to achieve a sensible 'unique ID' for a notebook, assuming you want the ID to persist if the notebook is modified or moved, but copies to get a new ID.
