### ISSUE TITLE
The python `notebook==5.6.0` wheel on pypi is missing three *.map files

### ISSUE THREAD

**Issue by mprogram** [jupyter/notebook#3823]
…which gives me the following 404 errors:

`[W 14:01:23.924 LabApp] 404 GET /static/components/proptypes/index.js.map (127.0.0.1) 34.31ms referer=None`
`…`
`[W 14:01:23.929 LabApp] 404 GET /static/components/preact/preact.min.js.map (127.0.0.1) 3.81ms referer=None`
`…`
`[W 14:01:23.934 LabApp] 404 GET /static/components/preact-compat/preact-compat.min.js.map (127.0.0.1) 4.73ms referer=None`

They also do now show up when building the wheel from source (though being mentioned in `bower.json`!)

**Comment by jtpio** [comment]
Closing as this version is not supported anymore.
