### ISSUE TITLE
Breaks with python-2.7

### ISSUE THREAD

**Issue by yurivict** [jupyter/notebook#3825]
```setup.py``` says that it is compatible with python-2.7, but this error occurs:
```
byte-compiling /usr/ports/www/py-notebook/work-py27/stage/usr/local/lib/python2.7/site-packages/notebook/tests/selenium/utils.py to utils.pyc
  File "/usr/local/lib/python2.7/site-packages/notebook/tests/selenium/utils.py", line 206
    def append(self, *values, cell_type="code"):
                                      ^
SyntaxError: invalid syntax
```

Found in the FreeBSD port, version 5.6.0

I suggest that you should maintain compatibility with python-2.7 because Jupiter needs to be able to run all sorts of python packages, some of which might not yet work on python3.

**Comment by shexiaogui** [comment]
I got similar problem when have 5.6.0 with python 2.7.15. It seems the urllib.parse is only in python 3 (https://docs.python.org/2/library/urlparse.html)
 
ConftestImportFailure: ImportError('No module named parse',)
   File "/var/lib/jenkins/workspace/dasense_analytics_develop/dslstack/lib/python2.7/site-packages/notebook/tests/selenium/conftest.py", line 9, in <module>
      from urllib.parse import urljoin

**Comment by Carreau** [comment]
This is strange as we do run test on 2.7 and they pass. It's just the UI test that can't be run on 2.7.

> I suggest that you should maintain compatibility with python-2.7 because Jupiter needs to be able to run all sorts of python packages

No, the kernel runs code, not the server. The server could be in Go/Rust/C or Ruby as far as you are concern. Also IPykernel (which does run the code) has already been python 3 only for a year or so,  if you need to run Python 2.7 code you will not get the latest version of the kernel already.

We could change the code to run the selenium test from Python 3 while the server runs python2, but that seem like a hassle.

Closing as we are not likely to fix that; and will anyway stop Python 2 support in the server as well pretty soon. 

Feel free to keep commenting or ask for reopening if you'd like. 
If you send a Pull-request fixing it may still be accepted.
