### ISSUE TITLE
Jupyter notebook list unexisting servers

### ISSUE THREAD

**Issue by debuggy** [jupyter/notebook#3828]
Hi, I started a jupyter server in other process  with childProcess.spawn(), and killed the process tree before existing. There is no jupyter or python related processes in process monitor anymore. 

However, the "jupyter notebook list" command still shows the server I have killed, unless I manually delete the runtime file. What the reason about this command behavior? Thanks.

System version: win10
```
> jupyter notebook list
Currently running servers:
http://localhost:8888/?token=abcd :: c:\Users\xxx\project\notebooks // this server process does not exist any more
```

**Comment by takluyver** [comment]
If the server info file is still there, we check the PID recorded in that file. But another process can have got the same PID after the notebook server was killed. In that case, it looks like the server is still there.

It's preferable to always ask the server to shut down cleanly, e.g. by calling `notebook.notebookapp.shutdown_server` with the info of the server you want to stop. That lets it clean up the server info file it created. If you kill it, it can't do that.

**Comment by debuggy** [comment]
Thanks for the reply. In my practice, using shutdown api is better than just killing the process. I will close this issue then.
