### ISSUE TITLE
Latex /binom not rendered properly by mathjax

### ISSUE THREAD

**Issue by enriquefernandez** [jupyter/notebook#386]
In one of my computers /binom is not rendered properly by mathjax in a markdown cell.
Instead, the cell shows /mathjoice (in red)

The code

```
\begin{align}
\binom{n}{k} = \frac{n!}{k! (n-k)!}
\end{align}
```

Is displayed as:

![untitled](https://cloud.githubusercontent.com/assets/709535/9661066/f9fca75c-5226-11e5-8061-42b540e0e68f.png)

I'm running Jupyter 4.0 installed through conda in OSX Yosemite. I've tried both Safari and Chrome and I get the same results.

I get the following interesting javascript error in the Chrome Developer Console:

![untitled](https://cloud.githubusercontent.com/assets/709535/9661105/32afbcf6-5227-11e5-980c-6c83070a4f94.png)
```
Font from origin 'null' has been blocked from loading by Cross-Origin Resource Sharing policy: Received an invalid response. Origin 'http://localhost:8888' is therefore not allowed access. Untitled.ipynb:1

Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8888/static/components/MathJax/extensions/TeX/mathchoice.js?rev=2.5.3 
```

I've tried installing mathjax locally, but it hasn't solved the issue.

Interestingly, this works fine in my laptop, which is supposedly running the same setup with the same versions.

I'm pretty sure this used to work fine and just broke recently.

Any ideas?

Thanks!

**Comment by Carreau** [comment]
This has already been fixed  by #324, it will be in 4.1.

Cf ipython/ipython#8754 also.
