### ISSUE TITLE
Error in launching the jupyter notebook kernel

### ISSUE THREAD

**Issue by kartikeya-gupta** [jupyter/notebook#3861]
Hi,
I am facing 'failed to start kernel' error in jupyter notebook. I am facing the same error in all python environments that I am using. Any clue to resolve this will be helpful.

> Traceback (most recent call last):
>   File "C:\Anaconda2\lib\site-packages\notebook\base\handlers.py", line 457, in wrapper
>     result = yield gen.maybe_future(method(self, *args, **kwargs))
>   File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1133, in run
>     value = future.result()
>   File "C:\Anaconda2\lib\site-packages\tornado\concurrent.py", line 261, in result
>     raise_exc_info(self._exc_info)
>   File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1141, in run
>     yielded = self.gen.throw(*exc_info)
>   File "C:\Anaconda2\lib\site-packages\notebook\services\sessions\handlers.py", line 62, in post
>     kernel_id=kernel_id))
>   File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1133, in run
>     value = future.result()
>   File "C:\Anaconda2\lib\site-packages\tornado\concurrent.py", line 261, in result
>     raise_exc_info(self._exc_info)
>   File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1141, in run
>     yielded = self.gen.throw(*exc_info)
>   File "C:\Anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
>     kernel_name)
>   File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1133, in run
>     value = future.result()
>   File "C:\Anaconda2\lib\site-packages\tornado\concurrent.py", line 261, in result
>     raise_exc_info(self._exc_info)
>   File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1141, in run
>     yielded = self.gen.throw(*exc_info)
>   File "C:\Anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
>     self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
>   File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1133, in run
>     value = future.result()
>   File "C:\Anaconda2\lib\site-packages\tornado\concurrent.py", line 261, in result
>     raise_exc_info(self._exc_info)
>   File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 326, in wrapper
>     yielded = next(result)
>   File "C:\Anaconda2\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
>     super(MappingKernelManager, self).start_kernel(**kwargs)
>   File "C:\Anaconda2\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
>     km.start_kernel(**kwargs)
>   File "C:\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 244, in start_kernel
>     self.start_restarter()
>   File "C:\Anaconda2\lib\site-packages\jupyter_client\ioloop\manager.py", line 52, in start_restarter
>     self._restarter.start()
>   File "C:\Anaconda2\lib\site-packages\jupyter_client\ioloop\restarter.py", line 47, in start
>     self._pcallback.start()
>   File "C:\Anaconda2\lib\site-packages\tornado\ioloop.py", line 1209, in start
>     self._schedule_next()
>   File "C:\Anaconda2\lib\site-packages\tornado\ioloop.py", line 1237, in _schedule_next
>     self._update_next(self.io_loop.time())
>   File "C:\Anaconda2\lib\site-packages\tornado\ioloop.py", line 1244, in _update_next
>     callback_time_sec *= 1 + (self.jitter * (random.random() - 0.5))
> TypeError: unsupported operand type(s) for *: 'ZMQIOLoop' and 'float'

Specifications:
Windows 10
conda - 4.5.0

**Comment by kartikeya-gupta** [comment]
I figured out the problem. I had to downgrade tornado from 5.1 to 4.5.3 to make it compatible with pyzmq 17.
Alternatively, I could have upgraded my conda as well.
I found the solution here - https://github.com/jupyter/notebook/issues/3407

**Comment by ksaliya** [comment]
> I figured out the solution. I had to downgrade tornado from 5.1 to 4.5.3 to make it compatible with pyzmq 17.
> Alternatively, I could have upgraded my conda as well.
> I found the solution here - #3407

Had the same problem and this solved it. However resulted in [#3895](https://github.com/jupyter/notebook/issues/3895). Had to run jupyter in a different port to get it working.
