### ISSUE TITLE
Swagger API

### ISSUE THREAD

**Issue by iiSeymour** [jupyter/notebook#387]
In the 3.X releases `/api` served the IPython version as a JSON object, however the 4.X releases return a 404 and `master` serves [api.yaml](https://github.com/jupyter/notebook/blob/master/notebook/services/api/api.yaml) [raw](https://github.com/jupyter/notebook/blob/master/notebook/services/api/handlers.py#L18).

Are all API routes eventually being migrated to use the swagger framework and `/api` will be a discovery route or should `/api` still return the version?

**Comment by minrk** [comment]
It was a mistake to merge the PR that put the YAML file on /api. I didn't realize that clobbered the existing endpoint. That should be considered a bug, and the experimental swagger stuff should be moved somewhere else.

**Comment by gibiansky** [comment]
What's the current status of this? Is there a way to get the Jupyter API as a Swagger JSON spec?

That would be very cool -- I would potentially migrate IHaskell to be part autogenerated from Swagger if that were easily available...

**Comment by minrk** [comment]
The version in master is in pretty good shape, I think. @blink1073 did most of it while writing jupyter-js-services, a JS client for the REST API.
