### ISSUE TITLE
Remove Run/Execute Arrow on Hover

### ISSUE THREAD

**Issue by robertdefilippi** [jupyter/notebook#3891]
Hello,

This is more of a UI request / questions.

Whenever I hover over a cell a "Run/Execute" arrow appears next to the "In". I was wondering if it was possible to disable this?

Thanks,

<img width="193" alt="screen shot 2018-08-30 at 9 19 43 am" src="https://user-images.githubusercontent.com/9288605/44865151-61927600-ac36-11e8-9383-bba35ed8ea58.png">

**Comment by takluyver** [comment]
This was removed in notebook 5.7, except for touchscreens.
