### ISSUE TITLE
stderr and stdout are indented in notebook 5.6

### ISSUE THREAD

**Issue by eaton-lab** [jupyter/notebook#3902]
The stderr and stdout from print statements seems to be indented by several spaces since notebook 5.6. I confirmed by downgrading to 5.5 (it went away) and re-upgrading (it came back). The image below contrasts the indentation in 5.5 (right) versus 5.6 (left). 

![image](https://user-images.githubusercontent.com/25778715/45186578-f92a3280-b1fb-11e8-94ea-c31c9d3f8c0a.png)

I did not see any reference to this in the changelog as being a stylistic choice. My two cents is that I prefer the non-indented behavior. It looks particularly odd/buggy when printing to stderr since the entire pink box is indented and the hover box when you mouse over does not align well.

![image](https://user-images.githubusercontent.com/25778715/45186967-30e5aa00-b1fd-11e8-967c-03e1cad0d75b.png)

**Comment by eaton-lab** [comment]
Behavior observed in Firefox.

**Comment by minrk** [comment]
Fixed by #3772
