### ISSUE TITLE
UI glitches in input cells

### ISSUE THREAD

**Issue by fonnesbeck** [jupyter/notebook#3903]
Using notebook 5.6 with Chrome as a browser, I am experiencing odd glitches with the input cells. As an example, most of the cells on the screen shot below do not actually have code in them (the ones that do not have load statements):

![image](https://user-images.githubusercontent.com/81476/45249018-7fb74080-b2de-11e8-8d2a-c948f97b7014.png)

You can see that one is even showing output from another location. When you activate any of these cells for editing, the artifact goes away:

![image](https://user-images.githubusercontent.com/81476/45249045-f5bba780-b2de-11e8-8110-64941098a0a7.png)

I've seen this behavior now running the notebook from my local machine and on a cluster.

Incase it is helpful, [here is a video screen grab of interaction with the notebook](https://d.pr/v/s9noz4)

Is this a notebook bug, or a browser issue?

**Comment by minrk** [comment]
I think these have come up a few times, mostly with Chrome. I think they've been due to browser rendering optimizations skipping repaints when they are actually needed. I'm not sure what we are doing to trigger it, but I do think its a browser bug.

**Comment by fonnesbeck** [comment]
That sounds right. I thought it was a Jupyter issue, but it looks like Chrome was updated automatically without my realizing it, and I have had this issue since.
