### ISSUE TITLE
base/js/dialog.js implicitly requires bootstrap, should be made explicit

### ISSUE THREAD

**Issue by jcb91** [jupyter/notebook#391]
The `modal.modal(...);` call on [line 126](https://github.com/jupyter/notebook/blob/master/notebook/static/base/js/dialog.js#L126) implicitly requires bootstrap to have been loaded for the modal method to be defined.
This appears not to be a problem for most of the notebook, since bootstrap will already be loaded, but for any extensions, it would be nice to make the dependency explicit by, e.g., calling `require('bootstrap');` in a similar manner to that used in [lines 7-8](https://github.com/jupyter/notebook/blob/master/notebook/static/base/js/dialog.js#L7-L8).

**Comment by Carreau** [comment]
Do you want to send a PR ?

**Comment by jcb91** [comment]
Sure, submitted. I wasn't sure how to attach it to this issue, so it shows up as #393
