### ISSUE TITLE
C++ Kernel Died Repeatedly on Windows

### ISSUE THREAD

**Issue by bowenfan2016** [jupyter/notebook#3920]
Hi, 
I've installed C++ kernels for Jupyter Notebook on Windows10 with `xeus-cling`. It did show kernels with drop-down menus. But every time I start a C++ kernel, it dies repeatedly. Here is the error message the Windows cmd reported.

> jupyter notebook
[I 18:39:04.304 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 18:39:04.320 NotebookApp] JupyterLab beta preview extension loaded from D:\VisualStudio2017_enterprise\Shared\Anaconda3_64\lib\site-packages\jupyterlab
[I 18:39:04.320 NotebookApp] JupyterLab application directory is D:\VisualStudio2017_enterprise\Shared\Anaconda3_64\share\jupyter\lab
[I 18:39:04.492 NotebookApp] Serving notebooks from local directory: C:\Users\TEL6478892516
[I 18:39:04.492 NotebookApp] 0 active kernels
[I 18:39:04.492 NotebookApp] The Jupyter Notebook is running at:
[I 18:39:04.492 NotebookApp] http://localhost:8888/?token=4cbd6f4c9e156dae1a10c155a52ac7a2d3d5c4f492a39072
[I 18:39:04.492 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:39:04.507 NotebookApp]
Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=4cbd6f4c9e156dae1a10c155a52ac7a2d3d5c4f492a39072&token=4cbd6f4c9e156dae1a10c155a52ac7a2d3d5c4f492a39072

> [I18:39:04.648 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 18:39:11.206 NotebookApp] Creating new notebook in /Desktop
[I 18:39:12.353 NotebookApp] Kernel started: 7bd63024-bbf1-410e-8a74-5898c6f1d8f0
2
2
ERROR in cling::CIFactory::createCI():
  resource directory C:/bld/xeus-cling_1536182173380/_b_env/Library\lib\clang\5.0.0 not found!
In file included from input_line_1:1:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\new:6:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\exception:7:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\yvals.h:7:
D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\yvals_core.h:294:5: error: STL1000: Unexpected compiler version, expected Clang 6 or newer.
   #error STL1000: Unexpected compiler version, expected Clang 6 or newer.
    ^
In file included from input_line_1:1:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\new:6:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\exception:8:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\type_traits:6:
D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\xstddef:338:2: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
        auto _Unfancy(_Ptrty _Ptr)
        ^
[I 18:39:15.352 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
2
2
ERROR in cling::CIFactory::createCI():
  resource directory C:/bld/xeus-cling_1536182173380/_b_env/Library\lib\clang\5.0.0 not found!
In file included from input_line_1:1:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\new:6:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\exception:7:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\yvals.h:7:
D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\yvals_core.h:294:5: error: STL1000: Unexpected compiler version, expected Clang 6 or newer.
   #error STL1000: Unexpected compiler version, expected Clang 6 or newer.
    ^
In file included from input_line_1:1:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\new:6:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\exception:8:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\type_traits:6:
D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\xstddef:338:2: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
        auto _Unfancy(_Ptrty _Ptr)
        ^
[I 18:39:18.429 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
2
2
ERROR in cling::CIFactory::createCI():
  resource directory C:/bld/xeus-cling_1536182173380/_b_env/Library\lib\clang\5.0.0 not found!
In file included from input_line_1:1:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\new:6:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\exception:7:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\yvals.h:7:
D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\yvals_core.h:294:5: error: STL1000: Unexpected compiler version, expected Clang 6 or newer.
   #error STL1000: Unexpected compiler version, expected Clang 6 or newer.
    ^
In file included from input_line_1:1:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\new:6:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\exception:8:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\type_traits:6:
D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\xstddef:338:2: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
        auto _Unfancy(_Ptrty _Ptr)
        ^
[I 18:39:21.487 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
2
2
ERROR in cling::CIFactory::createCI():
  resource directory C:/bld/xeus-cling_1536182173380/_b_env/Library\lib\clang\5.0.0 not found!
In file included from input_line_1:1:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\new:6:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\exception:7:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\yvals.h:7:
D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\yvals_core.h:294:5: error: STL1000: Unexpected compiler version, expected Clang 6 or newer.
   #error STL1000: Unexpected compiler version, expected Clang 6 or newer.
    ^
In file included from input_line_1:1:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\new:6:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\exception:8:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\type_traits:6:
D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\xstddef:338:2: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
        auto _Unfancy(_Ptrty _Ptr)
        ^
[W 18:39:22.399 NotebookApp] Timeout waiting for kernel_info reply from 7bd63024-bbf1-410e-8a74-5898c6f1d8f0
[I 18:39:24.532 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel 7bd63024-bbf1-410e-8a74-5898c6f1d8f0 restarted
2
2
ERROR in cling::CIFactory::createCI():
  resource directory C:/bld/xeus-cling_1536182173380/_b_env/Library\lib\clang\5.0.0 not found!
In file included from input_line_1:1:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\new:6:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\exception:7:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\yvals.h:7:
D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\yvals_core.h:294:5: error: STL1000: Unexpected compiler version, expected Clang 6 or newer.
   #error STL1000: Unexpected compiler version, expected Clang 6 or newer.
    ^
In file included from input_line_1:1:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\new:6:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\exception:8:
In file included from D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\type_traits:6:
D:\VisualStudio2017_enterprise\Visual Studio IDE\VC\Tools\MSVC\14.15.26726\include\xstddef:338:2: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
        auto _Unfancy(_Ptrty _Ptr)
        ^
[W 18:39:27.601 NotebookApp] KernelRestarter: restart failed
[W 18:39:27.602 NotebookApp] Kernel 7bd63024-bbf1-410e-8a74-5898c6f1d8f0 died, removing from map.
kernel 7bd63024-bbf1-410e-8a74-5898c6f1d8f0 restarted failed!
[W 18:39:27.667 NotebookApp] 410 DELETE /api/sessions/199453f5-e112-4b08-8231-c28df63c27b8 (::1): Kernel deleted before session
[W 18:39:27.668 NotebookApp] Kernel deleted before session
[W 18:39:27.680 NotebookApp] 410 DELETE /api/sessions/199453f5-e112-4b08-8231-c28df63c27b8 (::1) 17.00ms referer=http://localhost:8888/notebooks/Desktop/Untitled2.ipynb?kernel_name=xeus-cling-cpp11
[W 18:40:41.101 NotebookApp] Forbidden
[W 18:40:41.103 NotebookApp] 403 GET /api/sessions?_=1536964744895 (::1) 2.00ms referer=http://localhost:8888/tree/Desktop
[W 18:40:41.125 NotebookApp] Forbidden
[W 18:40:41.126 NotebookApp] 403 GET /api/terminals?_=1536964744896 (::1) 2.00ms referer=http://localhost:8888/tree/Desktop

Any help will be really appreciated!

**Comment by takluyver** [comment]
You'll need to report that to xeus-cling: https://github.com/QuantStack/xeus-cling
