### ISSUE TITLE
Ordering directories numerically

### ISSUE THREAD

**Issue by kdbeall** [jupyter/notebook#3921]
I'm using Jupyter for having code examples with a textbook and am making a directory per chapter. It would be nice to have the chapter directories ordered numerically e.g. chapter-1, chapter-2, etc.
Currently, it goes chapter-1, chapter-10, etc.

![screen shot 2018-09-14 at 11 24 11 pm](https://user-images.githubusercontent.com/10102694/45581936-531e9e00-b875-11e8-9fc7-8a6421910cdb.png)

Is there a simple way of ordering directories numerically?

**Comment by jasongrout** [comment]
The standard way to deal with this in the file system is to title them "chapter-01", etc.
