### ISSUE TITLE
include nbjs.json / .mo in source ? 

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#3924]
As far as I can tell, with current release process there is no translation included.

We can also make sure they are build into wheels ? 
Otherwise there is no frontend translation in released wheel which can be weirdly hard to setup.

**Comment by Carreau** [comment]
@takluyver you excluded them initially.

**Comment by minrk** [comment]
Aren't only the LC_MESSAGES required for frontend translation? They are included in package_data and I get UI translations when I run

    LANG=fr_FR jupyter notebook

after installing from a wheel

**Comment by Carreau** [comment]
I did try and it did not work for me locally, If I read correctly there is also some translations in the json files and some translations in the .po files to to get _everything_ translated you need both, and you need both LANG and the browser set to the same value

See https://github.com/jupyter/notebook/blob/master/notebook/i18n/README.md#known-issues-and-future-evolutions

**Comment by minrk** [comment]
I was able to confirm that with what's already packaged, frontend translations *do* work from a wheel (no files outside locale/xx_YY are used for translations at runtime).

This is the result from:

```
python setup.py bdist_wheel
pip install dist/*.whl
cd
LANG=fr_FR jupyter notebook
```

With language settings (chrome):

<img width="726" alt="screen shot 2018-09-19 at 14 53 03" src="https://user-images.githubusercontent.com/151929/45754384-d7797400-bc1b-11e8-8c02-4d4cd01e2531.png">

The result, where you can see frontend translations are using zh_CN and backend translations are using fr_FR:

<img width="473" alt="screen shot 2018-09-19 at 14 53 14" src="https://user-images.githubusercontent.com/151929/45754355-c3ce0d80-bc1b-11e8-9e23-e1f12fa1a775.png">


So I think with #3931, which fixes the exclusions from sdists, we can release 5.7. Do you agree?

**Comment by minrk** [comment]
Great! Notebook 5.7 is out
