### ISSUE TITLE
Prompt for folder name when creating a new folder

### ISSUE THREAD

**Issue by gustavoefeiche** [jupyter/notebook#3928]
On the server homepage, clicking **New -> Folder** creates a new folder called 'Untitled Folder' in the current path.

![jupyter](https://user-images.githubusercontent.com/11490046/45659194-a0934900-bac9-11e8-8119-06565ad16459.png)

It would be useful to have a prompt ask for folder name before creating. I would like to work on it if possible.

**Comment by gustavoefeiche** [comment]
Sorry guys, I forgot to link the pull-request! Here is the link: https://github.com/jupyter/notebook/pull/3945

**Comment by gustavoefeiche** [comment]
@minrk I submitted a [pull request](https://github.com/jupyter/notebook/pull/4030/) for this feature but it is a WIP. I also need to know if this feature is desired or not :D. If it is, could anyone help me completing some tasks detailed in the pull request message?

**Comment by avi-jain** [comment]
Sorry I know the issue's old but this is unnecessary extra clicks, no?

**Comment by kevin-bates** [comment]
Thanks for the efforts and thoughts on this.  Per https://github.com/jupyter/notebook/pull/6107#issuecomment-888328745, I'm closing this issue as it's not something we're going to take on at this time.
