### ISSUE TITLE
Inconsistent underscore behavior in Jupyter Notebook

### ISSUE THREAD

**Issue by reckoner** [jupyter/notebook#3943]
With a fresh kernel, the following sequence runs as expected,

![image](https://user-images.githubusercontent.com/173637/45765927-307ce400-bbeb-11e8-9f2f-e5176ce97f81.png)

Note that when the same notebook is run using the same kernel from the top, we get the following:

![image](https://user-images.githubusercontent.com/173637/45766050-7df95100-bbeb-11e8-8979-8e330c74cf10.png)

I realize that there is some difference between the IPython underscore behavior and the regular Python REPL  behavior but this should be consistent one way or the other.

Here is version info:
`notebook                  5.6.0                    py36_1`

Thanks in advance!

**Comment by minrk** [comment]
closing in favor of ipython/ipython#11325
