### ISSUE TITLE
Running Jupyter notebook without outputs

### ISSUE THREAD

**Issue by EscVM** [jupyter/notebook#3944]
This is a strange behavior I encounter every time I do the following actions ( I'm using an aws instance, but I think it's the same also without it):
1. I run a jupyter notebook over tmux
2. I launch a script in a cell and it works just fine
3. I close the browser window of the notebook
4. I close the console
When I re-open the notebook I can see that it is still running due to the hourglass on the top, but the output of the cell doesn't update anymore. There's not even the asterisk anymore.

Thank for your help.

**Comment by yshkk** [comment]
I've met the same question  😂. Refreshing the browser can also cause the output cell won't update. https://github.com/jupyter/notebook/issues/3991

**Comment by jasongrout** [comment]
Thanks for bringing this up. This issue is tracked over at #1647 - you're welcome to join the conversation over there!
