### ISSUE TITLE
List of running notebooks should indicate the kernel type

### ISSUE THREAD

**Issue by mjbright** [jupyter/notebook#395]
On the page which lists running Terminals and Notebooks, each running notebook is displayed with it's relative path.

It would be nice if the running kernel was indicated - a time saver if any "Untitled" notebooks are hanging around, for example.

**Comment by hwine** [comment]
works for me in 4.1.0 - time to close?

**Comment by jtpio** [comment]
Closing as fixed.

For reference this is what it looks like in Notebook 7:

![image](https://github.com/jupyter/notebook/assets/591645/c86405a5-3d7c-4629-a765-83d68373280b)
