### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_EditTags_Keyboard:Keyboard focus moves out to browser window,as we navigate through the pop-up.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3950]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
4.Navigate to any file present under Files tab-->Hit enter-->View Menu-->Cell Toolbar-->Tags. Click on Edit Tags button appeared on page.
5.Use keyboard to navigate to page with the help of any of the keyboard keys.
**Actual:**
When we navigate in the page with help of "Tab" key then the keyboard focus leaves the pop-up and moves to the window pane.  

**Similar issue has been observed with** 
1.DeleteConfirmationPopUp->Navigate to run button & hit enter --> select any file --> navigate to delete button & hit enter.
2.DuplicateConfirmationPopUp->Navigate to run button & hit enter --> select any file --> navigate to Duplicate button & hit enter.
3.EditAttachments-->Navigate to any file present under Files tab-->Hit enter-->View Menu-->Cell Toolbar-->Attachments. Click on Edit Attachments button appeared on page.
4.EditMetada-->Navigate to any file present under Files tab-->Hit enter-->View Menu-->Cell Toolbar-->Edit Metadata. Click on Edit Metadata button appeared on page.
5.MoveConfirmationPopUp->Navigate to run button & hit enter --> select any file --> navigate to delete button & hit enter.

**Expected:**
When the pop-up is invoked ,the keyboard focus should remain intact within the pop-up .
 
**UserImpact:**
User will not able to navigate to the page and do unnecessary traversing if focus does not remain intact within the pop-up.
 **Attachment:**
[A11y_AzureNotebooks_Jupyter_EditTags_Keyboard2.pptx](https://github.com/jupyter/notebook/files/2399687/A11y_AzureNotebooks_Jupyter_EditTags_Keyboard2.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
