### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_EditTags_ScreenReader:Narrator is reading the "Times " for the Cross button.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3951]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
4.Navigate to any file present under Files tab-->Hit enter-->View Menu-->Cell Toolbar-->Tags. Click on Edit Tags button appeared on page.
5.Use keyboard to navigate to page with the help og any of the keyboard keys.
6.Start the narrator.
**Actual:**
Narrator is reading the "Times " for the Cross button.
With NVDA it reads "Heading level 4" with Shift +TAB key
**Similar issue has been observed for the page**
1.DeleteConfirmationPopUp:
Navigate to run button & hit enter --> select any file --> navigate to delete button & hit enter.
2.EditAttachments:
Navigate to any file present under Files tab-->Hit enter-->View Menu-->Cell Toolbar-->Attachments. Click on Edit Attachments button appeared on page.
3. MoveConfirmationPopUp:
Navigate to run button & hit enter --> select any file --> navigate to delete button & hit enter

**Expected:**
Narrator should read the correct name for the control such as cancel or dismiss pop-up button. 
**UserImpact:**
User will not get wrong information regarding the cross button. 
**Attachment**

[A11y_AzureNotebooks_Jupyter_EditTags_ScreenReader.pptx](https://github.com/jupyter/notebook/files/2399704/A11y_AzureNotebooks_Jupyter_EditTags_ScreenReader.pptx)

**Comment by takluyver** [comment]
Closed by #4677
