### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader:Narrator is reading the Read-only for the "My Libraries" link.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3952]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
5.Navigate to the "My Libraries" link.
6.Start the Narrator.
**Actual:**
Narrator is reading the Read-only for the "My Libraries" link.
Similar issue is for the "Sample notebooks1","Files","Running","NbExtensions".

**Note:**
**Same issue is observed for below pages:**
1. Menubar: Navigate to any of the file names present in the samples-->>clickin the file name
* Links present under all Menu(File,Edit,View,Insert...etc) Narrator reading as Read only for all links.

**Expected:**
Narrator should read the corerct state of the link like clickable.
**UserImpact:**
User will not get wrong information regarding the state of the link. 
**Attachment:**
[A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader_Compressed.pptx](https://github.com/jupyter/notebook/files/2399865/A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader_Compressed.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
