### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_FilesTab_Keyboard:Keyboard focus is not logical after the "Jupyter' logo.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3953]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
5.Navigate to the "My Libraries" link.
6.Start the Narrator.
**Actual:**
Narrator is directly moving to the"Sample Notebooks1" intead of going to the "My Libraries".

**Note:
Same issue is observed in below pages:**
1. RunningTab: Navigate to run button & hit enter --> Navigate to running tab & hit enter.

**Expected:**
Narrator should move to "My Libraries" then "Sample Notebooks1" in proper logical order.
**UserImpact:**
User will face difficulty while traversing through the page and accessing the buttons. 
**Attachment:**
[A11y_AzureNotebooks_Jupyter_FilesTab_Keyboard.pptx](https://github.com/jupyter/notebook/files/2399877/A11y_AzureNotebooks_Jupyter_FilesTab_Keyboard.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
