### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_FilesTab_Keyboard:Keyboard focus goes to non- Interactive content present on the page such as "File size".

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3959]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
5.Navigate to the "Azure Notebooks......"using the "Tab" key.
 
Actual:
Keyboard focus goes to non- Interactive content present on the page such as "File size".

**Note:
Same issue is observed in below pages:**
1. RunningTab: Navigate to run button & hit enter --> Navigate to running tab & hit enter.(Refer Attachment)
2. Menu Bar: Navigate to any of the file names present in the samples-->clickin the file name
 * Some of the Menu items which were present under "Edit" are non-interactive but keyboard focus goes on those non- interactive controls.

**Expected:**
Keyboard focus goes to non- Interactive content present on the page such as "File size".
 **UserImpact:**
User will face difficulty while traversing through the page. 
**Attachment:**
[A11y_AzureNotebooks_Jupyter_FilesTab_Keyboard_New.pptx](https://github.com/jupyter/notebook/files/2399952/A11y_AzureNotebooks_Jupyter_FilesTab_Keyboard_New.pptx)
[A11y_AzureNotebooks_Jupyter_FilesTab_Keyboard_RunningTab.pptx](https://github.com/jupyter/notebook/files/2399955/A11y_AzureNotebooks_Jupyter_FilesTab_Keyboard_RunningTab.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
