### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader:Narrator is not reading any alert message regarding the  action performed on the refresh button.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3962]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
5.Navigate to the "Select All/None" dropdown.
6.Start the Narrator.
**Actual:**
Narrator is not reading any information about the  action performed on the refresh button.

**Note:
Same issue is observed in below pages:**
1. RunningTab: Navigate to run button & hit enter --> Navigate to running tab & hit enter.

**Expected:**
Narrator should read any information about the  action performed on the refresh button.
**UserImpact:**
User will not get any information regarding the refreshing of theb page. 
**Attachment:**
[A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader6.pptx](https://github.com/jupyter/notebook/files/2399996/A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader6.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
