### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader:Narrator is not reading the Order of list items present in the "Select......" Dropdown.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3963]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
5.Navigate to the "Select All/None" dropdown.
6.Start the Narrator.
**Actual:**
Narrator is not reading the Order of list items present in the "Select......" Dropdown.

**Same issue is observed for NVDA also.
Similar Issue has been observed in:**
"New" dropdown.

**Note:
Same issue is observed in below pages:**
1. Menu Bar: Navigate to any of the file names present in the samples-->>clickin the file name.

**Expected:**
Narrator should read the Order of list items present in the "Select......" Dropdown.
**UserImpact:**
User will not get wrong information regarding the state of the control.. 
**Attachment:**
[A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader7.pptx](https://github.com/jupyter/notebook/files/2400004/A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader7.pptx)

**Comment by takluyver** [comment]
Closed by #4695.
