### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader:Narrator is reading "Files","NbExtensions","Running" tab as link.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3965]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
5.Navigate to the "Files" tab.
6.Start the Narrator.
**Actual:
Issue1:**
Narrator is reading "Files","NbExtensions","Running" tab as link.
**Issue2:**
Narrator is not reading the dynamics changes in the selelection of the"Files","NbExtensions","Running" tabs.
**Expected:
Issue1:**
Narrator should read "Files","NbExtensions","Running" tab as TabItem..
**Issue2:**
As soon as we select the the"Files","NbExtensions","Running" tab , Narrator should read it selected.
 
 **UserImpact:**
User will not get any information regarding the tab items and which tab item is selected. 
 **Attachment:**        
[A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader9.pptx](https://github.com/jupyter/notebook/files/2400036/A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader9.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
