### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader:Narrator is reading the button for the"Select All/None...." checkbox.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3966]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
5.Navigate to the "My Libraries" link.
6.Start the Narrator.
**Actual:**
Narrator is reading the button for the"Select All/None...." checkbox.
**Expected:**
Narrator should read checkbox for the"Select All/None...." checkbox.
**UserImpact:**
User will not get wrong information regarding the  control type. 
**Attachment:**
[A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader11.pptx](https://github.com/jupyter/notebook/files/2400051/A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader11.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
