### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader:Narrator is only reading the tooltip for the "Duplicate","Edit","View","Refresh" buttons .

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3968]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails: 
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
5.Navigate to the "Files" tab.
6.Start the Narrator.
**Actual:**
Narrator is only reading the tooltip for the "Duplicate","Edit","View","Refresh" buttons in .It is not reading the control name.
**Expected:**
Narrator should read  the control name and then the tooltip for  "Duplicate","Edit","View" ,"Refresh"buttons. 
**UserImpact:**
User will not get confused between the control name and the tooltip. 
**Attachment:**
[A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader14.pptx](https://github.com/jupyter/notebook/files/2400088/A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader14.pptx)

**Comment by takluyver** [comment]
Closed by #4690
