### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader:Narrator is reading about the unnecessary "Browse" button and text "Enter a file to upload" which is visually not present on the Screen

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3969]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
5.Navigate to the "Files" tab.
6.Start the Narrator.
**Actual:**
Narrator is reading about the unnecessary "Browse" button and text "Enter a file to upload" (Read-only)which is visually not present on the screen.
**Expected:**
Narrtor should read about the content that is visually present on the screen.
**UserImpact:**
User will get confused  about the controls as the controls are not visually present on the screen and user will not be able to perform action on them.  . 
**Attachment:**
[A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader15.pptx](https://github.com/jupyter/notebook/files/2400105/A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader15.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
