### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader:Narrator is not reading descriptive tooltip for "Select......" dropdown.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3971]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
5.Navigate to the "Files" tab.
6.Start the Narrator.
**Actual:**
Narrator is not reading descriptive tooltip for "Select......" dropdown.
**Expected:**
Narrator should read descriptive tooltip for the toggle dropdown which gives some onformation regading the control.
**UserImpact:**
User will get confused  about the purpose of the control as it is not clear from the tooltip. 
**Attachmment**
[A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader16.pptx](https://github.com/jupyter/notebook/files/2400110/A11y_AzureNotebooks_Jupyter_FilesTab_ScreenReader16.pptx)

**Comment by takluyver** [comment]
Closed by #4690
