### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_CreationAndDeployment_Screenreader: Narrator is not reading "Error Suggestion Message" in code cell block.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3974]
**Environment Details:**
Application Name: AzureNotebooks_Jupyter
Login URL: notebooks.azure.com
Browser Details:
Edge: Microsoft Edge 42.17134.1.0
Chrome: Version 68.0.3440.106 
Operating System:Windows10

**Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Navigate to run button & hit enter --> Navigate to Creation and Deployment of an Azure ML Web Service & hit enter.
4. Navigate to Code Cell block and edit code to generate Error.
5.Verify whether the Narrator is reading Error Suggestion message.

**Actual:**
Narrator is not reading "Error Suggestion Message" in code cell block.

**Note:** 
Same issue is observed in Chrome with **NVDA**

**Expected:**
Narrator should read "Error Suggestion Message" in code cell block whenever Error is observed.

**User Impact:**
Screenreader Users face difficulties to understand the Error Suggestion Message generated after Debugging code.

**Attachment:**
(https://github.com/jupyter/notebook/files/2400175/A11y_AzureNotebooks_Jupyter_CreationAndDeployment_Screenreader.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
