### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_EnterExitRiseSlideshow_Screenreader: NVDA is not reading EnterExitRiseSlideshow Page "Reveal Shortcuts Help" Popup.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3975]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Chrome:Version 68.0.3440.106 
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
4.Navigate to the EnterExitRiseSlideshow using the "Tab" key.
 
**Actual:**
NVDA is not reading "?","Close" and the "Reveal Shortcuts Help" pop-up and its content.

**Expected:**
NVDA should read "?","Close" and the "Reveal Shortcuts Help" pop-up and its content.

**UserImpact:**
User will face difficulty while traversing through the page. 

**Attachment:**
(https://github.com/jupyter/notebook/files/2400188/A11y_AzureNotebooks_Jupyter_EnterExitRiseSlideshow_Screenreader.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
