### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_NBExtensionsTab_Keyboard: Checkbox is not able to checked using keyboard.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3980]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
4.Navigate to NBExtensions Tab and select filter.
5.Use keyboard to navigate NBExtensions configuration checkbox.

**Actual:**
NBExtensions configuration checkbox is not able to checked using keyboard(Enter or SpaceBar key).

**Expected:**
NBExtensions configuration checkbox can be checked using keyboard keys.
 
**UserImpact:**
User is not able to check the checkbox using keyboard.

**Attachment:**
(https://github.com/jupyter/notebook/files/2400303/A11y_AzureNotebooks_Jupyter_NBExtensionsTab_Keyboard.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
