### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_MenuBar_Keyboard: Keyboard focus is not Shifting to "Not Trusted" button.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#3983]
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Operating System:Windows10

**ReproSteps:**
1. Login with the appropriate credentials to azure notebook account.    
2. Navigate to any of the file names present in the samples-->>clickin the file name-->Welcome page opens with menubar.
3. Start Navigating through Menubar using keyboard.
4. Verify Keyboard focus is not Shifting to "Not Trusted" button which is present on right of menubar.

**Actual:**
Keyboard focus is not Shifting to "Not Trusted" button.

**Note:**
1. Same issue is observed in "**Chrome+NVDA**" Configuration.
2. And also **Narrator** and **NVDA** focus is also not shifting to "Not Trusted" button.

**Expected:**
Keyboard focus should shifts to all actionable controls or buttons.
In this MenuBar Keyboard focus should shifts to "Not Trusted" button as it is actionable.

**UserImpact:**
Keyboard Only Users face difficulty if Keyboard focus is not Shifting to actionable controls.

**Attachment:**
(https://github.com/jupyter/notebook/files/2400344/A11y_AzureNotebooks_Jupyter_MenuBar_Keyboard.pptx)

**Comment by takluyver** [comment]
FIxed by #4745.
