### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_EditAttachments_Keyboard: Keyboard focus is lost when pressing 'ESC' key on the active Pop-up.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#4006]
**Environment Details:**
Application Name: AzureNotebooks_Jupyter
Login URL: notebooks.azure.com
Browser Details:
Edge: Microsoft Edge 42.17134.1.0
Chrome: Version 68.0.3440.106 
Operating System:Windows10

**Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    

2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library

3.Click on Run or right click and select Run to run the notebook.

4.Navigate to any file present under Files tab-->Hit enter-->View Menu-->Cell Toolbar-->Attachments. Click on Edit Attachments button appeared on page.
5. Press 'ESC' key and verify the keyboard focus is lost or not.

**Actual**
Keyboard focus is lost when user presses 'ESC' key on the active Pop-up.

**Expected**
Keyboard focus should stay on the 'Edit attachment' Button when the Popup closes while pressing 'ESC' key.

**User Impact**
Keyboard user would get confuse and would have to navigate again when the keyboard focus is lost on the active pop-up.
**Attachments:**

[A11y_AzureNotebooks_Jupyter_EditAttachments_Keyboardnew.pptx](https://github.com/jupyter/notebook/files/2401180/A11y_AzureNotebooks_Jupyter_EditAttachments_Keyboardnew.pptx)

**Comment by takluyver** [comment]
Closed by #4711.
