### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_EditMetada_Keyboard: Keyboard focus does not go to 'Close' button of the Popup.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#4012]
**Environment Details:**
Application Name: AzureNotebooks_Jupyter
Login URL: notebooks.azure.com
Browser Details:
Edge: Microsoft Edge 42.17134.1.0
Chrome: Version 68.0.3440.106 
Operating System:Windows10

**Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library
3.Click on Run or right click and select Run to run the notebook.
4.Navigate to any file present under Files tab-->Hit enter-->View Menu-->Cell Toolbar-->Edit Metadata. Click on Edit Metadata button appeared on page.
5. Try to navigate to 'Close' button of the pop-up using keyboard.

**Actual:**
Keyboard focus does not go to 'Close' button of the Popup.

This issue exist for '**Chrome + NVDA**' configuration also.

**Note:**
Same issue is observed in below pages:
1. MoveConfirmationPopup: Navigate to run button & hit enter --> select any file --> navigate to Move button & hit enter.

**Expected:**
Keyboard focus should go to 'Close' button of the Popup.

**User Impact:**
Keyboard only user will not be access the 'Close' button present on the Popup.

**Attachment:**
(https://github.com/jupyter/notebook/files/2401275/A11y_AzureNotebooks_Jupyter_EditMetada_Keyboard.pptx)

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
