### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_EditAttachments_ScreenReader:Narrator reads 'Close' Button as 'Times' Button.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#4015]
**Environment Details:**
Application Name: AzureNotebooks_Jupyter
Login URL: notebooks.azure.com
Browser Details:
Edge: Microsoft Edge 42.17134.1.0
Chrome: Version 68.0.3440.106 
Operating System:Windows10

**Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    

2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library

3.Click on Run or right click and select Run to run the notebook.

4.Navigate to any file present under Files tab-->Hit enter-->View Menu-->Cell Toolbar-->Attachments. Click on Edit Attachments button appeared on page.
5.Start Narrator and verify how Narrator reads the 'Close' Button present on the PopUp.

**Actual**
Narrator reads 'Close' Button as 'Times' Button.
**NVDA reads close button as "Section".**

**Note:
Same issue observed on below pages:**
1)RenameConfirmationPopUp: Navigate to run button & hit enter --> select any file --> navigate to Rename button & hit enter.

**Expected**
Narrator should read 'Close' Button as 'Close' Button.

**User Impact**
https://microsoft.sharepoint.com/teams/msenable/mas/pages/mas-details.aspx?masid=1.3.1
**Attachment:**
[A11y_AzureNotebooks_Jupyter_EditMetada_ScreenReader21.pptx](https://github.com/jupyter/notebook/files/2401309/A11y_AzureNotebooks_Jupyter_EditMetada_ScreenReader21.pptx)

**Comment by joshuazeltser** [comment]
We have solved this in #4677

**Comment by takluyver** [comment]
Closed by #4677.
