### ISSUE TITLE
Some session URLs are urlencoded twice

### ISSUE THREAD

**Issue by seanson** [jupyter/notebook#402]
As part of my testing of JupyterHub in our corporate network, users are logged in and a URL is populated with the full username as authenticated by PAM. In setups like ours, usernames are prefixed with a domain, such as DOMAIN\username, which then is built into the Notebook URL. Almost all of the calls only call URL `utils.url_join_encode` on the URL once, resulting in a valid url like `/user/DOMAIN%5Cusername/api/kernels/b6c1f2f0-c864-4933-b360-5bb61e922efc/channels`, however there are two instances that call it twice, resulting in double-escaped URLs like  `/user/DOMAIN%255Cusername/api/kernels/b6c1f2f0-c864-4933-b360-5bb61e922efc/channels`

**Comment by jdfreder** [comment]
@minrk assigned you since it looked like you are helping with the PR already

**Comment by minrk** [comment]
closed by #403
