### ISSUE TITLE
Import error when running the notebook from cmd

### ISSUE THREAD

**Issue by Hyaxia** [jupyter/notebook#4025]
Hi, I have tried to run the book locally with pycharm.
The problem is when I try to execute the __ main __.py file in the notebook folder, 
every time there is an import that starts with "from notebook..." it fails saying ImportError: cannot import name notebookapp.

If i run from some other file:
from __future__ import absolute_import

if __name__ == '__main__':
    from notebook import notebookapp as app
    app.launch_new_instance()

it will work, but not from the actual source directory

Does anyone know what am I doing wrong?

Thanks!

**Comment by minrk** [comment]
That sounds like the notebook application isn't installed. Have you run `pip install notebook` or (`pip install -e .` if you want a dev install)?

**Comment by Hyaxia** [comment]
But the thing is I forked the project and its using a venv that has all the packages specified in the setup.py file.
Also, when i use python -m notebook it does work but without the js files

**Comment by qyj2006** [comment]
> @minrk I have solved all but one things..
> why when i run `python notebook` it dosent work, but when i run `python -m notebook` it works?
> It fails saying ImportError: cannot import name notebookapp.
> 
> Also, the dev version as i saw in the documentation is python -m pip install notebook --pre --upgrade
> isnt it?



> That sounds like the notebook application isn't installed. Have you run `pip install notebook` or (`pip install -e .` if you want a dev install)?


pip install -e 
is the  command used for creating the develop environment？
