### ISSUE TITLE
Problem with menu

### ISSUE THREAD

**Issue by diasgabriela** [jupyter/notebook#4033]
Hi,
My menu does not close; it keeps all the time drop-down (as can be seen in the image). I've uninstalled and reinstalled jupyter notebook, but nothing changed.
I use windows 10 and Firefox. 

![1d892280-f1c0-472b-b369-63f476b1c71a](https://user-images.githubusercontent.com/27743808/46043169-adc5be80-c0ed-11e8-9467-041eea0fb7a7.png)

**Comment by amrs-tech** [comment]
Can you please specify more details about your jupyter notebook, whether it is run with conda or separately ?

**Comment by diasgabriela** [comment]
It runs with Conda, but I've managed to solve it!
I've installed Jupyter-themes, tried some custom themes and then turned it back to the default theme, and fixed it.

Thanks anyway!

**Comment by jasongrout** [comment]
Great! I'm glad it's working!

**Comment by jasongrout** [comment]
And thanks @amrs-tech for volunteering to look at it!
