### ISSUE TITLE
Cannot find static file ''

### ISSUE THREAD

**Issue by Hyaxia** [jupyter/notebook#4042]
Ive got lately this issue when trying to start the notebook from a folder that i have pulled a forked version.
When doing that the notebook starts but without the static files and the notebook is pretty much non functional.
When running it regularly through the venv that I have created and that I have installed the package to it runs ok, but i want to work on a dev version, not on the regular one....

Has anyone seen this issue before and knows how to fix it?
Thanks

**Comment by waydegg** [comment]
What was your fix?

**Comment by ahhhhah** [comment]
I meet the same problem, could you please tell me how did you fix that?

**Comment by Hyaxia** [comment]
@waydegg @ahhhhah well I opened this issue so long ago that I don't really remember how to reproduce it....
But a fix to the problem might be just to use the `-m` flag when running the project in the following way: `python.exe -m notebook`.

The `notebook` is essentially the path to the folder that holds the notebook files.
For example, if my project is in `D:\projects\notebook-proj`, then i will change directory to `D:\projects\notebook-proj` and then run `python.exe -m notebook`.
