### ISSUE TITLE
Notebook `5.7.0` seems to miss cell execution when executing blocks of cells

### ISSUE THREAD

**Issue by esvhd** [jupyter/notebook#4052]
Hi,

I upgrade `notebook` from `5.6.0` to `5.7.0` and `ipython` to `7.0.1` over the weekend. 

When I tried to execute a block of cells, either by highlighting then Ctrl+Enter or selecting Execute All Below in the menu bar, some cells are being missed in the execution, resulting in following cells that depend on them to fail. 

To be precise, what I have seen is, in a block, cell `i` gets executed, cell `i+1` missed, and then cell `i+2` which uses cell `i+1` result fails. 

Has anyone seen similar results? I am seeing this in different notebooks on different Windows machines that have the same package versions.

System info below. Thanks.

```
pandas      0.23.4
numpy       1.15.2
tabulate    0.8.2
seaborn     0.9.0
2018-10-01 

CPython 3.6.4
IPython 7.0.1

notebook 5.7.0
ipykernel 5.0.0
ipywidgets 7.4.2

compiler   : MSC v.1900 64 bit (AMD64)
system     : Windows
release    : 7
machine    : AMD64
processor  : Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
CPU cores  : 4
interpreter: 64bit
```

**Comment by stonebig** [comment]
yes: https://github.com/ipython/ipython/issues/11348

**Comment by esvhd** [comment]
@stonebig that's exactly what I've seen here.

**Comment by r0f1** [comment]
i am having the same issue. is there a workround? can the new asyncio stuff you are referring to be disabled / modified?

**Comment by esvhd** [comment]
I ended up downgrading my ipykernel...

**Comment by r0f1** [comment]
Thank you! I also downgraded and this seems to be working. I downgraded to version `4.8.0`.

**Comment by stonebig** [comment]
donwgrading to pykernel-4.9.0 looks ok for me, no need to go further back in time.

**Comment by ciupicri** [comment]
I'm having the same problem. My setup is:
 - Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
 - ipykernel 5.0.0 py36h39e3cac_0
 - notebook 5.7.0 py36_0

**Comment by dhirschfeld** [comment]
This seems to be a fairly serious regression which would prevent me from upgrading.

**Comment by minrk** [comment]
I believe this is purely an issue in ipykernel 5, not IPython or notebook.

For everyone facing this issue, pinning `ipykernel<5` should avoid it while we work it out.

I haven't been able to reproduce the problem, but I notice a possibly relevant coincidence that every reported environment here is on Windows. Is anyone *not* on Windows seeing this issue?

Does anyone have a simple notebook that can reproduce the issue and a `conda env export` or `pip list` to go with it? I've been trying to reproduce this, but can't provoke the problem. Is matplotlib or other eventloop-integrating extension in use?

**Comment by dhirschfeld** [comment]
NB: I haven't seen it, but that's because I haven't upgraded *because* of these reports. I'm planning on upgrading towards the end of the week irrespective so can report back if it isn't already resolved.

For ref the ipykernel issue is https://github.com/ipython/ipykernel/issues/356 (also linked above)

**Comment by minrk** [comment]
I was able to reproduce it on Windows and it's related to the fact that timers are low-resolution on Windows and we didn't handle the case where there was a possible tie in the timestamp of two messages, which is ~impossible on unix, but easy on Windows.
 
https://github.com/ipython/ipykernel/pull/362 should fix the problem.

**Comment by esvhd** [comment]
Hi, I’m seeing this in Ubuntu 18.04. Have not tested Windows. Thx

**Comment by minrk** [comment]
@esvhd thanks! Can you share more info about the server (what CPU, is it a VM, etc.) and a notebook that produces the issue? Would you also be able to test if ipython/ipykernel#362 fixes the issue? I'm guessing it does, since it was pretty easy to reproduce once I set up a Windows environment.

**Comment by esvhd** [comment]
Hi, will try to share that when I get back tonight. Thanks for looking into this.

**Comment by Catime** [comment]
Hi, Downgrading ipykernel to 4.10.0 worked for me.

**Comment by esvhd** [comment]
@minrk I'm glad to report that actually my memory was wrong - I only saw this issue on Windows. I **failed** to reproduce this issue on Linux. Feeling old right now.... I saw this on Windows both at work and at home, but not my home Linux.

Here's my setup below anyway, python, os and cpu. Ubuntun 18.04 LTS, running standalone, not VM. At least now we know that worked in Linux, and the same hardware w/ Windows (dual boot, similar python versions) did not work.

Unfortunately this means that I have not tested [ipython/ipykernel#362](https://github.com/ipython/ipykernel/pull/362) on Linux.

Thanks.

```
%watermark -dvm -iv -p xarray,matplotlib,ipykernel,notebook

json        2.0.9
autopep8    1.4
numpy       1.15.2
pandas      0.23.4
seaborn     0.9.0
2018-10-08 

CPython 3.6.6
IPython 6.5.0

xarray 0.10.8
matplotlib 3.0.0
ipykernel 5.0.0
notebook 5.7.0
numpy 1.15.2
pandas 0.23.4

compiler   : GCC 7.2.0
system     : Linux
release    : 4.15.0-36-generic
machine    : x86_64
processor  : x86_64
CPU cores  : 20
interpreter: 64bit


$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ head /proc/cpuinfo

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping        : 1
microcode       : 0xb00002e
cpu MHz         : 1658.820
cache size      : 25600 KB
physical id     : 0
siblings        : 20
core id         : 0
cpu cores       : 10
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4397.63
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

```

**Comment by esvhd** [comment]
@minrk After playing for a while in Linux, i encountered a slightly different situation: 

Cell `i` which should produce variable `a` executes but **fails** due to code error, which means `a` isn't assigned / is invalid.

Cell `i+1` which uses `a` does not execute. 

But cell `i+2` which uses `a` is executed but fails because variable `a` cannot be found due to cell `i`'s failure.

Normally I'd expect execution to stop at `i+1` because `i` failed, but here only `i+2` got executed. If both `i+1` and `i+2` were executed and failed I'd be less surprised.

I'm trying to create a new notebook that reproduces this but not having luck yet. There might be some unknown dependency that I have not discovered, or some randomness. 

I'm going to try a bit more to see if I can get a reproducible notebook. System info same as above but with `ipython 7.0.1`.

**Comment by minrk** [comment]
@esvhd thanks! I think that's a slightly different issue, but the abort-on-error logic also had to be rewritten with the async updates, so it makes sense that there might have been a change there, too. A notebook to reproduce would be super helpful, even if it's only intermittent. It's hard to reproduce an error based on a description alone. For instance [this notebook](https://nbviewer.jupyter.org/gist/minrk/639102c3590a083c3a2bb11142b1927f) does what I think you are describing, but never seems to trigger the behavior you describe.

A few points:

- statement in the middle shouldn't be relevant. The only thing it cares or even knows about is whether an error is raised or not. But when a cell raises an error, all of the lines up to the error are still executed.
- references to the variables should also not be relevant. The content is never considered when it comes to decisions like whether to execute a cell

The most relevant aspect of the stop-on-error behavior is that it's timing-based. When execution fails, the kernel aborts all messages that are waiting to be executed, and then waiting [50 milliseconds](https://github.com/ipython/ipykernel/blob/fe52dbd726cb405eb3a1e74e6a7fdb32372150ed/ipykernel/kernelbase.py#L780) for more to arrive. If an execution that's part of a "run all" arrives significantly delayed (that is, at least 50 milliseconds later than the previous request).

I've updated #362 to increase this timeout to 100 milliseconds by default and make it configurable, which may mitigate the issue for you.

**Comment by minrk** [comment]
@esvhd I've closed this since the original issue is resolved, but feel free to open a new issue on ipython/ipykernel if you can reproduce the run-all issue with ipykernel 5.1

**Comment by esvhd** [comment]
@minrk Thanks v much, looks like `ipykernel 5.1` is out, will give it a try asap.
