### ISSUE TITLE
Every other cell execution very slow

### ISSUE THREAD

**Issue by mmcguffi** [jupyter/notebook#4059]
A problem I frequently run into is every other cell execution becoming quite slow (many orders of magnitude slower). On a "slow execution", if I manually interrupt the kernal and then execute it will often run at a normal speed. If there is a syntax error, it often wont catch it until many seconds after execution as well. This issue seems to possibly co-occur with tab autocomplete not working either.

When I use jupyter time magics (%%time), it does not accurately capture the slow speed. This is also the case when I measure it via time.time(). This evidence seems to point to a lot of "overhead" being calculated or something after pressing execute on the cell, but before actual execution?

Andy ideas on how to fix this or what's going on?

**Comment by ruaridht** [comment]
@mmcguffi Did you solve your issue? I was also experiencing extremely slow cell execution, while still having high CPU load for tasks such as `x = 1`. I found that disabling the variableInspector (https://github.com/lckr/jupyterlab-variableInspector) extension solved my problem.

I was using JupyterLab v0.34.9 and variableInspector v0.1.0. In my case this appears to be related to https://github.com/lckr/jupyterlab-variableInspector/issues/59

**Comment by mmcguffi** [comment]
@ruaridht I disabled variableInspector and it seemed to clear it up! Thank you for the solution! much appreciated.
