### ISSUE TITLE
LaTeX \texttt regression?

### ISSUE THREAD

**Issue by mfenner1** [jupyter/notebook#406]
In older versions of ipython notebook (specifically 2.4.1) rendered locally (not sure about other options like nbviewer), I had no problem with the following LaTeX:  $\texttt{np.nan}$ in a Markdown cell.  The \texttt rendered a fixed-width, block font (tt is for something like "typewriter text") of the enclosed text.

Now, (with ipython 3.2.1 installed) it shows up as: \<red\>\texttt\<\/red\>\<ital\>np.num\</ital\> (sorry for the adhoc notation).

The \texttt seems to have been an explicit "fix" in MathJax 2.4:  https://www.mathjax.org/mathjax-v2-4-now-available/.  I'm wonder if some MathJax resource path needs to be updated.

**Comment by Carreau** [comment]
I think the should have been fixed by #324

**Comment by mfenner1** [comment]
If I have a few minutes, I'll try a dev version and check it out.  Thanks!

**Comment by mfenner1** [comment]
I did try jupyter dev and the issue is fixed.
