### ISSUE TITLE
Error : [sprintf] expecting number but found string

### ISSUE THREAD

**Issue by salilmishra23** [jupyter/notebook#4065]
![screenshot_2018-10-04 lesson1-rf](https://user-images.githubusercontent.com/28807011/46527170-06dfe000-c8ae-11e8-9462-aa42a8b94c8b.png)

I am not able to use notebooks from fastai for both machine learning and deep learning.
Link to the notebooks: https://github.com/fastai/fastai/tree/master/courses

I am using Notebook v5.7 on Ubuntu 18.04

**Comment by OliverMaerz** [comment]
Same issue here. 

Notebook 5.2.2, Python 3.6.6 (Anaconda on Ubuntu 18.04.1)

**Comment by OliverMaerz** [comment]
Same issue here.

Notebook 5.2.2, Python 3.6.6 (Anaconda on Ubuntu 18.04.1)

**Comment by OliverMaerz** [comment]
Could be a duplicate of #3235

**Comment by takluyver** [comment]
#3235 was meant to be fixed in notebook 5.5, please upgrade.

**Comment by stas00** [comment]
for some reason your jupyter is unable to handle:

`"execution_count": null,`

which is what you're seeing. The workaround is  https://github.com/fastai/course-v3/issues/64#issuecomment-434501646 but you need to figure out what's wrong with your jupyter of course.

I don't have this problem with jupyter 5.7.0 on Ubuntu 18.04 Python 3.6.6

**Comment by pushpendrapratap** [comment]
upgrading jupyter notebook to 5.7 version fixed this issue for me
