### ISSUE TITLE
Cells not running sequentially on "Run all"

### ISSUE THREAD

**Issue by kaktus42** [jupyter/notebook#4067]
Attached you find the error happening, because jupyter is not executing the two cells in the correct order.
Because in the latter cell, the DataFrame is deleted, the previous cell throws an error.

Windows 10
$ jupyter --version
4.4.0
$ jupyter notebook --version
5.7.0
$ python --version
Python 3.6.5 :: Anaconda, Inc.

![2018-10-05 11_45_21-210 - jupyter bug](https://user-images.githubusercontent.com/1608815/46528753-d63f7c80-c894-11e8-8606-85d11baa2662.png)

**Comment by ayorgo** [comment]
Same issue on "Run All Above" in different notebooks of mine. Appears to be breaking the sequence randomly on each run of the same set of cells within the same notebook. Kernel restart/shutdown doesn't help.
```
$ jupyter --version
4.4.0
$ jupyter notebook --version
5.7.0
$ python --version
Python 3.6.6
$ conda --version
conda 4.5.11
```

**Comment by cibic89** [comment]
Having the same problem when running selected cells using shift on the keyboard...

**Comment by ayorgo** [comment]
Seems to have been addressed already: https://github.com/jupyter/notebook/issues/4052, https://github.com/ipython/ipython/issues/11348
Alleged fix: https://github.com/ipython/ipykernel/pull/362

**Comment by minrk** [comment]
Closing as duplicate. ipykernel 5.1 should be out with the fix shortly.
