### ISSUE TITLE
Releases 5.6 and 5.7 are missing (exist only as tags)

### ISSUE THREAD

**Issue by mirekphd** [jupyter/notebook#4071]
Versions 5.6 and 5.7 of the python library on pypi create an impression that releases 5.6 and 5.7 have been made here on github, while they turn out to be just tags. Why not stick to the usual convention, whereby python library versions are named after releases? Thus:

`pip install notebook==github_release`

**Comment by jtpio** [comment]
Closing as these versions are not maintained anymore.

Newer versions should have proper tags and releases.
