### ISSUE TITLE
How to name a folder?

### ISSUE THREAD

**Issue by endencia** [jupyter/notebook#4076]
I need to create a folder named data.  When I create a folder, it just says untitled folder and can't find the link on how to rename a folder?  I want to put files in this folder
Also, how do i delete files / folders without deleting the local host tree?

**Comment by bhansa** [comment]
Hi, you can make the checkbox `checked` specific to folder which you created and then use `Rename` from the top menu options.

![image](https://user-images.githubusercontent.com/9723884/46757923-267d6b00-cce9-11e8-9189-fced4925492c.png)

Use checkboxes in the same way to delete files/folders in that structure.
Let me know if it helps.
