### ISSUE TITLE
Github couldn't render the LaTeX mathematics expressions in my notebook properly

### ISSUE THREAD

**Issue by lnshi** [jupyter/notebook#4083]
This is how it looks like in my local with `jupyter notebook`:

<img width="1250" alt="screen shot 2018-10-09 at 18 16 35" src="https://user-images.githubusercontent.com/24580114/46663955-18005800-cbf2-11e8-89c7-cf163a25a86b.png">

When i committed to github it will looks like this:  https://github.com/lnshi/ml-exercises/blob/master/jupyter_notebooks/rdm001_simple_linear_regression/simple_linear_regression.ipynb

![screen shot 2018-10-09 at 18 36 47](https://user-images.githubusercontent.com/24580114/46664024-5269f500-cbf2-11e8-8259-b8a1dadf3449.png)

What should I do to fix this?

`jupyter --version` -> 4.4.0
`uname -a` -> Darwin *********** 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

Google Chrome is up to date
Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by jtpio** [comment]
Closing as this should now be fixed (GitHub improved their notebook rendering recently).

Thanks!
