### ISSUE TITLE
Tooltip text is overlapped by tooltip buttons

### ISSUE THREAD

**Issue by stmax82** [jupyter/notebook#4086]
Since I upgraded the Jupyter package a few days ago the tooltip buttons seem to overlap the tooltip text, as you can see here:

![tooltip1](https://user-images.githubusercontent.com/6381927/46744366-5017a180-ccab-11e8-9b5b-0b8fdc18aa48.png)

Could be fixed using:

```
.tooltipbuttons {
    position: relative; /* instead of absolute */
    padding-right: 15px;
    top: 0px;
    right: 0px;
}

.tooltiptext {
    clear: right; /* avoid the buttons to overlap */
}
```

Result:

![tooltip2](https://user-images.githubusercontent.com/6381927/46745522-848c5d00-ccad-11e8-9360-f97b7a79938e.png)

```
Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 5.7.0
The server is running on this version of Python:
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]

Current Kernel Information:
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by MonkeyDNoppu** [comment]
Can I ask you a stupid question ??
Where is the solving code should be ??

**Comment by stmax82** [comment]
@MonkeyDNoppu in the directory where you python packages are located, search for the file notebook\static\style\style.min.css 

.. replace the existing .tooltipbuttons / .tooltiptext entries with the above.

There's a pull request in #4087..

**Comment by stmax82** [comment]
this seems to have been fixed already...

**Comment by vishalpunj** [comment]
we can make the tooltip buttons more transparent so that the text that is overlapped is understandable
