### ISSUE TITLE
Configure jupyter to accept more than one password

### ISSUE THREAD

**Issue by Mikikkk** [jupyter/notebook#4088]
Hi,

Is there a way to make jupyter accept more than just one password?
I would like to make a separation between users that login into the jupyter.

If this is not possible, is there another way to make a separation between users? because I have searched the internet and I found how to do it on jupyterhub, but it seems that jupyter notebook doesn't support anything.

Thank you.

**Comment by calz1** [comment]
Look into Jupyter Hub.

**Comment by takluyver** [comment]
Jupyterhub is an extra layer around Jupyter to support multiple users. It sounds like that's exactly what you need.
