### ISSUE TITLE
Jupyter Notebook skipping cells after 'Restart & Run All'

### ISSUE THREAD

**Issue by dougollerenshaw** [jupyter/notebook#4089]
I recently started encountering cells that fail to execute, and appear to be skipped, when I run a notebook top-to-bottom using the 'Restart & Run All' command. The behavior appears non-deterministic: it doesn't always skip the same cell, and sometimes it doesn't skip any.

Here's a screenshot of a simple example I created to replicate the behavior:
![image](https://user-images.githubusercontent.com/19944442/46827899-af7abd80-cd4e-11e8-85ed-79c2d561152b.png)

This particular test notebook fails about 75% of the time, and it never seems to skip any cells above the 5th.

I get the same behavior in both Chrome and Firefox. This seems to be limited to an environment running Python 3.6.6. I can't replicate this behavior when I run in a Python 2 environment. 

Here's info on my Jupyter install:
![image](https://user-images.githubusercontent.com/19944442/46827936-c0c3ca00-cd4e-11e8-9463-b14ae0afff70.png)
This is a Windows 10 machine. I'm happy to provide more system information to help troubleshoot.

**Comment by stonebig** [comment]
you have to upgrade to latest ipykernel-5.1.0

**Comment by dougollerenshaw** [comment]
Thanks! That fixes it. Sorry for the duplicate issue. I'm marking this closed.
