### ISSUE TITLE
TLS Client Authentication

### ISSUE THREAD

**Issue by adambrewster** [jupyter/notebook#410]
It would be nice to use TLS authentication instead of a password for authentication.

It should be a very simple change.  I'm not a python developer, but I got it working in an older version ipython and ported the change to today's master [1].  I'm submitting an issue instead of a pull request because I don't know how to install the package behind a firewall, so I don't know if it works.

[1] https://github.com/adambrewster/notebook/commit/bb4f614c44b2b3765e026463b40ceba8c4cf13b7

**Comment by Carreau** [comment]
I think you can submit a PR. 

@rgbkrk you are our ssl expert, I assign you to the issue.
