### ISSUE TITLE
How to set custom token as a cookie to be used at the Notebook Dashboard aka /tree page ?

### ISSUE THREAD

**Issue by IamViditAgarwal** [jupyter/notebook#4106]
I have made a custom authenticator that makes the user to login to my website and then redirect to their Jupyter Notebooks i.e. I am bypassing hub login.
Now My website login gives a public token that I need to set as a cookie to be used at the user Notebook Dashboard aka/ /tree page to call my API  .
The user notebook opens in the docker environment . I know about the spawner and is setting some values through it but they are not as a cookie or available at the browser end . I want the token to be accessible via browser as it is a public token.

Can u share with me  some tips/ideas for this implementation .
Thanks in Advance .
vidit

**Comment by takluyver** [comment]
Authenticators are part of Jupyterhub - this is the issue tracker for the single-user notebook server. Have a look at: https://github.com/jupyterhub/jupyterhub#help-and-resources
