### ISSUE TITLE
Jupyter kernel failes to get removed

### ISSUE THREAD

**Issue by mdivk** [jupyter/notebook#4108]
I stopped the Jupyter server, and ran the command `jupyter kernel remove <kernel name>` to remove the kernel, the command hangs there forever after showing a few lines:

    [rxie@cedgedev03 bin]$ jupyter kernelspec list
    Available kernels:
      spark1.6_conda_python2    /usr/local/share/jupyter/kernels/spark1.6_conda_python2
      spark2.3_conda_python2    /usr/local/share/jupyter/kernels/spark2.3_conda_python2
      spark23-conda             /usr/local/share/jupyter/kernels/spark23-conda
      python3                   /usr/share/jupyter/kernels/python3
    [rxie@cedgedev03 bin]$ jupyter kernel remove python3
    [KernelApp] Starting kernel 'python3'
    [KernelApp] Connection file: /run/user/10155/jupyter/kernel-35052ab9-4d4c-4316-b6d6-ce400c7b0bbc.json
    [KernelApp] To connect a client: --existing kernel-35052ab9-4d4c-4316-b6d6-ce400c7b0bbc.json

Switched to sudo, still hanging

What's the problem?

**Comment by takluyver** [comment]
You want `jupyter kernelspec remove`

`jupyter kernel` is for running a kernel.
