### ISSUE TITLE
the title has double backslash 

### ISSUE THREAD

**Issue by Jeffiy** [jupyter/notebook#411]
when I set the notebook_dir end with backslash.
![1](https://cloud.githubusercontent.com/assets/5069316/9778856/7e062948-57a8-11e5-95c8-4a4a2132c91d.png)
the title has double backslash
![2](https://cloud.githubusercontent.com/assets/5069316/9778859/852a79e0-57a8-11e5-99a2-f44e61f500de.png)
Is this a problem?

**Comment by Carreau** [comment]
you should have any problem, but we could try fix it still.

**Comment by Carreau** [comment]
**shouldn't**, typed too fast.

**Comment by Jeffiy** [comment]
yeah, that is a minor problem. Thanks.

**Comment by minrk** [comment]
rstrip `os.sep` on notebook_dir should do it.

**Comment by captainsafia** [comment]
@Carreau — I'll take on this one for 4.1 Can you set me as assignee?

**Comment by Carreau** [comment]
> I'll take on this one for 4.1 Can you set me as assignee?

We cannot assign people without commit rights. Just dropping a line that you are working on it is sufficient.

**Comment by Carreau** [comment]
> We cannot assign people without commit rights. Just dropping a line that you are working on it is sufficient.

Actually I gave the "student" group, read access so that I can assign you.

**Comment by captainsafia** [comment]
:smile:
