### ISSUE TITLE
feature request: md link to the same notebook in the same tab

### ISSUE THREAD

**Issue by ggrrll** [jupyter/notebook#4116]
Hi, 

an idea  I just had while using my notebooks -- not sure if it's already under development:

whenever I have a internal reference to another section of the same notebook, in a md cell, would be nice if after clicking it, the following action would take you to the right point _in the same tab_ , instead of opening the same notebook in a new tab.

Thanks

ps: this is maybe related to #4115

**Comment by minrk** [comment]
This is the behavior I see when I click markdown links to local anchors. What do your links look like that open new tabs?

The following links result in local navigation of the current tab:

```markdown
[click to scroll](#scroll-target)
```

and in a later cell:

```markdown
<a id="scroll-target">you found me!</a>
```

**Comment by ggrrll** [comment]
ok, 

 I see -- what  I wrote in the title is what happes when one puts a url which contains before something else, than just `#scroll-target` , like `localhost:8888/my_notebook.ipynb#find-best-alpha`

so sorry, my fault -- thanks for clarifying  @minrk
