### ISSUE TITLE
notebook_loaded.Notebook fires before extensions are loaded?

### ISSUE THREAD

**Issue by dsblank** [jupyter/notebook#412]
Trying to debug a Javascript nbextension loading issue that worked in version 3.0, but not in 3.2.1.

I have code in IPython/html/templates/notebook.html that looks like:

```javascript
<script type="text/javascript">
    sys_info = {{sys_info}};
    require(['base/js/namespace', 'base/js/events'], function (IPython, events) {
	events.on("app_initialized.NotebookApp", function () {
            IPython.load_extensions("calico-publish",
                                    "calico-submit",
                                    "calico-spell-check",
                                    "calico-document-tools",
                                    "calico-cell-tools");
        });
    });
</script>
```
Some of those extensions have code that should run when the event `notebook_loaded.Notebook` fires. However, sometimes (about 50%) it appears that the extensions are loaded after that event has already fired, and so they don't do their tasks.

Here are a couple of pictures from the javascript console:

Example of the extensions being loaded late:

![screenshot from 2015-09-10 08 19 50](https://cloud.githubusercontent.com/assets/168568/9788085/b136e04a-5795-11e5-88ad-78555554a319.png)

Example of the extensions doing their tasks:

![screenshot from 2015-09-10 08 18 49](https://cloud.githubusercontent.com/assets/168568/9788089/b62be2d0-5795-11e5-9027-3a5067b8d742.png)

Am I loading the extensions in the wrong place (in the html template)? 

(About 5% of the time (depending on size of notebook it seems) the extensions don't load at all.)

Any suggestions/help appreciated!

**Comment by dsblank** [comment]
It may have worked before, because we added the extension loading to every user's custom.js. We are on a new system now, with users perhaps already having their own custom.js. Is there a system wide custom.js that would be run every time? Or a js equivalent file?

**Comment by dsblank** [comment]
Actually, just putting this code in my own custom.js doesn't help... still have the 50% doesn't run problem.

**Comment by minrk** [comment]
There isn't an equivalent js file, but adding one may be appropriate for contexts like JupyterHub deployments.

**Comment by dsblank** [comment]
Ok, then I can add it to all users' custom.js files (or blow away their ~/.iptyhon stuff).

But any idea why the code doesn't run reliably?

**Comment by minrk** [comment]
I'm guessing it's a race on the HTTP requests, which can vary a lot.

**Comment by dsblank** [comment]
Ok, thanks for the quick feedback. I have rewritten the code a bit, running the `notebook_loaded.Notebook` callback also when the button get's added to the toolbar, and that seems to cover the late loading case too.

**Comment by Carreau** [comment]
If you can don't use custom.js to load extension use the configuration json with the extension name. 

I did push at some point that custom.js should actually be a module that define a function (load_custom), which is called at the right time (actually exactly as an extension), but it didn't get any tractions. 

I think it would avoid these kind of race conditions.

**Comment by dsblank** [comment]
On Fri, Sep 11, 2015 at 11:34 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> If you can don't use custom.js to load extension use the configuration
> json with the extension name.
>

Can you provide more details here about what you mean about the
configuration json? Where is it/where does it go? If it matters, we're on
jupyterhub.

**Comment by Carreau** [comment]
Yes I can: http://carreau.gitbooks.io/jupyter-book/content/Jsextensions.html (need update)

The js api from the notebook will update this file :

```
$ cat  ~/.jupyter/nbconfig/notebook.json
{
  "load_extensions": {
    "create_assignment/main": true
  }
}
```
nbgrader activate its extension by modifying/creating this file from the Python side.

**Comment by Carreau** [comment]
@dsblank do you get correct extension loading order now ?

**Comment by dsblank** [comment]
I made two changes:

1. used "notebook_loaded.Notebook" rather than "app_initialized.NotebookApp"
2. made the code that goes through an opening notebook happen when we add to the toolbar.

Change 2 might not be necessary with change 1. There was an issue with very large notebooks, but we are testing in the field this week. Looks good so far!

**Comment by dsblank** [comment]
Looks like we have worked around the issue. Thanks!

**Comment by jason-s** [comment]
just curious -- where is it documented to do this sort of thing?

<script type="text/javascript">
    sys_info = {{sys_info}};
    require(['base/js/namespace', 'base/js/events'], function (IPython, events) {
    events.on("app_initialized.NotebookApp", function () {
            IPython.load_extensions("calico-publish",
                                    "calico-submit",
                                    "calico-spell-check",
                                    "calico-document-tools",
                                    "calico-cell-tools");
        });
    });
</script>
