### ISSUE TITLE
Markdown preview

### ISSUE THREAD

**Issue by Achifaifa** [jupyter/notebook#413]
When I switched from the ipython notebook to the jupyter notebook I noticed that the markdown preview is disabled (Select 'markdown' for cell type, write something like '#TEST' and run the cell. It should display a big 'TEST', but it just displays the markdown notation). 

I was wondering if this has a reason or it's just something that stopped working and didn't get fixed, since the links do work as expected.

**Comment by minrk** [comment]
This isn't normal behavior. Markdown rendering is the same as before. Do you see any errors in the js console?

**Comment by Achifaifa** [comment]
No, no error messages or warnings.

If it works for everyone else, could it be a missing dependency or something?

**Comment by Achifaifa** [comment]
OH, I found what's wrong. Using '#text' doesn't work, but using '# text' does. Maybe a parser issue?

**Comment by minrk** [comment]
Ah, yes. That's a deliberate change in marked, and not something we control. See #276

**Comment by Achifaifa** [comment]
Is the HTML thing also intentional? And if not, is there a way around it?

**Comment by minrk** [comment]
@Achifaifa I believe it is intentional. I am not aware of a workaround.

**Comment by Achifaifa** [comment]
Thanks, I'll have to find out another way :)
