### ISSUE TITLE
Load failed, save is disabled

### ISSUE THREAD

**Issue by jg-you** [jupyter/notebook#415]
Just updated to jupyter 4.0.4 (on Arch), up from ipython 3.x.x.
Now it's impossible to load old notebooks, or create new ones.
If I open a new notebook, I have to manually set the kernel to python 3 after creation to be able to type / run code, but it will never save.

I open the notebook in CLI with `ipython notebook` or `jupyter notebook` (no difference).
Here's the log

    [I 14:55:15.317 NotebookApp] Serving notebooks from local directory: /home/jgyou
    [I 14:55:15.317 NotebookApp] 0 active kernels 
    [I 14:55:15.317 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
    [I 14:55:15.317 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    Created new window in existing browser session.
    [W 14:55:20.754 NotebookApp] 404 GET /api/kernels/374421ed-5c8c-400e-a924-b84edd41b96d/channels?session_id=49354DAD83864233A209F6E07FA369D7 (::1): Kernel does not exist: 374421ed-5c8c-400e-a924-b84edd41b96d
    [W 14:55:20.766 NotebookApp] 404 GET /api/kernels/374421ed-5c8c-400e-a924-b84edd41b96d/channels?session_id=49354DAD83864233A209F6E07FA369D7 (::1) 16.33ms referer=None

**Comment by minrk** [comment]
@jg-you do you see any messages in the javascript console?

**Comment by jg-you** [comment]
Here is the content of the console:

    Default extension for cell metadata editing loaded.                                     main.min.js:23923
    Raw Cell Format toolbar preset loaded.                                                  main.min.js:24009 
    Slideshow extension for metadata editing loaded.                                        main.min.js:24057 
    Uncaught TypeError: IPython.load_extensions is not a function                           :8888/custom/custom.js?v=20150911142454:52 
    Loaded extension: widgets/notebook/js/extension main.min.js:12065 loaded widgets        :8888/nbextensions/widgets/notebook/js/extension.js?v=20150911142454:81 
    GET http://localhost:8888/static/components/backbone/backbone-min.map 404 (Not Found)   backbone-min.map:1

**Comment by jg-you** [comment]
Just now realized that it's caused by an extension (toc) with the line

    $([IPython.events]).on("app_initialized.NotebookApp", function () {
        IPython.load_extensions("toc");
    });

in `custom/custom.js`. So it's fixed I guess hehe.

**Comment by minrk** [comment]
Hm, bugs in custom.js really shouldn't cause everything to die like that.

**Comment by jg-you** [comment]
It could be that the syntax I used to include the extension is really out of date / does not work at all anymore? Not familiar with JS, I just copy pasted from the extension README back in the ipython notebook days.

**Comment by damianavila** [comment]
>s really out of date / does not work at all anymore?

It is outdated but I agree with @minrk that a bug there should not trigger all these problems...

**Comment by kuatroka** [comment]
I have another issue similar to this one. I can't save any changes.
Error message:

>  Load failed, save disabled

versions:
Python 3.4
IPython 4.2.0

message in terminal:
`
[W 17:29:54.971 NotebookApp] Unrecognized JSON config file version, assuming version 1
[I 17:29:55.572 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
[I 17:29:55.912 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 17:29:55.912 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 17:29:55.949 NotebookApp] [nb_anacondacloud] enabled
[I 17:29:55.952 NotebookApp] [nb_conda] enabled
[I 17:29:55.957 NotebookApp] Serving notebooks from local directory: /Users/yo/Documents/Books/Python_Programming/mastering_pandas_for_finance
[I 17:29:55.957 NotebookApp] 0 active kernels 
[I 17:29:55.957 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 17:29:55.957 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 17:29:57.471 NotebookApp] Notebook 06_Trading_Using_Google_Trends (1)-Copy1.ipynb is not trusted
[W 17:29:57.540 NotebookApp] 404 GET /nbextensions/nbpresent/js/nbpresent.deps.min.js.js (::1) 7.65ms referer=http://localhost:8888/notebooks/06_Trading_Using_Google_Trends%20%281%29-Copy1.ipynb
[I 17:29:58.236 NotebookApp] Kernel started: 923e3e48-e8f1-48cf-a6bc-6aa2d7090771
[I 17:37:08.937 NotebookApp] 302 GET / (::1) 0.91ms
`

Any help would be appreciated. Thanks.
