### ISSUE TITLE
Not able to open Jupyter Notebooks

### ISSUE THREAD

**Issue by prerna-p** [jupyter/notebook#4152]
I have been trying to open the Jupyter Notebooks in this repository since a couple of weeks now, and they don't load. Github always returns the message  "Something Went Wrong"
Its been happening for a while now.
This is the repository:
https://github.com/itaher1995/CS6220_Final_Project

**Comment by Dubrzr** [comment]
It works only for small .ipynb files.
It is not a problem related to this Jupyter/Notebook repository.
