### ISSUE TITLE
Authenticate with password over ssh/terminal

### ISSUE THREAD

**Issue by dscarmo** [jupyter/notebook#4154]
I use Jupyter on my home server.

There is a problem that if my jupyter backend at home for some reason shuts down, i cant turn it back on through SSH remotely. I have to open a browser to type in my password in the home server, which is impossible to do through ssh in a terminal.

Is there any way to authenticate the jupyter backend using password when i run it through SSH?

**Comment by takluyver** [comment]
It should be entirely possible to start it through SSH - just use the `--no-browser` flag. Then you should be able to open a browser locally to connect to your server and enter the password.

Alternatively, you could run a small instance of Jupyterhub set up as a system service which is automatically kept running.

**Comment by dscarmo** [comment]
Yeah that works! The trick is to NOT authenticate on the server. 

Steps:

1- Initialize your jupyter in your remote server through ssh, tunneling jupyter port to your local port and with --no-browser 

2- Run the browser in your local machine and type password. DO NOT do this on the remote server.

Thanks for the help!

**Comment by takluyver** [comment]
Glad you got it working. It shouldn't make any difference whether you authenticate a browser on the server, though. You can authenticate more than one browser.
