### ISSUE TITLE
Import Error: .py file cannot be edited after import

### ISSUE THREAD

**Issue by namanjn98** [jupyter/notebook#4156]
After importing, if we edited the .py file the changes do not show in the notebook. 
Re-Importing does not help.
Only restarting the kernel solves the issue.

**Comment by takluyver** [comment]
That's how Python imports work. You can [manually reload a module](https://docs.python.org/3/library/importlib.html#importlib.reload), or use IPython's [autoreload extension](https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html).
