### ISSUE TITLE
How about removing 'In' of 'In [  ]' and 'Out [  ]'?

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#4174]
I referenced the design of google [colab](http://colab.research.google.com) and found '   In ' took too much space of div.input_prompt and 'Out [  ]' is in fact unnecessary.

**Comment by jtpio** [comment]
Closing as this is now the case in Notebook 7:

![image](https://github.com/jupyter/notebook/assets/591645/dfc72e9e-985b-4118-8b73-f60e7da98411)


Thanks!
