### ISSUE TITLE
Write a Migration guide in particular --profile.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#419]
Title pretty self explanatory.

**Comment by ellisonbg** [comment]
@fperez and I had talked about this being on the jupyter/jupyter main docs
as some of the migration stuff spans multiple repos and projects.

On Fri, Sep 11, 2015 at 10:19 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Title pretty self explanatory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/419>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Sure, in jupyter/jupyter is fine too.

**Comment by minrk** [comment]
I'll try to spend some time this weekend drafting some transition docs that have come up in a few places. I've been spending much of the last day or two on Issue classification.

**Comment by damianavila** [comment]
> I've been spending much of the last day or two on Issue classification.

Yep, we saw a waterfall of PR notifications :wink: ... really great job and very appreciated!

**Comment by ellisonbg** [comment]
@minrk - I am also willing to help write the part of the migration on jupyter/jupyter, but I don't have it all in my head. If you want to jot down the main technical details somewhere I can iterate on the rest of it.

**Comment by willingc** [comment]
@minrk Happy to help as well.

**Comment by minrk** [comment]
@ellisonbg @willingc hopefully I'll have a draft up tomorrow covering the main points, and we can iterate from there. Thanks!

**Comment by Carreau** [comment]
cross link to https://github.com/ipython/ipython/issues/8769

**Comment by Carreau** [comment]
Link with [ML explanation](https://groups.google.com/forum/#!search/JUPYTER_CONFIG_DIR/jupyter/7q02jjksvFU/GI_rcYtQDQAJ).
