### ISSUE TITLE
MAS 2.4.1: Frames must have title attribute (#iframe)

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#4207]
Azure Notebooks - Welcome has an accessibility issue that needs investigation.

Issue Details
Frames must have title attribute
frame-title

Element Path
#iframe

Snippet
<iframe id="iframe" frameborder="0" style="width: 1140px; height: 1379px;" scrolling="no" src="/api/user/ahcan/library/amlsdkwidgets/html/Widgets.ipynb"></iframe>

How to fix
Fix any of the following:
- aria-label attribute does not exist or is empty
- aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
- Element has no title attribute or the title attribute is empty
- Element's default semantics were not overridden with role="presentation"
- Element's default semantics were not overridden with role="none"

To reproduce
Use K4W to investigate the issue details

Environment
Chrome version 69.0.3497.100

This accessibility issue was found using Keros for Web, a tool that helps debug and find accessibility issues earlier. Get more information & download this tool at http://aka.ms/K4Web.

[MAS 2.4.1 Frames must have title attribute (#iframe).zip](https://github.com/jupyter/notebook/files/2576209/MAS.2.4.1.Frames.must.have.title.attribute.iframe.zip)

**Comment by joshuazeltser** [comment]
Using the above tool this issue does not occur and the tool produces the following output: 
![image](https://user-images.githubusercontent.com/17781896/60175007-466aa580-980a-11e9-8358-faaf11940361.png)

I, therefore, can't see where this issue occurs?

**Comment by jtpio** [comment]
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!
