### ISSUE TITLE
Jupyter Notebook german Neo 2.0 Layout + and = not working

### ISSUE THREAD

**Issue by unic0rned** [jupyter/notebook#4226]
There was an earlier issue regarding the "-" key not working on Neo 2.0

Now 4 years later the "-" key is working. But "+" and "=" are not working anymore.

Similar to this closed issue
#3646

they produce one word cursor moves to the right or to the left.

it's mod key + n and mod key + o that I have to press for the + and the = sign.
In the keyboard shortcuts I can't find any shortcut that's in the way.

Do you have any ideas?

**Comment by leezu** [comment]
AFAIK this needs to be fixed upstream https://github.com/codemirror/CodeMirror/issues/4066

**Comment by unic0rned** [comment]
I understand. I try the proposed fix there. If this doesnt work I try a different browser.

**Comment by unic0rned** [comment]
You can close this Issue then.
