### ISSUE TITLE
Large buttons block view of docstring

### ISSUE THREAD

**Issue by JovanVeljanoski** [jupyter/notebook#4230]
Hi, 

Few months ago I upgraded my version of the Jupyter Notebook to 5.7.2. I noticed that when I few docstrings, these large buttons appear (please see screen-shot below), often blocking important keywords. I find myself that I remember many of the keywords first few keywords, but I like viewing the docstring after that, and this makes it a bit harder. 

I've have the same behaviour on Firefox, and Safari (macOS High Sierra). I am not a Chrome user so I can't comment on that. 

Thank you.

![buttons-blocking-docstring](https://user-images.githubusercontent.com/18574951/48935603-77979600-ef08-11e8-9a75-2c3080caef12.png)

**Comment by steaward** [comment]
Hey @JovanVeljanoski , how did you get the docstrings to appear?
 Shift-tab doesn't seem to make them appear for me.

**Comment by steaward** [comment]
> Hi @samarsultan , I use shift-tab, but more like shift-tab-tab (double tap on the tab) to get the description to appear. With just one tab press, I get the keywords only.

Awesome, thanks. I've replicated the bug and I'll work on fixing it!

**Comment by JovanVeljanoski** [comment]
Thank you, much appreciated!
