### ISSUE TITLE
[Help wnated] Hot to stop password protected notebook from terminal 

### ISSUE THREAD

**Issue by russoale** [jupyter/notebook#4238]
Hi there, 

I have a two convenient functions in my `.zshrc` to start and stop a jupyter notebook on a remote machine:

```

jupy(){
    echo "connect to remote server and start notebook ..."
    ssh user@remote -t 'bash -ci "cd workspace/; source venv/bin/activate; jupyter notebook --no-browser --port=XXXX &"'
    ssh -N -L XXXX:localhost:XXXX user@remote &
    open -a firefox -g http://localhost:XXXX &
}

jupy-stop() {
    ssh user@remote -t 'bash -ci "cd workspace/; source venv/bin/activate; jupyter notebook stop XXXX; deactivate &"'    
    lsof -ti:XXXX -sTCP:LISTEN | xargs kill
}

```

Now I would actually prefer to grep the token and save it in an environment variable. Actually been looking for a solution very long. Nevertheless I came up with a password. 
Now the issue is that I can't stop the password protected notebook via terminal command `jupyter notebook stop XXXX` always getting a `403`. 

Any idea how to make this possible? 
Thanks

**Comment by dickmao** [comment]
#4386
