### ISSUE TITLE
Literal String fails when ends with r'\'

### ISSUE THREAD

**Issue by villuis91** [jupyter/notebook#4249]
Probably he's thinking that \' is an special symbol and don't stop reading the string

For example:

```
temp_path = r'\\someserver\F$\Triada\'
def main():
     print("hello")
```

It handles def main() as a continuation of the text (you can see it with the text color or just try to execute). Must move to non literal to handle the exception.

**Comment by takluyver** [comment]
That appears to be how Python handles raw strings. I don't think there's any bug here.
