### ISSUE TITLE
Can not rename a folder

### ISSUE THREAD

**Issue by rexchoi1983** [jupyter/notebook#4263]
I can't rename a folder. It returns "No such file or directory:XXX" . No matter in Windows 10 or Centos 7.4. But i can create new folder or file, upload files. How can i fixed it ? 
![image](https://user-images.githubusercontent.com/40167113/49868685-2153ae00-fe49-11e8-8142-c9c0e0654d19.png)

**Comment by jtpio** [comment]
Closing as this should now be fixed in the latest version (Notebook 7 at the moment).

Thanks!
