### ISSUE TITLE
Configuring the Notebook and Server.ipynb / public_server.rst duplicate info

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#428]
also the ipynb refer to a crt file which is not created by the openssl command.

**Comment by Carreau** [comment]
@willingc that look that something you might be good at, want to have a look ?

**Comment by willingc** [comment]
@Carreau Taking a look at this [public_server.rst](https://github.com/jupyter/notebook/blob/master/docs/source/public_server.rst). A couple of questions:

* Is the goal to improve the docs on creating a self-signed cert and the gotchas that you may face when creating?
* When using the notebook with a self-signed cert `--certfile=mycert.pem`, the browser will likely complain that it's an unsafe action and ask to return to safety. What is our typical response to the user on what to do?
* Are both the `.rst` file or the `.ipynb` documents being used by users to create and use a cert? Or is one doc a legacy doc and the other the doc that will be used going forward?

**Comment by Carreau** [comment]
> Is the goal to improve the docs on creating a self-signed cert and the gotchas that you may face when creating?

That's one goal if possible but not obligatory. 



> When using the notebook with a self-signed cert --certfile=mycert.pem, the browser will likely complain that it's an unsafe action and ask to return to safety. What is our typical response to the user on what to do?

That we are aware, and even self signed is better than no certificate at all if you don't want people to snoop or modify what information on the wire.

> Are both the .rst file or the .ipynb documents being used by users to create and use a cert? Or is one doc a legacy doc and the other the doc that will be used going forward?

I think the rst is older. I think we can keep the `.ipynb` I just want to make sure all the info is on the one we keep whichever you think is fit. 

@rgbkrk, @minrk any other thoughts on that ?

**Comment by minrk** [comment]
I think this doc makes more sense as plain rst, but I don't feel strongly about which one we keep. I suspect there's information in both that should be merged into whichever one.

**Comment by rgbkrk** [comment]
> When using the notebook with a self-signed cert --certfile=mycert.pem, the browser will likely complain that it's an unsafe action and ask to return to safety. What is our typical response to the user on what to do?

We should link people to a solid resource for adding their (trusted) self signed certs to their system. This applies for Firefox, Chrome, and IE. Safari on the other hand is pretty much a non-starter. IIRC, self signed certs with Safari don't work with websockets for some reason.

**Comment by minrk** [comment]
> self signed certs with Safari don't work with websockets for some reason.

Safari doesn't allow websocket connections to *untrusted* certs (self-signed or otherwise). *Trusted* self-signed certs work fine.

**Comment by willingc** [comment]
I will merge the content from both docs and look for a solid resource or two on creating trusted self-signed certs. I will probably use rst for the doc. As for the ipynb, I will try to replicate the content of the rst in the notebook. I'll also add a note and link to the top of the notebook that the rst has the most up to date information.

**Comment by Carreau** [comment]
#443 was a first step toward that, I left 3 minor comments/questions in there to adress.
