### ISSUE TITLE
Improve displayed values from cell

### ISSUE THREAD

**Issue by aamster** [jupyter/notebook#4282]
In Rstudio rmarkdown or notebook, if I have the following code in a cell:

```
head(foo)
head(bar)
head(baz)
```
Then the head of foo, bar, baz will be displayed.

In jupyter notebook only `head(baz)` will be displayed. 

The use case is that I want to check several data frames by printing them below the cell. Or I want to make several plots. I believe you can use the function `display` to have this functionality but it is cumbersome.

**Comment by takluyver** [comment]
https://github.com/IRkernel/IRkernel is a separate project. You could try asking about it there, but I guess it's just the way it works. `head()` is not an explicit display function, it's returning an object with the first n objects.
