### ISSUE TITLE
Creation of redirect fail breaks use of `jupyter notebook list`

### ISSUE THREAD

**Issue by ChrisHowlin** [jupyter/notebook#4283]
## Description
The introduction of a redirect file in 270c0f96d761ec3c81e0ef3dae6f39d88677d6b5 breaks usage of `jupyter notebook list`, as the logic for determining running notebook servers relies on iterating over all files in runtime-dir with prefix "nbserver-" and trying to load as JSON.

See: https://github.com/jupyter/notebook/blob/51dae23b593ce74c0c99a9f13f2282e5c4c77da3/notebook/notebookapp.py#L1842

## Reproduction
1. `jupyter notebook`
2. `jupyter notebook list`

Error:
```
  File "<env>/python3.6/site-packages/notebook/notebookapp.py", line 1836, in list_running_servers
    info = json.load(f)
  File "<env>/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "<env>/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "<env>/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "<env>/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

### Change
The use of the redirect file (format `nbserver-%s-open.html`) breaks this assumption and causes a JSON parsing error (trying to parse an HTML file as JSON).

### How to fix
Two possibilities for resolving:
1. Use different prefix for redirect file
2. Update notebook list behaviour to filter for files matching format `nbserver-\d+.json`

**Comment by ChrisHowlin** [comment]
Tagging @takluyver as original committer of 270c0f9

**Comment by ChrisHowlin** [comment]
Introduced in 5.7.3

**Comment by takluyver** [comment]
Gah, sorry. I didn't think to check that, and our test suite wasn't sufficient to pick it up. #4284 should fix it, and add the missing test. Can you give that a try and check that there aren't any other problems affecting your use cases? Hopefully I can do a 5.7.4 soon.

**Comment by takluyver** [comment]
Thanks! I'm going to bed soon, so 5.7.4 will probably be tomorrow.
