### ISSUE TITLE
kernel dies on on_boundary

### ISSUE THREAD

**Issue by elonsucks** [jupyter/notebook#4289]
hey guys, so I am trying to run this code which I have attached, and kernel keeps dying at on_boundary everytime. I tried on 2 different systems with same results. what the hell is happening. I am new to this and I have absolutely no idea!
![2018-12-17](https://user-images.githubusercontent.com/43437396/50092741-2c268e00-020f-11e9-9514-44383a929c1d.png)
[part3 (1).zip](https://github.com/jupyter/notebook/files/2686410/part3.1.zip)

**Comment by takluyver** [comment]
Generally the kernel dying means that something has gone critically wrong in a compiled extension library. You might want to ask about it on a forum for whatever library or framework you're using in the notebook.
