### ISSUE TITLE
Kernel Cannot Be Found - Python 3.7.1 - Conda Install

### ISSUE THREAD

**Issue by RGAlexander216** [jupyter/notebook#4295]
I'll go ahead and state that this may be a duplicate, but I've been able to recreate this issue on two different devices and no other topic is (obviously) the same from what I can tell.

 Upgrading Python to 3.7.1 via conda install has broken the nb_conda_kernel. It states that the package is not installed, but it is at least present where it should be. If I revert back to 3.7.0 the issue is resolved so this appears to be version-specific.

**Comment by takluyver** [comment]
You'd probably need to ask on the nb_conda_kernels project about that: https://github.com/Anaconda-Platform/nb_conda_kernels
