### ISSUE TITLE
Jupyter Notebook RISE distorts layout of the HTML/CSS presentation

### ISSUE THREAD

**Issue by Foadsf** [jupyter/notebook#4296]
I have posted [my question here](https://stackoverflow.com/questions/53876812/jupyter-notebook-rise-distorts-the-html-css-layout-of-presentation) with all the details and sample codes I have tried. Basically I want to make an entire presentation in Jupyter-RISE. This is what I get in the browser:

![What I want](https://i.stack.imgur.com/cr0Lv.png)

and this is what iI get:

![What I get](https://i.stack.imgur.com/5ueaV.png)

I would appreciate if you could help me know wy this is happening and how I can resolve it.

**Comment by yuvipanda** [comment]
Heya!

Opening this issue in the RISE repository (https://github.com/damianavila/RISE) may bring better help. Am pinging @damianavila, who is the creator of RISE and maybe able to help transfer the issue.

**Comment by damianavila** [comment]
Yep, let's try to transfer this to the RISE repo.

**Comment by damianavila** [comment]
Closing in favor of https://github.com/damianavila/RISE/issues/438
