### ISSUE TITLE
MacOS file paths copied to Jupyter are not recognized

### ISSUE THREAD

**Issue by deitelberg** [jupyter/notebook#4297]
I hope this is the correct place to post this, let me know if I should post elsewhere. 

I'm running a Python 3.6 Jupyter Notebook created with Conda on MacOS Mohave (v10.14.1), in a Chrome browser (v71.0.3578.98). 

I used to work on Windows machines, and so I still copy/paste file paths. On a Mac, I right-click on the file and select 'Get info' to find the file path in the 'Where' line. I then highlight that and copy it. 
<img width="270" alt="screen shot" src="https://user-images.githubusercontent.com/16692712/50352959-bd01b000-0514-11e9-83e2-cb9c2f85c398.png">

I then paste the file path to my Jupyter Notebook, like this. 
<img width="562" alt="screen shot 2" src="https://user-images.githubusercontent.com/16692712/50353100-271a5500-0515-11e9-8419-3ee5616c1e94.png">

Then replace the triangles with forward slashes, and add quotes and such, like:
<img width="586" alt="screen shot 3" src="https://user-images.githubusercontent.com/16692712/50353186-706aa480-0515-11e9-9bde-868495c9f15c.png">

The Python OS package doesn't recognize this as a directory when using the copy/paste path.
<img width="567" alt="screen shot 4" src="https://user-images.githubusercontent.com/16692712/50353421-39e15980-0516-11e9-9754-4139f0bf36c0.png">

But when I hand type the exact same path as I see it in the above screenshot, it is recognized as a directory.
<img width="573" alt="screen shot 5" src="https://user-images.githubusercontent.com/16692712/50353505-790faa80-0516-11e9-8011-70e892149646.png">

Do you know why this is? Is there some hidden formatting? Should Jupyter handle this natively?

Here are the two paths, hopefully with any hidden formatting preserved here:
Copy/pasted:  '../⁨test_folder1⁩/⁨test_folder2⁩/⁨test_folder3⁩'
Hand-typed:  '../test_folder1/test_folder2/test_folder3'

Thanks.

 **FOLLOW UP:**
I looked into this more and found occurrences of isolate characters, unicode \u2068 and \u2069, that are copied from the 'Get info' window. Python/Jupiter reads these and does not know to ignore them in the path string.

**Comment by takluyver** [comment]
I don't think there's anything we can do about that. The invisible unicode characters make it an incorrect path.
