### ISSUE TITLE
I am beginner of deep learning , how to bulit a model

### ISSUE THREAD

**Issue by suri199507** [jupyter/notebook#4299]
Hi, i am a beginner of deep learning, I am trying to build deep learning for image classification model,
but I got the errors, please help me, anyone, how to solve it. 
This is my notebook link:
http://localhost:8888/notebooks/intel%20data.ipynb

model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=batch_size,epochs=epochs,verbose=1)
ValueError: Error when checking target: expected dense_8 to have shape (3,) but got array with shape (6,)

```

**Comment by BBraitling** [comment]
suri199507 
this does not seem to be a notebook issue.
It seems to be a problem with your understanding of deep learning and matrix size/shape, perhaps cross entropy.  Presuming you have no professor...  Here is a notebook version of a tutorial.

"Cross entropy is always larger than entropy; encoding symbols according to the wrong distribution...will always make us use more bits. " https://github.com/rdipietro/jupyter-notebooks/blob/master/friendly-intro-to-cross-entropy-loss/A%20Friendly%20Introduction%20to%20Cross-Entropy%20Loss.ipynb 

However, if you are using DeepLabCut there were issues when using certain installation configurations, but that should be addressed on their Git...

**Comment by suri199507** [comment]
Thank you BBraitling
