### ISSUE TITLE
Jupyter 4.0.4 doesn't open notebooks with python kernels on Mac 

### ISSUE THREAD

**Issue by Sjnjerak** [jupyter/notebook#430]
I just updated to Jupyter 4.0.4 through the Anaconda distribution. I can open the notebook app fine, but when I try to open one of my existing notebooks in my browser the No information is seen, and the circle in the corner indicate that the kernel is busy (see image). 
![notebook_will_not_open](https://cloud.githubusercontent.com/assets/8447235/9879186/27fcadc8-5bbe-11e5-9ddc-668e5964f5c2.png)

I don't get any error message in the terminal window, in fact the terminal window gives no indication that I have tried to open something.

I'm running Mac OS version 10.10.5.

Going back to an earlier version of Jupyter fixes the problem, but I would like to update at some point and thought you should be aware of the issue.

Thank you.

**Comment by minrk** [comment]
Do you see any error messages in the javascript console (View > Developer > Javascript Console in Chrome)?

**Comment by Sjnjerak** [comment]
I run the notebook in Safari, is there any equivalent?

**Comment by minrk** [comment]
In Safari it is 'Develop > Show Error Console' (Develop menu may be off, in which case check 'Preferences > Advanced > Show Develop menu'

**Comment by jsilve24** [comment]
I am having the same issue. This is what I get from teh javascript console in Chrome:
![ipython_notebook](https://cloud.githubusercontent.com/assets/452422/10107345/6cbf4ca0-6388-11e5-94cf-60ec601fb606.jpg)

**Comment by jsilve24** [comment]
I click on the :88/custom/custom.js?[...] link I see my custom.js file from when I installed the TOC extension from minrk. Specifically these lines:

// Load Table of Contents Extension 
// Found here: https://github.com/minrk/ipython_extensions
$([IPython.events]).on("app_initialized.NotebookApp", function () {
    IPython.load_extensions("toc");
});

However I have removed these lines from my current custom.js file. So why is chrome/ipython notebook still trying to load the old version?

Thank you

**Comment by jsilve24** [comment]
So somehow those same lines:

// Load Table of Contents Extension 
// Found here: https://github.com/minrk/ipython_extensions
$([IPython.events]).on("app_initialized.NotebookApp", function () {
IPython.load_extensions("toc");
});

Also made it into ~/.jupyter/custom/custom.js

So when I deleted those lines from there it fixed the problem.

**Comment by Sjnjerak** [comment]
Thank you. Sorry for the slow reply. Here is my error message:
![ipython_error_message](https://cloud.githubusercontent.com/assets/8447235/10108750/b0fa6ff8-63ba-11e5-80a0-c88d5d3f94f3.png)

**Comment by bliker** [comment]
I had different yet similar problems with safari. I suggest clearing your localhost/127.0.0.0 caches in Preferences > Privacy > Cookies and website data - Details

**Comment by Sjnjerak** [comment]
Thank you! I tried that, but it didn't help. Will go back to running the earlier version of the notebook for now. If anyone needs any additional information from me please let me know.

**Comment by tritemio** [comment]
I've seen this 404 error a few times and in my case it was related to an extension installed before the migration (in particular the TOC extension).

@Sjnjerak do you use any extension?

**Comment by tritemio** [comment]
I need to add that removing the extension code from the custom.js fixed the problem.

**Comment by minrk** [comment]
@tritemio thanks, then I think this is fixed by #424
