### ISSUE TITLE
Notebooks get missing cells when opened in colab (version compatibility?)

### ISSUE THREAD

**Issue by matanster** [jupyter/notebook#4307]
I am uploading notebooks saved with the following versions of jupyter components, and getting them missing some cells when opening them in google colab. The cells are not folded/collapsed, but really missing in in colab, such that the notebooks fail due to definitions missing due to the missing cells. I got this with two different notebooks on different days, and oddly it was consistent with each try of them and not something transient. I wonder whether anyone here or at google is testing version compatibility? 

I could be running a newer version of jupyter components than colab does, judging by seeing that colab uses e.g. an older version of pandas than the one I have with my conda install.

Here's by the way my jupyter version info, as seen from the output of `conda list | grep upyter`:

> jupyter                   1.0.0                    py36_4  
> jupyter_client            5.2.3                    py36_0  
> jupyter_console           5.2.0            py36he59e554_1  
> jupyter_contrib_core      0.3.3                      py_2    conda-forge
> jupyter_contrib_nbextensions 0.5.0                    py36_0    conda-forge
> jupyter_core              4.4.0            py36h7c827e3_0  
> jupyter_highlight_selected_word 0.2.0                    py36_0    conda-forge
> jupyter_latex_envs        1.4.4                    py36_0    conda-forge
> jupyter_nbextensions_configurator 0.4.0                    py36_0    conda-forge
> jupyterlab                0.32.1                   py36_0  
> jupyterlab_launcher       0.10.5                   py36_0  

If there's any word of which version colab's fork is using (I don't think it is open sourced?!) I could be happy to use the same one locally, if anyone happens to be able to share.

And if not that, alternatively, is there any way to backport a notebook to an older version of jupyter for this and similar non-colab cases?

**Comment by colaboratory-team** [comment]
Please share a notebook that exhibits this behavior and we'll take a look.

**Comment by matanster** [comment]
[test4.zip](https://github.com/jupyter/notebook/files/2716749/test4.zip)

In this minimized example notebook, the last cell will not show in colab after uploading it. At least with my user. There's a message "Cell 4HG9ip1tOSf6 already exists, ignoring." in the log (using Google Chrome).

**Comment by matanster** [comment]
I have found that the browser console warnings about "already existing cells" (see above) correspond to duplicate ids found in the original notebooks prior to loading them to colab. Maybe they get duplicated when e.g. splitting a cell. 

So looking at the notebook file with `grep`, I could workaround the problem by locating cells sharing the same (and hence) duplicate ids, and removing them after moving their contents to new cells (while maintaining the notebook's ultimate cell order). Uploading after this workaround ― those console error messages no longer show, and the notebook has all its cells.

**Comment by takluyver** [comment]
Closing as it sounds like a colab issue, not notebook. We've always tried to avoid baking unique cell IDs into Jupyter because of this kind of difficulty, along with the ugliness for storing notebooks in version control.

**Comment by matanster** [comment]
Oh, I was formwrly under the impression here that the collab team does
watch the issues here on the repo for the sake of embetterment or
portability

**Comment by takluyver** [comment]
It looks like they do, at least sometimes. But there's nothing to fix in the notebook package itself, as far as I can see, so it doesn't make sense to leave the issue open here.

**Comment by subhacom** [comment]
Encountered this issue when a cell was split in Jupyter notebook. The two new cells get the `id` metadata copied from the original and colab seems to ignore a cell if its `id` is a duplicate.
