### ISSUE TITLE
asyncio.run() fails in the notebook

### ISSUE THREAD

**Issue by pylang** [jupyter/notebook#4312]
**Problem**

I cannot run in the notebook a demo from the [asyncio docs][0]:

![2019-01-02 23_08_03-untitled](https://user-images.githubusercontent.com/10778668/50623487-6ae16700-0ee4-11e9-8242-9f4647699ef5.png)

**Observation**

It does seem to run in ipython:

![2019-01-02 23_06_19-cmder](https://user-images.githubusercontent.com/10778668/50623533-cd3a6780-0ee4-11e9-9331-e8a866760102.png)

**Setup**

I've installed a new everything on a fresh install of Windows 10.  
I am running Python 3.7 via Anaconda 2018.12.

```bash
conda                     4.5.12                   py37_0
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.2.0            py37h39e3cac_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.4                    py37_0
notebook                  5.7.4                    py37_0
```

  [0]: https://docs.python.org/3/library/asyncio-task.html#coroutines
  [1]: https://www.anaconda.com/download/

**Comment by takluyver** [comment]
cc @Carreau

**Comment by Carreau** [comment]
Yes, it is a known limitation. 
You need to use things like [nest-async-io](https://pypi.org/project/nest-asyncio/). This is [documented here](https://ipython.readthedocs.io/en/stable/interactive/autoawait.html?highlight=nest#using-autoawait-in-a-notebook-ipykernel). 

You should be able to just `await main()`

**Comment by Carreau** [comment]
I'm going to close as I'm not sure there is much we can do as nesting event loop is a bad idea.
Feel free to keep commenting or ask for a re-open.
