### ISSUE TITLE
Handling ANSI escape sequences in cell output

### ISSUE THREAD

**Issue by andyljones** [jupyter/notebook#4315]
The notebook doesn't appear to handle ASCII escape sequences like `\e[G17` (move cursor to character 17). This came to my attention because a commonly used function in the Julia REPL doesn't work in IJulia (JuliaLang/IJulia.jl#792). There's two approaches to fixing it: either add support here for these kind of sequences, or get Julia to stop using the sequences. 

Now, I know nothing about either Julia's internal's or Jupyter so: is adding support for this to Jupyter going to be easy/hard/very hard/notgonnahappen? I suspect (again, knowing nothing) it'd require passing the output from every cell through a terminal emulator of some sort, and if that's the case it's probably easier to get the Julia devs to get rid of their escape sequences.

**Comment by takluyver** [comment]
We support a limited set of escape sequences, mainly related to formatting, e.g. changing text colour. It does include overwriting the line and (I think) backspace, but not the arbitrary cursor movement commands.

I suspect it's not worth trying to support arbitrary cursor movement - we're not presenting a terminal UI, so there's only so much of the terminal that can be emulated. But if someone wanted to work out a specific proposal (e.g. handling movement to cells on the same line), it's not necessarily impossible.

**Comment by andyljones** [comment]
Well that sounds tricky. I'll try the alternative first, and close this for now. Thanks!
