### ISSUE TITLE
Cross origin websockets are broken for TermSocket

### ISSUE THREAD

**Issue by zischwartz** [jupyter/notebook#432]
Regardless of what `--NotebookApp.allow_origin` is set to, trying to use the the terminal/terminado websocket connection across origins is broken, and causes the error below.

Working on a fix now. I think TermSocket just needs to implement the `check_origin` [method](http://tornado.readthedocs.org/en/latest/websocket.html#tornado.websocket.WebSocketHandler.check_origin) (to satisfy tornado>4) and, confusingly `origin_check` (to override the terminado [method](https://github.com/takluyver/terminado/blob/master/terminado/websocket.py#L59)).

I'm running this from the included docker file. 

Vaguely related to  ipython/ipython#8375.

```
[I 15:33:34.190 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:80/
[I 15:33:34.191 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 15:33:38.299 NotebookApp] 302 GET / (192.168.99.1) 1.14ms
[I 15:33:46.678 NotebookApp] New terminal with automatic name: 1
[I 15:41:31.373 NotebookApp] New terminal with automatic name: 2
[E 15:41:31.394 NotebookApp] Uncaught exception GET /terminals/websocket/2 (192.168.99.1)
    HTTPServerRequest(protocol='http', host='192.168.99.100', method='GET', uri='/terminals/websocket/2', version='HTTP/1.1', remote_ip='192.168.99.1', headers={'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'Upgrade', 'Origin': 'http://0.0.0.0:8080', 'Sec-Websocket-Version': '13', 'Pragma': 'no-cache', 'Upgrade': 'websocket', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36', 'Host': '192.168.99.100', 'Accept-Language': 'en-US,en;q=0.8', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits', 'Cookie': '_ga=GA1.1.1035836965.1441995168', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'LZhtgg5WwFz5xFaDFUNpGw=='})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1369, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1572, in wrapper
        result = method(self, *args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 181, in get
        self.finish(log_msg)
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 389, in _disallow_for_websocket
        method(self, *args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 936, in finish
        self._log()
    TypeError: 'Logger' object is not callable
[E 15:41:31.400 NotebookApp] Cannot send error response after headers written
[E 15:41:31.401 NotebookApp] Failed to flush partial response
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1369, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1572, in wrapper
        result = method(self, *args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 181, in get
        self.finish(log_msg)
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 389, in _disallow_for_websocket
        method(self, *args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 936, in finish
        self._log()
    TypeError: 'Logger' object is not callable
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 962, in send_error
        self.finish()
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 389, in _disallow_for_websocket
        method(self, *args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 936, in finish
        self._log()
    TypeError: 'Logger' object is not callable
```

**Comment by sunlizhe** [comment]
it runs good on my local laptop .
ipthon version 4.1.1
jupyter --version 4.0.6


when I use jupyter  behind a Nginx Proxy I found( when i click to create a Terminal on the jupter web pages)  it does not work well, and here the exceptions log

how can i fix it 
```
[E 07:15:01.635 NotebookApp] Uncaught exception GET /terminals/websocket/1 (10.131.16.58)
    HTTPServerRequest(protocol='http', host='jupyter.hadoop.heracles.creditease.corp', method='GET', uri='/terminals/websocket/1', version='HTTP/1.0', remote_ip='10.131.16.58', headers={'Origin': 'http://jupyter.hadoop.heracles.creditease.corp', 'Accept-Language': 'en,zh-CN;q=0.8,zh;q=0.6,zh-TW;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'X-Forwarded-For': '10.106.0.111', 'Sec-Websocket-Version': '13', 'Host': 'jupyter.hadoop.heracles.creditease.corp', 'Sec-Websocket-Key': 'XGLpJ5YvwOGFYnQfX6J5Vg==', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36', 'Connection': 'close', 'Cookie': 'lzstat_uv=12308132433337636819|3371939', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'X-Real-Ip': '10.106.0.111', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits'})
    Traceback (most recent call last):
      File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1603, in wrapper
        result = method(self, *args, **kwargs)
      File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/websocket.py", line 148, in get
        self.finish(log_msg)
      File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/websocket.py", line 391, in _disallow_for_websocket
        method(self, *args, **kwargs)
      File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 934, in finish
        self._log()
    TypeError: 'Logger' object is not callable
[E 07:15:01.636 NotebookApp] Cannot send error response after headers written
[E 07:15:01.637 NotebookApp] Failed to flush partial response
    Traceback (most recent call last):
      File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 960, in send_error
        self.finish()
      File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/websocket.py", line 391, in _disallow_for_websocket
        method(self, *args, **kwargs)
      File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 934, in finish
        self._log()
    TypeError: 'Logger' object is not callable
```

**Comment by takluyver** [comment]
What does `jupyter notebook --version` give you? If it's less than 4.1, upgrade.

**Comment by sunlizhe** [comment]
`jupyter notebook --version`  do returns 4.1, this problem occured  when jupyter behind a nginx proxy  only.
It runs good on my local computer.

**Comment by minrk** [comment]
cc @rgbkrk for nginx ideas. Can you think of any configuration that might be missing?

@sunlizhe can you share your nginx version and relevant nginx config?

**Comment by sunlizhe** [comment]
user  nginx nginx;

worker_processes 4;
worker_rlimit_nofile 65535; 
error_log  /opt/yrd_logs/nginx/error.log notice;
pid        /var/run/nginx.pid;
events {
    use epoll;
    worker_connections  51200;
}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format main '[$time_local] $remote_addr $server_name "$request" $status $request_length $body_bytes_sent $request_time $upstream_response_time $upstream_addr $connection "$http_user_agent"';
    access_log  /dev/null;
    keepalive_timeout  600;
    server_names_hash_bucket_size 128;
    client_header_buffer_size 128k;
    large_client_header_buffers 4 256k;
    client_header_timeout  10m;
    client_body_timeout    10m;
    send_timeout           10m;
    sendfile                on;
    tcp_nopush     on;
    tcp_nodelay    on;
    client_max_body_size 50m;
    client_body_buffer_size 50m;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;
    proxy_read_timeout 600;
    proxy_buffer_size 4k;
    proxy_buffers 8 32k;
    proxy_busy_buffers_size 64k;
    proxy_temp_file_write_size 64k;
    proxy_temp_path  /dev/shm/proxy_temp;
    fastcgi_temp_path  /dev/shm/fastcgi_temp;
    client_body_temp_path  /dev/shm/client_body_temp;
    gzip on;
    gzip_min_length 1k;
    gzip_buffers     4 16k;
    gzip_comp_level 2;
    gzip_http_version 1.1;
    gzip_types text/plain application/x-javascript text/css application/xml;
    gzip_vary on;
    server {
        listen *:80 default;
        server_name _ "";
        return 444;
        access_log   off;
    }
    include /etc/nginx/conf.d/*.conf;
}

server
      {
    listen  80;
    server_name  jupyter.hadoop.heracles.creditease.corp;
    charset utf-8;
    access_log /opt/yrd_logs/nginx/jupyter_hadoop_heracles_creditease_access.log main;
    error_log  /opt/yrd_logs/nginx/jupyter_hadoop_heracles_creditease_error.log;
    root /opt/yrd_web;
    index index.html;

           location /  {
                       proxy_pass        http://jupyter_hadoop_heracles;
                       proxy_set_header   Host             $host;
                       proxy_set_header   X-Real-IP        $remote_addr;
                       proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
                       add_header Access-Control-Allow-Origin *;
                       add_header Access-Control-Allow-Headers X-Requested-With;
                       add_header Access-Control-Allow-Methods GET,POST,OPTIONS;

                       client_max_body_size 100m;
              }

          error_page  500 502 503 504  /50x.html;
          location = /50x.html {
            root   html/err;
          }
      }
upstream jupyter_hadoop_heracles {
    server 10.130.81.183:8889;
    }





nginx version: nginx/1.8.0

**Comment by sunlizhe** [comment]
on the website of jupter notebook I found the following description

'To function correctly, the firewall on the computer running the jupyter notebook server must be configured to allow connections from client machines on the access port c.NotebookApp.port set in :file:jupyter_notebook_config.py port to allow connections to the web interface. The firewall must also allow connections from 127.0.0.1 (localhost) on ports from 49152 to 65535. These ports are used by the server to communicate with the notebook kernels. The kernel communication ports are chosen randomly by ZeroMQ, and may require multiple connections per kernel, so a large range of ports must be accessible'

does it means  there is a ZeroMQ client (mybe base javascript ) need connections the jupyter notebook server via posts from 49152 to 65535 when using 'New--- Terminal' function on the web page side ? so its may be the reason of this problem?

**Comment by minrk** [comment]
No, by the time it gets to nginx, this is just http over a single port. The ZeroMQ stuff is between the server and its kernels.
