### ISSUE TITLE
Remote Notebook Server - Permission Denied

### ISSUE THREAD

**Issue by chrishagel** [jupyter/notebook#4324]
Hi, 

I set up a remote Jupyter Lab server following these instructions: 
https://www.blopig.com/blog/2018/03/running-jupyter-notebook-on-a-remote-server-via-ssh/

I can connect to the remote server via my local browser without issue. However, there is a specific instance where I am unable to *save or create new files*. In particular: 

- If I serve the notebook from the remote's "native" file system (e.g. $HOME, $HOME/test-folder/, etc), Jupyter Lab notebooks perform as expected when accessed via my local browser - I can save files and create new files.

- If, however, I serve the notebook from an "external" filesystem mounted to the remote (e.g. /media/test_folder), then I am not able to save or create new files when accessing the notebook from my local browser. For instance, when I try to create a new .txt file, I receive the following error: "403 POST /api/contents/?1546904638133 (127.0.0.1): Permission denied: untitled.txt"

Any idea what might be happening here?

I have searched and found what looks to be a related, albeit dated issue: https://github.com/jupyter/notebook/issues/605

*Remote*
Headless Ubuntu EC2 on AWS
Serving from a Conda environment with the following Jupyter packages installed:
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterlab==0.35.3
jupyterlab-server==0.2.0

Happy to provide additional information. Thanks, 

Chris

**Comment by buchholzmd** [comment]
Hey Chris, what was your solution for this?
