### ISSUE TITLE
Map kernel id/session id to notebook path

### ISSUE THREAD

**Issue by vilhelmen** [jupyter/notebook#4325]
I see a lot of information about getting the current notebook name from inside the notebook, but is there a way to figure out what file is being handled by a kernel given the kernel id or session id?

Let's say, hypothetically, you had injected yourself into `ZMQChannelsHandler._on_zmq_reply` and wanted to get some basic analytics. You can count cell executions, but it's not clear how you can resolve that execution to a notebook name; the ZMQ message only has kernel/session identifiers.

While poking through the `kernel_manager`, I realized the kernel probably doesn't have a concept of notebooks, so maybe the session is the way to go? I'm not sure if this session identifier is a ZMQ id or a notebook session id.

I'm not really concerned with the fragility of a solution, but I'd like it to be something that doesn't add too much of a burden on the message processor.

**Comment by vilhelmen** [comment]
With some more poking (4% battery left!) it seems I've found it. You can retrieve the session data from inside `ZMQChannelsHandler` via `self.session_manager.get_session(kernel_id=self.kernel_id)` which will look something like this:

```
{'id': 'dfdd7bf6-77aa-4605-a573-76abcc9c7b4a',
'path': 'Untitled1.ipynb',
'name': '',
'type': 'notebook',
'kernel': {'id': '487d1a4d-9d85-4247-83e6-794ae220905f', 'name': 'python3', 'last_activity': '2019-01-08T00:47:03.266596Z', 'execution_state': 'busy', 'connections': 1},
'notebook': {'path': 'Untitled1.ipynb', 'name': ''}}
```

Unless someone has a better solution, this can probably be considered closed.

**Comment by namrathakolli** [comment]
hi. I am trying to get the session id from the jupyter notebook. Using the above solution we get the session data but session id is not available. Could you please help?

**Comment by vilhelmen** [comment]
Is the session id not the `id` field returned from `self.session_manager.get_session(kernel_id=self.kernel_id)`?

**Comment by namrathakolli** [comment]
it is not the session id. we compared it with the session id in websocket request. the url for the websocket request has the session id. we are not able to get the session id from the juoyter notebook. please help.

**Comment by vilhelmen** [comment]
I'd question if the websocket ids are the same as the kernel session ids, my intuition says there's most likely a mapping as you can have multiple browser connections to the same notebook kernel.

the most interesting sounding results for `websocket` in the codebase are `./notebook/base/zmqhandlers.py` and `./notebook/gateway/handlers.py`.

You may want to look at `ZMQStreamHandler._on_zmq_reply` in the ZMQ handler.

`WebSocketChannelsHandler.on_message`, `WebSocketChannelsHandler._get_message_summary`, and `GatewayWebSocketClient._read_messages` are the most interesting sounding functions in the gateway handlers.

I usually work on jupyterhub so I don't think I can help much more, I'm not familiar with the notebook code. That should be a good start, though. There has to be a connection between those classes and the kernel handlers somewhere.
