### ISSUE TITLE
Cannot import aplpy

### ISSUE THREAD

**Issue by zlashie** [jupyter/notebook#4330]
Hello,

When I try to import aplpy as apl in Jupyter notebook I get

```
C:\ProgramData\Anaconda3\lib\site-packages\mpl_toolkits\axes_grid\__init__.py:12: MatplotlibDeprecationWarning: 
The mpl_toolkits.axes_grid module was deprecated in Matplotlib 2.1 and will be removed two minor releases later. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist, which provide the same functionality instead.
  obj_type='module')"
```

I have tried to manually install aplpy but it has not resolved the issue.
Any ideas?

**Comment by takluyver** [comment]
That looks like a warning, not an error, so it shouldn't prevent you using aplpy. If you want to get rid of the warning, talk to the aplpy maintainers (they may already have done it, I don't know).
