### ISSUE TITLE
Please backport optimization for large file uploads to 5.7.x

### ISSUE THREAD

**Issue by salekseev** [jupyter/notebook#4333]
Please backport https://github.com/jupyter/notebook/pull/4248 to 5.7.x

Do you know how we could get this packaged into a minor version release? My team would like to use this change but would also like to avoid forking jupyter/notebook internally if possible.

**Comment by takluyver** [comment]
Sorry, the point of patch releases is that they only include important bugfixes. Hopefully we'll get round to a new major release some time soon.
