### ISSUE TITLE
Opera browser: Access to the file was denied after starting

### ISSUE THREAD

**Issue by aakhmetz** [jupyter/notebook#4353]
When starting the notebook in Opera from the terminal, it gives me the message:
```
Access to the file was denied
The file at file:///run/user/1000/jupyter/nbserver-6407-open.html is not readable. 
It may have been removed, moved, or file permissions may be preventing access.

ERR_ACCESS_DENIED
```
so I have to copy the link from the terminal with a token.

It looks like it's Opera-linux-specific for me, because I haven't experienced this error anywhere else.

**Comment by McCoyBecker** [comment]
I have the same issue with Chrome. Must copy the link from the terminal.

**Comment by dzhoshkun** [comment]
Same here with Chromium. Works only with the `http://localhost:8888/?token=XXXXXXXXXXXXX` link

**Comment by kfrncs** [comment]
Same, Firefox on fresh Ubuntu install

**Comment by kfrncs** [comment]
Solution here:
https://github.com/jupyter/notebook/issues/4500

**Comment by RolandAckerl** [comment]
After playing around for almost a year, I was finally able to find a solution for Ubuntu 18.10 and Chromium/Chrome (should also work with Opera etc):

Usually this only happens if the browser was installed by snap or the software center. They are installed differently.
Solution:
Deinstall your browser and install it manualy, eg Chrome:
open terminal
`wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`
`sudo dpkg -i google-chrome-stable_current_amd64.deb`

Please do not play around with different notebook versions or even worse: don't open all doors with chmod!

**Comment by kosii** [comment]
Setting `c.NotebookApp.use_redirect_file = False` solved this issue for me (https://stackoverflow.com/questions/59096651/change-startup-url-in-jupyter-notebook/59578946#59578946)

**Comment by lcmuniz** [comment]
I followed the following steps:
- I created the configuration file: `jupyter notebook --generate-config`
- I edited the file `vi ~ / .jupyter / jupyter_notebook_config.py`
- I uncommented the line below and changed it from True to False:
 Before: `# c.NotebookApp.use_redirect_file = True`
After: `c.NotebookApp.use_redirect_file = False`

**Comment by diegogarromolina** [comment]
Excelent!! I have installed Opera Browser via Snap in Manjaro Linux and the solution by @lcmuniz worked for me. Thanks.

**Comment by ABD-01** [comment]
The solution by @lcmuniz is perfect.

Thanks a lot. :raised_hands:

**Comment by bhmit** [comment]
> After playing around for almost a year, I was finally able to find a solution for Ubuntu 18.10 and Chromium/Chrome (should also work with Opera etc):
> 
> Usually this only happens if the browser was installed by snap or the software center. They are installed differently.
> Solution:
> Deinstall your browser and install it manualy, eg Chrome:
> open terminal
> `wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`
> `sudo dpkg -i google-chrome-stable_current_amd64.deb`
> 
> Please do not play around with different notebook versions or even worse: don't open all doors with chmod!

thank work for me

**Comment by saugatach** [comment]
This happened to me after an OS upgrade. Clean reinstall of JupyterLab worked for me.
`jupyter lab clean --all
pip3 install jupyterlab --force-reinstall`
