### ISSUE TITLE
Dark Theme plots renders camouflage axes

### ISSUE THREAD

**Issue by ekeleshian** [jupyter/notebook#4358]
This is what I mean. The axes are super hard to read. Would like to continue working with this theme, but the camouflaged axes makes it a discouraging experience.  This is probably a minor CSS fix, but I figured posting this can be beneficial for users who are fans of the dark theme. 

![screenshot from 2019-01-21 09-12-30](https://user-images.githubusercontent.com/33647474/51489288-b4dba100-1d5c-11e9-8efe-3a47246b56a1.png)

**Comment by ekeleshian** [comment]
I had version 4.8.6.  I upgraded to 5.1.0, restarted jupyter lab, but still renders illegible axes.

**Comment by ian-r-rose** [comment]
What version of JupyterLab are you using? I have legible axes with JupyterLab 0.35 and ipykernel 5.

**Comment by ekeleshian** [comment]
@ian-r-rose, OK just upgraded jupyter lab as well,and it works now. looks fantastic. thanks for the help!

**Comment by ian-r-rose** [comment]
Glad you got it working! Closing as fixed.

**Comment by A-Fisk** [comment]
I'm looking for some help with the same issue, first time raising an issue so not sure if best to comment here on an closed issue or open a new one. 

I'm still getting this issue with jupyter lab version 0.35 and 1.0.2, and ipykernel 5.1.1 installed. Any suggestions?
