### ISSUE TITLE
Quoted text in an f-string expression breaks the syntax highlighting

### ISSUE THREAD

**Issue by jadczak** [jupyter/notebook#4360]
Trying to put quoted text in an f-string expression breaks the syntax highlighting.
`print(f"{'test'}") # this will break the syntax highlighting.`

Here's an image of a notebook on Chome.
![image](https://user-images.githubusercontent.com/11022442/51558249-fc415a80-1e4c-11e9-9ef2-edc45e13429a.png)

Google Chrome Version: 71.0.3578.98 (Official Build) (64-bit)
Firefox Version: 65.0b12 (64-bit)
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
Notebook Server: 5.7.4

Conda list follows:

Name|Version|Build
----|-------|-----
_ipyw_jlab_nb_ext_conf|0.1.0|py37_0
alabaster|0.7.12|py37_0
anaconda|2018.12|py37_0
anaconda-client|1.7.2|py37_0
anaconda-navigator|1.8.7|py37_0
anaconda-project|0.8.2|py37_0
appdirs|1.4.3|pip
appdirs|1.4.3|py37h28b3542_0
asn1crypto|0.24.0|py37_0
astroid|2.1.0|py37_0
astropy|3.1|py37he774522_0
atomicwrites|1.2.1|py37_0
attrs|18.2.0|py37h28b3542_0
automat|0.7.0|py37_0
babel|2.6.0|py37_0
backcall|0.1.0|py37_0
backports|1.0|py37_1
backports.os|0.1.1|py37_0
backports.shutil_get_terminal_size|1.0.0|py37_2
beautifulsoup4|4.6.3|py37_0
bitarray|0.8.3|py37hfa6e2cd_0
bkcharts|0.2|py37_0
black|18.9b0|pip
blas|1.0|mkl
blaze|0.11.3|py37_0
bleach|3.0.2|py37_0
blosc|1.14.4|he51fdeb_0
bokeh|1.0.2|py37_0
boto|2.49.0|py37_0
bottleneck|1.2.1|py37h452e1ab_1
bzip2|1.0.6|hfa6e2cd_5
ca-certificates|2018.03.07|0
certifi|2018.11.29|py37_0
cffi|1.11.5|py37h74b6da3_1
chardet|3.0.4|py37_1
click|7.0|py37_0
cloudpickle|0.6.1|py37_0
clyent|1.2.2|py37_1
code128|0.3|pip
colorama|0.4.1|py37_0
comtypes|1.1.7|py37_0
conda|4.5.12|py37_0
conda-build|3.16.2|py37_0
conda-env|2.6.0|h36134e3_1
conda-verify|3.1.1|py37_0
console_shortcut|0.1.1|3
constantly|15.1.0|py37h28b3542_0
contextlib2|0.5.5|py37_0
coverage|4.5.2|py37he774522_0
cryptography|2.4.2|py37h7a1dbc1_0
curl|7.63.0|h2a8f88b_1000
cx-Freeze|5.1.1|pip
cycler|0.10.0|py37_0
cython|0.29.2|py37ha925a31_0
cytoolz|0.9.0.1|py37hfa6e2cd_1
dask|1.0.0|py37_0
dask-core|1.0.0|py37_0
datashape|0.5.4|py37_1
decorator|4.3.0|py37_0
defusedxml|0.5.0|py37_1
distributed|1.25.1|py37_0
docutils|0.14|py37_0
entrypoints|0.2.3|py37_2
et_xmlfile|1.0.1|py37_0
fastcache|1.0.2|py37hfa6e2cd_2
filelock|3.0.10|py37_0
flask|1.0.2|py37_1
flask-cors|3.0.7|py37_0
freetype|2.9.1|ha9979f8_1
future|0.17.1|py37_0
get_terminal_size|1.0.0|h38e98db_0
gevent|1.3.7|py37he774522_1
glob2|0.6|py37_1
greenlet|0.4.15|py37hfa6e2cd_0
h5py|2.8.0|py37h3bdd7fb_2
hdf5|1.10.2|hac2f561_1
heapdict|1.0.0|py37_2
html5lib|1.0.1|py37_0
hyperlink|18.0.0|py37_0
icc_rt|2019.0.0|h0cc432a_1
icu|58.2|ha66f8fd_1
idna|2.8|py37_0
imageio|2.4.1|py37_0
imagesize|1.1.0|py37_0
importlib_metadata|0.6|py37_0
incremental|17.5.0|py37_0
intel-openmp|2019.1|144
ipykernel|5.1.0|py37h39e3cac_0
ipython|7.2.0|py37h39e3cac_0
ipython_genutils|0.2.0|py37_0
ipywidgets|7.4.2|py37_0
isort|4.3.4|py37_0
itsdangerous|1.1.0|py37_0
jdcal|1.4|py37_0
jedi|0.13.2|py37_0
jinja2|2.10|py37_0
jpeg|9b|hb83a4c4_2
jsonschema|2.6.0|py37_0
jupyter|1.0.0|py37_7
jupyter_client|5.2.4|py37_0
jupyter_console|6.0.0|py37_0
jupyter_core|4.4.0|py37_0
jupyterlab|0.35.3|py37_0
jupyterlab_launcher|0.13.1|py37_0
jupyterlab_server|0.2.0|py37_0
keyring|17.0.0|py37_0
kiwisolver|1.0.1|py37h6538335_0
krb5|1.16.1|hc04afaa_7
lazy-object-proxy|1.3.1|py37hfa6e2cd_2
libarchive|3.3.3|h0643e63_5
libcurl|7.63.0|h2a8f88b_1000
libiconv|1.15|h1df5818_7
libpng|1.6.35|h2a8f88b_0
libsodium|1.0.16|h9d3ae62_0
libssh2|1.8.0|h7a1dbc1_4
libtiff|4.0.9|h36446d0_2
libxml2|2.9.8|hadb2253_1
libxslt|1.1.32|hf6f1972_0
llvmlite|0.26.0|py37ha925a31_0
locket|0.2.0|py37_1
lxml|4.2.5|py37hef2cd61_0
lz4-c|1.8.1.2|h2fa13f4_0
lzo|2.10|h6df0209_2
m2w64-gcc-libgfortran|5.3.0|6
m2w64-gcc-libs|5.3.0|7
m2w64-gcc-libs-core|5.3.0|7
m2w64-gmp|6.1.0|2
m2w64-libwinpthread-git|5.0.0.4634.697f757|2
markupsafe|1.1.0|py37he774522_0
matplotlib|3.0.2|py37hc8f65d3_0
mccabe|0.6.1|py37_1
menuinst|1.4.14|py37hfa6e2cd_0
mistune|0.8.4|py37he774522_0
mkl|2019.1|144
mkl-service|1.1.2|py37hb782905_5
mkl_fft|1.0.6|py37h6288b17_0
mkl_random|1.0.2|py37h343c172_0
more-itertools|4.3.0|py37_0
mpmath|1.1.0|py37_0
msgpack-python|0.5.6|py37he980bc4_1
msys2-conda-epoch|20160418|1
multipledispatch|0.6.0|py37_0
navigator-updater|0.2.1|py37_0
nbconvert|5.4.0|py37_1
nbformat|4.4.0|py37_0
networkx|2.2|py37_1
nltk|3.4|py37_1
nodejs|8.9.3|hd6b2f15_0
nose|1.3.7|py37_2
notebook|5.7.4|py37_0
numba|0.41.0|py37hf9181ef_0
numexpr|2.6.8|py37hdce8814_0
numpy|1.15.4|py37h19fb1c0_0
numpy-base|1.15.4|py37hc3f5095_0
numpydoc|0.8.0|py37_0
odo|0.5.1|py37_0
olefile|0.46|py37_0
openpyxl|2.5.12|py37_0
openssl|1.1.1a|he774522_0
packaging|18.0|py37_0
pandas|0.23.4|py37h830ac7b_0
pandoc|1.19.2.1|hb2460c7_1
pandocfilters|1.4.2|py37_1
parso|0.3.1|py37_0
partd|0.3.9|py37_0
path.py|11.5.0|py37_0
pathlib2|2.3.3|py37_0
patsy|0.5.1|py37_0
pep8|1.7.1|py37_0
pickleshare|0.7.5|py37_0
pillow|5.3.0|py37hdc69c19_0
pip|18.1|py37_0
pkginfo|1.4.2|py37_1
pluggy|0.8.0|py37_0
ply|3.11|py37_0
prometheus_client|0.5.0|py37_0
prompt_toolkit|2.0.7|py37_0
psutil|5.4.8|py37he774522_0
py|1.7.0|py37_0
pyasn1|0.4.4|py37h28b3542_0
pyasn1-modules|0.2.2|py37_0
pycodestyle|2.4.0|py37_0
pycosat|0.6.3|py37hfa6e2cd_0
pycparser|2.19|py37_0
pycrypto|2.6.1|py37hfa6e2cd_9
pycurl|7.43.0.2|py37h7a1dbc1_0
pyflakes|2.0.0|py37_0
pygments|2.3.1|py37_0
pyhamcrest|1.9.0|py37_2
pylint|2.2.2|py37_0
pyodbc|4.0.25|py37ha925a31_0
pyopenssl|18.0.0|py37_0
pyparsing|2.3.0|py37_0
pyqt|5.9.2|py37h6538335_2
pyreadline|2.1|pip
pysocks|1.6.8|py37_0
pytables|3.4.4|py37he6f6034_0
pytest|4.0.2|py37_0
pytest-arraydiff|0.3|py37h39e3cac_0
pytest-astropy|0.5.0|py37_0
pytest-doctestplus|0.2.0|py37_0
pytest-openfiles|0.3.1|py37_0
pytest-remotedata|0.3.1|py37_0
python|3.7.1|h8c8aaf0_6
python-barcode|0.9.0|pip
python-dateutil|2.7.5|py37_0
python-libarchive-c|2.8|py37_6
pytz|2018.7|py37_0
pywavelets|1.0.1|py37h8c2d366_0
pywin32|223|py37hfa6e2cd_1
pywinpty|0.5.5|py37_1000
pyyaml|3.13|py37hfa6e2cd_0
pyzmq|17.1.2|py37hfa6e2cd_0
qt|5.9.7|vc14h73c81de_0
qtawesome|0.5.3|py37_0
qtconsole|4.4.3|py37_0
qtpy|1.5.2|py37_0
reportlab|3.5.10|py37h3e46f66_0
requests|2.21.0|py37_0
rope|0.11.0|py37_0
ruamel_yaml|0.15.46|py37hfa6e2cd_0
scikit-image|0.14.1|py37ha925a31_0
scikit-learn|0.20.1|py37h343c172_0
scipy|1.1.0|py37h29ff71c_2
seaborn|0.9.0|py37_0
send2trash|1.5.0|py37_0
service_identity|17.0.0|py37h28b3542_0
setuptools|40.6.3|py37_0
simplegeneric|0.8.1|py37_2
singledispatch|3.4.0.3|py37_0
sip|4.19.8|py37h6538335_0
six|1.12.0|py37_0
snappy|1.1.7|h777316e_3
snowballstemmer|1.2.1|py37_0
sortedcollections|1.0.1|py37_0
sortedcontainers|2.1.0|py37_0
sphinx|1.8.2|py37_0
sphinxcontrib|1.0|py37_1
sphinxcontrib-websupport|1.1.0|py37_1
spyder|3.3.2|py37_0
spyder-kernels|0.3.0|py37_0
sqlalchemy|1.2.15|py37he774522_0
sqlite|3.26.0|he774522_0
statsmodels|0.9.0|py37h452e1ab_0
sympy|1.3|py37_0
tblib|1.3.2|py37_0
terminado|0.8.1|py37_1
testpath|0.4.2|py37_0
tk|8.6.8|hfa6e2cd_0
toml|0.9.4|pip
toolz|0.9.0|py37_0
tornado|5.1.1|py37hfa6e2cd_0
tqdm|4.28.1|py37h28b3542_0
traitlets|4.3.2|py37_0
twisted|18.9.0|py37he774522_0
typed-ast|1.1.0|py37hfa6e2cd_0
typing|3.6.4|py37_0
unicodecsv|0.14.1|py37_0
urllib3|1.24.1|py37_0
vc|14.1|h0510ff6_4
vs2015_runtime|14.15.26706|h3a45250_0
wcwidth|0.1.7|py37_0
webencodings|0.5.1|py37_1
werkzeug|0.14.1|py37_0
wheel|0.32.3|py37_0
widgetsnbextension|3.4.2|py37_0
win_inet_pton|1.0.1|py37_1
win_unicode_console|0.5|py37_0
wincertstore|0.2|py37_0
winpty|0.4.3|4
wrapt|1.10.11|py37hfa6e2cd_2
xlrd|1.2.0|py37_0
xlsxwriter|1.1.2|py37_0
xlwings|0.15.1|py37_0
xlwt|1.3.0|py37_0
xz|5.2.4|h2fa13f4_4
yaml|0.1.7|hc54c509_2
zeromq|4.2.5|he025d50_1
zict|0.1.3|py37_0
zlib|1.2.11|h62dcd97_3
zope|1.0|py37_1
zope.interface|4.6.0|py37he774522_0
zstd|1.3.7|h508b16e_0

**Comment by kinpell** [comment]
Still nothing ? i have the same problem with this version of jupiter

**Comment by lemeb** [comment]
same here... :(

 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/7331643/55663872-b57bc380-57f2-11e9-9a6c-c13fefcd6c05.png">

thanks for all the good work though :)

**Comment by dz902** [comment]
Same here with 4.4.0, I believe this is a bug from CodeMirror the underlying editor though. Can only wait for an official update.

**Comment by JoranDox** [comment]
Same here, just wanted to link to https://github.com/jupyter/notebook/issues/2358 since that was the first thing to come up when I googled, and it would've been nice to have found this when looking through that.

**Comment by mOmUcf** [comment]
same here with 5.7.8.
notebook&jupyter are updated but nothing changes.

**Comment by JMBurley** [comment]
Ditto.  It is **very** annoying and far more than a cosmetic issue.

The indenting will persist for the rest of the cell, regardless of other local context. Fixing the indents wastes a lot of time / keypresses.

**Comment by jeanmonet** [comment]
I have the same issue with latest updates available as at the current date. (Quite frustrating)

**Comment by akdor1154** [comment]
this is fixed in `notebook` 6.0.2.

**Comment by JMBurley** [comment]
see: https://jupyter-notebook.readthedocs.io/en/stable/changelog.html

- Update CodeMirror to version 5.48.4 to fix Python formatting issues

**Comment by rthiyagarajan** [comment]
Same f-string syntax highlighting issue is occurring for me on notebook=6.03 on python =3.8
Found a version that doesn't have this issue: notebook=6.0.0 on python=3.7

**Comment by JMBurley** [comment]
I believe this issue can be closed.  Resolved as per the logs and issues I linked previously.
