### ISSUE TITLE
inaccurate translation

### ISSUE THREAD

**Issue by liyinan1001** [jupyter/notebook#4362]
https://github.com/jupyter/notebook/blob/7ded6383572b7bb4ae095c9bbeb3a6a0e0e060fd/notebook/i18n/zh_CN/LC_MESSAGES/nbjs.po#L1039

"木有连接成功"： “木有” should be “没有”

**Comment by takluyver** [comment]
Closed by #4367.

**Comment by berlala** [comment]
To say the truth this should not be a problem. 
Kind of joke in Chinese. ^_^
