### ISSUE TITLE
missing paragraph breaks in text/markdown display

### ISSUE THREAD

**Issue by stevengj** [jupyter/notebook#438]
Since IPython 3, the notebook has supported display of `text/markdown` data in mimebundles (ipython/ipython#4756).  However, I've noticed (in IPython 3.2) that it seems to be mis-rendering paragraph breaks.

If I put the following in a markdown cell in the notebook, it renders properly:
```
Some *markdown* text.

Another paragraph
```
is rendered as
![image](https://cloud.githubusercontent.com/assets/2913679/9894925/8417b38a-5bf7-11e5-9973-41797ab9e6da.png)

However, if I send the same text as `text/markdown` data in the mimebundle of a `display_data` message (via IJulia), it doesn't include a blank line for the paragraph break:
![image](https://cloud.githubusercontent.com/assets/2913679/9894957/cc10e3b4-5bf7-11e5-95e4-a160a464ecf4.png)

I've verified that the JSON message that is sent indeed contains the double newline: `"data":{"text/markdown":"Some *markdown* text.\n\nAnother paragraph.\n"}`

**Comment by Carreau** [comment]
Marking as 4.1 thanks for the report and detailed analysis.

**Comment by ellisonbg** [comment]
Thanks!

On Tue, Sep 15, 2015 at 8:02 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Marking as 4.1 thanks for the report and detailed analysis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/438#issuecomment-140611305>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
And double-bonus, already fixed:

IPython 3:

![screen shot 2015-09-16 at 10 51 29](https://cloud.githubusercontent.com/assets/151929/9900424/01110eb8-5c61-11e5-8cac-c5f20549b44b.PNG)

Notebook 4.1-dev:

![screen shot 2015-09-16 at 10 51 51](https://cloud.githubusercontent.com/assets/151929/9900429/0981a6e8-5c61-11e5-9b87-121f17095ff9.PNG)

**Comment by stevengj** [comment]
Thanks for looking into this.
