### ISSUE TITLE
Use nbdime as default diff tool for Jupyter Notebook on Github

### ISSUE THREAD

**Issue by odysseus0** [jupyter/notebook#4395]
I know that this is not really an issue but I feel that this is probably still the best place to voice it. As we all know now, `nbdime` is the best diff tool out there when doing version control on Jupyter Notebook. As a matter of fact, the generic `diff` really does not work with Jupyter Notebook. Currently, Github still uses line-by-line `diff` when viewing file change on Jupyter Notebook, which makes collaboration really hard.

I just opened a [post](https://github.community/t5/GitHub-API-Development-and/Use-nbdime-as-diff-tool-for-Jupyter-Notebook/m-p/18725#M858) on Github Community Forum to request using `nbdime` as the default `diff` tool when working with Jupyter Notebook. Please support it if you want to make it a reality soon.

Here is the link: https://github.community/t5/GitHub-API-Development-and/Use-nbdime-as-diff-tool-for-Jupyter-Notebook/m-p/18725#M858

**Comment by jtpio** [comment]
Closing as this is now available: https://github.blog/changelog/2023-03-01-feature-preview-rich-jupyter-notebook-diffs/

Thanks!
