### ISSUE TITLE
Restart & run all should not go through dialog.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#440]
Restart and run all menu item go through the dialog that ask you wether you really want to and if you want to clear all cells. 

Which is no coherent. 

Either make it skip confirmation, or just make the "run all" another button on the restart dialog.

**Comment by minrk** [comment]
This was me being lazy, sorry. Since it is a restart, I think it does need confirmation just like other restarts. Instead of skipping, I think alternative to making it a button is giving it its own dialog.

**Comment by minrk** [comment]
Should be improved in #465
