### ISSUE TITLE
Jupyter Notebook never becomes ready to execute cell

### ISSUE THREAD

**Issue by dallasssimpson** [jupyter/notebook#4441]
Starting today 3/1/2018 I started receiving the following error in the logs generated by `/bin/bash -c jupyter lab &> /tmp/jupyterlab`.

I found:
```Exception in callback <bound method WebSocketMixin.send_ ping of <notebook.terminal.handlers.TermSocket object at 0x7f5d24576668>> Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 907, in _run return self.callback() File "/usr/local/lib/python3.5/dist-packages/notebook/base/zmqhandlers.py" , line 175, in send_ping if self.stream.closed() and self.ping_callback is not None: AttributeError: 'NoneType' object has no attribute 'closed'```

Tornado released a new version today that seems to break things.

Downgrading Tornado from 6.0 to 5.1.1 and restarting Jupyter seems to resolve the issue.

**Comment by audy** [comment]
Same. [This](https://github.com/jupyter/notebook/commit/9035cb1bdd2fe6c8195912f67d232ed77da0f6c0) appears to fix it but it has not been released yet. Tag?

**Comment by davesque** [comment]
Same issue.

**Comment by C0NTRIBUTE** [comment]
Same issue.

**Comment by jasongrout** [comment]
See also #4399 for tornado 6 issues.

**Comment by dazzag24** [comment]
Same issue here. Both jupyter-lab and notebook were broken until I downgraded tornado from 6.0.0. to 5.1.1

**Comment by jasongrout** [comment]
My guess is this is the incompatibility with tornado 6 a lot of people have been experiencing. See https://github.com/jupyter/notebook/issues/4439 and https://github.com/jupyter/notebook/pull/4449. The solution would be either upgrading notebook to version 5.7.5, or downgrading tornado to version 5.1.1.

**Comment by minrk** [comment]
Yup, this is fixed in notebook 5.7.5
