### ISSUE TITLE
Kernel not connected Python 3.7

### ISSUE THREAD

**Issue by wbadry** [jupyter/notebook#4444]
Hello,
I installed Jupyter before with no problems. Is there any issue with **version 3.7.2** ?

When I try to start Jupyter notebook, it seems it doesn't connect at all although Jupyter notebook is launched on the browser. 

```
PS D:\> jupyter notebook
[I 04:59:04.211 NotebookApp] Serving notebooks from local directory: D:\
[I 04:59:04.211 NotebookApp] The Jupyter Notebook is running at:
[I 04:59:04.212 NotebookApp] http://localhost:8888/
[I 04:59:04.212 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 04:59:37.369 NotebookApp] Creating new notebook in
[I 04:59:38.929 NotebookApp] Kernel started: 1374b380-c7c8-411c-a197-6694cbca0cca
[I 04:59:39.744 NotebookApp] Adapting to protocol v5.1 for kernel 1374b380-c7c8-411c-a197-6694cbca0cca
c:\python37\lib\site-packages\notebook\base\zmqhandlers.py:284: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited
  super(AuthenticatedZMQStreamHandler, self).get(*args, **kwargs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[W 04:59:40.760 NotebookApp] Replacing stale connection: 1374b380-c7c8-411c-a197-6694cbca0cca:a302d1f529674d60a48751e5a0cbe9c6
[W 05:00:02.820 NotebookApp] Replacing stale connection: 1374b380-c7c8-411c-a197-6694cbca0cca:a302d1f529674d60a48751e5a0cbe9c6
[W 05:00:23.489 NotebookApp] Replacing stale connection: 1374b380-c7c8-411c-a197-6694cbca0cca:a302d1f529674d60a48751e5a0cbe9c6
```

Your help is appreciated. Thanks

**Comment by shimst3r** [comment]
I had the same issue yesterday. I fixed it by deleting `tornado` (was on version `6.0.0`) and installing it manually with `tornado==5.1.1`.

**Comment by JustinYearlen** [comment]
I had the same issue yesterday. I fixed it by deleting tornado (was on version 6.0.0) and installing it manually with tornado==5.1.1.

**Comment by wbadry** [comment]
Thanks, @shimst3r . This was exactly the problem.  I uninstalled tornado and installed version 5.1.1. Thanks a lot

**Comment by jasongrout** [comment]
My guess is this is the incompatibility with tornado 6 a lot of people have been experiencing. See https://github.com/jupyter/notebook/issues/4439 and https://github.com/jupyter/notebook/pull/4449. The solution would be either upgrading notebook to version 5.7.5, or downgrading tornado to version 5.1.1.

**Comment by AnjaniKumari** [comment]
I had the same issue, fixed by installing torando
> pip install "tornado<6"

**Comment by mhogg** [comment]
Again, same issue. Downgrading tornado to version 5.1.1 worked for me.

**Comment by shu2323** [comment]
thinks a lot

**Comment by dikshyam** [comment]
I had the same issue and downgrading tornado worked! Thanks!

**Comment by Jeffokafor** [comment]
please how do i downgrade or install tornado?

**Comment by Shruti-Saini** [comment]
> please how do i downgrade or install tornado?

- Open Anaconda Navigator- IDE
-  Click on Environment menu 
-  Packages will display on the right frame of IDE. Search Tornado
- Click on Tornado checkbox and go to 'Mark for specific version installation' and select version
- Click on Apply button

![image](https://user-images.githubusercontent.com/57751983/76402177-0c95fb00-63a9-11ea-95d9-79bbce9b2eb4.png)

**Comment by Shruti-Saini** [comment]
> please how do i downgrade or install tornado?

can do same via terminal using below command
pip uninstall tornado pip install tornado==5.1.1
