### ISSUE TITLE
"Replacing stale connection" -- Kernal cannot connect

### ISSUE THREAD

**Issue by seanngpack** [jupyter/notebook#4457]
Hi, does anyone have an input on my issue? I am running Jupyter from Anaconda and updated everything to the latest. When I enter the notebook on port 8888 it never connects to the kernel and I cannot run the cells.

I followed every single guide I could read and tried changing ports, deleting adblocks, and downgrading tornado to 5.1.1 but still no luck.

Thanks!

**Comment by jasongrout** [comment]
Can you try upgrading to notebook 5.7.5, just to make sure it's not the tornado incompatibility?

See https://github.com/jupyter/notebook/issues/4439 and https://github.com/jupyter/notebook/pull/4449.

**Comment by seanngpack** [comment]
Thanks! Figured out my issue was that I didn't have notebook installed.

**Comment by seanngpack** [comment]
Oops, false alarm wasn't notebook.
Upgraded notebook to 5.7.5, still issue.
Combinations I've tried:

- Notebook 5.7.5, tornado 6.0.1
- Notebook 5.7.5, tornado 5.1.1
- Notebook 5.7.4 tornados 6.0.1
- Notebook 5.7.4 tornados 5.1.1

**Comment by syagev** [comment]
I got the same issue after downgrading jupyter notebook from 5.7.6 to 5.7.4 due to https://github.com/jupyter/notebook/issues/4467.
Indeed downgrading tornado down to 4.2.0 solved the issue.

**Comment by andrewm4894** [comment]
downgrading to tornado 5.1.1 worked for me.

**Comment by VSehwag** [comment]
Simply downgrading tornado to 4.2.0 worked for me.

**Comment by alvations** [comment]
Just in case, anyone wants to go bleeding edge:

```
 python -m pip install git+https://github.com/jupyter/jupyter_console
 python -m pip install git+https://github.com/jupyter/jupyter_notebook
```

**Comment by tranhungnghiep** [comment]
Upgrading `tornado` to the current version 6.0.4 fixed the issue for me.

**Comment by seshu2169** [comment]
upgraded notebook to 6.0.3 ,issue resolved

**Comment by HeloiseS** [comment]
> downgrading to tornado 5.1.1 worked for me.

This also worked for me - I had the latest tornado version 6.0.4 and the downgrade fixed the pblm

**Comment by pdmptsjtsj** [comment]
I had the same problem when opening bash notebooks (not with python notebooks). Downgrading to different versions of tornado didn't help. Could this problem be related to port access?

**Comment by duongkstn** [comment]
Thanks everyone, I downgraded tornado==5.1.1 to replaced 6.0.3 version, then jupyter (jupyter-notebook==5.6.0, jupyter core==4.6.1) works properly.

**Comment by paultimothymooney** [comment]
Likewise, I was unable to start a new Jupyterlab session because of the "replacing stale connection" error message, but then I fixed the problem by running "pip install tornado==5.1.1" to downgrade from the latest available version.  This thread was helpful for solving that error, thank you.

**Comment by Isayiyas** [comment]
Thank you guys. It worked for me too: tornado==5.1.1 + jupyter notebook 5.6.0 !

**Comment by noklam** [comment]
> Thank you guys. It worked for me too: tornado==5.1.1 + jupyter notebook 5.6.0 !
Whoa, works for me, thanks!

**Comment by swill** [comment]
I am getting this same issue.  Can someone here provide me a little context around what steps you took to change the versions.  I am currently using the `jupyter/all-spark-notebook`, so I am suspecting that you updated the Dockerfile and changed/specified the versions of the packages installed.

I have found the `notebook` version defined in the `base-notebook`.
![image](https://user-images.githubusercontent.com/13644/121956684-6b29f180-cd2f-11eb-98d4-70aac586aa57.png)

However, I can't see tornado installed in any of the ancestors of the `jupyter/all-spark-notebook`:
```
base-notebook  > minimal-notebook > scipy-notebook > pyspark-notebook > all-spark-notebook
```

Any insights are welcome.  Thanks...

**Comment by kevin-bates** [comment]
Hmm.  Given this issue was created over two years ago and doesn't contain any diagnostic output, it might be worth taking a closer look at the error you're experiencing before following downgrade suggestions.

FWIW, I just pulled `jupyter/all-spark-notebook:latest` and can create all 3 of its supplied kernels:
![image](https://user-images.githubusercontent.com/22599560/121966481-9b6b9300-cd23-11eb-82ba-4aa83b3335bc.png)

Are you seeing any traceback information posted on the terminal from which the image was launched?  Could you please provide what you do see?  (Please scrape the screen rather than capturing an image so others can more easily extract information from it - thank you.)

**Comment by kevin-bates** [comment]
Hmm.  I suspect the websocket connection is not getting established.  The output implies the notebook server is being started via Hub.  To reduce interference, are you able to run the image directly using something like the following:
```
docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook
```
then enter the displayed URL beginning with `http://127.0.0.1:8888` in your browser and try to create any of the three kernels?

It might also be helpful to enable debug logging.  One way to do that is to just give the complete command in the `docker run`...
```
docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook jupyter notebook --debug
```

When I run that, I see the following surrounding the 'kernel started' info message:
```
[D 15:29:04.222 NotebookApp] Starting kernel: ['/opt/conda/bin/python', '-m', 'ipykernel_launcher', '-f', '/home/jovyan/.local/share/jupyter/runtime/kernel-ffc8fc81-f4db-4865-a400-cfa86bda9ac3.json']
[D 15:29:04.231 NotebookApp] Connecting to: tcp://127.0.0.1:56767
[D 15:29:04.233 NotebookApp] Connecting to: tcp://127.0.0.1:55243
[I 15:29:04.239 NotebookApp] Kernel started: ffc8fc81-f4db-4865-a400-cfa86bda9ac3, name: python3
[D 15:29:04.239 NotebookApp] Kernel args: {'kernel_name': 'python3', 'cwd': '/home/jovyan'}
[D 15:29:04.244 NotebookApp] Path components/MathJax/extensions/Safe.js served from /opt/conda/lib/python3.9/site-packages/notebook/static/components/MathJax/extensions/Safe.js
[D 15:29:04.246 NotebookApp] 304 GET /static/components/MathJax/extensions/Safe.js?V=2.7.9 (172.17.0.1) 4.350000ms
[D 15:29:04.248 NotebookApp] 201 POST /api/sessions (172.17.0.1) 85.720000ms
[D 15:29:04.477 NotebookApp] Initializing websocket connection /api/kernels/ffc8fc81-f4db-4865-a400-cfa86bda9ac3/channels
[D 15:29:04.480 NotebookApp] Requesting kernel info from ffc8fc81-f4db-4865-a400-cfa86bda9ac3
[D 15:29:04.481 NotebookApp] Connecting to: tcp://127.0.0.1:35863
[D 15:29:04.801 NotebookApp] activity on ffc8fc81-f4db-4865-a400-cfa86bda9ac3: status (starting)
[D 15:29:04.827 NotebookApp] activity on ffc8fc81-f4db-4865-a400-cfa86bda9ac3: status (busy)
[D 15:29:04.828 NotebookApp] activity on ffc8fc81-f4db-4865-a400-cfa86bda9ac3: status (idle)
[D 15:29:04.828 NotebookApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.3', 'implementation': 'ipython', 'implementation_version': '7.24.1', 'language_info': {'name': 'python', 'version': '3.9.4', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33) \nType 'copyright', 'credits' or 'license' for more information\nIPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text': 'Python Reference', 'url': 'https://docs.python.org/3.9'}, {'text': 'IPython Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Reference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'SymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[D 15:29:04.830 NotebookApp] 101 GET /api/kernels/ffc8fc81-f4db-4865-a400-cfa86bda9ac3/channels?session_id=702535f4120a48028439a1ee966393c7 (172.17.0.1) 353.640000ms
[D 15:29:04.830 NotebookApp] Opening websocket /api/kernels/ffc8fc81-f4db-4865-a400-cfa86bda9ac3/channels
[D 15:29:04.831 NotebookApp] Getting buffer for ffc8fc81-f4db-4865-a400-cfa86bda9ac3
[D 15:29:04.832 NotebookApp] Connecting to: tcp://127.0.0.1:55243
[D 15:29:04.833 NotebookApp] Connecting to: tcp://127.0.0.1:35863
[D 15:29:04.836 NotebookApp] Connecting to: tcp://127.0.0.1:56767
[D 15:29:04.838 NotebookApp] Connecting to: tcp://127.0.0.1:39159
[D 15:29:04.840 NotebookApp] Connecting to: tcp://127.0.0.1:35863
[D 15:29:04.842 NotebookApp] Nudge: attempt 1 on kernel ffc8fc81-f4db-4865-a400-cfa86bda9ac3
[D 15:29:04.850 NotebookApp] activity on ffc8fc81-f4db-4865-a400-cfa86bda9ac3: status (busy)
[D 15:29:04.850 NotebookApp] Nudge: IOPub received: ffc8fc81-f4db-4865-a400-cfa86bda9ac3
[D 15:29:04.850 NotebookApp] Nudge: resolving iopub future: ffc8fc81-f4db-4865-a400-cfa86bda9ac3
[D 15:29:04.851 NotebookApp] activity on ffc8fc81-f4db-4865-a400-cfa86bda9ac3: status (idle)
[D 15:29:04.852 NotebookApp] Nudge: shell info reply received: ffc8fc81-f4db-4865-a400-cfa86bda9ac3
[D 15:29:04.852 NotebookApp] Nudge: resolving shell future: ffc8fc81-f4db-4865-a400-cfa86bda9ac3
[D 15:29:04.858 NotebookApp] activity on ffc8fc81-f4db-4865-a400-cfa86bda9ac3: status (busy)
[D 15:29:04.862 NotebookApp] activity on ffc8fc81-f4db-4865-a400-cfa86bda9ac3: status (idle)
[D 15:29:04.866 NotebookApp] activity on ffc8fc81-f4db-4865-a400-cfa86bda9ac3: status (busy)
[D 15:29:04.872 NotebookApp] activity on ffc8fc81-f4db-4865-a400-cfa86bda9ac3: status (idle)
```

It might be helpful to compare this output to yours.

**Comment by swill** [comment]
Thank you, that was the tip I needed.  I upgraded my nginx config to upgrade to use websockets and now it connects and runs as expected.  I appreciate you taking the time to point me in the right direction.  Sorry for polluting this thread.

**Comment by kevin-bates** [comment]
No worries - glad to hear you're moving forward!

I think it might be best to close this issue anyway due to its staleness and lack of details.  It's easy to lump a general error message into the same bucket when it can be any number of things.  In addition, the advice to downgrade relative to one and two-year versions is not prudent today.
