### ISSUE TITLE
Error when starting a new Kernel after a few hours

### ISSUE THREAD

**Issue by MarkusThill** [jupyter/notebook#4478]
Hi, 
I am using Jupyter Notebooks for some Deep Learning tasks. Everything is working fine. So I start Jupyter, work on my notebooks, run them, etc.
However, after a few hours (I do not know after how much time, actually) I cannot start new Kernels (I need Python3 Kernels). I get the following error:

`Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/lib/python3.6/site-packages/jupyter_client/manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "/usr/lib/python3.6/site-packages/jupyter_client/connect.py", line 472, in write_connection_file
    kernel_name=self.kernel_name
  File "/usr/lib/python3.6/site-packages/jupyter_client/connect.py", line 137, in write_connection_file
    with open(fname, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1132/jupyter/kernel-9a6c897d-2591-4cc2-b3ea-9ac4803a8e55.json'
`

The comand `jupyter kernelspec list` delivers:
`
jupyter kernelspec list
Available kernels: 
python3    /usr/share/jupyter/kernels/python3
`

After restarting Jupyter, everything works fine again for some time. Kernels, which are already running do not cause any problems, they will also still run after many days. Only starting new Kernels after some time bothers me a little. Maybe somebody has an idea, what the problem could be. Unfortunately, I do not know which other information could be helpful. So please let me know if I can provide any additional information.

**Comment by kevin-bates** [comment]
It appears you're running into an instance of a missing sticky bit such that your `XDG_RUNTIME_DIR` (`/run/user/1132`) is getting cleared after some amount of time.  As a result, subsequent attempts to start a kernel, fail.  This is described here https://github.com/jupyter/jupyter_client/issues/199 - leading to a solution in jupyter_client 5.2.  The sticky bit is applied to Jupyter's runtime dir - which is the `jupyter` sub-directory to `/run/user/1132` when the first kernel is started. Try updating jupyter_client to an applicable version >= 5.2.0.

**Comment by MarkusThill** [comment]
Thanks for the fast reply. I updated jupyter_client to 6.0.0, but the problem remains. After some time the directory `/run/user/1132/` is removed. Can it have to do with the `screen`, in which I start jupyter?

**Comment by kevin-bates** [comment]
Hmm - the [latest version of jupyter_client is 5.2.4](https://pypi.org/project/jupyter_client/).  When you say `6.0.0`, is this from a build of the master branch?

This issue is more predicated on the existence of the `XDG_RUNTIME_DIR` environment variable.  When present, Jupyter will use that value as the prefix to its runtime location.  The operating system has its own _automatic cleanup_ mechanism for these files (thus their removal).  There are couple ways you can circumvent this - although the appropriate jupyter_client "should" correct this.  So, assuming you have a sufficient jupyter_client installed and still see the issue, you could try the following...
1. Set env `JUPYTER_RUNTIME_DIR` to some directory you have control over and restart Notebook.
2. unset env `XDG_RUNTIME_DIR` and restart Notebook.  I would not recommend unsetting this variable in a permanent fashion, since it may affect other applications. However, unsetting it as part of a startup script of Notebook is probably fine.  Technically, that script should restore the value in case the shell is reused after Notebook runs.  In this case, jupyter will use its default mechanisms and the kernel-<kid>.json file will likely windup in subdirectory under the Notebook user's home directory.

If the issue persists, you should probably open an issue in the jupyter_client repo - or reopen one of the previously fixed issues.

**Comment by MarkusThill** [comment]
Thanks again for the fast reply. Yes, I have a build of the master branch. That is why the version is 6.0.0. 
I will try your two suggestions and report later, if they worked. 

I noticed that the sticky bit is set on `/run/user/1132/jupyter` when I start jupyter (`drwx-----T`). Did I understand you correctly that if the bit is set, the OS should not automatically remove the directory?

**Comment by kevin-bates** [comment]
Thanks for the update.  Yes, that's my understanding based on the readings/resolutions of the previous issues in jupyter_client.  There was some thought about whether the [bit was actually required at the file level instead](https://github.com/jupyter/jupyter_client/issues/199#issuecomment-346844724), but we know from the error message, given the failure is during creation of the file, that the directory is no longer present, so I'd be surprised that's the issue.

Hmm - another question would be - when does the jupyter sub-directory get created in the first place and could that code also be used as part of the creation of the connection file?  I believe this file is only needed at initial kernel startup.  This would then tolerate timed-out removals.

**Comment by MarkusThill** [comment]
As far as I can see, the `jupyter` sub-directory is only created when I start jupyter (and it does not exist yet). I also think that the connection file is only needed for the kernel start-up, since my already running kernels do not cause any problems and still work after many days. So it could make sense to check the existance of the `jupyter` sub-directory when creating the connection file.
I also tried setting the sticky bit manually to `/run/user/1132/jupyter` and `/run/user/1132`, but it does not really help, the directory `/run/user/1132` is simply removed after some time. 
For the moment I will stick to your first suggestion, to set env `JUPYTER_RUNTIME_DIR`, which works perfectly fine.
Thanks for your help!!!

**Comment by kevin-bates** [comment]
Yeah, even if the sticky bit was required at the file level, it only keeps the directory present if there's another kernel running after the XDG expiration.  So until the directory is always created-if-not-present, I think this would be an issue.

Glad you're moving forward - thanks for all the experimenting!

**Comment by kevin-bates** [comment]
+1 to get this PR merged and drop use of XDG_RUNTIME_DIR: https://github.com/jupyter/jupyter_core/pull/143
