### ISSUE TITLE
Adding numbers to line in cell

### ISSUE THREAD

**Issue by helios1101** [jupyter/notebook#4487]
When we write long lines of codes and errors are thrown as " Error in line 20" or something other, then it becomes completely difficult to get to that line by mere counting.
My suggestion regarding this feature request would be adding numbers to the line to improve the interactive experience.

**Comment by kuckjwi0928** [comment]
You mean this function?
![2019-03-21 22-49-56 2019-03-21 22_50_37](https://user-images.githubusercontent.com/20429567/54756574-ddccc500-4c2b-11e9-95d0-ac65cea80b05.gif)

**Comment by helios1101** [comment]
Sorry! my bad, I didn't knew that function.
