### ISSUE TITLE
notebook 5.7.6 cannot work at browser

### ISSUE THREAD

**Issue by HoxinhLuo** [jupyter/notebook#4488]
When I install jupterthemes library, the notebook will automatically upgrade to version 5.7.6. Then I try to open notebook, it gives me a blank webpage no matter what browser I use. Then I downgrade the notebook's version to older. It also doesn't work until I uninstall jupterthemes. I don't know what the matter lies in, either notebook or jupterthemes ?

**Comment by IJM5157** [comment]
Encountering this issue as well.

Reading through previous issues it appears downgrading notebook to 5.7.4 works. If it still opens to a black page use "CNTRL+SHIFT+R" and it should work.

**Comment by ciupicri** [comment]
Sounds like a duplicate of issues #4491 and #4503.

**Comment by kwang2610** [comment]
> Encountering this issue as well.
> 
> Reading through previous issues it appears downgrading notebook to 5.7.4 works. If it still opens to a black page use "CNTRL+SHIFT+R" and it should work.

"CNTRL+SHIFT+R" works! Thanks!

**Comment by minrk** [comment]
Closing as duplicate of #4469
