### ISSUE TITLE
the jupyter notebook is not showing any thing in the browser

### ISSUE THREAD

**Issue by dheemanth1434** [jupyter/notebook#4494]
I installed Jupyter notebook in my laptop with a windows 10 install.
after installation, I opened notebook using command "jupyter notebook"
![image](https://user-images.githubusercontent.com/22279025/54629497-b0521100-4a9d-11e9-9072-0669f8d96b9d.png)

it opened in the browser but showing a blank screen
![image](https://user-images.githubusercontent.com/22279025/54629440-96b0c980-4a9d-11e9-8d17-b865e746c790.png)

**Comment by alifuk** [comment]
pip uninstall notebook
pip install notebook==5.7.5

**Comment by dheemanth1434** [comment]
it worked,
thanks.
