### ISSUE TITLE
Feature Request: Attach Files

### ISSUE THREAD

**Issue by Jwink3101** [jupyter/notebook#4502]
One of the beauties of the `ipynb` format and even the way it does HTML export is that it is a self-contained record of some particular results. Plots are stores inline (in base64) and stay with the document.

I think it would be really nice to be able to attach some files to a document. Obviously, this can get out of control, but that is on the user. And it will incur the cost of base64 encoding but that too, for some datasets, may be worth it.

The way I envision it, there would be something like a "data" block where you can attached  a file. And an iPython function set data programatically (some kind of `BytesIO` object). And of course an iPython api to grab the data (by filename? SHA1? Other ID?). 

Thoughts?

**Comment by minrk** [comment]
Execution is explicitly decoupled from the document, so accessing data within a notebook document would be hard to do. In general, data files have always been considered "out of scope" and the sharing unit for code+data should be a repo/directory/zipfile rather than a notebook.
