### ISSUE TITLE
Replace "Search and Replace" with "Find and Replace"

### ISSUE THREAD

**Issue by captainsafia** [jupyter/notebook#452]
@ellisonbg recommends that we rename the "Search and Replace" with "Find and Replace" to maintain consistency across editors that use a similar language to describe that functionality. I can give this one a go.

cc/ @Carreau

**Comment by Carreau** [comment]
Sure, I would appreciate if this could be done after #329 that would conflict with such changes.

**Comment by Carreau** [comment]
(you can review/test #329 if you like)
