### ISSUE TITLE
Jupyter Notebook so slow

### ISSUE THREAD

**Issue by rutujar** [jupyter/notebook#4540]
hi, I am encountering the problem in jupyter notebook. I am not able to run cells in jupyter from yesterday. i already reinstalled jupyter but the issue dint resolve and not displaying the output, i can see * symbol only till afte4 5 mins also. i need a help ??

![image](https://user-images.githubusercontent.com/26456931/55383273-6a895400-5545-11e9-993a-c118119b5970.png)

**Comment by janikarh** [comment]
Possible solution: Check installed `tornado` version, there seems to be ongoing issue with major version 6. Replace with version 5.x.

**Comment by rutujar** [comment]
can i know what is this error in jupyter @janikarh 
![image](https://user-images.githubusercontent.com/26456931/55715561-9eb3b780-5a12-11e9-9047-7db04ce40ad7.png)

**Comment by rutujar** [comment]
@janikarh it worked for tornado, thanks
