### ISSUE TITLE
jupyter notebook 5.7.8 %%time issue

### ISSUE THREAD

**Issue by henrikbol** [jupyter/notebook#4545]
After installing 5.7.8 the %%time feature leave declarations local in the cell.

Reproduce:

 
![image](https://user-images.githubusercontent.com/44621678/55479917-6a5d8700-561f-11e9-8214-9c479bb7004f.png)

![image](https://user-images.githubusercontent.com/44621678/55479958-7fd2b100-561f-11e9-8061-f5399706ca77.png)

**Comment by ildarbinanas** [comment]
I have equal issue on 5.7.8

**Comment by kevin-bates** [comment]
Per #4532 - This looks like an instance of ipython/ipython#11659 and not a notebook issue itself.
