### ISSUE TITLE
Error not logged in console

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#455]
Trying some config:

The following config:
```
Jupyter.notebook.get_selected_cell().config.update({CodeCell:{cm_config:{keyMap:"sublime"}}})
```

Break the notebook loading (need to require sublime keymap I guess), but does not log the error to the console:

```
The error was:
TypeError: Cannot read property 'attach' of undefined
See the error console for details.
```

**Comment by jdfreder** [comment]
Hmmm,  I see an error.  Was this fixed by #431 ?

<img width="1265" alt="screen shot 2015-09-29 at 4 06 20 pm" src="https://cloud.githubusercontent.com/assets/3292874/10176695/3e3bd1b6-66c4-11e5-9db1-21f123989734.png">

**Comment by ellisonbg** [comment]
@Carreau and @jdfreder any progress on this one?

**Comment by Carreau** [comment]
As for many other things, I will not have time to retry/investigate before next week (and still have a lot to catch up). 
You can assign someone else to try and if they can't reproduce feel free to close. 

Though the above error seem to be caught directly by chrome tool (cf codemirror.js:5321 which is not ours.), so thet stack will be available only if the debugger tools are **already open** before the stack happens. So the message `See the error console for details` is useless. 

The is a difference between **uncaught exception** that appear to console and **caught error** logged by **console.error**.

**Comment by jdfreder** [comment]
>  so thet stack will be available only if the debugger tools are already open before the stack happens. 

Doesn't seem to be true with Chrome 45.  I checked the behavior, with my console NOT open, and it seems fine:

![screenshot from 2015-10-07 14 12 15](https://cloud.githubusercontent.com/assets/3292874/10351331/d0aff772-6cfd-11e5-84e2-676b49763f65.png)

Popping up the console yields

![screenshot from 2015-10-07 14 13 12](https://cloud.githubusercontent.com/assets/3292874/10351345/ea769a30-6cfd-11e5-886d-910e34f487f3.png)

Clicking on the `(...)` causes the stack to show (in my previous screenshot).

**Comment by thisch** [comment]
@jdfreder why did you close this issue?

**Comment by jdfreder** [comment]
> @jdfreder why did you close this issue?

@Carreau opened the issue because the error wasn't being logged:

> Break the notebook loading (need to require sublime keymap I guess), but does not log the error to the console:

It is being logged.

The code he posted doesn't work and should not work, this is expected.

**Comment by thisch** [comment]
I also get the error mentioned in the first post by @Carreau when opening my existing notebooks, but I didn't change the config as he did. BTW I don't get the error when creating a new notebook.

I'm using the notebook package shipped with conda (4.0.5) .

**Comment by jdfreder** [comment]
Getting the error is good **IF** you've changed the config in the same manner as he did!

Seeing as you haven't changed the config, it is a bad error.  You mention that you don't get the problem when opening a new notebook, is it one or more particular notebook(s) that is/are causing the problem?  If so, can you share them?  Chances are the notebook(s) have bad JavaScript in them which is causing the load failure.

**Comment by thisch** [comment]
This error orrcurs only for some notebooks. If I open the notebook in an incognito window, I don't get this error. I guess it is a caching issue ..

**Comment by thisch** [comment]
Here is a minmal notebook, where I always get this 'attach' error while opening it: https://gist.githubusercontent.com/anonymous/8c7515ce6af19286fd92/raw/13dd9a1f7f31aec5bee2ca23255dc2c9f156d5cb/attacherror.ipynb

**Comment by jdfreder** [comment]
If you don't have the problem in incognito mode, you're right, it's probably a caching issue.  Try clearing your browser's cache.  That notebook looks fine to me.

**Comment by thisch** [comment]
When I tested it last weak (with google chrome) clearing the cache worked
fine. But today I always get this error even in incognito mode. This is
peculiar. The github notebook render seems to have no problem with
rendering the notebook.

I have just tested it with firefox, where I don't get this error.

On Mon, Oct 12, 2015 at 4:41 PM, Jonathan Frederic <notifications@github.com

**Comment by thisch** [comment]
Here is a screenshot of the javascript console in chrome. There are some suspicious errors
![javascriptstuff](https://cloud.githubusercontent.com/assets/206581/10431267/79be6f88-7104-11e5-9fe1-e036e03509b6.png)

**Comment by jdfreder** [comment]
Looks like your notebook is out of date - or your component versions are mismatched.  How did you install the notebook?  Can you update and then do a full cache clearing?

**Comment by thisch** [comment]
It seems that clearing ~/.jupyter and ~/.local/share/jupyter seems to have
fixed my problem. (Only clearing the browser cache didn't help). Can you
explain this?

On Mon, Oct 12, 2015 at 5:30 PM, Jonathan Frederic <notifications@github.com

**Comment by jdfreder** [comment]
You must have had some stale Javascript in your config.  Did you run the code @Carreau pasted above? Or install any notebook extensions?

**Comment by thisch** [comment]
Not that I know of.

**Comment by jdfreder** [comment]
Custom.js?

**Comment by jdfreder** [comment]
Or custom kernels?

**Comment by thisch** [comment]
I had this in my ``~/.ipython/profile_default/static/custom/custom.js`` (don't know if ~/.ipython/profile_default/static/.. is still used after the big refactoring in ipython/jupyter 4.0)

```
$([IPython.events]).on('app_initialized.NotebookApp', function(){
function to(mode) {
    var mode = mode || 'vim'
    // first let's apply vim mode to all current cells
    function to_mode(c) { return c.code_mirror.setOption('keyMap', mode);};
    IPython.notebook.get_cells().map(to_mode);
    // apply the mode to future cells created
    IPython.Cell.options_default.cm_config.keyMap = mode;
}

require(["components/codemirror/keymap/emacs"],
     function (emacs) {
         to('emacs');
         console.log('emacs.js loaded');
     });
})
```

**Comment by jdfreder** [comment]
That's probably it :)

**Comment by thisch** [comment]
Sry, I was unaware that this code was still in my custom.js. Thx @jdfreder for helping me fix this issue.
