### ISSUE TITLE
Changelog entries missing for 5.7.8 in master, for 5.7.7 in branch

### ISSUE THREAD

**Issue by rolweber** [jupyter/notebook#4552]
Notebook version 5.7.8 is the latest on PyPI, but the changelog in master ends with 5.7.7:
https://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst

There is a changelog entry for 5.7.8 in the 5.7.x branch, but here the entry for 5.7.7 is missing:
https://github.com/jupyter/notebook/blob/5.7.x/docs/source/changelog.rst

FYI @minrk

**Comment by rolweber** [comment]
On a closer look, the changelog entry for 5.7.8 in the branch includes most of the items from 5.7.7 on master. I guess the changelog-generating logic got thrown off because 5.7.7 was tagged in master, 5.7.8 in the branch?

**Comment by minrk** [comment]
Forgot to forward-port the changelog commit. Fixed in 8f2ab101aa40fea5169b9bcb4c614d1e6ed63a1c
