### ISSUE TITLE
disable autosave feature of jupyter notebook

### ISSUE THREAD

**Issue by Deepakchawla** [jupyter/notebook#4556]
I want to stop/disable autosave functionality in my jupyter notebook.

**Comment by mwouts** [comment]
Hello @Deepakchawla , I have just contributed a [new answer](https://stackoverflow.com/questions/25631344/turn-off-autosave-in-ipython-notebook/56549758#56549758) to that question on stackoverflow. 

My answer uses the `autosavetime` extension for Jupyter notebook (and no `custom.js` file). Could you please let me know if it works for you?

**Comment by jtpio** [comment]
Closing as answered above.

Also in Notebook 7 it's possible to disable the "Autosave Documents" via the settings menu:

![image](https://github.com/jupyter/notebook/assets/591645/0a5b565c-8452-4583-b39f-dc044f268ba0)
