### ISSUE TITLE
custom.js load order not the same if js compiled

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#456]
using require js:
```
custom.js first hit
custom.js:12 in custom.js listen for events:
///
notebook.js:2504 notebook_loaded.Notebook trigger
```

Minified js:
```
custom.js first hit
...
notebook.js:2504 notebook_loaded.Notebook trigger
...
custom.js:12 in custom.js //  listen for events
```

Which make some things (like changing keymap) impossible with minified JS. 

Have a specific call to `custom.js:load` if defined ?

**Comment by minrk** [comment]
Gotcha, so it's apparently a race condition and we were relying on everything being super slow to load. Would it be resolved if custom.js used `define`?

**Comment by minrk** [comment]
Or if we put custom.js in a vanilla script tag?

**Comment by minrk** [comment]
(BTW: async module loading is the dumbest thing ever)

**Comment by Carreau** [comment]
> Gotcha, so it's apparently a race condition and we were relying on everything being super slow to load. Would it be resolved if custom.js used define?

It might, I think we should still use a structure in the form :

```
define(function(){
    return {load:function(){
      /// user code
    }};
});
```

then add that in the middle of `main.js`
```
(custom.load || function(){}))()
```

Script tag won't do it : custom should be executed after most of deps are loaded, but early enough, 
to have a change tohook to events. Basically just in the middle of main .

**Comment by Carreau** [comment]
And that's awesome, I cannot reproduce.

**Comment by Carreau** [comment]
I think I figured it out, 

I might have tried someone custom.js that uses `require([...], function(){})` instead of `define([...], function(){...})` still not quite sure why it would change order though. 

Bumping to 4.x

**Comment by ellisonbg** [comment]
Do you want to look at this further, or should we just close until it shows up again?

**Comment by Carreau** [comment]
Ok, let's close.
