### ISSUE TITLE
Issue using TAB to call a method in Jupyter

### ISSUE THREAD

**Issue by AkiraCharles** [jupyter/notebook#4562]
Hi. I am having an issue as well using TAB within Jupyter. when I attempt to call a method off of a Dataframe within the Jupyter Notebook , I am trying to add the ".Unique()" method. But, when I attempt to call whatever methods may be available off of the dataframe object, the only thing that appears is "ipynb_checkpoints/". I have googled this issue but I cannot seem to find a way to resolve it. Does anyone have any advice on this? I tried uninstalling and reinstalling Anaconda and that does not solve the issue.

![Capture](https://user-images.githubusercontent.com/25424753/56065091-e2bff880-5d41-11e9-8f24-0a58dd28046a.PNG)

**Comment by mtd91429** [comment]
See https://github.com/ipython/ipython/issues/11530 for a solution

This isn't a Jupyter Notebook bug - it is a problem related to ipython, as the notebook is only displaying what ipython provides.
