### ISSUE TITLE
NameError: name 'x' is not defined in jupyer notebook upon using %%time

### ISSUE THREAD

**Issue by mdalvi** [jupyter/notebook#4566]
A very strange error occurred with me today, I was trying running my jupyter notebook until one of my cell contained a code segment from a package named [featuretools](https://docs.featuretools.com/#run-deep-feature-synthesis) which uses dask, distributed and what not in its backend for processing..... 

So upon running this line 

`features = {'matrix': None, 'defs': None}`
`features['matrix'], features['defs'] = ft.dfs(entities=entities, relationships=relationships, target_entity="customers")`

After completing the process, jupyter would give me 

`NameError: name 'features' is not defined`

Everything else is defined but the variables in this cell!

**Only to find that after removing **%%time** from this cell, it worked!**

Is there some relation to dask or any other package that magic constants cause problem?

I am using below OS

```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0] on linux
jupyter.__version__ = 1.0.0
IPython.__version__ = 7.4.0
```

**Comment by SofianeB** [comment]
@mdalvi experiencing same error. Using jupyter notebook ```5.7.8```.

**Comment by kevin-bates** [comment]
This is an issue with ipython and dup of #4532.

**Comment by kevin-bates** [comment]
@mdalvi - could you please close this issue since its not a notebook issue?  Thanks.

**Comment by CSFlorin** [comment]
why is this closed? it seems to still be an issue

**Comment by jasongrout** [comment]
> why is this closed? it seems to still be an issue

From the [comment above](https://github.com/jupyter/notebook/issues/4566#issuecomment-483341381), "This is an issue with ipython and dup of #4532."

**Comment by CSFlorin** [comment]
> > why is this closed? it seems to still be an issue
> 
> From the [comment above](https://github.com/jupyter/notebook/issues/4566#issuecomment-483341381), "This is an issue with ipython and dup of #4532."

Oh I had to follow a few links to find the resolution https://github.com/ipython/ipython/issues/11659

I honestly didn't know there's a difference between ipython and jupyter

**Comment by ClaudeCoulombe** [comment]
I've post a  [Question/ Solution](https://stackoverflow.com/questions/56660164/jupyter-notebook-nameerror-is-not-defined-time-prevents-assignment/56660165#56660165) about that on StackOverflow

**Comment by AleksandrKosolapov** [comment]
I had a problem too, solved by removing "import os" at the beginning of loading libraries

**Comment by iskgorka** [comment]
https://www.youtube.com/watch?v=WDG7i_tSFh4

**Comment by linehammer** [comment]
In most cases, this error is triggered when Python sees a variable name (Global or Local) and doesn't know what it's for. These errors can happen if you forget to initialize a variable , if you misspell a variable, or if you misspell a reserved word such as "True". Before you use the [global variable](http://net-informations.com/python/iq/global.htm) in your function for reading, it must be first initialized somewhere: either outside of the function or inside it.
