### ISSUE TITLE
How to execute(buy or sell) create and execute an operation at one time in Backtrader?

### ISSUE THREAD

**Issue by Sundetaly** [jupyter/notebook#4568]
For instance,
2016-02-23, SELL CREATE 24.20
2016-02-24, SELL EXECUTED Price: 24.76
24.24 and 24.76 are the close price of each day.
It is daily trading. Execute operation is performed the next day, on 24.
I want to create and execute the operation in 2016-02-23.
I mean that the action was created and executed at a price of 24.24. Is it possible to perform such operation?

**Comment by kevin-bates** [comment]
This question strikes me as specific to Backtrader and should first be asked on their community forum: https://community.backtrader.com/

I suspect you're driving at the ability to submit two backtrader requests within a transaction.  If so, providing the means of submitting multiple actions within a transaction would likely be something the backtrader api would need to provide - which is likely independent of the underlying kernel and notebook in particular.
