### ISSUE TITLE
Document how to customize cell code indentation

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#457]
From Google Group discussion (9/15/2015) between @Carreau and Ugo:

In recent version you shouldn’t even need to do all that. 
Just issue the following once in the javascript console of your browser:

``Jupyter.notebook.get_selected_cell().config.update({CodeCell:{cm_config:{indentUnit :2}}})``

Reload your notebook. 

it works. 

I'm a bit lost with respect to what are the directories that jupyter actually searches, and I was not able to get custom.js to be loaded.

Then I've tried to start from the instructions at https://carreau.gitbooks.io/jupyter-book/content/Jsextensions.html, and succeded at creating a simple extension:

define(function(){
  return {
    load_ipython_extension: function(){
      console.log('Loading ugos custom.js');
      require(["notebook/js/codecell"], function(result) {
        result.CodeCell.options_default.cm_config.indentUnit = 2;
        console.log('Loaded ugos custom.js');
      });
    }
  };
});

If I explicitly run a cell:
%%javascript
require(['base/js/utils'], function(utils) { utils.load_extensions('ugo'); });
in my notebook, then new cells do have 2 spaces indents.

But now I don't know how to get ipython to load the extension automatically, so that all the cells do get the same indentUnit.

You need to issue the 

 > Jupyter.notebook.config.update({"load_extensions":{"my_ext":true}})

That will load your extension every tim,

**Comment by willingc** [comment]
@carreau Do you want me to write the doc on this and you can review?

**Comment by Carreau** [comment]
I started something yesterday:

https://github.com/Carreau/jupyter_notebook/blob/2b79f882a837fcd0e95130166ad0fc10127aa72a/docs/source/notebook_frontend_configuration.rst

Would that help you ?

**Comment by willingc** [comment]
@carreau Ooh..shiny. Do you want to submit it as a PR and merge? I will iterate after that :bicyclist:

**Comment by Carreau** [comment]
I'm in a workshow, feel free to copy and past :-P

**Comment by willingc** [comment]
Will do. Enjoy the show. :performing_arts:

**Comment by ellisonbg** [comment]
@willingc looks like your PR was merged, closing this.
