### ISSUE TITLE
Error when launching Jupyter Lab, and happens for qt console as well

### ISSUE THREAD

**Issue by ColbyOstberg** [jupyter/notebook#4573]
Whenever I open Jupyter Lab I get this extensive error message, and I cannot run code because the kernel is not connected:

[I 16:06:04.323 LabApp] The port 8888 is already in use, trying another port.
[I 16:06:04.324 LabApp] The port 8889 is already in use, trying another port.
[I 16:06:04.324 LabApp] The port 8890 is already in use, trying another port.
[I 16:06:04.325 LabApp] The port 8891 is already in use, trying another port.
[I 16:06:04.325 LabApp] The port 8892 is already in use, trying another port.
[I 16:06:04.333 LabApp] JupyterLab extension loaded from /Users/colbyostberg/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 16:06:04.333 LabApp] JupyterLab application directory is /Users/colbyostberg/anaconda3/share/jupyter/lab
[W 16:06:04.335 LabApp] JupyterLab server extension not enabled, manually loading...
[I 16:06:04.336 LabApp] JupyterLab extension loaded from /Users/colbyostberg/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 16:06:04.337 LabApp] JupyterLab application directory is /Users/colbyostberg/anaconda3/share/jupyter/lab
[I 16:06:04.337 LabApp] Serving notebooks from local directory: /Users/colbyostberg
[I 16:06:04.337 LabApp] The Jupyter Notebook is running at:
[I 16:06:04.337 LabApp] http://localhost:8918/?token=987a5ad94b5179e7a41ae873dc25f6c6764b945632e39c24
[I 16:06:04.337 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:06:04.346 LabApp] 

To access the notebook, open this file in a browser:
file:///Users/colbyostberg/Library/Jupyter/runtime/nbserver-4998-open.html
Or copy and paste one of these URLs:
http://localhost:8918/?token=987a5ad94b5179e7a41ae873dc25f6c6764b945632e39c24
[W 16:06:06.489 LabApp] Could not determine jupyterlab build status without nodejs
[E 16:06:09.122 LabApp] Failed to run command:
['/anaconda3/envs/py37/bin/python', '-m', 'ipykernel_launcher', '-f', '/Users/colbyostberg/Library/Jupyter/runtime/kernel-6f1c8c8a-a9a3-4527-9939-4ca9a632cddc.json']
PATH='/Users/colbyostberg/anaconda3/bin:/Users/colbyostberg/anaconda3/bin:/Users/colbyostberg/anaconda3/condabin:/usr/bin:/bin:/usr/sbin:/sbin'
with kwargs:
{'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/Users/colbyostberg', 'start_new_session': True}

[E 16:06:09.123 LabApp] Uncaught exception POST /api/sessions?1555542369093 (::1)
HTTPServerRequest(protocol='http', host='localhost:8918', method='POST', uri='/api/sessions?1555542369093', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
result = await result
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
type=mtype))
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
value = future.result()
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
value = future.result()
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
value = future.result()
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
yielded = next(result)
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
super(MappingKernelManager, self).start_kernel(**kwargs)
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
km.start_kernel(**kwargs)
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
**kw)
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
proc = Popen(cmd, **kwargs)
File "/Users/colbyostberg/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
restore_signals, start_new_session)
File "/Users/colbyostberg/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda3/envs/py37/bin/python': '/anaconda3/envs/py37/bin/python'
[W 16:06:09.126 LabApp] Unhandled error
[E 16:06:09.126 LabApp] {
"Host": "localhost:8918",
"Connection": "keep-alive",
"Content-Length": "97",
"Authorization": "token 987a5ad94b5179e7a41ae873dc25f6c6764b945632e39c24",
"Origin": "http://localhost:8918",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36",
"Content-Type": "application/json",
"Accept": "*/*",
"Referer": "http://localhost:8918/lab",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en-US,en;q=0.9",
"Cookie": "_xsrf=2|cf6ce335|dca0d0ff784deca1592c752dd167b1a1|1554760347; username-localhost-8858=\"2|1:0|10:1555528455|23:username-localhost-8858|44:ZDM1NzJhMDY2NDE2NDExZjk3ZjViMzM5Yzg3ODg4NzM=|e4f31a9f29d447f5df789143d9d5d98c22b003e62b875a6d65df9b9c1f77791c\"; username-localhost-8791=\"2|1:0|10:1555528665|23:username-localhost-8791|44:N2MzODE5NjQ1ZGQxNDViMjgxZTA3YTMwMDdjYjRmZjg=|03491ac50fb58c067c0a9adfd73d436499096601cd2b4e65c0e88294f369dd2b\"; username-localhost-8906=\"2|1:0|10:1555528868|23:username-localhost-8906|44:NDYzMzI2YzQxNjJhNDEyMGFjOWQ4MmI0NzQ2ZTlhMDU=|2a5cee1a55900faeff1253d47a18ce4fc0741c3c8002e31786b631c06f4770c8\"; username-localhost-8795=\"2|1:0|10:1555530098|23:username-localhost-8795|44:MzU2NDY2MjRmOWFlNGU1N2FiYTJjN2NlNDA1ODUzZjI=|c6104757ee201c1ea41425da6d1338757edf29e5b2dec066bd0c45f7efe94368\"; username-localhost-8888=\"2|1:0|10:1555530581|23:username-localhost-8888|44:OWY0MzM4NmYxYjgwNDUxMzg1OWZjYmQzNWMxZDhmNmU=|d558318772f2e93a818f47614d48bf0503c9a421cbbe97a110eb0bf4ad71ba56\"; username-localhost-8889=\"2|1:0|10:1555530764|23:username-localhost-8889|44:MWFiYTg2NDFmMzJkNGI2YmE2N2QzZTYxNDExNjhiODE=|75b70072d7ebb95726b3a3924aac74591bf91d5a5751fce29d236f16ee4756b2\"; username-localhost-8891=\"2|1:0|10:1555532053|23:username-localhost-8891|44:ZGY3NDczYmVlMjA1NDRiMWExODhiMWYzZDMyOWI2NGE=|49aee4a982711321055a6c562588963c254ac611019827898cb8d904ce32dda1\"; username-localhost-8890=\"2|1:0|10:1555532188|23:username-localhost-8890|44:YjdjYTI0NTY5N2M2NDk4NWJiM2E2YTkwNGU3NzU3ZmM=|f93f52881d0d87c2599383b4c29713e669ec96a269d13a29eab70d426cc49e8d\"; username-localhost-8985=\"2|1:0|10:1555540277|23:username-localhost-8985|44:ODgyZDczMmE0YzM2NDJjOGEwZGZiYjJkYWE1NmFkYzA=|9f7dae906432bbe950f79adcf4f144201cc2ae62bdc97081d341cd528673064f\"; username-localhost-8892=\"2|1:0|10:1555541081|23:username-localhost-8892|44:YTRhMzM0YzMwNzUzNGU2ZWE2YTA0ZWRmMzAxOWE0ZDI=|1d34e0d807d5716e14fc701a86d8cb59794c5f3640cee41e89fe0e0b0158e244\"; username-localhost-8819=\"2|1:0|10:1555541753|23:username-localhost-8819|44:ZjIwZWZiMzQ2NDk1NGYwYmI3ZWRiZjliYzIxNzhhNmY=|9c3d4f8918cc92505d93626e8d6f428bfb4f1a248e4bde8e2673a8a0a8253bee\"; username-localhost-8854=\"2|1:0|10:1555542298|23:username-localhost-8854|44:ZTQwNjY4Y2VmMDM3NGEzOGE3MjBiNjY4N2Y0ODE1MTQ=|a8e930088a16c319ef586dd8f061b8640a8605b436ff32431a2682b624b3b709\"; username-localhost-8918=\"2|1:0|10:1555542367|23:username-localhost-8918|44:YzNlYTk1MTQxMjY3NDU1ZmFhMzlkOThjNTA3NDA3YzA=|ad96b762b69ece6441da4073a0fad043b5f400acaf72b121c2e14826b9d7f6a6\""
}
[E 16:06:09.127 LabApp] 500 POST /api/sessions?1555542369093 (::1) 29.17ms referer=http://localhost:8918/lab

**Comment by kevin-bates** [comment]
I suspect the in-use ports are a remnant of deleting the environment that you mention in #4572.  

You'll likely need to determine which processes are using those ports.  Since this appears to be a Mac, you might try [this SO answer](https://stackoverflow.com/questions/4421633/who-is-listening-on-a-given-tcp-port-on-mac-os-x) - then issue `kill -9 <PID>`.  (Normally one wouldn't use `-9` (SIGKILL) for this, but I'm fairly certain you don't need these _gracefully exited_.  If that's not the case, remove `-9`, but know they might not go away.)

Regarding the failure to launch the kernel, I can definitely see that the `kernel.json` I referenced in the other issue probably has an `argv` stanza consisting of `['/anaconda3/envs/py37/bin/python', '-m', 'ipykernel_launcher', '-f', '{connection_file}']`.  Updating the first entry should get you going.

**Comment by ColbyOstberg** [comment]
I killed all the processes which were using those ports. And the kernel fix in the last post worked for Jupyter lab as well. No more errors. You are the man. Thank you for all the help.

**Comment by kevin-bates** [comment]
@ColbyOstberg - could you please close this issue so that its "off the books"?  Thanks.
