### ISSUE TITLE
Is it possible to add cells that always stay at the bottom of the notebook? 

### ISSUE THREAD

**Issue by ChangyuYan** [jupyter/notebook#4599]
So we don't need to constantly insert cells above it and manually keep the order. Would it be possible to have an option to just have some cells sticky to the bottom of the entire notebook? 

Thanks!

**Comment by xiaohk** [comment]
Hi @ChangyuYan, you might want to check out [StickyLand](https://github.com/xiaohk/stickyland) :)

StickyLand is an extension that enables JupyterLab users to create sticky cells. Users can easily create sticky cells and freely arrange them with simple drag-and-drop. Users can also automatically execute these cells. With multiple sticky cells, users can even create a fully-fledged interactive dashboard.

![feature-gif](https://user-images.githubusercontent.com/15007159/155828752-af883f7d-e9ac-48d5-8231-087f62582d98.gif)
