### ISSUE TITLE
Internal server error on notebook exporting

### ISSUE THREAD

**Issue by Phyks** [jupyter/notebook#466]
Hi,

When trying to export [this notebook](http://verney.lv/phynum/homework1.ipynb) to PDF (with LaTeX), I get the following error (500 internal server error):

```
When looking at the server logs, I found this:
! Undefined control sequence.
    <argument> \ImportTok
                          {import} \NormalTok {math, numpy}
    l.550 \ImportTok{import} \NormalTok{math, numpy}

    ?
    ! Emergency stop.
    <argument> \ImportTok
                          {import} \NormalTok {math, numpy}
    l.550 \ImportTok{import} \NormalTok{math, numpy}

    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.
```

I should have all the necessary dependencies and tried it on two different systems, which can export normally to PDF other notebooks.

Thanks

**Comment by Carreau** [comment]
Remove the space after your  `$\alpha \symeq $` (I think you have this twice). 

convert to latex manually `jupyter nbconvert --to latex homework1.ipynb`

Add these for lines manually (without the plus) :

```
     \newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{{#1}}}}
+    \newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{{#1}}}}
+    \newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{{#1}}}}
+    \newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{{#1}}}}
+    \newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{{#1}}}}
     \newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.56,0.13,0.00}{{#1}}}
```

Compile with pdf latex manually. `pdflatex homeworks1.tex`

Fix in progress

Bon courage.

**Comment by Phyks** [comment]
Awesome, thanks a lot for the help and the very quick fix!

**Comment by Carreau** [comment]
The pull request will close the issue automatically at the right time.

**Comment by Phyks** [comment]
Ok, sorry.

**Comment by Carreau** [comment]
> Ok, sorry.

No problem, i"ll put that on the fact that it's 2am in France.
