### ISSUE TITLE
Docs: broken link

### ISSUE THREAD

**Issue by tritemio** [jupyter/notebook#467]
In this section of the docs:

http://jupyter-notebook.readthedocs.org/en/latest/notebook.html#code-cells

the link to the "Basic Output" notebook is broken. Is there a new official place where these notebooks live?

**Comment by willingc** [comment]
@tritemio Thanks for reporting the broken link. The docs live http://jupyter-notebook.readthedocs.org/ which is the link that you have currently.

I will take a look at the docs and see why the link is not working. Thanks for your patience and sorry for any inconvenience.

GitHub now renders notebooks, and you may find this link to the notebook examples and its index helpful in the interim https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Examples%20and%20Tutorials%20Index.ipynb
