### ISSUE TITLE
Feature Request: Mermaid support

### ISSUE THREAD

**Issue by parthi2929** [jupyter/notebook#4671]
Hi

Can you please support [mermaid](https://mermaidjs.github.io/) for drawing graphs? Its much easier than graphviz and can co exist. It is also one of widely used language for drawings in markdown documents.

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyter/notebook/issues/6902 since https://github.com/jupyter/notebook/issues/6902 now has a few more comments than this previous issue.

Thanks @parthi2929 for opening it!
