### ISSUE TITLE
Latest preact-compat release breaks notebook.

### ISSUE THREAD

**Issue by ssanderson** [jupyter/notebook#4680]
Three of our javascript dependencies, `preact`, `preact-compat`, and `proptypes`, are currently managed via [`unpkg` links](https://github.com/jupyter/notebook/blob/master/bower.json#L19), and pinned with `^` rather than `~`. `^` appears to have the same semantics as in npm, in which it means "allow non-major version upgrades".

The most recent release of `preact-compat` appears to have broken the notebook. If I clear my `~/.cache/bower` and then run `python setup.py css js` in an editably-installed `notebook` repo, when I run `jupyter notebook` I get a blank page on the notebook page, with console errors about missing `createContext` from `preact-compat`:

![image](https://user-images.githubusercontent.com/1588357/59719365-32132100-91ea-11e9-8104-7241f5d7dd8f.png)

I think the easiest fix here is to pin via `~`, which seems to be the convention followed for most other js dependencies (MathJax seems to be a notable exception to this rule). We may also want to report this upstream as a bug to `preact-compat`? I don't really have a good sense of whether that's desirable.

**Comment by ssanderson** [comment]
Switching to `~` fixes the issue for me locally: https://github.com/jupyter/notebook/pull/4681

**Comment by ssanderson** [comment]
NOTE: Clearing your bower cache is required to reproduce this issue. If you've previously build the js dependencies successfully, bower appears to continue to re-use the old deps even though it resolves different versions with an empty cache. :(

**Comment by leestott** [comment]
Just as update this fixes build issues in Build Pipelines in Azure DevOps Pipelines we had  the following issues and Errors 

![image](https://user-images.githubusercontent.com/2511341/59762792-ed41c580-928f-11e9-987c-37eeb3c33282.png)

Error 
 ##[section]Starting: Run base Tests
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/0ec4b1f4-49ab-41ab-9b5f-a8215f60bf3e.sh
Available kernels:
  python3    /opt/hostedtoolcache/Python/3.6.8/x64/share/jupyter/kernels/python3

Test group: base
Test file: &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;highlight.js                 ‌
Page Error
  Message:   TypeError: undefined is not an object (evaluating 'e.createContext')
  Call stack:
    line 1 of static/components/preact-compat/index.js
    line 1 of static/components/preact-compat/index.js
Page Error
  Message:   TypeError: undefined is not an object (evaluating 'e.createContext')
  Call stack:
    line 1 of static/components/preact-compat/index.js
    line 1 of static/components/preact-compat/index.js
Page Error
  Message:   ReferenceError: Can't find variable: preactCompat
  Call stack:
    line 42225 of static/notebook/js/main.min.js
    line 1693 of static/components/requirejs/require.js in execCb
    line 881 of static/components/requirejs/require.js in check
    line 1173 of static/components/requirejs/require.js in enable
    line 1554 of static/components/requirejs/require.js in enable
    line 1158 of static/components/requirejs/require.js
    line 134 of static/components/requirejs/require.js
    line 59 of static/components/requirejs/require.js in each
    line 1110 of static/components/requirejs/require.js in enable
    line 1554 of static/components/requirejs/require.js in enable
    line 1158 of static/components/requirejs/require.js
    line 134 of static/components/requirejs/require.js
    line 59 of static/components/requirejs/require.js in each
    line 1110 of static/components/requirejs/require.js in enable
    line 786 of static/components/requirejs/require.js in init
    line 1457 of static/components/requirejs/require.js
Timeout for http://localhost:8888/a@b/
Is the notebook server running?

Details for the 5 failed tests:

In /home/vsts/work/1/s/notebook/tests/base/highlight.js
  Untitled suite in &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;highlight.js‌
    uncaughtError: &quot;.CodeMirror-code&quot; still did not exist in 10000ms‌
In /home/vsts/work/1/s/notebook/tests/base/keyboard.js
  Untitled suite in &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;keyboard.js‌
    uncaughtError: &quot;.CodeMirror-code&quot; still did not exist in 10000ms‌
In /home/vsts/work/1/s/notebook/tests/base/misc.js
  Untitled suite in &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;misc.js‌
    uncaughtError: &quot;.CodeMirror-code&quot; still did not exist in 10000ms‌
In /home/vsts/work/1/s/notebook/tests/base/security.js
  Untitled suite in &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;security.js‌
    uncaughtError: &quot;.CodeMirror-code&quot; still did not exist in 10000ms‌
In /home/vsts/work/1/s/notebook/tests/base/utils.js
  Untitled suite in &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;notebook&#x2F;tests&#x2F;base&#x2F;utils.js‌
    uncaughtError: &quot;.CodeMirror-code&quot; still did not exist in 10000ms‌
Running tests with notebook directory '/tmp/tmpi8t4hukp'
 
_______________________________

**Comment by ssanderson** [comment]
@gnestor @minrk looks like you two have most of the git history around managing these js dependencies. Any objection to switching to pinning preact and friends with `~` instead of `^`?

**Comment by gnestor** [comment]
No objection from me 👍

**Comment by ssanderson** [comment]
@gnestor do you want to hit the button on https://github.com/jupyter/notebook/pull/4681 , or should we wait for more feedback? I'm a bit anxious to land this b/c as far as I can tell running the notebook from a fresh local checkout is broken right now.

**Comment by gnestor** [comment]
> If I clear my ~/.cache/bower and then run python setup.py css js in an editably-installed notebook repo, when I run jupyter notebook I get a blank page on the notebook page, with console errors about missing createContext from preact-compat

@ssanderson I'm unable to reproduce this.

**Comment by ssanderson** [comment]
@gnestor hmm, interesting. What OS are you on? Your cache path might be different than mine.

**Comment by ssanderson** [comment]
(I'm on Ubuntu 18.04)

**Comment by gnestor** [comment]
I'm on macOS 10.14.5. I was able to `rm -rf ~/.cache/bower` and reinstall the notebook but I'm not seeing these errors.

**Comment by limbuu** [comment]
i am having same issue. Any fix so far?

**Comment by ssanderson** [comment]
@limbuu I think this should be fixed on head of master since @lresende merged https://github.com/jupyter/notebook/pull/4681.

**Comment by ssanderson** [comment]
@gnestor have you cleared out your previous install of the js/css components in the repo? The components installed by `bower install` are downloaded to `notebook/static/components` (that directory is gitignored so it won't look dirty), so if you've previously set up the notebook in your checkout, you've probably already got them.

For me a complete repro is:

```
# Alternatively, `rm -rf notebook/static/components`.
$ git clone git@github.com:jupyter/notebook.git
$ cd notebook/
# Last commit prior to fix being merged.
$ git checkout fc2c46141deb06b9e939b295ce254907830d3147

# Assuming this is where your bower cache is.
$ rm -rf ~/.cache/bower/

# Install in fresh venv. `pip install -e .` invokes setup.py js internally, which uses bower to
# download to notebook/static/components.
$ mkvirtualenv -p python3 nb-repro
$ pip install -e .

$ jupyter notebook

# Navigate to new notebook page
```

![image](https://user-images.githubusercontent.com/1588357/60114481-e8728b00-9741-11e9-8c4d-e71df28bf6ca.png)

**Comment by ssanderson** [comment]
Also worth noting: this is only broken on the notebook page itself. The notebook list page is fine.

**Comment by gnestor** [comment]
@ssanderson I ended up just replacing preact with react in notebook. The ended up using preact only because of react's PATENT issue a couple years back. Next, I'd like to get react working with requirejs vs. adding a global UMD script to the page.
