### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by Jeffiy** [jupyter/notebook#469]
Hi, there is a small UI problem in login page that the height of `<div id="site" style="display: block; height: 596px;">` is not necessary and it's cause the scrollbar displayed.
![qq 20150921160110](https://cloud.githubusercontent.com/assets/5069316/9987521/33c91e7c-607b-11e5-8c01-2b23d49ea196.png)

**Comment by ellisonbg** [comment]
Thanks for the find!

On Mon, Sep 21, 2015 at 1:12 AM, zhangmm <notifications@github.com> wrote:

> Hi, there is a small UI problem in login page that the height of <div
> id="site" style="display: block; height: 596px;"> is not necessary and
> it's cause the scrollbar displayed.
> [image: qq 20150921160110]
> <https://cloud.githubusercontent.com/assets/5069316/9987521/33c91e7c-607b-11e5-8c01-2b23d49ea196.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/469>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Do you want to make a PR ?

**Comment by Jeffiy** [comment]
Yes, but I didn't find the way to fix it. I didn't know where the height of the div come from? can you give me some help? thanks.

**Comment by Carreau** [comment]
Hum, guessing, I would say that is is set by the js in
`notebook/static/base/js/page.js`, which is responsible from setting the
height when there is a header and/or a footer.

We should either deactivate that on the login page, or fix why it does the
calculation incorrectly.

probably in a resize_header method or something names alike.
