### ISSUE TITLE
terminal unable to display correctly on windows chrome 64b

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#47]
It's too wide and the cursor spanned two chars.

**Comment by Carreau** [comment]
generally js-terminal are termjs issues, we use of from upstream almost unmodified.

**Comment by JamiesHQ** [comment]
@cailiang9 : Greetings! I'm moving through our backlog and closing or progressing those over a year old. Have you found a resolution for this issue and can it be closed?

**Comment by cailiang9** [comment]
Thanks for your attention! I found it caused by larger font-size. So I reset with default font-size to resolve it.

**Comment by JamiesHQ** [comment]
@cailiang9 : super! glad you got it working the way you wanted!
