### ISSUE TITLE
Support for moving files

### ISSUE THREAD

**Issue by mrares** [jupyter/notebook#471]
This is a feature request, for usability reasons it would be beneficial if users could move files between Folders in the file view, allowing them to organise their notebooks after creation.

**Comment by hosemn** [comment]
I ran into this lately, also, but discovered a work-around (non-ideal, but usable when SSH is not an option or the notebook server is not local): rename the notebook from the UI, but put the desired directory path in front of the name. The notebook server will relocate the notebook into the directory. I also think it would be nice to have a UI element for moving a notebook, but for now you should be able to work around it using this.

**Comment by mrares** [comment]
Yes, that is one very creative solution, I will use it as a workaround for now.

**Comment by NHDaly** [comment]
I'm working on a pull request now to add moving files. :)

**Comment by SandboChang** [comment]
I have another solution, which may not be ideal in terms of data security but is easy to implement:
Simply link the root directory to Dropbox.

This is the current way I am running one server for my group in the university. Dropbox allows an easy way to manage multiple files using their website, however if your codes are very sensitive then you may not want them on Dropbox for unknown disclosure issue.

**Comment by annieeby** [comment]
Renaming with directory path yields this error: 

"Invalid notebook name. Notebook names must have 1 or more characters and can contain any characters except :/\. Please enter a new notebook name."

my attempted file name (to move to folder Flatiron Introduction to Python):
./Flatiron Introduction to Python/Lists With Maps

**Comment by Vinayk93** [comment]
**SOLUTION**:-
jupyter create ipynbcheckoint folder for the files previous state.
open file explorer look for that folder inside ipynbcheckpoint (hidden) most of the cases.
Create your new file there.

**Comment by jmg** [comment]
I made some improvements over the move functionality by adding a folder selector. The PR is https://github.com/jupyter/notebook/pull/4604

**Comment by MrAnalyticals** [comment]
A workaround solution I use is to download the notebook file to your local machine and then upload it to the required folder, not forgetting to delete the old version from the wrong location of course.
