### ISSUE TITLE
Fix Broken PIP Install

### ISSUE THREAD

**Issue by codemonkeyrawks** [jupyter/notebook#4743]
Hello There,

I see that when looking at PyPi the latest version of Jupyter is version 1.0 and your releasing on github version 5.7 and master. Is there any plans on updating this on a regular basis or is pulling from Github the only option now. If github is the only option I would suggest removing this from PyPi so people don't get confused on what software is current.

**Comment by kevin-bates** [comment]
Hello,

If you're referring to this [pypi page](https://pypi.org/project/jupyter/), `pip install jupyter` is a metapackage that merely ensures at least _some version_ of [these packages](https://github.com/jupyter/jupyter/blob/master/setup.py#L27-L32) are installed.  As a result, if you already had Notebook 5.7 installed, it would do nothing to that installation.

[Notebook releases are fairly regular](https://pypi.org/project/notebook/#history), although its been a few months.  5.7.8 was made available in April and, just last week, the 6.0.0rc1 pre-release was produced.  As a result, you might instead try updating the package directly (e.g., `pip install notebook --upgrade`).  This should update your environment to Notebook 5.7.8.

In looking at the [jupyter repo](https://github.com/jupyter/jupyter), I get the impression its for the initial seeding of a system primary jupyter components and general documentation. 

I hope that helps.
