### ISSUE TITLE
Connection Failed: failed to connect to kernel when set up in a remote server (websocket related)

### ISSUE THREAD

**Issue by cqcn1991** [jupyter/notebook#4757]
Hi, I'm trying to setup Anaconda and Jupyter in a remote server.

This is how I set it up in a remote server

```
docker run -p 8888:8888 -i -t continuumio/anaconda3 /bin/bash
jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser
```

After whitelisting port 8888, I'm able to visit jupyter notebook. However, I can't connect to the kernel. And the websocket reports 400 error

![image](https://user-images.githubusercontent.com/2425141/60949883-af810b80-a328-11e9-9cc0-eec191608876.png)

If I run the command locally in docker. I'm able to run code in jupyter.

How can I connect to jupyter in a remote server?

---- 

Some potential solutions:

- Downgrade to tornado 4.5.3 as in https://github.com/jupyter/notebook/issues/2664 : I tried, but doesn't work for me.
- Nginx websocket setup, as in https://github.com/jupyter/notebook/issues/625 : Have not tried.
- Using browser Firefox and Chrome as in https://github.com/jupyterhub/jupyterhub/issues/2595 : both browsers have the same problem.

**Comment by cqcn1991** [comment]
It's finally solved when open with `allow_origin`

**Comment by xiaoliuyang97** [comment]
我也遇到和你一样的问题  请问你最终是怎么解决的  可以稍微详细一点点指导我一下吗  真的到处找了很多办法都没用  谢谢你
