### ISSUE TITLE
6.0.0 release

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/notebook#4763]
I noticed the 6.0.0rc1 release that was done a few days ago. What is the target deadline for 6.0?

**Comment by lresende** [comment]
Discussions are happening [here](https://github.com/jupyter/notebook/issues/4698). I was aiming for today but got sidetracked and will try a little later or tomorrow.

**Comment by SylvainCorlay** [comment]
Thanks! Closing this.
