### ISSUE TITLE
jupyter notebook is not rendering

### ISSUE THREAD

**Issue by a1bhi2** [jupyter/notebook#4767]
My following notebook is not rendering 
https://github.com/a1bhi2/Hospital_locator/blob/master/mainproj.ipynb

how should i fix this?

**Comment by a1bhi2** [comment]
now it automatically working

**Comment by jasongrout** [comment]
Please file a support request with GitHub if their notebook rendering is not working. We have no control over how notebooks render on GitHub.

c.f. #3035
