### ISSUE TITLE
Feature Request: Dark mode.

### ISSUE THREAD

**Issue by timkofu** [jupyter/notebook#4770]
Would It be possible to implement dark mode?

**Comment by yavalvas** [comment]
There are third-party implementations such as:
[jupyter-themes](https://github.com/dunovank/jupyter-themes)

I guess with one theme others can be requested, so it makes less sense implementing it in this repo.

**Comment by timkofu** [comment]
Dark-mode is about preserving sight, so that one theme would make sense if it was part of core Jupyter.

However, that jupyter-themes has a theme or two that are also easy on the eyes.
