### ISSUE TITLE
Using `NotebookTestBase` for testing server extension outside of the notebook repo

### ISSUE THREAD

**Issue by hadim** [jupyter/notebook#4787]
I tried to use `NotebookTestBase` for a custom server extension at https://github.com/hadim/jupyter-archive/issues/1 but it looks like `NotebookTestBase` does not load/discover custom extension and so tests obviously failed.

Don't you think `NotebookTestBase` should be reusable across the server extension ecosystem?

I also found that it could be useful to `nb_conda`: https://github.com/Anaconda-Platform/nb_conda/blob/c27196f15528b92c808cff1123a7579ba046d180/nb_conda/tests/test_api.py#L43

**Comment by fcollonval** [comment]
A solution is to activate the extension by overwriting the `config` class attribute:

```python
from notebook.tests.launchnotebook import NotebookTestBase
from traitlets.config import Config

class MyExtensionTest(NotebookTestBase):
    config = Config({'NotebookApp': {"nbserver_extensions": {"jupyter_archive": True}}})
```

I submit a [PR in your repo ](https://github.com/hadim/jupyter-archive/pull/7) 😄

**Comment by hadim** [comment]
Thanks @fcollonval . I guess I can close then.
