### ISSUE TITLE
Docs: notebooks rendering and broken link

### ISSUE THREAD

**Issue by tritemio** [jupyter/notebook#479]
It is probably a known issue, but the [notebook examples](http://jupyter-notebook.readthedocs.org/en/latest/examples/Notebook/Examples%20and%20Tutorials%20Index.html) integrated in the Sphinx documentations are not rendering well. In particular, [images](http://jupyter-notebook.readthedocs.org/en/latest/examples/Notebook/Notebook%20Basics.html) and many [LaTeX equations](http://jupyter-notebook.readthedocs.org/en/latest/examples/Notebook/Typesetting%20Equations.html) are not rendered.

Also, there is a broken link that prevents accessing the original notebook here

http://jupyter-notebook.readthedocs.org/en/latest/examples/Notebook/Configuring%20the%20Notebook%20and%20Server.html

Finally the link "Edit on GitHub" is broken for rendered notebook.

**Comment by Carreau** [comment]
Thanks, we'll try to work on that !

**Comment by willingc** [comment]
@tritemio Thanks.

@carreau @minrk Would you mind checking if Read the Docs is getting our latest docs changes? Thanks.

**Comment by tritemio** [comment]
@willingc, you are right. The latest RTD version is e122f061d8441618136d486edf759e50bbfe40a6, which is a commit  from August 19. All the recent build are failing:

https://readthedocs.org/projects/jupyter-notebook/builds/

RTD may have updated sphinx and other things that broke the docs building here.

**Comment by Carreau** [comment]
@jdfreder @minrk or @takluyver can you make me admin on rtd for this repo ?

**Comment by Carreau** [comment]
Also I think we could make @willingc admin on rtd too.

**Comment by jdfreder** [comment]
I added @willingc and @Carreau : )  Let me know if you have trouble using it.

**Comment by willingc** [comment]
@jdfreder Thanks :sunflower:

**Comment by willingc** [comment]
I just added a PR #492 as a follow up to #488.

**Comment by willingc** [comment]
Recommendation: refactor docs to use `nbgrader`'s model for autogenerating rst from ipynb. This would enhance maintainability of docs. See note #494

**Comment by minrk** [comment]
@willingc good idea.
