### ISSUE TITLE
Define custom cell types?

### ISSUE THREAD

**Issue by leotrs** [jupyter/notebook#4801]
Is there a way to define custom cell types? Right now there are code cells, markdown cells, and raw cells. Say I want a fourth type that is just like a markdown cell but always has a gray background (or any other arbitrary CSS setting). How to do this?

A search for nbextensions that do this did not yield any results, so I thought I'd ask here. Thanks!

**Comment by jasongrout** [comment]
The Jupyter notebook format does not allow for more cell types.

**Comment by leotrs** [comment]
I think I can modify the [LaTeX extension](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/latex_envs/README.html) for my purposes. Thank you!
