### ISSUE TITLE
CodeMirror multiplex mode for magic\_ MIME types seems to be broken

### ISSUE THREAD

**Issue by gramster** [jupyter/notebook#483]
As I understand it, the 'magic\_' prefix on a MIME type is meant to have CodeMirror use a multiplex mode  to format the magic line differently to the rest of the cell, namely as plain/text (logic for this is in notebook/static/notebook/js/cell.js). However, unless this is meant to apply just to '%%' (which seems unlikely) it doesn't work. The magic line is getting formatted the same as the cell.

You can see this pretty easily; just put '%%python3 def foo bar' at the start of a cell and notice how the different terms get highlighted.

This can cause some strange behavior. E.g. do %%python3 """ and then type stuff in the cell; it will be fomatted as a multi-line string (but will not be interpreted as such).

**Comment by Carreau** [comment]
So I'll investigate more deeply, but IIRC, there are some issues, where indeed it might not be possible for he `magic_foo` mode to switch syntactic coloration at the end of the line, which probably screw up some modes. Someone will have to dive into Codemirror multiplexing.

**Comment by gramster** [comment]
If it helps at all, I created a simple hack for one case where I simply added a firstLine flag to the state object for the mode. In the mode, if firstLine was true I set it to false and ate the line, returning in our case 'keyword' for the token type.

Perhaps something like that with an overlay rather than a multiplexor may work.

**Comment by gramster** [comment]
It's possible that replacing that multiplexing mode that gets created in cell.js with this will work better:

   CodeMirror.defineMode(magic_mode, function(config) {
     var magicOverlay = {
       startState: function() {
         return {firstMatched : false}
       },
       token: function(stream, state) {
         var matched = null;
         if(!state.firstMatched) {
           state.firstMatched = true;
           if (stream.match("%%")) {
             matched = "magic"; // or whatever token you want the first line to match
           }
         }
         stream.skipToEnd();
         return matched;
       }
     };
     return CodeMirror.overlayMode(spec, magicOverlay);
   });

**Comment by gramster** [comment]
Ah, I have a better version which seems to work. 

    CodeMirror.defineMode(magic_mode, function(config) {
      var magicOverlay = {
        startState: function() {
          return {firstMatched : false, inMagicLine: false}
        },
        token: function(stream, state) {
          if(!state.firstMatched) {
            state.firstMatched = true;
             if (stream.match("%%", false)) {
              state.inMagicLine = true;
            }
          }
          if (state.inMagicLine) {
            stream.eat(function any(ch) { return true; });
            if (stream.eol()) {
              state.inMagicLine = false;
            }
            return "magic";
          }
          stream.skipToEnd();
          return null;
        }
      };
  return CodeMirror.overlayMode(CodeMirror.getMode(config, spec), magicOverlay);
});

**Comment by ellisonbg** [comment]
@Carreau do you think there is anything for us to do on this for 4.1?

**Comment by Carreau** [comment]
Bah, that have been broken for [a long time](https://github.com/ipython/ipython/issues/4836#issuecomment-33897907). If someone make a working PR i'm all for it, but it's not blocker.

**Comment by minrk** [comment]
closed by #498
