### ISSUE TITLE
Shutdown button under running tab is not working

### ISSUE THREAD

**Issue by anshmittal01** [jupyter/notebook#4867]
If we click the shutdown button which appears when we select any running file, the file stops running but shutdown button under the running tab is not working.
Please fix this issue.

**Comment by marhoy** [comment]
I have the same problem, both with version 6.0.0 and the newly released 6.0.1.
It works with notebook version 5.7.8.

**Comment by hanyunfan** [comment]
Same issue with 5.4.1

**Comment by astroboylrx** [comment]
I also have the same issue. Both on Mac and on Linux, both on Safari and Chrome (private or incognito does not help).

**Comment by utommo** [comment]
I'm also having this issue. On Windows 10, python 3.7.0, both in chrome and edge. 

jupyter --version

jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : not installed
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.3
jupyter lab      : 1.1.4
nbconvert        : 5.6.0
ipywidgets       : not installed
nbformat         : 4.4.0
traitlets        : 4.3.2

**Comment by merlin1608** [comment]
Hello,
Same issue on every browsers on Linux
jupyter core     : 4.5.0
jupyter-notebook : 6.0.0
qtconsole        : 4.5.1
ipython          : 7.6.1
ipykernel        : 5.1.1
jupyter client   : 5.3.1
jupyter lab      : 1.0.2
nbconvert        : 5.5.0
ipywidgets       : 7.5.0
nbformat         : 4.4.0
traitlets        : 4.3.2

**Comment by Sorkanius** [comment]
Same here!

jupyter                  1.0.0    
jupyter-client           5.3.1    
jupyter-console          6.0.0    
jupyter-core             4.5.0  
ipykernel                5.1.2    
ipython                  7.8.0    
ipython-genutils         0.2.0    
ipywidgets               7.5.1

**Comment by lonelykid** [comment]
Same issue here
Win 10 1803 + Chrome 77
jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.3
jupyter lab      : not installed
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

Someone reported this to JupyterLab. They pushed a fix for it. I don't use JupyterLab.

**Comment by jasongrout** [comment]
This is fixed in #4939, which was merged into master, but not released yet.
