### ISSUE TITLE
Request to call 'api/shutdown' after expiration of shutdown_no_activity_timeout

### ISSUE THREAD

**Issue by c3-dennis** [jupyter/notebook#4868]
Use case:
We have an `nbserver_extensions` to override the shutdown handler to perform some extra logic upon notebook shutdown. This handler is for path `api/shutdown`, which is requested when the Jupyter quit button is clicked.

Problem:
As can be seen in the following function, `api/shutdown` is not requested during a shutdown due to timeout.
https://github.com/jupyter/notebook/blob/70d74d21ac051fbeaa81d4ef4fff9fa759de96d7/notebook/notebookapp.py#L1640

Request:
Update implementation of `shutdown_no_activity` to make a request to `api/shutdown`, instead of calling `self.stop()`.

**Comment by jtpio** [comment]
Closing as Jupyter Server is now being developed in https://github.com/jupyter-server/jupyter_server.

Feel free to open a new issue there is it is still relevant, thanks!
