### ISSUE TITLE
Saving file on gvfs mounted file system give error

### ISSUE THREAD

**Issue by jfear** [jupyter/notebook#489]
I have having a strange issue with jupyter notebook interacting with gvfs mounts.

Steps to replicate:
1) Mount a location using GVFS
2) start jupyter notebook
3) Create a new notebook on GVFS mount point
4) Add something to the first cell and try to save notebook

The new notebook file is created, but is empty. Instead it is saved to a hidden file './~.${NOTEBOOKNAME}.ipynb' and an error thrown by the notebook server (below).

If I use the local file system or mount using CIFS then everything works fine.

I am guessing it may have something to do with special characters in the path that GVFS creates. I tried using symlinks to abstract this path, but Jupyter seems to find the full path.

Any advice would be appreciated.

Distro: Linux Mint 17.2
Python: 2.7.6
Jupyter: 4.0.6

Jupyter server output:

```
[E 13:44:45.612 NotebookApp] Error while saving file: Untitled.ipynb [Errno 95] Operation not supported: '/run/user/1000/gvfs/sftp:host=127.0.0.1,user=jfear/home/jfear/tmp/.~Untitled.ipynb'
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/notebook/services/contents/filemanager.py", line 386, in save
self.save_notebook(os_path, nb)
File "/usr/local/lib/python2.7/dist-packages/notebook/services/contents/fileio.py", line 198, in save_notebook
with self.atomic_writing(os_path, encoding='utf-8') as f:
File "/usr/lib/python2.7/contextlib.py", line 17, in __enter
return self.gen.next()
File "/usr/local/lib/python2.7/dist-packages/notebook/services/contents/fileio.py", line 131, in atomic_writing
with atomic_writing(os_path, args, *kwargs) as f:
File "/usr/lib/python2.7/contextlib.py", line 17, in enter
return self.gen.next()
File "/usr/local/lib/python2.7/dist-packages/notebook/services/contents/fileio.py", line 71, in atomic_writing
shutil.copy2(path, tmp_path)
File "/usr/lib/python2.7/shutil.py", line 131, in copy2
copystat(src, dst)
File "/usr/lib/python2.7/shutil.py", line 98, in copystat
os.utime(dst, (st.st_atime, st.st_mtime))
OSError: [Errno 95] Operation not supported: '/run/user/1000/gvfs/sftp:host=127.0.0.1,user=jfear/home/jfear/tmp/.~Untitled.ipynb'
[W 13:44:45.613 NotebookApp] Unexpected error while saving file: Untitled.ipynb [Errno 95] Operation not supported: '/run/user/1000/gvfs/sftp:host=127.0.0.1,user=jfear/home/jfear/tmp/.~Untitled.ipynb'
[E 13:44:45.613 NotebookApp] {
"Content-Length": "500",
"Accept-Language": "en-US,en;q=0.5",
"Accept-Encoding": "gzip, deflate",
"Connection": "keep-alive",
"Accept": "application/json, text/javascript, /; q=0.01",
"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0",
"Host": "localhost:8889",
"X-Requested-With": "XMLHttpRequest",
"Referer": "http://localhost:8889/notebooks/Untitled.ipynb",
"Content-Type": "application/json; charset=UTF-8"
}
[E 13:44:45.613 NotebookApp] 500 PUT /api/contents/Untitled.ipynb (127.0.0.1) 17.92ms referer=http://localhost:8889/notebooks/Untitled.ipynb
```

**Comment by minrk** [comment]
@jfear can you test #491 and see if it fixes the issue?

**Comment by jfear** [comment]
@minrk I was unable to get `self._copy()` to work, but if I used `shutil.copyfile()` everything works as expected. 

I am new to this so I want to be explicitly describe what I did.

I had tried to cloning your `minrk/notebook:copystat-can-fail` branch, but was getting some errors with bootstrap.min.js. 

I ended up applying the patch myself using `jupyter/notebook:master`. Could this be why self._copy() was not working??

**Comment by martinosorb** [comment]
The conclusion is not clear to me. I have the same problem: if I launch, locally, the ipynb server in a gfvs mounted directory, I'm unable to save any notebook.
Note that this was NOT the case previously, it's an issue that I've seen only since I installed ipython3.
