### ISSUE TITLE
Can't define new commands for LaTeX

### ISSUE THREAD

**Issue by fabiofortkamp** [jupyter/notebook#490]
Issue #349 was closed, but I still keep getting the same problems: defining new commands in markdown cells with `$\newcommand{}{}$` does not seem to work.

I'm using jupyter 4.0.6 ((`jupyter --version`), installed with Anaconda, on OS X. The cell were the new command is defined has the same strange output and the cells were the newly defined macro is used are not rendered; I just get the command name in red, like an error.

Here is a sample screenshot:

![image](https://cloud.githubusercontent.com/assets/5197952/10057512/064fb2ba-6217-11e5-9f83-6d0d3a1e822a.png)

**Comment by minrk** [comment]
I believe this is fixed in master, and will be released with notebook-4.1 (`jupyter notebook --version`).

**Comment by rabernat** [comment]
I just hit this issue and it's a big problem for me.

Will 4.1. be released soon? I am using conda for notebook and would prefer to keep it that way.

**Comment by ellisonbg** [comment]
We should confirm that this is fixed @SylvainCorlay is saying it isn't...

**Comment by ellisonbg** [comment]
Fixed and closing...

**Comment by minrk** [comment]
> Will 4.1. be released soon?

Yes, we are getting it ready for release in the next week or so.

**Comment by juangil** [comment]
I was having this bug also with ipython notebook, i fixed it reinstalling everything with conda, but installing the jupyter notebook directly from the repo, and everything is working nice, :).

**Comment by willingc** [comment]
@juangil Thanks for the report verifying that installing Jupyter notebook from the repo has the LaTeX working nicely. We hope you are enjoying Jupyter notebook too. :book: :smile:

**Comment by stonefly** [comment]
it works in live notebook, but it fails with nbconvert:

I'm using master branch (for both notebook and nbconvert)

"""
    LaTeX Warning: No \author given.
    
    (/usr/local/texlive/2015/texmf-dist/tex/latex/base/omscmr.fd)
    ! Undefined control sequence.
    l.252     \textbackslash{}(\RR
                                  \textbackslash{})
    ? 
    ! Emergency stop.
    l.252     \textbackslash{}(\RR
                                  \textbackslash{})
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.

"""

**Comment by stonefly** [comment]
to let nbconvert generate pdf, we need to define using
\global\def or use \gdef instead of using \def only

however this requires enabling a mathjax extension:

TeX: {
  extensions: ["begingroup.js"]
}
