### ISSUE TITLE
Pycharm shows strange code of Jupyter

### ISSUE THREAD

**Issue by grimwoo** [jupyter/notebook#4902]
I used the pro version (2019.07) of pycharm, and I might have installed all the module needed.
But when I open the try.ipynb file, I shows this stuff (figure attached below). Could anyone help me? 

![Jupyter](https://user-images.githubusercontent.com/49429496/65296312-9e5d4200-db96-11e9-901b-d0d9f7ee666b.png)
![interpreter](https://user-images.githubusercontent.com/49429496/65296315-9e5d4200-db96-11e9-9e3a-ae10d8ebd921.png)

![65381215-81a04600-dd1f-11e9-8ee8-8ce3905ec021](https://user-images.githubusercontent.com/49429496/65381460-67b53200-dd24-11e9-8240-f098a02a4d83.png)

**Comment by kevin-bates** [comment]
This is the raw notebook file - its just json.  If you were to run `jupyter notebook` from the directory in which this file is located, then open this file from the web browser page that the command opens, you should see a Python 3 kernel with what looks like an empty cell (i.e., the default notebook).

**Comment by grimwoo** [comment]
@kevin-bates thanks. But I really want to open it in Pycharm

**Comment by grimwoo** [comment]
Hi, I deleted the ".ipyng" in othors and added it in Jupyter Notebook in "Settings | Editor | File Types ". And then I closed the current ".ipynb" file and re-open it, and it worked! Many thanks to you and the support team of Pycharm!
