### ISSUE TITLE
Shell we remove py2 dependence in jupyter notebook?

### ISSUE THREAD

**Issue by 00Kai0** [jupyter/notebook#4922]
I saw the new `setup.py` in notebook shows:
```python
    error = """
Notebook 6.0+ supports Python 3.5 and above.
When using Python 3.4 or earlier (including 2.7), please install Notebook 5.x.

Python {py} detected.
{pip}
""".format(py=sys.version_info, pip=pip_message )

```

So the new notebook just supports `py>=3.5`.

And I saw many codes like:
```python
try: #PY3
    from base64 import encodebytes
except ImportError: #PY2
    from base64 import encodestring as encodebytes

```

Is it time to remove them?
I wanne try to do this.

**Comment by takluyver** [comment]
Fixed by #4936 (as far as I know - please feel free to open further PRs if there's more compatibility code that can be removed)
