### ISSUE TITLE
jupyter kernelspec remove -y broken

### ISSUE THREAD

**Issue by lramey** [jupyter/notebook#4925]
-y is ignored no matter where I put it in the command string.
-f works.

**Comment by kevin-bates** [comment]
@lramey - thanks for opening this issue.  The KernelspecApp is actually in the [jupyter_client](https://github.com/jupyter/jupyter_client) repo.  Would you mind "moving" this issue there and closing this one?

If you'd like to contribute a fix for this, that would be great.  I'd be happy to assist you if you need any help with that.

**Comment by kevin-bates** [comment]
Or better yet, can someone with appropriate privileges transfer this issue to `jupyter_client`?

cc: @minrk, @takluyver, @jasongrout, @lresende, @Zsailer

**Comment by lramey** [comment]
I'll open it in the right place.
