### ISSUE TITLE
kernel spec names case sensitivity

### ISSUE THREAD

**Issue by lramey** [jupyter/notebook#4930]
My code does this:

cmd = L"ipython kernel install --prefix " + userJupyterKernels + L" --name " + nameStr + L" --display-name " + nameStr;

Where nameStr is something like "TestEnv"

if I put break points in and look at the list after I do this I get this (from a command prompt):
(JupyterTool_vEnv) S:\Alteryx\bin_x64\Debug\Miniconda3\envs>jupyter kernelspec list
Available kernels:

  testenv             S:\Alteryx\bin_x64\Debug\Miniconda3\share\jupyter\kernels\testenv
  
But if you try to remove that kernel:

(JupyterTool_vEnv) S:\Alteryx\bin_x64\Debug\Miniconda3\envs>jupyter kernelspec remove TestEnv
Couldn't find kernel spec(s): TestEnv

Sending in "testenv" will work.

It looks like it lower cases things on the way in, but doesn't lower case them during remove.... which is sort of annoying since I'm doing this all programatically and I am sending in the same string to both commands. (I solved it... I can lower case my string on delete... but its sort of odd and I had to leave a big comment about why)

**Comment by kevin-bates** [comment]
Again, wrong repo - same exercise as https://github.com/jupyter/notebook/issues/4925.  Kernelspec names are case insensitive, so 'remove' should be as well.

**Comment by lramey** [comment]
This goes in the jupyter-client repo?

**Comment by kevin-bates** [comment]
Yes, its the same application (KernelspecApp).
