### ISSUE TITLE
jupyter notebook Error executing Jupyter command 'notebook': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by psbill2614** [jupyter/notebook#4966]
Hi just installed Anaconda 2.1.0 (x86_64) for one of my course on MAC OS. 
()Installation went OK
()PATH was updated
()ran the following commands and all seem to go OK.
     >> conda update conda
     >> conda update ipython
     >> conda update pip
     >> conda install bokeh
()version query returns
      conda --version
      conda 4.4.9

As per the instruction i should have notebook package installed.
But i get the follwing error 

XXXXX@Admins-MacBook-Pro ~ $ jupyter notebook
Error executing Jupyter command 'notebook': [Errno 2] No such file or directory

conda list only has ipython notebook

gsandhu@Admins-MacBook-Pro ~ $ conda list | grep notebook
ipython-notebook          2.2.0                    py27_0    <unknown>

Previously i tried updating jupyter using "pip install jupyter" and i was able to start the notebook but then there were issues in kernal . So i uninstalled everything and started from fresh.

Can anyone please guide me through this?  Thanks in Advance

**Comment by xuejianma** [comment]
> Try jupyter-notebook
> it will tell you to install
> "sudo apt install jupyter-notebook"
> now try "jupyter-notebook"
> works fine

works for me. Thx!

**Comment by MarkintoshZ** [comment]
For those who have tried all of the methods above and still have not get it to work, here is the solution for me:

`python -m jupyter notebook`
or 
`python -m jupyter lab`
(use `python3` or `python3.6` instead of `python` if needed)

Good luck!

**Comment by saurabhprasadsah** [comment]
ipython notebook 

open this command and use this

**Comment by saurabhprasadsah** [comment]
if you are using anconda then use this coomand 
ipython notebook
#4960

**Comment by kpreeti096** [comment]
> Try jupyter-notebook
> it will tell you to install


> "sudo apt install jupyter-notebook"
> now try "jupyter-notebook"
> works fine



"sudo apt install jupyter-notebook"
--it worked for me

**Comment by kpreeti096** [comment]
~$ sudo apt install jupyter-notebook

it will star downloading like this..........

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  fonts-font-awesome fonts-mathjax javascript-common
  jupyter-nbextension-jupyter-js-widgets libjs-backbone libjs-bootstrap
  libjs-bootstrap-tour libjs-codemirror libjs-es6-promise libjs-jed
  libjs-jquery libjs-jquery-typeahead libjs-jquery-ui libjs-marked
  libjs-mathjax libjs-moment libjs-requirejs libjs-requirejs-text
  libjs-text-encoding libjs-underscore libjs-xterm liblua5.1-0 libluajit-5.1-2
  libluajit-5.1-common pandoc pandoc-data python3-bleach python3-entrypoints

**Comment by vinimatos** [comment]
> Try jupyter-notebook
> it will tell you to install
> "sudo apt install jupyter-notebook"
> now try "jupyter-notebook"
> works fine

Work for me! thanks

**Comment by saurabhprasadsah** [comment]
Nop
ipython notebook

Work fine
😊

**Comment by saurabhprasadsah** [comment]
"sudo apt install jupyter-notebook"

This is not working

**Comment by najam2012** [comment]
> It seems to me as though the installation has messed up somehow. Try running:
> 
> # For Python 2
> pip install --upgrade --force-reinstall --no-cache-dir jupyter
> 
> # For Python 3
> pip3 install --upgrade --force-reinstall --no-cache-dir jupyter
> This should reinstall everything from PyPi. This should solve the problem as I think running pip install "ipython[notebook]" messed things up.

Thank you very much

**Comment by saurabhprasadsah** [comment]
yes sure this is running....

**Comment by cheetah90** [comment]
> Same issue fixed for me by updating conda and reinstalling jupyter:
> 
> ```
> conda update -n base conda
> conda install jupyter
> ```

This is the only solution that works for me.

**Comment by saurabhprasadsah** [comment]
yeah sure...
This is working fine...

**Comment by kevin-bates** [comment]
There have been lots of great responses and sufficient success to warrant this issue's closure.  Should others encounter this same issue and have applied the suggested tips, we can either reopen it or create a new issue (preferred).  Thanks to everyone for helping out with this issue.

**Comment by jetcem** [comment]
> For those who have tried all of the methods above and still have not get it to work, here is the solution for me:
> 
> `python -m jupyter notebook`
> or
> `python -m jupyter lab`
> (use `python3` or `python3.6` instead of `python` if needed)
> 
> Good luck!

I appreciate for that, JupyterLab is working with that.
Should I open the JupyterLab always in this way? Could it cause any problem?

**Comment by saurabhprasadsah** [comment]
yes this is also working fine...
`python -m jupyter notebook `
(use python 3 and python3.6)
..

**Comment by seyedali98** [comment]
> For me to solve the problem. instead of installing jupyter with `pip3 install jupyter `as stated on the jupyter website
> 
> In terminal, simply do
> `pip3 install numpy`
> 
> after
> `sudo apt-get install jupyter`
> 
> then run
> `jupyter notebook`
> to launch jupyter.
> 
> Cheers!!!

it's work for me. tnks

**Comment by saurabhprasadsah** [comment]
yeah sure this working fine

**Comment by OXPHOS** [comment]
> Update the `ipykernel` package - it should be fixed by 4.7 or newer. [ipython/ipykernel#278](https://github.com/ipython/ipykernel/pull/278)

Jupyter notebook stopped working once I logged out and logged in again.
This solution worked for me.

**Comment by nhat416** [comment]
> It seems to me as though the installation has messed up somehow. Try running:
> 
> # For Python 2
> pip install --upgrade --force-reinstall --no-cache-dir jupyter
> 
> # For Python 3
> pip3 install --upgrade --force-reinstall --no-cache-dir jupyter
> This should reinstall everything from PyPi. This should solve the problem as I think running pip install "ipython[notebook]" messed things up.

Beautiful. Works great thanks @hemangjoshi37a

**Comment by saurabhprasadsah** [comment]
this is also working....
@nhat416
