### ISSUE TITLE
How to save current Jupyter notebook via API?

### ISSUE THREAD

**Issue by takiholadi** [jupyter/notebook#4967]
I want to achieve "File" -> "Save and Checkpoint" programmatically.

There is "Save file" section in IPython API docs: https://github.com/ipython/ipython/wiki/IPEP-27%3A-Contents-Service#save-file

Tried without success:
```
import requests

response = requests.request(
    method='PUT',
    url='http://127.0.0.1:8888/api/contents/my-notebook.ipynb',
    headers={'Authorization': 'token 6ec2282d28e6e755629e9007787299a929a0154e54c59df7'},
)
print(response.status_code)
print(response.json())
```

**Comment by GF-Huang** [comment]
1 years nobody answer?

**Comment by kevin-bates** [comment]
I'm not sure there's an issue here.  It looks like the previous response must have failed to include a `body`.  

The following `curl` command will place the contents of `empty.ipynb` into the notebook server's `notebook-dir` location into `empty.ipynb`:
```bash
curl -d "@empty.ipynb" -H "Content-Type: application/json" -X PUT http://localhost:8888/api/contents/empty.ipynb?token=7f5af4bf8ce9514e2015c635851d2e343db9f7f9e0c963ff
```

To create the checkpoint (there is not one API request that does both 'save and checkpoint') you'd similarly issue a `POST` to `/api/contents/{path}/checkpoints`:

```bash
curl -d -H "Content-Type: application/json" -X POST http://localhost:8888/api/contents/empty.ipynb/checkpoints?token=7f5af4bf8ce9514e2015c635851d2e343db9f7f9e0c963ff
```

You might also find the swagger (OpenAPI) doc helpful: 
```bash
curl -s -X GET -i http://localhost:8888/api/spec.yaml?token=7f5af4bf8ce9514e2015c635851d2e343db9f7f9e0c963ff
```

FWIW, `empty.ipynb` consists of the following:
```JSON
{
 "cells": [],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 4
}
```
