### ISSUE TITLE
Jupyter Notebook kernel dies - Tensorflow-gpu 1.15/2.0 

### ISSUE THREAD

**Issue by sniafas** [jupyter/notebook#4979]
![Screenshot from 2019-10-17 13-02-04](https://user-images.githubusercontent.com/4542013/66999418-a4373c00-f0de-11e9-95a1-712f2a377f21.png)
Working on Debian 10, I have compiled and tried both of **Tensorflow 1.15 and 2.0** from source neither worked, with **Python3.6**, **Cuda 10.1** and **cudnn 7.6** support, in an virtual environment.
Importing tensorflow from python/ipython cli or running .py sources runs pretty fine.

I am providing some details of environmental variables derived from **os.environ**

`'LD_LIBRARY_PATH': '/usr/local/cuda-10.1/lib64:/usr/local/cudnn/lib64:'`
 `'VIRTUAL_ENV': '/home/steve/.virtualenvs/tf_dev'`
`'PATH': '/home/steve/.virtualenvs/tf_dev/bin:/usr/local/cuda-10.1/bin:/usr/local/cudnn/bin:/home/steve/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games','CUDNN_PATH':'/usr/local/cudnn'`
`'VIRTUAL_ENV': '/home/steve/.virtualenvs/tf_dev'`

I don't mind if downgrading tensorflow to few versions but not below 1.11 will be profitable but I don't think that's a tensorflow issue at all.

Any thoughts?

**Comment by SrushtiRS** [comment]
Facing similar problem.
Running system on TRX 2080 GPUs. So can't go below TensorFlow 2.0.

Any suggestions would be highly appreciated.

**Comment by sniafas** [comment]
> Facing similar problem.
> Running system on TRX 2080 GPUs. So can't go below TensorFlow 2.0.
> 
> Any suggestions would be highly appreciated.

Yes I am still stuck on this. If you could reproduce the issue it might get solved

**Comment by SrushtiRS** [comment]
System details:
windows 10
2 GPUS: both RTX 2080Ti
AMD Ryzen 7 CPU
Python: 3.6.7
Miniconda3
Tensorflow-gpu: 2.0.0
CUDA: v10
CuDNN: 7.3.1

I can import tensorflow fine both on anaconda prompt and jupyter notebooks.

Attempting to execute following code:
tf.debugging.set_log_device_placement(True)
# Create some tensors
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)
print(c)

Runs on anaconda prompt, but very slow compared to the data involved in the operation.
When attempted to run in Jupyter, it runs all the commands till definition of c. But when I try to execute print(c) statement, it kills the notebook.

On a side note, when I run tensorflow in anaconda prompt, i get a message saying
2019-11-05 16:19:23.843229: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-11-05 16:19:24.138873: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-05 16:19:24.143877: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2019-11-05 16:19:24.901541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-05 16:19:24.905581: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1
2019-11-05 16:19:24.908120: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N
2019-11-05 16:19:24.913134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N

**Comment by sniafas** [comment]
> System details:
> windows 10
> 2 GPUS: both RTX 2080Ti
> AMD Ryzen 7 CPU
> Python: 3.6.7
> Miniconda3
> Tensorflow-gpu: 2.0.0
> CUDA: v10
> CuDNN: 7.3.1
> 
> I can import tensorflow fine both on anaconda prompt and jupyter notebooks.
> 
> Attempting to execute following code:
> tf.debugging.set_log_device_placement(True)
> Create some tensors
> a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
> b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
> c = tf.matmul(a, b)
> print(c)
> 
> Runs on anaconda prompt, but very slow compared to the data involved in the operation.
> When attempted to run in Jupyter, it runs all the commands till definition of c. But when I try to execute print(c) statement, it kills the notebook.
> 
> On a side note, when I run tensorflow in anaconda prompt, i get a message saying
> 2019-11-05 16:19:23.843229: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> 2019-11-05 16:19:24.138873: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
> 2019-11-05 16:19:24.143877: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
> 2019-11-05 16:19:24.901541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-11-05 16:19:24.905581: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165] 0 1
> 2019-11-05 16:19:24.908120: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0: N N
> 2019-11-05 16:19:24.913134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1: N N

That is completely irrelevant with the posted issue. Your problem might be due to your AMD cpu

**Comment by kernelizd** [comment]
Same problem when running this tut
https://www.tensorflow.org/tutorials/generative/cvae

Windows machine
Titan RTX  GPUs

**Comment by sniafas** [comment]
I have found a possible solution and workaround for this. I have created a new gpu kernel for jupyter.

`python -m ipykernel install --user --name tf-gpu --display-name "TensorFlow-GPU"`

and now tensorflow-gpu load and works seamlessly. I have tested in a compiled from source tf 1.14 version, but I don't think would be any problem for other versions.
