### ISSUE TITLE
Accidentally deleted my desktop map from the comuter  

### ISSUE THREAD

**Issue by yousuftufail** [jupyter/notebook#4988]
Hi there,

I have accidentally deleted my whole desktop while I was online on Jupyter. I have checked all recycle bin, nothing is there. I have also checked my hard dive space and it is increased now. Is there any way to recover those deleted folders. These are extremely important for me. My whole PhD thesis, all my projects and all the programmings  of MatLab and python have deleted. I am happy to pay but I want those file to be recovered. Really really painful.

**Comment by jishanshaikh4** [comment]
This is not the right location for file recovery issues. You should consult support from any vendor for recovery software for Windows/Linux/Mac. Or you should try looking for open source solutions. Jupyter Notebook should not be responsible for what happened to your desktop. Right?

**Comment by yousuftufail** [comment]
ok
