### ISSUE TITLE
JN adds automatically unnecessary quotes to the file path

### ISSUE THREAD

**Issue by Sodbo** [jupyter/notebook#4996]
Dear JN developers,

I am using JN with R Kernel. I used to use an autocompletion of paths to files a lot and it had worked fine. However, a few months ago autocompletion changed its behavior. It adds unnecessary quotes to the path that blocks me to use TAB again to go deeper into the folders. Screenshots are attached. Configuration of my server, JN version, and IRkernel version are attached. 

![Screenshot from 2019-10-23 16-45-50](https://user-images.githubusercontent.com/7702600/67380952-50809300-f5b5-11e9-8f81-7761a1f2a112.png)

![Screenshot from 2019-10-23 16-46-02](https://user-images.githubusercontent.com/7702600/67380950-50809300-f5b5-11e9-8190-a789c8f187a0.png)

JN version: 5.7.0

R version
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes

IRkernel version: Version: 1.0.2

**Comment by yhf8377** [comment]
Happened to me too.

**Comment by kevin-bates** [comment]
This feels like an issue with IRkernel and I see its master branch includes a [fix relative quotes and completions](https://github.com/IRkernel/IRkernel/commit/c2c5e798449fc721462b599f2650a7633d7fc0b9) - assuming I'm interpreting that code correctly.  I suggest opening an issue in [IRkernel](https://github.com/IRkernel/IRkernel/issues). 

I'm closing this issue for now and happy to reopen it should we determine this is an issue that this repo should address.
