### ISSUE TITLE
Delete shortcut "D,D" does not work on chrome/firefox on mac osx

### ISSUE THREAD

**Issue by motleytech** [jupyter/notebook#500]
The `D,D` shortcut specified in the help menu seems to do nothing on chrome and firefox on osx. I have not tested on windows/linux, so it might work there. I am running the following (from notebook help -> about)

```
Server Information:

You are using Jupyter notebook.

The version of the notebook server is 4.0.4-afa88da and is running on:
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3]

Current Kernel Information:

Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.
```

The `x` cut cell shortcut works on both chrome and firefox. If this is what users should use, then we only need to fix the documentation... but it still is a hack and it might remove the last copied cell from the clipboard (without letting the user know).

**Comment by ellisonbg** [comment]
Are you sure you are typing it correctly - the actual keystrokes are `d d` (no comma char).

**Comment by motleytech** [comment]
Feel like an idiot... I should have tried the dd (duh vim). The comma threw me off.

**Comment by tnearey** [comment]
Hmm. I got stuck on this too. But I don't feel like an idiot. I feel  like I've been misled by inadequate documentation. Are there any other characters in the shortcuts that shouldn't actually be typed?

**Comment by takluyver** [comment]
When you see e.g. 'Shift-M', the - shouldn't be typed.

**Comment by tnearey** [comment]
Fair enough. 
But hyphenation is a pretty common convention with “mode keys”, meaning ‘simultaneously pressing the two keys joined by -’ ?
(So common, I didn’t even notice it was there.)
Can the same be said for  comma (in the meaning 'sequentially pressing the keys separated by , ‘) in any domain?


> On Mar 29, 2016, at 11:47 AM, Thomas Kluyver <notifications@github.com> wrote:
> 
> When you see e.g. 'Shift-M', the - shouldn't be typed.
> 
> On 29 March 2016 at 10:10, tnearey <notifications@github.com> wrote:
> 

Terrance Nearey
t.nearey@ualberta.ca

**Comment by takluyver** [comment]
I don't know of many applications that have shortcut sequences like that. Emacs appears to use spaces to separate consecutive parts of a shortcut. Maybe that would be a bit better, but I suspect someone is going to get confused whatever we put.

**Comment by dionisos2** [comment]
I got confused too. And I also believe people will get confused by any notation.
I think it should be made explicit in the help page than "X,X" mean "press X two times quickly".

**Comment by VitorTS** [comment]
> but I suspect someone is going to get confused whatever we put.
I think it's a good idea to just write what you are supposed to do in parenthesis instead of using a shorthand notation like @dionisos2 suggested
