### ISSUE TITLE
Improve navigation to Installation documentation

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#501]
# Current Status
Installation documentation for 'Jupyter Notebook' in the [Jupyter Notebook](https://jupyter.readthedocs.org/en/latest/index.html) documentation is limited. The bulk of the documentation for Jupyter Notebook installation is found in [Jupyter](https://jupyter-notebook.readthedocs.org/en/latest/) documentation.

Additionally, the link in the 'See Also' box within [The Jupyter Notebook Introduction Section](https://jupyter-notebook.readthedocs.org/en/latest/notebook.html) redirects to minimally helpful IPython documentation.

## Screen capture of current user experience
![install_docs_user_experience](https://cloud.githubusercontent.com/assets/2680980/10118221/447fca58-6428-11e5-8b85-6e146419a388.gif)

# Proposed initial solution
[ ] Fix the see also box link to redirect to Jupyter installation on RTD
[ ] Add links in 'Jupyter Notebook' table of contents to *Installation*, *Running the Notebook*, *Migrating from IPython* docs at 'Jupyter' docs.

## Screen capture with initial solution changes
![install_docs_user_experience_new](https://cloud.githubusercontent.com/assets/2680980/10118308/b6cec09a-6429-11e5-8708-2942544285d7.gif)

In a larger Jupyter documentation refactor, navigation between the 'Jupyter' and 'Jupyter Notebook' documentation should be seamless. Using Git submodules in the Jupyter docs would be one approach.

**Comment by minrk** [comment]
Let's avoid submodules. They were a source of constant problems when we used them in IPython. I think intersphinx should provide everything we need to link back and forth, and we just need to be more judicious about providing the links. Does that seem sufficient?

**Comment by willingc** [comment]
@minrk The main issue with Intersphinx is that it can't be used in toctrees. 

Sentry has a good approach to creating docs from multiple repos https://github.com/getsentry/sentry-docs

**Comment by minrk** [comment]
Sentry uses submodules everywhere, and I think that would not be a good fit for us. Using submodules would mean that every PR against any repo with docs must also be a PR against the docs repo to update the ref for the submodule.

**Comment by willingc** [comment]
@minrk Reasonable point. I think Sentry is using a doc sync hook to monitor changes in the individual repos to avoid the extra docs PR.

Either way it is likely simpler to write a work around to the Sphinx/intersphinx toctree limitation and create/use something that wraps and bundles all of the docs with minimal need for manual changes as individual repos change.

**Comment by ellisonbg** [comment]
Yeah, I don't think we want to do down the submodules path for our docs. If
we got to the point where we wanted fully integrated docs, I think it would
make more sense to just put them all in one repo.

I think we can get most of the integration we want with a very minimal work
- possibly without mucking with the intersphinx/toc stuff. I think the
starting point should be a manually shared and well designed Subproject
landing page that each repo has in the same place. We could maintain the
master copy of that file in jupyter/jupyter and just copy it into place
whenever it changes (which should only be when new subprojects come and go).

On Mon, Sep 28, 2015 at 12:28 PM, Carol Willing <notifications@github.com>
wrote:

> @minrk <https://github.com/minrk> Reasonable point. I think Sentry is
> using a doc sync hook to monitor changes in the individual repos to avoid
> the extra docs PR.
>
> Either way it is likely simpler to write a work around to the
> Sphinx/intersphinx toctree limitation and create/use something that wraps
> and bundles all of the docs with minimal need for manual changes as
> individual repos change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/501#issuecomment-143850961>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
closed by #502
