### ISSUE TITLE
Command palette dosen't open

### ISSUE THREAD

**Issue by BarFinish** [jupyter/notebook#5018]
Hi,

I'm using Jupyter notebook 4.4.0.
The command palette dosen't open and in the Chrome console arise the message displayed in the picture.
Does anybody have a solution?

Best,
Bar

![image](https://user-images.githubusercontent.com/57188692/67875746-77a00d00-fb3f-11e9-9bab-62a3c8bd7ab3.png)

**Comment by jtpio** [comment]
Closing as the classic notebook frontend has now been moved to https://github.com/jupyter/nbclassic.

Feel free to open an issue there if it still relevant, thanks!
