### ISSUE TITLE
Question regarding approach to authentication, alternative suggestion

### ISSUE THREAD

**Issue by tleeuwenburg** [jupyter/notebook#504]
I am running Jupyter internally to provide an IPython notebook environment to multiple users. I have looked into the security model provided by Jupyter Hub, and I'm not 100% comfortable with it. It seems to involve running the core process as root, then relying on the server to sudo into userspace to execute the notebooks. Having the server running as root seems inherently open to vulnerability.

I was looking for a simpler username/password challenge based on a simple lookup, with the server running using a low-privilege service role account. It seems like that might provide a stronger sandbox.

It seems to be this could be implement by modifying (or supplying an alternative) LoginHandler within login.py within the auth module. An alternative LoginHandler could then use a simple file lookup containing hashed passwords, or even offer email signup style functionality. I was wondering whether anyone had considered this approach, and what their thinking was in terms of the current implementation?

A simple-ish extension could allow for the hub to load a user/password dictionary whose filename was supplied in the config file, storing hashed passwords based on a configured salt value. This would have to be manually maintained by the server admin, but this would at least give me some greater sense of security at running code inside my intranet. It would be enough for me for now...

**Comment by minrk** [comment]
@tleeuwenburg The Hub most certainly does not need to run as root in general, and you can definitely do what you are asking for right now, without any extension of JuptyerHub at all. The *default* configuration is the simplest, where it needs access to the PAM service and using setuid to switch users. But the design of JupyterHub is focused on making it easy to have custom Authenticators (handle authentication) and Spawners (spawning servers for users). Existing custom Authenticators include using GitHub OAuth, Bitbucket, CILogon, Google OAuth, a simple dictionary, etc. And it's pretty common to use docker to spawn user servers, but you can also use PBS or any other mechanism.
