### ISSUE TITLE
Document contains formatting errors

### ISSUE THREAD

**Issue by 00Kai0** [jupyter/notebook#5063]
When I viewed the document, I saw some confusing parameter.
This one is on `master`, `lastest` and `stable` version:
![2019-11-19 00-32-27 的屏幕截图](https://user-images.githubusercontent.com/26342317/69071169-725e2000-0a64-11ea-848b-cd9e11952641.png)
And this one is on other version:
![2019-11-19 00-33-08 的屏幕截图](https://user-images.githubusercontent.com/26342317/69071565-1ba51600-0a65-11ea-8cff-aa2a59ea3eda.png)

I think something wrong on the stable document. It make me feel that the parameter is `notebook_dirUnicode` not `notebook_dir`.
The `:` is necessary.

**Comment by takluyver** [comment]
The rst for that is actually generated by traitlets, if you want to dig into what's going on:

https://github.com/ipython/traitlets/blob/c95f8483104c2abf6d529a5a0896b8f40f1a310c/traitlets/config/application.py#L541-L547

https://github.com/ipython/traitlets/blob/c3abe9a677967ec9f034e28060140a016ba8812a/traitlets/config/configurable.py#L384-L424

**Comment by 00Kai0** [comment]
thanks @takluyver
