### ISSUE TITLE
init_resources fails for non-root user

### ISSUE THREAD

**Issue by shevelevs** [jupyter/notebook#5070]
When running as non-privileged user, we get an error

...
  File "/.../lib/python3.5/site-packages/notebook/notebookapp.py", line 1420, in init_resources
    resource.setrlimit(resource.RLIMIT_NOFILE, (soft, hard))
ValueError: not allowed to raise maximum limit

I think this is how setrlimit behaves according to the doc (https://docs.python.org/3/library/resource.html) when process is trying to change hard limit as a non-root user.

I think the reasonable behavior would be not to fail unless the config was explicitly specified and is above the default limits for the effective user.

**Comment by shevelevs** [comment]
Related PR: https://github.com/jupyter/notebook/pull/4893

**Comment by takluyver** [comment]
Yes, that sounds reasonable. Do you want to make a PR?

It should probably still warn in that case (as the configured minimum must be higher than the hard limit), and maybe still raise the soft limit to the hard limit if they differ.

**Comment by takluyver** [comment]
Closed by #5075.
