### ISSUE TITLE
overriding browser shortcuts in terminal

### ISSUE THREAD

**Issue by eulerreich** [jupyter/notebook#510]
Currently, in chrome, if I want to recall the previous command in the terminal via `Ctrl+N`, I just get a new window. Also, in a terminal vim setup, I cannot use `Ctrl+W` to move cursor between windows because that would just close the chrome tab.

I'd appreciate if there's an option to disable the native browser shortcuts when the terminal is open.

**Comment by ellisonbg** [comment]
I don't know if this is possible for us to do. You may need to change you browser shortcuts

**Comment by eulerreich** [comment]
Chrome doesn't have an option to change shortcuts.
