### ISSUE TITLE
Can't add main function in cling

### ISSUE THREAD

**Issue by karthikone** [jupyter/notebook#5110]
**Code :**
    #include <iostream>
    using namespace std;
    int main()
    {
        cout<<"hello";
        return 0;
    } 
**Error :**
    input_line_10:4:1: error: function definition is not allowed here
    {
    ^
![Screenshot from 2019-12-09 16-46-46](https://user-images.githubusercontent.com/37996713/70431657-83b6ad00-1aa3-11ea-8d55-025dbd4ab177.png)
`

**Comment by FungluiKoo** [comment]
could you please specify your version and environment? Thanks
