### ISSUE TITLE
(feature request) add standalone input and output consoles/cells for rapid development

### ISSUE THREAD

**Issue by bitworm** [jupyter/notebook#514]
For development purposes, it would be nice if there were an option for input and output cells that existed _outside of the notebook_, and (as an option) always on-screen.  This is a common feature available in many dev. environments.

Why I'm requesting:
a) easier to test/debug small code sections before committing/integrating into current script/notebook
b) for long cells, an easy way to avoid scrolling up and down to compare input and output.

I'd also note that this would not interfere with the current jupyter notebook design; simply closing/hiding/disabling the "console cells" would leave the notebook unchanged.

**Comment by ellisonbg** [comment]
We are working on some things that will provide this type of UI.

**Comment by bitworm** [comment]
Great to hear!  Any suggestions on timescale / what to look out for?

**Comment by ellisonbg** [comment]
Probably in the Jan 2016 range.

On Tue, Oct 6, 2015 at 1:52 PM, bitworm <notifications@github.com> wrote:

> Great to hear! Any suggestions on timescale / what to look out for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/514#issuecomment-145944958>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by JamiesHQ** [comment]
@ellisonbg : can you share the status of this issue at this time?

**Comment by ellisonbg** [comment]
This is addressed by the console in JupyterLab. Closing.
