### ISSUE TITLE
Logging and Clearing Output Slows Firefox

### ISSUE THREAD

**Issue by pfigliozzi** [jupyter/notebook#515]
I noticed some performance issues in Firefox when I recently upgraded to the Jupyter notebook (4.0.5) from IPython Notebook (2.4.1). Firefox becomes really sluggish when running a cell that prints logging information to the output and is constantly being cleared by IPython.core.display.clear_output(). In the IPython Notebook (2.4.1) this logging method with clearing would work fine and not slowdown Firefox at all however in Jupyter (4.0.5) it gets really slow. An example might be:

``` python
import logging
import sys
from IPython.core.display import clear_output

logger = logging.getLogger()
del logger.handlers[0]
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler(sys.stdout)
ch.setLevel(logging.DEBUG)
logger.addHandler(ch)

for num, i in enumerate(range(1000)):
    square = i**2
    clear_output(wait=True)
    logger.info("The square of element %d is %d", num, square)
```

I noticed this sluggish behavior because the logging and clearing function is used in a third party module I use for analysis however I created a notebook that gives me a similar result (attached same as above). I have tested this in Firefox and Firefox in safe mode. Google Chrome works fine.

http://nbviewer.ipython.org/urls/dl.dropbox.com/s/2gweawfwkd9ztg0/Logger_test.ipynb

**Comment by ellisonbg** [comment]
We will investigate this - thanks for the example.

**Comment by takluyver** [comment]
I just tested this with the code sample, but I don't know if the problem reported still exists. The output updated less smoothly than in Chromium, but it didn't slow things down problematically. On the other hand, I'm running this on a relatively fast computer, so it may be worse on other machines.

If there is anything to improve, I'd guess it's in our stream concatenation and ansi processing machinery. If I insert a 0.01s sleep in the loop, it updates smoothly.

The jankiness that I saw is not tied to the logging framework: I could see the same with a plain print():

```python
import time
from IPython.display import clear_output

for num, i in enumerate(range(1000)):
    square = i**2
    clear_output(wait=True)
    print("The square of element %d is %d" %(num, square))
    #time.sleep(0.01)
```

**Comment by pfigliozzi** [comment]
Just to follow up. I tried the code from takluyver in the notebook 4.2.1 and it was still causing sluggishness in Firefox but was perfectly fine in Chrome. Adding the 0.01s sleep did help Firefox remain usable but was still sluggish.

Next I tried updating my packages so now I am running notebook 4.3.1. Trying once again takluyver's code in a notebook I found that using the new version 4.3.1 that I have much improved performance in Firefox when using a 0.01s sleep. However, if I remove the 0.01s sleep Firefox becomes just as sluggish as version 4.2.1 without the 0.01 sleep, typically there is a long delay before scrolling and switching tabs.

I tried playing around with it some more and tried increasing the number of loops from 1000 to 10000.  For Firefox, increasing the number of loops increases the amount of time Firefox is sluggish for when there is no 0.01s sleep. However, when using Chrome for 10000 loops and no 0.01s sleep the kernel would sometimes stop and return the following error:
```python 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-e1fa7ddf5af9> in <module>()
      5     square = i**2
      6     clear_output(wait=True)
----> 7     print("The square of element %d is %d" %(num, square))
      8 #     time.sleep(0.01)

C:\Users\Scherer Lab E\Anaconda2\lib\site-packages\ipykernel\iostream.pyc in write(self, string)
    315 
    316             is_child = (not self._is_master_process())
--> 317             self._buffer.write(string)
    318             if is_child:
    319                 # newlines imply flush in subprocesses

ValueError: I/O operation on closed file
```
Sometimes I can get this error in Firefox too when I am not using 0.01s sleep and trying to scroll the browser a lot while it is running.

I have summarized my results below for the two browsers running 10000 loops of the code from takluyver on notebook version 4.3.1.

Browser | With `time.sleep(0.01)` | Without `time.sleep(0.01)`
---------|------------------------|----------------------------------
Firefox | Runs fine, No slowdown | Massive slowdown, sometimes `ValueError`
Chrome | Runs fine, No slowdown | No slowdown, Sometimes `ValueError`

**Comment by takluyver** [comment]
Thanks for the detailed analysis! If you've got time, could you try it with master too (see [setting up a development environment](http://jupyter-notebook.readthedocs.io/en/latest/contributing.html#setting-up-a-development-environment))?

**Comment by minrk** [comment]
I've tried this with master and 10000 loops and Firefox 51.0.1. I do see the application get a little slower, but still responsive, and occasional 'IOPub message rate exceeded' messages suggesting that the new rate limiting is indeed helping. I think we can tentatively call this improved (if not solved) in 5.0.

**Comment by takluyver** [comment]
Thanks Min. Bumped to 5.1 in case we get any new info.

**Comment by gnestor** [comment]
I'm going to close this for now. If it comes up again, we can re-open...
