### ISSUE TITLE
Copying Python code in Firefox does not work

### ISSUE THREAD

**Issue by Phyks** [jupyter/notebook#516]
Hi,

When I copy the content of a Python cell in Firefox in a Jupyter notebook, it simply copies the "-" character. Hence, I cannot duplicate easily portions of code.

Thanks

**Comment by minrk** [comment]
@Phyks can you try it in a private browsing tab with no extensions enabled and see if it still does this?

**Comment by Phyks** [comment]
Same problem for me in private browsing without any extensions enabled. No problem in Chromium though…

**Comment by ellisonbg** [comment]
We will try to reproduce this. More info though:

* Firefox version?
* OS
* Extensions?

**Comment by ellisonbg** [comment]
We have tested that this works on Firefox 41 on OS X 10.10.5

**Comment by Phyks** [comment]
Cannot reproduce after a system upgrade (firefox 41.0.1). I think we can close it for now. If I manage to reproduce, I will post more details.

**Comment by ellisonbg** [comment]
Great, thanks! Closing!
