### ISSUE TITLE
jupyter notebook opening Signal Desktop on startup

### ISSUE THREAD

**Issue by HendrikF** [jupyter/notebook#5162]
When running `jupyter notebook` the Signal Desktop client is opened for some reason.

In the screenshot you can see that jupyter outputs Signals logging after startup and Signal opens. `htop` shows process dependencies and startup parameters.

I can access notebook by clicking the link in the console output, so everything else seems to work.

![Bildschirmfoto von 2020-01-15 14-48-37](https://user-images.githubusercontent.com/6961660/72441059-4e8c3180-37aa-11ea-8ce2-f5e25f5b4586.png)

Notebook Version: 6.0.2
(Installed via pip)
Python 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Ubuntu 18.04.3 LTS

Signal is installed via apt repo:
`deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main`

**Comment by doctaphred** [comment]
Wow, what a wild bug!

I am not a Jupyter contributor (just a random developer browsing through the project's issues), but I am fairly certain this must be caused by a bug in Signal Desktop, not in Jupyter Notebook.

This sounds similar to another truly wild bug where Roku devices would continually reboot if someone started playing Pokemon Sword or Shield on the same network: https://www.theverge.com/2019/11/18/20970743/roku-pokemon-sword-and-shield-crashing-boot-loop-fix

I would bet that Signal Desktop is doing something similar to Roku.

**Comment by doctaphred** [comment]
Yep, here's the same issue reported to Signal: https://github.com/signalapp/Signal-Desktop/issues/3695, which was closed as duplicate of https://github.com/signalapp/Signal-Desktop/issues/3602

**Comment by HendrikF** [comment]
I looked into the problem with a colleague a few days ago, and for some reason Signal was set as a handler for `.html` files.

To fix this on Ubuntu, I created an empty html file, right clicked it in nautilus or on gnome desktop, 'properties', 'open with', and select your favourite web browser as default again.

I have no idea why that would happen, as Signal has no ability to handle html files.

@doctaphred was right, this a duplicate of signalapp/Signal-Desktop#3602

**Comment by doctaphred** [comment]
Thanks for the update, and I'm glad you've resolved the issue!

Here's an update of my own: when I shared those links, I was still confused how Signal Desktop registering itself as an HTML file handler would cause it to start chatting with a local HTTP server on port 8888 (as seen in the server logs in your screenshot); but I just now figured out the `jupyter notebook` command *also* [writes out an HTML file](https://github.com/jupyter/notebook/blob/8a674771564789b5468e64fae4732f83046e5e73/notebook/notebookapp.py#L1834-L1852) and then calls [`browser.open()`](https://github.com/jupyter/notebook/blob/8a674771564789b5468e64fae4732f83046e5e73/notebook/notebookapp.py#L1901) on it: that `open` call must be what Signal Desktop intercepts. (Still not sure why it then starts chatting with the Jupyter server, but that's their problem to solve...)

**Comment by HendrikF** [comment]
You can see in my screenshot, that the browser gets called with the created html file as parameter, so of course it is creating that file.

And browser.open() probably just attaches the browsers stdout to jupyters stdout (or at least mirrors it there) and Signals logs to its stdout. That's why the logging appears to come from jupyter.

Signal does not intercept any open() call and does not talk to any of jupyters network ports. The browser module just uses the OS-wide preference for opening html files. As that was Signal, the browser module started a Signal process.
