### ISSUE TITLE
Jupyter notebook freezes on Windows 10

### ISSUE THREAD

**Issue by averri** [jupyter/notebook#5164]
I have installed jupyter notebook with: `pip install jupyterlab`.

When running any code cell the notebook freezes:
```python
a = 'This will freeze the notebook'
```
This error message is present in the notebook's log:
```
[I 09:43:23.477 NotebookApp] Creating new notebook in
[I 09:43:24.666 NotebookApp] Kernel started: 6e1bbdd3-ef57-4e25-9313-7f053859d86f
[W 09:43:24.687 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20200117094316 (::1) 18.00ms referer=http://localhost:8888/notebooks/Untitled8.ipynb?kernel_name=python3
```

**Comment by kevin-bates** [comment]
Hi @averri - I don't have anything immediate to offer, just a couple questions and a suggestion.

I would suggest you launch the notebook server with the `--debug` flag, as it may produce some additional insights.  The fact that the log is so silent is a little strange.  This seems to imply that the kernel is running, but you should see messaging relative to the kernel-info request/response - particularly that the response wasn't received - or something to the affect.

What version of python are you using?  There are known issues with event loops on Windows 10 + py8 that exist in both Notebook and IPykernel, but you'd have typically encountered the Notebook form of the issue immediately.

Are you using nb_conda_kernels?  This could explain why you didn't see the Win10/py8 event loop issue in Notebook, but it may be encountered in a conda env that is using py8.  Might that scenario fit your environment?

Sorry there's nothing concrete to offer here, but perhaps by adding `--debug` and getting an idea of your configuration, we can make some headway.

**Comment by averri** [comment]
Hi @kevin-bates, thank you for your answer. I haven't seen anything relevant in the debug logs. 
The same notebook is working fine with the Firefox browser, so I decided to disable Google Chrome browser plugins. After disabling the plugins, the problem is gone. This issue was related to a Google Chrome plugin interfering with the Jupyter Notebook JavaScript functions.
