### ISSUE TITLE
Encoding parameter to json.loads is deprecated and will be removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [jupyter/notebook#5165]
Some of the tests in test_gateway have encoding parameter passed to `json.loads`. This is ignored and deprecated to be removed in Python 3.9.

```
>>> json.loads(json.dumps({1: 1}), encoding='utf-8')
<stdin>:1: DeprecationWarning: 'encoding' is ignored and deprecated. It will be removed in Python 3.9
{'1': 1}
```

https://github.com/jupyter/notebook/blob/7b5248d1cebfaf7661198963fef23823db6604cd/notebook/tests/test_gateway.py#L189

**Comment by kevin-bates** [comment]
Agreed.  Did you want to provide a pull request for this?
