### ISSUE TITLE
Update conda-forge recipe for 6.0.2?

### ISSUE THREAD

**Issue by yzq89** [jupyter/notebook#5166]
Hi, could someone help to put 6.0.2 onto conda-forge? I'd really like to have some of the bugfixes from 6.0.2 (particularly https://github.com/jupyter/notebook/pull/4891), but also avoid having to have multiple conda channels in my docker build.

**Comment by bollwyvl** [comment]
Please raise issues like this directly on the feedstock:

https://github.com/conda-forge/notebook-feedstock

To save a bit if back-and-forth: this PR is presently passing, checks the
dependencies more aggressively, and offers myself to help keep it up to
date:

https://github.com/conda-forge/notebook-feedstock/pull/63

Just awaiting review.

Part of the delay was a series of upstreams (jupyter_client and
jupyter_core) that had to be upgraded first for all the supported platforms.

 If being able to install Jupyter software this way is important to you
and/or your employer, feel free to contribute there.

**Comment by yzq89** [comment]
Thanks @bollwyvl! Saw that PR got merged, many thanks for your work there!
