### ISSUE TITLE
Using an external editor

### ISSUE THREAD

**Issue by Phyks** [jupyter/notebook#517]
Hi,

I'd love to be able to use my own editor (Vim) in Jupyter notebooks, to edit the cells. I do not know if this is feasible at the moment, but did not find anything about it in the docs. Ideally, I would like to be able to edit cells in Vim, and still get the render in realtime in Jupyter notebook in my browser.

Plus, I think it would be better (if possible) to handle an external editor instead of adding Vim keybindings to Jupyter notebooks.

What do you think about it?

**Comment by eliemichel** [comment]
You might already find custom key bindings for IPython, to use or get inspiration to make your own:

https://mail.scipy.org/pipermail/ipython-dev/2012-January/008666.html
http://undefd.kaihola.fi/2013/10/25/emacs-keybindings-for-ipython-notebook-and-firefox.html

As the last link says, IPython uses CodeMirror, so you can look for CodeMirror related stuff too.

PS: So bad you don't use emacs: https://github.com/tkf/emacs-ipython-notebook

**Comment by minrk** [comment]
I believe there exist browser extensions to hook up vim for any text area on any webpage, which ought to work in notebooks. I haven't used any, though.

**Comment by davidbrochart** [comment]
This JavaScript snippet might be what you're looking for:
http://stackoverflow.com/questions/28309430/edit-ipython-cell-in-an-external-editor

**Comment by Phyks** [comment]
@davidbrochart Thanks for the link!

**Comment by grothesque** [comment]
May I ask why this issue has been closed?  I know of several people who would love to be able to reliably launch an external editor for jupyter cells.  I've spent multiple hours researching this problem, but there doesn't seem to be a satisfying solution:

Extensions like "it's all text" don't work with jupyter cells.

The [snippet](https://stackoverflow.com/questions/28309430/edit-ipython-cell-in-an-external-editor) mentioned above is a good start, but it has some serious problems.  It executes code in the kernel and thus has side effects (setting the `f` global variable, importing the `os` module) that could break actual notebook code in difficult to understand ways.  It also relies on actually having a Python kernel running, while Jupyter is a more general project.

Is there a way to run Python code from Javascript not in the kernel but in the ipython instance that is actually running jupyter?  How to pass values to and from java script?  If I had answers to these questions, I believe that I could come up with a nice way of launching external editors.

**Comment by grothesque** [comment]
My favorite editor happens to be emacs.  I've setup emacs keybindings for codemirror, and that's already something, but it doesn't come close to the real thing.  I would really appreciate help with fixing this.  Is there something like `Jupyter.notebook.kernel.execute` but not for executing code in the kernel, but in the main python process?

**Comment by grothesque** [comment]
OK, so I found ways to improve @davidbrochart's snippet to avoid its shortcomings:  https://stackoverflow.com/questions/28309430/edit-ipython-cell-in-an-external-editor/51071244#51071244

Given that no edit-in-external-editor browser extensions seem to work with Jupyter (I tried three different ones), I see this hack an acceptable workaround.

Now that I understand this issue (#517) better, I agree that it's not Jupyter's job to provide ways to launch external editors (so it's OK if this issue remains closed.)  The problem seems to be a lack of compatibility between CodeMirror and any of the existing edit-in-external-editor browser extensions.
