### ISSUE TITLE
Paths pointing to wrong directory

### ISSUE THREAD

**Issue by cbeebe44** [jupyter/notebook#5172]
The paths used by jupyter notebook and other apps are not correct. I want to know how to change them.  
They are currently pointing to the paths of another environment. I am using conda to manage environments. This faulty configuration only happens when I clone an environment that used pip to install jupyter. I'm not sure if that is important, I just want to know how to change it. I brought up the same issue in multiple repositories ([1](https://github.com/jupyter/jupyter_core/issues/180), [2](https://github.com/conda/conda/issues/9616), [3](https://stackoverflow.com/questions/59819150/jupyter-and-conda-error-when-cloning-environment)).  
Thanks

**Comment by jasongrout** [comment]
I think the jupyter_core issue is the relevant place for this discussion, so thanks for opening an issue there.

**Comment by cbeebe44** [comment]
good to know, thanks
