### ISSUE TITLE
Stream messages ignored or displayed under incorrect code cells

### ISSUE THREAD

**Issue by wellecks** [jupyter/notebook#518]
After executing a cell that produces `stream` messages, Jupyter will stop displaying the `stream` messages associated with the cell's `parent_header` `msg_id` after executing another cell.

This is leading to an [issue](https://github.com/ibm-et/spark-kernel/issues/129) in the Spark Kernel where stream messages from a previous cell are arriving, but not being displayed. In the following example, notice that messages with `parent_header` `msg_id` A81... continue to arrive but are not displayed:
![spark_kernel_example](https://cloud.githubusercontent.com/assets/680489/10206557/2ba94bea-678d-11e5-922c-266a3bf92fd3.gif)

It looks like the Python Kernel uses the `parent_header` `msg_id` from the most recently executed cell when sending stream messages. As a result, stream messages may 'switch' to another cell after execution:
![python_kernel_example](https://cloud.githubusercontent.com/assets/680489/10206487/b7ce567a-678c-11e5-8314-34df366bb9ac.gif)

Is this the desired behavior?

**Comment by wellecks** [comment]
Ok thanks - good to know. For the Spark kernel we'll look into sending the `idle` message later, or changing it to behave like the Python kernel

**Comment by JamiesHQ** [comment]
@wellecks : We're doing a little housekeeping on our issue log and I noticed this thread from 2015. Has this issue been resolved to your satisfaction and can it be closed? I'll be adding a "Reference" label to the closed issue to note its importance and to help other users who may have a similar question. 

You may also be interested in this Spark discussion on our mailing list: https://groups.google.com/forum/#!searchin/jupyter/Spark%7Csort:relevance/jupyter/O1KnaEPqCM4/1B1vGkbwEAAJ

thanks!

**Comment by wellecks** [comment]
Sure, this can be closed - thanks
