### ISSUE TITLE
Building image from Dockerfile fails

### ISSUE THREAD

**Issue by natemurthy** [jupyter/notebook#52]
I recently tried building from the most recent Dockerfile as of this commit (https://github.com/jupyter/jupyter_notebook/commit/89380e456be7399ff4cf4a44395d875099327323) on master, but I run into the following failure:

```
Unpacking /srv/ipython
  Running setup.py (path:/tmp/pip_build_root/ipython/setup.py) egg_info for package ipython
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/ipython/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/ipython/setup.py'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/ipython
Storing debug log for failure in /root/.pip/pip.log
INFO[13453] The command [/bin/sh -c pip2 install file:///srv/ipython#egg=ipython[all]] returned a non-zero code: 1 
```

This is as far as I get. Resolution kindly appreciated.

**Comment by minrk** [comment]
cc @rgbkrk do you know what's up here?

**Comment by rgbkrk** [comment]
That's so weird that `/srv/ipython` is mentioned in the log, when `ipython` itself comes straight from `pip` as part of the `ipykernel` install. I just tried building locally and ran into issues as well.

Let me see if I can get this working again.

/cc @parente

**Comment by parente** [comment]
Sorry. Late to the party on this one. @rgbkrk was there an explanation for the weirdness? Stable ipykernel packaging just fixed it?

**Comment by rgbkrk** [comment]
Yeah we were mid migration when this issue was opened. Pretty simple now.
