### ISSUE TITLE
Unable to Start Kernel (Stuck at 'Connecting to Kernel')

### ISSUE THREAD

**Issue by professor042** [jupyter/notebook#5214]
I have been trying to get juypter notebook to run on my Windows 10 machine, launching through Powershell with 'juypter notebook' for a long time and have been unsuccessful.

I am able to create a new notebook when I launch which I'm able to save, but the kernel fails to launch so I cannot run any code.

- I reviewed issue #1416 which did not resolve my issue.
- I tried to launch from both Chrome and Firefox, which both had the same issue.

I run Python 3.8 and have it working fine and can run scripts through PowerShell and have recently updated Python using pip.  My jupyter notebook version is 6.0.3.

This is my output from the Windows PowerShell when I try to run:

> PS C:\python35\python_work> jupyter notebook                                                                                                                                                                                         [I 18:13:37.330 NotebookApp] JupyterLab extension loaded from C:\python38\lib\site-packages\jupyterlab
> [I 18:13:37.330 NotebookApp] JupyterLab application directory is c:\python38\share\jupyter\lab
> [I 18:13:37.362 NotebookApp] Serving notebooks from local directory: C:\python35\python_work
> [I 18:13:37.362 NotebookApp] The Jupyter Notebook is running at:
> [I 18:13:37.362 NotebookApp] http://localhost:8888/?token=13977b4e183a979e949762d618395cb112db745004423a7a
> [I 18:13:37.362 NotebookApp]  or http://127.0.0.1:8888/?token=13977b4e183a979e949762d618395cb112db745004423a7a
> [I 18:13:37.362 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [C 18:13:37.371 NotebookApp]
> 
>     To access the notebook, open this file in a browser:
>         file:///C:/Users/JLZ%20PC%207579/AppData/Roaming/jupyter/runtime/nbserver-38928-open.html
>     Or copy and paste one of these URLs:
>         http://localhost:8888/?token=13977b4e183a979e949762d618395cb112db745004423a7a
>      or http://127.0.0.1:8888/?token=13977b4e183a979e949762d618395cb112db745004423a7a
> [W 18:13:38.828 NotebookApp] 404 GET /api/kernels/1dc3917c-3f19-4255-a48f-8c6e2c4cc581/channels?session_id=ce8a75db04fd40438591e90c5c5b1c7d (::1): Kernel does not exist: 1dc3917c-3f19-4255-a48f-8c6e2c4cc581
> [W 18:13:38.861 NotebookApp] 404 GET /api/kernels/1dc3917c-3f19-4255-a48f-8c6e2c4cc581/channels?session_id=ce8a75db04fd40438591e90c5c5b1c7d (::1) 47.85ms referer=None
> [I 18:13:48.999 NotebookApp] Creating new notebook in /bets_kp
> [I 18:13:50.525 NotebookApp] Kernel started: ab2c4986-430f-479a-a6ea-113da2ecca81
> Traceback (most recent call last):
>   File "C:\python38\lib\runpy.py", line 193, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\python38\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\python38\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
>     app.launch_new_instance()
>   File "C:\python38\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
>     app.initialize(argv)
>   File "<C:\python38\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
>   File "C:\python38\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
>     return method(app, *args, **kwargs)
>   File "C:\python38\lib\site-packages\ipykernel\kernelapp.py", line 527, in initialize
>     self.init_sockets()
>   File "C:\python38\lib\site-packages\ipykernel\kernelapp.py", line 287, in init_sockets
>     self.init_iopub(context)
>   File "C:\python38\lib\site-packages\ipykernel\kernelapp.py", line 295, in init_iopub
>     self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
>   File "C:\python38\lib\site-packages\ipykernel\iostream.py", line 68, in __init__
>     self._setup_pipe_in()
>   File "C:\python38\lib\site-packages\ipykernel\iostream.py", line 141, in _setup_pipe_in
>     self._pipe_in = ZMQStream(pipe_in, self.io_loop)
>   File "C:\python38\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
>     self._init_io_state()
>   File "C:\python38\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
>     self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
>   File "C:\python38\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
>     self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
>   File "C:\python38\lib\asyncio\events.py", line 501, in add_reader
>     raise NotImplementedError
> NotImplementedError
> [W 18:14:12.116 NotebookApp] Replacing stale connection: ab2c4986-430f-479a-a6ea-113da2ecca81:012281ff33774dc2bac5f1b83ec06aa0
> [W 18:14:34.460 NotebookApp] Replacing stale connection: ab2c4986-430f-479a-a6ea-113da2ecca81:012281ff33774dc2bac5f1b83ec06aa0
> [W 18:14:50.558 NotebookApp] Timeout waiting for kernel_info reply from ab2c4986-430f-479a-a6ea-113da2ecca81
> [I 18:14:50.573 NotebookApp] Starting buffering for ab2c4986-430f-479a-a6ea-113da2ecca81:012281ff33774dc2bac5f1b83ec06aa0
> [I 18:14:50.575 NotebookApp] Restoring connection for ab2c4986-430f-479a-a6ea-113da2ecca81:012281ff33774dc2bac5f1b83ec06aa0
> [I 18:15:50.456 NotebookApp] Saving file at /bets_kp/Untitled2.ipynb

**Comment by kevin-bates** [comment]
This appears related to the event loop change tornado made for python 3.8 that upsets Windows.  Please make sure your `ipykernel` package is at version `5.1.4` since it suffers the same fate as Notebook (that 6.0.3 addressed).

**Comment by professor042** [comment]
This worked - thanks so much!

For the record, I used 'pip install --upgrade ipykernel' in PowerShell to
upgrade from ipykernel 5.1.3 to version 5.1.4.

**Comment by hearaujo-hub** [comment]
> This appears related to the event loop change tornado made for python 3.8 that upsets Windows. Please make sure your `ipykernel` package is at version `5.1.4` since it suffers the same fate as Notebook (that 6.0.3 addressed).

How can I do that?
