### ISSUE TITLE
Jupyter Notebook in WSL causes an PowerShell-style error

### ISSUE THREAD

**Issue by altwarg** [jupyter/notebook#5220]
* What you're doing and what's happening:
```sh
$ sudo apt install python3-pip
$ sudo pip3 install notebook
$ jupyter notebook
```

* What's wrong / what should be happening instead:
There're must not be any PowerShell-style error messages:
![image](https://user-images.githubusercontent.com/34391398/74139481-7f725180-4c04-11ea-8077-43c42253b212.png)

This issue is related to [WSL issue 4881](https://github.com/microsoft/WSL/issues/4881)

**Comment by thomazpougy** [comment]
Try to folow this tutorial on medium https://medium.com/@harshityadav95/jupyter-notebook-in-windows-subsystem-for-linux-wsl-8b46fdf0a536. It seems that the last steps fix this problem ocurring in WSL

**Comment by altwarg** [comment]
@thomazpougy thanks! I figured it out. It seems that without an option `--no-browser` jupyter tries to open a browser inside WSL

**Comment by albertplus007** [comment]
Hi, I meet the seem problem, but how did you slove it?
Can you tell me? @altwarg

**Comment by altwarg** [comment]
@albertplus007 start Jupyter with option `--no-browser`:
```bash
$ jupyter-notebook --no-browser
```

**Comment by albertplus007** [comment]
Wow, nice solution, thanks a lot
