### ISSUE TITLE
Notebook validation failed: 1 is less than the minimum of 3: 1

### ISSUE THREAD

**Issue by KirosG** [jupyter/notebook#5228]
When new notebook opened it just opens Notebook validation failed
An invalid notebook may not function properly. The validation error was:
`Notebook validation failed: 1 is less than the minimum of 3:1`

**Comment by jasongrout** [comment]
As a guess, it sounds like you may have a notebook with format version 1? If you look inside the notebook file in a text editor, probably at the bottom, it will say what notebook format version it is, like this:

```
 "nbformat": 4,
 "nbformat_minor": 4
```
What versions does it say for your file?

**Comment by nealoman** [comment]
Almost the same error now appearing in our installation for existing notebook files, which were created under the previous release (last Nov release). Old notebook files have "nbformat_minor" : 2.

Not sure of the side-effects of just changing that value to 3, but that will solve the error popup problem.

Also getting a similar validation error when trying to create a new (Python 3) notebook now...and it refuses to create a new notebook.

**Comment by jasongrout** [comment]
> Old notebook files have "nbformat_minor" : 2.

The specific error above almost surely refers to the major version, not the minor version. What is "nbformat" for you?

**Comment by nealoman** [comment]
Current notebooks, which are throwing the error have "nbformat":4

**Comment by nealoman** [comment]
The pop-up "validation failed" error (so far just annoying, not obstructive) is: 
Notebook validation failed: 2 is less than the minimum of 3:
2

**Comment by jasongrout** [comment]
Can you upload an example notebook that doesn't work? What version of the nbformat package do you have?

**Comment by nealoman** [comment]
Notebook file attached, with the file extension changed to .txt. However, seems that we maybe had some dissonance in some components that didn't get restarted after a conda update. We had reason to reboot our server last night and now everything seems resolved at this point.
[EDA_Karlv1.0.txt](https://github.com/jupyter/notebook/files/4237071/EDA_Karlv1.0.txt)

**Comment by nealoman** [comment]
To your nbformat version question: nbformat==5.0.4

**Comment by jasongrout** [comment]
r

> However, seems that we maybe had some dissonance in some components that didn't get restarted after a conda update. We had reason to reboot our server last night and now everything seems resolved at this point.

Great!

I looked at the file, and everything seems to be in order there too.
