### ISSUE TITLE
Jupyter notebook: kernel restart failed

### ISSUE THREAD

**Issue by sharanbr** [jupyter/notebook#5233]
I am having issues running jupyter notebook.
The notebook opens without issues and then notebook indicates "restarting kernel" and then issues error ...
I see the following messages coming from the shell.

I need some help please.
Also, a week back this was all working fine.
I have uninstalled Anaconda multiple times and re-installed but to no avail.
This is on Windows 10 machine.

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("age is %s" % age)?
[I 18:13:13.650 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "D:\SW\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\SW\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\SW\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "D:\SW\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "D:\SW\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "D:\SW\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "D:\SW\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "D:\SW\lib\site-packages\traitlets\__init__.py", line 1, in <module>
    from .traitlets import *
  File "D:\SW\lib\site-packages\traitlets\traitlets.py", line 57, in <module>
    import six
  File "D:\Users\sharanb\OneDrive - HCL Technologies Ltd\Projects\MyBackup\Projects\Initiatives\machine learning\programs\six.py", line 3
    print "age is %s" % age
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("age is %s" % age)?
[W 18:13:16.706 NotebookApp] KernelRestarter: restart failed
[W 18:13:16.706 NotebookApp] Kernel fe026c42-8f37-4750-8a43-826a52fe6f77 died, removing from map.
[W 18:14:01.629 NotebookApp] Timeout waiting for kernel_info reply from fe026c42-8f37-4750-8a43-826a52fe6f77
[E 18:14:01.629 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: fe026c42-8f37-4750-8a43-826a52fe6f77)
[W 18:14:03.569 NotebookApp] 404 GET /api/kernels/fe026c42-8f37-4750-8a43-826a52fe6f77/channels?session_id=f4b373d078cc4fc0986632eec1573184 (::1): Kernel does not exist: fe026c42-8f37-4750-8a43-826a52fe6f77
[W 18:14:03.574 NotebookApp] 404 GET /api/kernels/fe026c42-8f37-4750-8a43-826a52fe6f77/channels?session_id=f4b373d078cc4fc0986632eec1573184 (::1) 6.05ms referer=None
[W 18:14:06.571 NotebookApp] Replacing stale connection: fe026c42-8f37-4750-8a43-826a52fe6f77:f4b373d078cc4fc0986632eec1573184
[W 18:18:11.593 NotebookApp] Replacing stale connection: fe026c42-8f37-4750-8a43-826a52fe6f77:f4b373d078cc4fc0986632eec1573184
[W 18:22:20.582 NotebookApp] Replacing stale connection: fe026c42-8f37-4750-8a43-826a52fe6f77:f4b373d078cc4fc0986632eec1573184
[W 18:26:36.629 NotebookApp] Replacing stale connection: fe026c42-8f37-4750-8a43-826a52fe6f77:f4b373d078cc4fc0986632eec1573184

**Comment by kevin-bates** [comment]
@sharanbr - I suspect the issue is that your ML program file `D:\Users\sharanb\OneDrive - HCL Technologies Ltd\Projects\MyBackup\Projects\Initiatives\machine learning\programs\six.py` is interfering/conflicting with IPython's ability to invoke `import six` and its importing your `six.py` - which contains Python 2 code, etc.  

Try renaming `D:\Users\sharanb\OneDrive - HCL Technologies Ltd\Projects\MyBackup\Projects\Initiatives\machine learning\programs\six.py` to a slightly different name.

> Also, a week back this was all working fine.

Perhaps your `six.py` has been recently introduced?  That particular import statement has been present in `traitlets.py` for more than 4 years, so I'm going with the first theory.

**Comment by sharanbr** [comment]
Kevin,
Thanks a lot. That exactly was the issue. 
I have uninstalled and installed at least 4 times since last 2 days with various combinations assuming the issue would get resolved.
Now, the issue is resolved. I tried a couple of examples. Who would have thought.

Now, one thing that is very surprising to me.
six.py is not a new file. It was created in 2018 apparently.
The same jupyter was working a few days back. The issue came up all of a sudden.

Anyway, thanks a lot.

**Comment by kevin-bates** [comment]
I wonder if something in IPython or IPykernel has changed in how it scopes files. Looks like [`ipykernel`](https://github.com/ipython/ipykernel/releases/tag/5.1.4) was released a few weeks ago to address a Windows/py3.8 issue so maybe something in your env triggered its upgrade.  Perhaps attempting to revert ipykernel to `5.1.3` (at the risk of sliding down a slippery slope) to see if your situation resolves again would be a good data point?  It's up to you.  Glad you're able to move forward.
