### ISSUE TITLE
Markdown rendering broken in the presence of punctuation.

### ISSUE THREAD

**Issue by johncbowers** [jupyter/notebook#5234]
If you end a parenthetical remark with italics (such as _this_) in a markdown block in Jupyter, instead of rendering the "this" in italics, it renders in the standard font with the underscores showing. 

A similar problem occurs when the underscore is followed by a '?'. I just tested these on jupyter.org/try to confirm that they do not work in Jupyter and on [marked.js.org](https://marked.js.org/demo/?text=(How%20well%20does%20_this%20render%3F_)%0AHow%20well%20does%20this%20_render_%3F%0AThis%20is%20some%20_italic%20text_.%20%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) to confirm that they render as expected on other markdown systems. 

In fact, it appears any use of punctuation following the underscore causes problems for the rendering.

Note that if you use only the first two lines of the following example in Jupyter you get all the underscores, but if you use all three lines, things go significantly more wonky even on the earlier lines (somehow the inclusion of the later line makes things even worse for the earlier lines):

`(How well does _this render?_)`
`How well does this _render_?`
`This is some _italic text_.`

GitHub's rendering also seems to work as expected: 

(How well does _this render?_)
How well does this _render_?
This is some _italic text_.

**Comment by mwermelinger** [comment]
The example given renders fine in Jupyter 6.1.4. This issue should probably be closed.

**Comment by kevin-bates** [comment]
Thanks @mwermelinger.  Just confirmed using 6.3.0 as well.  The version of `marked` was updated to version `0.7` in #5617 which first appeared in 6.1.  I suspect that bump did the trick - closing.
