### ISSUE TITLE
Buffered message don't replay but discarding

### ISSUE THREAD

**Issue by NEOherozzz** [jupyter/notebook#5243]
Hi,

Recently, I have some troubles with replaying buffered message. When running some cells, and close chrome tab. A few minutes later, reopen it. The running cells message don't show below the cells. 

I have read [#4105](https://github.com/jupyter/notebook/issues/4105), [#4110](https://github.com/jupyter/notebook/pull/4110). So I run `conda install -c conda-forge jupyterlab` to update the version of notebook. but the problem still exists.

This is the output of `jupyter troubleshoot`. 
[jupyter troubleshoot.log](https://github.com/jupyter/notebook/files/4231410/jupyter.troubleshoot.log)

This is the output of `jupyter lab --debug`.
[jupyter lab --debug.log](https://github.com/jupyter/notebook/files/4231416/jupyter.lab.--debug.log)

In `jupyter lab --debug`, I just open chrome tab, running cells below. When it running on cell 3, I close it, wait some minutes and reopen it. But the buffered messages don't show. 
![jupyterlab](https://user-images.githubusercontent.com/11733641/74947193-3049cf00-5403-11ea-894d-5b1c5b629a88.png)

Does anybody know how to solve it? Thanks in advance!

**Comment by NEOherozzz** [comment]
Does anyone has ideas to fix this?

**Comment by amangarg96** [comment]
@NEOherozzz Not a fix, but a work around - do not close/refresh the chrome tab.

Once you refresh the chrome tab, the messages from the kernel do reach the browser but the cell and message mapping is lost, so the browser does not know on which cell to render the output. 

To reconnect to the kernel, use the 'Reconnect to kernel' button instead - 
![image](https://user-images.githubusercontent.com/16137472/104203139-ce96b700-5451-11eb-9ea0-f1bc25ba23c0.png)

**Comment by lfdversluis** [comment]
Got the same issue. I closed my tab because I had a long running process and turned of my pc (lab is running headless remote). Saw nothing in the morning and only `Discarding 200 buffered messages for ...` in the console. @amangarg96's suggestion does not work for me as it perfectly fine was still connected to the kernel (now idle). Reconnecting to kernel did nothing for me.

**Comment by amangarg96** [comment]
Hi @lfdversluis ,
My suggestion was only for cases when the tab has **not** been closed or refreshed. 

I don't think there's any way to retrieve the messages once the message-to-cell mapping is lost

**Comment by dsvanidze** [comment]
Is there any solution? It is important to get all outputs and messages for an active kernel after refreshing a tab or closing a browser window.

**Comment by huaiyizhao** [comment]
This feature is badly needed. Imagine when you run the code on a remote server yesterday and no output shows on your reconnected browser tab now

**Comment by kevin-bates** [comment]
This is definitely something we'd like to support, but will likely [not happen here](https://github.com/jupyter/notebook#notice).  We're hoping the recent addition of cell-ids may be useful here - along the lines of [@amangarg96's comment](https://github.com/jupyter/notebook/issues/5243#issuecomment-780373218) above.  As a result, I'm going to (attempt to) move this to Jupyter Server...

@MeeseeksDev migrate to jupyter-server/jupyter_server
