### ISSUE TITLE
Add notebook trusted indicator

### ISSUE THREAD

**Issue by juhasch** [jupyter/notebook#526]
People get confused, when a notebook is not behaving as expected because it is not trusted.
Would it be worth adding a notebook trusted indicator ?

As local solution for a specific notebook extension, I have made this:

Trusted:
![](https://raw.githubusercontent.com/ipython-contrib/IPython-notebook-extensions/af2adcdc0a70ddf3e73244a4e415aa1c76e939a1/nbextensions/usability/python-markdown/trusted.png)

Untrusted:
![](https://raw.githubusercontent.com/ipython-contrib/IPython-notebook-extensions/af2adcdc0a70ddf3e73244a4e415aa1c76e939a1/nbextensions/usability/python-markdown/untrusted.png)
https://github.com/ipython-contrib/IPython-notebook-extensions/pull/329

**Comment by JamiesHQ** [comment]
Is this something we would add in the classic notebook or should the issue get ported over to JLab? @gnestor @jasongrout

**Comment by gnestor** [comment]
This has been implemented!

![image](https://cloud.githubusercontent.com/assets/512354/25409840/80faf75c-29c8-11e7-89fa-13bd33009b27.png)
