### ISSUE TITLE
Jupyter Notebook - Cannot Connect to Kernel

### ISSUE THREAD

**Issue by Bhanu-mbvg** [jupyter/notebook#5283]
Hey, I am not able to connect to the Python3 Server.
Machine - ThinkPad L440, Intel® Core™ i7-4600M CPU @ 2.90GHz × 4, Ubuntu 19.04

`[I 11:57:21.609 NotebookApp] The port 8888 is already in use, trying another port.

[I 11:57:21.633 NotebookApp] JupyterLab extension loaded from /home/kyadekhteho/ProgFiles/Anaconda/lib/python3.7/site-packages/jupyterlab

[I 11:57:21.633 NotebookApp] JupyterLab application directory is /home/kyadekhteho/ProgFiles/Anaconda/share/jupyter/lab

[I 11:57:21.635 NotebookApp] Serving notebooks from local directory: /home/kyadekhteho

[I 11:57:21.635 NotebookApp] The Jupyter Notebook is running at:

[I 11:57:21.635 NotebookApp] http://localhost:8889/?token=b8214845e93ede08e6b893007136bfe138d0eaf7cae0eb5b

[I 11:57:21.636 NotebookApp]  or http://127.0.0.1:8889/?token=b8214845e93ede08e6b893007136bfe138d0eaf7cae0eb5b

[I 11:57:21.636 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

[C 11:57:21.658 NotebookApp] 
`
AND 

`[W 11:58:49.920 NotebookApp] KernelRestarter: restart failed

[W 11:58:49.921 NotebookApp] Kernel fbacafca-c9ce-4fd7-8a09-a088af0abe1c died, removing from map.

[W 11:58:55.997 NotebookApp] Replacing stale connection: fbacafca-c9ce-4fd7-8a09-a088af0abe1c:21df4fc7929b45e9bcb348b0a4f239d8

[W 11:59:18.025 NotebookApp] Replacing stale connection: fbacafca-c9ce-4fd7-8a09-a088af0abe1c:21df4fc7929b45e9bcb348b0a4f239d8

[W 11:59:34.987 NotebookApp] Timeout waiting for kernel_info reply from fbacafca-c9ce-4fd7-8a09-a088af0abe1c

[E 11:59:34.989 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: fbacafca-c9ce-4fd7-8a09-a088af0abe1c)

[W 11:59:34.990 NotebookApp] 404 GET /api/kernels/fbacafca-c9ce-4fd7-8a09-a088af0abe1c/channels?session_id=21df4fc7929b45e9bcb348b0a4f239d8 (127.0.0.1): Kernel does not exist: fbacafca-c9ce-4fd7-8a09-a088af0abe1c

[W 11:59:35.002 NotebookApp] 404 GET /api/kernels/fbacafca-c9ce-4fd7-8a09-a088af0abe1c/channels?session_id=21df4fc7929b45e9bcb348b0a4f239d8 (127.0.0.1) 39007.59ms referer=None

[W 11:59:35.002 NotebookApp] 404 GET /api/kernels/fbacafca-c9ce-4fd7-8a09-a088af0abe1c/channels?session_id=21df4fc7929b45e9bcb348b0a4f239d8 (127.0.0.1): Kernel does not exist: fbacafca-c9ce-4fd7-8a09-a088af0abe1c

[W 11:59:35.003 NotebookApp] 404 GET /api/kernels/fbacafca-c9ce-4fd7-8a09-a088af0abe1c/channels?session_id=21df4fc7929b45e9bcb348b0a4f239d8 (127.0.0.1) 16981.69ms referer=None

[W 11:59:39.021 NotebookApp] Replacing stale connection: fbacafca-c9ce-4fd7-8a09-a088af0abe1c:21df4fc7929b45e9bcb348b0a4f239d8
`

**Comment by kevin-bates** [comment]
These messages are consistent with the front-end losing track of its back-end such that it sends requests relative to a kernel that it knows about, but the back-end doesn't.  Also, the port conflict on 8888 at startup indicates there's another notebook server running (or some other app) that perhaps knows about kernel id `fbacafca-c9ce-4fd7-8a09-a088af0abe1c`.

I would suggest restarting the notebook server after properly stopping the existing instance(s).

Prior to that, one exercise that might be interesting is to change the port in your browser back to `8888` to see if it reestablishes a connection to that particular kernel.  This depends on your affinity to that particular kernel instance.
