### ISSUE TITLE
"Exception: Jupyter command `jupyter-notebooks` not found"?

### ISSUE THREAD

**Issue by stur86** [jupyter/notebook#5297]
I've just started having this error when launching `jupyter notebook`, out of what looks like nowhere. Not sure what did I change to make it happen - no obvious recent causes e.g. updates or changes in my Python environment. Updating with `pip` does not solve the problem. Full error transcript:

```
Traceback (most recent call last):
  File "/home/<username>/miniconda2/bin/jupyter", line 11, in <module>
    sys.exit(main())
  File "/home/<username>/.local/lib/python3.6/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/home/<username>/.local/lib/python3.6/site-packages/jupyter_core/command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-notebooks` not found.
```

The silly thing is, I can launch it just fine if I launch `/home/<username>/miniconda2/bin/jupyter-notebook` by hand. The error seems simply that the script looks for `jupyter-notebooks`, with an -s at the end. If that's the case, it's a pretty basic bug, but is it really just that?

**Comment by kevin-bates** [comment]
I can only reproduce this when invoking `jupyter notebooks`.  This is because the `jupyter` script appends its [first argument](https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/command.py#L190) to [`jupyter-`](https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/command.py#L130) to form the actual target script name. 

Could you please include the command you're actually running?  Thanks

**Comment by stur86** [comment]
The problem stopped for me. I don't know what exactly happened, sorry for bringing this up, maybe it simply was a typo on my part. Closing.

**Comment by rherasm** [comment]
Hi,
try:

export PATH=$PATH:~/.local/bin
or 
  sudo -H pip install jupyter

cheers.

**Comment by savourylie** [comment]
You'll get this if you type `jupyter notebooks`. Not a big problem, just that the exception is a bit misleading.
