### ISSUE TITLE
Printing output to another cell in a jupyter notebook

### ISSUE THREAD

**Issue by abast** [jupyter/notebook#5304]
Disclaimer: I've already asked this question [on stackoverflow](https://stackoverflow.com/questions/60803057/can-i-print-output-to-another-cell-in-a-jupyter-notebook),  but without getting a satisfying answer so far. 

Let's assume there is a jupyter notebook that has two cells. In the second cell, we generate some output, e.g. by running `print('foo')`. Is there a way to change that print command in such a way that the output will be displayed as output of the first cell?

Why? In a typical data analysis workflow, I access several data sources somewhere in the notebook. It would be nice if I could extend my access_data method in such a way that all sources that I have used are listed in the first cell.

In case this is not already possible, this is supposed to be a feature request.

**Comment by jasongrout** [comment]
Here are some options:

1. You can use an ipywidgets output widget to capture output from any command and display it in the output widget, which you can display wherever you want. See https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html
2. You can use the `display` command with a display_id, and then from anywhere else you can update the display by using that id. See https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display and https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.update_display

**Comment by abast** [comment]
Thanks! Both look great. Unfortunately, I am stuck on version 5.1.0 and apparently, `update_display` was not implemented at that time. Also, using the output widget in a with statement does not redirect the output. 

I would fully understand if you, therefore, cannot provide any support. However, if you have any pointers towards a solution, that also works on 5.1.0, it would be greatly appreciated.

**Comment by jasongrout** [comment]
> Also, using the output widget in a with statement does not redirect the output.

Can you give an example of what is not working?

**Comment by abast** [comment]
out = widgets.Output(layout={'border': '1px solid black'})

raises 

    'TraitError: The 'layout' trait of an Output instance must be a Layout or None, but a value of type 'dict' (i.e. {'border': '1px solid black'}) was specified.

I therefore just tried

    out = widgets.Output()
    out

This creates a widget. If I then run


```
with out:
    for i in range(10):
        print(i, 'Hello world!')
```

the output is generated in that cell as if the `with out:`statement woud not exist.

**Comment by jasongrout** [comment]
What version of ipywidgets do you have installed? It seems that you may have a very old version, and may have installation issues besides that.

**Comment by jasongrout** [comment]
And what version of widgetsnbextension do you have installed?

**Comment by abast** [comment]
I absolutely agree with the very old version.

    widgetsnbextension.__version__
    > '1.2.6'

    ipywidgets.__version__
    >'5.2.2'

**Comment by jasongrout** [comment]
Upgrading ipywidgets should be able to help, then.

**Comment by abast** [comment]
I am giving up on that for now. After upgrading pip, I get the error 

> It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall. 

Without upgrading pip, python3 libraries are tried to be installed. Conda keeps stuck in 'resolving environment'. I might try a manual install ... 

Thanks again for your great support. If that aligns with your interest, I could post your solution as an answer to my question on stackoverflow to give it more exposure.

**Comment by oscar6echo** [comment]
I had the sample objective and found @jasongrout second suggestion very good because smack on and light weight.

For reference here is an example.  
Cell # 3 is updated with text, numpy array, pandas dataframe, matplolib plot.  

````python
# cell 1
from IPython.display import display
import random as rd
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

# cell 2
h = display(display_id='my-display')

# cell 3
h.display(None)
# ==> output is updated at each h.update() command in cells below

# cell 4
s = ''.join(rd.choices('abcedfghijklmn', k=5))
h.update(s)

# cell 5
a, b, c, d = rd.choices(range(10), k=4)
arr = np.array([[a,b,c,d], [d,c,b,a]])
h.update(arr)

# cell 6
a, b, c, d = rd.choices(range(10), k=4)
df = pd.DataFrame(data=[[a,b],[c,d]], columns=['A', 'B'])
h.update(df)

# cell 7
a, b, c, d = rd.choices(range(10), k=4)
df = pd.DataFrame(data=[[a,b],[c,d]], columns=['a', 'b'])
ax = df.plot();
fig = ax.get_figure()
h.update(fig)
plt.close()

# cell 8
fig, ax = plt.subplots()
a,b,c,d = rd.choices(range(10), k=4)
ax.plot([a,b,c,d]);
h.update(fig)
plt.close()
````

**Comment by oscar6echo** [comment]
I am working on the subject so I might as well post the result - it may help.  
With a helper class and some management of mime types:

````python
# cell 1
from IPython.display import display

import random as rd
import numpy as np
import pandas as pd
import matplotlib.pylab as plt

# cell 2
class Output:
    """
    Helper class
    """
    def __init__(self, name='my-display'):
        self.h = display(display_id=name)
        self.content = ''
        self.mime_type = None
        self.dic_kind = {
            'text': 'text/plain',
            'markdown': 'text/markdown',
            'html': 'text/html',
        }
        
    def display(self):
        self.h.display({'text/plain': ''}, raw=True)
        
    def _build_obj(self, content, kind, append, new_line):
        self.mime_type = self.dic_kind.get(kind)
        if not self.mime_type:
            return content, False
        if append:
            sep = '\n' if new_line else ''
            self.content = self.content + sep + content
        else:
            self.content = content
        return {self.mime_type: self.content}, True
        
    def update(self, content, kind=None, append=False, new_line=True):
        obj, raw = self._build_obj(content, kind, append, new_line)
        self.h.update(obj, raw=raw)


# cell 3
out = Output(name='my-display-2')

# cell 4
s = ''.join(rd.choices('abcedfghijklmn', k=5))
out.update(s, kind='text', append=False)

# cell 5
a, b = rd.choices(range(10), k=2)
s = f'''\
# Heading one {a}

This is a sample  {b}

* a
* list
'''
out.update(s, kind='markdown', append=True)

# cell 6
a, b = rd.choices(range(10), k=2)
s = f'''\
<h3>My Title {a}</h3>
<p>My paragraph {b}</p>
'''
out.update(s, kind='html')

# cell 7
a, b, c, d = rd.choices(range(10), k=4)
arr = np.array([[a,b,c,d], [d,c,b,a]])
out.update(arr)

# cell 8
a, b, c, d = rd.choices(range(10), k=4)
df = pd.DataFrame(data=[[a,b],[c,d]], columns=['A', 'B'])
out.update(df)

# cell 9
a, b, c, d = rd.choices(range(10), k=4)
df = pd.DataFrame(data=[[a,b],[c,d]], columns=['a', 'b'])
ax = df.plot();
fig = ax.get_figure()
out.update(fig)
plt.close()

# cell 10
fig, ax = plt.subplots()
a,b,c,d = rd.choices(range(10), k=4)
ax.plot([a,b,c,d]);
out.update(fig)
plt.close()

````
