### ISSUE TITLE
custom.js is loaded with no errors, runs script with a console log, but is possibly squashed by extensions?

### ISSUE THREAD

**Issue by jgoad** [jupyter/notebook#531]
This is very likely my own problem, so my apologies. I've just started trying to change the appearance of the notebook with script in custom.js, specifically trying to hide the code cells on startup. My first attempt was adding

`$('div.input').hide();`
to custom.js to no avail.

The script has evolved to 

`$([IPython.events]).on('app_initialized.NotebookApp', function () {
	$('div.input').hide();
	console.log("My Debug Output: script ran")	
});`

The console output in chrome has the "My Debug Output: ..." print, so I know the script is running, but it isn't hiding the code cells in the notebook. 

In the head element there are three sets of scripts being loaded, content, custom, and extensions in that order. 

Is it possible something in extensions is unhiding div.inputs after I hide them?

Thanks.

**Comment by ellisonbg** [comment]
Hmm, there might be a different event to trigger this on.

**Comment by jgoad** [comment]
Hey Brian. Where can I find a list of events? It seems like it's triggering before the code cells are created, and I am seriously JS deficient, but it seems like a lot of code cell set up happens in extensions.js

**Comment by jgoad** [comment]
Here's the list.

https://github.com/ipython/ipython/wiki/Dev:-Javascript-Events#notebook_loadednotebook

and the new *working* version of my script...

`$([IPython.events]).on('notebook_loaded.Notebook', function () {
	$('div.input').hide();
	console.log("My Debug Output: script ran")	
});`

Thanks for having this documented. The problem was not knowing enough about js to even know what to search.
