### ISSUE TITLE
how to launch a kernel by notebook api

### ISSUE THREAD

**Issue by lazywhite** [jupyter/notebook#5313]
I want to launch a kernel in my code, I want to use it like this

api.launch_kernel(kernel_name="python3", connection_file=a_file)

it there some api code like this?

**Comment by kevin-bates** [comment]
Hi @lazywhite.  You probably want to take a look at the [jupyter_client API](https://jupyter-client.readthedocs.io/en/latest/api/manager.html), specifically the KernelManager class's [`start_kernel()`](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L289) method.  This method will call `launch_kernel` to perform kernel launches, which returns a Popen instance against which the kernel lifecycle can be managed.  Communication with the kernel would then occur via an instance of `KernelClient` - all in the same package.

**Comment by lazywhite** [comment]
> Hi @lazywhite. You probably want to take a look at the [jupyter_client API](https://jupyter-client.readthedocs.io/en/latest/api/manager.html), specifically the KernelManager class's [`start_kernel()`](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L289) method. This method will call `launch_kernel` to perform kernel launches, which returns a Popen instance against which the kernel lifecycle can be managed. Communication with the kernel would then occur via an instance of `KernelClient` - all in the same package.

I didnt' do jupyter related work for a long time, so I have to close this issue
