### ISSUE TITLE
Jupyter session deletion async issue with remote kernel

### ISSUE THREAD

**Issue by yangyishan0901m** [jupyter/notebook#5314]
Hi,
I was using jupyter 6.0.3 and jupyter_enterprise_gateway 2.1.0
And when I switch kernels for example, on same notebook file test.ipynb, between python3 kernel and pyspark kernel. 
New session will not be created. I added log on /notebook/services/sessions/handlers.py and I notice that "exists = yield maybe_future(sm.session_exists(path=path))" will return true for first call, but session is already in deleting state. Since jupyter will think session still exists, however it is deleted(or deleting). Session won't be created. And when same function get called second time, it will return false. 

My fix is simple, but I can not prove why it behave like that. Just call exists = yield maybe_future(sm.session_exists(path=path)) and double check existence of session. So new session will be created.

For reproduce it, you will need switch from A to B and then switch back to A. And you may see error from gateway side, but it is a known issue which is not root cause of this async bug.
FYI: https://github.com/jupyter/enterprise_gateway/pull/790

**Comment by yangyishan0901m** [comment]
After switch, I run /api/sessions and /api/kernels, both are empty, since the switch will delete kernel and session first and create new one with new kernel type. Notebook will be in a unusable state.

**Comment by kevin-bates** [comment]
Hmm - I'm not reproducing this issue.  The output is produced by hitting the `/api/kernels` and `/api/sessions` endpoints against the Notebook server (not EG) follow each kernel switch - which I believe equates to your scenario:
```
A
[{"id": "8fcdba00-2ec4-4e4a-95e6-065411863e9d", "name": "python3", "last_activity": "2020-03-30T16:25:44.165278Z", "execution_state": "idle", "connections": 1}]
[{"id": "0d9b2d3f-24f8-49b5-96a2-38052ad6b7ba", "path": "Untitled1.ipynb", "name": "", "type": "notebook", "kernel": {"id": "8fcdba00-2ec4-4e4a-95e6-065411863e9d", "name": "python3", "last_activity": "2020-03-30T16:25:44.165278Z", "execution_state": "idle", "connections": 1}, "notebook": {"path": "Untitled1.ipynb", "name": ""}}]

B
[{"id": "0b28fe93-180b-4d77-80d2-a997310f1498", "name": "spark_python_yarn_cluster", "last_activity": "2020-03-30T16:26:42.371571Z", "execution_state": "starting", "connections": 0}]
[{"id": "64eb50cd-84ad-4197-b1e9-7abf4e662632", "path": "Untitled1.ipynb", "name": "", "type": "notebook", "kernel": {"id": "0b28fe93-180b-4d77-80d2-a997310f1498", "name": "spark_python_yarn_cluster", "last_activity": "2020-03-30T16:26:43.497512Z", "execution_state": "idle", "connections": 1}, "notebook": {"path": "Untitled1.ipynb", "name": ""}}]

A
[{"id": "5089313f-f45c-4dc1-920a-e4364a257deb", "name": "python3", "last_activity": "2020-03-30T16:27:10.601975Z", "execution_state": "idle", "connections": 1}]
[{"id": "04a93974-dfa2-4298-9afd-015792de2227", "path": "Untitled1.ipynb", "name": "", "type": "notebook", "kernel": {"id": "5089313f-f45c-4dc1-920a-e4364a257deb", "name": "python3", "last_activity": "2020-03-30T16:27:10.601975Z", "execution_state": "idle", "connections": 1}, "notebook": {"path": "Untitled1.ipynb", "name": ""}}]
```

I also see the deletion issue surrounding the cache_ports boolean as I'm using an unpatched EG, but still can't reproduce this.

> this async bug

Just to clarify, this isn't an issue with async per se (as in async/await), but more of a race condition.  Is that what you mean?  If so, we may want to replace `async issue` in the title with `race condition` so it isn't confused with async/await behaviors - which are taking place on the repo and in jupyter_client lately.

Questions:
1.  How long do your remote kernels take to fully start (i.e., are available to execute commands)?
2. Are you switching back from B to A ahead of B's startup completion?

**Comment by yangyishan0901m** [comment]
For question 
1. Remote kernel will take around 5 to 10 sec to start.
2. I did not do fast switch, I will wait switch kernel finished then do next switch.  
I added log around https://github.com/jupyter/notebook/blame/master/notebook/services/sessions/handlers.py#L64, and I think the EG exception will hide the issue I mentioned. Could you please try to patch EG? I tried locally and without patch, and EG won't really delete remote kernel, and it just return 500 error. So that, the jupyter will reuse the old kernel. And I apply patch(which already in EG mainline) to fix cache port bug. The kernel can be deleted successfully. And I start see the issue I described. I believe after EG release new version, this issue will be revealed. 
Sorry for the confusion naming, since I don't know what the root cause, and I thought it is some async issue between database deletion and commit.

Here is the log I saw. And I add log to confirm session id is deleted in database.
delete session1 and delete session2
```
[I 12:42:19.601 NotebookApp] Connecting to wss://localhost:18888/api/kernels/c4333d11-e43b-4683-9ccd-d887daa3f39f/channels
getAllsession
[W 12:42:20.564 NotebookApp] Websocket connection has been closed via client disconnect or due to error.  Kernel with ID 'c4333d11-e43b-4683-9ccd-d887daa3f39f' may not be terminated on GatewayClient: https://localhost:18888
[I 12:42:20.564 NotebookApp] Attempting to re-establish the connection to Gateway: c4333d11-e43b-4683-9ccd-d887daa3f39f
[I 12:42:20.564 NotebookApp] Connecting to wss://localhost:18888/api/kernels/c4333d11-e43b-4683-9ccd-d887daa3f39f/channels
[W 12:42:20.589 NotebookApp] Websocket connection has been closed via client disconnect or due to error.  Kernel with ID 'c4333d11-e43b-4683-9ccd-d887daa3f39f' may not be terminated on GatewayClient: https://localhost:18888
postAllsession
first:False
create session1:Untitled1.ipynb
[I 12:42:22.938 NotebookApp] Request start kernel: kernel_id=None, path=""
[I 12:42:23.836 NotebookApp] Kernel started: 8d93e1a6-3dfb-4058-b4cb-c126510cc4d9
get_session:<sqlite3.Row object at 0x10b51ac50>
[I 12:42:25.187 NotebookApp] Connecting to wss://localhost:18888/api/kernels/8d93e1a6-3dfb-4058-b4cb-c126510cc4d9/channels
delete one session:dea09da9-d720-4fd4-80ff-b0093ee4bf91
get_session:<sqlite3.Row object at 0x10b7ffe70>
[I 12:42:27.352 NotebookApp] Saving file at /Untitled1.ipynb
postAllsession
delete session1:dea09da9-d720-4fd4-80ff-b0093ee4bf91
delete session2:dea09da9-d720-4fd4-80ff-b0093ee4bf91
[W 12:42:30.282 NotebookApp] Kernel not found at: https://localhost:18888/api/kernels/8d93e1a6-3dfb-4058-b4cb-c126510cc4d9
first:True
already exists1:Untitled1.ipynb
[W 12:42:30.282 NotebookApp] 404 POST /api/sessions (::1): Session not found: path='Untitled1.ipynb'
[W 12:42:30.283 NotebookApp] Session not found: path='Untitled1.ipynb'
[W 12:42:30.283 NotebookApp] 404 POST /api/sessions (::1) 1720.57ms referer=http://localhost:8889/notebooks/Untitled1.ipynb
```

**Comment by kevin-bates** [comment]
I'm sorry, but I still cannot reproduce this.  Here's what I'm doing...
1. Start kernel 'Python 3' and wait for it to fully start (hollow circle next to kernel name).
    a. Capture /api/sessions against Notebook server.
2. Using the 'Change kernel' menu, change kernel to 'Spark - Python (YARN Cluster Mode)' and wait for it to fully start (5 - 10 secs)
    a. Capture /api/sessions against Notebook server.
3. Using the 'Change kernel' menu, change kernel to 'Python 3' and wait for it to fully start.
    a. Capture /api/sessions against Notebook server.

Are you encountering empty results on step 3a or both 2a and 3a?  I see complete and proper outputs on all three steps.

Can you please start Notebook and EG with `--debug`. It might be helpful to compare Notebook console outputs.

I'm also not seeing any of these?
```
[W 12:42:20.564 NotebookApp] Websocket connection has been closed via client disconnect or due to error.  Kernel with ID 'c4333d11-e43b-4683-9ccd-d887daa3f39f' may not be terminated on GatewayClient: https://localhost:18888
[I 12:42:20.564 NotebookApp] Attempting to re-establish the connection to Gateway: c4333d11-e43b-4683-9ccd-d887daa3f39f
[I 12:42:20.564 NotebookApp] Connecting to wss://localhost:18888/api/kernels/c4333d11-e43b-4683-9ccd-d887daa3f39f/channels
[W 12:42:20.589 NotebookApp] Websocket connection has been closed via client disconnect or due to error.  Kernel with ID 'c4333d11-e43b-4683-9ccd-d887daa3f39f' may not be terminated on GatewayClient: https://localhost:18888
```
I do see that your EG is local to your Notebook server.  I will try that configuration next.  My current configuration has EG on a node of my YARN cluster with Notebook on my desktop.  Perhaps the two Notebook instances are colliding on your system.  (Total conjecture at this point)

**Comment by kevin-bates** [comment]
Hi @yangyishan0901m - did you discover something different that caused things to work?  If not, I'm happy to help investigate, although it might be best to open an issue in the [EG repo](https://github.com/jupyter/enterprise_gateway/issues) since this appears to be specific to that. Thanks.
