### ISSUE TITLE
Review action/command names

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#532]
With the new action/command palette, the names of the actions become user visible. Because changing them will now be a public UI/API breakage, we should review our naming approaches before 4.1 comes out. I can take the lead on this.

**Comment by ellisonbg** [comment]
Pinging @sccolbert @dwillmer

**Comment by Carreau** [comment]
Brian, can we close this one ?

**Comment by ellisonbg** [comment]
Yep, closing...
