### ISSUE TITLE
Creating Jupyter Notebook Failed: error to write a readonly database

### ISSUE THREAD

**Issue by T-DevH** [jupyter/notebook#5321]
have installed Jupyter notebook. with python 3

When I try to create a new notebook file, I get a pop up windows saying: (image attached) An error occurred while creating a new notebook. Unexpected error while saving file: Untitled.ipynb attempt to write a readonly database

`[W 20:00:11.307 NotebookApp] 500 POST /api/contents (127.0.0.1): Unexpected error while saving file: Untitled.ipynb attempt to write a readonly database         
[W 20:00:11.307 NotebookApp] Unexpected error while saving file: Untitled.ipynb attempt to write a readonly database`

![Screenshot from 2020-03-28 19-57-17](https://user-images.githubusercontent.com/53409247/77987468-b98bd580-72ce-11ea-89aa-95dbf690b44b.png)

**Comment by T-DevH** [comment]
I am using Ubuntu 18.04, Only way to work is to access sudo bash first and then type 'jupyter notebook --allow-root' to use Jupyter Notebook without any problem. 
I can't just type '$ jupyter notebook'

**Comment by T-DevH** [comment]
Looks like I found a solution. 'sudo chown -R tarik-deeplearning:tarik-deeplearning /home/tarik-deeplearning/.local/share/jupyter' to change permission. then need to repeat that process (check ownership and fix it). 'sudo chown -R tarik-deeplearning:tarik-deeplearning /home/tarik-deeplearning/Projects/GoogleNet/.ipynb_checkpoints' & it works. –

**Comment by MANISH9990** [comment]
Unexpected error while saving file: Untitled.ipynb attempt to write a readonly database

I am trying to open jupyter notebook in windows 10. But I am getting error  **Unexpected error while saving file: Untitled.ipynb attempt to write a readonly database**   while creating python file. Anyone have any solution.

**Comment by kevin-bates** [comment]
I suspect the meaningful clues lie in the full traceback that should be on the notebook server console/log and look something like in this post: https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/dGcZoFIci1k

Apparently, nbformat wants to store a signature in a SQLite DB and can't.  

As posted, this command should work around the issue: `jupyter notebook --NotebookNotary.db_file=':memory:'`

You probably need to update the permissions of the `nbsignatures.db` file located in the juptyer data directory.  To find that directory, enter: `jupyter --paths` and check the directories (in the order they're listed) under the `data:` stanza.  The first directory containing that file is what is being used (assuming you're running that command in the same python env as notebook).
