### ISSUE TITLE
Issue with pushed .ipynb file not displaying correctly in GitHub

### ISSUE THREAD

**Issue by ahull002** [jupyter/notebook#5323]
System: WIN10

IDE: ANACONDA/Jupyter Lab

Language: Python version 3.7.3

Library: pandas version 1.0.1

Data source/Location: https://github.com/ahull002/P001.predictive.maintenance.logreg

Dataset/File: 2_Data_Understanding.ipynb

User Story:

I am having a conversion issue when trying to view .pynb files I have pushed to GitHub. They look crooked as if there is some sort of rendering issue. The markdown cells from Jupyter notebook are displaying horizontal and squeezed versus vertical and sliding up or down.

Steps were taken:

searched StackOverflow for rendering issues
search GitHub: Jupyter Notebook won't load on Github #3555
asked around but it is hard to articulate this issue versus just showing someone

**Comment by diarmaidfinnerty** [comment]
Hi, did you find a solution for this? I am trying to push a notebook to github and it is displaying horizontally as well. 

As you can see the cells are rendering horizontally when on jupyterlab they render normally. I wonder is it to do with having a large image in markdown. 
Any solutions would be useful

![github_blob](https://user-images.githubusercontent.com/15366181/80423390-e0dac000-88d7-11ea-8fc5-8aa8f55a147a.PNG)


Jupyter Lab version 
![jupyterlab](https://user-images.githubusercontent.com/15366181/80423492-049e0600-88d8-11ea-904b-f4e310a64475.PNG)

**Comment by ahull002** [comment]
Hi,

I did not find a solution this yet! But it seems like you may have: what did you do to fix it?

Warm Regards,
Alfred

**Comment by diarmaidfinnerty** [comment]
I haven't found anything unfortunately. The correct version is how it appears on jupyterlab
This should get assigned

**Comment by ahull002** [comment]
I agree. It looks fine in Jupyterab but when pushed to GitHub it is completely misaligned.

Thanks for posting the picture example!

**Comment by diarmaidfinnerty** [comment]
In the end I just moved the pictures to the README and it rendered fine. This seems to be an issue with images in markdown. So you could either move the images or deleted them as am unsatisfactory solution.

**Comment by Zsailer** [comment]
This is an issue with Github's Notebook renderer—we (Project Jupyter) don't have control over their rendered (it's close-sourced). It's recommended that you use [nbviewer](https://github.com/jupyter/nbviewer/) to view notebooks on Github.

**Comment by bibhuashish** [comment]
Not able to even upload the new jupyter notebooks.  Has anyone found the solution?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyter-notebooks-cells-displaying-horizontally/6762/1

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyter-notebooks-cells-displaying-horizontally/6762/4

**Comment by sayebms1** [comment]
I have the same issue. Even while opening the notebook on nbviewer the issue persists.
