### ISSUE TITLE
Usability review for 4.1

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#533]
We have a lot of new Ui in the notebook that need a solid overall usability review before the 4.1 release. I can work on this.

**Comment by jdfreder** [comment]
This and the related issue #558 are the last two things open for 4.1.

Do you know what the time frame is for this?  Maybe anyone not participating in the usability review in person (@minrk @Carreau and I) can have a use-the-notebook part-day on Monday to make sure nothing critical is broken.

**Comment by Carreau** [comment]
One thing, I think we moved the celltoolbar selector from toolbar to menu. Is that API change ?

**Comment by jdfreder** [comment]
The DOM className ?  if so, yeah I'd consider that an API change - it will break peoples custom css

**Comment by ellisonbg** [comment]
I don't consider our DOM class names like the celltoolbar to be public API.
To me our public DOM API right now is the stuff that ends up in nbconvert's
HTML output.

Part of releasing new features is taking the time to get them as right as
possible before release. We have enough usability problems as it is and
can't afford to pile on new usability and design debt. I am not saying we
need to bike shed and or get things perfect.

I should be able to spend time on this over the weekend and early next week.

On Fri, Oct 23, 2015 at 7:06 PM, Jonathan Frederic <notifications@github.com
> wrote:

> The DOM className ? if so, yeah I'd consider that an API change - it will
> break peoples custom css
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/533#issuecomment-150712665>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
No I mean the actual UI element is now gone.
I was like WTF, where is it:

<img width="539" alt="screen shot 2015-10-23 at 17 22 13" src="https://cloud.githubusercontent.com/assets/335567/10707687/48f09782-79ab-11e5-811c-4a27c18fcc38.png">

<img width="502" alt="screen shot 2015-10-23 at 17 22 35" src="https://cloud.githubusercontent.com/assets/335567/10707665/c26eabb8-79aa-11e5-8c0d-007d927aa40d.png">

I I found it because I knew there was a PR for that, and I knew what to look for.
This is actually changing user UI in between minor releases.

I'm not against the new location in the menu, I just think that a `CellToolbar` button which tells you where the new menu is would be nice, otherwise user will WTF when they **need** to use it at the worst moment.

**Comment by ellisonbg** [comment]
Ahh, got it. Any ideas on how to transition users to the new location more
easily? Want to give a button a go?

On Fri, Oct 23, 2015 at 8:27 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> No I mean the actual UI element is now gone.
> I was like WTF, where is it:
>
> [image: screen shot 2015-10-23 at 17 22 13]
> <https://cloud.githubusercontent.com/assets/335567/10707687/48f09782-79ab-11e5-811c-4a27c18fcc38.png>
>
> [image: screen shot 2015-10-23 at 17 22 35]
> <https://cloud.githubusercontent.com/assets/335567/10707665/c26eabb8-79aa-11e5-8c0d-007d927aa40d.png>
>
> I I found it because I knew there was a PR for that, and I knew what to
> look for.
> This is actually changing user UI in between minor releases.
>
> I'm not against the new location in the menu, I just think that a
> CellToolbar button which tells you where the new menu is would be nice,
> otherwise user will WTF when they *need* to use it at the worst moment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/533#issuecomment-150727332>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
I can display and highlight the location in the menu (with animation)through JS:
<img width="492" alt="screen shot 2015-10-23 at 22 42 20" src="https://cloud.githubusercontent.com/assets/335567/10709178/5ff189e2-79d7-11e5-8a78-7ce670393e05.png">

I can tackle that on monday.

**Comment by willingc** [comment]
@jhamrick Any usability thoughts on the changes to Cell Toolbar -> Create Assignment and nbgrader?

**Comment by jhamrick** [comment]
Thanks for the ping. I like something like Matthias' suggestion, though
I am away this weekend do will have a closer look on Monday.

**Comment by jdfreder** [comment]
@ellisonbg how's the usability study coming along?  Any issues arise yet that we can start to address?

**Comment by ellisonbg** [comment]
Been working on it this morning.

Found one just now - when you are using the command palette and I have
typed enough that there is only a single option left, if I press return it
doesn't do anything - I have to do arrow down to pick that single option.
In that case a simple return should "just work"

More to come soon...

On Mon, Oct 26, 2015 at 11:23 AM, Jonathan Frederic <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> how's the usability study
> coming along? Any issues arise yet that we can start to address?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/533#issuecomment-151172569>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> Found one just now - when you are using the command palette and I have
> typed enough that there is only a single option left, if I press return it
> doesn't do anything - I have to do arrow down to pick that single option.
> In that case a simple return should "just work"

I'm aware of this one there is already an issue open somewhere, 
it is one of the first thing I though about.
It is though technically really annoying to do for now, as for fuzzy searching. 
Otherwise it would already be in. It might need some refactor upstream.

**Comment by jhamrick** [comment]
Just had a look at this. I love the UI deprecation for the celltoolbar -- nice job @Carreau ! Seems like everything still works fine with nbgrader (I think the tests will break, but the actual functionality seems to be ok).

One note on the help for the keyboard shortcuts which might be potentially confusing -- the closeness of the description of "command mode" and the command key implies that they have something to do with each other (which they don't):

![image](https://cloud.githubusercontent.com/assets/83444/10738003/7377ef54-7bd2-11e5-992f-964d8ef3cadb.png)

I would suggest moving the section about the key names into a different box (maybe yellow or green or something) and out of the one that describes the different modes. Initially I was confused because I thought maybe the key bindings had changed and command had something to do with command mode now -- and I'm *used* to using the notebook :smile:

**Comment by ellisonbg** [comment]
I had the same experience as Jess with that. I think using a separate box
makes sense. Although, I think the color could be the same as both are
general informative.

On Mon, Oct 26, 2015 at 2:14 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> Just had a look at this. I love the UI deprecation for the celltoolbar --
> nice job @Carreau <https://github.com/Carreau> ! Seems like everything
> still works fine with nbgrader (I think the tests will break, but the
> actual functionality seems to be ok).
>
> One note on the help for the keyboard shortcuts which might be potentially
> confusing -- the closeness of the description of "command mode" and the
> command key implies that they have something to do with each other (which
> they don't):
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/83444/10738003/7377ef54-7bd2-11e5-992f-964d8ef3cadb.png>
>
> I would suggest moving the section about the key names into a different
> box (maybe yellow or green or something) and out of the one that describes
> the different modes. Initially I was confused because I thought maybe the
> key bindings had changed and command had something to do with command mode
> now -- and I'm *used* to using the notebook [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/533#issuecomment-151233528>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
Some more things:

* I like the blue bar that shows which cells are selected. However, it doesn't go away after merging cells and thus if I want to merge other cells it will merge *all* the cells including the one that was selected from before, and I can't seem to find a way to un-select it.

* Undoing the merging of cells is broken. It will un-delete the cell that was originally deleted, but it doesn't remove the source from the first cell that was merged in.

**Comment by ellisonbg** [comment]
You can unmark individual cells with ctrl-shift or do the "unmark-all-cell"
action in the command palette.

But we should probably start to create separate issues for the things we
find related to this.

On Mon, Oct 26, 2015 at 2:19 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> Some more things:
>
>    -
>
>    I like the blue bar that shows which cells are selected. However, it
>    doesn't go away after merging cells and thus if I want to merge other cells
>    it will merge *all* the cells including the one that was selected from
>    before, and I can't seem to find a way to un-select it.
>    -
>
>    Undoing the merging of cells is broken. It will un-delete the cell
>    that was originally deleted, but it doesn't remove the source from the
>    first cell that was merged in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/533#issuecomment-151235775>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
Ok, I will open a new issue then.

**Comment by Carreau** [comment]
> I like the blue bar that shows which cells are selected. However, it doesn't go away after merging cells and thus if I want to merge other cells it will merge all the cells including the one that was selected from before, and I can't seem to find a way to un-select it.

Escape will deselect once https://github.com/jupyter/notebook/pull/657 will be merged.

**Comment by Carreau** [comment]
How do you "undo merge" ? With undo delete ?

**Comment by Carreau** [comment]
(and Brian meant unselect with Ctrl-Space not shift)

**Comment by jhamrick** [comment]
Ok, I think having stuff be deselected with "escape" would make that less surprising for me. I was looking for a menu option and found none. The problem with relying on the command palette there is because users won't necessarily know the correct terminology -- e.g. I didn't know it was called "marked" (I would have thought to look for "selected"). Having unmarking being bound to escape seems intuitive, though.

**Comment by ellisonbg** [comment]
Jess makes a good point - do you think we should also have an edit menu
item for unmarking all cells as well?

On Mon, Oct 26, 2015 at 2:33 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> Ok, I think having stuff be deselected with "escape" would make that less
> surprising for me. I was looking for a menu option and found none. The
> problem with relying on the command palette there is because users won't
> necessarily know the correct terminology -- e.g. I didn't know it was
> called "marked" (I would have thought to look for "selected"). Having
> unmarking being bound to escape seems intuitive, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/533#issuecomment-151240742>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
Ok, all the various PRs I opened today should address I think all my usability concerns about the cell marking.
