### ISSUE TITLE
Jupyter notebook cannot connect to R Kernel

### ISSUE THREAD

**Issue by Carlos31213** [jupyter/notebook#5365]
Hello,

I have a problem with Jupyter notebook. I can connect to python kernels without a problem but if I want to create a new R notebook, the connection always fails. I use jupyter via Anaconda. I will put the terminal output below. Maybe one of you has had a similar problem and can help out. Thanks!

Best,
Carlos

[I 11:04:21.728 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
dyld: Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /Users/carlosscherlenberg/opt/anaconda3/lib/R/lib/libR.dylib
  Reason: image not found
[W 11:04:24.736 NotebookApp] KernelRestarter: restart failed
[W 11:04:24.737 NotebookApp] Kernel 677aa6d9-200f-4cb0-a3cb-ff70133b5f54 died, removing from map.
[W 11:05:09.759 NotebookApp] Timeout waiting for kernel_info reply from 677aa6d9-200f-4cb0-a3cb-ff70133b5f54
[E 11:05:09.761 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 677aa6d9-200f-4cb0-a3cb-ff70133b5f54)
[W 11:05:10.789 NotebookApp] 404 GET /api/kernels/677aa6d9-200f-4cb0-a3cb-ff70133b5f54/channels?session_id=668a76d848464d4f9c9543919d0a8c33 (::1): Kernel does not exist: 677aa6d9-200f-4cb0-a3cb-ff70133b5f54
[W 11:05:10.802 NotebookApp] 404 GET /api/kernels/677aa6d9-200f-4cb0-a3cb-ff70133b5f54/channels?session_id=668a76d848464d4f9c9543919d0a8c33 (::1) 14.89ms referer=None
[W 11:05:12.819 NotebookApp] Replacing stale connection: 677aa6d9-200f-4cb0-a3cb-ff70133b5f54:668a76d848464d4f9c9543919d0a8c33

**Comment by kevin-bates** [comment]
Hi @Carlos31213 - thanks for opening this issue.  Setting up the IRkernel (which I assume is the R kernel you're using) can be a bit more involved.  This portion of the traceback needs to be addressed:

>dyld: Library not loaded: @rpath/libreadline.6.2.dylib
Referenced from: /Users/carlosscherlenberg/opt/anaconda3/lib/R/lib/libR.dylib
Reason: image not found

I would also suggest visiting the installation instructions in the [IRkernel repo](https://github.com/IRkernel/IRkernel).

**Comment by Carlos31213** [comment]
Hello @kevin-bates, thank you for the quick reply! 
So to start of I have removed the IRkernel I had installed via anaconda environments. Then I tried to run the commands listed in the installation guide you provided, but got the following errors messages:

> install.packages('IRkernel')
trying URL 'https://cran.revolutionanalytics.com/bin/macosx/el-capitan/contrib/3.6/IRkernel_1.1.tgz'
Content type 'application/octet-stream' length 143064 bytes (139 KB)
==================================================
downloaded 139 KB

tar: Failed to set default locale

The downloaded binary packages are in
	/var/folders/g6/6bfh3wzj0h9fq3ny6m2_87280000gn/T//RtmpHMoEsR/downloaded_packages
> IRkernel::installspec()
Error: .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: if (id[2] != fn.dylib) {
  error: missing value where TRUE/FALSE needed
In addition: Warning message:
In system(paste(cmd.ot, " -D ", fn.dylib, sep = ""), intern = TRUE) :
  running command '/usr/bin/otool -D /Library/Frameworks/R.framework/Versions/3.6/Resources/library/pbdZMQ/libs/libzmq.5.dylib' had status 1
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
> 

Sorry if it's something obvious I am doing wrong here. I don't have a computer science background. Thanks a lot for helping out!

**Comment by kevin-bates** [comment]
Hi @Carlos31213 - nothing relative to R is obvious! :smile:

You might consult our esteemed colleague - google.  Here's a hit relative tot he `xcrun: error: invalid active developer` that might be helpful: https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

Should issues continue and you're running out of reliable posts on the web, I suggest opening an issue in https://github.com/IRkernel/IRkernel - since that's where the expertise for these kinds of problems reside.

**Comment by Carlos31213** [comment]
Hey @kevin-bates, thanks for the help! I will try to solve the issue by researching on my own and if there is nothing helping me out I will open an issue at irkernel.
Have a good day!
