### ISSUE TITLE
Option to download notebook as a Word file

### ISSUE THREAD

**Issue by aaqibqadeer** [jupyter/notebook#5366]
There should be an option to save the notebook as a Word (.doc, .docx) file.

It will be very helpful for blog writers and others who did some data analysis and visualization and now want to write an article. They can just easily download the notebook as a Word file (which includes all the code, markdown, and images) and continue to edit in the MS Word.

**Comment by kevin-bates** [comment]
Hi @aaqibqadeer - Thank you for your suggestion.

nbconvert is the place for this as that is where the "save as" functionality occurs.  In particular, see this issue: https://github.com/jupyter/nbconvert/issues/121

Closing.

**Comment by aaqibqadeer** [comment]
I see. Thank you for your quick response.
