### ISSUE TITLE
Issue: '##' is visible in markdown cell for notebook

### ISSUE THREAD

**Issue by gokulyc** [jupyter/notebook#5376]
![image](https://user-images.githubusercontent.com/13468848/79313380-ddc9f200-7f1d-11ea-8a9a-fad20b07858e.png)

Issue: '##' is visible in markdown cell for notebook

details:

The version of the notebook server is: 6.0.3
The server is running on this version of Python:
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

Current Kernel Information:
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

**Comment by kevin-bates** [comment]
Did you run the markdown cell?  This will trigger its rendering.  To edit again, double-click the markdown text and its raw form should reappear.

**Comment by gokulyc** [comment]
Ok i got it. I directly clicked on next cell. I thought it auto renders like that, my bad...

**Comment by kevin-bates** [comment]
No worries - closing.
