### ISSUE TITLE
Jupyter Notebook using wrong Python Version

### ISSUE THREAD

**Issue by RicardoJMPaiva** [jupyter/notebook#5377]
Hello!
I'ved installed jupyter notebook throught Anaconda (Anaconda Navigator) to open a notebook for a class. But when i run the first command (for example "!pip install geopandas") the installation is done on python 2.7.
Then when i try to import the geopandas directory does not recognise because i think that  is installed on python 3.7.
I think is easier to understand with some prints.
<img width="1159" alt="Screenshot 2020-04-15 at 13 14 14" src="https://user-images.githubusercontent.com/43242841/79336121-15836a80-7f1b-11ea-8ae9-725af75b9881.png">
<img width="1159" alt="Screenshot 2020-04-15 at 13 14 29" src="https://user-images.githubusercontent.com/43242841/79336130-187e5b00-7f1b-11ea-831a-4e919cda61c4.png">

I would like to know if someone can help me with this.
Thanks

**Comment by yochem** [comment]
Using `pip install ...` is not recommended. Use `<your python> -m pip install ...`. In this case it would probably be `python3 -m pip install geopandas`.
