### ISSUE TITLE
confusing behaviour for reimport pandas after pip install -U pandas

### ISSUE THREAD

**Issue by aohan237** [jupyter/notebook#5383]
first i import pandas as pd.
then i found maybe i should use the latest version of pandas.
so i tried !pip install -U pandas or import sys sys.execute -m pip install -U pandas.

but when i import pandas, it is still the old version of pandas.
i have check the pandas.__file__ and sys.execute  , it is the exactly path where my kernel lives.

so i check the ipython ,it is the latest version, and i use this kernel start a new jupyter notebook, at the first, it is the old verions, but if i restart the kernel ,then the latest verion comes.

can you explain why this happens?  what can i do if i just want to only upgrade a specfic module ,rather than restarting the whole kernel, which have plenty of data i dont want to reload

**Comment by jasongrout** [comment]
This is a python question. Reloading a library after updating it is very tricky to do. You can try doing something like the approaches suggested in https://stackoverflow.com/questions/684171/how-to-re-import-an-updated-package-while-in-python-interpreter

But the safest thing to do is to restart the kernel.

**Comment by aohan237** [comment]
@jasongrout  i tried reload the module, but reload will raise exception about something cant import.  such as "pandas.core.numpy", etc.

**Comment by jasongrout** [comment]
My guess is that your only option is to restart the kernel, then. Like I said, it is a tricky problem to cleanly reimport a module.

Perhaps you can serialize the data you want to save out to disk so you can reload it after restarting the kernel.

**Comment by aohan237** [comment]
thanks，i just did things like you said.
just curious aoubt it's behaviour.

**Comment by jasongrout** [comment]
(but you might also get better help for this question on a list dedicated to python questions)
