### ISSUE TITLE
Idea/New Feature: A "History" or "Recent Notebooks" 

### ISSUE THREAD

**Issue by tyk122** [jupyter/notebook#5384]
This is my first time contributing here so I apologize if this is not in line with the guidelines.  I'm not sure if this idea has been previously presented, but I was wondering what the interest would be in having a "History" or "Recent Notebooks" feature on the home page.  I know that I have a large collection of notebooks, many of which are buried in folders.  I'm not sure JupyterLab has anything like this either, but it would be helpful to me.  Just a thought anyway.

**Comment by jasongrout** [comment]
See https://github.com/jupyterlab/jupyterlab/issues/2043 for discussion and two extensions giving a recents view and a favorites view.

**Comment by jasongrout** [comment]
https://github.com/NERSC/jupyterlab-favorites and https://github.com/NERSC/jupyterlab-recents

**Comment by jasongrout** [comment]
(Closing as answered, but feel free to continue the discussion if those are not what you want)
