### ISSUE TITLE
Jupyter commands open PyCharm rather than browser

### ISSUE THREAD

**Issue by allej8** [jupyter/notebook#5392]
Have Anaconda3 installed as well as PyCharm Professional. Initially, Jupyter commands worked as intended by opening the default browser. One day I tried to open and edit a HTML file in a project in PyCharm and ever since both `jupyter notebook` and `jupyter lab` open an HTML file in PyCharm with essentially the output from the terminal. 

Wiping PyCharm causes Jupyter to behave normally but reinstalling unfortunately brought the issue right back. Any ideas?

**Comment by jpcastil** [comment]
What is the default setting for opening HTML files on your computer?

**Comment by allej8** [comment]
Whatever the default browser is. Switched it from Firefox to Chrome and everything behaves a little better. There is a benign error now when I launch either notebook or lab but both generally work as intended with Chrome as the default browser. Might be able to close due to finding a work around.

**Comment by Zsailer** [comment]
This sounds like an issue with PyCharm. It might be better to post an issue over there—perhaps they have a setting in PyCharm that hijacks the browser launching mechanism.
