### ISSUE TITLE
Ensemble for Word Embedding (FASTText and TFIDF)

### ISSUE THREAD

**Issue by DSKaarthick** [jupyter/notebook#5393]
Hi All,

We have Query_Text from enterprise commercial search and this tells what the users are searched about. now we have to find out similarity between two Query_Text. if both  QueryText are same in terms semantic , then mark both as same conversation else different conversation id.

We have decided to use FastText -Gensim  and TFIDF (TfidfVectorizer)
but we wanted to Ensemble use and  could not find how can i use ensemble for word embedding.

Please share me if any one have idea about this.

![image](https://user-images.githubusercontent.com/63085392/79863412-5be23900-83f5-11ea-9c84-092add31e4bb.png)

Thanks and Regards,
Karrthik

**Comment by kevin-bates** [comment]
This doesn't strike me as being related to this repository so I'm closing this issue.  If you can show how it's related, we can re-open at that time should that be warranted.  Thanks.
