### ISSUE TITLE
Build command broken on Windows

### ISSUE THREAD

**Issue by sccolbert** [jupyter/notebook#540]
Running `setup.py build` on Windows breaks on the CSS command. This is due to excessive quoting of the command by the `run` function.

[This change](https://github.com/jupyter/notebook/commit/f175b2391ae468de39831e65674012c9543b0ccb) introduced an extra level of quoting to all commands. 

On Windows, the `lessc` command list looks like the following:

```
['lessc', '--source-map', "--include-path='E:\\Development\\sccolbert\\notebook\\notebook\\static'", 'E:\\Development\\sccolbert\\notebook\\notebook\\static\\style\\ipython.less', 'E:\\Development\\sccolbert\\notebook\\notebook\\static\\style\\ipython.min.css']
```

Which would be valid if joined with spaces. But with the extra quoting, the command is invalid on Windows:

```
lessc --source-map '--include-path='"'"'E:\Development\sccolbert\notebook\notebook\static'"'"'' 'E:\Development\sccolbert\notebook\notebook\static\style\ipython.less' 'E:\Development\sccolbert\notebook\notebook\static\style\ipython.min.css'
```

The [docs](https://docs.python.org/2/library/pipes.html#pipes.quote) for `pipes.quote` indicate that the quoting is only compatible with Unix shells.

On my machine, doing a simple space-join is sufficient to fix the breakage. But, I'm not sure if this will cause breakage on other platforms.

pinging @jdfreder @minrk

**Comment by minrk** [comment]
Fixed by #550
