### ISSUE TITLE
custom_display_url changes only one URL

### ISSUE THREAD

**Issue by liamhuber** [jupyter/notebook#5400]
First, sorry if I'm posting this in the wrong sub-repo.

My issue is that after setting `c.NotebookApp.custom_display_url = 'http://mycustomurl/'`, it changes only the *first* url in the user output, e.g.

```
    Or copy and paste one of these URLs:
        http://mycustomurl/?token=[a token string]
     or http://127.0.0.1:8888/?token=[a token string]
```

In my particular case I'm just changing the port to 8009, and the result is `localhost:8009` and `127.0.0.1:8888` both appearing.

Would it be possible to show only one link whenever `custom_display_url` is set to something non-empty?

I tracked down [the issue](https://github.com/jupyter/docker-stacks/issues/709) where this url display was decided on, but couldn't find any more recent related issues.

**Comment by kevin-bates** [comment]
Hi @liamhuber - I apologize for the delayed response - this is the correct place to raise this issue.

Your issue makes sense to me.  Did you want to submit a pull request for this?

**Comment by kevin-bates** [comment]
Closed via #5544

**Comment by liamhuber** [comment]
@kevin-bates @LaurMerl,

Thanks for the fix and merge! Thanks for your patience on the gratitude too -- I'm on parental leave atm so my timelines for work stuff are super stretched out.

**Comment by kevin-bates** [comment]
No worries @liamhuber - thanks for raising the issue.  I'm sure there will be other opportunities to contribute to Jupyter.
 
Congratulations on your new addition! :tada:
