### ISSUE TITLE
Issue with headings

### ISSUE THREAD

**Issue by rajtulluri** [jupyter/notebook#5402]
Hi,
The headings created by either putting a '#' or HTML tags in a jupyter notebook when uploaded do not seem to render on my Github page. Why is this so? Is there any other method?
Here is a link to my repo - [Link](https://github.com/rajtulluri/Analyzing-Employee-Exit-Survey/blob/master/Analyzing%20employee%20Exit%20Survey.ipynb)
The headings appear fine when viewed in nbviewer - [Link](https://nbviewer.jupyter.org/github/rajtulluri/Analyzing-Employee-Exit-Survey/blob/master/Analyzing%20employee%20Exit%20Survey.ipynb)
Thanks

**Comment by Zsailer** [comment]
Unfortunately, this is an issue with Github's Notebook renderer. We don't have control over this (it's not open source), so we're unable to fix it. We recommend using NBViewer—which it looks like you're doing :+1:. 

Closing this for now.
