### ISSUE TITLE
Exception: Jupyter command `jupyter-notebook` not found.

### ISSUE THREAD

**Issue by ankitnagdeve** [jupyter/notebook#5409]
pip3 install jupyter
sudo apt install jupyter-core
sudo jupyter notebook --allow-root

i tried to download jupyter notebook directly on Ubuntu 20, but giving this following error

Traceback (most recent call last):
  File "/usr/bin/jupyter", line 11, in <module>
    load_entry_point('jupyter-core==4.6.3', 'console_scripts', 'jupyter')()
  File "/home/ankit/.local/lib/python3.8/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/home/ankit/.local/lib/python3.8/site-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-notebook` not found.

how to fixed this

**Comment by kevin-bates** [comment]
This implies that notebook is not installed although I would have expected that to have happened when you installed jupyter.  Running `jupyter --version` should confirm.  Try installing `notebook` explicitly.

**Comment by ankitnagdeve** [comment]
Yes I have tired it... and its working fine now i can use this with localhost
thank you Kevin for your reply.
