### ISSUE TITLE
[Errno 20] Not a directory: '/.../sublime'

### ISSUE THREAD

**Issue by nassmim** [jupyter/notebook#5420]
I am on a macos Mojave 10.14.6 and I am trying to launch a jupyter from anaconda but I get this error message and I could not find anywhere how to solve this: 

Erreur serveur :Traceback (most recent call last): File "/Users/Nassim/opt/anaconda3/envs/data_science_pro/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute result = yield result File "/Users/Nassim/opt/anaconda3/envs/data_science_pro/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run value = future.result() File "/Users/Nassim/opt/anaconda3/envs/data_science_pro/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper yielded = next(result) File "/Users/Nassim/opt/anaconda3/envs/data_science_pro/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get path=path, type=type, format=format, content=content, File "/Users/Nassim/opt/anaconda3/envs/data_science_pro/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 427, in get model = self._dir_model(path, content=content) File "/Users/Nassim/opt/anaconda3/envs/data_science_pro/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 334, in _dir_model if self.allow_hidden or not is_file_hidden(os_path, stat_res=st): File "/Users/Nassim/opt/anaconda3/envs/data_science_pro/lib/python3.7/site-packages/notebook/utils.py", line 149, in is_file_hidden_posix stat_res = os.stat(abs_path) NotADirectoryError: [Errno 20] Not a directory: '/Users/Nassim/sublime'

The issue seems to be raised from tornado, I have tried to downgrade it to 5.1.1 but even this does not work. And also I do not understand why it is trying to reach the '/Users/Nassim/sublime' folder.
This is in a virtual env I cloned from my base env. But same issue if I remain to the base env. 

Any solutions?

Thanks

**Comment by nassmim10** [comment]
Just checked on my professional computer running on windows, I have tornado 6.0.3 and everything works fine. So it is actually not due to this module.
