### ISSUE TITLE
Log kernel type 

### ISSUE THREAD

**Issue by pinarkavak** [jupyter/notebook#5424]
Kernel type information is only logged as a prometheus metric. It would be great to see it in the normal logs also.

I added this line: `self.log.info("Kernel type: %s" % self._kernels[kernel_id].kernel_name)`
at line 180 of "notebook/notebook/services/kernels/kernelmanager.py" and submitted PR: https://github.com/jupyter/notebook/pull/5425.

**Comment by kevin-bates** [comment]
Fixed via #5425
