### ISSUE TITLE
no files or folders appearing when i launch jupyter notebook

### ISSUE THREAD

**Issue by ShadowPeregrine** [jupyter/notebook#5427]
when i open jupyter notebook the files/folders are **not** present but the tools in the top are the only things which appear. you will understand this better with a screenshot.
<img width="960" alt="Capture5" src="https://user-images.githubusercontent.com/57762641/81144271-535f3600-8f91-11ea-9968-4056fbf0c626.PNG">

i can't even select, open, create files. please help me fix this issue.
thank you,
surya

**Comment by kevin-bates** [comment]
Hi @SuryaChethanReddy2 - thank you for opening this issue.  

Could you please post the contents of the notebook server's console/terminal from startup to this condition (which appears to be immediate)?  Thank you.

**Comment by SuryaChethanReddy2** [comment]
@kevin-bates 
<img width="660" alt="sdsa" src="https://user-images.githubusercontent.com/57762641/81388491-fcdf2c80-9135-11ea-96b3-b21e736c1a59.PNG">
this?

**Comment by kevin-bates** [comment]
Yes.  That looks clean.  Looks like you have the JupyterLab extension configured.

Hmm - I see this is the same location where you have anaconda installed and I wonder if Notebook is taking time to gather up its contents to display?  Could you try copying a notebook to some temporary location in a subfolder of `C:\Users\aka` (e.g., `C:\Users\aka\tmpdir`), then restart notebook with `jupyter notebook --notebook-dir=C:\Users\aka\tmpdir`.  This will isolate notebook's file content scope to just that directory.  If it starts properly and you see the single notebook file, then I would suggest pointing your `--notebook-dir` to a folder hierarchy that doesn't include your anaconda installation.

**Comment by SuryaChethanReddy2** [comment]
@kevin-bates could you please mention where to type the command` jupyter notebook --notebook-dir=C:\Users\aka\tmpdir`

**Comment by kevin-bates** [comment]
It shouldn't matter if you're pointing your notebook-dir at a different location.  If you were to type the command in `C:\Users\aka\tmpdir`, then you wouldn't need the `--notebook-dir` option at all since the default notebook directory is the current working directory (i.e., the location in which notebook is started).

**Comment by SuryaChethanReddy2** [comment]
@kevin-bates when i did `jupyter notebook --notebook-dir=C:\Users\aks\Desktop`(in anaconda prompt) i still got the same issue
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/57762641/81525260-b8d86b80-9371-11ea-8a7c-9e0baf0612f1.png">

**Comment by kevin-bates** [comment]
I don't know how populated your desktop is, but using your Desktop folder as your notebook-dir is not recommended for this experiment as this folder is typically used as an "access point" to many things - including folders.  In fact, we might find that it's your Desktop folder, and not your Anaconda folder that is the issue here - both of which have the potential for containing large amounts of files.

So that we (I) know the notebook-dir is not the root folder of a huge hierarchy, please follow my original instructions and **create** a new folder in `C:\Users\aka` (e.g., `C:\Users\aka\tmpdr`), place a couple of **files** into it, then, then start notebook pointing the `--notebook-dir` at that folder.

**Comment by SuryaChethanReddy2** [comment]
@kevin-bates 
<img width="844" alt="sdsa" src="https://user-images.githubusercontent.com/57762641/81638902-03bcb680-9438-11ea-9c6e-58ad08ec9037.PNG">
<img width="661" alt="sad" src="https://user-images.githubusercontent.com/57762641/81638913-0a4b2e00-9438-11ea-8cea-47cdd0980753.PNG">
<img width="881" alt="sdds" src="https://user-images.githubusercontent.com/57762641/81638918-0f0fe200-9438-11ea-8ede-ba6896df421c.PNG">
it still doesn't work

**Comment by kevin-bates** [comment]
@SuryaChethanReddy2 - although you created a new folder (`C:\tmpdr`) you still started notebook pointing the `notebook-dir` option at `C:\Users\aka\Desktop`.  As a result, this last experiment was invalid.

Please stop your currently running notebook server and issue the following command...
```
jupyter notebook --notebook-dir=C:\tmpdr
```

My original suggestion was for you to create `tmpdir` (note the additional 'i') in your home folder: `C:\Users\aka`, then run `jupyter notebook --notebook-dir=C:\Users\aka\tmpdir`.

**Comment by SuryaChethanReddy2** [comment]
@kevin-bates 
<img width="657" alt="dsads" src="https://user-images.githubusercontent.com/57762641/81910313-6acd9d00-95e9-11ea-9ded-c54fdb7ebd1a.PNG">
<img width="931" alt="asdsad" src="https://user-images.githubusercontent.com/57762641/81910320-6d2ff700-95e9-11ea-97e5-c97e93cd4a2e.PNG">
still doesn't work

**Comment by kevin-bates** [comment]
Thank you - I must be barking up the wrong tree here.

Using the New dropdown button on the right, are you able to create a new notebook or text file?  Do the other behaviors appear to work?  

For whatever reason, I don't think the contents service is working correctly.  Even if no files are present, you should see an indication that there are no files to display...
![image](https://user-images.githubusercontent.com/22599560/81941788-21139100-95ae-11ea-8e5e-f8d0aef0cfe2.png)

**Comment by SuryaChethanReddy2** [comment]
@kevin-bates no, i am not able to create any files.
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/57762641/82112022-00db0200-9767-11ea-8035-9f022139b05e.PNG">

**Comment by tugaevaea** [comment]
Hi there! Was this issue solved? I am facing the same...

**Comment by declanbarry1** [comment]
Also having the same issue

**Comment by Ibrahim-hussain** [comment]
Also having the same issue

**Comment by poojagilda** [comment]
Just now, i faced the same problem, you should select the path where the files are located/ the path from where you want to access the required files n then change the path in anaconda prompt.
cd C:\Users\USERNAME

**Comment by oncealegend** [comment]
same thing happened to me , i solved it by deleting conda and python also removing file paths from environmental variables . After that just reinstalled the newest python version , while installing it tick mark the box add path to environmental variables . After this use - _pip install notebook_     , now open the Jupiter notebook from CMD -- jipyter notebook  ---

worked for me :) hope it works for you
this error comes when there is multiple file paths for python present in environmental variables

**Comment by jberry777** [comment]
I encountered this issue today as well. This solved it for me:
`pip3 install 'notebook<6'`

**Comment by ShadowPeregrine** [comment]
how do you all find the solution? i tried for days but failed.
