### ISSUE TITLE
Jupyter Notebook launch error [OSError: [WinError 10038] An operation was attempted on something that is not a socket]

### ISSUE THREAD

**Issue by mik-niborrr** [jupyter/notebook#5435]
![Jupyter Notebook Error](https://user-images.githubusercontent.com/63914683/81505627-07671500-9334-11ea-9346-708105ad1b60.png)
(miknibor) C:\Users\mink9>jupyter notebook
[I 02:49:03.930 NotebookApp] Serving notebooks from local directory: C:\Users\mink9
[I 02:49:03.930 NotebookApp] The Jupyter Notebook is running at:
[I 02:49:03.930 NotebookApp] http://localhost:8888/?token=18110471a08ca8d7d80a0306919e2067762df21c32e25708
[I 02:49:03.930 NotebookApp]  or http://127.0.0.1:8888/?token=18110471a08ca8d7d80a0306919e2067762df21c32e25708
[I 02:49:03.930 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 02:49:03.934 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/mink9/AppData/Roaming/jupyter/runtime/nbserver-21608-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=18110471a08ca8d7d80a0306919e2067762df21c32e25708
     or http://127.0.0.1:8888/?token=18110471a08ca8d7d80a0306919e2067762df21c32e25708
[I 02:49:03.935 NotebookApp] Shutting down 0 kernels
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\miknibor\Scripts\jupyter-notebook-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\envs\miknibor\lib\site-packages\jupyter_core\application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\miknibor\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\envs\miknibor\lib\site-packages\notebook\notebookapp.py", line 1956, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\envs\miknibor\lib\site-packages\tornado\platform\asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\envs\miknibor\lib\asyncio\base_events.py", line 442, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\envs\miknibor\lib\asyncio\base_events.py", line 1426, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\ProgramData\Anaconda3\envs\miknibor\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\ProgramData\Anaconda3\envs\miknibor\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

When I try to launch the notebook through terminal I always end up getting this error. When I copy and paste the urls given it comes off with a "connection failure" page.
I am currently using Anaconda3 in python 3.7, in Windows 10
and I've tried to search up solutions to anything that is as close to the error I am getting but was not successful, and it's frustrating especially that I've just taken a step into learning python.
Is there any solution to the issues that I am facing?

Thank you for your time!

**Comment by tchaye59** [comment]
Hi! I have the same problem, did you find a solution?

**Comment by mik-niborrr** [comment]
> Hi! I have the same problem, did you find a solution?

Hi, yes fortunately Jupyter went up and running once I set IP and port as follows:
jupyter notebook --ip=127.0.0.1 --port=9999

**Comment by tchaye59** [comment]
> > Hi! I have the same problem, did you find a solution?
> 
> Hi, yes fortunately Jupyter went up and running once I set IP and port as follows:
> jupyter notebook --ip=127.0.0.X --port=9999
> 
> Though I am not quite sure if it will work the same with others

Thanks, it is working for me.
I just change the default IP in the config file: **~/.jupyter/jupyter_notebook_config.py**
To generate this config file you have to run the command:  **jupyter notebook --generate-config**
After you need to uncomment and set :   **c.NotebookApp.ip = '127.0.0.1'**

**Comment by kevin-bates** [comment]
Great responses - thank you.  Closing this issue.

**Comment by LIUxDD** [comment]
> > > 嗨！我有同样的问题，您找到解决方案了吗？
> > 
> > 
> > 嗨，是的，幸运的是，一旦我按如下所示设置IP和端口，Jupyter就可以启动并运行：
> > jupyter notebook --ip = 127.0.0.X --port = 9999
> > 虽然我不太确定它是否可以和其他人一起使用
> 
> 谢谢，它为我工作。
> 我只是更改了配置文件中的默认IP：**〜/ .jupyter / jupyter_notebook_config.py**
> 要生成此配置文件，您必须运行以下命令： **jupyter notebook --generate-config**
> 需要取消注释并设置后： **c.NotebookApp。 ip ='127.0.0.1'**

Thank you very much.
