### ISSUE TITLE
Notebook validation failed An invalid notebook may not function properly. The validation error was:

### ISSUE THREAD

**Issue by Bomma-Pranay** [jupyter/notebook#5437]
Why is this error coming whenever I try to open Jupyter notebook?
Notebook validation failed
An invalid notebook may not function properly. The validation error was:

Notebook validation failed: {'model_id': 'c8f1cd89dc4741759fda2ff9fd880337'} is not valid under any of the given schemas:
{
 "model_id": "c8f1cd89dc4741759fda2ff9fd880337"
}

**Comment by kevin-bates** [comment]
The content service is failing to validate the notebook.  It uses the [nbformat](https://github.com/jupyter/nbformat) application for this task.  You might take a look at https://github.com/jupyter/nbformat/issues/166 and see if loading your notebook using Jupyter Lab upgrades it to the expected format.

**Comment by Bomma-Pranay** [comment]
Loading my notebook in Jupyter Lab worked !! Thank you so much for fixing the issue!😊

**Comment by Bomma-Pranay** [comment]
Loading my notebook in Jupyter Lab worked !! Thank you so much for fixing the issue!😊
