### ISSUE TITLE
Add support to Bookmarks

### ISSUE THREAD

**Issue by rainwoodman** [jupyter/notebook#545]
This is a feature request. Most file browsers nowadays have bookmarks that allow user to directly jump to a directory without going through the tree. (at least in Nautilus / Windows Explorer)

Such feature can be quite useful when a user works on many projects in various locations of the file system, because a bookmark will allow the user to quickly jump to the project and set up a 'contextual' workspace, without clicking through several layers of directory hierarchy.

Bookmarks will also allow the user to jump to a directory that's off the 'root' of the notebook server. This is useful in some setups of jupyterhub where there users also obtain a separate location for storing files in addition to their home directory. 

To minimal changes to the UX is to append bookmarks to the 'Running'  page. halted notebooks and directories can be appended to the list, probably with a gray icon to indicate they are bookmarks to inactive notebook or a folder icon to indicate it is an icon.

Bookmarks shall be broken if the original location is gone.

**Comment by rainwoodman** [comment]
I would like to comment that bookmarks is in some sense normalizing the usecases created by the users in

http://stackoverflow.com/questions/15680463/change-ipython-working-directory

(e.g. creating a desktop shortcut that switch directories before launching an ipython notebook server)

**Comment by fperez** [comment]
It's also worth noting that you can use your browser's native bookmarking capabilities for much of this.  While having it natively implemented in Jupyter might allow for smarter functionality (exposing these bookmarks in more relevant locations, or having them be smarter about relative paths and ports, etc), at least if you assume that your server always runs on `localhost:8888://home/you/default/path/`, then your bookmarks can be fairly stable, and you can use your browser's bookmarks tab to get much of this job done.

Not the perfect solution, but I just want to point out a potential way out for some cases...

**Comment by minrk** [comment]
I feel like browsers already provide sufficient bookmark functionality, and we shouldn't be reimplementing bookmarks inside of a UI that already has bookmarks.

**Comment by rainwoodman** [comment]
I still feel in general it is difficult to locate notebook files with the current Files UI. Especially if directories contain ~ 100 of files.

If bookmarks are not the way to go, I would suggest these following features that enhance locating notebooks and files, and are difficult to relay to the browser UI. 

(more or less like http://linux.about.com/library/gnome/blgnome6n3c.htm)

- adding an edit button to the location bar
- add search (even just by file names for now) can also be useful. 
- tagging notebooks and searching tags.

These features are more or less supported in most of OS file browsers, probably because they do solve real issues for real users.

**Comment by minrk** [comment]
@rainwoodman I didn't say that bookmarks aren't the way to go, just that there are already bookmarks provided by the browser because every notebook and directory has a URL.

I think typing in the location is a good idea, and we've had it for a long time, but nobody has been able to implement it yet.

I think a better answer to the full features of a file browser is to provide a better API ([nbopen](https://github.com/takluyver/nbopen)) for opening notebooks from the real file browser. *Using* a real file browser will always be better than reimplementing one in a browser.

**Comment by JamiesHQ** [comment]
@rainwoodman : We're doing a little housekeeping on our issue log and noticed this thread from 2015. Have you found a good solution in the interim and would you like us to continue to keep the issue open?

cc: @gnestor

**Comment by gnestor** [comment]
I'm going to mark this as Reference and close for now...

**Comment by maxpv** [comment]
I know this is old, but is there any news on this?
