### ISSUE TITLE
Dockerfile CI support

### ISSUE THREAD

**Issue by jakirkham** [jupyter/notebook#546]
It would be nice if building of the Dockerfile was tested with CI. Potentially, this could include some usage tests of a container.

Due to the build time required, this probably should happen outside of the normal build matrix. It could also be done on a different CI service.

**Comment by rgbkrk** [comment]
I enjoy that it's outside the normal build matrix. That's the other reason we have the webhooks to docker in place, as well as running iptest (though those have since been taken out of the image itself).
