### ISSUE TITLE
check_origin() method for gateway based websocket communication

### ISSUE THREAD

**Issue by ricklamers** [jupyter/notebook#5460]
Hi all,

While proxying Jupyter Notebook combined with a gateway I ran into the issue of CORS enforcement by the tornado network lib for websocket connections.

In the  [notebook/gateway/handlers.py](https://github.com/jupyter/notebook/blob/20c2c66857430a0092a5e751fbfa5555f3b74054/notebook/gateway/handlers.py) that's used by the gateway there is no `check_origin(self, origin=None)` method, like there is in the [notebook/base/zmqhandlers.py](https://github.com/jupyter/notebook/blob/20c2c66857430a0092a5e751fbfa5555f3b74054/notebook/base/zmqhandlers.py).

I think it should be respecting the c.NotebookApp.allow_origin config too. Not sure if this is desired or a wontfix.

Cheers!

**Comment by kevin-bates** [comment]
Thank you for raising this issue.  I see [this change](https://github.com/jupyter/nb2kg/pull/22) was made to the NB2KG extension after Notebook included it and I suspect that needs to ported here.

**Comment by kevin-bates** [comment]
Hi @ricklamers - this topic being foreign to me, could you please describe how to configure/reproduce this so I can confirm that the previously referenced change addresses your situation?  Thank you.

**Comment by kevin-bates** [comment]
Nevermind - I was able to piece things together with some key assistance from @dylanzjy (the fixes original author).

**Comment by ricklamers** [comment]
I see it was indeed fixed in https://github.com/jupyter/nb2kg/pull/22 ! I think that should be usable for the gateway code to adhere to the config for origin checking on the websocket connection too.

Feel free to close this issue once @dylanzjy

**Comment by ricklamers** [comment]
Impressive turnaround! Great job
