### ISSUE TITLE
Jupyter Notebook's cell does not show up. 

### ISSUE THREAD

**Issue by SoominLee1206** [jupyter/notebook#5481]

**Comment by SoominLee1206** [comment]
I uploaded a jupyter notebook file on my repository, 
It shows another language, not python.
How can I solve it?

<img width="1068" alt="스크린샷 2020-05-26 오후 8 07 45" src="https://user-images.githubusercontent.com/64841056/82893933-c5bda780-9f8c-11ea-99af-be09a638af2e.png">

**Comment by kevin-bates** [comment]
hi @SoominLee1206.  

Notebook files (those files with `.ipynb` extensions) are just JSON documents.  The `"source"` stanza of your first cell appears to contain python import statements, so I suspect the language of your notebook is indeed python.

If you scroll to the end of file, you should see a `"metadata"` stanza, similar to this:
```json
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
```
The `"kernelspec"` stanza describes the kernel last used to run the notebook. It's `"language"` field will typically reflect the language used in the code cells (although some kernels support magics to support multiple embedded languages).
