### ISSUE TITLE
Issue with Jupiternote book. Could you please help me?

### ISSUE THREAD

**Issue by PeterSelvaraj1** [jupyter/notebook#5493]
![Annotation 2020-05-30 215540](https://user-images.githubusercontent.com/44896623/83333875-747d2300-a2c0-11ea-8b35-6cd24425aa33.png)

**Comment by PeterSelvaraj1** [comment]
All of sudden this error is occurring. Dont know what is the issue?

**Comment by kevin-bates** [comment]
I suspect your local `pandas.py` file is in conflict with the `import pandas` reference.  You might try renaming your local file to avoid that conflict.

**Comment by PeterSelvaraj1** [comment]
Thanks a lot sir. U r  such a genius,

**Comment by kevin-bates** [comment]
Glad you're moving forward. Closing.
