### ISSUE TITLE
Jupyter notebook cannot connect to kernel

### ISSUE THREAD

**Issue by butifnot0701** [jupyter/notebook#5496]
Hello.

Jupyter notebook can't connect to kernel as i get: "**A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.** " error message.

Things i've tried:

1. reinstall anaconda
2. reinstall tornado as version 5.1.1

I don't think it's a firewall issue as Im working at home and it worked just a few days ago.

Could anyone suggest a solution or even a direction in which I could look? I've been searching online and I am at loss.

Thank you very much.

**Comment by kevin-bates** [comment]
Could you please provide the contents of your Notebook server console?  I would expect some traceback information, etc. that might help troubleshoot.

**Comment by butifnot0701** [comment]
Thank you for quick response! Turns out that there was another random.py file that I created that was interfering. It works now. I will close the issue.
