### ISSUE TITLE
Is it possible to fold cell editors (or limit the height of editors)? We want to use ipynb as business reports sometimes (they don't like code, but they can read some sql if they want).

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#55]
a simple way to achieve:
Add a shrink cell mode. In shrink-cell mode, shrink cell height when it is out of focus.

**Comment by takluyver** [comment]
There's a codefolding extension here: https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Codefolding_v3

Depending on how you're using them, you could also use nbconvert to render notebooks to HTML. By supplying a custom template, you can format the result however you want.

**Comment by cailiang9** [comment]
Thanks a lot! I think my idea is a bit like gmail - only expand when editing. People want to read the output figures at first glance.

**Comment by flying-sheep** [comment]
you can extend [this template](https://github.com/jupyter/jupyter_nbconvert/blob/master/jupyter_nbconvert/templates/html/full.tpl), and in it override a block in the [“basic” template](https://github.com/jupyter/jupyter_nbconvert/blob/master/jupyter_nbconvert/templates/html/basic.tpl) it inherits from to do nothing:

```jinja2
{%- extends 'full.tpl' -%}
{%- block input_group -%}{%- endblock input_group -%}
```

**Comment by Carreau** [comment]
Closing as there is no plan to do anything.
