### ISSUE TITLE
Backspace doesn't delete empty line

### ISSUE THREAD

**Issue by m2-farzan** [jupyter/notebook#5502]
Bug description:

In a code cell, pressing backspace removes characters correctly until it reaches the beginning of the line. Then, it fails to delete the empty line and go up.

I stepped through the recent commits and tested them. Apparently d406b8c6a3d377bf1f8ae5744df2659161373947 is causing the problem.

**Comment by jasongrout** [comment]
Thanks for running master and finding the commit. Assigning to the 6.0.4 milestone so we don't ship broken code.

**Comment by kevin-bates** [comment]
@benthayer - would you be able to look into this as it appears related to #4880?

**Comment by benthayer** [comment]
Yes, I'll check it out this weekend. I think this code is pretty similar to the code I used to fix this in  https://github.com/jupyterlab/jupyterlab/pull/7401, so I'll check to see if that's an issue as well
