### ISSUE TITLE
NameError: name 'datetime' is not defined when run under python 3.5 on Windows 7

### ISSUE THREAD

**Issue by neokril** [jupyter/notebook#551]
When open notebook on win7 I always get the following error:

```
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "c:\program files\python 3.5\lib\site-packages\ipykernel\kernelbase.py", line 175, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "c:\program files\python 3.5\lib\site-packages\jupyter_client\session.py", line 870, in deserialize
    return adapt(message)
  File "c:\program files\python 3.5\lib\site-packages\jupyter_client\adapter.py", line 386, in adapt
    header['date'] = datetime.now().isoformat()
NameError: name 'datetime' is not defined
```

Components versions: MarkupSafe-0.23 decorator-4.0.4 ipykernel-4.1.0 ipython-4.0.0 ipython-genutils-0.1.0 ipywidgets-4.0.3 jinja2-2.8 jsonschema-2.5.1 jupyter-1.0.0 jupyter-client-4.1.0 jupyter-console-4.0.3 jupyter-core-4.0.6 mistune-0.7.1 nbconvert-4.0.0 nbformat-4.0.1 notebook-4.0.5 path.py-8.1.2 pickleshare-0.5 pygments-2.0.2 pyzmq-14.7.0 qtconsole-4.0.1 simplegeneric-0.8.1 tornado-4.2.1 traitlets-4.0.0

Quickfix is to add the following line on top of jupyter_client/adapter.py:

```
from datetime import datetime
```

**Comment by minrk** [comment]
Fixed in jupyter-client 4.1.1
