### ISSUE TITLE
Figures not flushed if code contains certain things

### ISSUE THREAD

**Issue by mildsunrise** [jupyter/notebook#5532]
I use Arch Linux, just upgraded and Jupyter starts making funny things like this one:

![Captura de 2020-06-12 22-35-26](https://user-images.githubusercontent.com/1177304/84544348-633f0800-acfd-11ea-84bb-c8b8085bc3de.png)

When a cell contains lines like `h = [ x for x in [1] ]`, it won't flush its figures.
Figures will then be rendered in the next cell that does not contain lines like these.
Seems like an ipython bug?

**Comment by mildsunrise** [comment]
using python 3.8.3 and

~~~
jupyter core     : 4.6.1
jupyter-notebook : 6.0.2
qtconsole        : not installed
ipython          : 7.15.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 2.1.4
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 4.4.0
traitlets        : 4.3.3
~~~

**Comment by JoaoFelipe** [comment]
Can you check if it still occurs with ipykernel 5.3.1?

**Comment by mildsunrise** [comment]
yeah, this is the same issue as #5568.
ipykernel 5.3.1 fixed it, thanks!! <3
