### ISSUE TITLE
unable to execute ipython kernel install --user command

### ISSUE THREAD

**Issue by angrosamund** [jupyter/notebook#5535]
I'm trying to run Jupyter Notebook but I'm unable to obtain any cell outputs and there seems to be a kernel error stated onscreen. I tried installing a new kernel? But I keep getting this error which I don't know how to solve. I am quite new to Ubuntu/programming, and would really appreciates some help/advice, thank you! 

This is my error 

ipython kernel install --user
Traceback (most recent call last):
  File "/home/apeiyin/anaconda3/envs/py36/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/apeiyin/anaconda3/envs/py36/lib/python3.7/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/apeiyin/anaconda3/envs/py36/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/apeiyin/anaconda3/envs/py36/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 352, in start
    return self.subapp.start()
  File "/home/apeiyin/anaconda3/envs/py36/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 577, in start
    return self.subapp.start()
  File "/home/apeiyin/anaconda3/envs/py36/lib/python3.7/site-packages/ipykernel/kernelspec.py", line 176, in start
    prefix=opts.prefix, display_name=opts.display_name)
  File "/home/apeiyin/anaconda3/envs/py36/lib/python3.7/site-packages/ipykernel/kernelspec.py", line 133, in install
    path, kernel_name=kernel_name, user=user, prefix=prefix)
  File "/home/apeiyin/anaconda3/envs/py36/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 345, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/home/apeiyin/anaconda3/envs/py36/lib/python3.7/shutil.py", line 368, in copytree
    raise Error(errors)
shutil.Error: [('/tmp/tmp9fntjp9c_kernels/python3/kernel.json', '/home/apeiyin/.local/share/jupyter/kernels/python3/kernel.json', '[Errno 1] Operation not permitted'), ('/tmp/tmp9fntjp9c_kernels/python3/logo-32x32.png', '/home/apeiyin/.local/share/jupyter/kernels/python3/logo-32x32.png', '[Errno 1] Operation not permitted'), ('/tmp/tmp9fntjp9c_kernels/python3/logo-64x64.png', '/home/apeiyin/.local/share/jupyter/kernels/python3/logo-64x64.png', '[Errno 1] Operation not permitted'), ('/tmp/tmp9fntjp9c_kernels/python3', '/home/apeiyin/.local/share/jupyter/kernels/python3', '[Errno 1] Operation not permitted')]

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by kevin-bates** [comment]
I would carefully check the permissions of this directory hierarchy: `/home/apeiyin/.local/share/jupyter/kernels/python3`.  

Does the `pyhon3` directory already exist and, if so, who is it owned by?  Check the owner of the parent `kernels` directory.  Given this appears to be a home directory, are you running the command as user `apeiyin`?  Can you create a directory in the `kernels` directory?

I would imagine failure to install the kernelspec may be related to your cell-runtime issue as well.

**Comment by angrosamund** [comment]
@kevin-bates both the python3 directory and the parent kernels directory are owned by 'root'. I am able to create new directories in 'kernels'.

**Comment by kevin-bates** [comment]
Your information in the linked issue was the key.  Please see this https://github.com/jupyter/notebook/issues/5536#issuecomment-644778703.

Regarding the re-installation of the kernel, do you see files in `/home/apeiyin/.local/share/jupyter/kernels/python3`?  Namely a `kernel.json` and a logo image file?  If so, I believe the error you're encountering is the command's inability to overwrite the existing files.

If necessary, you _could_ point Jupyter to use a different directory for these kinds of files by setting environment variable `JUPYTER_DATA_DIR` to a location you have more control over.
