### ISSUE TITLE
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython'

### ISSUE THREAD

**Issue by ggrrll** [jupyter/notebook#5543]
Hi,

I am not able to launch notebook, as it returns the same error as in #3435

neither `pip un/install`  `pyzmq` or `jsonschema` worked 

I am on Mac OS 10.15.5 and jupyter

```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.5.5
ipython          : 8.0.0.dev
ipykernel        : not installed
jupyter client   : not installed
jupyter lab      : 1.2.3
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.0.4
traitlets        : 4.3.3
```

Thanks for your help

(you can also reply [in this SO post](https://stackoverflow.com/questions/62432483/jupyter-importerror-cannot-import-name-constants-from-partially-initialized-m) if you want)

**Comment by ggrrll** [comment]
ok, I had two python v. 3.7 and 3.8 – I removed 3.7 and now it's fine (I still have to link the kernel, etc...)

**Comment by wang-nima** [comment]
hi @ggrrll how do you remove other python version? and how do you find all python version installed on Mac?

**Comment by ggrrll** [comment]
no, I still have v. 2.7 -- just open a terminal window, type `python`, press `tab key` and the autocomplete will show you what you have :)

**Comment by Mohsinrazaa** [comment]
Hey , use the following:
**pip uninstall pyzmq**
**pip install pyzmq**

The thing with conda is that it has a lot of conflicts, you might be having a conflict. Using simple pip command would help you to remove those conflicts. I mean it worked for me. I hope it helps

**Comment by sandyrock2020** [comment]
> Hey , use the following:
> **pip uninstall pyzmq**
> **pip install pyzmq**
> 
> The thing with conda is that it has a lot of conflicts, you might be having a conflict. Using simple pip command would help you to remove those conflicts. I mean it worked for me. I hope it helps

It worked. Thanks
