### ISSUE TITLE
can't load jupyter notebook in browser

### ISSUE THREAD

**Issue by angrosamund** [jupyter/notebook#5555]
I'm using Ubuntu 20.04 LTS (on WSL), and am trying to run jupyter notebook on a remote server. I'm quite new to using remote servers, so I would appreciate any help on this matter, thank you!

Steps:
1. Connect to remote server `ssh user@remote`
2. Install Anaconda 2020.02
3. Launch Jupyter Notebook  `jupyter-notebook --no-browser`

When I try using the `file://` link, it says that the file is not found, and that it may have been move or deleted. When I try using the other 2 given URLS into Chrome, there is the loading symbol but the webpage never loads. I'm not getting any error messages anywhere though.

Another thing I've noticed (not sure if this is useful) but my /home/user/.local/share/jupyter/runtime file does not have any .json files, whereas I had a few kernel .json files on my local computer (I was able to launch the notebook there successfully).

Alternatively, I've also tried using ssh tunneling using the following:
`localuser@localserver: $ ssh -N -f -L localhost:8888:localhost:8889 remoteuser@remotehost`

and obtained the following error
`channel 2: open failed: connect failed: Connection refused`
and several similar messages with different channel numbers.

**Comment by thealtruist** [comment]
Hi @angrosamund, there are a few workarounds needed to make this happen. I wrote an article that explains everything here:

[How to Set Up the Jupyter Notebook Home and Public Server On Windows Subsystem for Linux 2 (WSL2)](https://medium.com/@thealtruist/how-to-set-up-the-jupyter-notebook-home-and-public-server-on-windows-subsystem-for-linux-2-wsl2-e6990e328f36)
