### ISSUE TITLE
I'm new in the anaconda navigator and I guess I installed everything correctly. Jupiter notebook launched and everything seem okay but when I tried importing simpy it displayed the following error., ModuleNotFoundError: No module named 'simpy'

### ISSUE THREAD

**Issue by Ziwerd** [jupyter/notebook#5563]

**Comment by kevin-bates** [comment]
Sounds like the conda env in which 'simpy' was installed is a different conda env in which you're running notebook.  Try installing 'simpy' in the notebook env and restart notebook your kernel (or notebook server to be certain).

**Comment by nvspavan007** [comment]
Hi .  It's simple.  just type this command in jupyter notebook cell :  !pip install simpy. It will be solved .

**Comment by kevin-bates** [comment]
Thank you for the alternate form for installing the package.  Closing.

**Comment by nvspavan007** [comment]
so is the problem solved?
