### ISSUE TITLE
cartographic view

### ISSUE THREAD

**Issue by Gopichand-2255** [jupyter/notebook#5566]
# this is my code

import pandas as pd 
import cartopy.crs as ccrs 
import cartopy.feature as cfeature 
import matplotlib.pyplot as plt 

birddata = pd.read_csv("bird_tracking.csv") 
bird_names = pd.unique(birddata.bird_name) 

# To move forward, we need to specify a 
# specific projection that we're interested 
# in using. 
proj = ccrs.Mercator() 

plt.figure(figsize=(10,10)) 
ax = plt.axes(projection=proj) 
ax.set_extent((-25.0, 20.0, 52.0, 10.0)) 
ax.add_feature(cfeature.LAND) 
ax.add_feature(cfeature.OCEAN) 
ax.add_feature(cfeature.COASTLINE) 
ax.add_feature(cfeature.BORDERS, linestyle=':') 
for name in bird_names: 
	ix = birddata['bird_name'] == name 
	x,y = birddata.longitude[ix], birddata.latitude[ix] 
	ax.plot(x,y,'.', transform=ccrs.Geodetic(), label=name) 
plt.legend(loc="upper left") 
plt.show() 

# errors

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-8f28822e9abe> in <module>
      1 import pandas as pd
----> 2 import cartopy.crs as ccrs
      3 import cartopy.feature as cfeature
      4 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'cartopy'

I'm getting this type of error
what should i want to do

**Comment by kevin-bates** [comment]
This suggests `cartopy` is not installed in the environment in which the kernel is running.  Try installing it into the same env.  You should also be able to issue `!pip install cartopy` from a cell prior to the import statement to get the module installed.

Closing this issue as its not anything this repo needs to address.  We can still converse on this issue should further support be necessary.
