### ISSUE TITLE
WARNING: The scripts jupyter-bundlerextension, jupyter-extension and jupyter-server are installed in '/home/sneha/.local/bin' which is not on PATH.   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.   WARNING: The script voila is installed in '/home/sneha/.local/bin' which is not on PATH.   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

### ISSUE THREAD

**Issue by snehaverma3192** [jupyter/notebook#5579]
how do i change path
i am trying to open jupyter but this error shows up

**Comment by kevin-bates** [comment]
This is not an error - just a warning.  

To set your PATH to include the directory, you would do this prior to launching `jupyter <whatever>`:
```bash
prompt> export PATH=/home/sneha/.local/bin:${PATH}
prompt> jupyter <whatever>
```
However, that will only reflect the update to `PATH` _for the duration of the current shell_ nor will the update be reflected in new terminals, etc.  To make the update permanent, you'll need to update your shell's "profile" file.  I would suggest googling for that information as it requires more knowledge about your configuration.
