### ISSUE TITLE
Search and Replace issues

### ISSUE THREAD

**Issue by jasongrout** [jupyter/notebook#558]
First, the search and replace is _very_ nice!  I love the immediate feedback, especially.
In reviewing the search and replace, here are some issues I'm seeing:

Bugs/changes:
- [x] The joke in the regexp tooltip ("Now you have N+1 Problems") is funny to me, but not appropriate for this interface, I think.  On the other hand, it would be extremely helpful if the regexp tooltip said it was using javascript regexp syntax
- [x] selecting multiple cells, and then clicking Edit | Find and Replace deselects all but one cell.  Thus the "Replace in selected cells" is much less useful
- [x] "Replace in selected cells" checkbox actually also affects the find results, and so should be up with the case insensitive button (thanks to @ellisonbg for pointing this out)
- [x] ~~number of matches moved down next to the replace all button~~

Feature requests:
- [ ] I think it would be really useful to have filters for replacing only in code cells or only in markdown cells.

Visual style:
- [ ] Remove the blue highlight on the number of matches.
- [ ] Make the vertical spacing between the different elements more consistent. Rigth now there are at least 3-4 different spacings used.

**Comment by ellisonbg** [comment]
+1 on all these ideas - Jason and I did an in person UI/UX review of this.

On Thu, Oct 8, 2015 at 1:22 PM, Jason Grout <notifications@github.com>
wrote:

> First, the search and replace is *very* nice! I love the immediate
> feedback, especially.
> In reviewing the search and replace, here are some issues I'm seeing:
>
>    - The joke in the regexp tooltip ("Now you have N+1 Problems") is
>    funny to me, but not appropriate for this interface, I think. On the other
>    hand, it would be extremely helpful if the regexp tooltip said it was using
>    javascript regexp syntax
>    - selecting multiple cells, and then clicking Edit | Find and Replace
>    deselects all but one cell. Thus the "Replace in selected cells" is much
>    less useful
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/558>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
I added #566 which is the underlying problem of your second bullet- so I went ahead and checked it off the list here.  I also checked off the two points addressed by #567 .

**Comment by jasongrout** [comment]
On second thought, I'm not convinced that moving the number of matches down next to the replace all is better than at the top.  I like knowing how many matches I have as a summary of the scope of my replacements.  @ellisonbg?

**Comment by jdfreder** [comment]
I'd also -1 that because it can't be done with our utils dialog function as is.  We'd need to modify it to allow non-button content in the footer.  And like Jason says, I think it makes sense for it to live where it does.

**Comment by ellisonbg** [comment]
Ok

**Comment by jdfreder** [comment]
> I think it would be really useful to have filters for replacing only in code cells or only in markdown cells.

This should probably integrate into the tagging system we designed together a while back.

**Comment by Carreau** [comment]
#567 was only partially closing this, reopening.

**Comment by Carreau** [comment]
I"m not sure any of the remaining feature are blocking for 4.1

**Comment by ellisonbg** [comment]
I will try to look over things again.

On Thu, Oct 22, 2015 at 1:33 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> I"m not sure any of the remaining feature are blocking for 4.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/558#issuecomment-150298962>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
The all look like they can be bumped to 4.2 (or 5.0, whichever is our next target).

**Comment by ellisonbg** [comment]
Let's leave this as 4.1 to remind me about things to look at in final usability reviews before the release. But I am guessing we will close at the release.

**Comment by akhmerov** [comment]
It would be nice to be able to apply replacements not on all cells, but in each instance separately. Perhaps adding a replace button to every line, like below would be an option?

![replace_one_cell](https://cloud.githubusercontent.com/assets/2069677/11759896/f041630e-a0c0-11e5-8cfd-6c5d7d117ba4.png)

**Comment by Carreau** [comment]
The 3rd button (that have a weird symbol with look like align left) apply the replace only to cells selection. 

Replace on each preview is relatively complex to implement, though it is one of the things we were thinking about.

**Comment by akhmerov** [comment]
Yes, I saw the 'apply to selection', but it means planning before seeing the result, and so has a different functionality.

**Comment by ellisonbg** [comment]
I am opposed to trying implement that in our current UI - it doesn't have
the needed abstractions to do that well. In the new JupyterLab/Workbench it
will be quite easy to build a find/replace UI in a separate panel that
allows us to toggle the individual replacements while still showing the
notebook (in a non-model way).

On Sat, Dec 12, 2015 at 5:38 AM, Anton Akhmerov <notifications@github.com>
wrote:

> Yes, I saw the 'apply to selection', but it means planning before seeing
> the result, and so has a different functionality.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/558#issuecomment-164151099>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jtpio** [comment]
Closing as partially fixed by https://github.com/jupyter/notebook/pull/567.

This may have been fully fixed in the classic notebook UI later on.

This should also largely be improved in Notebook 7 too, which uses the JupyterLab Search and Replace functionality.

Thanks all!
