### ISSUE TITLE
Cannot create new files on mac BadYieldErrors

### ISSUE THREAD

**Issue by aksein** [jupyter/notebook#5602]
<img width="865" alt="Screen Shot 2020-07-13 at 1 36 59 AM" src="https://user-images.githubusercontent.com/68198431/87252917-5b63b680-c4a9-11ea-80d2-4b686d72868e.png">

**Comment by kevin-bates** [comment]
Tough to determine from this. 

Could you please provide the contents of the notebook server console window (scraped - no screenshot), as well as the output of `jupyter --version`?
