### ISSUE TITLE
Feature Request: suppressing output of different nature

### ISSUE THREAD

**Issue by Sisyphuss** [jupyter/notebook#561]
Notebook can be used for development as well as presentation. Some outputs (returned value, print, warning) are used for development, some are used for debugging, others are used for presentation. At a certain time, we may not want all outputs. Is there a way to toggle on/off output of different intentions?

For example, in C++, one can print debugging information in a special way, and define a macro later to suppress these printings, so that it could be delivered to the client. When find a bug, just undefine the macro to get all debugging printing.

**Comment by minrk** [comment]
You can use CSS to show/hide each of the different output *types* (result, display, stdout, stderr). Each output type has a different css class, so you can use `display: none` on these classes to hide what you want. The notebook does *not* have semantic information about things like warnings, though, so 'intention' is not available information. That would have to be done in the kernel, e.g. by using Python's warning filter system in the case of IPython.

I don't think you can generally distinguish between *types* of output for what's used for development and what's used for presentation. I have done plenty of presentations were I use every single output type Jupyter understands. You may, at the library level, be able to distinguish between what is 'presentation output' and what is 'debugging output', but Jupyter cannot, and probably most Kernels cannot, either.

**Comment by Carreau** [comment]
I'm going to close as this is really not likely to be implemented.
