### ISSUE TITLE
docx --TemplateExporter.exclude_input=True doesn't remove input cells

### ISSUE THREAD

**Issue by WysokiStudent** [jupyter/notebook#5623]
After running the command
```bash
jupyter nbconvert --to docx --TemplateExporter.exclude_input=True Untitled.ipynb  
```
where the content of Untitled.ipynb is a single cell containing ```print("Hello world!")``` and its output "Hello World".
The resulting Untitled.docx file contains:
```
print("Hello world!")
Hello world!
```

Running 
```bash
jupyter nbconvert --to pdf --TemplateExporter.exclude_input=True Untitled.ipynb 
```
results in Untitled.docx consisting only of the title, date and the text "Hello world!"

Is this difference a bug or is it by design?
Note, I copied the command from https://stackoverflow.com/a/50790330/13559733 where the author says that the command should remove input cells irrespective of the output format.

**Comment by kevin-bates** [comment]
Hi @WysokiStudent - this issue should be opened in the [nbconvert repo](https://github.com/jupyter/nbconvert).  Thanks.
