### ISSUE TITLE
Conda install doesn't work on AWS EMR Jupiter Notebook

### ISSUE THREAD

**Issue by MilenkoM** [jupyter/notebook#5625]
I tried this
`! conda install --channel=conda-forge nb_conda_kernels`
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
Elapsed: -
Same if I try Boto3 or Pyspark.
`! python -m nb_conda_kernels.install -v --status`
/opt/conda/bin/python: Error while finding module specification for 'nb_conda_kernels.install' (ModuleNotFoundError: No module named 'nb_conda_kernels')
`!type -a python`
python is /opt/conda/bin/python
python is /usr/bin/python
`!type -a conda`
conda is /opt/conda/bin/conda

How to resolve Nb_conda_kernels?

This is Conda list output
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.12                   py37_1    defaults
attrs                     19.3.0                     py_0    conda-forge
autovizwidget             0.13.1                     py_0    defaults
awseditorssparkmonitoringwidget 1.0                      py37_0    file:///tmp/conda-repo
awseditorsstorage         0.0.1                    py37_0    file:///tmp/conda-repo
backcall                  0.1.0                    py37_0    defaults
beautifulsoup4            4.9.0            py37hc8dfbb8_0    conda-forge
blas                      1.0                         mkl    defaults
bleach                    3.1.4                      py_0    defaults
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.1.1                      0    defaults
certifi                   2020.4.5.1               py37_0    defaults
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    defaults
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-build               3.19.2           py37hc8dfbb8_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-package-handling    1.6.0            py37h8f50634_2    conda-forge
conda-verify              3.1.1           py37hc8dfbb8_1001    conda-forge
cryptography              2.9.2            py37hb09aad4_0    conda-forge
cycler                    0.10.0                   py37_0    defaults
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.3                      py37_0    defaults
expat                     2.2.9                he1b5a44_2    conda-forge
filelock                  3.0.10                     py_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.1               he06d7ca_0    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gitdb                     4.0.2                      py_0    defaults
gitpython                 3.1.1                      py_1    defaults
glib                      2.64.2               h6f030ca_0    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.1.2                h6c8ec71_1    defaults
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
hdijupyterutils           0.12.9                     py_0    defaults
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
intel-openmp              2020.0                      166    defaults
ipykernel                 5.1.4            py37h39e3cac_0    defaults
ipython                   7.13.0           py37h5ca1d4c_0    defaults
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    defaults
jedi                      0.16.0                   py37_1    defaults
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.14.1                     py_0    defaults
jpeg                      9c                h14c3975_1001    conda-forge
json5                     0.9.4                      py_0    defaults
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter_client            6.1.2                      py_0    defaults
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                1.2.7                      py_0    conda-forge
jupyterlab-git            0.10.1                     py_0    conda-forge
jupyterlab_server         1.1.0                      py_0    defaults
kiwisolver                1.1.0            py37he6710b0_0    defaults
krb5                      1.16.4               h173b8e3_0    defaults
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libarchive                3.3.3             h3a8160c_1008    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblief                   0.9.0                hf8a498c_1    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libsodium                 1.0.16               h1bed415_0    defaults

**Comment by MilenkoM** [comment]
conda --config show

add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_conda_downgrades: False
allow_cycles: True
allow_non_channel_urls: False
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_activate_base: True
auto_stack: 0
auto_update_conda: False
bld_path: 
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: flexible
channels:
  - file:///tmp/conda-repo/
  - defaults
  - conda-forge
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
conda_build: {}
create_default_packages: []
croot: /opt/conda/conda-bld
custom_channels:
  pkgs/main: https://repo.anaconda.com
  pkgs/r: https://repo.anaconda.com
  pkgs/pro: https://repo.anaconda.com
custom_multichannels:
  defaults: 
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
  local: 
debug: False
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
default_python: 3.7
default_threads: None
deps_modifier: not_set
dev: False
disallowed_packages: []
download_only: False
dry_run: False
enable_private_envs: False
env_prompt: ({default_env}) 
envs_dirs:
  - /opt/conda/envs
  - /home/notebook/.conda/envs
error_upload_url: https://conda.io/conda-post/unexpected-error
execute_threads: 1
extra_safety_checks: False
force: False
force_32bit: False
force_reinstall: False
force_remove: False
ignore_pinned: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
migrated_custom_channels: {}
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pip_interop_enabled: False
pkgs_dirs:
  - /opt/conda/pkgs
  - /home/notebook/.conda/pkgs
proxy_servers: {}
quiet: False
remote_backoff_factor: 1
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
repodata_fns:
  - current_repodata.json
  - repodata.json
repodata_threads: None
report_errors: None
restore_free_channel: False
rollback_enabled: True
root_prefix: /opt/conda
safety_checks: warn
sat_solver: pycosat
separate_format_cache: False
shortcuts: True
show_channel_urls: True
solver_ignore_timestamps: False
ssl_verify: True
subdir: linux-64
subdirs:
  - linux-64
  - noarch
target_prefix_override: 
track_features: []
unsatisfiable_hints: True
unsatisfiable_hints_check_depth: 2
update_modifier: update_specs
use_index_cache: False
use_local: False
use_only_tar_bz2: False
verbosity: 0
verify_threads: 1
whitelist_channels: []

**Comment by kevin-bates** [comment]
I don't think installing `nb_conda_kernels` from a notebook cell is going to work, even if the installation was successful, because its installation would require the notebook server application to be restarted.  This is because `nb_conda_kernels` overrides the default `KernelSpecManager` class with their own so they can discover kernel specifications across the various conda envs and, essentially, configures the kernelspec on the fly so that the appropriate env is activated and "there can only be one" KernelSpecManager configured at a time.

That said, I don't know what kinds of access AWS EMR provides to the server instance and whether Notebook could be restarted, but a Notebook restart is required within the same instance for this kind of thing to work.

Should you continue to have installation issues, you should direct those issues to the [nb_conda_kernels repo](https://github.com/Anaconda-Platform/nb_conda_kernels).
