### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.nn'

### ISSUE THREAD

**Issue by YashPandya2001** [jupyter/notebook#5626]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-9222d105398f> in <module>
     15 from reco_utils.dataset.amazon_reviews import download_and_extract, data_preprocessing
     16 from reco_utils.dataset.download_utils import maybe_download
---> 17 from reco_utils.recommender.deeprec.models.sequential.sli_rec import SLI_RECModel
     18 ####  to use the other model, use one of the following lines:
     19 #from reco_utils.recommender.deeprec.models.sequential.asvd import A2SVDModel

D:\ADM Assignment 3\recommenders\reco_utils\recommender\deeprec\models\sequential\sli_rec.py in <module>
      6     SequentialBaseModel,
      7 )
----> 8 from tensorflow.nn import dynamic_rnn
      9 from reco_utils.recommender.deeprec.models.sequential.rnn_cell_implement import (
     10     Time4LSTMCell,

ModuleNotFoundError: No module named 'tensorflow.nn'

**Comment by kevin-bates** [comment]
You might try: `from tensorflow.python.ops.nn import dynamic_rnn` based on a quick google search.

Should you find this _is_ related to notebook, please provide the appropriate context.
