### ISSUE TITLE
Kernel is not getting connected

### ISSUE THREAD

**Issue by AnkS4** [jupyter/notebook#5630]
Jupyter showing "Kernel connecting" & then not connected after few minutes:

```
`AttributeError: module 're' has no attribute 'search'`

...

Kernel does not exist

```
[Terminal Log](https://gist.github.com/AnkS4/1110ba03a1cebd7f0230a60583ba104b)

**Comment by kevin-bates** [comment]
Your local file `/home/anks/re.py` is conflicting with the kernel's ability to load the regular expression module.  Please rename your local python file.
