### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by meteorsh** [jupyter/notebook#5633]
When I use ipython or jupyter notebook, it still gets wrong. I have installed module 'six'. So how to fix it?
![image](https://user-images.githubusercontent.com/46078304/88564819-4882e180-d066-11ea-9efd-59605f8b188d.png)
![image](https://user-images.githubusercontent.com/46078304/88564927-7405cc00-d066-11ea-9598-fc4c9df36bad.png)

**Comment by kevin-bates** [comment]
Looks like `ipython` and `pip3` are associated with two different python installations.  You might try using `pip` or `pip3` that is likely in `/usr/local/bin` to see if `six` gets installed into `/usr/local/lib/python3.7/site-packages`.

**Comment by meteorsh** [comment]
> Looks like `ipython` and `pip3` are associated with two different python installations. You might try using `pip` or `pip3` that is likely in `/usr/local/bin` to see if `six` gets installed into `/usr/local/lib/python3.7/site-packages`.

![image](https://user-images.githubusercontent.com/46078304/88609720-6e84a200-d0b7-11ea-8d0b-c6d58981817b.png)


My pip3 is at this path.

![image](https://user-images.githubusercontent.com/46078304/88609483-ccfd5080-d0b6-11ea-8251-e70fbc64463c.png)

Yep, I got into the directory `/usr/local/lib/python3.7/site-packages`, but I didn't find `six`.  So how can I install six into this directory? Should I change the pip3 install directory?

**Comment by kevin-bates** [comment]
Try forcing the use of the other pip3 to install the `six` package: `/usr/local/bin/pip3 install six`

**Comment by meteorsh** [comment]
> Try forcing the use of the other pip3 to install the `six` package: `/usr/local/bin/pip3 install six`

After I ran the command `cp /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/six.py /usr/local/lib/python3.7/site-packages/`, it works!

Thanks for give me the inspiration!

**Comment by SimasJan** [comment]
> > Try forcing the use of the other pip3 to install the `six` package: `/usr/local/bin/pip3 install six`
> 
> After I ran the command `cp /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/six.py /usr/local/lib/python3.7/site-packages/`, it works!
> 
> Thanks for give me the inspiration!

Thanks for your comment. Didn't initially worked for me within the virtual environment. I have installed six using pip outside the virtual environment and has fixed the problem within the virtual environment without the need to copy. :) Thank you again.

**Comment by UnmeshP** [comment]
pip install --ignore-installed six worked for me
