### ISSUE TITLE
[Help!]Jupyter notebook fail to connect to server

### ISSUE THREAD

**Issue by aussunny** [jupyter/notebook#5638]
The jupyter notebook was all fine on my chrome, until I have this issue since last week, not quite sure the reason behind this. 
Any comments or suggestion are welcome, I desperately need Jupiter notebook to get the project done with deadline approaching....
On the notebook, it was like:
![image](https://user-images.githubusercontent.com/23005563/88993381-22d92f00-d329-11ea-80c0-5def5904f7c1.png)
On the promo side, it was like:
![image](https://user-images.githubusercontent.com/23005563/88993461-5ddb6280-d329-11ea-967e-35abaeab5f5e.png)
I tried to uninstall the Jupiter notebook via:conda remove jupyter jupyter-client jupyter-console jupyter-core
![image](https://user-images.githubusercontent.com/23005563/88993513-8b281080-d329-11ea-8185-4dee93732f21.png)
I tried to uninstall the Jupiter notebook via:conda remove jupyter jupyter-client jupyter-console jupyter-core
![image](https://user-images.githubusercontent.com/23005563/88993582-b7dc2800-d329-11ea-9fd9-03a7d43d3899.png)
Seems it can not be removed, then I tried reinstall it via: pip install jupyter notebook
![image](https://user-images.githubusercontent.com/23005563/88993637-d7735080-d329-11ea-85d1-ccf69831bbdf.png)
![image](https://user-images.githubusercontent.com/23005563/88993665-e823c680-d329-11ea-87a7-e19f414f91fd.png)
I'm thinking uninstall conda, and reinstall everything. 
Any comments or suggestion are welcome, I desperately need Jupiter notebook to get the project done with deadline approaching....
Many thanks in advance.

**Comment by kevin-bates** [comment]
Please try upgrading notebook: `pip install --upgrade notebook`

**Comment by aussunny** [comment]
> Please try upgrading notebook: `pip install --upgrade notebook`

Oh my!!! it works, thanks so much!!!!!
