### ISSUE TITLE
Hey , use the following:

### ISSUE THREAD

**Issue by Ashit-cloud** [jupyter/notebook#5646]
Hey , use the following:
pip uninstall pyzmq
pip install pyzmq

The thing with conda is that it has a lot of conflicts, you might be having a conflict. Using simple pip command would help you to remove those conflicts. I mean it worked for me. I hope it helps

_Originally posted by @harsh23tyagi in https://github.com/jupyter/notebook/issues/3435#issuecomment-398549304_

**Comment by Ashit-cloud** [comment]
it worked
while installing pyzmq i am getting this error . how to resolve

ERROR: spyder 4.0.1 requires pyqt5<5.13; python_version >= "3", which is not installed.
ERROR: spyder 4.0.1 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.

**Comment by kevin-bates** [comment]
This doesn't appear to be a notebook issue.  If you disagree, please update the issue's title and provide additional information.  Thank you.

I'm closing this for now.  It can be reopened should that be deemed necessary.
