### ISSUE TITLE
Kernel starting,please wait

### ISSUE THREAD

**Issue by Dhananjay201** [jupyter/notebook#5647]
I have tried out multiple things but the issue still persists.Chrome is up to date.No ad blocking plugins.Please Help

**Comment by Dhananjay201** [comment]
Does not work in Firefox as well.Shows same error.

**Comment by kevin-bates** [comment]
You'll need to provide more information for anyone to help you.  Start with a copy (preferably not a screenshot) of the notebook server's console when attempting to start your kernel.

**Comment by Dhananjay201** [comment]
Hey Kevin.Thanks for replying.I was able to solve this by upgrading prompt-toolkit and installing Flask-WTF.Cheers!
