### ISSUE TITLE
Multi-select doesn't work as expected

### ISSUE THREAD

**Issue by jdfreder** [jupyter/notebook#565]
I can't seem to figure out how to select multiple cells.  I've tried:

Ctrl-click (on the cells, prompts, and whitespace)
Shift-click
Meta-click
Ctrl-up/down
Shift-up/down
Meta-up/down

In both command and edit modes.

Running master of everything.  I've tested the API function `jupyter.notebook.extend_selection`, and it seems to work just fine.  It's a little ridiculous to require someone to open the web console and type code to select multiple cells.

**Comment by jdfreder** [comment]
I should mention, the machine is a Linux, Ubunutu variant.

**Comment by jdfreder** [comment]
*grumbles*  these are crappy default shortcuts: 

```
'shift-k': 'ipython.extend-selection-previous',
'shift-j': 'ipython.extend-selection-next',
```

Why not (additionally)

```
'shift-up': 'ipython.extend-selection-previous',
'shift-down': 'ipython.extend-selection-next',
```

**Comment by ellisonbg** [comment]
Yes, Jason and I were saying the say thing yesterday!

Also, there are many other bugs with multiple-selection we are finding -
will be opening issues on those separately.

On Fri, Oct 9, 2015 at 10:48 AM, Jonathan Frederic <notifications@github.com
> wrote:

> *grumbles* these are crappy default shortcuts:
>
> 'shift-k': 'ipython.extend-selection-previous',
> 'shift-j': 'ipython.extend-selection-next',
>
> Why not (additionally)
>
> 'shift-up': 'ipython.extend-selection-previous',
> 'shift-down': 'ipython.extend-selection-next',
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/565#issuecomment-146893075>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
