### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by hamelena** [jupyter/notebook#5651]
Hi,

starting JN today I see the error message "AttributeError: module 'time' has no attribute 'clock'". I learned that this module is deprecated in new Python and tried to upgrade JN but it didn't work. Can you help? Thank you in advance.

**Comment by kevin-bates** [comment]
Could you please provide some context in which this message is displayed?  Is this after starting a kernel (i.e., opening a notebook) or during startup of the server itself?  Please provide the console's output as well as the output of `jupyter --version`.  Thanks.

**Comment by hamelena** [comment]
![jupyter bug](https://user-images.githubusercontent.com/61279356/89530410-b6f63b00-d7ee-11ea-967b-d3183cc41286.jpg)
This is the pic of my console after starting a kernel. I tried to install resources through pip but it didn't resolve the issue.

The output of jupyter --version is:
jupyter core     : 4.6.3
jupyter-notebook : 6.1.1
qtconsole        : not installed

I'm ready to provide further informations.

**Comment by kevin-bates** [comment]
It looks like your IPython package is out of date as `time.clock()` was deprecated a couple of years ago and its use removed from IPython.  Try upgrading your IPython: `pip install --upgrade ipython` and ensure you're running a version >= 7.1.0 (with 7.17.0 being most current).

**Comment by hamelena** [comment]
Thank you, it worked!

**Comment by Sandy4321** [comment]
but I have latest version but still have this error

for
https://pixiedust.github.io/pixiedust/use.html

https://github.com/pixiedust/pixiedust/issues/796

![image](https://user-images.githubusercontent.com/11426119/105423167-06042100-5c13-11eb-82bb-e467b9092639.png)

**Comment by Sandy4321** [comment]
![image](https://user-images.githubusercontent.com/11426119/105423310-46fc3580-5c13-11eb-8d8f-062887a5b1b5.png)

**Comment by rajibahmed97** [comment]
> It looks like your IPython package is out of date as `time.clock()` was deprecated a couple of years ago and its use removed from IPython. Try upgrading your IPython: `pip install --upgrade ipython` and ensure you're running a version >= 7.1.0 (with 7.17.0 being most current).

Thank you, it works......
