### ISSUE TITLE
Downloading file is forbidden from SageMaker instance

### ISSUE THREAD

**Issue by CindyQi7788** [jupyter/notebook#5654]
I encountered issue to download file from my SageMaker instance since yesterday. The error shows as below.

403 : Forbidden
The error was:
Blocking Cross Origin request from https://xin-pilot-study.notebook.us-east-2.sagemaker.aws/tree/xxx

Previously I always could download files from my SageMaker Instance without any issue. 

Please help me on how to resolve it. Thanks a lot.

**Comment by Zsailer** [comment]
This looks like an issue for Amazon's Sagemaker Team. I suggest trying to reach out to their team directly. SageMaker is a proprietary product that happens to use Jupyter but is separate from the core Jupyter dev team.
