### ISSUE TITLE
not able to plot graph, getting error

### ISSUE THREAD

**Issue by 101Priyanshi** [jupyter/notebook#5658]
![lala](https://user-images.githubusercontent.com/47392409/89516938-aea1fe00-d7f6-11ea-91df-c41d58d28ea9.png)
![lala2](https://user-images.githubusercontent.com/47392409/89517015-c6798200-d7f6-11ea-9a9c-19dcf2c3e80b.png)
![image](https://user-images.githubusercontent.com/47392409/89517047-d09b8080-d7f6-11ea-9a44-c39261a1a331.png)
![image](https://user-images.githubusercontent.com/47392409/89517076-d8f3bb80-d7f6-11ea-8c1c-3b9c5d99587f.png)
![image](https://user-images.githubusercontent.com/47392409/89517099-e1e48d00-d7f6-11ea-8c44-218e2864c56f.png)

**Comment by 101Priyanshi** [comment]
please solve the error I'm getting

**Comment by kevin-bates** [comment]
Assuming this code runs fine outside a notebook, then this issue should be opened in the [IPython repo](https://github.com/ipython/ipython) as this is not an issue for this repository.  If you have not confirmed the code runs via pure python (without a notebook), I would ensure that works first.

Closing.
