### ISSUE TITLE
Selecting multiple cells and then clicking on the menu bar clears the selection

### ISSUE THREAD

**Issue by jdfreder** [jupyter/notebook#566]
Title says it all.

Ping @ellisonbg, who also is testing multiselect today.

This is the underlying cause of one of the points in #558

**Comment by ellisonbg** [comment]
Yep, this is the second one that @jasongrout and I saw!

**Comment by minrk** [comment]
Is this fixed by #597?

**Comment by ellisonbg** [comment]
Yep

On Tue, Oct 20, 2015 at 4:44 AM, Min RK <notifications@github.com> wrote:

> Is this fixed by #597 <https://github.com/jupyter/notebook/pull/597>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/566#issuecomment-149479509>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
