### ISSUE TITLE
Global [role=tooltip] styles impact notebook extensions

### ISSUE THREAD

**Issue by magdapoppins** [jupyter/notebook#5670]
In https://github.com/jupyter/notebook/commit/fb08a1bda3ec03a820891cb10434f128734b4fb8#diff-321a1fb8c95f4257fbede791b7856b7cR438-R459 some global styles regarding elements with `role="tooltip"` were introduced. They were meant to fix issues specific to the `.dynamic-buttons`-div element, and wouldn't need to be put in global scope.

Setting every element with `role="tooltip"` `visibility` to `hidden` impacts notebook extensions and makes it tedious to use this attribute correctly. 

I suggest changing the scope of the above mentioned style to `.dynamic-buttons [role=tooltip]` in notebook/static/tree/less/tree.less line 438.

**Comment by akx** [comment]
The related issue and PR (so GitHub links them here): #3964, #4729

**Comment by Zsailer** [comment]
@magdapoppins, good catch! Would you be interested in opening a PR with your proposed fix? Otherwise, I'm happy to submit the change myself. Thanks!

**Comment by magdapoppins** [comment]
@Zsailer I can open a pr tomorrow. 👍
