### ISSUE TITLE
Suggestion: Multiple outputs in notebook

### ISSUE THREAD

**Issue by mha-py** [jupyter/notebook#5675]
Hello!

Id like to make a suggestion: A cell can have multiple outputs, for example two outputs in two rows. This would allow to, for example, show debugging informtion of my code on the right column, while on the left column the normal progress bar is running, etc.

```
from ipython.something import multiple_outputs, set_output

multiple_outputs(2)
set_output(0) # <-- automatically
print('This is in output 0')
set_output(1)
print('This is in output 1')
plt.imshow(img) # <-- will be shown in the right column
```

In a debugging situation, one could do:

```
# ....
set_output(1) # <-- activate debugging output pipeline
print(information_for_debugging)
set_output(0) # <-- activate normal output pipeline
# ....
```

Column is meant as a html column in the notebook.
I think this would be super useful for many users!

**Comment by kevin-bates** [comment]
Hi @mha-py - thank you for this suggestion.  However, this appears more related to kernel behavior and not Notebook itself.  I  recommend opening this issue in either of the [`ipython`](https://github.com/ipython/ipython) or [`ipykernel`](https://github.com/ipython/ipykernel) repositories.

**Comment by jtpio** [comment]
> Hi @mha-py - thank you for this suggestion. However, this appears more related to kernel behavior and not Notebook itself. I recommend opening this issue in either of the [`ipython`](https://github.com/ipython/ipython) or [`ipykernel`](https://github.com/ipython/ipykernel) repositories.

Closing as this indeed sounds more related to the kernel behavior.
