### ISSUE TITLE
Limited Functionality of %%latex cell magic 

### ISSUE THREAD

**Issue by amjames** [jupyter/notebook#569]
It looks like when using the %%latex cell magic only math environments are rendered in the notebook. 

in a cell like this: 
```
%% latex 
\[
\hat{H}\Psi = E\Psi
\]
\begin{itemize}
\item First item
\end{itemize}
```

The equation will render correctly in the output cell but not the `itemize` environment. This seems to happen for other latex environments as well, and it is not very consistent. For example the align environment works but the equation environment does not. 

The docs simply say `Render the cell as a block of latex` for `%% latex`. Is this a bug, or is there only a subset of latex that is supported. If the latter is the case it should be added to the docs somewhere!

**Comment by jdfreder** [comment]
Hi @amjames ,

We only support a subset of latex in the live notebook because the component we use to render the latex, MathJax, only supports a subset.

You're right though, this should be better documented.

**Comment by amjames** [comment]
@jdfreder thanks for getting back to me.  

That is a shame, but understandable due to the limitations of MathJax. 

Is there any plan to include more widespread latex support in the live notebook? 

Thanks!

**Comment by jdfreder** [comment]
@minrk I'm curious, did this autoclose from the PR merge in ipython/ipython?

**Comment by willingc** [comment]
@jdfreder I think so. Likely because @minrk has sufficient privileges on both repos. https://github.com/blog/1439-closing-issues-across-repositories

**Comment by minrk** [comment]
@jdfreder yup, as @willingc explains, we can auto-close cross-linked issues as long as we have permission on the target repo.

**Comment by jdfreder** [comment]
> Is there any plan to include more widespread latex support in the live notebook?

@amjames not currently, unless MathJax decides to support more.
