### ISSUE TITLE
No buttons at all

### ISSUE THREAD

**Issue by KerimMatlab** [jupyter/notebook#5699]
Hi,

I'm new in python
I installed Anaconda and my jupyter notebook look as in the picture. As you can see there is no any buttons and I can't understand how to launch the code.
How to fix that?
Windows 10 x64
![image](https://user-images.githubusercontent.com/43808863/91382355-401ef180-e832-11ea-9865-f0d0256ab4dd.png)

**Comment by Zsailer** [comment]
The file you've opened is a markdown file (the file extension is `.md`), not a Jupyter Notebook file (which ends in `.ipynb`). 

Open an `.ipynb` file to see the full Jupyter Notebook interface. I'm closing issue for now. Feel free to reopen if you're still having issues.
