### ISSUE TITLE
LaTeX \bm not rendering

### ISSUE THREAD

**Issue by jakubbober** [jupyter/notebook#5700]
When I want to write LaTeX vectors in my notebook and I use `\bm` command for it, the bolded vector does not get generated and I just see the raw text with LaTeX code. Since `\boldsymbol` is deprecated and `\bm` is very commonly used, it would be nice to have `\bm` render in jupyter notebooks.

**Comment by Zsailer** [comment]
@jakubbober, thanks for opening this issue! 

The latex rendering in Jupyter Notebooks is done using MathJax, and unfortunately, it looks like MathJax doesn't currently support `\bm`. There is, however, an [issue open over there](https://github.com/mathjax/MathJax/issues/1219) to track this issue. We'll have to wait for the change to happen there before it works in Jupyter Notebooks. 

Closing here.
