### ISSUE TITLE
Add a technical overview of notebook and Docker to Developer Documentation 

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#571]
Prompted by discussion on PR #554.

Developers and end users may find technical details of how Notebook interacts with Docker to be helpful. A technical overview including details such as discussed in #554 would be valuable to developers and users. While the README is not well suited for detailed documentation, our Developer Documentation (https://jupyter-notebook.readthedocs.org/en/latest/#developer-documentation) would be a reasonable place for such detail.

cc/ @jakirkham @funkyfuture @minrk @ellisonbg 
Please label as docs, wishlist or 5.0. Thanks.

**Comment by funkyfuture** [comment]
i don't that would be the proper place for the usage instructions regarding Docker, it's expected to appear [on the Docker hub](https://hub.docker.com/r/jupyter/notebook/).

other discussions about the Docker image have also shown that there are enough differences between users' and developer's needs. therefore i cite myself. 

https://github.com/jupyter/notebook/pull/537#issue-110129811:

> i would also suggest that the docker registry repo is bound to another source repo as it is expected there to provide only stable releases or at least a stable release as default. atm only a reflection of the master's tip is available.
it would also allow to design the Dockerfile here for development purposes and to add image variants (i could make use of an onbuild-variant to include packages).
disclaimer: if this didn't change recently, the docker registry repo must be deleted and be created again to link it to another source repo. as a sideeffect all repo statistics go to void.

**Comment by jakirkham** [comment]
There are often many ways one could want to launch an image. Not to mention, it is worth noting how to build them. I can understand wanting to move them out of the README.

Can we make sure there is a link included in the README to the relevant section in the developer documentation? This way it will be easy to get more details for the GitHub and Docker Hub main pages.

**Comment by willingc** [comment]
@funkyfuture I don't see this section in the developer documentation as a place for usage instructions. I see it as a high level technical explanation of how the notebook interacts with the Docker daemon.

Usage and configuration documentation that is specific to individual operating systems using Jupyter  and Docker would be in their own documents in another section, linking to Docker specific documents as needed. Generic documentation would not cover the use cases with OS X and Windows adequately due to legacy use of boot2docker, more recent use of docker-machine, security permissions, and operating system versions.

@jakirkham Absolutely there should be a link from the README to any relevant sections in the Developer documentation or User documentation.

**Comment by ellisonbg** [comment]
I think we do want to have an explanation about the relationship between the notebook and docker. And because it spans multiple repos, I think the developer section of the jupyter/jupyter docs makes sense.

**Comment by ellisonbg** [comment]
Going to label as 4.2 for now - could be 4.1 or 5.0 depending on when it gets done.

**Comment by takluyver** [comment]
Anybody want to have a go at this for 5.0?

**Comment by takluyver** [comment]
I'm triaging issues for 5.1 - is anyone interested in tackling this, or shall we bump it again?

**Comment by funkyfuture** [comment]
though i know this doesn't belong to this issue; both Docker and Jupyter are getting more attention from the academia in regards to reproducible research. imo, it's worth to cover that in the user docs. i'll see that i get a look on the proceedings of a related conference that may be useful.

regarding your formulation @willingc, i don't really get it. Jupyter shouldn't interact with the Docker daemon at all. the daemon provides an isolated environment Jupyter runs in, but Jupyter isn't aware of that, it's just like any other Linux environment.

**Comment by willingc** [comment]
Thanks for the input @funkyfuture. This is a pretty old issue, and I'm sorry that I was not more precise in my language.

As an FYI, the [docker-stacks project](https://github.com/jupyter/docker-stacks) has information about Jupyter and docker. In addition, the work-in-process [Zero to JupyterHub with Kubernetes](https://zero-to-jupyterhub.readthedocs.io/en/latest/) documentation may be of interest.

**Comment by willingc** [comment]
@takluyver I recommend closing this issue due to the age and the fact that it is overly broad in scope. A newer more targeted issue would be more productive and actionable.

**Comment by takluyver** [comment]
Thanks @willingc - feel free to open one or more new issues for particular tasks. :-)
