### ISSUE TITLE
notebook=6.1.3 download files with spaces gives a 404

### ISSUE THREAD

**Issue by AbdealiJK** [jupyter/notebook#5715]
I was earlier using `notebook==6.0.3` and have recently shifted to `notebook==6.1.3`.
I find that with the newer version, when I try to download files with spaces - it fails witha  404 error.

I run jupyter notebook with `jupyter notebook`. No special configs have been set.

When I create a file called `my file.ipynb` and:
 - Download (gives 404): http://localhost:8888/files/my%2520file.ipynb?download=1
 - View (works fine): http://localhost:8888/notebooks/my%20file.ipynb

In jupyter 6.0.3 - When I create a file called `my file.ipynb` and:
 - Download (works fine): http://localhost:8888/files/my%20file.ipynb?download=1
 - View (works fine): http://localhost:8888/notebooks/my%20file.ipynb

It looks like when we download a file with spaces in it - the URL is different now (it has a extra %25 in it)

The same issue occurs if the folder has spaces instead of the file

NOTE: When I try this on try-jupyter https://jupyter.org/try it works fine - It seems to be using 6.0.3

**Comment by kevin-bates** [comment]
😞 Looks like [this update](https://github.com/jupyter/notebook/pull/5351/files#diff-1bb6ee004561527c18aa1fbae3ea8fffR1154) is leading to a double-encoding:  `<sp>` -> `%20` -> `%2520`

cc: @berendjan @Zsailer

**Comment by Zsailer** [comment]
Thanks for raising this issue, @AbdealiJK. 

Indeed—there's a double encoding happening. Fixed in #5720
