### ISSUE TITLE
I got this issue while running a Hydrogen in atom

### ISSUE THREAD

**Issue by anantgupta129** [jupyter/notebook#5717]
Check that the language for this file is set in Atom, that you have a Jupyter kernel installed for it, and that you have configured the language mapping in Hydrogen preferences.

To detect your current Python install you will need to run:

python -m pip install ipykernel
python -m ipykernel install --user

but i have everything installed and my language mapping is this

![image](https://user-images.githubusercontent.com/66518357/91716868-0b9e9300-ebae-11ea-8fc8-011930b8262f.png)

**Comment by kevin-bates** [comment]
>Check that the language for this file is set in Atom, that you have a Jupyter kernel installed for it, and that you have configured the language mapping in Hydrogen preferences.

>To detect your current Python install you will need to run:

>python -m pip install ipykernel
python -m ipykernel install --user

Is this all from some other product documentation?  

What is the actual issue you are seeing when attempting to use this kernel?  Please provide the notebook server's console output produced with attempting to use this kernel.

**Comment by anantgupta129** [comment]
its written above its not detecting python kernel i guess
this is the issue

**Check that the language for this file is set in Atom, that you have a Jupyter kernel installed for it, and that you have configured the language mapping in Hydrogen preferences.

To detect your current Python install you will need to run:

python -m pip install ipykernel
python -m ipykernel install --user**

**Comment by kevin-bates** [comment]
Is there any _notebook server_ console output when attempting to use this kernel?  What you provided originally is from Hydrogen and you'll need to track this from the Hydrogen side as everything so far points at its configuration.

Looking at the Hydrogen repo briefly, it appears it can be a little [frustrating initially](https://github.com/nteract/hydrogen/issues/1883).  [This particular issue](https://github.com/nteract/hydrogen/issues/1674) may be a good place to start.

I'm closing this issue.  Should there be something that warrants its reopening, we can address its state at that time.
