### ISSUE TITLE
Weird rendering of Jupyter notebook on Github

### ISSUE THREAD

**Issue by NielsRogge** [jupyter/notebook#5724]
My Jupyter notebook renders a bit weird on Github: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/Custom_Named_Entity_Recognition_with_BERT.ipynb

Could it be that this is missing CSS?

However, on nbviewer, everything looks fine: https://nbviewer.jupyter.org/github/NielsRogge/Transformers-Tutorials/blob/master/Custom_Named_Entity_Recognition_with_BERT.ipynb

Am I doing something wrong here?

**Comment by liamross** [comment]
I'm having the same issue, it also doesn't seem to be running python code and all image links are broken. I'm relatively new to Jupyter notebook, but after doing a quick search for other notebooks hosted on GitHub I've found many that seem to be configured exactly the same [like this](https://github.com/jerry-git/learn-python3/blob/master/notebooks/beginner/notebooks/conditionals.ipynb) but are not broken.

**Comment by liamross** [comment]
For context, here's my `metadata`:

```json
{
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```

And here's the metadata of [the working example](https://github.com/jerry-git/learn-python3/blob/master/notebooks/beginner/notebooks/conditionals.ipynb):

```json
{
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.4" // <-- DIFFERENT
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1 // <-- DIFFERENT
}
```

**Comment by zack-kimble** [comment]
I don't think it's related to the file, but the account. All of my .ipynb started rendering weird today, even ones that have not been changed in months.

Even a notebook in my fork of openai baselines has the same issue. It's up-to-date with the upstream master and last commit was in 2018.

My fork is misrendered: https://github.com/zack-kimble/baselines/tree/master/docs/viz
Upstream is fine: https://github.com/openai/baselines/blob/master/docs/viz/viz.ipynb

I think this is a github issue, not a jupyter issue. I contacted support there, but haven't heard anything

**Comment by kevin-bates** [comment]
As colleagues have noted in other issues, Project Jupyter has no control over how notebooks render on GitHub.  Please file a support request with GitHub if their notebook rendering is not working.  We also recommended that you use [nbviewer](https://github.com/jupyter/nbviewer/) to view notebooks on Github. 

cf. #3035, #3555, #4582, #5323
