### ISSUE TITLE
Jupyter Notebook Configuration lost

### ISSUE THREAD

**Issue by yash-rai22** [jupyter/notebook#5725]
The code is colorless, the tables don't have lines
The code is shifted left
https://github.com/yash-rai22/Marketing-Campaign-for-Banking-Products/blob/master/MLproject.ipynb

**Comment by liamross** [comment]
Same issue as #5724

**Comment by kevin-bates** [comment]
As colleagues have noted in other issues, Project Jupyter has no control over how notebooks render on GitHub.  Please file a support request with GitHub if their notebook rendering is not working.  We also recommended that you use [nbviewer](https://github.com/jupyter/nbviewer/) to view notebooks on Github. 

cf. #3035, #3555, #4582, #5323
