### ISSUE TITLE
Windows install using `conda-forge` as only channel

### ISSUE THREAD

**Issue by adriendelsalle** [jupyter/notebook#5729]
Hi! Thanks for your work!

Description
---
I hit `UnsatisfiableError`s using `conda install -c conda-forge` on Windows, with `ipywidgets`, `notebook` or any other package having `m2w64-gcc-libs` as a dependency.

For example,  `conda install -c conda-forge ipywidgets`:
ipywidgets -> widgetsnbextension -> notebook -> terminado -> pywinpty -> m2w64-gcc-libs

`m2w64-gcc-libs` and its deps are only available from the [`msys2`](https://anaconda.org/msys2/) channel on [anaconda.org](https://anaconda.org).
Its dependencies are namely:
- m2w64-gcc-libgfortran
- m2w64-gcc-libs-core
- m2w64-gmp
- m2w64-libwinpthread-git
- msys2-conda-epoch

Proposition
---
Also publish those packages on [`conda-forge`](https://anaconda.org/conda-forge/) to ease installation process.

I'm opening this issue here because I can't locate public repos (projects or feedstocks) related to those libs.
Maybe some of you have contacts with the Anaconda team.

**Comment by saaketp** [comment]
m2w64-gcc-libs seems to be available now from conda-forge
I am able to install both ipywidgets and notebook from conda-forge only.

**Comment by kevin-bates** [comment]
Thank you for this update @saaketp - it's much appreciated.  Closing.
