### ISSUE TITLE
Require a file name in the "Save As" dialog

### ISSUE THREAD

**Issue by pavpanchekha** [jupyter/notebook#5732]
I just had an issue today where I clicked through the "Save As" dialog without typing in a file name. Jupyter helpfully takes that empty string, attaches its extension, and so creates the file `.ipynb` in the named directory. That file is hidden, so you have a hell of a time finding it!

I believe the fix has to happen here:
https://github.com/jupyter/notebook/blob/7978c0f763391a3336cc22273c684dcb00860008/notebook/static/notebook/js/notebook.js#L2920

Another option is to add the "required" attribute to the input element used in that dialog, so the browser takes care of it for you, here:
https://github.com/jupyter/notebook/blob/7978c0f763391a3336cc22273c684dcb00860008/notebook/static/notebook/js/notebook.js#L2906

**Comment by kevin-bates** [comment]
This is a great catch @pavpanchekha!  I just confirmed your finding and this feels like something we should include in the (very near) patch release.

Did you want to contribute the fix?  I'm not a frontend dev so can't really help, although a "required" attribute strikes me as the right approach (provided it's "stable" amongst the various browsers).  At any rate, I'd be happy to verify the fix at that time while someone else can review the code change.

**Comment by kevin-bates** [comment]
Fantastic - thank you!  What machine/OS/browser are you using or have tried against?

**Comment by pavpanchekha** [comment]
I'm on macOS 10.15.6 (Catalina) using Safari. Thanks for testing it and referring to another maintainer!
