### ISSUE TITLE
docs: "Notebook front-end client" links all go to the same thing

### ISSUE THREAD

**Issue by mriedem** [jupyter/notebook#5740]
All of the links here go to the same reference:

https://jupyter-notebook.readthedocs.io/en/latest/config_overview.html#notebook-front-end-client

So instead of `Example: Changing the notebook’s default indentation setting` going here [1] and `Persisting configuration settings` going here [2] they all go to the same link which is just [3] because they are all using the same reference:

```
- :ref:`How front-end configuration works <frontend_config>`
    * :ref:`Example: Changing the notebook's default indentation setting
      <frontend_config>`
    * :ref:`Example: Restoring the notebook's default indentation setting
      <frontend_config>`
- :ref:`Persisting configuration settings <frontend_config>`
```

It's not a big deal but I expected links to sub-sections to actually go to those sub-sections in the other doc.

[1] https://jupyter-notebook.readthedocs.io/en/latest/frontend_config.html#example-changing-the-notebook-s-default-indentation
[2] https://jupyter-notebook.readthedocs.io/en/latest/frontend_config.html#persisting-configuration-settings
[3] https://jupyter-notebook.readthedocs.io/en/latest/frontend_config.html#frontend-config

**Comment by kevin-bates** [comment]
Thank you @mriedem - this looks like an issue indeed.  Based on your posting of #5741, can I assume that a PR is on its way for this (and that)?  :smile:

**Comment by mriedem** [comment]
> can I assume that a PR is on its way for this

Yup, #5742 was my solution to _this_ issue. I'm not entirely sure how you'd want to address #5741.

**Comment by kevin-bates** [comment]
Thank you.  I commented on #5741 relative to that - your help is much appreciated.
