### ISSUE TITLE
Instructions on building the docs don't mention that `notebook` needs to be installed as well

### ISSUE THREAD

**Issue by mriedem** [jupyter/notebook#5741]
I was following the instructions on building the documentation [1] using the pip install version (not conda). I was doing it within a virtualenv called `.docs`. I pip installed `docs/doc-requirements.txt` per the instructions and then ran `make html` which failed because `notebook` isn't installed:

```console
(.docs) osboxes@osboxes:~/jupyter/notebook/docs$ make html
python3 autogen_config.py
Traceback (most recent call last):
  File "autogen_config.py", line 4, in <module>
    from notebook.notebookapp import NotebookApp
ModuleNotFoundError: No module named 'notebook'
Makefile:62: recipe for target 'source/config.rst' failed
make: *** [source/config.rst] Error 1
```

The fix is simple, I just did `pip install .` from the root of the notebook project directory and that got me past that issue, but assume it should be called out in the docs as one of the steps in building the documentation.

[1] https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.rst#building-the-documentation

**Comment by mriedem** [comment]
I also hit this:

```
Notebook error:
PandocMissing in examples/Notebook/Connecting with the Qt Console.ipynb:
Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
Makefile:57: recipe for target 'html' failed
make: *** [html] Error 2
```

It looks like pandoc is missing from the docs requirements?

**Comment by mriedem** [comment]
> It looks like pandoc is missing from the docs requirements?

Nevermind, looks like you need to install the binary from the distro (`sudo apt install -y pandoc` for me on ubuntu 18.04).

**Comment by mriedem** [comment]
I see that the building the docs section mentions:

>To build the documentation you'll need Sphinx, pandoc and a few other packages.

I just assumed I had it (I already had Sphinx).

**Comment by kevin-bates** [comment]
Hi Matt, My guess is that it was assumed notebook would be installed into the docs build env already.  Seems like a simple note of what you did would be sufficient.  I hesitate to add notebook to the doc requirements file as that seems a little heavy, but one could probably make that argument.
