### ISSUE TITLE
Command line / configuration option to disable shutdown confirmation

### ISSUE THREAD

**Issue by ankane** [jupyter/notebook#5745]
Hi, thanks for this project! It'd be nice if there was the option to disable shutdown confirmation, like:

```sh
jupyter notebook --no-confirm-exit
```

I thought this might be possible with the `-y` option ("Answer yes to any questions instead of prompting"), but it appears not to answer the shutdown prompt.

```sh
jupyter notebook -y
```

**Comment by FlorinAndrei** [comment]
Does anyone know the answer? I need this exact same feature.

**Comment by kevin-bates** [comment]
Thanks for the update @FlorinAndrei - this was resolved via https://github.com/jupyter/notebook/pull/5941 in 6.3.0.

**Comment by ankane** [comment]
Awesome, thanks @afshin, @kevin-bates, and @FlorinAndrei!
