### ISSUE TITLE
jupyter not importing any module (required field "type_ignores" missing from Module)

### ISSUE THREAD

**Issue by kirancrazy99** [jupyter/notebook#5746]
Updated my Anaconda environment to 2020.07, since then notebook not functioning properly, whatever the module trying to import hitting below error. (Using Python :3.8.3)
**TypeError                                 Traceback (most recent call last)
~\anaconda3\lib\codeop.py in __call__(self, source, filename, symbol)
    134 
    135     def __call__(self, source, filename, symbol):
--> 136         codeob = compile(source, filename, symbol, self.flags, 1)
    137         for feature in _features:
    138             if codeob.co_flags & feature.compiler_flag:

TypeError: required field "type_ignores" missing from Module**

**Comment by kevin-bates** [comment]
Please update your [IPython package to at least 7.3.0](https://github.com/ipython/ipython/issues/11590).
