### ISSUE TITLE
Blank Figure output

### ISSUE THREAD

**Issue by SAMANDOLL** [jupyter/notebook#5750]
Hi i am using seaborn for box plant, in the browser graph showing but plt.savefing(") showing blank output in all formats. How i can solve this error???

**Comment by designerguy13-photonics** [comment]
Not sure what exactlly you might be missing but recheck if you are passing everything into following 

bplot.figure.savefig(plot_file_name,
                    format='jpeg',
                    dpi=100)

Also i see you are using savefing !!

**Comment by SAMANDOLL** [comment]
Thanks solve it.
