### ISSUE TITLE
Upgrade MathJax from v2 to v3

### ISSUE THREAD

**Issue by eeopd** [jupyter/notebook#5758]
Currently MathJax 2.7.4 is used, but the latest version is 3.1.2. In v3, a complete rewrite of the project, some nice improvements [were made](https://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html), including much faster rendering and some new packages. However, because MathJax 3.0 is a complete rewrite it includes quite a few [incompatible changes](https://docs.mathjax.org/en/latest/upgrading/v2.html), so this upgrade would require quite a bit of work to get working, and in the end result in some differing behaviours/broken TeX blocks, and also cause several extensions to break.

Would you be open to a patch? Or would working on integrating KaTeX seem preferable (#3094,  #4066)?

**Comment by jtpio** [comment]
FYI the next version of the Jupyter Notebook (Notebook 7) is based on JupyterLab 4 and will use MathJax 3.

For reference this was implemented in https://github.com/jupyter/notebook/pull/6777 and https://github.com/jupyterlab/jupyterlab/pull/13877.

You can already try the beta with: `pip install --pre notebook`.

**Comment by jtpio** [comment]
Closing as this has now been implemented in Notebook 7.

**Comment by jtpio** [comment]
> i am wondering if we can use jupyter whitout Mathjax , my Browser crash all time when Mathjax load page whit safe.js ???

If you are using JupyterLab or Notebook 7, you could look into switching to KaTeX via an extension: https://github.com/jupyterlab/jupyter-renderers

**Comment by malouke2020** [comment]
Hi,
I use the folowing version of jupyter notebook
notebook                          6.5.4
notebook_shim                     0.2.3
-and i try different Browser  in Incognito mode  and regular mode
- i have a big data Frame  that i can't split in diffrente sub part 
- when i start processing after clear all notebook and restare from scratch  two things can Hapen;
- 1 crash of google chrome or fireforx  
- 2 i lose the connection to my  jupyter server (all process are in local no ssh no proy .....)
i suspect Mathjax and Safe.js to triger that error beceasu the majorty of time i can see the paths to mathjax or safe.js loading when crash happen.
i can't use jupyterlab for the reason i have to change css  to dispaly dataframe side by side and this it's too simple with 
CSS = """
.output {    
    flex-direction: row;
    flex-flow: row wrap;   
    font-size: 10pt;
}
"""
HTML('<style>{}</style>'.format(CSS))
But with jupyterlab i found that hard to control all output dispaly ...
can i ask you advice .
Thanks
