### ISSUE TITLE
Download github pc command

### ISSUE THREAD

**Issue by rafaelgomes123** [jupyter/notebook#5761]
pip install notebook

jupyter notebook

**Comment by kevin-bates** [comment]
Hi @rafaelgomes123 - please clarify what your question or issue is regarding - there is nothing here that indicates a question.  

I would also suggest visiting the [Notebook documentation](https://jupyter-notebook.readthedocs.io/en/latest/?badge=latest#the-jupyter-notebook) prior to opening issues as your question may be answered there.  

I'm going ahead and closing this issue.  If you feel your issue warrants further support, please provide more details and the maintainers will be happy to re-open this issue (or you can do that yourself when leaving your clarifying information).  

Thank you.
