### ISSUE TITLE
How do I disable the restoring of the files/kernels I opened the last time.

### ISSUE THREAD

**Issue by Boltzmachine** [jupyter/notebook#5764]
Every time I start my Jupiter notebook/lab, it will automatically start the files I opened the last time. I want to disable it. Is there any way to do it?

**Comment by kevin-bates** [comment]
Hi @Boltzmachine - I believe this behavior applies only to [Jupyter Lab](https://github.com/jupyterlab/jupyterlab).  Could you please open this issue (or find a similar issue) in that repository?  The notebook frontend doesn't open additional tabs for each of the previously running kernels upon restarts.

**Comment by Boltzmachine** [comment]
Oh, my fault. Sorry for wasting your time.

**Comment by kevin-bates** [comment]
No worries at all @Boltzmachine - thanks for using Jupyter and participating in the community.
