### ISSUE TITLE
Korean character broken when Jupyter accessed from iPad(Safari, Chrome) 

### ISSUE THREAD

**Issue by yhur** [jupyter/notebook#5766]
Dear,

I appreciate you guys' work on the Jupyter Notebook development. 

Recently, I am starting use the iPad for my daily work and tried to access the Jupyter Notebook from my iPad,
and found when I typed the Korean character in, then all the consonants and vowels are repeated till the whole character formed up. I guess somehow the automata of Jupyter is echoing out them.

Can anyone help on this?

**Comment by yhur** [comment]
I’m revising the issue.

This problem happens on the colab.research.google.com.

Thanks.

**Comment by kevin-bates** [comment]
Thank you for the update, it's much appreciated. 

We'll go ahead close this issue. We can circle back and reopen it, should that be necessary.

**Comment by yhur** [comment]
Thanks Kevin.

And I checked the colab github and found the same problem reported.
Just for the record, I'm linking that issue here.

    https://github.com/googlecolab/colabtools/issues/1050
