### ISSUE TITLE
Docs: Update the "Notebook Basics" example

### ISSUE THREAD

**Issue by tritemio** [jupyter/notebook#578]
I've found that the best explanation on using the notebooks UI for first time users is the **Notebook Basics** example, which contains crucial information (and screenshots!) of Dashboard, notebook, edit vs command mode, toolbar etc:

https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb

This info is very important and not found anywhere else in the notebook documentation.

The first section (Running the Notebook Server, which discuss using non-default ports) is, however, distracting. User can use some publically hosted notebooks or may launch the notebook via the Anaconda launcher. I would separate how to launch the server from how to use the notebook interface.

So I propose to remove the first section and start with the section: The Notebook dashboard.

The paragraphs on launching the server can be moved to the main sphinx documentation, maybe expanding this section:

https://jupyter.readthedocs.org/en/latest/running.html#running-the-notebook

Also this important notebook should be highlighted better in the main sphinx docs.

**Comment by takluyver** [comment]
This appears to have been done at some point; the example notebook now starts with the section about the dashboard.
