### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by Cheteni006** [jupyter/notebook#5782]
i am confused with this one " how can i make my notebook visible based on the URL and how can i change the country to something other than South Africa?
![image](https://user-images.githubusercontent.com/71906476/94664951-d6e83d80-030b-11eb-8ce4-a7526d7be301.png)

**Comment by kevin-bates** [comment]
Hi @Cheteni006 - This is not an issue related to notebook. I suggest you first look at the data set (just looking at `df_raw` should be sufficient) and get familiar with the columns, then check out some tutorials on using pandas dataframes.

**Comment by Cheteni006** [comment]
Thanks for the response
Regards
Cheteni006
