### ISSUE TITLE
Prevent inconsistent states in `jupyter notebook list`

### ISSUE THREAD

**Issue by mueslo** [jupyter/notebook#5788]
`jupyter notebook list` is a command that is used to tell which jupyter notebooks are currently running. The same interface (`notebookapp.list_running_servers()`) is used by at least one important tool `nbopen`, to enable click-to-launch Jupyter notebooks, which greatly increases ease-of-use and user-friendliness and hence can drive adoption (and really should be included out of the box!). 

However, the method used is not particularly resilient. When starting, it simply writes this to a json state file in the runtime directory, and it seems like updates/removes this entry when cleanly shutting down. However, there may be *many* reasons why this can leave the state file and command in an inconsistent state. The notebook may have:

* been killed accidentally or on purpose by the user
* been killed by the OS, e.g. due to running out of RAM
* been killed due to an unclean shutdown
* crashed due to a programming error
* etc.

All of this results in `jupyter notebook list` still showing a running notebook.

In turn, this prevents tools like `nbopen` from properly working, as they think a notebook is still running and redirect the user to the old notebook's URL.

Proposed fix: write the root PID of the launched notebook into the state file. When reading the state file (in `notebookapp.list_running_servers()`) is run, first check if the process is still running, and if not, clean up the state file.

Edit: it seems like the PID *is* contained in the state file, just that it is never checked whether it's still running. However, on second thought, this is also not quite enough, it should also check that the PID actually corresponds to a notebook server with the same parameters as in the `nbserver-#.json` state file.

Edit 2: checking the code (https://github.com/jupyter/notebook/blob/498b0bcefbc5e5c3e64c2517cf5ef1ef3ab9c2b0/notebook/notebookapp.py#L2299-L2306) it seems like this logic is present, but it obviously does not seem to work, at least on Windows (notebook 6.0.3). Maybe `check_pid` is to blame.

**Comment by mueslo** [comment]
_check_pid_win32 seems to be the culprit

**Comment by rsokl** [comment]
@mueslo  I am hitting this issue as well. I.e. `notebook list` reports a stale server that doesn't actually exist. 

By what process can I "flush" this list - I can't seem to find the `nbserver-#.json` file you mention

**Comment by mueslo** [comment]
What version of jupyter are you running. Where did you look for the file?

**Comment by rsokl** [comment]
I am running version `6.1.5`. 

I looked in `~/.jupyter` and in the various folders of `~/.ipython` (old SO posts suggested that the json files would be under the latter). I am running the notebook server from an anaconda environment, so perhaps the json files are stored somewhere in that directory structure.

`jupyter notebook stop` raises a `ConnectionRefusedError: [Errno 111]`

**Comment by mueslo** [comment]
Try ~/.local/share/jupyter/runtime

Did you have jupyter running for a very long time by any chance?

**Comment by rsokl** [comment]
(First of all, thank you very much for your generous help! I really appreciate it)

Ah yes, there is a `nbserver-#.json` lecated in `~/.local/share/jupyter/runtime` (and many `nbserver-#-open.html`). I am assuming that  it corresponds to the "zombie".

Is there an obvious correspondence that I am missing between

```
http://localhost:8888/?token=676ef9027441c7136c3aa1bf739135e131f636e784f7a316 :: /home/rsokl
```

and 

```
nbserver-2846.json
```

Regardless, is it safe for me to simply delete this json?

>Did you have jupyter running for a very long time by any chance?

It is possible.. I often start a jupyter server on this machine remotely and it is possible for me to lose the ssh session and then forget about the running server. That being said, I also had to recently kill a kernel that was about to fill up my memory on this remote machine, and I suspect that I did so in a way that left this remnant behind.

**Comment by kevin-bates** [comment]
>Is there an obvious correspondence that I am missing between
    `http://localhost:8888/?token=676ef9027441c7136c3aa1bf739135e131f636e784f7a316 :: /home/rsokl`
and
    `nbserver-2846.json`

No - nothing obvious.  The first string is composed from the file's contents in the second string via `jupyter notebook list` (as you have found).  The numeric value in the json filename is the process id (pid) of the notebook server that just started.  You could infer that filename based on the `nbserver-pid-open.html` filename listed on the console just prior to the other URLs...
```
    To access the notebook, open this file in a browser:
        file:///Users/kbates/Library/Jupyter/runtime/nbserver-30667-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=d920c3a420abe1514cd44ff8c4943443bd699fef8b2856d3
     or http://127.0.0.1:8888/?token=d920c3a420abe1514cd44ff8c4943443bd699fef8b2856d3
```
but that's about it.

>Regardless, is it safe for me to simply delete this json?

Both 'jupyter notebook list` and `jupyter notebook stop` leverage the contents of this file. If you know that the pid is no longer associated with a notebook process, then, by all means, it would be safe (and advised) to delete the file.  If, on the other hand, you know the associated notebook server is running, then it's up to you (and your usage of the 'list' and 'stop' commands) as to whether you should delete the file since its premature deletion will prevent those commands from producing expected results.

The file will be automatically deleted on "controlled" stops (either via ctrl-C or 'stop').

**Comment by rsokl** [comment]
Thank you very much for taking the time to help me out and for the informative response.
