### ISSUE TITLE
Starting with 6.1, I can't start terminals directly with a GET request

### ISSUE THREAD

**Issue by santiagobasulto** [jupyter/notebook#5790]
Hello. I am teaching a beginners Operating Systems class (explaining the very basics of Linux to young students). Up to version `6.0.3`, I was able to direct my students to `https://myserver.com:8888/terminals/1` and that'd immediately start a terminal for them.

Starting with `6.1` I can't do that, now it throws a 404. Did the API change and now it's necessary to somehow "create" the terminal before issuing the GET request? Is there any way to circumvent this?

Thanks!

**Comment by kevin-bates** [comment]
Hi @santiagobasulto - this appears to have occurred with #4180.  As you can see, there's some sentiment that this was a bug but, if I'm understanding the conversation, @rgbkrk suggested a named path that would possibly restore the "hidden" functionality.

Kyle - are you planning on contributing support for `GET .../terminals/new`?

Santiago - in the meantime, your students might be best off staying on `6.0.3`.

**Comment by santiagobasulto** [comment]
Oh wow! such a tiny piece of code was the source of all my troubles 😂. Thanks for your response @kevin-bates, I'll stick to 6.0.3 for now, but I think this is actually a great feature, specially to open several shells at the same time.

**Comment by cailiang9** [comment]
This feature is quite useful. Many people use it to indicate functions of some metric monitors, such as .../terminals/htop .../terminals/username .../terminals/nvidia-smi.  Then start the command in the corresponding terminal page.
@kevin-bates @rgbkrk Any plans to re-open this useful feature？

**Comment by kevin-bates** [comment]
Thanks for the comments @cailiang9 and @santiagobasulto.  If possible, it would be helpful if you could take a look at #5813 and/or take it for a spin.  It does introduce a slight change in behavior, but I think that's probably the compromise we're looking at.

**Comment by rgbkrk** [comment]
> are you planning on contributing support for `GET .../terminals/new`?

It ended up being less of a priority, so it's far down my backlog. If someone runs with it I don't mind. 😄

**Comment by rgbkrk** [comment]
Oh whoops, I see you've opened the PR since I last had this tab open. Thank you @kevin-bates, I'll review it.

**Comment by santiagobasulto** [comment]
Thanks folks!
