### ISSUE TITLE
RFE: Add support for JSON logging format

### ISSUE THREAD

**Issue by mriedem** [jupyter/notebook#5798]
We're able to configure `Application.log_datefmt` and `Application.log_format` options but with something like this configuration:

```yaml
c.Application.log_datefmt = '%Y-%m-%dT%H:%M:%S'
c.Application.log_format = '%(levelname)s %(asctime)s.%(msecs).03dZ [%(name)s %(module)s:%(lineno)d] %(message)s'
```

You get logs like this:

```
WARNING 2020-10-07T16:01:41.630Z [SingleUserNotebookApp filemanager:266] Invalid ctime 1601063354730.0 for /home/jovyan/test2.txt
INFO 2020-10-07T16:01:41.632Z [SingleUserNotebookApp log:174] 200 GET /user/5e18a4193f4a3f001127f809/api/contents/?type=directory&_=1602086500971 (5e18a4193f4a3f001127f809@10.185.195.144) 387.15ms
INFO 2020-10-07T16:01:45.283Z [SingleUserNotebookApp log:174] 200 GET /user/5cc87910c20b7200111d7315/metrics (5cc87910c20b7200111d7315@10.185.195.144) 3.22ms
```

We're using LogDNA and with that config we can at least filter logs by level but what we'd like to be able to do is have json log formatting so that individual fields can be used in query filters to the logging system (I think LogDNA is or at least used to use ElasticSearch under the covers).

If this is already possible with the notebook app config or tornado I'm not sure how to do it easily.

I see there is a log formatter defined here:

https://github.com/jupyter/notebook/blob/498b0bcefbc5e5c3e64c2517cf5ef1ef3ab9c2b0/notebook/notebookapp.py#L705

But I'm not sure where that `_log_formatter_cls` attribute gets used, I don't see it in jupyter-core or tornado.

https://www.tornadoweb.org/en/stable/log.html doesn't mention anything about being able to define a different JSON log format. I see some stuff in https://dchua.com/2016/07/19/logging-tornado-logs-to-graylog/ but I was wondering how easy it would be to just add an option to the notebook app to use json logging and then use a formatter / handler from something like https://pypi.org/project/json-logging/ or https://github.com/madzak/python-json-logger.

**Comment by kevin-bates** [comment]
> But I'm not sure where that _log_formatter_cls attribute gets used, I don't see it in jupyter-core or tornado.

The traitlets package, and its hierarchy of classes, is where you'll likely wind up in this journey.  Here's where the logging is configured for a given `Application` class - from which most all Jupyter-related applications are derived: https://github.com/ipython/traitlets/blob/master/traitlets/config/application.py#L237

**Comment by mriedem** [comment]
Ah OK and it's a specific interface so to add JSON logging to the notebook app we'd need to do something like extend LogFormatter (like JupyterHub does [here](https://github.com/jupyterhub/jupyterhub/blob/2ff7d05b15e679e25b2b525de86a401ef763ebe7/jupyterhub/log.py#L60) and then handle the JSON formatting in there, maybe using one of the aforementioned packages for JSON logging.

**Comment by kevin-bates** [comment]
Thanks Matt.  This is something we'd definitely be interested in moving forward with in [Jupyter Server](https://github.com/jupyter/jupyter_server) as well.
