### ISSUE TITLE
How do I select multiple cells with mouse?

### ISSUE THREAD

**Issue by eulerreich** [jupyter/notebook#580]
I know I can do this with shift+j/k but is there a way to do it with mouse? I tried the intuitive way of clicking the beginning cell, and holding shift, clicking the end cell, but that doesn't work.

**Comment by jdfreder** [comment]
You don't :worried:

Related to #565

We definitely should add this capability.  However, I'm unsure of the level of effort involved, optimistically marking as 4.1, but should be non-blocking.

**Comment by captainsafia** [comment]
Hm. I will take a look at this.

**Comment by jdfreder** [comment]
@ellisonbg

**Comment by ellisonbg** [comment]
@jdfreder is looking at a slightly different way of managing
multiple-selection that will separate out the "selected" cell abstraction
(which is really like a cursor) from the "marking" of cells. As part of
that, there will be a new keyboard shortcut for marking a cell - in
addition to the existing cell selection extending shortcuts. Let's wait to
figure that stuff out before we dive into mouse based multiple cell
selection.


On Mon, Oct 12, 2015 at 12:44 PM, Jonathan Frederic <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/580#issuecomment-147457855>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by captainsafia** [comment]
Got it! @jdfreder, is there a PR where you are working on that that I can keep track of the changes in?

**Comment by jdfreder** [comment]
@captainsafia sure!  I just opened the PR and pinged you in it, it's ready for review.

**Comment by dpsanders** [comment]
Any chance that extension of cell selection of multiple cells could be with `Shift` and arrow keys as well as the current `Shift-K` and `Shift-J`?

**Comment by jdfreder** [comment]
@dpsanders https://github.com/jupyter/notebook/pull/568

**Comment by dpsanders** [comment]
Great, thanks ! (and sorry, guess I did a checkout slightly more than a week ago).

**Comment by jdfreder** [comment]
Closed by https://github.com/jupyter/notebook/pull/597
