### ISSUE TITLE
extra_static_paths config ignored

### ISSUE THREAD

**Issue by apemann** [jupyter/notebook#5809]
I've been trying to serve custom JS files on the notebook server (on Linux Mint). This should be possible by providing a path to the custom static files in `jupyter_notebook_config.py` as follows:
`c.NotebookApp.extra_static_paths = ["/home/user/notebook_dir/static"]`

I would then expect any JS (and CSS) files in the provided directory to be served in the 'custom' directory of the notebook server. However only the custom.js is served from `.jupyter/custom`. Looking at old discussions and blog posts, it would appear as though this used to work.

When running `jupyter notebook --debug` I can see the correct config file is loaded and there are no errors. Also using the jupyter-config app and running `jupyter config search extra_static_paths` shows the supplied config has priority. 

Creating and extension is not a great solution for my application for a number of reasons.

**Comment by kevin-bates** [comment]
Hi.  Full disclosure: I know hardly anything about the front-end of things, so please take this with a grain of salt.

Does the comment in this file provide any hints: https://github.com/jupyter/notebook/blob/master/notebook/static/custom/custom.js

To me, it implies that the containers of the custom code are commonly named - `custom.js` and `custom.css`, although I'd agree with the implication that a custom directory should allow for any file in that directory to be available. Are you able to show the references that imply custom files other than `custom.js` and `custom.css` can be used?  Perhaps those references might provide some further hints.

Also, I noticed that besides [`extra_static_paths` there is `static_custom_path`](https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1281-L1303) which might be what you want to use instead.

That said, I may be just causing more grief here, but I hope you might find this useful.

**Comment by apemann** [comment]
Thanks @kevin-bates.
The files may not be served in the custom directory, but they should be taken from the specified directory in the file system to be made available on some corresponding directory on the web server. 
From the docs:

```
NotebookApp.extra_static_paths List
Default: []
Extra paths to search for serving static files.

This allows adding javascript/css to be available from the notebook server machine, or overriding individual files in the IPython
```
I can't find `static_custom_path` in the docs, but it doesn't sound like it would give you the flexibility of adding multiple directories.

**Comment by Zsailer** [comment]
@apemann, this seems to be working for me. 

For example, I have a directory `/path/to/my/custom/stuff` on disk with some JS files, say `test.js`. I can configure the notebook server using the following `jupyter_notebook_config.py`: 
```python
c.NotebookApp.extra_static_paths = [
    "/path/to/my/custom/stuff",
]
```
Now, if I visit `localhost:8888/static/test.js`, I can see my JS file as I'd expect. 

Just a couple of things to note: 
1) Static files are served behind the `/static` endpoint, e.g. `/static/test.js` in my example above.
2) The full path you supply, e.g. `/path/to/my/custom/stuff`, is not included in the URL. 

Are you expecting something different?

**Comment by apemann** [comment]
@Zsailer Thank you for taking a look. You are correct - the error was mine in that I was relying on the Chrome dev tools to inspect served static files, but for some reason they do not appear there. You can access the files by entering the URL manually as you suggested. Looks like I put too much faith in the console - lesson learned.

Thanks again.
