### ISSUE TITLE
Double clicking cell enters edit mode

### ISSUE THREAD

**Issue by eulerreich** [jupyter/notebook#581]
If I double click a cell output, I enter edit mode, with focus in the cell input. This only works the first time. Subsequent double clicks just select the word in the output.

Is this the intended behavior?

I always try to select a word in the output with double clicks. It seems kind of silly to enter edit mode with a double click when you can just reach above a bit and single click.

**Comment by minrk** [comment]
I suspect this is UI for markdown cells, where double-click is meant to enter edit mode, leaking into code cells.

**Comment by YokkaBear** [comment]
After double click, you enter the edit mode. After modification, you can run this cell to make it back to markdown display format again. At least for me, any time of such operation is ok.
