### ISSUE TITLE
Change the docker base image (discussion)

### ISSUE THREAD

**Issue by jakirkham** [jupyter/notebook#582]
Currently, the base image being used is Ubuntu 14.04. However, that makes this image different from other docker images ( https://github.com/jupyter/docker-stacks ) ( https://github.com/jupyter/docker-demo-images/blob/master/Dockerfile ), which are using Debian Jessie as the base image.

I propose that we pick one base image for all of the Docker images. At present, more images are using Debian Jessie so that seems like a reasonable choice. Thoughts?

**Comment by jakirkham** [comment]
attn: @minrk @rgbkrk @parente

**Comment by rgbkrk** [comment]
I prefer debian:jessie. We ended up not switching these over for a few backwards incompatibility decisions, as well as some other encoding issues IIRC. Totally fine by me if we change it moving forward. :+1:

**Comment by minrk** [comment]
+1, though I'm increasingly wondering how much the `jupyter/notebook` base image even makes sense at all.

**Comment by jakirkham** [comment]
Cool, I'll start working on the changes then so we can discuss.

> We ended up not switching these over for a few backwards incompatibility decisions, as well as some other encoding issues IIRC.

Do you recall what the cause backwards incompatibility was? Is it missing functionality issue or just the fact that base image would be different. I think I have seen the encoding issues, but believe I have a way to resolve them.

> though I'm increasingly wondering how much the `jupyter/notebook` base image even makes sense at all.

From my perspective, it is nice because it includes the latest build of the `notebook` codebase. This will be very handling combined with CI ( https://github.com/jupyter/notebook/pull/547 ) to verify that this medium of distribution still works. It also allows for others to base their image off this one and take advantage of the latest changes by using repository links ( https://docs.docker.com/docker-hub/builds/ ). Taking advantage of Docker Hub's ability to build tags ( https://github.com/jupyter/notebook/issues/593 ) will allow proper versions to be built and released from here. Having the latest release of code in a working environment could also be used to provide others a simple working test/development environment.

Finally, as this image becomes more robust and compatible, it only makes sense that it will take the place of the minimal notebook ( https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/Dockerfile ) by eliminating all, or at least most, of its need. This will become the base image and allow for the latest changes to be propagated downstream to other configurations ( https://github.com/jupyter/docker-stacks ). Pinning the version of `notebook` by using tags of this build will also be an option.

**Comment by parente** [comment]
> Finally, as this image becomes more robust and compatible, it only makes sense that it will take the place of the minimal notebook ( https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/Dockerfile ) by eliminating all, or at least most, of its need.

I always assumed the Dockerfile in this repository was there for dev and test purposes, and why it installed from source. On the other hand, I saw docker-stacks/minimal-notebook as a baseline environment for actually using Jupyter Notebook for work, hence the conda environment.

Is it desirable to mix the two or replace one with the other?

**Comment by minrk** [comment]
@parente good point. We need to decide what exactly this Dockerfile is meant to be. To me, it's primarily a source of documentation for a simple install and/or the simplest example deployment. I would specifically *not* use it as a general base image, where I would always want to be using conda, install more packages, etc. This seems to what we are accomplishing with docker-stacks, so I wouldn't do it here. Perhaps this file should be removed entirely, and we ensure we have a sensible minimal base image in jupyter/docker-stacks that we point `jupyter/notebook` to on Docker Hub.

**Comment by parente** [comment]
I agree with putting a stake in the ground one way or the other and making it very clear what each image should be.

My 2 cents: If there's an interest in having a dockerized dev setup that puts all the tools (python, node, etc) in one container image, then I think the Dockerfile in this repo should satisfy that desire. If there's currently no interest in that kind of dev environment, then I agree that this repo should drop the Dockerfile in the interest of keeping all the docker image definitions together over in docker-stacks.

**Comment by jakirkham** [comment]
Perhaps I have gotten the wrong idea (to some extent) about this image. Given that it is called `jupyter/notebook` on Docker Hub, I figured that this was an authoritative image in some regards. Also seeing optimizations of this sort ( https://github.com/jupyter/notebook/pull/528 ) made me think we really did want this to be a performant image. I apologize if I have overstepped here.

If we are leaning towards removing this from here, I would like to suggest that it gets moved over to ( https://github.com/jupyter/docker-stacks ) so that we can have some time to see what can be saved and coalesced into a singular form with `jupyter/minimal-notebook`. It would be unfortunate to see the work that went into this go to waste.

**Comment by parente** [comment]
@jakirkham Certainly don't want to see any improvements you or others have made go to waste. Not at all!

At the moment, I'm just looking for consensus on:

1. Should jupyter/notebook have its own Dockerfile? 
2. If so, what's its purpose in comparison with jupyter/docker-stacks/minimal-notebook?
3. If not, what is jupyter/docker-stacks/minimal-notebook lacking that should be ported from here?

@minrk , @rgbkrk can we decide it here? Take it to the google group?

**Comment by rgbkrk** [comment]
We should take this one to the google group.

Where I stand now, as a user of the notebook in containers, I don't rely on the jupyter/notebook image anymore. When tmpnb always had latest master, continuously, I used it then. Nowadays I use one cacheable image which uses assets from a CDN. That's reliant on the minimal-notebook as well.

**Comment by minrk** [comment]
@jakirkham I definitely don't want to waste the work - it's precisely the fact that you are doing helpful work that makes me think that perhaps this repo isn't the right place for the Dockerfile.

**Comment by jakirkham** [comment]
Ok, please let me know what you decide and I will try to help out where I can.

**Comment by minrk** [comment]
Will do, thanks for all your help already, @jakirkham!

**Comment by parente** [comment]
Posted here for discussion and raised the issue up a bit too: https://groups.google.com/forum/#!topic/jupyter/tfVaVCQaNXM

**Comment by jakirkham** [comment]
There is no longer a Docker image here so there is no longer a need for this discussion. 😄
