### ISSUE TITLE
Jupyter Lab and Notebook table in markdown should be `display: inline-block`, instead of centered

### ISSUE THREAD

**Issue by jph00** [jupyter/notebook#5857]
Currently, tables that are output in jupyter lab and notebook are left aligned, but markdown tables are centered.

Centered tables are very hard to read, especially on large displays, because they're a long way away from the rest of the text.

I'm currently working around this by adding CSS `display: inline-block` locally. I think it would be helpful to do something similar by default in jupyterlab. It would be nice to do this in classic notebook too.

cc @willingc @choldgraf

**Comment by choldgraf** [comment]
Agree it is a bit weird to have different behavior for markdown tables that are output vs. code cell tables that are output.

It looks like the CSS on the notebook UI is here:

https://github.com/jupyter/notebook/blob/9de5042e1058dc8aef7632f313e3e86c33390d31/notebook/static/notebook/less/renderedhtml.less#L77

I think you might get more engagement on the [JupyterLab repository](https://github.com/jupyterlab/jupyterlab). My understanding is that this notebook repo [is not heavily watched or maintained](https://github.com/jupyter/notebook#notice).

**Comment by jph00** [comment]
OK will close here and re-open there.
