### ISSUE TITLE
unit tests for JavaScript notebook extensions

### ISSUE THREAD

**Issue by quartox** [jupyter/notebook#586]
I am trying to write unit tests for a JavaScript notebook extension and was wondering if there is any way to do this through the jupyter notebook server. My favorite JavaScript unit testing runners/frameworks (karma and jasmine) host their own server which does not appear to work with a notebook extension. Can I host a jupyter notebook server from one of these test runners or is there a better way to do this?

**Comment by blink1073** [comment]
Hi @quartox, we are testing `jupyter-js-services` using Karma, launching a separate notebook server with cross-origin enabled:  https://github.com/jupyter/jupyter-js-services/blob/master/test/run_test.py

**Comment by quartox** [comment]
Thanks, that is exactly what I was looking for. 

I don't know if this is the appropriate place to ask questions but I am getting an error trying to run the jupyter-js-services tests (using the source build, running 'npm test' gives a 'WeakMap is not defined' error, presumably because something on my system isn't using ES6). Can you direct me to the right place to ask these kinds of questions?

**Comment by willingc** [comment]
Hi @quartox, Happy that @blink1073 answered your initial question. :penguin: 

Thanks for asking about where to ask questions. That's something we're in the process of documenting :book: across all the subprojects. 

Usage questions and questions that span multiple projects are probably best asked at jupyter@googlegroups.com. If you are not yet subscribed to that Google Group, you may find that helpful.

If the question is isolated to errors in a specific project (for example, jupyter-js-services) where it's possible that it may be an issue or something that needs better documentation, I suggest opening an issue in the particular project's repo (in this case, jupyter-js-services).

I hope that helps :smile:

**Comment by blink1073** [comment]
Hi @quartox, can you try running `npm run build` and then `npm test`?

**Comment by quartox** [comment]
Hey @blink1073 , `npm run clean` and `npm run build` did not fix the problem, but I figured out that it was my version of nodejs (0.10) which did not support ES6. I updated to nodejs 0.12 and it works now.

**Comment by blink1073** [comment]
Thanks for the feedback @quartox, see https://github.com/jupyter/jupyter-js-services/pull/41.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Glad @quartox was able to figure the issue at hand (an old node.js)

Thanks everyone and happy hacking! :bowtie:
