### ISSUE TITLE
NLTK - ImportError: DLL load failed while importing _regex: Not enough memory resources are available to process this command

### ISSUE THREAD

**Issue by karthikeyankc** [jupyter/notebook#5865]
In my jupyter notebook, `import nltk` errors out with the following traceback. However, it works if I use it outside the notebook environment.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-453-1d2184025e54> in <module>
----> 1 import nltk

d:\projects\casual\venv\lib\site-packages\nltk\__init__.py in <module>
    131 from nltk.grammar import *
    132 from nltk.probability import *
--> 133 from nltk.text import *
    134 from nltk.tree import *
    135 from nltk.util import *

d:\projects\casual\venv\lib\site-packages\nltk\text.py in <module>
     28 from nltk.metrics import f_measure, BigramAssocMeasures
     29 from nltk.collocations import BigramCollocationFinder
---> 30 from nltk.tokenize import sent_tokenize
     31 
     32 ConcordanceLine = namedtuple(

d:\projects\casual\venv\lib\site-packages\nltk\tokenize\__init__.py in <module>
     64 
     65 from nltk.data import load
---> 66 from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
     67 from nltk.tokenize.mwe import MWETokenizer
     68 from nltk.tokenize.destructive import NLTKWordTokenizer

d:\projects\casual\venv\lib\site-packages\nltk\tokenize\casual.py in <module>
     36 ######################################################################
     37 
---> 38 import regex  # https://github.com/nltk/nltk/issues/2409
     39 import html
     40 

d:\projects\casual\venv\lib\site-packages\regex\__init__.py in <module>
----> 1 from .regex import *
      2 from . import regex
      3 __all__ = regex.__all__

d:\projects\casual\venv\lib\site-packages\regex\regex.py in <module>
    417 # Internals.
    418 
--> 419 import regex._regex_core as _regex_core
    420 import regex._regex as _regex
    421 from threading import RLock as _RLock

d:\projects\casual\venv\lib\site-packages\regex\_regex_core.py in <module>
     19 from collections import defaultdict
     20 
---> 21 import regex._regex as _regex
     22 
     23 __all__ = ["A", "ASCII", "B", "BESTMATCH", "D", "DEBUG", "E", "ENHANCEMATCH",

ImportError: DLL load failed while importing _regex: Not enough memory resources are available to process this command.
```

* Windows 10: 1909 64-bit
* Python version: 3.8.2 (32-bit)
* Installed memory: 8 GB
* Free memory: ~ 4 GB
* jupyter core     : 4.6.3
* jupyter-notebook : 6.1.4
* qtconsole        : not installed
* ipython          : 7.18.1
* ipykernel        : 5.3.4
* jupyter client   : 6.1.7
* jupyter lab      : 2.2.9
* nbconvert        : 6.0.7
* ipywidgets       : not installed
* nbformat         : 5.0.8
* traitlets        : 5.0.5

**Comment by kevin-bates** [comment]
This issue likely belongs in [ipython](https://github.com/ipython/ipython) or [ipykernel](https://github.com/ipython/ipykernel) since it's occurring from the notebook kernel process.

> However, it works if I use it outside the notebook environment.

Have you tried reproducing this issue from the IPython REPL directly (e.g., `$ ipython -h`)?  That's usually a good litmus test for kernel-related issues like this.  Be sure to invoke the REPL in the same env in which you're running the notebook server.

**Comment by karthikeyankc** [comment]
> Have you tried reproducing this issue from the IPython REPL directly (e.g., `$ ipython -h`)? That's usually a good litmus test for kernel-related issues like this. Be sure to invoke the REPL in the same env in which you're running the notebook server.

It does work here though. Imported `nltk` in the same environment from IPython.

**Comment by karthikeyankc** [comment]
I recreated the environment and ran the same notebook. It's working now.
