### ISSUE TITLE
jupyter_datatables error

### ISSUE THREAD

**Issue by xzt1995** [jupyter/notebook#5866]
i can not use my notebook to read the hive tables after i  imoport datatables_Mode , somestime it work , but i can not find how to fix the problem . 
![企业微信截图_7a518d74-57c8-4a8e-a86b-f7947bf1e5af](https://user-images.githubusercontent.com/49546812/99207553-34234a00-27f9-11eb-8400-f783f32d226f.png)
![企业微信截图_0d6ae909-08b9-4ec8-9d92-168769fc3db0](https://user-images.githubusercontent.com/49546812/99207573-3dacb200-27f9-11eb-8d69-736609d4d0b2.png)

**Comment by kevin-bates** [comment]
Hi @xzt1995 - This is not a notebook issue and should be pursued via the [`jupyter-datatables`](https://github.com/CermakM/jupyter-datatables) and/or [`jupyter-require`](https://github.com/CermakM/jupyter-require) repositories.
