### ISSUE TITLE
Unable to launch Jupyter notebook from Anaconda Navigator but notebook is opening from command prompt

### ISSUE THREAD

**Issue by Sibasish** [jupyter/notebook#5873]
I have the lat4est version of Anaconda, Python v3.8 installed on my system running on Windows 10 Pro. I have not installed Anaconda in the default drive but set the path for Python, conda to the installed drive. But in spite of doing everything right as it seems, the Jupyter notebook is not opening when launched from the Anaconda Navigator but opens fine when I type the command from the Windows command prompt. None of the applications displayed in the Anaconda Navigator open and remain stuck as seen in the screenshot attached. But these applications do open when executed independently from the Windows Start menu.
 Hope you understand the issue and respond to what may be the issue that makes the Navigator work improperly. I have already reinstalled many times but the issue persists.

![Screenshot (549)](https://user-images.githubusercontent.com/8840620/99533404-dbf07180-29cb-11eb-88d1-be6fb570345d.png)

**Comment by kevin-bates** [comment]
Hi @Sibasish - there is nothing here for us to help you with as we don't maintain Anaconda Navigator.  If there were some form of log messages, we might be able to help.  Since you find that notebook launches properly from the command line, I believe your only recourse is to take this issue up with the Navigator folks.

**Comment by Sibasish** [comment]
Please let me know how do I take up the issue with Navigator people. Any ideas please?

**Comment by kevin-bates** [comment]
I just googled for 'anaconda navigator support jupyter' - expecting to get to some support forum, but the second hit (the first was our docs suggesting you try from the command line) was this SO post: https://stackoverflow.com/questions/52300930/jupyter-notebook-not-launching-from-anaconda-navigator

I should not have assumed you tried searching for a solution and apologize for the quick redirect.  

Here's a troubleshooting page for navigator: https://docs.anaconda.com/anaconda/navigator/troubleshooting/

One the bottom of that page is a Help & Support link: https://www.anaconda.com/help. There, based on your product, you should find links to mailing lists, etc., but I suspect the first course of action should always be an internet search.
