### ISSUE TITLE
File uploading size limit, when access via nginx proxy

### ISSUE THREAD

**Issue by JacksonHub2** [jupyter/notebook#5879]
Jupyter Notebook version: 6.1.4(runs in docker), 6.0.3(installed from Ubuntu repo)
Running as default port 127.0.0.1:8888
Using Nginx to have it reverse proxy access, on http://127.0.0.1

Issue describe: 
> It seems when I tried to upload file more than 900KB, upload failed with no error info. (and also in NotebookApp running log)

![Screenshot_20201121_202111](https://user-images.githubusercontent.com/71587680/99877174-29244b80-2c37-11eb-8e56-b95dac372d2c.png)

**Note:**
When direct access to 8888 port, file upload all fine, no file size issue at all. (Seems whatever how big file size is )
My concern is whether the settings in nginx might case this issue? Or there's some limit of Jupyter in its conf?

Nginx conf as:
```
map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
upstream jupyter {
      server 127.0.0.1:8888;
  }

server {
	listen 80 default_server;
	listen [::]:80 default_server;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

    location / {
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_pass http://jupyter;
	proxy_redirect off;
	}

 location ~* /(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/? {
	proxy_pass http://jupyter;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	# WebSocket support
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection $connection_upgrade;
	proxy_set_header Origin "";
	}
}
```

**Comment by JacksonHub2** [comment]
Seems no one is looking for this issue, update then)

**Comment by krishnava11** [comment]
Hi @JacksonHub2 , add **client_max_body_size 100M;** in your nginx.conf file under http block, which will allow you to upload till 100MB file

**Comment by JacksonHub2** [comment]
@krishnava11, thanks for your update, it works! 27.07.2021, 14:31, "krishnava11" ***@***.***>:
Hi @JacksonHub2 , add client_max_body_size 100M; in your nginx.conf file under http block, which will allow you to upload till 100MB file

**Comment by kevin-bates** [comment]
@krishnava11 - thank you for the great help here.  Closing.
