### ISSUE TITLE
Learning the notebook

### ISSUE THREAD

**Issue by david12481** [jupyter/notebook#5885]

**Comment by arjun-krishna1** [comment]
If you are learning how to use Jupyter Notebooks, check out this article:
https://medium.com/codingthesmartway-com-blog/getting-started-with-jupyter-notebook-for-python-4e7082bd5d46
Or this video:
https://www.youtube.com/watch?v=CwFq3YDU6_Y&feature=emb_logo|

Best of luck!

**Comment by Zsailer** [comment]
Thanks, @arjun-krishna1!

**Comment by david12481** [comment]
"/user/local/david12481/python@3.8/3.8.6_2/Frameworks/Python.Framework/
/"Jscript";
/"cons" explain =("Your Self");
/"Your Self" = ("Zachary Sailer");
/"What's that supposed to mean"explain;
