### ISSUE TITLE
Jupyter lab/notebook can't import due to "required field "type_ignores" missing from Module"

### ISSUE THREAD

**Issue by OrLichter** [jupyter/notebook#5888]
I recently updated my macOS to Big Sur and launched jupyter lab. I tried to start a new notebook and started it:
```python
import os
```
and got the following error
![image](https://user-images.githubusercontent.com/23155874/100520441-5f694a00-31a6-11eb-9ee1-18b837a005bf.png)

This happens when importing `pandas` or `nupy` as well and happens on Jupyter Notbook. On the other hand on Ipython I succeeded importing these modules successfully. 

This is my pip freeze:
```
appnope==0.1.0
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
backcall==0.2.0
bleach==3.2.1
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
circus==0.17.1
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
idna==2.10
iniconfig==1.1.1
ipykernel==5.3.4
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.2
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-contrib-core==0.3.3
jupyter-core==4.7.0
jupyter-nbextensions-configurator==0.4.1
jupyterlab==2.2.9
jupyterlab-pygments==0.1.2
jupyterlab-server==1.2.0
MarkupSafe==1.1.1
mistune==0.8.4
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nest-asyncio==1.4.2
notebook==6.1.4
numpy==1.19.4
packaging==20.4
pandas==1.1.4
pandocfilters==1.4.3
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
prometheus-client==0.8.0
prompt-toolkit==3.0.8
psutil==5.7.3
ptyprocess==0.6.0
py==1.9.0
pycparser==2.20
Pygments==2.7.2
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.1.2
python-dateutil==2.8.1
pytz==2020.4
PyYAML==5.3.1
pyzmq==20.0.0
qtconsole==5.0.1
QtPy==1.9.0
requests==2.24.0
Send2Trash==1.5.0
six==1.15.0
terminado==0.9.1
testpath==0.4.4
toml==0.10.2
tornado==6.1
traitlets==5.0.5
urllib3==1.25.11
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
```

**Comment by jasongrout** [comment]
This looks like a python issue, perhaps with using the system distribution, which likely was upgraded when you upgraded to Big Sur. If I were you, I'd check to see if `ipython` was running in exactly the same python environment as the notebook kernel. For example, `import sys; print(sys.prefix)` in ipython and in the notebook should give you a hint about where the each python environment is - if they are different, that would explain why they are behaving differently.

**Comment by OrLichter** [comment]
@jasongrout Thanks for the quick answer! Both are using the same version. 
As I couldn't import `sys` in Jupyter I ran `!which python` and I got `/Users/orlichter/.pyenv/versions/3.8.2/bin/python`
From ipython I got `/Users/orlichter/.pyenv/versions/3.8.2`

**Comment by jasongrout** [comment]
`!which python` isn't that helpful - it's just telling you what your shell says in either case.

Another thought: `jupyter kernelspec list` will give you an idea of what kernel is running when you run the notebook.

**Comment by OrLichter** [comment]
Only have one kernel so I guess both ipython and jupter are running on that same one.

**Comment by jasongrout** [comment]
IIRC, `ipython` does not use a kernel, it just runs ipython directly. The question to answer with `jupyter kernelspec list` is to see what the kernel is launching. You can look in that json file to see exactly what binary is being run for the kernel.

**Comment by shivamkumar0611** [comment]
Thanks

**Comment by brifordwylie** [comment]
For anyone else hitting this thread... I had this and issue and another issue (https://github.com/minrk/appnope/issues/12). So I simply deleted my Python virtualenv (I used pyenv) and created a new one... both problems completely disappeared.

**Comment by Zsailer** [comment]
Thanks, @brifordwylie. Closing the issue here. Feel free to reopen if the issue appears again.
