### ISSUE TITLE
Add "guidelines for contributing" to docs

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#590]
Adding a link in the Readme file and the project documentation would be helpful for onboarding new contributors. 

There is currently information in the Contributing.md file and a link to the IPython contributor guidelines. We should make this info a little easier for new contributors to find. :sunny:

**Comment by minrk** [comment]
On the jupyter/jupyter docs, then? Maybe even linked from top-level Jupyter.org as well?

**Comment by willingc** [comment]
@minrk I opened as a placeholder for me to remember. Since this project has pretty high velocity of issues and PRs, I've parked the idea here for now. I will loop back to this after Grace Hopper :+1:

**Comment by captainsafia** [comment]
@willingc I think this issue can be closed?

**Comment by minrk** [comment]
Going through old issues. Looks like this was addressed some time ago on the main jupyter docs.
