### ISSUE TITLE
Drop Travis/Appveyor

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/notebook#5909]
The delays on travis are getting me down on #5907. And appveyor is... appveyor.

It's probably a relatively quick PR to get GitHub Actions spun up and get results faster, and increase platform coverage. Anybody violently against?

**Update**: taking a look here: https://github.com/bollwyvl/notebook/pull/1

**Comment by bollwyvl** [comment]
In exploring this, terminals fail on win/39:

https://github.com/spyder-ide/pywinpty/issues/134

**Comment by bollwyvl** [comment]
Have all of the python tests running on 3.6-3.9 + pypy:

https://github.com/bollwyvl/notebook/actions/runs/417927458

- some skips for pypy
- ignore terminals on py39

**Comment by minrk** [comment]
We've been busy migrating ~everything on JupyterHub to GHA and been super happy with it. Migrating from Travis hasn't been too tough in most cases. Feel free to open that PR!

**Comment by Zsailer** [comment]
Done in #5938.

Looks like terminals on Windows and Python 3.9 are still an issue, but the rest of the tests appear to be running okay :+1:
