### ISSUE TITLE
Broken tooltip in Help menu

### ISSUE THREAD

**Issue by krysros** [jupyter/notebook#591]
Tooltip (title) for second section of Help menu is broken.

![help_title](https://cloud.githubusercontent.com/assets/5299999/10418105/db987194-7051-11e5-8e27-90086f628667.png)

https://github.com/jupyter/notebook/blob/master/notebook/templates/notebook.html#L279

**Comment by willingc** [comment]
Thanks @krysros for reporting the issue, @captainsafia for the timely fix, and @minrk for merging. :cake:  :sunglasses:
