### ISSUE TITLE
apply sentence case in markdown cells

### ISSUE THREAD

**Issue by shuai-zhou** [jupyter/notebook#5914]
This is not a bug or any malfunction. I was just wondering if there is a function that can automatically change texts in the markdown cells to sentence case. Specifically, automatically change the first letter right after a period/question mark/exclamation mark, etc to upper case, also capitalize the sigle letter "i" automatically.

**Comment by kevin-bates** [comment]
I'm not aware of any such function, but that isn't saying a whole lot.  I would not be surprised if there's some kind of notebook extension (nbextension) that does this kind of thing, however.  I recommend posting this question in the [Notebook discourse forum](https://discourse.jupyter.org/c/notebook/31) where you should get better exposure to community resources.
