### ISSUE TITLE
Error "bad file descriptor"

### ISSUE THREAD

**Issue by CarlatBuffalo** [jupyter/notebook#5919]
**Can't launch Jupyter Notebook**
I tried to install tensorflow then the numpy doesn't work. So I reinstalled numpy then jupyter notebook doesn't work at all. Whenever I open or create a new ipynb file the service will be diconnected and such error pops out:  
Bad file descriptor (D:\bld\zeromq_1605919615529\work\src\epoll.cpp:100)  
Then jupyter crashes :(

****Attach a screen shot****
![图片](https://user-images.githubusercontent.com/70539654/103325036-e4e75080-4a17-11eb-8abc-3e233b65fcc3.png)

**To Reproduce**
1. launch the jupyter notebook
2. go to the notebook page (so far everything seems good)
3. open a ipynb file
4. lose connection, error pops out in the powershell prompt shell

**Expected behavior**
Open an ipynb file normally.

**Screenshots**
This is the error from the prompt
![图片](https://user-images.githubusercontent.com/70539654/103258985-7053d980-4965-11eb-8e3a-785f31948687.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - Anaconda Powershell Prompt (mini) 4.9.2
 - Jupyter Notebook 6.1.6

**Additional context**
I uninstalled jupyter and conda and re-install them but it doesn't work. I still get the same error.

**Comment by kevin-bates** [comment]
Hi @CarlatBuffalo - Could you please include a screen-scrape of the entire traceback information - not just the `Bad file descriptor` message?  That should provide some additional details that might help others identify the issue.

**Comment by XIONGWUU** [comment]
I had the same problem.Here is the wrong message.

**Comment by CarlatBuffalo** [comment]
Issue solved today. I tried the following command to reinstall jupyter then it somehow works.
`pip install --upgrade --force-reinstall --no-cache-dir jupyter`

**Comment by NewDongJun** [comment]
I have a smae plroblem Thanks to you, I solved this problem.

**Comment by otumarastudio** [comment]
![image](https://user-images.githubusercontent.com/31704759/109910714-1c120080-7cec-11eb-88cd-13646d2ff043.png)

Same issue, I tried to force reinstall, but result like pic.
