### ISSUE TITLE
JSON.dumps() creates invalid JSON with single quote

### ISSUE THREAD

**Issue by psuhas20** [jupyter/notebook#5926]
**Describe the bug**
JSON.dumps() creates invalid JSON with single quote
the JSON.dumps() function should create valid JSON using double quotes only, however when the function is run with an object as its argument it results in invalid JSON using single quotes. As defined in the ECMA-404 JSON Data Interchange Syntax (http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) JSON should use double quotes not single quotes.

**To Reproduce**
1. Create CSV file (attached)
2. Run the below Python code to get the JSON output
3. And notice that there are Single quotes instead of double quotes.

csvFilePath = open('/Users/suhas/Downloads/InventoryLots.csv','r')
jsonFilePath = open('/Users/suhas/Downloads/InventoryLots.csv.json','w')

fieldnames = ("itemId","shipNode","type","productClass","tagNumber","shipByDate","quantity","changedQuantity","unitOfMeasure","eta")

reader = c.DictReader( csvFilePath, fieldnames)

for row in reader:
    if reader.line_num == 1:
        continue
    j.dump(row, jsonFilePath)
    jsonFilePath.write(',\n')
    print(row)

jsonFilePath.close()

Output is:
{'itemId': 'PH-INLOT-500000001', 'shipNode': 'P71015723', 'type': 'CB', 'productClass': 'ONHAND', 'tagNumber': 'NEW', 'shipByDate': '2020-11-10T08:00:00Z', 'quantity': '2020-11-10T08:00:00Z', 'changedQuantity': '137', 'unitOfMeasure': '137', 'eta': 'EACH', None: ['1900-01-01T08:00:00Z', 'P71015723_CB']}

**Expected behavior**
The resulting JSON should have Double Quotes instead of Single quotes. See - https://bugs.python.org/issue42583

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur Version 11.1 (20c69)
 - Browser: chrome
 - Version: 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
The said issue wasn't exist until November 2020.  This has surfaced probably in December 2020 onwards.

[InventoryLots.csv.zip](https://github.com/jupyter/notebook/files/5772823/InventoryLots.csv.zip)
![image](https://user-images.githubusercontent.com/77027198/103704899-f3c18c00-4f5e-11eb-8df8-cbe53f72189a.png)

**Comment by bollwyvl** [comment]
Seems like it has nothing to do with this repo? Cool bug, at any rate!

**Comment by psuhas20** [comment]
Although the print(row) shows o/p in Single quotes, the actual o/p stored in JSON has double quote.  

I am closing this GH as it requires changes on UI and I am not sure which GH repo would be ideal to do so.
