### ISSUE TITLE
Notebook loaded event not called ('notebook_loaded.Notebook').

### ISSUE THREAD

**Issue by robertstrauss** [jupyter/notebook#5942]
## **Describe the bug**
The notebook_loaded.Notebook event is not called (binding to it from a jupyter notebook extension).
This might be because it is called before the extension is loaded. I'm not sure why, but if the notebook loaded event is binded (bound?) to in the main.js of a notebook extension, the bound function is never called.
The code meant to be called on 'notebook_loaded' can't just be run in the main.js of the extension, because if it is in larger notebooks the cells might not be loaded in by the time this is called, which is a problem if the extension needs to access the cells or the notebook interface.

## **To Reproduce**
1. Create basic jupyter notebook extension setup, including the necessary files for an extension (description.yaml and main.js).
    
    Directory structure of example extension:

    ```
    extension_folder
    |
    |--- main.js
    |--- description.yaml
    ```

2. In main.js, in the define statement, require jupyter events and bind to the 'notebook_loaded.Notebook' event with, for example, a console log.

    example `main.js`:
    ```js
    define([
        'base/js/events',
    ], function (events) {
    
    
    events.on('notebook_loaded.Notebook', function(event, data){
        console.log("notebook loaded called");
    });
    
    console.log('extension running!')
    
    
    });
    ```

3. Install and enable the extension.

    To install an extension:
    `jupyter nbextension install extension_folder --user`
    And enable it:
    `jupyter nbextension enable extension_folder/main --user`

4. Open a jupyter notebook.
5. Open the console, and observe whatever you bound to the notebook loaded event was not called.

## **Expected behavior**
The notebook_loaded.Notebook event should be called when the notebook interface has finished loading, so the extension is ready to manipulate it.

## **Screenshots**
Code for main.js of an extension.
![image](https://user-images.githubusercontent.com/29357472/104656358-64158f00-567c-11eb-9bf4-05109f129276.png)

The browser console in the jupyter notebook. Note 'extension running!' is printed in the console, meaning the extension fired, but 'notebook loaded called' is not, meaning the event listener never fired.
![image](https://user-images.githubusercontent.com/29357472/104656459-93c49700-567c-11eb-91c1-6b50ff66a678.png)

**Desktop (please complete the following information):**
 - OS: linux (ubuntu 20.04)
 - Browser Chrome, Firefox, Brave
 - Version: all tested Jupyter notebook versions (6.x.x)

**Comment by kevin-bates** [comment]
This issue appears to have been unexpectedly duplicated, but since the latter issue (#5943) has been more recently updated, I'm closing this one.
