### ISSUE TITLE
Colab Notebook Not showing Properly 

### ISSUE THREAD

**Issue by deenukhan** [jupyter/notebook#5948]
Hi Everyone, 

I am not able to see properly my colab notebook in GitHub Jupyter notebook viewer, not sure why this is happening but it's happening only for notebooks that are made on colab and later uploaded in Github repo.

Check out the notebook: https://github.com/deenukhan/Personalized-Medicine-Redefining-Cancer-Treatment/blob/main/personalized_cancer_dig_updated.ipynb

[Issue_Screenshot](https://drive.google.com/file/d/1k2DAwdK10XwhFFkhTn7LPq70LFGyXvpB/view?usp=sharing)

**Comment by jasongrout** [comment]
Both Colab and GitHub notebook viewer are out of our control - we do not develop them and this is not the appropriate place to ask for help on either of them. I suggest you contact either the colab support or GitHub support about this.
