### ISSUE TITLE
hi my jupyter kernal connection failed lots of time.Kindly support

### ISSUE THREAD

**Issue by Pinku28-bit** [jupyter/notebook#5950]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Zsailer** [comment]
@Pinku28-bit, if you're still having issues, would you mind posting a bit more information? Ideally, try running `jupyter notebook --debug` in your terminal and paste the output in this issue. That might help you/us identify the source of your issue. 

I'm going to close this for now, but feel free to re-open if you're still having issues. Thanks!
