### ISSUE TITLE
pyzmq >=21.0 drops support for Python <=3.5, breaks Python 3.5 pip install

### ISSUE THREAD

**Issue by jameslzhu** [jupyter/notebook#5961]
pyzmq 21.0 has dropped support for Python 3.5. 
https://github.com/zeromq/pyzmq/blob/442c0308a00a73e812889fc848803cec990a87ae/docs/source/changelog.rst

The usage of f-strings breaks the setup.py install on Python 3.5:
```
Collecting pyzmq>=17.1 (from qtconsole->jupyter)
  Using cached https://files.pythonhosted.org/packages/af/9f/5b4942b3b028fb38cd66514472649025644d78ca0b29f7b79e9ff2acc048/pyzmq-21.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yqn57qxi/pyzmq/setup.py", line 687
        warn(f"platform={get_platform()}, vcvars=")
                                                 ^
    SyntaxError: invalid syntax
```
Manually specifying pyzmq<20 worked for me and `pip install notebook` worked after that.

Please help update the dependencies to specify `pyzmq<21.0` if you wish to keep supporting Python 3.5 (pyzmq<20 for Python 3.4). Since 3.5 is EOL, dropping support may also be an option but would break flows on Ubuntu 16.04 LTS (which I'm using on this box).
https://github.com/jupyter/notebook/blob/a9f04697098c850b20d5f5166d87e933fbc977a2/setup.py#L104

**Comment by kevin-bates** [comment]
This sounds like your version of `pip` doesn't support the `python_requires` statement which `pyzmq` (21+) sets to `3.6`.  I would suggest you update `pip` or pin `pyzmq<21.0`, but there really isn't anything we should do from a notebook perspective.  When I use an updated `pip`, installation of `pyzmq` pulls in 20.x in python 3.5.

On the 3.5 support front, we discussed this today in the maintainer's meeting and decided that [dropping 3.5](https://github.com/jupyter/notebook/pull/5962) would be best.  As a result, you may need to look into pinning `notebook<6.3` as well.

**Comment by jameslzhu** [comment]
Thanks, Kevin. I'll look into updating my pip version.

I totally understand the decision to drop support for 3.5. I would appreciate an update to the install documentation to specify this, but I agree no other technical action is needed.
