### ISSUE TITLE
the problem of Code completion function

### ISSUE THREAD

**Issue by wang1xu** [jupyter/notebook#5964]
When I use jupyter notebook,like I inupt pri then press TAB,jupyter notebook does not respond。

The environment is created by Anaconda3.
![image](https://user-images.githubusercontent.com/48145639/106101760-529ead80-6179-11eb-8029-0b9891b3cb85.png)

**Comment by kevin-bates** [comment]
This sounds like a duplicate of several issues and rooted in IPython.  Please see https://github.com/jupyter/notebook/issues/5922#issuecomment-753390002 and downgrade your `jedi` release.
