### ISSUE TITLE
Kernel does not exist on jupyter server. Please select another kernel

### ISSUE THREAD

**Issue by orlandoandradeb** [jupyter/notebook#5969]
Hello 

I have been using Jupyter Notebook in Pycharm for a while normally without many problems. However, I just install a new environment and when I created a new project using that new environment I cant begin the  connection with jupyter notebook. The message that I got is the following:   "Kernel does not exist on jupyter server. Please select another kernel". Same thing happend if I run it directly in jupyter notebook.  I attach a picture: 

https://mega.nz/file/zdIjyIob#afVoei2plzG5nPVxjYmt367oxg-aAm-vcfirWYWijmQ

Another weird thing is that where I suposed to see the rest of the enivroments It does not show me nothing. 

Any Idea what can be?   

I check the configuration of the server and it is linked with the correct interpreter, I uninstall and install again the dependences of the library jupyter. 

I don´t know what else can be. I hope you can help me with this. 

Thank you

**Comment by kevin-bates** [comment]
Hello @orlandoandradeb.  I'm not familiar with PyCharm's Jupyter integration, but your problem's description implies that the target kernel and the running notebook server (presumably started by PyCharm) are probably in different python environments.

I see the tab name (which I assume is the kernel name) of `Python [conda env:ambientequetzal]`.  This looks like a kernel name produced by [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) which overrides the default kernel spec manager with their own to essentially allow for kernels to span environments.  As a result, there could be something related to that.

It might be helpful to run `jupyter kernelspec list` from the environment in which you're experiencing this issue and locate the directory of the kernel you're having issues with.  Then check that directory's `kernel.json` file and ensure its `argv` stanza is pointing a valid command.

**Comment by michaelpedota** [comment]
I am currently working on Mac OS Big Sur 11.1. I am also having kernel issues, however, it is related to Jupyter notebook. I have looked at all GitHub pages pertaining to this error, and none of the suggestions made have worked. It seems to be an error associated with appnope. It leads to an error with AssertionError: Couldn't find class NSProcessInfo. If there are any suggestions that would be very helpful.

**Comment by kevin-bates** [comment]
@michaelpedota - a quick google of _"NSProcessInfo appnope"_ suggests you might start here: https://github.com/minrk/appnope/issues/12#issuecomment-741618954

**Comment by michaelpedota** [comment]
@kevin-bates - I have tried all of the different Github threads pertaining to this NSProcessInfo and none have worked so far

**Comment by kevin-bates** [comment]
As you said, your issue is related to `appnope`.  Does it reproduce without `appnope` installed? 
> I have tried all of the different Github threads pertaining to this NSProcessInfo and none have worked so far

It would also be helpful to know what you have tried.  This https://github.com/jupyterlab/jupyterlab/issues/9410 suggests it's not a notebook (or lab) issue since `appnope` is being imported in a notebook's cell, which indicates that `ipykernel` would be the "process carrier" for this. 

If you still believe your issue pertains to this repository, please open a separate issue and we'll go from there.  I don't want this to side-track the original issue above.

**Comment by michaelpedota** [comment]
@kevin-bates - I uninstalled a few packages which lead to Jupyter notebook not being able to be called through terminal. I reinstalled Jupyter and a few more packages and the kernel issues seems to have miraculous disappeared. Thank you for all your help

**Comment by Schmidtbit** [comment]
@michaelpedota what packages did you remove? I am having this same issue with appnope=0.1.2, python=3.8.5

**Comment by wxtt522** [comment]
I am having this same issue too

**Comment by wxtt522** [comment]
i solve this problem use :  pip install 'tornado==6.1' --force-reinstall 。I just reinstalled one casually, but my jupyter notebook can work in pycharm now
