### ISSUE TITLE
'port' moved from NotebookApp to ServerApp, but Jupyter ignores ServerApp.port

### ISSUE THREAD

**Issue by fofoni** [jupyter/notebook#5977]
**Description**
Today I installed Jupyter in a new virtual environment, and when started, it displayed the following warning:

```
[W 2021-02-05 15:12:00.626 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
```

It still worked as usual. After I changed the line:

```
c.NotebookApp.port = <my custom port>
```

in `~/.jupyter/jupyter_notebook_config.py` to:

```
c.ServerApp.port = <my custom port>
```

the warning is no more, but now Jupyter ignores the configuration and listens at the default 8888 port.

The same problem happened to other configuration variables, like `password`.

**To Reproduce**
1. Change the setting `NotebookApp.port` to `ServerApp.port` in the file `~/.jupyter/jupyter_notebook_config.py`
2. Run `jupyter notebook`, and check that it outputs `[I 20:16:38.282 NotebookApp] http://localhost:8888/?token=<...>`

**Expected behavior**
The warning message `'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config` led me to believe that, if I changed the config from `NotebookApp` to `ServerApp`, everything would still work as usual (in particular, Jupyter would listen at my custom port as specified in `ServerApp.port`).

**Version info:**
Fedora 31 `Linux 5.5.13-200.fc31.x86_64 #1 SMP Wed Mar 25 21:55:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : 5.0.2
ipython          : 7.20.0
ipykernel        : 5.4.3
jupyter client   : 6.1.11
jupyter lab      : 3.0.7
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5

$ python
Python 3.9.1 (default, Feb  5 2021, 15:04:29) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
```

**Comment by Zsailer** [comment]
@MeeseeksDev migrate to jupyter-server/jupyter_server
