### ISSUE TITLE
Jupyter Notebook fails to launch

### ISSUE THREAD

**Issue by Bambillo1** [jupyter/notebook#5982]
Using commands:

jupyter notebook

jupyter notebook list

jupyter notebook stop

from the anaconda prompt on Windows fail to resolve jupyter notebook failure to launch.

Kindly help me to resolve this problem by listing all probable causes of this problem.

**Comment by Zsailer** [comment]
Hi @Bambillo1, thanks for opening this issue. This doesn't appear to be an issue with Jupyter Notebook; rather, it might be an issue with how anaconda installed Jupyter.

We suggest posting your question on [Jupyter's Discourse page](https://discourse.jupyter.org/), where you're likely to receive more timely feedback/help. Remember to paste any output from your prompt in the post to help with diagnosing your issue. Thank you!
