### ISSUE TITLE
kernel interrupt command is ignored

### ISSUE THREAD

**Issue by evfro** [jupyter/notebook#5985]
**Describe the bug**
I use a dedicated conda environment with jupyter notebook and jupyterlab server installed in it. Let's call it `jlab_env`. I also install `nb_conda_kernels` in the `jlab_env` to switch between different conda environments from within the notebook.

For a new project, I create a new clean environment -- let's call it `no_jlab_env` -- and only register its kernel by running `conda install ipykernel` within this environment. This kernel gets visible in the running notebook thanks to `nb_conda_kernels`.

In the notebook interface, I switch from `jlab_env` to my freshly created `no_jlab_env` kernel. All notebook cells can be executed normally.  However, the notebook becomes unresponsive to kernel interrupt commands. It is impossible to stop execution of any cell until it fully completes executing its code . If I switch back to `jlab_env`, cells run as normal and I can interrupt execution at any time.

**To Reproduce**
Here's a simple example that I run in the notebook with both kernels and get completely different behavior:
```python
import time

for i in range(50):
    print(i, end=',')
    time.sleep(0.2)
print('\nDone')
```
If I use `no_jlab_env` kernel, it will print all numbers from 0 to 49 as well as final "Done" line no matter how many times I press `i-i`, or select `Interrupt Kernel` from the menu, or hit the black square stop-buttton in the notebook. In contrast, the same code can be interrupted at any time in the `jlab_env` kernel using any of the methods above.

**Expected behavior**
Hitting `i-i`, or selecting `Interrupt Kernel` from the menu, or pressing the black square stop-button should immediately interrupt execution in the `no_jlab_env`. It should display the `KeyboardInterrupt` error, stop printing numbers, and never print "Done".

**Desktop (please complete the following information):**
 - OS: tested on Windows 10 and several Ubuntu systems of different versions.
 - Browser: tested in recent versions of Microsoft Edge (chromium-based) and Mozilla Firefox

**Additional context**
Below are the logs from the console.

Launching the `no_jlab_env` ipython kernel from the dropdown menu activated by `nb_conda_kernels`:
```
[I 10:16:56.868 LabApp] Kernel started: b7b29d3f-b1f0-4121-8428-3ea5723c832f, name: conda-env-no_jlab_env-py
Active code page: 65001
CONDA_PREFIX=C:\Users\user\Anaconda3\envs\jlab_env
[I 10:17:55.156 LabApp] Kernel restarted: b7b29d3f-b1f0-4121-8428-3ea5723c832f
Active code page: 65001
CONDA_PREFIX=C:\Users\user\Anaconda3\envs\jlab_env
```
Executing a for loop in a cell and trying to interrupt it by hitting stop button 2 times:
```
[I 10:18:06.940 LabApp] Kernel interrupted: b7b29d3f-b1f0-4121-8428-3ea5723c832f
[I 10:18:07.794 LabApp] Kernel interrupted: b7b29d3f-b1f0-4121-8428-3ea5723c832f
```
It had no effect, the loop continued to run and got fully exhausted with no interruption, no `KeyboardInterrupt` message appeared.

Now switching to the `jlab_env` kernel:
```
[I 10:18:54.722 LabApp] Kernel shutdown: b7b29d3f-b1f0-4121-8428-3ea5723c832f
[I 10:18:54.976 LabApp] Kernel started: d43ff21e-ae02-4cf0-b6ba-c72be23b4cfc, name: conda-env-jlab_env-py
```
Again executing the for loop and hitting the stop button right after it started:
```
[I 10:19:01.181 LabApp] Kernel interrupted: d43ff21e-ae02-4cf0-b6ba-c72be23b4cfc
```
This time cell execution interrupts immediately as expected. I can see the `KeyboardInterrupt` message.

**Comment by kevin-bates** [comment]
What's interesting about this is that it happens on Windows **and** Linux and those two platforms use different mechanisms for interrupts (an `interrupt_event` vs. `SIGINT`, respectively).  

This led me to look at `nb_conda_kernels` and I notice that the kernel is launched differently depending on whether the current process (i.e., the notebook or jupyter server) `sys.prefix` path matches that of the target kernel's conda env.  If matched, the startup is identical to not using nb_conda_kernels (and likely more akin to what you see with your `jlab_env` kernel). If not-matched, or "external", the target conda env must be activated, then the kernel is started.  All of this occurs via the `nb_conda_kernel.runner` script and, as a result, I believe the process inheritance is affected, leading to both `interrupt_events` and `signals` not _flowing_ to the "child" process.

I then checked for open issues regarding interrupts and found you opened this issue https://github.com/Anaconda-Platform/nb_conda_kernels/issues/180 back in September and one in Lab four months prior to that: https://github.com/jupyterlab/jupyterlab/issues/8388.

Based on the findings above, I believe this needs to be pursued by the `nb_conda_kernels` maintainers.  However, if your kernel were to support _message-based interrupts_, (which ipykernel does not) then the interrupt sent from `jupyter_client` would go through the messaging protocol and not via a signal (or interrupt_event) and would likely work.

I suspect that if you run the server (notebook or jupyter server) from the `no_jlab_env`, then _that_ kernel will be interruptable, while the `jlab_env` kernel will not.

I'm closing this issue and the jupyter lab issue should similarly be closed.  Should there be an actual Jupyter issue from this, it would likely need to be dealt with in the `jupyter_client` repository where the kernel's lifecycle management takes place.

**Comment by evfro** [comment]
@kevin-bates thank you very much for rigorous analysis and for explanation! All mentioned issues were also mine, I felt desperate due to inability to understand from which side the problem comes from. Now it's clear. I'll close the jupyterlab issue.

You're absolutely right, if I'd install `jupyterlab` in the `no_jlab_env`, it would work normally. However, it defeats the purpose of the described setup. The whole idea is to have and maintain only one `jupyterlab` installation in a dedicated environment rather than having to install `jupyterlab` in every new environment created for each new project. It's a pity that such functionality doesn't work out-of-the-box (I thought that it's a pretty common usage pattern). Simply switching the kernel (when `nb_conda_kernels` is disabled or not installed) doesn't activate the proper environment.

I have started the related discussion at https://discourse.jupyter.org/t/unable-to-reliably-use-single-jypyterlab-server-with-multiple-conda-environments/7979. Maybe someone will come up with a workaround, at least unless `nb_conda_kernels` gets fixed. I'd really like to avoid having to install `jupyterlab` in all my current and future environments. But I don't see any viable alternative so far...

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/unable-to-reliably-use-single-jypyterlab-server-with-multiple-conda-environments/7979/2

**Comment by kevin-bates** [comment]
> However, it defeats the purpose of the described setup. The whole idea is to have and maintain only one jupyterlab installation in a dedicated environment rather than having to install jupyterlab in every new environment created for each new project.

I understand.  The purpose of that experiment was to confirm the hypothesis that its the _external_ environments that yield uninterruptible kernels.  I agree that this is something that would be worth addressing.
