### ISSUE TITLE
How to change jupyter lab's open.html file location on Windows 10

### ISSUE THREAD

**Issue by AntoineLu** [jupyter/notebook#5996]
Hi,
When I start my jupyter lab server in the Powershell with the `jupyter-lab` command, the following output displays
```
Jupyter Server 1.4.1 is running at:
[I 2021-03-01 16:37:43.498 ServerApp] http://localhost:8888/lab?token=48f3f45f1d874b47b48474be9e71dfe44356834b5585c234
[I 2021-03-01 16:37:43.499 ServerApp]  or http://127.0.0.1:8888/lab?token=48f3f45f1d874b47b48474be9e71dfe44356834b5585c234
[I 2021-03-01 16:37:43.499 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-03-01 16:37:43.565 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/<my username>/AppData/Roaming/jupyter/runtime/jpserver-22204-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=48f3f45f1d874b47b48474be9e71dfe44356834b5585c234
     or http://127.0.0.1:8888/lab?token=48f3f45f1d874b47b48474be9e71dfe44356834b5585c234
```
and the browser opens the jpserver-22204-open.html.

The thing is that this file is not located in the described path but rather in `C:\Users\<my username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\Roaming\jupyter\runtime`

Of course the browser displays a nice ERR_FILE_NOT_FOUND since that file does not exist.

I installed Python 3.9 via the Microsoft Store and Jupyter Lab via pip.
Seems like Jupyter thinks it is installed in another directory. How to change the default file location or even better, directly make the browser to open on localhost:8888and not the open.html file?
I tried setting the `c.NotebookApp.use_redirect_file` variable to False in the jupyter-notebook-config.py but it did not change anything.

Thanks.

**Comment by loginov671** [comment]
I have the same problem

**Comment by Zsailer** [comment]
@MeeseeksDev port to jupyter-server/jupyter_server

**Comment by Zsailer** [comment]
@MeeseeksDev migrate to jupyter-server/jupyter_server
