### ISSUE TITLE
Fix rendering of single quotes in pdfTeX output

### ISSUE THREAD

**Issue by khughitt** [jupyter/notebook#600]
Currently, when saving a notebook to PDF via LaTeX, any single quotes in notebook are rendered as unicode apostrophes.
- before: '
- after: ’  ([U+2019](http://www.fileformat.info/info/unicode/char/2019/index.htm)?)

This has a couple of problematic side-effects, particularly when rendering Python, etc. code output:
1. Code cannot be copied and pasted into a console
2. Scripts cannot be executed without specifying a unicode coding, even when the only apostrophes are in comment sections.

It seems like there should be an option at the pdfTeX level to specify that ascii characters should be used in place of the apostrophes (e.g., http://tex.stackexchange.com/questions/63345/how-to-make-a-real-apostrophe-or-single-quote-in-latex/63348#63348)

It would be great if this could be implemented in Jupyter's PDF generation.

See also: http://stackoverflow.com/questions/32973952/ipython-notebook-single-quotes-rendered-incorrectly-in-pdf-output
## Version info
- Arch Linux (4.2.1 64-bit)
- Python 2.7.10 / 3.5.0
- IPython 4.0.0
- pdfTeX, Version 3.14159265-2.6-1.40.16

**Comment by Carreau** [comment]
Once we have the migrating script working we should move that to jupyter/nbconvert I guess.

**Comment by JamiesHQ** [comment]
@mpacer : do you know if this issue has been resolved and if so, please go ahead and close it. thanks!

**Comment by mpacer** [comment]
This is expected behaviour of LaTeX — `'` is treated as the apostrophe `’` and in order to get a left single quote you need to use backticks (` which seems impossible to render as code in gfm) and to get a straight single quote is somewhat more complicated, see https://tex.stackexchange.com/questions/52529/straight-quotes but in short use the `textcomp` package and then use `\textsinglequote`

MWE
```
\documentclass{article}
\usepackage{textcomp}     % for \textquotesingle macro
\begin{document}
This is a straight quote called explicitly: \textquotesingle.

This is a backtick turned into an opening single quote: `.

This is a straight quote turned into an apostrophe: '. 
\end{document}
```

**Comment by takluyver** [comment]
This does now seem to be working as expected in code blocks - I can copy and paste string literals (`'hello'`) from PDF and Python accepts them as valid string literals. I think that's what the original complaint was about.
