### ISSUE TITLE
UI for adding cell metadata tags?

### ISSUE THREAD

**Issue by stevengj** [jupyter/notebook#601]
It would be nice to have a UI for adding [cell metadata](https://nbformat.readthedocs.org/en/latest/format_description.html#cell-metadata), especially tags, for processing of notebooks by other tools (and by the notebook itself; e.g. see the `norun` tag proposed in jupyter/nbformat#20).

A possible UI would be something like an "Add Tag..." entry in the _Cell_ menu (shortcut C-m C-t), which prompts you to type in a tag string to add to the current cell.  (There could also be a dropdown menu of tags that have already been added.)

The tags could be displayed as e.g. little tabs above the input area, something like:
![image](https://cloud.githubusercontent.com/assets/2913679/10457798/b3b45cac-7195-11e5-8b6d-5855d57785fb.png)

Clicking on the tab would allow you to edit or delete the tag.

**Comment by stevengj** [comment]
Or maybe it would be better for the tabs to be below the `In` line:
![image](https://cloud.githubusercontent.com/assets/2913679/10458033/dbc7fe14-7196-11e5-9978-234fb81a8302.png)
This would be better for e.g. Markdown cells, since they don't have the grey background and tabs above the text might be distracting.

**Comment by minrk** [comment]
cc @jdfreder, who I believe has written a version of this before. I'm not sure where that went. Also @ellisonbg, UI overlord.

**Comment by jdfreder** [comment]
It never got merged, I'd be happy to rewrite && reopen as a PR against jupyter/notebook master if everyone agrees to it. https://github.com/ipython/ipython/pull/6638

(I never created a plugin as stated at the bottom of the PR)

**Comment by stevengj** [comment]
@jdfreder, some version of that looks great to me!

I don't mind re-typing the tag each time if there is a keyboard shortcut (e.g. `C-m C-t`) and tab completion.

**Comment by ellisonbg** [comment]
It would be great to see this revived - it would be really useful to have.

On Tue, Oct 13, 2015 at 3:04 PM, Steven G. Johnson <notifications@github.com
> wrote:

> @jdfreder <https://github.com/jdfreder>, some version of that looks great
> to me!
>
> I don't mind re-typing the tag each time if there is a keyboard shortcut
> (e.g. C-m C-t) and tab completion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/601#issuecomment-147815487>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by damianavila** [comment]
> It would be great to see this revived - it would be really useful to have.

I agree...

**Comment by bollwyvl** [comment]
Content-less string tags are so last decade. :) Might i recommend if we re-visit this and start opening up the ui to more use of metadata, that we strongly consider using a robust, URI-based approach for defining cell metadata, such as json-ld? Pay no attention to the rdf part, all we really need is @id, @type and @context: what is it, what type is it, according to whom?

**Comment by takluyver** [comment]
I'm sure there's a use for JSON-LD, but I think we want a way for people to quickly add simple, arbitrary tags to cells, without having to think about semantic web concepts. I think simple string tags will do nicely for this.

json-ld is so next decade, and I suspect it still will be in 10 years time ;-)

**Comment by stevengj** [comment]
See also jupyter-incubator/contentmanagement#18

**Comment by takluyver** [comment]
A basic UI was added in #2048 for 5.0; I expect that as people start to use it we'll get a fancier UI.
