### ISSUE TITLE
Unable to save in an 'untitled folder' directory

### ISSUE THREAD

**Issue by wood-chris** [jupyter/notebook#6028]
**Describe the bug**

Saving a notebook in an "untitled folder" generates an error

**To Reproduce**
1. Run a jupyter notebook session
2. Click on New -> New Folder
3. This creates a directory called "Untitled Folder"
4. Enter this folder, and create a new notebook }
5. File -> Save as shows `Untitled%20Folder` - adding a file name after this, ending up with `Untitled%20Folder/my_notebook.ipynb` and click save. Error shows:

        ```Unexpected error while saving file: Untitled%%20Folder/test.ipynb [Errno 2] No such file or directory: '/Users/chris/Untitled%%20Folder/test.ipynb'```

    it looks like it's added an extra percent symbol in the directory name

**Expected behavior**
The notebook should save without error!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: Version 89.0.4389.90 (Official Build) (x86_64)

**Comment by kevin-bates** [comment]
Hi @wood-chris - thank you for opening this issue.  I can reproduce this (even back to Notebook 5.7.8) and would characterize the issue as "SaveAs into space-separated folder fails".  We'll need to take a look.

In the meantime, you should be able to work around this via Duplicate/Rename/{modify}/Save/Delete{original} or use the Lab extension as I'm unable to reproduce it using `jupyter lab`.
