### ISSUE TITLE
My os.environ don't see my actual variables from Jupyter notebook

### ISSUE THREAD

**Issue by Casyfill** [jupyter/notebook#604]
I have some environmental variables i want to use frop python. 
While everything is ok with python started from bash, os.environ shows some default list of variables, but not mine, when it is started from Jupyter

I use Mac OS El Capitan, anaconda python 2.7

**Comment by minrk** [comment]
How are you starting the notebook? What variables are different?

**Comment by Casyfill** [comment]
starting with sudo ipython notebook (don't work without sudo, writes IOError: [Errno 13] Permission denied: '/Users/casy/Library/Jupyter/runtime/notebook_cookie_secret'

I dont have any of my preconfigured variables, but all generic ones: LOGNAME
USER
PATH
HOME
DISPLAY
LANG
TERM
SHELL
SHLVL
EDITOR
SUDO_USER
USERNAME
JPY_PARENT_PID
SSH_AUTH_SOCK
SUDO_UID
GIT_PAGER
LC_ALL
_
SUDO_COMMAND
SUDO_GID
CLICOLOR
__CF_USER_TEXT_ENCODING
PWD
MAIL
PAGER

**Comment by minrk** [comment]
sudo's probably the reason. That switches user and changes the environment. Try fixing the permissions on your files and relaunching without sudo:

    sudo chown -R `whoami`:staff ~/Library/Jupyter
    jupyter notebook

**Comment by Casyfill** [comment]
Thanks, that works fine

**Comment by Casyfill** [comment]
Thanks!

yet now I don't have rights to write anything (((:
IOError: [Errno 13] Permission denied: '/Users/cas...

**Comment by Carreau** [comment]
Can you expand on `not in my home directory` , do you mean like system wide, like `/Library` or actual subfolder of your home directory ?

**Comment by minrk** [comment]
@Casyfill the fix is probably the same - whatever file you don't have read access to was probably created when you started IPython and/or the notebook with `sudo`. You can use the same

```bash
chown -R `whoami`:staff PATH
```

fix to resolve any permissions on files that were created in this way.

**Comment by Casyfill** [comment]
Yes thank you I did exactly that. Probably easier way for me is to chow -R for my home root



—

**Comment by JamiesHQ** [comment]
@Casyfill : We're doing a little housekeeping on our issue log and noticed this thread from 2015. Has this issue been resolved to your satisfaction and can it be closed? thanks!

**Comment by Casyfill** [comment]
Oh yeah, thank you!
