### ISSUE TITLE
invalid syntax on anaconda

### ISSUE THREAD

**Issue by Ant9615** [jupyter/notebook#6040]
hi! 
I install jupyter notebook in anaconda virtual environment in windows10 
but it is not working! because syntax error, invalid synatax 
I don`t know why i get this error, and how solve this problem 

 - OS: windows10
 - Browser: chrome
 - Version: 1.0.0

![Capture](https://user-images.githubusercontent.com/49273778/115591305-ec0ad500-a30c-11eb-8ce7-9f6f7cddf895.PNG)

**Comment by kevin-bates** [comment]
This is a known issue in [jupyter_client](https://github.com/jupyter/jupyter_client/issues/634) and implies you (implicitly) installed jupyter_client `6.1.13` - which has since been removed.  Please update your jupyter_client to `6.1.12` and restart your notebook server.
