### ISSUE TITLE
support sigalarm to prevent stuck on service requests such as listing huge folders.

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#6047]
support sigalarm to prevent blocking on service requests such as listing huge folders.

**Comment by kevin-bates** [comment]
Per our [README](https://github.com/jupyter/notebook#notice), we probably won't be taking on this kind of thing (not to mention Windows doesn't support SIGALRM - although there are alternatives there).  I would recommend looking at the [`AsyncContentsManager`](https://jupyter-server.readthedocs.io/en/latest/developers/contents.html?highlight=AsyncContentsManager#asynchronous-support) that was recently introduced in Jupyter Server.  If that isn't sufficient, we'd be more inclined to entertain such a feature request in Jupyter Server.

**Comment by cailiang9** [comment]
Are there any roadmap about this? When is it available?

Even async IO could prevent jupyter stucking on "listing huge folders", the underlying IO operations can still cause overhead nfs(such as ceph) IO access. If often cause the host to reboot. Maybe we still need a 10s-timeout on IO operations.
