### ISSUE TITLE
Remote notebook server permission denied

### ISSUE THREAD

**Issue by liuyigh** [jupyter/notebook#605]
Hi, fellow ,

I setup a remote public server according to [Running a notebook server](http://jupyter-notebook.readthedocs.org/en/latest/public_server.html).

However, I cannot save the notebooks. Got a permission error. I am using `anaconda` under `pyenv`. 

![capture_web](https://cloud.githubusercontent.com/assets/5641850/10473261/5f491a56-71de-11e5-9e1b-ec28fa8fd61a.PNG)

If I switch to system anaconda, running ipython 3.2, the server runs fine with ipython `nbserver` profile.

Did I missing anything in the new jupyter server setup?

Thanks a lot! Jupyter is awesome!

-- Yi

```
(root)yi@seqC:/mnt/ahseqdata/Yi$ ipython notebook
[I 19:02:15.009 NotebookApp] Writing notebook server cookie secret to /run/user/1005/jupyter/notebook_cookie_secret
[W 19:02:15.026 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
[I 19:02:15.043 NotebookApp] Serving notebooks from local directory: /mnt/ahseqdata/Yi
[I 19:02:15.043 NotebookApp] 0 active kernels
[I 19:02:15.044 NotebookApp] The IPython Notebook is running at: https://[all ip addresses on your system]:9999/
[I 19:02:15.044 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 19:02:24.346 NotebookApp] 302 GET / () 1.82ms
[I 19:02:24.356 NotebookApp] 302 GET /tree () 1.82ms
[I 19:02:26.032 NotebookApp] 302 POST /login?next=%2Ftree () 1.39ms
[W 19:02:49.022 NotebookApp] Notebook qPCR-PC/20151012-geno/p100 4bp loss genotyping 2015.10.13.ipynb is not trusted
[W 19:02:49.075 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js () 13.44ms referer=https://:9999/notebooks/qPCR-PC/20151012-geno/p100%204bp%20loss%20genotyping%202015.10.13.ipynb
[I 19:02:49.709 NotebookApp] Kernel started: 540a4062-cb3a-4ea5-81a2-b9f4fc6ac755
[I 19:02:53.722 NotebookApp] Saving file at /qPCR-PC/20151012-geno/p100 4bp loss genotyping 2015.10.13.ipynb
[W 19:02:53.723 NotebookApp] Saving untrusted notebook qPCR-PC/20151012-geno/p100 4bp loss genotyping 2015.10.13.ipynb
[W 19:02:53.774 NotebookApp] Permission denied: qPCR-PC/20151012-geno/p100 4bp loss genotyping 2015.10.13.ipynb
[W 19:02:53.775 NotebookApp] 403 PUT /api/contents/qPCR-PC/20151012-geno/p100%204bp%20loss%20genotyping%202015.10.13.ipynb () 60.38ms referer=https://:9999/notebooks/qPCR-PC/20151012-geno/p100%204bp%20loss%20genotyping%202015.10.13.ipynb
```

**Comment by liuyigh** [comment]
Working now. It seems running the 4.0 server under `pyenv` does not have permission to `/mnt` NASes. Running it in my home folder works fine.

But why system python has no problem?

**Comment by minrk** [comment]
Can you compare the uid, gid, and environment variables between the two sessions where one works and one doesn't? Also, what are the permissions (owner, group, and mask) of the place where accessing fails?

**Comment by liuyigh** [comment]
Thanks for your reply, Minrk!

I ran `ps axjf`. The two processes have same uid `1005`:

One works:
```
PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
11781 15838 15838 11781 pts/4    15838 S+    1005   0:00  |           \_ /opt/anaconda/bin/python /opt/anaconda/bin/ipython notebook --profile=nbserver
```

Doesn't work:
```
11781 16221 16221 11781 pts/4    16221 S+    1005   0:00  |           \_ /home/yi/.pyenv/versions/miniconda-3.16.0/bin/python /home/yi/.pyenv/versions/miniconda-3.16.0/bin/jupyter-n
```

permission:
Home folder works:
`drwxr-xr-x 1 yi yi  32 Apr 13  2015 scripts/`

`1005` is `yi`'s uid, gid mask

NAS /mnt fails:
`drwxrwxrwx  3 1000010 1000001    0 Oct 13 18:56 20151012-geno/`

**Comment by minrk** [comment]
Does it work if you run the code in regular Python in the pyvenv?

**Comment by liuyigh** [comment]
Unfortunately, I don't have root privilege to install `sqlite3-lib` on the machine. It is required to compile regular python in `pyenv`. Thanks for your reply all the same.

**Comment by JamiesHQ** [comment]
This issue appears to be resolved and is being closed. Please re-open the issue if you are still experiencing difficulties. thanks!
