### ISSUE TITLE
Unabe to 'save as' a notebook inside folder name which contains space character

### ISSUE THREAD

**Issue by HarshithMjh** [jupyter/notebook#6054]
Steps to reproduce: 
1. Create a folder which contains space (Eg: 'Untitled Folder')
2. Navigate inside the folder and create a notebook
3. Go to file -> Save As
4. It would already contain the folder name. But space would be replaced with %20. Enter the name for the new notebook to be created after '/'. 
5. Click on "Save". It fails with the error.

Manual resolution:
Remove the %20 manually. Then click on "save". It works

**Comment by HarshithMjh** [comment]
Screenshot of error
![savefail](https://user-images.githubusercontent.com/42462113/117605670-e79c4400-b175-11eb-877f-8cd385e9d7ed.jpg)

**Comment by kevin-bates** [comment]
Hi @HarshithMjh - I can confirm this is an issue in the Notebook frontend.  It does not occur using Lab, so there's some missing escape logic in the save-as functionality.

We're minimally "staffed" on frontend maintainers at the moment, so until a fix can be contributed, using Lab or the manual replacement workaround will need to suffice.  Sorry for the inconvenience.

**Comment by stephenisau** [comment]
Hi @kevin-bates, @HarshithMjh! I saw this issue on my feed and decided to look into it. Tracked the issue down to [this pull request](https://github.com/jupyter/notebook/pull/6030) which seems to have fixed the issue. Commenting here to follow more closely and to see if the issue needs further investigation!

**Comment by jtpio** [comment]
Closing as fixed and released (see comments above).
