### ISSUE TITLE
Console error: "#element".tooltip is not a function (in the home page)

### ISSUE THREAD

**Issue by ra218** [jupyter/notebook#6062]
**Describe the bug**
I am receiving a browser console error when loading home page in jupyter notebook.

1. start jupyter terminal
2. go to browser window with opened jupyter notebook home page
3. Open the developer console window to check the error

**Expected behavior**
The console error should not be present on loading the home page

**Screenshots**
![image](https://user-images.githubusercontent.com/77959857/118354258-9e048c80-b5ad-11eb-9654-e25a3fef5a43.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - chrome
 - Version - 6.1.1

**Additional context**
The issue cannot be seen in the console of ipynb file.
![Untitled](https://user-images.githubusercontent.com/77959857/118354627-3cddb880-b5af-11eb-8883-eb180b1fefc8.jpg)

**Comment by ilayh123** [comment]
I fixed the bug, now waiting for approval: https://github.com/jupyter/notebook/pull/6070. Hope this helps you!
