### ISSUE TITLE
ERROR:asyncio:Exception in callback  jupyter notebook

### ISSUE THREAD

**Issue by xmirager** [jupyter/notebook#6064]
HOW TO SOLVE THIS PROBLEM???

PYTHON 3.8.9
JUPYTER NOTEBOOK

ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x0000021AC443E5B0>(<Future finis...5947\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x0000021AC443E5B0>(<Future finis...5947\r\n\r\n'>)>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-4' coro=<HTTP1ServerConnection._server_request_loop() running at c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\tornado\http1connection.py:823> wait_for=<Future finished result=b'GET /api/co...85947\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\tornado\ioloop.py:688]> while another task <Task pending name='Task-92' coro=<MappingKernelManager.start_kernel() running at c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\notebook\services\kernels\kernelmanager.py:176> cb=[IOLoop.add_future.<locals>.<lambda>() at c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\tornado\ioloop.py:688]> is being executed.

**Comment by xmirager** [comment]
Resolved, dependency conflict, jupyter-client downgrade,6.2.0→6.1.12,pip install jupyter-client==6.1.12

**Comment by kevin-bates** [comment]
Sorry that this wasn't directly evident from your original description.  Jupyter client 6.2.0 had a lifespan of hours and was pulled back to 6.1.12.  Nothing in that description rang any bells from the 6.2.0 issues or implied a jupyter_client relationship - which I'll chalk up to just plain bad luck.

Really glad you're moving forward again!
