### ISSUE TITLE
Path name with spaces converted to "%20" by Jupyter Notebook was not valid for saving

### ISSUE THREAD

**Issue by biallenchanuow** [jupyter/notebook#6067]
**Environment**
Jupyter Notebook version:  6.0.1
Conda version: 4.8.2
Python version: 3.7.10
Platform: Mac OS version 10.15.3
Browser Version: Google Chrome - Version 90.0.4430.212 (Official Build) (x86_64)

**Description**
I have encountered this issue when I tried to save a Notebook file in the subpath of the current path which has spaces in its name - the spaces were automatically converted to "%20", but the file failed to be saved without any changes to the original pathname, except for adding a subpath at the end. Removing the "%20" markers and added the spaces back did work though.

https://user-images.githubusercontent.com/80367048/118929902-7126ef80-b988-11eb-89ce-5fc358882508.mov

**Comment by kevin-bates** [comment]
This should be resolved via https://github.com/jupyter/notebook/pull/6030 and available in the 6.4.0 release.

**Comment by biallenchanuow** [comment]
Thank you @kevin-bates
