### ISSUE TITLE
Juypter notebook taking forever to open it's homepage on Brave browser

### ISSUE THREAD

**Issue by BhShanmukhaBhargav-project** [jupyter/notebook#6079]
I recently reinstalled Anaconda and changed the working directory of the Jupyter notebook from C drive to D. Since then it's taking longer than usual. It's working fine on Chrome but not performing well on Brave browser.

**Comment by SahilSunda** [comment]
i guess there is some issue on Brave browser side as the problems are also with the previous users

**Comment by kevin-bates** [comment]
I'm going to close this as a duplicate of #6080.  If we can get general Brave support and this still isn't resolved, we can re-open at that time.  It would be better to just collaborate on #6080 for now.
