### ISSUE TITLE
Problem with Displaying Graphs Using Matplotlib Floating Axes in Jupyter Notebook

### ISSUE THREAD

**Issue by znusbick** [jupyter/notebook#6086]
When running the following
```python
from matplotlib.transforms import Affine2D
import mpl_toolkits.axisartist.floating_axes as floating_axes
import matplotlib.pyplot as plt
from mpl_toolkits.axisartist.grid_finder import (FixedLocator, MaxNLocator,
                                                 DictFormatter)

fig = plt.figure(figsize=(8, 4))
    
tr = Affine2D().scale(2, 1).rotate_deg(30)

    
grid_helper = floating_axes.GridHelperCurveLinear(
    tr, extremes=(-0.5, 3.5, 0, 4),
    grid_locator1=MaxNLocator(nbins=4),
    grid_locator2=MaxNLocator(nbins=4))

    
ax = fig.add_subplot(
    131, axes_class=floating_axes.FloatingAxes, grid_helper=grid_helper)

aux_ax = ax.get_aux_axes(tr)


fig.subplots_adjust(wspace=0.3, left=0.05, right=0.95)

aux_ax.bar([0, 1, 2, 3], [3, 2, 1, 3])

plt.show()
```

The correct images come up through my terminal, but when transferring it to a jupyter notebook, the images become distorted.  Both are running Matplotlib 3.4 and Python 3.8, so there should be no difference in the end result.  I also tested this with Python 3.7 and 3.9 and the same issues occur.

**Comment by kevin-bates** [comment]
Hi @znusbick - thanks for opening this issue.  Assuming the embedded image[*] depicts the behavior you're describing, it also occurs using Jupyter Lab 3.0.  I recommend opening this issue in https://github.com/jupyterlab/jupyterlab where you'll get much better support. I don't think this would be addressed in this repository unless it amounts to a harmless version bump on some dependency (which could be the case).

![image](https://user-images.githubusercontent.com/22599560/120823065-e0195200-c50b-11eb-89b3-27f19dd612c3.png)

[*]: Note, I was working off your original description via email that was based entirely on this [demo](https://predictablynoisy.com/matplotlib/gallery/axisartist/demo_floating_axes.html#sphx-glr-gallery-axisartist-demo-floating-axes-py).  I now see you've trimmed down the scenario (thank you), but the demo shows the _expected image_ as the left-most image of the three.  I've also confirmed the similar output (of the left-most image) using your update.
