### ISSUE TITLE
: EnvironmentLocationNotFound: Not a conda environment: C:\ProgramData\Anaconda3.

### ISSUE THREAD

**Issue by ieefs416** [jupyter/notebook#6087]
Hi everyone,

When I tried to open Anaconda navigator and install Jupyter notebook, I saw this error: EnvironmentLocationNotFound: Not a conda environment: C:\ProgramData\Anaconda3. Then, Jupyter Notebook was installed oddly but any notebook didn't connect to kernel and finally kernal was dead. Later, I closed Anaconda and opened it again but this time Jupyter was not launched and I installed it again but over and over again I saw this error message: EnvironmentLocationNotFound: Not a conda environment: C:\ProgramData\Anaconda3.

When I first downloaded Anaconda, i didnt have any problems. It was working properly. I just installed jupyter notebook once and then Jupyter was opened a new Chrome window with green border. But two days ago, everything suddenly changed.

But there is something else; if I use to Anaconda prompt and write jupyter notebook, Jupyter open with new Google Chrome window with green border and everything is okay. Notebook connect to kernel and kernel is ready to use. But
if I closed this chrome window with green border,I didnt find .ipynb files in Users folder and one more thing, if I open anaconda and click to install and launch jupyter notebook, I am facing the above mentioned problems.

What do you think I should solve this problem?

Thank you.

**Comment by kevin-bates** [comment]
A quick [google search](https://www.google.com/search?q=EnvironmentLocationNotFound%3A+Not+a+conda+environment%3A+C%3A%5CProgramData%5CAnaconda3&oq=EnvironmentLocationNotFound%3A+Not+a+conda+environment%3A+C%3A%5CProgramData%5CAnaconda3&aqs=chrome..69i57j69i58j69i60.252j0j1&sourceid=chrome&ie=UTF-8) implies this is an `nb_conda` issue and nothing we can address here.  Two hits led to these issues:

https://github.com/Anaconda-Platform/nb_conda/issues/66
https://github.com/Anaconda-Platform/nb_conda/issues/94
