### ISSUE TITLE
Kernel dies when trying to plot an image with matplotlib

### ISSUE THREAD

**Issue by mattpodolak** [jupyter/notebook#6089]
**Describe the bug**
Kernel dies when running `plt.imshow()`

**To Reproduce**
1. Run cell with imports:
```
import tensorflow as tf
import numpy as np
from tensorflow import keras
from PIL import Image
import matplotlib.pyplot as plt
import imagehash
import torch
```
2. Run cell to load images:
```
Y_img = Image.open('./img/img1.jpg')
X_img = Image.open('./img/img2.jpg')
target = torch.tensor(imagehash.dhash(Y_img, hash_size=16).hash, dtype=torch.float32)
```
3. Try to plot X_img:
```
plt.imshow(X_img)
```
4. Kernel dies within 1-2 seconds, no errors thrown, no image plotted

**Expected behavior**
I expected matplotlib to plot the image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - jupyter core     : 4.7.1
 - jupyter-notebook : 6.4.0

**Additional context**

**Comment by mattpodolak** [comment]
I commented out the `torch` import, and this allowed the code to run successfully

**Comment by mattpodolak** [comment]
From the console log from jupyter notebook:
```
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

```

**Comment by kevin-bates** [comment]
This is not a notebook issue but more related to Open MP.  A google hit shows quite a bit of success using the suggestion of setting `KMP_DUPLICATE_LIB_OK = True`.  There are also other suggestions in issue 1715 of the https://github.com/dmlc/xgboost repo.
