### ISSUE TITLE
how can we compile and build the whole project from the source code

### ISSUE THREAD

**Issue by whuii** [jupyter/notebook#6092]
Dear authors:
     Since we need to refactor the project, how can we compile and build the whole project from the source code? Do you have any relevant explanatory materials? Thks.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Zsailer** [comment]
Here is some documentation that should help: https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.rst#setting-up-a-development-environment
