### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 1334738575** [jupyter/notebook#6100]
When I run “jupyter notebook”，I find：  
  from jupyter_client.channels import HBChannel
  File "D:\anaconda3-2021.5\envs\tensorflow\lib\site-packages\jupyter_client\channels.py", line 47
    time_to_dead: float = 1.0
                ^
SyntaxError: invalid syntax

**Comment by krassowski** [comment]
Are you using Python 3.5? If so, you may need to either:
- downgrade `jupyter_client` to 6.1.12
- upgrade Python to 3.6 or newer as Python 3.5 reached end of life and is no longer supported (see [here](https://stackoverflow.com/questions/40655195/is-there-official-guide-for-python-3-x-release-lifecycle) and [here](https://devguide.python.org/#status-of-python-branches)).

See: https://github.com/jupyter/jupyter_client/issues/634

**Comment by kalpitgupta369** [comment]
Hey, I would like to help your issue. Please approve the required permissions.

**Comment by 1334738575** [comment]
> Hey, I would like to help your issue. Please approve the required permissions.

Thank you for your concern, but the issue has been resolved.
