### ISSUE TITLE
Reconsider `space` based command mode shortcuts

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#611]
Right now in master we have the following keyboard shortcuts that involve space:

* `space` = scroll down
* `shift-space` = scroll up
* `ctrl-space` = toggle marked cell

I have a feeling that cell marking is going to be more common than scrolling and am wondering if we want to swap these into:

* `ctrl-space` = scroll down
* `ctrl-shift-space` = scroll up
* `space` = toggle marked cell

**Comment by jdfreder** [comment]
I prefer the second, but should point out space and shift-space are browser defaults for scrolling.

**Comment by Carreau** [comment]
Shortcut feel like API to me, I would prefer not to change in between minor revisions.

**Comment by jdfreder** [comment]
> Shortcut feel like API to me

True, especially if the user is automating things.

**Comment by ellisonbg** [comment]
OK I will look for another shortcut...

**Comment by ellisonbg** [comment]
But we should not break keyboard shortcuts in the 4.x series.

**Comment by ellisonbg** [comment]
Yeah, I am going to close this ...

**Comment by jdfreder** [comment]
All of the shortcuts could use an audit for 5.0.
