### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Apidwalin** [jupyter/notebook#6111]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
![logo](https://user-images.githubusercontent.com/84679338/126641437-ad5a479d-5f81-40a4-b272-8d86a3bae06f.png)
![Uploading jupyter_notebook_dogs.jpg…]()

**Comment by kevin-bates** [comment]
Hi @Apidwalin - I'm going to close this issue since it doesn't contain any information.  If you feel this is a mistake, please open a new issue and provide a detailed description of the problem you are experiencing and we can work off that new issue. Thank you.
