### ISSUE TITLE
Notebook cannot connect to kernel in fresh miniconda environment (Windows, Python 3.8)

### ISSUE THREAD

**Issue by jennirinker** [jupyter/notebook#6113]
**Describe the bug**
Jupyter, installed in a fresh miniconda environment on Windows 10 using pip, cannot connect to the kernel. Fails loading win32api and then fials on loading runtime connection json files. Uninstalling `pywin32` with pip and then reinstalling with conda fixes the issue, but jupyter is still not super stable. Installing jupyter by conda, instead of pip, resolves issues.

**To Reproduce**
1. In Anaconda prompt `conda create -n testing python=3.8`, then `conda activate testing`
2. `pip install jupyter`
3. `jupyter notebook`
4. Try to open a notebook, see the kernel never starts and several error messages are printed to the Anaconda prompt.

**Expected behavior**
The kernel should work.

**Screenshots**
Error on first kernel try:
![billede](https://user-images.githubusercontent.com/11503804/126772733-9e5f75c3-536f-48a4-b03d-daa73f3bbe27.png)

Error on second kernel try:
![billede](https://user-images.githubusercontent.com/11503804/126772768-2682c24b-1a58-4127-90f7-939bacec5ef0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 89.0.2

**Additional context**
Uninstalling the pywin32 package with pip and then reinstalling with conda allows the kernel to start. However, the "quit" button doesn't seem to work, but you can always ctrl-c many times to stop the kernel.

EDIT: Confirmed that installing jupyter via conda, not pip, resolves both the kernel issue and the problem of not being able to shut down.

**Comment by kevin-bates** [comment]
Hi @jennirinker - thanks for opening the issue and documenting how it was resolved.  There is quite a history of installation issues surrounding `pywin32` and the Jupyter stack on WIndows and there really isn't a whole lot we can do about it.  Since it sounds as if you're adequately moving forward, I'm going ahead with this issue's closure.
