### ISSUE TITLE
Error: Invalid URI. What is the format to pass URL of Jupyter notebook to the websocket server?

### ISSUE THREAD

**Issue by Vishav3** [jupyter/notebook#6118]
I made a python client (websockets based). I need to send URL of the python server which is running in the Jupyter notebook. This is the URL of my running notebook

![image](https://user-images.githubusercontent.com/80038335/127048838-114c5947-19bc-44ed-9029-c393577bd170.png)

I am using this in client code as:

# Importing the relevant libraries
import websockets
import asyncio

# The main function that will handle connection and communication with the server

async def listen():
   
   url = "ws://127.0.0.1:8888/notebooks/check_text.ipynb"
   print("hello")
   # Connect to the server
   async with websockets.connect(url) as ws:
        # Send a greeting message
        await ws.send("Hello Server!")
        # Stay alive forever, listening to incoming msgs
        while True:
            msg = await ws.recv()
            print(msg)

# Start the connection
asyncio.get_event_loop().run_until_complete(listen())

But i am not able to establish communication. The error is:
![image](https://user-images.githubusercontent.com/80038335/127049176-c2645bcc-bdc4-4adf-abc8-920713d99ea6.png)

The URL is working well when i open it in another browser window. I am not understanding whether i am using wrong syntax for URL or something else is missing. Any suggestions would be helpful.

**Comment by Zsailer** [comment]
@Vishav3, thanks for the question. Unfortunately, this repository is watched by only a few people doing small maintenance, i.e. bug and security fixes. (See this [notice](https://github.com/jupyter/notebook#notice).)

I suggest posting your question on our [Jupyter Discourse](https://discourse.jupyter.org/) channel. There is a larger group of Jupyter community members that hang out there and might be able to help.
