### ISSUE TITLE
Unexpected bold italic markdown rendering

### ISSUE THREAD

**Issue by chezzwizz** [jupyter/notebook#6126]
**Description**
Text marked for bold and italics seems to parse as expected during the preview, but renders with unexpected results. During the preview, the text will appear with both bold and italics when using `***text** more text*`, but will render as if it had been entered as `**\*text** more text*`. In fact, the former and the latter produce similar output. 

**To Reproduce**
1. Create a new markdown cell. *(in existing notebook)*
2. Enter in the following markdown:
```
***bold italics** italics*
```
3. Click the "Run" button, Ctrl-Enter, or selecting "Run cells" from the Cells menu on the Jupyter notebook rendered web page.

**Behaviors**
Expected | Actual
-------------|--------
***bold italics** italics* | **\*bold italics** italics*

**Screenshots**
Unrendered:
![jupyter_bold_italics_markdown_unrendered](https://user-images.githubusercontent.com/1437965/128617922-27902ff5-c02c-4efa-a5a1-5d05cdc5837c.png)

Rendered:
![jupyter_bold_italics_markdown_rendered](https://user-images.githubusercontent.com/1437965/128617924-688b5dcd-0e7b-4d9e-bf0b-4210d1de8156.png)

**Platform**
*Desktop/Operating System :* 
   Chrome OS (Version 91.0.4472.167 64-bit Official Build) running Anaconda 3

*Kernel Version:*
   output from command `uname -or`:
   ```
   5.4.109-26094-g381754fbb430 GNU/Linux
   ```

*Browser:*
   Google Chrome

*Browser Version:*
   64-bit  Official build: 91.0.4472.167

**Comment by blackphoenix42** [comment]
I would like to take on this issue. Can anyone assign me?
@Zsailer
