### ISSUE TITLE
Can not use JupyterLab or Jupyter Notebooks with `unsafe-eval` turned off in Content Security Policy

### ISSUE THREAD

**Issue by MikeMcGarry** [jupyter/notebook#6129]
**Describe the bug**

Since 5 days ago the juptyer/notebook now uses a --development webpack build by default.

Unfortunately this is incompatible with a sensible Content Security Policy which does not have unsafe-eval included.

This is the line here: https://github.com/jupyter/notebook/blame/79fc76e890a8ec42f73a3d009e44ef84c14ef0d5/package.json#L20

And this is the merge request here: https://github.com/jupyter/notebook/commit/79fc76e890a8ec42f73a3d009e44ef84c14ef0d5

**To Reproduce**
1. Install JupyterHub using the most recent version of the `notebook`
2. Visit your installation from any browser with a Content Security Policy that does not contain `unsafe-eval`. You will get nothing rendered when trying to run a notebook and the following console error

**Expected behavior**
No console error and everything works as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/30035387/128826791-0fd5f8c4-0989-4378-8a7f-20b3e7fa7657.png)

**Desktop (please complete the following information):**
- Chrome 
- Safari
- Edge

**Additional context**

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/can-not-use-jupyterlab-or-jupyter-notebooks-with-unsafe-eval-turned-off-in-content-security-policy/10321/2

**Comment by MikeMcGarry** [comment]
Thank you for addressing this so quickly!
