### ISSUE TITLE
Jupyter can’t start a kernel Files called kernel specs tell Jupyter how to start different kinds of kernels. To see where these are on your system, run jupyter kernelspec list:

### ISSUE THREAD

**Issue by Javed000** [jupyter/notebook#6138]
$ jupyter kernelspec list
Available kernels:
  python3      /home/takluyver/.local/lib/python3.6/site-packages/ipykernel/resources
  bash         /home/takluyver/.local/share/jupyter/kernels/bash
  ir           /home/takluyver/.local/share/jupyter/kernels/ir

**Comment by kevin-bates** [comment]
Hi @Javed000 - Thanks for the helpful tip for folks. I'm going ahead and closing this since it really isn't pointing out an issue.
