### ISSUE TITLE
Text marked for bold and italics seems to parse as expected during the preview

### ISSUE THREAD

**Issue by Javed000** [jupyter/notebook#6139]
Description
Text marked for bold and italics seems to parse as expected during the preview, but renders with unexpected results. During the preview, the text will appear with both bold and italics when using ***text** more text*, but will render as if it had been entered as **\*text** more text*. In fact, the former and the latter produce similar output.

To Reproduce

Create a new markdown cell. (in existing notebook)
Enter in the following markdown:
***bold italics** italics*
Click the "Run" button, Ctrl-Enter, or selecting "Run cells" from the Cells menu on the Jupyter notebook rendered web page.
See error

![128617922-27902ff5-c02c-4efa-a5a1-5d05cdc5837c](https://user-images.githubusercontent.com/62198674/129768082-6a822b4b-8952-4808-a80b-78d6831c8a4b.png)

**Comment by Zsailer** [comment]
Repeat of #6126
