### ISSUE TITLE
Notebook Showing Browser Context Menu on Right Click

### ISSUE THREAD

**Issue by ankitmishra88** [jupyter/notebook#6140]
On the tree page, where all the files and folder are listed, We expect to have its own context menu when we do right click on any file or directory name, but currently it has browser default context menu.
As a new contributor to the Open Source Community, I wanted to add this.

Default:
Browser Own context menu on right-click

Expected:
Notebook own context menu containing options like "Open", "Rename", "Move" and "Delete"

Please see the attached image.
I am willing to do this improvement. Let me know please, If I should proceed with it? (I have done the half change, will be more than happy, if this can be included, and I should proceed)
![expected vs default](https://user-images.githubusercontent.com/42653549/129881505-75baa22f-2feb-4391-8746-a3fb1738f9ad.png)

**Comment by ankitmishra88** [comment]
Update: I have added the context menu and added 4 options for now "Open", "Rename", "Move", "Delete", and they are working.
Please find the attached video
https://www.loom.com/share/37cc92d2b5c948c0bcbffa511c20fede

**Comment by Zsailer** [comment]
Thanks, @ankitmishra88! See my comments in #6143. Closing here.
