### ISSUE TITLE
The Notebook kernel sometimes gets automatically stop!

### ISSUE THREAD

**Issue by Oga997** [jupyter/notebook#6144]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Zsailer** [comment]
Unfortunately, we won't be able to help you without more information. I suggest posting your question on our [Jupyter Discourse forum](https://discourse.jupyter.org/). There are more community members lurking on that channel who may be able to help you identify your issue. Closing here.
