### ISSUE TITLE
!pip install prompts shell error

### ISSUE THREAD

**Issue by shaw1111** [jupyter/notebook#6166]
notebook:6.4.3, centos:8, python:3.6

type the ` !pip install jieba`, the errors:

`OSError                                   Traceback (most recent call last)
<ipython-input-18-8d4aba8ffc6d> in <module>
----> 1 get_ipython().system('pip install jieba')

/usr/local/lib/python3.6/site-packages/ipykernel/zmqshell.py in system_piped(self, cmd)
    648                 self.user_ns['_exit_code'] = system(cmd)
    649         else:
--> 650             self.user_ns['_exit_code'] = system(self.var_expand(cmd, depth=1))
    651 
    652     # Ensure new system_piped implementation is used

/usr/local/lib/python3.6/site-packages/IPython/utils/_process_posix.py in system(self, cmd)
    155                 child = pexpect.spawnb(self.sh, args=['-c', cmd]) # Pexpect-U
    156             else:
--> 157                 child = pexpect.spawn(self.sh, args=['-c', cmd])  # Vanilla Pexpect
    158             flush = sys.stdout.flush
    159             while True:

/usr/local/lib/python3.6/site-packages/IPython/utils/_process_posix.py in sh(self)
     64             self._sh = pexpect.which(shell_name)
     65             if self._sh is None:
---> 66                 raise OSError('"{}" shell not found'.format(shell_name))
     67 
     68         return self._sh

OSError: "/bin/nologin" shell not found
`

**Comment by kevin-bates** [comment]
Is your notebook server running as a service process (where shell logins are disabled)?  I suspect `ipykernel` requires a shell to implement its `!` command.

You could probably modify your `kernel.json` file to add/extend the `env:` stanza to include a `SHELL` value.  For example (for `ipykernel`):
```JSON
{
 "argv": [
  "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python",
 "env": {
   "SHELL": "sh"
 },
 "metadata": {
   "debugger": true
 }
}
```

This file can be located using `jupyter kernelspec list`, identifying your kernel name in the left-hand column and the `kernel.json` is located in the directory identified in the corresponding right-hand column.

cc: @Carreau

**Comment by shaw1111** [comment]
thanks, adding the `env` is worked
