### ISSUE TITLE
Attention is all you need

### ISSUE THREAD

**Issue by QasimNiaz** [jupyter/notebook#6183]
Facing this issue:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-14-ec4f59b9cf67> in <module>
----> 1 spacy.load('en_core_web_sm')

/usr/local/lib/python3.7/site-packages/spacy/__init__.py in load(name, **overrides)
     28     if depr_path not in (True, False, None):
     29         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 30     return util.load_model(name, **overrides)
     31 
     32 

/usr/local/lib/python3.7/site-packages/spacy/util.py in load_model(name, **overrides)
    218     elif hasattr(name, "exists"):  # Path or Path-like to model data
    219         return load_model_from_path(name, **overrides)
--> 220     raise IOError(Errors.E050.format(name=name))
    221 
    222 

OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by Zsailer** [comment]
Hi @QasimNiaz, thanks for opening this issue, but this isn't related to Jupyter Notebook in any way. I suggest reopening you question on the [spaCy](https://github.com/explosion/spaCy) page.
