### ISSUE TITLE
[DOCS] Notebook examples not rendering properly

### ISSUE THREAD

**Issue by choldgraf** [jupyter/notebook#6193]
### Description

Between version `v5.7.6` and the `stable`, the notebook examples section has become broken. For example:

- [The working version on `v5.7.6`](https://jupyter-notebook.readthedocs.io/en/5.7.6/examples/Notebook/Notebook%20Basics.html)

![image](https://user-images.githubusercontent.com/1839645/136105978-af5b01f3-c312-4ec1-a189-0476a39a3ba4.png)

- [The broken version on `stable`](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Notebook%20Basics.html)

![image](https://user-images.githubusercontent.com/1839645/136106075-6366a342-81d0-4312-b7b6-f5b271af8248.png)

It looks like the notebook `.ipynb` files are being parsed as raw text, rather than parsed properly by `nbsphinx`.

I tried getting a dev environment set up to debug this, but `pip install .` wasn't working because I ran into the error `error: [Errno 2] No such file or directory: 'bower'`. So opening this issue to track it.

The notebook examples are at the link below, and I suspect the fix will need to be somewhere around there, or in the Sphinx configuration:

https://github.com/jupyter/notebook/tree/master/docs/source/examples/Notebook

Originally reported in https://discourse.jupyter.org/t/error-in-jupyter-readthedocs-page-rendering/11038

**Comment by choldgraf** [comment]
Do you think it'd be helpful to do a quick update on the notebook docs to make them more maintainable, and point others in the right direction for other docs resources? I'd be happy to have a quick chat and brainstorm some low-hanging-fruit PRs with you

**Comment by Zsailer** [comment]
> Do you think it'd be helpful to do a quick update on the notebook docs to make them more maintainable

@choldgraf, YES! Big resounding YES! 🤣 

I think this would be extremely helpful moving forward. Anything we can do to lessen the maintenance needs on the project would be extremely helpful. I'm happy to hop on a call anytime.

**Comment by kevin-bates** [comment]
I'd be happy to - is your RTD account name `choldgraf`?

**Comment by choldgraf** [comment]
@kevin-bates OK I think I've deleted one of the webhooks so we should only get one build per merge instead of two...we can re-sync it if the builds are broken somehow.

I've also triggered another build on master to see if the environment has updated

**Comment by mgeier** [comment]
The "Verbatim" problem is happening when using Sphinx >= 4.1.0 AND nbsphinx < 0.8.7.
See https://github.com/spatialaudio/nbsphinx/pull/591.

That's why I removed the `nbsphinx` version pinning in #6200.

**Comment by kevin-bates** [comment]
Sigh - yeah, I'm seeing nbsphinx 0.8.6 references and they're probably interfering with this portion of the build.  I should have caught this when reviewing #6200, but there was still a pin to 0.8.6 in docs/environment.yml.

PR submitted: https://github.com/jupyter/notebook/pull/6201

**Comment by kevin-bates** [comment]
crossed posts: @choldgraf - let's see where #6201 leaves us first.

**Comment by mgeier** [comment]
Sorry, I didn't realize that you are using `conda` on RTD. I'm normally not using it because it's soooo much slower.

**Comment by choldgraf** [comment]
Many thanks @kevin-bates and @mgeir for quick turnarounds this latest round of fixes 🙂
