### ISSUE TITLE
Kernel dies when trying to plot an image with matplotlib

### ISSUE THREAD

**Issue by MySlientWind** [jupyter/notebook#6219]
**Describe the bug**
Kernel dies when running `plt.plot([0,1], [0,1])`

**To Reproduce**
run this code
```python
import matplotlib.pyplot as plt
plt.plot([0,1], [0,1])
```

**Expected behavior**
I expected matplotlib to plot the image

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
![image](https://user-images.githubusercontent.com/50664099/139701946-3bf97d48-d55c-4fa3-b12b-5735764f150e.png)

**Additional context**
From the console log of jupyter notebook:
```python
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x000001C6AC984F10>(<Future finis...d8a"\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x000001C6AC984F10>(<Future finis...d8a"\r\n\r\n'>)>
Traceback (most recent call last):
  File "C:\Users\[myusername]\anaconda3\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-10' coro=<HTTP1ServerConnection._server_request_loop() running at C:\Users\[myusername]\anaconda3\lib\site-packages\tornado\http1connection.py:823> wait_for=<Future finished result=b'GET /custom...fd8a"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at C:\Users\[myusername]\anaconda3\lib\site-packages\tornado\ioloop.py:688]> while another task <Task pending name='Task-147' coro=<KernelManager._async_start_kernel() running at C:\Users\[myusername]\anaconda3\lib\site-packages\jupyter_client\manager.py:336>> is being executed.
```
I have checked issue 6089 and 3709, not my case.

**Comment by kevin-bates** [comment]
Hi @MySlientWind - this may be more related to https://github.com/jupyter/notebook/issues/6164 than matplotlib.  Can you see if the workaround described there helps  (i.e., using the `AsyncMappingKernelManager`)?  (Thanks)

**Comment by MySlientWind** [comment]
> Hi @MySlientWind - this may be more related to #6164 than matplotlib. Can you see if the workaround described there helps (i.e., using the `AsyncMappingKernelManager`)? (Thanks)

Thanks for your reply, using the `AsyncMappingKernelManager` do fix the asyncio error but unfortunately `plt.plot([0,1], [0,1])` still fail and kernel still die.

**Comment by MySlientWind** [comment]
This error also exists when I use jupyter lab or vscode.

**Comment by MySlientWind** [comment]
I found this is not a jupyter notebook issuebut matplotlib issue, see following links for details
- https://stackoverflow.com/questions/69786885/after-conda-update-python-kernel-crashes-when-matplotlib-is-used
- https://github.com/matplotlib/matplotlib/issues/21511
