### ISSUE TITLE
Decide on merging strategy for retrolab into notebook

### ISSUE THREAD

**Issue by tonyfast** [jupyter/notebook#6225]
@Zsailer @jtpio let us use this issue to discuss the plans for retrolab into notebook.

**Comment by jtpio** [comment]
Thanks @tonyfast for starting this and setting up the board to track issues :+1: 

Pasting the meeting notes here for reference:

---

* where to handle discussions knowing we're replacing one technology with another.
* Technical steps/questions
    * Do we move retrolab into jupyter/notebook?
    * Dis-entangling NBClassic, JupyterLab, and Notebook
        * NBClassic depends on Notebook and JupyterLab depends on NBClassic.
        * Making RetroLab become Notebook 7.x forces JupyterLab to drop NBClassic as dependency *or* NBClassic drops it's notebook dependency.
        * Pin nbclassic to 6.x.
---

**Comment by jtpio** [comment]
Practically speaking:

- RetroLab still needs a place to track issues for development. Moving to `jupyter/notebook` would probably mean moving the development effort to the repo as well
- RetroLab would need to update its `/retro/tree`, `/retro/notebooks`... endpoints to `/tree`, `/notebooks`...
- Some of the dependency management issues mentioned above need to be thought throw to ensure the best `pip install --pre notebook` experience

Apart from that, the first pre-release of notebook 7 could ship retrolab almost as is (after fixing the points mentioned above)

**Comment by tonyfast** [comment]
i think when we merge the project histories we can transfer issues from retrolab to notebook. there are enough to probably do by hand. the caveat is 

>  You can only transfer issues between repositories owned by the same user or organization account. You can't transfer an issue from a private repository to a public repository. https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

so we'll need notebook in the jupyterlab repo to make this work.

**Comment by jtpio** [comment]
Otherwise Meeseek can create new issues on the target repo, for example: https://github.com/jupyter-server/jupyter_server/issues/533

**Comment by jtpio** [comment]
While that merge implies publishing under the `notebook` name on PyPI, we should also consider change the name of the underlying JS packages published to npm.

For now they are under the `@retrolab` organization, for example: https://www.npmjs.com/package/@retrolab/application

It would have been nice to publish them under `@notebook` which unfortunately seems to already be taken. I have created the `@jupyter-notebook` organization on npm just in case for now. Happy to use something else if anyone has other suggestions.

**Comment by jtpio** [comment]
The RetroLab code base has been integrated in the notebook repo, and the first 7.0 pre-release is out. See the following links for more context:

- https://github.com/jupyter/notebook/pull/6294
- https://github.com/jupyter/notebook/issues/6266
- https://github.com/jupyter/notebook/releases/tag/v7.0.0a1

Transferring issues from retrolab to notebook is tracked in https://github.com/jupyter/notebook-team-compass/issues/9.

Closing as fixed, thanks all!
