### ISSUE TITLE
Create the necessary issue templates needed to alert patrons of the current changes

### ISSUE THREAD

**Issue by tonyfast** [jupyter/notebook#6226]
As we sunrise retrolab, we'll need to want to alert folks filing issues in classic and let them know about the ongoing work

**Comment by jtpio** [comment]
Thanks @tonyfast for starting this and setting up the board to track issues :+1: 

Pasting the meeting notes here for reference:

---

* where to handle discussions knowing we're replacing one technology with another.
* Technical steps/questions
    * Do we move retrolab into jupyter/notebook?
    * Dis-entangling NBClassic, JupyterLab, and Notebook
        * NBClassic depends on Notebook and JupyterLab depends on NBClassic.
        * Making RetroLab become Notebook 7.x forces JupyterLab to drop NBClassic as dependency *or* NBClassic drops it's notebook dependency.
        * Pin nbclassic to 6.x.
---

**Comment by jtpio** [comment]
Practically speaking:

- RetroLab still needs a place to track issues for development. Moving to `jupyter/notebook` would probably mean moving the development effort to the repo as well
- RetroLab would need to update its `/retro/tree`, `/retro/notebooks`... endpoints to `/tree`, `/notebooks`...
- Some of the dependency management issues mentioned above need to be thought throw to ensure the best `pip install --pre notebook` experience

Apart from that, the first pre-release of notebook 7 could ship retrolab almost as is (after fixing the points mentioned above)

**Comment by jtpio** [comment]
Linking to https://github.com/jupyter/notebook-team-compass/issues/7 where this is also discussed.
