### ISSUE TITLE
page Importing Notebooks.ipynb typo

### ISSUE THREAD

**Issue by mahengrui1** [jupyter/notebook#6232]
**Describe the bug**
The document provided online is not in perfect syntax

**To Reproduce**
1 go to https://github.com/jupyter/notebook/blob/20574f7fdcd8b5be7ca65a73c90b69aa5470553f/docs/source/examples/Notebook/Importing%20Notebooks.ipynb
2 see line 150

    "        try:\n",
    "          for cell in nb.cells:\n",
    "            if cell.cell_type == 'code':\n",

**Expected behavior**

    "        try:\n",
    "            for cell in nb.cells:\n",   (4 " ")
    "                if cell.cell_type == 'code':\n",

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win10
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] 93

**Additional context**

I see this via https://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Importing%20Notebooks.html

and in every version

**Comment by jtpio** [comment]
Closing as this appears to be fixed on `main` (likely because of the docs linting):

![image](https://github.com/jupyter/notebook/assets/591645/a2f7f3cc-df92-411e-a844-e3bceb125c25)
