### ISSUE TITLE
Wrong base URL in notebook

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/notebook#626]
Some deployments of the Jupyter notebook such as binder prefix URLs. In the case of binder, the prefix is the app id. If one uses `require.config` to specify paths for non AMD modules in **nbextensions**, then
- one cannot use `/nbextensions/foobar` because this would remove the URL prefix.
  
  ~~note: this is currently recommended in [the deprecation warning for static/widgets/js](https://github.com/jupyter/notebook/blob/531b6650ca3fe4008004b9977fed01d9af53d1ce/notebook/notebookapp.py#L123)~~ fixed in #769.
- one cannot use `nbextensions/foobar` because the configured base url is configured to `'notebook/static'`, and this would link to `notebook/static/nbextensions/foobar`.

**Comment by SylvainCorlay** [comment]
@Carreau

**Comment by SylvainCorlay** [comment]
@freeman-lab FYI, this is the issue I was having with require.config and binder.

**Comment by minrk** [comment]
`nbextensions/foobar` should work (and does when I try it with a prefix) because `nbextensions` is configured as a path to map to the correct prefix. `/nbextensions` should never be used. If `nbextensions` didn't map to the prefix, it would never work even with an empty prefix, since that's how we use it in load_extensions.

Can you provide a failing example? Everything I test works as intended with a base_url.

**Comment by SylvainCorlay** [comment]
@minrk indeed, a requirejs statement like 
```JavaScript
define(["nbextensions/widgets/widgets/js/widget", "nbextensions/foo/bar"], function(widget, foobar) { });
```
works. But the following : 

```JavaScript
require.config({
    path: {
        "foo": "/nbextensions/foo",   // wrong, removes the URL prefix
        "bar": "nbextensions/bar",    // points to BaseUrl/static/nbextensions/bar 
    }
});
```
does job what is expected.

**Comment by SylvainCorlay** [comment]
@jasongrout this is impacting pythreejs. For the flight simulator binder, I require a branch in my fork changing the require config paths.

**Comment by minrk** [comment]
Hm. I guess require.config doesn't take existing paths into account. I wonder if there's another way to do the same thing, or a way to ask require what the path for `nbextensions` is.

**Comment by Carreau** [comment]
`require.toUrl('');` will get the prefix `require.toUrl('nbextension');` will give you `/static/nbextension` if it's what you ask.

**Comment by SylvainCorlay** [comment]
@minrk @Carreau do you think we should do anything about this? (not sure the needs-info tag applies btw)

**Comment by SylvainCorlay** [comment]
FYI, I just opened a PR in pythreejs that is a workaround for this issue. https://github.com/jovyan/pythreejs/pull/35

**Comment by minrk** [comment]
I'm not sure what we can or should do about it. It seems like we just need answer to the question:

> How do we specify that one nbextension should load another?

It's possible that there's something we should change in our require config to make that work, and it's also possible that using `paths` is just the wrong way to do it, and `map` is the right thing to use.

**Comment by SylvainCorlay** [comment]
Closing as this is no longer relevant with the current extension mechanism.
