### ISSUE TITLE
Pre-release plan for Notebook v7

### ISSUE THREAD

**Issue by Zsailer** [jupyter/notebook#6266]
This describes the shortest path to get out a pre-release of Notebook v7 (currently called RetroLab).

There are still discussion around what we should do about git histories between jupyter/notebook and jupyterlab/retrolab (i.e. do we merge the two histories or not?). In the meantime, @bollwyvl mentioned changing the current `jupyter-notebook` entrypoint in notebook to retrolab might be a good place to start for the pre-release.

I'd also like to suggest that we temporarily rename the jupyterlab/retrolab repository to jupyterlab/notebook-7 or something similar, since the name "retrolab" might add some confusion for users. It's officially notebook-7 now.

Here are the steps I propose (and we should discuss):
1. Add retrolab as a dependency of the notebook package in jupyter/notebook.
2. Change the `jupyter-notebook` entrypoint in jupyter/notebook to run retrolab.
    1. Add some messaging in the logs that tell users they are looking at a new interface. If they find issues, they should report them to the jupyterlab/retrolab (or better, jupyterlab/notebook-7) repository.
    2. Also add messaging to point users to the classic entrypoint in the next point
3. Add a new entrypoint that allows users to still run the classic notebook, say `jupyter-classic` or something similar.

## Notebook 7 pre release steps

- [x] Release [notebook_shim](https://github.com/jupyterlab/notebook_shim/releases/tag/v0.1.0)
- [x] [Drop nbclassic](https://github.com/jupyterlab/jupyterlab/pull/11894) (and notebook dependency) from JupyterLab
- [x] [Add `notebook_shim` as dependency to `nbclassic`](https://github.com/jupyterlab/nbclassic/pull/88)
- [x] Release JupyterLab Pre-release (4.0): https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0a20
- [x] Create a `6.x` branch
- [x] Move RetroLab to Notebook `main` (v7) ([Draft PR to prepare for the move](https://github.com/jupyterlab/retrolab/pull/323))
- [x] Pre-release Notebook 7

Ping @tonyfast @bollwyvl @jtpio

**Comment by jtpio** [comment]
Thanks @Zsailer for opening this :+1: 

Probably the main issue with this approach will be RetroLab coming with the `/retro` endpoints. So for an end user using the pre-release of Notebook 7 with `jupyter notebook`, this will result in different URLs which might be confusing. Some UI elements will also still be referring to "RetroLab" which can look odd at first to someone installing the `notebook` package.

**Comment by bollwyvl** [comment]
My suggestion was such that we might "get away" with a fair amount of reuse-by-extension, and not get have to get too crazy on it, but could it be its own (wrapper) `NotebookApp(RetrolabApp)` in a new `retroapp.py` that:
- used `add_handlers` directly to achieve the "classic" urls
- specified `appName` in `page_settings` such that it said `Notebook` instead of `Retrolab`

If all of these things are hardcoded all over, maybe this is a good time to push on this (and the lab 4 upstream).

**Comment by Zsailer** [comment]
Last week, we discussed moving the development of retrolab to the notebook repo. 

This repo's `master` branch would become retrolab and the classic notebook would be maintained on a `6.x.x` branch, i.e. `6.4.x` today. 

I went ahead and created a `6.4.x` branch. @jtpio will work on submitting a PR with retrolab to the `master` branch.

**Comment by jtpio** [comment]
> submitting a PR with retrolab to the master branch.

Linking https://github.com/jupyterlab/retrolab/pull/323 (draft PR to get the CI checks) where some work has been started to make the transition.

**Comment by jtpio** [comment]
Posting here the steps to make the first v7 pre-release happen, as discussed yesterday during the [weekly Notebook meeting](https://github.com/jupyter/notebook-team-compass/issues/5#issuecomment-1042095593):

- Notebook 7 pre release steps:
    - [x] Release [notebook_shim](https://github.com/jupyterlab/notebook_shim/releases/tag/v0.1.0)
    - [ ] [Drop nbclassic](https://github.com/jupyterlab/jupyterlab/pull/11894) (and notebook dependency) from JupyterLab
    - [ ] Add notebook_shim as dependency to nbclassic
    - [ ] Release JupyterLab Pre-release (4.0)
    - [ ] Move RetroLab to Notebook `main` (v7) ([Draft PR to prepare for the move](https://github.com/jupyterlab/retrolab/pull/323))
    - [ ] Pre-release Notebook 7
    - [ ] Move Notebook JS to nbclassic?
        - possible, would require changing endpoints
        - downstream dependencies would not understand this
        - alternative
            - keep v6 branch "alive"

**Comment by jtpio** [comment]
Once we have a first prerelease out, we can close this issue and open a new "Notebook v7 Release Plan" issue.

Or rename this issue to "Notebook v7 Release Plan" and continue here.

**Comment by jtpio** [comment]
> Posting here the steps to make the first v7 pre-release happen

I moved the checklist to the top-level comment for visibility, and added links to the relevant issues and PRs: https://github.com/jupyter/notebook/issues/6266#issue-1094679322

**Comment by Zsailer** [comment]
I created the [6.4.x ](https://github.com/jupyter/notebook/tree/6.4.x) branch already, a little over a month ago. 😃  Should we go with that?

**Comment by jtpio** [comment]
Thanks @Zsailer.

I think this sounds good. This can be changed later if needed, in case there are plans to release a `6.5` at some point.

**Comment by jtpio** [comment]
The remaining item for this issue is to actually make the pre-release.

What do folks think about doing it with the current state of the `main` branch?

Since the repo is compatible with the Jupyter Releaser, we can follow the regular process of a "Draft Changelog" followed by a "Full Release".
We have already bumped the version to `7.0.0a0`, so if we do this with `next` as the version spec then we'll release `7.0.0a1`:

![image](https://user-images.githubusercontent.com/591645/157451958-991d3efc-437b-4e53-bf5e-8b0f71117a80.png)

**Comment by jtpio** [comment]
Also I don't seem to have rights to publish to PyPI: https://pypi.org/project/notebook.

So maybe @Zsailer would like to help with this, thanks!

**Comment by jtpio** [comment]
A follow-up would be to open a new "Notebook v7 Release Plan" issue to start discussing the timeline and items for 7.0 final.

**Comment by Zsailer** [comment]
@jtpio I added you as an owner to the PyPI package. 😎

**Comment by jtpio** [comment]
Thanks all!!

The pre-release is out so we should be able to close this issue now.

I opened https://github.com/jupyter/notebook/issues/6307 as a follow-up to plan the 7.0 release.
