### ISSUE TITLE
Regression: CSS styles in markdown not shown in v6.4.6

### ISSUE THREAD

**Issue by krassowski** [jupyter/notebook#6270]
**Describe the bug**

A user reported on mailing list that CSS styles do not work for them. They somewhat incorrectly attributed it to a security fix in version 6.4.3. The facts are:
- version 6.4.4 contained a fix and worked well
- version 6.4.5 worked well
- version 6.4.6 regressed and the styles do not work any more in markdown cells

We saw that in JupyterLab too: https://github.com/jupyterlab/jupyterlab/issues/11473. This is not a result of any deliberate action taken by Jupyter maintainers; instead an update to `klona` broke `sanitize-html` which broke allowing to pass styles. I described this in https://github.com/jupyterlab/jupyterlab/issues/11473#issuecomment-974695619; the upstream issue is https://github.com/apostrophecms/sanitize-html/issues/510.

It appears that v6.4.6 was released using releaser. This seems to have pulled a newer version of klona. To counteract that I think that we need to update `sanitize-html` and to do so we need to bump `@jupyterlab/apputils` to 3.2.x get https://github.com/jupyterlab/jupyterlab/pull/11510; currently we have:

https://github.com/jupyter/notebook/blob/ea5bfc413f830c6809ca496773a6d1861077a6a9/package.json#L22

**To Reproduce**
1. Create markdown cell
2. Enter `<span style="color: red; font-size: 30px">test</span>`
3. Render cell
4. See that text is not red and not large

**Expected behavior**

**Screenshots**

Seen in 6.4.6:

![image](https://user-images.githubusercontent.com/5832902/149025306-4782c795-afeb-44eb-bb4f-dc27e9f435bb.png)

Expected (and seen in 6.4.4 and 6.4.5):

![image](https://user-images.githubusercontent.com/5832902/149025278-384ef692-ca0b-4fb7-a347-6e943edf0cd1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 96

**Additional context**

**Comment by krassowski** [comment]
Huh, I misread, we have a caret not tilde. So we should be picking 3.2.x, unless there is a lock file which needs updating?

**Comment by krassowski** [comment]
It might be that no code changes are needed and just releasing a new patch version would fix the issue (pulling 3.2.5 apputils which was released after notebook 6.4.6).

**Comment by gutow** [comment]
I believe I am the user referred to.

I am testing combinations at the moment. What I see is that using pip install of jupyter into a clean environment with ubuntu 20.04 and Python 3.8.10,  ending up with IPython 7.31.0 and notebook 6.4.1 - 6.4.6 styles are not rendered. If  however, I run a Jupyter lab install in a clean environment as `jupyter nbclassic` the styles are rendered. So there is definitely something different between the way the two server setups process things.

I have reproduced this on several machines. Including one that I stripped out and reinstalled python3, the gui and Jupyter from scratch. This included purging and redownloading everything.

I do not think I understand enough about how the markdown processing is built to be helpful beyond this without being given specific things to check.

**Comment by gutow** [comment]
A little more information. I tried a number of install sequences. This is what I found. If I do a `pip install jupyter` into a clean environment the html styling did not work. Following that with a down grade `pip install notebook==6.4.0` makes the html styling work. If I then step up from there through 6.4.1...6.4.6 html styling does not work. However, if I skip to 6.4.4 directly from 6.4.0 styling does work. I can then step up to 6.4.5 and it still works. Stepping up to 6.4.6 causes it to stop working. Stepping back down to 6.4.5 does recover. As I was not originally paying attention to the notebook versions, this suggests the problems I had with 6.4.4 & 6.4.5 related to something not cleaning up properly when upgrading. So, it looks like I need to pin any environments that depend on this to 6.4.0, 6.4.4 or 6.4.5 for the time being. I assume there will soon be a 6.4.7 that will fix the regression in 6.4.6.

Thanks.

**Comment by krassowski** [comment]
Thanks for the extra details! I am perplexed as to what could cause this to be installation sequence dependent. I was going to suggest that you might have a conflicting conda/pip installation (if you have conda obviously) in which case some static files could be pulled from another version of notebook under certain conditions; similarly it could be the case if you have both global and local installations with local environment inheriting from global. It's good to hear that you found a sequence that works for now though.

@kevin-bates, @Zsailer would you think that publishing a 6.4.7 from master would be worth a shot now? As mentioned in https://github.com/jupyter/notebook/issues/6270#issuecomment-1010412246 the problem might just resolve itself if the releaser build pulls the new `@jupyterlab/apputils` which upgraded the dependency that broke (but I am not confident here - is there a lock file that needs updating first?).

**Comment by Zsailer** [comment]
@krassowski, sure. I'm happy to trigger a patch release. Starting the jupyter-releaser steps now...

**Comment by kevin-bates** [comment]
Thanks @Zsailer!  We'll probably need to follow up shortly with 6.4.8 to gather the close-to-complete PRs, but a quick 6.4.7 will allow us to determine if we need to make any adjustments for this issue.

@krassowski and @gutow - thank you for troubleshooting this and driving it to a potential resolution!

**Comment by krassowski** [comment]
I tested v6.4.7 and it fixes the issue locally for me. @gutow please let us know if the new release helps :)

In any case, I think we can keep this ticket open to see if we can figure out why there is some installation-sequence dependency as reported by @gutow, but this would require some more user feedback to narrow down when it happens so we can triangulate.

**Comment by gutow** [comment]
6.4.7 looks like a fix for this regression! An install into a clean pipenv `pip install -U jupyter` picks notebook==6.4.7 and the style rendering works. 

Thank you.

I do not presently have time to try doing an update to a non-working installation to see if it also properly recovers that. I will try to get to that.

**Comment by gutow** [comment]
Most styling I've tested works now. However, `style = "background-image:linear-gradient('color1','color2');" ` does not work. However, using a .png as a background image does work. This suggests it may be specifically the gradients that are being scrubbed. There may be a reason. If not it would be great if gradients could be allowed as well.

**Comment by jweill-aws** [comment]
@krassowski Should we close this issue or retitle it to cover the styling incompatibility that @gutow noticed?

**Comment by gutow** [comment]
I vote to re-title, but am biased as I added the note.

**Comment by gutow** [comment]
I think that is a good idea. I will report it there. Close this please.

**Comment by kevin-bates** [comment]
Thanks again Jonathan and Michał - closing.
