### ISSUE TITLE
Port bugfix from jupyter_server

### ISSUE THREAD

**Issue by kycutler** [jupyter/notebook#6281]
https://github.com/jupyter-server/jupyter_server/pull/628 fixed an issue in `jupyter_server`, but was never ported over to the `notebook` backend. I'm not sure what the standard procedure here is, so I'm opening this issue to hopefully get the ball rolling as this would be great to have fixed in both backends if possible.

**Comment by jweill-aws** [comment]
@blink1073 made the change in https://github.com/jupyter-server/jupyter_server/pull/628 — should this be ported into this package as well?

**Comment by blink1073** [comment]
I think so, but you'd also need https://github.com/jupyter-server/jupyter_server/pull/636 to account for kernels that don't expect that message on the control channel.

**Comment by kycutler** [comment]
@blink1073 Would you mind reviewing the PR I opened to close this?
