### ISSUE TITLE
No scroll bar for wide pandas table

### ISSUE THREAD

**Issue by guma44** [jupyter/notebook#629]
Hi,

I have a problem with Pandas display wide table. I was searching a bit but I could not find any solution. I updated from pandas 13 to 16 and suddenly the scroll horizontal bars disappeared from the tables. They look now like this:
![zrzut_ekranu](https://cloud.githubusercontent.com/assets/7634398/10639479/d0d7529a-7810-11e5-8b8e-b72fda122cc0.png)

Is the issue known? Or any idea how to solve it?

Best,
Rafal

**Comment by guma44** [comment]
One more thing that might be helpful. When I click the output to fold it the bars appear:
![zrzut_ekranu-1](https://cloud.githubusercontent.com/assets/7634398/10639729/fad3b56a-7811-11e5-9903-8d4249e91894.png)


So I can make it appear and disappear just by clicking the fold-output "button".

**Comment by captainsafia** [comment]
Thanks for opening an issue!

This was previously reported in #254 and was (maybe) fixed in #535. Can you see if this issue persists when you work off master?

**Comment by szeitlin** [comment]
I'm still having this problem (or something related), and it's seriously disrupting my work, so I guess I should try pulling the latest dev version-? Is there any other workaround you can recommend?

**Comment by takluyver** [comment]
I've just tested in master, and the horizontal scrollbars appear to be back.
