### ISSUE TITLE
Open `.py` and `.md` documents with the Notebook factory (Jupytext)

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6324]
> Maybe only the `Notebook` factory should open in `/notebooks` then?

Looking into this briefly, the trouble for jupytext are actually for file types already defined in core (like .py or .md). I was thinking to use the `Router` to deal with path like `/notebooks/not/a-ipynb-file.ext` URL to redirect to the `/edit/not/a-ipynb-file.ext?factory=Jupytext%20Notebook` if the extension is supported by Jupytext. What do you think @jtpio ?

_Originally posted by @fcollonval in https://github.com/jupyter/notebook/issues/6315#issuecomment-1074035151_

**Comment by jtpio** [comment]
@fcollonval I thought `docRegistry.defaultWidgetFactory(path)` would return "Notebook" for a .md or .py with Jupytext.

Which means there could be a check for this before redirecting to `/notebooks` or `/edit` here?

https://github.com/jupyter/notebook/blob/30310847d6804294cbeb274eeb91d126c86669f0/packages/docmanager-extension/src/index.ts#L55

**Comment by fcollonval** [comment]
Today it is not possible to coerce a factory to a existing file types. You can link a type and a factory either when defining the factory or the type. But if they have been defined as separated. This cannot be changed - in fact Jupytext is unique in that sense that it create an impossible contract on the frontend using a factory for an unsupported type. I'm reluctant to modify Jupyter core to support that corner case.

Another possibility would be for Jupytext to override the default notebook factory plugin `@jupyterlab/notebook-extension:widget-factory` by providing its own version extending the file types supported.

**Comment by fcollonval** [comment]
This should be feasible by hard-coding the settings plugin id the toolbar customization is read from to ensure it loads the core definition.

**Comment by jtpio** [comment]
@parmentelat just checking if the issue is now resolved with the latest Jupyter Notebook 7.0.3 release, as fixed by https://github.com/jupyter/notebook/issues/6914 and linked issues and PRs?

**Comment by parmentelat** [comment]
hi @jtpio 

yes the issue can be deemed fixed indeed, we've been using jupytext notebooks in the classroom since early september without a glitch, thanks !

**Comment by jtpio** [comment]
That's great to hear!

Thanks for the help, closing as fixed.
