### ISSUE TITLE
6.4.10 on PyPI but no changelog entry or tag here

### ISSUE THREAD

**Issue by hroncok** [jupyter/notebook#6325]
What commit was 6.4.10 built from?

**Comment by hroncok** [comment]
was it 5beec5484a1e08b8c53a5c7e416052b21d056f83 ?

**Comment by krassowski** [comment]
Yes, see https://github.com/jupyter/notebook/security/advisories/GHSA-m87f-39q9-6f55.

**Comment by hroncok** [comment]
Thanks.

**Comment by hroncok** [comment]
Could you please tag it and add it to https://github.com/jupyter/notebook/blob/6.4.x/CHANGELOG.md before closing this issue? I can send a PR for the changelog later this week.

**Comment by krassowski** [comment]
The release tag is available here: https://github.com/jupyter/notebook/releases/tag/6.4.10. As for changelog, I agree that it would help. I would support updating the procedure for releasing security patches to include updating changelog once the advisory is out - this could possibly be a new action of https://github.com/jupyter-server/jupyter_releaser.
