### ISSUE TITLE
Marked cells vs multi-selection.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#638]
Right now you can both mark cells (ctrl-space) and have have multiple selection (Shift-J/K). What is the difference / What's the point ?

Merge cell works only on multi-selection, not on marked cell ?
The command palette does not find any action which is triggerd only on marked cell ? 

ping @jdfreder @ellisonbg

**Comment by Carreau** [comment]
![marked vs select](https://cloud.githubusercontent.com/assets/335567/10652630/0606f852-780d-11e5-804b-4a2d633e19a8.gif)

**Comment by jdfreder** [comment]
It's a bug, you should only be able to mark.

**Comment by ellisonbg** [comment]
Hmm, I am not seeing that behavior on master. Refresh cache?

On Wed, Oct 21, 2015 at 8:06 PM, Jonathan Frederic <notifications@github.com
> wrote:

> It's a bug, you should only be able to mark.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/638#issuecomment-150058316>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Hum I have deactivate my cache globally and run my notebook with --ignore_minified_js=True, but will retry.

Envoyé de mon iPhone

**Comment by Carreau** [comment]
Hum, cannot reproduce you are right. 

Closing, opening another related bug though.
