### ISSUE TITLE
render with voila does not work

### ISSUE THREAD

**Issue by bdch1234** [jupyter/notebook#6386]
Pressing the button "render with voila" does not work, instead it just opens a new tab with the notebook-viewer again.

**Comment by andrii-i** [comment]
Can't be fixed on our side, needs to be fixed in voila

**Comment by jtpio** [comment]
Actually https://github.com/jupyter/notebook/issues/6688 might help with this. Or at least give the option to end users to open the Voila preview in the right area for example.
