### ISSUE TITLE
Unable to hyperlink to current folder

### ISSUE THREAD

**Issue by raymondw2** [jupyter/notebook#6387]
## Description

In a markdown cell, whenever we attempt to hyperlink `[current directory](./)` to show the contents of the current directory like this:
<img width="1244" alt="Screen Shot 2022-02-01 at 4 50 15 PM copy" src="https://user-images.githubusercontent.com/56237041/152450462-e5404657-7492-44d3-ba54-91f6cac7b2ee.png">

I get this error: 
<img width="550" alt="Screen Shot 2022-02-01 at 4 52 00 PM" src="https://user-images.githubusercontent.com/56237041/152450545-2ecf95e7-1fb0-45bc-be06-d762f2444a60.png">

## Reproduce

1. Go to a markdown cell
2. Type in `[current directory](./)`
3. Click on link

## Expected behavior

The hyperlink should display: 
<img width="1244" alt="Screen Shot 2022-02-01 at 4 50 15 PM copy" src="https://user-images.githubusercontent.com/56237041/152450694-ee84fe8c-fccf-4742-a192-739502653fcf.png">
the contents of the current directory. 

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by jtpio** [comment]
Checking the behavior with the latest Notebook 7 pre-release (currently `7.0.0a13`).

Linking to the current directory does not show the error dialog anymore, but it also doesn't open the folder in a new browser tab:

https://user-images.githubusercontent.com/591645/220569136-69a90ef7-a4e0-47ca-b6a9-67b841db2f91.mp4

Linking to another directory tries to open the directory under `/edit`:

https://user-images.githubusercontent.com/591645/220569210-b7865717-4c4c-4fc4-87e7-0bb60c678bf9.mp4
