### ISSUE TITLE
Should `custom.css` equivalent be supported?

### ISSUE THREAD

**Issue by krassowski** [jupyter/notebook#6390]
### Problem

Notebook v6 allows users to customize CSS styles by including `custom.css`; this was requested for JupyterLab too: https://github.com/jupyterlab/jupyterlab/issues/2102 but it seems that the issue got closed without a real solution for users who don't know TypeScript and just want to add a few tweaks. Some users seem to have expectation that it will just work in JupyterLab too jupyterlab/jupyterlab#12318 and others would like to customise their CSS programatically, the way https://github.com/deathbeds/jupyterlab-fonts allows them to do so.

### Proposed Solution

- maybe `custom.css` should still be 1-1 supported in future Notebook 7?
- maybe we could have a simple styles editor in Settings, either:
  - using "CSS-in-JSON" approach as in https://github.com/deathbeds/jupyterlab-fonts, or
  - just making a textarea allowing to paste plain CSS and be done with it?

I really don't know the solution, but just wanted to bring it up so that it is not forgotten about and maybe stimulate some discussion.

**Comment by tavin** [comment]
> Seems like `custom.css` should probably just be made to work. It's a foot gun, but has a relatively limited blast radius (maybe just a few toes).

Yes, give me the foot gun please :)

I want a CSS file relative to the project I am working on, so an "advanced setting" or whatnot in which you can input a filename or pathname. A textbox in which to paste CSS is not needed nor would it help if you're using different CSS for different projects.

Styles in %%html have a sort of delayed rendering effect, result in an unwanted output block you have to ignore or hide, and aren't possible in markdown files.

**Comment by jtpio** [comment]
Probably it would be fine to add the `{{ base_url }}/custom/` handle to Notebook 7 by default, or behind a flag, just for `custom.css`.

For those who like to have a look at implementing this for 7.0, the classic notebook defines the handler on the server and links the extra stylesheet as follows:

https://github.com/jupyter/notebook/blob/64e7c061e0273150d6e471ead34a84216220a796/notebook/templates/page.html#L17

I guess the approach for Notebook 7 would be similar.

**Comment by Higgs32584** [comment]
I will try this out! Thank you

**Comment by RRosio** [comment]
Just wanted to mention that I'm taking a look at this now!

**Comment by jtpio** [comment]
Thanks @RRosio!

**Comment by RRosio** [comment]
I began a draft PR for this issue, https://github.com/jupyter/notebook/pull/6841, but I am running into an error as the styles are not being applied. I'm working to resolve this issue, but would appreciate any feedback thus far..
