### ISSUE TITLE
Allow running Notebook v7 with JupyterLab development install

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/notebook#6392]
### Problem

RetroLab depends on JupyterLab, but changes in JupyterLab's code are not taken into account in a development install of RetroLab.

### Proposed Solution

It would be nice to have RetroLab support a `jupyter retro --dev-mode` that runs JupyterLab's development install.

**Comment by brichet** [comment]
One option can be to use [yalc](https://github.com/wclr/yalc), that act as a local package repository.

See https://github.com/jupyter/notebook/pull/7292 changes for more details.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter/notebook/pull/7292.

Feel free to open a new issue or propose improvements in a PR, thanks!
