### ISSUE TITLE
Initialized cells for new notebooks

### ISSUE THREAD

**Issue by sciunto** [jupyter/notebook#640]
Hi,

For my usage, I tend to have always the first one or two cells identical (basically imports...).
A wonderful enhancement would be that the user could define the content of new notebooks (like a template), one per language. So, each new notebook would have pre-filled cells.

I looked in the documentation, config files and asked on stackoverflow, and it seems that this feature doesn't exist so far.

Many thanks.

**Comment by guma44** [comment]
Hey,

I totally agree. I searched a bit and I could not find anything. When I start my work I always lose my time to fill all the cells I am using every day: goal, materials and methods, results, imports and initialization statements etc. That is a bit frustrating after some time so this feature would be just great! I do not known when would be the start point for the implementation of this.

Rafal

**Comment by Carreau** [comment]
You don't need to have that in the notebook itself, 

I would around notebook extension (like [here](https://github.com/ipython-contrib/IPython-notebook-extensions)) if it already exists.

It's a matter of writing a loop of `Jupyter.notebook.insert_cell_below(cell_type).set_text('Something')`, and you will have more flexibility as an extension than baked in. 

You can use the content service API if you want to access file on the filesystem,

Plus I suppose you might want to insert template cells in already existing notebooks, so this would definitively be the direction to go.

**Comment by guma44** [comment]
Hmm, I will give it a try with an extension. I never have done it though, so I do not know how far I can get with it.

**Comment by Carreau** [comment]
> Hmm, I will give it a try with an extension. I never have done it though, so I do not know how far I can get with it.

Feel free to ask question, the docs for extension is a bit lacking, I wrote [that](https://carreau.gitbooks.io/jupyter-book/content/) some time ago but it's not that up to date. 

Keep us informed of what you come up with !

**Comment by sciunto** [comment]
i'll be happy to test and make feedbacks or patches if necessary. @Carreau You pointed out a repository with extensions, but that's unofficial. Is there any plan from the jupyter community to maintain a repository with extensions? I think that would increase the visibility of such efforts and I'm pretty convinced that this one would be one of the top used extensions.

**Comment by guma44** [comment]
Thanks for support. I will check how I can get around with time and try to implement this.

**Comment by Carreau** [comment]
> Is there any plan from the jupyter community to maintain a repository with extensions

Not from the official team, but I am part of unofficial repo I pointed you too. 
The time we spend in maintaining the core itself is more than enough work, and
we do not want to commit to maintain all extensions. 

In the other direction, if the repo is well maintained, we woudl be happy to point user to it., and potentially link it from the official doc.

**Comment by demianw** [comment]
Hi! Im also looking for this solution, @Carreau where would you insert the line

`Jupyter.notebook.insert_cell_below(cell_type).set_text('Something')`

Or where would I find documentation about where to insert it? ;)
