### ISSUE TITLE
Split the help extension into multiple plugins

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6406]
### Problem

At the moment the help plugin is all contained in a single plugin:

https://github.com/jupyterlab/retrolab/blob/752e21fde9fbd995f2ab006a5c8650f7ae55a1f0/packages/help-extension/src/index.tsx#L42-L166

Ideally the functionalities would be split into multiple plugins, similar to JupyterLab:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/help-extension/src/index.tsx

This would make it easier for downstream projects or end users to disable some of the help plugins, for example the about dialog which is being replaced in JupyterLite: 

https://github.com/jtpio/jupyterlite/blob/a198d902908483f8eea36fecae858cbd14b4a078/packages/application-extension/src/index.tsx#L63-L156 

### Proposed Solution

Split plugins in the `help-extension` package like in JupyterLab:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/help-extension/src/index.tsx

**Comment by Rixant** [comment]
Hi @jtpio , I would like to work on this issue. Could you please assign me?

**Comment by jtpio** [comment]
Sure thing, thanks @Rixant!

**Comment by RRosio** [comment]
Hi @jtpio, I noticed that this issue doesn't have a PR to be merged. I opened a draft PR in hopes of being able to address it, I hope that's okay.

**Comment by jtpio** [comment]
Yes, many thanks @RRosio!
