### ISSUE TITLE
Add toggle to set default output mode of all cells to being fully expanded rather than scrollable

### ISSUE THREAD

**Issue by shergreen** [jupyter/notebook#6443]
Note that this feature request is for notebook 7.x/retrolab.

**Comment by shergreen** [comment]
Sorry for tagging this as a bug, it happened automatically. This is a feature request.

**Comment by jtpio** [comment]
Maybe a setting in the settings editor would work?

If so this is likely where the logic would go:

https://github.com/jupyter/notebook/blob/676a0fec824f4a6ce78ee6946f9c2463109c5420/packages/notebook-extension/src/index.ts#L332-L418

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter/notebook/pull/7511
