### ISSUE TITLE
config on windows (conda) fails with special username, UnicodeEncodeError

### ISSUE THREAD

**Issue by figgis** [jupyter/notebook#646]
Hi,

I can't get jupyter notebook to start on our windows laptop running anaconda. The username has a swedish character in it and that messes up with the paths.

    C:\Anaconda>jupyter --version
    4.0.6

I've changes the paths by setting the env-variables, `JUPYTER_CONFIG_DIR`, `JUPYTER_PATH` and so on to an alternative location. But I can't change the data-path as seen below:

    C:\Anaconda>jupyter --paths
    config:
        c:\anaconda\.jupyter
        C:\Anaconda\etc\jupyter
        C:\ProgramData\jupyter
    data:
        c:\anaconda\jupyter <-- I've set JUPYTER_PATH equal to this only
        C:\Users\┼sa\AppData\Roaming\jupyter  <-- I guess this is the problem
        C:\Anaconda\share\jupyter
        C:\ProgramData\jupyter
    runtime:
        c:\anaconda\jupyter\runtime

Error message:

    C:\Anaconda>jupyter notebook
    Traceback (most recent call last):
    File "C:\Anaconda\Scripts\jupyter-notebook-script.py", line 5, in 
    sys.exit(main())
    File "C:\Anaconda\lib\site-packages\jupyter_core\application.py", line 267, in
    launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, kwargs)
    File "C:\Anaconda\lib\site-packages\traitlets\config\application.py", line 591
    , in launch_instance
    app.initialize(argv)
    File "", line 2, in initialize
    File "C:\Anaconda\lib\site-packages\traitlets\config\application.py", line 75,
    in catch_config_error
    return method(app, args, *kwargs)
    File "C:\Anaconda\lib\site-packages\notebook\notebookapp.py", line 1003, in in
    itialize
    super(NotebookApp, self).initialize(argv)
    File "", line 2, in initialize
    File "C:\Anaconda\lib\site-packages\traitlets\config\application.py", line 75,
    in catch_config_error
    return method(app, args, *kwargs)
    File "C:\Anaconda\lib\site-packages\jupyter_core\application.py", line 243, in
    initialize
    self.migrate_config()
    File "C:\Anaconda\lib\site-packages\jupyter_core\application.py", line 169, in
    migrate_config
    migrate()
    File "C:\Anaconda\lib\site-packages\jupyter_core\migrate.py", line 220, in mig
    rate
    src = src_t.format(env)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xc5' in position 9:
    ordinal not in range(128)

**Comment by Carreau** [comment]
Is this an anaconda python2 install by any chance ? 

If so, I'm 99% certain that if you try with an anaconda Python3 you will not have any problem.

**Comment by figgis** [comment]
yes

```
C:\Anaconda>python --version
Python 2.7.10 :: Anaconda 2.3.0 (64-bit)
```

**Comment by figgis** [comment]
I'll try python3 tomorrow. Bedtime now :-)

**Comment by Carreau** [comment]
Well, if you can afford to migrate to anaconda python3 I would definitively  do that (you can still use Python2 in conda envs), I think I have a fix availlable but it will take a few days (weeks ?) to be rolled out. 

Good night in Europe.

**Comment by figgis** [comment]
well, the windows laptop is just for playing around. I do my real work on my linux-ditto. I'll upgrade and test and closes this one.

**Comment by Carreau** [comment]
No need to close we should still try to fix it. We'll close once the fix/workaround is in.
