### ISSUE TITLE
Upgrade jQuery to 3.5.x for Notebook 5.x

### ISSUE THREAD

**Issue by dylanraws** [jupyter/notebook#6469]
As reported in https://github.com/jupyter/notebook/issues/5489, jQuery versions below 3.5.0 have known security vulnerabilities. My organization provides customers with a managed compute environment with Jupyter Notebook 5.x installed. Our customers have the requirement that we update jQuery to resolve known CVEs. Long term, we will work with our customers to use newer major versions of Jupyter Notebook and Jupyter Lab, but for now, we ask that the jQuery version be upgraded and a new version of Jupyter Notebook 5.x be released.

**Comment by dylanramzn** [comment]
Tagging @jweill-aws for visibility

**Comment by jtpio** [comment]
Closing as this would have to be implemented in https://github.com/jupyter/nbclassic if still needed.

Please open a new issue there if the issue is still relevant, thanks!
