### ISSUE TITLE
Bug when renaming file (notebook 6.4.12)

### ISSUE THREAD

**Issue by jinzhen-lin** [jupyter/notebook#6473]
**Describe the bug**
In notebook 6.4.12，we cannot rename file sometimes.

**To Reproduce**

1. Install notebook 6.4.12
2. Start notebook with `root_dir="/home/foobar"`
3. Create a directory named `abc` (or any name with length `len(root_dir) - len("Untitled") - 1`)
4. Create a notebook with default filename 'Untitled.ipynb'
5. Rename the notebook to any other filename

Then you should got the error message 

```
File "/home/xxxxxxx/.miniconda3/lib/python3.8/site-packages/notebook/services/contents/filemanager.py",
line 579, in rename_file raise web.HTTPError(400, f'Cannot rename hidden file or directory {os_path!r}')
NameError: name 'os_path' is not defined
```

**Expected behavior**

Rename the file successfully.

According to the error message, I found a typo here (`os_path` is not defined, it should be `old_path`). .https://github.com/jupyter/notebook/blob/3e5b767ddbc3526729cadbc69fe472ffc3ec2e7e/notebook/services/contents/filemanager.py#L578-L579 And I notice that the result of `is_hidden(old_path, self.root_dir)` is true, this is because the result of `"abc/Untitled.ipynb"[len("/home/foobar"):]` is `.ipynb` and it is treated as a hidden file.

It seems that this bug is introduced by this commit https://github.com/jupyter/notebook/commit/f69eb96cff7149b38bca068f4b7faaa7baf55902 .

**Comment by braceletboy** [comment]
I faced this same error too. Can someone fix this?

**Comment by pyh-129** [comment]
> I faced this same error too. Can someone fix this?

Me too!

**Comment by YXW249** [comment]
Same error. I have to rename it in the file folder after I close the jupyter notebook.

**Comment by player999** [comment]
The same.

**Comment by sbushmanov** [comment]
Please resolve the bug

**Comment by ee2110** [comment]
The renaming error still prompt out, not sure if I need to use another version Jupyter notebook. For now, I rename file by manually change the file name at root folder. Look forward to have better version of Jupyter notebook! I like to use it

**Comment by pyh-129** [comment]
Hi，
After I rename it, it will be fine. I continue to check the information. It may have the same name as a file in the system

**Comment by yacchin1205** [comment]
I faced this same error too.

**Comment by ztsweet** [comment]
i get the same error

**Comment by vishvapalsinh** [comment]
same error :(

**Comment by charlesnyankieya** [comment]
Just rename it offline and reload the page. It should work

**Comment by sanchezis** [comment]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notebook/services/contents/filemanager.py

there is an error on this file rename function

**Comment by zyzand** [comment]
This problem also exists in version 6.5.2

**Comment by RRosio** [comment]
@zyzand The latest release of Notebook, 6.5.3 should include the fix by @yacchin1205. Would you be able to upgrade to 6.5.3 and see if you still experience this issue?

**Comment by zyzand** [comment]
It works after I upgrade to version 6.5.3. Thanks.

> @zyzand The latest release of Notebook, 6.5.3 should include the fix by @yacchin1205. Would you be able to upgrade to 6.5.3 and see if you still experience this issue?

**Comment by RRosio** [comment]
Thank you @zyzand! As there has been a release with a fix for this issue, I will go ahead and close it.
