### ISSUE TITLE
Split cell leave one cell marked.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#648]
I don't think that is intended.

**Comment by jdfreder** [comment]
? I don't understand the title of this issue, sorry.  You split a cell and what leaves what where?  Are you saying that when you split a cell only one cell is left marked?

**Comment by Carreau** [comment]
once-> one typo. 

When I split a cell into 2 other cells the second one have is still marked in blue. 

I expect the selection to be empty:

![blue](https://cloud.githubusercontent.com/assets/335567/10706762/b8b8bdd6-799e-11e5-8e87-24b2021201ca.gif)

**Comment by jdfreder** [comment]
Ah yeah, that is weird.

**Comment by ellisonbg** [comment]
There are a number of other marked state issues that we should fix before
4.1.

On Fri, Oct 23, 2015 at 7:05 PM, Jonathan Frederic <notifications@github.com
> wrote:

> Ah yeah, that is weird.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/648#issuecomment-150712482>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
