### ISSUE TITLE
Using tab key to select modal dialog widgets

### ISSUE THREAD

**Issue by auneri** [jupyter/notebook#649]
Pressing "00" to access the "restart" modal dialog, it is currently (v4.0.6) not possible to select "clear all outputs and restart" option.

A possible solution would be to use the tab key to focus on dialog widgets [as described here](http://www.java2s.com/Tutorials/HTML_CSS/Bootstrap_Example/Dialog/Use_keyboard_to_control_modal_dialog.htm).

**Comment by takluyver** [comment]
@gnestor @Carreau @minrk do we understand how to fix this, and can it be done without interfering with other keyboard functionality?

**Comment by minrk** [comment]
This appears to be fixed in master. When the dialog is opened, the restart button is focused, and I can select other buttons with tab/shift-tab.

**Comment by takluyver** [comment]
Great. I thought I had tested it and found it still not working, but I just went to test again and it seems to work.
