### ISSUE TITLE
Solve Invalid NoteBook Error In GitHub

### ISSUE THREAD

**Issue by pkenjora** [jupyter/notebook#6507]
**Describe the bug**
Taking a notebook from Colab and saving it to GitHub results in an "Invalid Notebook" error.

The bug happens because the code blocks from Colab are missing "outputs':[] and "execution_count":null.

```
    {
        "cell_type": "code",
        "metadata": {
         "id": "e2769b9e0005"
       },
        "source": [
          "!pip install git+https://github.com/google/starthinker\n"
        ]
      },
```
To fix add the missing fields to the colab source **for any code block only** not markdown:

```
    {
        "cell_type": "code",
        "execution_count": null,
        "outputs": [],
        "metadata": {
          "id": "e2769b9e0005"
        },
        "source": [
          "!pip install git+https://github.com/google/starthinker\n"
        ]
     },
```

**To Reproduce**
1. Create a notebook with a **code block** using Colab site. 
2. Save it to GitHub.
3. See error on GitHub render page.

**Expected behavior**
Render of the Colab with all sections.  Colab site should render the missing fields by default so all official site generated colabs render on GitHub without the need for manual modification.

`"outputs':[] and "execution_count":null`

**Additional context**
Yes this is a GitHub issue, however for good UX adding the missing fields will make all Colab generated notebooks compatible with GitHub. Which helps promote the product!

**Comment by jasongrout** [comment]
This is a colab and GitHub issue, neither of which is in our control.

Cc'ing @blois who works on colab, though. There is a colab repo to report colab issues, or you can report to GitHub.

**Comment by blois** [comment]
Can you share a notebook which does this? I'm unable to reproduce and this behavior is unexpected.
