### ISSUE TITLE
+1 on the solution

### ISSUE THREAD

**Issue by FICU-tensileai** [jupyter/notebook#6510]
**How I solved my similar problem**

_Prerequisite:_
1) anaconda already installed
2) Spark already installed (https://spark.apache.org/downloads.html)
3) pyspark already installed (https://anaconda.org/conda-forge/pyspark)

_Steps I did_ (NOTE: set the folder path accordingly to your system)

1. set the following environment variables.
2. SPARK_HOME to 'C:\spark\spark-3.0.1-bin-hadoop2.7'
3. set HADOOP_HOME  to 'C:\spark\spark-3.0.1-bin-hadoop2.7'
4. set PYSPARK_DRIVER_PYTHON to 'jupyter'
5. set PYSPARK_DRIVER_PYTHON_OPTS to 'notebook'
6. add 'C:\spark\spark-3.0.1-bin-hadoop2.7\bin;' to PATH system variable.
7. Change the java installed folder directly under C: (Previously java was installed under Program files, so I re-installed directly under C:)
8. so my JAVA_HOME will become like this 'C:\java\jdk1.8.0_271'

now. it works !

_Originally posted by @ptyadana in https://github.com/jupyter/notebook/issues/743#issuecomment-757435697_

I can't believe it was the dreaded space in the Java path but that fixed my problem!!! TY!!

I can't believe after 20 years of this the installer won't default to C:\Java or something other than Program Files. I despise that directory!

**Comment by RRosio** [comment]
Hi @FICU-tensileai, thank you for sharing your findings in relation to issue #743! People will be able to search and find this helpful information in the future! 
As this is seems to be a solution to a problem related to the installation path of the Java JDK I think it would be best to tag this with `no action` and `environment`, then close this issue. Before I do close it, please feel free to let me know if you feel this issue requires further discussion!

**Comment by RRosio** [comment]
Closing this issue as previously mentioned, please feel free to re-open if there needed! Thank you!
