### ISSUE TITLE
Bad address (bundled\zeromq\src\epoll.cpp:100) Jupyter error

### ISSUE THREAD

**Issue by alibukharai** [jupyter/notebook#6512]
Hi, I am new to Jupiter notebook. I followed all the steps to install it. However, there were some errors. Does anyone help me with this thanks.
Below is the output of the anaconda prompt  and Jupiter notebook screenshot 

![image](https://user-images.githubusercontent.com/60029742/183850595-306509d2-cef9-4b22-9c33-66679c7fc753.png)
![image](https://user-images.githubusercontent.com/60029742/183850766-a879db70-9bdf-43c2-b0f2-1cbb734a2517.png)

**Comment by RRosio** [comment]
Hi @alibukharai, I found [this comment](https://discourse.jupyter.org/t/unable-to-run-jupyter-notebook-after-update-localhost/10764/8
) in an earlier discussion in jupyter.org, which might be useful to you. It looks like the workaround was uninstalling pyzmq and reinstalling an older version, but if that's not possible or does not solve your issue, maybe you could also [double check the user site packages](https://github.com/microsoft/vscode-jupyter/issues/8630#issuecomment-1013959525) to see if pyzmq is installed there? 

I can see you are running JupyterLab so while this issue has been seen in notebook, I think it would be best to move it to the jupyterlab repository so we are aware that this issue also happens there. If you could share more of your environment details like the output of ```conda list``` by pasting it here, it would be helpful.

**Comment by RRosio** [comment]
@MeeseeksDev please migrate to jupyterlab/jupyterlab

**Comment by krassowski** [comment]
@meeseeksdev please migrate to jupyterlab/jupyterlab

**Comment by RRosio** [comment]
Thanks again for submitting this issue @alibukharai! As we couldn't get the bot to move it, I've cross-posted this issue in [jupyterlab](https://github.com/jupyterlab/jupyterlab/issues/12939). I'll be closing this issue in favor of the issue in jupyterlab, please feel free to provide any additional information that would be helpful in diagnosing the error there!

**Comment by scruel** [comment]
It might be related to winsock2 unresolved issue on Windows (When you installed some VPN programs):
https://github.com/microsoft/WSL/issues/4177

You can execute NoLsp.exe with jupyter related EXE files to do the fix:
```
NoLsp.exe "C:\Users\scruelt\miniconda3\envs\py310-torch\Scripts\jupyter-notebook.exe"
NoLsp.exe "C:\Users\scruelt\miniconda3\envs\py310-torch\Scripts\jupyter.exe"
NoLsp.exe "C:\Users\scruelt\miniconda3\envs\py310-torch\python.exe"
```

**Comment by scruel** [comment]
It might be related to winsock2 unresolved issue on Windows (When you installed some VPN programs):
https://github.com/microsoft/WSL/issues/4177

You can execute NoLsp.exe with jupyter related EXE files to do the fix:
```
NoLsp.exe "C:\Users\scruel\miniconda3\envs\py310-torch\Scripts\jupyter-notebook.exe"
NoLsp.exe "C:\Users\scruel\miniconda3\envs\py310-torch\Scripts\jupyter.exe"
NoLsp.exe "C:\Users\scruel\miniconda3\envs\py310-torch\python.exe"
```
