### ISSUE TITLE
Input field for numbers only accepts one nuber at a time in Jupyter Advanced Settings

### ISSUE THREAD

**Issue by mosc9575** [jupyter/notebook#6514]
**Description**
When I try to modify the setting in the Edvanced Settings Editor using jupyterlab 3.3.0. I can only add one number at a time. After pressing any number, the settings are saved and the cursor moves to a different field.

**Expected behavior**
A expect that it is possible to add multipe numbers to an input field without activating this field multiple times.

**Screenshots**
![set_ruler](https://user-images.githubusercontent.com/68053396/185573921-bf8721c9-600f-447e-82e0-6c7679a1d3fc.gif)

**System information**
<details>
  <summary>Desktop</summary>

* Python version      :  3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
* Operating system    :  Linux-4.19.0-21-amd64-x86_64-with-glibc2.31

Selected Jupyter core packages...
* IPython          : 8.1.1
* ipykernel        : 6.9.1
* ipywidgets       : 7.6.5
* jupyter_client   : 7.1.2
* jupyter_core     : 4.9.2
* jupyter_server   : 1.13.5
* jupyterlab       : 3.3.0
* nbclient         : 0.5.12
* nbconvert        : 6.4.2
* nbformat         : 5.1.3
* notebook         : 6.4.8
* qtconsole        : not installed
* traitlets        : 5.1.1
</details>

**Comment by jweill-aws** [comment]
@meeseeksdev migrate to jupyterlab/jupyterlab

**Comment by RRosio** [comment]
Hi @mosc9575 this issue was fixed in jupyterlab with this PR: https://github.com/jupyterlab/jupyterlab/pull/12470. If you have some follow-up questions please feel free to open up jupyterlab issues in the jupyterlab repo. Thank you!
