### ISSUE TITLE
Notebook 5: Add console output to indicate end-of-life

### ISSUE THREAD

**Issue by jweill-aws** [jupyter/notebook#6524]
Notebook 5 will no longer be maintained after Notebook 7 is released. In the Notebook 5 branch, when the user launches Notebook from a terminal, add console output to urge the user to upgrade to version 6 or later.

We discussed this at the 2022-08-24 Notebook meeting.

**Comment by kostyafarber** [comment]
Hi I'd like to contribute. Any tips on where to get started with this?

**Comment by kostyafarber** [comment]
@jweill-aws

**Comment by jtpio** [comment]
@kostyafarber probably we good first step would be to start from the `5.x` branch of the repo and add a warning somewhere during the application startup:

https://github.com/jupyter/notebook/blob/5.7.x/notebook/notebookapp.py

For example with `self.log.warning()`.

**Comment by kostyafarber** [comment]
Ah okay. Thanks for the guidance, I'll work on it.

**Comment by kostyafarber** [comment]
@jtpio @jweill-aws Any suggestions on the content of the warning? I was thinking something along the lines of `Notebook version 5 is no longer being maintained. Please upgrade to version 6 or later.`

Also:
- at what point in the startup do we want this msg to appear? (I've initially put it here)

![Screen Shot 2022-10-06 at 08 22 19](https://user-images.githubusercontent.com/73378227/194243106-2fb3b44d-e370-42fb-9cca-85233789dded.png)

- once we've agreed upon the warning, will I need to do the same in every branch of a `5.x.x` and have a seperate PR for each?

Thanks.

**Comment by jtpio** [comment]
> at what point in the startup do we want this msg to appear? (I've initially put it here)

Thanks for sharing the screenshot, this looks good :+1: 

> once we've agreed upon the warning, will I need to do the same in every branch of a `5.x.x` and have a seperate PR for each?

Probably it would be fine to only target one branch. The latest `5.x` release is `5.7.15` as of today. This could go in a `5.8` final release for example.

cc @RRosio for awareness

**Comment by kostyafarber** [comment]
Thanks for the quick reply. Will work on it and submit PR.

**Comment by jweill-aws** [comment]
Fixed in v. 5.7.16. Thanks again @kostyafarber !
