### ISSUE TITLE
Next cell does not execute after an exception is thrown

### ISSUE THREAD

**Issue by bentaculum** [jupyter/notebook#6526]
**Describe the bug**

When using the pyqt gui via `%gui qt`, the cell that I execute after after an exception is thrown is not run.

**To Reproduce**

Run
```python
%gui qt
1/0
```
in a cell. 
After that, the first cell I want to run e.g. 
```python
print("Run")
```
does not execute. The second cell I run executes as normal.

**Screenshots**

<img width="1143" alt="Screen Shot 2022-08-28 at 21 21 03" src="https://user-images.githubusercontent.com/8866751/187105144-ea38b6d7-476b-4824-b2b3-be0e2fabc811.png">

**Desktop (please complete the following information):**
- OS: MacOS 12.5
- Browser Chrome
- Version 104.0.5112.101

**Comment by RRosio** [comment]
Hi @bentaculum we were able to reproduce this without the qt gui but not in the ipython terminal. Thank you for submitting this issue! Would you be able to provide a recording of the steps you take to reproduce this issue?

**Comment by bentaculum** [comment]
I confirm, this issue does not occur in the ipython terminal for me either, only in the jupyter notebook. I have used the [jupyter lab test environment](https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html) to produce this error in the jupyter notebook.

**Comment by vdrhtc** [comment]
Confirming, too, observed on multiple computers. Occurs when %matplotlib qt is loaded.

**Comment by jdranczewski** [comment]
Hi all, this should be fixed in ipykernel release 6.29.3: https://github.com/ipython/ipykernel/releases/tag/v6.29.3 with the PR https://github.com/ipython/ipykernel/pull/1212

**Comment by jtpio** [comment]
Thanks @jdranczewski for following-up, closing as fixed then!
