### ISSUE TITLE
Consider adding UI gif link from #651 to Release Note for 4.1

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#653]
The UI gif by @Carreau provides a nice overview of the user interface change. Might be helpful for end users to have the link in the release note/changes.

https://cloud.githubusercontent.com/assets/335567/10711889/59665a5a-7a3e-11e5-970f-86b89592880c.gif

**Comment by Carreau** [comment]
I'm writing a blog post on blog.jupyter.org with @jdfreder to underline the new feature. 
We can extract things from there.

**Comment by willingc** [comment]
Cool!
