### ISSUE TITLE
No mouse pointer when hovering on the Jupyter icon

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6532]
With the latest 7.0 pre-release hovering on the Jupyter icon in the top area does not show the mouse pointer:

![image](https://user-images.githubusercontent.com/591645/188081580-4759821a-c07d-45be-b3aa-069dc555c160.png)

https://user-images.githubusercontent.com/591645/188081975-b57caccb-005a-4311-b7f1-b3c4522f291b.mp4

I think it used to be, so probably a regression that happened at some point.

**Comment by dhbsbdhdhd** [comment]
Hey! I am a first time contributor.I would like this issue to be my first contribution. Can you guide me more about the issue so that I can work on it?

**Comment by MuhammadNoorani** [comment]
Is this issue open,
I would like to contribute to it, would love to collaborate and solve this issue. So, can I go ahead

**Comment by AaronB3110** [comment]
Hello! I am a beginner contributor and I would love to contribute to this issue if it has not been worked on.
I would love guidance through it and work on it.

**Comment by harsh788** [comment]
Hello there! I am new to the open source world and would like to contribute to some real-world projects. If this issue is not resolved yet, can I be assigned to it?

**Comment by jtpio** [comment]
@AaronB3110 @harsh788 @MuhammadNoorani yes the issue is still open, feel free to work on it and open a PR, thanks!

**Comment by Grimoors** [comment]
Hi! This looks like a good first issue. I am new to open source and want to try to contribute to this. May I try to work on this issue as well? (@jtpio )

**Comment by jtpio** [comment]
Sure, whoever wants to work on this please feel free to open a PR, thanks!
