### ISSUE TITLE
Bad config encountered during initialization: The 'port' trait of a NotebookApp instance expected an int, not the str '12151-12250'

### ISSUE THREAD

**Issue by schlanghorvetz** [jupyter/notebook#6534]
Please find my detailed question is here

https://stackoverflow.com/questions/73582091/bad-config-encountered-during-initialization-the-port-trait-of-a-notebookapp

Feel free to help me here or there! 

Thanks,

**Comment by RRosio** [comment]
Hi @schlanghorvetz this looks like an environment issue, maybe reaching out to the person who set the port number or trying to start a new environment. There is also `jupyter --paths` that you can check to see where other configurations may be set. It could be coming from a JUPYTER_PORT environment variable. Other people have fixed configuration issues in the comments of issue #274 as well.

**Comment by RRosio** [comment]
Hi @schlanghorvetz! Just following up on this issue, are there any updates to share?

**Comment by RRosio** [comment]
Please feel free to reopen this if new information comes up!
