### ISSUE TITLE
Invalid signature error

### ISSUE THREAD

**Issue by empet** [jupyter/notebook#6536]
Two weeks ago a reinstalled miniconda3, jupyter notebook and then Julia 1.7.3. Everything worked fine, but today, suddenly when I selected the Julia kernel  and tried to run a few cells the following error was displayed:
```    
    [E 20:59:31.643 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "C:\Users\username\miniconda3\envs\emplotly\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
        callback(*args, **kwargs)
      File "C:\Users\username\miniconda3\envs\emplotly\lib\site-packages\zmq\eventloop\zmqstream.py", line 278, in stream_callback
        return callback(self, msg)
      File "C:\Users\username\miniconda3\envs\emplotly\lib\site-packages\notebook\services\kernels\handlers.py", line 467, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "C:\Users\username\miniconda3\envs\emplotly\lib\site-packages\jupyter_client\session.py", line 1056, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: b'error'
```
![Server-info](https://user-images.githubusercontent.com/3627253/188500177-7a56e303-b831-47bf-b163-9fcb2aee86e1.PNG)
 
 Please give an advice how to fix it.

**Comment by RRosio** [comment]
Hi @empet, we are not sure if this is maybe an issue with Jupyter Notebook or the Julia kernel. If you open this notebook with JupyterLab maybe, do you have this same issue? If you could provide a code snippet of what causes this issue that would be helpful. Thank you!

**Comment by empet** [comment]
Hi @RRosio,
This was the code generating the above error:
```
using PlotlyJS, CSV, DataFrames, HTTP, Base64
df=CSV.read("data/long-medals.csv", DataFrame) #https://raw.githubusercontent.com/empet/Datasets/master/long-medals.csv
fig = Plot(df, kind="bar", x=:nation, y=:count, color=:medal, 
              Layout(barmode="stack", showlegend=false,
                     xaxis_visible=false, yaxis_visible=false,
                     bargap=0,
                     margin= attr(l= 0, r= 0, t= 0, b= 0),
                     height=100, width=100,
                     paper_bgcolor="rgba(0,0,0,0)",
                     plot_bgcolor="rgba(0,0,0,0)"
    )
)
display(fig)
savefig(fig, "stacked.png")
vecuint8 = read("stacked.png") 
bs64 = base64encode(vecuint8)
imgsource= "data:image/png;base64,"*bs64
```
It is an answer for a Julia discourse question. It was written in a single cell.
Now running it again, and moving the line:
```
using PlotlyJS, CSV, DataFrames, Base64
```
to the upper cell, it worked.

**Comment by RRosio** [comment]
Hi @empet, thank you for sharing, I'm glad you were able to solve it. I will close this issue as it seems this was not a Notebook issue. Please open another one if you have any other issues.
