### ISSUE TITLE
Mac´s window freeze using gym on Jupyter

### ISSUE THREAD

**Issue by devimprevia** [jupyter/notebook#6542]
**Describe the bug**
When using `frame = env.render(mode='rgb_array')` in Jupyter on my Mac, a window pops-up with the result (animation of Lunar Lander, for example) and then it freezes. The only way I can close it is by restarting Kernel.
This happened on a Mac where I installed different versions of gym, and by chance I happened to buy a new Mac some days ago. The first thing I did was installing Jupyter so I´d be sure it was not something that had to do with other configuration files of other programs. But the error was the same.

**To Reproduce**

1. Open a Jupyter notebook file.
2. Use `frame = env.render(mode='rgb_array')` in any gym file.
3. See the pop-up window open and then freeze.

**Expected behavior**
In any tutorial I´ve seen of people using Mac, this doesn´t happen.

**Screenshots**

**Desktop (please complete the following information):**

- Operating System and version: MacOS Monterrey, MacBookPro M1
- Browser and version: Version 105.0.5195.125

**Comment by RRosio** [comment]
Hi @devimprevia, thank you for submitting this issue. Would you please provide the version of Notebook that you are using? If you could please provide a full code cell that would reproduce this issue. If possible as well, could you try this in JupyterLab and see if you encounter this issue. It would be great if we could identify if this is a Notebook issue, a Gym issue or something else. Thank you!

**Comment by RRosio** [comment]
Hi @devimprevia, just wanted to follow-up with you and see if there are any updates that you could provide? Thanks!

**Comment by RRosio** [comment]
Hey @devimprevia, thanks again for submitting this issue! At this moment I will be closing this issue, but please feel free to reopen it if the issue persists and there is more information you'd like to provide!
