### ISSUE TITLE
Improve the About dialog

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6552]
The look of the current "About" dialog could be improved:

![image](https://user-images.githubusercontent.com/591645/193758807-639a9464-880b-4947-be4a-c9b1bc166c89.png)

As a comparison this is what the about dialog in JupyterLab looks like:

![image](https://user-images.githubusercontent.com/591645/193759193-3dd12c0f-ea9b-46c6-9f77-fece0e5bbbfc.png)

Maybe the notebook dialog could be aligned to look more like the one in JupyterLab, and also display a link to the contributor list.

**Comment by jtpio** [comment]
This is where the About dialog is created:

https://github.com/jupyter/notebook/blob/e8e0f8f32172ab834ce9005277c32ad04fadf8cd/packages/help-extension/src/index.tsx#L119-L161

**Comment by krassowski** [comment]
The Notebook v6 About dialog was even more informative:

![Screenshot from 2022-10-04 10-20-01](https://user-images.githubusercontent.com/5832902/193783359-0b3ce353-de42-4558-ab23-dade5e94ad2e.png)

In particular, showing jupyter-server version (and maybe also the Python version it is running on) might be worth considering.

I think I remember that the kernel info was a separate menu item in JupyterLab at some point but I cannot find it any more - either a regression or I am wrong and it was never implemented.

**Comment by davinderpalrehal** [comment]
Is someone working on this issue? If not I would like to have a crack at it.

**Comment by kostyafarber** [comment]
@davinderpalrehal you still working on this?

**Comment by davinderpalrehal** [comment]
@kostyafarber plans are to work on this over the weekend, is it time sensitive? If it's needed urgently I don't mind if someone else picks it up, my intention was to have the PR open by Monday.

**Comment by kostyafarber** [comment]
Oh no go ahead! Just wanted to make sure if you weren't working on it I could pick it up. Thanks.

**Comment by davinderpalrehal** [comment]
Sounds good, thanks @kostyafarber.

**Comment by davinderpalrehal** [comment]
Hey @kostyafarber , I couldn't finish setting up the repo on my laptop and get it up and running, if you are still free please proceed with picking this issue up.

**Comment by kostyafarber** [comment]
No worries @davinderpalrehal I'll try check it out

**Comment by dohrisalim** [comment]
Is this issue still open? @kostyafarber @jtpio

**Comment by kostyafarber** [comment]
If you think there are further improvements to be made and the maintainers agree, please go ahead!

**Comment by jtpio** [comment]
We could probably do a quick pass on the CSS to style the links. This is what it looks like at the moment:

![image](https://user-images.githubusercontent.com/591645/217482146-dc2d3c6d-08a4-45cb-b124-6df1382360f0.png)

**Comment by Tony-j77** [comment]
I can finish the CSS if needed. @jtpio just react or reply so I know this is still needed.

**Comment by AdityaGirdhar** [comment]
@jtpio Do you have any more improvements in mind? Maybe adding some more information like Notebook v6 had (showing jupyter-server version, and also the Python version it is running on). I've a university break starting from next week and I'd love to contribute.

**Comment by krassowski** [comment]
Of note the odd hover style seen on the screenshot in original issue is an upstream issue in JupyterLab. Contributions to solve: https://github.com/jupyterlab/jupyterlab/issues/14084 are welcome!

**Comment by Aryasarkar008** [comment]
hey is this issue still open??

**Comment by yjrab** [comment]
Is this issue still open? @jtpio
Any help needed regarding the CSS of the About dialog?

**Comment by andrii-i** [comment]
Hi @yjrab! Thank you for taking interest in fixing this issue. You are not required to ask for a permission to work on such issue, please feel free to open a pull request with proposed implementation.

**Comment by andrii-i** [comment]
Here is the css of "About" dialog in JupyterLab, can be used for reference: https://github.com/jupyterlab/jupyterlab/blob/e0b4de1eb37c9dd37c11e5319ed00cb8d37b8d92/packages/help-extension/style/base.css

**Comment by yjrab** [comment]
Thank you @andrii-i for you reply.
I will check the reference and propose something accordingly.

**Comment by Razeeeeeeeeeee** [comment]
Hey @andrii-i,
Is this issue still open?
I'd like to work on it

**Comment by sameemqureshi** [comment]
I'd like to work on this issue, is this still open?

**Comment by andrii-i** [comment]
Hi @Razeeeeeeeeeee. Please feel free to work on it and open a PR when ready.
