### ISSUE TITLE
Toolbar is often empty when opening a Notebook

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6553]
Sometimes the notebook toolbar moves most of the items in the toolbar popup, leaving only the popup opener visible.

This is one of the causes for the flaky UI tests ([example run](https://github.com/jupyter/notebook/actions/runs/3192850297)):

https://user-images.githubusercontent.com/591645/194165361-234a2c8e-f9e6-40d3-b098-0376cd87d91d.mp4

But this sometimes also happens when opening a notebook or refreshing the page:

![image](https://user-images.githubusercontent.com/591645/194166181-6b1d013c-327b-40a5-b41f-934b8e798dda.png)

There seems to be a race condition somewhere. Or the toolbar resize logic is being triggered too early in the process of loading the notebook widget and adding it to the shell.

**Comment by jtpio** [comment]
This looks like a real issue / race condition.

Part of the fix should include the removal of this workaround in the UI tests added in https://github.com/jupyter/notebook/pull/6487:

https://github.com/jupyter/notebook/blob/62c0fa84d2ea58afd5227b9c5cbc0657be243940/ui-tests/test/mobile.spec.ts#L21-L23

and:

https://github.com/jupyter/notebook/blob/62c0fa84d2ea58afd5227b9c5cbc0657be243940/ui-tests/test/mobile.spec.ts#L44-L46

**Comment by andrii-i** [comment]
I'm having a hard time reproducing this locally. Does this happens locally (often) or this is more of a testing problem? If it's the latter, should this issue be moved to 7.x and not be a blocker?

**Comment by jtpio** [comment]
Right, as noticed in https://github.com/jupyter/notebook/pull/6887#issuecomment-1581521852, the issue now seems to be more about some items being cropped rather than items missing from the toolbar:

![image](https://github.com/jupyter/notebook/assets/591645/0dbe2401-0d7e-4229-b8a9-e29d374a1cfe)


However it seems to be reproducible when testing with a mobile layout via the dev tools and refreshing the page several times:

**items are "cropped"**

![image](https://github.com/jupyter/notebook/assets/591645/7b262065-41d3-45be-a13d-ed49655f2fb6)

**expected behavior**

![image](https://github.com/jupyter/notebook/assets/591645/a3fd0391-f222-49cf-abf3-c070e4e41b2c)

**Comment by jtpio** [comment]
Given that this is not very easily reproducible (although the UI tests seem to be catching it consistently in https://github.com/jupyter/notebook/pull/6887), we can bump that one to `7.0.x` for now.

But if someone would like to work on it in the meantime please feel free.

**Comment by jtpio** [comment]
For reference I just experienced this issue when using JupyterLab 4. So maybe it's a bug in JupyterLab and we should investigate it there:

![image](https://github.com/jupyter/notebook/assets/591645/70d91400-b7b2-4b1c-9784-1745222de78a)
