### ISSUE TITLE
Align the RTC user menu dropdown in the top area

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6555]
A user menu dropdown is automatically added to the top area of the notebook when RTC is enabled:

![image](https://user-images.githubusercontent.com/591645/194317779-41ab5aff-0ead-4efe-babb-13adb876a835.png)

This menu is currently a bit off and should be aligned vertically so it's more visually pleasing.

**Comment by stephenisau** [comment]
I can take a look at this ticket over the weekend if no one's claimed it yet.
