### ISSUE TITLE
Hide the debugger button on mobile

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6556]
https://github.com/jupyter/notebook/pull/6487 added the debugger extension by default.

This shows the debugger button in the notebook toolbar:

![image](https://user-images.githubusercontent.com/591645/194328218-9512ed44-0ca1-4269-9e4e-5ddb6b39d712.png)

However on mobile it might not make sense to support debugging since the viewport is usually much smaller:

![image](https://user-images.githubusercontent.com/591645/194328575-c38968b1-5e82-49a4-b002-6bffc3b50ac1.png)

We should consider hiding the debugger button on mobile by default to at least make it more difficult to start the debugger by mistake (menu items are left untouched).

**Comment by l3atjin** [comment]
Hi @jtpio. Can I have a go at this?
