### ISSUE TITLE
Running Panel sections not accessible at browser zoom

### ISSUE THREAD

**Issue by kulsoomzahra** [jupyter/notebook#6559]
This issue was discovered during browser zoom audits.

## Context
When Kernels section is expanded, it's hard to access other sections (like Language Server and Terminal) of the Running Panel.

![Screencast-from-Saturday-08-October-2022-12_23_18-IST](https://user-images.githubusercontent.com/46336830/194634263-465f18a7-2553-4874-b749-a5798144d98c.gif)

**Expected behavior**
Our goal is to be able to reach other sections of the Running Panel like for e.g. in VS code.

[VSCode.webm](https://user-images.githubusercontent.com/46336830/194643793-c46dc69d-07aa-42f7-b244-619cff9e009a.webm)

**To Reproduce**

1. Zoom to 400%
2. Open a few notebooks
3. Click on 'Running' tab
4. Expand 'Kernels'
5. Try to reach 'Language Server' or 'Terminal'

**Desktop (please complete the following information):**

- OS: Linux (Ubuntu)
- Browser:  Chrome version 104.0.5112.101

**Comment by kulsoomzahra** [comment]
Hey! @jtpio
Are you aware of any plans to upstream the expand/collapse functionality of the Running Panel sections to JupyterLab?
 I'm asking in an attempt to resolve an [accessibility issue](https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/37) in JupyterLab. Thanks!

**Comment by jtpio** [comment]
Many thanks @kulsoomzahra for opening this issue and for the screenscasts :+1: 

> Are you aware of any plans to upstream the expand/collapse functionality of the Running Panel sections to JupyterLab?

The Running Panel section in Notebook 7 is the same as the one JupyterLab. It was recently updated in https://github.com/jupyterlab/jupyterlab/pull/13074, and Notebook 7 just reuses it as is.

So any fix to this component should be implemented upstream in JupyterLab. Which can then be pulled in Notebook 7 next time the JupyterLab dependency is updated.

**Comment by kulsoomzahra** [comment]
@jtpio That's great, thanks!

**Comment by kulsoomzahra** [comment]
**Update-1**
Something that I tried doing:

1. Identify the **.lm-AccordionPanel** and put a scroll to it.
2. Modified `min-height:auto` which helps to scroll the entire length of the **.lm-AccordionPanel**.
(Previously it was 328px)


Current scenario:

[Scroll.webm](https://user-images.githubusercontent.com/46336830/195037428-5a738a81-ba92-4293-a1a0-922818fb9b22.webm)

**Comment by jtpio** [comment]
Thanks @kulsoomzahra! Feel free to open a PR (even as a draft) in JupyterLab if you would like to suggest these fixes :+1:

**Comment by kulsoomzahra** [comment]
I've opened a PR in https://github.com/jupyterlab/jupyterlab/pull/13241, @jtpio thanks for following up! :)
