### ISSUE TITLE
Jupyter Notebook is getting stuck after upgrading to WIN11

### ISSUE THREAD

**Issue by LinyiGuo96** [jupyter/notebook#6560]
Hi Jupyter Notebook Support Team,

I found my jupyter is getting stuck while inputting recently, while the run time is still very quick.

The main changes of my environment include:

- Win10 to Win11
- Reinstall the Anaconda, as welll as Jupyter Notebook

![image](https://user-images.githubusercontent.com/51500878/194716510-c2f9358d-5fc4-42ae-8a5d-d018f37bc934.png)

I tried the suggestions online but this issue is still there. Any advise? Much appreciated!

**Comment by RRosio** [comment]
Hi @LinyiGuo96 thank you for submitting this issue! Are there any errors that you are able to see in the terminal when encountering this issue? What are you trying to input when you see this issue? If you could post a recording demonstrating the issue you are experiencing or provide the terminal output it would be helpful in diagnosing what may be going on!

**Comment by LinyiGuo96** [comment]
@RRosio Hi, I didn't see any errors in the terminal/jupyter notebook. The issue is only about the latency of my input.

And my work is mainly about some data management work (using pandas and numpy). 

Usually the input speed at the beginning is fine, but after a few time it will get slow and delayed. 

Not sure whether this is about my environment set-up, or some optimization problem, is there any way to check it?

**Comment by RRosio** [comment]
Hi @LinyiGuo96, thank you for your response! It is not clear yet if this is a Jupyter Notebook issue or related to environment issues. If you try running your notebook in other like Papermil or IPython, do you see the same behavior? Also, if you could open up your task manager, do you see the the Jupyter process is using up a lot of your system's RAM?

**Comment by RRosio** [comment]
Hi @LinyiGuo96 I just wanted to follow up and see if this is still an issue you are encountering and/or if there is any additional information?

**Comment by LinyiGuo96** [comment]
Hi @RRosio My Jupyter Notebook is still slow while I am inputting, but now I am moving to use other tools for python programming, thanks for your help!
