### ISSUE TITLE
Missing syntax highlighting for the JSON viewer

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6567]
As noticed in https://github.com/jupyter/notebook/pull/6566#issuecomment-1276424208, syntax highlighting is missing when opening JSON files with the JSON viewer:

![image](https://user-images.githubusercontent.com/591645/195393192-31be07e6-f30f-4a1b-ac7f-1865d018c2a0.png)

**Comment by kostyafarber** [comment]
This looks interesting. Any ideas on where to get started with this?

**Comment by jtpio** [comment]
Thanks @kostyafarber for looking into this.

Right I guess the first step would be to check if the styles are correctly added to the page, as there could be one missing in notebook compared to lab (haven't looked more into it since)

**Comment by kostyafarber** [comment]
Can't seem to isolate why notebook is not applying the styles. I can see in JupyterLab style tags are produced with these `ͼr` styles  in `head` but in notebook they are missing. 

I can't find any reference to these in the code anywhere. They look like they are to do with `CodeMirror` but don't know how they are produced by it.

<img width="1512" alt="Screenshot 2022-11-18 at 22 03 19" src="https://user-images.githubusercontent.com/73378227/202811123-ceeb8dff-afc6-410f-96bb-e2c04d01ca0d.png">

**Comment by fcollonval** [comment]
@kostyafarber for CodeMirror 6, the theme uses CSS in JS (see [documentation](https://codemirror.net/examples/styling/#themes)). That way is usually combined with auto-generated class name (as you are seeing). But they are never mentioned explicitly in the code (as they should never be used and can change without notice).

So if in notebook you can see the style applied have colored defined like `var(--jp-mirror-editor-keyword-color)`. This means the JupyterLab CodeMirror theme is correctly applied by the JSON viewer. But those CSS properties are not define on the page - they should come from the theme package:

https://github.com/jupyterlab/jupyterlab/blob/9ee65ca27712b19cb8a7a2f4e99453ef1439a525/packages/theme-light-extension/style/variables.css#L335

**Comment by kostyafarber** [comment]
@fcollonval okay, I can see these styles in the debug console on notebook.

![image](https://user-images.githubusercontent.com/73378227/203095470-d191bc64-d7dc-4418-b238-6485392c8fa1.png)

I can even see the `ͼ12` styles attached to the spans in the JSON (which are the styles that have colours applied to them in Lab), but there are no styles defined on them in notebook.

It looks like these styles are being extracted by this function here:

https://github.com/jupyterlab/jupyterlab/blob/3dadf14e4411c3af143f97d055b3309901216ad7/packages/json-extension/src/component.tsx#L37-L39

And being called here for example:

https://github.com/jupyterlab/jupyterlab/blob/3dadf14e4411c3af143f97d055b3309901216ad7/packages/json-extension/src/component.tsx#L82-L84

But these styles aren't being produced on notebook. Not sure how to map that to a missing css import on the page. Is there meant to be an extra css file defined somewhere here to enable this function to work properly in notebook?

https://github.com/jupyter/notebook/blob/main/packages/application/style/index.css

**Comment by fcollonval** [comment]
Ok I think I get what is happening - the CodeMirror theme rules are not added to the page because there are no CodeMirror editor.

**Comment by fcollonval** [comment]
What we should do is add the CodeMirror rules on the page for the JSON Renderer.

https://github.com/jupyterlab/jupyterlab/blob/42992295a40e030d7875ab063aa8ebb1ada3ca74/packages/json-extension/src/component.tsx#L38

You can do that by adding manually the style using [`style-mod`](https://github.com/marijnh/style-mod):

```ts
StyleModule.mount(document, jupyterHighlightStyle.module)
```

**Comment by fcollonval** [comment]
`StyleModule` is designed to add a style sheet only once. So I would suggest fixing it upstream.

**Comment by kostyafarber** [comment]
Sorry if this is a silly question, but what do you mean by fixing it upstream?

**Comment by fcollonval** [comment]
Sorry fixing it in JupyterLab itself

**Comment by kostyafarber** [comment]
All good! Thanks for the help 😄

**Comment by fcollonval** [comment]
We usually refer JupyterLab as the upstream of notebook as notebook v7 is a remix of JupyterLab plugins.

**Comment by kostyafarber** [comment]
Ah okay. Thanks for that. Good to know the lingo
