### ISSUE TITLE
Jupyter Notebook 6.5.0 is broken - Upgrade to 6.5.1

### ISSUE THREAD

**Issue by echarles** [jupyter/notebook#6572]
Jupyter Notebook 6.5.0 release is broken, please upgrade to 6.5.1.

**Comment by jtpio** [comment]
How about yanking it on PyPI?

![image](https://user-images.githubusercontent.com/591645/195664781-a3ec7cf4-f70e-4bc4-b521-2129c4d7f87c.png)

**Comment by echarles** [comment]
We could yank `notebook 6.5.0` or `nbclassic 0.4.6` (nbclassic 0.4.6 generates the issue, notebook 6.5.1 pins to nbclassic 0.4.6).

I had a quick discussion with @Zsailer and it looks like Jupyter typically does not yank. In this case, we could have an exception. WDYT?
 (cc/ @blink1073)

**Comment by echarles** [comment]
(corrected above:  notebook 6.5.1 pins to nbclassic 0.4.5 (not 0.4.6).

**Comment by blink1073** [comment]
I've definitely yanked when needed before, if a particular version is broke

**Comment by echarles** [comment]
I don't have karma to yank in pypi notebook.

Can someone yank notebook `6.5.0` for me, or give me the credentials to do it? Thx.

**Comment by jtpio** [comment]
Done

**Comment by echarles** [comment]
Thx @jtpio Could you please pin this issue to the issue board so users can find it more easily.

**Comment by jtpio** [comment]
Just pinned, although the yank should already help in most cases.

Closing as fixed. You might also want to edit the GitHub Release to mention it is broken: https://github.com/jupyter/notebook/releases/tag/v6.5.0

**Comment by echarles** [comment]
Thx, I have updated the release notes.

<img width="927" alt="Screenshot 2022-10-14 at 09 31 59" src="https://user-images.githubusercontent.com/226720/195788813-a46a5d17-c2f7-499a-801a-bcd8677c9688.png">
