### ISSUE TITLE
6.5.1 regression: NotebookApp] Could not open static file '' jquery-ui

### ISSUE THREAD

**Issue by willgleich** [jupyter/notebook#6573]
Relevant jupyter server logs:
> NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css
> NotebookApp] 404 GET /static/components/jquery-ui/jquery-ui.min.js?v=20221013190655

Looks like notebook 6.5.1 has a regression with `jupyter_contrib_nbextensions`

The nbextensions tab is missing from the notebook homepage.

I was able to work around this with downgrading notebook
`pip install jupyter notebook=6.4.12`

Relevant js console errors:
>Refused to apply style from 'http://localhost:8888/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Versions:

python 3.7.13
IPython          : 7.34.0
ipykernel        : 6.16.0
ipywidgets       : 8.0.2
jupyter_client   : 7.4.2
jupyter_core     : 4.11.1
jupyter_server   : 1.21.0
jupyterlab       : not installed
nbclient         : 0.7.0
nbconvert        : 7.2.1
nbformat         : 5.7.0
notebook         : 6.5.1
qtconsole        : 5.3.2
traitlets        : 5.4.0

**Comment by echarles** [comment]
Thx for the report.

> NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css

We have seen that issue and will fix it ASAP, but I don't think it is related to the `jupyter_contrib_nbextensions` not working;

> Looks like notebook 6.5.1 has a regression with jupyter_contrib_nbextensions

We have an open PR in https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/141 to fix that. @damianavila can maybe give more inputs on when this could be reviewed and released.

**Comment by RRosio** [comment]
I wanted to provide an update on the fix for the jquery-ui 404 error, PR #6578 has been merged!

**Comment by KC0lin** [comment]
been half-day with the exact same problem and errors. *install jupyter notebook=6.4.12* this has worked for me

**Comment by echarles** [comment]
For the jquery-ui 404, Notebook 6.5.2 is released and does not show the jquery-ui 404 anymore. 

For jupyter_nbextensions_configurator, https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/141 is waiting for reviews from the core maintainers. Please upvote that PR in the jupyter-contrib repository if you want to get this move forward.

I will close this issue related to the jquery-ui (please reopen if it does not work for you).
