### ISSUE TITLE
jquery-ui 404

### ISSUE THREAD

**Issue by echarles** [jupyter/notebook#6576]
The following is shown in the server log. It does not impact the notebook behaviour, but we need to fix it as this is confusing for the user.

```
[W 08:11:42.605 NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css (::1) 11.530000ms referer=http://localhost:8888/tree?token=abe46dae2ea736aced4c0fe0580c8731ac9691b62f20fd68
[W 08:11:48.089 NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css (::1) 1.450000ms referer=http://localhost:8888/tree
[W 08:11:50.765 NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css (::1) 2.790000ms referer=http://localhost:8888/tree
````

Was that introduced by https://github.com/jupyter/nbclassic/pull/152 ?

cc/ @RRosio @ericsnekbytes

**Comment by RRosio** [comment]
Yes, I believe that was the PR that introduced this issue. I think the issue with these packages could be that I may have had two different jquery-ui package sources in my bower cache which may have resulted in either package being installed from the cache. They have different file structure so there is a bad path to the jquery-ui files if one of the packages is installed.

**Comment by Alowree** [comment]
> 

It does impact the notebook behavior a little bit since the nbextension menu does not how up. It appears to me that neither the css file nor the js file has been properly installed. Still struggling for a fix. 

<img width="864" alt="image" src="https://user-images.githubusercontent.com/57390638/198826648-45ceb0cb-8cfe-43ae-8210-5d51257d8094.png">

**Comment by echarles** [comment]
Notebook 6.5.2 is released and does not show the jquery-ui 404 anymore. Closing (please reopen if it does not work for you).
