### ISSUE TITLE
OpenSCAD kernel

### ISSUE THREAD

**Issue by pidpawel** [jupyter/notebook#659]
I think that [OpenSCAD](http://www.openscad.org/) integration would be great in some applications. I'm leaving this "issue" just as an enhancement proposal. You're doing an awesome job ;-)

**Comment by jdfreder** [comment]
Hi @pidpawel , thanks for the feedback.  The Jupyter org doesn't actually maintain any kernels.  That said, most of the devs in the Jupyter org are also members of the IPython org, which is where we maintain the Python kernel.  We encourage our users to write their own kernels by having a well documented API and providing a simple wrapper kernel base class.

**Comment by Carreau** [comment]
You can find a list of already available kernels here: https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages. If  OpenSCAD implement the protocol it should just work out of the box without us having to do anything.  Thanks !
