### ISSUE TITLE
Training deep learning model in Jupyterlab desktop

### ISSUE THREAD

**Issue by ddharshan** [jupyter/notebook#6610]
Hi,
I am trying to train my Deep reinforcement learning based model using jupyterlab desktop. When the training passes 9hrs, the desktop app frozen and the model is not training.(I checked
the task manager as well). Is this because of memory limitation, Do i have to change any settings?

**Comment by RRosio** [comment]
Hi @ddharshan, thank you for submitting this issue. As this is an existing issue happening with jupyterlab, I will go ahead and close this issue here.

Jupyterlab Issues
https://github.com/jupyterlab/jupyterlab-desktop/issues/504
