### ISSUE TITLE
Tooltip for signature and docstring appears at wrong vertical position

### ISSUE THREAD

**Issue by stanwest** [jupyter/notebook#6611]
In versions 6.5.1 and 6.5.2 of *notebook*, but not in v. 6.4.12, the tooltip that displays the current object's signature and docstring when one hits Shift + Tab appears at the wrong height within the browser window. As far as I've seen, the tooltip appears too low when the view is scrolled near the top of the notebook and too high when near the bottom. The screen-shots below illustrate the behavior.

![low](https://user-images.githubusercontent.com/38358698/199740866-881e97e7-a2c7-4161-8031-3986705e4082.png)

![high](https://user-images.githubusercontent.com/38358698/199740882-944dc5e5-0be5-4747-9c62-060b06b9294b.png)

For a long enough notebook scrolled down somewhat, the tooltip may have so high a position that it is outside the window, giving the impression that the notebook is ignoring Shift + Tab (at least until the fourth press raises the pager).

**Comment by RRosio** [comment]
Hi @stanwest thank you for submitting this issue! As we are not able to reproduce this issue on our end, would it be possible to provide a screen recording to demonstrate the steps to reproduce this issue? Would you also be able to try to reproduce this issue with with no extensions enabled? Also, if you could paste the output from your browser Javascript console here, you can see https://webmasters.stackexchange.com/a/77337 for how to access the JavaScript console.

**Comment by stanwest** [comment]
Thank you for the suggestion to disable extensions. That led me to associate the behavior with the Collapsible Headings extension, and I've opened an issue (ipython-contrib/jupyter_contrib_nbextensions#1611) in its repository. Sorry for the spurious report.
