### ISSUE TITLE
ImportError: cannot import name 'default_gui_banner' from 'IPython.core.usage'

### ISSUE THREAD

**Issue by Benr027** [jupyter/notebook#6614]
Hi
I am not able to launch notebook.
I am using `PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.1"
VERSION_ID="2022.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"`

I have installed Anaconda and then launch Jupyter Notebook .I am trying to upload  my notebook but I am not getting the ouput.

I am attaching some images please find out.
[](https://user-images.githubusercontent.com/49396146/68005227-5c93e100-fc96-11e9-942d-9f3dbf1f1564.JPG)

And i get this error after typing this command `jupyter notebook`

`[I 01:42:46.714 NotebookApp] KernelRestarter: restarting kernel (5/5), new random ports
Traceback (most recent call last):
  File "/home/deep/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/deep/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/deep/anaconda3/lib/python3.9/site-packages/ipykernel/__main__.py", line 2, in <module>
    from ipykernel import kernelapp as app
  File "/home/deep/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 37, in <module>
    from .ipkernel import IPythonKernel
  File "/home/deep/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 15, in <module>
    from .zmqshell import ZMQInteractiveShell
  File "/home/deep/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 35, in <module>
    from IPython.core.usage import default_gui_banner
ImportError: cannot import name 'default_gui_banner' from 'IPython.core.usage' (/home/deep/anaconda3/lib/python3.9/site-packages/IPython/core/usage.py)
[W 01:42:49.734 NotebookApp] KernelRestarter: restart failed
[W 01:42:49.734 NotebookApp] Kernel 2ee2dd0a-581f-4651-a571-881f07711448 died, removing from map.
`

Thanks for your help.

**Comment by RRosio** [comment]
Hi @Benr027, thank you for opening this issue. There is a similar issue that was previously submitted  https://github.com/jupyter/notebook/issues/4375#issuecomment-471511903 and the recommendation is to try updating ipython and/or conda. Could you give this a try and see if this resolves your issue? If not, you can feel free to reopen this issue and post more information about your environment like the version of notebook you are using with `jupyter --version`?

**Comment by Benr027** [comment]
> Hi @Benr027, thank you for opening this issue. There is a similar issue that was previously submitted [#4375 (comment)](https://github.com/jupyter/notebook/issues/4375#issuecomment-471511903) and the recommendation is to try updating ipython and/or conda. Could you give this a try and see if this resolves your issue? If not, you can feel free to reopen this issue and post more information about your environment like the version of notebook you are using with `jupyter --version`?

Thanks, it worked when I did the update.
