### ISSUE TITLE
Regarding popup

### ISSUE THREAD

**Issue by ShubhamSongire** [jupyter/notebook#6619]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/68246393/201730707-25dce112-ce1c-4569-a9cd-b911a0ae23f0.png">

Hello Team Jupyter,
   From the last few days this popup was coming whenever I close the command prompt before closing all ipynb files, this is not stopping until I stut down my PC. please fix this error. I am using windows 11.

**Comment by RRosio** [comment]
Hi @ShubhamSongire thank you for submitting this issue. Do you see this issue when you run Python scripts or only when you use Jupyter Notebook? Also if you could please provide the version of Python and Jupyter Notebook you are using? How did you install jupyter Notebook in this case? Could you try uninstalling Jupyter Notebook and re-installing it?

**Comment by ShubhamSongire** [comment]
Sir problem solved, I tried to update my jupyter notebook version at that
time warning has came that your jupyter notebook is installed in path which
is not in environment, do add it. I have added that path into system
environment path and error solved,
thank you for your kind reply 🙏



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
11/21/22,
12:59:13 AM
