### ISSUE TITLE
Document 4.1 new features

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#662]
See https://github.com/jupyter/notebook/issues/653 we added things in what's new. 

We should actually have longer descriptions.

**Comment by parente** [comment]
I can help out here if someone can point me to where the doc to edit lives. Are we talking about just extending the changelog descriptions or the doc site or something else?

**Comment by Carreau** [comment]
Docs are in the [docs folder](https://github.com/jupyter/notebook/tree/master/docs/source), auto published [there](http://jupyter-notebook.readthedocs.org/en/latest/) once merged in master. 

I think Min already did a bit of work [there](https://github.com/jupyter/notebook/pull/786).

Thanks !

(also tell us which incompatibility you have with 4.1)

**Comment by minrk** [comment]
I got everything I could think of in #786, but if anyone has other things I missed, by all means PR away!

**Comment by Carreau** [comment]
We can likely have section for each of these things that describe in more details how to use them (like shortcut and position in the menu, icon in toolbar..)

**Comment by Carreau** [comment]
Advertise the tool for generating certificate and password.

**Comment by parente** [comment]
Still planning to take a crack at this tonight or tomorrow when I have time. (But don't let me hold anything up if you're looking to get it done sooner!)

**Comment by Carreau** [comment]
> Still planning to take a crack at this tonight or tomorrow when I have time. (But don't let me hold anything up if you're looking to get it done sooner!)

Don't worry we can document during beta phase so we have 2 weeks :-)

**Comment by willingc** [comment]
Perhaps this should be a new documentation issue or part of a blog post on 4.1. The GIF here demonstrates copy and pasting a cell using the new command pallette. At the end, a cell is deleted using command DD (though the GIF doesn't reflect this well - a brief screencast with audio would be better. It could be helpful as folks go through the beta period to make small GIFs of some of these items. Perhaps adding a GIFs folder to the docs source or more simply a GIF issue where folks could place their GIFs. FWIW, the GIF helped more than text or a static image to see what was going on with the new feature.

![command_pallette_sample](https://cloud.githubusercontent.com/assets/2680980/11761827/c7249ffc-a086-11e5-81f9-81f193220be3.gif)

**Comment by Carreau** [comment]
> or part of a blog post on 4.1

The blog post is already written and has (some) gifs. 
I don't want to mix documentation and blog post, as documentation is self contained, and will likely be rebuilded shipped on linux distro like debian. 

When I think of docs, think that you'r on mars, and it take 16min (at least) to do a roundtrip to earth. So I would prefer not to refer to a blog post for this kind of things. 

Thoug I

> Perhaps adding a GIFs folder to the docs source or more simply a GIF issue where folks could place their GIFs

The issue with doing that while developing (beta should be fine though) is that the UI change; for the blog post I had to re-record the gif 3 times.

**Comment by willingc** [comment]
@carreau Thanks for the feedback. I'll open a separate issue about documentation and helping users understand the user interface.

**Comment by parente** [comment]
I added a bit more detail about how to trigger the major new UI features to the changelog. I also went through all the PRs and issues closed for 4.1 and picked out a few that seemed worthy of changelog mention (IMHO). For all the rest, I included links to the full lists of milestone 4.1 PRs and issues on GitHub for folks that want that level of detail.

**Comment by minrk** [comment]
closed by #871. Thanks @parente!
