### ISSUE TITLE
Icons not visible with the `jupyterlab-night` theme

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6633]
Opening the issue in this repo since they used to be visible before if I recall correctly.

Trying the latest 7.0.0a9 pre-release on Binder with the `jupyterlab-night` theme (https://github.com/martinRenou/jupyterlab-night), the icons in the menu are not clearly visible:

![image](https://user-images.githubusercontent.com/591645/203157767-fc3e12ad-0f79-4006-b738-996cac32a470.png)

It might be related to a change in the latest JupyterLab 4.0 pre-releases.

**Comment by jtpio** [comment]
This is an upstream issue: https://github.com/jupyterlab/jupyterlab/issues/13461

Leaving open until we update to a new release that fixes.

**Comment by HaudinFlorence** [comment]
In PR #13279, new css variables have been introduced in file variable.css both in ligth and dark themes and used in the relevant files. The goal is to define colors that are independant of other css variables like `--jp-warn-colori`.
```
/* File or activity icons and switch semantic variables */
  --jp-jupyter-icon-color: var(--md-orange-900);
  --jp-notebook-icon-color: var(--md-orange-700);
  --jp-json-icon-color: var(--md-orange-700);
  --jp-console-icon-background-color: var(--md-blue-700);
  --jp-console-icon-color: white;
  --jp-terminal-icon-background-color: var(--md-grey-800);
  --jp-terminal-icon-color: var(--md-grey-200);
  --jp-text-editor-icon-color: var(--md-grey-700);
  --jp-inspector-icon-color: var(--md-grey-700);
  --jp-switch-color: var(--md-grey-400);
  --jp-switch-true-position-color: var(--md-orange-700);
  --jp-switch-cursor-color: rgba(255, 255, 255, 1);
```

I guess that for custom themes these variables should also be present in the variable.css file to properly render the icons.
