### ISSUE TITLE
Jupyter notebook does not run - Please HELP

### ISSUE THREAD

**Issue by ohabam** [jupyter/notebook#6645]
So I tried a couple of things, like downgrading tornado to 5.1.1 and the uninstalling anaconda and reinstalling it again, but nothing works. The error I get in jupyter notebook is "A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration." I tried to upgrade pip and then upgrading tornado to 6.0.4, here is the terminal output:

pip install --upgrade pip
Requirement already satisfied: pip in /opt/anaconda3/lib/python3.9/site-packages (22.2.2)
Collecting pip
  Downloading pip-22.3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 5.4 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
Successfully installed pip-22.3.1
(base) elisha-fred@elishafredsMBP ~ % pip install --upgrade tornado==6.0.4
Collecting tornado==6.0.4
  Downloading tornado-6.0.4.tar.gz (496 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 496.2/496.2 kB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tornado
  Building wheel for tornado (setup.py) ... done
  Created wheel for tornado: filename=tornado-6.0.4-cp39-cp39-macosx_10_9_x86_64.whl size=416984 sha256=211f00de97db3810313256b1b0e8ac85f4660728fdf73d56ecde3df61207bb5b
  Stored in directory: /Users/elisha-fred/Library/Caches/pip/wheels/6f/77/43/3a50c44e98323ecd4817dbb0f8e6ba4ba09b62518ca869abbb
Successfully built tornado
Installing collected packages: tornado
  Attempting uninstall: tornado
    Found existing installation: tornado 5.1.1
    Uninstalling tornado-5.1.1:
ERROR: Could not install packages due to an OSError: Cannot move the non-empty directory '/opt/anaconda3/lib/python3.9/site-packages/tornado-5.1.1.dist-info/': Lacking write permission to '/opt/anaconda3/lib/python3.9/site-packages/tornado-5.1.1.dist-info/'.

Would you have ideas how to fix this? I could not make jupyter notebook work.

Cheers

**Comment by RRosio** [comment]
Hi @ohabam, thank you for submitting this issue! Could please provide the version Jupyter Notebook you are using? What is the output that you get in the command window where you ran `jupyter notebook`, is there any error message from the server?

**Comment by RRosio** [comment]
Hi @ohabam, to follow up with you on this issue, is this still a problem that you are experiencing? If so, the additional information mentioned above would be helpful to have so that we can try find out what may be going on.

**Comment by RRosio** [comment]
Hi @ohabam, we'll be closing this issue as we haven't received any updates. If you have updates please feel free to reopen this issue. Thank you!
