### ISSUE TITLE
Is it possible to recover jupyter notebook being deleted with a no permission error?

### ISSUE THREAD

**Issue by HelloWorldLTY** [jupyter/notebook#6654]
Hi all, I mistakely deleted my jupyter notebook, and I tried to look up it in the trash file. However, I met this error:
[Errno 13] Permission denied: b'/gpfs/gibbs/.Trash-19130'
Even if facing this error, jupyter still deleted this file.

I wonder if there are still methods or not to recover this notebook.

I tired to use the cache innner the browser, but the cache is not modified today and all content is wrong codes. Thanks.

**Comment by RRosio** [comment]
Hi @HelloWorldLTY, thank you for submitting this issue. Generally you can look for a folder called `.ipynb_checkpoints` to look for older versions of your notebooks and recover them this way. If this doesn't work for you, you might have to rely on any backups you have saved.
