### ISSUE TITLE
XSRF cookie does not match POST argument 403 forbidden 

### ISSUE THREAD

**Issue by spattanaik0** [jupyter/notebook#6657]
I want to embed jupyter into a webpage, I run the image of jupyter on a docker,ki cluster.

The embedded jupyter on the webpage prompts "XSRF cookie does not match POST argument", but I can normally access jupyter from localhost:8888 and the endpoint
@everyoneI have tried many things, nothing seems to work
![Uploading PXL_20221206_181945600.jpg…]()
![PXL_20221206_181945600](https://user-images.githubusercontent.com/15346646/206007729-67b67824-3311-4bb0-9699-1412d58b3fe1.jpg)

Please suggest what can I add to config file

**Comment by RRosio** [comment]
Hi @spattanaik0, thank you for submitting this issue. This has been discussed at length in the Jupyter Community Forum, for example, [here](https://discourse.jupyter.org/t/jupyterhub-integration-in-web-application/16590). You might receive more feedback on this issue there. Here is the [documentation](https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#content-security-policy-csp).

There is an alternative that you might also consider, [Jupyterlite](https://github.com/jupyterlite).
