### ISSUE TITLE
Now I face the problem of dead kernel in jupyter notebook when I reach 43-epoch because there is 50-epoch in my code. It took two nights to reach 43-epoch by using two GPUs. I run it two times but it didn't work. I want to get the last epoch. Please advise me what I need to do.

### ISSUE THREAD

**Issue by aishashema** [jupyter/notebook#6666]
Now I face the problem of dead kernel in jupyter notebook when I reach 43-epoch because there is 50-epoch in my code. It took two nights to reach 43-epoch by using two GPUs. I run it two times but it didn't work. I want to get the last epoch. Please advise me what I need to do.

_Originally posted by @may-phyu in https://github.com/jupyter/notebook/issues/1892#issuecomment-585544033_
      @may-phyu i have same issue please did find a solution .Mine is after running one Ephoc

**Comment by RRosio** [comment]
Hi @aishashema thank you for submitting this issue. Would you please provide the log of output from when the kernel dies? If you are running jupyter-server, you can try using the [resource usage extension](https://github.com/jupyter-server/jupyter-resource-usage) to monitor your memory usage (thanks @krassowski).

**Comment by RRosio** [comment]
Hi @aishashema, just following up with you on this issue, is this problem still occurring? If you could share the log output as mentioned above it would also be helpful.

**Comment by RRosio** [comment]
Hi @aishashema, we'll be closing this issue as we haven't received any updates. However if you have updates you are welcome to reopen this issue. Thank you!
