### ISSUE TITLE
Find and go-to text

### ISSUE THREAD

**Issue by luismi98** [jupyter/notebook#6685]
The `F` command in `Edit` mode which allows you to _Find and Replace_ across all cells is useful. However, it would be a lot more useful if it allowed you to _Go_ to each of those occurrences of the text you are looking for.

This would be particularly useful for users like me that work with large notebooks and love the _Collapsible Headings_ or _Codefolding_ extensions from the [jupyter_contrib_nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html), since they hide code and hence do not enable us to just use the `Crtl+F` browser command to travel across the notebook.

I believe this would really make a difference to the productivity of anyone that works with those extensions in large notebooks, and hence why I am writing this issue.

**Comment by jtpio** [comment]
Closing as implemented and available in Notebook 7.

As mentioned in the comment above the Notebook 7 beta can be installed with `pip install --pre notebook`. The final release is expected in the coming weeks.
