### ISSUE TITLE
Find text only searches part of file

### ISSUE THREAD

**Issue by PAGWatson** [jupyter/notebook#6697]
If I open a long .py file in Notebook 7.0.0a10 and try to search for text with Ctrl+F, text only seems to be found if it appears within the portion of the file being viewed on screen, and it says there are zero instances otherwise. If I try it in jupyterlab (4.0.0a32), the text is found as long as it exists somewhere in the file, so this seems to be an issue specific to Notebook. It would be desirable to be able to search the whole of python scripts, text files etc.

**Comment by PAGWatson** [comment]
Sure. As an example, one of my scripts has a function "get_color_cycle", and if I search for this in the searchbar brought up by Ctrl+F when viewing the top of the file, then it returns zero results:

![image](https://user-images.githubusercontent.com/6704648/212890690-e4ca8bc6-3739-459c-bddb-089967224c4a.png)

If I scroll down to show the function in the browser window and search again, the text is found:

![image](https://user-images.githubusercontent.com/6704648/212890989-4849ac51-dcca-4a41-8e0f-8a8d727722c7.png)

My guess was that the notebook is only loading the file contents near the location that is being viewed or something? For small text files and scripts, I'd guess it's generally better to load the whole thing.

**Comment by jtpio** [comment]
Ah interesting thanks for sharing the screenshots.

> If I try it in jupyterlab (4.0.0a32), the text is found as long as it exists somewhere in the file

In JupyterLab, does the Ctrl-F trigger the browser search popup like in Notebook 7? Or the JupyterLab search / replace tool?

**Comment by Higgs32584** [comment]
So I looked over this bug to see if I could replicate it. I was able to replicate it, but the functionality is more nuanced. So the HTML search bar does not pick up on the text in the python file, but the localized search bar does. I guess it is a matter of if we want the HTML search bar to pick up on the python code. 



![case#3](https://user-images.githubusercontent.com/55243596/222810705-49b24399-dbf5-4eae-a44c-6963e870d048.png)
on built into the application, where
![screenshot#2](https://user-images.githubusercontent.com/55243596/222810725-42899810-5a82-4afe-bd77-5efa62830d43.png)

**Comment by fcollonval** [comment]
Small comment: the browser search will always fail as the text editor (i.e. codemirror 6) is only rendering the text content that fits in the viewport.

There are two solutions:
- most desirable: use the jupyter search (as implemented in JupyterLab)
- less desirable: use the codemirror 6 search extension

**Comment by jtpio** [comment]
This is still an issue in the latest `main`, but using the built-in `Find` should work:

https://github.com/jupyter/notebook/assets/591645/72474ef4-f759-4b91-8a1c-ec01beddaf30

The `Ctrl-F` keybinding was disabled by default on purpose in https://github.com/jupyterlab/retrolab/pull/294, because searching on a page this way is so common.

But now that the rendering of the notebook has changed in JupyterLab (and in Notebook 7), maybe `Ctrl-F` should trigger the JupyterLab search / replace popup instead of the browser one to make sure we can find the content on the whole page and in the editors? This should be matter of removing the override here (or the whole file):

https://github.com/jupyter/notebook/blob/044089dc98dc72d205a587599653cae4bea68871/packages/documentsearch-extension/schema/notebookShellWidgetListener.json#L5-L10

**Comment by jtpio** [comment]
> maybe `Ctrl-F` should trigger the JupyterLab search / replace popup instead of the browser one to make sure we can find the content on the whole page and in the editors? This should be matter of removing the override here (or the whole file):

In that case the new default would be to open the JupyterLab search box when hitting `Ctrl-F`. But we could also document how to disabled the keybinding to `Ctrl-F` would use the browser search bar like now. Just to make it configurable by end users.

**Comment by ericsnekbytes** [comment]
I'm looking at this now and have reproduced the issue and did some basic testing on the proposed solution. I have opened a [PR](https://github.com/jupyter/notebook/pull/6905) with that change suggested above by @jtpio. I'm also planning to investigate the documentation changes needed for this.

**Comment by ericsnekbytes** [comment]
@jtpio How would a user disable the shortcut? In the keyboard shortcuts menu in the settings editor, I see a way to view and add shortcuts, but can they be disabled? I didn't see an option for that with this document search shortcut (was able to see the shortcut for document search but when selecting and deleting the keys, it just goes back to its previous value)...

**Comment by jtpio** [comment]
Right I'm not sure it's possible to disable the shortcut via the Settings Editor UI.

However it should be possible with the Advanced Settings Editor by adding `"disabled": true`:

https://github.com/jupyter/notebook/assets/591645/fc9c33a0-a71e-40fa-bcec-9682f7753fd3

**Comment by ericsnekbytes** [comment]
@jtpio Thanks, I'm gonna work up documentation for this to include in the PR.
