### ISSUE TITLE
Jupyter notebook gets stuck

### ISSUE THREAD

**Issue by metatl** [jupyter/notebook#670]
I'm on Mac 10.8.*, python 4.0, python 2.7, jupyter 4.0.6

Here's the log. Then everything will hang there with infinite time. A jupyter window does appear in the browser but in the 'running' tab, it says nothing is running. 

**anyone knows what's causing this ** thanks!

>[D 14:42:29.438 NotebookApp] Config changed:
[D 14:42:29.438 NotebookApp] {'NotebookApp': {'log_level': 10}}
[D 14:42:29.439 NotebookApp] Searching [u'/Users/foouser', '/Users/foouser/.jupyter', '/Users/foouser/anaconda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 14:42:29.439 NotebookApp] Attempting to load config file jupyter_config.py in path /etc/jupyter
[D 14:42:29.439 NotebookApp] Attempting to load config file jupyter_config.json in path /etc/jupyter
[D 14:42:29.439 NotebookApp] Attempting to load config file jupyter_config.py in path /usr/local/etc/jupyter
[D 14:42:29.439 NotebookApp] Attempting to load config file jupyter_config.json in path /usr/local/etc/jupyter
[D 14:42:29.440 NotebookApp] Attempting to load config file jupyter_config.py in path /Users/foouser/anaconda/etc/jupyter
[D 14:42:29.440 NotebookApp] Attempting to load config file jupyter_config.json in path /Users/foouser/anaconda/etc/jupyter
[D 14:42:29.440 NotebookApp] Attempting to load config file jupyter_config.py in path /Users/foouser/.jupyter
[D 14:42:29.440 NotebookApp] Attempting to load config file jupyter_config.json in path /Users/foouser/.jupyter
[D 14:42:29.440 NotebookApp] Attempting to load config file jupyter_config.py in path /Users/foouser
[D 14:42:29.440 NotebookApp] Attempting to load config file jupyter_config.json in path /Users/foouser
[D 14:42:29.440 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /etc/jupyter
[D 14:42:29.441 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /etc/jupyter
[D 14:42:29.441 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /usr/local/etc/jupyter
[D 14:42:29.441 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /usr/local/etc/jupyter
[D 14:42:29.441 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/foouser/anaconda/etc/jupyter
[D 14:42:29.441 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/foouser/anaconda/etc/jupyter
[D 14:42:29.441 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/foouser/.jupyter
[D 14:42:29.441 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/foouser/.jupyter
[D 14:42:29.441 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/foouser
[D 14:42:29.442 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/foouser
[I 14:42:29.494 NotebookApp] Serving notebooks from local directory: /Users/foouser
[I 14:42:29.494 NotebookApp] 0 active kernels 
[I 14:42:29.494 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 14:42:29.494 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 14:42:29.773 NotebookApp] Using contents: services/contents
[D 14:42:29.822 NotebookApp] 200 GET /tree (::1) 51.74ms
[D 14:42:29.848 NotebookApp] 200 GET /custom/custom.css (::1) 9.01ms
[D 14:42:30.030 NotebookApp] 200 GET /static/services/contents.js?v=20151027144229 (::1) 0.97ms
[D 14:42:30.035 NotebookApp] 200 GET /custom/custom.js?v=20151027144229 (::1) 1.37ms
[D 14:42:30.055 NotebookApp] 200 GET /api/config/tree?_=1445971349965 (::1) 0.96ms
[D 14:42:30.058 NotebookApp] 200 GET /api/config/common?_=1445971349966 (::1) 1.05ms
[D 14:42:30.065 NotebookApp] 200 GET /api/terminals?_=1445971349967 (::1) 0.69ms
[D 14:42:30.069 NotebookApp] Native kernel (python2) available from /Users/foouser/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 14:42:30.070 NotebookApp] Native kernel (python2) available from /Users/foouser/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 14:42:30.071 NotebookApp] 200 GET /api/kernelspecs (::1) 3.49ms
[D 14:42:30.075 NotebookApp] 200 GET /api/sessions?_=1445971349968 (::1) 2.74ms
[D 14:42:30.076 NotebookApp] 200 GET /api/terminals?_=1445971349969 (::1) 0.68ms
[D 14:42:30.114 NotebookApp] 200 GET /api/contents?type=directory&_=1445971349970 (::1) 17.84ms

**Comment by hosemn** [comment]
That doesn't mean that it's not working, as far as I know (as a Jupyter Notebook user that is probably slightly above "casual"). You must create a notebook and start using it before Jupyter will fire up a running kernel and show anything in the __Running__ section of the Jupyter overview.

Once your Notebook server is running and it opens in the browser, try the following:

1. Click the __New__ button (upper-right) and from the drop-down choose "Python 2" or "Python 3" from the __Notebooks__ section
2. (The notebook should open in a new tab) In the first cell, do some Python, maybe like `print("Hello, world!")`
3. Press `Ctrl+Enter` to run the cell
4. Observe the output
5. Return to the original tab (leave the notebook running in the other tab)
6. Click on __Running__ again to see if there are any running notebooks (may have to refresh with `F5` key in your browser)
7. Return to the active tab with the notebook running in it
8. From the __File__ menu, choose __Close and Halt__
9. Re-visit the __Running__ section of the original tab and see if there are any notebooks still running (again, you may have to refresh in your browser by using the `F5` key

Please give that a try and report back your status.

**Comment by metatl** [comment]
@hosemn 
Yes. It was actually working. I just didn't know it. I am completely new…I tried everything you suggested and it all works.

Now I have a related question. How do I use this together with iTorch? When I type iTorch notebook, the same window opens and I can start a notebook session. But in Torch how do I display stuff in the notebook window? Do you happen to know that?

**Comment by hosemn** [comment]
@metatl I am not personally familiar with iTorch, but it looks like it works generally like the Jupyter notebook in that it provides you with a notebook interface where you can write code and see the results in real-time, maintaining a living document of what you're doing as you interact with it. Though, the libraries it bundles are specific to Torch, which appears to be a machine learning framework. Sounds like cool stuff.

A great place to start is to get to know how the Jupyter (formerly IPython) notebook works, by viewing some tutorial videos: https://www.youtube.com/playlist?list=PLRJx8WOUx5Xd3_dgw5xRmABUd8MWdsA_C

If you're already familiar with the Python language enough to play around, those should get you up and running until you can start to familiarize yourself with Torch and iTorch. Most likely you'll need to look to the iTorch documentation (and/or developers) for assistance with the Torch/iTorch libraries and how to use them. They have a few examples on their GitHub main page and also they link to a sample notebook which has some examples of things you can do. I hope that helps.

**Comment by metatl** [comment]
@hosemn 
Thank you so much for the tips and suggestions.

The issue is resolved. The iTorch wasn't linked up properly. Now I'm good.

**Comment by hosemn** [comment]
I'm glad you resolved it! Would you mind marking the issue as "closed" so the devs don't have to? They're busy working on important stuff for release 4.1, so their attention is elsewhere. I'm just a lurker, so I (rightly) don't have permissions to close the issue.

**Comment by willingc** [comment]
Thanks @hosemn and @metatl for resolving this issue. :smile:
