### ISSUE TITLE
Fresh install of Jupyter is too slow to use

### ISSUE THREAD

**Issue by acgrama** [jupyter/notebook#6701]
**Describe the bug**
After installing Jupyter on a fresh machine, it runs extremely slowly. Most other slowness issues I have seen have answers like "shut down notebooks" and such, but I can't even start a notebook because even browsing in http://localhost:8888/tree uses like 25-30% CPU and temporarily freezes the page.

**To Reproduce**
Started notebook server in command line with `jupyter notebook`.

**Expected behavior**
I would like to be able to open a notebook without my CPU being overloaded and the notebook server freezing eveyr second :-)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome Version 108.0.5359.126 64 bit
- Version:
**Python 3.11.1**

**Jupyter**:
```
C:\WINDOWS\System32>jupyter --version
Selected Jupyter core packages...
IPython          : 8.8.0
ipykernel        : 6.20.2
ipywidgets       : not installed
jupyter_client   : 7.4.9
jupyter_core     : 5.1.3
jupyter_server   : 2.1.0
jupyterlab       : not installed
nbclient         : 0.7.2
nbconvert        : 7.2.8
nbformat         : 5.7.3
notebook         : 6.5.2
qtconsole        : not installed
traitlets        : 5.8.1
```

**Additional information**
Maybe the output of the notebook start is also relevant:
```
C:\WINDOWS\System32>jupyter-notebook
[I 11:02:02.187 NotebookApp] Serving notebooks from local directory: C:\WINDOWS\System32
[I 11:02:02.187 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 11:02:02.187 NotebookApp] http://localhost:8888/?token=9211dd5c57b14c95ce246e26367f54feb05f2672d7e60b49
[I 11:02:02.187 NotebookApp]  or http://127.0.0.1:8888/?token=9211dd5c57b14c95ce246e26367f54feb05f2672d7e60b49
[I 11:02:02.187 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:02:02.218 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/cristina.einramhof/AppData/Roaming/jupyter/runtime/nbserver-9056-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=9211dd5c57b14c95ce246e26367f54feb05f2672d7e60b49
     or http://127.0.0.1:8888/?token=9211dd5c57b14c95ce246e26367f54feb05f2672d7e60b49
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 11:07:02.222 NotebookApp] Interrupted...
[I 11:07:02.222 NotebookApp] Shutting down 0 kernels
[I 11:07:02.222 NotebookApp] Shutting down 0 terminals
```

**Comment by JasonWeill** [comment]
Related: #4706 is about the file browser being slow when Jupyter Notebook runs in a directory with lots of files.

**Comment by RRosio** [comment]
Hi @acgrama following up with you regarding this issue. Since there is a known issue with running Notebook from a directory with many files, it would be better if you ran Notebook from a directory with only Jupyter Notebooks in it.

**Comment by acgrama** [comment]
Solved, thanks a lot!
