### ISSUE TITLE
Missing `jupyter-notebook.desktop` file in version 7

### ISSUE THREAD

**Issue by frenzymadness** [jupyter/notebook#6704]
Notebook version 6 has [jupyter-notebook.desktop](https://github.com/jupyter/notebook/blob/v6.5.2/jupyter-notebook.desktop) for the integration to the GUI desktop environments. For some unknown reason, the file was deleted in https://github.com/jupyter/notebook/commit/5b6ed99aecdd1c337a70531efa20b6bb65e9e7c8 

The icon, notebook.svg, is still there.

**Comment by jtpio** [comment]
Thanks @frenzymadness for spotting this.

> For some unknown reason, the file was deleted in [5b6ed99](https://github.com/jupyter/notebook/commit/5b6ed99aecdd1c337a70531efa20b6bb65e9e7c8)

I think it was removed by mistake when the code base switched to Notebook 7 in this huge PR: https://github.com/jupyter/notebook/pull/6294

Probably we could just add it back. Would you like to open a PR? Thanks!
