### ISSUE TITLE
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS'

### ISSUE THREAD

**Issue by skr3178** [jupyter/notebook#6707]
```

   from charset_normalizer.md import mess_ratio
  File "charset_normalizer/md.py", line 5, in <module>
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (/home/skr/anaconda3/envs/prob3/lib/python3.7/site-packages/charset_normalizer/constant.py)
```

(prob3) skr@skr-X670E-Pro-RS:~/protein_bert$ conda list
 packages in environment at /home/skr/anaconda3/envs/prob3:

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.4.0                    pypi_0    pypi
anyio                     3.5.0            py37h06a4308_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py37h7f8727e_0  
astunparse                1.6.3                    pypi_0    pypi
attrs                     22.1.0           py37h06a4308_0  
babel                     2.11.0           py37h06a4308_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1           py37h06a4308_0  
bleach                    4.1.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py37h27cfd23_1003  
ca-certificates           2023.01.10           h06a4308_0  
cachetools                5.3.0                    pypi_0    pypi
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37h5eee18b_3  
charset-normalizer        3.0.1                    pypi_0    pypi
cryptography              38.0.4           py37h9ce1e76_0  
cudatoolkit               11.2.2              hbe64b41_11    conda-forge
cudnn                     8.1.0.77             h90431f1_0    conda-forge
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.5.1            py37h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
entrypoints               0.4              py37h06a4308_0  
expat                     2.4.9                h6a678d5_0  
flatbuffers               23.1.21                  pypi_0    pypi
flit-core                 3.6.0              pyhd3eb1b0_0  
fontconfig                2.14.1               h52c9d5c_1  
freetype                  2.12.1               h4a9f257_0  
gast                      0.4.0                    pypi_0    pypi
giflib                    5.2.1                h5eee18b_1  
glib                      2.69.1               he621ea3_2  
google-auth               2.16.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.51.1                   pypi_0    pypi
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
h5py                      3.8.0                    pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      3.4              py37h06a4308_0  
importlib-metadata        6.0.0                    pypi_0    pypi
importlib_metadata        4.11.3               hd3eb1b0_0  
importlib_resources       5.2.0              pyhd3eb1b0_1  
ipykernel                 6.15.2           py37h06a4308_0  
ipython                   7.31.1           py37h06a4308_1  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.6.5              pyhd3eb1b0_1  
jedi                      0.18.1           py37h06a4308_1  
jinja2                    3.1.2            py37h06a4308_0  
jpeg                      9e                   h7f8727e_0  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.16.0           py37h06a4308_0  
jupyter                   1.0.0            py37h06a4308_8  
jupyter_client            7.4.8            py37h06a4308_0  
jupyter_console           6.4.4            py37h06a4308_0  
jupyter_core              4.11.2           py37h06a4308_0  
jupyter_server            1.23.4           py37h06a4308_0  
jupyterlab                3.5.2            py37h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.16.5           py37h06a4308_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
keras                     2.11.0                   pypi_0    pypi
krb5                      1.19.4               h568e23c_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libclang                  15.0.6.1                 pypi_0    pypi
libdeflate                1.8                  h7f8727e_5  
libedit                   3.1.20221030         h5eee18b_0  
libevent                  2.1.12               h8f2d780_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libllvm10                 10.0.1               hbcb73fb_5  
libpng                    1.6.37               hbc83047_0  
libpq                     12.9                 h16c4e8d_3  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                hecacb30_0  
libuuid                   1.41.5               h5eee18b_0  
libwebp                   1.2.4                h11a3e52_0  
libwebp-base              1.2.4                h5eee18b_0  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                hfa300c1_0  
libxml2                   2.9.14               h74e7548_0  
libxslt                   1.1.35               h4e12654_0  
lxml                      4.9.1            py37h1edc446_0  
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib-inline         0.1.6            py37h06a4308_0  
mistune                   0.8.4           py37h14c3975_1001  
nb_conda                  2.2.1            py37h06a4308_1  
nb_conda_kernels          2.3.1            py37h06a4308_0  
nbclassic                 0.4.8            py37h06a4308_0  
nbclient                  0.5.13           py37h06a4308_0  
nbconvert                 6.5.4            py37h06a4308_0  
nbformat                  5.7.0            py37h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6            py37h06a4308_0  
notebook                  6.5.2            py37h06a4308_0  
notebook-shim             0.2.2            py37h06a4308_0  
nspr                      4.33                 h295c915_0  
nss                       3.74                 h0370c37_0  
numpy                     1.21.6                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1s               h0b41bf4_1    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.0                     pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0                    py37_1  
pickleshare               0.7.5                 py37_1001  
pip                       23.0                     pypi_0    pypi
pkgutil-resolve-name      1.3.10           py37h06a4308_0  
ply                       3.11                     py37_0  
prometheus_client         0.14.1           py37h06a4308_0  
prompt-toolkit            3.0.36           py37h06a4308_0  
prompt_toolkit            3.0.36               hd3eb1b0_0  
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.0            py37h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyqt                      5.15.7           py37h6a678d5_1  
pyqt5-sip                 12.11.0          py37h6a678d5_1  
pyrsistent                0.18.0           py37heee7806_0  
pysocks                   1.7.1                    py37_1  
python                    3.7.16               h7a1cb2a_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py37h06a4308_0  
pytz                      2022.7           py37h06a4308_0  
pyzmq                     23.2.0           py37h6a678d5_0  
qt-main                   5.15.2               h327a75a_7  
qt-webengine              5.15.9               hd2b0992_4  
qtconsole                 5.4.0            py37h06a4308_0  
qtpy                      2.2.0            py37h06a4308_0  
qtwebkit                  5.212                h4eab89a_4  
readline                  8.2                  h5eee18b_0  
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                65.6.3           py37h06a4308_0  
sip                       6.6.2            py37h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.2.0            py37h06a4308_1  
soupsieve                 2.3.2.post1      py37h06a4308_0  
sqlite                    3.40.1               h5082296_0  
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.11.0                   pypi_0    pypi
tensorflow-estimator      2.11.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.30.0                   pypi_0    pypi
termcolor                 2.2.0                    pypi_0    pypi
terminado                 0.17.1           py37h06a4308_0  
tinycss2                  1.2.1            py37h06a4308_0  
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py37h06a4308_0  
tornado                   6.2              py37h5eee18b_0  
traitlets                 5.7.1            py37h06a4308_0  
typing-extensions         4.4.0            py37h06a4308_0  
typing_extensions         4.4.0            py37h06a4308_0  
urllib3                   1.26.14          py37h06a4308_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py37_1  
websocket-client          0.58.0           py37h06a4308_4  
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py37h06a4308_0  
wrapt                     1.14.1                   pypi_0    pypi
xz                        5.2.10               h5eee18b_1  
zeromq                    4.3.4                h2531618_0  
zipp                      3.12.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.2                ha4553b6_0  
(prob3) skr@skr-X670E-Pro-RS:~/protein_bert$

**Comment by RRosio** [comment]
Hi @skr3178, thank you for submitting this issue. If you could verify that this issue is coming from importing the notebook server then we could take a look. Providing the full traceback for this error that would be helpful! You could also double check that you have all the needed packages installed.

**Comment by skr3178** [comment]
!pip install chardet

helped me resolve.

https://stackoverflow.com/questions/74182807/no-module-named-charset-normalizer-md-mypyc
