### ISSUE TITLE
Currently pip install --pre -e . ≠ pip3 install --pre -e .

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/notebook#671]
When I follow the instructions exactly for installing the dev master branch of the notebook 

    pip install --pre -e 

it builds `notebook-4.1.0.dev0`. 

However if I run what should be an equivalent command (just using `python3` and `pip3` instead):

    pip3 install --pre -e 

it builds the most recently released version of the notebook which at this time is `notebook-4.0.6`.

This seemed like an undesirable asymmetry for what should be equivalent commands, but it may be that there's something about `pip3` that I don't know. Otherwise, I figure it's a bug, and I don't know enough about `distutils` and the differences between `pip` and `pip3` to fix it myself.

**Comment by blink1073** [comment]
It sounds like you have different versions of pips, try:

```bash
pip --version
pip3 --version
```

**Comment by michaelpacer** [comment]
Nope, 

    $ pip --version
    pip 7.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
    $ pip3 --version
    pip 7.1.2 from /usr/local/lib/python3.5/site-packages (python 3.5)

I don't think it's that.

**Comment by blink1073** [comment]
Huh, bummer.

**Comment by willingc** [comment]
@michaelpacer Within a Python3 virtualenv on OS X, I'm not seeing any difference in behavior between `pip install --pre -e .` and `pip3 install --pre -e .`. Both commands  install the most recent development version.

<img width="691" alt="screen shot 2015-10-27 at 7 05 03 pm" src="https://cloud.githubusercontent.com/assets/2680980/10777984/517290be-7cde-11e5-8613-70c376bc4e9d.png">

**Comment by minrk** [comment]
@michaelpacer what do you see in `pip list`? And what do you get from

    python -c 'import notebook; print(notebook.__file__)'

?

**Comment by minrk** [comment]
Closing as probably something we can do nothing about. This is likely due to previous installations putting setuptools in a confused state - pip has been known to output "installed package-x" when it actually just *uninstalled* package-x and installed package-y.
