### ISSUE TITLE
Completion with tab is not working with R kernel 

### ISSUE THREAD

**Issue by dugamarian** [jupyter/notebook#6711]
Hi, 

I’m using version:7.0.0a11 with R kernel. Nothing happens when I hit tab to autocomplete. I’ve enabled language servers and code completion in settings but nothing happened.

**Comment by RRosio** [comment]
Pinging @krassowski on this

**Comment by andrii-i** [comment]
Fixed by @krassowski in JupyterLab in https://github.com/jupyterlab/jupyterlab/pull/14505

**Comment by andrii-i** [comment]
@dugamarian could you please check if this issue is still present?

**Comment by krassowski** [comment]
The upstream PR in lab was merged after 7.0.0b2 was released.

**Comment by dugamarian** [comment]
I have installed and tested the new version of jupyter lab 4.0.0 an is working fine. Thanks!

**Comment by jtpio** [comment]
FYI @dugamarian `7.0.0b3` was released today and should include this fix: https://github.com/jupyter/notebook/releases/tag/v7.0.0b3

Closing as fixed, but feel free to open a new issue if needed, thanks!
