### ISSUE TITLE
Provide .mo and .json files for translations

### ISSUE THREAD

**Issue by frenzymadness** [jupyter/notebook#6717]
As you can see in `notebook/notebook/i18n/` only the `nl` translation provides also generated .mo files and nbjs.json files. I've checked the wheel file provided on PyPI and the content is the same. Is that intended? I mean, AFAIU, the .po files are useless without the generated .mo files, right?

Would it be possible to regenerate all the .po files into .mo files and nbjs.po to nbjs.json?

**Comment by RRosio** [comment]
Thank you for reporting this issue @frenzymadness. Just noting here, as @krassowski mentioned in Triage, that Notebook 7 will use Jupyterlab machinery, https://github.com/jupyterlab/jupyterlab-translate and https://github.com/jupyterlab/language-packs, for translations. If you would like to provide feedback on these translations that would be appreciated!

**Comment by frenzymadness** [comment]
The standalone language packs look very good and the whole process of their release is very promising. Good job.

Would it be accepted for version 6.5 if I open a PR with pre-generated .mo and .json files to fix it before we'll be able to switch to version 7?

My motivation for this is that I'd like to update notebook in Fedora Linux to version 6.5 and I'm able to generate the .mo files during the build of RPM packages but I'm not able to generate the .json files because the JS implementation of po2json from npm is not available in Fedora.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter/notebook/pull/6728, thanks!
