### ISSUE TITLE
It is _still_ impossible to navigate to a different Windows drive from the notebook or lab file selection UI

### ISSUE THREAD

**Issue by PaulKGrimes** [jupyter/notebook#6729]
Please reopen issue #1334, as the problem persists, and the final workaround listed in #1334 before it was locked - using Jupyter-FS from JPChaseMorgan - does not work due to Jupyter-FS no longer working - in particular, it is unable to open subfolders reliably.

This is greatly hampering me using Jupyter Notebook and Lab on a day-to-day basis, as I have multiple projects using notebooks across several drives on my PC, including shared Google Drives, etc.

As evidenced by this discussion on the Jupyter Discourse at https://discourse.jupyter.org/t/jupyter-not-finding-folders/1116 many people have a problem with this particular design decision.

**Comment by RRosio** [comment]
Re-opened #1334
