### ISSUE TITLE
Styling regressions in Notebook 7 tab bar

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/notebook#6730]
**Describe the bug**
CSS issues in Notebook 7 tab bar include that:

1. There is no dark background (as in JupyterLab 4) in the space to the right of the rightmost tab.
2. The tab bar boundary is very slightly (1 pixel?) higher than the top of each individual tab
3. The rightmost edge of the tab bar slightly overhangs the right edge of the active tab's container.

![image](https://user-images.githubusercontent.com/93281816/218588064-e6b6d3fe-94b4-434a-b657-1ff0fd056979.png)

**To Reproduce**

1. Launch Notebook 7
2. See behaviors above

**Expected behavior**

1. There should be a darker background for the negative space than for any active or inactive tab.
2. The tab bar boundary should be even with or lower than the top of any tab.
3. The rightmost edge of the tab bar should be flush with the right edge of the active tab container, with a drop shadow to match.

**Screenshots**

See above

**Desktop (please complete the following information):**

- OS: macOS 12.6.3
- Browser: Firefox
- Version: 102.7.0esr

**Comment by jtpio** [comment]
Also wondering if we should follow the style used in Jupyterlab, or maybe try to be closer to the classic notebook UI: https://github.com/jupyter/notebook/issues/6397

**Comment by jtpio** [comment]
FYI @JasonWeill https://github.com/jupyter/notebook/pull/6738 made some tweaks to the file browser UI:

![image](https://user-images.githubusercontent.com/591645/219743890-91185b7b-e6aa-4760-b2e4-ba526e40230e.png)

Which can be tested on Binder: https://mybinder.org/v2/gh/jupyter/notebook/main?urlpath=tree

Feel free to open an issue if you think there is still room for improvements, thanks!
