### ISSUE TITLE
jupyter do not run code

### ISSUE THREAD

**Issue by p4vlos** [jupyter/notebook#674]
I am running jupyter notebook on my macbook pro using safari and i push the play button to run code section but nothing happened. If i do this from uni PCs are working fine. I tried also google chrome but nothing.
<img width="939" alt="screen shot 2015-10-28 at 14 12 26" src="https://cloud.githubusercontent.com/assets/11935187/10790962/1de5cac2-7d7e-11e5-8aa8-c8611eef8e1e.png">

**Comment by minrk** [comment]
That's a difference between Legacy Python and Python 3. In Legacy Python, calling `range()` returns a list of numbers. In Python 3, it creates a `range` object, which is more efficient, and whose representation happens to look the same as your input. You can see this more clearly if you do:

```python
start = 3
stop = 12
range(start, stop)
```

which will have the result

```python
range(3, 12)
```

If you want to get the Legacy Python list in Python 3, you can pass the range to `list`:

```python
list(range(2, 5))
[2, 3, 4]
```
