### ISSUE TITLE
Add the "Open with Classic Notebook" entry in the interface dropdown if NBClassic is available?

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6746]
Currently the latest Notebook 7 pre-release only lists JupyterLab as an alternative interface for opening the current notebook:

![image](https://user-images.githubusercontent.com/591645/220920346-6ab63db3-e27d-4a53-b441-b1e8b8aeaac3.png)

When it was added in RetroLab it also displayed the classic notebook because `notebook` was installed automatically as a transitive dependency: https://github.com/jupyterlab/retrolab/pull/309

https://user-images.githubusercontent.com/591645/147280995-7ce202ed-c09d-4aa7-a3a3-6f85f1b52b6e.mp4

Currently nothing installs `nbclassic` by default anymore so the "Open with Classic Notebook" entry is not displayed.

But maybe the interface switcher plugin should try to detect if `nbclassic` is available, and add an extra menu entry that points to `/nbclassic/notebooks` if it is?

**Comment by jtpio** [comment]
The relevant part of the code is located here:

https://github.com/jupyter/notebook/blob/0ccb87867d9de4af6feaeccfdf1539af541f6268/packages/lab-extension/src/index.ts#L114-L130

**Comment by yuvipanda** [comment]
I would really like this to be part of the release! Adding that to retrolab was how we were able to convince many instructors to give retrolab a try, and I think it's a low effort high impact thing - being able to say 'you can switch to the older interface at any time' dissolves a lot of resistance, even if that is unused.

**Comment by jtpio** [comment]
Reposting https://github.com/jupyter/notebook/pull/6793#issuecomment-1490205486 here for visibility:

1. either we add a new entry in the dropdown pointing to `/nbclassic/notebook`, but without depending on `nbclassic` in `notebook`. The link might give a 404 if `nbclassic` is not installed. But would work if `nbclassic` is installed. Users will have to explicitly `pip install nbclassic` to get the classic notebook UI
2. or we add the new entry as mentioned in 1., and also make `notebook==7` depend on `nbclassic` to make sure it's always there.

@yuvipanda suggests to go with 2 to make the Notebook 7 rollout smoother.

cc @jupyter/notebook-council for awareness and thoughts about this

**Comment by echarles** [comment]
> 1. either we add a new entry in the dropdown pointing to /nbclassic/notebook, but without depending on nbclassic in notebook. The link might give a 404 if nbclassic is not installed. But would work if nbclassic is installed. Users will have to explicitly pip install nbclassic to get the classic notebook UI

This does not sound like a good option to me.

> 2. or we add the new entry as mentioned in 1., and also make notebook==7 depend on nbclassic to make sure it's always there.

That will work. I don't see direct negative impact as we have designed the system to support that case. For sure there are not a lot of such env in the field, meaning that is not widely tested and issues might not have been reported yet.

3. Another option would be to detect on server launch if nbclassic is present or not and inject that information in the pageconfig, so that Notebook 7 adapts its ui/menu accordingly. That is some extra development work. BTW this could be generalised to detect the existence of some well-targeted packages and that feature could be useful to other, so would need maybe to be implemented in JupyterLab, probably too late today due to the current beta/rc release cycle for JupyterLab 4.

**Comment by yuvipanda** [comment]
I also like (2), extended to (3) in the future if resources exist to do so.

**Comment by ellisonbg** [comment]
I think it is a mistake to have a hard dependency on nbclassic in notebook 7. For many users, they won't know the difference and it will confuse them (why do I have the current and last release of an application at the same time when they look and act nearly identical). This also makes it much more difficult for operators that don't want to deploy nbclassic.

**Comment by ellisonbg** [comment]
I think that option (3) above (detect nbclassic dynamically) would be fine. If this is the right thing for users, we can help get this done for the notebook 7 release.

**Comment by ellisonbg** [comment]
Great, Andrii would be the one who can do that work, go ahead and mention it to him.

**Comment by andrii-i** [comment]
@echarles @ellisonbg was missing the the context before the Notebook; would be happy to work on this, please assign it to me

**Comment by jtpio** [comment]
An alternative to making `notebook` depend on `nbclassic` would be to add `nbclassic` to the `jupyter` metapackage instead: https://github.com/jupyter/jupyter

The jupyter metapackage is very popular. Users often "pip install jupyter" when they are told to "Install Jupyter".
