### ISSUE TITLE
themePath handling issue

### ISSUE THREAD

**Issue by serhiisobol** [jupyter/notebook#6751]
- `themePath` is platform-dependent (on Windows, the backslash is needed, on Linux/macOS forward slash) 
- the error message when the file specified by `themePath` ("themePath is empty") is very misleading

On the left side of the screenshot inside `package.json`, `themePath` value is  `"style/index.css"`
On the right `themePath` handling from `commands.py`
![image](https://user-images.githubusercontent.com/87301227/222120778-682d8bee-7a4b-451c-9dc2-97ed572e0f25.png)

During the installation a jupyter lab extension with `jupyter labextension link .` 
I am getting the path of styles with a backslash
![image](https://user-images.githubusercontent.com/87301227/222125419-11392795-62f0-4e22-88f4-6d2f1595f836.png)

**Comment by RRosio** [comment]
Hi @serhiisobol, thank you for submitting this issue! As this applies to JupyterLab, I have copied this issue over to the [JupyterLab repository](https://github.com/jupyterlab/jupyterlab) for further discussion there.

**Comment by serhiisobol** [comment]
> Hi @serhiisobol, thank you for submitting this issue! As this applies to JupyterLab, I have copied this issue over to the [JupyterLab repository](https://github.com/jupyterlab/jupyterlab) for further discussion there.

Hello, thank you!
