### ISSUE TITLE
Document the new features in Notebook 7

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6758]
Before the first 7.0 beta is released, we should document some of the major new features available in Notebook 7.

Taking inspiration from https://jupyter.org/enhancement-proposals/79-notebook-v7/notebook-v7.html, but with screenshots or videos.

The documentation should also cover how to configure extensions, toolbars and other components. A concrete example would be to explain how to enable the file search bar in the file browser toolbar (added in https://github.com/jupyter/notebook/pull/6757).

**Comment by AnkurRajneta** [comment]
I have created an outline regarding the documentation .In which file do  I need to make changes @jtpio

**Comment by AnkurRajneta** [comment]
Unable to find the repository .Can you point me the location @jtpio

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter/notebook/pull/6813.

Docs: https://jupyter-notebook.readthedocs.io/en/latest/notebook_7_features.html
