### ISSUE TITLE
idris

### ISSUE THREAD

**Issue by idris123aydin** [jupyter/notebook#6759]
**Describe the bug**

**To Reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: \[e.g. iOS\]
- Browser \[e.g. chrome, safari\]
- Version \[e.g. 22\]

**Additional context**

**Comment by jtpio** [comment]
Closing as this appears to have been opened by mistake.
