### ISSUE TITLE
 Toolbar button "Restart Kernel and Run All Code..." has no icon

### ISSUE THREAD

**Issue by jitseniesen** [jupyter/notebook#6761]
**Describe the bug**
Toolbar button "Restart Kernel and Run All Code..." has no icon

**To Reproduce**

1. Download source for version 7.0.0a14 (current HEAD) 
1. Create development environment following the instructions in CONTRIBUTING.md
1. Start Jupyter Notebook and create a new notebook

**Expected behavior**
The text on the button looks out of place, it should probably be an icon (or perhaps the button should not be in the toolbar at all).

**Screenshots**
![jupyter-notebook](https://user-images.githubusercontent.com/7941918/223156823-94c63b19-011e-429e-8699-5fe7eac39b46.png)

**Desktop (please complete the following information):**

- OS: Linux Debian
- Browser: Firefox
- Version: 102.8.0esr

**Additional context**
The issue may well be in how I follow the instructions in CONTRIBUTING.md (though they seem pretty clear) or the instructions themselves. I have very little JavaScript experience and the build process still holds many mysteries for me.

**Comment by jtpio** [comment]
Thanks @jitseniesen for the report.

This will likely be fixed by https://github.com/jupyter/notebook/pull/6757, which should include the fix that landed upstream in JupyterLab: https://github.com/jupyterlab/jupyterlab/pull/14000

**Comment by jitseniesen** [comment]
Thanks @jtpio for your quick reply and fix. You probably don't need this, but I can confirm that the latest release fixes the issue.

More broadly, thanks very much to everybody concerned for your work on Jupyter Notebook 7. I am trying to see whether it can be integrated in Spyder. It looks much better than my previous attempt, that was based on the example-notebook distributed with Jupyter Lab.
