### ISSUE TITLE
empty py.test file in notebook/

### ISSUE THREAD

**Issue by frenzymadness** [jupyter/notebook#6763]
Commit https://github.com/jupyter/notebook/commit/22475a39ab4932490ae5827e2ce3f1e2e729b924 introduced `notebook/py.test` file and I have no idea why an empty file like that might be needed. What is the purpose of that file?

**Comment by jtpio** [comment]
Thanks @frenzymadness for the report.

Not sure it's needed. Would you like to open a PR that removes the file, so we can see if CI still passes? Thanks!

**Comment by frenzymadness** [comment]
CI is green so I think the file is useless.
