### ISSUE TITLE
ModuleNotFoundError: No module named notebook.notebookapp

### ISSUE THREAD

**Issue by MaxDragonheart** [jupyter/notebook#6765]
After months I'm trying to start a Jupyter Notebook inside a Poetry environments using PyCharm but I see this error:

> Jupyter server process exited with code 1 Traceback (most recent call last): File "/home/max/.cache/pypoetry/virtualenvs/env_name/bin/jupyter-notebook", line 5, in   from notebook.notebookapp import main ModuleNotFoundError: No module named 'notebook.notebookapp'

Last time that I've used the notebook all worked fine.

I've deleted the environment(`rm -rf env_name`) and the project folder. So I've cloned again the project from GitHub and then, via `poetry install`, I've recreated the environment but nothing is changed.

The `toml` contains this packages:
```
[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^0.21.1"
shapely = "^2.0.1"
pandas = "^1.5.3"
geopandas = "^0.12.2"
psycopg2-binary = "^2.9.5"
googlemaps = "^4.10.0"
tqdm = "^4.64.1"
XlsxWriter = "^3.0.8"
openpyxl = "^3.1.0"
Unidecode = "^1.3.6"
fsspec = "^2023.1.0"
SQLAlchemy = "<2.0"
GeoAlchemy2 = "^0.13.1"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
notebook = "^6.5.2"
jupyter-server-proxy = "^3.2.2"
```
How I can solve this problem? I'm on Ubuntu 20.04 with PyCharm 2022.3.3

**Comment by tonyfast** [comment]
i have a feeling you might running into some environment issues related to poetry rather than the notebook. do you need to [`poetry install --dev-dependency`](https://python-poetry.org/docs/cli/)? i am not a poetry user and can't help too much. i think this question might get some different support responses on https://discourse.jupyter.org

**Comment by MaxDragonheart** [comment]
@tonyfast probably you are rigth. I try to find some information on the jupyter forum, thank you
