### ISSUE TITLE
Settings Editor cannot open after switching to JSON

### ISSUE THREAD

**Issue by yumyumqing** [jupyter/notebook#6778]
**Describe the bug**
When I work in development environment, in `Settings` - `Setting Editor` - `Settings Editor Form UI`, once I switched from UI to JSON, I couldn't open `Setting Editor` any more.

I have tried some methods to reset my settings but so far no luck yet.
- clear my browser cache
- reclone the repo
- remove and recreate my mamba env
- restart the laptop

**To Reproduce**

1. Set up dev environment as https://github.com/jupyter/notebook/blob/main/CONTRIBUTING.md#setting-up-a-development-environment
2. Go to the browser page opened by `jupyter notebook`
3. Click `Settings`
4. Click `Settings Editor`
5. Click `Settings Editor Form UI`
6. Toggle to `json` and close the settings tab
7. Try to open settings menu again

**Expected behavior**
I should be able to reopen the settings menu and change it back.

**Console output**
When I tried to reopen settings again, it shows:
```
Uncaught (in promise) Error: Command 'settingeditor:open-json' not registered.
    at CommandRegistry.execute (index.es6.js:363:35)
    at eval (index.js:141:41)
```

**Screenshots**
<img width="1437" alt="settingeditor" src="https://user-images.githubusercontent.com/21135321/226083493-c50c0323-307e-4d2d-ac52-d02f4f60636c.png">

**Desktop (please complete the following information):**

- OS: MacOS Ventura 13.2.1 
- Browser: chrome
- Version: tip of main branch

Thank you for taking a look at it!

**Comment by jtpio** [comment]
Thanks @yumyumqing for reporting this!

Most likely the missing command is because only the upstream `form-ui` plugin is included in the build:

https://github.com/jupyter/notebook/blob/551515559b83316655fae6fe620912ef8516c8fb/app/package.json#L274-L276

I don't remember if there was an issue with the other plugin that adds the `settingeditor:open-json` command. Maybe we could check what happens if the whole  `@jupyterlab/settingeditor-extension` extension is included?

**Comment by yumyumqing** [comment]
Thank you @jtpio for your help! 
Following your advice, I did:
1. Added whole extension (`plugin` is the only other one) in notebook/app/package.json.
```
"@jupyterlab/settingeditor-extension": [
    "@jupyterlab/settingeditor-extension:plugin",
    "@jupyterlab/settingeditor-extension:form-ui"
]
```
2. Rebuild the app by `jlpm build`
3. Launch the notebook by `jupyter notebook`

The `Setting Editor` is still not clickable. This time the console doesn't spit `Uncaught error of open-json` but it has this warning.
```
DevTools failed to load source map: 
Could not load content for webpack://_JUPYTERLAB.CORE_OUTPUT/node_modules/@jupyterlab/settingeditor-extension/lib/index.js.map: 
Fetch through target failed: Unsupported URL scheme; 
Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

May I ask if I am missing anything here? Thanks!

p.s. Also I am having some difficulties on how I could find out where does jupyter notebook store the `json` settings I made. Can you please help me on finding where it specifies the location where it stores the settings? Thanks a lot!

**Comment by jtpio** [comment]
> this warning.

Probably this one could be ignored for now as it seems to be related to the source map.

> The `Setting Editor` is still not clickable.

Looking at the upstream code in JupyterLab it looks like the `open-json` command tries to add the widget to the main area:

https://github.com/jupyterlab/jupyterlab/blob/8230a1a41d48207ae05394607e368b196670cd6a/packages/settingeditor-extension/src/index.ts#L248-L311

Currently in Notebook 7 the `main` area accepts the first widget, which could explain why it does not show up.

Maybe we should try to do something similar as for the Settings Editor UI here:

https://github.com/jupyter/notebook/blob/cc454bb0ccca905a2a78805276eb0dcb7db09d9c/packages/tree-extension/src/index.ts#L304-L310

But using `IJSONSettingEditorTracker` instead.

**Comment by yumyumqing** [comment]
Thank you @jtpio ! 

Can you please elaborate a bit more on how I should modify the notebook/lab extension codebase and how to build the modified lab extension into the notebook binary?
I tried a couple of things but couldn't figure it out. Thanks a lot!

**Comment by jtpio** [comment]
Thanks @yumyumqing for looking into it!

My guess is that we could add `IJSONSettingEditorTracker` as an optional dependency here:

https://github.com/jupyter/notebook/blob/cc454bb0ccca905a2a78805276eb0dcb7db09d9c/packages/tree-extension/src/index.ts#L208

And then add a block similar to the following one:

https://github.com/jupyter/notebook/blob/cc454bb0ccca905a2a78805276eb0dcb7db09d9c/packages/tree-extension/src/index.ts#L304-L310

That would look like this:

```ts
if (jsonSettingEditorTracker) {
  jsonSettingEditorTracker.widgetAdded.connect((_, editor) => {
    nbTreeWidget.addWidget(editor);
    nbTreeWidget.tabBar.addTab(editor.title);
    nbTreeWidget.currentWidget = editor;
  });
}
```

This should handle JSON editors and add them as an extra tab.

Feel free to open a (draft) PR if you would like to look into this, thanks!

**Comment by yumyumqing** [comment]
Thanks @jtpio ! With your advised changes, it seems to work on my end. I will study the guideline and create a PR.

**Comment by yumyumqing** [comment]
Hi @jtpio I have created a [PR draft](https://github.com/jupyter/notebook/pull/6795) but I might have missed adding a label and I couldn't find out where to modify the labels now. Can you help taking a look? Thanks!
