### ISSUE TITLE
Focus issues after clicking on "add cell above/below" cell toolbar buttons

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/notebook#6780]
**Describe the bug**

After clicking the "Add Cell Above" or "Add Cell Below" toolbars, when the current cell is in edit mode, the new cell focuses but the cursor remains in the old cell.

**To Reproduce**

1. Create a new notebook with three markdown cells containing A, B, and C.
1. Edit cell B.
1. Click the "Add below" button in the toolbar.
1. The cursor continues to blink in cell B, but a new cell (cell D) appears between B and C. If the user types, text appears in cell D.

(Same if the user clicks "Add above")

**Expected behavior**
The cursor appears in cell D.

**Screenshots**

https://user-images.githubusercontent.com/93281816/226478440-701d87a5-6aee-4452-a594-043fd27c0da4.mov

**Desktop (please complete the following information):**

- OS: Windows 10 Enterprise 21H2 (19044.2604)
- Browser Firefox
- Version 102.9.0esr

**Comment by JasonWeill** [comment]
Problem occurs with 7.0.0a17. Also occurs in JupyterLab 4.0.0a37.

**Comment by jtpio** [comment]
Thanks @JasonWeill.

> Also occurs in JupyterLab 4.0.0a37.

Should this be reported upstream in JupyterLab? It would also be fine to keep it open here in `jupyter/notebook` until fixed if needed.

**Comment by JasonWeill** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/issues/14271.
