### ISSUE TITLE
Stub toolbar visible at top of text files

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/notebook#6784]
There is a weird remnant of a minimized toolbar at the top of text files in notebook. Looks like we are pulling this over from lab without any modification to make it look right. Another difficult thing is that the line number column has the same background as the rest of the page, making it look odd.

This was found by @ellisonbg during a bug bash.

![image](https://user-images.githubusercontent.com/93281816/226790526-4344f62a-42e0-42be-9e83-152b6d9b4c8d.png)

**Comment by jtpio** [comment]
Thanks for reporting.

I believe this comes from the default toolbar of the `MainAreaWidget` being empty. And is likely similar in JupyterLab as well. This was briefly discussed at a recent Notebook weekly call (cc @afshin).

Probably there should be some styling to hide it if is empty (although some extensions might add toolbar buttons to it).
