### ISSUE TITLE
Text editor should display a partial view with a drop shadow

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/notebook#6785]
The bottom of the page of the text editor shows the white document portion going all the way to the bottom. It should render like a "document" - in other words, a white piece of paper on a grey table.

This was found during a bug bash by @ellisonbg .

See also https://github.com/jupyter/notebook/issues/6781.

![Screen Shot 2023-03-20 at 3 31 30 PM](https://user-images.githubusercontent.com/93281816/226790928-226f8c39-9976-4b5c-9d37-03d388076b72.png)

**Comment by jtpio** [comment]
For reference the editor in the Classic Notebook goes almost all the way to the bottom (it has a small margin bottom):

![image](https://user-images.githubusercontent.com/591645/226860823-c6886668-2302-4108-8259-4ce8e17b0269.png)

**Comment by j-publius** [comment]
Currently waiting on guidance for the shadow aspect of this issue, but I got another [PR](https://github.com/jupyter/notebook/pull/6804) that fixes the white space :)

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter/notebook/pull/6804
