### ISSUE TITLE
Styling issues in console (Python)

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/notebook#6789]
In Notebook 7.0.0a17, the console (Python) has some weird styling issues.

- [ ] If you click on a cell, you initiate a drag interaction but you can't drag cells.
- [ ] No favicon for terminal in browser tab.
- [ ] every run cell gets a blinking text cursor. 
- [ ] thin toolbar at top of window.

![Screen Shot 2023-03-20 at 3 42 50 PM](https://user-images.githubusercontent.com/93281816/226791909-5dcaebcf-2ecf-4d19-a547-f532641fd19c.png)

**Comment by JasonWeill** [comment]
This was found by @ellisonbg during a bug bash.

**Comment by jtpio** [comment]
Thanks @JasonWeill.

Similar to #6788, this seems to be an issue in JupyterLab 4? If so the issue could be opened in the JupyterLab repo.

**Comment by JasonWeill** [comment]
Resolving in favor of https://github.com/jupyterlab/jupyterlab/issues/14541.
