### ISSUE TITLE
Replace "Interface" dropdown with button if only one option is present

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/notebook#6792]
The "Interface" dropdown in JupyterLab is a large dropdown in the toolbar with only one option, "Open With Jupyter Notebook":

![image](https://user-images.githubusercontent.com/93281816/227317479-3c4013cc-1315-45e2-a35e-f342265630df.png)

… and in Jupyter Notebook, it's a dropdown with one option, "Open With JupyterLab":

![image](https://user-images.githubusercontent.com/93281816/227317570-eaf4a67d-a19e-4490-88f5-fb6ac5f73129.png)

If only one option is present, replace this dropdown with a single button with an icon for the other interface, also on the toolbar, to save space.

In addition, add a command to the right-click context menu on the notebook body to "Open With" the other interface.

This was found during a Bug Bash by @ellisonbg .

**Comment by jtpio** [comment]
For reference there used be buttons in the toolbar before (in RetroLab): https://github.com/jupyterlab/retrolab/issues/256

Which was then switched to a menu to avoid confusion: https://github.com/jupyterlab/retrolab/pull/309

There is also https://github.com/jupyter/notebook/issues/6746

**Comment by JasonWeill** [comment]
Thanks @jtpio! From https://github.com/jupyterlab/retrolab/pull/309, here's the "before" picture showing RetroLab with buttons for "open in JupyterLab" (Jupyter logo with 3 moons) and "open in classic notebook" (Jupyter logo with no moons".

![notebook-chromium-linux](https://user-images.githubusercontent.com/93281816/227374808-94243410-052e-48de-9cd0-b854048ebb1d.png)

**Comment by JasonWeill** [comment]
After discussion with @ellisonbg , this requested change is revised to:

1. If the interface menu has only one option, display a button using a UI as demonstrated in #6793.
2. If the interface menu has more than one option, display a menu with multiple choices.

**Comment by jtpio** [comment]
> this requested change is revised to:

Will that change actually be needed if https://github.com/jupyter/notebook/issues/6746 is implemented?

If `notebook` depends on both `nbclassic` and `jupyterlab`, there will always be at least two entries.
