### ISSUE TITLE
Notebook cells not executing sequentially

### ISSUE THREAD

**Issue by braedd** [jupyter/notebook#6794]
When I Shift+Enter multiple cells so that sequentially, they get executed one after another. But after the first 2 cells are executed, the rest of the cells just ... not run.The * symbol next to the cells would just disappear. This has never happened to me before, on the same machine and OS even. 
I've reinstalled Anaconda, reinstalled Jupyter, reinstall ipykernel so far and to no avail. Is there anyone who knows how to fix this weird issue? Thank you

**Comment by RRosio** [comment]
Closing this issue as no further information was provided. Please feel free to re-open this issue and update with additional information if it persists!
