### ISSUE TITLE
Please add an option to disable the Notebook 7 migration banner administratively

### ISSUE THREAD

**Issue by moschlar** [jupyter/notebook#6798]
Could you please add an option to disable the Notebook 7 migration banner that was introduced in #6742 administratively (e.g. for JupyterHub deployments where it is the admins responsibility and not necessarily the users.

**Comment by jtpio** [comment]
Thanks @moschlar.

cc @echarles @RRosio for awareness

**Comment by echarles** [comment]
Notebook 6.5.4 is released with this feature. Closing as fixed
