### ISSUE TITLE
Handle cases when there are marked cells off-screen

### ISSUE THREAD

**Issue by jhamrick** [jupyter/notebook#680]
The user could potentially do things they don't intend to (e.g. delete multiple cells) if there are marked cells off screen. This might also be something they do intend to do, though, so I would say we shouldn't prevent users from taking actions on off-screen marked cells, but that we should at least give them a heads up that this is the case. I have some ideas for this:

* add something to the notification area
* have a little banner at the top or bottom of the screen (kind of like what gitter has for unread messages)
* put a counter or something somewhere near the current cell selector that displays the total number of marked cells (but only display it if the number is greater than 1)

Thoughts?

**Comment by ellisonbg** [comment]
What about scrolling the top of the marked section into view, leaving things marked and allowing the user another go at the action. Could couple this with a message to the notification area. I do also like the idea of a marked cell counter, but I worry users won't see it when it matters.

**Comment by jhamrick** [comment]
Hmm, what if the marked cells are below the currently selected cell (meaning technically the "top" of the marked section is already in view)? I also tend to dislike things that automatically scroll the page somewhere else... but that's just my personal preference, not sure about other people.

**Comment by willingc** [comment]
Perhaps a simple notification on top bar whenever there are marked cells existing off screen. I'm with @jhamrick that I prefer not to have things scroll automatically.

**Comment by jhamrick** [comment]
Here is a prototype that uses the notification area:

![](http://i.imgur.com/RpAMvby.gif)

**Comment by blink1073** [comment]
Nice! :+1:
