### ISSUE TITLE
Kernel Dying When Importing Pandas and NumPy Into Jupyter Notebook File

### ISSUE THREAD

**Issue by sebreaw** [jupyter/notebook#6801]
Hello,
I am trying to import Pandas and Numpy to complete assignments for my data analytics bootcamp and am met with the pop up below:

<img width="734" alt="Screenshot 2023-03-27 at 8 09 42 PM" src="https://user-images.githubusercontent.com/124512204/228100792-be605f7f-e8c7-48ce-a8e0-fedd484c4c2e.png">

Some of the things i've done to fix this is:
1.Restarting the kernel
2. Installed both packages using pip
3. Ran code to update both packages through the Mac terminal
4.Checked for conflicting libraries (none found)
5.Increased the memory allocation (inserted the code `import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'` at the beginning of the notebook
6. Updating Mac OS software
7. Clearing cache

So far nothing has worked. I am using a Macbook Pro and Python 3.9.7 installed in the Anaconda environment.
I would greatly appreciate any hands-on support.

**Comment by sebreaw** [comment]
@RRosio 
<img width="1426" alt="Screenshot 2023-04-10 at 7 50 29 PM" src="https://user-images.githubusercontent.com/124512204/231027075-10c9cdda-bd49-447b-a18d-7ffb2fb21744.png">

**Comment by RRosio** [comment]
Hi @sebreaw, thank you for providing this. In this console, if you search for `Jupyter`, do you see any errors specific to it? Also, does this issue happen when you run a different kernel?

**Comment by sebreaw** [comment]
@RRosio 
I don't see any errors pertaining to Jupyter or Anaconda. Also, I've only been using the Terminal app to access the kernel. Not sure how to run other kernels... I wonder if there are any sites where I can get in touch with a computer programmer or software engineer

**Comment by RRosio** [comment]
There is a [discourse](https://discourse.jupyter.org/c/notebook/31) and other community resources [here](https://jupyter.org/community), where you can post questions.  There is a similar issue previously posted, https://github.com/jupyter/notebook/issues/5614, but it seems like you've already tried those suggestions. Per triage, this doesn't seem to be an issue with the notebook codebase, but I encourage you to look into discourse for troubleshooting.
