### ISSUE TITLE
How to hide Run this cell button?

### ISSUE THREAD

**Issue by MrClearLovez** [jupyter/notebook#6811]
Hello, my jupyter pop up Run this cell button. My jupyter is deployed on a Linux server, but I do not have root permission. When I run jupyter on another computer, the button disappears. How can I solve this problem and sincerely ask for your help!

![1680488424006](https://user-images.githubusercontent.com/103395438/229397010-56b02504-013e-431c-990e-88f84825c631.png)

**Comment by RRosio** [comment]
Thanks for submitting this issue @MrClearLovez! If you go to the Help -> About button, could you share which frontend Jupyter application you are running?

**Comment by MrClearLovez** [comment]
Thank you very much for your reply,t
his is the program I'm running.










------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月5日(星期三) 凌晨0:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jupyter/notebook] How to hide Run this cell button? (Issue #6811)





 
Thanks for submitting this issue @MrClearLovez! If you go to the Help -&gt; About button, could you share which frontend Jupyter application you are running?

**Comment by MrClearLovez** [comment]
Hi,I solved the problem by restarting the computer. Thank you very much for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jupyter/notebook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月5日(星期三) 凌晨0:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jupyter/notebook] How to hide Run this cell button? (Issue #6811)





 
Thanks for submitting this issue @MrClearLovez! If you go to the Help -&gt; About button, could you share which frontend Jupyter application you are running?
