### ISSUE TITLE
`impor<tab>` -> `importimport`

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#6818]
Testing the new beta (7.0.0b0), good work BTW. 

Completion has this issue:

```
impor<tab><tab><tab><tab><tab><tab>
```

Lead to `importimport`

https://user-images.githubusercontent.com/335567/230024493-c12293bd-e3c9-4adf-9457-30868a9bfd24.mov

I believe the second import is inserted when the completer cycle back to the "top"

Also unclear why it does not cycle to `import: keyword` ?

No error in console.

**Comment by jtpio** [comment]
Thanks @Carreau for reporting this issue:

This also seems to be happening with JupyterLab `4.0.0b0`:

https://user-images.githubusercontent.com/591645/230029038-acda23e9-b0ee-4621-a9ad-c77c54dfde27.mp4

Would you mind reporting the issue in the JupyterLab repo? https://github.com/jupyterlab/jupyterlab

Once it is fixed there Notebook 7 can update to the latest JupyterLab packages to grab the fix.
