### ISSUE TITLE
Notebook 7, tree view should promote notebooks higher in the (default) tree view

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#6819]
Notebook 6 had made the explicit decision to have folders on top, followed by notebooks, then other files. 

As notebook7 will likely not be used to modify other type of files, it would be good to keep this ordering, or it may force users to unnecessarily scroll.

**Comment by jtpio** [comment]
This is what it looks like in the Classic Notebook:

![image](https://user-images.githubusercontent.com/591645/230101238-fda72e9a-d1d8-4001-9c57-4439b3e48d47.png)

Not sure this sorting is supported at the moment.

However this could probably be fixed upstream in JupyterLab as a file browser option. The option could let users choose `classic` (or similar) for sorting files and folders, which would ensure notebooks are placed at the top.

Would you like to open an issue in the JupyterLab repo to track this? https://github.com/jupyterlab/jupyterlab

**Comment by jtpio** [comment]
This will likely be fixed by https://github.com/jupyterlab/jupyterlab/pull/14497

**Comment by Carreau** [comment]
❤️
