### ISSUE TITLE
Multi cursors missing in notebook v7 ? 

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#6820]
It looks like having multiple cursor is gone in notebook 7, is that on purpose ? I'm guessing due to a difference codemirror version ?

**Comment by RRosio** [comment]
Hi @Carreau, I am not familiar with the multiple cursor, would you mind providing an example?

**Comment by Carreau** [comment]
Here you go, 


https://user-images.githubusercontent.com/335567/231412272-1968a56e-016f-4af8-a275-1d90a8ecde4f.mov

Ctrl/Cmd on mac, this seem to be related to https://github.com/jupyterlab/jupyterlab/issues/14105 ?

**Comment by jtpio** [comment]
Closing as this appears to be fixed in `7.0.0b2` now (likely grabbed the fix from JupyterLab during one of the updates):

https://github.com/jupyter/notebook/assets/591645/6576efe6-bf06-4923-92d8-b4a7712ee67a
