### ISSUE TITLE
Misc search and replace issues in notebook 7

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#6821]
1) It seem that codemirror hijack Ctrl-F on a per-cell level. This seem annoying
2) The F binding for the global search and replace is not present. 
3) "Replace" does often not work for me, only "Replace all".
4) Didn't we had a "replace all only in selected cell" at some point in the past ? I think a single dialog to either replace all, or in current/selected cell was an explicit decision in v6. 

For 3, yes I figured I had to click one of the arrow to have one of the item selected and yellow and then it seem to work, but it seem like there might be a bug somewhere.

https://user-images.githubusercontent.com/335567/230028730-b2af420f-ab29-4a29-b89b-9e9f25a4b837.mov

**Comment by jtpio** [comment]
cc @krassowski who might know more about this, since there are couple of open issues related to search and replace in JupyterLab: https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aopen+is%3Aissue+label%3A%22tag%3ASearch+and+Replace%22+

**Comment by jtpio** [comment]
> The F binding for the global search and replace is not present.

For reference this is a deliberate decision to match the Classic Notebook behavior and was originally implemented in https://github.com/jupyterlab/retrolab/pull/294#issuecomment-988712849.

**Comment by Carreau** [comment]
> (1) I do not understand. what did you expect?

I expect Ctrl-F in a cell to either get the global Search and Replace, or the Browser one. 

>> (2) The F binding for the global search and replace is not present.

> For reference this is a deliberate decision to match the Classic Notebook behavior and was originally implemented in https://github.com/jupyterlab/retrolab/pull/294#issuecomment-988712849.

I'm not sure if this means Yuvi's view is deliberate decision or Ctrl-F overriding is the deliberate decision.

I agree with Yuvi's comment, the classic notebook shortcut is `F` not `Ctrl-F`, plus notebook 7 is meant to help sunset notebook 6, so for notebook 6 users we are trying to make notebook 7 as seamless as possible. If you want a user story, say my grandmother is using notebook 6, I should be able to update her to notebook 7 and she should not notice it.

So the way I see it the default shortcut should be:
 - F (global search and replace same a menu click).
 - Ctrl-F/Cmd-F : browser search
That is to say same as notebook 6 i believe.


> (4) click the funnel icon, click "search in selection", select some cells and go to command mode. [...]

Hum, that seem too complicated and not discoverable. May I suggest to have at maximum a single button that expand the search (and replace) dialog ? That is to say only the arrow on the left to encompass both the "replace", and "filters" ?

**Comment by Carreau** [comment]
Also maybe the menu item should be `Find (and replace)...` instead of just `Find ...` ? 

And sorry for the noise, I know it's hard to view some of those things when working on a codebase, so I'm doing a qa-pass and listing anything that feel a tiny bit weird to me.

**Comment by krassowski** [comment]
> I expect Ctrl-F in a cell to either get the global Search and Replace, or the Browser one.

It gets global Search and Replace, so either condition is met. Or do you mean that you would like first hit of Ctrl-F to open our search and replace and second to open the browser one? This could be implemented as a setting but I do not see an issue for this. Worth opening one on JupyterLab repo?

> May I suggest to have at maximum a single button that expand the search (and replace) dialog ? 

There is a tradeoff between the overlay using up space and features being easily visible. I do not think we should merge replace and filters into a single expander, but I do agree that we should explore how to make both more discoverable.

> Also maybe the menu item should be `Find (and replace)...` instead of just `Find ...` ?

Or both?

**Comment by Carreau** [comment]
> It gets global Search and Replace, so either condition is met

No I don't get the global one I get the per-cell one.

https://user-images.githubusercontent.com/335567/231102641-bc60ed0b-d52b-438f-aad1-e7fe1ab7fe54.mov

In Classic, F -> Our Global search and replace, Ctrl-F -> Browser Search. I think we Should keep that.

Currently for me on my machine. 

Ctrl-F -> Codemirror S&R
?? -> Global
?? -> Browser.

>  I do not think we should merge replace and filters into a single expander

That's fine, I don't think it's a blocker, but I think you might have interacted of thought about it too much to see it with a fresh view.

There are reasons that dialog with only and "advanced" mode is pretty standard.

1) The filter button is literally just hiding 2 checkboxes. I just find it a bit over engineered for gain 10 px maybe, and unnecessarily hiding options in sub-menus.

2) the two buttons are high cognitive load for user, this search dialog has 4 states, (basic, filter, replace, filter and replace). That's definitively a UX smell.

3) The UI in inconsistant. You get sometime arrow for expanding options, and sometime buttons to toggle options (Case sensitivity, regex, ...), sometime buttons to expand options (filter), and sometime checkboxes, sometime you need to hover to know what buttons are doing, sometime they have labels next to it.

This would a big billions dollars company I would have guess two teams were in charge of the replace and filters options and did not coordinate.

I understand that this is _close_ to what VS code is doing but VS code payed attention to not have the Filter button to toggle the state the expanded dialog, but offer a drop-down, and the filter button is _inside_ the search field. 

But again I think it's minor.

**Comment by Carreau** [comment]
The latest version of Notebook is much better. The per-cell search is one of the last things that I find confusing in the UI.

Awesome work on the rest

**Comment by jtpio** [comment]
@Carreau do you think there are still some outstanding issue with the latest `7.0.0b3` release w.r.t search and replace?

Or could this issue be closed?

**Comment by jtpio** [comment]
OK thanks @Carreau.

Then let's close the issue and we can open more specific ones if needed.
