### ISSUE TITLE
V7 many shortcut displayed many times in help

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#6823]
<img width="492" alt="Screen Shot 2023-04-05 at 10 57 03" src="https://user-images.githubusercontent.com/335567/230033100-7ae61d98-6b40-44c9-ad1f-4c52faec43c8.png">
<img width="459" alt="Screen Shot 2023-04-05 at 10 57 31" src="https://user-images.githubusercontent.com/335567/230033105-b5d64874-3fc1-46ca-b5d4-a1252c89141d.png">

**Comment by jtpio** [comment]
This might be fixed upstream by https://github.com/jupyterlab/jupyterlab/pull/14053

**Comment by jtpio** [comment]
@Carreau would you be able to check again with `7.0.0b2` or higher? It should now use the same shortcuts dialog as in JupyterLab 4. Thanks!
