### ISSUE TITLE
V7 Menu "Show line number" does not show it's corresponding shortcut.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#6824]
Though the shortcut (`Shift L`) works

**Comment by jtpio** [comment]
Thanks @Carreau.

Just checked and it is also not displayed in JupyterLab (latest `main` as of today):

![image](https://github.com/jupyter/notebook/assets/591645/c5049c4e-55e4-4723-be8d-0a79afa7f3db)


So we can probably open the issue there to track this.

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/issues/14689, thanks for reporting!
