### ISSUE TITLE
V7: Untrusted notebook on releoad.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#6828]
V7 seem to emit invalid notebooks. 

I see the following in the terminal

```
MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)
```

This seem to prevent notebooks to be trusted.

**Comment by jtpio** [comment]
This was recently investigated in https://github.com/jupyterlab/jupyterlab/issues/14025.

With some incremental improvements upstream in https://github.com/jupyterlab/jupyterlab/pull/14039.

cc @krassowski who probably knows more about it

**Comment by jtpio** [comment]
Nice, thanks @krassowski!

**Comment by krassowski** [comment]
> MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.

If nbformat is fixing the issue transparently, then it should not be the reason for untrusted notebook, right? I opened https://github.com/jupyter/nbformat/issues/359 to discuss.

**Comment by krassowski** [comment]
@Carreau would you be able to provide a bit more detailed reproduction steps? I could not replicate this behaviour. Both Notebook and Lab emit notebooks with cell IDs present for me.

**Comment by Carreau** [comment]
Hu, I can't in a fresh env... This is weird. Maybe there is a sequence of interaction that create a cell that has no ID... I'll close this for now and reopen if I encounter it again.
