### ISSUE TITLE
improve dev Install instruction on (Linux/ubuntu)

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#685]
I've tried the dev-install instruction on ubuntu yesteday on someones laptop. 

Even after 30min of tinkering I was completely unable to install the notebook. 
In particular `node` was `nodejs`, I had to `apt-get install  npm`, bower was requiring `sudo`, and was calling `/usr/bin/env node` instead of `nodejs`, even though the `sudo python setup.py [css|js|...]` failed at various step, and reconstructing the command to run by hand was a pain. 

I'm not sure if it was this particular system, or a more general linux/ubuntu case, 
as in particular it seem to work flawlessly on Travis.

**Comment by willingc** [comment]
@Carreau Thanks for sharing. Python 2 or 3 or both? I think there is an ubuntu difference than the general linux.

**Comment by Carreau** [comment]
3 in my case, but the issues where not python-version specific. They where more with Javascript/css building tools (invoked through python though).

**Comment by willingc** [comment]
Did you happen to dump the screen? It may be some weirdness with ubuntu and purging node/nodejs before installing again.

I will try to check on my ubuntu laptop later.

**Comment by Carreau** [comment]
it was a mixed of issues, like no permission to write to /user/local, nodejs being a different name, and so on an so forth, so really hard to debug fro lambda user.

**Comment by Jeffiy** [comment]
Yeah, I had the same problems too, and I tried so many times to build it, especially building css/js.

**Comment by damianavila** [comment]
@Carreau did you try a conda-based installation... you can get nodejs and bower easily from the javascript channel... it should reduce your pain a lot...
