### ISSUE TITLE
Add the "Click to add a cell" button

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6852]
https://github.com/jupyter/notebook/pull/6838 updated to JupyterLab `4.0.0b2` but disabled the "Click to add a cell" button:

![](https://user-images.githubusercontent.com/591645/234590241-4911773c-2aa8-41eb-8867-082d97ed739c.png)

It's a useful feature and should be re-enabled.

**Comment by jtpio** [comment]
Related issue: https://github.com/jupyterlab/jupyterlab/issues/14453

**Comment by BrahmDevPandey** [comment]
Can I take this issue??

**Comment by jtpio** [comment]
This should also fix https://github.com/jupyter/notebook/issues/6389

**Comment by jtpio** [comment]
@BrahmDevPandey the latest `main` should now include the changes from https://github.com/jupyterlab/jupyterlab/issues/14453. So it should be possible to resume work on this if you would like to.

Likely the only change is to remove these two lines:

https://github.com/jupyter/notebook/blob/573becfa6470ce2b9b1a1451c5a54955d57b9c7a/packages/notebook-extension/style/base.css#L127-L128

Thanks!
