### ISSUE TITLE
Advanced Settings editor does not show anything

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6854]
Likely related to #6838 or #6853 

![image](https://user-images.githubusercontent.com/591645/235080295-1206599e-569b-4fae-8b60-0575b3543f34.png)

**Comment by jtpio** [comment]
Fixing this should add UI tests to help catch such regressions in the future.

**Comment by jtpio** [comment]
Actually seems to be an issue in JupyterLab:

![image](https://user-images.githubusercontent.com/591645/235080776-e3a77cc1-8615-4ecb-9866-2148a3e042dc.png)

**Comment by jtpio** [comment]
Upstream issue: https://github.com/jupyterlab/jupyterlab/issues/14454

**Comment by andrii-i** [comment]
Looking into https://github.com/jupyterlab/jupyterlab/issues/14440

**Comment by andrii-i** [comment]
https://github.com/jupyterlab/jupyterlab/pull/14486 would transitively fix this. 

Am I correct that for Notebook to get this fix, a version of the JupyterLab including the fix should be released and then Notebook would neeed to update dependency to the new version of JupyterLab?

**Comment by jtpio** [comment]
> Am I correct that for Notebook to get this fix, a version of the JupyterLab including the fix should be released and then Notebook would neeed to update dependency to the new version of JupyterLab?

Yes that's correct.

**Comment by andrii-i** [comment]
PR https://github.com/jupyterlab/jupyterlab/pull/14486 was merged but it does not have a test case as [described in this comment](https://github.com/jupyterlab/jupyterlab/pull/14486#issuecomment-1533985891) (could use an advise too). I created issue https://github.com/jupyterlab/jupyterlab/pull/14486 to track the need for the test case.
