### ISSUE TITLE
Missing clear all output action ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#686]
Came across that yesterday.

**Comment by Carreau** [comment]
(not sure if worth for 4.1)

**Comment by ellisonbg** [comment]
I can take a go at this. I ran into a few other related things that sort of
go with this.

On Thu, Oct 29, 2015 at 1:00 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> (not sure if worth for 4.1)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/686#issuecomment-152249124>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Actually I think this is because we havent' finished moving al menus to actions.

**Comment by Carreau** [comment]
Should I tag this as 4.1 ?

**Comment by minrk** [comment]
If you want, sure. No harm in marking now and then punting if we don't get around to it.

**Comment by Carreau** [comment]
closed by #692

**Comment by eromoe** [comment]
Hi, I still can't find `clear-all-cells-output` in jupyter 4.2.1
