### ISSUE TITLE
V7b1: Nbconvert jumps to the wrong link in collaboration mode

### ISSUE THREAD

**Issue by minger233** [jupyter/notebook#6863]
**Describe the bug**
Nbconvert jumps to the wrong link in collaboration mode.

**To Reproduce**
1. Install and activate jupyter-collaboration
2. Open any `.ipynb` file
3. File - Save and Export Notebook As - LaTeX (or other options)
4. The server returns 404, because the the browser goes to  `/nbconvert/latex/RTC%3AFILENAME.ipynb?download=true` instead of `/nbconvert/latex/FILENAME.ipynb?download=true`

**Expected behavior**
the browser goes to  `/nbconvert/latex/FILENAME.ipynb?download=true`

**Screenshots**
![image](https://user-images.githubusercontent.com/83628655/236789656-2a9ba8d8-0d4a-4051-b1d2-5a682d0b21a2.png)

![image](https://user-images.githubusercontent.com/83628655/236790683-ad03bc78-e589-4df5-844d-87c7e6355953.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Edge (Chromium)
- Server Version:
CentOS : LSB Version core-4.1-amd64:core-4.1-noarch
Conda Version: 23.3.1
Python : 3.10.9
IPython : 8.13.1
ipykernel : 6.22.0
ipywidgets : not installed
jupyter_client : 8.2.0
jupyter_core : 5.3.0
jupyter_server : 2.5.0
jupyterlab : 4.0.0rc0
nbclient : 0.7.4
nbconvert : 7.3.1
nbformat : 5.8.0
notebook : 7.0.0b1
qtconsole : not installed
traitlets : 5.9.0

**Comment by JasonWeill** [comment]
Can you please open this issue in https://github.com/jupyterlab/jupyter_collaboration/ instead? This is the repository where our Real Time Collaboration (RTC) code now lives. Please close this issue once you've opened one in the RTC repo. Thanks!

**Comment by minger233** [comment]
> Can you please open this issue in https://github.com/jupyterlab/jupyter_collaboration/ instead? This is the repository where our Real Time Collaboration (RTC) code now lives. Please close this issue once you've opened one in the RTC repo. Thanks!

OK, thanks!
