### ISSUE TITLE
asyncio.create_subprocess_exec throws NotImplementedError in Windows and notebook 6.5.4

### ISSUE THREAD

**Issue by kumaranvpl** [jupyter/notebook#6882]
Hello,

Following is the test code I have taken from python docs - https://docs.python.org/3/library/asyncio-subprocess.html#examples

```
import asyncio
import sys

async def get_date():
    code = 'import datetime; print(datetime.datetime.now())'

    # Create the subprocess; redirect the standard output
    # into a pipe.
    proc = await asyncio.create_subprocess_exec(
        sys.executable, '-c', code,
        stdout=asyncio.subprocess.PIPE)

    # Read one line of output.
    data = await proc.stdout.readline()
    line = data.decode('ascii').rstrip()

    # Wait for the subprocess exit.
    await proc.wait()
    return line

date = await get_date()
print(f"Current date: {date}")
```

If I execute the above code in a cell, then it throws `NotImplementedError`. This behavior was mentioned in this [issue](https://github.com/jupyter/notebook/issues/5916) also.
I am using windows. My library versions are python version 3.11.3, notebook version 6.5.4 and ipykernel version 6.23.1.

1. Install latest version of jupyter and run it in windows machine
2. Copy the above code to cell and execute it

**Screenshots**
![image](https://github.com/jupyter/notebook/assets/7011056/2ee12a51-a7ff-414a-9421-97007ffed623)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: python version 3.11.3, notebook version 6.5.4 and ipykernel version 6.23.1

**Comment by kumaranvpl** [comment]
@RRosio Yup. I am still seeing this issue. Sorry for replying late.

**Comment by JasonWeill** [comment]
It looks like this is a limitation of running `ipykernel` in Windows that has been known for over 4 years: https://github.com/ipython/ipykernel/issues/391 .

Please follow up on the issue above. It looks like this isn't a Jupyter Notebook issue specifically. Thanks for your contribution!
