### ISSUE TITLE
Unable to create new notebook or open an existing notebook

### ISSUE THREAD

**Issue by bocchi-otaku** [jupyter/notebook#6889]
Hello, I'm having problem opening notebook file or creating a new notebook. I used PowerShell v7, and I could run the notebook by typing `jupyter notebook`. But if I try to open an existing notebook or create a new notebook, it failed.
![jupyter_issue](https://github.com/jupyter/notebook/assets/48517391/8b6ee79b-403b-4f37-9fe2-671288861a10)
When I check the PowerShell, it seems that the notebook is shutdown without any error message. Following is the full message in PowerShell from starting the notebook to unexpected shutdown.
![powershell](https://github.com/jupyter/notebook/assets/48517391/ac1406cd-c3e9-4353-b893-56cb5922d750)
My system info is as follows
- OS: Windows 11 22H2 22621.1778
- Browser: Chrome 113.0.5672.127
- ipython: 8.13.2
- python: 3.10.11

**Comment by bocchi-otaku** [comment]
> Thank you for the updated information @bocchi-otaku! Unfortunately, there was nothing much more helpful in the additional output from the detailed log.
> 
> If I understand correctly, you were previously able to run `jupyter notebook` successfully, but you are no longer able to do so? Can you share of any browser extensions or security software that you may have turned on/installed in between the time when `jupyter notebook` ran fine on your system and then stopped?

There are some misunderstanding. 
The situation is I can run `jupyter notebook`, but I can't create new notebook file nor opening existing 'ipynb' file. The notebook would disconnect without warning if I try to create or open notebook file. I recorded a video to show you the problem. https://youtu.be/degVt7MzRH4

I also tried to disable all Chrome extensions, not working.

**Comment by bocchi-otaku** [comment]
> Thanks for the clarifications @bocchi-otaku, especially appreciate the video! I've browsed around for similar issues and have only found a few which ended up being resolved through user actions. The two I found are: [one on discourse](https://discourse.jupyter.org/t/not-able-to-create-new-notebook-or-open-exisiting-notebooks/7531/5) and #4510. Because the notebook process terminates without a discernible error on the terminal I am inclined to say that this is likely not an issue with Notebook but rather something with the host environment affecting it.

I see. I guess none of those solutions in that two posts work for me. Thank you for your help though.

I guess this might be some weird bug with Windows or some package version. In the shell screenshot you can see that I was using a ds environment. All the packages in that environment was installed thourgh conda-forge channel. However if I just install all the packages in base environment using `pip` without any specification, everything works just fine.

Anyway I can use jupyter noterbook in the base environment so I should be fine. Thank you again!

**Comment by JasonWeill** [comment]
Thank you @bocchi-otaku for your contribution! It looks like this is not necessarily an error in Jupyter Notebook, so I'm going to close this issue. If you find any other problems, please open another issue or ask in another support channel, like Discourse.
