### ISSUE TITLE
Notebook v7 JupyterHub Integration

### ISSUE THREAD

**Issue by tuncbkose** [jupyter/notebook#6904]
In looking at the [v7.0.0b3](https://github.com/jupyter/notebook/releases/tag/v7.0.0b3) release, I didn't notice any JupyterHub integrations. 

In JupyterLab, there is the `hub-extension` package. Are there any plans of including that in v7 or providing similar functionality?

**Comment by jtpio** [comment]
Thanks @tuncbkose for raiding raising this question.

I believe Notebook 7 is already being used with JupyterHub in some deployments so it should already work with JupyterHub.

For reference the `hub-extension` was added in https://github.com/jupyterlab/retrolab/pull/148 (when Notebook 7 was still RetroLab). And it is still part of Notebook 7 here:

https://github.com/jupyter/notebook/blob/245bc87ecf56b5a86be0595bc86f709110340859/app/package.json#L57

**Comment by jtpio** [comment]
@tuncbkose would you be able to check if Notebook 7 is working as expected on JupyterHub?

**Comment by tuncbkose** [comment]
@jtpio Could you take a look at a convenient time or restore the Needs Triage label?

**Comment by andrii-i** [comment]
Moving to 7.0.x for further follow up after Notebook 7 release. Please feel free to move it back if necessary.

**Comment by jtpio** [comment]
Taking a closer look, the JupyterLab plugin expects `hubPrefix` to be defined here to add the menu entries:

https://github.com/jupyterlab/jupyterlab/blob/86326b258138b9d0413de77089c83d5ec95c6a4e/packages/hub-extension/src/index.ts#L49-L52

It also passes the the `hubPrefix` option as part of the page config here:

https://github.com/jupyterlab/jupyterlab/blob/86326b258138b9d0413de77089c83d5ec95c6a4e/jupyterlab/labapp.py#L827-L848

But Notebook 7 uses the same approach here:

https://github.com/jupyter/notebook/blob/bf42a0c797a1ce49361e896cc7b7af3ac865370d/notebook/app.py#L61-L72

So normally the `hubPrefix` should be available on the frontend and be activated.

**Comment by jtpio** [comment]
I tried aligning the JupyterHub config in https://github.com/jupyter/notebook/pull/6918 but it looks like the `hub_prefix` option is not set correctly when Notebook 7 is started first, which means the menu items are not visible.

Digging a bit into the JupyterHub code base, there is a single user app that looks for the `NotebookApp` and `ServerApp` and tries to perform some logic depending on which one it finds: https://github.com/jupyterhub/jupyterhub/blob/main/jupyterhub/singleuser/app.py

In Notebook 7 the class is not `NotebookApp` anymore but `JupyterNotebookApp` (to not conflict with the classic notebook shims), so maybe that's why:

https://github.com/jupyter/notebook/blob/bf42a0c797a1ce49361e896cc7b7af3ac865370d/notebook/app.py#L240

**Comment by jtpio** [comment]
cc @yuvipanda who might know what needs to be done here to have Notebook 7 and the "Hub Control Panel" menu to work with JupyterHub.

**Comment by jtpio** [comment]
Actually it seems to be showing the menu entries correctly if the `jupyter-labhub` is specified as the spawner command and using the changes from https://github.com/jupyter/notebook/pull/6918.

This is the configuration I used for testing, inspired by https://github.com/jupyterhub/jupyterhub/blob/main/testing/jupyterhub_config.py:

```py
c = get_config()  # noqa

from jupyterhub.auth import DummyAuthenticator

c.JupyterHub.authenticator_class = DummyAuthenticator

# Optionally set a global password that all users must use
# c.DummyAuthenticator.password = "your_password"

from jupyterhub.spawner import SimpleLocalProcessSpawner

c.JupyterHub.spawner_class = SimpleLocalProcessSpawner

# only listen on localhost for testing
c.JupyterHub.bind_url = 'http://0.0.0.0:8000'

c.JupyterHub.default_url = '/tree'
c.Spawner.cmd = ["jupyter-labhub"]
```

After starting a new server: 

https://github.com/jupyter/notebook/assets/591645/b7c90edf-5737-4897-a188-eda0aaf01c6f

**Comment by jtpio** [comment]
So I think https://github.com/jupyter/notebook/pull/6918 should already help with this issue.

Then I suspect using `c.Spawner.cmd = ["jupyter-labhub"]` will be needed for the menu entries (and the underlying lab extension) to work properly in Notebook 7.

**Comment by tuncbkose** [comment]
Thank you for investigating this!

**Comment by jtpio** [comment]
@tuncbkose let us know if you are able to test the latest changes on the `main` branch now that https://github.com/jupyter/notebook/pull/6918 is merged, using the `jupyter-labhub` spawner command.

Otherwise we'll try to get the release candidate out this week.

**Comment by tuncbkose** [comment]
With #6918 and the configuration you provided, I am able to see the buttons now. Thanks again!

**Comment by jtpio** [comment]
Nice, and thank you for trying the Notebook 7 beta!
