### ISSUE TITLE
Rename browser tab title to Home

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6912]
Currently the browser tab says "Jupyter Notebook - Tree" when on the file browser page:

![image](https://github.com/jupyter/notebook/assets/591645/b59bcc5d-3f78-485f-8fb1-c7fdd882db2a)

However the classic notebook UI shows "Home" in its title:

![image](https://github.com/jupyter/notebook/assets/591645/5d8e9fb1-a674-412e-882c-a64ccf0bf42e)

This is likely just a matter of replacing the following text in `<title>` here by "Home":

https://github.com/jupyter/notebook/blob/82703a67c35dc4dd5532397737c858862f9d062f/notebook/templates/tree.html#L6

**Comment by Cheukting** [comment]
I will have a look in a few hours so or
