### ISSUE TITLE
jupyterlab-myst does not render admonitions under nb7

### ISSUE THREAD

**Issue by parmentelat** [jupyter/notebook#6915]
**Describe the bug**

the jupyterlab-myst extension does not work as expected in nb7

**To Reproduce**

1. install jlab4 as released in pip
2. install nb7 with `pip install -U --pre notebook`
3. install jupyterlab-myst with  
  `pip install git+https://github.com/executablebooks/jupyterlab-myst.git@agoose77/feat-jupyterlab-v4`
4. create a notebook with a simple admonition
5. open in jlab and check that the admonition renders properly
6. open the same notebook in nb7, the admonition is not rendered

**Expected behavior**
the extension should behave the same under both envs

**Screenshots**

the view under jlab

![image](https://github.com/jupyter/notebook/assets/4519227/290325fb-44b9-476d-897b-1d6940264001)

under nb7

![image](https://github.com/jupyter/notebook/assets/4519227/039a8ba5-7678-4088-ad51-1895e3f4919d)

**Desktop (please complete the following information):**

- OS: \[e.g. iOS\] MacOS & linux
- Browser \[e.g. chrome, safari\] - chrome
- Version \[e.g. 22\]

* jlab 4.0.2
* notebook 7.0.0b4
* as of this writing, https://github.com/executablebooks/jupyterlab-myst.git@agoose77/feat-jupyterlab-v4 is on commit b405903
 

**Additional context**

https://discourse.jupyter.org/t/generic-question-about-jlab4-and-nb7/19846

**Comment by jtpio** [comment]
Thanks @parmentelat for the detailed report.

Is there an error in the browser dev tools console?

**Comment by parmentelat** [comment]
yes indeed, and quite a few :)

like for the other issue #6914 I will try this again in a clean slate environment, and will then report the console errors 

while doing so I will also be careful to not install any other extension, because I'm starting to believe I may have experienced unplanned interferences from others exts.

**Comment by jtpio** [comment]
> 3\. install jupyterlab-myst with
>         `pip install git+https://github.com/executablebooks/jupyterlab-myst.git@agoose77/feat-jupyterlab-v4`

ok I just checked locally and this indeed works in lab: 

![image](https://github.com/jupyter/notebook/assets/591645/62f4e4c1-d3c3-467d-b328-bea8a984e119)

But not in Notebook 7:

![image](https://github.com/jupyter/notebook/assets/591645/b04ccc09-cbe0-4e5a-83fc-8758ec054148)

The error in Notebook 7 is the following:

```
Shared module @jupyterlab/markdownviewer doesn't exist in shared scope default
```
