### ISSUE TITLE
Corrupted URL when upgraded to Jupyter Notebook version 7.0.0rc0 and Jupyter Lab version 4.0.2

### ISSUE THREAD

**Issue by balajialg** [jupyter/notebook#6940]
**Describe the bug**

The URL to launch the notebook got corrupted when we upgraded the Jupyter Notebook version to 7.0.0rc0 and the Jupyter Lab version to 4.0.2 (JN version 7.0.0rc0 warranted an upgrade from 4.0.0 to 4.0.2 in Lab). When we launch the hub, it loads a URL - Hub_URL/user/xx/user/xx/user/xx/lab that repeats "user/username" thrice and as a result returns a 404 error. This has been reported by multiple users within Berkeley who tested the deployment. Previously, we had Notebook 7.0.0b3 and Lab 4.0.0 which did not have the URL corruption issue.

I am not sure whether this is a Lab specific issue or a notebook-specific issue. Please redirect me to the right repository if I am mistaken here. @ryanlovett 

**To Reproduce**

1. Upgrade Notebook to 7.0.0rc0 
1. Upgrade Lab to 4.0.2
1. Try launching the hub
1. See 404 error because of URL getting corrupted

**Expected behavior**
Notebook should launch without any URL corruption issues

**Screenshots**
![image](https://github.com/jupyter/notebook/assets/2306166/0502ae05-2662-471d-a18f-c259f7bfcf50)

**Desktop (please complete the following information):**

- OS: Windows/Mac
- Browser: Firefox/Safari

**Additional context**

**Comment by jtpio** [comment]
Many thanks @balajialg for trying the rc and reporting the issue :+1: 

This change might be related since it realigned how the JupyterHub config was handled with what JupyterLab does: https://github.com/jupyter/notebook/pull/6918

Not sure yet but maybe it's related.

If you are able to try with `7.0.0b4` then we could see if this is an issue with `7.0.0rc0` only.

**Comment by balajialg** [comment]
@jtpio Sure, I will definitely test 7.0.0b4 version and report the results here!

**Comment by balajialg** [comment]
@jtpio From our initial investigation (@ryanlovett and myself), the error seems to persist even after downgrading to notebook version `7.0.0b3`. We tried to check whether it was due to lab and downgraded lab to `4.0.1` and the error persisted. We also tried to downgrade the lab to `4.0.0` but the build failed with the following error,

```
The conflict is caused by:
    The user requested jupyterlab==4.0.0
    notebook 7.0.0b4 depends on jupyterlab<5 and >=4.0.1
```

**Comment by jtpio** [comment]
Thanks @balajialg for the input.

Then looking at the `7.0.0b4` changelog it could be because of this change https://github.com/jupyter/notebook/pull/6899.

**Comment by jtpio** [comment]
FYI @balajialg `7.0.0rc1` is released: https://github.com/jupyter/notebook/releases/tag/v7.0.0rc1

Let us know if that fixes the issue, thanks!

**Comment by jtpio** [comment]
Just opened https://github.com/berkeley-dsep-infra/datahub/pull/4671

**Comment by balajialg** [comment]
That's great. Thanks @jtpio! We will test rc1 and give you an update wrt resolution!

**Comment by balajialg** [comment]
@jtpio Upgrade to rc1 seems to have fixed the issue for me. I will let @ryanlovett test the deployment and confirm this. Thanks a lot for the quick fix!

**Comment by ryanlovett** [comment]
@balajialg Confirmed!

**Comment by jtpio** [comment]
Nice, thanks @balajialg and @balajialg for checking!
