### ISSUE TITLE
Styling error of running notebook list

### ISSUE THREAD

**Issue by jhamrick** [jupyter/notebook#695]
The styling on the list of running notebooks appears to be messed up:

![image](https://cloud.githubusercontent.com/assets/83444/10860659/c7f6c38a-7f28-11e5-97d4-1aea8da63a0f.png)

Running on most recent master.

**Comment by Carreau** [comment]
Can't reproduce but saw it on @jhamrick screen which is on master and on same chrome version than me (46)

**Comment by jhamrick** [comment]
Happens for other kernel types, too. Not terminals though:

![image](https://cloud.githubusercontent.com/assets/83444/10860868/0e076f6a-7f2d-11e5-9528-687262d4fa4d.png)

**Comment by jhamrick** [comment]
Needed to update javascript components, bleh.
