### ISSUE TITLE
Notebook 7.0.0 ignores kernel's help_links property

### ISSUE THREAD

**Issue by culler** [jupyter/notebook#6963]
### Problem

With Classic Jupyter and Jupyter Lab, when a kernel is selected to be used by a notebook, the kernel's help_links property is read and the contents are used to add kernel-specific items to the Help Menu.  This useful feature appears to have been removed from Notebook 7.0.0.  Testing with the SageMath kernel, which provides help_links as a property, indicates that the help_links getter is never called when a SageMath notebook is launched.

### Proposed Solution

Please consider restoring this feature (or documenting it, if it actually exists in some other form.)

**Comment by culler** [comment]
Thanks for responding @RRosio.  No, I do not see this problem with jupyterlab-4.0.2 installed from pypi.  It takes a few seconds, but the Help menu gets populated with all of the links provided by the SageMath kernel.

I am not at all sure this is relevant, but in the index.tsx file for the Jupyter Lab help-extension I see the following code, for which I could not find an analog anywhere in the notebook source tree:

```
    // Populate the Help menu.
    const helpMenu = mainMenu.helpMenu;

    const resourcesGroup = resources.map(args => ({
      args,
      command: CommandIDs.open
    }));
    helpMenu.addGroup(resourcesGroup, 10);

    // Generate a cache of the kernel help links.
    const kernelInfoCache = new Map<
      string,
      KernelMessage.IInfoReplyMsg['content']
    >(); 
```

**Comment by jtpio** [comment]
Thanks @culler for reporting and trying Notebook 7.

Maybe it would just be a matter to include the `@jupyterlab/help-extension:resources` plugin in Notebook 7 to get these menu entries.

**Comment by culler** [comment]
Maybe sol I don't know.  But I would hope that the extension could be enabled by the kernel, or by configuring the notebook package in advance before distributing it with the SageMath application, rather than require that a user know that using the kernel requires running the enable command.

**Comment by culler** [comment]
Thank you!!!!

**Comment by culler** [comment]
I was wondering if this could be finished up now.  It looks like the jupyterlab dependency has been released.

**Comment by jtpio** [comment]
Good point, thanks @culler for the ping :+1:

**Comment by jtpio** [comment]
Actually we still need to wait for this repo to update to the JupyterLab 4.1 packages first.
