### ISSUE TITLE
Document development install

### ISSUE THREAD

**Issue by jhamrick** [jupyter/notebook#697]
There should be instructions in the README (or at least linked to from the README) on how to setup a development install. If this information is documented somewhere, it is at least not easily accessible. Things that should ideally be included in this:

* [x] post-checkout hooks for updating and recompiling javascript and css
* [x] instructions for how to install post-checkout hooks
* [x] instructions for how to update js components, compile js, and compile css
* [x] instructions for how to run the test suite

**Comment by willingc** [comment]
@jhamrick For the benefit of others until we get the above completed, there is some info in the existing README file, scattered info in issues, and some in the docs themselves. Huge +1 to consolidating.
