### ISSUE TITLE
"New View for Notebook" is unaccessible

### ISSUE THREAD

**Issue by aakhmetz** [jupyter/notebook#6984]
![image](https://github.com/jupyter/notebook/assets/2173206/f739c004-7441-4045-8e2f-26941e6ea6f5)

I am not sure why but many options like "New View for Notebook" became unaccessible for me. I am running in ArchLinux with the latest update installed.

**Comment by jtpio** [comment]
Thanks @aakhmetz for reporting.

This screenshot appears to be for JupyterLab. Would you be able to open the issue on the JupyterLab repo? https://github.com/jupyterlab/jupyterlab

**Comment by aakhmetz** [comment]
Ah, sorry! my mistake
