### ISSUE TITLE
JN 7 → Code Folding starts at the first line regardless the type

### ISSUE THREAD

**Issue by MichalRIcar** [jupyter/notebook#6987]
Hi, 

Jupyter Notebook 7:

I would like to propose to be able to fold any cell by the first line of text regardless its type.

Reasoning of it is that in many scenarios we have a cell with certain description and funcionality in some type of representation, flow. 

Once user of a Notebook reads instructions, it is not necessary to keep the whole cell unfolded, actually it is very beneficial to allow to fold the whole cell keeping only the first row (likely a Title of a cell).

E.g. cell worthy to read and then fold it to see only a title "The Generator X"
Cell:
```
# The Generator X
# This function produces...
A = FunctionX()

# Callable Output
#...
```

Best,
Michal

**Comment by krassowski** [comment]
The way I read it, this basically requests what was already implemented in https://github.com/jupyterlab/jupyterlab/pull/14141

![Screenshot from 2023-08-01 17-45-39](https://github.com/jupyter/notebook/assets/5832902/8f4493d9-5ec9-4afb-b84f-b721c4f157ef)

@MichalRIcar is this correct?

**Comment by MichalRIcar** [comment]
Hi,

I will use an example from JN 6 with this feature on via codefolding extension:

Before Folding
![image](https://github.com/jupyter/notebook/assets/62614119/2320d8a8-5278-4263-b978-1da8f4f0dd7e)

After Folding
<img width="262" alt="image" src="https://github.com/jupyter/notebook/assets/62614119/e37f2752-cd25-4649-a92f-dc20b0be3845">

**Comment by MichalRIcar** [comment]
As we can see, the "old" codefolding allowed to fold any cell by its first line regardless of its type..very useful feature in notebook presentation.

**Comment by krassowski** [comment]
Sorry but I still do not see how it differs from what was implemented in https://github.com/jupyterlab/jupyterlab/pull/14141.

**Comment by MichalRIcar** [comment]
@krassowski, thank you for pointing this out. You are absolutely correct that these two options are almost identical. However, I can only access the cell collapsing feature through the 'View' menu by selecting 'Collapse Selected Code' or 'Collapse All Code.' Perhaps I'm just missing some optional feature in Jupyter Notebook 7 because I don't see any dynamic option inside a cell to fold a whole code cell - similarly as we see in the example above? 

Or idea behind this feature in JN7 is to not provide code folding in a code cell and force user to use View option? Originally, I though it will be among these..
![image](https://github.com/jupyter/notebook/assets/62614119/a00021a1-612c-46f5-914c-65b141dfa725)

**Comment by krassowski** [comment]
You can click on the blue bar next to the cell:

![click-clock](https://github.com/jupyter/notebook/assets/5832902/d6d2e1fa-22ca-4f07-b308-79ab66f54be0)

This is somewhat documented in JupyterLab [user guide](https://jupyterlab.readthedocs.io/en/latest/user/notebook.html) but not in notebook itself. I think we should move the Notebook content User Guide to this repo (recreating videos using playwright) and then just embed it in JupyterLab docs.

**Comment by MichalRIcar** [comment]
Right! That was the first thing I tried and it doesn't work even though I have code folding allowed everywhere in Settings..

**Comment by MichalRIcar** [comment]
Is this dynamic bar folding connected with some other setup in the JN Settings?

**Comment by krassowski** [comment]
Can you provide a recording and check if there are any errors in the [JS console](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_developer_tools#the_javascript_console)?

**Comment by MichalRIcar** [comment]
Absolutely, I've just checked that in JL it works indeed..but JN no luck.

**Comment by MichalRIcar** [comment]
JS concole has these errors and tons of warnings
![image](https://github.com/jupyter/notebook/assets/62614119/dcb72c4b-23a3-4f88-9b01-55593a0fe232)

**Comment by MichalRIcar** [comment]
Warnings
![image](https://github.com/jupyter/notebook/assets/62614119/98a49d88-6c92-4bb0-a5ec-611b3109798c)

**Comment by jtpio** [comment]
The collapsing issue might be similar to the one reported in https://github.com/jupyter/notebook/issues/7020

**Comment by tmatsuzawa** [comment]
This active code folding is broken on my machine. I just installed the latest jupyter notebook.

**Comment by krassowski** [comment]
I tested this in Notebook 7.2.0 which was recently released and it works well 

@MichalRIcar and @tmatsuzawa can you confirm that it works with Notebook 7.2?

**Comment by MichalRIcar** [comment]
Hello @krassowski, thank you for following up on this important feature! 

Good news is that now I can fold the very first cell, however, any other cell is still static - the blue left bar doesn't allow folding, doesn't change color when I move mouse on it like the first cell.

I have tried it using Chrome and Edge and the behavior is identical. 
In Edge (only) the first cell once folded shrinks to approx. half length aligned to the right leaving half space as background as picture shows
![image](https://github.com/jupyter/notebook/assets/62614119/264a8ccf-0f80-4462-86dc-91b27f11a083)

**Comment by krassowski** [comment]
>  I can fold the very first cell, however, any other cell is still static

This is very helpful, I can reproduce this. This is a CSS problem - another element obstructs the collapser so that it cannot be clicked. 

https://github.com/jupyter/notebook/blob/433f18094d80398a4898dc894265d129a5ad19a4/packages/notebook-extension/style/base.css#L154-L165

It looks like it was originally added in https://github.com/jupyter/notebook/pull/6433, but I do not understand why because it does not seem to do anything other than preventing clicking on the cell collapsed. @trungleduc do you remember if this was intentional? If not, these lines can be removed to fix the issue.

**Comment by trungleduc** [comment]
Sorry for my late reply, I missed the notification. 

> It looks like it was originally added in https://github.com/jupyter/notebook/pull/6433, but I do not understand why because it does not seem to do anything other than preventing clicking on the cell collapsed. @trungleduc do you remember if this was intentional? If not, these lines can be removed to fix the issue.

IIRC at this time, it was quite hard to have the same shadow visual as the old notebook due to the structure of the cell widgets. So I need to add pseudo-elements to apply the shadow effect.
