### ISSUE TITLE
Open Jupyter Notebook documentation website from Help menu

### ISSUE THREAD

**Issue by fcollonval** [jupyter/notebook#6992]
### Problem

There is no help menu entries to open https://jupyter-notebook.readthedocs.io/en/stable/ in the Help menu

### Proposed Solution

Add some menu entries to help allowing to open the Jupyter Notebook documentation website

### Additional context

Notebook 7.0.0

**Comment by jtpio** [comment]
Marking as "good first issue".

If someone would like to give it a try, maybe the simplest would be to add an entry to the resources here:

https://github.com/jupyter/notebook/blob/2270c0443597e765fef2917af1d7ff350fec8479/packages/help-extension/src/index.tsx#L22-L31

**Comment by Mikil03** [comment]
hey i am new to this can you tell me how to run on windows to check working of code

**Comment by jtpio** [comment]
Here is the contributing guide: https://jupyter-notebook.readthedocs.io/en/stable/contributing.html

Thanks!
