### ISSUE TITLE
Respect bootstrap CSS

### ISSUE THREAD

**Issue by flying-sheep** [jupyter/notebook#7]
stuff like [unstyled and inline lists](http://getbootstrap.com/css/#type-lists) should work

**Comment by minrk** [comment]
@flying-sheep can you elaborate?

**Comment by Carreau** [comment]
He got the wrong link : http://getbootstrap.com/css/#unstyled

list with `class="list-inline"` should get no decoration. our rendered-html class override that.

**Comment by flying-sheep** [comment]
the link is as good as yours ;)

what this bug is actually about: we should decide on either removing or embracing the bootstrap classes.

* removing means that we compile the .less in a way that skips the parts we don’t use in UI, or prefix bootstrap with `:not(.rendered_html)`
* embracing means that we override carefully enough to not break the bootstrap classes in the rendered html.

**Comment by Carreau** [comment]
> the link is as good as yours

Wrong as anchor could be more precise. we are lazy and don't read far :-) 
We'll try to do better.

**Comment by flying-sheep** [comment]
i linked the semantically superordinate header, you linked a wrong one :stuck_out_tongue_closed_eyes:

**Comment by flying-sheep** [comment]
any opinions on this?

**Comment by ellisonbg** [comment]
Up to now we have been pretty deliberate to keep bootstrap out of the
rendered-html, to allow that content to be used outside of a bootstrap. My
initially though it to keep it that way. I am still now quite clear on what
the bug/problem is associated with this issue. Is there a way of fixing it
without starting to use bootstrap in the rendered html?

On Wed, Aug 26, 2015 at 2:09 AM, Philipp A. <notifications@github.com>
wrote:

> any opinions on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/7#issuecomment-134908908>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> Up to now we have been pretty deliberate to keep bootstrap out of the
> rendered-html

We have been, many libs (pandas) rely on bootstrap css leaking in.

**Comment by ellisonbg** [comment]
I know we have places (widgets) where we use bootstrap in the notebook
content as well. While I like bootstrap, it definitely complicates things
like this.

On Wed, Aug 26, 2015 at 7:22 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Up to now we have been pretty deliberate to keep bootstrap out of the
> rendered-html
>
> We have been, many libs (pandas) rely on bootstrap css leaking in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/7#issuecomment-135038229>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by flying-sheep** [comment]
well, we could define a set of classes and styles that are guaranteed to be available in a notebook for HTML content.

or we could explicitly say that nobody should expect any CSS class to be defined.

or we could provide a hook that kernels can use to insert their own CSS without having to run a cell.

**Comment by Carreau** [comment]
> or we could provide a hook that kernels can use to insert their own CSS without having to run a cell.

Yep, but that complicate installation, and introduce extra problem, but its the kind of things that are on the back of our mind.

**Comment by flying-sheep** [comment]
ah, i rather thought about runtime (included in the first handshake between kernel and frontend)

but of course including it in the kernelspec would also make sense. maybe one list of stylesheets and one list of scripts to include? or just one of each?

**Comment by Carreau** [comment]
Neither, you might have installed package that want to register things later after kernel start, and you most likely want lazy loading. I think that the kind of stuff where we want a working group from `Haskell/Julia/Python/(a few other)` of people that know what they want and have enough inside knowlege of how Jupyter and their language work to design something that suite everyone. IBM is working on that IIRC.

**Comment by flying-sheep** [comment]
> Neither, you might have installed package that want to register things later after kernel start

well that’s trivial. simply do `display_javascript('''...''')` or `display_html('''<style>...</style>''')`

**Comment by Carreau** [comment]
> well that’s trivial. simply do display_javascript('''...''') or display_html('''<style>...</style>''')

Won't work or you have to display that which every call, and will break at notebook load as `<scripts>`might not be evaluated in order. 
Or you get an `init()` step, but the user remove the cell and it break, or does not work through conversions.

Also people use themes, so want kernel to display things with their theme. 

And also complain if your conversion to PDF does not apply the CSS style. 

So I would'nt call that "trivial"

**Comment by flying-sheep** [comment]
well, i just meant inserting CSS or running JS

**Comment by JamiesHQ** [comment]
@Carreau @ellisonbg : what is the status of this wishlist item from 2015? Is it in a development queue in either notebook or JupyterLab? Or possibly taken care of in recent releases. 

@flying-sheep : let us know if you still need this functionality. I'm working through open issues from 2015 and closing those that are long in the tooth. Thanks!

**Comment by ellisonbg** [comment]
Moving forward, we are making any promise to support bootstrap. I think we can close this as no action.

**Comment by gnestor** [comment]
> Moving forward, we are making any promise to support bootstrap. I think we can close this as no action.

For reference, that should be "no" promise to support bootstrap 👍
