### ISSUE TITLE
Missing .py import as .ipynb

### ISSUE THREAD

**Issue by ffinger** [jupyter/notebook#70]
In the old notebook one could import a .py file as a notebook by dragging it into the list of existing notebooks in the folder. If the .py contained special markup for text cells etc it was possible to import it as a multi-cell ipynb. Now it is just possible to import the .py into the folder in that way, without converting it to a notebook or splitting cells.
This feature was very important to me because I used it to compare several versions of my notebooks by exporting the .py files, doing a diff or merge on them, and reimporting the results as a new notebook.

**Comment by minrk** [comment]
I'm sorry the removal of .py notebook import has hurt you. You may be interested in [ipymd](https://github.com/rossant/ipymd), which stores notebooks as markdown files, which are more easily diffed and merged than JSON files. We will also be adding import functionality to nbconvert, which may be useful for workflows of this sort.
