### ISSUE TITLE
Jupyter notebook syntax highlight in vscode is broken

### ISSUE THREAD

**Issue by yongqiang-zhao** [jupyter/notebook#7007]
When I use Jupyter notebook in vscode, the syntax highlight is completely broken, all color disappears and all codes are colored white. However, the syntax highlight is still working for python script. When I empty vscode user settings json files, the highlight comes back again.

**Comment by JasonWeill** [comment]
Hi @yongqiang-zhao ! This repository is for the Jupyter Notebook software. You can open a bug against Visual Studio Code by following these instructions: https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
