### ISSUE TITLE
Add a `description` to plugins

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#7008]
Lumino 2 now supports adding a `description` to plugins: https://github.com/jupyterlab/lumino/pull/572

Currently most plugins in this repo don't make use of it, for example:

https://github.com/jupyter/notebook/blob/b5133c67f1a5c9c87d99abc44b7b04e6214aca45/packages/application-extension/src/index.ts#L499-L533

We should add them to the notebook code base, so it's useful for contributors but also for users at some point: https://github.com/jupyterlab/jupyterlab/pull/14536

**Comment by jtpio** [comment]
This could be a good task for a new contributor willing to get into the notebook code base.

**Comment by Ramyahkay** [comment]
I am a beginner contributor and I'd like to work on this issue
