### ISSUE TITLE
Missing notebook.auth submodule?

### ISSUE THREAD

**Issue by apowers313** [jupyter/notebook#7015]
## Description

`notebook.auth` disappeared in notebook 7.x?

Importing `notebook.auth` raises a `ModuleNotFoundError`. Importing `notebook` by itself works fine, and it seems that the `auth` submodule was removed. Works with 6.x and I can't find anything in the changelog that says this API was removed.

## Reproduce

As mentioned in [countless](https://stackoverflow.com/questions/39759623/jupyter-notebook-server-password-invalid) [tutorials](https://jupyter-notebook.readthedocs.io/en/5.5.0/public_server.html), with notebook 7.x installed:

``` python
from notebook.auth import passwd
passwd("foo")
```

## Expected behavior

Should yield a hashed password that can be dropped into a config file.

**Comment by jtpio** [comment]
Thanks @apowers313 for opening this issue.

Similar to https://github.com/jupyter/notebook/issues/7010, this is because Notebook 7 is now based on Jupyter Server.

You can achieve the same result by importing from `jupyter_server` instead:

```py
from jupyter_server.auth import passwd
passwd("foo")
```

**Comment by jtpio** [comment]
Maybe this should be documented in the migration guide for visibility: https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

**Comment by apowers313** [comment]
+1 to documentation. The three places I looked before posting a bug were:
1. Migration notes
2. [Changelog](https://github.com/jupyter/notebook/blob/main/CHANGELOG.md)
3. [Config docs](https://jupyter-notebook.readthedocs.io/en/stable/configuring/config_overview.html)

**Comment by jtpio** [comment]
Maybe the following changes to the docs would help then:

- Migration notes: add new section about using the `jupyter_server` imports
- Changelog: Move the 7.0 highlights to the top of the changelog for better visibility, since they already include a link to the migration guide.
- Config docs: new section / warning about this change in Notebook 7, and redirect to the Jupyter Server docs.
