### ISSUE TITLE
Can u please guide me how to resolve this issue 

### ISSUE THREAD

**Issue by Devan021** [jupyter/notebook#7032]
jupyter notebook
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
ModuleNotFoundError: No module named 'notebook.notebookapp'

**Comment by jtpio** [comment]
@Devan021 looks like trying to reinstall the `notebook` package might help?

Would you be able to share more information on how you installed `notebook` on your system. We usually recommend using virtual environment to properly isolate dependencies. But your logs suggest this is a system-wide install so something like the following might work:

```
pip install --upgrade --force-reinstall notebook 
```

**Comment by andrii-i** [comment]
@Devan021, have you been able to reinstall the notebook as suggested above? 

`pip install --upgrade --force-reinstall notebook`

**Comment by Devan021** [comment]
Thank you guys with your support the issue is fixed ..>
Requesting to close this issue
