### ISSUE TITLE
Checkbox rendering in Firefox

### ISSUE THREAD

**Issue by akhmerov** [jupyter/notebook#704]
The checkboxes in the notebook don't resize for high zoom in Firefox (Chrome is OK).

![checkbox](https://cloud.githubusercontent.com/assets/2069677/10934535/ba34e5ae-82e0-11e5-8c7a-d33a9ae24381.png)

This becomes noticeable when teaching and using an overhead projector.

**Comment by Carreau** [comment]
Hum, works for me on firefox, does it do it on checkbox on other website ? I doubt there is anything we can do.

**Comment by akhmerov** [comment]
Sorry, you're right, I should have checked. I see that Firefox behaves so in Ubuntu with any checkbox/radiobutton.
