### ISSUE TITLE
Long math expression in output is not wrapped unlike notebook 6

### ISSUE THREAD

**Issue by kwankyu** [jupyter/notebook#7055]
Hi,

Testing notebook 7 with SageMath, we noticed long math expression rendered by MathJax 3 is not wrapped, unlike notebook 6.

See https://github.com/sagemath/sage/pull/36129#issuecomment-1711714578

I hope this behavioral change is not intended. I think it is a bug.

- [ ] checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

I checked the issue on Chrome browser both with notebook 7.0.3 and jupyterlab 4.0.6

**Comment by krassowski** [comment]
Just for context, this is a know issue in MathJax 3 and will probably be resolved by upgrading `@jupyterlab/mathjax` to MathJax 4 once it is released (see https://github.com/jupyterlab/jupyterlab/issues/14570). For now you can install [`jupyterlab-mathjax2`](https://pypi.org/project/jupyterlab-mathjax2/) to downgrade to previous MathJax version (which is a trade=off because that has performance impact).

**Comment by kwankyu** [comment]
I am not sure if this is the same issue with https://github.com/jupyterlab/jupyterlab/issues/14570. The math expression does not use `\\`; it is a single long expression (a polynomial).

On the other hand, I could confirm that it is an issue of mathax3 vs mathjax2.  No problem with Notebook 7 itself.

Thank you for attention.

**Comment by dimpase** [comment]
Isn't it possible to fix this by an appropriate CSS styling of `mjx-container`?

I noticed that placing and evaluating an html cell in the notebook, like this:
```html
%%html
<style>
mjx-container {
  overflow-x: auto;
  overflow-wrap: break-word;
  max-width: 50%;
  }
</style>
```
does make the window to show a displayed LaTeX formula narrow (50% width, as requested), but does not force formula wrapping.

It could be a bug/missing feature in MathJax-3, I don't know.

**Comment by dimpase** [comment]
>  install [`jupyterlab-mathjax2`](https://pypi.org/project/jupyterlab-mathjax2/) to downgrade to previous MathJax version (which is a trade=off because that has performance impact).

apart from performance impact, it breaks off-line display of MathJax. Not sure whether this can be considered a bug in `jupyterlab-mathjax2`.
