### ISSUE TITLE
Notebook version is missing from "About Jupyter Notebook" dialog

### ISSUE THREAD

**Issue by andrii-i** [jupyter/notebook#7060]
## Description

Notebook version is missing from "About Jupyter Notebook" dialog:
![Screenshot 2023-09-18 at 3 10 04 PM](https://github.com/jupyter/notebook/assets/26686070/c35a4dc3-8787-40c2-b970-f1bf72753c16)

## Reproduce

1. Go to "Help" menu
2. Click on "About Jupyter Notebook"
3. Note missing version

## Expected behavior

Current version of the Notebook is shown in the About dialog in line with JupyterLab

![Screenshot 2023-09-18 at 3 08 11 PM](https://github.com/jupyter/notebook/assets/26686070/f0d7bf85-46ea-44cc-8131-5576d8739297)

**Comment by jtpio** [comment]
Thanks @andrii-i for reporting :+1: 

I think it's a regression from https://github.com/jupyter/notebook/pull/7049, which should be fixed in https://github.com/jupyter/notebook/pull/7061

**Comment by andrii-i** [comment]
Thank you @jtpio
