### ISSUE TITLE
Shift-J/K selection UI usability Bug. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#707]
It is common is multi selection, UI that if you extend the selectin, you can shrink it after. 

in particular in the notebook,  if one press Shift-J,J,J,J,J,K,K one expect to have "only" 3 cell selected, and not 5.

**Comment by Carreau** [comment]
This is inherent to the way the cell-marking is currently implemented. 
The notion of anchor and cursor in the selection that @takluyver did implement fro multi-selection was removed, while it was one of the only decent way to actually track this kind of selection behavior without a lot of brittle heuristic. 

We might be able to track wether shift-J/K extend or contract the cell marking by looking at wether the cursor is at beginning or end of contiguous marking. Though this become ambiguous in some case where you have non-contiguous marking. 

We cannot either track wether shift was keeped pressed as you can do Shift-J,J,J leave you keyboard then again Shift-J,K,K and should end up with 2 cell selected. 

One of the correct way to implement that is to have the current "selection" be composed of a cursor (which is the one you move with J,K, and arrow keys) and an "Anchor". The anchor is *in general* always on the same cell as the cursor, except when you press shift, in which case the *Anchor*, stays on it's current cell. 

See this UI prototype where the anchor is explicitly marked by a Cyan background:

When shift is pressed, you can see that the cursor move independantly from the anchor. 
![anchor](https://cloud.githubusercontent.com/assets/335567/10983609/89d273e8-83c8-11e5-9475-f0220ad2314f.gif)

The default moving J/K always bring back the **anchor** and the **cursor** together.
 
I propose we reintroduce the the concept of **multiple selection** where all cells in between the anchor and the cursor are **selected** (and thus implicitly marked), then provide 2 shortcuts: 

  - mark all cell in selection 
  - unmark all cells in selection

For which `+` and `-` would be good shortcut candidates. 
This would make the process of multiple selection/marking much closer to all other  UI exposed to user. Plus this would allow Shift-J/K to deselect marked cells, and will allow most action to be done without an explicit marking. By not needing explicit marking we would also get rid of  lots of issues of having marked cells out of the screen. 

Thoughts ?

Ping @ellisonbg, @jhamrick , @jdfreder

**Comment by jdfreder** [comment]
I think bringing back the multiple selection is fine, as long as no logic is multiselect only, and is always union(multiselect, marked).

**Comment by Carreau** [comment]
Multi select has nothing to do with what action apply to. this is action responsibility. 

But yes, we still apply commands to the union.

**Comment by ellisonbg** [comment]
Let's just fix shift-j/k. Here is one possible decision set we can use
inside `extend_marked`:

(old selection) -> (new selection) = (action in extend_marked)
marked -> unmarked = do nothing
marked -> marked = do nothing
unmarked -> unmarked = mark the old one
unmarked -> marked = unmark the new one

I am pretty sure gives the standard behavior of shift-j/k and even works
for multiple separately contiguous blocks selected this way.


On Fri, Nov 6, 2015 at 12:51 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Multi select has nothing to do with what action apply to. this is action
> responsibility.
>
> But yes, we still apply commands to the union.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/707#issuecomment-154484129>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
I'm pretty sure it won't work (X for marked , < for cursor, perssion Shift-J many time):

```
X<  X   X   X   X   X   X    X
X   X<  X   X   X   X   X    X
         <  X   X   X   X    X
X   X   X    <                
                X<  X   X    X
                     <        
                        X <  X
                              <
```
Just before after;;
```
XX
XX
 X
X 
 X
  
 X
  
```

**Comment by Carreau** [comment]
fixed !
