### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by Rabiyeganeh** [jupyter/notebook#7077]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 

- Jupyter Notebook version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter notebook` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by Rabiyeganeh** [comment]
Hi Guys,
I am new in data analysis practice.  I want to put multiple csv files in a single data frame. But 
I get the following error. I  appreciate any suggestions. 


![issue1](https://github.com/jupyter/notebook/assets/136314972/caf92a97-41f4-4018-a61c-126023bd397c)

![issue2](https://github.com/jupyter/notebook/assets/136314972/74b7bdeb-fad9-4ad1-b2f6-3bd46eb15579)
![issue3](https://github.com/jupyter/notebook/assets/136314972/4d2c3ed9-875e-4648-956d-b004bdf58272)

**Comment by Mat-Algo** [comment]
Hello @Rabiyeganeh , thankyou for opening this issue. You can try the following:

```
import os
import pandas as pd

directory_path = '' #specify the directory

# list to store dataframe
dataframes = []

for filename in os.listdir(directory_path):
    if filename.endswith('.csv'):
        file_path = os.path.join(directory_path, filename)
        df = pd.read_csv(file_path)
        dataframes.append(df)


combined_df = pd.concat(dataframes, ignore_index=True)
```

**Comment by Rabiyeganeh** [comment]
> Hi @Rabiyeganeh thank you for opening this issue. Have you tried using a relative path rather than the absolute path you are using in the second cell?
> 
> Additionally, this repository is intended to receive issues concerning bugs, regressions, enhancement requests etc. pertaining to the Notebook application. The better place to post a question like this would be in a [Discourse thread](https://discourse.jupyter.org/) or [Gitter](https://matrix.to/#/#jupyterlab_jupyterlab:gitter.im).

Hi @RRosio 
thank you for your suggestions. I tried relative path but again something went wrong. Also thanks for introducing Gitter and  Discourse thread.

**Comment by Rabiyeganeh** [comment]
> Hello @Rabiyeganeh , thankyou for opening this issue. You can try the following:
> 
> ```
> import os
> import pandas as pd
> 
> directory_path = '' #specify the directory
> 
> # list to store dataframe
> dataframes = []
> 
> for filename in os.listdir(directory_path):
>     if filename.endswith('.csv'):
>         file_path = os.path.join(directory_path, filename)
>         df = pd.read_csv(file_path)
>         dataframes.append(df)
> 
> 
> combined_df = pd.concat(dataframes, ignore_index=True)
> ```

Hello @Mat-Algo 
Thank you so much for your effective solution. It worked. 
Bests
