### ISSUE TITLE
ipywidgets widget layout problem in safari

### ISSUE THREAD

**Issue by mbakker7** [jupyter/notebook#709]
A slider widget, created with ipywidgets.interact, shows a strange layout in Safari.
Example code:

    def printx(x):
        print x
    from ipywidgets import interact
    interact(printx, x=(-10,10)); 

The widget has the name of the variable (here x) on the right side of the window. Other than that, the widget works fine.

Safari 8.06
ipywidgets 4.1.0
jupyter notebook 4.0.6
python 2.7.10

Same code on same machine (so same ipywidgets, jupyter, python) works fine with Chrome.

**Comment by ellisonbg** [comment]
ping @jdfreder

**Comment by jdfreder** [comment]
Migrated
