### ISSUE TITLE
Add the plugin manager extension

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#7097]
Moved from https://github.com/jupyter/notebook/pull/7096, tracking this separately to not block https://github.com/jupyter/notebook/pull/7096.

Upstream PR: https://github.com/jupyterlab/jupyterlab/pull/14536

Similar to the Settings Editor, we can consider opening the panel on the file browser page:

![image](https://github.com/jupyter/notebook/assets/591645/d1e90cf4-6888-4c69-9f5e-384fdda9bd98)

**Comment by joaovml** [comment]
Hi @jtpio , could you give more information about this issue and the final goal, I'm not sure I follow 100%. Thanks!

**Comment by jtpio** [comment]
> Upstream PR: [jupyterlab/jupyterlab#14536](https://github.com/jupyterlab/jupyterlab/pull/14536)

JupyterLab added support for exploring and managing the underlying plugins that can be found in extensions in this PR.

The final goal would be to expose this functionality in Notebook 7 too.
