### ISSUE TITLE
markdown equation rendering is suppressed if preceded by fenced code block

### ISSUE THREAD

**Issue by stevengj** [jupyter/notebook#7106]
The following issue was reported in https://github.com/JuliaLang/IJulia.jl/issues/1096, but is also reproducible with the Python kernel, so it seems to be an issue of the Jupyter notebook front end. 

Basically, under some circumstances the rendering of LaTeX equations in Markdown text is suppressed if the text is preceded by a fenced code block.   A minimal reproducer is:

````py
from IPython.display import display, Markdown
display(Markdown('''
```
foo
```

Some maths: $\sqrt{1 + x}$.
'''))
````
which is rendered in my Jupyter (6.5.4) notebook as follows, *without* LaTeX math formatting:

<img width="365" alt="image" src="https://github.com/jupyter/notebook/assets/2913679/2ed23fcc-62ca-472a-acf5-26b2337c6ad7">

If I simply remove the fenced code block from the beginning of the Markdown string, then the equation renders correctly:

<img width="387" alt="image" src="https://github.com/jupyter/notebook/assets/2913679/9ed2dfc0-1b3b-4271-8f06-be511b272d3e">

**Comment by jtpio** [comment]
@stevengj this is what it looks like with Notebook 7.0.6 (the latest release at the moment):

![image](https://github.com/jupyter/notebook/assets/591645/62f0f564-b479-4fb0-b759-afa13ec8703d)

**Comment by stevengj** [comment]
Ok, great, it's fixed in the latest version?  In that case I guess this issue can be closed?

**Comment by JasonWeill** [comment]
Closing because this is fixed in Notebook 7. Thanks for your help, @stevengj !
