### ISSUE TITLE
Javascript Error: IPython is not defined

### ISSUE THREAD

**Issue by qci-amos** [jupyter/notebook#7115]
I'm not sure what the correct repo is to report this... I picked here because downgrading to `notebook<7` fixes the issue.

## Description

If I use this in a notebook cell:

```python
import matplotlib.pyplot as plt
import numpy as np

%matplotlib notebook
plt.plot(np.arange(5))
```

I get the error:
```
Javascript Error: IPython is not defined
```

<img width="445" alt="image" src="https://github.com/jupyter/notebook/assets/45039789/7ab5f93a-d292-4a28-9c12-a9e06185705d">

## Reproduce

1. `conda create python=3.11 -n mynb`
2. `pip install jupyter notebook matplotlib`
3. make new jupyter notebook with the above cell

## Expected behavior

If I downgrade `pip install "notebook<7"` then a plot appears (with no error message)

## Context

- Operating System and version: windows 11
- Browser and version: Chrome

- Jupyter Notebook version: 

```console
$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.16.1
ipykernel        : 6.25.2
ipywidgets       : 8.1.1
jupyter_client   : 7.4.9
jupyter_core     : 5.4.0
jupyter_server   : 2.8.0
jupyterlab       : 4.0.7
nbclient         : 0.8.0
nbconvert        : 7.9.2
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : 5.4.4
traitlets        : 5.11.2
```

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter notebook` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by qci-amos** [comment]
This documentation:
https://matplotlib.org/stable/users/explain/figure/interactive.html#jupyter-notebooks-jupyterlab
says that the magic is supported:
```python
%matplotlib notebook
```

**Comment by jtpio** [comment]
Looks like it says the magic is supported in the classic notebook but not in JupyterLab though?

![image](https://github.com/jupyter/notebook/assets/591645/6f35f9c8-a042-40e2-ada7-11f30946e7f0)

Notebook 7 is based on JupyterLab and reuses the notebook component from JupyterLab. Which is likely why you get this error. The classic notebook used to provide JavaScript globals like `IPython` and `JavaScript`, but Notebook 7 does not anymore.

**Comment by qci-amos** [comment]
This is a good point to clarify then because the way I opened my notebook was:

```console
$ jupyter-notebook.exe mynb.ipynb
```

That is I assumed I was **not** using JupyterLab. When I click on About I see this:

![image](https://github.com/jupyter/notebook/assets/45039789/48dc42fb-9d39-4e67-9902-8250e9c845c2)

**Comment by qci-amos** [comment]
If you're saying this issue belongs in matplotlib then I can move it.

I would nevertheless ask if there's a more clear error message that could be raised.

**Comment by jtpio** [comment]
In this case the fix would probably be to use `%matplotlib widget`?

**Comment by jtpio** [comment]
> That is I assumed I was **not** using JupyterLab. When I click on About I see this:

That's right, it's another application (Notebook 7). And the classic notebook refers to Notebook < 7.

**Comment by qci-amos** [comment]
Yes, we can look into using different magic(s). The problem is that we have a lot of notebooks which use `%matplotlib notebook` from many non-software engineers so it might take us a while to update them. In the meantime, we added a `notebook<7` pin in our stack while we sort this out.

> And the classic notebook refers to Notebook < 7.

Ok, this point wasn't known to me. If this is the case, we can ask matplotlib to clarify their documentation? It sounds like you're saying this is likely a `won't fix`?

**Comment by jtpio** [comment]
> this point wasn't known to me. If this is the case, we can ask matplotlib to clarify their documentation? It sounds like you're saying this is likely a `won't fix`?

Update the matplotlib documentation to mention that Notebook 7 behaves like JupyterLab would indeed be useful :+1: 

There is an issue to discuss adding a compatibility layer with some classic notebook globals: https://github.com/jupyter/notebook/issues/6394. Although for now there is no such thing available and not sure there will be. So for now this would indeed be a "won't fix" unless someone volunteers to implement https://github.com/jupyter/notebook/issues/6394 (or similar).

**Comment by qci-amos** [comment]
Just a quick note according to my colleagues: `%matplotlib widget` does not support live plotting whereas `%matplotlib notebook` does.

**Comment by JasonWeill** [comment]
Closing this because Notebook developers are not likely to make a change for this issue; see #6394 for the issue @jtpio mentioned. @qci-amos thank you for your contribution!

**Comment by rjk** [comment]
> In this case the fix would probably be to use `%matplotlib widget`?

👆 For any other novices like myself encountering the IPython is not defined problem when using notebook v7, this is the solution. Change the line that says `%matplotlib notebook` to instead say `%matplotlib widget`. This changes the backend used by matplotlib to one that works with notebook v7. Or if you don't need an interactive chart you can probably just comment the line out altogether.

**Comment by oihan-a** [comment]
God bless you

**Comment by PRISCILLE7** [comment]
Hello everyone,

I'm working on a Python project using JupyterLab (version 4.4.3, Python 3.10). Recently, I've been getting the following error every time I open a Pyleecan notebook:

vbnet
Copier
Modifier
Javascript Error: IPython is not defined
Here's what I've tried so far:

Upgraded JupyterLab using pip install --upgrade jupyterlab

Switched browsers (tested with Chrome and Brave)

Cleared the browser cache

The error still appears, even in an empty notebook.

Any idea where this could be coming from or how to fix it? Could it be related to a JS bug, a missing extension, or a version conflict?

Thanks in advance for your help

**Comment by EricDuminil** [comment]
Just in case it helps anyone, I also got "Javascript Error: IPython is not defined" in Jupyter Notebook 7. Using `%matplotlib widget` only lead to "Error displaying widget".

What helped was:

```bash
pip install -U ipympl ipywidgets jupyterlab_widgets
```
