### ISSUE TITLE
Menu View → Table of Contents should toggle

### ISSUE THREAD

**Issue by parmentelat** [jupyter/notebook#7147]
## Description

not sure whether it's a bug or a usability issue, but:

- clicking once in the menu *View* → *Table of Contents* does show the TOC
- but clicking a second time **does not hide** the TOC

and btw same goes for *View* → *Debugger Panel*

## Reproduce

use the menu entry twice 

## Expected behavior

I'd expect these 2 functions to behave as togglers, just like how the *Show Header* thing behaves; 
otherwise newby users can only regain their real estate by reloading the page

## Context

- Operating System and version: seen on macos and linux
- Browser and version: chrome 118

- Jupyter Notebook version: 
```
jupyter --version
Selected Jupyter core packages...
IPython          : 8.17.2
ipykernel        : 6.26.0
ipywidgets       : not installed
jupyter_client   : 8.5.0
jupyter_core     : 5.5.0
jupyter_server   : 2.9.1
jupyterlab       : 4.0.7
nbclient         : 0.8.0
nbconvert        : 7.10.0
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : not installed
traitlets        : 5.13.0
```

no output in the browser console

**Comment by parmentelat** [comment]
PS: i just realized - a couple hours later - that the TOC pane has a small closing cross in the upper right corner
not very conspicuous, I must say
I'd rather if the menu acted as a toggle, just like *Show Header* does
but maybe that's good enough like that...

**Comment by cccindyyyl** [comment]
Hi @RRosio ! I have some experience with front-end development, and I have successfully reproduced the bug on my end. Would it be possible for me to work on this issue? Thanks!
