### ISSUE TITLE
cannot create R notebooks in v7

### ISSUE THREAD

**Issue by janxkoci** [jupyter/notebook#7151]
## Description

In the new Notebook 7 interface, I see no direct way to create notebooks with alternative kernels, such as `irkernel` for `R`. Creating new notebook from menu or the "new" dropdown always creates a Python notebook.

## Reproduce

1. Go to File > New > Notebook
2. After new notebook opens in new tab, see the kernel in top right corner - it's Python.
3. Click the kernel name.
4. Here I get to select the R kernel and switch to it.

## Expected behavior
I should be able to directly create R notebooks, just like I can in Notebook Classic or Jupyterlab, without going through the Python kernel first.

## Context

- Operating System and version: Linux Ubuntu 22.04
- Browser and version: Firefox 119.0.1
- Jupyter Notebook version: 7.0.6
- `notebook` installed with `mamba 1.4.2`

**Comment by jtpio** [comment]
This should be fixed by #7255, with the "New" dropdown mimicking allowing to select a kernel, similar to the behavior of the classic notebook:

[create-new-r-notebook.webm](https://github.com/jupyter/notebook/assets/591645/e535aa20-7ffb-4dbf-87d9-cc95851c3337)
