### ISSUE TITLE
Jupyter notebook not updating

### ISSUE THREAD

**Issue by ErdemBey31** [jupyter/notebook#7157]
Hello, I am downloading the v7 version of Jupyter with the pip install notebook==7.0.6 command. But when I start it, jupyter version is 4.0.9.

**Comment by Eyobagithub** [comment]
pip install -U jupyter

**Comment by ErdemBey31** [comment]
> pip install -U jupyter

**Same error**

**Comment by ErdemBey31** [comment]
[](url)

**Comment by ErdemBey31** [comment]
;)
