### ISSUE TITLE
jupyter notebook hangs and donot load just show : Skipped non-installed server(s):

### ISSUE THREAD

**Issue by dankarthik25** [jupyter/notebook#7160]
I have install jupyter inside my conda env using pip 
```
conda activate opencv
pip install notebook
```
it worked till yesterday but stop working from today 
when i run jupyter 
```
conda activate opencv
jupyter notebook 
```
It loads in browser but page hangs not loading 
in terminal it is showing `Skipped non-installed server(s)`
```
[I 2023-11-21 16:39:14.007 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
```

## Context

- Operating System and version: NAME=Linux Mint 20

- Browser and version: Firefox 110.01

- Jupyter Notebook version: 
jupyter                   1.0.0
jupyter_client            8.3.1
jupyter-console           6.6.3
jupyter_core              5.3.1
jupyter-events            0.7.0
jupyter-lsp               2.2.0
jupyter_server            2.7.3
jupyter_server_terminals  0.4.4
jupyterlab                4.0.6
jupyterlab-pygments       0.2.2
jupyterlab_server         2.25.0
jupyterlab-widgets        3.0.9

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter notebook` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
        http://localhost:8888/tree?token=e30ee7f7dc3bed0e19a4e1ad205b9072b845706537c915c6
        http://127.0.0.1:8888/tree?token=e30ee7f7dc3bed0e19a4e1ad205b9072b845706537c915c6
[I 2023-11-21 16:39:14.007 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server

</pre>
</details>
![Screenshots_2023-11-21T16-51-36](https://github.com/jupyter/notebook/assets/20885404/ac92314b-6639-4c1f-9b3c-3c46b8a23ee9)

**Comment by pkartsev** [comment]
My additions (Gentoo Linux amd64, Jupyter Server 2.9.1, Firefox v120.0, Opera v105.0.4970.13 - updated yesterday)

1) Firefox today started showing blank page and there is error in debug console (F12) : "... TypeError: g[e] is undefined .."
2) while Opera shows the page without problems
3) nbclassic version still shows ok in both

then
4) I don't remember why but ran "jupyter notebook --generate-config"
5) two hours later, I did not anything else but simply restarted jupyter (not classic) and now Firefox shows the jupyter home page just fine.

Not sure which point has helped but you could try another browser too :)

Regards!

**Comment by pkartsev** [comment]
Hi again!
Today I found the idea about clearing cache and cookies.
Entered Firefox settings and removed 5 cookies belonging to localhost. 
Now everything works! on two different PCs.

**Comment by susanth-bv** [comment]
Hi @RRosio , I'm am still experiencing this issue while trying to setup jupyter in ubuntu, what should i do, is this a problem from my side? thank you in advance.

**Comment by virathod** [comment]
cleaning the browser cache helped!

**Comment by KarolineHoller** [comment]
I have the same issue, using notebook 7.0.7. Using Brave and clearing cache didn't help, the start page of jupyter won't load. In Firefox it seems to work fine.

**Comment by mikechen66** [comment]
Please execute the following commands and then it will work fine.

0. Uninstall jupyter 

$ conda uninstall jupyter 
or 
$ pip uninstall jupyter 

2. install jupyter again 

$ conda install -c anaconda jupyter

3. update jupyter 

$ conda update jupyter
 
4. solve the compatibility 

$ pip install --upgrade 'nbconvert>=7' 'mistune>=2'

Cheers,

**Comment by ANGEL1303** [comment]
Hi I also have this issue  on microsoft edge browser. Jupyter CAD doesn't show up on web page, algo on jupyter desktop.
Only by copying and paste the  http://127.0.0.1:8888/cad?token=473b5c664fe3e8b05e8357781f4f26cfc2b9c1ab039d00c6 appeared on the terminal but it is not practical
