### ISSUE TITLE
unable to accessing jupyter notebook terminal on browswe with python version other than 3.7 

### ISSUE THREAD

**Issue by vikas41299** [jupyter/notebook#7209]
After successfully launching Jupyter Notebook in my browser, I find that the terminal feature within the notebook is not functioning or is inaccessible. Jupyter Notebook works seamlessly with Python 3.7 on my system, but encounters issues with other Python versions. Could you please help me to figure out the problem, why they do so. I'm currently work oveer python but facing issue regarding compatibility of jupyter-notebook with python other than 3.7 installed in virtual env.

By running the command jupyter notebook, by running command jupyter notebook, i got message given below and open blank browser

(jnb) vikass_thakur.iitr@login03:~$ juputer notebook
bash: juputer: command not found...
(jnb) vikass_thakur.iitr@login03:~$ jp
[W 2024-01-05 19:43:30.616 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be depr                                                                                               ecated in future releases of Jupyter Server.
[W 2024-01-05 19:43:30.704 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprec                                                                                               ated in future releases of Jupyter Server.
[W 2024-01-05 19:43:30.705 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be de                                                                                               precated in future releases of Jupyter Server.
[I 2024-01-05 19:43:30.706 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-01-05 19:43:30.724 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-01-05 19:43:30.745 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-01-05 19:43:30.771 ServerApp] nbclassic | extension was successfully linked.
[I 2024-01-05 19:43:30.797 ServerApp] notebook | extension was successfully linked.
[I 2024-01-05 19:43:31.298 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-01-05 19:43:31.356 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-01-05 19:43:31.362 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-01-05 19:43:31.364 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-01-05 19:43:31.379 LabApp] JupyterLab extension loaded from /home/vikass_thakur.iitr/miniconda3/envs/jnb/lib/python3.10/site-packages/jupyterlab
[I 2024-01-05 19:43:31.379 LabApp] JupyterLab application directory is /home/vikass_thakur.iitr/miniconda3/envs/jnb/share/jupyter/lab
[I 2024-01-05 19:43:31.380 LabApp] Extension Manager is 'pypi'.
[I 2024-01-05 19:43:31.386 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2024-01-05 19:43:31.402 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-01-05 19:43:31.418 ServerApp] notebook | extension was successfully loaded.
[I 2024-01-05 19:43:31.419 ServerApp] The port 8888 is already in use, trying another port.
[I 2024-01-05 19:43:31.420 ServerApp] The port 8889 is already in use, trying another port.
[I 2024-01-05 19:43:31.420 ServerApp] The port 8890 is already in use, trying another port.
[I 2024-01-05 19:43:31.421 ServerApp] The port 8891 is already in use, trying another port.
[I 2024-01-05 19:43:31.421 ServerApp] The port 8892 is already in use, trying another port.
[I 2024-01-05 19:43:31.422 ServerApp] Serving notebooks from local directory: /home/vikass_thakur.iitr
[I 2024-01-05 19:43:31.423 ServerApp] Jupyter Server 2.12.2 is running at:
[I 2024-01-05 19:43:31.423 ServerApp] http://localhost:8981/tree?token=8e9e77635581903af0c81963cd9c8efb8fadc290b868f336
[I 2024-01-05 19:43:31.423 ServerApp]     http://127.0.0.1:8981/tree?token=8e9e77635581903af0c81963cd9c8efb8fadc290b868f336
[I 2024-01-05 19:43:31.423 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-01-05 19:43:31.563 ServerApp]

    To access the server, open this file in a browser:
        file:///home/vikass_thakur.iitr/.local/share/jupyter/runtime/jpserver-121406-open.html
    Or copy and paste one of these URLs:
        http://localhost:8981/tree?token=8e9e77635581903af0c81963cd9c8efb8fadc290b868f336
        http://127.0.0.1:8981/tree?token=8e9e77635581903af0c81963cd9c8efb8fadc290b868f336
[I 2024-01-05 19:43:31.632 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-ser                                                                                               ver, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-se                                                                                               rver
START /usr/bin/firefox "/home/vikass_thakur.iitr/.local/share/jupyter/runtime/jpserver-121406-open.html"
Running without a11y support!
^C[I 2024-01-05 19:53:57.704 ServerApp] interrupted
[I 2024-01-05 19:53:57.704 ServerApp] Serving notebooks from local directory: /home/vikass_thakur.iitr
    0 active kernels
    Jupyter Server 2.12.2 is running at:
    http://localhost:8981/tree?token=8e9e77635581903af0c81963cd9c8efb8fadc290b868f336
        http://127.0.0.1:8981/tree?token=8e9e77635581903af0c81963cd9c8efb8fadc290b868f336
Shutdown this Jupyter server (y/[n])? y
[C 2024-01-05 19:53:58.255 ServerApp] Shutdown confirmed
[I 2024-01-05 19:53:58.258 ServerApp] Shutting down 6 extensions

**Comment by JasonWeill** [comment]
Python 3.7 is end-of-life, so newer versions of Python, with the possible exception of Python 3.12, should work.

**Comment by vikas41299** [comment]
> Thanks for opening this issue @vikas41299, could you share the version of Notebook that you are running into this issue with? Can you try clearing the cache in your browser to see if that changes anything for you?

Complete description of  jupyter notebook version using cmd below along with python version Python 3.10.12

(jnb) vikass_thakur.iitr@login08:/scratch/vikass_thakur.iitr/home$ pip show jupyter notebook
Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD
Location: /home/vikass_thakur.iitr/miniconda3/envs/jnb/lib/python3.10/site-packages
Requires: ipykernel, ipywidgets, jupyter-console, nbconvert, notebook, qtconsole
Required-by:
---
Name: notebook
Version: 7.0.6
Summary: Jupyter Notebook - A web-based notebook environment for interactive computing
Home-page:
Author:
Author-email: Jupyter Development Team <jupyter@googlegroups.com>
License: BSD 3-Clause License

        - Copyright (c) 2001-2015, IPython Development Team
        - Copyright (c) 2015-, Jupyter Development Team

        All rights reserved.

        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:

        1. Redistributions of source code must retain the above copyright notice, this
           list of conditions and the following disclaimer.

        2. Redistributions in binary form must reproduce the above copyright notice,
           this list of conditions and the following disclaimer in the documentation
           and/or other materials provided with the distribution.

        3. Neither the name of the copyright holder nor the names of its
           contributors may be used to endorse or promote products derived from
           this software without specific prior written permission.

        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
        AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
        IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
        DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
        FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
        DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
        SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
        CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
        OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: /home/vikass_thakur.iitr/miniconda3/envs/jnb/lib/python3.10/site-packages
Requires: jupyter-server, jupyterlab, jupyterlab-server, notebook-shim, tornado
Required-by: jupyter

**Comment by vikas41299** [comment]
> Python 3.7 is end-of-life, so newer versions of Python, with the possible exception of Python 3.12, should work.

I already tried with python 3.12, still suffer with same issue.

**Comment by vikas41299** [comment]
> Python 3.7 is end-of-life, so newer versions of Python, with the possible exception of Python 3.12, should work.


By using Python 3.17,  proceeding Jupyter notebook cmd gives blank webpage
Could you please let me know why these extension point shows
 

[W 2024-01-13 16:04:05.696 ServerApp] **_A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Serve_**r.
[W 2024-01-13 16:04:05.782 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-01-13 16:04:05.783 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-01-13 16:04:05.802 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-01-13 16:04:05.825 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-01-13 16:04:05.849 ServerApp] notebook | extension was successfully linked.
[I 2024-01-13 16:04:06.367 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-01-13 16:04:06.435 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-01-13 16:04:06.441 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-01-13 16:04:06.444 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-01-13 16:04:06.469 LabApp] JupyterLab extension loaded from /home/vikass_thakur.iitr/.conda/envs/jnb/lib/python3.12/site-packages/jupyterlab
[I 2024-01-13 16:04:06.469 LabApp] JupyterLab application directory is /home/vikass_thakur.iitr/.conda/envs/jnb/share/jupyter/lab
[I 2024-01-13 16:04:06.470 LabApp] Extension Manager is 'pypi'.
[I 2024-01-13 16:04:06.476 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-01-13 16:04:06.492 ServerApp] notebook | extension was successfully loaded.
[I 2024-01-13 16:04:06.493 ServerApp] The port 8888 is already in use, trying another port.
[I 2024-01-13 16:04:06.494 ServerApp] The port 8889 is already in use, trying another port.
[I 2024-01-13 16:04:06.494 ServerApp] The port 8890 is already in use, trying another port.
[I 2024-01-13 16:04:06.495 ServerApp] The port 8891 is already in use, trying another port.
[I 2024-01-13 16:04:06.496 ServerApp] The port 8892 is already in use, trying another port.
[I 2024-01-13 16:04:06.497 ServerApp] Serving notebooks from local directory: /scratch/vikass_thakur.iitr/home
[I 2024-01-13 16:04:06.497 ServerApp] Jupyter Server 2.12.4 is running at:
[I 2024-01-13 16:04:06.497 ServerApp] http://localhost:8807/tree?token=8ee3e5364351584b9e65247d419ec05178ac1e2694d0df8b
[I 2024-01-13 16:04:06.497 ServerApp]     http://127.0.0.1:8807/tree?token=8ee3e5364351584b9e65247d419ec05178ac1e2694d0df8b
[I 2024-01-13 16:04:06.497 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-01-13 16:04:06.613 ServerApp]

    To access the server, open this file in a browser:
        file:///home/vikass_thakur.iitr/.local/share/jupyter/runtime/jpserver-128362-open.html
    Or copy and paste one of these URLs:
        http://localhost:8807/tree?token=8ee3e5364351584b9e65247d419ec05178ac1e2694d0df8b
        http://127.0.0.1:8807/tree?token=8ee3e5364351584b9e65247d419ec05178ac1e2694d0df8b
[I 2024-01-13 16:04:06.699 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
START /usr/bin/firefox "/home/vikass_thakur.iitr/.local/share/jupyter/runtime/jpserver-128362-open.html"
Failed to open connection to "session" message bus: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Running without a11y support!

**Comment by vikas41299** [comment]
> Thanks for the update @vikas41299, it looks like those warnings are not related to the original issue. `notebook_shim` and `jupyter-lsp` are extensions that must declare the functions in the warning, but it seems like they should be working for you at the moment based on the message itself. Just wanted to double-check, if you try clearing the cache and reloading the webpage, do you get the same error?


Thank you for always responding to my queries so promptly. Your quick and helpful replies are greatly appreciated!
 The problem is resolved now: Instead of using pip to install jupyter, Using the 'conda -channel' option helped resolve the present issue, and now it works fine with Python versions greater than 3.7 as well
