### ISSUE TITLE
Update docker

### ISSUE THREAD

**Issue by sayem314** [jupyter/notebook#7228]
https://github.com/jupyter/notebook/releases/tag/v7.0.7 is missing on docker

**Comment by jtpio** [comment]
@sayem314 looks like you are referring to the Jupyter docker images, maintained by the Jupyter Docker Stacks project?

If so, then you can open the issue on this repo: https://github.com/jupyter/docker-stacks. And / or check if they have plans to update to the latest version.

**Comment by JasonWeill** [comment]
@sayem314 As @jtpio suggested, please open an issue in https://github.com/jupyter/docker-stacks if this is still not available. Thank you for your contribution!
