### ISSUE TITLE
UI issue: cell cursor does not move to the target cell when using keyboard shortcuts

### ISSUE THREAD

**Issue by tanweihou** [jupyter/notebook#7229]
## Description
Jupyter notebook does not move the target cell when inserting a new cell above (pressing A).

[notebook ui problem.webm](https://github.com/jupyter/notebook/assets/15125658/5b316a11-145c-4d50-b95b-08920acbd7be)

## Reproduce

1. Type a few lines of code, ideally comes with many lines of error messages (my example), many lines of output. 
2. Press "Shift+Enter" to execute that cell.
3. Use arrow key to move up to the same cell.
4. Press A and check if cell cursor move to the cell above. 

## Expected behavior
Cell cursor should move to the target cell.

[expected behavior.webm](https://github.com/jupyter/notebook/assets/15125658/e04f76fd-6eb7-489c-960b-e96f0ff0f090)

## Context

- Operating System and version: Windows 11, Ubuntu 22.04
- Browser and version: Chrome 121 on both Windows 11 and Ubuntu 22.04 
- Jupyter Notebook version: 7.0.6
-  Jupyter Lab version: 4.0.8

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter notebook` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
Triage notes: This will likely be fixed in 7.1. Please verify when this version is available.

**Comment by tanweihou** [comment]
Hi, I just checked it with the following specs
- Jupyter Notebook version: 7.1.1
- Jupyter Lab version:  4.1.2

and the UI issue has been fixed.
Thanks a lot.
