### ISSUE TITLE
CSS issue when the Notebook windowing mode is set to `full`

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#7231]
Testing on the latest `main`, which includes the recent changes that landed in JupyterLab w.r.t windowing mode, it looks like the CSS is off:

![image](https://github.com/jupyter/notebook/assets/591645/97ecf393-55e4-491d-bccc-d411a091bd69)

This is likely related to an underlying DOM structure change, which affects the CSS customizations in Notebook.

**Comment by jtpio** [comment]
Adding to `7.1.x` since `full` is not the default windowing mode.

**Comment by jtpio** [comment]
Marking as a "good first issue" if someone would like to have a look:

The windowing mode can be set to `full` via the settings editor:

![image](https://github.com/jupyter/notebook/assets/591645/57523248-d096-4c42-9295-12e67d2bfa3d)

This will also likely require tweaking some CSS depending on the DOM structure: https://github.com/jupyter/notebook/blob/main/packages/notebook-extension/style/base.css

**Comment by kgaurav8026** [comment]
Hi @jtpio,
I’m interested in contributing to JupyterLab, and I’d like some additional context regarding the issue related to cell alignment. From what I understand, the issue pertains to the misalignment of the cell box when windowing. Specifically, should the cell box be centered on the screen?

**Comment by jtpio** [comment]
Yes it should be centered like when using the default mode:

![image](https://github.com/jupyter/notebook/assets/591645/9ad11bc5-991a-484d-aac9-2b32cc7a2419)

**Comment by v-lozko** [comment]
Hello, would it be possible to have this assigned to me?

Thanks

**Comment by kgaurav8026** [comment]
Hi @v-lozko , i am finding it difficult to fix the bug.  So you can start working on it if you want. 
Thanks

**Comment by kgaurav8026** [comment]
@v-lozko Also, if you are able to merge Kindly tell me the approach as i am keen on understanding how to tackle such issues in the future.

**Comment by v-lozko** [comment]
hello @jtpio, i can't seem to recreate the issue. I was a bit busy the past couple days and finally able to get to it and with full windowing mode enabled when i create a new notebook it's centered.

**Comment by v-lozko** [comment]
Hello @jtpio i can't seem to replicate the issue. This is the first issue i'm dealing with in Jupyter, but it definitely seems like i set up the environment correctly, and having changed my settings to full i do not have the CSS issue that you shared. it looks fine.

**Comment by jtpio** [comment]
I just tried from the latest commit (851a4beaae084a513ac7cf851292b7be1c87c198) and it still seems to be an issue:

![image](https://github.com/jupyter/notebook/assets/591645/3c9d3791-a5dc-45df-b115-968dcabf3c90)

**Comment by v-lozko** [comment]
huh, i have windowing set to full
![image](https://github.com/jupyter/notebook/assets/156805389/87edfcd6-cb67-4a9f-b6da-535fbef44a92)
and here is what i'm seeing
![image](https://github.com/jupyter/notebook/assets/156805389/c8b56a83-471c-4034-9bbc-d059658c968a)

**Comment by jtpio** [comment]
Did you refresh the notebook page after changing the setting?

**Comment by v-lozko** [comment]
yes, and i've tried reinstalling the build multiple times. i see you're using gitpod based on your url, could that be a possible source of the issue?

**Comment by jtpio** [comment]
Here is a screencast to reproduce the issue, testing on Binder with Notebook 7.1.2 from this gist: https://gist.github.com/jtpio/d368ab89cee5123ecee60683115e15f3

[notebook-full-windowing-mode.webm](https://github.com/jupyter/notebook/assets/591645/8fa70700-6b1b-40e0-a0b7-0ae52973cc14)

> you're using gitpod based on your url, could that be a possible source of the issue?

This was tested in a fresh new environment on Gitpod, so not sure this is the reason. And it is also reproducible on Binder (which also creates a clean new environment).

**Comment by v-lozko** [comment]
So i went out, got a new macbook as i was previously using a windows, set everything up and this time tried it both with chrome and safari as well as binder. i get the issue with safari and binder, but i am not able to repeat it on chrome. so at least this gives me a place to start

**Comment by jtpio** [comment]
Thanks @v-lozko for looking into this.

I also checked on Chromium (on Ubuntu) and it also seems to be the case:

![image](https://github.com/jupyter/notebook/assets/591645/3abe1576-7fa7-49cc-9ae7-4cf53d5c9c31)

**Comment by v-lozko** [comment]
Thanks for your patience as well, I have been a bit busy these past couple days but had a chance to look into a little. I'm not certain its the DOM, as it seems the right margin for the windowed panel is being overridden by a style attribute coming from somewhere (which surprisingly isn't happening with chrome). I'll get it sorted in next day or so, someone much better versed in CSS will help me sort it out.

**Comment by Dev-Akash** [comment]
Hi @v-lozko , I hope I can help on the CSS part in this issue, if there is a room for contribution please let me know.
Thank you!

**Comment by v-lozko** [comment]
Hey @Dev-Akash, I have put some time in already trying to resolve this and would like to see it through in next day or so. If I can't figure it out I can definitely let you know! I appreciate the offer

**Comment by Dev-Akash** [comment]
Sure! @v-lozko. 
Thank you!

**Comment by v-lozko** [comment]
@jtpio i submitted a PR [here](https://github.com/jupyter/notebook/pull/7301) for this issue however i forgot to appropriately label it so its not tied to this issue. Is there a way to edit the labels post submittal of the PR?

**Comment by tentomush1** [comment]
Is the issue solved yet? what is the progress?

**Comment by felixmachaoran** [comment]
This problem seems still happening in notebook version 7.2.2

**Comment by jtpio** [comment]
@felixmachaoran would you be able to provide a screenshot of the issue? Thanks!

**Comment by felixmachaoran** [comment]
![Image](https://github.com/user-attachments/assets/00f5a59d-221b-4d67-a280-bf7524924365)
Here is the screenshot happen on the version 7.2.2

**Comment by jtpio** [comment]
Thanks @felixmachaoran.

Wondering if this might be a browser caching issue. Would you be able to clear your browser cache and reload the page, to double check?

**Comment by felixmachaoran** [comment]
When I downgrade to version 7.1.2, this issue disappeared, once I upgrade to 7.2.2, it happens again

**Comment by jtpio** [comment]
OK, and if you try to clear the cache entirely? Or try in a different web browser?

**Comment by felixmachaoran** [comment]
Sorry, after clear the browser cache, the issue seems solved, thank you for your help

**Comment by jtpio** [comment]
OK good to hear, thanks for checking!
