### ISSUE TITLE
Avoid visualising all the data of a numpy.ndarray   

### ISSUE THREAD

**Issue by omaech** [jupyter/notebook#7238]
### Problem

In the Python-Blosc2 project we found some problems with the new Jupyter NoteBook version when printing a big array. This is better described in: https://github.com/Blosc/Python-Blosc2/issues/164

### Proposed Solution

It would be nice that when the array is big the output is not the whole data. Instead it could only show the firsts and lasts positions of the array like it did in later versions.

**Comment by JasonWeill** [comment]
Triage notes: With which version of `numpy` do you see this behavior? If you saw different behavior before, was it with a different `numpy` version? If so, which version? It's unclear if this is a bug in Jupyter Notebook or in NumPy.

**Comment by JasonWeill** [comment]
@omaech Any updates about the questions from earlier?
