### ISSUE TITLE
Cannot type with option key

### ISSUE THREAD

**Issue by sereios** [jupyter/notebook#7240]
## Description

In Jupyter Notebook, since I opened and closed the right sidebar, I am not able to type any characters that require pressing the option key on my keyboard.

I am working on a German Mac keyboard which requires pressing e.g. Option + 8 to type curly brackets like so: `{`

The JS console prints:

```
Cannot execute key binding 'Alt 8': command 'application:toggle-side-tabbar' is not registered. [3301.bundle.js:1:4552](http://localhost:8888/static/notebook/3301.bundle.js)
Cannot execute key binding 'Alt 9': command 'application:toggle-side-tabbar' is not registered. [3301.bundle.js:1:4552](http://localhost:8888/static/notebook/3301.bundle.js)
Cannot execute key binding 'Alt 7': command 'application:toggle-side-tabbar' is not registered. [3301.bundle.js:1:4552](http://localhost:8888/static/notebook/3301.bundle.js)
Cannot execute key binding 'Alt 6': command 'application:toggle-side-tabbar' is not registered. [3301.bundle.js:1:4552](http://localhost:8888/static/notebook/3301.bundle.js)
Cannot execute key binding 'Alt 5': command 'application:toggle-side-tabbar' is not registered. [3301.bundle.js:1:4552](http://localhost:8888/static/notebook/3301.bundle.js)
Cannot execute key binding 'Alt 4': command 'application:toggle-side-tabbar' is not registered. [3301.bundle.js:1:4552](http://localhost:8888/static/notebook/3301.bundle.js)
Cannot execute key binding 'Alt 3': command 'application:toggle-side-tabbar' is not registered. [3301.bundle.js:1:4552](http://localhost:8888/static/notebook/3301.bundle.js)
Cannot execute key binding 'Alt 2': command 'application:toggle-side-tabbar' is not registered. [3301.bundle.js:1:4552](http://localhost:8888/static/notebook/3301.bundle.js)
Cannot execute key binding 'Alt 1': command 'application:toggle-side-tabbar' is not registered.
```

1. This issue appears only in Jupyter Notebook, not in other applications or any other kind of input option on my computer. So it seems to be an issue of Notebook, not of my machine as such. 
2. It also appears across Notebooks, so it seems not be an issue of the specific Notebook I am running.
3. Finally, the issue also appears across browsers: I have tried Safari, Firefox, Chrome and Arc.
4. The issue is persistent. It is not resolved by restarting the kernel or shutting down and rerunning jupyter. It is also not resolved by restarting my machine.

**Something within Jupyter Notebook somehow has been set to permanently confuse regular keyboard input within cells with some sidebar shortcut.**

## Reproduce

Perhaps difficult to reproduce, as nobody seems to have experienced the problem before, but:

1. Menu: View > Right Sidebar > Show Notebook Tools
2. Close Notebook Tools
3. Set Input Cursor in any cell
4. Type some character requiring the Option key
5. Nothing happens

## Expected behavior

I would expect to be able to type characters like curly brackets etc.

## Context

**System:** M1 Mac (Ventura 13.1)
**Environment:** virtual environment using **pipenv**.
**Notebook Version:** 7.0.7
**Browsers:** Safari, Chrome, Arc, Firefox

As it seems to be an input problem related to JavaScript, I have put some content form the JS Console above.

**Comment by batchmode** [comment]
I observed a very similar (if not the same) issue today after upgrading my jupyterlab installation to version 4.1.0 yesterday.
And I also use Jupyterlab on Mac (docker) German Keyboard and cannot type any of Option+[any number].

I believe it has to do with a misconfigured default shortcut configuration for the toggle of the left action bar. (At least for me)
In the shortcut configuration I have this:

![Bildschirmfoto 2024-02-08 um 18 15 32](https://github.com/jupyter/notebook/assets/30779809/f30b2ab5-a721-4f8e-954f-8de8dbd5f320)

I can work around this by disabling each of this shortcuts in the custom settings as described in the json config of the system defaults.

```
    // Note: To disable a system default shortcut,
    // copy it to User Preferences and add the
    // "disabled" key, for example:
    // {
    //     "command": "application:activate-next-tab",
    //     "keys": [
    //         "Ctrl Shift ]"
    //     ],
    //     "selector": "body",
    //     "disabled": true
    // }
```

Maybe you have the same issue and the workaround could help you too.

**Comment by jtpio** [comment]
Thanks for reporting the issue :+1: 

As a temporary workaround, would you be able to try downgrading JupyterLab to a previous version? Notebook depends on JupyterLab so this might help fix the issue:

```
python -m pip install "jupyterlab<4.1.0"
```

**Comment by sereios** [comment]
Thank you both!

@jtpio: I can confirm that downgrading worked just fine. Thank you for the workaround.
@batchmode: Thank you for pointing me to issue [15744](https://github.com/jupyterlab/jupyterlab/issues/15744). I will follow this and upgrade again when the main issue is resolved.

**Comment by sereios** [comment]
Closing this issue.
