### ISSUE TITLE
Cry for help, please, give us "right button" and "ctrl+F" back!

### ISSUE THREAD

**Issue by avloss** [jupyter/notebook#7246]
This is just my opinion, but I find it extremely frustrating when functionality like "right button" or "ctrl+F" (page search) are overridden. When I press right button I expect to see MY menu, I have custom Chrome plugins which modify it. I expect to see "Open Link In a New Tab", I expect to see "Copy" and what I always see, on every other website. Left button is functional, and surely developers should make the most of it, but "Right Button" is "personal user space", please do not override it with any functionality. Same for page search - as I user I'm used to certain behaviour when I search on a web page - where and how search field would appear and how it'll behave - please do NOT override it! Also, when I click on BreadCrumbs in "Tree View" with right button - I expect "open in a new Tab", but it's not there. We as users are used to certain ways of interacting with a web-page. Please do not override those basic browser functions (Right Click, Ctrl+F).

This is more of an emotional appeal, I really love using Jupyter Notebook, and it's been a huge part of my professional career. But what Notebook 7 is becoming is almost unusable to me. People who want that "immersive lab experience" can surely use Jupyter Lab, but for those who want to treat Notebook as an "interactive web page" - we really do want to have it act as a web page.

This is more of a cry-for-help. I've downgraded to 6.5.6 after using 7 for quite some time. I understand that it's unlikely that it'll happen, but I just want there to be awareness, that people who didn't switch to "Jupyter Lab" already just want their normal Notebook, with predictable behaviour.

Right now there's "nbclassic" but it's prompting for "migration", so my understanding is it'll be discontinued sooner than later.

**Comment by jtpio** [comment]
Thanks @avloss for opening the issue.

> When I press right button I expect to see MY menu

The context menu is indeed inherited from JupyterLab. However you should be able to open the default browser context menu by holding <kbd>Shift</kbd> before right-clicking:

![image](https://github.com/jupyter/notebook/assets/591645/4f810e0a-4c66-4736-8c72-987863500b84)

> CTRF-F

This was indeed the case for a while before the final release of Notebook 7. However it was causing issues because the default browser search was not able to find elements on the page. See https://github.com/jupyter/notebook/pull/6905 for more details.

You may want to disable that shortcut as mentioned in https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#searching

**Comment by avloss** [comment]
> Shift
Thanks, didn't know that!
> CTRF-F
For me it only searches code, but not the cell output, which is most of the time not what I expect. Perhaps that's by design.
<img width="481" alt="Screenshot 2024-02-08 at 22 19 18" src="https://github.com/jupyter/notebook/assets/17853685/d9658d6f-0e8e-4dcd-8ad9-649ff3df4691">

**Comment by jtpio** [comment]
> Thanks, didn't know that!

Happy to add more documentation to the [migration guide](https://jupyter-notebook.readthedocs.io/en/stable/migrate_to_notebook7.html) or other places in the docs, if you think that would be useful. Maybe also to document how to disable the context menu entirely.

> For me it only searches code, but not the cell output, which is most of the time not what I expect. Perhaps that's by design.

You may need to expand the search filters and select "Search Cell Outputs":

![image](https://github.com/jupyter/notebook/assets/591645/fb86dcc7-ab7f-488c-b116-649454885124)

Do you think this should be enabled by default? If so maybe this can be submitted as a feature request in https://github.com/jupyterlab/jupyterlab?

**Comment by avloss** [comment]
Thank you for your response! I'll close the issue now.
