### ISSUE TITLE
Displaying external HTML files

### ISSUE THREAD

**Issue by michaelbeaumont** [jupyter/notebook#725]
I'm using IHaskell and I'm trying to include external HTML files, in an iframe. It seems crazy that I can't get around HTML Sanitizer constantly removing my src attribute, even by trusting my notebook. Is there a different way to include HTML? My use case is, I have some HTML generated by another process that I'd like to show in my notebook.

**Comment by minrk** [comment]
Markdown is sanitized unconditionally (i.e. always untrusted). Only output can be trusted. If you want to include such HTML, it can be done as an HTML output from an execution.

**Comment by michaelbeaumont** [comment]
What is an HTML output? IHaskell doesn't have anything like IFrame in ipython. Can I do it somehow from the shell? The HTML file is on my machine.

**Comment by JamiesHQ** [comment]
@michaelbeaumont : We're doing a little housekeeping on our issue log and noticed this thread from 2015. Were you able to find a solution to your issue? Should we close this issue? thanks!

**Comment by gnestor** [comment]
In ipython, you would do something like:

```py
from IPython.display import HTML

HTML(file="./my_html_file.html")
```

I'm not familiar with displaying data in IHaskell, but the kernel just needs to return a `display_data` message with a mime bundle resembling `{"text/html": HTML_DATA}`.

Closing this for now. Feel free to re-open if you're still having issues.

**Comment by elFua** [comment]
@gnestor:
In current version of jupyter the argument is named `filename`, not `file`:

```python
HTML(filename="./my_html_file.html")
```

**Comment by gnestor** [comment]
@elFua You're correct! I updated my comment 👍

**Comment by DROMZEE** [comment]
`[link text](./my_html_file.html)`

**Comment by Projyots** [comment]
It worked fine.
Is there any parameter to display size?
