### ISSUE TITLE
Julia no longer supported by github backend

### ISSUE THREAD

**Issue by setrar** [jupyter/notebook#7251]
## Description

For the past few months, I have been using github to display Jupyter Notebooks [REPORT.ipynb](https://github.com/setrar/DigiCom/blob/main/Labs/TP2/REPORT.ipynb) using the Julia language.
The github backend worked like a charm until yesterday.
In the time being, I put a link to manually render the notebook on [REPORT.ipynb on nbviewer](https://nbviewer.org/github/setrar/DigiCom/blob/main/Labs/TP2/REPORT.ipynb).
Since Python Notebooks are working fine, I was wondering if it was just Julia causing the issue.
What would be the solution for Github to allow Julia back again on their platform?

## Reproduce

1. Click on [REPORT.ipynb](https://github.com/setrar/DigiCom/blob/main/Labs/TP2/REPORT.ipynb)
2. Expected behavior [REPORT.ipynb on nbviewer](https://nbviewer.org/github/setrar/DigiCom/blob/main/Labs/TP2/REPORT.ipynb)
3. Error: Jupyter Cells are no longer rendering Julia source code

**Comment by stevengj** [comment]
I just noticed the same thing with my notebooks, e.g. [this one](https://github.com/mitmath/matrixcalc/blob/5037c8b3cc554c88e139812bdf883c3c9f85ee59/notes/Finite%20difference%20checks.ipynb).  In particular, code cells are no longer rendered correctly.  This is particularly noticeable with multi-line code cells, e.g.

![image](https://github.com/jupyter/notebook/assets/2913679/64777374-227e-40c7-a2b5-986ed9e57bea)

in the link above — you can see that the line breaks are gone, and everything is smashed together.  If you look at the raw `.ipynb` file (which is just text in JSON format), you can see that the underlying data contains line breaks:
```js
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "201cdbe8-df2f-4c2f-8f3b-9d92c5d05911",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "freq_offset_est (generic function with 1 method)"
      ]
     },
     "execution_count": 43,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "########################################################\n",
    "# Frequency Offset Estimator Function\n",
    "########################################################\n",
    "function freq_offset_est(sₚₛₛ, hₚₛₛ, Nf, m, 𝑓ₛ)\n",
    "\n",
    "    # Frequency offset estimator\n",
    "    Y = zeros(Float64, length(m));\n",
    "    L = length(hₚₛₛ)\n",
    "    t = 0:(1/𝑓ₛ):((L-1)/𝑓ₛ)\n",
    "\n",
    "    for i = 1:length(m)\n",
    "        # vec() denote the operation of reshaping sequence into a one-dimensional vector\n",
    "        # in Matlab it is the .' (per element transpose)\n",
    "        # (.)ˣ is the conjugate operation\n",
    "        Y[i] += abs2.( ∑( exp.(-2π * j * m[i] .*t ) .* (hₚₛₛ)ˣ .* vec(sₚₛₛ[Nf:(Nf + L -1)])));\n",
    "    end\n",
    "\n",
    "    A𝑓ₒ, 𝑓ₒ = argmax(Y) # Frequency Offset Ampitude, Index and adjusted signal\n",
    "\n",
    "    return m[𝑓ₒ], A𝑓ₒ, 𝑓ₒ, Y # m[𝑓ₒ] Index of the transmitted PSS in Hz\n",
    "end"
   ]
  },
```
which is why it renders fine on nbviewer.

**Comment by stevengj** [comment]
However, this is not a Jupyter issue — it should be reported to github.

**Comment by stevengj** [comment]
I've created a github support ticket: https://support.github.com/ticket/personal/0/2590265

**Comment by setrar** [comment]
> I've created a github support ticket: https://support.github.com/ticket/personal/0/2590265
> 
> Probably this issue can be closed here, since there is nothing the Jupyter project can do about it.

Hi @stevengj , I saw your reply on Julia Discourse. I am closing this ticket.

Thanks

**Comment by setrar** [comment]
Issue related to github.com Backend https://support.github.com/ticket/personal/0/2589778
