### ISSUE TITLE
Connecting to existing kernels

### ISSUE THREAD

**Issue by kehey** [jupyter/notebook#727]
Since kernels keep on running even when closing the notebook, and you can connect a new frontend to an existing kernel ([link](http://nbviewer.ipython.org/github/ipython/ipython/blob/3.x/examples/Notebook/Connecting%20with%20the%20Qt%20Console.ipynb)), would it not technically be possible to connect a notebook to an existing kernel? And thus allow for people to switch a notebook between running python and running R kernels so that switching does mean loosing all objects in memory?

**Comment by cjermain** [comment]
Check out [takluyver/nbopen](https://github.com/takluyver/nbopen/) as a possible solution.

**Comment by Carreau** [comment]
Technically, yes it is feasible, There are though many abstractions, API, UI that would be complex, and the use case are rare enough that we haven't taken the time to do that. 

I suppose it should be doable only with an extension, not sure though.

**Comment by kehey** [comment]
I have no insight in the complexity of the API and UI, so perhaps a naive question: would the UI need to be complex? 

Would it not be possible to add a magic command such as %connect_info (but then one that executes the actuall connection) on top of every cell (and having a default set at the kernel in which you started so that people only need to type it when necesary)? For me, I wouldn't even expect changes in the UI. I still can't speak about the API and abstractions.

**Comment by Carreau** [comment]
No, the magics are kernel specific and many non-python kernel do not have magics. 

The current server have mapping from filename to kernel and keep track of which file is associated with which kernel. We would need a one-to-many mapping with a notion of currently active, with API to switch. Also when you would restart or shut-down a kernel, would it restart/shutdown only  the current one ? Or all kernels ?

While I see why it would make some sens in a some case, I'm not sure the cost/benefit is worth such complexity yet.

There is also users asking for many kernel at once on the page, with variable kernel on a per cell basis. 

I think the [metakernel or calico kernel](https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages) use to have the ability to actually proxy to other subkernels, so from the UI perspective there was 1 kernel, and with `%%%lang` you could change the current lang of the kernel. 
It had advantages and drawback.

**Comment by dsblank** [comment]
MetaKernel is alive and well, and should not be referred to in the past tense... it doesn't like that :)

MetaKernel is a completely different project from Calico, although some of the same people are involved. Calico is a kernel that dispatches to different languages. It is no longer in active development, but still works. MetaKernel can indeed start up subkernels using the %kernel and %kx magics. 

There are many kernels based on MetaKernel, including Matlab, Octave, Java9, Processing, Assembly language, and more.

For more on subkernels, see:

https://github.com/Calysto/metakernel/blob/master/metakernel/magics/README.md

**Comment by Carreau** [comment]
Sorry for metakernel, I used past in the send that I wasn't sure it was this kernel that had this ability and wether t still had it. I can buy metakernel a coffee next time as an apology. 

I'm at the airport so I keep my messages short. But thanks for reminding us of the various pieces and how they work!

Envoyé de mon iPhone

**Comment by kehey** [comment]
Okay, thanks for the comments and info all of you! :-)
