### ISSUE TITLE
Menu item not clickable on mobile device unless doing in a quite strange way

### ISSUE THREAD

**Issue by sdshq** [jupyter/notebook#7270]
## Description

I ran into this issue using a mobile device (Huawei Matepad Pro 13.2') with a external mouse. The issue happens consistently in the official Jupyter Notebook/Lab/Lite demos. When clicking a 1st level menu (e.g. File), I can't make any 2nd-level item (e.g. New) to take effect by just clicking it. I have to do that in a quite strange way: 1) hover on the item, 2) press the left mouse button and hold, 3) slightly move the mouse,  and finally get the menu item working.

## Reproduce

As described above.

## Expected behavior

I need the menu work like any other normal apps.

## Context

- Operating System and version:  HarmonyOS 4.0 (which is based on Android 12).
- Browser and version:  Kiwi, Edge, and other Chromium based browsers.

- Jupyter Notebook version:   Latest versions on Jupyter official demos.

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
[ I ran into this issue in Jupyter official demos ]
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter notebook` here, use `--debug` if possible.
[ I ran into this issue in Jupyter official demos ]
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by jtpio** [comment]
Thanks @sdshq for the report :+1: 

> The issue happens consistently in the official Jupyter Notebook/Lab/Lite demos

Maybe we should open the issue on the JupyterLab repo then? https://github.com/jupyterlab/jupyterlab
There will be a higher chance to get it fixed there. Notebook 7 (developed in this repo) just reuses the JupyterLab components as is.
This might also be something to fix in Lumino directly: https://github.com/jupyterlab/lumino

**Comment by sdshq** [comment]
> This might also be something to fix in Lumino directly: https://github.com/jupyterlab/lumino
This may be true since I get the same experience when exploring other solutions that seem also based on lumino (e.g.  Theia).

**Comment by sdshq** [comment]
After reinstalling browsers/termux for some times, I can no longer re-produce this issue.
Closing this issue to not disturb others.
