### ISSUE TITLE
Add support for reading token from file

### ISSUE THREAD

**Issue by radusuciu** [jupyter/notebook#7286]
When running jupyter in a containerized environment it's convenient to provide a token using a file or envvar. This used to be supported in previous versions of Jupyter:

- https://github.com/jupyter/notebook/pull/2921
- https://github.com/jupyter/notebook/pull/5587

**Comment by jtpio** [comment]
@radusuciu which version of Notebook are you using?

If it's Notebook 7, then this issue should be open on the Jupyter Server, because Notebook 7 uses Jupyter Server: https://github.com/jupyter-server/jupyter_server

**Comment by radusuciu** [comment]
@jtpio you're right, I did not realize that the server component was spun out. There might still be an issue since I've tried both of these envvars to no effect, but I'll try and have a repro case before re-raising the issue since it does seem like there are code and tests for this feature in the jupyter server repo.

Thank you.
