### ISSUE TITLE
Pages for ports 8888 and 8889 are blank

### ISSUE THREAD

**Issue by angelfish0808** [jupyter/notebook#7330]
After the new version 7.13 is opened, the pages with ports 8888 and 8889 are blank, and those after 8890 are normal. When testing jupyterlab, there is no such problem.
![image](https://github.com/jupyter/notebook/assets/157368558/7c5c815d-32f8-4024-acbd-26e5ce127f04)
![image](https://github.com/jupyter/notebook/assets/157368558/16f4e3fa-be31-4495-9a78-274d3155e2a7)

**Comment by navaneethnpk** [comment]
Having the same issue in two of my conda env where 
```
(env1) student@zbook15:~$ jupyter notebook --version  
7.0.8
```
```
(env2) student@zbook15:~$ jupyter notebook --version  
7.1.3
```

**Comment by JasonWeill** [comment]
Does this problem persist after you clear your browser's cache and local storage? It's possible that something is being cached as an application manifest for `localhost:8888` and `8889` from a prior version, for example.

**Comment by JasonWeill** [comment]
@angelfish0808 Any update on this issue after you clear your browser's cache and local storage? Thanks!

**Comment by angelfish0808** [comment]
@JasonWeill @RRosio @navaneethnpk I didn't clear the cache, but I recently automatically updated other dependency packages, and now I can open them normally.
