### ISSUE TITLE
issues with 15 apr release of pyzmq on Windows

### ISSUE THREAD

**Issue by malgarop** [jupyter/notebook#7332]
## Description

When installing jupyter on a new windows machine, it will fail to connect to any python3 kernel, with the following error popup: "Error Starting KernelNetworkError when attempting to fetch resource."

## Reproduce

On a Powershell on a Windows 11 machine with python 3.12.3:
1. 'pip install jupyter'
2. 'python -m jupyter notebook' or 'jupyter-lab'
3. start a new notebook, or open an existing one, with python3 kernel
4. process fails and error pops up. In the shell I get the following output: 
"Bad file descriptor (C:\Users\runneradmin\AppData\Local\Temp\tmp9czwcdbh\build\_deps\bundled_libzmq-src\src\epoll.cpp:73)"

It works after I uninstall pyzmq and reinstall the Dec 5, 2023 version: 
1. 'pip freeze | findstr pyzmq'
 output: "pyzmq==26.0.0"
2. 'pip uninstall pyzmq'
3. 'pip install pyzmq==25.1.2'

## Context

- Operating System and version: Windows 11
- Browser and version: Firefox 125.0.1 (64-bit), Chrome 124.0.6367.61 (Official Build) (64-bit)

- Jupyter Notebook version: 
Selected Jupyter core packages...
IPython          : 8.23.0
ipykernel        : 6.29.4
ipywidgets       : 8.1.2
jupyter_client   : 8.6.1
jupyter_core     : 5.7.2
jupyter_server   : 2.14.0
jupyterlab       : 4.1.6
nbclient         : 0.10.0
nbconvert        : 7.16.3
nbformat         : 5.10.4
notebook         : 7.1.3
qtconsole        : 5.5.1
traitlets        : 5.14.2

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter notebook` here, use `--debug` if possible.
[I 2024-04-18 17:13:42.172 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-04-18 17:13:42.180 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-04-18 17:13:42.185 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-04-18 17:13:42.194 ServerApp] notebook | extension was successfully linked.
[I 2024-04-18 17:13:42.482 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-04-18 17:13:42.546 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-04-18 17:13:42.546 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-04-18 17:13:42.546 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-04-18 17:13:42.554 LabApp] JupyterLab extension loaded from C:\Users\XXXXXXX\XXXXXXX\venv\Lib\site-packages\jupyterlab
[I 2024-04-18 17:13:42.554 LabApp] JupyterLab application directory is C:\Users\XXXXXXX\XXXXXXX\venv\share\jupyter\lab
[I 2024-04-18 17:13:42.555 LabApp] Extension Manager is 'pypi'.
[I 2024-04-18 17:13:42.927 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-04-18 17:13:42.936 ServerApp] notebook | extension was successfully loaded.
[I 2024-04-18 17:13:42.936 ServerApp] Serving notebooks from local directory: C:\Users\XXXXXXX\XXXXXXX
[I 2024-04-18 17:13:42.936 ServerApp] Jupyter Server 2.14.0 is running at:
[I 2024-04-18 17:13:42.936 ServerApp] http://localhost:8888/lab?token=XXXXXXXXXXXXXXXXXXXXXXX
[I 2024-04-18 17:13:42.936 ServerApp]     http://127.0.0.1:8888/lab?token=XXXXXXXXXXXXXXXXXXXXXXX
[I 2024-04-18 17:13:42.936 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-04-18 17:13:42.981 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/XXXXXXX/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/Roaming/jupyter/runtime/jpserver-36904-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=XXXXXXXXXXXXXXXXXXXXXXX
        http://127.0.0.1:8888/lab?token=XXXXXXXXXXXXXXXXXXXXXXX
[I 2024-04-18 17:13:43.101 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-04-18 17:13:45.227 LabApp] Could not determine jupyterlab build status without nodejs
[I 2024-04-18 17:13:49.010 ServerApp] Creating new notebook in
Bad file descriptor (C:\Users\runneradmin\AppData\Local\Temp\tmp9czwcdbh\build\_deps\bundled_libzmq-src\src\epoll.cpp:73)

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by minrk** [comment]
@malgarop thanks for reporting! Can you move this to https://github.com/zeromq/pyzmq/issues ? 

This is an underlying issue in libzmq somewhere, and I'll need to figure out some more info about why some Windows systems are compatible, but others are not.

**Comment by malgarop** [comment]
sure! opened https://github.com/zeromq/pyzmq/issues/1981

**Comment by minrk** [comment]
thank you! closing in favor of https://github.com/zeromq/pyzmq/issues/1981
