### ISSUE TITLE
Markdown Syntax Highlighting in IE11

### ISSUE THREAD

**Issue by gracana** [jupyter/notebook#734]
![jupyter_markdown_syntax](https://cloud.githubusercontent.com/assets/9268280/11244022/7ffe551a-8dd9-11e5-964e-b70de9de5395.png)

I'm running Jupyter 4.0.6 on Windows (installed using anaconda), and I'm viewing the notebook with IE11. Markdown syntax highlighting is broken as shown above. It looks like the highlighted text is displayed using the rendered text style plus blue.

**Comment by Carreau** [comment]
IIRC, this has been fixed in codemirror. Either you can manually update codemirror, or next release should have this fixed automatically.

**Comment by Carreau** [comment]
Fixed on codemirror master.
