### ISSUE TITLE
Is there a way to disable saving to checkpoints folder（.ipynb_checkpoints） for Jupyter Notebooks?

### ISSUE THREAD

**Issue by LBJ6666** [jupyter/notebook#7348]
version:
notebook==6.4.6
ipython==8.14.0
ipython-genutils==0.2.0

Try setting it in Jupyter's configuration file jupyter_notebook_config.py：
c.NotebookApp.checkpoints_enabled = False
but it didn't work

**Comment by JasonWeill** [comment]
@LBJ6666 Thank you for your contribution! It looks like this is already open as an enhancement in JupyterLab, which shares code with Jupyter Notebook: https://github.com/jupyterlab/jupyterlab/issues/11826

Let's keep the conversation going in the issue linked above.
