### ISSUE TITLE
Provide option to load nbextensions not inside nbextensions/ Jupyter.utils.load_extension 

### ISSUE THREAD

**Issue by ericjang** [jupyter/notebook#736]
When developing new nbextensions, debugging it must migrate the extension build to the ~/.jupyter/nbextensions folder. Is this intentional or should there be a feature to let the user specify the absolute file path to include?

**Comment by minrk** [comment]
It is intentional that only the nbextensions directory is served. For development, you can use symlinks, if that helps.
