### ISSUE TITLE
Trouble rendering \tilde LateX command.

### ISSUE THREAD

**Issue by furetosan** [jupyter/notebook#737]
I'm compiling LateX via MathJax.js (a small window shows up to the bottom left when a markdown cell containing LateX gets executed).

For instance, if I need \tilde \epsilon, it doesn't compile, but with \bar \epsilon, this works fine.

I'm running iPython 4.1.0-dev on Python 3.5 on an updated Mac Air.

Cheers!

**Comment by Carreau** [comment]
which version of `notebook` (not IPython), if `\binom{1}{3}` this has been fixed in notebook 4.0.6

**Comment by Carreau** [comment]
Closing as likely fixed.
