### ISSUE TITLE
Flaky UI tests

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#7370]
It looks like we still have some flakiness with the notebook toolbar sometimes missing the overflow button menu:

![image](https://github.com/jupyter/notebook/assets/591645/7c5c635f-622c-45e2-b0ed-6d08dcc60172)

cc @brichet who looked into the notebook toolbar recently (as part of https://github.com/jupyter/notebook/issues/7311) and may know if that might also be happening in JupyterLab.

_Originally posted by @jtpio in https://github.com/jupyter/notebook/issues/7361#issuecomment-2110267357_

**Comment by brichet** [comment]
Thanks @jtpio for the ping.

Wondering if this is only a matter of time for the button to be visible, and if we want to fix it (if it's inconvenient to use) or only fix the test (waiting for the button to be visible).
Did you notice the missing button outside the tests?

**Comment by jtpio** [comment]
> Did you notice the missing button outside the tests?

Usually not, so it might indeed just be an issue with the tests.

There is some logic to wait for the kernel status animations to be gone before taking the screenshot, which may not be enough: 

https://github.com/jupyter/notebook/blob/08fe5c5df12182178280bad5d2fbae02b3486146/ui-tests/test/mobile.spec.ts#L58-L59

But maybe there could indeed also be a check to wait for that button to be visible, just to be sure.

**Comment by brichet** [comment]
I can take a look at the test and we'll see if it's enough.

**Comment by brichet** [comment]
Probably related to https://github.com/jupyter/notebook/pull/6731, see https://github.com/jupyter/notebook/pull/7371 for details.

**Comment by jtpio** [comment]
Re-opening to keep track of updating to a new JupyterLab version, and check if it fixes the flakiness.

**Comment by jtpio** [comment]
From https://github.com/jupyter/notebook/pull/7378 (which should include https://github.com/jupyterlab/jupyterlab/pull/16335), it looks like this time it is the button to toggle the virtual scrollbar that is sometimes showing up:

| Actual | Expected |
| :---: | :---: |
| ![image](https://github.com/jupyter/notebook/assets/591645/15e2bd95-cae6-4811-a96d-433cb7e483a2) | ![image](https://github.com/jupyter/notebook/assets/591645/44ca4782-0d03-4b1f-825f-4aa837c86ba4) |

**Comment by brichet** [comment]
Opened https://github.com/jupyterlab/jupyterlab/pull/16409, it fixes this issue locally, during tests and usage.
Too bad that we don't have yet an easy way to run all the tests on CI with this PR...

**Comment by jtpio** [comment]
Yes, thanks for looking into them!

I'll re-open to keep track of it, which should be fixed after the next JupyterLab update.

**Comment by jtpio** [comment]
Closing as likely fixed by https://github.com/jupyter/notebook/pull/7416.

We can re-open if the failure still happens in the future. Thanks!
