### ISSUE TITLE
Nothing shown in the browser Safari when notebook is upgrade to 7.2.0

### ISSUE THREAD

**Issue by YuccaTang** [jupyter/notebook#7373]
I have upgraded the notebook and Jupyter Lab to the latest versions this morning. But when the browser pops up, only blank is seen.

**Comment by yutang-1sec** [comment]
But it works in Google Chrome.

**Comment by yutang-1sec** [comment]
> Thanks @yutang-1sec for reporting.
> 
> Are you able to clear the browser cache and reload the page to check if notebook properly loads?
> 
> Wondering if that might be related to #7354, as some users have reported similar issues previously.

Many thanks. It works after clearing the browser cache.

**Comment by jtpio** [comment]
Thanks for checking and answering back.

We'll be looking into finishing #7354 to fix this issue for future versions.

**Comment by jtpio** [comment]
@YuccaTang we just published version `7.3.0b2` which should hopefully help fix the issue.

Would you be able to try this version, for example in a new environment? The idea would be to install a previous version, and then update to the new one, and check Notebook can be loaded properly.

**Comment by jtpio** [comment]
Hey all,

We just published version 7.3.0b2 which should hopefully help fix the issue.

Would you be able to try this version, for example in a new environment? The idea would be to install a previous version, and then update to the new one, and check Notebook can be loaded properly. Thanks!
