### ISSUE TITLE
Cell selection and commands

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#738]
Meta issues to list commands that we might want to apply on selection/marked cell. 

- Clear cell output
- change to code/markdown

**Comment by Carreau** [comment]
PIng @ellisonbg @fperez

**Comment by fperez** [comment]
* Copy/Cut/Delete

**Comment by Carreau** [comment]
@parleur Still waiting for your PR. I know it was working.

**Comment by Carreau** [comment]
see #802 #803 #804 #792 #793 #794 #795 #796 #797
