### ISSUE TITLE
Remove debug statements introduced in #729

### ISSUE THREAD

**Issue by captainsafia** [jupyter/notebook#740]
Logging of debug statements was added in #729 in order to aid with debugging an issue with strange file change messages outlined in #484.

This is a reminder to remove these debug statements once the issue in #484 has been resolved.

cc/ @ellisonbg @Carreau @jdfreder @fperez

**Comment by fperez** [comment]
Tagging this 4.2 may be wishful thinking, but let's see how it goes.

**Comment by Carreau** [comment]
#484  has still not been solved, or seen again. Bumping to 4.4 for now.

**Comment by ragnerok** [comment]
Hi, I'd like to take this one up! Correct me if I am wrong, all I have to do is remove the file changes done  by @Carreau on his PR #729

**Comment by Carreau** [comment]
Hi @ragnerok ; Yes if they are still there; you can remove them.

If you are incomfortable with Git or anything else feel free to ask for guidance.

**Comment by jzf2101** [comment]
@takluyver is this ready to close?
