### ISSUE TITLE
Entering numbers in output automatically changes the code cell to markdown and kernel hangs

### ISSUE THREAD

**Issue by vinoth137** [jupyter/notebook#7415]
## Description

I installed the latest version of anaconda (version 24.5.0) and launched the Jupyter Notebook. I created my own environment which had the default python packages. 

`!jupyter --version`

Selected Jupyter core packages...
IPython          : 8.25.0
ipykernel        : 6.28.0
ipywidgets       : not installed
jupyter_client   : 8.6.0
jupyter_core     : 5.7.2
jupyter_server   : 2.14.1
jupyterlab       : 4.2.2
nbclient         : 0.8.0
nbconvert        : 7.10.0
nbformat         : 5.9.2
notebook         : 7.0.8
qtconsole        : not installed
traitlets        : 5.14.3

## Steps to reproduce the issue

1. For example, I tried the below code with the cell type selected as 'Code'

import calendar

year = int(input("Enter the year: "))
month = int(input("Enter the month: "))

cal = calendar.month(year,month)
print (cal)

![image](https://github.com/jupyter/notebook/assets/16617754/78fd928a-638d-4b84-8df0-2a719a7f833d)

2. Click on the Run button in the notebook.
3. The output prompt shows "Enter the year: [

![image](https://github.com/jupyter/notebook/assets/16617754/5dabd034-aedf-46b0-bac8-e0a4f831406c)

4. The moment I type 2, the cell automatically changes from Code to Markdown. It adds 2 hashes at the begining of the code.

![image](https://github.com/jupyter/notebook/assets/16617754/8e38b87c-1d03-47c7-8162-c35663d83d5b)

After this unexpected cell type switch, the kernel runs in a continous loop. It has to be restarted by clearing all outputs. 
The cell type has to be manually changed from 'Markdown' to 'Code' to make changes. 

## Expected behavior

Ideally, the cell should have remained in 'Code' and accepted the input for 'year' and proceeded to the next input 'month'.

**Comment by vinoth137** [comment]
@RRosio Thanks for your suggestion. I upgraded my Jupyter Notebook to **7.2.1** but the issue still persists. 
![image](https://github.com/jupyter/notebook/assets/16617754/a4f9e252-d7e4-48ee-9bbb-c638d54bd895)

To be sure, I shutdown my notebook instance and tried again with a fresh one. The problem is still recurring. The moment you type the number in the output, it adds two hashes to the first line of the code and the cell type changes from 'Code' to 'Markdown' automatically. 

Here's some new information. I noticed that this version of Jupyter takes the input of selective strings only. For example, if you type 'a' , then it automatically adds a new empty Mardown cell at the top. In the below example, I tried to type 'Adam'. I know that 'A' is a shortcut for adding new cells above, but ideally this behaviour should not happen in the output area while the kernel is executing the code. 

Have also noticed if string inputs, if you enter numbers, it adds the equal number of # in the first line of code. 

![image](https://github.com/jupyter/notebook/assets/16617754/3feb9d0c-311c-4be0-aee6-9178b2a22252)

For int and float input, if you enter a number then immediately this problem occurs.

**Comment by krassowski** [comment]
> The moment I type 2, the cell automatically changes from Code to Markdown. It adds 2 hashes at the begining of the code.

This is related to a "feature" - it allows you to change markdown heading level (e.g. 2 will add two hashes, 3 will add three etc). I think this should not be active for code cells.

Your other issue about typing in `input()` was a bug that was fixed upstream. Can you try an alpha version of 7.3?

**Comment by vinoth137** [comment]
@RRosio and @krassowski : Thank you so much for your inputs. 
The problem was persistent in notebook 7.2.1 even though I didn't have any chrome browser extensions installed. 
So, I thought it would be better to do a clean reinstallation of Anaconda. 
My current Jupyter notebook version is 7.0.8 and the above issue hasn't come up. 
For now, the notebook is working as expected.
