### ISSUE TITLE
Support the new filebrowser filter

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#7424]
As noticed in https://github.com/jupyter/notebook/pull/7423

Notebook should also support the new changes related to the file browser filter which landed in https://github.com/jupyterlab/jupyterlab/pull/16446.

![image](https://github.com/user-attachments/assets/a3887c02-8413-4fea-ad7f-bc83e0503149)

To be done after https://github.com/jupyter/notebook/pull/7423 is merged.

**Comment by RanjanRavi2398** [comment]
@jtpio I would like to contribute and develop it shortly

**Comment by jtpio** [comment]
Thanks @RanjanRavi2398!

Please feel free to open a draft PR when you have something, even if it's not fully finished yet.
