### ISSUE TITLE
Syntax highlighting not on by default

### ISSUE THREAD

**Issue by ai-robert** [jupyter/notebook#7437]
Hello, following up on #7427 .
issue: Syntax highlighting not on by default
OS: windows 11 64 bit
Versions I tried two different versions of Jupyter7, first I was using Jupyter 7.0.8 bundled with Anaconda (which I saw is the recommended practice on the install jupyter page). Then after reading issue https://github.com/jupyter/notebook/issues/7368 as @JasonWeill said I tried force upgrading jupyter with pip which gave me a 7.2.x build. It definitely wasn't working on the 7.0.8 with anaconda, and then I only briefly tried it on the 7.2.x before deciding to go back to Jupyter 6.x

**Comment by JasonWeill** [comment]
Syntax highlighting is on by default in Notebook 7, but it does not work exactly as in Notebook 6. @ai-robert please provide the improvements you'd like to see, and we can reopen this issue. Thanks!
