### ISSUE TITLE
Context-aware auto-indenting not on by default

### ISSUE THREAD

**Issue by ai-robert** [jupyter/notebook#7438]
Hello, following up on https://github.com/jupyter/notebook/issues/7427 .
issue: Context-aware auto-indenting not on by default
OS: windows 11 64 bit
Versions I tried two different versions of Jupyter7, first I was using Jupyter 7.0.8 bundled with Anaconda (which I saw is the recommended practice on the install jupyter page). Then after reading issue https://github.com/jupyter/notebook/issues/7368 as @JasonWeill said I tried force upgrading jupyter with pip which gave me a 7.2.x build. It definitely wasn't working on the 7.0.8 with anaconda, and then I only briefly tried it on the 7.2.x before deciding to go back to Jupyter 6.x

**Comment by JasonWeill** [comment]
@ai-robert When you provide more information about your expectations for context-aware auto-indenting, and what you'd like to see on by default in Notebook 7, we can reopen this issue. Thanks!
