### ISSUE TITLE
import error dll load failed while importing rpds : the special procedure could not be find in while run jupyter

### ISSUE THREAD

**Issue by mkarimiFard** [jupyter/notebook#7440]
Hi everyone
im used windows 7 and i do install jupyterlab from pip install jupyter lab and successful install then i jupyter lab in cmd this show me (import error dll load failed while importing rpds : the special procedure could not be find in while run jupyter) 
whats wrong?
i update drivers and windows
thankyou

**Comment by JasonWeill** [comment]
@mkarimiFard Thanks for opening this issue! This repository is for Jupyter Notebook; the JupyterLab issues repository is https://github.com/jupyterlab/jupyterlab/issues/ . Windows 7 reached end of life in January 2020, so applications like JupyterLab may no longer work with it.

Please open an issue in the JupyterLab repo, providing all relevant details, including the versions of all related packages, the version of Python you're using, and any logs you get when you run `jupyter lab`. Thanks!

**Comment by prettycms** [comment]
I have the same question.
