### ISSUE TITLE
Jupyter Password/Security token comes in some of the time

### ISSUE THREAD

**Issue by zarif98** [jupyter/notebook#7443]
![image (9)](https://github.com/user-attachments/assets/01cf250e-559d-4f19-b7a4-bc7a84bd9972)

I have noticed amongst our machines that the security token only comes in some of the time. Is there a reason why the security token box gets triggered?

**Comment by JasonWeill** [comment]
I've only seen that box appear when I use a new browser, or when I'm using a browser that does not retain data from prior sessions — such as a browser in private or incognito mode. Is your browser set up to discard data regularly, such as every day or on exit?

**Comment by zarif98** [comment]
So we use Chromium for all of our machines. We use Microsoft Edge but we don't believe we have any settings that does not retain data from prior sessions. Right now, everything feels a little random and we'd like to figure out why. We don't want to stop this authentication but would like to know how we can be secure and maybe not have it pop up at the same time.

**Comment by zarif98** [comment]
Sorry forgot to respond but yes! We are planning on putting some logs in and checking it from our end to really see what is going on. Thanks for the comment, it was insightful to look into what was actually ticking this feature.
