### ISSUE TITLE
LaTeX labels getting auto compiled in code cells

### ISSUE THREAD

**Issue by SaptarshiSrkr** [jupyter/notebook#7460]
## Description

Jupyter notebook (also lab) compiles latex automatically in code cells, changing plotting labels.

For example:

`$text$` gets modified to `texttext`
`$\mu$` gets modified to `μ\mu`

## Reproduce

1. Add a new cell.
2. Enter `$text$`
3. The cell automatically converts to texttext.

## Context
OS: Ubuntu 24.04.1 LTS
The issue is only seen on 2024 versions of Anaconda + texlive-full (pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian)).

**Comment by SaptarshiSrkr** [comment]
I reinstalled Anaconda twice, and it looks like it fixed itself after the second reinstall. I will close this issue for now, but am sharing the requested details below if it ever happens again.

Version:

Selected Jupyter core packages...
IPython          : 8.25.0
ipykernel        : 6.28.0
ipywidgets       : 7.8.1
jupyter_client   : 8.6.0
jupyter_core     : 5.7.2
jupyter_server   : 2.14.1
jupyterlab       : 4.0.11
nbclient         : 0.8.0
nbconvert        : 7.10.0
nbformat         : 5.9.2
notebook         : 7.0.8
qtconsole        : 5.5.1
traitlets        : 5.14.3

The bug was happening in the notebook itself, few moments after typing in the label, it would automatically remove the dollar signs and compile the LaTeX command within the cell.

**Comment by krassowski** [comment]
> notebook : 7.0.8
> jupyterlab : 4.0.11

These are very old versions with know security vulnerabilities, I would advise upgrading to the latest versions. If that is shipped with Anaconda by default I would raise it with their support.
