### ISSUE TITLE
Cannot run JupyterLab on NGINX

### ISSUE THREAD

**Issue by manel00** [jupyter/notebook#7464]
## Description

When I am running NGINX with Jupyterlab, I can access but I am retrieving the following error in Console on Firefox

`Ha fallado la carga del <script> con origen "http://127.0.0.1:8080/static/lab/main.b19b8a0b5c015351f92f.js?v=b19b8a0b5c015351f92f".`

I set up with the URL localhost:8080/lab

`
services:
  lab:
    build:
      context: .
      dockerfile: ./Dockerfile_lab
    volumes:
    - ./notebooks:/home/jovyan/work/python_app
    # - ./coger_conf:/home/coger_conf
    - ./.jupyter:/home/jovyan/.jupyter
    ports:
      - 8888:8888
    # container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="
`

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 

- Jupyter Notebook version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter notebook` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
We haven't received other information about this, so I'm going to close this issue. Please feel free to open another issue if you still see this problem. Thanks for your contribution!
