### ISSUE TITLE
Clicking the status circle could take you to the currently executing cell

### ISSUE THREAD

**Issue by stuaxo** [jupyter/notebook#7478]
When I'm quickly scrolling up and down it's sometimes hard to tell where the current cell is.

The status circle shows how far execution has gone, it would be nice if clicking it went to the currently executing cell.

![Image](https://github.com/user-attachments/assets/3db6f03d-5ebb-464d-810f-3637f70e7631)

**Comment by mohitsharma012** [comment]
please assign this to me

**Comment by jtpio** [comment]
Since Notebook is based on JupyterLab, this would need to be implemented in the JupyterLab repo directly: https://github.com/jupyterlab/jupyterlab

Feel free to open a new issue on https://github.com/jupyterlab/jupyterlab and/or a draft PR there, thanks!

**Comment by stuaxo** [comment]
Thanks, I opened a replacement issue here https://github.com/jupyterlab/jupyterlab/issues/16867
