### ISSUE TITLE
Deleting notebook running notebook and creation of new notebook with same name.

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/notebook#748]
1. Create a notebook (`Untitled.ipynb`)
2. run `a = 100` in the first cell
3. delete the notebook from the file system (from a console)
4. Create a new notebook. The same `Untitled.ipynb` is created.
5. Apparently, it is connected to the same old kernel as the first version of `Untitled.ipynb`.
   (a is 100, prompt number starts a 2.)

**Comment by minrk** [comment]
We can't feasibly watch filesystem events to ensure that nobody is breaking running state like this. When do you propose we detect that the notebook has been deleted, and what action should we take? Destroy the kernel? If the user with the open notebook presses, or waits for autosave at any point, the state returns to being consistent.

**Comment by SylvainCorlay** [comment]
OK, I was expecting a `wontfix` anyway. I think that it is fine.

**Comment by minrk** [comment]
I think we could add a sanity-check on session-list or other action, or even a periodic sweep. I'm just not quite sure what the right action is, since it will necessarily be automatic and have no prompting.

**Comment by SylvainCorlay** [comment]
Closing as I am not sure this can be fixed in a reasonable way.
