### ISSUE TITLE
Error loading html / javascript

### ISSUE THREAD

**Issue by stefanseefeld** [jupyter/notebook#749]
I'm trying to embed a snakeviz plot into a notebook. My notebook profiles a chunk of code, generates a pstats table, and passes that to snakeviz. This appears to be working as expected when I dump the generated html to a static file and then load that separately into a browser. 
However, when attempting to embed the html into the current notebook, it generates these javascript errors:

Uncaught TypeError: $(...).dataTable is not a function
profiler.ipynb:4 Uncaught ReferenceError: Immutable is not defined
profiler.ipynb:104 Uncaught ReferenceError: sv_call_stack is not defined
profiler.ipynb:17 Uncaught ReferenceError: sv_root_func_name is not defined

The notebook console output shows all the relevant javascripts being loaded, though the above error suggests the javascript runtime doesn't quite contain the expected objects.

As it's unfortunately not possible to attach tarballs to bug reports I have checked in the notebook into my repo fork at https://github.com/stefanseefeld/notebook/tree/bug (into the 'testcase' subdirectory in the 'bug' branch.

**Comment by Carreau** [comment]
You cannot embed a full html document with doctype and headers into another page unless you use an iframe, you will likely get undefined behavior from browser. 

So either use IFrame and set src, or refactor your template to only include the relevant part of snakeviz.

**Comment by stefanseefeld** [comment]
Thanks for catching this. I committed a little fix for this. The original (javascript) error however remains.

**Comment by stefanseefeld** [comment]
Any chance someone could confirm this to be a notebook bug ?

**Comment by embray** [comment]
@stefanseefeld I don't think this is a notebook bug.  It looks like you're loading a second instance of jquery on top of the one already used by the notebook before loading the dataTable plugin.  This is likely leading to confusion with respect to which jquery is which, and which one is getting the dataTable plugin registered on it.  This is probably the problem in #499 as well.

Some clearer developer documentation on how to define and require JS dependencies through AMD / RequireJS might be helpful here, as this is a (relatively) new thing many people (myself included) won't be highly familiar with.

**Comment by stefanseefeld** [comment]
@embray , thanks for the tip ! Unfortunately commenting out the <script> element loading the jquery in the template didn't seem to make a difference.

**Comment by damianavila** [comment]
@minrk I talked with you about this shortly in the chat room... thoughts?

**Comment by embray** [comment]
Right, but that probably wouldn't make a difference.  If I understand correctly the notebook is using RequireJS (e.g. https://github.com/jupyter/notebook/blob/master/notebook/templates/page.html#L21) to load all JS modules.  This loads all JS asynchronously, but performs dependency resolution to ensure that scripts are loaded in the correct order based on their dependencies.  So for jQuery plugins for example it's going to be important that they're loaded *after* jQuery (though I would think you would get an error from the plugin if `jQuery` isn't found in the globals?)

In any case, because of this scripts embedded directly in the page with `<script>` tags will run synchronously, more or less as soon as the browser parses the HTML.

**Comment by stefanseefeld** [comment]
Ah, so if I understand correctly the proper way to resolve this would be to 'AMDify' all the javascript modules used by snakeviz, and then use requirejs to load. Correct ?

**Comment by minrk** [comment]
Yes, that's likely the right fix for how to load js in the notebook. In general, require is the way to go in the notebook.

**Comment by stefanseefeld** [comment]
OK, thanks. I was able to work around the issue by embedding my html into an iframe. Everything appears to be working fine with that.

Thanks all for your help !

**Comment by bartaelterman** [comment]
Hi guys,

@stefanseefeld has been able to work around the issue, but I haven't. I'm also trying to use the dataTable plugin for jQuery, but I keep having a `TypeError: $(...).DataTable is not a function` error. I have included the dataTable library now with requirejs:

```
%%javascript
require.config({
  paths: {
      datatables: '//cdn.datatables.net/1.10.11/js/jquery.dataTables.min'
  }
});
```

but that doesn't seem to help. Can anyone help me how to add jQuery plugins to the notebook properly?

**Comment by embray** [comment]
@bartaelterman It's not enough to just provide a path for a JS module.  You need to activate it, in this case by providing a "shim" configuration.  See http://requirejs.org/docs/api.html#config-shim for documentation, and https://github.com/requirejs/example-jquery-shim for a complete example.

**Comment by bartaelterman** [comment]
Thanks. Adding `shims: datatables: ["jquery"]` to the `require.config` object doesn't help. [This SO post](http://stackoverflow.com/questions/20093957/configuring-jquery-datatable-with-require-js-and-using-with-backbone-js) says that dataTables is already an AMD module and that there is no need to add a shim for it. However, that doesn't help either as that brings me back to the previous situation.
Remains only one thing I guess: that `baseUrl` in the require config. The notebook source code you were referring to earlier sets this baseUrl using template tags, so I'm not sure to what it is set, and whether I should set the same url when trying to add dataTables. Any thoughts?
