### ISSUE TITLE
Can not reload module automatically when use Jupyter in VS code.

### ISSUE THREAD

**Issue by luomeng007** [jupyter/notebook#7500]
[Problem](https://github.com/microsoft/vscode/issues/229123#issuecomment-2363049572).

Is there anyone who can help me check this? Any solutions about this one? I asked VS code engineer, but they labeled this as an extension error. Thus now I turn to Jupyter for help.

**Comment by JasonWeill** [comment]
@luomeng007 It looks like you're having a problem with the Jupyter functionality in Visual Studio Code. This might be covered by the [Jupyter VS Code extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter), which has its own GitHub repo: https://github.com/Microsoft/vscode-jupyter

This repository is for the Jupyter Notebook application, which is not associated with Visual Studio Code. Please follow up with the developers of the application or extension you're using. Thanks for your interest!

**Comment by luomeng007** [comment]
Thank you, I see.
