### ISSUE TITLE
On "Undo" action, scroll to cursor position

### ISSUE THREAD

**Issue by kuraga** [jupyter/notebook#7514]
### Problem

On the "Find" action, the browser scrolls to the found position. (So we _can_ do it.)

On the "Undo" action, the browser _doesn't_ scroll to the cursor-after-undo position.

### Proposed Solution

On the "Undo" action, scroll to the cursor-after-undo position.

### Additional context

Just imagine the cell is big...

**Comment by krassowski** [comment]
This is tracked in:
- https://github.com/jupyterlab/jupyterlab/issues/15102
- https://github.com/jupyter-server/jupyter_ydoc/issues/240

**Comment by kuraga** [comment]
Ok, thanks!
