### ISSUE TITLE
Adopt pandas-style Jupyter contribution guide

### ISSUE THREAD

**Issue by captainsafia** [jupyter/notebook#754]
During the November 24th developer meeting, there was a discussion around the friendliness and accessibility of our documentation, especially with regard to new contributors.

I'd like to propose that we create a new Jupyter Contribution Guide that goes a step beyond the previous [IPython Contribution Guide](https://github.com/ipython/ipython/blob/master/CONTRIBUTING.md) that we link to in all of the repositories and incorporates some of the great additions @jhamrick made to the contribution guide.

I selected `pandas` as a model for a contribution guide because [their guide](https://github.com/pydata/pandas/blob/master/CONTRIBUTING.md) was immensely helpful to me when I submitted my first ever PR to an OS project. We can incorporate features of other contribution guidelines into this, of course.

It might be a good idea (and very meta) to have a first time contributor submit a PR for this with the help of one of the more regular developers just so we can make sure the guidelines have the right perspective.

Thoughts?

cc/ @ellisonbg @fperez @willingc

**Comment by ellisonbg** [comment]
I think this is a great idea!

Because of the complexity of the multi-repo and multi-language universe we
live in now, I think it should go into the "Developer Documentation"
section of the main docs here:

http://jupyter.readthedocs.org/en/latest/index.html#developer-documentation

That section already has some initial information about how to contribute
to our docs.

I am fine with using some of the pandas guide, but the existing IPython
guide should also serve as a starting point. The other thing is that I
don't think we should cover basic git and github usage in the guide. It
should suffice to describe *how* we use git/GitHub (pull requests, rebasing
not merging) and then link to other content that gives the full details of
how to use git/Github. IOW, there are tons of resources on learning
git/Github on the internet - let's not repeat that. I find the pandas guide
way too verbose on that side of things.

We also probably want to divide our contribution guide in to backend
(mostly python), frontend (JS) and common information as they are quickly
becoming very different worlds.

But overall, yes!





On Tue, Nov 24, 2015 at 3:36 PM, Safia Abdalla <notifications@github.com>
wrote:

> During the November 24th developer meeting, there was a discussion around
> the friendliness and accessibility of our documentation, especially with
> regard to new contributors.
>
> I'd like to propose that we create a new Jupyter Contribution Guide that
> goes a step beyond the previous IPython Contribution Guide
> <https://github.com/ipython/ipython/blob/master/CONTRIBUTING.md> that we
> link to in all of the repositories and incorporates some of the great
> additions @jhamrick <https://github.com/jhamrick> made to the
> contribution guide.
>
> I selected pandas as a model for a contribution guide because their guide
> <https://github.com/pydata/pandas/blob/master/CONTRIBUTING.md> was
> immensely helpful to me when I submitted my first ever PR to an OS project.
> We can incorporate features of other contribution guidelines into this, of
> course.
>
> It might be a good idea (and very meta) to have a first time contributor
> submit a PR for this with the help of one of the more regular developers
> just so we can make sure the guidelines have the right perspective.
>
> Thoughts?
>
> cc/ @ellisonbg <https://github.com/ellisonbg> @fperez
> <https://github.com/fperez> @willingc <https://github.com/willingc>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/754>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
:+1:

**Comment by captainsafia** [comment]
> Because of the complexity of the multi-repo and multi-language universe we
live in now, I think it should go into the "Developer Documentation"
section of the main docs here:

> http://jupyter.readthedocs.org/en/latest/index.html#developer-documentation

> That section already has some initial information about how to contribute
to our docs.

I concur.

>  IOW, there are tons of resources on learning git/Github on the internet - let's not repeat that.

That makes sense. I think the best approach is to link to external resources for some parts of the guide just so we know that when people are setting up the project they are doing it in a certain way.

> We also probably want to divide our contribution guide in to backend (mostly python), frontend (JS) and common information as they are quickly becoming very different worlds.

Excellent point! I think I'll start off with the Python guide.

**Comment by ellisonbg** [comment]
Great!

On Tue, Nov 24, 2015 at 4:10 PM, Safia Abdalla <notifications@github.com>
wrote:

> Because of the complexity of the multi-repo and multi-language universe we
> live in now, I think it should go into the "Developer Documentation"
> section of the main docs here:
>
> http://jupyter.readthedocs.org/en/latest/index.html#developer-documentation
>
> That section already has some initial information about how to contribute
> to our docs.
>
> I concur.
>
> IOW, there are tons of resources on learning git/Github on the internet -
> let's not repeat that.
>
> That makes sense. I think the best approach is to link to external
> resources for some parts of the guide just so we know that when people are
> setting up the project they are doing it in a certain way.
>
> We also probably want to divide our contribution guide in to backend
> (mostly python), frontend (JS) and common information as they are quickly
> becoming very different worlds.
>
> Excellent point! I think I'll start off with the Python guide.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/754#issuecomment-159444803>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
@captainsafia A :bouquet: for helping others learn to :fishing_pole_and_fish: Keep up the :sunny: ideas.

**Comment by fperez** [comment]
Thanks so much, excellent! This goes right in line with this morning's discussion about barriers to entry that we need to lower. The mere act of writing these guides will show us where our on-ramp to contribution is more like a fence with barbed wire :(

Agreed that for more generic things about github workflows we can just link, but in general I think the pandas guide is an excellent starting point: it is comprehensive, and systematic.

As far as our docs, the beauty is that as usual, it's a mess :) Our real developer documentation isn't linked from the page that Brian mentioned above, that only talks about contributing to the docs. All our developer-oriented docs are still in the [old IPython docs](http://ipython.readthedocs.org/en/stable/development/index.html), and the information about contributing to the project itself is [in the wiki](https://github.com/ipython/ipython/wiki/Dev:-Index).

As a starting point, cleaning up that mess with a first pass of rationalizing the information would be already huge progress and would make things more welcoming to newcomers.

Pinging @minrk who's also been thinking about this...

**Comment by minrk** [comment]
+1, great idea.

**Comment by damianavila** [comment]
:+1: as well...
