### ISSUE TITLE
Hyperlinks are wrong if directly followed by punctuation

### ISSUE THREAD

**Issue by Zirunis** [jupyter/notebook#7541]
## Description

Jupyter Notebook seems to be doing some HTML sanitization, including detecting URLs and adding clickable hyperlinks. This is a great feature but it doesn't seem to be working entirely correctly.
I noticed that for this warning
_The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`_
the hyperlink falsely contains the end of sentence period, leading to an invalid link.
Interestingly, note that github extracts the correct hyperlink just fine.

## Reproduce

1. Print a valid hyperlink directly followed by punctuation
2. Click on the link
3. URL contains punctuation, site doesn't exist

## Expected behavior

If the last character is a period, it should be cut off. Other punctuation, like question marks, exclamation points, commas and semi-colons should probably also be cut off.

**Comment by andrii-i** [comment]
Hi @Zirunis, thank you creating this issue. I was not able to reproduce this in Notebook v7.3.1. When I paste text you used into a notebook markdown cell, URL is identified and rendered properly, without the trailing space (please see the screenshot below).  What version of the notebook are you using? Could you please try the same actions in Notebook v7.3.1? 

<img width="1245" alt="Image" src="https://github.com/user-attachments/assets/e8bac309-c4fe-4b61-86e2-4c01f8657892" />

**Comment by Zirunis** [comment]
Ah, should've updated first. I was on 6.5.7. Also can't reproduce on 7.3.1, works correctly for all punctuation I mentioned in the issue above.
Sorry for wasting your time.

**Comment by andrii-i** [comment]
No worries @Zirunis, glad that the problem is resolved.
