### ISSUE TITLE
Requirejs config and path names

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/notebook#767]
The requirejs path shortcuts for things like `jquery-ui` defined in `page.html` don't match the actual names of the packages. For example, `jqueryui` should be `jquery-ui` etc...

It could help transitioning to the nodejs world to use the actual package names instead.

See e.g. the shims by @jdfreder here: https://github.com/ipython/ipywidgets/blob/master/ipywidgets/static/widgets/js/requirejs-shim.js#L25

@minrk @jdfreder

**Comment by jdfreder** [comment]
Clarification:  They don't match the names of the npm packages.
