### ISSUE TITLE
Inconsistent Serialization of the Session Identifier

### ISSUE THREAD

**Issue by cstotzer** [jupyter/notebook#768]
Notebook (4.0.4) seems to serialise the session identifier (which, according to the doc, is a UUID) differently than the console (4.0.3). While the console sends a standard canonical UUID in the form 8-4-4-4-12 the notebook sends an all uppercase 32-byte string without hyphens. UUIDs should always be serialised the same way so they can be parsed and re-serialized in a predictable way. 

### Initial KERNEL_INFO_REQUEST from Notebook
    Header: {"session":"EDB01B4A6E6D4FD28C5AB266C5A7DF28","username":"cstotzer","msg_type":"kernel_info_request","msg_id":"3c939200-00a9-4127-b53f-2dd23c9e158c","version":"5.0","date":"2015-11-27T17:55:26.896956"}
    ParentHeader: {}
    Metadata: {}
    Content: {}
    Verification Signature: b9d81e798f694216322993e404db75f2504cc6e175f08dbb577e0e08c9ece83e

### Initial KERNEL_INFO_REQUEST from Console
    Header: {"session":"1c5a38a7-84ab-46c4-b2f2-df9c19400694","username":"cstotzer","msg_type":"kernel_info_request","msg_id":"637406cd-4f71-4d1b-aafa-65108a79785a","version":"5.0","date":"2015-11-27T17:58:50.534067"}
    ParentHeader: {}
    Metadata: {}
    Content: {}
    Verification Signature: f6afb2af8c32c4c505cfdc598bcb6004115f0ccd804b80eec79049ff6bbdb4fc

**Comment by minrk** [comment]
The session id can be any sufficiently unique string, it is not defined as a UUID per se. `"session" : "cabbages"` would be equally valid.

**Comment by cstotzer** [comment]
Got it - note that in this case the documentation is misleading and incomplete as the description of the [message format](http://jupyter-client.readthedocs.org/en/latest/messaging.html#general-message-format) leads to believe that the session identifier is in fact a UUID.

**Comment by minrk** [comment]
Should be clarified by jupyter/jupyter_client#97

**Comment by cstotzer** [comment]
Perfect, thanks a lot!
