### ISSUE TITLE
Support animation as an extension to the interact function?

### ISSUE THREAD

**Issue by mikecroucher** [jupyter/notebook#79]
We currently have `interact` that allows us to do this

    import numpy as np
    import matplotlib.pyplot as plt

    x = np.linspace(-2*np.pi,2*np.pi,100) 
    def plotsin(f=2):
        plt.plot(x,sin(x*f))
    interact(plotsin,f=(2,10,0.1));

very nice it is too! Could we extend this function so that it worked as an animator?
For example, perhaps if I were to write 

    interact(plotsin,f=(2,10,0.1),auto=True);

it would behave exactly like the interactive version but automatically step through the values of f. Perhaps there could be a 'stop' button for when we are tired of the animation. Maybe we could go a step further and do

    interact(plotsin,f=(2,10,0.1),auto=True,show_controls=False);

Which would remove the slider and just show the results of the animation.

**Comment by rgbkrk** [comment]
This now belongs in https://github.com/ipython/ipywidgets (sorry about all the movement).

It might be nice if there was just another command, say `animate` that wrapped `interact` with configurable delay, a way to pause, and whether the controls would be shown.

**Comment by Carreau** [comment]
Nah, dont' need too, just a while loop in next cell that change the value
of the widgets since it's linked.

**Comment by mikecroucher** [comment]
Thanks, both. I'll have a play and maybe open an issue in ipywidgets if appropriate.
Cheers,
Mike

**Comment by sebnil** [comment]
@mikecroucher , did you find a solution to this?
