### ISSUE TITLE
Paste cell and replace broken

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#792]
from menu, if I select 3 cells (markdown; respective test: 1,2,3) it pasts 3 empty code cells.

**Comment by ellisonbg** [comment]
Good catch

**Comment by Carreau** [comment]
Gah, my fix is wrong, we should probably replace the **selection** if one click on replace. Not only the head.

**Comment by jdfreder** [comment]
> Gah, my fix is wrong, we should probably replace the selection if one click on replace. Not only the head.

Does that mean you intend to close #799?
