### ISSUE TITLE
Move cell up and down inconsistant.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#793]
do not work with multiple selection (we can decide that how it works though), 
but imho it should move blocks. 

Or implementation side, move the cell before the block after the block when move up,  and vice versa. (Though it might unbind callbacks)

**Comment by ellisonbg** [comment]
@takluyver mentioned the possibility of even removing move cell up and
down. I think that is a good idea (not for 4.x though). But does this
change our thinking about fixing this issue? But if we do fix, I think it
should move blocks.

On Tue, Dec 8, 2015 at 6:47 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> do not work with multiple selection (we can decide that how it works
> though),
> but imho it should move blocks.
>
> Or implmentation wise, move the cell before the block after the block when
> move up, and vice versa. (Though it might unbind callbacks)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/793>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
@takluyver ask to remove the **UI** the action can still be manually bound to a shortcut, so it still need fixing.

**Comment by takluyver** [comment]
I don't think it would be unreasonable to remove/deprecate the action itself. I really don't think that move up/down makes sense when you can select multiple cells, and especially if you can select non-contiguous cells.

**Comment by Carreau** [comment]
> and especially if you can select non-contiguous cells.

you can't anymore.

**Comment by takluyver** [comment]
Ah, OK. I thought from skimming through the long conversation about it that that was why we had implemented the multi-cell selection all over again.

**Comment by Carreau** [comment]
You can select multiple-contiguous. For a few weeks we had non-contiguous, it was removed after much yak-shedding, (or bike-shaving).

**Comment by takluyver** [comment]
Am now picturing a bike with yak hair. Good job.

**Comment by Carreau** [comment]
As long as it's not a pink-haired-colored yak...

**Comment by ellisonbg** [comment]
Would you think of removing the toolbar buttons in 4.1?

On Tue, Dec 8, 2015 at 12:00 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> As long as it's not a pink-haired-colored yak...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/793#issuecomment-162997787>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> Would you think of removing the toolbar buttons in 4.1?

No. I've see too many people use them with single cell. 
Removing the button mean teaching people about multiple selection and copy/past semantic, which are not obvious in notebook.

**Comment by ellisonbg** [comment]
k

On Tue, Dec 8, 2015 at 11:26 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Would you think of removing the toolbar buttons in 4.1?
>
> No. I've see too many people use them with single cell.
> Removing the button mean teaching people about multiple selection and
> copy/past semantic, which are not obvious in notebook.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/793#issuecomment-163139693>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by parente** [comment]
So that I know and can inform others when they ask: what's the modern replacement?

**Comment by Carreau** [comment]
> So that I know and can inform others when they ask: what's the modern replacement?

I think Brian and Thomas want to replace that with Copy-Past. 



> Edit: I too know a whole bunch of folks who use the toolbar buttons.

I'm worry too that removing "move up-down" will piss off many people. We already got a lot of complaint when we removed the Ctrl-j/k bindings.

**Comment by jdfreder** [comment]
I've deprecated the action in #815 , I'll bump the milestone for the issue now.

**Comment by Carreau** [comment]
> I've deprecated the action in #815 , I'll bump the milestone for the issue now.

Bumping down to 4.1 again, as it is (still) broken with multiple selection.
Deprecation does not forbid us from fixing the behavior.
