### ISSUE TITLE
Insert cell above/below and multiple selection.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#794]
Should insert after/before the full selection, likely not the selection-head.

**Comment by ellisonbg** [comment]
Yep.

Should the selection be reset after insertion?

On Tue, Dec 8, 2015 at 6:50 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Should insert after/before the full selection, likely not the
> selection-head.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/794>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> Should the selection be reset after insertion?

reset ? You mean select back the selected cells (A)  ? Of focus the new one (B)?

(B) is what all commands should do IMHO
