### ISSUE TITLE
Run and select below + Multiselect

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#795]
Does not select after the selection, select the last cell of selection.

**Comment by ellisonbg** [comment]
I sort of think that all of the run commands should just be inplace if
there are multiple cells seleted. The select below and insert below parts
don't really make sense with mulitple cells selected. Thoughts?

On Tue, Dec 8, 2015 at 6:52 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Does not select after the selection, select the last cell of selection.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/795>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> Thoughts?

It's call run and select below, so it should run and select below. 
We can have another action name that does something else and make it the default. Then I'm fine. 

Thou I can see myself selecting 2-3 cells up, and pressing shift enter. 
I would expect  the nth+1 cell to be selected.
