### ISSUE TITLE
Run and insert below

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#796]
Does not insert on multi-selection.

**Comment by ellisonbg** [comment]
From my other comment:

I sort of think that all of the run commands should just be inplace if
there are multiple cells seleted. The select below and insert below parts
don't really make sense with mulitple cells selected. Thoughts?

On Tue, Dec 8, 2015 at 6:52 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Does not insert on multi-selection.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/796>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Same comment, if the action is name "and insert below" it should insert below. 

Though I still think that Alt-enter to run-selected insert below selection make sens.
