### ISSUE TITLE
Multi-selection and menu.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#797]
Menu commands that act on many cells should be plural. 

(once the underlying commands are working on many cells)

**Comment by ellisonbg** [comment]
Yes, they should say cells, but I think it should be `cells` not `cell(s)`

On Tue, Dec 8, 2015 at 6:53 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Menu commands that act on many cells should be plural.
>
> (once the underlying commands are working on many cells)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/797>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by captainsafia** [comment]
I'll give this a stab.

**Comment by captainsafia** [comment]
@captainsafia so I can find this later.
