### ISSUE TITLE
Executing code on a server

### ISSUE THREAD

**Issue by sho-87** [jupyter/notebook#810]
I just set up jupyter notebook on my homeserver with a reverse proxy so I can access everything remotely.

I typically train machine learning models which can take a while, so my ideal situation is that I can work remotely through the browser, hit the execute button which will run the code on the server. This is all fine and working.

But currently if I close my remote browser (turn off my laptop, close the web browser etc.) the code is presumably still running on the server, but when I visit the notebook site again I'm not able to see the output generated from the training session. This is probably because the output didn't save as I closed the browser/laptop before any output was generated.

If I'm correct in understanding that this is the way things are meant to be, are there any alternative solutions so I can execute code on server, close my remote computer, come back to it hours later and still see the progress thats been made?

**Comment by Carreau** [comment]
> If I'm correct in understanding that this is the way things are meant to be, are there any alternative solutions so I can execute code on server, close my remote computer, come back to it hours later and still see the progress thats been made?

We are aware of the limitation, what we suggest for now is to save the value and display only once you are connected.  It's often not hard to refactor code to do that. 

We are working on rewiring the infrastructure to allow this kind of reconnection, but it's far from easy. 

As it's tracked in many other places, I'm going to close the issues, but feel free to keep asking quesions.

**Comment by rladeira** [comment]
Any progress about this issue?
