### ISSUE TITLE
How to add a java class path in jupyter 

### ISSUE THREAD

**Issue by liushiqi9** [jupyter/notebook#82]
Since it didn't provide a page for us to add it.(using calico kernel run java)

**Comment by takluyver** [comment]
@dsblank can you help with this?

**Comment by dsblank** [comment]
Indeed, Calico comes with a Java interpreter. However, this is not just a regular system, and might not be what you want (a generic, standard Java system). This Java interpreter is written in Java, but run by .NET/Mono, to integrate with the rest of Calico.

You will need to install Calico for Mac, Windows, or Linux here:
http://calicoproject.org/Calico_Download

Then, you need to make a kernelspec for Java:
`./calico --create-kernelspec --display-name="Calico Java" --nographics --lang=java --only`

That will make the calico_java kernelspec. You can then use it from console/qtconsole, or the notebook:

```
$ ipython console --kernel calico_java
Loading Calico version 4.0.0...
IPython Console 3.1.0
In [1]: x = 1;
In [2]: System.out.println(x);
1
```
It uses a special form of Java called DynamicJava... types are optional, but you can't change the type once set.

I do plan on making a more standard Java kernel at some point. Also, you might be interested in Calysto Processing, that converts Java to Javascript.

Followup questions and comments to: https://bitbucket.org/ipre/calico/

Thanks!

**Comment by liushiqi9** [comment]
Sorry, I think I didn't explain well about what I mean.
We already add calico into jupyter and we can load the kernel in the notebook web. We can run java program now, Our question is we don't know how to add a java class path to import our .jar files.
Thank you!

**Comment by rgbkrk** [comment]
This highlights a bigger issue to me, which is of setting environment variables. Are kernels launched with the same `env` as the notebook server?

**Comment by takluyver** [comment]
The kernelspec can specify extra environment variables for kernels - these are added to a copy of the notebook server environment variables. If you want to do more complex things (like adding directories to `$PATH`) the kernelspec can point to a script which modifies its environment variables and then starts the actual kernel.

**Comment by dsblank** [comment]
@liushiqi9 Let's take these questions out of jupyter issue tracker, as this is a specific kernel question. (Briefly, this isn't regular Java, it doesn't sound like you want to integrate with .NET, so this isn't probably what you want. Wait for a real Java kernel.)

**Comment by rjpg** [comment]
How to add a java class path in jupyter ?
