### ISSUE TITLE
Find and replace in selected cell apply on all cells.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#831]
Marking as 4.1

**Comment by captainsafia** [comment]
Hm. I can take a look at this later today.

**Comment by Carreau** [comment]
@parleur might have a look too. Just coordinate with each other.

**Comment by captainsafia** [comment]
Sure! @parleur, let me know if you get a chance to start working on it before I do and I can help out on any pull request that you have. I will bing you on this issue when I start looking into it.

**Comment by parleur** [comment]
Starting now.

**Comment by parleur** [comment]
Just to be clear the purpose here is to restraint s&r only on selected cells.

**Comment by captainsafia** [comment]
Yes!

I believe @Carreau opened this as part of the work we are doing to polish up multiselect.

**Comment by jonathan-alvaro** [comment]
I think that this problem is happening again. I'm using jupyter 4.4.0. As this is my first time reporting an issue like this, please feel free to contact me should you need any further information.
