### ISSUE TITLE
Write test for "Find and replace in selected cell apply on all cells"

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#838]
Cf #831 and #836

**Comment by captainsafia** [comment]
OK. I'm on this.

**Comment by captainsafia** [comment]
This is marked 4.2 so no urgency on this question I guess. But I am having trouble figuring out how to write good tests for this without having to refactor the code.

I was originally thinking that I could just test `get_cells` but it isn't exposed via the export so I'm a bit unsure of what to do.

**Comment by abiduzz420** [comment]
What is the status of this issue ? Is anyone working on it

**Comment by jasongrout** [comment]
I don't know of anyone working on it. @gnestor, do you know anyone working on it?

**Comment by gnestor** [comment]
Nope, @abiduzz420 would you like to take a shot at it?

**Comment by akshaysuresh4793** [comment]
Hey Is this issue fixed? I would like to work on it

**Comment by gnestor** [comment]
@akshaysuresh4793 Not yet. Please go right ahead 👍

**Comment by takluyver** [comment]
N.B. new frontend tests are now using Selenium, and we're gradually getting rid of the PhantomJS tests. See: https://github.com/jupyter/notebook/tree/master/notebook/tests/selenium

**Comment by arovit** [comment]
Hi, I have created PR https://github.com/jupyter/notebook/pull/3630 for this. Thanks.

**Comment by eseiver** [comment]
PR #3630 was merged and this can be closed.
