### ISSUE TITLE
Focus during mutli-cell selection

### ISSUE THREAD

**Issue by akhmerov** [jupyter/notebook#846]
Short description: selecting multiple cells can result in the active cell being off screen.

My environment:  
* Ubuntu + latest chrome/firefox
* Notebook v4.1.0b1

Reproducing:  
* Open a notebook with more cells than fits into a single screen
* Press shift+J (shift-K) several times

Result:  
Active cell is off screen

Expected behavior:  
Active cell is the lowest visible cell (highest visible cell for shift-K), same as with regular J/K.

**Comment by ellisonbg** [comment]
I haven't tested locally, but I agree that the focus behavior or shift-J/K
should behave the same as J/K.

On Fri, Dec 11, 2015 at 7:20 PM, Anton Akhmerov <notifications@github.com>
wrote:

> Short description: selecting multiple cells can result in the active cell
> being off screen.
>
> My environment:
>
>    - Ubuntu + latest chrome/firefox
>    - Notebook v4.1.0b1
>
> Reproducing:
>
>    - Open a notebook with more cells than fits into a single screen
>    - Press shift+J (shift-K) several times
>
> Result:
>
> Active cell is off screen
>
> Expected behavior:
>
> Active cell is the lowest visible cell (highest visible cell for shift-K),
> same as with regular J/K.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/846>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
I think I had a workaround, but it completly break the focus behavior. 
It's not obvious why J/K keep focus on not with shift.

**Comment by Carreau** [comment]
I think I got it, it's a 3 line change, but it's not super obvious.

**Comment by Carreau** [comment]
See #863
