### ISSUE TITLE
javascript exception

### ISSUE THREAD

**Issue by JanSchulz** [jupyter/notebook#851]
When I use the code inspector in chrome, I see the following exception in the js console:

```
Uncaught SyntaxError: Unexpected token &
```

This seems to come from:

```
<script type="text/javascript">
    sys_info = {&#34;os_name&#34;: &#34;nt&#34;, &#34;sys_version&#34;: &#34;3.4.3 |Continuum Analytics, Inc.| (default, Nov  7 2015, 13:21:48) [MSC v.1600 64 bit (AMD64)]&#34;, &#34;sys_platform&#34;: &#34;win32&#34;, &#34;notebook_version&#34;: &#34;4.0.5&#34;, &#34;platform&#34;: &#34;Windows-7-6.1.7601-SP1&#34;, &#34;commit_hash&#34;: &#34;&#34;, &#34;commit_source&#34;: &#34;&#34;, &#34;default_encoding&#34;: &#34;cp850&#34;, &#34;sys_executable&#34;: &#34;C:\\portabel\\miniconda\\envs\\ipython-notebook\\python.exe&#34;, &#34;notebook_path&#34;: &#34;C:\\portabel\\miniconda\\envs\\ipython-notebook\\lib\\site-packages\\notebook&#34;};
</script>
```

**Comment by Carreau** [comment]
Is that on notebook 4.1.0b1 ? Can you check if it's only windows specific ? And if so can you try to narrow it down ?

The value is explicitly [marked as safe](https://github.com/jupyter/notebook/blob/caa23d0d8ba77e01e4025aca31551923b9d62e7e/notebook/templates/notebook.html#L341-L343) so if quotes are escaped, it means that Jinja2 does not do it's job. 

Is that a custom embed application, or is it ran in a specific context ?

**Comment by JanSchulz** [comment]
As that `|safe` [was just committed in September](https://github.com/jupyter/notebook/commit/bce9c94f32d2257f14895dc0fb3137faaeedb46e) and wasn't present in my versions and went away as I applied the same fix to my template, I consider this fixed. Sorry for not testing it on the latest beta...
