### ISSUE TITLE
User Interface Tour Tweak

### ISSUE THREAD

**Issue by damontallen** [jupyter/notebook#852]
This is a small problem, but during the User Interface Tour the Interrupting the Kernel slide doesn't highlight anything.

**Comment by willingc** [comment]
@damontallen Hmm... Below are the results that I am getting using the latest version of Firefox on a Mac. Perhaps the issue that you are seeing is related to a particular browser or configuration? If you let us know which browser and OS that you are using, we would be happy to look into it. Thanks.

![interupting_kernel](https://cloud.githubusercontent.com/assets/2680980/11770341/8b718ecc-a1b0-11e5-85bd-d545ede5750c.gif)
<img width="611" alt="screen shot 2015-12-13 at 3 44 47 pm" src="https://cloud.githubusercontent.com/assets/2680980/11770342/91e7e8fa-a1b0-11e5-9966-a2871b903432.png">

**Comment by damontallen** [comment]
I was using Ubuntu 15.10 (64bit) and Firefox.  

I just double checked and it's working now.  I guess I just needed to reboot.

**Comment by willingc** [comment]
@damontallen Glad it's working. Enjoy Jupyter notebook :sunglasses:
