### ISSUE TITLE
Log on disk path of files served when using --debug

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#857]
cf https://github.com/jupyter/notebook/pull/708#issuecomment-164293699, 

That would be useful to debug some issues.

**Comment by Carreau** [comment]
Annoying for 4.1 since the easy  place where we can know the the requested path, and the file abspath is a class method on which we cannot access `self.log`

**Comment by CJSchell** [comment]
Hey guys wondering if this is still a priority and if I can help?

**Comment by takluyver** [comment]
@Carreau do you remember if you were thinking of files served as static files, or files loaded through the contents manager?

**Comment by Rishabh0712** [comment]
Hi guys, I am a beginner and would like to contribute to it. Can you provide some info ??

**Comment by SeymourPashayev** [comment]
Is this still open up for grabs?

**Comment by kevin-bates** [comment]
Sure @SeymourPashayev - anything that improves supportability is always welcome.  Thank you for your interest.

**Comment by vaibhavarora102** [comment]
Hi, @Carreau  @SeymourPashayev  is this issue still open?
if So, I would like to contribute to this issue, and can you please guide a bit if we need to locate the file address while debugging
and if possible the can you please provide the main file address upon which changes are to be made
thanks

**Comment by Carreau** [comment]
I believe you will need too look at the following files in the jupyter_server repo: 

https://github.com/jupyter-server/jupyter_server/blob/49d57729e8b22147b23047e24900371e610c190e/jupyter_server/files/handlers.py#L41

It should lead you to this method:

https://github.com/jupyter-server/jupyter_server/blob/49d57729e8b22147b23047e24900371e610c190e/jupyter_server/services/contents/filemanager.py#L376

And in there you will likely find mentions to `_get_os_path` in helper function and methods.

Around those lines, you want to try adding things like `self.log.debug('Reading path from disk:', path)` or similar to try to log which files we are actually trying to read.

**Comment by goyaldhara** [comment]
Hi, @Carreau  Can I take this issue ?

**Comment by Carreau** [comment]
You do not need to ask usually, just saying that you are looking into it is
enough, in order to make sure there is no duplicate work. And feel free to
post informations like " I think that this likely need to be fixed in this
file", etc, so that we are aware you are making progress.

**Comment by jayeshsingh9767** [comment]
@Carreau I have created the PR for this, could u please check. Also **Enforce PR label** is failing and I am not able to add label after PR creation, could someone please add label as Maintenance in this [PR](https://github.com/jupyter-server/jupyter_server/pull/1336) else I need to recreate another PR.

**Comment by jayeshsingh9767** [comment]
@blink1073 can we close this issue?

**Comment by blink1073** [comment]
Yes, thanks again!
