### ISSUE TITLE
Add a "What's New in 4.1" sidebar box to docs

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#859]
Any interest in having the key new functionality highlighted in a sidebar box in the docs? We could put links to the changelog or blog post introducting 4.1 too.

<img width="1186" alt="screen shot 2015-12-13 at 2 42 59 pm" src="https://cloud.githubusercontent.com/assets/2680980/11769956/0b5d6718-a1a8-11e5-8754-c393d5085506.png">

cc/ @ellisonbg @fperez

**Comment by fperez** [comment]
+1, excellent idea!

On Sun, Dec 13, 2015 at 2:46 PM, Carol Willing <notifications@github.com>
wrote:

> Any interest in having the key new functionality highlighted in a sidebar
> box in the docs? We could put links to the changelog or blog post
> introducting 4.1 too.
>
> [image: screen shot 2015-12-13 at 2 42 59 pm]
> <https://cloud.githubusercontent.com/assets/2680980/11769956/0b5d6718-a1a8-11e5-8754-c393d5085506.png>
>
> cc/ @ellisonbg <https://github.com/ellisonbg> @fperez
> <https://github.com/fperez>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/859>.
>



-- 
Fernando Perez (@fperez_org; http://fperez.org)
fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
fernando.perez-at-berkeley: contact me here for any direct mail

**Comment by Carreau** [comment]
I don't know how much this is possible. But if you know how to do it (or a project that does it,) we can do that.

We can Also inject a header on top of all pages, with a `4.1 beta` message.

**Comment by willingc** [comment]
The sidebar box is just a sphinx directive so adding the box is straightforward. I'll open a PR later for comments.
