### ISSUE TITLE
Some problems with the ConfigManager

### ISSUE THREAD

**Issue by damianavila** [jupyter/notebook#880]
Context: I have written a custom config manager but it is not working... looking for the issue, I just tried to setup the env path directly in the current ConfigManager with no luck:

If I change https://github.com/jupyter/notebook/blob/master/notebook/services/config/manager.py#L17
from
`return os.path.join(jupyter_config_dir(), 'nbconfig')`
to
`return os.path.join(ENV_CONFIG_PATH[0], 'nbconfig')`

and I still can not load the nbconfig from that conda env... ideas???

Even more, if I try the option the option
`--ConfigManager.config_dir=path/to/env/etc/jupyter/nbconfig` when I launch the notebook, it keeps loading nbconfig from the `./jupyter` user space...

What other `jupyter_config_dir`-related things am I missing? Or it could be some problem upstream this? maybe `traitlets`?

pinging @takluyver @minrk who are probably interested, also @jdfreder who chat a little bit with me about this, although everyone else in invited :wink:

**Comment by ellisonbg** [comment]
With my proposal in #878 can you get by without a custom ConfigManager?

But the changes you are making should work fine.

**Comment by damianavila** [comment]
yes @ellisonbg, I will comment in the issue soon...
This is just me playing with alternatives and I think I found and issue/bug because it is not working if I make the changes I suggested above... but I can not figure out why not yet :wink:

**Comment by minrk** [comment]
The notebook app [specifies](https://github.com/jupyter/notebook/blob/4.0.6/notebook/notebookapp.py#L820) that frontend config is always in the Juptyer config dir, so it's not really true that ConfigManager.config_dir is configurable, since it's not allowed to be set from config.

**Comment by damianavila** [comment]
OK, so removing that line will fallback in the default at ConfigManager, making that config option to work... sound like a reasonable request for a PR, so here it is: #882 :wink:
