### ISSUE TITLE
built-in words are used as variable and argument names 

### ISSUE THREAD

**Issue by jennolsen84** [jupyter/notebook#888]
For example, in https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L320

both `type` and `format` are remapped as argument names

builtins:
```
In [1]: format(5) # formats to str
Out[1]: '5'

In [1]: type(5) # returns type of the object
Out[1]: int
```

**Comment by takluyver** [comment]
While this is not recommended, it doesn't actually break anything. Since the example you point to is part of the public API, it's probably not worth changing. We should try to avoid overloading these names in new code, though.

**Comment by minrk** [comment]
Yup, it's no problem for these to be used as arguments in a method.
