### ISSUE TITLE
JS api breakage ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#891]
cf https://github.com/jupyter-incubator/dashboards, investigate.

**Comment by Carreau** [comment]
The action/prefix separator changed from `.` to `:`. 

We should try to detect/warn is someone try to append an action where the separator is `.`.

**Comment by ellisonbg** [comment]
Our JS API is not stable and can change in arbitrary ways between minor releases. I don't see how that is a bug...

**Comment by Carreau** [comment]
It's not because it's unstable, that we shouldn't raise correct error messages, or prevent the notebook from crashing if a bad API is used. 

In the end, if an extension use unstable API and user get broken notebook on update, that will open issues on our repos, and we will have to respond, and spend time explaining to user. 

Also even if we say it **is** unstable, we are doing efforts to not break too much. 

I've bumped to 4.2, but nice and correct error message, even in the js console, would be nice for 4.1.

**Comment by ellisonbg** [comment]
Got it, thanks for the clarification...

On Tue, Dec 22, 2015 at 10:31 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> It's not because it's unstable, that we shouldn't raise correct error
> messages, or prevent the notebook from crashing if a bad API is used.
>
> In the end, if an extension use unstable API and user get broken notebook
> on update, that will open issues on our repos, and we will have to respond,
> and spend time explaining to user.
>
> Also even if we say it *is* unstable, we are doing efforts to not break
> too much.
>
> I've bumped to 4.2, but nice and correct error message, even in the js
> console, would be nice for 4.1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/891#issuecomment-166697742>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
