### ISSUE TITLE
Attempts to rerun the notebook fail: ImportError

### ISSUE THREAD

**Issue by yurivict** [jupyter/notebook#895]
On FreeBSD I am getting this error after any attempt to restart:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-8d1abd5f35c0> in <module>()
----> 1 import pymc as pm
      2 
      3 
      4 parameter = pm.Exponential("poisson_param", 1)
      5 data_generator = pm.Poisson("data_generator", parameter)

ImportError: No module named pymc
```
I followed the instructions to install the notebook.

Tried with this document: https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers

**Comment by Carreau** [comment]
That's likely an issue to see with the author of this book, it has nothing to do with the notebook application itself. 

The notebook is just an editing environment, it does not deal with installing software or library. This is up to your package manager. 

You likely need to install [pymc](https://pypi.python.org/pypi/pymc), either through `pip`, `conda`, (or `pkg` IIRC the name of FreeBSD package manager) depending on your preference. 

I'm closing the issue, but feel free to continue asking questions.

**Comment by takluyver** [comment]
To expand a bit: it sounds like you have the notebook installed OK, but the code inside notebooks can use all kinds of packages which you need to install separately. You're using a notebook that requires the package PyMC, so you'll need to install that.

We often recommend that people install [Anaconda](https://www.continuum.io/downloads), a bundle which includes the notebook along with a lot of popular scientific Python packages. I forget whether PyMC is one that it installs by default, though.

**Comment by yurivict** [comment]
For example, I am getting this error:
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-8d1abd5f35c0> in <module>()
----> 1 import pymc as pm
      2 
      3 
      4 parameter = pm.Exponential("poisson_param", 1)
      5 data_generator = pm.Poisson("data_generator", parameter)

ImportError: No module named pymc
```

I do have pymc installed: py27-pymc-2.3.6,1
And this program succeeds when run standalone.

**Comment by willingc** [comment]
@yurivict pymc has dependencies on numpy and scipy so do check as Thomas suggests to have them installed.
Here are two gists with bash scripts that you may find helpful in troubleshooting:
[checkmypython.sh](https://gist.github.com/willingc/9ff70a642b54023cc8d4)
[checkmypackages.sh](https://gist.github.com/willingc/9dd6efb251399e84468f)

**Comment by yurivict** [comment]
numpy and scipy are both installed, because they are dependencies of pymc, but there is still a problem. I don't use pip.

On the other hand, on FreeBSD ipython hasn't been used and updated for a while, and jupyter is a new port that I just made, so there is something wrong in between there.

**Comment by Carreau** [comment]
You are likely running the notebook kernel from one installation of Python and installed PyMC, numpy ans scipy in another. 

The best way to see which python is used in the notebook is to use n a cell:
```
import sys
print(sys.executable)
```
and compare that to the python you installed PyMC for. If you don't use pip i'm not sure how to test which python you install these pacakges for.
