### ISSUE TITLE
traceback turns into a hyperlink when a URL is in the code comments

### ISSUE THREAD

**Issue by goretkin** [jupyter/notebook#904]
I'm using Jupyter Notebook 4.0.6

Here is the notebook http://nbviewer.ipython.org/urls/gist.githubusercontent.com/goretkin/7ea77986a3137ed53762/raw/3c82c90889ec3cab051f0d398db92cd34e327a38/reveal-bug.ipynb

however it doesn't show the behavior in the notebook viewer.

Here's what it looks like in Firefox

<img width="889" alt="screenshot 2015-12-28 23 53 18" src="https://cloud.githubusercontent.com/assets/581043/12029669/644d1dce-adbe-11e5-9b2c-630526cba98c.png">

I'm hovering over the underlined section of the traceback.

**Comment by willingc** [comment]
@goretkin Thanks for the issue report.

@carreau I've replicated the issue on FF with current release candidate. It looks like the conversion of the traceback text is not properly closing tags when the source of the cell includes a comment with a link.

### Conversion of link in comment of Traceback message is not properly closing the tag

<img width="1209" alt="screen shot 2015-12-28 at 9 44 42 pm" src="https://cloud.githubusercontent.com/assets/2680980/12030032/ac4f2020-adac-11e5-9f0c-ee8c653138ec.png">

### Traceback display works as expected when the source has no link in comment
<img width="1210" alt="screen shot 2015-12-28 at 9 46 12 pm" src="https://cloud.githubusercontent.com/assets/2680980/12030033/b069e708-adac-11e5-8dcb-81332db8ae80.png">

#### Test environment: latest release candidate, Python 3.5, and Firefox
<img width="693" alt="screen shot 2015-12-28 at 9 47 18 pm" src="https://cloud.githubusercontent.com/assets/2680980/12030040/d418160c-adac-11e5-8333-6b1dca01330f.png">
