### ISSUE TITLE
Add a user interface visual to docs which labels UI items

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#906]
A nice documentation enhancement in the notebook documentation would be to add a "what's it called" visual for the User interface items. Reference https://github.com/jupyter/enhancement-proposals/issues/9#issuecomment-167805546

**Comment by willingc** [comment]
@captainsafia Any time or interest in adding this to the notebook docs?

**Comment by captainsafia** [comment]
I can look at it this afternoon!

**Comment by willingc** [comment]
Cool. No rush. Nice to know you know graphics :happy: :dancers:

I think there may be some good info in the tour of the notebook that is in the Help when running the notebook.

**Comment by captainsafia** [comment]
![1bbfws1](https://cloud.githubusercontent.com/assets/1857993/12039349/4e554de0-ae25-11e5-92bb-0855ff66aaac.gif)

And noted.

**Comment by willingc** [comment]
Nice GIF. Made me laugh.
