### ISSUE TITLE
Terminal broken on master of notebook and terminado

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#912]
When just did a clean install from master of notebook and terminado and the terminal is broken. I see the following traceback in the log file:

```python
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 417, in _run_callback
        callback(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/notebook/base/zmqhandlers.py", line 179, in open
        return super(WebSocketMixin, self).open(*args, **kwargs)
      File "/tmp/src/terminado/terminado/websocket.py", line 90, in open
        if not self.check_origin():
    TypeError: check_origin() missing 1 required positional argument: 'origin'
```

**Comment by ellisonbg** [comment]
I am not sure what the fix is, but I see roughly where the problem is:

* In `tornado>=4` there is a `WebSocketHandler.check_origin(self, origin)` method that checks the origin of web sockets. It has a required positional argument.
* In jupyter/notebook, we have a subclass that we use in our handlers `ZMQStreamHandler(WebSocketMixin, WebSocketHandler)` which also has the `check_origin` method with the required positional.
* In terminado there is `TermSocket(tornado.websocket.WebSocketHandler)` which has a `check_origin` method with an *optional* `keyword argument`.
* In `TermSocket.open` `self.check_origin()` is called with no arguments.
* At first glance this looks like it should work fine because it will be calling terminado's subclasses `check_origin`.
* *But*, the code which calls open in juipyter/notebook does so by doing `super(WebSocketMixin, self).open(*args, **kwargs)`.
* Somehow, that is causing the base tornado `check_origin` to be called, but with *no arguments*, which results in an exception.

The part that I am still confused about is that `WebSocketMixin` doesn't have the base tornado `WebSocketHandler` in its mro, so I don't see how it is resolving to that.

Questions:

* All of this logic in terminado is to handle tornado<4. But tornado 3 is really old now and jupyter/notebook now requires tornado>=4. Can we just remove all this logic from terminado?
* Is there something more subtle going on with the inheritance here that needs to be fixed?
* The tornado `check_origin` method has never had a different signature. Buy terminado subclassing and changing the signature, this was bound to happen at some point. If we keep the logic in terminado,  can we address this API difference?

@minrk @takluyver

**Comment by ellisonbg** [comment]
Also, I think we should release a new version of terminado along with 4.1 of the notebook. There were other things fixed in terminado recently that all users should be using.

**Comment by fperez** [comment]
I'm curious, I'm not seeing this problem on my side... Wondering why, is it a difference in terminado versions? I'm running master of the notebook, terminado 0.5, tornado 4.3.

**Comment by ellisonbg** [comment]
I think it was these changes to terminado in October that are related to it:

https://github.com/takluyver/terminado/commit/2e362b084963d8f102ccd99a1f8e3f1ecbda274f

I am running from master as there are some other recent changes that fix
another bug in terminado.

Can you install terminado from master and see if you can reproduce?

On Wed, Dec 30, 2015 at 6:22 PM, Fernando Perez <notifications@github.com>
wrote:

> I'm curious, I'm not seeing this problem on my side... Wondering why, is
> it a difference in terminado versions? I'm running master of the notebook,
> terminado 0.5, tornado 4.3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/912#issuecomment-168111305>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by fperez** [comment]
Yup, just installed terminado master, and I now see the same exact traceback you're reporting.

So at least I can confirm the problem...

**Comment by fperez** [comment]
The symptom is then that the terminal never initializes, so it's pretty much hosed.

**Comment by fperez** [comment]
BTW @takluyver, would be good to bump the `__version__` string in terminado post-release to something like `0.6dev` or somesuch, master still reports `0.5`, so it's a bit confusing by simply checking version strings I had to carefully check that I was really importing from a dev path.

**Comment by minrk** [comment]
#914 fixes it. It's a combination of changes in terminado and notebook that triggered this - terminado adopting tornado 4 conventions, and a change in the notebook assuming the origin arg is always passed. We usually allow check_origin to be called with no arg, so I restored that in #914.

**Comment by ellisonbg** [comment]
@minrk thanks for the fix. Other questions:

* The comments in the code suggest we shouldn't need our own custom
check_origin after we ditch tornado<4 (which we have). Can we just get rid
of all that in both jupyter/notebook and terminado?
* Should we cut a release of terminado with 4.1?

On Thu, Dec 31, 2015 at 1:45 AM, Min RK <notifications@github.com> wrote:

> #914 <https://github.com/jupyter/notebook/pull/914> fixes it. It's a
> combination of changes in terminado and notebook that triggered this -
> terminado adopting tornado 4 conventions, and a change in the notebook
> assuming the origin arg is always passed. We usually allow check_origin to
> be called with no arg, so I restored that in #914
> <https://github.com/jupyter/notebook/pull/914>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/912#issuecomment-168159109>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
Terminado technically hasn't dropped support for tornado 3, which is one source of the issue. I opened takluyver/terminado#25 to fix the issue, and takluyver/terminado#26 if we want to drop support for tornado < 4.

We don't need to push a release of terminado with 4.1, but we can do one soon after. There are no issues with released terminado, and it won't be an issue to ensure there aren't with the next release, either.

**Comment by ellisonbg** [comment]
OK, thanks, I will look at those PRs as well.

But there is a bug that this commit fixed:

https://github.com/takluyver/terminado/commit/eb17fac6fb47bd339e9c10a2af97e49da783097f

since the last release - without that fix, it doesn't work on my latest
ubuntu systems...

On Thu, Dec 31, 2015 at 8:40 AM, Min RK <notifications@github.com> wrote:

> Terminado technically hasn't dropped support for tornado 3, which is one
> source of the issue. I opened takluyver/terminado#25
> <https://github.com/takluyver/terminado/pull/25> to fix the issue, and
> takluyver/terminado#26 <https://github.com/takluyver/terminado/pull/26>
> if we want to drop support for tornado < 4.
>
> We don't need to push a release of terminado with 4.1, but we can do one
> soon after. There are no issues with released terminado, and it won't be an
> issue to ensure there aren't with the next release, either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/912#issuecomment-168218769>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
If there's an important bug that's fixed we can make a release of terminado. But I don't see a need for coordinated release, because that's not a bug that only affects notebook master and not 4.0, right?

**Comment by ellisonbg** [comment]
Yep

**Comment by yuvipanda** [comment]
Another issue that'll probably benefit from a terminado bump (or not?) is #104 (which I'm still able to repro on Firefox on Linux with 4.1rc)

**Comment by ellisonbg** [comment]
Oh, yes - this is a *huge* improvement - just been using it in the last day.

On Thu, Dec 31, 2015 at 2:19 PM, Yuvi Panda <notifications@github.com>
wrote:

> Another issue that'll probably benefit from a terminado bump (or not?) is
> #104 <https://github.com/jupyter/notebook/issues/104> (which I'm still
> able to repro on Firefox on Linux with 4.1rc)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/912#issuecomment-168254973>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by takluyver** [comment]
@yuvipanda that probably won't be affected, unfortunately - that's an issue related to term.js, the JS terminal emulator frontend which the notebook bundles. Terminado is the backend infrastructure term.js talks to, and I don't think that needs any changes to support copy & paste.

**Comment by takluyver** [comment]
Released a new version of terminado which fixes this by depending on Tornado >= 4, and fixes @ellisonbg's issue with 'bad fd' errors.

**Comment by ellisonbg** [comment]
Thanks!
