### ISSUE TITLE
How to set the window title for matplotlib

### ISSUE THREAD

**Issue by itoed** [jupyter/notebook#919]
Using `%matplotlib notebook` for the interactive plot, I can set the window title with
```python
plt.gcf().canvas.set_window_title('This title does not last')
```
but once the cell finishes execution, the title is reset to *Figure 1*.  How should this title be set to last?

![jupyter-window-title](https://cloud.githubusercontent.com/assets/187891/12072354/e46bd120-b0a8-11e5-9493-c03c0f49376e.gif)

**Comment by itoed** [comment]
Okay, I can set the title with `figure`:

```python
plt.figure(num='This is the title')
```

**Comment by saravanabalagi** [comment]
This additionally prints `<Figure size 432x288 with 0 Axes>` which sounds like a debug message to me, does anyone know how to suppress that?

**Comment by zxweed** [comment]
> This additionally prints `<Figure size 432x288 with 0 Axes>` which sounds like a debug message to me, does anyone know how to suppress that?

You should end the line with a semicolon:
`plt.figure(num='This is the title');`
