### ISSUE TITLE
Pulling static assets from the Jupyter CDN

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/notebook#92]
Now that we've set up assets on cdn.jupyter.org (specifically for https://github.com/jupyter/nbconvert/pull/20), I'd like to be able to use this for the try.jupyter.org deployment as well as JupyterHub (instead of the Rube Goldberg nginx machinery I've set up before).

To run a notebook server but relying on a CDN, I use:

```
jupyter notebook --NotebookApp.tornado_settings="{'static_url_prefix':'https://cdn.jupyter.org/notebook/4.0.0-dev/'}"
```

This has worked great so far, which I've tested by removing the entire static folder. This has the side effect of a single error getting logged:

```
[E 20:35:58.142 NotebookApp] Could not open static file ''
```

otherwise it runs flawlessly (this doesn't affect the run).

Right now the CDN has static assets for the current master branch, to be built nightly as 4.0.0-dev, and 3.1.0. My hope is to have this hooked up for try.jupyter.org (tmpnb.org) and a JupyterHub deployment within the week.

**Comment by minrk** [comment]
I need to fix that error message. It hides what file is actually not found.

**Comment by Carreau** [comment]
Do you know where this error come from ? I can't find the location though grepping.

**Comment by jdfreder** [comment]
Looks like it may be thrown by tornado, is that right?

**Comment by jdfreder** [comment]
https://github.com/tornadoweb/tornado/blob/bbfd096f4f3b951da91081d06c275c74e6bc1bf3/tornado/web.py#L2596

**Comment by minrk** [comment]
The error message comes from tornado, but we are passing the empty string. We don't need to block 4.1 on this one.

**Comment by rgbkrk** [comment]
By the way, I added the other 4.0.x releases to cdn.jupyter.org last night after reading this message. Makes me wonder if we should track the RSS feed from PyPI to grab the `notebook` package on updates.

**Comment by minrk** [comment]
Or poll git for tags

**Comment by rgbkrk** [comment]
> Or poll git for tags

We're already cloning, might as well.

**Comment by JamiesHQ** [comment]
Hi y'all- can this issue be closed? If not, what are the next steps?

**Comment by rgbkrk** [comment]
Yeah I think we're even using this already. Closing.
