### ISSUE TITLE
Fix documentation issues induced by global replace

### ISSUE THREAD

**Issue by steveholden** [jupyter/notebook#926]
It appears from http://jupyter-notebook.readthedocs.org/en/latest/security.html that at least some documentation has had global replacements of `"IPython"` with `"Jupyter"`. This has left the string "an Jupyter" in a number of places - the occurrences I've noticed are at lines 19 and 138 of `docs/source/security.rst` but I expect there will be similar issues sprinkled about.

**Comment by willingc** [comment]
Thanks @steveholden for catching the ``an``s.

I've checked all the ``*.rst`` files in ``docs/source``  and your PR #927 corrects those that are outstanding. I will double check the notebook files as well.

Thanks for your help.

**Comment by willingc** [comment]
All other rst and ipynb files were checked and no "an Jupyter" combinations were found.
