### ISSUE TITLE
Update `log.warn` to `log.warning`

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#928]
Identical to ipython/ipython#9091

As said in the documentation : [`warn` is a deprecated alias](https://docs.python.org/3/library/logging.html?highlight=logging#logging.Logger.warning), we should try not to use it. 

`log.warn` seem to be used in the following files:

```
   1 notebook/services/api/handlers.py
   1 notebook/services/security/handlers.py
   1 notebook/services/sessions/handlers.py
   2 notebook/services/contents/handlers.py
   3 notebook/base/handlers.py
   3 notebook/services/contents/filemanager.py
   3 notebook/services/contents/manager.py
   3 notebook/services/kernels/handlers.py
   3 notebook/services/kernels/kernelmanager.py
   3 setupbase.py
   7 notebook/base/zmqhandlers.py
  10 notebook/notebookapp.py
```

As in other issue bonus point to add a warnings filter that turn usage of `log.warn` in the package into an error in CI.

**Comment by diego898** [comment]
Hello,

I'd like to try the bonus @Carreau mentioned in ipython/ipython#9091, though he said that it would likely be hard. Any other advice to get started?

**Comment by Carreau** [comment]
See https://github.com/ipython/ipython/pull/9110 I tried but it does not work, I don't know why. You can try to figure it out !

**Comment by takluyver** [comment]
Reading up on the [warnings module](https://docs.python.org/3/library/warnings.html) is a good place to start. We need to make quite a specific filter, so it doesn't fail because of other warnings.

I'm not quite sure how we'd do it for this repo - for ipython we have our own test runner (iptest), so it's easier to set up things like that before the tests start. For all the other repos, we use [nose](https://nose.readthedocs.org/en/latest/) - there's probably some way of setting up things like this before any code runs, but I'm not sure exactly what that is.

**Comment by diego898** [comment]
ok Ill take a look at ipython/ipython#9110 first, as it seems more direct. Thanks!

**Comment by Carreau** [comment]
> I'm not quite sure how we'd do it for this repo - for ipython we have our own test runner (iptest), so it's easier to set up things like that before the tests start. For all the other repos, we use nose - there's probably some way of setting up things like this before any code runs, but I'm not sure exactly what that is.

For nose, see this PR #940 , I wrote a nose extension to do that (I need to rebase the PR though)

**Comment by JamiesHQ** [comment]
@gnestor : this looks like it can be closed- the first comment says it is identical to https://github.com/ipython/ipython/issues/9091 which is closed. Please confirm. thx!

**Comment by gnestor** [comment]
Closing for now. @diego898 Feel free to reopen if you would like to submit a PR to add a warning filter in iptest warns if we use `log.warn`.
