### ISSUE TITLE
Kernel status indicator during kernel restart

### ISSUE THREAD

**Issue by praveen-srinivasan** [jupyter/notebook#934]
Hi,
The kernel status indicator in the notebook seems to be idle while a kernel is restarting (the time in between the "kernel_restarting" and "kernel_ready". Ideally, it seems like the indicator should be in the busy state in this period - does that seem reasonable?

Kernel: kernel_restarting (39039a47-279b-4ab5-9b7c-a624cd91983f)
main.min.js:22324 

Kernel: kernel_created (39039a47-279b-4ab5-9b7c-a624cd91983f)
main.min.js:22668 

Starting WebSockets: ws://localhost:8888/api/kernels/39039a47-279b-4ab5-9b7c-a624cd91983f
main.min.js:22324 

Kernel: kernel_connected (39039a47-279b-4ab5-9b7c-a624cd91983f)
main.min.js:22324 

Kernel: kernel_ready (39039a47-279b-4ab5-9b7c-a624cd91983f)

**Comment by praveen-srinivasan** [comment]
This is notebook version 4.1.0.b1 on a Mac.

**Comment by Carreau** [comment]
It's likely a good idea. Marking as 4.2. It's a UI/UX thing to ping @ellisonbg

**Comment by praveen-srinivasan** [comment]
Along with that - the notebook flashes indicator messages e.g. "Kernel starting" etc... - anyway to make them not disappear very quickly? I'd like to see "Kernel starting" during the entire time the kernel is starting.

**Comment by ellisonbg** [comment]
I think these changes sound like a good idea...

On Fri, Jan 8, 2016 at 12:46 PM, Praveen Srinivasan <
notifications@github.com> wrote:

> Along with that - the notebook flashes indicator messages e.g. "Kernel
> starting" etc... - anyway to make them not disappear very quickly? I'd like
> to see "Kernel starting" during the entire time the kernel is starting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/934#issuecomment-170119561>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jtpio** [comment]
Closing as the classic notebook UI has now been moved to https://github.com/jupyter/nbclassic.

Feel free to open a new issue there if it is still relevant, thanks!
