### ISSUE TITLE
Warn if message signing disabled

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#945]
Certain kernels apparently haven't implemented message signing (e.g. zabirauf/icsharp#17), and in at least one case, a kernel installation routine writes a notebook config file to disable message signing so that it will work.

This can happen without users ever being aware that they're reducing their security. We should display a reasonably loud warning on starting the server if signing is disabled (maybe even something in the UI, rather than just the terminal), to give users a chance to notice this. It would also be useful to indicate to kernel authors that disabling message signing is for development only, and not something they should do on users' machines.

**Comment by Carreau** [comment]
I think that disabling signing should be much harder in general, like only available through a flag on the notebook server. Not config.

**Comment by takluyver** [comment]
I don't think we currently have any way to have command line flags without config.

**Comment by Carreau** [comment]
Through tornado option likely possible. That it to say we have to make it a non-traitlets.

**Comment by minrk** [comment]
I agree with the warning, but not adding some artificial difficulty to implement it.

**Comment by minrk** [comment]
Warning in jupyter/jupyter_client#106
