### ISSUE TITLE
auto format?

### ISSUE THREAD

**Issue by lfz** [jupyter/notebook#946]
It would be nice if the editor integrate the auto format function~

**Comment by Carreau** [comment]
It's hard as the frontend support ~50 languages. So it's likely have to be done via an extension.

**Comment by janschulz** [comment]
See https://github.com/ipython-contrib/IPython-notebook-extensions/issues/365

**Comment by davidlattimore** [comment]
Has it been considered if Jupyter kernels could provide code formatting? I got a feature request to integrate rustfmt into the evcxr (Rust) Jupyter kernel. If it were just a matter of implementing an API in the kernel that accepted a string and returned that string auto-formatted, it'd be pretty easy. But I'm not sure I want to write custom client-side code to call the auto-formatter in the kernel. For starters, if every kernel did that, then there'd be many different and inconsistent UIs for how to trigger auto-formatting.
