### ISSUE TITLE
Jupyter 4.1.0rc1 %matplotlib notebook bug

### ISSUE THREAD

**Issue by ericdill** [jupyter/notebook#949]
Hi Jupyter devs,

In previous version of the notebook, executing a cell with `shift+enter` that contained matplotlib code to generate an interactive figure, say `fig, ax = plt.subplots()`, would cause the matplotlib figure to gain control over keyboard inputs and the notebook cell highlighting would remain on that same cell.  Pressing `shift+enter` again would return the keyboard control back to the notebook and move to the next notebook cell.

In `4.1.0rc1`, this behavior has changed and is almost certainly a bug.  [Here is an example notebook] (https://gist.github.com/ericdill/537effed420f22af82e0) to demonstrate this bug.  If you download this notebook and execute its cells with shift+enter, here is what seems to happen:

First `shift+enter`: executes the import cell.
Second `shift+enter`: creates the interactive matplotlib figure, but moves the cell outline to the third cell
Third `shift+enter`: Moves the cell outline to the fourth cell, but does not execute the third cell
Fourth `shift+enter`: Executes the fourth cell and prints out a new random number.

I have provided a list of my conda environment in the notebook linked above.  Let me know if I can provide any additional information! Thanks!

**Comment by Carreau** [comment]
indeed O_o. Thanks.

**Comment by minrk** [comment]
Closing this one in favor of duplicate #1124 with more info.
