### ISSUE TITLE
Terminal with apple keyboard

### ISSUE THREAD

**Issue by jpaos** [jupyter/notebook#962]
When I want to use the terminal window, since I am mac user with portuguese keyboard layout, I cannot enter curly brackets { and } because they are entered as ALT-8 or ALT-9, and Alt is interpreted in some different way.

Does anyone knows how to change this behaviour? How to set up properly the meta-keys, or how to recognize the correct keyboard layout?

**Comment by takluyver** [comment]
Keyboard handling across different browsers, locales and physical keyboards is a nightmare.

The terminal we use is a component called term.js. It looks like this issue, or something similar, has been reported as chjj/term.js#91 .

There's nothing we can really do except update term.js when there's a new release, so closing here.
