### ISSUE TITLE
Notebooks marked unsaved on opening.

### ISSUE THREAD

**Issue by rlabbe** [jupyter/notebook#964]
This is new behavior with the latest release 4.1.0 I open a notebook, and at the top of the title bar it states 

    Last Checkpoint: a few minutes ago (unsaved changes)

I press the save button, and confirm that the terminal prints out a save message. The header changes to:

    Last Checkpoint: a few seconds ago (autosaved)

I close the notebook window, then reopen the notebook. The top of the title bar states

    Last Checkpoint: a few seconds ago (unsaved changes)

In short, every time I open a notebook it is marked as unsaved.

I've been able to diagnose this. I have autosave turned off in my custom.js, where I have

    $([IPython.events]).on("notebook_loaded.Notebook", function () {
       IPython.notebook.set_autosave_interval(0);
    });

If I comment that out the notebook opens and immediately saves itself.

If this is the intended behavior I guess go ahead and just close this. But this is new behavior, it never happened before 4.1. I have autosave turned off because I run my notebooks in a dropbox directory, and in the past the notebooks and dropbox didn't always get along - you'd get errors on saves, and it is extremely annoying to deal with error messages every few minutes. 

I originally mentioned this on gitter. Carreau suggested I look for javascript errors. I see nothing  that stands out to me. I'll paste it in a reply if you are interested.

Environment: Windows 7 and 10, Notebook server 4.1.0, running on
Python 3.5.1 |Anaconda 2.4.1 (64-bit)| (default, Dec  7 2015, 15:00:12) [MSC v.1900 64 bit (AMD64)]

**Comment by Carreau** [comment]
Thanks for the report, it's not critical, so it might not make it in 4.2, we'll definitively have a look.

**Comment by DavidPowell** [comment]
I have also observed this bug, on 64 bit Anaconda running on both Linux and Windows.

**Comment by minrk** [comment]
Should be fixed by #992
