### ISSUE TITLE
Support HEAD for /files/ handler

### ISSUE THREAD

**Issue by obgeneralao** [jupyter/notebook#965]
Hi,
I used jsroot(github:linev/jsroot) to browse root files .

![selection_002](https://cloud.githubusercontent.com/assets/13013814/12390271/6399493c-be19-11e5-856b-0a6cfb4438b0.png)

Accessing root files from other servers has no issues
But, whenever i tried to browse the root file locally , i always get 405 error

![selection_001](https://cloud.githubusercontent.com/assets/13013814/12390293/9dc08544-be19-11e5-9c51-7254eb93a993.png)

I checked tornado's documentation since it could point to Httpserver. But I was kind of lost.
I would appreciate any help for a workaround on this issue.

My Software Version:
Python	2.7.11 64bit [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
IPython	4.0.2
pyzmq	14.7.0
jinja2	2.8
tornado	4.3
mistune	0.7.1
jsonschema	2.4.0
pygments	    2.0.2
terminado	0.5
jupyter	1.0.0
notebook	4.1.0

**Comment by takluyver** [comment]
405 is 'Method not allowed'. But I wonder if there's a mismatch between the notebook URL structure and the URLs jsroot tries to use, and it looks in the wrong place for it. Is that `hsimple.root` file inside `MyScripts/MyOwnROOTScripts`?

**Comment by obgeneralao** [comment]
i already tried putting hsimple.root to different directories. Like, the same location where index.htm is, also the directory where I launched the notebook . 

i tried the steps from this site http://stackoverflow.com/questions/21124869/how-to-view-html-file-in-remote-unix-server  and it worked.

The only problem is when I do it in iframe in jupyter notebook

**Comment by takluyver** [comment]
Ah, I see it. The `/files/` handler now uses our ContentsManager machinery, rather than a standard static file handler. It should be easy to add HEAD support.

**Comment by takluyver** [comment]
I think #966 should fix this, so long as the file is in the right place (which looks like it's the directory where you started the notebook server).

**Comment by obgeneralao** [comment]
Perfect!!!! It works now

Thanks a lot
