### ISSUE TITLE
/files/ should use StaticFileHandler when files are local

### ISSUE THREAD

**Issue by minrk** [jupyter/notebook#968]
Right now, the ContentsManager is used for requests on `/files/`. This is the most generic and will work for any ContentsManager, but is very inefficient when it's not needed. For the default case of FileContentsManager, we should go back to using AuthenticatedFileHandler, which is now unused (#865).

The simplest way to express this, I think, is a files_handler_class attribute on the ContentsManager. The base class should set the default to what we use now, and FileContentsManager should set it to AuthenticatedFileHandler.

**Comment by takluyver** [comment]
Closed by #2656
