### ISSUE TITLE
Tests fail on new builds of Jupyter Notebook

### ISSUE THREAD

**Issue by wielandbrendel** [jupyter/notebook#971]
The tests run during the build of Jupyter Notebook on Docker Hub fail, please see the [full build log](https://hub.docker.com/r/jupyter/notebook/builds/bys4ac8vttnqujuajmdygkk/). This issue arised today and is most likely due to a broken dependency on a 3rd package: the 4.0.0 and 4.1.0 release all show the same issue.

**Comment by willingc** [comment]
@wielandbrendel Thanks for including the build log with your issue report.

@takluyver @minrk @parente The logs show errors on setting the locale on Ubuntu. Do we want to try to update the Dockerfile here with one from jupyter/docker-stacks?

**Comment by wielandbrendel** [comment]
Thanks for taking care! One downside (for me) is that the jupyter/docker-stacks are based on Debian, whereas I (and probably many others) prefer Ubuntu. In other words, I'd really appreciate a working installation on Ubuntu :).

**Comment by minrk** [comment]
This is a change in the pygments BashLexer between 2.0 and 2.1, and seems like a pygments bug. In any case, we can safely ignore it and shouldn't be running the IPython tests in the Dockerfile anyway.

**Comment by minrk** [comment]
Should be fixed by #976
