### ISSUE TITLE
kernel_ready.Kernel triggered twice when creating a new notebook

### ISSUE THREAD

**Issue by minrk** [jupyter/notebook#973]
@neilzimmerman opened ipython/ipython#8069

Any time you a pushed directly into a new notebook, the 'kernel_ready.Kernel' is triggered twice from kernel.js. This usually happens when creating a new notebook or "making a copy" from within a running notebook.

**Comment by gnestor** [comment]
I can't reproduce this anymore. I tried adding the following to my custom.js and I only got 1 log:

```js
events.on('kernel_ready.Kernel', function(event){ 
    console.log('kernel_ready.Kernel', event);
});
```
