### ISSUE TITLE
Piped commands return a write error

### ISSUE THREAD

**Issue by esafak** [jupyter/notebook#975]
For example, the command `!find . -name foo | head -1` yields:

```shell
foo
find: `standard output': Broken pipe
find: write error
```

Tested on jupyter NB  4.0.6 & 4.1.0 w/python 3.4.3 on Ubuntu 14.04.3.

**Comment by takluyver** [comment]
This is working for me on master on Linux Mint.

**Comment by minrk** [comment]
@esafak what version of IPython? This appears to be working with IPython 4.2.0 and master.

**Comment by esafak** [comment]
It works in Jupyter 4.2.1 w/python 3.5 on OS X.
