### ISSUE TITLE
ipython notebook shift-tab completion function arguments/completion not working 

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#981]
@datnamer opened ipython/ipython#8999

Windows 7, python 3.5, Jupyter 4.0 and rackspace hosted Python 3 instance. 

Regular tab works for global scope of exceptions etc, but   I'm not getting function args with shift-tab

**Comment by minrk** [comment]
Closing for no response in a long time. Feel free to reopen with more details if this is still an issue.
