### ISSUE TITLE
"Make a copy" menu item loses unsaved changes

### ISSUE THREAD

**Issue by DavidPowell** [jupyter/notebook#986]
Sometimes I find myself making changes to a notebook, then realise that I should keep my original notebook for comparison reasons.

So I use the "Make a copy" option to save a copy of the notebook with my changes (and go back to undo them from my original file). However, this make a copy of the current *notebook state on disk, neglecting any unsaved changes*.

I appreciate that this may be subjective, but this behaviour seems quite counter-intuitive to me. My expectation of this option is that it should operate more like "Save As...", so that the current contents of the notebook gets saved to a new filename.

**Comment by Carreau** [comment]
Hello David. 

Thanks for the report.  [Current version is supposed to save](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/menubar.js#L114-L120) before making a copy.

Though the `save_notebook` function seem to ignore the `{async:false}` option which is handled nowhere.  We will try to get a fix for 4.2.

**Comment by minrk** [comment]
Apparently the passthrough of ajax options was disabled in c7529c53ebdc4e8045dd4d513e2b38a8e016a319. We need to put it back

**Comment by minrk** [comment]
Actually, no, I think we can use a promise to do it.

**Comment by minrk** [comment]
Should be fixed by #987

**Comment by DavidPowell** [comment]
I just tested the fix from @minrk  and it appears to have solved the issue.

Thanks for this, I do appreciate the time the Jupyter devs spend on this tedious bug chasing.
