### ISSUE TITLE
Keybindings in tab completion

### ISSUE THREAD

**Issue by justmytwospence** [jupyter/notebook#991]
Is there a way to bind other keys (eg `C-n` `C-p`) to perform the `up` and `down` actions while the code completion menu is active?

**Comment by Carreau** [comment]
Hum, likely hard as it is actually just an normal HTML element. We'll try to consider that for the current rewriting we are doing.

Ping @blink1073

**Comment by blink1073** [comment]
The current example in jupyter-js-filebrowser allows you to use `C-n` and `C-p` to move between items, so it is definitely possible to do this with JupyterLab.

https://github.com/jupyter/jupyter-js-filebrowser/blob/master/example/src/index.ts#L78

**Comment by minrk** [comment]
Closing here, as something note feasible in the current notebook, but doable in jupyterlab.
