### ISSUE TITLE
Notebook server failures when too many notebooks open

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/notebook#993]
When many (~20) notebooks are open in tabs of the browser, I start getting the following error when connecting to the dashboard:

```
Server error: directory does not exist: u'...'
```

Closing tabs and reloading the page solves the issue.

**Comment by minrk** [comment]
I've opened ~50 notebooks without any trouble, so I'm going to call this one probably fixed. Feel free to reopen if you can still see this.
