### ISSUE TITLE
Run cells before notebook is live

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/notebook#994]
When a notebook just got opened, and as the kernel is still starting, it is already possible to "execute" the first cells with `Shift+Enter`.

However, execution requests are lost instead of being queued and the later cells executed likely error due to the missing first cells. This problem is especially visible with windows where the kernel startup time is longer than on OS X or linux. 

We should probably either queue the messages or keep the current cell selected.

**Comment by minrk** [comment]
If I recall correctly, execution requests aren't lost because the kernel connection isn't established yet. Instead, they are never produced.

**Comment by SylvainCorlay** [comment]
OK, it remains an issue from a UX perspective. We should probably avoid giving the impression that cells are run.

**Comment by jasongrout** [comment]
Yes, it looks like this line is the one ignoring the execution: https://github.com/jupyter/notebook/blob/527538839beb69d5ed1cbf4a3a43e352ea3ca119/notebook/static/notebook/js/codecell.js#L308

**Comment by jasongrout** [comment]
Here are a couple of options:

1. Queue up the pending cells at the notebook level and run them when the kernel is set. This doesn't prevent the cells from being modified before they are run, though.

2. Make a fake "kernel" that just queues up execution requests, and set that to the cells when they are first created. This has the advantage that the cell logic identifying it's running, etc., still works as-is.

3. Throw an error when trying to run a cell and a kernel is not active.

I think a combination of (2) and (3) would work well.  The initial dummy kernel optimistically assumes there will eventually be a good connection, and just queues up execution requests.  However, if there is an error with the kernel, we throw an error to the user when trying to execute the cells.

**Comment by jasongrout** [comment]
@SylvainCorlay, @minrk, comments on the above?

**Comment by jasongrout** [comment]
One question: when we delay execution, should we execute the original contents of the cell, or the current contents of the cell?

**Comment by jasongrout** [comment]
Okay, I think I have a minimal solution at #1002, but it's one that makes the notebook rely a bit on the CodeCell behavior, so it smells a bit, but maybe not more than other notebook code.

**Comment by takluyver** [comment]
Should this be closed by what Jason implemented in #1002, or is there more to do?

**Comment by minrk** [comment]
Just lost track. This is fixed.
