### ISSUE TITLE
How to logging into a  defined file and rollover like TimedRotatingFileHandler?

### ISSUE THREAD

**Issue by Anne623** [jupyter/notebook#995]
Hi,All

   I want to logging Notebookapp logs into a defined file like notebookapp.log, and I want to rollover log file with time or size  like TimedRotatingFileHandler. how to do it?

**Comment by Carreau** [comment]
Logging does use normal [python logging module](https://docs.python.org/3/library/logging.html), any documentation there should work out of the box. See also [Logging Howto](https://docs.python.org/3/howto/logging.html)

**Comment by willingc** [comment]
Hi @Anne623 @Carreau,

Closing this issue as it's been inactive for several months. If there are still more questions, please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue.

Thanks! :sunflower:
