### ISSUE TITLE
Crash if a subfolder of the current folder has more than 50'000 files

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#999]
@Gansgar opened ipython/ipython#9165

iPython "crashes" or better gets stuck forever if at least one subdirectory of my current directory has more than 50'000 files. 

I have this file structure:

notMNIST_large
    A - 50'000 files
    B - 50'000 files
    ...
    J - 50'000 files

If I enter (or start in) the directory "notMNIST_large" iPython gets stuck and the web fronted shows a server failure. A new access to the web fronted gets stuck. All webbrowsers so far are trying to load it, but their wait till I need to kill ipython with a sigterm 3. The response to ^C is still there, but it never shuts down. (Probably yes after a long time that I'm not willing to wait)

**Comment by minrk** [comment]
This was fixed by jupyter/notebook#998
